### ISSUE TITLE
cluster etcd

### ISSUE THREAD

**Issue by billikill** [coreos/etcd#10011]
hi, i create cluster, but 1 noda start and 2 noda not starting

i see error
request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)
Aug 15 17:01:59 JR-Conf-APP-01.orglot.office etcd[10206]: request cluster ID mismatch (got ac35a989f096e63a want fd461ca99076ebab)

node1 
#[Member]
ETCD_DATA_DIR="/var/lib/etcd/jira_5.etcd"
ETCD_LISTEN_CLIENT_URLS="http://10.200.19.50:2379,http://127.0.0.1:2379"
ETCD_NAME="jira_5"
#[Clustering]
ETCD_LISTEN_PEER_URLS="http://10.200.19.50:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.200.19.50:2380"
ETCD_INITIAL_CLUSTER="jira_5=http://10.200.19.50:2380,jira_6=http://10.200.19.51:2380"
ETCD_ADVERTISE_CLIENT_URLS="http://10.200.19.50:2379"
ETCD_INITIAL_CLUSTER_TOKEN="jira"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_ELECTION_TIMEOUT="5000"
ETCD_HEARTBEAT_INTERVAL="100"
#
#[Logging]
#ETCD_DEBUG=true
#ETCD_LOG_PACKAGE_LEVELS=""
#ETCD_LOG_OUTPUT="/var/log/etcd/etcd.log"

node 2
#[Member]
ETCD_DATA_DIR="/var/lib/etcd/jira_6.etcd"
ETCD_LISTEN_CLIENT_URLS="http://10.200.19.51:2379,http://127.0.0.1:2379"
ETCD_NAME="jira_6"
#[Clustering]
ETCD_LISTEN_PEER_URLS="http://10.200.19.51:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.200.19.51:2380"
ETCD_INITIAL_CLUSTER="jira_5=http://10.200.19.50:2380,jira_6=http://10.200.19.51:2380"
ETCD_ADVERTISE_CLIENT_URLS="http://10.200.19.51:2379"
ETCD_INITIAL_CLUSTER_TOKEN="jira"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_ELECTION_TIMEOUT="5000"
ETCD_HEARTBEAT_INTERVAL="100"
#
#[Logging]
#ETCD_DEBUG=true
#ETCD_LOG_PACKAGE_LEVELS=""
#ETCD_LOG_OUTPUT="/var/log/etcd/etcd.log"

**Comment by billikill** [comment]
i rename ETCD_DATA_DIR and cluster start

**Comment by gyuho** [comment]
> 1 noda start and 2 noda not starting

Are you setting up a fresh cluster? Then, make sure the data directories are empty.

**Comment by hexfusion** [comment]
@billikill can we close this? @gyuho has verified that the data dir must be empty for a fresh cluster. This would also be accomplished by your action of renaming ETCD_DATA_DIR, which would result in new empty directories.

**Comment by billikill** [comment]
@hexfusion  yes. you can close
