### ISSUE TITLE
Client v3 rpc.swagger.json has Cyclic calling between etcdserverpbTxnRequest and etcdserverpbRequestOp

### ISSUE THREAD

**Issue by sanamsarath** [coreos/etcd#10013]
Hi,

I am trying to generate C++ supported API's for the client v3 to interact with etcd server using rpc.swagger.json (https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/apispec/swagger/rpc.swagger.json).

Following is the command used to generate the API's: 

java -jar /usr/share/java/openapi-generator-cli-3.1.2.jar generate -t /usr/cna/lib/openapi-templates/cpprest -g cpp-restsdk -i interface/swagger/rpc.swagger.yaml -o /src/cna/.build/dbg/interface/swagger/export/src/rpc.swagger

And every time it is failing at EtcdserverpbTxnRequest.h and throws "error: use of undeclared identifier 'EtcdserverpbRequestOp'".

 "etcdserverpbRequestOp": {
      "type": "object",
      "properties": {
        "request_delete_range": {
          "$ref": "#/definitions/etcdserverpbDeleteRangeRequest"
        },
        "request_put": {
          "$ref": "#/definitions/etcdserverpbPutRequest"
        },
        "request_range": {
          "$ref": "#/definitions/etcdserverpbRangeRequest"
        },
        "request_txn": {
          "$ref": "#/definitions/etcdserverpbTxnRequest"
        }
      }
    },

    "etcdserverpbTxnRequest": {
      "type": "object",
      "properties": {
        "compare": {
          "description": "compare is a list of predicates representing a conjunction of terms.\nIf the comparisons succeed, then the success requests will be processed in order,\nand the response will contain their respective responses in order.\nIf the comparisons fail, then the failure requests will be processed in order,\nand the response will contain their respective responses in order.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/etcdserverpbCompare"
          }
        },
        "failure": {
          "description": "failure is a list of requests which will be applied when compare evaluates to false.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/etcdserverpbRequestOp"
          }
        },
        "success": {
          "description": "success is a list of requests which will be applied when compare evaluates to true.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/etcdserverpbRequestOp"
          }
        }
      }
    },

When "request_txn" is removed from "etcdserverpbRequestOp" API's are built fine. 

Is there any specific reason for calling etcdserverpbTxnRequest and etcdserverpbRequestOp each other cyclically ??

Thanks.

**Comment by hexfusion** [comment]
@sanamsarath the swagger spec is machine generated from our dependency grpc-gateway and validates without error via https://editor.swagger.io/. I am not familiar with the openapi-generator but it seems that it might be the issue. Have you attempted to try other tooling such as swagger codegen for example?

**Comment by hexfusion** [comment]
It looks like https://editor.swagger.io/ will output cpprest client, I hope that helps.

**Comment by hexfusion** [comment]
[cpprest-client-generated.zip](https://github.com/coreos/etcd/files/2292083/cpprest-client-generated.zip)

**Comment by sanamsarath** [comment]
@hexfusion Thanks. closing the issue.
