### ISSUE TITLE
quorum=true and wait=true does not work as expected

### ISSUE THREAD

**Issue by donatello** [coreos/etcd#1004]
I am trying to use quorum=true with wait=true to wait on a key change. The API call returns immediately without waiting for any changes. I am using version v0.4.6

This seems to work fine with consistent=true, instead of quorum=true. 

From discussions in previous issues related to Jepson testing, it appears that quorum=true makes sure that a majority of the nodes acknowledge the read (i.e. acknowledge the leadership of the current leader and thus its response to the read request), and with consistent=true, simply talks to whoever the current node thinks is the leader (which could be out of date). Is my understanding correct?

**Comment by yichengq** [comment]
If you get the request through WAIT, it means that the change has been recorded in majority.

When you use get with quorum=true, it promises that you are getting the latest value in the cluster.
