### ISSUE TITLE
"expire" notification was lost when waiting on a directory recursively, and there are more than one child expires at the same time

### ISSUE THREAD

**Issue by ashun** [coreos/etcd#1074]
it's etcd 0.4.6, here is the steps:

1. tcpdump on  port 4001
<pre>
sudo tcpdump -i lo port 4001 -s0 -w tcpdump.cap
</pre>

2. execute the following script on another terminal
<pre>
curl -XPUT http://127.0.0.1:4001/v2/keys/dir/key1 -d value=value1 -d ttl=5;
curl -XPUT http://127.0.0.1:4001/v2/keys/dir/key2 -d value=value2 -d ttl=5;
curl "http://127.0.0.1:4001/v2/keys/dir?wait=true&recursive=true&stream=true";
</pre>

after 5 seconds, the watcher will receive only one 'expire' notification not two. the captured 'tcpdump.cap' is for details.

**Comment by xiang90** [comment]
watch stream is pretty racy right now. in v3, we support watch stream. there is an ongoing fix: https://github.com/coreos/etcd/pull/2879. we are not sure it still worth the effort though. so probably we will not fix this for v2.
