### ISSUE TITLE
define request parameter compatibility matrix

### ISSUE THREAD

**Issue by jonboulle** [coreos/etcd#1171]
We have a whole lotta parameters supported for HTTP requests: `wait`, `recursive`, `dir`, `stream`, `prevIndex`, etc etc. We should explicitly define what permutations are supported and consider rejecting requests with unsupported combinations, to be more predictable/consistent to users.

**Comment by xiang90** [comment]
This is irrelevant for v3 anymore. We use rpc instead of http requests for v3. So we do not need to use these para to infer the action.
