### ISSUE TITLE
simplify storerecorders

### ISSUE THREAD

**Issue by jonboulle** [coreos/etcd#1185]
We have _n_ different `storeRecorders` implementations for unit tests, where _n_ --> ∞. We should be able to consolidate these into either a single one or a much smaller number. Also, it might be useful splitting them out to a dedicated package so they can be shared in tests across packages.

**Comment by yichengq** [comment]
We have reduced the number of storeRecorder, and we will keep v2 store tests as what they are today, so it is fine to not simplify it more.

BTW, we have extracted recorder to a common package at https://github.com/coreos/etcd/blob/master/pkg/testutil/recorder.go
