### ISSUE TITLE
watch directory for add/ delete operations

### ISSUE THREAD

**Issue by gucki** [coreos/etcd#1229]
Watching a directory doesn't report anything when children are added/ deleted. When watching it recursively, all changes to it's children are reported. There's no way to detect the deletion of children.

Is it possible add the ability to listen to directory changes only (addition and deletion of children)?

**Comment by cchamplin** [comment]
For people looking for this in 2.x, I've put together a preliminary implementation.

Adding level=# to a wait request on a directory will restrict notifications to a specific depth
Adding filter=[action(s)] to a wait request on a directory will restrict notifications to specific action types

Commit:
https://github.com/cchamplin/etcd/commit/28824c0816196a8e17c9f408fb1e81ab86e1f63d
Patch File
https://github.com/cchamplin/etcd/commit/28824c0816196a8e17c9f408fb1e81ab86e1f63d.patch 

Example (level):
```sh
curl -L 'http://127.0.0.1:4001/v2/keys/foo/?wait=true&recursive=true&level=1'
curl -L http://127.0.0.1:4001/v2/keys/foo/bar/message -XPUT -d value="Hello"
# Watch does not return
curl -L http://127.0.0.1:4001/v2/keys/foo/message -XPUT -d value="Hello"
# Watch Returns
```

Example (filter):
```sh
curl -L 'http://127.0.0.1:4001/v2/keys/foo/?wait=true&recursive=true&filter=expire,create'
curl -L http://127.0.0.1:4001/v2/keys/foo/message -XPUT -d value="Hello"
# Watch does not return
curl -L http://127.0.0.1:4001/v2/keys/foo/message -XPUT -d value="Hello" -d prevExist=false
# Watch returns because of "create" filter
```


I've included tests, and done some local testing but if anyone wants to do some testing that would be great. 


**I doubt that this would get included in the upstream 2.x branch at this point, but if it's possible I'll go ahead and create a pull request after additional testing and finishing some TODOs**


TODO: Add support for this to the client and etcdctl
TODO: Update docs
TODO: Write tests
