### ISSUE TITLE
Feature Request: Ability to BATCH GET multiple nodes via a set of input keys

### ISSUE THREAD

**Issue by derekwaynecarr** [coreos/etcd#1282]
The Kubernetes project is using etcd currently to support persistence of information in our cluster.

If you review, https://github.com/GoogleCloudPlatform/kubernetes/pull/1183 , you can see we have use cases that require some ability to filter data based on a particular set of node field values.  

We discussed building our own indexer that would index the keys for resources that had a particular field value, but we would like to be able to actually request from etcd a batchGet(keys) request to avoid N HTTP operations over the wire to improve cluster performance at larger numbers of resources.

**Comment by xiang90** [comment]
@derekwaynecarr @smarterclayton @sachja Please take a look at the new api under /doc/rfc. It should solve this issue. Thanks!

**Comment by smarterclayton** [comment]
It does, thanks!

**Comment by zhangddjs** [comment]
Hi @xiang90  master, is this feature also be able to take effect on clientv3? seems currently the kv.go do not have a batchGet function to get result with specified keys.
