### ISSUE TITLE
etcd fails when discovery service goes away during startup

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#1456]
1. Create a discovery token. I'm using a custom discovery endpoint at local ports 4000/7000

```
curl -X PUT http://localhost:4000/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/_config/size -d value=3
```

2. Start the first etcd node. It will add itself to the discovery config and wait for the remaining members of the cluster to show up:

```
% ~/src/etcd/bin/etcd -name node1 -discovery=http://127.0.0.1:4000/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83 --listen-client-urls http://127.0.0.1:4001 --advertise-client-urls http://127.0.0.1:4001 --listen-peer-urls http://127.0.0.1:7001 --initial-advertise-peer-urls http://127.0.0.1:7001
2014/10/28 08:37:22 etcd: no data-dir provided, using default data-dir ./node1.etcd
```

3. Take down the discovery service. For me, all I have to do is kill the process. At this point, the etcd node we're trying to bring up exits with the following log line:

```
2014/10/28 08:37:25 etcdserver: unexpected EOF
```

I have no idea what to do with that error. I would expect a useful warning to be printed to the etcd logs, and for the "node1" etcd service to actually stay up, waiting for the discovery service to come back.

**Comment by xiang90** [comment]
@yichengq Do you think this has been fixed?

**Comment by yichengq** [comment]
Let me give it a try.

**Comment by yichengq** [comment]
etcd retries to discover forever in this case now. And its log is friendly:
```
08:29:10 etcd3 | 2015-08-25 08:29:10.639348 E | discovery: error #0: unexpected EOF
08:29:10 etcd3 | 2015-08-25 08:29:10.639385 I | discovery: waiting for other nodes: error connecting to http://127.0.0.1:4001, retrying in 2s
```

The issue has been fixed.
