### ISSUE TITLE
etcd logs missing timezone

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#1461]
My local server is running in PDT. It generates logs like so:

```
2014/10/28 09:14:23 etcd: listening for peers on http://localhost:2380
```

If I were to share these logs with someone in a different timezone, they would not know how to orient themselves with that timestamp.

1. Log the timezone
2. Log in UTC (optional, but highly encouraged)

**Comment by xiang90** [comment]
This will be addressed by the log pkg etcd uses. The related issue is here https://github.com/coreos/pkg/issues/30.
