### ISSUE TITLE
Add timeout to etcdctl

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#1515]
Originally reported in https://github.com/coreos/etcdctl/issues/111. etcdctl needs to support a user-configurable timeout for the API requests it makes.

**Comment by xiang90** [comment]
@yichengq This is blocked on client timeout support.

**Comment by yichengq** [comment]
@xiang90 Could you specify what kind of client timeout support is needed for this case? I think timeout for each HTTP request is a reasonable one, but i am unsure about whether it is sufficient for this case.
