### ISSUE TITLE
etcdctl: new command "getwait": gets a key or waits for it to appear.

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#1516]
Originally reported in https://github.com/coreos/etcdctl/issues/113:

**Problem**

* I have two services: a rabbitmq service and a worker service which pulls jobs from the rabbitmq service.  The worker service needs to know the ip address of the rabbitmq service before it can start.

* I am using the [Simple Sidekick](https://coreos.com/docs/launching-containers/launching/launching-containers-fleet/) pattern with a separate unit file that announces the hostname of my rabbitmq service to `/rabbit`.

* Since the worker service requires the rabbitmq hostname before it can call `docker run` in `ExecStart`, it needs to somehow block until the `/rabbit` key appears in etcd.  

While I can probably write a bash loop to do this, it's complicated and error prone.  It would be great if  etcdctl could make this easy.

I can't use `watch`, because of the race between the two units.  Eg, if the unit that announces the `/rabbit` key runs before the worker unit runs, then the worker unit's call to `etcdctl watch` would block forever.

**Proposed solution** 

Add a new command called `getwait`. 

Here's how it would be used to get the `/rabbit` key once it appears in etcd:

```
ExecStart=bash -c 'RBT=$(etcdctl getwait /rabbit); docker run ubuntu worker --rabbitmq $RBT'
```

**Getwait semantics**

* If the key exists, return it immediately.
* If the key does not exist, wait until it appears and then return it.  (eg, watch it)

**Comment by analytically** [comment]
+1

**Comment by analytically** [comment]
See https://github.com/coreos/etcd/pull/2154

**Comment by xiang90** [comment]
@analytically We are not going to support every use case in etcdctl. etcdctl should just provide the most simple features. You can implement the feature you want pretty easily with etcd client.
