### ISSUE TITLE
Unreliable exec-watch behavior

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#1518]
Originally reported in https://github.com/coreos/etcdctl/issues/79

I'm running CoreOS 317.0.0 (alpha) and am not consistently getting alerts when exec-watch is watching a key. 

Here's my test setup:
On system 1:
`etcdctl exec-watch --recursive /tests -- sh -c "env | grep ETCDTEST >> test.out"`

On system 2:
`for i in {1..100}; do etcdctl set /tests/ETCDTEST-${i} $(date +%s);  sleep 1; done` 

After the for loop on system 2 finishes, switch back to system 1 and run:
`grep -c ETCDTEST test.out`

My result was 88 results out of the 100 changes, even though doing an etcdctl ls /tests shows all 100 entries in /tests. After removing duplicates I get just 58:
`cat test.out  | sort --unique | grep -c ETCD`

 I've run this a few times to confirm it's not just a fluke. The numbers differ slightly but not significantly. Please let me know if there's more information / detail I can include to help investigate. Having an approximately 60% chance of triggering a needed reconfiguration would make using etcd significantly more difficult for me.

**Comment by xiang90** [comment]
@kelseyhightower @veverjak I cannot reproduce this on current master. Feel free to reopen this if you can reproduce the problem.

**Comment by veverjak** [comment]
cool, works for me with:
```
NAME=CoreOS
ID=coreos
VERSION=494.4.0
VERSION_ID=494.4.0
BUILD_ID=
PRETTY_NAME="CoreOS 494.4.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by spyrospph** [comment]
Using the latest stable coreos 607.0.0 this problem persists EXACTLY as veverjak has reported.
