### ISSUE TITLE
Watching directory doesn't return list on change

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#1520]
Originally reported in https://github.com/coreos/etcdctl/issues/62

When watching a directory, the list of items isn't returned when a new one is inserted. Instead, the new value of a key is returned. But you can't match that up to a key at all without re-listing the directory and fetching. If it returned the new key in the directory, you're at least only a `etcdctl get` away from the new value.

Window 1:
```
etcdctl watch /foo-service --recursive
```

Window 2: 
```
etcdctl set /foo-service/container2 localhost:2222
```

Window 1:
```
etcdctl watch /foo-service --recursive
localhost:2222
```

**Comment by xiang90** [comment]
I am closing this since etcdctl already starts to print out the key and action when `--recursive` is set.

Example
```
[set] /foo/bar
foo
```
