### ISSUE TITLE
etcdhttp: document server timeout and make configurable

### ISSUE THREAD

**Issue by jonboulle** [coreos/etcd#1551]
from https://github.com/coreos/etcd/pull/1550#issuecomment-61302404
>  we should document this and make it a cluster tunable like heartbeat interval and election timeout.

It's unclear why the timeout was originally set to 500 ms ([here](https://github.com/coreos/etcd/commit/b2e0836bb3b63fc114e2347d158923bae4d7c091#diff-990c5e2eb11478ffb6ac247ce48a3b04R27))

Previous discussion: #1215

**Comment by yichengq** [comment]
it is documented in #2041 and will be made configurable in #2038
