### ISSUE TITLE
http server timeout causes SSL read error

### ISSUE THREAD

**Issue by gfxmonk** [coreos/etcd#1607]
I'm using https (with certs for both server & client) and node-etcd (with etcd v0.4.6).

After 5 minutes of watching a key which doesn't change within that time, I get an SSL error:

    Error: 140720501249856:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:s3_pkt.c:492:

I checked with curl, and it's not particular to node-etcd:

    $ curl --key etcd-client.key --cert etcd-client.crt --cacert etcd-ca.crt 'https://localhost:4001/v2/keys/app/?wait=true'
    curl: (56) SSL read: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac, errno 0
    
    real	5m0.142s
    user	0m0.052s
    sys	0m0.025s

Since it's 5 minutes, I'm assuming it's the http server timeout. When not using https, this manifests as an empty response (see https://github.com/stianeikeland/node-etcd/issues/32). But evidently an empty response isn't gracefully handled when using https.

Am I doing something wrong by sending a long-lived wait request? Or should the etcd http server be finishing these requests less abruptly? Ideally it'd be good to receive a valid (error) response body indicating that the request timed out.

**Comment by xiang90** [comment]
@gfxmonk We have fixed this since 2.0. 2.0 will not timeout a client after 5 minutes. Sorry for super long delay.
