### ISSUE TITLE
Enhancement: Allow watch from "first available index" vs. new updates or updates from a valid start index

### ISSUE THREAD

**Issue by raff** [coreos/etcd#1666]
Currently watch requests only allow watchIndex=0 (new updates) or watchIndex >= start index (start from watchIndex). I would like to be able to get all available updates without having to specify a valid watchIndex.

Something like watchIndex = -1 means "start from first available" or an extra flag to allow watchIndex < startIndex (again, it would start from first available).

With the current implementation I need to parse the error message ("the requested history has been cleared [%v/%v]") and resubmit the request with the current startIndex, but if more updates are published while doing this I may never get to fetch any valid value.

I am happy to submit a pull request if we can agree on the interface (watchIndex < 0 or new flag)

**Comment by gyuho** [comment]
I am working to improve watch features. This PR https://github.com/coreos/etcd/pull/4043 might help support this.

**Comment by heyitsanthony** [comment]
#4495 can do this in v3.
* There's no longer a need to parse an error message; the earliest available revision is given as a `WatchResponse` in case the revision is too old. To get the earliest revision, Watch on rev=1, and check for a `CompactRevision` on the first message.
* The missed updates problem shouldn't be an issue now that there's better handling of revision history.
