### ISSUE TITLE
watch() operation returns hidden node

### ISSUE THREAD

**Issue by brentryan** [coreos/etcd#1677]
If you add a hidden directory node like this:

curl -v 'http://localhost:4001/v2/keys/env/app/_status/config/myhost' -X PUT -d value="abc"

And then do a watch like this;

curl -v 'http://localhost:4001/v2/keys/env/app?wait=true&waitIndex=1879&recursive=true'

The hidden node _status is returned in the watch results if the index that was updated was 1879.  I'd expect that _status is only returned if I request that node directly, regardless of waitIndex specified.

**Comment by brentryan** [comment]
Is this issue fixed in the recent 2.0 release that just came out?

**Comment by brentryan** [comment]
@xiang90 Why is this marked as wontfix ?  This seems like a bug to me and still exists in 2.0.

**Comment by xiang90** [comment]
@brentryan Since we do not suggest people to use hidden key anymore. To solve the security issue, we have introduced the auth api. etcd will not support hidden key in v3.
