### ISSUE TITLE
/v2/members wont list member type and not in standard response format

### ISSUE THREAD

**Issue by pnegahdar** [coreos/etcd#1722]
/v2/members has the following output: 

    {  
      "members":[  
         {  
            "id":"ce2a822cea30bfca",
            "name":"default",
            "peerURLs":[  
               "http://localhost:2380",
               "http://localhost:7001"
            ],
            "clientURLs":[  
               "http://localhost:2379",
               "http://localhost:4001"
            ]
         }
      ]
    }

Which no longer has the 'leader' follower member types. Also this isn't a standard etcd response (with nodes/nodes). Whats the best way to get current members and leadership from the client?

**Comment by xiang90** [comment]
> Whats the best way to get current members and leadership from the client?

You can use the member API provided by etcd/client. The member api is outside kv space. So it does not follow the same format.
