### ISSUE TITLE
Mirroring

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#1749]
replicate a collection of key value pairs from one etcd cluster to another etcd cluster.

**Comment by F21** [comment]
Will this be on a master-master basis or will it have 1 "master" datacenter and the rest as "slaves"?

**Comment by yichengq** [comment]
@F21 Basically it will make the same update of the local cluster to the remote cluster every time interval.

**Comment by F21** [comment]
So will I be able to update the key from any cluster and it will reflect? For example, I update the key from dc1 and then later update it from dc2. After doing so, will all data centers see the same value?

**Comment by xiang90** [comment]
One mirror only mirrors the key at one side. dc1->dc2 only propagates the changes in one direction.

**Comment by F21** [comment]
Is it possible to set up 2 mirrors in opposite directions, or will that result in strange/undefined behavior?

**Comment by xiang90** [comment]
@F21 You can point them to different prefix without letting them affect each other. After all that being said, we have not started to implement anything.

**Comment by raoofm** [comment]
@xiang90 so I shouldn't be expecting this for v2 :disappointed:

**Comment by philips** [comment]
This can be done outside of etcd in userspace, right?

**Comment by xiang90** [comment]
@philips Right.

**Comment by davidquarles** [comment]
_Is_ there anything like this in userspace right now?  I can't imagine this is a ton of code to write, especially if it is not written as part of the etcd core (though I'm open to hacking on etcd directly if this is an issue you want some help with this), and I'm happy to write something if not.  At the risk of sounding pushy (I'm honestly just curious), when _might_ we expect this to surface?

**Comment by philips** [comment]
@davidquarles No, there is nothing in userspace right now. I thought I remembered someone worked on it but I can't find that project. Part of the question if you have mirroring do you want to be able have the same indexes or not?

**Comment by raoofm** [comment]
I think if we are naming it mirroring, then the indexes should be the same, else it should be named as a data-sync or data-backup or data-replication utility.
For my usecase indexes wouldn't matter.

**Comment by xiang90** [comment]
@davidquarles @raoofm 

We already started this work for v3. The index (revision in v3) would not be preserved. We only mirror the key-value space.

We also work on a snapshot tool that preserves the revisions when recovers from a backup.

Snapshot and mirror share the same logic though.
