### ISSUE TITLE
batching fsync

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#1757]
we do not batch fsync today. It might cause issues on some cloud env which has a very limited number of iops.

**Comment by xiang90** [comment]
a fsync must be called before:
1. leader sends out a raft message with a larger commit index.
2. follower sends out a msgAppResp after appending new entries.

If we want to batch fsync, we need to batch the messages basically.

/cc @yichengq

**Comment by extemporalgenome** [comment]
Somewhat related (#2486), writes and fsync calls occur continuously on an idle single-node cluster with no data and no api calls being made to it. strace indicates that no network syscalls are called other than bind and accept, yet pairs of write + fsync syscalls occur about 4+ times per second to the WAL.

I suspect write frequency is driven EtcdServer.Ticker.

**Comment by xiang90** [comment]
@extemporalgenome the idle cluster will do sync too. and it is 4 times per second(sync/500ms, which involves two writes and one fsync).

**Comment by extemporalgenome** [comment]
@xiang90 --cluster-sync-interval doesn't seem to have an effect on the write rate.

**Comment by xiang90** [comment]
@extemporalgenome It is an internal thing to sync the TTL. You cannot tune it. But I guess 4 iops is fine... If you want to run etcd smoothly, you should at least prepare for 100s iops even with fsync batching.

**Comment by xiang90** [comment]
Now we already start batching message and disk io seems not to be the bottleneck.
