### ISSUE TITLE
remove the last but one member in the cluster correctly

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#1759]
the TestDecreaseClusterSizeOfX tests cannot always remove the last but one member correctly now.

1. two members are alive
2. send the request to the follower to remove the leader
3. follower forward MsgProp to the leader
4. the leader sends out the MsgApp with confChange entry to follower
5. follower sends MsgAppResp back
6. the leader sends out the MsgApp with no entry and newer commit index that indicates the removal entry is committed
7. the message is filtered out by current streaming client
8. the leader stops itself
9. the follower still thinks the leader is alive
10. the remove http request times out

**Comment by xiang90** [comment]
Fixed via #2032 and #1992

**Comment by ongardie** [comment]
I don't see enough info here to understand the problem or the solution. What about the current Raft implementation does not allow this, and what'd you end up doing to solve it?

Have you seen the membership changes chapter in my thesis? AFAIK, the approach there works for two-server clusters.
