### ISSUE TITLE
raft

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#1808]
TODOs:
- [x] snapshot contains io.readcloser and snapshotMatedata?
- [x] reduce allocation per ready
- [x] able to batch proposal?
- [ ] state machine systematic testing
- [ ] move raft to a separate reop?
- [x] a simple kv app running on top of raft state machine for testing/benchmark?
- [x] integration test with etcd with fault injection
- [ ] integration test with cockroachdb with fault injection
- [ ] remove assertion and runtime panic

**Comment by buaazp** [comment]
Hi @xiang90

I plan to use etcd/raft in my applications. So I want to know when will you move raft to a separate reop?

If a separate repo is not easy, could you provide a sample to show how to use etcd/raft like [raftd](https://github.com/goraft/raftd)?

**Comment by xiang90** [comment]
@buaazp The doc is here: https://github.com/coreos/etcd/blob/master/raft/doc.go.

We plan to do it, but do not have a timeline yet.

**Comment by xiang90** [comment]
@bdarnell 
We already started etcd level failure injection test at https://github.com/coreos/etcd/tree/master/tools/functional-tester

**Comment by blueszhangsh** [comment]
I'm learning the raft algorithm implemented by etcd. There's some problems i don't catch. How do etcd's raft implementation deal with situation where peer receive a conflicted MsgApp messages.

**Comment by xiang90** [comment]
@blueszhangsh Can you be more specific? I do not really follow you.

**Comment by AdoHe** [comment]
@blueszhangsh what you mean conflicted MsgApp message? actually, during the normal process, the follower will not receive conflicted MsgApp messages. Maybe after a new election, when the non-leader nodes sync with the leader node, there is some log difference, but I dont think this is conflict.

**Comment by xiang90** [comment]
@gyuho @bdarnell I am pretty confident about our raft pkg now. I think we can start to remove the runtime panics. What do you think?

**Comment by gyuho** [comment]
Sorry, I am late for this discussion. What do we mean by `remove assertion and runtime panic`?
I see raft package does panic with `logger.Panic`. Are we suggesting that runtime panic does not
happen anymore in raft package?

**Comment by xiang90** [comment]
@gyuho Yes. We add a few panic inside raft pkg to catch logic errors. So it would be easier for us to debugging when there is something goes wrong at runtime. But I feel raft is pretty stable right now.

**Comment by gyuho** [comment]
Got it. Then would we switch to `Warning` or `Debug`?
Sounds good to me.

**Comment by gyuho** [comment]
Oh you mean remove from `TODO`? SGTM as well. Thanks,

**Comment by bdarnell** [comment]
Raft itself is stable, but we still find some of the assertions useful for finding bugs in our use of raft (e.g. when our `raft.Storage` implementation returns inconsistent results for first/last/applied/committed index). I think most of the assertions should stay.

**Comment by xiang90** [comment]
@heyitsanthony got a simple kv on top of raft at https://github.com/coreos/etcd/tree/master/contrib/raftexample.

We will update raft/doc.go to refer that.

**Comment by buaazp** [comment]
Good job! @heyitsanthony @xiang90

**Comment by xiang90** [comment]
I am closing this out since raft is pretty stable right now. We might move raft into its own repo. But that is a longer term goal.
