### ISSUE TITLE
leak readloop goroutine when integration testing

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#1853]
https://travis-ci.org/coreos/etcd/builds/42929844

It really needs some time to debug and fix it. We will skip the check as the first step.

**Comment by xiang90** [comment]
@yichengq Have we reported this to golang upstream yet?

**Comment by yichengq** [comment]
I reported it here: https://groups.google.com/forum/#!topic/golang-nuts/YKASjGmjPXw
I am trying to replay it with simple go program now. Will open an issue in golang repo when i make it.

**Comment by yichengq** [comment]
It is reported here:
https://github.com/golang/go/issues/10457
I will keep track of the issue.

**Comment by xiang90** [comment]
closing this since it is being tracked in golang repo.
