### ISSUE TITLE
feature request: allow creating nodes and directories with the same name

### ISSUE THREAD

**Issue by glerchundi** [coreos/etcd#1855]
As i mentioned some weeks ago  (#1301), I would like to have the possibility to create nodes and directories with the same at the same path. This is motivated by this project: https://github.com/glerchundi/parkeeper.

**Comment by coquin** [comment]
I tried to reproduce this issue but I couldn't:

1. Create a directory `dir`:

```
curl http://127.0.0.1:2379/v2/keys/dir -XPUT -d dir=true

=> {
    "action": "set",
    "node": {
        "createdIndex": 1,
        "dir": true,
        "key": "/dir",
        "modifiedIndex": 1
    }
}
```

2. Add a node `dir` to this directory:

```
curl http://127.0.0.1:2379/v2/keys/dir/dir -XPUT -d value=bar

=> {
    "action": "set",
    "node": {
        "createdIndex": 2,
        "key": "/dir/dir",
        "modifiedIndex": 2,
        "value": "bar"
    }
}
```

It worked. And if I list `dir` contents it returns this `dir` node without any errors.

@glerchundi, could you, please, confirm that it works for you too or clarify your case (step to reproduce and/or a bit more info about this feature request)?

**Comment by glerchundi** [comment]
@coquin, i want to be able to create a node alongside the folder (with the same name), not inside it, this shouldn't work:

```
curl http://127.0.0.1:2379/v2/keys/dir -XPUT -d dir=true
curl http://127.0.0.1:2379/v2/keys/dir -XPUT -d value=bar
```

**Comment by yichengq** [comment]
@xiang90 Do we want to support this in v2? A unix file system doesn't support to set value to dir, but zookeeper seems to support that.

**Comment by xiang90** [comment]
@glerchundi Please take a look at the v3 api under /doc/rfc. Thanks!
