### ISSUE TITLE
An etcd v0.5 cluster is substantially less performant than an etcd v0.4.6 cluster

### ISSUE THREAD

**Issue by onsi** [coreos/etcd#1896]
I'm running the `benchmark` package in etcd v0.4.6 (which is no longer present in v0.5).

I'm getting these results:

#### 1 v0.4.6 node
```
bench > go run bench.go
2014/12/09 11:36:19 Benchmarking http://127.0.0.1:4001
2014/12/09 11:36:19 50000 writes with 500 concurrent writers and 500 watches
2014/12/09 11:36:22 Took 3.416377967s
```

#### 1 v0.5 node
```
bench > go run bench.go
2014/12/09 11:36:52 Benchmarking http://127.0.0.1:4001
2014/12/09 11:36:52 50000 writes with 500 concurrent writers and 500 watches
2014/12/09 11:36:55 Took 3.143856048s
```

#### 3 v0.4.6 nodes
```
bench > go run bench.go
2014/12/09 11:37:10 Benchmarking http://127.0.0.1:4001
2014/12/09 11:37:10 50000 writes with 500 concurrent writers and 500 watches
2014/12/09 11:37:16 Took 5.625537074s
```

#### 3 v0.5 nodes
```
bench > go run bench.go
2014/12/09 11:37:30 Benchmarking http://127.0.0.1:4001
2014/12/09 11:37:30 50000 writes with 500 concurrent writers and 500 watches
<after much time>
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
...
```

This never completes.  Running in -verbose yields a much lower write-rate.

In addition to this, I have my own benchmark suite that starts 500 concurrent writers, writes to etcd repeatedly and then measures the write rate:

1 v0.4.6 node: ~10480 writes/second
3 v0.4.6 nodes: ~8600 writes/second
1 v0.5 node: ~11700 writes/second
3 v0.5 nodes: ~164 writes/second

these are mostly consistent with the numbers coming out of the benchmark

**Comment by nkhare** [comment]
I configured 3 node etcd cluster and set ulimit value to 100000 (ulimit -n 100000) on all nodes and ran boom benchmark for 50 K request with concurrency set to 500 
$ ./gocode/bin/boom -m PUT -d value=bar -n 50000 -c 500 http://etcdhost1:4001/v2/keys/bench

and I always get " dial tcp 172.20.10.77:4001: cannot assign requested address
"  errors.  

With 20400 requests it works fine.

**Comment by xiang90** [comment]
@nkhare What is the OS that etcd was running on?

**Comment by xiang90** [comment]
@nkhare We have tested etcd with millions of requests on ec2 linux from around a thousand of concurrent clients without a problem.

**Comment by nkhare** [comment]
@xiang90 I am trying it on RHEL7 with etcd-v2.0.0-rc.1.

**Comment by philips** [comment]
@nkhare Did you use the binary release with RHEL7 or did you compile it yourself? If you compiled it yourself which version of Go did you use?

**Comment by nkhare** [comment]
@philips I downloaded from

**Comment by nkhare** [comment]
@philips I downloaded it from 
https://github.com/coreos/etcd/releases/download/v2.0.0-rc.1/etcd-v2.0.0-rc.1-linux-amd64.tar.gz

**Comment by philips** [comment]
@nkhare Can you reproduce on CentOS7? I don't have easy access to a RHEL7 host.

**Comment by nkhare** [comment]
@philips Sure. I'll try and get back with steps. Do you want to track that in this issue or should I open new one.

**Comment by yichengq** [comment]
@nkhare Please open a new one.
Could you check the usage of ports in etcd and boom that is running using `lsof` too? I wanna check whether it really uses 100000 that many file descriptors. Because the error indicates there is no available file descriptors to use.

**Comment by nkhare** [comment]
@philips  @yichengq opened new issues https://github.com/coreos/etcd/issues/2028

**Comment by xiang90** [comment]
This is mostly a client issue. We have a pending fix at https://github.com/coreos/go-etcd/pull/176.
We can do better at the server-side to mitigate too. But it will be a long-term goal.
