### ISSUE TITLE
discovered cluster verifcation

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#1937]
verify the discovered cluster is valid. no duplicated peer urls, etc..

**Comment by xiang90** [comment]
This is a reliability issue. Moving to 2.2.

**Comment by philips** [comment]
@xiang90 I don't understand what this issue is, can you provide more explanation?

**Comment by xiang90** [comment]
@philips We need to verify the discovered cluster too. For example, if the discovered cluster is `1=10.10.10.1:1, 2=10.10.10.1:1` it should be considered invalid. Since the peer url is conflicting.

**Comment by philips** [comment]
@xiang90 Ah, I see, I will update the description.

**Comment by xiang90** [comment]
fixed by https://github.com/coreos/etcd/pull/2304
