### ISSUE TITLE
shuffle docs for 2.0

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#1957]
move some still valid docs from docs/ to docs/0.5

**Comment by robszumski** [comment]
@xiang90 You'll need to review and update `errorcode.md` and `design/cluster-finding.md`

**Comment by robszumski** [comment]
@xiang90 and `security.md`

**Comment by yichengq** [comment]
1. new docs have been moved under Documentation/, and 0.5/ dir is removed
2. outdated docs are removed
3. old docs are updated, or absorbed by new docs
