### ISSUE TITLE
Documentation for data size limit

### ISSUE THREAD

**Issue by sushantk** [coreos/etcd#1978]
Could you please provide details on data size limit on each key's value and number of children? Also, is there a way to limit the number of child keys fetched from a directory?

**Comment by thockin** [comment]
I'm getting a 413 from etcd with no body, but I can not find any docs for what the actual limit is.  Is it written down somewhere?

**Comment by gyuho** [comment]
Another thread asking about this: 

> -I didnt find any documentation about what kinds of keys and values does etcd store ?
-if i am watching a etcd  directory, how many nodes at max can be present inside it, for it to be able to watch changes to contents of that directory
-what is max numbers of keys supported
-what is max size of value supported ?

https://groups.google.com/d/msg/etcd-dev/BbgMBBCEoaE/RGTmv53PAwAJ

**Comment by imcom** [comment]
Though this is closed, it seems to me that the maximum number of children keys under a path/dir is not given?
