### ISSUE TITLE
streaming improvement

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#1988]
- [x] refactor
- [x] only send actual data while streaming
- [x] streaming proposal redirections

**Comment by xiang90** [comment]
@yichengq What is the current status of this?

**Comment by yichengq** [comment]
It has been done. Current etcd cluster can run smoothly with 2000 write requests per second for a long time, and it fixes the proposal issue: https://github.com/coreos/etcd/issues/2238#issuecomment-77177315
