### ISSUE TITLE
Add support for sd_notify

### ISSUE THREAD

**Issue by eyakubovich** [coreos/etcd#1998]
After etcd has been launched, it will reject with 503 all requests until it has joined the cluster. To make it easier for services to depend on etcd, add support for systemd's sd_notify and signal ready once the instance has joined the cluster.

**Comment by dash1291** [comment]
Not sure if it already exists, but I wonder if an HTTP endpoint which simply returns the ready state of the node fits this scenario.

**Comment by crawford** [comment]
https://github.com/coreos/etcd/issues/2724 is a dup of this, but they've added it to the v2.2.0 milestone (vs the v3.0.0-maybe milestone) here. I'll close this one ;)
