### ISSUE TITLE
etcdctl: can't accept key or value with preceding '-'

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2020]
Example error:

```
etcdctl set /kev/val '-param'


Incorrect Usage.

NAME:
   set - set the value of a key

USAGE:
   command set [command options] [arguments...]

OPTIONS:
   --ttl '0'            key time-to-live
   --swap-with-value        previous value
   --swap-with-index '0'    previous index
```

/cc @yaronr https://github.com/coreos/etcd/issues/1517#issuecomment-65254978

**Comment by djhworld** [comment]
This is a problem with the way github.com/codegangsta/cli does its flag processing code, error is being caught here https://github.com/codegangsta/cli/blob/v1.2.0/command.go#L77

**Comment by xiang90** [comment]
@gyuho Can you try to see if this is still an issue with etcdctl (we updated the dependency a few months ago).

Also can you try to verify that etcdctlv3 does not have this issue?

**Comment by gyuho** [comment]
@xiang90 

Just confirmed that both v2 and v3 have problems with parsing value with special characters or negative numbers. And found out this is the way unix commands have been working [1]. So I suggest to do the same thing as cockroachdb [1], just printing out the help message to show users workarounds.

```
# (X) NOT WORK
./etcdctl set aaa -bbb
./etcdctl set aaa '-bbb'
./etcdctl set qqq -100

# (O) WORK
./etcdctl set -- aaa -bbb
./etcdctl set -- aaa '-bbb'
./etcdctl set -- qqq -100

# (X) NOT WORK
./etcdctlv3 --endpoint="127.0.0.1:12378" put aaa -bbb
./etcdctlv3 --endpoint="127.0.0.1:12378" put aaa '-bbb'
./etcdctlv3 --endpoint="127.0.0.1:12378" put qqq -100

# (O) WORK
./etcdctlv3 --endpoint="127.0.0.1:12378" put aaa -- -bbb
./etcdctlv3 --endpoint="127.0.0.1:12378" put aaa -- '-bbb'
./etcdctlv3 --endpoint="127.0.0.1:12378" put qqq -- -100

# (O) WORK
./etcdctlv3 --endpoint="127.0.0.1:12378" put -- aaa -www
./etcdctlv3 --endpoint="127.0.0.1:12378" put -- aaa '-iii'
./etcdctlv3 --endpoint="127.0.0.1:12378" put -- qqq -200
```


---
[1]: https://github.com/spf13/cobra/issues/124
[2]: https://github.com/cockroachdb/cockroach/pull/1667

**Comment by xiang90** [comment]
> So I suggest to do the same thing as cockroachdb 1, just printing out the help message to show users workarounds.

Can you give me an example of cockroach's workaround?

**Comment by gyuho** [comment]
@xiang90 https://github.com/mbertschler/cockroach/blob/a27760c33fa18b1a1b42dafb63f8b24155f67589/server/cli/kv.go#L140-L148

**Comment by xiang90** [comment]
@gyuho Seems reasonable. Can you improve the sub command doc then?

**Comment by gyuho** [comment]
@xiang90 Sure, I will update help message of v2 and v3 `etcdctl`s. Thanks

**Comment by gyuho** [comment]
Resolved with https://github.com/coreos/etcd/pull/4193.

Now we have man page for special cases:

```
./etcdctl set -h
NAME:
   ./etcdctl set - set the value of a key

USAGE:
   ./etcdctl set [command options] <key> <value>

DESCRIPTION:
   Set sets the value of a key.

   When <value> begins with '-', <value> is interpreted as a flag.
   Insert '--' for workaround:

   $ set -- <key> <value>

OPTIONS:
   --ttl "0"			key time-to-live
   --swap-with-value 		previous value
   --swap-with-index "0"	previous index
   


./etcdctlv3 put -h
NAME:
	put - Put puts the given key into the store.

USAGE:
	etcdctlv3 put [options] <key> <value>

DESCRIPTION:
	Put puts the given key into the store.
	
	When <value> begins with '-', <value> is interpreted as a flag.
	Insert '--' for workaround:
	
	$ put [options] <key> -- <value>
	$ put [options] -- <key> <value>

OPTIONS:
      --lease="0"	lease ID attached to the put key

GLOBAL OPTIONS:
      --endpoint="127.0.0.1:2378"	gRPC endpoint

```
