### ISSUE TITLE
Getting "cannot assign requested address" on CentOS#7 

### ISSUE THREAD

**Issue by nkhare** [coreos/etcd#2028]
I configured 3 node etcd cluster and set ulimit value to 100000 (ulimit -n 100000) on all nodes and ran boom benchmark for 50 K request with concurrency set to 500 
$ ./gocode/bin/boom -m PUT -d value=bar -n 50000 -c 500 http://etcdhost1:4001/v2/keys/bench

and I always get " dial tcp 172.20.10.77:4001: cannot assign requested address
" errors.

With 20400 requests it works fine.

Following are Steps to re-produce the issue on single system. 

1. Install CentOS 7.

2. Add following entries in /etc/hosts

127.0.0.1       etcdhost1
127.0.0.1       etcdhost2
127.0.0.1       etcdhost3

3. Install wget,golang,git,lsof
$ yum install wget golang git lsof

4. Download etcd and extract it on /root
$ wget https://github.com/coreos/etcd/releases/download/v2.0.0-rc.1/etcd-v2.0.0-rc.1-linux-amd64.tar.gz

5. Untar it create a softlink to /root/etcd 
$ tar xvfz etcd-v2.0.0-rc.1-linux-amd64.tar.gz 
$ ln -s etcd-v2.0.0-rc.1-linux-amd64 etcd

6. Install goreman and boom
$ mkdir /root/gocode
$ export GOPATH=/root/gocode
$ go get github.com/mattn/goreman
$ go get github.com/rakyll/boom

7. Create a a goreman config file (Procfile_3nodes) with following content
etcd1: /root/etcd/etcd -name etcdhost1 -listen-client-urls http://etcdhost1:4001 -advertise-client-urls http://etcdhost1:4001 -listen-peer-urls http://etcdhost1:7001 -initial-advertise-peer-urls http://etcdhost1:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'etcdhost2=http://etcdhost2:7002,etcdhost1=http://etcdhost1:7001,etcdhost3=http://etcdhost3:7003' -initial-cluster-state new
etcd2: /root/etcd/etcd -name etcdhost2 -listen-client-urls http://etcdhost2:4002 -advertise-client-urls http://etcdhost2:4002 -listen-peer-urls http://etcdhost2:7002 -initial-advertise-peer-urls http://etcdhost2:7002 -initial-cluster-token etcd-cluster-1 -initial-cluster 'etcdhost2=http://etcdhost2:7002,etcdhost1=http://etcdhost1:7001,etcdhost3=http://etcdhost3:7003' -initial-cluster-state new
etcd3: /root/etcd/etcd -name etcdhost3 -listen-client-urls http://etcdhost3:4003 -advertise-client-urls http://etcdhost3:4003 -listen-peer-urls http://etcdhost3:7003 -initial-advertise-peer-urls http://etcdhost3:7003 -initial-cluster-token etcd-cluster-1 -initial-cluster 'etcdhost2=http://etcdhost2:7002,etcdhost1=http://etcdhost1:7001,etcdhost3=http://etcdhost3:7003' -initial-cluster-state new
  
8. Set ulimit to 100000
$ ulimit -n 100000

9. Using goreman set the etcd cluster
$ /root/gocode/bin/goreman -f Procfile_3nodes start 

10. Run the benchmark
$ /root/gocode/bin/boom -m PUT -d value=bar -n 50000 -c 500 http://etcdhost1:4001/v2/keys/bench

**Comment by nkhare** [comment]
With "lsof" I don't see open files crossing more than 13 K - 14 K. If there are less FDs to open then I get "dial tcp 127.0.0.1:4001: too many open files" error.

**Comment by xiang90** [comment]
@nkhare You are running the client and sever on the same machine. And it seems like the request rate is higher than the port recycling rate. 

Boom (the benchmark tool) is not implemented correctly, since it does not read all the body before close it. So you cannot reuse the port: https://github.com/rakyll/boom/blob/master/boomer/run.go#L64.

See: https://go-review.googlesource.com/#/c/1531/3/src/net/http/response.go

**Comment by xiang90** [comment]
@nkhare I will send an issue to boom repo soon.

**Comment by nkhare** [comment]
@xiang90 thanks. Setting up follow also helps. 
sysctl -w net.ipv4.tcp_tw_reuse=1
