### ISSUE TITLE
cluster wide configuration

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2038]
from #1551 
The thoughts is to expose HTTP endpoint for it and make the timeout cluster-wide configurable.

**Comment by damm** [comment]
This would be rather helpful for my team as we use etcd in most regions (asia pacific, england, us, soon india) 

also a command line argument would work no? 

P.S. if help will bump this milestone up please add the label.

**Comment by xiang90** [comment]
@yichengq Any update on this one?

**Comment by xiang90** [comment]
This is a configuration issue. It is not urgent since most users can actually ensure the configuration are consistent across their cluster members and do not really need to do runtime configuration changes.

**Comment by xiang90** [comment]
this is unlikely to happen anytime soon. we rarely see people have configuration issues due to the incompatible flags provided to different etcd members in the cluster.
