### ISSUE TITLE
long polling returns a success with an empty body after 5 min without updates

### ISSUE THREAD

**Issue by julien-truffaut** [coreos/etcd#2053]
I haven't been able to find a documentation on this behavior and I don't know if it is configurable.

Side points:
server returns a 200 with empty body and no content length header, a 204 and / or content length will be very helpful to identify this situation without parsing the body of the response.

**Comment by xiang90** [comment]
We have fixed this issue. Please try with current master. Thanks.

**Comment by julien-truffaut** [comment]
@xiang90 would you have a link to the fix? Could you also tell me if it has been released? 
Thank you

**Comment by xiang90** [comment]
@julien-truffaut https://github.com/coreos/etcd/pull/2049
we cannot set the timeout due to an upstream issue: https://github.com/golang/go/issues/9524.

We now use tcp keep alive to detect client disconnection. We will include this change in the next release, probably late this month.
