### ISSUE TITLE
swagger http api

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2055]
we might want to define v3 http api in swagger

**Comment by xiang90** [comment]
Closing for now. We decided to use gRPC instead of HTTP+JSON as initial API for v3. So the definition is a proto currently at https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md .We will revisit this when we start to design HTTP API.

**Comment by philips** [comment]
ideally we just use this https://github.com/gengo/grpc-gateway
