### ISSUE TITLE
kill todos

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2058]

**Comment by jonboulle** [comment]
This sounds ambitious so I'd be inclined to break it apart, but first step is just to collect and list them all.

**Comment by yichengq** [comment]
I need to kill the TODO at https://github.com/coreos/etcd/blob/master/etcdserver/cluster.go#L340, which helps address https://github.com/coreos/etcd/pull/3657#issuecomment-146697923 .

**Comment by xiang90** [comment]
we already broke this into different parts. closing.
