### ISSUE TITLE
Two nodes can see key, other cannot

### ISSUE THREAD

**Issue by tleyden** [coreos/etcd#2063]
All machines can see eachother:

```
core@core-03 ~ $ fleetctl list-machines
MACHINE		IP		METADATA
0f26e50a...	172.17.8.101	-
900b519c...	172.17.8.103	-
b43a0698...	172.17.8.102	-
```

(same result on all machines)

On core-01 and core-03, it can see the key:

```
core@core-01 ~ $ etcdctl get /services/couchbase/bootstrap_ip
172.17.8.101
core@core-03 ~ $ etcdctl get /services/couchbase/bootstrap_ip
172.17.8.101
```

But on core-02, it cannot:

```
$ etcdctl get /services/couchbase/bootstrap_ip
Error:  100: Key not found (/services/couchbase/bootstrap_ip) [1250787]
```

Although `ls` does work:

```
core@core-02 ~ $ etcdctl ls /services/couchbase/bootstrap_ip
/services/couchbase/bootstrap_ip
```

Anything I can provide to help debug/reproduce this?  I've run CoreOS many times under Vagrant, and this is the first time I've seen an issue like this.

I am running CoreOS stable on Vagrant, using etcd version 0.4.6.

**Comment by yichengq** [comment]
@tleyden 
I think the data is different because core-02 doesn't catch up the progress of core-01 and core-03.
Could you print out `etcdctl -o 'extended' get /services/couchbase/bootstrap_ip` for more details?

**Comment by tleyden** [comment]
Sure, here you go:

## core-01

```
core@core-01 ~ $ etcdctl -o 'extended' get /services/couchbase/bootstrap_ip
Key: /services/couchbase/bootstrap_ip
Created-Index: 1503985
Modified-Index: 1503985
TTL: 29
Etcd-Index: 1504036
Raft-Index: 2454784
Raft-Term: 1282

172.17.8.102
```

## core-02

```
core@core-02 ~ $ etcdctl -o 'extended' get /services/couchbase/bootstrap_ip
Error:  100: Key not found (/services/couchbase/bootstrap_ip) [1250787]
```

## core-03

```
core@core-03 ~ $ etcdctl -o 'extended' get /services/couchbase/bootstrap_ip
Key: /services/couchbase/bootstrap_ip
Created-Index: 1503985
Modified-Index: 1503985
TTL: 25
Etcd-Index: 1504040
Raft-Index: 2454796
Raft-Term: 1282

172.17.8.102
```

**Comment by tleyden** [comment]
@yichengq anything else I can collect?  I can hop on irc if it will speed up debugging.

**Comment by yichengq** [comment]
The index is the time in etcd life (https://github.com/coreos/etcd/blob/master/Documentation/2.0/api.md#setting-the-value-of-a-key).
core-02's current index is smaller than created index of the key in core-01 and core-03, which is the reason that core-02 cannot see this key.

I guess that core-02 cannot connect and sync the data from core-01 or core-03 for a long time. Can you check the log of core-02 and the connections between them?

**Comment by tleyden** [comment]
Sure.  Can you provide the command(s) to check the log?

**Comment by tleyden** [comment]
The box rebooted itself:

```
Broadcast message from locksmithd at 2015-01-10 06:08:15.135373079 +0000 UTC:
System reboot in 5 minutes!

Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.
```

and when it came back up, the problem was gone.  Is it too late to get anything useful from the logs?

**Comment by yichengq** [comment]
`journalctl -u etcd` gives your the log of etcd service that ran behind.

As long as etcd works again, it is great. If you want to dig in, could you provide the full log of the lost machine?

**Comment by tleyden** [comment]
I will close this since it may have been related to running an older version of CoreOS as mentioned in #2070
