### ISSUE TITLE
fleetctl list-machines returns error on one node in Vagrant cluster

### ISSUE THREAD

**Issue by tleyden** [coreos/etcd#2070]
I'm running coreos stable 494.4.0 (slightly out of date) under Vagrant, and all the sudden I'm getting this error after running `vagrant halt && vagrant up`.  It started happening shortly after I saw https://github.com/coreos/etcd/issues/2063, though I don't know if they are related.

Here is the vagrant output when I boot up:

https://gist.github.com/tleyden/a9bd816876f55440b40e

When I ssh into core-02 and core-03, `fleetctl list-machines` and `systemctl status etcd` both look fine:

* [core-02 output](https://gist.github.com/tleyden/db8c6f7c3df662a8f4c3)
* [core-03 output](https://gist.github.com/tleyden/963a9c39afb5f87a650c)

But core-01 has a problem when I run `fleetctl list-machines`:

```
2015/01/10 23:16:01 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: too many redirects
```

* [Full core-01 output](https://gist.github.com/tleyden/3a72c56a7db896bd496f)  (in particular, note the line where [etcd stops](https://gist.github.com/tleyden/3a72c56a7db896bd496f#file-gistfile1-txt-L31))

Not sure if this is relevant, but if I manually look into etcd from core-01, I can see three unique machine ids:

```
core@core-01 ~ $ etcdctl ls /_coreos.com/fleet/machines
/_coreos.com/fleet/machines/0f26e50a64dd4941b622e7f0bdc82929
/_coreos.com/fleet/machines/900b519c8e6548778b4cf7dff16ab7b4
/_coreos.com/fleet/machines/b43a0698c2374a659bfcec4e12722d7a
```

So far it's been 100% reproducible, I've ran `vagrant halt && vagrant up` several times, and each time have gotten the same issue.

Should I upgrade to a later coreos version and retry?  Or is it worth debugging?

**Comment by yichengq** [comment]
@tleyden I think you should go and try a later version. It should work fine now.

**Comment by tleyden** [comment]
Ok thanks.  I'll close the bug for now, and re-open it if I still see issues.

**Comment by yichengq** [comment]
thx

**Comment by tleyden** [comment]
OK I updated ([vagrant logs here](https://gist.github.com/tleyden/870c261a858b83a6f121)) and I'm getting the exact same error as mentioned in the initial bug report.

```
core@core-01 ~ $ fleetctl list-machines
2015/01/12 20:54:16 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: too many redirects
2015/01/12 20:54:16 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms
2015/01/12 20:54:16 INFO client.go:278: Failed getting response from http://127.0.0.1:4001/: too many redirects
2015/01/12 20:54:16 ERROR client.go:200: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 200ms
...
```

Here is the full [journalctl -u etcd](https://gist.github.com/tleyden/a6a2a3a2963c733f5f1c) output from core-01 machine which is getting the above errors.

Do you need the `journalctl -u etcd` output from the other 2 machines as well?

**Comment by yichengq** [comment]
could you clear the image and start from the beginning? Current failure is caused by old data directory which is broken somehow.
It will be great if you can give full lines through `journalctl`.

**Comment by tleyden** [comment]
> It will be great if you can give full lines through journalctl.

Sure, how do I do that?

**Comment by tleyden** [comment]
> could you clear the image and start from the beginning? 

When you say clear the image, do you mean `vagrant destroy` it?  

Let me know the `journalctl` option and I will get back to you on that.

**Comment by tleyden** [comment]
> could you clear the image and start from the beginning?

Actually, I'm hoping for a lighter weight operation because this would mean re-downloading a bunch of rather large docker images from scratch.

**Comment by yichengq** [comment]
i think `vagrant destroy` destroys all resources that were created during the machine creation process, and `vagrant box` manages boxes.

try `journalctl --no-pager -u etcd`

**Comment by tleyden** [comment]
@yichengq here is the output from `journalctl --no-pager -u etcd`

https://gist.github.com/tleyden/58e76b9a8e7af9d21d1e

**Comment by yichengq** [comment]
@tleyden It happened some known bugs in old version in the log.
Could you `vagrant destroy` and see whether it performs well in the latest version?

**Comment by tleyden** [comment]
@yicheng2 do you mean coreos alpha release channel?

**Comment by tleyden** [comment]
or do you mean upgrade from stable '522.4.0' to stable '522.5.0'...?

**Comment by tleyden** [comment]
I ran this:

```
vagrant destroy
vagrant box update  (upgraded to stable version 522.5.0)
vagrant up
```

and now the `fleetctl list-machines` issue is gone:

```
core@core-01 ~ $ fleetctl list-machines
MACHINE		IP		METADATA
5ce71b20...	172.17.8.101	-
7aa76eae...	172.17.8.102	-
9210087f...	172.17.8.103	-
```

Thanks for your help!
