### ISSUE TITLE
Respect of interface in configuration

### ISSUE THREAD

**Issue by pierreozoux** [coreos/etcd#2072]
Hi,

For now, I'm using a single node etcd cluster, with planning to expand to many nodes.
As a security mesure, I decided to map the `etcd` ports to the docker gateway network interface (I needed it inside a confd container).
(For the future, I'll build a vpn between my node, and map `etcd` ports to the VPN network interface)

Here is my configration:
````
cat /var/run/systemd/system/etcd.service.d/20-cloudinit.conf  
[Service]
Environment="ETCD_ADDR=172.17.42.1:4001"
Environment="ETCD_PEER_ADDR=172.17.42.1:7001"
````

My issue: I can see that the port `4001` and `7001` are also open to the wild (my public IP...), and I'm not confident about that.
I think my configuration is good, but maybe there is a mistake there. If my configuration is good, I believe it's a bug in etcd that doesn't respect the network inteface.
(If you send me an [email](pierre@ozoux.net), I can give you an IP of a server with this config and "bug")

Thanks for your help!

**Comment by yichengq** [comment]
@pierreozoux 
You need to set `-bind-addr` and `-peer-bind-addr` to make it listen on private ip only.

**Comment by pierreozoux** [comment]
From the documentation, it says:
`-addr` - The advertised public hostname:port for client communication. Defaults to 127.0.0.1:4001.
`-bind-addr` - The listening hostname for client communication. Defaults to advertised IP.
 `-peer-addr` - The advertised public hostname:port for server communication. Defaults to 127.0.0.1:7001.
`-peer-bind-addr` - The listening hostname for server communication. Defaults to advertised IP.

Is'nt it enough to set `-addr` and `-peer-addr`, the bind should follow?
I'll try as you say and let you know.

Thanks for your help!

Pierre

**Comment by yichengq** [comment]
@pierreozoux I check the code and think that is documentation error.

**Comment by pierreozoux** [comment]
Ok, just tested, and you are right!

I'll update my code.
I leave this open as a reference to update documentation? Unfortunately i'm not yet comfy with go to go and read it directly, but the source is always the best documentation!

Thanks again for your help!

About updating the documentation, I'll let you do it, as I still don't understand to what the `bind` addresses default to..

**Comment by yichengq** [comment]
@kelseyhightower has fixed it. Thanks!
