### ISSUE TITLE
Howto for off-public-internet etcd cluster build/config

### ISSUE THREAD

**Issue by bevand10** [coreos/etcd#2080]
Hi.

I'm struggling to find a concise, known-to-work, howto for building, from scratch, an off-public-internet etcd cluster.

Initially using 3 machines, I'm looking for the contents of /etc/etcd/etcd.conf to install on all 3 nodes, given the following:

CoreOS1 - 10.0.1.1
CoreOS2 - 10.0.1.2
CoreOS3 - 10.0.1.3
ClusterName - myetcdcluster20150113040

I have no public internet access so can't use discovery.etcd.io - and wouldn't want to for an intranet site anyway.

I've read https://coreos.com/docs/cluster-management/setup/cluster-discovery/ and the section "Running Your Own Discovery Service" but it contains no information on how to actually do it!

My aim is to build one of these https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services - without a dependency on discovery.etcd.io.

**Comment by bevand10** [comment]
OK, for others who may stumble across this question in the future. You need the following:

On CoreOS01, /etc/etcd/etcd.conf should contain:

addr = "10.0.1.1:4001"
bind_addr = "0.0.0.0:4001"
discovery = "http://10.0.1.1:4001/v2/keys/_etcd/myetcdcluster20150113040"
peers = [ "10.0.1.2:4001", "10.0.1.3:4001" ]
[peer]
addr = "10.0.1.1:7001"
bind_addr = "0.0.0.0:7001"

On CoreOS2, /etc/etcd/etcd.conf should contain:

addr = "10.0.1.2:4001"
bind_addr = "0.0.0.0:4001"
discovery = "http://10.0.1.1:4001/v2/keys/_etcd/myetcdcluster20150113040"
peers = [ "10.0.1.1:4001", "10.0.1.3:4001" ]
[peer]
addr = "10.0.1.2:7001"
bind_addr = "0.0.0.0:7001"

On CoreOS3, /etc/etcd/etcd.conf should contain:

addr = "10.0.1.3:4001"
bind_addr = "0.0.0.0:4001"
discovery = "http://10.0.1.1:4001/v2/keys/_etcd/myetcdcluster20150113040"
peers = [ "10.0.1.1:4001", "10.0.1.2:4001" ]
[peer]
addr = "10.0.1.3:7001"
bind_addr = "0.0.0.0:7001"

Then use "systemctl restart etcd.service && systemctl daemon-reload" on each node to bring them up/to join the cluster "myetcdcluster20150113040".

I'm hoping that this could perhaps make it into the official documentation - just to help new users out?

**Comment by sholsapp** [comment]
Did this ever end up getting documented?
