### ISSUE TITLE
Cannot set --name correctly in etcd 2.0.0-rc.1

### ISSUE THREAD

**Issue by waitingkuo** [coreos/etcd#2081]
I'm currently the v2.0.0-rc1 version on my Mac.
It works when I use the default machine name "default".
Both of following commands work:

    ./etcd
    ./etcd --name 'default'

But it doesn't work when I assign another name

    MacBook-Pro:try willy$ ./etcd --name default2 
    2015/01/13 17:57:58 no data-dir provided, using default data-dir ./default2.etcd
    2015/01/13 17:57:58 etcd: listening for peers on http://localhost:2380
    2015/01/13 17:57:58 etcd: listening for peers on http://localhost:7001
    2015/01/13 17:57:58 etcd: listening for client requests on http://localhost:2379
    2015/01/13 17:57:58 etcd: listening for client requests on http://localhost:4001
    2015/01/13 17:57:58 etcd: stopping listening for client requests on http://localhost:4001
    2015/01/13 17:57:58 etcd: stopping listening for client requests on http://localhost:2379
    2015/01/13 17:57:58 etcd: stopping listening for peers on http://localhost:7001
    2015/01/13 17:57:58 etcd: stopping listening for peers on http://localhost:2380
    2015/01/13 17:57:58 etcd: couldn't find local name "default2" in the initial cluster configuration

**Comment by xiang90** [comment]
The name you give to etcd must match the name you have in the initial cluster configuration. The default ones are matched. If you change the name, then you need to change the initial cluster configuration. 

Please refer https://github.com/coreos/etcd/blob/master/Documentation/2.0/clustering.md
