### ISSUE TITLE
low cost linearizable read

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2102]
- [x] high latency, high throughput l-read on followers
- [x] low latency l-read on leader
- [x] do not hit disk 
- [x] linearizable by default

**Comment by xiang90** [comment]
etcd server itself is keeping on sending proposals. 

Probably the simplest way for us to achieve "low cost read" is to delay the executing of the read request until there is a proposal that proposed on the local server after the read request got applied on the local server. So both follower and leader can serve read requests.

"low cost" = low communication cost + high throughput. we probably can afford the extra latency.
/cc @yichengq @ongardie

**Comment by ongardie** [comment]
There's various ways to trade off cost and consistency under various failure models. Have you read through section 6.4 of that big book I left in your office?

Keep in mind that a follower needs to know that (1) it's up-to-date with the leader AND (2) the leader is up-to-date. So I think it takes more than 1 round trip for followers to serve linearizable reads without relying on clocks.

**Comment by xiang90** [comment]
@ongardie Yea. I have looked the approaches described in the book. However, they all involve the raft internal.

I am thinking of a simpler but higher latency way to do it at application level, given the fact etcd is keeping generating proposals at all servers.

1. Client read arrives at T1 to server A.
2. Server A holds the read requests. 
3. Server A waits until a write request it proposed after T1 to be applied at T2.
4. Server A executes the read request and replies to client at T3. 

We have the guarantee that T3 > T2 > T1. 
And we know the state of server A at T2 MUST be more up-to-date (see all the invocations before T1) than the states of all the servers at T1, since server A at T2 has seen a event that happens after T1.

So we know the read request/reply of A is linearizable.

**Comment by ongardie** [comment]
@xiang90 sounds like that'd work. When you say "waits until a write request", you probably want to issue a no-op after a timeout; otherwise you might be waiting a very long time :)

**Comment by mitake** [comment]
@xiang90 @ongardie hi, could you share the title of the book describing the approach? It would be related to my ongoing work: https://github.com/coreos/etcd/pull/3950

**Comment by gyuho** [comment]
@mitake I think they talk about [Diego's dissertation](https://github.com/ongardie/dissertation).

**Comment by ongardie** [comment]
Yes, thank you @gyuho.

**Comment by gyuho** [comment]
Np!

Sincerely,
Gyu-Ho Lee

**Comment by mitake** [comment]
@gyuho @ongardie thanks a lot!

**Comment by xiang90** [comment]
this is finally fixed by https://github.com/coreos/etcd/pull/5553. The application part is tracked by https://github.com/coreos/etcd/issues/5193
