### ISSUE TITLE
etcdctl watch crashes, when watching a ttl key that expired

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#2111]
Three nodes fedora2, fedora3, fedora4 are watching a ttl key "lock" that expires. I am assuming the empty line gets printed as a result of the key expiring. After sometime, one of them gets a panic as watch returns a nil response. The other two nodes get an error saying unexpected JSON output. I thought this issue was fixed in 2.0.0.

[root@fedora2 ~]# etcdctl --version
etcdctl version 2.0.0-rc.1

[root@fedora2 ~]# etcdctl watch /lock --forever
fedora1

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x44140e]

goroutine 16 [running]:
runtime.panic(0x796ba0, 0x9f5593)
	/home/ravi/toolchain/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/coreos/etcd/etcdctl/command.printAll(0x0, 0xc208000b80, 0x6)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:132 +0x1e
github.com/coreos/etcd/etcdctl/command.watchCommandFunc(0xc2080424d0, 0xc208050280, 0x5, 0x0, 0x0)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/watch_command.go:79 +0x5ae
github.com/coreos/etcd/etcdctl/command.rawhandle(0xc2080424d0, 0x89d0b0, 0x7fa30829e768, 0x0, 0x0)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:74 +0x535
github.com/coreos/etcd/etcdctl/command.handlePrint(0xc2080424d0, 0x89d0b0, 0x89d070)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:80 +0x31
github.com/coreos/etcd/etcdctl/command.handleKey(0xc2080424d0, 0x89d0b0)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:113 +0x3b
github.com/coreos/etcd/etcdctl/command.func·013(0xc2080424d0)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/watch_command.go:39 +0x31
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x7ec310, 0x5, 0x0, 0x0, 0x825d90, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc2080560c0, 0xc20800e000, 0x4, 0x4, 0x0, 0x0)
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:125 +0x941
main.main()
	/home/ravi/open/etcd/gopath/src/github.com/coreos/etcd/etcdctl/main.go:59 +0x6f0

[root@fedora3 ~]# etcdctl watch /lock --forever
fedora1

Error:  unexpected end of JSON input

[root@fedora4 ~]# etcdctl watch /lock --forever
fedora1

Error:  unexpected end of JSON input

**Comment by xiang90** [comment]
@ravigadde Please try with master. It should be solved.
