### ISSUE TITLE
etcdctl watch returned before real value change

### ISSUE THREAD

**Issue by linfan** [coreos/etcd#2114]
Hi,

I wrote below script watching path "/demo", it suppose to append a prefix "Hello" when the content in that path changed. Then I triggered a change on another node. But as a result, the "etcdctl get" command always got the old value of path "/demo", not the changed one.
```KEY=/demo
while true; do 
    etcdctl watch ${KEY}
    etcdctl update ${KEY} "Hello $(etcdctl get ${KEY})"    
done
```

However, after I put a bit delay before getting the value of path, it begin to work as expected.
```KEY=/demo
while true; do 
    etcdctl watch ${KEY}
    sleep 1s      # <-- wait 1s here
    etcdctl update ${KEY} "Hello $(etcdctl get ${KEY})"    
done
```

So from appearance, the reason is when "etcdctl watch" command returned, etcd is still under synchronisation process and not ready to provide the new value.

Is this a designed behaviour or unexpected issue?

**Comment by xiang90** [comment]
@linfan Can you try to reproduce this on current master? Thanks.

**Comment by linfan** [comment]
I tried again against the master build, this issue already gone. Thanks!

The etcd version tagged as 2.0.3

```
root@7db926a0818c:/etcd/bin# ./etcd --version
etcd version 2.0.3
```
