### ISSUE TITLE
"etcdctl member add host-2 http://localhost:7002" terminates etcd

### ISSUE THREAD

**Issue by AndersBlomdell** [coreos/etcd#2115]
Running the following script:

#####################################################
#!/bin/sh
start () {
    rm -rf /tmp/etcd/$1
    mkdir /tmp/etcd/$1
    cd /tmp/etcd/$1
    INITIAL_CLUSTER="host-$1=http://localhost:700$1"
    etcd \
        --name host-$1 \
        --initial-cluster-state 'new' \
        --listen-peer-urls "http://localhost:700$1" \
        --initial-advertise-peer-urls "http://localhost:700$1" \
	--listen-client-urls "http://localhost:400$1" \
        --advertise-client-urls "http://localhost:400$1" \
        --initial-cluster-token etcd-cluster-1 \
        --initial-cluster ${INITIAL_CLUSTER} 2>&1 | sed -e "s|^|host-$1: |" 
    RES=$?
    echo "host-$1: terminated with $RES"
}

pkill etcd
mkdir -p /tmp/etcd
echo ; echo "### Starting host-1"
start 1 &
sleep 2
echo ; echo "### Starting host-2"
start 2 &
sleep 2
echo ; echo "### Trying to add host-2 to host-1"
etcdctl member add host-2 http://localhost:7002
sleep 2
echo ; echo "### Killing remaining servers"
pkill etcd
##########################################

Generates the following (host -1 terminated at member add)

##########################################
### Starting host-1
host-1: 2015/01/19 17:25:39 no data-dir provided, using default data-dir ./host-1.etcd
host-1: 2015/01/19 17:25:39 etcd: listening for peers on http://localhost:7001
host-1: 2015/01/19 17:25:39 etcd: listening for client requests on http://localhost:4001
host-1: 2015/01/19 17:25:39 etcdserver: name = host-1
host-1: 2015/01/19 17:25:39 etcdserver: data dir = host-1.etcd
host-1: 2015/01/19 17:25:39 etcdserver: heartbeat = 100ms
host-1: 2015/01/19 17:25:39 etcdserver: election = 1000ms
host-1: 2015/01/19 17:25:39 etcdserver: snapshot count = 10000
host-1: 2015/01/19 17:25:39 etcdserver: advertise client URLs = http://localhost:4001
host-1: 2015/01/19 17:25:39 etcdserver: initial advertise peer URLs = http://localhost:7001
host-1: 2015/01/19 17:25:39 etcdserver: initial cluster = host-1=http://localhost:7001
host-1: 2015/01/19 17:25:39 etcdserver: start member a8266ecf031671f3 in cluster 1837dffd61a07a42
host-1: 2015/01/19 17:25:39 raft: a8266ecf031671f3 became follower at term 0
host-1: 2015/01/19 17:25:39 raft: newRaft a8266ecf031671f3 [peers: [], term: 0, commit: 0, lastindex: 0, lastterm: 0]
host-1: 2015/01/19 17:25:39 raft: a8266ecf031671f3 became follower at term 1
host-1: 2015/01/19 17:25:39 etcdserver: added local member a8266ecf031671f3 [http://localhost:7001] to cluster 1837dffd61a07a42
host-1: 2015/01/19 17:25:41 raft: a8266ecf031671f3 is starting a new election at term 1
host-1: 2015/01/19 17:25:41 raft: a8266ecf031671f3 became candidate at term 2
host-1: 2015/01/19 17:25:41 raft: a8266ecf031671f3 received vote from a8266ecf031671f3 at term 2
host-1: 2015/01/19 17:25:41 raft: a8266ecf031671f3 became leader at term 2
host-1: 2015/01/19 17:25:41 raft.node: a8266ecf031671f3 elected leader a8266ecf031671f3 at term 2
host-1: 2015/01/19 17:25:41 etcdserver: published {Name:host-1 ClientURLs:[http://localhost:4001]} to cluster 1837dffd61a07a42

### Starting host-2
host-2: 2015/01/19 17:25:41 no data-dir provided, using default data-dir ./host-2.etcd
host-2: 2015/01/19 17:25:41 etcd: listening for peers on http://localhost:7002
host-2: 2015/01/19 17:25:41 etcd: listening for client requests on http://localhost:4002
host-2: 2015/01/19 17:25:41 etcdserver: name = host-2
host-2: 2015/01/19 17:25:41 etcdserver: data dir = host-2.etcd
host-2: 2015/01/19 17:25:41 etcdserver: heartbeat = 100ms
host-2: 2015/01/19 17:25:41 etcdserver: election = 1000ms
host-2: 2015/01/19 17:25:41 etcdserver: snapshot count = 10000
host-2: 2015/01/19 17:25:41 etcdserver: advertise client URLs = http://localhost:4002
host-2: 2015/01/19 17:25:41 etcdserver: initial advertise peer URLs = http://localhost:7002
host-2: 2015/01/19 17:25:41 etcdserver: initial cluster = host-2=http://localhost:7002
host-2: 2015/01/19 17:25:41 etcdserver: start member 6e3bd23ae5f1eae0 in cluster 26d3992030da154a
host-2: 2015/01/19 17:25:41 raft: 6e3bd23ae5f1eae0 became follower at term 0
host-2: 2015/01/19 17:25:41 raft: newRaft 6e3bd23ae5f1eae0 [peers: [], term: 0, commit: 0, lastindex: 0, lastterm: 0]
host-2: 2015/01/19 17:25:41 raft: 6e3bd23ae5f1eae0 became follower at term 1
host-2: 2015/01/19 17:25:41 etcdserver: added local member 6e3bd23ae5f1eae0 [http://localhost:7002] to cluster 26d3992030da154a
host-2: 2015/01/19 17:25:43 raft: 6e3bd23ae5f1eae0 is starting a new election at term 1
host-2: 2015/01/19 17:25:43 raft: 6e3bd23ae5f1eae0 became candidate at term 2
host-2: 2015/01/19 17:25:43 raft: 6e3bd23ae5f1eae0 received vote from 6e3bd23ae5f1eae0 at term 2
host-2: 2015/01/19 17:25:43 raft: 6e3bd23ae5f1eae0 became leader at term 2
host-2: 2015/01/19 17:25:43 raft.node: 6e3bd23ae5f1eae0 elected leader 6e3bd23ae5f1eae0 at term 2
host-2: 2015/01/19 17:25:43 etcdserver: published {Name:host-2 ClientURLs:[http://localhost:4002]} to cluster 26d3992030da154a

### Trying to add host-2 to host-1
host-1: 2015/01/19 17:25:43 etcdserver: added member 1aec93d1c7c2f15d [http://localhost:7002] to cluster 1837dffd61a07a42
Added member named host-2 with ID 1aec93d1c7c2f15d to cluster

ETCD_NAME="host-2"
ETCD_INITIAL_CLUSTER="host-2=http://localhost:7002,host-1=http://localhost:7001"
ETCD_INITIAL_CLUSTER_STATE="existing"
host-2: 2015/01/19 17:25:43 rafthttp: request ignored due to cluster ID mismatch got 1837dffd61a07a42 want 26d3992030da154a
host-1: 2015/01/19 17:25:43 etcdserver: conflicting cluster ID with the target cluster (26d3992030da154a != 1837dffd61a07a42)
host-1: 2015/01/19 17:25:43 etcdserver: the data-dir used by this member must be removed.
host-1: terminated with 0

### Killing remaining servers
host-2: terminated with 0

##########################################

**Comment by yichengq** [comment]
@AndersBlomdell 
You should start host-2 after letting it join the cluster.

We support static bootstrap now, which you can bootstrap a multiple-member cluster directly. You can find the doc here: https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static

If you want to play with runtime reconfiguration, here is documentation about how to do so: https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-member

**Comment by yichengq** [comment]
Feel free to write comments if it is still a problem to you.

**Comment by AndersBlomdell** [comment]
I know, the fact that an incorrect 'etcdctl member add' kills the server is my main complaint, just rejecting it would be a saner response (IMHO)

**Comment by yichengq** [comment]
@AndersBlomdell 
host-1 forms cluster-1, and host-2 forms cluster-2. The two clusters are different, and cannot be talked to each other, or it will corrupt the log.
In the view of cluster-1, the `member add` command is reasonable. When it tries to communicate with the new member, it finds that the cluster-id doesn't match. So it fatals.
When host-1 receives the `member add`, it is a sane request.

**Comment by AndersBlomdell** [comment]
I understand that the two clusters can't be merged, but is killing one of the clusters a sane behaviour?
Perhaps an implicit 'etcdctl member remove' would be saner in this case?

**Comment by xiang90** [comment]
@AndersBlomdell The first step is to make sure the original cluster is not corrupted by misconfiguration. The second step is to provide better user experience. 

What we can do it:
1. simply kill one of the conflicting machines. (current solution)
2. tries to detect which machines is the bad one and only kill the bad one.
3. never kill a machine but keep on outputting warnings. 

There might be more options. We are still exploring the alternatives, so we will go with the simplest one in the near future. If you have a better solution to share, we would be happy to hear and discuss in another issue.

Thanks!

**Comment by AndersBlomdell** [comment]
On 2015-01-20 20:33, Xiang Li wrote:
> @AndersBlomdell The first step is to make sure the original cluster
> is not corrupted by misconfiguration. The second step is to provide
> better user experience.
> 
> What we can do it:
> 1. simply kill one of the conflicting machines. (current solution)
Well, it's actually kill one of the clusters (see attached bug-01)

> 2. tries to detect which machines is the bad one and only kill the bad one.
> 3. never kill a machine but keep on outputting warnings. 
> 
> There might be more options. We are still exploring the alternatives,
> so we will go with the simplest one in the near future. If you have a
> better solution to share, we would be happy to hear and discuss in
> another issue.
Perhaps:
4. treat newly added members as prospects until they have proven worthy,
   i.e. don't actually join them to the cluster until they have proven
   that they don't conflict. This will prevent problems like those in
   attached bug-02 (which is actually not a bug :-), but more a flaw)

It would also be nice if the termination code was something else than 0
when etcd terminates.

/Anders

-- 
Anders Blomdell                  Email: anders.blomdell@control.lth.se
Department of Automatic Control
Lund University                  Phone:    +46 46 222 4625
P.O. Box 118                     Fax:      +46 46 138118
SE-221 00 Lund, Sweden
#!/bin/sh

#
# Demonstrating killing off a cluster by trying to join
# another cluster to it
#

INITIAL_CLUSTER_1="host-1=http://localhost:7001"
INITIAL_CLUSTER_1+=",host-2=http://localhost:7002"
INITIAL_CLUSTER_1+=",host-3=http://localhost:7003"
INITIAL_CLUSTER_1+=",host-4=http://localhost:7004"
INITIAL_CLUSTER_1+=",host-5=http://localhost:7005"

INITIAL_CLUSTER_2="host-6=http://localhost:7006"

start () {
    (
        rm -rf /tmp/etcd/$1
        mkdir /tmp/etcd/$1
        cd /tmp/etcd/$1
        set -x
        etcd \
            --name host-$1 \
            --initial-cluster-state $2 \
            --listen-peer-urls "http://localhost:700$1" \
            --initial-advertise-peer-urls "http://localhost:700$1" \
	    --listen-client-urls "http://localhost:400$1" \
            --advertise-client-urls "http://localhost:400$1" \
            --initial-cluster-token etcd-cluster-1 \
            --initial-cluster $3 
        RES=$?
        echo "host-$1: terminated with $RES"
    ) 2>&1 | sed -e "s|^|host-$1: |"
}

pkill etcd
mkdir -p /tmp/etcd
start 1 new ${INITIAL_CLUSTER_1} &
start 2 new ${INITIAL_CLUSTER_1} &
start 3 new ${INITIAL_CLUSTER_1} &
start 4 new ${INITIAL_CLUSTER_1} &
start 5 new ${INITIAL_CLUSTER_1} &
start 6 new ${INITIAL_CLUSTER_2} &
sleep 5
echo
echo
echo
etcdctl --peers http://localhost:4001 member list
echo
etcdctl --peers http://localhost:4006 member list
echo
echo
echo
sleep 5
etcdctl member add host-6 http://localhost:7006
echo
echo
echo

for i in 1 2 3 4 5 6 7 8 9 10 ; do
    echo
    echo
    etcdctl member list
    echo
    echo
    jobs
    sleep 1
done

#!/bin/bash

#
# Demonstrating rendering a cluster unusable by adding new
# nonexisting members until consensus is lost
#
INITIAL_CLUSTER_1="host-1=http://localhost:7001"
INITIAL_CLUSTER_1+=",host-2=http://localhost:7002"
INITIAL_CLUSTER_1+=",host-3=http://localhost:7003"

start () {
    (
        rm -rf /tmp/etcd/$1
        mkdir /tmp/etcd/$1
        cd /tmp/etcd/$1
        set -x
        etcd \
            --name host-$1 \
            --initial-cluster-state $2 \
            --listen-peer-urls "http://localhost:700$1" \
            --initial-advertise-peer-urls "http://localhost:700$1" \
	    --listen-client-urls "http://localhost:400$1" \
            --advertise-client-urls "http://localhost:400$1" \
            --initial-cluster-token etcd-cluster-1 \
            --initial-cluster $3 
        RES=$?
        echo "host-$1: terminated with $RES"
    ) 2>&1 | sed -e "s|^|host-$1: |"
}

pkill etcd
mkdir -p /tmp/etcd
start 1 new ${INITIAL_CLUSTER_1} &
pid1=$!
start 2 new ${INITIAL_CLUSTER_1} &
pid2=$!
start 3 new ${INITIAL_CLUSTER_1} &
pid3=$!
sleep 5
echo
echo
echo
etcdctl --peers http://localhost:4001 member list
echo
echo
echo
sleep 5
echo
echo
etcdctl member list
etcdctl set last "$(date)"
etcdctl get last
echo
echo
etcdctl member add host-4 http://localhost:7004
echo
echo
etcdctl member list
etcdctl set last "$(date)"
etcdctl get last
echo
echo
etcdctl member add host-5 http://localhost:7005
echo
echo
etcdctl member list
etcdctl set last "$(date)"
etcdctl get last
echo
echo

for i in 1 2 3 ; do
    echo
    echo
    etcdctl member list
    etcdctl set last "$(date)"
    etcdctl get last
    echo
    echo
    jobs
    sleep 1
done
echo
echo
echo Kill consensus
echo
echo
kill -HUP $pid1
#
# Now we will soon lose all contact with the cluster
#
for i in 1 2 3  ; do
    echo
    echo
    etcdctl member list
    etcdctl set last "$(date)"
    etcdctl get last
    echo
    echo
    jobs
    sleep 1
done

**Comment by yichengq** [comment]
Considering we can only do best-effort for it, and it is a small corner case, we have no plan to improve it now.
If you want to start a multi-member cluster, you should use static bootstrap. If you want to add new member, check the IP cautiously.
