### ISSUE TITLE
cluster initialization fails with URLs in hostname

### ISSUE THREAD

**Issue by sorah** [coreos/etcd#2123]
cluster initialization fails on the following commandline:

```
./etcd \
  --name $(hostname) \
  --listen-peer-urls "https://0.0.0.0:2380,https://0.0.0.0:7001" \
  --listen-client-urls "https://0.0.0.0:2379,https://0.0.0.0:4001" \
  --advertise-client-urls "https://$(hostname -f):2379" \
  --initial-advertise-peer-urls "https://$(hostname -f):2380" \
  --peer-ca-file=/etc/etcd/ca.crt --peer-cert-file=/etc/etcd/node.crt --peer-key-file=/etc/etcd/node.key \
  --ca-file=/etc/etcd/ca.crt --cert-file=/etc/etcd/node.crt --key-file=/etc/etcd/node.key \
  --initial-cluster-state new \
  --initial-cluster-token 'mycluster' \
  --initial-cluster 'etcd-001=https://etcd-001:2380,etcd-002=https://etcd-002:2380,etcd-003=https://etcd-003:2380'
```

```
$ ./start.sh
2015/01/22 13:14:52 netutil: Resolving etcd-001:2380 to 10.0.0.136:2380
2015/01/22 13:14:52 netutil: Resolving etcd-001:2379 to 10.0.0.136:2379
2015/01/22 13:14:52 netutil: Resolving etcd-001:2379 to 10.0.0.136:2379
2015/01/22 13:14:52 no data-dir provided, using default data-dir ./etcd-001.etcd
2015/01/22 13:14:52 etcd: peerTLS: cert = /etc/etcd/node.crt, key = /etc/etcd/node.key, ca = /etc/etcd/ca.crt
2015/01/22 13:14:53 etcd: listening for peers on https://0.0.0.0:2380
2015/01/22 13:14:54 etcd: listening for peers on https://0.0.0.0:7001
2015/01/22 13:14:54 etcd: clientTLS: cert = /etc/etcd/node.crt, key = /etc/etcd/node.key, ca = /etc/etcd/ca.crt
2015/01/22 13:14:54 etcd: listening for client requests on https://10.0.0.136:2379

2015/01/22 13:14:54 etcd: stopping listening for client requests on https://10.0.0.136:2379
2015/01/22 13:14:54 etcd: stopping listening for peers on https://0.0.0.0:7001
2015/01/22 13:14:54 etcd: stopping listening for peers on https://0.0.0.0:2380
2015/01/22 13:14:54 etcd: etcd-001 has different advertised URLs in the cluster and advertised peer URLs list
```

apurls is `[https://10.0.0.136:2380]` and `m.PeerURLs` is `[https://etcd-001:2380/]` at this point:

``` go
	if !reflect.DeepEqual(apurls, m.PeerURLs) {
		return fmt.Errorf("%s has different advertised URLs in the cluster and advertised peer URLs list", c.Name)
	}
```

I'm specifying initial-cluster url in hostname, because IP address is not fixed in our environment and etcd requires valid common name / subjectAltName validation for cluster peer URL.

Commit 705ec450830035a5d3cb4a5e9fd157ec098410a8  (#1991, #1996) is a cause of this issue... resolves `apurls`. So reverting the commit fixes the problem... but it makes issue #1991 again.

I'm planning to write a patch to make to try hostname verification with member name. Suggest me if there's better way.

**Comment by sorah** [comment]
problems:

- validate TLS certificate commonName/subjectAltName with member node's name?
- m.PeerURLs have to dns resolved too?

**Comment by sorah** [comment]
As I wrote at another pull request I'm still new to etcd, does etcd recommend to use IP address basically...?

**Comment by barakmich** [comment]
You're running into a sanity check which, as you correctly identified, has changed a little. We didn't resolve before but (and, check me on this, @xiang90) that's kind of where that's going. 

I think the right answer may be to resolve m.PeerURLs as you mentioned (and error if we cannot). Further, this starts to unify with the way DNS-SRV discovery works (which may also help your use case!)

**Comment by sorah** [comment]
Yes, resolving `m.PeerURLs` makes the check pass. as I said But it breaks hostname verification.

I can contribute a patch, but, I can't determine a way to fix (including short-term) this. as you said it's not easy to fix in the right way.
So as a short-term fix, (and to get etcd cluster in my environment,) having a commandline option for customizing TLS cert verification is my opinion... what is the detail of DNS-SRV unification?

**Comment by sorah** [comment]
To get etcd cluster on our environment, wrote a patch #2150. I don't think this is the best.

**Comment by xiang90** [comment]
@sorah I marked this as closed since we merged https://github.com/coreos/etcd/pull/2150.

**Comment by sorah** [comment]
thanks :sparkles:
