### ISSUE TITLE
Tcl Binding

### ISSUE THREAD

**Issue by efrecon** [coreos/etcd#2127]
I just wanted to let you know that I had made available an implementation of the [client API in tcl](https://github.com/efrecon/etcd-tcl). It is nearly complete and follows v2 of the API. Maybe would you like to add this to the list of existing [language bindings and tools](https://github.com/coreos/etcd/blob/master/Documentation/libraries-and-tools.md)?

**Comment by yichengq** [comment]
@efrecon Could you send a PR for this?
(Some ref if you want to do this: https://github.com/coreos/etcd/blob/master/CONTRIBUTING.md#format-of-the-commit-message)

**Comment by efrecon** [comment]
Fixed.
