### ISSUE TITLE
Getting tons of `received msgApp rejection`

### ISSUE THREAD

**Issue by mediocregopher** [coreos/etcd#2166]
We have a three node etcd cluster (2.0.0-rc.1), and at some point we started receiving tons of:

```
2015/01/27 16:00:25 raft: 512ef1c906982373 received msgApp rejection from 233a2bfca7c59d9 for index 518557273
2015/01/27 16:00:25 raft: 512ef1c906982373 received msgApp rejection from 233a2bfca7c59d9 for index 518557272
2015/01/27 16:00:25 raft: 512ef1c906982373 received msgApp rejection from 233a2bfca7c59d9 for index 518557271
2015/01/27 16:00:25 raft: 512ef1c906982373 received msgApp rejection from 233a2bfca7c59d9 for index 518557270
```

on one node, the other two being the rejectors. I searched around and tried restarting the whole cluster (which didn't work), as well as removing the problem node from the cluster using `etcdctl member remove 512ef1c906982373` on one of the "working" nodes, but that just gets back `context deadline exceeded`.

We have this cluster up for testing, so it's not mission critical to get it working right now. I can mess around with things and bring it up and down if that helps diagnose any bugs. If anyone could give me a hand I'd really appreciate it :)

**Comment by xiang90** [comment]
@mediocregopher Can you try to reproduce this current master. From log, I think one of the member was down for a long time and trying to catch up.

**Comment by mediocregopher** [comment]
I deployed a build off master to all three of the nodes, shut off etcd on all of them, then started it up with the master build. I no longer get the `received msgApp errors`, but the nodes won't full start up. They die with the message:

    2015/01/27 20:01:06 etcdserver: read wal error: wal: snapshot not found

And aren't responsive to any calls from etcdctl

**Comment by xiang90** [comment]
@mediocregopher The data format of rc1 and master has changed. You have to remove your data dir. Then you can try to reproduce the problem you met before.

**Comment by mediocregopher** [comment]
Ah, I see. Well I'll leave this running for a while then. If it hasn't re-occurred in a few days I'll close the issue. Thanks for the help!

**Comment by xiang90** [comment]
@mediocregopher Are you keeping on writing different keys into etcd for your old cluster?

**Comment by xiang90** [comment]
@mediocregopher From the log, the follower cannot catch up with the current leader. We have improved the algo a little bit for fast catch up. However, I guess the root problem might be you put a large amount of data into etcd.

**Comment by mediocregopher** [comment]
There is a process which is constantly overwriting a large-ish amount of data (the ip addresses of about 300+ hosts) every few minutes. My assumption was that this wouldn't be a huge problem, but maybe that isn't the case? Instead of overwriting I could change the script to only change values which are different than they should be.

**Comment by xiang90** [comment]
overwriting 300 keys should be fine

**Comment by mediocregopher** [comment]
I'd figured. Maybe our process got away from us when we weren't looking. I'll keep an eye on it and update this in a day or two. Thanks for your help!
