### ISSUE TITLE
initial-cluster and initial-cluster-state flags

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [coreos/etcd#2179]
This is more of a question than an issue; I suppose the "issue" would be that this info isn't clearly available in the docs.  My question is about the `--initial-cluster` and `--initial-cluster-state` flags.

My guess is that the `--initial-cluster-state=new` flag is only set on the first node of a cluster, and only one time on the initial deployment.  The `--initial-cluster` value for that first node on the first deployment should represent the cluster of nodes expected to comprise the initial deployment.  Is this correct?  This means that subsequent nodes in the initial deployment have `--initial-cluster-state=existing` and no value given for `--initial-cluster` (or rather, the value for `--initial-cluster` will be ignored).

Then, for subsequent updates to the cluster (scale up, scale down, software updates, maintenance cycles, etc.), all nodes including the first are given `--initial-cluster-state=existing` and nothing for `--initial-cluster` (i.e. `--initial-cluster` value doesn't matter and will be ignored). 

Is my understanding correct?

Now, what if instead I always had the `--initial-cluster-state=new` flag on node 1, and `--initial-cluster-state=existing` on higher nodes, even for updates to the deployed cluster?  That is, I've already bootstrapped but have the "new" flag on the first node anyways.  Will anything go wrong?  The reason I ask is I would like to automate my cluster management statelessly, so I don't need to know if the cluster is a new deployment or had already been deployed in the past.

Thanks
- Amit + @vito

**Comment by xiang90** [comment]
> Then, for subsequent updates to the cluster (scale up, scale down, software updates, maintenance cycles, etc.), all nodes including the first are given --initial-cluster-state=existing and nothing for --initial-cluster (i.e. --initial-cluster value doesn't matter and will be ignored).

This does not matters. The existing bootstrapped nodes has the data-dir. etcd can safely infer its previous state from that info.

> Now, what if instead I always had the --initial-cluster-state=new flag on node 1, and --initial-cluster-state=existing on higher nodes, even for updates to the deployed cluster? That is, I've already bootstrapped but have the "new" flag on the first node anyways. Will anything go wrong? The reason I ask is I would like to automate my cluster management statelessly, so I don't need to know if the cluster is a new deployment or had already been deployed in the past.

We suggest you to bootstrap your whole cluster statically when it is possible. 
For the first bootstrapped node, you can always use the original flag set. As I mentioned above, it does not matter. For the newly added node, you need to set `existing` and you only need to set it once. After it successfully bootstrapped, the bootstrapped related flag does not matter anymore.

**Comment by vito** [comment]
Okay, so is this correct:

1) Initial deploy of 3 nodes:
* bring up first server with `--initial-cluster-state new` and `--initial-cluster name0=http://url.0.com,name1=http://url.1.com,name2=http://url.2.com`
* add second member using `etcdctl`
* bring up second server with `--initial-cluster-state existing` and same same `--initial-cluster` as above.
* add third member using `etcdctl`
* bring up third server same as second

2) Perform rolling update of the 3-node cluster
* stop, do maintenance, and bring up each server, without `--initial-cluster-state` and `--initial-cluster` flags. **However** we could keep those flags in but they'll just be ignored because the `data-dir` is already there.

3) Roll 3 nodes **and** scale up by two more nodes
* do same as scenario 2) for the first 3 nodes
* Add member 4
* Start member 4 with "existing" and `--initial-cluster` representing what?  The original cluster of 3, or the expected cluster of 5?
* Do same for node 5 as you did for node 4

Thanks,
- Amit + @vito

**Comment by xiang90** [comment]
> Start member 4 with "existing" and --initial-cluster representing what? The original cluster of 3, or the expected cluster of 5?

The desired current configuration, which should be 4 (old 3 ones + this new one).

**Comment by robszumski** [comment]
I'm seeing a few docs enhancements coming out of this conversation:

1. Make it clear that `-initial-cluster` should always contain the latest desired state of the cluster (new node + any existing nodes).
2. Expand the description about `new` vs `existing`. If you attempt to use the wrong value, etcd will refuse to start, but we should mention that those checks exist, so a user can expect it.
3. Sort of unrelated, but modify the order of some sections in `runtime-configuration.md` to make it easier to understand.

**Comment by xiang90** [comment]
@Amit-PivotalLabs @vito @robszumski It would be great if you can help to improve the doc and send pull request.

**Comment by yichengq** [comment]
@vito 

> 1) Initial deploy of 3 nodes:
bring up first server with --initial-cluster-state new and --initial-cluster name0=http://url.0.com,name1=http://url.1.com,name2=http://url.2.com
add second member using etcdctl
bring up second server with --initial-cluster-state existing and same same --initial-cluster as above.
add third member using etcdctl
bring up third server same as second

You don't need to use etcdctl in this case. Give the binary the same initial-cluster and initial-cluster-state=new is fine. It is a static bootstraping process. More docs:
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static


> 3) Roll 3 nodes and scale up by two more nodes
do same as scenario 2) for the first 3 nodes
Add member 4
Start member 4 with "existing" and --initial-cluster representing what? The original cluster of 3, or the expected cluster of 5?

Use the four-member cluster for -initial-cluster and existing. Check the runtim reconfig here: https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md

**Comment by Amit-PivotalLabs** [comment]
@yichengq @xiang90 @robszumski Thanks for all the help so far.  I'm going to play around and see if I can get something working, that can scale up, down, deal with temporary loss of a node, etc, and then submit a PR documenting the workflow.

One question I have is: What are the pros and cons of the static bootstrap configuration vs. the runtime reconfiguration?  Please let me know if this understanding is correct.  Static bootstrapping allows you to bring up `n` nodes in parallel rather than serially, so you don't have to wait for quorum to be reached after each node.  However, static bootstrapping only works on the initial deploy of the cluster, and does not apply to any modifications of the cluster after that.

On the other hand, runtime reconfiguration seems more general.  One could "bootstrap" an initial cluster of, say, 3 nodes by only bootstrapping the first one as follows:

`etcd -name infra1 -initial-advertise-peer-urls http://10.0.1.11:2380 \
  -listen-peer-urls http://10.0.1.11:2380 \
  -initial-cluster infra1=http://10.0.1.11:2380 \
  -initial-cluster-state new`

And then bringing up the second one as a runtime reconfiguration as follows:

`etcdctl -C https://10.0.1.11:2380 member add infra2 http://10.0.1.12:2380
etcd -name infra2 -initial-advertise-peer-urls http://10.0.1.12:2380 \
  -listen-peer-urls http://10.0.1.12:2380
  -initial-cluster infra1=http://10.0.1.11:2380,infra2=http://10.0.1.12:2380 \
  -initial-cluster-state existing`

And the third:

`etcdctl -C http://10.0.1.11:2380,http://10.0.1.12:2380 member add infra3 http://10.0.1.13:2380
etcd -name infra3 -initial-advertise-peer-urls http://10.0.1.13:2380 \
  -listen-peer-urls http://10.0.1.13:2380
  -initial-cluster infra1=http://10.0.1.11:2380,infra2=http://10.0.1.12:2380,infra3=http://10.0.1.13:2380 \
  -initial-cluster-state existing`

**Comment by Amit-PivotalLabs** [comment]
To give a bit more context, we need to be able to deploy etcd clusters in a fully automated way without human intervention, and our tooling is best suited to software that can be deployed and configured idempotently.  In particular, it's not ideal to have different config/setup for the first time deploy versus subsequent deploys.  We also do a lot of subsequent deploys, mostly keeping software up to date, and also scaling up/down (although the etcd clusters we deploy often don't change much in size), so we would probably want to optimize for the runtime reconfiguration case rather than the static set-it-and-forget-it case.

**Comment by xiang90** [comment]
> Please let me know if this understanding is correct. Static bootstrapping allows you to bring up n nodes in parallel rather than serially, so you don't have to wait for quorum to be reached after each node. 

Correct.

> However, static bootstrapping only works on the initial deploy of the cluster, and does not apply to any modifications of the cluster after that.

No. You still can do runtime configuration even if the cluster is statically bootstrapped. Bootstrap and configuration are two separate thing.

**Comment by xiang90** [comment]
> In particular, it's not ideal to have different config/setup for the first time deploy versus subsequent deploys. We also do a lot of subsequent deploys, mostly keeping software up to date, and also scaling up/down (although the etcd clusters we deploy often don't change much in size), so we would probably want to optimize for the runtime reconfiguration case rather than the static set-it-and-forget-it case.

We suggest you to bootstrap the first cluster by using static bootstrap if you can. 
Of course, you can statically bootstrap a one member cluster.

You can replace dead machine, increase/decrease cluster size by using runtime configuration.

**Comment by robszumski** [comment]
@Amit-PivotalLabs Would you mind taking a look at the changed introduced in #2191 and #2193? Do those help address your questions?

**Comment by Amit-PivotalLabs** [comment]
@robszumski Those doc changes are helpful, thanks!  We're working on being able to describe an automated workflow that handles initial deploy, scale up, scale down, and rolling update.  Once we have something that works we'll submit a PR to the docs.

**Comment by xiang90** [comment]
@Amit-PivotalLabs One thing we want to emphasis is that scale up,down comes with a cost. Normally you do not want to do that expect the initial setup phase.

**Comment by Amit-PivotalLabs** [comment]
@xiang90 Realistically, we're going to want to deploy an etcd cluster that our own stuff (Cloud Foundry) relies on.  A deployment may be around for years, and over time, there may be reason to scale the cluster up or down.  It will be quite infrequent, but it could happen.  For instance, if we add more availability zones in the form of hardware clusters, we'll want an etcd node on that cluster for increased fault tolerance.

Could you expand on what the costs/risks are of scaling up or down?  Aside from the work of having to actually issue the commands to do this, the docs aren't clear about any additional risks.  If there are any, they should be emphasized in the docs.

**Comment by xiang90** [comment]
@Amit-PivotalLabs etcd is a replicated system. When you add a new member to it, the leader will try to replicate *ALL* data to the new member. If you have a large data, then the system might suffer from it. Internally, replicating the whole data *might* involve a lot of burst CPU/io work. We will try to optimize etcd for the normal operation, thus we might decide to do lazy snapshotting. 

We have not done this kind of work yet. But I just want to say etcd is not suitable for frequent scaling up and down.

**Comment by Amit-PivotalLabs** [comment]
Yep, we're aware.  We've seen the doc about the case where you want to
migrate the data dir if the size of the data is very large (~50Mb).  We
don't put a ton of data in etcd, so we're not worried about this case, but
know that as we run more containers we'll have to deal with this.  We may
shard data across multiple etcd clusters at that point if necessary.  At
any rate, we'll cross that bridge when we come to it, but thanks for the
heads up.

**Comment by Amit-PivotalLabs** [comment]
Hey @xiang90 @robszumski, we have a nice set of automation now that handles initial deploy in both single-instance and clustered mode, rolling upgrades, scale up, scale down, and restart after unexpected node failure.  Given your recent changes to the docs, I think it's all pretty well covered, not much we can add.  Thanks for all the help!

**Comment by robszumski** [comment]
Thanks for the update. Sounds like that would make an awesome blog post!

**Comment by Amit-PivotalLabs** [comment]
Hmm, still not stable actually, will keep banging on it next week.

**Comment by cuiyuan** [comment]
If an old node restart , --initial-cluster-state should be new or existing? 
I tried, both can work, why?
