### ISSUE TITLE
"wal: snapshot not found" on upgrade from 2.0-rc.1 to 2.0

### ISSUE THREAD

**Issue by tjdett** [coreos/etcd#2182]
When restarting etcd after an upgrade from 2.0-rc.1 to 2.0, etcd does not start, and fails with the following log output:
```
etcdserver: discovery token ignored since a cluster has already been initialized. Valid log found at "/var/lib/etcd/wal"
etcdserver: recovered store from snapshot at index 3630363
etcdserver: name = <redacted>
etcdserver: data dir = /var/lib/etcd
etcdserver: heartbeat = 100ms
etcdserver: election = 500ms
etcdserver: snapshot count = 10000
etcdserver: discovery URL= <redacted>
etcdserver: advertise client URLs = <redacted>
etcdserver: loaded cluster information from store: <redacted>
etcdserver: read wal error: wal: snapshot not found
```

The server is able to start again after a rolling back to 2.0-rc.1.

**Comment by xiang90** [comment]
@tjdett We only support upgrade from 0.4.x releases to 2.0 release. There might be issues when you try to upgrade the cluster from 0.5.x/2.0.rc -> 2.0. 

Can you try to use etcd-backup tool to back up the cluster first, then to force restart a new cluster if the data is important to you?

/cc @yichengq

**Comment by yichengq** [comment]
@tjdett PR sent to make it work.
You can check https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery and make it workable.

**Comment by tjdett** [comment]
After repeated attempts, I was unable to get `-force-new-cluster` to rewrite the data dir in a way that 2.0.0 could restart and not see the previous cluster members when loading "cluster information from store". etcd 2.0.0 would then panic.

The `201` branch would start fine despite seeing the old cluster members.

My data can be regenerated, so at this point it's less effort to rebuild the cluster and data from scratch on 2.0.0 and recover.

Hopefully the upgrade to 2.0.1 isn't similarly painful.

**Comment by yichengq** [comment]
@tjdett 
> The 201 branch would start fine despite seeing the old cluster members.

I start one member, force-new-cluster and restart it. It seems to work fine. When rebooting, it should see nothing but itself in the cluster. It will add original members back first, and then remove them in sequence.

The upgrade to later version will be smooth. :)
