### ISSUE TITLE
etcd API Backward Compatibility

### ISSUE THREAD

**Issue by AdoHe** [coreos/etcd#2223]
I tested etcd 2.0 yesterday, and just found a little bit problem: when you call `curl -L http://127.0.0.1:4001/v2/keys/` within etcd 0.4.6, you will get such response: `{"action":"get","node":{"key":"/","dir":true}}`, but with the same call in etcd 2.0, you will get different response: `{"errorCode":100,"message":"Key not found","index":2}`, it seems there is no way to fetch all the keys in etcd. I don't whether this is right or not.

**Comment by yichengq** [comment]
I think this is a bug. Will fix.

**Comment by AdoHe** [comment]
yes, if any possible, i would like to help :)

**Comment by xiang90** [comment]
@AdoHe I think we forget to create the root after creating the store.

**Comment by AdoHe** [comment]
@xiang90 I will look into this, and try to fix this issue...

**Comment by xiang90** [comment]
@AdoHe Thanks!

**Comment by AdoHe** [comment]
@yichengq  Great, I have tested this, and it just works. thanks :+1:

**Comment by yichengq** [comment]
@AdoHe We used to map '/' in the store to '/v2/keys/' at the key space. '/' is created at the beginning, and is set read-only.
For internal reason, we now map '/1/' in the store to '/v2/keys/' at the key space. And we didn't do the special setting for that path in the store. So it is not correct.
Thanks for reporting and help.

**Comment by AdoHe** [comment]
@yichengq yes, I saw the source code, and did compare this with 0.4.6, it's exactly what you said. There is another problem I don't know how you think about: you know in etcd 0.4.6 the dashboard module is deprecated temporarily due to its unstable state, and in the new released etcd 2.0.0 this module was totally removed, just etcdctl left. Personally I think this module is very important and quite user friendly, at least in our company people are more willing to use dashboard, recently I did do something with the old dashboard module, pulled it away from the entire etcd project, and made a new project https://github.com/AdoHe/etcd-dashboard, I want to know whether you will add this module to the etcd again?

**Comment by philips** [comment]
@AdoHe I would be happy to start compiling a new release binary called "etcd-dashboard" if you want to help out with that.

**Comment by philips** [comment]
@AdoHe Ideally it would be a standalone go binary like the old dashboard and you would just specify the host/port on the CLI the etcd client.

**Comment by AdoHe** [comment]
@philips sure I would like to help with this, and I will start this.

**Comment by AdoHe** [comment]
@philips I just add this repository: https://github.com/AdoHe/etcd-dashboard you may have a look...

**Comment by xiang90** [comment]
@AdoHe Do you have a QQ number? Or any instant message account we can discuss about it?

**Comment by AdoHe** [comment]
@xiang90 of course I use QQ, and my QQ number is 2584691618, you can add me, so we can discuss about it. :)

**Comment by AdoHe** [comment]
@xiang90 have you found me on QQ?
