### ISSUE TITLE
check -xxx-urls flags has correct scheme setting

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2234]
When tls info is given in the flag set, urls should be `https` instead of `http`.
It helps improve the user experiences.

**Comment by xiang90** [comment]
This has been fixed by https://github.com/coreos/etcd/pull/2456?

**Comment by yichengq** [comment]
This is another case needed to be fixed. If user gives the tls info and 'http' urls, etcd should warn that 'https' is recommended.

**Comment by xiang90** [comment]
ok. sure. but in that case shall we stop as an error instead of just warning? 

/cc @kelseyhightower @barakmich

**Comment by yichengq** [comment]
fixed by #3134
