### ISSUE TITLE
Watcher returns index number smaller than the parameter 'waitIndex'

### ISSUE THREAD

**Issue by snowdreamist** [coreos/etcd#2246]
Hi, all
I'm just developing a python module to 'sync directory' between python objects and etcd directory by __watching__ and I found some strange behaviours.
My etcd version is 2.0.0 (internal version 2) and only 1 node in etcd cluster
Here's my log (from requests):
* "__GET__ /v2/keys/fs_synctest?waitIndex=__669__&recursive=True&wait=True HTTP/1.1" 200 None
* "__PUT__ /v2/keys/fs_synctest/file1 HTTP/1.1" 200 261
*  The first request response: {"action":"set","node":{"key":"/fs_synctest/file1","value":"value1","expiration":"2015-02-06T11:44:05.835401286Z","ttl":120,"modifiedIndex":__669__,"createdIndex":__669__},"prevNode":{"key":"/fs_synctest/file1","value":"value1","modifiedIndex":659,"createdIndex":659}} {'transfer-encoding': 'chunked', 'x-raft-index': '166876', 'x-raft-term': '5', '__x-etcd-index__': '__668__', 'date': 'Fri, 06 Feb 2015 11:42:05 GMT', 'content-type': 'application/json', 'x-etcd-cluster-id': '7e27652122e8b2ae'}

hmm, I'm expecting the x-etcd-index to be __669__ in order to continue watching from this index after update this delta data.

So, am I making anything wrong? :)

**Comment by yichengq** [comment]
'x-etcd-index' for wait action is the index of etcd store at the time that watch starts.
you can use the latest modifiedindex to do next watching.

**Comment by snowdreamist** [comment]
All right, I got it.
The document is quite misleading:
"The X-Etcd-Index is important. It is the index when we got the value of /foo. So we can watch again from the (X-Etcd-Index + 1) without missing an event after the last get."
I didn't realize the behavior of 'x-etcd-index' is different between get value and watch for changes.

Thanks for reply, I'll fix this in my service.

**Comment by yichengq** [comment]
@snowdreamist We are fixing the doc in this PR: https://github.com/coreos/etcd/pull/3128 Feel free to review and comment.

**Comment by yichengq** [comment]
Have clarified confusing points in #3128 . Feel free to comment if it is still a problem.
