### ISSUE TITLE
Local Discovery Documentation Setup.

### ISSUE THREAD

**Issue by Johnz86** [coreos/etcd#2247]
Hi, I have a problem with setting up of a local cluster discovery.

I am using 3 coreos vagrant machines to test this out. And I tried to follow the etcd documentation. Unfortunately it describes only how to this with commands and not with unit files in the vagrant setup.  So I was thinking, that I will try to test out at least the static discovery described in etcd documentation. It did not work for me.

When I called the commands described in Procfile:

```
etcd -name infra1 -listen-client-urls http://127.0.0.1:4001 -advertise-client-urls http://127.0.0.1:4001 -listen-peer-urls http://127.0.0.1:7001 -initial-advertise-peer-urls http://127.0.0.1:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://127.0.0.1:7001,infra2=http://127.0.0.1:7002,infra3=http://127.0.0.1:7003' -initial-cluster-state new
````
I got 
```
flag provided but not defined: -listen-client-urls
```
I tried to set up Vagrant machine with:
```
curl -X PUT http://172.17.8.101:4001/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/_config/size -d value=3
```
And then configure the cloud init to:
````
coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    # WARNING: replace each time you 'vagrant destroy'
    discovery: http://172.17.8.101:7001/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/
````
But it did not work.

How can I configure local discovery on the coreos? What am I doing wrongly with the static setup?

Thanks

Jan.

**Comment by yichengq** [comment]
> flag provided but not defined: -listen-client-urls
I think you are using v0.4.6 etcd. Could you check the version of etcd?

> But it did not work.
The master documentation is for etcd v2.0. The v0.4 etcd is at https://github.com/coreos/etcd/tree/v0.4.6/Documentation

Moreover, could you provide the output log of failed etcd?

**Comment by Johnz86** [comment]
You are right. When I queried port 7001.
```
curl -L http://127.0.0.1:7001/version
```
I got a  response.
```
2
```
But when I queried the port 4001.
```
curl -L http://127.0.0.1:4001/version
```
I got response.
```
etcd 0.4.6
```
When I looked into older documentation, I got the right responses.

Thanks.

**Comment by yichengq** [comment]
That endpoint is an internal one. Glad to see it is solved.
