### ISSUE TITLE
32-bit build fails to create new db

### ISSUE THREAD

**Issue by onechip** [coreos/etcd#2248]
I've tried cross compiling from a linux-amd64 host to linux-386, linux-arm and freebsd-386.  The build works but the resulting binary has a problem.  It appears to be the same problem with all 3 platforms.  The common element is 32-bit build.

On first run, there is a "panic: runtime error: invalid memory address or nil pointer dereference", but a new data dir is created.  On second run I get a stream of "etcdserver: publish error: etcdserver: request timed out".  

This is with both the v2.0.0 release and with HEAD as it was when this issue was posted.

It appears to me as though issue https://github.com/golang/go/issues/6404 may apply.  Some 64-bit integer may be improperly aligned within its structure.

**Comment by xiang90** [comment]
@onechip see https://github.com/coreos/etcd#32-bit-systems. We do not support 32bit well at the moment.

**Comment by onechip** [comment]
Log extract (first run):
...
2015/02/06 12:06:50 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e27652122e8b2ae
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x80c7ddb]

goroutine 22 [running]:
runtime.panic(0x834c900, 0x854f633)
        /usr/lib/go/src/pkg/runtime/panic.c:279 +0xe9
sync/atomic.StoreUint64(0x1873453c, 0x1, 0x0)
        /usr/lib/go/src/pkg/sync/atomic/asm_386.s:196 +0xb
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0x18734510, 0x1871ae10, 0x1, 0x1, 0x18760220, 0x0, 0x0, 0x0)
        /home/ardev/etcd/etcd-github/gopath/src/github.com/coreos/etcd/etcdserver/server.go:679 +0x1f7
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0x18734510)
        /home/ardev/etcd/etcd-github/gopath/src/github.com/coreos/etcd/etcdserver/server.go:405 +0xb29
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
        /home/ardev/etcd/etcd-github/gopath/src/github.com/coreos/etcd/etcdserver/server.go:288 +0x19a
...
