### ISSUE TITLE
Problems with connecting to etcd 2.0 that runs in a docker container

### ISSUE THREAD

**Issue by ArtfulCoder** [coreos/etcd#2253]
I have been following this online page to run etcd in a container.
https://coreos.com/blog/Running-etcd-in-Containers/
The page talks about running etcd:0.4.6 in a container and it works.

When I tried doing this with etcd 2.0.0, the etcd service seems to start up but I am unable to connect to it via etcdctl.

(The docker images used below are hosted on dockerhub and are public)
------------- etcd 0.4.6 steps ----------------
The following command starts etcd 0.4.6 in docker, and works. I can connect to it with etcdctl.
>docker run   -p 4001:4001  kubernetes/etcd:0.4.6 /usr/local/bin/etcd   -name abhi-master   -addr `hostname -i`:4001

> docker exec {container-id-that-just-started} /usr/local/bin/etcdctl -C="http://localhost:4001" ls
(this works)

------------- etcd 2.0.0 steps ---------------- 
The following command starts etcd 2.0.0 in docker, but can't connect to it via etcdctl.
> docker run   -p 4001:4001  kubernetes/etcd:2.0.0 /usr/local/bin/etcd  --addr `hostname -i`:4001 

> docker exec {container-id-that-just-started} /usr/local/bin/etcdctl -C="http://localhost:4001" ls
Error: 501:  All the given peers are not reachable (Tried to connect to each peer twice and failed)[0]

cc @dchen1107 @thockin

**Comment by xiang90** [comment]
@ArtfulCoder The default listen addr of 2.0 is localhost instead of 0.0.0.0. I think this might be the root cause.

**Comment by ArtfulCoder** [comment]
I did try to connect to localhost using etcdctl within the container using "docker exec", but that did not resolve it.

**Comment by yichengq** [comment]
I think this is because etcd 2.0 doesn't do backward compatibility well.
The fix is #2271 . Could you check whether it works for you?

**Comment by ArtfulCoder** [comment]
It seems that when I build using the build script, the generated etcd file is dynamically linked.
Can you verify that etcd is being statically linked.
There is an explicit comment in the build file that says that etcd is being statically linked. But that does not seem to be the case.
@alban

**Comment by denisura** [comment]
etcd 2.0 uses port 2379 and 2380 (as opposed to etcd 0.4.6 which used 4001 and 7001.)

**Comment by yichengq** [comment]
Does it work now?

**Comment by thockin** [comment]
We're still wrestling with it - can someone @coreOS post a canonical
'docker run' command that runs etcd 2.0 in a container and open a host port
that I can then connect to via etcdctl?

I am sure I am missing something simple

**Comment by kelseyhightower** [comment]
@thockin I'm running through this now.

**Comment by kelseyhightower** [comment]
@thockin See the etcd docker guide for working `docker run` commands for single, and multi-node etcd setups.
