### ISSUE TITLE
Choose endpoints intelligently

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#2254]
As of https://github.com/coreos/etcd/commit/7d172bb1142eee5ee3bb6b2b4f08e2390217e01f etcd/client.Client round-robins across all given endpoints. This is not ideal. The client should pin itself to a given endpoint until that endpoint becomes unhealthy. The endpoint should be chosen randomly in order to achieve a pseudo-random distribution of all clients across the cluster's members.

**Comment by yichengq** [comment]
Some good advice from @andrewnicols : https://github.com/coreos/etcd/issues/2549#issuecomment-84753442

**Comment by yichengq** [comment]
The client could pin itself to a given endpoint until that endpoint becomes unhealthy or there is cluster change.

The client will randomly connect to a member when reset, but it cannot achieve a pseudo-random distribution of all clients across the cluster's members under all cases, e.g., server restart, add member. We don't see users meet the problem of server overload today, and don't know how to address it best. So I would collect more feedback and tackle the problem in the future.
