### ISSUE TITLE
Remove go-etcd

### ISSUE THREAD

**Issue by bcwaldon** [coreos/etcd#2258]
As of https://github.com/coreos/etcd/commit/7d172bb1142eee5ee3bb6b2b4f08e2390217e01f, etcdctl uses the etcd/client pkg and github.com/coreos/go-etcd. The official etcd/client pkg needs to be rich enough to drive all of etcdctl, and go-etcd needs to be removed from etcd altogether.

**Comment by philips** [comment]
@xiang90 We talked about adding this to the v2.1.0 milestone. But we need to consider #2604 too.

**Comment by yichengq** [comment]
progress at #2913

**Comment by xiang90** [comment]
Fixed by #3083
