### ISSUE TITLE
etcd cluster in an inconsistent state

### ISSUE THREAD

**Issue by onsi** [coreos/etcd#2265]
We have an etcd 2.0 cluster comprised of 3 nodes: A, B, and C

A, B, and C all agree that C is the leader.

The cluster is accepting writes.

Despite this, the components of our distributed system that consume etcd are seeing two *different* (i.e. inconsistent) views of the key-value store.  We've configured our go-etcd client with STRONG_CONSISTENCY and we pass all members of the cluster to the client.  We restarted one of our components repeatedly and saw that it would flip flop between which of the two states it saw.  Digging further it looks like the go-etcd client randomly picks a cluster member to communicate with.  If it picks A it sees one view of the store.  If it picks B or C it sees the other.

Further exploration with curl revealed the same thing.  If we perform a GET against A we get one view of the store.  If we GET from B or C we see the other view of the store.  This is true even if we set `quorum=true`.

Curiously, if we run `etcdctl ls` locally on each etcd node we see a single consistent view of the world (interestingly, it is always As view).  If we run etcdctl with `-no-sync` we always get the inconsistent result (`etcdctl -no-sync` on A always returns A's picture of the world, whereas `etcdctl -no-sync` on B/C always returns B/C's view of the world).  We tried calling go-etcd's `SyncCluster` method in our own client but still did not manage to get the kind of consistency we see with `etcdctl`.

But... regardless of all that noise about clients.  It seems very strange that:

- A never catches up with B/C
- etcdctl favors A's view of the world over B/C even though *C* is the leader!

We've uploaded the snap and wal directories, along with the output logs to http://onsi-public.s3.amazonaws.com/etcd_snap_wal_logs.tar

We're going to need to scrap our etcds soon and bring our environment back afresh -- let me know if there's anything you want me to try before doing that.

**Comment by onsi** [comment]
It's worth adding: *new* writes propagate correctly to all members in the cluster even when we write to individual members of the cluster/read from individual members of the cluster with curl.

**Comment by xiang90** [comment]
@onsi Can you give me an example of inconsistency? Thanks

**Comment by xiang90** [comment]
@onsi For example, what is the request you sent via curl and what is the response?

**Comment by onsi** [comment]
Thanks @xiang90 here's a gist:
https://gist.github.com/onsi/38b0cbcd942c3cf674ac

**Comment by xiang90** [comment]
@onsi Is it a fresh etcd 2.0 cluster? Or it was upgraded from 0.4.x?

**Comment by xiang90** [comment]
@onsi By examining at the log and snapshot, I found the log are the same but the snapshot was broken. We have just found a bug in the snapshot generation, and it probably caused by that. 

Can you please confirm that:
1. you were doing compare and swap by index.
2. node A was down for a while and then brought up again.

If both 1 and 2 are true, then it is probably the case. And we will release 2.0.1 soon, which includes the fix.

**Comment by onsi** [comment]
It as a fresh install, not an upgrade.

We perform CAS by index all over the place so it's likely.  Not sure if A
was down for a while or not but it may have been...

**Comment by onsi** [comment]
OK thanks @xiang90 -- any eta on 2.0.1?

I'm going to go ahead and nuke that environment and (maybe) scale down to 1 instance to be safe.

**Comment by xiang90** [comment]
@onsi Hopefully this week.

**Comment by onsi** [comment]
Will close this for now and reopen if we see the issue again.

**Comment by xiang90** [comment]
@onsi We have the bug fix in the current master. We will release the binary with the fix soon.

**Comment by onsi** [comment]
oh so it was not in 2.0.1? will reopen this then...

**Comment by xiang90** [comment]
@onsi 2.0.2 is released
