### ISSUE TITLE
/v2/members gives 404 (called by etcd.SetCluster())

### ISSUE THREAD

**Issue by hkjn** [coreos/etcd#2273]
Hi,

I was having issues with the go-etcd library's `etcd.SetCluster()` on CoreOS - I've traced it to the following line, which sends `GET [etcd peer]/v2/members`:
https://github.com/coreos/go-etcd/blob/master/etcd/client.go#L301

Testing manually, `curl -L http://127.0.0.1:4001/v2/members` gives 404 directly in the CoreOS host.

The cluster is fine as far as I can tell; I can write and read values to etcd both using `curl` and `go-etcd`. I can replicate this behavior both on a physical machine cluster and a GCE test cluster (etcd version is 0.4.6 in both cases). 

Since I was not clear whether this is a bug in the go-etcd package (expecting a path that doesn't exist) or in etcd itself (not publishing a HTTP resource it should be publishing) I'm filing the bug here for now; please let me know if it should go against go-etcd instead.

I found this when trying to debug why the confd package gave an error, which turned out to be when it called `etcd.SetCluster()`:
https://github.com/kelseyhightower/confd/blob/7f5790fe1982d412bc87f29b038a252fe4d846c3/backends/etcd/etcdutil/client.go#L34

**Comment by xiang90** [comment]
@hkjn Please use go-etcd client library for 0.4.6 at https://github.com/coreos/go-etcd/tree/v0.4.6. The master uses etcd 2.0 api.

**Comment by hkjn** [comment]
Ah, thanks xiang90, sounds like this is a bug with confd's version of go-etcd then, I'll open a bug over there.

Cheers!
