### ISSUE TITLE
Cluster run time membership change

### ISSUE THREAD

**Issue by aaskey** [coreos/etcd#2285]
Hi there,

I was following the member API to do cluster membership run time change:

https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#post-v2members

I started a 3-node cluster, then remove one node from the cluster using the command below:
$ curl http://127.0.0.1:4002/v2/members/272e204152 -XDELETE

This command worked well, now the cluster is left with 2-node:

$ curl http://127.0.0.1:4002/v2/members

{"members":[{"id":"c3fc3f283aab4cc7","name":"E31C0801","peerURLs":["http://127.0.0.1:7004"],"clientURLs":["http://127.0.0.1:4004"]},{"id":"d653b2ec69ce607c","name":"E31C0802","peerURLs":["http://127.0.0.1:7002"],"clientURLs":["http://127.0.0.1:4002"]}]}

I was trying to add this member back to the cluster. First, I issued a POST request, 

$ curl http://127.0.0.1:4002/v2/members -XPOST -H "Content-Type: application/json" -d '{"peerURLs":["http://127.0.0.1:7003"]}'

{"message":"etcdserver: peerURL exists"}

Then, I issued the the same command which I used to add the original node to the 3-node cluster. However, I got the following error:

...

2015/02/11 14:18:12 raft: 8d4d400c2fde2262 is starting a new election at term 14

2015/02/11 14:18:12 raft: 8d4d400c2fde2262 became candidate at term 15

2015/02/11 14:18:12 raft: 8d4d400c2fde2262 received vote from 8d4d400c2fde2262 at term 15

2015/02/11 14:18:12 raft: 8d4d400c2fde2262 [logterm: 10, index: 312] sent vote request to c3fc3f283aab4cc7 at term 15

2015/02/11 14:18:12 raft: 8d4d400c2fde2262 [logterm: 10, index: 312] sent vote request to d653b2ec69ce607c at term 15

2015/02/11 14:18:12 etcdserver: reject message from removed member 8d4d400c2fde2262

2015/02/11 14:18:12 etcdserver: reject message from removed member 8d4d400c2fde2262

2015/02/11 14:18:12 etcdserver: the member has been permanently removed from the cluster

2015/02/11 14:18:12 etcdserver: the data-dir used by this member must be removed.

2015/02/11 14:18:12 sender: error posting to 1411fafa70abeff8: dial tcp 127.0.0.1:7003: connection refused

2015/02/11 14:18:12 sender: the connection with 1411fafa70abeff8 becomes inactive

What procedure should I follow to add a previously removed node back to a cluster?

Thanks,

Ken

**Comment by xiang90** [comment]
@aaskey I have tried on the current master. And I cannot reproduce your problem. It is fine to add back a removed member. I guess you added it twice for some reason.

Here is what I have tried:
```
$ ./etcdctl member list
6e3bd23ae5f1eae0: name=infra2 peerURLs=http://localhost:7002 clientURLs=http://localhost:4002
924e2e83e93f2560: name=infra3 peerURLs=http://localhost:7003 clientURLs=http://localhost:4003
a8266ecf031671f3: name=infra1 peerURLs=http://localhost:7001 clientURLs=http://localhost:4001

$ ./etcdctl member remove 924e2e83e93f2560
Removed member 924e2e83e93f2560 from cluster

$ ./etcdctl member add infra3 http://localhost:7003
Added member named infra3 with ID f1bc9676b955be7f to cluster

ETCD_NAME="infra3"
ETCD_INITIAL_CLUSTER="infra2=http://localhost:7002,infra1=http://localhost:7001,infra3=http://localhost:7003"
ETCD_INITIAL_CLUSTER_STATE="existing"
```

**Comment by xiang90** [comment]
@aaskey 
I suggest you to retry again. 
If you still have a problem to add back a removed member, please provide *ALL* the steps you do and the logs etcd generates.

**Comment by aaskey** [comment]
Here is the procedure I used:

1. Create a 3-node cluster (Note: All nodes are running on the same machine, this might be different from your environment)
etcd -listen-peer-urls http://127.0.0.1:7004 -initial-advertise-peer-urls http://127.0.0.1:7004 -listen-client-urls http://127.0.0.1:4004 -advertise-client-urls http://127.0.0.1:4004 -initial-cluster E31C0801=http://127.0.0.1:7004,E31C0802=http://127.0.0.1:7002,E31C0803=http://127.0.0.1:7003 -initial-cluster-state new -initial-cluster-token CoolDog -data-dir /Users/u875/machines/E31C0801 -name E31C0801 &

etcd -listen-peer-urls http://127.0.0.1:7002 -initial-advertise-peer-urls http://127.0.0.1:7002 -listen-client-urls http://127.0.0.1:4002 -advertise-client-urls http://127.0.0.1:4002 -initial-cluster E31C0801=http://127.0.0.1:7004,E31C0802=http://127.0.0.1:7002,E31C0803=http://127.0.0.1:7003 -initial-cluster-state new -initial-cluster-token CoolDog -data-dir /Users/u875/machines/E31C0802 -name E31C0802 & 

etcd -listen-peer-urls http://127.0.0.1:7003 -initial-advertise-peer-urls http://127.0.0.1:7003 -listen-client-urls http://127.0.0.1:4003 -advertise-client-urls http://127.0.0.1:4003 -initial-cluster E31C0801=http://127.0.0.1:7004,E31C0802=http://127.0.0.1:7002,E31C0803=http://127.0.0.1:7003 -initial-cluster-state new -initial-cluster-token CoolDog -data-dir /Users/u875/machines/E31C0803 -name E31C0803 &

$ curl http://127.0.0.1:4002/v2/members
{"members":[{"id":"1411fafa70abeff8","name":"","peerURLs":["http://127.0.0.1:7003"],"clientURLs":[]},{"id":"c3fc3f283aab4cc7","name":"E31C0801","peerURLs":["http://127.0.0.1:7004"],"clientURLs":["http://127.0.0.1:4004"]},{"id":"d653b2ec69ce607c","name":"E31C0802","peerURLs":["http://127.0.0.1:7002"],"clientURLs":["http://127.0.0.1:4002"]}]}

2. Remove one node from the cluster
$ curl http://127.0.0.1:4002/v2/members/1411fafa70abeff8 -XDELETE
2015/02/11 16:26:27 etcdserver: removed member 1411fafa70abeff8 from cluster df859bb50b3303e
2015/02/11 16:26:27 etcdserver: removed member 1411fafa70abeff8 from cluster df859bb50b3303e

$ curl http://127.0.0.1:4002/v2/members
{"members":[{"id":"c3fc3f283aab4cc7","name":"E31C0801","peerURLs":["http://127.0.0.1:7004"],"clientURLs":["http://127.0.0.1:4004"]},{"id":"d653b2ec69ce607c","name":"E31C0802","peerURLs":["http://127.0.0.1:7002"],"clientURLs":["http://127.0.0.1:4002"]}]}

3. Now only two etcd instances are running.

u8             1962   0.4  0.1 145182052   9804 s001  S     4:22PM   0:01.90 etcd -listen-peer-urls http://127.0.0.1:7002 -initial-advertise-peer-urls http://127.0.0.1:7002 -listen-client-urls http://127.0.0.1:4002 -advertise-client-urls http://127.0.0.1:4002 -initial-cluster E31C0801=http://127.0.0.1:7004,E31C0802=http://127.0.0.1:7002,E31C0803=http://127.0.0.1:7003 -initial-cluster-state new -initial-cluster-token CoolDog -data-dir /Users/u875/machines/E31C0802 -name E31C0802

u8             1961   0.4  0.1 145185148   9752 s001  S     4:22PM   0:03.07 etcd -listen-peer-urls http://127.0.0.1:7004 -initial-advertise-peer-urls http://127.0.0.1:7004 -listen-client-urls http://127.0.0.1:4004 -advertise-client-urls http://127.0.0.1:4004 -initial-cluster E31C0801=http://127.0.0.1:7004,E31C0802=http://127.0.0.1:7002,E31C0803=http://127.0.0.1:7003 -initial-cluster-state new -initial-cluster-token CoolDog -data-dir /Users/u875/machines/E31C0801 -name E31C0801 

4. Add the node back
$ curl http://127.0.0.1:4002/v2/members -XPOST -H "Content-Type: application/json" -d '{"peerURLs":["http://127.0.0.1:7003"]}'
2015/02/11 16:31:12 etcdserver: added member c91f5fe0a6fcdad0 [http://127.0.0.1:7003] to cluster df859bb50b3303e
2015/02/11 16:31:12 sender: error posting to c91f5fe0a6fcdad0: dial tcp 127.0.0.1:7003: connection refused
2015/02/11 16:31:12 sender: the connection with c91f5fe0a6fcdad0 becomes inactive
2015/02/11 16:31:12 etcdserver: added member c91f5fe0a6fcdad0 [http://127.0.0.1:7003] to cluster df859bb50b3303e
{"id":"c91f5fe0a6fcdad0","name":"","peerURLs":["http://127.0.0.1:7003"],"clientURLs":[]}

5. Now members shows there are 3 nodes, but in reality there are only 2 instances running.  
$ curl http://127.0.0.1:4002/v2/members
{"members":[{"id":"c3fc3f283aab4cc7","name":"E31C0801","peerURLs":["http://127.0.0.1:7004"],"clientURLs":["http://127.0.0.1:4004"]},{"id":"c91f5fe0a6fcdad0","name":"","peerURLs":["http://127.0.0.1:7003"],"clientURLs":[]},{"id":"d653b2ec69ce607c","name":"E31C0802","peerURLs":["http://127.0.0.1:7002"],"clientURLs":["http://127.0.0.1:4002"]}]}

6.Trying to start the 3rd instance but saw the error

$ etcd -listen-peer-urls http://127.0.0.1:7003 -initial-advertise-peer-urls http://127.0.0.1:7003 -listen-client-urls http://127.0.0.1:4003 -advertise-client-urls http://127.0.0.1:4003 -initial-cluster E31C0801=http://127.0.0.1:7004,E31C0802=http://127.0.0.1:7002,E31C0803=http://127.0.0.1:7003 -initial-cluster-state new -initial-cluster-token CoolDog -data-dir /Users/u875/machines/E31C0803 -name E31C0803 &
[3] 1994

$ 2015/02/11 16:35:15 etcd: listening for peers on http://127.0.0.1:7003
2015/02/11 16:35:15 etcd: listening for client requests on http://127.0.0.1:4003
2015/02/11 16:35:15 etcdserver: name = E31C0803
2015/02/11 16:35:15 etcdserver: data dir = /Users/u8/machines/E31C0803
2015/02/11 16:35:15 etcdserver: heartbeat = 100ms
2015/02/11 16:35:15 etcdserver: election = 1000ms
2015/02/11 16:35:15 etcdserver: snapshot count = 10000
2015/02/11 16:35:15 etcdserver: advertise client URLs = http://127.0.0.1:4003
2015/02/11 16:35:15 etcdserver: restart member 8d4d400c2fde2262 in cluster df859bb50b3303e at commit index 311
2015/02/11 16:35:15 raft: 8d4d400c2fde2262 became follower at term 16
2015/02/11 16:35:15 raft: newRaft 8d4d400c2fde2262 [peers: [], term: 16, commit: 311, applied: 0, lastindex: 312, lastterm: 10]
2015/02/11 16:35:15 etcdserver: added local member 8d4d400c2fde2262 [http://127.0.0.1:7003] to cluster df859bb50b3303e
2015/02/11 16:35:15 etcdserver: added member c3fc3f283aab4cc7 [http://127.0.0.1:7004] to cluster df859bb50b3303e
2015/02/11 16:35:15 etcdserver: added member d653b2ec69ce607c [http://127.0.0.1:7002] to cluster df859bb50b3303e
2015/02/11 16:35:15 raft: 8d4d400c2fde2262 [term: 16] received a MsgHeartbeat message with higher term from c3fc3f283aab4cc7 [term: 27]
2015/02/11 16:35:15 raft: 8d4d400c2fde2262 became follower at term 27
2015/02/11 16:35:15 raft.node: 8d4d400c2fde2262 elected leader c3fc3f283aab4cc7 at term 27
2015/02/11 16:35:15 sender: the connection with c91f5fe0a6fcdad0 becomes active
2015/02/11 16:35:15 raft: 8d4d400c2fde2262 [logterm: 0, index: 17636] rejected msgApp [logterm: 27, index: 17636] from c3fc3f283aab4cc7
2015/02/11 16:35:15 etcdserver: reject message from removed member 8d4d400c2fde2262
2015/02/11 16:35:15 etcdserver: reject message from removed member 8d4d400c2fde2262
2015/02/11 16:35:15 etcdserver: the member has been permanently removed from the cluster
2015/02/11 16:35:15 etcdserver: the data-dir used by this member must be removed.
2015/02/11 16:35:15 etcdserver: reject message from removed member 8d4d400c2fde2262
2015/02/11 16:35:15 sender: error posting to c91f5fe0a6fcdad0: dial tcp 127.0.0.1:7003: connection refused
2015/02/11 16:35:15 sender: the connection with c91f5fe0a6fcdad0 becomes inactive

Even if I don't perform step 4 but do step 6 directly, no matter I removed the data directory or not before performing step 6, I was giving the similar error.

**Comment by xiang90** [comment]
@aaskey Can you please format your comment a little bit? (I am OK with it, but let us consider people who also watch this project)

**Comment by xiang90** [comment]
@aaskey 
The step 6 is incorrect. 
You need to start the added back member with `--initial-cluster-state = existing` and `--initial-cluster = the expected cluster`.
Also please make sure you have removed the old data directory.

More details in the docs: https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member

**Comment by aaskey** [comment]
Hi Xiang,

Sorry for the messed up formatting in my previous message. I was labelling them in order, but somehow Github has a different understanding :-)

Yes, setting --initial-cluster-state = existing solving the problem. Thank you very much. 

On the other hand, it would be really nice if etcd can be more intelligent to figure out whether a node's initial-cluster-state is "new" or "existing". From application perspective, saving the history of node comes and goes can be burdensome.

**Comment by xiang90** [comment]
@aaskey I fixed the comment for you. 

> On the other hand, it would be really nice if etcd can be more intelligent to figure out whether a node's initial-cluster-state is "new" or "existing".

Unfortunately, we do not want etcd to guess any configuration related flags from the limited info user gives. User must explicitly tell etcd what to do.
