### ISSUE TITLE
Segmentation fault on log compaction

### ISSUE THREAD

**Issue by TheDude05** [coreos/etcd#2299]
I'm running into an issue while testing etcd and flannel where etcd crashes with a segfault when/after attempting log compaction. When trying to restart the etcd process again I get the same error.

The crash dump information is below. Please note that because I was just wanting to test out flannel, I was running etcd in a "non production" setting (i.e as user root on a t2.micro instance). Not sure if that makes a difference here but I wanted to mention it just in case. I'm also attempting to reproduce this with a non superuser account on the same system.

*The initial crash:* https://gist.github.com/TheDude05/5b61fcce1c270a15caf0
*Crash after attempting to restart:* https://gist.github.com/TheDude05/b2cf56e9961556f728cd

I'm using etcd version 2.0.2 (sha1 9b4348a31609440b7f01774a6d411233bcbdd235) on Fedora 21 (kernel 3.17.4-301.fc21.x86_64). I also have a tarball of the data directory if that will help in debugging.

Let me know if there is anything else I can provide.

**Comment by xiang90** [comment]
dup with #2295 
fix at #2298

**Comment by TheDude05** [comment]
Bah, totally missed that issue. Sorry for the noise
