### ISSUE TITLE
etcd 2.0.3 fails to start

### ISSUE THREAD

**Issue by crawford** [coreos/etcd#2306]
`ETCD_DATA_DIR=/var/lib/etcd etcd` results in:

```
2015/02/14 02:02:19 starter: detect etcd version empty in /var/lib/etcd
2015/02/14 02:02:19 starter: failed to get /etcdURL from http://
2015/02/14 02:02:19 starter: failed to check start version through peers: failed to get version from urls []
2015/02/14 02:02:19 starter: start etcd version 2
2015/02/14 02:02:19 etcd: listen tcp: lookup localhost on [10.0.2.3]:53: no such host
```

**Comment by crawford** [comment]
I have no idea where it's getting that address from.

```
core@coreos_developer_qemu-592-0-0-20 ~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP qlen 1000
    link/ether 52:54:00:12:34:56 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86111sec preferred_lft 86111sec
    inet6 fe80::5054:ff:fe12:3456/64 scope link 
       valid_lft forever preferred_lft forever
```

```
core@coreos_developer_qemu-592-0-0-20 ~ $ ip r
default via 10.0.2.2 dev eth0  proto dhcp  src 10.0.2.15  metric 1024 
10.0.2.0/24 dev eth0  proto kernel  scope link  src 10.0.2.15 
10.0.2.2 dev eth0  proto dhcp  scope link  src 10.0.2.15  metric 1024
```

**Comment by xiang90** [comment]
@crawford Are you running this on coreos? Is that img has two etcd binaries at the right place?

**Comment by yichengq** [comment]
I think etcd tries to listen on `localhost:4001` but fails. Is your system able to parse/lookup localhost?

**Comment by crawford** [comment]
@xiang90 yes, this is CoreOS.

```
/ore@coreos_developer_qemu-593-0-0-20 ~ $ ls /usr/libexec/etcd/internal_versions/
1  2
```

**Comment by crawford** [comment]
What does `etcd: listen tcp: lookup localhost on [10.0.2.3]:53: no such host` mean?

Is it using 10.0.2.3 to resolve the hostname?

**Comment by kelseyhightower** [comment]
@crawford Yes, it seems that DNS resolution fails for localhost.

**Comment by kelseyhightower** [comment]
@crawford Do you have an entry in /etc/hosts for localhost?

**Comment by crawford** [comment]
Yes. Actually /usr/share/baselayout/hosts.

`ping localhost` works.

**Comment by kelseyhightower** [comment]
@crawford I think this might be a DNS resolver is in Golang.

**Comment by yichengq** [comment]
@crawford 
Could we narrow the range down?
I guess this code will print error in your env:
```
if _, err := net.Listen("tcp", "localhost:4001"); err != nil {
  log.Println(err)
}
```

**Comment by yichengq** [comment]
@crawford I meet this problem on my CoreOS 593.0.0 machine too. And the `net.Listen` on `localhost:4001` failed with `listen tcp: lookup localhost on 192.168.65.2:53: too many redirects`.
I guess this is a coreos problem.

**Comment by crawford** [comment]
The issue is that etcd is statically compiled on CoreOS. If we dynamically compile etcd, it will use libc and follow our nsswitch settings (which allows us to read from /usr/share/baselayout/hosts as well as /etc/hosts).

We need to update the etcd ebuild to compile dynamically.
