### ISSUE TITLE
undefined binDir in migrate/functional/member.go in 2.0.3

### ISSUE THREAD

**Issue by jelmer** [coreos/etcd#2310]
I'm having trouble compiling one of the migrate files since 2.0.1:

migrate/functional/member.go:59: undefined: binDir

**Comment by yichengq** [comment]
@jelmer Could you tell me that platform, go version, and the command to reproduce the compilation problem?

**Comment by jelmer** [comment]
On Tue, Feb 17, 2015 at 12:08:13AM -0800, Yicheng Qin wrote:
> @jelmer Could you tell me that platform, go version, and the command to reproduce the compilation problem?

This is on Debian unstable, which has go 1.3.3. That should not really matter
though, it seems clear that this variable (binDir) is not defined or imported
in this file.

Jelmer

**Comment by yichengq** [comment]
@jelmer I have to know why we make the changes. :)
The patch has been sent.
