### ISSUE TITLE
Etcdctl fails to connect to remote cluster

### ISSUE THREAD

**Issue by zapman449** [coreos/etcd#2312]
Email thread:  https://groups.google.com/forum/#!topic/etcd-dev/4UvCwXp6P7Y

etcdctl overwrites the --peers command line with variants of localhost in
    ./Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go
in the function
    InternalSyncCluster
.

Cluster is known to be working because curl commands work fine, and when I (ACK!) override the localhost definition in /etc/hosts on the client to be one of the servers, etcdctl works fine as well... That obviously isn't acceptable as a workaround however... ;-)

**Comment by xiang90** [comment]
@zapman449 

You did not set client-advertise url correctly. The default is "localhost:4001". 

https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-advertise-client-urls

**Comment by zapman449** [comment]
Thank you for pointing out my mistake.

**Comment by zapman449** [comment]
FWIW: I wrote a gist showing how someone could get it up and working in Vagrant using Centos7:

https://gist.github.com/zapman449/72f4040b6bed202b20e9
