### ISSUE TITLE
Strange leader IP

### ISSUE THREAD

**Issue by akaspin** [coreos/etcd#2315]
I'm use etcd on EC2. CoreOS, etcd 4.6:

Leader configuration from cloud-config:
```
# /run/systemd/system/etcd.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADDR=172.31.9.157:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/...
Environment="ETCD_HTTP_READ_TIMEOUT=86400"
Environment="ETCD_MAX_RETRY_ATTEMPTS=100"
Environment="ETCD_PEER_ADDR=172.31.9.157:7001"
Environment="ETCD_PEER_ELECTION_TIMEOUT=1200"
Environment="ETCD_PEER_HEARTBEAT_INTERVAL=200"
```
But.
```
$ curl -L http://172.31.0.7:4001/v2/machines
http://172.31.9.157:4001, http://172.31.0.7:4001, http://172.31.13.107:4001   # <--- OK

$ curl -L http://172.31.0.7:4001/v2/leader
http://127.0.0.1:7001                                    # <--- Err...
```
And finally:
```
$ curl -L http://172.31.0.7:7001/v2/admin/machines
[{"name":"51a21ae26dfa4253944a1a7a2fb3de39",
  "state":"follower",
  "clientURL":"http://172.31.0.7:4001",
  "peerURL":"http://172.31.0.7:7001"},
{"name":"9a9f1a75f704463694407e2cfa1cba63",
  "state":"follower",
  "clientURL":"http://172.31.13.107:4001",
  "peerURL":"http://172.31.13.107:7001"},
{"name":"c2eec18fbfd74d1daf787f23f475fc75",
  "state":"leader",
  "clientURL":"http://172.31.9.157:4001",
  "peerURL":"http://127.0.0.1:7001"}]         # <--- Err...
```
OK. My question: leader IP `127.0.0.1`. Is it normal?

**Comment by yichengq** [comment]
No, it is a wrong setting.
In 0.4.6, the peerURL of each member is set through arguments. I doubt that the setting to start "c2eec18fbfd74d1daf787f23f475fc75" is wrong. Could you log into that machines and check the initial command by `systemctl cat etcd`?

**Comment by devurandom** [comment]
I have a very similar issue.

```
core@localhost ~ $ systemctl cat etcd
# /usr/lib64/systemd/system/etcd.service
[Unit]
Description=etcd
Conflicts=etcd2.service

[Service]
User=etcd
PermissionsStartOnly=true
Environment=ETCD_DATA_DIR=/var/lib/etcd
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd
Restart=always
RestartSec=10s
LimitNOFILE=40000

# /run/systemd/system/etcd.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/fbfeab1f8d74c343792574105aaae8b2"
```

If you check https://discovery.etcd.io/fbfeab1f8d74c343792574105aaae8b2, you will see immediately that all my machines apparently announced themselves as "localhost".

```
$ sudo cat /var/lib/coreos-install/user_data
#cloud-config

coreos:
  units:
    - name: static.network
      runtime: true
      content: […]
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
  etcd:
    discovery: https://discovery.etcd.io/fbfeab1f8d74c343792574105aaae8b2

ssh_authorized_keys:
  - […]
```

**Comment by yichengq** [comment]
@devurandom You need to set addr and peer-addr for etcd unit. Reference: https://github.com/coreos/coreos-cloudinit#user-data-field-substitution

**Comment by devurandom** [comment]
I used https://coreos.com/docs/cluster-management/setup/cluster-discovery/ to set this up. It was not clear to me, that addr and peer-addr are needed in every case. I assumed they are only necessary in "multi-region and multi-cloud deployments". Maybe this could be emphasized on that page? Or maybe it could default to $private_ipv4?

**Comment by devurandom** [comment]
I tried both $public_ipv4 and $private_ipv4, but the resulting environment always is:
```
# /run/systemd/system/etcd.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADDR=:4001"
Environment="ETCD_DISCOVERY=…"
Environment="ETCD_PEER_ADDR=:7001"
```

It appears CoreOS is for some reason unable to get the IP address of my local network interface…?

**Comment by yichengq** [comment]
I think the comment means that you need to set addr to $public_ipv4 instead of $private_ipv4 in multi-region and multi-cloud deployments. You always need to set addr for etcd to find each other.
I don't know why you cannot get correct Environment. You could try to google it or report it at github.com/coreos/bugs
