### ISSUE TITLE
etcd2 cluster config issues -advertise-client-urls

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2318]
So i ran into this gem on updating to the tip of k8's.   

If -advertise-client-urls != -listen-client-urls, clients such as etcdctl will fail.  

Perhaps the default should of advertise-client-urls should = listen-client-urls.

**Comment by xiang90** [comment]
advertise-client-urls and listen-client-urls are different.

Can you provide an example of the failure case? And what is your expectation?

**Comment by timothysc** [comment]
If you specify -listen-client-urls=http//$HOSTNAME:4001 and leave advertise-client-urls blank tools will fail.

**Comment by xiang90** [comment]
@timothysc That is expected. You need to specify the advertise client url correctly. We would like the user to set everything cluster-wide configuration explicitly. Does this make any difficulties to you?

```
-advertise-client-urls List of this member's client URLs to advertise to the rest of the cluster.
```

https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-advertise-client-urls

**Comment by timothysc** [comment]
Perhaps, but it's a usability shift from previous versions which could likely be stated in the initial clustering examples: 

https://github.com/coreos/etcd/blob/master/Documentation/clustering.md

NOTE: ...

**Comment by xiang90** [comment]
@timothysc 
We do document the compatibility problem here https://github.com/coreos/etcd/blob/master/Documentation/backward_compatibility.md#command-line-flags-changes. 

You might want to look at it while switching from the old versions of etcd to 2.x.

If you feel you can help to improve the documentation, pull requests are welcomed!

**Comment by kelseyhightower** [comment]
@timothysc Thanks for reporting this issue. As stated by @xiang90 we made this change to increase the visibility of these two settings, which we hope will prevent people from being surprised. The draw back is the change of behavior.

Based on the links provided is there something we can do to improve the documentation?

**Comment by kelseyhightower** [comment]
@timothysc I'm going to close this one out for now. If you can think of anything we can do to improve the docs around this, please feel to reopen this issue.
