### ISSUE TITLE
etcd crashes on windows, out of nowhere

### ISSUE THREAD

**Issue by kjellski** [coreos/etcd#2324]
We've started to test etcd and it seems to crash just out of nowhere. We've not even any sort of load on it. when it crashed tonight, it had no client whatsoever connected.

Here is the dump, if it helps:

    C:\Users\Administrator.xxx\Desktop\etcd-v2.0.2-windows-amd64>etcd -addr "10.10.1.37:4001" -bind-addr "10.10.1.37:4001"
    2015/02/17 07:40:19 no data-dir provided, using default data-dir ./default.etcd
    2015/02/17 07:40:19 etcd: listening for peers on http://localhost:2380
    2015/02/17 07:40:19 etcd: listening for peers on http://localhost:7001
    2015/02/17 07:40:19 etcd: listening for client requests on http://10.10.1.37:4001
    2015/02/17 07:40:19 datadir is valid for the 2.0.1 format
    2015/02/17 07:40:19 etcdserver: name = default
    2015/02/17 07:40:19 etcdserver: data dir = default.etcd
    2015/02/17 07:40:19 etcdserver: member dir = default.etcd/member
    2015/02/17 07:40:19 etcdserver: heartbeat = 100ms
    2015/02/17 07:40:19 etcdserver: election = 1000ms
    2015/02/17 07:40:19 etcdserver: snapshot count = 10000
    2015/02/17 07:40:19 etcdserver: advertise client URLs = http://10.10.1.37:4001
    2015/02/17 07:40:19 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 10001
    2015/02/17 07:40:19 raft: ce2a822cea30bfca became follower at term 12
    2015/02/17 07:40:19 raft: newRaft ce2a822cea30bfca [peers: [], term: 12, commit: 10001, applied: 0, lastindex: 10001, lastterm: 12]
    2015/02/17 07:40:19 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e27652122e8b2ae
    2015/02/17 07:40:19 etcdserver: start to snapshot (applied: 10001, lastsnap: 0)
    2015/02/17 07:40:19 etcdserver: compacted log at index 10001
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x1 addr=0x0 pc=0x61e8fc]

    goroutine 22 [running]:
    runtime.panic(0x7eb720, 0xa7cac2)
            /usr/local/go/src/pkg/runtime/panic.c:279 +0x11f
    github.com/coreos/etcd/snap.(*Snapshotter).save(0x0, 0xc082056bd0, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:71 +0x3bc
    github.com/coreos/etcd/snap.(*Snapshotter).SaveSnap(0x0, 0xc08230a000, 0x2b8d, 0x494d, 0xc082112348, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:59 +0xc3
    github.com/coreos/etcd/etcdserver.(*storage).SaveSnap(0xc082112050, 0xc08230a000, 0x2b8d, 0x494d, 0xc082112348, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:59 +0x6c
    github.com/coreos/etcd/etcdserver.(*EtcdServer).snapshot(0xc08201a100, 0x2711, 0xc082052c30)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:822 +0x58d
    github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc08201a100)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:423 +0xd44
    created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:295 +0x1d9

    goroutine 16 [runnable]:
    github.com/coreos/etcd/etcdmain.Main()
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:76 +0x572
    main.main()
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1b2

    goroutine 19 [finalizer wait]:
    runtime.park(0x415000, 0xa81760, 0xa7f889)
            /usr/local/go/src/pkg/runtime/proc.c:1369 +0xac
    runtime.parkunlock(0xa81760, 0xa7f889)
            /usr/local/go/src/pkg/runtime/proc.c:1385 +0x42
    runfinq()
            /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xdd
    runtime.goexit()
            /usr/local/go/src/pkg/runtime/proc.c:1445

    goroutine 23 [runnable]:
    github.com/coreos/etcd/etcdserver.(*EtcdServer).Do(0xc08201a100, 0x247788, 0xc08206a4e0, 0xca4b967b06390001, 0x83c5d0, 0x3, 0xc0820530e0, 0x26, 0xc082116280, 0x3a, ...)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:479 +0x5d6
    github.com/coreos/etcd/etcdserver.(*EtcdServer).publish(0xc08201a100, 0x12a05f200)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:641 +0x2d0
    created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:276 +0x53

    goroutine 24 [runnable]:
    github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc08201a100)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:306 +0x3fc
    created by github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:277 +0x6b

    goroutine 25 [IO wait]:
    net.runtime_pollWait(0x241b90, 0x72, 0x0)
            /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x6d
    net.(*pollDesc).Wait(0xc082068170, 0x72, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x4d
    net.(*ioSrv).ExecIO(0xc082038018, 0xc082068060, 0x84bf50, 0x8, 0xc0821123d0, 0xc082068480, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:188 +0x242
    net.(*netFD).acceptOne(0xc082068000, 0x910988, 0xc0820741c0, 0x2, 0x2, 0xc082068060, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:546 +0x3c7
    net.(*netFD).accept(0xc082068000, 0x910988, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:573 +0x187
    net.(*TCPListener).AcceptTCP(0xc082038028, 0xc082116380, 0x0, 0x0)
            /usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x64
    net.(*TCPListener).Accept(0xc082038028, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x52
    github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc082065400, 0x0, 0x0, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x80
    net/http.(*Server).Serve(0xc08206a540, 0x241c40, 0xc082065400, 0x0, 0x0)
            /usr/local/go/src/pkg/net/http/server.go:1698 +0x98
    github.com/coreos/etcd/etcdmain.serveHTTP(0x241c40, 0xc082065400, 0x247540, 0xc082052bd0, 0x45d964b800, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x13d
    github.com/coreos/etcd/etcdmain.func┬╖005(0x241c40, 0xc082065400)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:175 +0x5d
    created by github.com/coreos/etcd/etcdmain.startEtcd
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:176 +0x1358

    goroutine 26 [IO wait]:
    net.runtime_pollWait(0x241ae0, 0x72, 0x0)
            /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x6d
    net.(*pollDesc).Wait(0xc0820682f0, 0x72, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x4d
    net.(*ioSrv).ExecIO(0xc082038018, 0xc0820681e0, 0x84bf50, 0x8, 0xc082112400, 0xc082068600, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:188 +0x242
    net.(*netFD).acceptOne(0xc082068180, 0x910988, 0xc0820742a0, 0x2, 0x2, 0xc0820681e0, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:546 +0x3c7
    net.(*netFD).accept(0xc082068180, 0x910988, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:573 +0x187
    net.(*TCPListener).AcceptTCP(0xc082038038, 0xc082116400, 0x0, 0x0)
            /usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x64
    net.(*TCPListener).Accept(0xc082038038, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x52
    github.com/coreos/etcd/pkg/transport.(*rwTimeoutListener).Accept(0xc082065540, 0x0, 0x0, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go:44 +0x80
    net/http.(*Server).Serve(0xc08206a5a0, 0x241c40, 0xc082065540, 0x0, 0x0)
            /usr/local/go/src/pkg/net/http/server.go:1698 +0x98
    github.com/coreos/etcd/etcdmain.serveHTTP(0x241c40, 0xc082065540, 0x247540, 0xc082052bd0, 0x45d964b800, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x13d
    github.com/coreos/etcd/etcdmain.func┬╖005(0x241c40, 0xc082065540)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:175 +0x5d
    created by github.com/coreos/etcd/etcdmain.startEtcd
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:176 +0x1358

    goroutine 27 [IO wait]:
    net.runtime_pollWait(0x241a30, 0x72, 0x0)
            /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x6d
    net.(*pollDesc).Wait(0xc082068470, 0x72, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x4d
    net.(*ioSrv).ExecIO(0xc082038018, 0xc082068360, 0x84bf50, 0x8, 0xc082112410, 0xc082068780, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:188 +0x242
    net.(*netFD).acceptOne(0xc082068300, 0x910988, 0xc082074380, 0x2, 0x2, 0xc082068360, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:546 +0x3c7
    net.(*netFD).accept(0xc082068300, 0x910988, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/fd_windows.go:573 +0x187
    net.(*TCPListener).AcceptTCP(0xc082038040, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/tcpsock_posix.go:234 +0x64
    net.(*TCPListener).Accept(0xc082038040, 0x0, 0x0, 0x0, 0x0)
            /usr/local/go/src/pkg/net/tcpsock_posix.go:244 +0x52
    github.com/coreos/etcd/pkg/transport.(*keepaliveListener).Accept(0xc082001490, 0x0, 0x0, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go:48 +0x77
    net/http.(*Server).Serve(0xc08206a600, 0x241c78, 0xc082001490, 0x0, 0x0)
            /usr/local/go/src/pkg/net/http/server.go:1698 +0x98
    github.com/coreos/etcd/etcdmain.serveHTTP(0x241c78, 0xc082001490, 0x2477c8, 0xc08210c0e0, 0x0, 0x0, 0x0)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/http.go:36 +0x13d
    github.com/coreos/etcd/etcdmain.func┬╖006(0x241c78, 0xc082001490)
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:183 +0x88
    created by github.com/coreos/etcd/etcdmain.startEtcd
            /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:184 +0x147c

    C:\Users\Administrator.xxx\Desktop\etcd-v2.0.2-windows-amd64>

And there was nothing in default.etcd/member/snap directory, but these in the member/wal directory:

![image](https://cloud.githubusercontent.com/assets/30225/6224797/4e28bf78-b682-11e4-9812-9e6b52bb613c.png)

**Comment by yichengq** [comment]
This is due to a bug introduced in 2.0.2
Using 2.0.3 should fix this problem.
