### ISSUE TITLE
etcd 2.0.3 --force-new-cluster retains old cluster's information

### ISSUE THREAD

**Issue by jedsmith** [coreos/etcd#2328]
Hello,

I have a five-node v0.4.6 cluster that I am attempting to migrate to a *new* v2.0.3 cluster. Here are the steps I have followed:

1. Perform a snapshot from the v0.4.6 cluster.
2. Run `etcd-migrate` from v2.0.3 on the v0.4.6 data directory. This converted fine.
3. Run `etcd` with `--force-new-cluster` against that data directory. Again, this ran fine.

At this point, I can run `etcdctl` and everything is fine. I can see data. I restarted etcd to drop the FORCE_NEW_CLUSTER flags and so on to switch to production mode, leaving the final command line for the single node forced cluster as this:

    /usr/bin/docker run --net=host --name=etcd2 -e ETCD_NAME=discovery4
        -e ETCD_LISTEN_CLIENT_URLS=http://10.0.0.155:4001,http://127.0.0.1:4001
        -e ETCD_LISTEN_PEER_URLS=http://10.0.0.155:7001
        -e ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.155:7001
        -e ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.155:4001,http://127.0.0.1:4001
        -e ETCD_DATA_DIR=/data -v /usr/share/ca-certificates/:/etc/ssl/certs
        -v /mnt/ssd/etcd2:/data
        quay.io/coreos/etcd:v2.0.3

After checking that `etcdctl` can still communicate with this member, I then attempted to add a new member.

    $ ~/etcdctl member add discovery1 http://10.0.0.220:7001
    Added member named discovery1 with ID 446e1346f598e422 to cluster
        
    ETCD_NAME="discovery1"
    ETCD_INITIAL_CLUSTER="discovery1=http://10.0.0.220:7001,discovery4=http://10.0.0.191:7001"
    ETCD_INITIAL_CLUSTER_STATE="existing"

Wait a second, that address doesn't look right in `ETCD_INITIAL_CLUSTER`. Sure enough, `etcdctl` is giving me the old address from the old cluster, from before the forced new cluster. Upon deeper inspection, etcd is *also* reporting the old address on the single node that was forced:

    $ curl http://10.0.0.155:7001/members | python -mjson.tool
    [
        {
            "id": 4930899837506348066,
            "peerURLs": [
                "http://10.0.0.220:7001"
            ]
        },
        {
            "clientURLs": [
                "http://10.0.0.155:4001",
                "http://127.0.0.1:4001"
            ],
            "id": 9661612683175327943,
            "name": "discovery4",
            "peerURLs": [
                "http://10.0.0.191:7001"
            ]
        }
    ]

This is where `etcdctl` gets its information from. After I force new cluster, etcd should not remember anything from the prior cluster.

**Comment by xiang90** [comment]
@jedsmith You need to run etcdctl backup on the data dir before you run force-new. 

We probably should rename `force-new` to `force-standalone`. Today's `force-new` only removes the other members in the cluster by appending entries. etcd itself never modifies the old log entries. 

etcdctl backup tool would modify the log entries.

**Comment by jedsmith** [comment]
The root bug, then, is that etcd lies about its peer URL in this state. The peer URL I provide via environment variable is overridden and reported as another peer URL, against my express wishes.
