### ISSUE TITLE
Manual intervention required for replacing a failed node in etcd 2.0.3

### ISSUE THREAD

**Issue by karlgrz** [coreos/etcd#2330]
After upgrading to etcd 2.0.3 it appears that a few manual steps are required to replace a bad node in the cluster.

NOTE: urls and id's obfuscated

### Step One: Get Failed Node ID

Query the ETCD cluster api to get the ID of the failed node.

```bash
$ alias curl="curl --cert client.crt --key client.key"
$ curl https://etcd.test.com:2379/v2/members
```

Output:

```json
{
   "members" : [
      {
         "id" : "9999999999999999",
         "clientURLs" : [
            "https://127.0.0.135:2379"
         ],
         "peerURLs" : [
            "http://etcd-us-east-1d-host1.test.com:2380"
         ],
         "name" : "etcd-us-east-1d-host1"
      },
      {
         "name" : "etcd-us-east-1e-host1",
         "peerURLs" : [
            "http://etcd-us-east-1e-host1.test.com:2380"
         ],
         "clientURLs" : [
            "https://127.0.0.86:4001"
         ],
         "id" : "cccccccccccccccc"
      },
      {
         "id" : "eeeeeeeeeeeeeeee",
         "peerURLs" : [
            "http://etcd-us-east-1b-host1.test.com:2380"
         ],
         "clientURLs" : [
            "https://127.0.0.24:2379"
         ],
         "name" : "etcd-us-east-1b-host1"
      }
   ]
}
```

### Step Two: Delete the Failed Node

This assumes that etcd-us-east-1e-host1 has been identified as the failed node.  The id cccccccccccccccc the id for etcd-us-east-1e-host1 is from step one.

```bash
$ curl -X DELETE https://etcd-us-east-1b-host1.test.com:2379/v2/members/cccccccccccccccc
```

### Step Three: Add Replacement Node

This assumes that etcd-us-east-1e-host1 has been identified as the failed node.

```bash
$ curl --cert client.crt --key client.key -X POST https://etcd-us-east-1b-host1.test.com:4001/v2/members -H 'Content-Type: application/json' -d '{"PeerURLs": ["http://etcd-us-east-1e-host1.test.com:2380"]}'
```

### Step Four: Restart the Failed Node

At this point the container should automatically restart and reconnect to the cluster.  If this does not happen, login to the server and ensure the container has started correctly.

What are we missing here? Would be happy to provide more details to get this resolved.

**Comment by xiang90** [comment]
@karlgrz You can run etcdctl --cluster-health to find out the failed node with its id.

Other than that, it is correct.

**Comment by xiang90** [comment]
@karlgrz Do you have other questions?

**Comment by karlgrz** [comment]
No, thanks!
