### ISSUE TITLE
etcdctl: backup command removes data under /_etcd

### ISSUE THREAD

**Issue by jedsmith** [coreos/etcd#2333]
Similar to the recent fix in v2.0.3 to prevent `etcd-migrate` from deleting `/_etcd`, apparently passing the same data set through `etcdctl backup` first causes the `/_etcd` key to either be removed or not created.

The `etcdctl backup` flow is definitely implicated, because `etcd-migrate` was recently fixed to not do this. When creating a single-node cluster from the `etcd-migrate`d data incorrectly, the `/_etcd` key is present, containing all user data stored there. Once step 3 is added, the `/_etcd` key disappears.

#### Steps to replicate

1. Take a v0.4.6 snapshot.
2. From v2.0.3, run `etcd-migrate --data-dir=snapshot --name=<name>`.
3. Run `etcdctl backup --data-dir=snapshot --backup-dir backup`.
4. Start etcd against the `backup` directory and `--force-new-cluster`.

#### Expected behavior

- User data under `/_etcd` is retained.

#### Observed behavior

- The entire `/_etcd` directory does not exist, including any user data that was underneath.

**Comment by yichengq** [comment]
I cannot reproduce this problem:

```
terminal 1:
$ git checkout tags/v0.4.6
$ ./build
$ ./bin/etcd --snapshot-count=10

terminal 2:
$ curl http://127.0.0.1:4001/v2/keys/_etcd/foo -d value=bar -XPUT
{"action":"set","node":{"key":"/_etcd/foo","value":"bar","modifiedIndex":3,"createdIndex":3}}

terminal 1:
^C
$ git checkout master
$ ./build
$ ./bin/etcd-migrate --data-dir=CoreOS.libcore.so.etcd -name=CoreOS.libcore.so
$ ./bin/etcdctl backup --data-dir=CoreOS.libcore.so.etcd --backup-dir backup.etcd
$ ./bin/etcd --data-dir=backup.etcd -force-new-cluster

terminal 2:
$ curl http://127.0.0.1:4001/v2/keys/_etcd/foo
{"action":"get","node":{"key":"/_etcd/foo","value":"bar","modifiedIndex":3,"createdIndex":3}}
```

Could you check this?

**Comment by jedsmith** [comment]
Nor can I, now, though I did twice last night. I'm not sure what changed, but this can be closed.
