### ISSUE TITLE
forbid setting listen-urls without setting advertise-urls

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2334]
listen-urls and advertise-urls have to be set explicitly in etcd 2.0
The design goal of this is that people have to set everything explicitly, and understand what is happening in the etcd cluster. listen-urls instruct what etcd should listen on, and advertise-urls instruct what urls should be recorded in the cluster, which are used in configuration fetch and change.

People can only set listen-urls without setting advertise-urls, which leaves advertise-urls as localhost, which cannot be accessed by other members. This issue aims to forbid this case because it is rather confusing.

For the future, maybe we can imply listen-urls from advertise-urls to save user efforts.

/cc @jedsmith

**Comment by xiang90** [comment]
Closed via #2761
