### ISSUE TITLE
falloc on segmented wal files

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2336]
We want to pre-allocate the space for the WAL files when it is created. 

It brings some benefits:
1. Avoid runtime short write when running out of disk space
2. Better error message for running out of disk space
3. Less fragmentation, better performance

As a starter, we probably only need to implement this for osx and linux. They have different syscalls though.

**Comment by xiang90** [comment]
Seems like only linux support this. 
For osx, see https://blog.mozilla.org/tglek/2010/09/09/help-wanted-does-fcntlf_preallocate-work-as-advertised-on-osx/

**Comment by digambar15** [comment]
Hi xiang90,

    can I work on this issue, if you dont mind. I want to start contribution to coreos & I think this is good to start.

Thanks,
Digambar

**Comment by xiang90** [comment]
@digambar15 Hm... Sorry we just fixed this issue. Can you try to grab another one?

**Comment by digambar15** [comment]
Sure xiang. can you suggest me low hanging fruit to start with ?
