### ISSUE TITLE
etcd master sometimes fails with flags

### ISSUE THREAD

**Issue by barakmich** [coreos/etcd#2346]
Repro:

From the root checkout of etcd:
1) `./build`
2) `cp bin/etcd ./`
3) Change `Procfile` slightly: for node3, instead of running bin/etcd, run etcd -- which is the binary we just copied
4) `goreman start`

...and node3 fails to run. Why?

```
$ goreman start  
13:59:47 etcd1 | START
13:59:47 etcd2 | START
13:59:47 etcd3 | START
13:59:47 proxy | START
13:59:47 etcd3 | flag provided but not defined: -initial-advertise-peer-urls
```

The other two work. Why?

**Comment by xiang90** [comment]
@barakmich I cannot reproduce this on Mac and CoreOS. Probably you messed up the Procfile? Or you run another etcd, which is a binary at some other place?

**Comment by barakmich** [comment]
I'm an idiot. Closing

**Comment by ilackarms** [comment]
@barakmich can you explain the solution you used?
