### ISSUE TITLE
snapshot issues

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2370]
- [x] no snapshot resend in raft
- [x] snapshot sending status reporting
- [x] non-blocking snapshot encoding
- [x]  keep a min number of entries in memory for the follower latency gap
- ~~[ ] saving snapshot should not block the raftNode loop~~ - #3714
- ~~[ ] best effort snapshot pre-fetch when starting/restarting~~ - #3715
- [x] incremental snapshot (aka raft log as wal and disk-backend as state)

**Comment by yichengq** [comment]
I have played with large(~1G) incremental snapshot on AWS and GCE. etcd v3 could host ~1G data while making progress stably.

Moreover, i tested sending snapshot from leader to follower, and it works well in most cases.

The only exception is using standard persistent disk in GCE as both data-dir and wal-dir. Read requests to load snapshot and send it out will make WAL write requests wait too long, which affects heartbeat mechanism between leader and other followers, so the cluster may switch leader frequently and become unstable. Either changing to use local SSD, or using one device for wal-dir and another for data-dir could bypass the problem. Our TODO is to find way to ensure WAL write requests is treated as high priority.

**Comment by yichengq** [comment]
Close it because all issues are cleared.
