### ISSUE TITLE
Benchmark for performance and scalability

### ISSUE THREAD

**Issue by dchen1107** [coreos/etcd#2371]
For etcd release, there should be a benchmark for performance and scalability:

\# of entries: 
\# size of per entries
\# max writes/s per instance 
\# max reads/s per instance
...

**Comment by countspongebob** [comment]
Ideally some kind of benchmark should be integrated into the test suite to guard against performance regression - is there no such test today?

**Comment by xiang90** [comment]
@dchen1107 
https://github.com/coreos/etcd/tree/master/Documentation/benchmarks

This kind of solves the issue. At least we have the baseline now. We will publish the benchmark tool soon.
