### ISSUE TITLE
CLI option: Add ability to specify default host

### ISSUE THREAD

**Issue by bbangert** [coreos/etcd#2375]
By default, all the various flags for etcd to start up with default to 'localhost'. This presents quite a config hurdle when jumping from playing with 3 instances locally (a common demo in etcd presentations), to running 3 instances on 3 separate machines/VM's, as every single config option using a hostname (a lot) now all need to be specified.

It would make sense to have a single 'hostname' or 'ip_address' flag that replaces all uses of 'localhost', which would make it much easier to try 3 instances on 3 separate machines.

**Comment by xiang90** [comment]
do you mean a --initial-default-hostname ?

**Comment by bbangert** [comment]
Sure, something that would replace 'localhost' in all the config bits that use it.

**Comment by yichengq** [comment]
@bbangert What about this alternative:
```
IP=10.0.0.2 etcd --listen-peer-urls $IP:7001 --initial-advertise-peer-urls $IP:7001
```
Does it solve the problem?

For localhost running, i always running `goreman start` to start a 3-member cluster: https://github.com/coreos/etcd#running-local-etcd-cluster

**Comment by xiang90** [comment]
@bbangert Does @yichengq's suggestion work for you?

**Comment by bbangert** [comment]
Aren't there more settings to configure that all default to localhost as well? The main issue was having to specify every single option with the new IP, rather than just being able to change 'localhost' -> IP with a single flag. I guess I'm just weird that I actually launch things by typing in the command instead of assembling Procfile's to run with goreman.

**Comment by xiang90** [comment]
@bbangert I think a Procfile might serve you's purpose(for demo) better. We are kind of conservative/careful about adding a CLI flag, especially the purpose of it is not for production usage.

**Comment by yichengq** [comment]
@bbangert Another way is to write a script to play with it easily.

Feel free to reopen it if you still have troubles with it.
