### ISSUE TITLE
is etcdctl peers flag ignored if --no-sync is not used?

### ISSUE THREAD

**Issue by agokjr** [coreos/etcd#2376]
ETCDCTL v2.0.3

Setting ETCDCTL_PEERS or --peers to external ip that matches the cert generated via etcd-ca tool.
```
export ETCDCTL_PEERS=https://xxx.xxx.xxx.xxx:4001
```
I noticed that I instead of the expected external https end point I am getting the following.

```
Cluster-Endpoints: http://127.0.0.1:2379, http://127.0.0.1:4001, http://localhost:2379, http://localhost:2379, http://localhost:4001, http://localhost:4001, https://127.0.0.1:2379, https://127.0.0.1:4001
Curl-Example: curl -X GET http://127.0.0.1:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://127.0.0.1:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://127.0.0.1:4001/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:2379/v2/keys/?consistent=true&recursive=false&sorted=false
Curl-Example: curl -X GET http://localhost:4001/v2/keys/?consistent=true&recursive=false&sorted=false
```

It does not look like the ETCDCTL_NO_SYNC flag works.

Thanks

**Comment by kelseyhightower** [comment]
@agokjr Can you provide the full commands you are running for etcdctl?

**Comment by agokjr** [comment]
I'm fairly sure it was set up like this. However I can check on Monday when I have the file I used to generate the environment with me. I have since turned off the client https and switched client to only 127.0.0.1.  (I was having with fleet with the https see lower half of #2378 where fleet was saying request were canceled and machines would timeout and temporary disappear from fleetctl list-machines)

## etcd
Lets see I have `/opt/bin/etcd` 2.0.3 running.
With 
> ETCD_CA_FILE=/etc/ssl/certs/etcd.pem # note update-ca-certificates has been run
> ETCD_CERT_FILE=/etc/etcd/etcd.crt
> ETCD_KEY_FILE=/etc/etcd/etcd.key.insecure
> ETCD_PEER_CA_FILE=/etc/ssl/certs/etcd.pem
> ETCD_PEER_CERT_FILE=/etc/etcd/etcd.crt
> ETCD_PEER_KEY_FILE=/etc/etcd/etcd.key.insecure

I also have basic flags set via environment variables
- advertise-client-urls=listen-client-urls=https://0.0.0.0:2380,https://0.0.0.0:7001
- listen-peer-urls=https://$public_ipv4:2380,https://$public_ipv4:7001
- initial-advertise-peer-urls=http://$public_ipv4:2380,http://$public_ipv4:7001 

## etcdctl
For `/opt/bin/etcdctl` v2.0.3
> ETCDCTL_PEERS=https://127.0.0.1:4001 # I think it might have been $public_ipv4
> ETCDCTL_CA_FILE=/etc/ssl/certs/etcd.pem
> ETCDCTL_CERT_FILE=/etc/etcd/etcd.crt
> ETCDCTL_KEY_FILE=/etc/etcd/etcd.key.insecure

As for actual command
Failed:
> /opt/bin/etcdctl --debug ls
Worked:
> /opt/bin/etcdctl --no-sync --debug ls

Trying with curl directly worked.
```bash
curl --cacert $ETCDCTL_CA_FILE --cert $ETCDCTL_CERT_FILE \
 --key $ETCDCTL_KEY_FILE -X GET "$ETCDCTL_PEERS/v2/keys/" 
````
Note $public_ipv4 is replaced by script.

Now what does the sync part of `--no-sync` (I would guess A)
A) sync look up who is the current members 
B) cache the the etcd contents?

**Comment by yichengq** [comment]
A is the sync part. It grabs the advertise client urls from the cluster, and uses these urls to do the requests. (i recommend that you set advertise-client-urls correctly)

etcdctl peers flag is not ignored. It is used in the sync part.

**Comment by agokjr** [comment]
Ops Forgot I had it on the same line right now.

**Comment by yichengq** [comment]
`advertise-client-urls=https://127.0.0.1:4001` is better to be `advertise-client-urls=https://$public-ip:4001`, so other can fetch the endpoint through public ip.

**Comment by agokjr** [comment]
Ok I now have the files in front of me, and I think I know what my problem was now. Mix up of '-' and '_' in the file that I used to generate the cloud config file. 'advertise-client-urls' vs 'advertise_client_urls'

Here is what I had moved to a separate file for generating the cloud config.
```json
{
  "coreos" : {
    "etcd" : {
        "key_file" : "/etc/etcd/etcd.key.insecure",
        "cert_file" : "/etc/etcd/etcd.crt",
        "ca_file" : "/etc/ssl/certs/etcd.pem",
        "advertise-client-urls": "https://$public_ipv4:2379,https://$public_ipv4:4001",
        "listen_client_urls":"https://0.0.0.0:2379,https://0.0.0.0:4001"
    }
  }
}
```

**Comment by yichengq** [comment]
@agokjr Cool. Any other problems?

**Comment by agokjr** [comment]
Things are working nicely now with etcd.
