### ISSUE TITLE
'etcdctl member add' ignores name of node

### ISSUE THREAD

**Issue by heyryanw** [coreos/etcd#2380]
**Problem:** Following the documentation [here](https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md), using the 'etcdctl member add' tool doesn't properly set node name.

**Steps to reproduce:** On any current member in a cluster: 'etcdctl member add node1 http://1.2.3.4:2380'. The resulting output is correct in that it shows the environment variables to be issued to the new node, with the proper node name and all, however, immediately checking that these keys were stored correctly with 'etcdctl member list' shows a blank name for this host, though the peer url is correct.

Further investing the keys via the membersAPI shows a blank value for this new node, but a correct peerurl.

**Comment by kelseyhightower** [comment]
@heyryanw Thanks for reporting this issue. What happens once you add the new member using the output from the `etcdctl member add` command?

**Comment by yichengq** [comment]
@heyryanw We don't register name into the cluster when adding new member now, so the behave is expected.
The name of the member will be registered into the cluster when the member is actually bootstrapped.

**Comment by xiang90** [comment]
@heyryanw This is duplicated with https://github.com/coreos/etcd/issues/2251.

We need to list the unstarted member as unstarted.

**Comment by heyryanw** [comment]
Sorry, for the delayed response. As @kelseyhightower asked, when using the commands to add the member in, it throws an error stating it cannot be found in the cluster by name. Guess there's a few issues surrounding this though.
