### ISSUE TITLE
security implementation

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2384]
Security feedback

- [x] decouple the enable and root user creation
- [x] add root role, so we can have multiple admin users
- [x] doc: /security/user -> /security/users
- [x] add everyone user and role when enabling security, which has all access to key space. the no user:pass falls into everyone.
- [x] prefix matching
- [x] never return error message from store
- [x] security needs to be enabled each time reboot, it returns `{"enabled":false}` when I check it
- [x] enable after reboot returns `{"errorCode":105,"message":"Key already exists","cause":"/2/users/root","index":11}`
- [x] delete users/root return `{"message":"Can't delete root user; disable security instead."}`, but it is not enabled
- [x] password can be empty
- [x] both create/update return 201 created
- [x] return hashed password when updating password
- [x] fix the examples in the rfc 
- [x] log the admin operations
- [x] update role fails to work, and returns the old role json as HTTP result

**Comment by xiang90** [comment]
Security feedback

- [ ] decouple the enable and root user creation
- [ ] add root role, so we can have multiple admin users
- [ ] doc: /security/user -> /security/users
- [ ] add everyone user and role when enabling security, which has all access to key space. the no user:pass falls into everyone.
- [ ] prefix matching
- [ ] never return error message from store
- [ ] security needs to be enabled each time reboot, it returns `{"enabled":false}` when I check it
- [ ] enable after reboot returns `{"errorCode":105,"message":"Key already exists","cause":"/2/users/root","index":11}`
- [ ] delete users/root return `{"message":"Can't delete root user; disable security instead."}`, but it is not enabled
- [ ] password can be empty
- [ ] both create/update return 201 created
- [ ] return hashed password when updating password
- [ ] fix the examples in the rfc 
- [ ] log the admin operations
- [ ] update role fails to work, and returns the old role json as HTTP result

**Comment by barakmich** [comment]
not an "everyone" user, but a "guest" role

**Comment by barakmich** [comment]
There may be some error messages from the store, but not the same way

**Comment by barakmich** [comment]
enable/disable should be fixed, which are some of the bugs mentioned

**Comment by xiang90** [comment]
Fixed via #2384

**Comment by benmccann** [comment]
Fixed by what? :-)  That's a self-referential link :-)

**Comment by barakmich** [comment]
@benmccann #2654 -- Typo, with the same first and last numbers.
