### ISSUE TITLE
etcdctl recursive delete with wildcards

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2385]
There are times where is would be very useful to recursively delete based on wildcard.  

e.g. rm -rf /foo/bar/*

**Comment by yichengq** [comment]
We have remove recursively functonality:

```
unihorn@CoreOS ~/g/s/g/c/etcd> ./bin/etcdctl --no-sync rm --help
   rm - remove a key

USAGE:
   command rm [command options] [arguments...]

OPTIONS:
   --dir		removes the key if it is an empty directory or a key-value pair
   --recursive		removes the key and all child keys(if it is a directory)
   --with-value 	previous value
   --with-index '0'	previous index
```

**Comment by timothysc** [comment]
what about the wild-cards?  

--recursive		removes the key and all child keys(if it is a directory)

**Comment by kelseyhightower** [comment]
@timothysc What you want here is the ability to do this:

Give the following keys:

```
/foo/bar/a
/foo/bar/b
/foo/bar/dir/a
/foo/bar/dir/b
```

After running the following command:

```
rm -rf /foo/bar/*
````

You want the following keys to exist:

```
/foo/bar/dir/a
/foo/bar/dir/b
```

Does that look right?

**Comment by timothysc** [comment]
@kelseyhightower yup.

**Comment by olibob** [comment]
I ended up here looking exactly for what's requested. I ended up doing a `etcdctl ls -recursive`, greping for the keys I wanted to remove and feeding them to `etcdctl rm`

**Comment by timothysc** [comment]
@olibob great minds think alike ;-) 

Anyway... I know upstream is not to keen on treating it as a file-system, but users would ideally like to perform all the traditional ops.  IMHO a fuse mount would enable, and folks could just say they *will not* support the entirety of POSIX semantics.

**Comment by jeremyeder** [comment]
Sounds like I'm not the only one that wants etcdctl to become a full-fledged etcd CLI client...

**Comment by ianbytchek** [comment]
:+1:

**Comment by dgonyeo** [comment]
Just chanced across this, but wouldn't the shell fill in the `*` before passing it into etcdctl?

**Comment by xiang90** [comment]
I am inclined to close this. We do not actively working on v2 anymore. v3 does not support the concept of dir, so this is not an issue anymore.

**Comment by timothysc** [comment]
sgtm

**Comment by rustyx** [comment]
For etcd v3 use **`etcdctl del --prefix=true <prefix>`**

That will delete everything starting with `<prefix>`
