### ISSUE TITLE
More configuration options for testing and limited use

### ISSUE THREAD

**Issue by grimnight** [coreos/etcd#2389]
I would like to be able to run etcd in localhost only without clustering and without persistence (no disk, memory-only).

Can you add command line option for configuration file so it is possible to have multiple configuration files.

Can you add option for memory use limits or limits for number of keys.

Can you add configuration file option to enable/disable the possibility to remotely flush etcd to disk.

Can you add configuration file option to enable/disable the possibility to remotely shutdown etcd.

Well, that was a lot to ask for, I hope atleast some of these are possible.
Thank you for making etcd.

**Comment by kelseyhightower** [comment]
@grimnight Thanks for reaching out, but it will be easier to consider these requests if they were proposed in a separate issue. Please open new issue of each item you would like us to review.
