### ISSUE TITLE
running etcd in localhost only, without clustering and without persistence

### ISSUE THREAD

**Issue by grimnight** [coreos/etcd#2391]
I would like to be able to run etcd in localhost only without clustering and without persistence (no disk, memory-only).

**Comment by yichengq** [comment]
Why do you want this feature? etcd should run on stable storage, or it cannot guarantee the consistency it provides.

**Comment by grimnight** [comment]
I would like these features for testing purposes, I do not need persistence or clustering for my current use. To be specific I would like etcd to load existing data directory but not write back to it, there may be multiple separate instances of etcd running at the same time at separate ports.

**Comment by AdoHe** [comment]
@grimnight maybe you should find another solution, etcd is not very suitable for such case.

**Comment by kelseyhightower** [comment]
@grimnight For this use case you can write a wrapper script that removes etcd's datadir before starting etcd and after etcd shuts down. 

You can configure etcd with an initial cluster size of one and a single peer giving you a standalone etcd cluster.

Does this work for you?

**Comment by kelseyhightower** [comment]
@grimnight Closing for now, let me know if the proposed solution does not work for you.
