### ISSUE TITLE
add command line option for configuration file

### ISSUE THREAD

**Issue by grimnight** [coreos/etcd#2392]
Can you add command line option for configuration file so it is possible to have multiple configuration files?

**Comment by yichengq** [comment]
If you want to have configuration file, we recommend you write a `systemd` file in linux to bootstrap etcd. It is much clean and helps logging.

**Comment by grimnight** [comment]
I'm on a mac so I would be using launchd or a process supervisor. Can you recommend a lightweight process supervisor that works well with etcd? Or I can try to make multiple launchd plist files, each with their own options.

**Comment by kelseyhightower** [comment]
@grimnight Yes a plist file would work and provide the same workflow that systemd does. Just be sure to use a different data directory for each "config".
