### ISSUE TITLE
option for memory use limits or limits for number of keys

### ISSUE THREAD

**Issue by grimnight** [coreos/etcd#2393]
Can you add option for memory use limits or limits for number of keys?

**Comment by yichengq** [comment]
Is this related to #2371 ?

**Comment by grimnight** [comment]
This is not related to #2371 . I would just like to be able to limit memory use.

**Comment by kelseyhightower** [comment]
@grimnight Yes this is not related.

A couple of questions come to mind for a feature like this. When memory usage limits are reached how should etcd handle new writes? Expiring TTLs -- should we let them expire and risk losing data?

**Comment by bprashanth** [comment]
+9000 to main memory limits, it's a common concept in most databases and I was puzzled that it wasn't configurable in etcd. I'd prefer having etcd swap to disk when it hits the limit, if that's not possible, flip to read-only and spam the logs with memory limit reached for each write. Just my 2c.

**Comment by klausenbusk** [comment]
Any update on this? Currently etcd2 use 90M or 18% of my memory (512MB Digital Ocean node)

**Comment by xiang90** [comment]
@klausenbusk What is the problem with 90M memory usage?

**Comment by klausenbusk** [comment]
@xiang90 It a large portion of the memory, when the nodes is only 512MB. Before I restarted etcd it was 136MB, I was testing something.

**Comment by xiang90** [comment]
@klausenbusk If you want to limit the memory usage, you can always limit the number of keys yourself; we can set a hard limit too to avoid you adding more keys into etcd. However etcd will keep ALL data in memory.

**Comment by klausenbusk** [comment]
I only have < 30 keys, but I refresh some of them very often. The 3 db nodes alone do around ~ 140 "refresh" every minute, then I also have some other node, but around ~ 200 "refresh" per minute.

**Comment by xiang90** [comment]
@kalabiyau etcd keeps internal history events for watch/replication etc.. Also etcd2 is not memory efficient and it is improved with our new v3 backend.
