### ISSUE TITLE
configuration file option to enable/disable the possibility to remotely flush etcd to disk

### ISSUE THREAD

**Issue by grimnight** [coreos/etcd#2394]
Can you add configuration file option to enable/disable the possibility to remotely flush etcd to disk?

**Comment by kelseyhightower** [comment]
@grimnight Are you thinking of an API endpoint that will allow you to dump etcd data?

**Comment by grimnight** [comment]
Yes. An API endpoint to trigger a flush.

**Comment by xiang90** [comment]
@grimnight We might be interested in this idea if you has a concrete use case. It is not on our short term roadmap.

**Comment by yichengq** [comment]
@grimnight Could you give more details about why you want it?

**Comment by uidzero** [comment]
Wouldn't it make more sense to build this functionality into etcdctl? You could then force a flush with something like:
```
etcdctl exec-watch /foo/bar -- bash -c " \
  if [ $ETCD_WATCH_VALUE == "flush" ]; then \
    etcdctl flush ;\
    etcdctl set /foo/bar "no-flush" ;\
 fi"
```

**Comment by uidzero** [comment]
@yichengq The use case I see here is flushing to disk from a system shutdown script. This would be especially useful if you're running etcd as a single node instead of in a cluster.

**Comment by yichengq** [comment]
> The use case I see here is flushing to disk from a system shutdown script. This would be especially useful if you're running etcd as a single node instead of in a cluster.

etcd could recover data store when restart. If you plan to move it to a new machine, you could backup data dir to the remote and start etcd using that data dir.

**Comment by xiang90** [comment]
@uidzero I think @yichengq has an answer for you. If a request is committed, etcd will make sure it is persistent. You do not have to flush it manually.
