### ISSUE TITLE
Error: "invalid memory address or nil pointer dereference" when trying to add new node to existing cluster

### ISSUE THREAD

**Issue by wsimmonds** [coreos/etcd#2396]
Hi,

I'm currently experiencing an issue when trying to add a new node to an existing cluster. I'm running 2.0.3 from within a Docker container. My log looks somewhat like the following:

Feb 27 14:52:58 ip-10-21-1-94.ec2.internal systemd[1]: Starting etcd container...
Feb 27 14:52:58 ip-10-21-1-94.ec2.internal writer_process[4938]: etcd
Feb 27 14:52:58 ip-10-21-1-94.ec2.internal writer_process[4945]: etcd
Feb 27 14:52:58 ip-10-21-1-94.ec2.internal writer_process[4953]: Pulling repository quay.io/coreos/etcd
Feb 27 14:52:59 ip-10-21-1-94.ec2.internal writer_process[4953]: Status: Image is up to date for quay.io/coreos/etcd:v2.0.3
Feb 27 14:52:59 ip-10-21-1-94.ec2.internal systemd[1]: Started etcd container.
Feb 27 14:52:59 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:52:59 etcd: listening for peers on http://0.0.0.0:2380
Feb 27 14:52:59 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:52:59 etcd: listening for peers on http://0.0.0.0:7001
Feb 27 14:52:59 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:52:59 etcd: listening for client requests on http://0.0.0.0:2379
Feb 27 14:52:59 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:52:59 etcd: listening for client requests on http://0.0.0.0:4001
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: could not get cluster response from http://10.21.1.43:2380: Get http://10.21.1.43:2380/members: net/http: request canceled while waiting for connection
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: name = ip-10-21-1-94.ec2.internal
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: data dir = /opt/etcd
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: member dir = /opt/etcd/member
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: heartbeat = 100ms
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: election = 1000ms
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: snapshot count = 10000
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: 2015/02/27 14:53:00 etcdserver: advertise client URLs = http://10.21.1.94:2379,http://10.21.1.94:4001
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: [signal 0xb code=0x1 addr=0x0 pc=0x4a5b5d]
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 16 [running]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: runtime.panic(0x7dc1e0, 0xa63493)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: github.com/coreos/etcd/etcdserver.startNode(0xc20803a580, 0x0, 0x0, 0x0, 0xc208044f80, 0x0, 0x0, 0x10, 0x10)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:78 +0xdd
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: github.com/coreos/etcd/etcdserver.NewServer(0xc20803a580, 0xc20803a580, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:171 +0x6bc
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: github.com/coreos/etcd/etcdmain.startEtcd(0xc20807c000, 0x0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:162 +0x1013
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: github.com/coreos/etcd/etcdmain.Main()
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:58 +0x1c5
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: main.main()
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1ab
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 19 [finalizer wait]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: runtime.park(0x4131d0, 0xa67fd8, 0xa66209)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: runtime.parkunlock(0xa67fd8, 0xa66209)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: runfinq()
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: runtime.goexit()
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/runtime/proc.c:1445
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 20 [syscall]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: os/signal.loop()
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: created by os/signal.init·1
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 28 [IO wait]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net.runtime_pollWait(0x7fbec1e58938, 0x72, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net.(*pollDesc).Wait(0xc20807efb0, 0x72, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x46
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net.(*pollDesc).WaitRead(0xc20807efb0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x42
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net.(*netFD).Read(0xc20807ef50, 0xc208074000, 0x1000, 0x1000, 0x0, 0x7fbec1e573f0, 0xb)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/fd_unix.go:242 +0x34c
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net.(*conn).Read(0xc2080380a0, 0xc208074000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/net.go:122 +0xe7
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: github.com/coreos/etcd/pkg/transport.timeoutConn.Read(0x7fbec1e58f30, 0xc2080380a0, 0x12a05f200, 0x12a05f200, 0xc208074000, 0x1000, 0x1000, 0x7fbec1e590b8, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go:43 +0x16f
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: github.com/coreos/etcd/pkg/transport.(*timeoutConn).Read(0xc2080405e0, 0xc208074000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: <autogenerated>:21 +0xcc
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net/http.noteEOFReader.Read(0x7fbec1e59068, 0xc2080405e0, 0xc20803a738, 0xc208074000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:1203 +0x72
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net/http.(*noteEOFReader).Read(0xc208040600, 0xc208074000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: <autogenerated>:124 +0xca
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: bufio.(*Reader).fill(0xc2080049c0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/bufio/bufio.go:97 +0x1b3
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: bufio.(*Reader).Peek(0xc2080049c0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/bufio/bufio.go:132 +0x101
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net/http.(*persistConn).readLoop(0xc20803a6e0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:782 +0x95
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: created by net/http.(*Transport).dialConn
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 26 [runnable]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net/http.(*persistConn).readLoop(0xc20803a2c0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:868 +0x829
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: created by net/http.(*Transport).dialConn
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 27 [select]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net/http.(*persistConn).writeLoop(0xc20803a2c0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: created by net/http.(*Transport).dialConn
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: goroutine 29 [select]:
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: net/http.(*persistConn).writeLoop(0xc20803a6e0)
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: created by net/http.(*Transport).dialConn
Feb 27 14:53:00 ip-10-21-1-94.ec2.internal writer_process[4961]: /usr/local/go/src/pkg/net/http/transport.go:601 +0x957
Feb 27 14:53:01 ip-10-21-1-94.ec2.internal systemd[1]: etcd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 27 14:53:01 ip-10-21-1-94.ec2.internal writer_process[5026]: etcd
Feb 27 14:53:01 ip-10-21-1-94.ec2.internal systemd[1]: Unit etcd.service entered failed state.

The existing cluster consists of 2 nodes, my etcd.service looks like this:

[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
SyslogIdentifier=writer_process
ExecStartPre=-/usr/bin/docker kill etcd
ExecStartPre=-/usr/bin/docker rm etcd
ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.3
ExecStart=/bin/bash -c "/usr/bin/docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  -p 4001:4001 \
  -p 7001:7001 \
  --name etcd \
  -v /opt/etcd:/opt/etcd \
  -v /usr/share/ca-certificates/:/etc/ssl/certs \
  quay.io/coreos/etcd:v2.0.3 \
  -data-dir /opt/etcd \
  -name %H \
  -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
  -advertise-client-urls http://10.21.1.94:2379,http://10.21.1.94:4001 \
  -listen-peer-urls http://0.0.0.0:2380,http://0.0.0.0:7001 \
  -initial-advertise-peer-urls http://10.21.1.94:2380,http://10.21.1.94:7001 \
  -initial-cluster-state existing \
  -initial-cluster ip-10-21-1-43.ec2.internal=http://10.21.1.43:2380,ip-10-21-1-43.ec2.internal=http://10.21.1.43:7001,ip-10-21-2-166.ec2.internal=http://10.21.2.166:2380,ip-10-21-2-166.ec2.internal=http://10.21.2.166:7001"
ExecStop=/usr/bin/docker kill etcd

I thought at first it might be related to the "could not get cluster response", but a quick check from .94 works:

core@ip-10-21-1-94 /etc/systemd/system $ curl -L http://10.21.1.43:2380/members
[{"id":12394471189341718283,"peerURLs":["http://10.21.2.166:2380","http://10.21.2.166:7001"],"name":"ip-10-21-2-166.ec2.internal","clientURLs":["http://10.21.2.166:2379","http://10.21.2.166:4001"]},{"id":13661735980988760828,"peerURLs":["http://10.21.1.43:2380","http://10.21.1.43:7001"],"name":"ip-10-21-1-43.ec2.internal","clientURLs":["http://10.21.1.43:2379","http://10.21.1.43:4001"]}]

Any help would be hugely appreciated.

**Comment by kelseyhightower** [comment]
@wsimmonds At a quick glance it seems you have a configuration issue with the `-initial-cluster` flag. Notice that `ip-10-21-1-43.ec2.internal` is listed twice. I suspect this will not work even though you're using a different port for the peer address. My current understanding is that each member of the cluster requires a unique name. If you want to run two etcd servers on a single machine (not recommend for production), you need to give each etcd instance it's own name. In this case using the hostname is not the best option.

To help me troubleshoot this I need all three etcd services files. Please include the complete service file for each node. For example:

ip-10-21-1-43.ec2.internal

```
[Service]
EnvironmentFile=/etc/environment
TimeoutStartSec=0
SyslogIdentifier=writer_process
ExecStartPre=-/usr/bin/docker kill etcd
ExecStartPre=-/usr/bin/docker rm etcd
ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.3
ExecStart=/bin/bash -c "/usr/bin/docker run \
-p 2379:2379 \
-p 2380:2380 \
-p 4001:4001 \
-p 7001:7001 \
--name etcd \
-v /opt/etcd:/opt/etcd \
-v /usr/share/ca-certificates/:/etc/ssl/certs \
quay.io/coreos/etcd:v2.0.3 \
-data-dir /opt/etcd \
-name %H \
-listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
-advertise-client-urls http://10.21.1.94:2379,http://10.21.1.94:4001 \
-listen-peer-urls http://0.0.0.0:2380,http://0.0.0.0:7001 \
-initial-advertise-peer-urls http://10.21.1.94:2380,http://10.21.1.94:7001 \
-initial-cluster-state existing \
-initial-cluster ip-10-21-1-43.ec2.internal=http://10.21.1.43:2380,ip-10-21-1-43.ec2.internal=http://10.21.1.43:7001,ip-10-21-2-166.ec2.internal=http://10.21.2.166:2380,ip-10-21-2-166.ec2.internal=http://10.21.2.166:7001"
ExecStop=/usr/bin/docker kill etcd
```

**Comment by kelseyhightower** [comment]
We also need to investigate why etcd is blowing up here. /cc @yichengq

**Comment by wsimmonds** [comment]
Thanks kelseyhightower. Case of not seeing the wood for the trees - been modifying so many different configurations lately that I missed that and suspect you are correct. Will let you know outcome shortly.

**Comment by yichengq** [comment]
@wsimmonds 
It doesn't work because the name of the node `ip-10-21-1-94.ec2.internal` doesn't appear on the initial-cluster-list `ip-10-21-1-43.ec2.internal=http://10.21.1.43:2380,ip-10-21-1-43.ec2.internal=http://10.21.1.43:7001,ip-10-21-2-166.ec2.internal=http://10.21.2.166:2380,ip-10-21-2-166.ec2.internal=http://10.21.2.166:7001"`

etcd doesn't check this beforehand, so it panics here. gonna fix it.

If a member wants to claim multiple peer urls, it appears in initial-cluster several times, e.g., https://github.com/coreos/etcd/blob/master/etcdmain/config.go#L156
And different members should have different names.

**Comment by wsimmonds** [comment]
@yichengq 
Thanks for your response. Indeed the issue wasn't having multiple entries in initial-cluster for the same server with multiple endpoints.

However, it seems adding the node per your suggestion isn't working? (note: I have changed instance to .1.66 and got rid of .1.94 in case wondering about IP address change):

-initial-cluster ip-10-21-1-66.ec2.internal=http://10.21.1.66:2380,ip-10-21-1-66.ec2.internal=http://10.21.1.66:7001,ip-10-21-1-43.ec2.internal=http://10.21.1.43:2380,ip-10-21-1-43.ec2.internal=http://10.21.1.43:7001,ip-10-21-2-166.ec2.internal=http://10.21.2.166:2380,ip-10-21-2-166.ec2.internal=http://10.21.2.166:7001

It results in:

Feb 27 16:42:23 ip-10-21-1-66.ec2.internal writer_process[2506]: 2015/02/27 16:42:23 etcd: error validating peerURLs ip-10-21-1-43.ec2.internal=http://10.21.1.43:2380,ip-10-21-1-43.ec2.internal=http://10.21.1.43:7001,ip-10-21-2-166.ec2.internal=http://10.21.2.166:2380,ip-10-21-2-166.ec2.internal=http://10.21.2.166:7001: member count is unequal

Just to give some background, originally I was trying to bootstrap (via public discovery) a 3-node cluster but experienced the issue detailed #2325. This was due to the nodes starting-up with a gap of over 60 seconds and resulting in only two nodes successfully joining. However, my behaviour was slightly different in that one of the nodes was elected leader:

Feb 27 10:09:44 ip-10-21-2-166.ec2.internal writer_process[772]: 2015/02/27 10:09:44 discovery: found peer 9151b8e40b023e27 in the cluster
Feb 27 10:09:44 ip-10-21-2-166.ec2.internal writer_process[772]: 2015/02/27 10:09:44 discovery: found peer bd983c7de20202fc in the cluster
Feb 27 10:09:44 ip-10-21-2-166.ec2.internal writer_process[772]: 2015/02/27 10:09:44 discovery: found self ac0201e0c386c70b in the cluster
Feb 27 10:09:44 ip-10-21-2-166.ec2.internal writer_process[772]: 2015/02/27 10:09:44 discovery: found 3 needed peer(s)
...
Feb 27 10:09:45 ip-10-21-2-166.ec2.internal writer_process[772]: 2015/02/27 10:09:45 raft: ac0201e0c386c70b [q:2] has received 2 votes and 0 vote rejections
Feb 27 10:09:45 ip-10-21-2-166.ec2.internal writer_process[772]: 2015/02/27 10:09:45 raft: ac0201e0c386c70b became leader at term 2

If I try to start an etcd instance via public discovery, it starts in proxy mode (which is expected behaviour because it thinks there are 3 instances). Trying to change cluster using etcdctl member add for that doesn't work - #2380 perhaps? Although it said it had successfully added the instance it remained in an unhealthy state.

**Comment by yichengq** [comment]
@wsimmonds We expect the peer urls to join the cluster is exactly the advertise-peer-urls of the new bootstrapped member. This is mostly for safety, ensures everything behaves correctly, and errors as early as possible. You should add the correct peer urls into the cluster.

This case is interesting. Could you reproduce it? I'd like to dig more into it in a new issue.

**Comment by wsimmonds** [comment]
@yichengq I will attempt to create a reliable complete set of steps to reproduce the issue and post it here when done.

I understand an expectation of matching the initial-advertise-peer-urls, and in my instance they do match? Here is some config extract from .1.66:

 -advertise-client-urls http://10.21.1.66:2379,http://10.21.1.66:4001 \
  -listen-peer-urls http://0.0.0.0:2380,http://0.0.0.0:7001 \
  -initial-advertise-peer-urls http://10.21.1.66:2380,http://10.21.1.66:7001 \
  -initial-cluster-state existing \
  -initial-cluster ip-10-21-1-66.ec2.internal=http://10.21.1.66:2380,ip-10-21-1-66.ec2.internal=http://10.21.1.66:7001,ip-10-21-1-43.ec2.internal=http://10.21.1.43:2380,ip-10-21-1-43.ec2.internal=http://10.21.1.43:7001,ip-10-21-2-166.ec2.internal=http://10.21.2.166:2380,ip-10-21-2-166.ec2.internal=http://10.21.2.166:7001

**Comment by yichengq** [comment]
@wsimmonds Please open a new issue because it is another problem.

It maintains a cluster info in etcd cluster too. Please check
https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#list-members or `etcdctl member list` to see whether they are match.

**Comment by timhaak** [comment]
Hi

I'm having the same problem when using -initial-cluster-state existing.

Double checked and no duplicates. 

2015/03/02 16:33:03 no data-dir provided, using default data-dir ./mojo5.etcd
2015/03/02 16:33:03 etcd: listening for peers on http://0.0.0.0:2380
2015/03/02 16:33:03 etcd: listening for client requests on http://0.0.0.0:2379
2015/03/02 16:33:03 etcd: listening for client requests on http://0.0.0.0:4001
2015/03/02 16:33:03 etcdserver: name = mojo5
2015/03/02 16:33:03 etcdserver: data dir = mojo5.etcd
2015/03/02 16:33:03 etcdserver: member dir = mojo5.etcd/member
2015/03/02 16:33:03 etcdserver: heartbeat = 100ms
2015/03/02 16:33:03 etcdserver: election = 1000ms
2015/03/02 16:33:03 etcdserver: snapshot count = 10000
2015/03/02 16:33:03 etcdserver: advertise client URLs = http://192.168.222.3:2379,http://192.168.222.3:4001
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4bf782]

goroutine 1 [running]:
github.com/coreos/etcd/etcdserver.startNode(0xc208046210, 0x0, 0x0, 0x0, 0xc208038820, 0x0, 0x0, 0x508760, 0xc208031750)
	/home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:78 +0xd2
github.com/coreos/etcd/etcdserver.NewServer(0xc208046210, 0xc2080703f0, 0x0, 0x0)
	/home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:171 +0x7cc
github.com/coreos/etcd/etcdmain.startEtcd(0xc208088000, 0x0, 0x0, 0x0)
	/home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:162 +0x15ee
github.com/coreos/etcd/etcdmain.Main()
	/home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:58 +0x1fc
main.main()
	/home/core/share/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/main.go:48 +0x1de

goroutine 5 [syscall]:
os/signal.loop()
	/home/core/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/home/core/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 12 [runnable]:
net/http.(*persistConn).readLoop(0xc208046420)
	/home/core/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/home/core/go/src/net/http/transport.go:660 +0xc9f

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc208046420)
	/home/core/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/home/core/go/src/net/http/transport.go:661 +0xcbc

goroutine 11 [sleep]:
net.func·019()
	/home/core/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/home/core/go/src/net/dnsclient_unix.go:269 +0x20c

**Comment by wsimmonds** [comment]
@timhaak - I have got mine working now, but only by listening on a single peer port and calling etcdctl member add prior to starting the node (which I hadn't read/understood previously). My issue seems to have been a combination of several others which are already on the issues list and I'll post more details later or tomorrow.

Prior to starting your instance, have you done etcdctl member add <name> http://<ip>:2380?

**Comment by timhaak** [comment]
Yes think I'm doing something wrong. Was more that I assume it should say x wrong not give run time error. 

Sorted out what I needed on my side so not critical to me :) 

I should have been using proxy not existing. Was a misunderstanding of the model on my side. I assumed you bootstrapped then added all the servers and they decide between themselves which were active and which slave (proxy).

**Comment by kelseyhightower** [comment]
@timhaak This correct. Everything in etcd 2.0.0 is explicit now. @yichengq Is there a new ticket for the nil pointer issue?

**Comment by yichengq** [comment]
@kelseyhightower This one is the issue to track the panic error. Will fix it later.

**Comment by wsimmonds** [comment]
@yichengq I've now had time to create a new cluster and work out the exact steps necessary to reliably (at least in my case!) reproduce the panic seen above:

- Start up a new 3-node cluster (in my case, I used Public Discovery but I doubt that matters) with etcd v2.0.3
- Remove 1 node (etcdctl member remove & take it offline)
- Create new node but don't start etcd yet. Configure/start as follows:
  - initial-cluster-state should be existing 
  - initial-cluster should contain the other peers but NOT this one
- Start the new node without having called etcd member add and it should panic

In my case it's listening on 2739/4001 and 2380/7001, not sure if that makes a difference.

Hopefully that will be enough for you to re-create the scenario, otherwise let me know and happy to help more.
