### ISSUE TITLE
etcd level logging

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2398]
https://github.com/coreos/etcd/pull/2367#commitcomment-9963091

Current etcd logs all things to Stderr. Separate logs into several levels(e.g., warning, info, debug) can make log file easier to read, and give users the control of log verbosity.

For example, when the remote is disconnected, local keeps attempting to build the connection. The details of each attempt can help debug, but the fact that we are attempting to connect to the remote is enough for users to know what is happening.

/cc @barakmich

**Comment by xiang90** [comment]
we are going to use https://github.com/coreos/pkg/tree/master/capnslog

**Comment by philips** [comment]
@yichengq Can you please expand the description to provide an example of how this would work?

**Comment by yichengq** [comment]
@philips More description is given.
We will move to https://github.com/coreos/pkg/tree/master/capnslog, and it provides level logging natively.

**Comment by philips** [comment]
I would like to see this include HTTP client request logs so I can debug simple things like is etcd seeing a request from my client. Essentially dump the path, verb and client IP.

**Comment by philips** [comment]
I think this should be done in etcd 2.1.0. It is rather frustrating to not be able to debug the request logs.

**Comment by yichengq** [comment]
followed up by #2707
