### ISSUE TITLE
Duplicate updates

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#2399]
Using python-etcd, I started a loop, listening for updates recursively on a directory.  Then I used etcdctl to repeatedly set a value in a subdirectory.  Each time I set the value, I get two updates in python for the key that I set with consecutive etcd_index values and different raft_index values.  Both updates seem to show the same update event i.e. they have the same prev_node and new value and all other fields seem the same.

Either I'm doing something wrong or it seems wasteful (or possibly bugged?) to duplicate the update like this.

The URLs that python-etcd is generating look like this:

    /v2/keys/calico/?waitIndex=48&recursive=true&wait=true
    /v2/keys/calico/?waitIndex=49&recursive=true&wait=true

The version I'm using is etcd-v2.0.3-linux-amd64.

**Comment by kelseyhightower** [comment]
@yichengq Can you take a look at this one?

**Comment by yichengq** [comment]
Could you give me a more concrete example with URLs that python-etcd generated? Based on your description, i cannot figure out whether the problem comes from etcd or python-etcd.

My guess so far is that the event index returned > 49, so if you wait on 48 and 49, you will get two events.

**Comment by fasaxc** [comment]
I'll try to boil it down and double check my index calculation logic. Maybe
I accidentally incremented the request index instead of the new index from
the response.

**Comment by yichengq** [comment]
How is it going so far?

**Comment by fasaxc** [comment]
I've boiled this down, I wait on say, index 80, then the response I get has etcd_index == 79, so I increment from 79 and get back to 80 and poll again.

I used this logic to poll:

```
import logging
import etcd
logging.basicConfig(level=logging.DEBUG)
client = etcd.Client()
client.set("/repro/foo/bar", "foobar")
initial_dump = client.read("/repro/", recursive=True)
last_etcd_index = initial_dump.etcd_index
while True:
    print
    print "Waiting on index", (last_etcd_index + 1)
    response = client.read("/repro/",
                           wait=True,
                           waitIndex=last_etcd_index + 1,
                           recursive=True,
                           timeout=0)
    print "Etcd response:", response
    print "Response index:", response.etcd_index
    last_etcd_index = response.etcd_index
```

A single set from etcdctl:
```
./etcdctl set /repro/foo/bar baz
```
Gives this output:
```
$ python ./etcdrepro.py 
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:urllib3.connectionpool:"PUT /v2/keys/repro/foo/bar HTTP/1.1" 200 190
DEBUG:urllib3.connectionpool:"GET /v2/keys/repro/?recursive=true HTTP/1.1" 200 257

Waiting on index 83
DEBUG:urllib3.connectionpool:"GET /v2/keys/repro/?waitIndex=83&recursive=true&wait=true HTTP/1.1" 200 None
Etcd response: <class 'etcd.EtcdResult'>({'newKey': False, '_prev_node': <class 'etcd.EtcdResult'>({'newKey': False, '_children': [], 'createdIndex': 82, 'modifiedIndex': 82, 'value': u'foobar', 'expiration': None, 'key': u'/repro/foo/bar', 'ttl': None, 'action': None, 'dir': False}), 'raft_index': 313051, '_children': [], 'createdIndex': 83, 'modifiedIndex': 83, 'value': u'baz', 'etcd_index': 82, 'expiration': None, 'key': u'/repro/foo/bar', 'ttl': None, 'action': u'set', 'dir': False})
Response index: 82

Waiting on index 83
DEBUG:urllib3.connectionpool:"GET /v2/keys/repro/?waitIndex=83&recursive=true&wait=true HTTP/1.1" 200 None
Etcd response: <class 'etcd.EtcdResult'>({'newKey': False, '_prev_node': <class 'etcd.EtcdResult'>({'newKey': False, '_children': [], 'createdIndex': 82, 'modifiedIndex': 82, 'value': u'foobar', 'expiration': None, 'key': u'/repro/foo/bar', 'ttl': None, 'action': None, 'dir': False}), 'raft_index': 313058, '_children': [], 'createdIndex': 83, 'modifiedIndex': 83, 'value': u'baz', 'etcd_index': 83, 'expiration': None, 'key': u'/repro/foo/bar', 'ttl': None, 'action': u'set', 'dir': False})
Response index: 83

Waiting on index 84
DEBUG:urllib3.connectionpool:"GET /v2/keys/repro/?waitIndex=84&recursive=true&wait=true HTTP/1.1" 200 None

```
Have I misunderstood the relationship between `waitIndex` and `etcd_index`?

**Comment by yichengq** [comment]
@fasaxc etcd_index in wait operation is the etcd index when you starts to watch, not the one when you ends watching. You should use the modified index of the return result plus one as the next wait index.

**Comment by fasaxc** [comment]
Ah OK, I'll give that a go!

**Comment by xiang90** [comment]
@fasaxc I assume this is solved. Reopen this if there is still a problem. Thanks for reporting!
