### ISSUE TITLE
etcdctl: port to use github.com/coreos/etcd/client

### ISSUE THREAD

**Issue by philips** [coreos/etcd#2411]
We need to port etcdctl to client to make sure the API makes sense and that the implementation works.

**Comment by ecnahc515** [comment]
I wouldn't mind taking a stab here, but go-etcd has a ton of logic explicitly just for dealing with curl examples and debugging info. Do we want to port that stuff over in this process as well?

It would be trivial to port things over to the new commands (except a few that are missing), but there's some client level stuff that wont be as quick.

**Comment by xiang90** [comment]
@ecnahc515 I do not think so. Just port enough for the command to work well. I played with it a little. And I really want to get rid of the func pointers all over the place.

**Comment by ecnahc515** [comment]
Alright, I can easily do the trivial parts. I would really like to make sure this new client API works well enough for use in other projects, as I've started using it. So getting it into etcdctl will be a great start for showing us what it needs.

**Comment by xiang90** [comment]
@ecnahc515 Yes. That is the intention. 

But the etcdctl also needs a cleanup. So I would suggest you to rewrite the command one by one rather than trying to modify the helper funcs.

**Comment by ecnahc515** [comment]
Ok. I'll do that. I can see where it might be a problem to try and use all the helpers.

**Comment by yichengq** [comment]
progress at #2913

**Comment by xiang90** [comment]
closed by #3083
