### ISSUE TITLE
etcd on windows

### ISSUE THREAD

**Issue by rismoney** [coreos/etcd#2419]
I am testing out the etcd-v2.0.4 windows amd64

Several questions-
Should the binaries for etcd and etcdctl be renamed as .exe?
It does not appear that the command line switches seem to be working.

Is etcd on windows only at the point of building succesfully or has functionality been confirmed?
I am trying to run etcd as a proxy, that points to a etcd cluster elsewhere.
Any guidance would be appreciated!

**Comment by kelseyhightower** [comment]
@rismoney We don't activity test etcd on windows here, so we only provide the binaries. Are you getting any error messages?

**Comment by rismoney** [comment]
```shell
C:\etcd-testing\etcd\etcd-v2.0.4-windows-amd64>etcd --proxy on readonly --listen-client-urls 127.0.0.1:8080 --initial-cluster infra0=http://foo.example.com:4001

2015/03/03 09:49:47 no proxy data-dir provided, using default proxy data-dir ./default.etcd
2015/03/03 09:49:47 proxy: using peer urls [http://localhost:2380 http://localhost:7001]
2015/03/03 09:49:48 etcdserver: could not get cluster response from http://localhost:2380: Get http://localhost:2380/members: net/http: request canceled while waiting for connection
2015/03/03 09:49:49 etcdserver: could not get cluster response from http://localhost:7001: Get http://localhost:7001/members: net/http: request canceled while waiting for connection
2015/03/03 09:49:49 proxy: etcdserver: could not retrieve cluster information from the given urls
2015/03/03 09:49:49 proxy: listening for client requests on localhost:2379
2015/03/03 09:49:49 proxy: listening for client requests on localhost:4001
```

Am I trying to invoke the proxy wrong?

**Comment by yichengq** [comment]
@rismoney use `--proxy on` or `--proxy readonly`. That should make you continue to explore. I will open an issue for flag parsing stuff.
The clustering command example is here: https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static

**Comment by yichengq** [comment]
@rismoney Any progress?

**Comment by xiang90** [comment]
@rismoney I am closing this due to low activity. If you have tried what @yichengq suggested and it still does not work, please reopen this issue. Thanks!

**Comment by rismoney** [comment]
Apparently i didnt get notifications for this issue. The proxy works perfectly on windows.  

My issue, for interested readers was the URLs for peer abd advertisements on the etcd cluster needed to be changed from 0.0.0.0 to actual hostnames.  This way the proxy does not get confused when it learns who to use and the IP space is then incorrect from the proxy perspective.
