### ISSUE TITLE
Brought up a 2-node cluster, two different clusters...

### ISSUE THREAD

**Issue by iamthemuffinman** [coreos/etcd#2424]
I brought up a 2-node cluster using the same cloud-config file and ended up with two different clusters somehow. Here's my [cloud-config](https://gist.github.com/iamthemuffinman/09ec9acc971a6206f6f8). When I ```fleetctl list-machines``` on either of the nodes, they only show that specific machine in the cluster, not both. I checked the output of ```journalctl -u etcd``` on both machines and they both show the same discovery token, but they both state they changed themselves to the leader. Any help would be greatly appreciated.

**Comment by kelseyhightower** [comment]
@iamthemuffinman Setting up a two node cluster is not a good idea. See this guide for more details: https://coreos.com/docs/cluster-management/scaling/etcd-optimal-cluster-size

As to why you are having this issue, I need to take a look at the cloud configs and maybe the logs from both etcd machines. Happy to help figure this out in IRC too.

**Comment by iamthemuffinman** [comment]
Doh! Didn't see that. I'm gonna rebuild the cluster using 3 nodes this time and see if I still have the issue. I'll report back later today.
