### ISSUE TITLE
etcd --discovery-srv and initial configuration

### ISSUE THREAD

**Issue by vtolstov** [coreos/etcd#2426]
I have 100 nodes and want to run etcd on it, i'm prefer discovery-srv method to provide nodes addresses.
But as i see i can't use this in initial configuration, does it possible to determine that cluster is empty and doing initial configuration while bootstrap?

**Comment by kelseyhightower** [comment]
@vtolstov Ideally you will run an active etcd cluster of 3 - 5 nodes and the other nodes will run etcd in proxy mode. Using the DNS bootstrap, you can set aside 3 - 5 DNS entries that resolve to the active nodes. Then you can create the DNS SRV record as described in the DNS bootstrap guide.

The same DNS SRV record can be used to point the etcd proxy, which runs on all the other machines, to the active cluster members.

**Comment by vtolstov** [comment]
@kelseyhightower i'm think about 9 nodes in active mode and all other in failover mode.

**Comment by vtolstov** [comment]
As i see etcd can't combine initial-cluster and discovery-srv.. why?

My use case - try to discovery-srv if cluster info is absent - use initial-cluster. 
```
etcd --data-dir /var/lib/etcd/   --advertise-client-urls 'http://selfip.ru:2379,http://selfip.ru:4001'  --listen-peer-urls 'http://selfip.ru:2380,http://selfip.ru:7001' --listen-client-urls 'http://selfip.ru:2379,http://selfip.ru:4001' --initial-cluster 'default=http://selfip.ru:2380,default=http://selfip.ru:7001' --initial-advertise-peer-urls 'http://selfip.ru:2380,http://selfip.ru:7001' --discovery-srv selfip.ru
2015/03/04 05:37:03 etcd: error verifying flags, multiple discovery or bootstrap flags are setChoose one of "initial-cluster", "discovery" or "discovery-srv"
```

**Comment by kelseyhightower** [comment]
@vtolstov Using the discovery-srv means that you want to get your inital-cluster from DNS. You will need to write a wrapper script to check the DNS SRV record and adjust your configuration as needed. The goal of the initial bootstrapping is to be very explicit.

**Comment by vtolstov** [comment]
@kelseyhightower i know about wrapper, but why not try to form cluster from dns and if it fails, try fallback from initial-cluster?

**Comment by hickey** [comment]
@kelseyhightower Would it not be better to get some better documentation in the clustering.md document? There is a significant number of questions that this document does not answer and even if one attempts to follow the DNS Discovery section, it does not work. 

If one attempts to follow the bootstrapping instructions for DNS verbatim, then one gets the message that the node can not be found in the initial cluster configuration. Then one attempts to add the -initial-cluster to the command to create the cluster and gets the messages that are talked about above. 

Seriously, is it too much to ask that someone spend a few mins to add another paragraph or two to the bootstrapping DNS section to wipe away some of the fog and discuss how to properly bring up an etcd cluster using DNS?

**Comment by damm** [comment]
I used the DNS Verbatim and it worked out for me.  

```
etcd -name `hostname` -discovery-srv domain.com -initial-advertise-peer-urls http://`hostname`.domain.com:2380 -initial-cluster-token shadowstoked -initial-cluster-state new -advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379
```

Although I do use a Chef cookbook I wrote to deploy it.  I did follow the guide to success.

P.S. if you get the error message the node cannot be found it's likely your discovery settings are not matching with the advertise peer urls.  Such as:

domain.com has your key; but the actual servers are internal.domain.com; you will want to update the command line to like:

```etcd -initial-advertise-peer-urls http://`hostname -f`:2380```

Provided hostname -f gives the FQDN otherwise make it right.
