### ISSUE TITLE
Standby Internal Error

### ISSUE THREAD

**Issue by AdoHe** [coreos/etcd#2428]
I use etcd 0.4.6 and create a cluster with three nodes, after some time I found there is just one node can work, when visit other two nodes, you will get `Standby Internal Error`

**Comment by yichengq** [comment]
@AdoHe For 0.4, it does auto removal of dead members.
You could invalidate this by set infinite long removal delay: https://github.com/coreos/etcd/blob/release-0.4/Documentation/api.md#set-cluster-config

**Comment by AdoHe** [comment]
@yichengq I will upgrade to the latest version. Thanks anyway :)
