### ISSUE TITLE
httptypes: unmarshal memberCollection failure

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2429]
From https://github.com/coreos/go-etcd/issues/189

The https://github.com/coreos/etcd/commit/4a77760f56d9ae6ca86a2250aeb3aed0f971a20c breaks the backward compatibility:
https://github.com/coreos/go-etcd/blob/master/etcd/client.go#L315

**Comment by ematpl** [comment]
Thanks, @yichengq!

**Comment by yichengq** [comment]
@ematpl 
The PR goes here: https://github.com/coreos/go-etcd/pull/201
It is good to break go-etcd dependency on etcd because the dependency is little.
Maybe extract necessary types into a separate package and import it in the future if necessary.
