### ISSUE TITLE
Use wrong url to add itself to discovery.etcd.io service

### ISSUE THREAD

**Issue by leeychee** [coreos/etcd#2430]
etcd version: 0.4.7

when `discovery=http://192.168.97.190:4001/v2/keys/_etcd/registry/7acda9caa786690d4ff7402411c92db6`, It woks fine.

but when
`discovery=http://192.168.97.190/7acda9caa786690d4ff7402411c92db6`, it does not work.
It uses wrong url `http://192.168.97.190//7acda9caa786690d4ff7402411c92db6/node_name` to add itself.

So, how should I do to avoid this issue?

**Comment by xiang90** [comment]
@yichengq Can you please take a look?

**Comment by yichengq** [comment]
@leeychee This is designed in this way: https://github.com/coreos/etcd/blob/release-0.4/Documentation/discovery-protocol.md
For public discovery service, we redirect it into /v2/keys/. If you have interest for it: https://github.com/coreos/discovery.etcd.io

**Comment by leeychee** [comment]
@yichengq The point is when use discovery.etcd.io service, etcd use `http://192.168.97.190//7acda9caa786690d4ff7402411c92db6/node_name`. There are two `/` . 

Public discovery service can handle this. but got code 301 with private discovery.etcd.io service.

200: `curl -v http://192.168.97.190/7acda9caa786690d4ff7402411c92db6`
301: `curl -v http://192.168.97.190//7acda9caa786690d4ff7402411c92db6`

**Comment by yichengq** [comment]
Do you use https://github.com/coreos/discovery.etcd.io to build your private discovery service? Could you list the reproduce procedure step by step? I don't know how you get there.

**Comment by leeychee** [comment]
I use [timeincuk/discovery.etcd.io](https://registry.hub.docker.com/u/timeincuk/discovery.etcd.io/). 

1. start timeincuk/discovery.etcd.io docker in a coreos(1 node); It works fine. 
2.  request `http://192.168.97.190/new`, get `http://192.168.97.190/7acda9caa786690d4ff7402411c92db6`
3.  use this url as new coreos(CoreOS 607.0.0) cluster's discovery

cluster does not works. 

So, I turn on ETCD_VERY_VERY_VERBOSE=true. I found that, when etcd want to join the cluster, it request `http://192.168.97.190//7acda9caa786690d4ff7402411c92db6` rather than `http://192.168.97.190/7acda9caa786690d4ff7402411c92db6`.  Response is 301.

**Comment by yichengq** [comment]
@leeychee 
i cannot reproduce it. When I do `curl https://discovery.etcd.io//dbb1ff7f03dda42a916c591ef5a0aa37` on public discovery service, it works. Could you write a detailed steps to reproduce it?

**Comment by leeychee** [comment]
@yichengq 

1. It does work on public discovery service; 
2. My point is, url should not contain two `//`; 

Steps:

1. Get etcd 0.4.6 following by `https://github.com/coreos/etcd/releases/tag/v0.4.6`

2. Then 
```
# run etcd for discovery.etcd.io
./etcd

# run discovery.etcd.io
cd ~/github.com/coreos/discovery.etcd.io 
go run discovery.go -addr=":8087" -host="http://127.0.0.1:8087"

# Use discovery.etcd.io
curl http://127.0.0.1/new

ETCD_NAME=n2 ETCD_VERY_VERY_VERBOSE=true ./etcd -discovery="http://127.0.0.1:8087/ff64f740282ca051d5b611f10b17e582" -peer-bind-addr="127.0.0.1:8001" -bind-addr="127.0.0.1:5001"
```

Then, I got this 
```
[etcd] Mar 16 13:15:02.106 WARNING   | Using the directory n2.etcd as the etcd curation directory because a directory was not specified. 
[raft]13:15:02.107266 [n2 Term:0] no.snapshot.to.load
[etcd] Mar 16 13:15:02.107 DEBUG     | n2 finished load snapshot
[raft]13:15:02.107326 [n2 Term:0] readConf.open  n2.etcd/conf
[raft]13:15:02.107345 log.open.open  n2.etcd/log
[raft]13:15:02.107360 log.open.exist  n2.etcd/log
[raft]13:15:02.107407 open.log.append: finish 
[raft]13:15:02.107418 open.log.recovery number of log  0
[etcd] Mar 16 13:15:02.107 DEBUG     | The type of path n2.etcd/log is 61267
[etcd] Mar 16 13:15:02.107 INFO      | Discovery via http://127.0.0.1:8087 using prefix /ff64f740282ca051d5b611f10b17e582.
[go-etcd] Mar 16 13:15:02.107 DEBUG     | PUT /ff64f740282ca051d5b611f10b17e582/n2  [http://127.0.0.1:8087]
[go-etcd] Mar 16 13:15:02.107 DEBUG     | begin trail 1
[go-etcd] Mar 16 13:15:02.107 DEBUG     | send.request.to http://127.0.0.1:8087//ff64f740282ca051d5b611f10b17e582/n2 | method PUT 
[go-etcd] Mar 16 13:15:02.108 DEBUG     | recv.response.from http://127.0.0.1:8087//ff64f740282ca051d5b611f10b17e582/n2
[go-etcd] Mar 16 13:15:02.108 WARNING   | bad status code 301 
[go-etcd] Mar 16 13:15:02.108 DEBUG     | begin trail 2
[go-etcd] Mar 16 13:15:02.108 DEBUG     | send.request.to http://127.0.0.1:8087//ff64f740282ca051d5b611f10b17e582/n2 | method PUT 
[go-etcd] Mar 16 13:15:02.108 DEBUG     | recv.response.from http://127.0.0.1:8087//ff64f740282ca051d5b611f10b17e582/n2
[go-etcd] Mar 16 13:15:02.108 WARNING   | bad status code 301 
[go-etcd] Mar 16 13:15:02.108 DEBUG     | begin trail 3
[etcd] Mar 16 13:15:02.108 WARNING   | Discovery encountered an error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
[etcd] Mar 16 13:15:02.108 WARNING   | n2 failed to connect discovery service[http://127.0.0.1:8087/ff64f740282ca051d5b611f10b17e582]: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
[etcd] Mar 16 13:15:02.108 CRITICAL  | n2, the new instance, must register itself to discovery service as required
```

**Comment by yichengq** [comment]
It does happen. Will fix.

@jedsmith 
etcd sends request `https://discovery.etcd.io//701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false` to our public service, and it does work. But when it sends request `http://127.0.0.1:8087//bec8f13c57c459bb67e8a9538704ac02/n2` to a private discovery service, it fails. Do you know what magic does our public discovery service have?

**Comment by jedsmith** [comment]
When I try this from inside the ELB, our public discovery service sends me a 301 as well.

    core@discovery1 ~ $ curl -vvv -H "Host: discovery.etcd.io" "http://10.0.0.12//701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false"
    * About to connect() to 10.0.0.12 port 80 (#0)
    *   Trying 10.0.0.12...
    * Adding handle: conn: 0x7f0ac85cc750
    * Adding handle: send: 0
    * Adding handle: recv: 0
    * Curl_addHandleToPipeline: length: 1
    * - Conn 0 (0x7f0ac85cc750) send_pipe: 1, recv_pipe: 0
    * Connected to 10.0.0.12 (10.0.0.12) port 80 (#0)
    > GET //701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false HTTP/1.1
    > User-Agent: curl/7.30.0
    > Accept: */*
    > Host: discovery.etcd.io
    >
    < HTTP/1.1 301 Moved Permanently
    < Location: /701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false
    < Date: Mon, 16 Mar 2015 18:28:04 GMT
    < Content-Length: 91
    < Content-Type: text/html; charset=utf-8
    <
    <a href="/701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false">Moved Permanently</a>.

    * Connection #0 to host 10.0.0.12 left intact

Going through the ELB, it sends back a 200.

    [jed@jed ~]$ curl -vvv "http://discovery.etcd.io//701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false"
    * Hostname was NOT found in DNS cache
    *   Trying 54.153.65.49...
    * Connected to discovery.etcd.io (54.153.65.49) port 80 (#0)
    > GET //701d0770cc5894624e5c6335aa7eb7d8/_state?prevExist=false HTTP/1.1
    > User-Agent: curl/7.37.1
    > Host: discovery.etcd.io
    > Accept: */*
    >
    < HTTP/1.1 200 OK
    < Content-Type: application/json
    < Date: Mon, 16 Mar 2015 18:31:29 GMT
    < X-Etcd-Cluster-Id: 4c00833c2a0002
    < X-Etcd-Index: 402988822
    < X-Raft-Index: 816210502
    < X-Raft-Term: 1155772
    < Content-Length: 159
    < Connection: keep-alive
    <
    {"action":"get","node":{"key":"/_etcd/registry/701d0770cc5894624e5c6335aa7eb7d8/_state","value":"started","modifiedIndex":401808022,"createdIndex":401808022}}
    * Connection #0 to host discovery.etcd.io left intact

It is possible the ELB is correcting the request URL before sending it on. How does the client end up with a double-slashed URL? The configuration on the third-party Docker container needs to be fixed, I think. We specifically address this case in public discovery (I wrote the patch in coreos/discovery.etcd.io@61804c8) by trimming extra slashes if the passed in `--host` has trailing slashes.

This means if I run that container like this:

    docker run coreos/discovery.etcd.io --addr=:8080 --host=https://private-discovery.etcd.io////

The URLs returned by `127.0.0.1:8080/new` will only have one slash as expected.

A case could be made that the 301 itself is an issue, particularly since it returns `text/html` in spite of `Accept` (I'm guessing), but `/new` in the third-party Docker container really needs to be taught to not hand out double-slashed URLs. That's the real fix.

@leeychee I'm guessing you use that third-party build because it has support for changing the hostname. This was recently merged into our own and you might consider using it -- see the command line above.

**Comment by leeychee** [comment]
@jedsmith I'm using  [timeincuk/discovery.etcd.io](https://registry.hub.docker.com/u/timeincuk/discovery.etcd.io/) now, but thanks anyway.

**Comment by jedsmith** [comment]
@leeychee I see they merged my commit to allow configurable hosts. How are you calling the Docker container? It shouldn't be in a position where it hands out double-slashed URLs unless they've patched it.

**Comment by yichengq** [comment]
@leeychee quick fix:
```
diff --git a/discovery/discovery.go b/discovery/discovery.go
index 19ced31..4af346e 100644
--- a/discovery/discovery.go
+++ b/discovery/discovery.go
@@ -46,6 +46,7 @@ func (d *Discoverer) Do(discoveryURL string, name string, peer string, closeChan

        // prefix is prepended to all keys for this discovery
        d.prefix = strings.TrimPrefix(u.Path, "/v2/keys/")
+       d.prefix = strings.TrimPrefix(d.prefix, "/")

        // keep the old path in case we need to set the KeyPrefix below
        oldPath := u.Path
```

**Comment by leeychee** [comment]
@yichengq thx
