### ISSUE TITLE
There should be a full tutorial for upgrading from etcd 0.4.x to etcd 0.2.x

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#2432]
This guide should also cover etcd migrations and running etcd in fully manage mode outside of an CoreOS cluster.

**Comment by rosskukulinski** [comment]
Thanks @kelseyhightower, this would be awesome.  I'm available to do early testing of the guide on the following platforms:
* bare-metal w/ pxe boot
* Cloud w/ Rackspace

**Comment by kelseyhightower** [comment]
Ok, This is my highest priority this week.

**Comment by xiang90** [comment]
@kelseyhightower Any progress on this?

**Comment by AdoHe** [comment]
This is awesome :+1:

**Comment by lawrencewu** [comment]
great!

**Comment by yichengq** [comment]
The migration method is documented here:
https://github.com/coreos/etcd/blob/master/Documentation/backward_compatibility.md#data-directory-migration

@rosskukulinski @AdoHe @lawrencewu Give it a try?

**Comment by rosskukulinski** [comment]
Thanks @yichengq - will find some time to review next week

**Comment by AdoHe** [comment]
@yichengq  I did migration in our real production, and it just works.

**Comment by yichengq** [comment]
@AdoHe Glad to know!
