### ISSUE TITLE
discovery: figure out etcd discovery method + ACLs

### ISSUE THREAD

**Issue by philips** [coreos/etcd#2436]
When we add ACLs (#2242) to etcd we will need to consider how the user will use an ACL protected etcd cluster to bootstrap another cluster. Right now we just assume a client can write/read unauthenticated.

/cc @barakmich

**Comment by xiang90** [comment]
@philips The first step is to create a `public` role. All `anonymous` clients has the `public` role.

/cc @kelseyhightower @barakmich

**Comment by barakmich** [comment]
Fixed by the "guest" role in #2654
