### ISSUE TITLE
document the support for writing the wal and snapshots on separate disks 

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#2442]
etcd supports writing the write ahead log and snapshots in different directories, the database administrator can optimize log compaction (snapshotting) by using separate disks for the log (wal) and the snapshot.

This is easy to do in the places we need it most. While a single SSD can be costly in the cloud, multiple  disks (non-SSD) are relatively inexpensive.

**Comment by xiang90** [comment]
This is not only a doc issue. etcd needs to support snap-dir and wal-dir separately.

**Comment by kelseyhightower** [comment]
@xiang90 I think the snapshots are in a different director under the data dir

So we can mount

/var/lib/etcd
/var/lib/etcd/snapshot

**Comment by xiang90** [comment]
@kelseyhightower Oh, right. You can do that without the support from etcd.

**Comment by xiang90** [comment]
@kelseyhightower After thinking this more, I found it would be hard for people to mount. 

They have to understand the data dir layout of etcd and create all the dirs before initialize etcd.

/cc @philips Any opinion on this one?

**Comment by philips** [comment]
I would rather we have explicit flags/environment variables for each dir instead of having the user poke around and assume things about the etcd data layout.

**Comment by AdoHe** [comment]
@xiang90 @philips I totally agree with philips, we should have explicit flags/environment for each dir, have default value for each dir, and document it.
