### ISSUE TITLE
Ports 4001 and 7001 are closed

### ISSUE THREAD

**Issue by iamthemuffinman** [coreos/etcd#2445]
When I bring up a 3-node cluster on bare-metal, the first 2 nodes come up fine but with all ports closed except the ssh port. I verified this by looking at iptables and nmap via the toolbox container. The 3rd node doesn't even contain the SSH key listed in the cloud-config. Here's my [cloud-config](https://gist.github.com/iamthemuffinman/d6fd65480eed7292c422).

EDIT:

When I pull up a 3-node cluster in Vagrant, it all works as expected (Using the coreos-vagrant cloud-config). So I'm inclined to believe it's my cloud-config that's the issue. @kelseyhightower The cloud-config I'm using is the one you had modified.

**Comment by xiang90** [comment]
@kelseyhightower Can you take a look?

**Comment by iamthemuffinman** [comment]
@kelseyhightower Find anything out about this?

**Comment by iamthemuffinman** [comment]
The ports I opened didn't persist after a reboot so I'm at a loss as to why the ports are closed in the first place.
