### ISSUE TITLE
Read Consistency Problem

### ISSUE THREAD

**Issue by AdoHe** [coreos/etcd#2452]
Hi guys, I noticed that you removed `Read Consistency` part from the 2.0 documentation. There is a problem I just get confused: in etcd v0.4.6, whether the leader will handle all the client requests, no matter read or write? the follower will not handle client requests ? as you moved `consistent` flag in the 2.0, so how about a client read from the follower? it will get the most up-to-date value?

**Comment by xiang90** [comment]
Please refer the doc at https://github.com/coreos/etcd/blob/master/Documentation/backward_compatibility.md#key-value-api

**Comment by AdoHe** [comment]
so it means within etcd cluster, every node(leader or non-leader) can handle client read requests, the follower has no need to redirect client read requests to leader node, but if `consistent` flag set to true, just the leader node can handle client read&write requests.

**Comment by AdoHe** [comment]
@xiang90 is it right?

**Comment by yichengq** [comment]
Yes. This is how 0.4 works.

In 2.0, the normal read operations provides the same consistency guarantees with the 0.4.6 read operations with consistent flag set.

**Comment by AdoHe** [comment]
@xiang90 @yichengq Thanks very much :)
