### ISSUE TITLE
raft pkg logging

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2457]
@yichengq @bdarnell

raft pkg deserves a separate logger. we have a few options here:

1. add an interface
2. use a pkg level global logger like juju/loggo
3. your opinions 

we are also trying to solve this problem in etcd. etcdserver can be embedded too.

**Comment by bdarnell** [comment]
We use https://github.com/golang/glog in cockroach. If etcd used glog, we'd run into trouble because you vendor your dependencies with rewritten imports and the two sets of init() hooks would collide. (This is likely to be a problem for any logging library and is one of the reasons to break raft out into a separate project).

I think that since we want to make raft available as a reusable library, we have to make a logging interface so people can integrate with whichever logging system they choose. The question is what that interface should look like. Should it look like the standard library's log.Logger or have levels like glog and loggo (which would be ignored when using the standard log.Printf)? I think a multi-level logger is a good idea.

**Comment by xiang90** [comment]
> I think that since we want to make raft available as a reusable library.

Definitely, we are trying hard not involve any etcd/cockroach specific logic into raft as well as achieving clean API.

>  we have to make a logging interface so people can integrate with whichever logging system they choose.

Sure. The default one would be a thin wrapper around default log probably.

>  I think a multi-level logger is a good idea.

What levels do you have in mind? I can work on it and let you review.

**Comment by bdarnell** [comment]
Log levels error/warning/info/debug seem pretty universal. Glog has a numbered verbosity level which is effectively an infinite number of "debug" levels, but that's probably too fine-grained.

**Comment by marineam** [comment]
On Fri, Mar 6, 2015 at 6:56 PM, Ben Darnell <notifications@github.com>
wrote:

> We use https://github.com/golang/glog in cockroach. If etcd used glog,
> we'd run into trouble because you vendor your dependencies with rewritten
> imports and the two sets of init() hooks would collide. (This is likely to
> be a problem for any logging library and is one of the reasons to break
> raft out into a separate project).
>

FWIW this could be cleaned up by running `godep restore` on etcd to revert
the import rewrites and then vendoring the result in your project. I did
that when importing etcd into another project that also used godep. The
only library I had to be careful about was protobuf which needs to stay in
sync with any autogenerated protobuf code.

**Comment by bdarnell** [comment]
@marineam I must be missing something. Etcd's imports were rewritten with `godep save -r`, but `godep restore` doesn't have a `-r` flag to undo the damage. How do you get an etcd that will actually use the results of `godep restore`?

In any case, even if this works it compels anyone who depends on etcd to use import rewriting, which is not our preference (we're using glock instead). It's nice to have the option available when necessary, but it would be better to leave etcd as a leaf in the dependency graph and move the reusable parts into separate libraries that don't depend on import rewriting.

**Comment by marineam** [comment]
@bdarnell hm, if godep restore doesn't undo rewrites then I don't remember what I did to clean that up. godep gets confusing at times... Anyway, agreed that things are a lot easier if reusble parts are on their own and it is just the 'main' package that gets bundled with vendored/rewritten libs. On the other hand fewer git repos are easier to keep track of. :)

**Comment by xiang90** [comment]
@marineam @bdarnell We have been very careful about the dependency inside raft pkg. We hope it can be a reusable component and easy to manage. The only external dependency is `context`. We can even remove that dependency it necessary.

**Comment by xiang90** [comment]
@bdarnell OK. working on it. should have something ready for review on Monday.

**Comment by bdarnell** [comment]
And gogoproto. Cockroach currently contains two copies of gogoproto: one for raft and one for itself. This isn't a problem, but it would be nice to clean it up.

**Comment by xiang90** [comment]
closed via https://github.com/coreos/etcd/pull/2460
