### ISSUE TITLE
etcd timeout documentation and tests

### ISSUE THREAD

**Issue by AdoHe** [coreos/etcd#2458]
is there any tests about timeout within etcd 0.4.6?

**Comment by yichengq** [comment]
No.

We will document the usage of timeouts in 2.0 in the future.

**Comment by AdoHe** [comment]
@yichengq cool. a little bit tests even better.

**Comment by yichengq** [comment]
IMO unit tests for timeouts are enough.

**Comment by AdoHe** [comment]
@yichengq I mean request timeout not election timeout

**Comment by xiang90** [comment]
We are not going to support 0.4.x. This issue becomes irrelevant.
