### ISSUE TITLE
Is it possible to automatically create a unique and isolated key namespace for each unit started by fleet

### ISSUE THREAD

**Issue by eric-nuaa** [coreos/etcd#2462]
I know there will be authentication and ACL in etcd soon (https://github.com/coreos/etcd/blob/master/Documentation/rfc/api_security.md). However I think it will be helpful to automatically create a unique and isolated key namespace every time when a new unit is started by fleet (e.g., v2/keys/units/myunit), and the unit is ONLY allowed to read/writer under this key namespace. In this way, when user starts their own unit via fleet, they do not need to worry about the key-values resources of their unit will be read/write by others. This is a key to achieve multi-tenant.

And I think the key namespace should be transparent to the unit, i.e., the unit does not know it at all, just like it could read/write the whole etcd. I do not think it is a good idea to expose the whole etcd to the end user's unit.

The idea is similar with the namespace in Docker for containers.

**Comment by yichengq** [comment]
@eric-nuaa The unit management is done in docker and fleet, so they should be responsible for ACL management IMO.
Fleet/docker could talk to etcd, set unit user to each unit, and assign it to the unit.

**Comment by eric-nuaa** [comment]
@yichengq Agree, I will ask this in fleet, thanks!
