### ISSUE TITLE
Disaster Recovery doesn't work? (w00t)

### ISSUE THREAD

**Issue by haf** [coreos/etcd#2463]
I'm simulating a major outage with my small vagrants, and in this case I've gotten a full disk, destroyed a node and "accidentally" rebooted the machines, so that the quorum was lost.

You can read all about that here: https://github.com/deis/deis/issues/3235

But besides that, the [docs on disaster recovery](https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery) don't seem to work, because I get 'No help for "backup" command"'. From there's it's unclear how to proceed.

When trying this:

```
 sudo env ETCD_DATA_DIR=/var/lib/etcd etcd -force-new-cluster
```

You're met with:

```
flag provided but not defined: -force-new-cluster
```

**Comment by xiang90** [comment]
what version of etcd were you running? The doc is for etcd 2.0 release.

**Comment by xiang90** [comment]
@haf From the dies issue, you were running 0.4.7. Can you please try 2.0? Thanks for reporting.

**Comment by haf** [comment]
How do I do that? I'm using coreos stable?

**Comment by haf** [comment]
Isn't it stable?

**Comment by haf** [comment]
You latest release doesn't contain v2.0 even (alpha)

![screen shot 2015-03-08 at 18 12 26](https://cloud.githubusercontent.com/assets/193115/6546722/b6cc374e-c5be-11e4-9b49-f49421979e53.png)

**Comment by xiang90** [comment]
@haf 

Putting the new version of etcd into CoreOS image involves some extra work. We need to ensure the upgrading experience is smooth enough for most people. We have done most of the hard work and will release etcd 2.0.x into CoreOS image soon.

At this moment, you can 1) try 2.0 by installing the released binary 2) wait for us release 2.0 in CoreOS.

**Comment by haf** [comment]
How? Is there a package manager for CoreOS? I'm new to this so I haven't been able to find anything about it? Does that still rescue my data?

**Comment by xiang90** [comment]
@haf 
> I'm new to this so I haven't been able to find anything about it?

You can run etcd inside a container. You can find it in the release page of etcd project on github.

> Does that still rescue my data?

As you are just simulating the process, I guess you should probably go directly with etcd 2.0 instead of trying to recover the broken 0.4 data.

**Comment by haf** [comment]
The thing is, I still need Deis to work in production (which is the aim of the testing), and according to SemVer, the 2.0 version won't work (or won't be tested).

So what do you recommend? Would you recommend that new Deis deployments are switched to etcd 2.0 and you know that works?

**Comment by xiang90** [comment]
> The thing is, I still need Deis to work in production (which is the aim of the testing), and according to SemVer, the 2.0 version won't work (or won't be tested).

We bump the major version only because we broke the internal API, not the external API.

> So what do you recommend? Would you recommend that new Deis deployments are switched to etcd 2.0 and you know that works?

I suggest people to try out etcd 2.0 and move to etcd 2.0 from 0.4.6. I cannot say Deis would work perfectly on etcd 2.0. You need to contact Deis team to confirm that or ask them to test.
