### ISSUE TITLE
Configurable memory usage options for etcd

### ISSUE THREAD

**Issue by bprashanth** [coreos/etcd#2465]
I was playing around with etcd 2.0.4 on a puny ~1.6G, single core debian. I noticed if i just throw writes at it while I get some coffee, it ooms. I used:

```
while true; do curl -L http://127.0.0.1:4001/v2/keys/$RANDOM -XPUT -d value="$(base64 /dev/urandom | head -c 10000)"; done
```
There were 2 problems:
1. The memory grew unbounded till it crashed
2. When I restarted it, it OOM'ed trying to restore the snapshot (or take another): https://gist.github.com/bprashanth/1b23eb9464c3b2494311

I solved 2 by setting --snapshot-count to 500. This at least allowed restarts. I had a single etcd instance, no peers. 

It would be nice if etcd exposed some memory consumption variables through a config, I'm looking for something like `innodb_buffer_pool_size`. I don't fully understand what etcd stores in memory (is it the entire state macine discussed in the raft paper?) but some WAL systems have a memory buffer that can be flushed safely. I initially suspected a leak of some sort, but was confused that etcd consumed 1G even after the restart.

[max-result-buffer](https://coreos.com/docs/distributed-configuration/etcd-configuration/) looked promising, but etcd 2.0.4 ignores it. If it can't flush to disk, maybe just flip to read-only mode upon hitting the limit?

**Comment by yichengq** [comment]
Could you check the size of the snapshot in etcd? It is at
$etcd_path/member/snapshot/*

We do load the snapshot into the memory for several times. And we have plan
to improve it soon.

**Comment by bprashanth** [comment]
```
root@etcdtest:/var/etcd/data/member# ls -lh --recursive
.:
total 8.0K
drwx------ 2 root root 4.0K Mar  9 21:37 snap
drwx------ 2 root root 4.0K Mar  9 21:37 wal

./snap:
total 532M
-rw-r--r-- 1 root root  93M Mar  9 21:35 0000000000000004-000000000001db85.snap
-rw-r--r-- 1 root root 100M Mar  9 21:36 0000000000000004-000000000001df6e.snap
-rw-r--r-- 1 root root 107M Mar  9 21:36 0000000000000004-000000000001e357.snap
-rw-r--r-- 1 root root 114M Mar  9 21:37 0000000000000004-000000000001e740.snap
-rw-r--r-- 1 root root 120M Mar  9 21:37 0000000000000004-000000000001eb29.snap

./wal:
total 46M
-rw------- 1 root root 9.2M Mar  9 21:36 00000000000000e9-000000000001db86.wal
-rw------- 1 root root 9.2M Mar  9 21:36 00000000000000ea-000000000001df6f.wal
-rw------- 1 root root 9.2M Mar  9 21:37 00000000000000eb-000000000001e358.wal
-rw------- 1 root root 9.2M Mar  9 21:37 00000000000000ec-000000000001e741.wal
-rw------- 1 root root 9.2M Mar  9 21:38 00000000000000ed-000000000001eb2a.wal

```

If you have a gce accout to play with you can reproduce this on a standard g1-small and the line of bash in my first comment. 

I still see memory continuing to grow after the snapshot, roughly the same memory consumed after the restart, and pretty much the same behavior (unbounded memory usage) on changing the snapshot-count from 10,000 to 1000. I haven't completely understood log compaction in etcd yet, can you explain what's responsible for the memory. Maybe I can mitigate it client side? 

I have observed something interesting, when it crashes and I restart, it consumes much more memory than if I restart cleanly. For example:

- Crash
- Restart
```
2015/03/09 21:53:46 etcdserver: recovered store from snapshot at index 130742
2015/03/09 21:53:46 etcdserver: name = etcdtest
2015/03/09 21:53:46 etcdserver: data dir = /var/etcd/data
2015/03/09 21:53:46 etcdserver: member dir = /var/etcd/data/member
2015/03/09 21:53:46 etcdserver: heartbeat = 100ms
2015/03/09 21:53:46 etcdserver: election = 1000ms
2015/03/09 21:53:46 etcdserver: snapshot count = 1000
2015/03/09 21:53:46 etcdserver: advertise client URLs = http://10.240.188.68:4001
2015/03/09 21:53:46 etcdserver: loaded cluster information from store: etcdtest=http://etcdtest:2380
2015/03/09 21:53:47 etcdserver: restart member ed305fcf5035acc7 in cluster 919fe6c5000f97e3 at commit index 131743
2015/03/09 21:53:47 raft: ed305fcf5035acc7 became follower at term 7
2015/03/09 21:53:47 raft: newRaft ed305fcf5035acc7 [peers: [ed305fcf5035acc7], term: 7, commit: 131743, applied: 130742, lastindex: 131743, lastterm: 7]
2015/03/09 21:53:47 etcdserver: start to snapshot (applied: 131743, lastsnap: 130742)
2015/03/09 21:53:49 etcdserver: compacted log at index 131743
2015/03/09 21:53:52 etcdserver: publish error: etcdserver: request timed out
2015/03/09 21:53:55 etcdserver: saved snapshot at index 131743
2015/03/09 21:53:56 raft: ed305fcf5035acc7 is starting a new election at term 7
2015/03/09 21:53:56 raft: ed305fcf5035acc7 became candidate at term 8
2015/03/09 21:53:56 raft: ed305fcf5035acc7 received vote from ed305fcf5035acc7 at term 8
2015/03/09 21:53:56 raft: ed305fcf5035acc7 became leader at term 8
2015/03/09 21:53:56 raft.node: ed305fcf5035acc7 elected leader ed305fcf5035acc7 at term 8
2015/03/09 21:53:56 etcdserver: published {Name:etcdtest ClientURLs:[http://10.240.188.68:4001]} to cluster 919fe6c5000f97e3
```
- Memory 1.3G
- Restart for no reason other than to force it to use another snapshot
```
2015/03/09 21:54:24 received terminated signal, shutting down...
2015/03/09 21:54:26 WARNING: flag "-vv" is no longer supported - ignoring.
2015/03/09 21:54:26 netutil: Resolving etcdtest:2380 to 10.240.188.68:2380
2015/03/09 21:54:26 etcd: listening for peers on http://localhost:2380
2015/03/09 21:54:26 etcd: listening for peers on http://localhost:7001
2015/03/09 21:54:26 etcd: listening for client requests on http://0.0.0.0:4001
2015/03/09 21:54:26 datadir is valid for the 2.0.1 format
2015/03/09 21:54:35 etcdserver: recovered store from snapshot at index 131743
2015/03/09 21:54:35 etcdserver: name = etcdtest
2015/03/09 21:54:35 etcdserver: data dir = /var/etcd/data
2015/03/09 21:54:35 etcdserver: member dir = /var/etcd/data/member
2015/03/09 21:54:35 etcdserver: heartbeat = 100ms
2015/03/09 21:54:35 etcdserver: election = 1000ms
2015/03/09 21:54:35 etcdserver: snapshot count = 1000
2015/03/09 21:54:35 etcdserver: advertise client URLs = http://10.240.188.68:4001
2015/03/09 21:54:35 etcdserver: loaded cluster information from store: etcdtest=http://etcdtest:2380
2015/03/09 21:54:36 etcdserver: restart member ed305fcf5035acc7 in cluster 919fe6c5000f97e3 at commit index 131801
2015/03/09 21:54:36 raft: ed305fcf5035acc7 became follower at term 8
2015/03/09 21:54:36 raft: newRaft ed305fcf5035acc7 [peers: [ed305fcf5035acc7], term: 8, commit: 131801, applied: 131743, lastindex: 131801, lastterm: 8]
2015/03/09 21:54:37 raft: ed305fcf5035acc7 is starting a new election at term 8
2015/03/09 21:54:37 raft: ed305fcf5035acc7 became candidate at term 9
2015/03/09 21:54:37 raft: ed305fcf5035acc7 received vote from ed305fcf5035acc7 at term 9
2015/03/09 21:54:37 raft: ed305fcf5035acc7 became leader at term 9
2015/03/09 21:54:37 raft.node: ed305fcf5035acc7 elected leader ed305fcf5035acc7 at term 9
2015/03/09 21:54:37 etcdserver: published {Name:etcdtest ClientURLs:[http://10.240.188.68:4001]} to cluster 919fe6c5000f97e3
```
- Memory 600M

So the first restart (using snapshot 130742) would've been pretty useless, because the moment I insert anything, it's just going to OOM again.

**Comment by yichengq** [comment]
@bprashanth 
The smaller snapshot count cannot help your problem a lot. In snapshot, it records all values in the store. If you write 100 10KB key, it needs at least 1MB in snapshot. We have plan to make a disk-backend store to solve this problem.

The two restarts are the same to etcd. And I think the second one will go up to 1.3G if you write 1000 keys into the cluster.

**Comment by bprashanth** [comment]
Ok, thanks for the explanation. so when it restarts it restores just the last snapshot, and it always keeps all versions of all keys in memory, so if I keep adding keys, I will run out of memory (at least in the current version). @yichengq Is this correct? 

The 2 restarts are the same etcd using 2 different snapshots (130742, 131743), one restart was after a crash, and the other was after a graceful shutdown; There's no other difference between them. The sequence of events was: crash->restart->wait till memory stabilizes (1.3G)->sudo /etc/init.d/etcd restart->wait till memory stabilizes (600M), no writes or reads happened inbetween from the client.

I don't necessarily want a disk backed store, just swap file backed virtual memory (obviously I'm simplifying a hard problem I don't fully understand), for example I don't mind if it restores from the raft log on restart because the swapfile is gone.

**Comment by yichengq** [comment]
@bprashanth It keeps at least one version of all keys in memory. If you keep adding new keys, it will run out of memory soon.

The first restart finishes a snapshot when you check:
```
2015/03/09 21:53:47 etcdserver: start to snapshot (applied: 131743, lastsnap: 130742)
2015/03/09 21:53:49 etcdserver: compacted log at index 131743
2015/03/09 21:53:52 etcdserver: publish error: etcdserver: request timed out
```
That may explain why it uses more memory.

We are considering the way to prevent OOM in best efforts. https://github.com/coreos/etcd/issues/2393 is also related.

**Comment by yichengq** [comment]
For memory usage, it is tracked here: #2473 
For configurable memory usage options, it is tracked here: #2393
