### ISSUE TITLE
How to run DEBUG mode, how to configure logs

### ISSUE THREAD

**Issue by xcrezd** [coreos/etcd#2466]
1.Where is no information about how to run etcd in debug mode(or verbose) in etcd --help
1.Where is no information about how to configure logs(level, path to file) in etcd --help

I tried to search it in source code, but with no success.

./etcd --version
etcd version 2.0.4

**Comment by AdoHe** [comment]
@xcrezd I am afraid there is no such option now. For the log, I think you can find some in your data dir.

**Comment by yichengq** [comment]
@AdoHe is correct. We don't have debug mode now.

For current stage, we could get enough information from the stderr output.

**Comment by yichengq** [comment]
@xcrezd More info: We will use level logging: https://github.com/coreos/etcd/issues/2398
