### ISSUE TITLE
unknown state - crash unrecoverable.  

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2470]
I have a 3 node etcd-2 cluster that appears to have gone into an unknown state after stress testing kubernetes.  I'm not exactly certain how it has gotten into this state, but it is unrecoverable once it has entered.  

In my cluster I have 3 nodes: 
host01-rack10
host02-rack10
host17-rack11

when host01 and host17 come back online all is well.  However, when host02 tries to join back in both host01 and host 17 die with the following error: 

__2015/03/09 19:59:24 etcdserver: open wal error: wal: file not found__

while host02 is caught in a loop reporting: 

__2015/03/09 19:52:54 rafthttp: roundtripping error: error roundtripping to http://host01-rack10:7001/raft/stream/a7a3f570406dda64: dial tcp 10.1.4.1:7001: connection refused__

**Comment by yichengq** [comment]
It crashes because it cannot find WAL(write-ahead log). Could you list the data directory, and check whether the WAL is in it?

**Comment by timothysc** [comment]
cd /var/lib/etcd && find . 
.
./snap
./default.etcd
./default.etcd/member
./default.etcd/member/snap
./default.etcd/member/wal
./default.etcd/member/wal/0000000000000000-0000000000000000.wal
./default.etcd/member/wal/0000000000000004-0000000000002712.wal
./default.etcd/member/wal/0000000000000001-0000000000002712.wal
./default.etcd/member/wal/0000000000000002-0000000000002712.wal
./default.etcd/member/wal/0000000000000003-0000000000002712.wal
./host01-rack10.fqdn.etcd
./host01-rack10.fqdn.etcd/snapshot
./host01-rack10.fqdn.etcd/snapshot/6859_9974474.ss
./host01-rack10.fqdn.etcd/member
./host01-rack10.fqdn.etcd/member/snap
./host01-rack10.fqdn.etcd/member/snap/00000000000061de-0000000000facc71.snap
./host01-rack10.fqdn.etcd/member/snap/00000000000061db-0000000000faa560.snap
./host01-rack10.fqdn.etcd/member/snap/00000000000061df-0000000000fb1a94.snap
./host01-rack10.fqdn.etcd/member/snap/00000000000061e2-0000000000fb41a5.snap
./host01-rack10.fqdn.etcd/member/snap/00000000000061de-0000000000faf383.snap
./host01-rack10.fqdn.etcd/member/wal
./host01-rack10.fqdn.etcd/member/wal/000000000000031c-0000000000fb49a0.wal
./host01-rack10.fqdn.etcd/member/wal/000000000000031d-0000000000fb5047.wal
./host01-rack10.fqdn.etcd/member/wal/000000000000031b-0000000000fb4304.wal
./host01-rack10.fqdn.etcd/member/wal/000000000000031f-0000000000fb5da6.wal
./host01-rack10.fqdn.etcd/member/wal/000000000000031e-0000000000fb56f9.wal
./host01-rack10.fqdn.etcd/log
./host01-rack10.fqdn.etcd/conf

**Comment by yichengq** [comment]
It is probably a bug.

Which etcd version are you running on?

**Comment by jayunit100** [comment]
To add some color : We saw this bug after running dense, network  intensive set of tasks.

**Comment by timothysc** [comment]
we run the tip nightly: 

etcd version 2.0.4+git
Revision: 17ba06b5cd419ea1b48391c86ba25f4b71ef7011

**Comment by yichengq** [comment]
@timothysc Is etcd restarted in the process of stress testing? 
Did you restart the etcd cluster because it goes into some error? If so, what is it?
Do you have the logs of previous runs?

**Comment by yichengq** [comment]
BTW, do you have idea how big the key written into etcd is?
and list the size of files under `./host01-rack10.fqdn.etcd/member/snap` and `./host01-rack10.fqdn.etcd/member/wal`?

**Comment by timothysc** [comment]
The etcd cluster was down on inspection, I'll try to grok backwards in the logs.

du -sk * 
1770304	00000000000061db-0000000000faa560.snap
1855804	00000000000061de-0000000000facc71.snap
1312244	00000000000061de-0000000000faf383.snap
1326608	00000000000061df-0000000000fb1a94.snap
1269112	00000000000061e2-0000000000fb41a5.snap

-----------------------------------------

du -sk * 
62548	000000000000031b-0000000000fb4304.wal
62692	000000000000031c-0000000000fb49a0.wal
62840	000000000000031d-0000000000fb5047.wal
62988	000000000000031e-0000000000fb56f9.wal
28784	000000000000031f-0000000000fb5da6.wal

**Comment by xiang90** [comment]
@timothysc Thanks for reporting! I think we find the root problem and are fixing. But we still would like you to retrieve the log if possible to verify the problem. Thanks!

**Comment by xiang90** [comment]
https://github.com/coreos/etcd/pull/2474

/cc @yichengq @timothysc

**Comment by timothysc** [comment]
So I combed the logs, and the only standout information is what was provided earlier.

We are going to try to see if we can somehow repro, but we entered into this state unexpectedly.

**Comment by xiang90** [comment]
@timothysc 
There should be some log lines like "filePurge: remove ..." before the restart.

I think this should be fixed. You can try to use both the previous head and current head to repro this issue. (large values and large snapshot can trigger it.)

**Comment by xiang90** [comment]
@timothysc I assume this is solved. Thanks for reporting! Reopen if you still see this problem.

**Comment by timothysc** [comment]
@xiang90 ack, we'll be sure to let you know if we find something.
