### ISSUE TITLE
etcd runs into a crashloop and couldn't recover

### ISSUE THREAD

**Issue by dchen1107** [coreos/etcd#2471]
Over the weekend, my 4-node cluster with etcd 2.0.3 runs into a crashloop. There is no much load on cluster overall. Initially it was crashed due to runtime OOM issue during snapshotting, but please note that there is no system OOM pressure on the node, and I checked kernel log, no oom killing at all.

```
2015/03/07 05:25:11 error writing event: write tcp 10.240.43.157:53708: broken pipe
2015/03/07 05:44:00 etcdserver: start to snapshot (applied: 30003, lastsnap: 20002)
2015/03/07 05:44:09 etcdserver: compacted log at index 30003
2015/03/07 05:44:14 etcdserver: saved snapshot at index 30003
2015/03/07 07:01:58 etcdserver: start to snapshot (applied: 40004, lastsnap: 30003)
2015/03/07 07:02:08 etcdserver: compacted log at index 40004
2015/03/07 07:02:15 etcdserver: saved snapshot at index 40004
2015/03/07 08:20:43 etcdserver: start to snapshot (applied: 50005, lastsnap: 40004)
2015/03/07 08:20:54 etcdserver: compacted log at index 50005
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc2c51f0000, 0x1b4c0000, 0x7febf2448000, 0xa513f8)
        /usr/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0xa56ae0, 0x1b4c0000, 0x42c382)
        /usr/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0xa56ae0, 0xda5b, 0x10100000000, 0x108010001)
        /usr/local/go/src/runtime/mheap.c:240 +0x66

goroutine 7 [running]:
runtime.switchtoM()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc209965248 sp=0xc209965240
runtime.mallocgc(0x1b4b40ce, 0x7139a0, 0x1, 0x0)
        /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc2099652f8 sp=0xc209965248
runtime.newarray(0x7139a0, 0x1b4b40ce, 0x681ddd)
        /usr/local/go/src/runtime/malloc.go:365 +0xc1 fp=0xc209965330 sp=0xc2099652f8
runtime.makeslice(0x705c60, 0x1b4b40ce, 0x1b4b40ce, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:32 +0x15c fp=0xc209965378 sp=0xc209965330
github.com/coreos/etcd/snap/snappb.(*Snapshot).Marshal(0xc209965510, 0x0, 0x0, 0x0, 0x0, 0x0)            /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/snap/snappb/snap.pb.go:150 +0x74 fp=0xc2099653b8 sp=0xc209965378
github.com/coreos/etcd/snap.(*Snapshotter).save(0xc2080319c0, 0xc20b770090, 0x0, 0x0)       /Users/philips/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:67 +0x301 fp=0xc257c17550 sp=0xc257c173b8
```

After this crash, monit tried to bring it up every 2 mins, and etcd crashed immediately at same place. Finally, it got into too_many_open_file issue forever:

```
2015/03/09 20:49:20 netutil: Resolving kubernetes-master:2380 to 10.240.43.157:2380
2015/03/09 20:49:20 etcd: listening for peers on http://localhost:2380
2015/03/09 20:49:20 etcd: listening for peers on http://localhost:7001
2015/03/09 20:49:20 etcd: listening for client requests on http://0.0.0.0:4001
2015/03/09 20:49:30 etcdserver: recovered store from snapshot at index 40004
2015/03/09 20:49:30 etcdserver: name = kubernetes-master
2015/03/09 20:49:30 etcdserver: data dir = /var/etcd/data
2015/03/09 20:49:30 etcdserver: heartbeat = 100ms
2015/03/09 20:49:30 etcdserver: election = 1000ms
2015/03/09 20:49:30 etcdserver: snapshot count = 10000
2015/03/09 20:49:30 etcdserver: advertise client URLs = http://10.240.43.157:4001
2015/03/09 20:49:30 etcdserver: loaded cluster information from store: kubernetes-master=http://kubernetes-master:2380
2015/03/09 20:49:30 etcdserver: open wal error: open /var/etcd/data/wal/00000000000001ff-000000000000c356.wal: too many open files
```

cc/ @xiang90

**Comment by yichengq** [comment]
The OOM may be caused by the big size of snapshot, which is loaded into memory in current impl. Could you provide the size of the snapshot and the memory size of the machine?

For too_many_open_file issue, could you give a chance to check where file descriptors point to and which status they are in?

**Comment by bprashanth** [comment]
@dchen1107 I think we both observed the same thing independently, https://github.com/coreos/etcd/issues/2465. @yichengq I changed the snapshot size but it didn't prevent an OOM. Since etcd rotates out snapshots I'm assuming it only has the latest snapshot in memory? In which case it should easily handle a 100M snapshot right?

**Comment by dchen1107** [comment]
Machine has roughtly 4G memory.  

```
root@kubernetes-master:/var/etcd/data/snap# ls -alt 
total 988748
drwx------ 4 etcd etcd      4096 Mar  9 22:21 ..
drwx------ 2 etcd etcd      4096 Mar  7 07:02 .
-rw-r--r-- 1 etcd etcd 389159381 Mar  7 07:02 0000000000000002-0000000000009c44.snap
-rw-r--r-- 1 etcd etcd 310041461 Mar  7 05:44 0000000000000002-0000000000007533.snap
-rw-r--r-- 1 etcd etcd 215735222 Mar  7 04:27 0000000000000002-0000000000004e22.snap
-rw-r--r-- 1 etcd etcd  97527268 Mar  7 03:12 0000000000000002-0000000000002711.snap
```

Regarding too_many_open_file, system itself has

```
 /sbin/sysctl fs.file-max
fs.file-max = 377308
```

Per processes has limit of 1024, and currently on my node has:

```
#  lsof | wc -l
11146
```

**Comment by dchen1107** [comment]
@bprashanth both of us ran into similar issues lately. Actually other folks reported the same. I am wondering what is changed lately on how we are using etcd in kubernetes.

**Comment by yichengq** [comment]
@dchen1107 OOM may be reasonable because the snapshot size is nearly 400MB. Maybe k8s write more keys into etcd store without deleting old ones. The snapshot size increases 100MB per 75 minutes.

Could you list all file descriptors used by the etcd process? This can help me narrow down which module uses that many fds.
( sudo lsof -a -p `pidof etcd` )

**Comment by kelseyhightower** [comment]
@dchen1107 @yichengq 

```
sudo lsof -a -p `pidof etcd` | wc -l
```

**Comment by dchen1107** [comment]
@kelseyhightower I did run above, the result is zero. Monit tries to restart etcd every 2 mins, but etcd quickly exit due to too_many_open_file issue. I couldn't catch the moment when open_files by etcd is high unfortunately.

**Comment by yichengq** [comment]
@dchen1107 The possible case for this situation is that all file descriptors are consumed between the time that etcd listens on the port and the moment that it opens WAL to read the log. Observed from the log, the duration is 10s(most of which is used to decode snapshot), and maybe more than 1000 clients make requests in this period. Could you check this possibility?

**Comment by kelseyhightower** [comment]
@yichengq @dchen1107 Is there any chance we can get that data directory from the etcd node?

**Comment by dchen1107** [comment]
I destroyed that node last night after we found the root cause of large snapshot. Will report to you guys when I observe the same issue next time; or you can try to reproduce it, not sure if you can do it or not. In my situation, there is a snapshot is too big, and failed to recover due to OOM for a couple of hundreds times (507 times by processing etcd.log), etcd restarting runs into this issue. 

I do have log if you want.

**Comment by xiang90** [comment]
@dchen1107 We have reproduced both the OOM and fd issues. We reproduced the fd issue with an assumption that the number of client is large.

SO we want to confirm that the etcd cluster did have many concurrent clients connected. 

@kelseyhightower I do not think we need to etcd data.

**Comment by dchen1107** [comment]
Assume each watcher is a client creating the connection to etcd server. We can theoretically calculate the number of watcher objects we created currently is based on the cluster size, and workload:

# of watchers = # of nodes + # of replica controllers + 1 (node controller) + 2 (scheduler)

So theoretically we have 12 watchers totally ( 4 (nodes) + 5 (rc) + 1 (node controller) + 2 (scheduler) )

But I am not sure if there is a bug in the system which leak the watcher object. Do you know anyway to check how many watchers / clients besides lsof :-)

**Comment by xiang90** [comment]
@dchen1107 I have fixed the `out of memory` issue in master branch. It is caused by high memory consumption during recovery phase. Thanks for reporting!

**Comment by pegerto** [comment]
Hi @xiang90 

This bug has been fixed already unfortunately we keep running   `"etcdserver": "2.3.1"` and we are affected, can you clarify the merge request or version where the issue is fixed.

Regards.

**Comment by heyitsanthony** [comment]
@pegerto the fix should already be in 2.3.1. The release for 2.3.0 happened a year after this issue was closed.

**Comment by pegerto** [comment]
Hello @heyitsanthony 

I see, I understand that the issue is old, issue, I saw other issue we keep having issues to recover for a memory crash after multiple transactions. As initially described at this ticket.

```
Nov 18 17:08:39 etcd00-k8s1.ci1.x etcd2[27030]: fatal error: runtime: out of memory
Nov 18 17:08:39 etcd00-k8s1.ci1.x etcd2[27030]: runtime stack:
Nov 18 17:08:39 etcd00-k8s1.ci1.x etcd2[27030]: runtime.throw(0xf85480, 0x16)
Nov 18 17:08:39 etcd00-k8s1.ci1.x etcd2[27030]: /usr/lib/go/src/runtime/panic.go:527 +0x90
Nov 18 17:08:39 etcd00-k8s1.ci1.x etcd2[27030]: runtime.sysMap(0xc850e70000, 0x9370000, 0x0, 0x141e4f8)
```

**Comment by heyitsanthony** [comment]
@pegerto please open a fresh issue with the logs explaining how to reproduce, the machine configuration, and the amount of data being kept in etcd? It could just be that the machine is legitimately out of memory.
