### ISSUE TITLE
etcd memory usage benchmark

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2473]
We need to understand and measure how much memory will be used in all kinds of cases.

/cc @dchen1107 @bprashanth

from #2471

**Comment by bprashanth** [comment]
IMO the memory used by a database should never grow unbounded, it should survive as long as there's disk. We're facing memory issues on a single node so at this point it isn't very different than, say, memcached (which actually does a few tricks to explicitly *avoid* using disk). 

So I think it's more important to define what happens under  heavy memory pressure than profile read/write throughput etc. Just my 2c.

**Comment by yichengq** [comment]
The memory usage we observed so far:
huge memory usage overhead (20X than real data) in normal run (#2657)
giant memory usage overhead on leader when recovering progress of dead follower(40x) (#2662)

40x is the upper bound that we have observed so far.

**Comment by yichengq** [comment]
I would like to delay this benchmark to v3. etcd v3 has different memory model, and this benchmark should try it and take care of v2 and v3 together. We have rough thoughts about the upper limit of today's memory usage already, so i think it is ok to delay a little.

**Comment by xiang90** [comment]
Let us move this to 2.2. This is not a blocker for the rc release at all.

**Comment by yichengq** [comment]
Based on discussion OOL, we would like to separate v2 and v3 memory benchmark to make each one as clear as possible. For v2 one, we would focus on its memory expectation and limitation.

**Comment by yichengq** [comment]
I have done the memory usage benchmark on 2.2.

We have done some memory benchmark on storage package, but have not done it for v3 because it doesn't have cluster version today. It is not a blocker for 2.2 release, so move it to 3.0.

**Comment by xiang90** [comment]
@yichengq Moving this to 2.3. We will have a clustered version of api+storage in 2.3.

**Comment by jonboulle** [comment]
@xiang90 to put up a doc and @jonboulle to help review.

**Comment by jonboulle** [comment]
This should help with #2657

**Comment by xiang90** [comment]
fixed by https://github.com/coreos/etcd/pull/3729
