### ISSUE TITLE
logging: disable timestamp if running under journal

### ISSUE THREAD

**Issue by philips** [coreos/etcd#2475]
If etcd detects it is running under systemd it should disable the timestamps on the loglines, otherwise we get double dates:

```
Mar 10 01:22:33 ip-10-0-0-12.us-west-1.compute.internal etcd[31078]: 2015/03/10 01:22:33 
```

**Comment by xiang90** [comment]
move this to 2.2 based on offline discussion. 
/cc @barakmich @kelseyhightower @philips

**Comment by xiang90** [comment]
@barakmich Will this be handled in coreos/log?
