### ISSUE TITLE
etcd fatal because it has no file descriptor to open WAL/snapshot

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2477]
This happens in several situations:
1.
(a) etcd listens on the port, but has not started to serving
(b) client requests eat up all file descriptors
(c) etcd fails to open WAL and fatal
2.
(a) etcd is running
(b) client requests eat up all file descriptors
(c) etcd fails to save snapshot and fatal

This is met by functional tests and #2471

**Comment by philips** [comment]
@yichengq What is the plan of attack here? Will we reserve a few file descriptors for WAL handling?

**Comment by yichengq** [comment]
@philips Based on the discussion, the first step is to expose the number of fds used and give users instructions.

It is reasonable to reserve a few file descriptors or restrict the number of fds used by rafthttp. We want to wait for users' suggestions before improving it.

**Comment by yichengq** [comment]
etcd logs and exposes file descriptor usage now.
wait for more user feedback to see what restriction is expected.

**Comment by xiang90** [comment]
Is this a bug? What is your plan? @yichengq

**Comment by yichengq** [comment]
I think it is an enhancement instead of a bug.

Based on the #2928 issue, an abusive client may eat up all fds and cause etcd cluster out-of-work. User could fix the wrong client, but this is not ideal because etcd cluster could be affected. So I want to improve it.

My rough plan is to restrict the total number of fds that could be used for remote clients.

**Comment by adizere** [comment]
Hello,
What if one *wants* to allow many clients connecting to etcd?
Since `file_descriptor_limit` is set to 1024, that means that no more than ~1000 clients can connect to etcd.

Is there any way to change the `file_descriptor_limit`, or the underlying `RLIMIT_NOFILE`?
