### ISSUE TITLE
Plans to upgrade etcd to > 2.0 in Alpha?

### ISSUE THREAD

**Issue by visit1985** [coreos/etcd#2479]
When can we expect etcd > 2.0 in Alpha?

I also noticed that the 0.4.7 tag is missing in this repo but stated on https://coreos.com/releases/. Is there any special reason for that?

Keep up the awesome work!

**Comment by crawford** [comment]
We are finishing up the last bit of migration testing and should be ready (assuming all goes well) to put etcd into the image within the next couple of weeks.

0.4.7 is tagged in this repo, it just doesn't have release notes attached. @yichengq, can you add some release notes for that release?

**Comment by visit1985** [comment]
Ahh, my bad. GitHub sorts it by date and it was tagged after 0.5.
Nevermind ;-)
