### ISSUE TITLE
Single-node idle cluster continuously writes to disk

### ISSUE THREAD

**Issue by extemporalgenome** [coreos/etcd#2486]
Running a single-node cluster with `etcd` generates ~7.83K/s writes continuously according to the Linux iotop utility (when snapshotting, this peaks to ~11.73K/s) and strace. The cluster has not been interacted with at all (has no data), thus all these writes seem redundant.

Further, because of the use of a subsequent fsync on each of these writes, if deployed on SSDs, it would cause continuous wear even when, as in this case, nothing is semantically happening.

**Comment by xiang90** [comment]
@extemporalgenome This is kind of duplicate with https://github.com/coreos/etcd/issues/1757. 

Can you please add your concern to that issue? And we can track all related problem there?

**Comment by xiang90** [comment]
@extemporalgenome I am going to close this since it is kind of duplicate with #1757 and we have reference from #1757 to this one.
