### ISSUE TITLE
about API  /v2/stats/leader

### ISSUE THREAD

**Issue by lawrencewu** [coreos/etcd#2489]
Hi team,
    as now I setup a cluster using ETCD v2.0.4 with three ips(10.2.3.1, 10.2.3.2, 10.2.3.3), 10.2.3.3 is the leader's IP, calling the v2/stats/leader API, the result:
10.2.3.1:
{"message": "not current leader"}
10.2.3.2
{"message": "not current leader"}
10.2.3.3
{"leader": "e15b2c5ad298c819","followers": {"570f819cb07b647b": {"latency": {
"current": 0.04551,"average": 0.07842731802412709,"standardDeviation": 0.20539326076968417,"minimum": 0.014055, "maximum": 29.62512},"counts":{"fail": 0, "success": 522583}},"f6b23e48e8d1cac1":{"latency":{"current": 0.095036,"average": 0.06204500975165349, "standardDeviation": 0.1650211755350052,"minimum": 0.014175,"maximum": 31.651171},
"counts": { "fail": 150,"success": 522373}}}}

Can followers get leader's information? @xiang90

**Comment by il9ue** [comment]
Hello, I think the answer is on ETCD API Documentation already.
If you didn't go through please check the below curl command : 

curl -L http://127.0.0.1:4001/v2/stats/self

which might produce the result such as,

{
    "leaderInfo": {
        "leader": "machine1",
        "uptime": "1m18.544996775s"
    },
    "name": "machine0",
    "recvAppendRequestCnt": 5871307,
    "recvBandwidthRate": 630.3121596542599,
    "recvPkgRate": 19.272654323628185,
    "sendAppendRequestCnt": 3175763,
    "startTime": "2014-01-01T15:26:24.96569404Z",
    "state": "follower"
}

**Comment by lawrencewu** [comment]
hi @il9ue  this only works on the leader server, how about the server that is not the leader?

**Comment by xiang90** [comment]
@lawrencewu You need to find the leader. And then get the information for the leader. Our plan is to have etcdctl do that for you in the future.

**Comment by xiang90** [comment]
@lawrencewu I am closing this due to low activity. Reopen if you have a follow-up. Thanks!
