### ISSUE TITLE
The `--ca-file` flag should not enable client auth by default

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#2499]
When configuring etcd for SSL using the following instructions:

https://github.com/kelseyhightower/etcd-production-setup/tree/multinode#configuring-etcd-for-ssl

I get the following errors in the etcd logs: 

```
2015/03/12 15:55:19 rafthttp: roundtripping error: error roundtripping to https://etcd1.example.com:2380/raft/stream/message/689d213e8fdfef61: x509: certificate signed by unknown authority
```

The only way to make it work was to set the `--ca-file`, which also has the side effect of enabling client auth. This was not what I wanted in this case. 

My only option at this point is to figure out how to get my OS to trust the CA cert. Ideally the --ca-flag can be used to trust the CA cert and another flag would enable client-auth.

**Comment by philips** [comment]
Hrm, we can do one of two things to avoid breaking any users

- Add a new 'trusted-ca' flag to let you add things outside of your OS trusted CA list
- Add a new 'client-cert-auth' flag that takes a boolean

**Comment by kelseyhightower** [comment]
@philips Both options look great! I'm leaning towards both :)

**Comment by kelseyhightower** [comment]
I think adding both `--trusted-ca` and `--client-cert-auth` flags will allow us to deprecate the `--ca-file` flag at some point down the road.

**Comment by yichengq** [comment]
@kelseyhightower Could you give a detailed example about this? I think `--ca-file` is only designed to enable client auth, and the above error should be resolved by setting `--peer-ca-file` to authenticate peer identity.

If you set `--peer-ca-file`, `--peer-key-file` and `--peer-cert-file`, etcd should work well with server-to-server communication.

**Comment by kelseyhightower** [comment]
@yichengq Client SSL does not work in this setup.

**Comment by yichengq** [comment]
@kelseyhightower Client SSL should work if `--key-file` and `--cert-file` are set. Further, if etcd is expected to auth the client identity, `--ca-file` should be given.

**Comment by kelseyhightower** [comment]
@yichengq I will retest this.

**Comment by kelseyhightower** [comment]
@yichengq I don't think the peer ca cert gets added to the cert pool: https://github.com/coreos/etcd/blob/master/pkg/transport/listener.go#L151

**Comment by kelseyhightower** [comment]
@yichengq We will have the same problem when an etcd follower has to proxy a client request. We want to have the ability to trust the client server cert without requiring client auth.
