### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by borillo** [coreos/etcd#2506]
Running etc with docker:
$ docker run --rm -p 4001:4001 quay.io/coreos/etcd:v2.0.5
2015/03/13 13:45:24 no data-dir provided, using default data-dir ./default.etcd
2015/03/13 13:45:24 etcd: listening for peers on http://localhost:2380
2015/03/13 13:45:24 etcd: listening for peers on http://localhost:7001
2015/03/13 13:45:24 etcd: listening for client requests on http://localhost:2379
2015/03/13 13:45:24 etcd: listening for client requests on http://localhost:4001
2015/03/13 13:45:24 etcdserver: name = default
2015/03/13 13:45:24 etcdserver: data dir = default.etcd
2015/03/13 13:45:24 etcdserver: member dir = default.etcd/member
2015/03/13 13:45:24 etcdserver: heartbeat = 100ms
2015/03/13 13:45:24 etcdserver: election = 1000ms
2015/03/13 13:45:24 etcdserver: snapshot count = 10000
2015/03/13 13:45:24 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/03/13 13:45:24 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/03/13 13:45:24 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/03/13 13:45:24 etcdserver: start member ce2a822cea30bfca in cluster 7e27652122e8b2ae
2015/03/13 13:45:24 raft: ce2a822cea30bfca became follower at term 0
2015/03/13 13:45:24 raft: newRaft ce2a822cea30bfca [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/03/13 13:45:24 raft: ce2a822cea30bfca became follower at term 1
2015/03/13 13:45:24 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e27652122e8b2ae
2015/03/13 13:45:25 raft: ce2a822cea30bfca is starting a new election at term 1
2015/03/13 13:45:25 raft: ce2a822cea30bfca became candidate at term 2
2015/03/13 13:45:25 raft: ce2a822cea30bfca received vote from ce2a822cea30bfca at term 2
2015/03/13 13:45:25 raft: ce2a822cea30bfca became leader at term 2
2015/03/13 13:45:25 raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 2
2015/03/13 13:45:25 etcdserver: published {Name:default ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster 7e27652122e8b2ae

Execute curl:
curl -L http://localhost:4001/version

The result is always:
curl: (52) Empty reply from server

**Comment by kelseyhightower** [comment]
@borillo Looks like your etcd server is only listening on localhost inside the container. You will need to bind to an external IP (0.0.0.0 might help). Then via curl you will need to use the IP of the container.

See the following etcd clustering flags for more info: https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#clustering-flags

**Comment by kelseyhightower** [comment]
@borillo You will need to set `-advertise-client-urls` to the IP of the docker host, since you will have a hard time predicting the container IP upfront. You also need to set the `-listen-client-urls` to something like http://0.0.0.0:4001 to ensure you listen on the container IP.

Also see the etcd docker guide from more details: https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md

**Comment by borillo** [comment]
Cool!! Works perfect with -listen-client-urls :)
Thx a lot for your quick and clear answer
