### ISSUE TITLE
etcdserver: failed to purge snap file

### ISSUE THREAD

**Issue by jazzzz** [coreos/etcd#2515]
I use etcd v2.0.5 for Windows 64 bits (Windows 7 and 8.1), and after some hours, etcd crashes with this error message:

```
 etcdserver: failed to purge wal file remove etcd-data/member/wal/0000000000000002-0000000000004e23.wal: The process cannot access the file because it is being used by another process.
```

If I try to restart etcd, I get the same error.
I checked: this file is not used by any process, I could remove it manually and etcd could restart normally.

**Comment by xiang90** [comment]
@jazzzz 

I guess this is probably caused by the empty file lock implementation for win. 
https://github.com/coreos/etcd/blob/master/pkg/fileutil/lock_windows.go

**Comment by jazzzz** [comment]
I forgot to precise I use this command line: `-max-snapshots 5 -max-wals 5`, maybe it is linked to theses options.

**Comment by gyuho** [comment]
We might be able to do this using https://github.com/tgulacsi/lock.

**Comment by gyuho** [comment]
@jazzzz  `The process cannot access the file because it is being used by another process.` happens when the `WAL` file has no locks. We have added flocks to Windows at https://github.com/coreos/etcd/pull/4871.
