### ISSUE TITLE
Last nights master build 8a589d11d5573201869de0d5aa9e0e6b24a8b246 fails. 

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2524]
gopath/src/github.com/coreos/etcd/etcdserver/etcdhttp/client_security.go:49: r.BasicAuth undefined (type *http.Request has no field or method BasicAuth)
gopath/src/github.com/coreos/etcd/etcdserver/etcdhttp/client_security.go:76: r.BasicAuth undefined (type *http.Request has no field or method BasicAuth)

**Comment by AdoHe** [comment]
@timothysc You should check your local go version, maybe this will help you https://golang.org/doc/go1.4

**Comment by timothysc** [comment]
All previous builds were working fine on 1.3.3, is 1.4 now a hard requirement?

**Comment by AdoHe** [comment]
@timothysc for the next version of etcd, you should use go 1.4

**Comment by xiang90** [comment]
@timothysc We probably will require go1.4 for 2.1 release.

**Comment by vbatts** [comment]
rawr
