### ISSUE TITLE
Option to pretty print json

### ISSUE THREAD

**Issue by F21** [coreos/etcd#2528]
It would be nice if there's an option to pretty print the json when requesting things over the http interface.

Something like this would be nice:
```
curl -L http://127.0.0.1:4001/v2/keys/?recursive=true&pretty=true
```

This would make working with curl much easier and remove the need to install some json-prettifying tool to pipe the output to.

**Comment by xiang90** [comment]
@F21 We probably will not do this at server-side if it can be done at client side. Yea. Pipe it to json-prettifying tool please. :)

**Comment by yichengq** [comment]
`echo '{"foo": "lorem", "bar": "ipsum"}' | python -m json.tool`

**Comment by agokjr** [comment]
Check out https://github.com/stedolan/jq

**Comment by F21** [comment]
@xiang90 @yichengq Fair point. I will be closing this then :smile: 

@agokjr That tool looks awesome! Thanks for mentioning it!
