### ISSUE TITLE
Cannot establish etcd cluster with SSL/TLS - raft fall into infinite loop

### ISSUE THREAD

**Issue by josefzamrzla** [coreos/etcd#2539]
I'm trying to run an etcd cluster of 3 machines (10.0.0.1, 10.0.0.2, 10.0.0.3) with SSL/TLS both for client and transport security, but I'm still getting into trouble, it seems like the cluster isn't able to elect its leader - raft falls into infinite loop and fails after several tries.  All machines uses etcd 2.0.5

*server1*

etcd -name eu1 -data-dir eu1 \
 -ca-file=/root/etcd-ca/ca.crt -cert-file=/root/etcd-ca/server1.crt -key-file=/root/etcd-ca/server1.key \
 -peer-ca-file=/root/etcd-ca/ca.crt -peer-cert-file=/root/etcd-ca/server1.crt -peer-key-file=/root/etcd-ca/server1.key \
 -initial-advertise-peer-urls=https://10.0.0.1:2380 -listen-peer-urls=https://10.0.0.1:2380 \
 -discovery https://discovery.etcd.io/7855c14b6cd05060974839f3833ea932

*server2*

etcd -name eu2 -data-dir eu2 \
 -ca-file=/root/etcd-ca/ca.crt -cert-file=/root/etcd-ca/server2.crt -key-file=/root/etcd-ca/server2.key \
 -peer-ca-file=/root/etcd-ca/ca.crt -peer-cert-file=/root/etcd-ca/server2.crt -peer-key-file=/root/etcd-ca/server2.key \
 -initial-advertise-peer-urls=https://10.0.0.2:2380 -listen-peer-urls=https://10.0.0.2:2380 \
 -discovery https://discovery.etcd.io/7855c14b6cd05060974839f3833ea932

*server3*

etcd -name player -data-dir player \
 -ca-file=/root/etcd-ca/ca.crt -cert-file=/root/etcd-ca/server3.crt -key-file=/root/etcd-ca/server3.key \
 -peer-ca-file=/root/etcd-ca/ca.crt -peer-cert-file=/root/etcd-ca/server3.crt -peer-key-file=/root/etcd-ca/server3.key \
 -initial-advertise-peer-urls=https://10.0.0.3:2380 -listen-peer-urls=https://10.0.0.3:2380 \
 -discovery https://discovery.etcd.io/7855c14b6cd05060974839f3833ea932

Log file with outputs: http://pastebin.com/JBitRT1e

**Comment by xiang90** [comment]
@kelseyhightower Can you take a look at this?

**Comment by genti-t** [comment]
I'm having the same issue. I'm using version 2.0.5 on docker container with static discovery:

ExecStart=/bin/bash -c "/usr/bin/docker run \
  -p 4001:4001 \
  -p 2379:2379 \
  -p 2380:2380 \
  --name etcd \
  -v /var/lib/etcd:/var/lib/etcd \
  -v /var/lib/etcd-certs:/etc/ssl/certs quay.io/coreos/etcd:v2.0.5 \
  -data-dir /var/lib/etcd \
  --ca-file=/etc/ssl/certs/ca.crt \
  --cert-file=/etc/ssl/certs/core01.crt \
  --key-file=/etc/ssl/certs/core01.key \
  --peer-ca-file=/etc/ssl/certs/ca.crt \
  --peer-cert-file=/etc/ssl/certs/core01.crt \
  --peer-key-file=/etc/ssl/certs/core01.key \
  -name %H \
  -advertise-client-urls https://$COREOS_PRIVATE_IPV4:2379,https://$COREOS_PRIVATE_IPV4:4001 \
  -listen-client-urls https://0.0.0.0:2379,https://0.0.0.0:4001 \
  -initial-advertise-peer-urls https://$COREOS_PRIVATE_IPV4:2380 \
  -listen-peer-urls https://0.0.0.0:2380 \
  -initial-cluster-token etcd-cluster-1 \
  -initial-cluster core01=https://192.168.0.173:2380,core02=https://192.168.0.179:2380,core03=https://192.168.0.180:2380\
  -initial-cluster-state new"
...

**Comment by josefzamrzla** [comment]
Yep, the static bootstrapping ends with the same result as well.

**Comment by atmouse-** [comment]
The same issue here, if I set back with non-TLS peers, Then it works.

**Comment by xiang90** [comment]
@josefzamrzla @atmouse- @josefzamrzla 
I suspect tls increase the latency significantly. Can you try to increase `-election-timeout` to 5 seconds or higher? 
https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-election-timeout

At the meantime, we are looking into the problem.

**Comment by genti-t** [comment]
I tried this with version 2.0.8.
Increased  election-timeout up to 20 seconds, there is a leader elected now, but after that :
etcdserver: publish error: etcdserver: request timed out
etcdserver: publish error: etcdserver: request timed out
....
sender: dropping MsgAppResp because maximal number 64 of sender buffer entries to https://<node_ip>:2380/raft has been reached
....

**Comment by xiang90** [comment]
@genti-t Hrm... Currently etcd peer side does not reuse any tcp connections, which means your server are doing tls handshake for every request and eats a lot of resources. We have solved the problem in current master and it will be available in 2.1 release.  For now, you have to switch to a more powerful machine. :(

**Comment by xiang90** [comment]
@genti-t Can you test with current master by the way?

**Comment by agokjr** [comment]
I think I am hitting this too. 
2.0.4 was manageable but it seems worse in 2.0.5-2.0.8
Ellection timeout to 20000ms and heartbeat 1000ms.
Also I looks like the side effect of not all peers on same term.

**Comment by xiang90** [comment]
@agokjr Yea...... We started to not reuse connection from 205...

**Comment by josselin-c** [comment]
I hit this as well with 2.0.8 on machines with Xeon E3-1225. I don't have the problem with current master though.

**Comment by xiang90** [comment]
@josselin-c We fixed it on current master.

**Comment by jlsalvador** [comment]
Hello @xiang90 
I think that TLS is important enough to backport the patch to the actual stable version (to prevent future problems when CoreOS updates etcd to 2.0.x).

**Comment by xiang90** [comment]
@jlsalvador It is hard since we made big improvement from 2.0 to 2.1 around more efficient transportation. We have release 2.1.alpha0. I think it is fixed there.

**Comment by pstengel** [comment]
Please backport :cry:

![](http://i.imgur.com/CuEJnxJm.png)

**Comment by rdark** [comment]
+1 Peer TLS being broken in stable is a pretty big issue..

**Comment by philips** [comment]
@rdark @pstengel @jlsalvador Can you please try this workaround: https://github.com/coreos/etcd/pull/3097

**Comment by rdark** [comment]
@philips - I tried playing around with the timeouts a while back on an earlier release of stable; but launching a cluster just now to see what the state of things is currently: TL;DR exactly the same as before. Though things are improved, improved is a relative term - etcd cluster is still nowhere near stable.

On a three node m3.large cluster running on AWS, nothing running other than fleet + etcd2 using the settings from #3097, load averages around 1.00, with nodes constantly being evicted due to timeouts. You might get one or more nodes in the cluster for a minute or so, then a few seconds later there are suddenly no active nodes, then that's pretty much the way it stays.

**Comment by pstengel** [comment]
@philips Same here as @rdark mentioned. I found that workaround mentioned in a few places. I tried several different values, and none of them resolved the problem.

The work around I'm using for now is just keeping etcd in a separate VPC and keeping the peer traffic private. This is fine for now, but I'd really like to take advantage of local etcd proxies on the worker nodes, and you need peer traffic for that to work.
