### ISSUE TITLE
X-Etcd-Index is less than modifiedIndex

### ISSUE THREAD

**Issue by cmollen** [coreos/etcd#2541]
Repro:

Clean install of 2.0.5. One-node, simply launched with "etcd" on command line. No data. Index is 2. 

Wait for next change:
http://127.0.0.1:4001/v2/keys/test?wait=true&waitIndex=3

Create key:
curl http://127.0.0.1:4001/v2/keys/test -XPUT -d value="Hello world"

Waiting request returns, with modifiedIndex = 3, and X-Etcd-Index = 2. I assume this is not the expected behaviour?

{"action":"set","node":{"key":"/test","value":"Hello world","modifiedIndex":3,"createdIndex":3}}

Remote Address:127.0.0.1:4001
Request URL:http://127.0.0.1:4001/v2/keys/test?wait=true&waitIndex=3
Request Method:GET
Status Code:200 OK
Content-Type:application/json
Date:Thu, 19 Mar 2015 17:37:22 GMT
Transfer-Encoding:chunked
X-Etcd-Cluster-Id:7e27652122e8b2ae
X-Etcd-Index:2
X-Raft-Index:62
X-Raft-Term:2

**Comment by yichengq** [comment]
`X-etcd-index` is the etcd index when this watch starts.

**Comment by cmollen** [comment]
Thank you for the clarification, @yichengq.
