### ISSUE TITLE
Ports 4001 and 7001 are closed when using the peers flag

### ISSUE THREAD

**Issue by iamthemuffinman** [coreos/etcd#2550]
As the title says, ports 4001 and 7001 are being closed when using the peers flag in my cloud-config.yaml file. [Here's](https://gist.github.com/iamthemuffinman/d6fd65480eed7292c422) my config file. When I take out the peers flag, the ports open again.

**Comment by yichengq** [comment]
@iamthemuffinman Could you give more details about it? `systemctl cat etcd` and `journalctl -u etcd` could give you the systemd file and log so far. How did you figure out the ports are closed?

**Comment by iamthemuffinman** [comment]
Ah, I forgot to include that stuff. My apologies. I used nmap in the toolbox container to determine whether or not the ports were open.

[nmap](https://gist.github.com/iamthemuffinman/103006511dfc31a1674e)
[systemctl cat etcd](https://gist.github.com/iamthemuffinman/b8287f29f979c034a098)
[systemctl status etcd -l](https://gist.github.com/iamthemuffinman/9c94da760dab2bc13fa0)

**Comment by iamthemuffinman** [comment]
@yichengq Have you figured anything out about this?

**Comment by yichengq** [comment]
I cannot reproduce it here based on the information so far. Could you reproduce it step by step in very-verbose(-vv) mode and share the full log with me? Before that, please ensure the connection between each other is healthy.

**Comment by iamthemuffinman** [comment]
I've been messing with this for a few weeks now and decided to give up and upgrade to etcd to 2.0. I have had no issues so far with that. Thanks for your help @yichengq

**Comment by yichengq** [comment]
@iamthemuffinman Let me know if you encounter any problem when using 2.0
