### ISSUE TITLE
Installing etcdctl CLI on OSX?

### ISSUE THREAD

**Issue by olalonde** [coreos/etcd#2559]
It is possible to install fleetctl through brew `brew install fleetctl` but I haven't found a way to install `etcdctl` on OS X. What would be the recommended way to do this?

**Comment by AdoHe** [comment]
@olalonde once you installed the etcd in your OS X, you get `etcdctl` installed, it is also in the `bin` folder.

**Comment by olalonde** [comment]
Oh thanks.

**Comment by olalonde** [comment]
@AdoHu It seems there is no flag to tunnel the connection to a remote CoreOS server like fleetctl right?

**Comment by ahosam** [comment]
us brew install etcd, it work. :D
