### ISSUE TITLE
the etcd `--version` flag should print more information 

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#2560]
It would greatly help debugging if etcd would print more version info. I think the way the docker project does this is perfect:

```
$ docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): darwin/amd64
```

**Comment by AdoHe** [comment]
yeah, this is nice...

**Comment by MSamman** [comment]
I'd like to give this a go if no one else is working on it?

**Comment by xiang90** [comment]
@MSamman No one is working on it. Go for it if you want.

**Comment by MSamman** [comment]
I set it so that the `version` flag prints off etcd version, min cluster version, git SHA, OS and architecture.

I didn't see a HTTP API version anywhere, but I also didn't look that hard.
