### ISSUE TITLE
etcd master broken on linux/arm

### ISSUE THREAD

**Issue by bketelsen** [coreos/etcd#2562]
Building on Raspbian, on an original raspberry pi.

HypriotOS: pi@black-pearl in ~/src/github.com/coreos/etcd/bin on master
$ ./etcd --force-new-cluster 'true'
2015/03/22 18:16:29 etcd: no data-dir provided, using default data-dir ./default.etcd
2015/03/22 18:16:29 etcd: listening for peers on http://localhost:2380
2015/03/22 18:16:29 etcd: listening for peers on http://localhost:7001
2015/03/22 18:16:29 etcd: listening for client requests on http://localhost:2379
2015/03/22 18:16:29 etcd: listening for client requests on http://localhost:4001
2015/03/22 18:16:29 etcdserver: name = default
2015/03/22 18:16:29 etcdserver: force new cluster
2015/03/22 18:16:29 etcdserver: data dir = default.etcd
2015/03/22 18:16:29 etcdserver: member dir = default.etcd/member
2015/03/22 18:16:29 etcdserver: heartbeat = 100ms
2015/03/22 18:16:29 etcdserver: election = 1000ms
2015/03/22 18:16:29 etcdserver: snapshot count = 10000
2015/03/22 18:16:29 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/03/22 18:16:29 etcdserver: initial advertise peer URLs = http://localhost:2380,http://localhost:7001
2015/03/22 18:16:29 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
2015/03/22 18:16:29 etcdserver: start member ce2a822cea30bfca in cluster 7e27652122e8b2ae
2015/03/22 18:16:29 INFO: raft: ce2a822cea30bfca became follower at term 0
2015/03/22 18:16:29 INFO: raft: newRaft ce2a822cea30bfca [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/03/22 18:16:29 INFO: raft: ce2a822cea30bfca became follower at term 1
2015/03/22 18:16:29 etcdserver: added local member ce2a822cea30bfca [http://localhost:2380 http://localhost:7001] to cluster 7e27652122e8b2ae
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x4 pc=0x1a8a7c]

goroutine 18 [running]:
sync/atomic.storeUint64(0x10800fd4, 0x1, 0x0)
	/usr/local/go/src/sync/atomic/64bit_arm.go:20 +0x48
github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0x10800fa0, 0x10830e70, 0x1, 0x1, 0x108cbe08, 0x0, 0x0, 0x0)
	/home/pi/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:679 +0x210
github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0x10800fa0)
	/home/pi/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:395 +0xb10
created by github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/home/pi/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:294 +0x2cc
[...]

checking out tag v0.4.6 built and ran perfectly, so this seems to be a regression.  I'm going to update GCC and try again

**Comment by bketelsen** [comment]
installed gcc, rebuilt (with no errors) same stack trace when running.

**Comment by bketelsen** [comment]
similar error after etcd starts, but when it serves its first HTTP request:

2015/03/22 19:57:20 http: panic serving 127.0.0.1:57959: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xb8
sync/atomic.addUint64(0x10939aec, 0x1, 0x0, 0x1, 0x0)
	/usr/local/go/src/sync/atomic/64bit_arm.go:31 +0x70
(This is v0.4.6 - which leads me to believe that there's an error in sync.Atomic on go linux/arm)

**Comment by bketelsen** [comment]
Running all.bash in the Go directory to see if there are tests that fail.  If so, will report upstream.

**Comment by bketelsen** [comment]
no failures in all.bash - leaving this open for now.

**Comment by davecheney** [comment]
See golang/go#599

**Comment by bketelsen** [comment]
Thanks @davecheney - closing here due to upstream issue.
