### ISSUE TITLE
sorted directory returns numeric keys in lexicographic order

### ISSUE THREAD

**Issue by alunduil** [coreos/etcd#2564]
When using a directory as a queue like mentioned in #2490 , we've found that the during digit increases (i.e. 9 → 10) the nodes are sorted lexicographically when using sorted.  This is counter to the way the documentation indicates this use case and appears to be a flaw in etcd's return value when using sorted on a directory.  If this is by design can we get the documentation updated to reflect that?

**Comment by xiang90** [comment]
Now the created key are padded with 0s. We updated the doc here https://github.com/coreos/etcd/blob/master/Documentation/api.md#atomically-creating-in-order-keys.
