### ISSUE TITLE
etcdctl cluster-health problem

### ISSUE THREAD

**Issue by pacasrc** [coreos/etcd#2567]
Hi All,

I found some strange things when I use `etcdctl cluster-health' to get cluster info in v2.0.4 & v2.0.5.
etcdctl cluster-health output the different result between leader node and followers node:

The reproduced step is:
1. create 2 node etcd cluster(hostname: cy_1, cy_2)
2. add 1 node in cluster(hostname: cy_3, 3 node total)
3. stop first 2 node, and restart. Now the leader is on the cy_3.
4. run etcdctl cluster-health on the cy_3
cy_3> etcdctl cluster-health
cluster is healthy
member 9c4b7ed44baf45d6 is healthy
member f4254e5cec3e10bb is healthy
member f99119c17906d2b9 is healthy
5. run etcdctl cluster-health on the first two node(cy_1 or cy_2)
cy_1> etcdctl cluster-health
cluster is unhealthy
 
it seems the output is wrong?

6. the /v2/stats/leader output is the same situation:
cy_3> curl -L http://127.0.0.1:2379/v2/stats/leader
{"leader":"f99119c17906d2b9","followers":{"9c4b7ed44baf45d6":{"latency":{"current":0.011874,"average":0.02430547631578948,"standardDeviation":0.08355942022783903,"minimum":0.007778,"maximum":1.000442},"counts":{"fail":45,"success":380}},"f4254e5cec3e10bb":{"latency":{"current":0.025711,"average":0.03298229519450799,"standardDeviation":0.030884346691124567,"minimum":0.01236,"maximum":0.480749},"counts":{"fail":0,"success":437}}}}

cy_1> curl -L http://127.0.0.1:2379/v2/stats/leader
{"message":"not current leader"}

> etcdctl member list
f99119c17906d2b9: name=cy_3 peerURLs=http://192.168.7.227:2380 clientURLs=http://localhost:2379,http://localhost:4001
f4254e5cec3e10bb: name=cy_2 peerURLs=http://192.168.11.253:2380 clientURLs=http://localhost:2379,http://localhost:4001
9c4b7ed44baf45d6: name=cy_1 peerURLs=http://192.168.10.25:2380 clientURLs=http://localhost:2379,http://localhost:4001
 
Is this by design?

7. But, I can use /v2/stats/self to get the correct leader id on every three nodes:
cy_1> curl -L http://127.0.0.1:2379/v2/stats/self
{"name":"cy_1","id":"9c4b7ed44baf45d6","state":"StateFollower","startTime":"2015-03-18T14:25:52.465264249+08:00","leaderInfo":{"leader":"f99119c17906d2b9","uptime":"10m41.044022573s","startTime":"2015-03-18T14:25:53.102445282+08:00"},"recvAppendRequestCnt":1287,"recvPkgRate":2.010433125475242,"recvBandwidthRate":225.1685100532271,"sendAppendRequestCnt":0} 

cy_3> curl -L http://127.0.0.1:2379/v2/stats/self
{"name":"cy_3","id":"f99119c17906d2b9","state":"StateLeader","startTime":"2015-03-18T14:25:26.519115109+08:00","leaderInfo":{"leader":"f99119c17906d2b9","uptime":"11m7.118240351s","startTime":"2015-03-18T14:25:53.040128152+08:00"},"recvAppendRequestCnt":0,"sendAppendRequestCnt":7494,"sendPkgRate":11.46770008099765,"sendBandwidthRate":826.2477908358807} 

Thanks for any feedback!

**Comment by yichengq** [comment]
Sorry for late response.

The problem comes from that the -advertise-client-URLs are not set(or set to `http://localhost:2379,http://localhost:4001`) on each etcd member. Internally, cluster-health first finds the leader ID, then gets the leader member's clientURLs, then use that urls to make requests. So it needs the correct client URLs registered in the cluster.

In your case, it is actually saying that 'i fetched leader stats from leader, but i failed to do that, so the cluster must be unhealthy'. It may need a better log to let users know what is actually happening.

**Comment by yichengq** [comment]
Let us continue the discussion in #2650 since these two are the same.
