### ISSUE TITLE
client get status code 500

### ISSUE THREAD

**Issue by AdoHe** [coreos/etcd#2569]
Hi All, is there any possibility that when the client requests etcd HTTP API, the client will get http status code 500?

**Comment by yichengq** [comment]
Yes, it indicates the internal server error. Sometimes it happens because the request is proposed, but failed to be committed in the given time.
You can check the response body or the server log to see what the detail it is.

**Comment by AdoHe** [comment]
@yichengq so the client should retry the request?

**Comment by yichengq** [comment]
@AdoHe If the error indicates that the server is under leader election, the client should retry the request because the requests may be dropped when switching leader.

**Comment by AdoHe** [comment]
@yichengq so the client should check the response body, and once the `errorCode` is `301`, the client should retry this request?

**Comment by yichengq** [comment]
Yes. If the cluster is always under leader election, this could be a problem too. Either the majority of the cluster is dead, or the cluster is under frequent leader switch. Admin should check the status of the cluster then.

**Comment by AdoHe** [comment]
@yichengq thanks :)
