### ISSUE TITLE
Cluster network throughput

### ISSUE THREAD

**Issue by durzo** [coreos/etcd#2585]
I'm running a 3 node cluster on aws t2.small ec2 instances.
At idle (no clients reading or writing), I see network throughput of between 100-170 kilobytes/second throughput on all 3 nodes with the leader being the highest.

Is this normal? should I increase my heartbeat interval?

Current heartbeat is 100, election timeout is 1000 - I am not seeing anything in the logs to suggest heartbeat time outs or election failures.

2 nodes are in AZ-A with 0.4ms ping, 1 node is in AZ-B with a 1ms ping to/from the nodes in AZ-A
all 3 nodes are in the same region.

**Comment by yichengq** [comment]
Yes, this is normal.
etcd does some internal sync, and that consumes some network throughput.
Based on your network case, i think default setting should work well for you.

**Comment by durzo** [comment]
Good to know, thanks
