### ISSUE TITLE
Running back-2-back tests split-brain condition, unrecoverable. 

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2592]
We were running tests on kubernetes and encountered a split-brain issue, we are pouring through the logs and data to diagnose.  Is there a secure place to handoff data?  

etcd version 2.0.4+git  635e4db6d942cd84e8b613c37c6b47f8c06b94dd

Here are the symptoms: 

\#etcdctl ls /
/coreos.com
/fuckotest

curl -L http://host01-rack10:4001/v2/keys/ | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0  29181      0 --:--:-- --:--:-- --:--:-- 32333
{
    "action": "get",
    "node": {
        "dir": true,
        "nodes": [
            {
                "createdIndex": 5,
                "dir": true,
                "key": "/coreos.com",
                "modifiedIndex": 5
            },
            {
                "createdIndex": 3880163,
                "dir": true,
                "key": "/fuckotest",
                "modifiedIndex": 3880163
            }
        ]
    }
}

\# curl -L http://host02-rack10:4001/v2/keys/ | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   189  100   189    0     0  30691      0 --:--:-- --:--:-- --:--:-- 37800
{
    "action": "get",
    "node": {
        "dir": true,
        "nodes": [
            {
                "createdIndex": 5,
                "dir": true,
                "key": "/registry",
                "modifiedIndex": 5
            },
            {
                "createdIndex": 15588,
                "dir": true,
                "key": "/coreos.com",
                "modifiedIndex": 15588
            }
        ]
    }
}

\# curl -L http://host17-rack11:4001/v2/keys/ | python -mjson.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   113  100   113    0     0  41061      0 --:--:-- --:--:-- --:--:-- 56500
{
    "action": "get",
    "node": {
        "dir": true,
        "nodes": [
            {
                "createdIndex": 4,
                "dir": true,
                "key": "/registry",
                "modifiedIndex": 4
            }
        ]
    }
}

**Comment by xiang90** [comment]
@timothysc xiang.li@coreos.com Thanks!

**Comment by xiang90** [comment]
@timothysc I have not received the log. Can you try to resend it? Or can you please upload it to somewhere so that I can get it to look into?

**Comment by jayunit100** [comment]
meanwhile, is there a etcd health test we can run periodically ?  I was going to cobble a bash script together to do something simple, but maybe someone already has one

**Comment by xiang90** [comment]
@jayunit100 https://github.com/coreos/etcd/tree/master/tools/functional-tester

We have our own functional tester here. You can write you own failure case, it will check the healthy for you.

**Comment by timothysc** [comment]
@xiang90 Send a private share as the data-dirs are large

**Comment by xiang90** [comment]
@timothysc @jayunit100 
After examining the log and snapshot, all three nodes are running separately with default configuration. So they are 3 one-node clusters. All nodes have the same id `ce2a822cea30bfca.`

**Comment by timothysc** [comment]
That's weird, below are our configs. 

host01-rack10.scale.openstack.engineering.redhat.com

ETCD_NAME=host01-rack10
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="http://host01-rack10.scale.openstack.engineering.redhat.com:2380,http://localhost:2380,http://host01-rack10.scale.openstack.engineering.redhat.com:7001,http://localhost:7001"
ETCD_LISTEN_CLIENT_URLS="http://host01-rack10.scale.openstack.engineering.redhat.com:2379,http://localhost:2379,http://host01-rack10.scale.openstack.engineering.redhat.com:4001,http://localhost:4001"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://host01-rack10.scale.openstack.engineering.redhat.com:2380,http://localhost:2380,http://host01-rack10.scale.openstack.engineering.redhat.com:7001,http://localhost:7001"
ETCD_INITIAL_CLUSTER="host01-rack10=http://host01-rack10.scale.openstack.engineering.redhat.com:7001,host02-rack10=http://host02-rack10.scale.openstack.engineering.redhat.com:7001,host17-rack11=http://host17-rack11.scale.openstack.engineering.redhat.com:7001"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-1"
ETCD_ADVERTISE_CLIENT_URLS="http://host01-rack10.scale.openstack.engineering.redhat.com:2379,http://localhost:2379,http://host01-rack10.scale.openstack.engineering.redhat.com:4001,http://localhost:4001"

host02-rack10.scale.openstack.engineering.redhat.com
ETCD_NAME=host02-rack10
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="http://host02-rack10.scale.openstack.engineering.redhat.com:2380,http://localhost:2380,http://host02-rack10.scale.openstack.engineering.redhat.com:7001,http://localhost:7001"
ETCD_LISTEN_CLIENT_URLS="http://host02-rack10.scale.openstack.engineering.redhat.com:2379,http://localhost:2379,http://host02-rack10.scale.openstack.engineering.redhat.com:4001,http://localhost:4001"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://host02-rack10.scale.openstack.engineering.redhat.com:2380,http://localhost:2380,http://host02-rack10.scale.openstack.engineering.redhat.com:7001,http://localhost:7001"
ETCD_INITIAL_CLUSTER="host01-rack10=http://host01-rack10.scale.openstack.engineering.redhat.com:7001,host02-rack10=http://host02-rack10.scale.openstack.engineering.redhat.com:7001,host17-rack11=http://host17-rack11.scale.openstack.engineering.redhat.com:7001"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-1"
ETCD_ADVERTISE_CLIENT_URLS="http://host02-rack10.scale.openstack.engineering.redhat.com:2379,http://localhost:2379,http://host02-
rack10.scale.openstack.engineering.redhat.com:4001,http://localhost:4001"

host17-rack11.scale.openstack.engineering.redhat.com
ETCD_NAME="host17-rack11"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="http://host17-rack11.scale.openstack.engineering.redhat.com:2380,http://localhost:2380,http://host17-rack11.scale.openstack.engineering.redhat.com:7001,http://localhost:7001"
ETCD_LISTEN_CLIENT_URLS="http://host17-rack11.scale.openstack.engineering.redhat.com:2379,http://localhost:2379,http://host17-rack11.scale.openstack.engineering.redhat.com:4001,http://localhost:4001"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://host17-rack11.scale.openstack.engineering.redhat.com:2380,http://localhost:2380,http://host17-rack11.scale.openstack.engineering.redhat.com:7001,http://localhost:7001"
ETCD_INITIAL_CLUSTER="host01-rack10=http://host01-rack10.scale.openstack.engineering.redhat.com:7001,host02-rack10=http://host02-rack10.scale.openstack.engineering.redhat.com:7001,host17-rack11=http://host17-rack11.scale.openstack.engineering.redhat.com:7001"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-1"
ETCD_ADVERTISE_CLIENT_URLS="http://host17-rack11.scale.openstack.engineering.redhat.com:2379,http://localhost:2379,http://host17-rack11.scale.openstack.engineering.redhat.com:4001,http://localhost:4001"

**Comment by xiang90** [comment]
@timothysc From the data, the initial cluster is not set as you posted here. I suspected that you gave the configuration to an existing cluster and it will ignore the initial configuration.

**Comment by xiang90** [comment]
All the members' `initial-peer-urls` are just default localhost.

**Comment by timothysc** [comment]
What would happen if the cluster machines were 1st started as a local setup, then converted?

**Comment by yichengq** [comment]
@timothysc You can check the members in the cluster at endpoint /v2/members.https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#list-members

To verify 3 one-node clusters, you can fetch /v2/members on all three members you are running now.
You can start from a empty data dir, run these commands with `initial-peer-urls` set as xiang suggested, and check the members of cluster using /v2/members.

**Comment by yichengq** [comment]
@timothysc When there is a data dir, it ignores the inital flags.
And it prints out what it starts with:
```
2015/03/30 11:33:27 etcdserver: loaded cluster information from store: default=http://localhost:2380,default=http://localhost:7001
2015/03/30 11:33:27 etcdserver: restart member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit index 20062
```

**Comment by xiang90** [comment]
@timothysc 

> What would happen if the cluster machines were 1st started as a local setup, then converted?

You need to do runtime configuration to add members to an existing cluster. 
https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md

Changing the configuration and restart will not help.

**Comment by timothysc** [comment]
k, this may be an order of operation on our part then.  

but this was good to know.

**Comment by xiang90** [comment]
@timothysc Closing this. Thanks for the reporting!

**Comment by timothysc** [comment]
k, I wiped contents reset configs removing legacy setup and all was well.  

Ordering appeared to be the issue.
