### ISSUE TITLE
vmware esxi etcd connection denied

### ISSUE THREAD

**Issue by nrbrt** [coreos/etcd#2602]
I am using the latest stable coreos-vmware.ova image and a config iso with a user_data file on 2 vmware vm's. I have configured fixed ip's and that works fine. I can't get etcd working because the ports 4001 and 7001 are not open for some reason. I tried to telnet from a different machine to these ports and they seem to be closed on both machines. I have not configured iptables and when I run iptables --list it shows no rules.
my user_data file looks like this:

```
#cloud-config

hostname: core-2

write_files:
    - path: /etc/systemd/network/static.network
      permissions: 0644
      content: |
        [Match]
        Name=en*

        [Network]
        Address=172.16.66.202/24
        Gateway=172.16.66.1
        DNS=172.16.66.20

ssh_authorized_keys:
- ssh-rsa XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

coreos:
  etcd:
      name: core-2
      discovery: https://discovery.etcd.io/XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      addr: 172.16.66.202:4001
      peer-addr: 172.16.66.202:7001
  fleet:
      public-ip: 172.16.66.202
      metadata: lavaleriana

  units:
    - name: vmtoolsd.service
      command: start
      content: |
        [Unit]
        Description=VMware Tools Agent
        Documentation=http://open-vm-tools.sourceforge.net/
        ConditionVirtualization=vmware

        [Service]
        ExecStartPre=/usr/bin/ln -sfT /usr/share/oem/vmware-tools /etc/vmware-tools
        ExecStart=/usr/share/oem/bin/vmtoolsd
        TimeoutStopSec=5

    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
  oem:
    bug-report-url: "https://github.com/coreos/bugs/issues"
    id: vmware
    name: VMWare
    version-id: "9.4.6"

```

The problem is that journalctl -u etcd produces this:

```
Mar 30 08:15:18 core-2 etcd[1225]: [etcd] Mar 30 08:15:18.181 INFO      | Discovery via https://discovery.etcd.io using prefix /XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Mar 30 08:15:19 core-2 etcd[1225]: [etcd] Mar 30 08:15:19.465 INFO      | Discovery found peers [http://172.16.66.203:7001]
Mar 30 08:15:19 core-2 etcd[1225]: [etcd] Mar 30 08:15:19.465 INFO      | Discovery fetched back peer list: [172.16.66.203:7001]
Mar 30 08:15:19 core-2 etcd[1225]: [etcd] Mar 30 08:15:19.465 INFO      | core-2 attempted to join via 172.16.66.203:7001 failed: fail checking join version: Client Internal Error (Get http://172.16.66.203:7001/version: dial tcp 172.16.66.203:7001: connection refused)
Mar 30 08:15:19 core-2 etcd[1225]: [etcd] Mar 30 08:15:19.465 INFO      | core-2 is unable to join the cluster using any of the peers [172.16.66.203:7001] at 0th time. Retrying in 3.6 seconds
Mar 30 08:15:22 core-2 etcd[1225]: [etcd] Mar 30 08:15:22.466 INFO      | core-2 attempted to join via 172.16.66.203:7001 failed: fail checking join version: Client Internal Error (Get http://172.16.66.203:7001/version: dial tcp 172.16.66.203:7001: connection refused)
Mar 30 08:15:22 core-2 etcd[1225]: [etcd] Mar 30 08:15:22.466 INFO      | core-2 is unable to join the cluster using any of the peers [172.16.66.203:7001] at 1th time. Retrying in 3.6 seconds
Mar 30 08:15:25 core-2 etcd[1225]: [etcd] Mar 30 08:15:25.466 INFO      | core-2 attempted to join via 172.16.66.203:7001 failed: fail checking join version: Client Internal Error (Get http://172.16.66.203:7001/version: dial tcp 172.16.66.203:7001: connection refused)
Mar 30 08:15:25 core-2 etcd[1225]: [etcd] Mar 30 08:15:25.467 WARNING   | core-2 cannot connect to existing peers [172.16.66.203:7001]: fail joining the cluster via given peers after 3 retries
Mar 30 08:15:25 core-2 etcd[1225]: [etcd] Mar 30 08:15:25.467 CRITICAL  | fail joining the cluster via given peers after 3 retries
Mar 30 08:15:25 core-2 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Mar 30 08:15:25 core-2 systemd[1]: Unit etcd.service entered failed state.
Mar 30 08:15:25 core-2 systemd[1]: etcd.service failed.

```

So it does find it's peer via the discovery url and tries the correct ip (172.16.66.203), but it can't connect.  Both machines have the same errors about the connection being refused in their logs. What am I missing here? I hope someone can help me out. Thnx

**Comment by nrbrt** [comment]
UPDATE: when I start etcd from the commandline with the same options, it does seem to work. What am I doing wrong in the user_data file? I would really appreciate any pointers....

**Comment by philips** [comment]
@nrbrt Can you `curl 172.16.66.203:7001`? Are both hosts up?

**Comment by nrbrt** [comment]
@philips I can't connect to either host with curl or telnet for that matter. Both hosts are up and I have access with ssh. I have stopped trying to get this working with the user_data file for the moment. I am trying to get it to work from the command line first. Not having much luck I am sad to say. When start etcd from the command line, I can connect with curl. I keep having other issues though.
It seems strange that there is so little actual information on the combination coreos and vsphere 5.5. Most examples for vmware stop where they show you how to get the ssh keys in place and seem to assume that after that etcd is running. No word about how to get it to do just that other than that $private_ipv4 and $public_ipv4 substitution variables don't work for vmware in the etcd part of the config file.( https://coreos.com/docs/running-coreos/platforms/vmware/ ) I am feeling a bit lost to be honest. Once I figure this out, I will write a proper howto on this. That is, on using the coreos-vmware.ova file and creating a working user_data file packaged in an .iso file that leaves you with a vm with a fixed or dynamic ip address and functional etcd and fleet services. For the moment, I keep on struggling and will post another question when I have a more concrete one than just "please help" ;-)

**Comment by nrbrt** [comment]
I have resolved most issues and things are working nicely now. Mostly it was a case of trying to run before I could walk. I will still write that howto to guide people like me, for whom this is their first brush with coreOS. Closing the case.
