### ISSUE TITLE
deprecate `--ca-file` and `--peer-ca-file`

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2609]
- [x] deprecate `--ca-file` and `--peer-ca-file`
- [x] update related documents

/cc @kelseyhightower

**Comment by jelmer** [comment]
what would --ca-file be replaced by?

**Comment by yichengq** [comment]
@jelmer We will use `--trusted-ca-file` and `--client-cert-auth` instead. It makes TLS setting more clear for better UX. `--ca-file XXX` == `--trusted-ca-file XXX --client-cert-auth`

**Comment by yichengq** [comment]
all done.
