### ISSUE TITLE
Election timeout and heartbeat are they per instance or cluster init?

### ISSUE THREAD

**Issue by agokjr** [coreos/etcd#2618]
election_timeout and heartbeat_interval are they per instance or cluster init?
Can they been changed to an existing cluster?

**Comment by xiang90** [comment]
@agokjr They should be set consistently across the cluster. They can be reset, but should be reset to the same value across all the members. We have long-term plan to make this dynamically reconfigurable across the cluster.

**Comment by agokjr** [comment]
Ok sound good.
