### ISSUE TITLE
Support for verifying peer certificates using TLSA records

### ISSUE THREAD

**Issue by jelmer** [coreos/etcd#2632]
It would be great if etcd supported TLSA records for verifying peer certificates as an alternative to ca certificates.

https://tools.ietf.org/html/draft-ietf-dane-protocol-23

**Comment by yichengq** [comment]
What is the benefits of TLSA records?
I think it needs to set DNS location, and its complication is the same as setting ca certificates.

**Comment by jelmer** [comment]
On Fri, Apr 17, 2015 at 03:18:49PM -0700, Yicheng Qin wrote:
> What is the benefits of TLSA records?
> I think it needs to set DNS location, and its complication is the same as setting ca certificates.
It doesn't require distributing the custom CA to all peers.

**Comment by xiang90** [comment]
@yichengq Can you move forward this issue?

**Comment by yichengq** [comment]
@jelmer This method requires users to set a separate DNS server, right?

I don't see there are strong requirements for this feature, so I prefer to put it in low-priority queue now.

/cc @philips

**Comment by jelmer** [comment]
yes, it would require a separate DNS server.

**Comment by xiang90** [comment]
@yichengq Any more thought on this?

**Comment by yichengq** [comment]
@xiang90 I would put the feature in low-priority queue, and consider it more when more users ask for it.

**Comment by gyuho** [comment]
No plan to support this as of now.

If anybody has a strong use case, please create a new issue.
