### ISSUE TITLE
DNS discovery for etcdctl

### ISSUE THREAD

**Issue by nixn** [coreos/etcd#2636]
It would be nice to have the possibility to use the same DNS discovery with etcdctl as with confd (which is the SRV entry _etcd._tcp.example.com). It could be something like `etcdctl -D example.com ...`. That's fault-tolerant (one must not know which hosts are up or even how they are called) and much faster typing than `etcdctl -C http://etcd1.example.com:2379,http://etcd2.example.com:2379 ...`.

**Comment by ripienaar** [comment]
+1 this would be really good to have

**Comment by delianides** [comment]
+1 for this but I would also add the same behavior for discovery urls/tokens.

**Comment by xiang90** [comment]
@yichengq @philips @barakmich How do you think make this a target of 2.2?

**Comment by yichengq** [comment]
The feature sounds good. It makes etcdctl more flexible and easier to use.

**Comment by xiang90** [comment]
We already added the discovery functionality into etcd/client. 
https://github.com/coreos/etcd/blob/master/client/discover.go

We need to hook it up with etcdctl now.

**Comment by yichengq** [comment]
Note: please make change and send PR on branch dev-2.2

**Comment by MSamman** [comment]
What should occur if both DNS discovery and peers options are provided? Concatenate the endpoints? Ignore one or the other?

**Comment by xiang90** [comment]
@MSamman I think we should use the result of discovery.

**Comment by yichengq** [comment]
fixed by #3115 . Thanks @MSamman !

**Comment by MSamman** [comment]
NP.
