### ISSUE TITLE
etcdctl exec-watch unreliable

### ISSUE THREAD

**Issue by spyrospph** [coreos/etcd#2644]
Hi,

I am using exec-watch to continuously watch a specific etcd value and when that changes to execute a few commands.

```
[Service]
User=core
TimeoutSec=15m
RemainAfterExit=yes
EnvironmentFile=/etc/environment
ExecStartPre=/usr/bin/docker pull test/test
ExecStart=/bin/etcdctl exec-watch /foo/bar -- /usr/bin/bash -c ' \
        VERSION=$(etcdctl get /test/version); \
        echo "Received new version: $VERSION"; \
        /usr/bin/docker pull test/data:$VERSION; \
        /usr/bin/docker create -v /var/www --name somedata_$VERSION test/data:$VERSION; \
        /usr/bin/docker run --rm --name whatever_$VERSION --env-file /tmp/test-$VERSION test/somecont & \
        /usr/bin/docker run -d --name whateverelse_$VERSION --volumes-from somedata_$VERSION  test/someothercont; 
 ```

Problem is that sometimes exec-watch does not get triggered AT ALL. Behavior is fairly random and if it does not get triggered I then have to restart my service.

```
sudo systemctl restart servicename.service
```

Post-restart of service,exec-watch gets triggered successfully, just to fail at some coreos nodes in the next etcdctl sets.

I have tried this with coreos 557.2.0 as well as the latest stable 607.0.0.

Any ideas what is wrong or how I can troubleshoot this?

**Comment by niclashoyer** [comment]
I just experienced the same issues on a single node cluster (just tried out exec-watch).

**Comment by xiang90** [comment]
@spyrospph 
@niclashoyer 
Can any of you reproduce the issue on dev2.2 branch?

**Comment by xiang90** [comment]
This seems to be duplicated with https://github.com/coreos/etcd/issues/1518. 

I cannot reproduce this on etcd2 (both 1,3 member cluster). Please give etcd2 a try. If you can reproduce the issue. Please reopen it.

**Comment by petergardfjall** [comment]
I'm seeing this issue on `CoreOS alpha (935.0.0)`.

I've set up a 3-node cluster in Vagrant following the instructions [here](https://coreos.com/os/docs/latest/booting-on-vagrant.html), running the `stable channel` edition.

Then, I've simply been playing with `etcd` according to the instructions in the [Getting started with etcd](https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html) guide.

On one host (`core-02`) I'm running 

    etcdctl exec-watch --recursive /messages -- sh -c 'echo $ETCD_WATCH_VALUE'

On host `core-01` I'm doing:

    etcdctl set /messages/msg1 '1'
    etcdctl set /messages/msg1 '2'
    etcdctl set /messages/msg1 '3'
    ...
    etcdctl set /messages/msg1 '15'

Although one would expect all numbers from 1 to 15 to be output on `core-02`, it only displays the following:

    7
    13

So, `exec-watch` is triggered somewhat arbitrarily.

**Comment by petergardfjall** [comment]
I've opened a separate issue #4287 to track this bug.
