### ISSUE TITLE
boltdb evaluation

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2646]
We want to explore the disk backend options for etcd.

We have the following requirement:

1. Pure Go
2. Reliable
3. Predictable Performance
4. Non-blocking Snapshot

After initial comparison between `bitcask`, `leveldb` and `boltdb`, we think `boltdb` might be the best choice.

We want to evaluate boltdb from the following aspect:

1. API - Write a simple coalescer 
2. Reliability - Tear Down testing for 
3. Write amplification - Amplification factor for 64,128,1024 bytes value
4. Memory usage - The memory usage pattern of boltdb

**Comment by xiang90** [comment]
### Sequential Write Amplification 

The amplification factor is around  4 for small keys and 2 for large keys. It is acceptable for our use cases (Target at 10 128bytes keys).  With high FillPrecent and sequential writes, the best we can get is 2.

It is consistent with LMDB, which is tested at http://influxdb.com/blog/2014/06/20/leveldb_vs_rocksdb_vs_hyperleveldb_vs_lmdb_performance.html

From ben
```
you can tweak the `Bucket.FillPercent` if you know you're only writing sequentially. that should shrink it down.
when a page splits it puts half the data in one page and half in the other. if you're writing sequentially with a `FillPercent` of `1.0` then it'll leave all the data in the first page and just the new data in the second.
```

Default FillPrecent (worst case)

#### 64kb pre key

| Number | Ideal Size in MB | Actual Size in MB | Factor |
|--------|------------------|-------------------|--------|
| 1M     | 64               | 269               | 4.2    |
| 10M    | 640              | 2200              | 3.5    |

#### 128kb pre key

| Number | Ideal Size in MB | Actual Size in MB | Factor |
|--------|------------------|-------------------|--------|
| 1M     | 128               | 539              | 4.2    |
| 10M    | 1280              | 3300             | 2.6    |

#### 1024kb pre key

| Number | Ideal Size in MB | Actual Size in MB | Factor |
|--------|------------------|-------------------|--------|
| 1M     | 1024               | 2200               | 2.2    |
| 10M    | 10240              | 22000              | 2.2    |

With FillPercent = 1.0

#### 128kb pre key

| Number | Ideal Size in MB | Actual Size in MB | Factor |
|--------|------------------|-------------------|--------|
| 1M     | 128               | 268               | 2.2    |
| 10M    | 1280              | 2200           | 2.2    |

### Sequential Write + Sequential Delete Amplification 

The amplification factor is the same. The trick part is deletion will not reclaim disk space and mapped memory.

**Comment by xiang90** [comment]
## Memory Usage

bolt can use up all available memory as os page cache if the working set is large (10GB Virtual Memory when the data size is 10GB, and all available 1GB RSS) in my experiments. 

It won't swap out the allocated memory from other application though.

If the working set is small, the RSS is small (10x MBs) and Virtual remains the same (expected due to mmap).

We should suggest people to have enough memory to hold the working set of data in memory anyway. 

The overall memory usage amplification is about 3X with real data. If there are 1M 128bytes keys, the memory is around 400MB (ideally 128MB). If the dataset is larger than the real physical the db can use, it will swap out old pages rather than OOM (today we will OOM since we do need the physical memory).

from README
```
Bolt uses a memory-mapped file so the underlying operating system handles the caching of the data. 

Typically, the OS will cache as much of the file as it can in memory and will release memory as needed to other processes. 

This means that Bolt can show very high memory usage when working with large databases. However, this is expected and the OS will release memory as needed. 

Bolt can handle databases much larger than the available physical RAM.
```

**Comment by xiang90** [comment]
### Reliability 

We check the reliability by killing the db during the write transactions as following

// check if there is any previous committed transaction lost
// check if the db is in corrupted states
do_db_check()
if check_failed {
    panic()
}

// can be killed at anytime during for loop
for {
    do_tnxs()
}

Bolt survives for a two days long testing. Maybe a harsher test?

From ben
```
the copy-on-write design from LMDB makes it pretty easy to ensure consistency. nothing gets committed until the meta page is written and that has a checksum on it to verify.
```

Code:

https://github.com/xiang90/bolt-torturing

https://github.com/boltdb/bolt/blob/master/simulation_test.go

**Comment by xiang90** [comment]
Are these reasonable to you @benbjohnson?

**Comment by benbjohnson** [comment]
lgtm :+1:

**Comment by xiang90** [comment]
The evaluation went well. We are working on a new bolt backed storage system.

**Comment by benbjohnson** [comment]
:tada:
