### ISSUE TITLE
v3 api/store design

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2647]
We have been working really hard on the internal raft. As the new raft getting stable, we are starting to design the new API/store for etcd. 

Here are the feature requests from the community that we plan to support:

1. Optimistic concurrency https://github.com/GoogleCloudPlatform/kubernetes/issues/1957#issuecomment-69863343
2. Access to past versions of objects (after history compaction) https://github.com/GoogleCloudPlatform/kubernetes/issues/1957#issuecomment-69863343
3. Efficient reliable and recursive watch https://github.com/GoogleCloudPlatform/kubernetes/issues/1957#issuecomment-69863343
4. Multi-object transactions https://github.com/coreos/etcd/issues/1282 https://github.com/coreos/etcd/issues/860 https://github.com/coreos/etcd/issues/652
5. The ability to somehow build multiple indices https://github.com/coreos/etcd/issues/860 https://github.com/coreos/etcd/issues/1548
6. Pagination support https://github.com/GoogleCloudPlatform/kubernetes/issues/1957#issuecomment-69863343
7. Low per-object memory footprint https://github.com/GoogleCloudPlatform/kubernetes/issues/1957#issuecomment-69863343
8. Object TTLs (for events, logically deleted objects) https://github.com/coreos/etcd/issues/1232
9. Allow clients to request watch heartbeats to refresh the clients window https://github.com/coreos/etcd/issues/2048
10. Binary key and value https://github.com/coreos/etcd/issues/1548
11. On-disk storage https://github.com/coreos/etcd/issues/732

We plan to send out an API proposal mid April for feedback. 

cc all the related people to see if I missed something important.
@derekwaynecarr  @tristanz @klizhentas @mauricioabreu @victorpoluceno @ytjohn @ehames  @sachja  @bgrant0607 @sckott  @lavalamp @smarterclayton @technoweenie @hchoudh
@wojtek-t

**Comment by AdoHe** [comment]
Cool :+1:

**Comment by lavalamp** [comment]
List looks good!

**Comment by smarterclayton** [comment]
Yeah, awesome list.

**Comment by wojtek-t** [comment]
I agree - the list looks really good!

**Comment by xiang90** [comment]
closed in favor of https://github.com/coreos/etcd/pull/2675

**Comment by kapilt** [comment]
list looks pretty good, some comments on a few below.

- one item not mentioned, acls...
- the multi object atomic sounds great to be able to replace zookeeper setups.
- 5 / indexes is a bit unclear, there typically app specific and given the multi object atomic primitive applications can construct these themselves.
- pagination around a path/container listing would be great.
- i wonder at the cost and use cases around past object version history post compaction. along with recursive watch their in my nice to have features.

**Comment by xiang90** [comment]
@kapilt Can you please comment in https://github.com/coreos/etcd/pull/2675 as well? We moved the discussion to there. Thanks!
