### ISSUE TITLE
How to config etcd cluster

### ISSUE THREAD

**Issue by dreameryan** [coreos/etcd#2652]
I try to build up etcd cluster according to:
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md
The static way.

I run following command on 2 machines:
/home/idcuser/HATest/etcd-v2.0.9-linux-amd64/etcd -name monitorserver1 -listen-peer-urls http://10.120.73.86:7001 -listen-client-urls http://10.120.73.86:4001 -initial-cluster-token monitorserver-cluster -initial-advertise-peer-urls http://10.120.73.86:7001 -initial-cluster monitorserver1=http://10.120.73.86:7001,monitorserve2=http://10.112.206.10:2380 -initial-cluster-state new &>> /home/idcuser/HATest/etcd.log &

/home/idcuser/HATest/etcd-v2.0.9-linux-amd64/etcd -name monitorserver2 -listen-peer-urls http://10.112.206.10:2380 -listen-client-urls http://10.112.206.10:2379 -initial-cluster-token monitorserver-cluster -initial-advertise-peer-urls http://10.112.206.10:2380 -initial-cluster monitorserver1=http://10.120.73.86:7001,monitorserver2=http://10.112.206.10:2380 -initial-cluster-state new &>> /home/idcuser/HATest/etcd.log &

But when I run client.machines. It will output 
machines [u'http://localhost:2379', u'http://localhost:2379', u'http://localhost:4001', u'http://localhost:4001']
Seems it still find cluster machines from localhost.

**Comment by xiang90** [comment]
Can you provide the log output from etcd process?

**Comment by dreameryan** [comment]
@xiang90
Hi. 
I tried to modify monitorserve2 to monitorserver2, but it still not work.
etcdctrl member list still shows localhost ips:
[idcuser@docker-itm-agent-dal01 etcd-v2.0.9-linux-amd64]$ ./etcdctl member list
145f81b1e050b7c7: name=monitorserver2 peerURLs=http://127.0.0.1:2380 clientURLs=http://localhost:2379,http://localhost:4001
3260c3386e0bf9d8: name=monitorserver1 peerURLs=http://127.0.0.1:7001 clientURLs=http://localhost:2379,http://localhost:4001

I could ping each other successfully on each machine
And the port is working on each machine.
[10.120.73.86]$ netstat -ano| grep 7001
tcp 0 0 10.120.73.86:7001 0.0.0.0:* LISTEN off (0.00/0/0)
[10.112.206.10]$ netstat -ano|grep 2380
tcp 0 0 10.112.206.10:2380 0.0.0.0:* LISTEN off (0.00/0/0)

on monitorserver1 machine, etcd log as below:
2015/04/12 04:04:18 etcd: no data-dir provided, using default data-dir ./monitorserver1.etcd
2015/04/12 04:04:18 etcd: already initialized as member before, starting as etcd member...
2015/04/12 04:04:18 etcd: listening for peers on http://10.120.73.86:7001
2015/04/12 04:04:18 etcd: listening for client requests on http://localhost:2379
2015/04/12 04:04:18 etcd: listening for client requests on http://localhost:4001
2015/04/12 04:04:18 etcdserver: datadir is valid for the 2.0.1 format
2015/04/12 04:04:18 etcdserver: name = monitorserver1
2015/04/12 04:04:18 etcdserver: data dir = monitorserver1.etcd
2015/04/12 04:04:18 etcdserver: member dir = monitorserver1.etcd/member
2015/04/12 04:04:18 etcdserver: heartbeat = 100ms
2015/04/12 04:04:18 etcdserver: election = 1000ms
2015/04/12 04:04:18 etcdserver: snapshot count = 10000
2015/04/12 04:04:18 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/04/12 04:04:18 etcdserver: restart member 3260c3386e0bf9d8 in cluster d32407294ef780c at commit index 313
2015/04/12 04:04:18 raft: 3260c3386e0bf9d8 became follower at term 7872
2015/04/12 04:04:18 raft: newRaft 3260c3386e0bf9d8 [peers: [], term: 7872, commit: 313, applied: 0, lastindex: 313, lastterm: 142]
2015/04/12 04:04:18 etcdserver: added member 145f81b1e050b7c7 [http://127.0.0.1:2380] to cluster d32407294ef780c
2015/04/12 04:04:18 raft: newRaft 3260c3386e0bf9d8 [peers: [], term: 7872, commit: 313, applied: 0, lastindex: 313, lastterm: 142]
2015/04/12 04:04:18 etcdserver: added member 145f81b1e050b7c7 [http://127.0.0.1:2380] to cluster d32407294ef780c
2015/04/12 04:04:18 etcdserver: added local member 3260c3386e0bf9d8 [http://127.0.0.1:7001] to cluster d32407294ef780c
2015/04/12 04:04:19 raft: 3260c3386e0bf9d8 is starting a new election at term 7872
2015/04/12 04:04:19 raft: 3260c3386e0bf9d8 became candidate at term 7873
2015/04/12 04:04:19 raft: 3260c3386e0bf9d8 received vote from 3260c3386e0bf9d8 at term 7873
2015/04/12 04:04:19 raft: 3260c3386e0bf9d8 [logterm: 142, index: 313] sent vote request to 145f81b1e050b7c7 at term 7873
2015/04/12 04:04:19 sender: error posting to 145f81b1e050b7c7: dial tcp 127.0.0.1:2380: connection refused
2015/04/12 04:04:19 sender: the connection with 145f81b1e050b7c7 became inactive
2015/04/12 04:04:21 raft: 3260c3386e0bf9d8 is starting a new election at term 7873
2015/04/12 04:04:21 raft: 3260c3386e0bf9d8 became candidate at term 7874
2015/04/12 04:04:21 raft: 3260c3386e0bf9d8 received vote from 3260c3386e0bf9d8 at term 7874
2015/04/12 04:04:21 raft: 3260c3386e0bf9d8 [logterm: 142, index: 313] sent vote request to 145f81b1e050b7c7 at term 7874
2015/04/12 04:04:21 raft: 3260c3386e0bf9d8 received vote from 3260c3386e0bf9d8 at term 7874
2015/04/12 04:04:21 raft: 3260c3386e0bf9d8 [logterm: 142, index: 313] sent vote request to 145f81b1e050b7c7 at term 7874
2015/04/12 04:04:22 raft: 3260c3386e0bf9d8 is starting a new election at term 7874
2015/04/12 04:04:22 raft: 3260c3386e0bf9d8 became candidate at term 7875
2015/04/12 04:04:22 raft: 3260c3386e0bf9d8 received vote from 3260c3386e0bf9d8 at term 7875

on monitorserver2 machine ,etcd log as below:
2015/04/12 04:06:02 etcd: no data-dir provided, using default data-dir ./monitorserver2.etcd
2015/04/12 04:06:02 etcd: already initialized as member before, starting as etcd member...
2015/04/12 04:06:02 etcd: listening for peers on http://10.112.206.10:2380
2015/04/12 04:06:02 etcd: listening for client requests on http://localhost:2379
2015/04/12 04:06:02 etcd: listening for client requests on http://localhost:4001
2015/04/12 04:06:02 etcdserver: datadir is valid for the 2.0.1 format
2015/04/12 04:06:02 etcdserver: name = monitorserver2
2015/04/12 04:06:02 etcdserver: data dir = monitorserver2.etcd
2015/04/12 04:06:02 etcdserver: member dir = monitorserver2.etcd/member
2015/04/12 04:06:02 etcdserver: heartbeat = 100ms
2015/04/12 04:06:02 etcdserver: election = 1000ms
2015/04/12 04:06:02 etcdserver: snapshot count = 10000
2015/04/12 04:06:02 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/04/12 04:06:02 etcdserver: restart member 145f81b1e050b7c7 in cluster d32407294ef780c at commit index 2124
2015/04/12 04:06:02 raft: 145f81b1e050b7c7 became follower at term 7893
2015/04/12 04:06:02 raft: newRaft 145f81b1e050b7c7 [peers: [], term: 7893, commit: 2124, applied: 0, lastindex: 2124, lastterm: 12]
2015/04/12 04:06:02 etcdserver: added local member 145f81b1e050b7c7 [http://127.0.0.1:2380] to cluster d32407294ef780c

**Comment by xiang90** [comment]
From the log, we can see the advertise peer url is not reachable by the other member. They advertise their local addr rather than public addr. 
```
./etcdctl member list
145f81b1e050b7c7: name=monitorserver2 peerURLs=http://127.0.0.1:2380 clientURLs=http://localhost:2379,http://localhost:4001
3260c3386e0bf9d8: name=monitorserver1 peerURLs=http://127.0.0.1:7001 clientURLs=http://localhost:2379,http://localhost:4001
```

You have to remove the data-dir and use the correct configuration to bootstrap the cluster again.
The configuration in the first post is almost correct, except the naming issue.

**Comment by dreameryan** [comment]
it works. Thanks for your great help
