### ISSUE TITLE
update on unhealthly cluster

### ISSUE THREAD

**Issue by grzechum** [coreos/etcd#2653]
When I performed key value update on the  unhealthy cluster (2 of 3 nodes down) I've got.
```json
{"message": "Internal Server Error"}
```
Which is expected, 
but then after adding back one node to the cluster - previously failed updates are hiddenly applied (values changed index moved)

Is this expected behaviour?

**Comment by xiang90** [comment]
`Internal Server Error` does not imply the proposal you sent must be failed. etcd is trying its best to get it committed.

**Comment by grzechum** [comment]
Is there any flag (e.g. consistent=true) to control this behaviour?
e.g. consistent=true + fail -> means failed (no quorum) and forgotten (no auto retry)

This will simplify error handling scenarios.

**Comment by durzo** [comment]
This error is certainly misleading, I was under the impression it meant the value was not updated. Is it possible to change the error to reflect that it was committed but not updated until cluster health is restored?

**Comment by xiang90** [comment]
@grzechum No. etcd cannot give you any guarantee at the moment. 

If it is a follower (or even a leader), it might send out the proposal. It cannot know if the proposal will succeed or not until it gets the ack from leader (or get the ack from other followers). Any error happened during the process is `Server Internal Error` right now. We can improve the error message.

To support a stronger guarantee require significant amount of work. It is not a very simple problem.

**Comment by xiang90** [comment]
@durzo It might be committed or might not be. We can improve the error message.
