### ISSUE TITLE
Error adding 2nd machine to the cluster

### ISSUE THREAD

**Issue by mikea** [coreos/etcd#2655]
I'm trying to add second machine to /etcd cluster and I see lots of heartbeat timeouts and http headers timeouts even though machines can reach each another.

This gist: https://gist.github.com/mikea/3eebacc56d4737545c98
Has information from leader & follower. Let me know if you need more info.

**Comment by yichengq** [comment]
It may be the first bootstrap failure for some strange reason. Could you remove all data dirs and reproduce it?

**Comment by mikea** [comment]
This was with clean dir. I was able to reproduce it several times with same results on clean dir.

**Comment by yichengq** [comment]
@mikea It is a bug in some version. Could you try etcd 0.4.9?

**Comment by xiang90** [comment]
@mikea I am going to close this due to low activity. Also I suggest you to try etcd2 if possible. :) Thank you for reporting!
