### ISSUE TITLE
etcd introduce significant throughput overhead(more than 10X) comparing to raw raft

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2656]
Test env: ec2 large machine
Proposal: etcd command ("/foo"="bar"); apply latency (10us)

raft 1 node perf with disk io `84966 ops/second`
raft 3 node perf with disk io `83127 ops/second`.

I did some **VERY SIMPLE PROFILING**, The bottleneck of raft seems to be CPU. A lot of marshaling and syscall.Write (not sync). The number of nodes does not matter a lot since our raft can do smart batching. The latency is much higher though. These are expected. 

However, the best number I can get out of etcd with same command is around `10000 ops/second` for one member cluster and `5000 ops/second` for a three member cluster.

etcd introduces more than 10X throughput overhead than raw raft.

**Comment by AdoHe** [comment]
@xiang90 awesome :+1:

**Comment by nrshrivatsan** [comment]
@xiang90 and @AdoHe  Load scripts

1. [Go](https://gist.github.com/nrshrivatsan/8c997511b5d337f9d929) 
1. [node](https://gist.github.com/nrshrivatsan/35d5ca1342981ee6e593)

Can you provide suggestions/feedback?

Appreciate your time.

**Comment by xiang90** [comment]
We now can achieve 30K request per second. Not a huge issue any more.
