### ISSUE TITLE
huge memory usage overhead (20X than real data)

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2657]
I wrote a simple script that keeps on putting key-value pairs into a one member etcd cluster.

The key is 8 bytes and the value is 128 bytes.

After I put 200k key-value into etcd, etcd uses more than 600MB RES. The total value is only around 30MB. 

The write overhead is around 20X.

**Comment by AdoHe** [comment]
@xiang90 ever think about the log size?

**Comment by xiang90** [comment]
@AdoHe The log is compacted periodically. The max in memory of log is around 10000*(128bytes + some small overhead).

**Comment by xiang90** [comment]
I did an additional test for 3 member cluster. The memory overhead is higher than 600MB on the leader.

**Comment by dchen1107** [comment]
cc/ @bgrant0605 @davidopp

**Comment by bgrant0607** [comment]
cc @hchoudh

**Comment by eaoliver** [comment]
I'm seeing ridiculous memory usage on the 4th node of a fresh 3-node cluster.  Memory usage is approximately 800MB.  The only command run on the 4th node is 'etcdctl member list', which failed.  The other 3 nodes are healthy.

**Comment by davidopp** [comment]
@fgrzadkowski @wojtek-t  FYI

**Comment by philips** [comment]
We are designing changes to future versions of etcd to address this.  You can read the plan here: https://groups.google.com/forum/#!searchin/etcd-dev/store/etcd-dev/ATZm7sRJy60/aqeQcrIB7NcJ

If you are interested in taking a look or helping out the packages that are implementing this new storage backend are here:

- http://godoc.org/github.com/coreos/etcd/storage
- http://godoc.org/github.com/coreos/etcd/storage/backend

**Comment by jonboulle** [comment]
V3 store/API should resolve this but is pending benchmarks to be sure.

**Comment by xiang90** [comment]
We have a benchmark here https://github.com/coreos/etcd/blob/master/Documentation/benchmarks/etcd-storage-memory-benchmark.md. 

The hard memory requirement is significantly reduced. But we still only support near in memory workload for v3. But the memory usage factor is almost down to 2 from 20 if the key-value is larger than 256bytes, which is most of the cases.

**Comment by derekwaynecarr** [comment]
@xiang90 - awesome!

**Comment by wojtek-t** [comment]
+1 - awesome!
