### ISSUE TITLE
the memory usage per watch is high

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2658]
I create N watchers watching on N different key spaces. 
The memory usage per watcher is around 45KB, which is pretty high.

I hope this should be O(1)KB if not bytes.

**Comment by xiang90** [comment]
Add more details, we should be able to watch more keys (so more watcher) per connection. For each connection, we need to allocate a go-routine and user space/kernel space fd/buffer. O(10)kb memory for each connection is fine.

**Comment by xiang90** [comment]
For v3, the average memory consumption per watch is reduced to less than 1kb when you have O(1k) clients with O(100) watchers per client.

**Comment by jonboulle** [comment]
Woo-hoo!
