### ISSUE TITLE
use quorum=true & recursive=true at the same time

### ISSUE THREAD

**Issue by pacasrc** [coreos/etcd#2674]
The output of the following two commands should be the same:

cy3411> curl http://127.0.0.1:2379/v2/keys/dir?quorum=true&recursive=true
{"action":"get","node":{"key":"/dir","dir":true,"nodes":[{"key":"/dir/file1","value":"file1","modifiedIndex":122,"createdIndex":122},{"key":"/dir/dir1","dir":true,"modifiedIndex":123,"createdIndex":123}],"modifiedIndex":122,"createdIndex":122}}
 
cy3411> curl http://127.0.0.1:2379/v2/keys/dir?recursive=true&quorum=true
{"action":"get","node":{"key":"/dir","dir":true,"nodes":[{"key":"/dir/file1","value":"file1","modifiedIndex":122,"createdIndex":122},{"key":"/dir/dir1","dir":true,"nodes":[{"key":"/dir/dir1/file2","value":"file2","modifiedIndex":123,"createdIndex":123}],"modifiedIndex":123,"createdIndex":123}],"modifiedIndex":122,"createdIndex":122}}

**Comment by xiang90** [comment]
@pacasrc Ah... I think you need to escape the `&`

So please try `http://127.0.0.1:2379/v2/keys/dir?quorum=true\&recursive=true`
