### ISSUE TITLE
etcd should support filtering for watches

### ISSUE THREAD

**Issue by aledbf** [coreos/etcd#2679]
Currently is not possible to filter certain keys (using a TTL for instance) inside a watch. 
If `confd` is used without this feature with a template that read such keys the traffic between `confd` and `etcd` is huge and it starts to throw template errors.

I could be possible to not send TTL updates to watchers or at least be able to filter such updates?
Thanks

**Comment by xiang90** [comment]
@aledbf TTL updates has no different between normal value updates. The client can filter it out by comparing the changes in the event (prevValue, Value, prevTTL and TTL). 

We can do this at server side to reduce the traffic between server and client.

But can I know how many TTL keys are you watching at? And how many watcher are you thinking there will be?

**Comment by aledbf** [comment]
@xiang90 here is some context to my problem:

This is part of the upgrade to confd in deis. In particular this part https://github.com/deis/deis/pull/3415 (which I'm working on)
```
confd 0.6  (deis v1.4.1) http://asciinema.org/a/18710    -interval 5
confd 0.80 (deis v1.5.0) http://asciinema.org/a/18709    -watch
confd 0.90 (deis master) https://asciinema.org/a/18711   -watch -prefix /deis
```

the amount of traffic between confd and etcd makes no sense. 
This videos are from a new cluster (3 nodes using 607.0.0 in vagrant)

*note:* some directories (like /deis/services) uses a 10 sec ttl per key
This is the output using confd with -watch -prefix /deis https://gist.github.com/aledbf/331aa794dbed3cbca0b3

**Comment by aledbf** [comment]
ping @kelseyhightower

**Comment by xiang90** [comment]
@aledbf 
I do not quite follow your three videos. 
Do you mean that there was no problem before and there is a problem when you upgraded confd? 
the old version of cond/etcd does not filter watch as far as I can tell.

**Comment by xiang90** [comment]
@aledbf Oh... I see, so when you upgraded confd you also changed the flags you are using from 
`-interval 5` to `watch` to `watch with prefix`?

Does 5 second interval polling work well for you?

**Comment by aledbf** [comment]
@xiang90 yes the interval flag works just fine. The idea to upgrade confd and use watch was to remove the "delay" of 5 seconds. Without prefix there's too much traffic between confd and etcd (and is not related with the content of the templates) and with a specific prefix "works" but with some template errors (missing keys).

The request for the filter is because in keys that I need to watch only changes the TTL, not the value, so if I could just see the changes in the values the traffic would be considerably less

**Comment by aledbf** [comment]
@xiang90 please tell me what I can do to show you more clearly this scenario.
Thanks

**Comment by carmstrong** [comment]
Any updates on this? We'd really like to use confd watch to template etcd values, but cannot because of the volume of traffic when TTLs change.

**Comment by carmstrong** [comment]
ping @xiang90 @barakmich Please let us know how we can help push this along.

**Comment by xiang90** [comment]
@carmstrong Please see #952

**Comment by xiang90** [comment]
This duplicates with #952. I am closing this and we should continue the discussion there.
