### ISSUE TITLE
prevIndex is ignored if prevExist is specified

### ISSUE THREAD

**Issue by durzo** [coreos/etcd#2684]
etcd ignores prevIndex when prevExist is also specified in a set request.

$ curl -X PUT http://10.43.116.242:4001/v2/keys/test -d value=1
{"action":"set","node":{"key":"/test","value":"1","modifiedIndex":115601,"createdIndex":115601},"prevNode":{"key":"/test","value":"3","modifiedIndex":115600,"createdIndex":115599}}

$ curl -X PUT http://10.43.116.242:4001/v2/keys/test -d value=2
{"action":"set","node":{"key":"/test","value":"2","modifiedIndex":115602,"createdIndex":115602},"prevNode":{"key":"/test","value":"1","modifiedIndex":115601,"createdIndex":115601}}

$ curl -X PUT http://10.43.116.242:4001/v2/keys/test -d value=3 -d prevIndex=115601
{"errorCode":101,"message":"Compare failed","cause":"[115601 != 115602]","index":115602}

$ curl -X PUT http://10.43.116.242:4001/v2/keys/test -d value=3 -d prevIndex=115601 -d prevExist=true
{"action":"update","node":{"key":"/test","value":"3","modifiedIndex":115603,"createdIndex":115602},"prevNode":{"key":"/test","value":"2","modifiedIndex":115602,"createdIndex":115602}}

**Comment by durzo** [comment]
the same thing happens when supplying prevValue and prevExists

$ curl -X PUT http://10.43.116.242:4001/v2/keys/test -d value=1
{"action":"set","node":{"key":"/test","value":"1","modifiedIndex":115610,"createdIndex":115610},"prevNode":{"key":"/test","value":"3","modifiedIndex":115609,"createdIndex":115605}}

$ curl -X PUT http://10.43.116.242:4001/v2/keys/test -d value=3 -d prevValue=9000 -d prevExist=true
{"action":"update","node":{"key":"/test","value":"3","modifiedIndex":115611,"createdIndex":115610},"prevNode":{"key":"/test","value":"1","modifiedIndex":115610,"createdIndex":115610}}
{"key":"/test","value":"3","modifiedIndex":115607,"createdIndex":115605}}

**Comment by AdoHe** [comment]
@durzo in etcd 0.4.6 there is no such problem, which version are you using?

**Comment by AdoHe** [comment]
@durzo this should be an issue within etcd 2.*

**Comment by durzo** [comment]
sorry, v2.0.5 and v2.0.8

**Comment by xiang90** [comment]
@durzo Thanks for reporting. I can confirm this is a bug. I will fix it tomorrow.

**Comment by AdoHe** [comment]
@durzo @xiang90 I think the cause is that when prevExist is specified, etcd will do update operation instead of compare and swap operation

**Comment by xiang90** [comment]
@AdoHe You are right. I have a quick fix here: https://github.com/coreos/etcd/pull/2685. I will make it work soon.

**Comment by AdoHe** [comment]
@xiang90 it should work :+1:

**Comment by xiang90** [comment]
Fix via #2685

**Comment by durzo** [comment]
Thanks @xiang90

**Comment by xiang90** [comment]
@durzo Thank you for reporting and extensive explanation.
