### ISSUE TITLE
etcdserver: support v2/migration/snapshot

### ISSUE THREAD

**Issue by philips** [coreos/etcd#2691]
etcd v0.4.9 added the `/v2/migration/snapshot` endpoint, we should support the same API in etcd v2.0. This brings v2.0+ plus in parity with the v0.4.9 API.

**Comment by xiang90** [comment]
@philips I am not quite sure about this yet. The primary goal of adding this on to 0.4.9 is just for migration. 

Point-in-time snapshot is a nice thing to have for sure. But it actually costs a lot under v2 store. Moreover the snapshot format of v2 is different. 

So it does not work with etcdctl import command (in the command we explicitly say it requires valid 0.4.x snapshot). 

If there is a good use case of getting point-in-time snapshot from a running machine over the network, we can consider to add it into 2.0.x.

**Comment by xiang90** [comment]
@philips We are not going to add this for etcd v2 store. But etcd v3 will support this. 

Close in favor of https://github.com/coreos/etcd/issues/4095
