### ISSUE TITLE
etcd watch command gets nil etcd.Response

### ISSUE THREAD

**Issue by amyangfei** [coreos/etcd#2693]
We first start a standalone etcd server bind at 127.0.0.1:4001 and then run a watch command with <code>etcdctl</code> tool like

    etcdctl watch --forever --recursive /update/t

then we run a benchmark file to update keys like /update/t/xxxxx with 20 concurrent clients and each client updates keys with frequency of 0.01(100 time per second), the benchmark file is here [notify.go](https://github.com/amyangfei/daily_work/blob/344810e8a2b0a2e9ee5262a5275d794e36d07f69/etcd_notify_test/notify.go), for example we run it with command:
    
    go run notify.go -t=60 -r=0.01 -n=20

somtimes the <code>etcdctl</code> may exit with error:

    Error:  401: The event in requested index is outdated and cleared (the requested history has been cleared [499204/499201]) [500203]

and sometimes panic happens like following: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x45821f]

goroutine 1 [running]:
github.com/coreos/etcd/etcdctl/command.printAll(0x0, 0xc2080b1ef0, 0x6)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:130 +0x1f
github.com/coreos/etcd/etcdctl/command.watchCommandFunc(0xc208078580, 0xc208090000, 0x5, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/watch_command.go:77 +0x7b5
github.com/coreos/etcd/etcdctl/command.rawhandle(0xc208078580, 0x8af400, 0x4, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:72 +0x58a
github.com/coreos/etcd/etcdctl/command.handlePrint(0xc208078580, 0x8af400, 0x8af3b8)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:78 +0x32
github.com/coreos/etcd/etcdctl/command.handleKey(0xc208078580, 0x8af400)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/handle.go:111 +0x3e
github.com/coreos/etcd/etcdctl/command.func·013(0xc208078580)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/command/watch_command.go:37 +0x34
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x7fcac0, 0x5, 0x0, 0x0, 0x83acb0, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:101 +0
xe42
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc20806c000, 0xc20800a000, 0x5, 0x5, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:125 +0xb70
main.main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdctl/main.go:59 +0xc45
```

I look up the etcdctl source code and find the <code>etcdctl</code> received a nil Response from receiver channel, file here: [watch_command.go](https://github.com/coreos/etcd/blob/f1ed69e8838548e7226250555598a97fd9f9bc52/etcdctl/command/watch_command.go#L76)

Besides if we run the [moitor.go](https://github.com/amyangfei/daily_work/blob/344810e8a2b0a2e9ee5262a5275d794e36d07f69/etcd_notify_test/monitor.go), which uses the watch interface provided by <code>go-etcd</code>, we will get endless nil etcd.Response from receiver channel.

**Comment by xiang90** [comment]
@amyangfei The error is expected, since etcd only keeps a limited window size. We will look into the panic.

**Comment by xiang90** [comment]
@amyangfei This has been fixed in dev2.2 branch. Can you please give it a try? Thanks!
