### ISSUE TITLE
Always getting same cluster ID when I run single-node cluster

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#2699]
Using etcd-v2.0.9-linux-amd64, I did the following:
```
$ ./etcd
...
2015/04/16 11:46:12 etcdserver: published {Name:default ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster 7e27652122e8b2ae
...
[Ctrl-C]
$ rm -rf default.etcd
$ ./etcd
...
2015/04/16 11:48:14 etcdserver: published {Name:default ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster 7e27652122e8b2ae
...
```

I blew away the data dir but the cluster ID ended up being created the same; it always seems to be 7e27652122e8b2ae on my host.  I was expecting a new ID each time.

I want a new ID so that I can spot from the client side if the cluster has been replaced.  Also, I thought it was part of etcd's consistency model to use a new ID each time.

**Comment by yichengq** [comment]
You should set random --initial-token each time you bootstrap a etcd cluster:
https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-initial-cluster-token

It can help to generate different cluster ID for safety check.

**Comment by fasaxc** [comment]
Can't random be the default?  This caught me out and I bet it will catch others out too.  (Plus, generating good random values is hard so it's probably better to do it once correctly inside etcd.)

**Comment by xiang90** [comment]
@fasaxc 
> Can't random be the default?

It cannot. That random must be shared with other members in the cluster. It has to be user-defined when possible.
We do not want to do something special for one member case, which is not our main use case.
