### ISSUE TITLE
etcd on reboot fails

### ISSUE THREAD

**Issue by ksaritek** [coreos/etcd#2702]
When reboot 3 coreos cluster, etcd failed

Apr 17 15:16:21 coreos3 etcd[889]: [etcd] Apr 17 15:16:21.183 WARNING   | [vote] Error: nil response
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 INFO      | node003: state changed from 'stopped' to 'stopped'.
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 INFO      | node003: state changed from 'follower' to 'stopped'.
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 INFO      | node003: term #18446744073709551615 started.
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 INFO      | node003: state changed from 'candidate' to 'follower'.
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.768 INFO      | removed during cluster re-configuration
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.767 INFO      | node003: state changed from 'follower' to 'candidate'.
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.498 INFO      | node003: state changed from 'initialized' to 'follower'.
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.498 INFO      | node003 starting in peer mode
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.498 INFO      | peer server [name node003, listen on :7001, advertised url http://10.19.1.3:7001]
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.497 INFO      | etcd server [name node003, listen on :4001, advertised url http://10.19.1.3:4001]
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.495 WARNING   | node003 cannot connect to previous cluster [10.19.1.2:7001 127.0.0.1:7001 10.19.1.1:7001 10.19.1.1:7001 10.19.1.2:7001]: fail joining the cluster via given peers af
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.495 INFO      | node003 attempted to join via 10.19.1.2:7001 failed: fail on join request: Raft Internal Error ()
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.486 INFO      | Send Join Request to http://10.19.1.2:7001/join
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.484 INFO      | node003 attempted to join via 10.19.1.1:7001 failed: fail checking join version: Client Internal Error (strconv.ParseInt: parsing "404 page not found\n": invalid sy
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.484 INFO      | node003 attempted to join via 10.19.1.1:7001 failed: fail checking join version: Client Internal Error (strconv.ParseInt: parsing "404 page not found\n": invalid sy
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.483 INFO      | node003 attempted to join via 127.0.0.1:7001 failed: fail checking join version: Client Internal Error (Get http://127.0.0.1:7001/version: dial tcp 127.0.0.1:7001:
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.482 INFO      | node003 attempted to join via 10.19.1.2:7001 failed: fail on join request: Raft Internal Error ()
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.481 INFO      | Send Join Request to http://10.19.1.2:7001/join
Apr 16 08:31:30 coreos3 etcd[889]: [etcd] Apr 16 08:31:30.479 INFO      | Discovery fetched back peer list: [10.19.1.1:7001 10.19.1.2:7001]

**Comment by yichengq** [comment]
The cluster is in a strange status now, and I cannot tell what is wrong without full logs and cluster info.

Moreover, we are not going to fix bugs in 0.4.x, since we have moved to development and maintainence of 2.0. Maybe you could give it a try. It is also in latest CoreOS image. (https://coreos.com/blog/coreos-alpha-with-etcd-2/)

**Comment by ksaritek** [comment]
Seems that fix it,  just set up a single cluster, when actual size parameter given for etcd as 1, no problem occures then.
