### ISSUE TITLE
Not able to run etcd on Amazon EC2

### ISSUE THREAD

**Issue by pdhar-tibco** [coreos/etcd#2703]
In continuation of my earlier issue #3489 trying to install DEIS on vmware fusion single node . As advised I am now trying to install DEIS on Amazon EC2 (3 nodes) and I have completed the provisioning step. I did the following steps as mention in the readme.
1. export DEISCTL_TUNNEL=52.11.XXX.XXX (masked my public ip of the ec2 node)
2. deisctl config platform set sshPrivateKey=~/.ssh/deis.pem (from laptop ssh console)
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
3. systemctl status etc -> (ec2 instance)
systemctl status etcd
● etcd.service - etcd -> (ec2 instance)
   Loaded: loaded (/etc/systemd/system/etcd.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd.service.d
           └─10-oem.conf, 20-cloudinit.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2015-04-17 18:12:06 UTC; 2s ago
  Process: 30752 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 30752 (code=exited, status=1/FAILURE)
4.journalctl -u etcd -> ( discovery url was created fresh with DEIS_NUM_INSTANCES=3 as generated to user-data file ) (ec2 instance)
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.356 INFO      | Discovery via https://discovery.etcd.io using prefix /f4741ddaec75b183930c9c6ac38e3177.
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.758 WARNING   | Discovery encountered an error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.758 WARNING   | c21ab1d7393b4b3bbb52f55766f3f651 failed to connect discovery service[https://discovery.etcd.io/f4741ddaec75b183930c9c6ac38e3177]: 501: All the given peers are n
Apr 17 04:50:40 corevm etcd[859]: [etcd] Apr 17 04:50:40.758 CRITICAL  | c21ab1d7393b4b3bbb52f55766f3f651, the new instance, must register itself to discovery service as required
Apr 17 04:50:40 corevm systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Apr 17 04:50:40 corevm systemd[1]: Unit etcd.service entered failed state.
Apr 17 04:50:40 corevm systemd[1]: etcd.service failed.
5. etcd.service file looks like this (not sure if the ETCD_NAME should be there , automatically generated by the provisioning script)
Environment="ETCD_ADDR=172.31.40.165:4001"
Environment="ETCD_DATA_DIR=/media/ephemeral/etcd"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/f4741ddaec75b183930c9c6ac38e3177"
Environment="ETCD_PEER_ADDR=172.31.40.165:7001"
Environment="ETCD_PEER_ELECTION_TIMEOUT=2000"
Environment="ETCD_PEER_HEARTBEAT_INTERVAL=500"
6. etcd version = etcd version 0.4.7
7. network security rules are
Type   Protocol    Port Range    Source
Custom TCP Rule TCP 2222 sg-97bab8f2 (DeisCluster-DeisWebELBSecurityGroup-19LO9VQJGKGWS)
SSH     TCP     22  0.0.0.0/0
Custom TCP Rule  TCP  4001  0.0.0.0/0
All traffic  All  All    sg-99bab8fc (DeisCluster-VPCSecurityGroup-1GACN6BJIGFS3) (same subnet_
HTTPS  TCP  443  sg-97bab8f2 (DeisCluster-DeisWebELBSecurityGroup-19LO9VQJGKGWS)
Custom TCP Rule  TCP  7001  0.0.0.0/0
HTTP  TCP  80  sg-97bab8f2 (DeisCluster-DeisWebELBSecurityGroup-19LO9VQJGKGWS)

I don't know at this point if I am missing something critical or there is an issue with etcd.

**Comment by yichengq** [comment]
@pdhar-tibco Any more details on why you close it?

**Comment by pdhar-tibco** [comment]
I realized it might be related to DEIS setup procedures. I am trying the steps again to see if it happens again and will reopen if it persists.

-Pranab

**Comment by pdhar-tibco** [comment]
I tried again with the same results.

**Comment by yichengq** [comment]
@pdhar-tibco It is good to report this to DEIS guys because it is so DEIS related.
