### ISSUE TITLE
use coreos/pkg/log

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2707]
we want to use coreos/pkg/log to provide leveled log.

**Comment by xiang90** [comment]
@barakmich @yichengq Let us try to finish this in 2.1 as discussed.

I will start with wal and raft pkg. @barakmich will also start to work on other pkg.
Yicheng can probably work on rafthttp pkg.

**Comment by yichengq** [comment]
https://github.com/coreos/etcd/issues/2398#issuecomment-97135480
> I would like to see this include HTTP client request logs so I can debug simple things like is etcd seeing a request from my client. Essentially dump the path, verb and client IP.

**Comment by yichengq** [comment]
Based on discussion OOL, here is some points about log level:
1. if it indicates an internal bug, etcd should panic
2. if it must be hardware error/user misconfiguration/user misoperation, etcd should error.
e.g. network error, disk error, running etcd of different cluster together
3. if it is possible hardware error/user misopeartion/misconfiguration, etcd should warning
e.g. connection from previously removed member(one case is that removed member is not stopped immediately, the other one is that the removed member is restarted by mistake)
4. if it's expected but significant change, notice should be used
e.g. add/removed a member, enable security, etc
5. if it's normal but noteable to the user, it's worth an info level
e.g. automatic snapshot
6. if user is not the cause of it, and user can do nothing for it, it is debug message.
