### ISSUE TITLE
expose version on peer url for rolling upgrades

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2714]
etcd servers should only accept a command/API supported by all members of the cluster. Or the command will be replicated to a server that does not understand it and cause a potential panic or inconsistency.

so we want etcd cluster to agree on one single operating version.

TODO:

1. add version endpoint at peer url. currently we only expose version endpoint at client url.

2. all the servers periodically check the versions of other servers.

3. etcdserver exposes a `clusterVer` Interface for the API pkg. `clusterVer` is the min version of all servers in the cluster. Before accepting a request, the server checks the `clusterVer` to decide if it can accept the request or not. `clusterVer` will be initialized as the min version of the current binary supports. 

For example, if `clusterVer` is 2.0, a 2.1 etcd server should reject /v2/security request. A 2.1 etcdserver should reject /v2/security by default (initial `clusterVer` is 2.0) until it knows everyone is 2.1. 

We might want to have a `maxVer`, which might be useful when we want to deprecate an API.
We might also want to expose raft version for raft state machine upgrade.

**Comment by bakins** [comment]
If sever has > minVer it should probably remove itself and "complain loudly" - error log, return errors to API calls, etc.

**Comment by xiang90** [comment]
@bakins Hrm... I do not quite follow.

**Comment by xiang90** [comment]
@bakins Right. Now I understand it. Yes, besides the version coordination, we need to enforce the version too: new member with < minVer dies, existing member restarting with a old version binary dies, etc..

**Comment by xiang90** [comment]
related to https://github.com/coreos/etcd/issues/2716

**Comment by xiang90** [comment]
@barakmich Can you take a look at the proposal?

**Comment by philips** [comment]
It is probably much easier if we make the version a monotonically increasing number instead of an actual version.

**Comment by xiang90** [comment]
@philips I am using go-semver. So it is fine actually. 

I am not sure if we need to start versioning our sub component, like API and raft. 
For example, current v2 API is v2.0 and v2 API with security is v2.1. Personally, I think it is overkilled for etcd. etcd is pretty tight coupled. So I think a single binary version is good enough for most the use cases.

**Comment by bakins** [comment]
A single version is probably fine.  No strong feelings on single number version vs semver except if we do semver, have to be careful which part of version we bump and compatibility, etc.

**Comment by xiang90** [comment]
@bakins Yea... We already use semver for etcd. I am not quite sure if we want to map semver to a number version just for easy comparison. (it does make our life a lot easier when compare 3.0 to 2.x, since 2.x has to know 3.0 is its next version).

**Comment by xiang90** [comment]
closed via https://github.com/coreos/etcd/pull/2718
