### ISSUE TITLE
versioning enforcement

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2716]
### bootstrap time enforcement

1. new member checks the current cluster version. dies if version is too high or low. if we cannot determine the version since some member is offline, we will rely on runtime enforcement. [done]

2. existing member checks with wal when restarts. dies if version is lower than previous.

### run time enforcement [done]

attach x-version in all the server-to-server http headers (raft-http probably?).  
only talk to current+-1 version(we can define this too. max-version, min-version). higher version binary ignores too low version request. smaller version should dies and log if there is a request from a too high version? /cc @bakins @philips

**Comment by xiang90** [comment]
@barakmich What is you opinion?

**Comment by philips** [comment]
I don't understand the bootstrap case. Why do we have to check with everyone? Aren't we going to be regularly receiving candidate RPCs when we come up for bootstrap?

**Comment by xiang90** [comment]
@philips See https://github.com/coreos/etcd/pull/2830. This solves bootstrap 1.

**Comment by xiang90** [comment]
moved this to 2.2. the left thing is not a blocker for 2.1 release.
