### ISSUE TITLE
Lacking documentation on how clients not participating in the etcd cluster are supposed to connect to an existing cluster

### ISSUE THREAD

**Issue by hookenz** [coreos/etcd#2719]
I can't find any documentation on how to connect to an existing cluster except using the proxy which requires me to run etcd2 in a docker container.  Even that documentation is rather sketchy.

What if I don't want to do that?  I simply want to use etcd 0.48 in the current stable release. 
I can start a 5 machine cluster.  But now how do I reference that cluster from other machines who are not running etcd locally?

For example I need to:
1) make the machine become part of fleet, without being an active member of the etcd cluster.
2) Have app's be able to find the cluster.  e.g. etcdctl can't connect to 127.0.0.1:4001... is there a way to do this?  How should apps running in the container connect to the cluster?

Real world documentation is sorely lacking.

**Comment by hookenz** [comment]
After a lot of searching and stumbling around, I have found some answers.  It would be great if documentation could be updated to reflect this.  It's not easy to find.  I stumbled upon examples and had to ask questions in various places.

Firstly, the etcd cluster.  Applies to pre version 2 etcd.

Suppose we have 3 servers we want in a cluster and don't want to use the discovery URL.  
The key is to add a peers section in cloud init to all the nodes participating in the cluster except one. 

e.g.
node1: 10.1.1.1
node2: 10.1.1.2
node3: 10.1.1.3

Node1 Cloud Init:

    coreos:
      etcd:
        addr: 10.1.1.1:4001
        peer-addr: 10.1.1.1:7001
      units:
        - name: etcd.service
          command: start
        - name: fleet.service
          command: start

Node2:

    coreos:
      etcd:
        addr: 10.1.1.2:4001
        peer-addr: 10.1.1.2:7001
        peers: 10.1.1.1:7001,10.1.1.2:7001:10.1.1.3:7001
      units:
        - name: etcd.service
          command: start
        - name: fleet.service
          command: start

Node3:

    coreos:
      etcd:
        addr: 10.1.1.3:4001
        peer-addr: 10.1.1.3:7001
        peers: 10.1.1.1:7001,10.1.1.2:7001:10.1.1.3:7001
      units:
        - name: etcd.service
          command: start
        - name: fleet.service
          command: start

What is not clear is if you should list yourself as a peer in the peers list or miss it off (i.e. where peer-addr value is also part of peers list).  Maybe someone in the know can comment on that?

Also not clear is what the difference between the two ports are.  Why is 7001

For fleet, machines can join the fleet cluster without running etcd with:
e.g.

    coreos:
      fleet:
        public-ip: 10.1.1.10
        etcd_servers: http://10.1.1.1:4001,http://10.1.1.2:4001,http://10.1.1.3:4001
      units:
        - name: fleet.service
          command: start

Do not add -name: etcd.service, command: start.  Which I've seen in many examples.  That will end up creating an isolated single server cluster running on the node.  If you end up connecting to it, you'll be wondering why things you've written to it are not appearing. 

As for etcdctl, the recommended method which unfortunately is pretty complex is here:
https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services  
It's a pity that there is no /etc/etcdctl.conf or similar with a peers setting.  Hopefully that's improvied in etcd2.

**Comment by yichengq** [comment]
https://coreos.com/docs/cluster-management/setup/cluster-architectures/#production-cluster-with-central-services is the recommended way to run etcd in a big cluster. We will definitely help to make etcdctl easy to use in this case.

4001 and 7001 are random ports used in etcd 0.4, and we are moving to 2379 and 2380 in etcd 2.0, which are IANA ports for etcd service.

For proxy stuff, it is still under exploration. One usage is to set 10 proxy in a 1000-machine cluster, and reduce the burden of etcd cluster by caching and watch coalescing. Another usage is to proxy requests to above proxy or etcd cluster. Maybe we will split them into two binaries in the future.

Strongly recommend running etcd2 instead of etcd0.4. etcd2 is more stable and under full maintainence now.

**Comment by hookenz** [comment]
Thanks @yichengq .  I would run etcd2 in docker, and did once stumble upon a link to some documentation on how to run it in docker.  However, I can't find this page anymore.  Would you know where I can find that information?

**Comment by yichengq** [comment]
@hookenz This is a docker guide in the repo: https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md

**Comment by xiang90** [comment]
@hookenz I think @yichengq answered all your questions. I am closing this issue. If you still have a concern or follow-up, feel free to reopen this issue.
