### ISSUE TITLE
wait request does not return any message

### ISSUE THREAD

**Issue by lukexue** [coreos/etcd#2723]
curl -v http://127.0.0.1:4001/v2/keys/message

\* Hostname was NOT found in DNS cache
\*   Trying 127.0.0.1...
\* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)

 > GET /v2/keys/message HTTP/1.1
 > User-Agent: curl/7.37.1
 > Host: 127.0.0.1:4001
 > Accept: \*/\*
 > 
 < HTTP/1.1 200 OK
 < Content-Type: application/json
 < X-Etcd-Cluster-Id: e9c7614f68f35fb2
 < X-Etcd-Index: 22
 < X-Raft-Index: 69030
 < X-Raft-Term: 23
 < Date: Wed, 22 Apr 2015 00:11:01 GMT
 < Content-Length: 103
 < 
  {"action":"get","node":{"key":"/message","value":"Hello world3","modifiedIndex":21,"createdIndex":21}}
\* Connection #0 to host 127.0.0.1 left intact
---

 curl -v http://127.0.0.1:4001/v2/keys/message?wait=true&waitIndex=1
 [13] 15288

\* Hostname was NOT found in DNS cache
\*   Trying 127.0.0.1...
\* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
 > GET /v2/keys/message?wait=true HTTP/1.1
 > User-Agent: curl/7.37.1
 > Host: 127.0.0.1:4001
 > Accept: \*/\*
 > 
 < HTTP/1.1 200 OK
 < Content-Type: application/json
 < X-Etcd-Cluster-Id: e9c7614f68f35fb2
 < X-Etcd-Index: 22
 < X-Raft-Index: 69122
 < X-Raft-Term: 23
 < Date: Wed, 22 Apr 2015 00:11:47 GMT
 < Transfer-Encoding: chunked
 < 
 ---
 no other response message
 ---

**Comment by xiang90** [comment]
@lukexue You need to escape `http://127.0.0.1:4001/v2/keys/message?wait=true&waitIndex=1` as 
`http://127.0.0.1:4001/v2/keys/message?wait=true/&waitIndex=1`

**Comment by lukexue** [comment]
curl -v http://127.0.0.1:4001/v2/keys/message?wait=true/&waitIndex=1
[1] 25886
[~]$ * Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4001 (#0)
> GET /v2/keys/message?wait=true/ HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 127.0.0.1:4001
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< X-Etcd-Cluster-Id: e9c7614f68f35fb2
< X-Etcd-Index: 0
< Date: Wed, 22 Apr 2015 04:23:59 GMT
< Content-Length: 91
< 
{"errorCode":209,"message":"Invalid field","cause":"invalid value for \"wait\"","index":0}
* Connection #0 to host 127.0.0.1 left intact

**Comment by xiang90** [comment]
@lukexue  curl -v http://127.0.0.1:4001/v2/keys/message?wait=true\&waitIndex=1. I made a mistake.

**Comment by lukexue** [comment]
thanks
