### ISSUE TITLE
etcd should notify systemd when it's ready to accept requests

### ISSUE THREAD

**Issue by crawford** [coreos/etcd#2724]
If etcd sent a notify signal to systemd via [sd_notify](http://www.freedesktop.org/software/systemd/man/sd_notify.html), then we could make the service a "notify" type. That way people wouldn't need to write various implementations of wait-for-etcd.service.

**Comment by yichengq** [comment]
I don't want etcd to strictly bound on systemd. Could it reach the same goal if etcd provides a http endpoint that says whether it's ready to accept requests?

**Comment by philips** [comment]
@yichengq This isn't making etcd strictly bound to systemd, etcd can detect whether systemd is executing it and make this notification.

**Comment by philips** [comment]
@crawford Now, I am a bit skeptical that this is a good thing as people's clients must wait for etcd anyways because at any point etcd may become unavailable due to network partitions and they will need polling/backoff logic in their clients.

**Comment by crawford** [comment]
@philips I see this being useful for scheduling local services though; during system initialization. Remote services will still need to be resilient to network outages, but local jobs should be able to use systemd primitives.

**Comment by xiang90** [comment]
>  but local jobs should be able to use systemd primitives.

I am not sure if I understand this correctly. In my opinion, the local client also needs to prepare for local etcd unavailability. If there is a network outage, the local etcd would become unavailable too.

Or can you please provide a concrete use case when this is very useful?

**Comment by crawford** [comment]
The system operator should have an accurate picture when looking at what is actually running. Being able to see that etcd is starting (for example, while it's joining a cluster) is nice for performance monitoring and debugging. "Why isn't etcd responding to my requests? Oh, it's still starting. I need to figure out why it hasn't started." Even though clients should be resilient to etcd being down, I don't think it's fair to make all services aware of etcd's quirks in order to accurately gauge its current state.

**Comment by crawford** [comment]
wait-for-etcd.service is a pretty good example as well.
