### ISSUE TITLE
Unable to set  listen-client-urls to all interfaces 0.0.0.0 in proxy mode

### ISSUE THREAD

**Issue by timechanter** [coreos/etcd#2725]
If I set the listen-client-urls to http://0.0.0.0:2379  with proxy on then the Proxy fails to setup due to

proxy: failed to direct request to http://:2379: dial tcp :2379: cannot assign requested address

Once I change it to use a specific ip address it works.

Edit:  Using etcd 2.0.8
Edit: Further testing shows that if I list the same port on multiple ip's it also fails. 
e.g.
listen-client-urls: http://10.0.0.10:2379,http://127.0.0.1:2379,http://10.0.0.10:4000,http://127.0.0.1:4000 

However listen-client-urls: http://10.0.0.10:2379,http://10.0.0.10:4000  works and so does listen-client-urls: http://127.0.0.1:2379,http://127.0.0.1:4000 just not the combined set.

**Comment by timechanter** [comment]
A bit more background. I;m using the coreos 653 version with etcd2 operational. I presently have a 3 member cluster running etcd2 happily. I'm now adding in additional nodes as proxy's into the same cluster and this is failing with the above. Even once I get etcd2 to startup well I rapildly run out of files. netstat shows 26k->40k in seconds and random failures. So something is going crazy on the proxy. For now Ill just switch to all active nodes to move on with my life.

**Comment by timechanter** [comment]
For those who pass in the future. My issue was the initial 3 member cluster had an incorrect variable expansion on the clientURLs which was where http://:2379 was coming from. So the proxy would connect, get a broken set of URLs and then go into a very tight loop wasting FD's (TIME_WAIT). The proxy should probably be a little less aggressive here, or at least detect the bad url's eariler.

**Comment by yichengq** [comment]
@timechanter I think the tight loop on proxy that eats up all fds on etcd server is a big problem. Could you open an issue for it?
