### ISSUE TITLE
auth: Improve test coverage

### ISSUE THREAD

**Issue by barakmich** [coreos/etcd#2740]

**Comment by apsanz** [comment]
On windows, TestMergeUser was failing on the 5th cases due to the ordering of the roles:
    
     !reflect.DeepEqual(User{User: "foo", Roles: []string{"role1", "role2"}}, User{User: "foo", Roles: []string{"role2", "role1"}}

Is this an issue that needs to be fixed for users? Do we need to add an equals function to User? Should we change the slices to a data structure that does not depend on order?

**Comment by barakmich** [comment]
All done in the two PRs
