### ISSUE TITLE
Allow to filter out wait events through the rest api

### ISSUE THREAD

**Issue by tmaret** [coreos/etcd#2747]
Hi, 

I am developing a discovery service based on the version 2.0 of the rest api.
Each instance is represented by a key associated to a ttl which is refreshed periodically.

Detecting discovery changes using "?wait=true" would allow to react fast to topology changes (instance added/removed).
However the amount of requests that each instance issues due to the ttl maintenance is too large to be practical.

Assuming a cluster with 100 instances which refresh their ttl every 10 seconds, it would generate an average overhead load of 1k req/s. The overhead load could be reduced to 0 if we could filter out any events else than child keys being added/removed.

Could the next version of the api allow to specify a fine grained set of event types to watch for ?

Regards, 

Timothee

**Comment by yichengq** [comment]
In v3 API, we introduce lease concept. As long as lease is valid, the keys attached to the lease will be there. When the lease expires or revoked, the keys will be deleted. (https://github.com/coreos/etcd/pull/2675/files#diff-22f48da10db79c87fa69a04d3203af57R36)
I think it can handle your use cases perfectly, right?

**Comment by tmaret** [comment]
@yichengq Thanks for your reply. Currently, I store each instance announce under the key

```
/announces/<uniqueId>
           + value = "{ ... some json identifying the instance associated to the announce ...}"
           + ttl = 10
```

where `<uniqueId>` key is created by etcd atomically and in order (POST req + ttl)
The first announce (ordered by the key name) under `/announces/` is the leader in my topology.

I looked at the Lease proposal and I would need a few details to see if it could fit. My understanding is the following:

before creating a `<uniqueId>` key, I would need to first create a lease using `LeaseCreate`.
The lease would not be stored in the existing structure of key and folders but and I would get a lease id back.
Then, I would need to atomically create a `<uniqueId>` key and associate it to the lease. For this operation, the API proposal seems to provide `LeaseTnx`, however it seems the doc says

```
This is rpc is useful when you want to put a key and attach it to a lease atomically.
``` 

Would that also work with created keys (using POST) ?

If that's the case, then I could apply the lease concept to my existing data structure and periodically extends the lease ttl instead of the `<uniqueId>` key ttl (in fact there would be no ttl on it). 

Furthermore, if there will be no events generated when extending the lease (using `LeaseKeepAlive`), then it would be an efficient way to solve the problem mentionned in this issue.

Are my assumptions regarding the events and ability to atomically create and associate keys to a lease correct ?

Thanks a lot!

**Comment by yichengq** [comment]
> Would that also work with created keys (using POST) ?

Yes. You can use `LeaseAttach` to attach existing keys to the lease. Or you can use LeaseTnx to create key in the lease.
We don't support POST in v3, and instead you can create unique key using transaction.

> I would set a single watch under the key /announces/ which would trigger either when an announce key is removed (because the lease has elapsed, because the instance failed to refresh it) or when the announce is modified (because an instance changed its properties stored under its announce key).

Yes, and you will not receive refresh info anymore. That also helps etcd to have better ttl key scalability.

**Comment by tmaret** [comment]
> We don't support POST in v3, and instead you can create unique key using transaction.

Excellent. I don't see how it could not fit, so I'll close this issue. Thanks!
