### ISSUE TITLE
tooling: membership controllers for API driven environments

### ISSUE THREAD

**Issue by philips** [coreos/etcd#2752]
One of the reasons for building etcd is that we wanted something that could be [runtime reconfigured](https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md) for cloud environments. Our first attempt at that was the standby system of etcd 0.4. This didn't work well as users could not understand the types of assurances and safety this sort of system can give you.

In etcd2 we moved to having an explicit membership addition system which is documented in the [runtime reconfigured](https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md) docs. However, currently this process requires manual intervention on the behalf of the 
## Kubernetes cluster

On a Kubernetes cluster it would be nice to be able to run an etcd cluster and have it continue working even in the face of worker machine failure. In this environment etcd would likely exist on non-persistent disks and would be backed-up in an async manner.

In order to automate this process we would need to have an "etcd-k8s-admin" singleton container that was running in the cluster and was able to talk to both the etcd cluster's administrative API and k8s API. Then it would run a simple reconciliation loop between the members it finds matching the cluster labels in k8s with the members listed in the etcd membership endpoint.
## AWS Autoscale

On AWS I might setup a 5 member etcd cluster and rely on AWS to spin up new machines when old ones die. This would be very similar to the k8s use case.
## Problems in Our Way
1. etcd will exit if the cluster configuration doesn't match, this means in the case of k8s the pod will be rescheduled if executed directly. Ideally etcd would just "hold" until the cluster configuration matches.
2. It is difficult to know if a new machine's etcd is already up and runnning. Perhaps we consider a pending etcd member list. That way we can know the new etcd member is running before making the automated change.

This is just a general discussion of something that we can figure out to provide a nice user interface. For example it would be nice to use this sort of reconciliation loop in a test on top of k8s to test failure and reconfiguration in an automated manner.

**Comment by raoofm** [comment]
:+1:

**Comment by ecnahc515** [comment]
I believe https://github.com/deis/etcd essentially does a lot of this using Kubernetes, an etcd discovery service, and some wrapper programs to manage the life cycle changes.

**Comment by BlueDragonX** [comment]
I began specing out a tool to handle deploying etcd into an AWS autoscaling group with a fixed size. Its primary purpose would be to automate the replacement of failed machines and to allow rolling or incremental upgrades of etcd.

That's a tall order for one dude and was hoping someone else has begun work on this. Any word?

**Comment by tj-corrigan** [comment]
We are currently running etcd in an AWS autoscaling group using https://github.com/MonsantoCo/etcd-aws-cluster/ . Basically it is just a helper script that pulls the other machines' ips from the aws cli. It certainly isn't as full featured as what you are proposing but might be helpful in getting started.

**Comment by radamsfc** [comment]
We pretty much wrote our own because we hit a wall on getting traction that someone might want to rebuild an AWS instance that is a cluster member and we would want it to automatically

1. remove the membership from the cluster when the new instance came online because the IP probably changed
2. join the cluster membership dynamically and sync up the data
3. have a discovery end point that any other node in the system can discover the cluster ips on

Initially we used discovery.etcd.io in a slightly modified form with a wrapper script.  This worked really well except for the discovery.etc.io service expires the discovery endpoints after many weeks/months breaking the "discovery" link.

So now we are having to write our own discovery endpoint either in dynamodb or s3.

**Comment by heyitsanthony** [comment]
Also related: https://github.com/crewjam/etcd-aws

**Comment by bassamtabbara** [comment]
@xiang90 what are you plans for this one? We also would like to use etcd in a similar manner to @radamsfc. 

I read the reasoning for not using a discovery endpoint highlighted here https://github.com/coreos/etcd/blob/master/Documentation/v2/runtime-reconf-design.md#do-not-use-public-discovery-service-for-runtime-reconfiguration. 

We'd hate to be the nth implementation of this logic. It would be great if etcd supported an option for dynamic runtime reconfiguration through a discovery service (and even it's just private).

**Comment by xiang90** [comment]
This issue is finally fixed by a separate project:

https://github.com/coreos/etcd-operator

**Comment by BlueDragonX** [comment]
@xiang90 except that isn't a general solution, runnable anywhere. It's specifically for Kubernetes. So not terribly useful for the general population.

**Comment by raoofm** [comment]
@xiang90 shouoldn't etcd-operator be a wrapper/generic that could be used for kubernetes, aws, etc rather than (as @BlueDragonX says) specific to kubernetes.
