### ISSUE TITLE
Add reference documentation for the API

### ISSUE THREAD

**Issue by jimmycuadra** [coreos/etcd#2760]
The guide-style API documentation is very useful, but is lacking as a specification, for example, when building an API client for etcd. There should be reference documentation that:
- Lists all API endpoints
- Lists all possible input parameters for each endpoint
- Details which input parameters are required and which are optional
- Lists all possible HTTP response codes for each endpoint
- Details the full structure of the response body for each endpoint
- When detailing response bodies, notes which fields are always present, which fields may sometimes be absent, and under what condition they may be absent
- Details the structure and possible values of error response bodies.

**Comment by philips** [comment]
@jimmycuadra Are you interested in helping to do this work? Do you have an example of an API document that you think does this particularly well?

**Comment by jimmycuadra** [comment]
DigitalOcean has pretty good docs along the lines of what I'm describing. For example, their main v2 API docs: https://developers.digitalocean.com/documentation/v2/. An open source API documentation generator that's worth checking out is [Swagger](http://swagger.io/).

I'm going to be building an etcd client for Rust. It's likely I'll come across things that are not well covered by the current docs. I can certainly open issues about things that I find unclear or missing. If you folks decide that you want to do reference-style docs and agree on how to approach it, I could probably help out with that too.

**Comment by jimmycuadra** [comment]
Another possible option is Google's discovery API format: https://developers.google.com/discovery/v1/reference/apis. Fleet uses this, and I used it when building a client for fleet. While fleet didn't have docs generated from the spec, I was able to refer to the raw JSON when fleet's docs didn't have enough information.

**Comment by akauppi** [comment]
Is this still a valid issue, in 2017?

I came here because of thinking to suggest a minor change / simplification to documentation. Current (3.1.0) documents repeat the field name in description, like "ID: ID is the ...". In my opinion, that's unnecessary. I am new to the project and would just like to raise this as an observation.

![screen shot 2017-02-24 at 10 30 53](https://cloud.githubusercontent.com/assets/1297734/23296337/2c5ef074-fa7d-11e6-825d-33aba38b22b8.png)

**Comment by heyitsanthony** [comment]
@akauppi those are [go-doc](https://blog.golang.org/godoc-documenting-go-code) style comments. They're idiomatic.

**Comment by xiang90** [comment]
We already have generated API reference for v3: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md

So closing.

**Comment by jimmycuadra** [comment]
This is still a problem for the v2 API and bit us on the rust client recently: https://github.com/jimmycuadra/rust-etcd/pull/18

**Comment by euank** [comment]
@xiang90 Since etcd3 serves the v2 api (presumably meaning it's supported) and there are still significant users of it, shouldn't this issue remain open?
