### ISSUE TITLE
RPM for installing etcd in Centos 6?

### ISSUE THREAD

**Issue by mcandre** [coreos/etcd#2763]
Where can I find an RPM for installing etcd in Centos 6? I tried ftp://rpmfind.net/linux/fedora/linux/updates/testing/21/x86_64/e/etcd-2.0.9-1.fc21.x86_64.rpm , but it complains that it needs systemd.

**Comment by philips** [comment]
Perhaps @lsm5 could point you in the right direction. He did one of the early check-ins of etcd into Fedora.

Thanks!

**Comment by lsm5** [comment]
@mcandre looks like there's no el6 branch of the fedora rpm yet. @ingvagabund is the one usually handling etcd on Fedora and perhaps you might wanna check with him on the el6 branch, perhaps even help co-maintain it :)

**Comment by philips** [comment]
I am going to close this out since there is nothing the etcd team can do directly and we setup the communication channels here :) Thanks @lsm5 and @ingvagabund.

**Comment by mcandre** [comment]
@ingvagabund Do you have an email address? I'm not sure how to contact you on GitHub.

**Comment by ingvagabund** [comment]
Hi @mcandre, please, create a bug in bugzilla [1] for etcd component and el6 version. Something like "Hey you, what is etcd not in epel6?" :). Thanks.

[1] https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL

**Comment by mcandre** [comment]
@ingvagabund Cheers!

https://bugzilla.redhat.com/show_bug.cgi?id=1217518

**Comment by ahammond** [comment]
This looks like it went over to the redhat bugzilla and died.

**Comment by mcandre** [comment]
I know Docker containers are the way to go these days for enterprise-level etcd installation, but it's still really helpful for medium operations and for newbies, to provide more typical OS packages for traditional tutorials.
