### ISSUE TITLE
slow write performance on v2.0.10

### ISSUE THREAD

**Issue by durzo** [coreos/etcd#2765]
versions:
etcd v2.0.10
python-etcd 0.3.2
ab 2.3

3 member etcd cluster in AWS, each member is in a separate Availability Zone with 0.3ms ping between them. Each member instance class is m3.xlarge - 4 vCPU, 15GB RAM.

Tests performed on an instance that is not a cluster member, running etcd in proxy mode. keys read/written are single key/value (key=foo)

performance using python-etcd (no concurrency):
1000 reads in 1.266191 seconds - 789/sec
100 writes in 21.993278 seconds - 4/sec

Read performance using ab (concurrency: 10)
Concurrency Level:      10
Time taken for tests:   2.207 seconds
Complete requests:      10000
Failed requests:        0
Keep-Alive requests:    10000
Total transferred:      3340000 bytes
HTML transferred:       1020000 bytes
Requests per second:    4530.47 [#/sec] (mean)
Time per request:       2.207 [ms] (mean)
Time per request:       0.221 [ms] (mean, across all concurrent requests)
Transfer rate:          1477.71 [Kbytes/sec] received

Write performance using ab (concurrency: 10)
Concurrency Level:      10
Time taken for tests:   37.561 seconds
Complete requests:      1000
Failed requests:        0
Keep-Alive requests:    1000
Total transferred:      423000 bytes
Total body sent:        174000
HTML transferred:       191000 bytes
Requests per second:    26.62 [#/sec] (mean)
Time per request:       375.611 [ms] (mean)
Time per request:       37.561 [ms] (mean, across all concurrent requests)
Transfer rate:          11.00 [Kbytes/sec] received
                        4.52 kb/s sent
                        15.52 kb/s total

I saw a small increase in write performance when writing directly to a cluster member, bypassing the proxy:
Concurrency Level:      10
Time taken for tests:   23.275 seconds
Complete requests:      1000
Failed requests:        0
Keep-Alive requests:    1000
Total transferred:      423000 bytes
Total body sent:        178000
HTML transferred:       191000 bytes
Requests per second:    42.96 [#/sec] (mean)
Time per request:       232.749 [ms] (mean)
Time per request:       23.275 [ms] (mean, across all concurrent requests)
Transfer rate:          17.75 [Kbytes/sec] received
                        7.47 kb/s sent
                        25.22 kb/s total

Any idea what could be causing the slow writes? They used to be fast on v2.0.5 (thousands/second)

**Comment by yichengq** [comment]
It is related to https://github.com/coreos/etcd/issues/2238 .
We have improved it in current master, and it should be several thousands/second. Give v2.1.0-alpha.0 a try?

I think v2.0.5 cannot have that good performance with 10 clients. I tested it locally and it performed the same as v2.0.10

**Comment by durzo** [comment]
same tests as before with both cluster and local proxy on v2.1.0-alpha.0

python-etcd:
1000 reads in 0.865769 seconds - 1155/sec
100 writes in 2.270518 seconds - 44/sec

ab write test:
Concurrency Level:      10
Time taken for tests:   2.089 seconds
Complete requests:      1000
Failed requests:        999
   (Connect: 0, Receive: 0, Length: 999, Exceptions: 0)
Keep-Alive requests:    1000
Total transferred:      423003 bytes
Total body sent:        174000
HTML transferred:       191003 bytes
Requests per second:    478.77 [#/sec] (mean)
Time per request:       20.887 [ms] (mean)
Time per request:       2.089 [ms] (mean, across all concurrent requests)
Transfer rate:          197.77 [Kbytes/sec] received
                        81.35 kb/s sent
                        279.13 kb/s total



ab read test:
Concurrency Level:      10
Time taken for tests:   2.667 seconds
Complete requests:      10000
Failed requests:        0
Keep-Alive requests:    10000
Total transferred:      3340000 bytes
HTML transferred:       1020000 bytes
Requests per second:    3749.87 [#/sec] (mean)
Time per request:       2.667 [ms] (mean)
Time per request:       0.267 [ms] (mean, across all concurrent requests)
Transfer rate:          1223.10 [Kbytes/sec] received


Huge improvement, but still room for more.

**Comment by yichengq** [comment]
I build a 3-member etcd cluster on n1-highcpu-2, and run a proxy on the 4th member.
I use [boom](https://github.com/rakyll/boom) to do the benchmark testing:
1000 reads: 2000 req/s
100 writes: 600 req/s
10 reads: 1900 req/s
10 writes: 86 req/s

We understand that we do have much space to improve. Do you have any expectation or requirement of the performance?

**Comment by durzo** [comment]
My only expectation of performance was from the docs, specifically this page: https://github.com/coreos/etcd/blob/master/Documentation/benchmarks/etcd-2-1-0-benchmarks.md which shows a write QPS of >1000 in most scenarios

The performance gains in 2.1.0-alpha.0 are enough to handle our application workload, so thats great.

I dont want this to turn into a negative thread, I appreciate all the hard work that has gone into etcd.

Closing this issue :)

**Comment by yichengq** [comment]
@durzo 
Correction: The result i mentioned 40mins ago is got from etcd cluster that run on n1-standard-1 actually.(1vCPU) Sorry for confusion.

The benchmark in doc is measured on operations to etcd member, and each etcd member uses a SSD as backend, which reduces disk time. That are two possibilities that may explain the reduction. We don't do any optimization on proxy today.

We do have long-term plan for performance improvement. The future proxy will cache the result and coalesce requests, so we expect that it will bring up higher throughput.
