### ISSUE TITLE
open too many files error on proxy with one client when proxy forward address is proxy listen address

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2772]
1. start a etcd cluster, and set each member's advertise-client-urls as http://localhost:8080
2. start a etcd proxy, which listens on http://localhost:8080
3. proxy updates its forward address to http://localhost:8080
4. when it proxy requests, it forwards it to itself, form the loop, and finally fail with:
```
06:56:03 proxy | 2015/04/27 06:56:03 http: Accept error: accept tcp 127.0.0.1:8080: too many open files; retrying in 5ms
06:56:03 proxy | 2015/04/27 06:56:03 proxy: failed to direct request to http://127.0.0.1:8080: dial tcp 127.0.0.1:8080: too many open files
06:56:03 proxy | 2015/04/27 06:56:03 proxy: marked endpoint http://127.0.0.1:8080 unavailable
06:56:03 proxy | 2015/04/27 06:56:03 proxy: failed to direct request to http://127.0.0.1:8080: dial tcp 127.0.0.1:8080: too many open files
06:56:03 proxy | 2015/04/27 06:56:03 proxy: marked endpoint http://127.0.0.1:8080 unavailable
06:56:03 proxy | 2015/04/27 06:56:03 proxy: failed to direct request to http://127.0.0.1:8080: dial tcp 127.0.0.1:8080: too many open files
06:56:03 proxy | 2015/04/27 06:56:03 proxy: marked endpoint http://127.0.0.1:8080 unavailable
06:56:03 proxy | 2015/04/27 06:56:03 proxy: unable to get response from 3 endpoint(s)
```

**Comment by yichengq** [comment]
from https://github.com/coreos/etcd/issues/2728#issuecomment-96965684
/cc @bahbka

**Comment by xiang90** [comment]
@yichengq Can we solve this in 2.1?

**Comment by yichengq** [comment]
I don't find any general solution for this issue. Several Go implementations don't solve it, and will meet the same error. apache2 reverse proxy will hang there forever in this case.

i prefer to move to 2.2 to more exploration.

**Comment by xiang90** [comment]
This should be documented at least.

**Comment by sebschrader** [comment]
This should definitely be documented somewhere (e.g. clustering.md or proxy.md). I got hit by this and took me quite a while to figure out what was wrong.

**Comment by xiang90** [comment]
@sebschrader The first step would be documented it. If you have a suggestion, can you send a pull request? The second would be detect a loop (forward a request to a add:port that it is listening on). Any opinion?

**Comment by sebschrader** [comment]
I already deleted my comment, because I realized it is already documented to some extend in [proxy.md](https://github.com/coreos/etcd/blob/1abf2636b54d4d1fa329359362f8b5b08dbcf15a/Documentation/proxy.md):

> The member list used by proxy consists of all client URLs advertised within the cluster, as specified in each members' -advertise-client-urls flag. If this flag is set incorrectly, requests sent to the proxy are forwarded to wrong addresses and then fail. The fix for this problem is to restart etcd member with correct -advertise-client-urls flag. After client URLs list in proxy is recalculated, which happens every 30 seconds, requests will be forwarded correctly.

**Comment by xiang90** [comment]
@sebschrader Do you think we can improve? Probably we can mention it at a more important place?

**Comment by sebschrader** [comment]
@xiang90 I created the pull request #3314

**Comment by xiang90** [comment]
@sebschrader Great! Will review. Thanks!

**Comment by sebschrader** [comment]
May I suggest a possible loop detection mechanism?

A HTTP header could be added to the requests forwarded by the proxy that can be checked by subsequent proxys to find out if they have seen a request before. The contents of this header could contain:
* A hop count (like in IP packets) that starts at a specific value and gets decremented. If the hop count reaches zero an error is returned.
* A list of IDs of the etcd proxy instances that have seen this request before. A proxy checks if its own ID is contained in this list and returns an error in this case.

**Comment by xiang90** [comment]
@yichengq Can we open up an new issue for the loop detection? I do not think that has to be done in 2.2.

**Comment by xiang90** [comment]
I am closing this one in favor of #3317.
