### ISSUE TITLE
etcd cluster unhealthy after restarting a node

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#2779]
[root@tb1-01 ~]# etcd --version
etcd version 2.0.3

3 node cluster, powered off a node.

[root@tb1-01 ~]# etcdctl cluster-health
cluster is healthy
member 40666828cb6d1c07 is unhealthy
member 536674211254cc4 is healthy
member 891add51dc689bd3 is healthy

power up the node, etcd starts on that node
[root@tb1-01 ~]# etcdctl cluster-health
cluster is unhealthy

No details on why the entire cluster is unhealthy

[root@tb1-02 ~]# curl -X GET http://127.0.0.1:4001/health
{"health": "false"}

**Comment by ravigadde** [comment]
I haven't found any way to enable debugs or debug what the problem is.

**Comment by xiang90** [comment]
@ravigadde Can you provide the log info from all three members? Thanks

**Comment by ravigadde** [comment]
@xiang90  Can you please let me know what exactly to collect?

**Comment by xiang90** [comment]
@ravigadde The log from stderr of tb1-02 from the beginning after the reboot. I cannot tell you what exactly you should collect. If I could tell you, I should be able to help you already.

**Comment by ravigadde** [comment]
@xiang90 Running it as a systemd service. Dont see anything in journalctl other than started/stopped service. Is there anything I can enable to generate/save these logs and try to reproduce? Dont see the -v or the -vv options anymore.

**Comment by xiang90** [comment]
@ravigadde etcd by default should generate error log. We log almost everything when etcd is at bad path.

**Comment by ravigadde** [comment]
@xiang90 This turned out be an iptable issue specific to that particular node. I dont understand why one node going out caused the cluster to be unhealthy though. Cant reproduce the issue again. Will close for now and investigate the logging part. Hopefully will have logs if we hit it again. Thanks for your help.
