### ISSUE TITLE
Support gzip encoding for rest API

### ISSUE THREAD

**Issue by tmaret** [coreos/etcd#2784]
In order to minimise bandwidth, for rest API users that want to, it would be beneficial to support delivering etcd content in gzip format. Users that want that feature would send the `Accept-Encoding: gzip` header and etcd would return the content gzipped with the `Content-Encoding: gzip` header.

We could run etcd behind a dispatcher in order to perform the same, but would it be ok (for consistency) to run an extra piece of infrastructure (proxying requests) in front of etcd instances ?

**Comment by AdoHe** [comment]
@tmaret I think this should be ok.

**Comment by tmaret** [comment]
Thanks for your insight. Is running etcd behind a dispatcher the recommended setup ?

If not, wouldn't it make sense to add support for gzip in the etcd server itself ? 

It would allow to avoid adding extra components that can fail as well as keep the resource footprint of an etcd setup low (which is something nice about etcd).

**Comment by xiang90** [comment]
@tmaret I think you can gzip the content yourself. etcd has no plan to support it in short term (we have frozen v2 api)
