### ISSUE TITLE
Document metrics of etcdv2

### ISSUE THREAD

**Issue by mwitkow-io** [coreos/etcd#2785]
As far as I can see throughout the codebase @xiang90 added support for Prometheus `/metrics` endpoint. That is great news, as we're using Prometheus for our internal monitoring and having etcd2 is very useful.

However, I'm not sure whether this is a public feature or something internal for the Etcd team. Are these metrics there to stay? If so, can we have a mention of them somewhere in public docs?

**Comment by xiang90** [comment]
This is still super expr. We will add some doc around it when we feel more confident about it. (For example, we need to set up our own Prometheus server and see what the actual metrics looks like, etc..) 

But you can try it out and give me feedback. This can help me gain more confidence.

**Comment by mwitkow-io** [comment]
Yea, I wish we could use it. We're currently on the CoreOS Alpha channel and AFAIK the metrics endpoints are in 2.1, right? What's the ETA of 2.1 in Alpha channel?

**Comment by xiang90** [comment]
@mwitkow-io 

When we release the non-alpha version with the metrics endpoint, we will document it but probably as experimental. 

> What's the ETA of 2.1 in Alpha channel?

Next few weeks.
