### ISSUE TITLE
How to watch leader changes in an etcd cluster

### ISSUE THREAD

**Issue by eric-nuaa** [coreos/etcd#2789]
I set up an etcd cluster with 3 nodes, and in each node, beside etcd, I also run my own software which talks with the etcd locally. I'd like my own software be awared once etcd leader changes.
I know that I can check "http://127.0.0.1:2379/v2/stats/self" in each node to know the leader, however, it seems watch API can not be used to watch "http://127.0.0.1:2379/v2/stats/self". So is there a way to get notified once the etcd leader changes.

Thanks.

**Comment by xiang90** [comment]
You cannot watch leader change for now. The endpoint is not watchable right now.
