### ISSUE TITLE
single node etcdhttp: unexpected error: etcdserver: request timed out

### ISSUE THREAD

**Issue by titanous** [coreos/etcd#2791]
A single node cluster (v2.0.10) is throwing these errors:

```text
etcdhttp: unexpected error: etcdserver: request timed out
```

```json
{
  "name": "e7004a513031d43a14c16ec59fc99170",
  "id": "e5f6dda5425fdceb",
  "state": "StateLeader",
  "startTime": "2015-05-06T17:27:02.777681073Z",
  "leaderInfo": {
    "leader": "e5f6dda5425fdceb",
    "uptime": "3h32m24.283035057s",
    "startTime": "2015-05-06T17:27:04.078053172Z"
  },
  "recvAppendRequestCnt": 0,
  "sendAppendRequestCnt": 0
}
```

```json
{
  "getsSuccess": 25204,
  "getsFail": 3,
  "setsSuccess": 23,
  "setsFail": 0,
  "deleteSuccess": 0,
  "deleteFail": 0,
  "updateSuccess": 18415,
  "updateFail": 21,
  "createSuccess": 18,
  "createFail": 15,
  "compareAndSwapSuccess": 0,
  "compareAndSwapFail": 0,
  "compareAndDeleteSuccess": 0,
  "compareAndDeleteFail": 0,
  "expireCount": 10,
  "watchers": 2
}
```

Full log: https://git.io/vJb0r

/cc @temujin9

**Comment by xiang90** [comment]
@titanous This is wired. Are you able to reproduce it? I cannot reproduce it on my local env :(

**Comment by titanous** [comment]
@xiang90 No, this is the first time I've seen it, it was on one of @temujin9's servers.

**Comment by xiang90** [comment]
@temujin9 The only reason I can image is slow disk issue. The data path is pretty simple for a one member cluster. Are you able to reproduce this?

**Comment by temujin9** [comment]
@xiang90 Not predictably, no.

**Comment by xiang90** [comment]
@temujin9 I am still not able to reproduce it. Reopen if you hit this again. We might want the data dir, the log, configuration and your system status for digging into it when it happens again. Thanks!
