### ISSUE TITLE
Document GOMAXPROCS recommendation

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#2794]
re: https://github.com/GoogleCloudPlatform/kubernetes/issues/7767

It would be useful to document recommended GOMAXPROC for optimal performance.

**Comment by barakmich** [comment]
@yichengq Does this make sense for part of our test suite?

**Comment by xiang90** [comment]
@barakmich We can include this var into our benchmark. And we can suggest the "optimal" number of cores for different workload.
