### ISSUE TITLE
github url changed, breaks etcd image w/'rkt fetch'

### ISSUE THREAD

**Issue by drumulonimbus** [coreos/etcd#2796]
```
myhost# ./rkt fetch coreos.com/etcd
rkt: searching for app image coreos.com/etcd
rkt: fetching image from https://github.com/coreos/etcd/releases/download/latest/etcd-latest-linux-amd64.aci
Downloading signature from https://github.com/coreos/etcd/releases/download/latest/etcd-latest-linux-amd64.aci.asc
error downloading the signature file: bad HTTP status code: 404
myhost#
```

Apparently something has changed, and the 'latest' in the URL no longer points at the actual 'latest' directory... if you go to https://github.com/coreos/etcd/releases/latest the URL is rewritten to https://github.com/coreos/etcd/releases/<version>/...

**Comment by philips** [comment]
Sorry, I don't think that we have ever had the latest work with etcd. Is there a doc that says it does?

You can do this though:

```
rkt fetch coreos.com/etcd,version=v2.0.10
```

**Comment by xiang90** [comment]
@drumulonimbus Can you try to what @philips suggest? I am going to close this issue. Reopen it if there is a problem. Thank you for reporting!
