### ISSUE TITLE
excessive log message when an etcd process is killed

### ISSUE THREAD

**Issue by bmccandless** [coreos/etcd#2798]
In 2.1.0-alpha, I have a 3 node cluster.
When I kill the etcd process on one of the nodes, the other two start logging messages at a fast rate,
about 18 messages per second, or about 5KB/second.  This adds up pretty fast.  Is there some way to turn down the frequency or quite it down in some other way. 

2015/05/07 23:50:27 rafthttp: roundtripping error: error roundtripping to http://node3:2380/raft/stream/message/1c72a8f45eb39769: dial tcp 172.30.104.4:2380: connection refused
2015/05/07 23:50:27 rafthttp: roundtripping error: error roundtripping to http://node3:2380/raft/stream/msgapp/1c72a8f45eb39769: dial tcp 172.30.104.4:2380: connection refused
...

**Comment by xiang90** [comment]
This is kind of duplicate with https://github.com/coreos/etcd/issues/2197. The only difference is we changed the logging content. But this should be solved. I am closing this one and will add your issue in #2197.
