### ISSUE TITLE
Request ignored due to cluster ID mismatch?

### ISSUE THREAD

**Issue by hookenz** [coreos/etcd#2800]
I'm attempting to get etcd working correctly on 633.1.0 with an initial cluster of 5 machines.

As suggested previously I'm using etcd2 running inside a docker container.  In order to override the inbuilt etcd in 633.1.0 I created a service file in /etc/systemd/system

I set my initial cluster size to 5 when creating the URL. So extra machines should fall into a proxy mode.  Does that work?

/etc/systemd/system/etcd.service:

    [Unit]
    Description=etcd container
    After=docker.service
    Before=fleet.service

    [Service]
    Restart=always
    RestartSec=10s
    LimitNOFILE=40000
    EnvironmentFile=/etc/environment
    ExecStartPre=-/usr/bin/docker kill etcd
    ExecStartPre=-/usr/bin/docker rm etcd
    #ExecStartPre=/usr/bin/docker pull quay.io/coreos/etcd:v2.0.8
    ExecStart=/usr/bin/docker run \
      -v /var/lib/etcd:/var/lib/etcd \
      -v /usr/share/ca-certificates/:/etc/ssl/certs \
      -p 4001:4001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v2.0.8 \
      -name %H \
      -data-dir /var/lib/etcd \
      -initial-advertise-peer-urls http://${COREOS_PRIVATE_IPV4}:2380 \
      -listen-peer-urls http://0.0.0.0:2380 \
      -discovery=https://***my unique discovery url***
    ExecStop=/usr/bin/docker stop etcd

    [Install]
    WantedBy=multi-user.target

In order to allow restarting etcd, I'm setting the data directory and mounting it locally so it's not lost and it will allow me to hopefully switch to etcd2 when the native version comes out and I won't be needing to put it into docker.

The problem is however, it doesn't work.  The discovery URL is being populated, but I have these errors on my nodes repeated over and over again.

    May 08 01:37:34 service2-3 docker[957]: 2015/05/08 01:37:34 rafthttp: request ignored due to cluster ID mismatch got a7c6bb9a1ba51b7d want 29ac8734ae277c83
    May 08 01:37:45 service2-3 docker[957]: 2015/05/08 01:37:45 rafthttp: request ignored due to cluster ID mismatch got a7c6bb9a1ba51b7d want 29ac8734ae277c83

Can someone please please write a recipe, or tell me what is the recommended way to start a cluster from CoreOS stable using etcd2 without switching to Alpha channel.  Or tell me what's wrong with the above.  

Ideally, write some documentation on how to do it.  Since to switch to Alpha means to migrate my entire cluster.  I'm not going to do that.  I just want etcd2.   I can't use 0.4x, I don't think anyone can possibly run it for more than a few days without it crashing your hosts.  So how do I do it?  

And please, more examples of running bare metal.  I'm using some scripts to populate COREOS_PRIVATE_IPV4 and doing the double-init thing.  That works.

**Comment by xiang90** [comment]
I thing you somehow misconfigured your cluster. Can you please provide the full log of your etcd members?

**Comment by hookenz** [comment]
Unfortunately not.  I tore it down and went with a static config. It's the only one I could get to actually work.

**Comment by xiang90** [comment]
@hookenz It works good with me. And I cannot get this reproduced. Reopen if you can reproduce it and get some meaningful log. Thanks!
