### ISSUE TITLE
Couldn't find localname "service2-2" in the initial cluster configuration.  Funny, it's there is it not?

### ISSUE THREAD

**Issue by hookenz** [coreos/etcd#2801]
Trying to bootstrap a cluster from DNS.

root@b2e8e1955943:/# dig +noall +answer SRV _etcd-server._tcp.cluster
_etcd-server._tcp.cluster. 0    IN      SRV     0 0 1 service2-3.cluster.
_etcd-server._tcp.cluster. 0    IN      SRV     0 0 1 service2-2.cluster.
_etcd-server._tcp.cluster. 0    IN      SRV     0 0 1 service2-1.cluster.

root@b2e8e1955943:/# dig +noall +answer service2-3.cluster service2-1.cluster service2-2.cluster
service2-3.cluster.     0       IN      A       10.10.10.23
service2-1.cluster.     0       IN      A       10.10.10.21
service2-2.cluster.     0       IN      A       10.10.10.22

Service file:

    [Unit]
    Description=etcd container
    After=docker.service
    Before=fleet.service

    [Service]
    Restart=always
    RestartSec=10s
    LimitNOFILE=40000
    EnvironmentFile=/etc/environment
    ExecStartPre=-/usr/bin/docker kill etcd
    ExecStartPre=-/usr/bin/docker rm etcd
    ExecStart=/usr/bin/docker run \
      -v /var/lib/etcd:/var/lib/etcd \
      -v /usr/share/ca-certificates/:/etc/ssl/certs \
      -p 4001:4001 -p 2380:2380 -p 2379:2379 --name etcd quay.io/coreos/etcd:v2.0.8 \
      -name %H \
      -data-dir /var/lib/etcd \
      -discovery-srv cluster \
      -initial-advertise-peer-urls http://%H.cluster:2380 \
      -initial-cluster-token etcd-cluster1 \
      -initial-cluster-state new \
      -advertise-client-urls http://%H.cluster:2379,http://%H.cluster:4001 \
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
      -listen-peer-urls http://0.0.0.0:2380
    ExecStop=/usr/bin/docker stop etcd

    [Install]
    WantedBy=multi-user.target
  
Journal:

    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 netutil: Resolving service2-2.cluster:2380 to 10.10.10.22:2380
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 netutil: Resolving service2-2.cluster:2379 to 10.10.10.22:2379
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 netutil: Resolving service2-2.cluster:4001 to 10.10.10.22:4001
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 discovery: Error querying DNS SRV records for _etcd-server-ssl lookup _etcd-server-ssl._tcp.cluster: no such host
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 discovery: Got bootstrap from DNS for etcd-server at host service2-1.cluster.:1 to http://10.10.10.21:1
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 discovery: Got bootstrap from DNS for etcd-server at host service2-3.cluster.:1 to http://10.10.10.23:1
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 discovery: Got bootstrap from DNS for etcd-server at host service2-2.cluster.:1 to http://10.10.10.22:1
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: listening for peers on http://0.0.0.0:2380
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: listening for client requests on http://0.0.0.0:2379
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: listening for client requests on http://0.0.0.0:4001
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcdserver: datadir is valid for the 2.0.1 format
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: stopping listening for client requests on http://0.0.0.0:4001
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: stopping listening for client requests on http://0.0.0.0:2379
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: stopping listening for peers on http://0.0.0.0:2380
    May 08 03:19:51 service2-2 docker[15469]: 2015/05/08 03:19:51 etcd: couldn't find local name "service2-2" in the initial cluster configuration
    May 08 03:19:51 service2-2 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
    May 08 03:19:51 service2-2 docker[15522]: etcd
    May 08 03:19:51 service2-2 systemd[1]: Unit etcd.service entered failed state.
    May 08 03:19:51 service2-2 systemd[1]: etcd.service failed.

Am I missing something.  Isn't it there?  Why is it failing.  Please help.

**Comment by xiang90** [comment]
@hookenz 
I do not think there is anything funny. And I think you made a mistake.

The best way to help yourself is to read the doc carefully and do things more carefully. 
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#dns-discovery

You named your member in SRV as `service2-2.cluster`. However, you gave the name `service2-2` in your configuration. As the log explicitly tells you "etcd: couldn't find local name "service2-2" in the initial cluster configuration".

**Comment by hookenz** [comment]
Ok I tried appending ".cluster" too. The error was the actually identical. I'll try it again and confirm that

**Comment by xiang90** [comment]
@hookenz Also I found another wired thing:
```
 service2-1.cluster.:1 to http://10.10.10.21:1
```

Do you know where is the :1 port come from?

**Comment by xiang90** [comment]
@hookenz 

Ok. I see your another problem

```
_etcd-server._tcp.cluster. 0 IN SRV 0 0 1 service2-3.cluster.
_etcd-server._tcp.cluster. 0 IN SRV 0 0 1 service2-2.cluster.
_etcd-server._tcp.cluster. 0 IN SRV 0 0 1 service2-1.cluster.
```

You should give the correct port as
```
$ dig +noall +answer SRV _etcd-server._tcp.example.com
_etcd-server._tcp.example.com. 300 IN   SRV 0 0 2380 infra0.example.com.
_etcd-server._tcp.example.com. 300 IN   SRV 0 0 2380 infra1.example.com.
_etcd-server._tcp.example.com. 300 IN   SRV 0 0 2380 infra2.example.com.
```
https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#create-dns-srv-records

**Comment by hookenz** [comment]
Ah Yeah I thought the port was optional. I will try this again next week and append 2380. I think this is more convenient than my static config if i can get it to work properly. 

By the way which data directory is default for etcd2 is it /var/lib/etd or /var/lib/etcd2? So that when etd2 eventually appears in stable by default I can just remove my service file.

**Comment by xiang90** [comment]
i think it is probably /var/lib/etcd2

**Comment by hookenz** [comment]
@xiang90 - Thanks for the hints.  I changed the srv entry to include 2380 as the port number and appended .cluster to the name and it now works.
