### ISSUE TITLE
ttl keys not expiring after node dies

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#2802]
A node was refreshing this ttl key before it died. Instead of the key getting deleted, the ttl goes -ve. Is this a known issue?

{"action":"get","node":{"key":"/foo","value":"bar","expiration":"2015-05-08T07:20:03.786812635Z","ttl":-74,"modifiedIndex":2256,"createdIndex":10},"etcdIndex":2268,"raftIndex":3586,"raftTerm":16}

etcd version 2.0.3

**Comment by ravigadde** [comment]
It seems to get deleted as soon as the node comes up.

**Comment by xiang90** [comment]
Hm... This should be a bug. Can you please give me more details about how to reproduce this?

**Comment by ravigadde** [comment]
I am running my application in 3 vagrant vms. It uses ttl key to implement a lock. The lockholder is killed with a vagrant halt.

**Comment by xiang90** [comment]
Is the "lockholder" your application or etcd? You killed a etcd process?

**Comment by ravigadde** [comment]
The application refreshes the ttl every .4*ttl when its alive. The whole vm is killed. Expectation is for the ttl key to expire and get deleted. Then another node will create the key and refresh ttl.

Used to work with earlier versions.

**Comment by xiang90** [comment]
@ravigadde 

> The whole vm is killed

What is on the whole vm? You still did not answer my simple question: Is the "lockholder" your application or etcd? You killed a etcd process?

**Comment by ravigadde** [comment]
Its an application lock that the 3 VMS are contending for. The lock is implemented using a ttl key.

I halted the vagrant VM which had the lockholder. It will end up sending SIGTERM to all processes is the VM before stopping it. etcd should still have quorum because the other two nodes are up.

Hope that answers your question. I will try a poweroff instead of halt to see if the behavior is any different.

**Comment by xiang90** [comment]
@ravigadde Just make it super clear. Your etcd and your application were on the same vm. When you halted the VM, it SIGTERMed both etcd and your application (the lockholder you mentioned). Correct?

**Comment by ravigadde** [comment]
@xiang90 

Yes, thats correct. All three VMs have etcd and the application running.

**Comment by xiang90** [comment]
@ravigadde Thanks. I will try to reproduce it. If you can reliably reproduce with your env, let me know.

**Comment by tmaret** [comment]
Not sure if it is the same issue, but it has the same symptoms (ttl going < 0). Here is how to reproduce with etcd 2.0.8

Start a three instance cluster locally

```
  $ etcd -name c1 \
  	   -listen-client-urls http://localhost:4001 \
       -advertise-client-urls http://localhost:4001 \
       -initial-advertise-peer-urls http://localhost:2381 \
       -listen-peer-urls http://localhost:2381 \
       -data-dir /Users/tmaret/Desktop/etcd/c1/data.etcd \
       -initial-cluster c1=http://localhost:2381,c2=http://localhost:2382,c3=http://localhost:2383

  $ etcd -name c2 \
  	   -listen-client-urls http://localhost:4002 \
  	   -advertise-client-urls http://localhost:4002 \
       -initial-advertise-peer-urls http://localhost:2382 \
       -listen-peer-urls http://localhost:2382 \
       -data-dir /Users/tmaret/Desktop/etcd/c2/data.etcd \
       -initial-cluster c1=http://localhost:2381,c2=http://localhost:2382,c3=http://localhost:2383


   $ etcd -name c3 \
  	   -listen-client-urls http://localhost:4003 \
  	   -advertise-client-urls http://localhost:4003 \
       -initial-advertise-peer-urls http://localhost:2383 \
       -listen-peer-urls http://localhost:2383 \
       -data-dir /Users/tmaret/Desktop/etcd/c3/data.etcd \
       -initial-cluster c1=http://localhost:2381,c2=http://localhost:2382,c3=http://localhost:2383
```

And a proxy node (on port 9001)

```
$ etcd -proxy on -listen-client-urls http://localhost:9001 -initial-cluster c1=http://localhost:2381,c2=http://localhost:2382,c3=http://localhost:2383
```

Create a key with ttl (through the proxy)

```
$ curl -XPUT localhost:9001/v2/keys/some/key -d ttl=30
```

Kill two of the etcd peers

Get the key with the ttl (periodically, through the proxy)

```
$ curl localhost:9001/v2/keys/some/key
```

Once the ttl has elapsed, it goes below 0

**Comment by xiang90** [comment]
@tmaret This is not the same. The TTL key cannot be removed when you lost quorum, since you killed two etcd members at the same time. The <0 TTL key is expected in your case. This is kind of a design flaw, we probably should not decrease TTL when the quorum is lost. But this is not going to be solved in v2 api.

**Comment by tmaret** [comment]
@xiang90 thanks, something to take into account then. Sorry for hijacking.

**Comment by ravigadde** [comment]
@xiang90 

I tried to recreate several times this morning, no luck so far. Hit it 4 times in a row last night. Rotten luck I suppose.

FYI.. there is also ntpd running on all 3 nodes. I have seen with vagrant VMs on Virtualbox, where they have a big jump in time when they are woken up after a large halt. In our application ntpd is started after etcd and when it syncs time from the ntp server, there is a huge jump in time (order of mins), causing etcd to go in to -ve ttl state. I cannot blame ntpd for hitting it 4 times in a row though. Usually, this big ntp jump happens only when the VMs were halted for a while and woken up the first time.

In the message I posted earlier, you can see ttl decrementing slowly. So I cant blame ntpd in this instance.

Is there a way to add a defensive check around -ve ttl and delete the key?

**Comment by xiang90** [comment]
@ravigadde I think you need to:

1. synced your time between the machine within second level (this should be practical) 

2. reproduce the issue and confirm with me.

I will try to reproduce too. But I never see this happen before. I still suspect this is:

1. because of the time drift on your machines

2. because of your quorum lose

But again, I am not sure. So I have to know you can reproduce it or I can with a right configuration.

**Comment by ravigadde** [comment]
@xiang90 

Sure. Quorum was not lost for sure because I am able to read the keys from the other VMs and see the ttl decrement.

Can you comment on my earlier question about having a defensive check?

**Comment by xiang90** [comment]
> Can you comment on my earlier question about having a defensive check?

That is not possible for now.

The removal action is led by the leader. So if your follower has a large time drift with the leader, then you will see the TTL difference. Users need to make sure the time thing themselves if they want to use TTL feature.

**Comment by xiang90** [comment]
> Quorum was not lost for sure because I am able to read the keys from the other VMs and see the ttl decrement.

You can always read a key from etcd even if the q is lost.

**Comment by ravigadde** [comment]
@xiang90 Thanks! Isn't it a quorum read by default? Sorry if this is a dumb question.

**Comment by xiang90** [comment]
It is not.

**Comment by xiang90** [comment]
@ravigadde Any update?

**Comment by ravigadde** [comment]
@xiang90 

I haven't been able to reproduce it, will close the issue.
