### ISSUE TITLE
Unable to create cluster with v2.1.0-alpha.0

### ISSUE THREAD

**Issue by durzo** [coreos/etcd#2803]
I have successfully used v2.1.0-alpha.0 when upgrading older versions, however starting a new cluster with this version is proving difficult.

I'm using the public etcd discovery url to create a new 2 node cluster:

root@etcd1$ etcd --name etcd1 --discovery='https://discovery.etcd.io/REMOVED' --initial-advertise-peer-urls=http://10.42.23.252:7001 --listen-peer-urls=http://10.42.23.252:7001 --advertise-client-urls=http://10.42.23.252:4001 --listen-client-urls=http://10.42.23.252:4001 --data-dir /var/cache/etcd/state
2015/05/08 22:21:59 etcd: listening for peers on http://10.42.23.252:7001
2015/05/08 22:21:59 etcd: listening for client requests on http://10.42.23.252:4001
2015/05/08 22:21:59 etcdserver: datadir is valid for the 2.0.1 format
2015/05/08 22:22:01 discovery: found self fe5a410a1407cc14 in the cluster
2015/05/08 22:22:01 discovery: found 1 peer(s), waiting for 1 more
-- This is the point where I start etcd on the second node, at which point this node exits with the following error.
2015/05/08 22:23:00 etcd: stopping listening for client requests on http://10.42.23.252:4001
2015/05/08 22:23:00 etcd: stopping listening for peers on http://10.42.23.252:7001
2015/05/08 22:23:00 etcd: unexpected end of JSON input

root@etcd2$ etcd --name etcd2 --discovery='https://discovery.etcd.io/REMOVED --initial-advertise-peer-urls=http://10.42.198.87:7001 --listen-peer-urls=http://10.42.198.87:7001 --advertise-client-urls=http://10.42.198.87:4001 --listen-client-urls=http://10.42.198.87:4001 --data-dir /var/cache/etcd/state
2015/05/08 22:23:05 etcd: listening for peers on http://10.42.198.87:7001
2015/05/08 22:23:05 etcd: listening for client requests on http://10.42.198.87:4001
2015/05/08 22:23:05 etcdserver: datadir is valid for the 2.0.1 format
2015/05/08 22:23:06 discovery: found peer fe5a410a1407cc14 in the cluster
2015/05/08 22:23:06 discovery: found self 4195bbfacc8432ef in the cluster
2015/05/08 22:23:06 discovery: found 2 needed peer(s)
2015/05/08 22:23:06 etcdserver: name = etcd2
2015/05/08 22:23:06 etcdserver: data dir = /var/cache/etcd/state
2015/05/08 22:23:06 etcdserver: member dir = /var/cache/etcd/state/member
2015/05/08 22:23:06 etcdserver: heartbeat = 100ms
2015/05/08 22:23:06 etcdserver: election = 1000ms
2015/05/08 22:23:06 etcdserver: snapshot count = 10000
2015/05/08 22:23:06 etcdserver: discovery URL= https://discovery.etcd.io/REMOVED
2015/05/08 22:23:06 etcdserver: advertise client URLs = http://10.42.198.87:4001
2015/05/08 22:23:06 etcdserver: initial advertise peer URLs = http://10.42.198.87:7001
2015/05/08 22:23:06 etcdserver: initial cluster = etcd1=http://10.42.23.252:7001,etcd2=http://10.42.198.87:7001
2015/05/08 22:23:06 etcdserver: start member 4195bbfacc8432ef in cluster 42213f824bdd1a0
2015/05/08 22:23:06 INFO: raft: 4195bbfacc8432ef became follower at term 0
2015/05/08 22:23:06 INFO: raft: newRaft 4195bbfacc8432ef [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/05/08 22:23:06 INFO: raft: 4195bbfacc8432ef became follower at term 1
2015/05/08 22:23:06 etcdserver: added local member 4195bbfacc8432ef [http://10.42.198.87:7001] to cluster 42213f824bdd1a0
2015/05/08 22:23:06 etcdserver: added member fe5a410a1407cc14 [http://10.42.23.252:7001] to cluster 42213f824bdd1a0
-- At this point etcd1 has crashed, so of course we cannot connect.
2015/05/08 22:23:06 rafthttp: roundtripping error: error roundtripping to http://10.42.23.252:7001/raft/stream/msgapp/4195bbfacc8432ef: dial tcp 10.42.23.252:7001: connection refused
2015/05/08 22:23:06 rafthttp: roundtripping error: error roundtripping to http://10.42.23.252:7001/raft/stream/message/4195bbfacc8432ef: dial tcp 10.42.23.252:7001: connection refused
2015/05/08 22:23:07 rafthttp: roundtripping error: error roundtripping to http://10.42.23.252:7001/raft/stream/msgapp/4195bbfacc8432ef: dial tcp 10.42.23.252:7001: connection refused
2015/05/08 22:23:07 rafthttp: roundtripping error: error roundtripping to http://10.42.23.252:7001/raft/stream/message/4195bbfacc8432ef: dial tcp 10.42.23.252:7001: connection refused

Am I doing something wrong?

**Comment by yichengq** [comment]
@durzo Could you reproduce it? How often do you meet the failure?

**Comment by durzo** [comment]
I was able to reproduce this numerous times last night but it seems to be working just fine today.
Could this be a problem with the discovery service at discovery.etcd.io ?

**Comment by yichengq** [comment]
@durzo Yes, it could be. The case deserves a better error message, and maybe retry logic.

**Comment by xiang90** [comment]
@durzo Closing. If you still see the same problem, feel free to reopen. Thanks.
