### ISSUE TITLE
/v2/stats/leader does not redirect to the leader

### ISSUE THREAD

**Issue by tmaret** [coreos/etcd#2806]
In earlier version of etcd, the API to `/v2/stats/leader` was redirecting (using 307) to the leader instance automatically. With the version 2.0.8, the call is not redirected, either using the etcd proxy or issuing requests to follower instances.

Could this behaviour be added back ?

**Comment by xiang90** [comment]
etcdserver will not do 307 redirection anymore. You can use /v2/members/leader to find out who is the "current" leader in the view of that member and how to connect to it.
