### ISSUE TITLE
what is host IP on docker guide?

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#2812]
Hello,

I am following this documentation and ran into some issues:
https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md

@kelseyhightower could you be more specific on `host IP`? I have no previous experience in CoreOS and am just trying to run `etcd` in container environments. I am quite not sure what you mean by `host IP`. Is it public IP address of the host machine? Or fixed IP address for this case? If so, where does this number come from? Or is it just an arbitrary number?

```
export HostIP="192.168.12.50"
```

I used my public IP address in my local machine and it works as well.

Thanks!

**Comment by barakmich** [comment]
Running inside of Docker depends on your networking setup. Is it host networking? Is it private? Are teh ports forwarded? 

Usually etcd is run outside a container, but there's no reason it can't work inside one either. All `HostIP` means in that context is the IP which other etcd nodes (and clients) can ping or connect to -- if that's inside the container, great. You can usually discover it by running `ifconfig` in the appropriate environment.

**Comment by gyuho** [comment]
Thanks, @barakmich. 
I figured it out running without docker.
