### ISSUE TITLE
The etcd cannot start normally after crash

### ISSUE THREAD

**Issue by lukexue** [coreos/etcd#2814]
Insert bulk data to etcd cause crash. The etcd cannot start normally
---
2015/05/12 22:15:01 raft: a7f2946a0c7c5265 [term: 2914] ignored a MsgHeartbeat message with lower term from 743f1c8f104548d4 [term: 2896]
2015/05/12 22:15:01 raft: a7f2946a0c7c5265 [term: 2914] ignored a MsgHeartbeat message with lower term from 743f1c8f104548d4 [term: 2896]
2015/05/12 22:15:01 raft: a7f2946a0c7c5265 [logterm: 0, index: 1171307] rejected msgApp [logterm: 2904, index: 1171307] from 5478de17b979af77
2015/05/12 22:16:25 etcd: no data-dir provided, using default data-dir ./mp_cluster1.etcd
2015/05/12 22:16:25 etcd: already initialized as member before, starting as etcd member...
2015/05/12 22:16:25 etcd: listening for peers on http://10.0.0.5:7001
2015/05/12 22:16:25 etcd: listening for client requests on http://10.0.0.5:4001
2015/05/12 22:16:25 etcdserver: datadir is valid for the 2.0.1 format
fatal error: runtime: out of memory

runtime stack:
runtime.SysMap(0xc2311e0000, 0x14870000, 0xa54d00, 0xa5f678)
        /usr/local/go/src/runtime/mem_linux.c:149 +0x98
runtime.MHeap_SysAlloc(0xa64d60, 0x14870000, 0x42c782)
        /usr/local/go/src/runtime/malloc.c:284 +0x124
runtime.MHeap_Alloc(0xa64d60, 0xa432, 0x100000000, 0xc208000240)
        /usr/local/go/src/runtime/mheap.c:240 +0x66

goroutine 1 [running]:
runtime.switchtoM()
        /usr/local/go/src/runtime/asm_amd64.s:198 fp=0xc208084bf8 sp=0xc208084bf0
runtime.mallocgc(0x14864000, 0x0, 0x3, 0x14864000)
        /usr/local/go/src/runtime/malloc.go:199 +0x9f3 fp=0xc208084ca8 sp=0xc208084bf8
runtime.rawmem(0x14864000, 0x14864000)
        /usr/local/go/src/runtime/malloc.go:371 +0x39 fp=0xc208084cd0 sp=0xc208084ca8
runtime.growslice(0x70d580, 0x0, 0x0, 0x0, 0x14863973, 0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/slice.go:83 +0x237 fp=0xc208084d30 sp=0xc208084cd0
github.com/coreos/etcd/raft/raftpb.(*Snapshot).Unmarshal(0xc208066000, 0xc21c902000, 0x148639a3, 0x14864000, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/raft/raftpb/raft.pb.go:495 +0x294 fp=0xc208084e08 sp=0xc208084d30
github.com/coreos/etcd/snap.Read(0xc208036140, 0x43, 0x2, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:126 +0x5a0 fp=0xc208084ee8 sp=0xc208084e08
github.com/coreos/etcd/snap.loadSnap(0xc20801dc40, 0x1c, 0xc20803ae70, 0x26, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:93 +0x105 fp=0xc208084f78 sp=0xc208084ee8
github.com/coreos/etcd/snap.(*Snapshotter).Load(0xc208031700, 0x17, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/snap/snapshotter.go:81 +0x13c fp=0xc208085030 sp=0xc208084f78
github.com/coreos/etcd/etcdserver.NewServer(0xc208038210, 0xc2080663f0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:213 +0x20df fp=0xc2080854a8 sp=0xc208085030
github.com/coreos/etcd/etcdmain.startEtcd(0xc208088000, 0x0, 0x0, 0x0)
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:180 +0x13b0 fp=0xc208085c98 sp=0xc2080854a8
github.com/coreos/etcd/etcdmain.Main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:81 +0x594 fp=0xc208085f90 sp=0xc208085c98
main.main()
        /Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x1b fp=0xc208085f98 sp=0xc208085f90
runtime.main()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc208085fe0 sp=0xc208085f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208085fe8 sp=0xc208085fe0

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x35

**Comment by xiang90** [comment]
@lukexue etcd runs out of memory. You have to give it more physical memory. See https://github.com/coreos/etcd/issues/2657. 

We will improve in the later version of etcd.

**Comment by lukexue** [comment]
Can i  set binary data into key/value ?

**Comment by xiang90** [comment]
@lukexue Not in v2.
