### ISSUE TITLE
netutil.URLsEqual may return wrong result

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2815]
I go through the code, and think this is a bug.

In function(https://github.com/coreos/etcd/blob/master/pkg/netutil/netutil.go#L63), it compares the element of two URL slices(we sorted them before passing into function) one by one, but it may resolve TCP address when comparing them.

For example, `http://a.com == http://10.0.0.2` and `http://b.com == http://10.0.0.1`, so I pass in []{`http://a.com`, `http://b.com`} and []{`http://10.0.0.1`, `http://10.0.0.2`}, and they are not equal then.

possible solution is mentioned here: https://github.com/coreos/etcd/pull/2150#issuecomment-71507580
take care of hostname for TLS: https://github.com/coreos/etcd/pull/2150#issuecomment-71525602

@sorah : do i read your code correctly?

**Comment by xiang90** [comment]
@yichengq I do not think we are resolving hostname anymore. So this actually does not matter anymore. We can simply remove the code in netutil probably.

**Comment by xiang90** [comment]
@yichengq I made a mistake before. We do not resolve tcp addr for apurls anymore. However, when doing srv discovery, we do allow user to pass in TCP address or domain name(We have documentation for this usage). So we have to compare the resolved TCP addresses.
