### ISSUE TITLE
Read WAL error after reaching disk full status on 2.0.9

### ISSUE THREAD

**Issue by smarterclayton** [coreos/etcd#2819]
On 02697ca725e5c790cc1f9d0918ff22fad84cb4c5 we saw someone run out of space during an etcd write, at which point the etcd WAL became corrupted (I guess?).  The process was rebooting (due to the wall error) and so it's likely that the repair process also failed because the disk was full.  Is that something explicitly guarded against today?

The logs for the first run after restart when they tried to recover are lost (due to continuing to restart the service) but the most recent was:

```
May 12 09:44:01 os3mndvw1 openshift-master: 2015/05/12 09:44:01 etcdserver: datadir is valid for the 2.0.1 format
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: recovered store from snapshot at index 1220122
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: name = openshift.local
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: data dir = /var/lib/openshift/openshift.local.etcd
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: member dir = /var/lib/openshift/openshift.local.etcd/member
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: heartbeat = 100ms
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: election = 1000ms
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: snapshot count = 0
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: advertise client URLs = https://10.80.88.20:4001
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: loaded cluster information from store: openshift.local=https://10.80.88.20:7001
May 12 09:44:02 os3mndvw1 openshift-master: 2015/05/12 09:44:02 etcdserver: read wal error: unexpected EOF
```

I saw https://github.com/coreos/etcd/issues/2736 and I assume that the original repair information is lost and this is an unrecoverable error.  Is it possible to truncate the WAL or recover the snap from an earlier state?  I believe the built in repair failed (or suspect), but I didn't find a mention of a force repair.

**Comment by yichengq** [comment]
@smarterclayton etcd doesn't support repair in 2.0, and the repair feature is introduced in 2.1

In your case, it is expected that etcd will fatal with wal error because the log entry is half written.
In 2.1, etcd will truncate the half-written part automatically, and it provides the same guarantee as before.  If repair happens, etcd will print out the log explicitly.

**Comment by smarterclayton** [comment]
Ok.  Thanks
