### ISSUE TITLE
etcd2: memory leak in proxy mode?

### ISSUE THREAD

**Issue by serbaut** [coreos/etcd#2825]
I'm running a 3 node etdc2 cluster with an etcd2 proxy on the master node of a kubernetes cluster.

The members in the cluster are using about 42MB RAM but the proxy seems to slowly leak memory (the kuberenetes master ran out of memory yesterday).

### member
    $ cat /proc/$(pidof etcd2)/status
    Name:   etcd2
    State:  S (sleeping)
    Tgid:   560
    Ngid:   0
    Pid:    560
    PPid:   1
    TracerPid:      0
    Uid:    232     232     232     232
    Gid:    232     232     232     232
    FDSize: 128
    Groups: 232
    VmPeak:   177840 kB
    VmSize:   177840 kB
    VmLck:         0 kB
    VmPin:         0 kB
    VmHWM:     48956 kB
    VmRSS:     42576 kB
    VmData:   165168 kB
    VmStk:       136 kB
    VmExe:      3032 kB
    VmLib:      1896 kB
    VmPTE:       144 kB
    VmPMD:        20 kB
    VmSwap:        0 kB
    Threads:        8
    SigQ:   0/3894
    SigPnd: 0000000000000000
    ShdPnd: 0000000000000000
    SigBlk: 0000000000000000
    SigIgn: 0000000000000000
    SigCgt: ffffffffffc1feff
    CapInh: 0000000000000000
    CapPrm: 0000000000000000
    CapEff: 0000000000000000
    CapBnd: 0000003fffffffff
    Seccomp:        0
    Cpus_allowed:   1
    Cpus_allowed_list:      0
    Mems_allowed:   00000000,00000000,00000000,00000001
    Mems_allowed_list:      0
    voluntary_ctxt_switches:        69
    nonvoluntary_ctxt_switches:     20

#### proxy
    $ cat /proc/$(pidof etcd2)/status
    Name:   etcd2
    State:  S (sleeping)
    Tgid:   549
    Ngid:   0
    Pid:    549
    PPid:   1
    TracerPid:      0
    Uid:    232     232     232     232
    Gid:    232     232     232     232
    FDSize: 16384
    Groups: 232
    VmPeak:  1020584 kB
    VmSize:  1020584 kB
    VmLck:         0 kB
    VmPin:         0 kB
    VmHWM:    672524 kB
    VmRSS:    672524 kB
    VmData:  1003688 kB
    VmStk:       136 kB
    VmExe:      2720 kB
    VmLib:      1984 kB
    VmPTE:      1408 kB
    VmPMD:        20 kB
    VmSwap:        0 kB
    Threads:        10
    SigQ:   0/3894
    SigPnd: 0000000000000000
    ShdPnd: 0000000000000000
    SigBlk: 0000000000000000
    SigIgn: 0000000000000000
    SigCgt: ffffffffffc1feff
    CapInh: 0000000000000000
    CapPrm: 0000000000000000
    CapEff: 0000000000000000
    CapBnd: 0000003fffffffff
    Seccomp:        0
    Cpus_allowed:   1
    Cpus_allowed_list:      0
    Mems_allowed:   00000000,00000000,00000000,00000001
    Mems_allowed_list:      0
    voluntary_ctxt_switches:        63
    nonvoluntary_ctxt_switches:     19

**Comment by serbaut** [comment]
The following appears in the log every five minutes. Dont know if it is related:

    May 13 13:06:51 localhost kube-controller-manager[673]: E0513 13:06:51.851413     673 replication_controller.go:172] error from watch during sync: 401: The event in requested index is outdated and cleared (the requested history has been cleared [137418/115570]) [138417]

**Comment by xiang90** [comment]
@serbaut This is a known issue. There was a fd leak. It has been fixed.

**Comment by serbaut** [comment]
Great! In what version? I am running 2.0.8.

**Comment by xiang90** [comment]
@serbaut We will release 2.0.11 this week which will contain that patch.

**Comment by serbaut** [comment]
Ok, thank you!
