### ISSUE TITLE
Http2/push for change notifications

### ISSUE THREAD

**Issue by rektide** [coreos/etcd#2844]
Hello. There's #1980 which mentions upgrading the transport to HTTP2. I greatly enjoy the existing API, but I'd love to see HTTP2's push capabilities put to use for node change notifications.

Instead of registering interest by maintaining an open HTTP request (`&wait=true`), across an HTTP2 connection a client would notify the server of interest (perhaps a `?subscribe=true` query parameter), and when updates become available they are HTTP2 pushed across the held-open connection used by the initiating request.

This would reduce the number of long-poll HTTP2 requests which would have to be held open, hopefully somewhat reducing held state on the client & server.

**Comment by AdoHe** [comment]
@rektide this is cool, I am also wondering how to implement push with etcd.

**Comment by xiang90** [comment]
@rektide When we switch to HTTP2 (automatically happen if you use TLS and compile etcd with go 1.6), one HTTP request will not block other HTTP requests on the same TCP connection. Server Push will not bring us a lot of benefits there. 

We will use gRPC in v3. We use stream to handle watches and it is efficient. We will provide http/http2 + json gateway to gRPC.

I think we can close this now.
