### ISSUE TITLE
etcd2 (2.0.10) in tight loop - dropping MsgHeartbeatResp messages

### ISSUE THREAD

**Issue by eaoliver** [coreos/etcd#2845]
etcd2 gets into a tight loop reporting 'dropping MsgHeartbeatResp' messages.

Following is a sample from: journalctl -u etcd2.service  

May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached
May 18 21:30:17 vb-command etcd2[606]: 2015/05/18 21:30:16 sender: dropping MsgHeartbeatResp because maximal number 64 of sender buffer entries to http://10.0.249.72:2380/raft has been reached

**Comment by xiang90** [comment]
Yes. We are aware of this. And we (@yichengq) are working the improvement.

**Comment by pacasrc** [comment]
I hit this problem on v2.0.9 when I enable peerTLS:
	2015/05/26 03:04:31 raft: 3b2016b3b2f9c7c0 became leader at term 7
	2015/05/26 03:04:31 raft.node: 3b2016b3b2f9c7c0 elected leader 3b2016b3b2f9c7c0 at term 7
	2015/05/26 03:04:32 etcdserver: publish error: etcdserver: request timed out
	2015/05/26 03:04:37 etcdserver: publish error: etcdserver: request timed out
	2015/05/26 03:04:42 etcdserver: publish error: etcdserver: request timed out
	2015/05/26 03:04:42 sender: dropping MsgHeartbeat because maximal number 64 of sender buffer entries to https://192.168.13.248:2380/raft has been reached
	2015/05/26 03:04:42 sender: dropping MsgHeartbeat because maximal number 64 of sender buffer entries to https://192.168.13.248:2380/raft has been reached

==
But I can enable peerTLS on v2.1.0-alpha however there are some io errors
	2015/05/26 03:07:46 INFO: raft: 3b2016b3b2f9c7c0 became leader at term 6
	2015/05/26 03:07:46 INFO: raft.node: 3b2016b3b2f9c7c0 elected leader 3b2016b3b2f9c7c0 at term 6
	2015/05/26 03:07:46 rafthttp: roundtripping error: error roundtripping to https://192.168.13.248:2380/raft/stream/message/3b2016b3b2f9c7c0: read tcp 192.168.13.248:2380: i/o timeout
	2015/05/26 03:07:46 rafthttp: roundtripping error: error roundtripping to https://192.168.13.248:2380/raft/stream/msgapp/3b2016b3b2f9c7c0: read tcp 192.168.13.248:2380: i/o timeout
	2015/05/26 03:07:47 INFO: raft: 3b2016b3b2f9c7c0 failed to send message to b47e5cb226f06fa8 because it is unreachable [next = 4, match = 3, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
	2015/05/26 03:07:47 pipeline: error posting to b47e5cb226f06fa8: read tcp 192.168.13.248:2380: i/o timeout
	2015/05/26 03:07:47 INFO: raft: 3b2016b3b2f9c7c0 failed to send message to b47e5cb226f06fa8 because it is unreachable [next = 4, match = 3, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
	2015/05/26 03:07:47 etcdserver: published {Name:server1 ClientURLs:[http://127.0.0.1:2379]} to cluster 32277b97acfcd316
	2015/05/26 03:07:48 INFO: raft: 3b2016b3b2f9c7c0 failed to send message to b47e5cb226f06fa8 because it is unreachable [next = 8, match = 7, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
	2015/05/26 03:07:49 INFO: raft: 3b2016b3b2f9c7c0 received msgApp rejection(lastindex: 7) from b47e5cb226f06fa8 for index 9
	2015/05/26 03:07:49 INFO: raft: 3b2016b3b2f9c7c0 failed to send message to b47e5cb226f06fa8 because it is unreachable [next = 11, match = 10, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
	2015/05/26 03:07:51 rafthttp: roundtripping error: error roundtripping to https://192.168.13.248:2380/raft/stream/msgapp/3b2016b3b2f9c7c0: read tcp 192.168.13.248:2380: i/o timeout
	2015/05/26 03:07:51 rafthttp: roundtripping error: error roundtripping to https://192.168.13.248:2380/raft/stream/message/3b2016b3b2f9c7c0: read tcp 192.168.13.248:2380: i/o timeout

**Comment by steveeJ** [comment]
I'm seeing similar behaviour with etcd-2.0.11 trying to use peerTLS and clientTLS. In my case the cluster is not fully functional. Can you confirm any of these symptoms?
*  `etcdctl cluster-health` will return unhealthy randomly
* fleet will not work upon the etcd cluster and just print `INFO client.go:292: Failed getting response from https://127.0.0.1:2379/: cancelled` instead
* disabling peerTLS but keeping clientTLS allows fleet to work

I'll happily provide any useful configuration files or logs.

**Comment by Telvary** [comment]
Hi, 
same issue with etcd-2.0.11 and fleet-0.10.1 on a 4 nodes cluster. Tried with and without local etcd proxy.
- cluster-health was ok for me
- same fleet error message
- everything went ok after bootstrapping a new cluster without peerTLS.

**Comment by delianides** [comment]
any update on this? @xiang90

**Comment by groob** [comment]
Hello, 

Same issue here when bootstrapping an etcd-2.0.11 cluster with peerTLS.
cluster-health reports that cluster is unhealthy some of the time.

**Comment by xiang90** [comment]
@yichengq This is resolved by https://github.com/coreos/etcd/pull/2923. Right?

**Comment by yichengq** [comment]
@xiang90 The dropping message log is still a flood, and i will fix it.

**Comment by yichengq** [comment]
The log printout has been improved through #2960 , which only prints necessary logs now.

The TLS problem has been solved in current master.
