### ISSUE TITLE
etcd (2.0.10) not dropping dead node from cluster

### ISSUE THREAD

**Issue by eaoliver** [coreos/etcd#2846]
I have a three node cluster.  Three nodes are added.  One node is dropped.  Hours later it still persists in the member list.

core@vb-command ~ $ etcdctl member list
cff8dc47b12098: name=dd0f8d39432c4a9aa6bcf107cfb8056e peerURLs=http://10.0.148.177:2380 clientURLs=http://localhost:2379
5a1d6fb5c6c43670: name=7f31f7ab04e440f1b13e203c8029bd18 peerURLs=http://10.0.249.72:2380 clientURLs=http://localhost:2379
6819e1dfa1122915: name=vb_command peerURLs=http://10.0.0.10:2380 clientURLs=http://localhost:2379

**Comment by xiang90** [comment]
@eaoliver You need to remove it via runtime reconfiguration API. All configuration needs to be done explicitly.

**Comment by xiang90** [comment]
Here is the API doc: https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md

**Comment by eaoliver** [comment]
Thanks.  I tried removing it, but it doesn't work.  I got "Recieved an error trying to remove member cff8dc47b12098: context deadline exceeded"

core@vb-command ~ $ etcdctl member list
cff8dc47b12098: name=dd0f8d39432c4a9aa6bcf107cfb8056e peerURLs=http://10.0.148.177:2380 clientURLs=http://localhost:2379
5a1d6fb5c6c43670: name=7f31f7ab04e440f1b13e203c8029bd18 peerURLs=http://10.0.249.72:2380 clientURLs=http://localhost:2379
6819e1dfa1122915: name=vb_command peerURLs=http://10.0.0.10:2380 clientURLs=http://localhost:2379

core@vb-command ~ $ etcdctl member remove  cff8dc47b12098

Recieved an error trying to remove member cff8dc47b12098: context deadline exceeded

core@vb-command ~ $ etcdctl member list
cff8dc47b12098: name=dd0f8d39432c4a9aa6bcf107cfb8056e peerURLs=http://10.0.148.177:2380 clientURLs=http://localhost:2379
5a1d6fb5c6c43670: name=7f31f7ab04e440f1b13e203c8029bd18 peerURLs=http://10.0.249.72:2380 clientURLs=http://localhost:2379
6819e1dfa1122915: name=vb_command peerURLs=http://10.0.0.10:2380 clientURLs=http://localhost:2379
