### ISSUE TITLE
too many open files in a 3-node cluster

### ISSUE THREAD

**Issue by 985** [coreos/etcd#2847]
I got this issue with etcd 0.4.7 and docker 1.5.0 in 3 nodes cluster.  I made this cluster with 647 stable release coreos. I have used it for a week without any problem. Somehow, it doesn't work now.
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/%202015-05-19%2011.16.13_zpstjqy6xo8.png)
At first, I found this 
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/%202015-05-19%2011.06.25_zpsufgegxle.png)
then, I checked service of fleet.
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/%202015-05-19%2011.05.59_zpstsfzl7tr.png)
I thought it is about etcd
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/%202015-05-19%2011.05.35_zpsemqc3hpn.png)
Then, [issue1959](https://github.com/coreos/etcd/issues/1959) says it may be because of file-descriptor-limit. 
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/max_zpsto1qvjoe.jpg)
It seems that I have used them all.
now ,I want to know how to change the max file descriptor limit, how to release the current use and how to make it work. I already tried this one.
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/ulimit_zpshmxcf5vh.jpg)
![](http://i1066.photobucket.com/albums/u407/5681713/too%20many%20open%20files/hi_zpsvhbfnkjz.jpg)

**Comment by xiang90** [comment]
@985 There are many reasons that you might end up with fd issues:

1. you have too many concurrent clients?

2. you have many long polling clients?

3. your client is leaking connections?

4. there is a bug in etcd?

Without your client side information and the current fd usage status, it is hard for me to dig it deeper. 

But as you said, it seems that your client used up all the fds.
> now ,I want to know how to change the max file descriptor limit

You can google around about how to increase the limitation of fd.

**Comment by xiang90** [comment]
@985 I am closing this due to low activity. Reopen if you have a follow-up. Thanks!
