### ISSUE TITLE
fails to set keys to etcd

### ISSUE THREAD

**Issue by ngpestelos** [coreos/etcd#2851]
Running etcd 0.4.6 on a Deis cluster: https://github.com/deis/deis/issues/3726

Restarted etcd on one of the nodes and still no journal; `debug-etcd` is returning an error, too. 

Also. when I manually set a value (e.g. `/deis/logs/drain`), the value gets set, but disappears after a while.

**Comment by barakmich** [comment]
It'd help to have a bit more context; what's the error that's being returned? Are you using journald? Is it necessary to run 0.4.6, or is 2.0.x available to you?

**Comment by ngpestelos** [comment]
Thanks for replying. I filed this ticket after reporting this issue in Deis: https://github.com/deis/deis/issues/3726 

My workaround was to identify and to replace the troublesome node.

No, my version of etcd depends on what Deis currently uses.
