### ISSUE TITLE
etcdctl get and remove lock

### ISSUE THREAD

**Issue by grahamjenson** [coreos/etcd#2855]
I would like to have the ability to get a lock from the command line. I think this could work like

```
etcdctl getlock lockname --timeout 60s
```

which will wait untill the lock is available, or error after 60 seconds.

then of course, clear the lock for others to grab

```
etcdctl clearlock lockname
```

This would be really useful for global systemd services to ensure a specific order of booting

```
fleetctl start global.service
```

and in the systemd file:

```
...
ExecStartPre=/usr/bin/etcdctl getlock lockname --timeout 60s
...
ExecStartPost=/usr/bin/etcdctl clearlock lockname
```

This came up while trying to write a global service for a clustering DNS server consul, where one node would need to first start then advertise to the rest of the services.

**Comment by barakmich** [comment]
This relates to the adding of some standard lock methods (perhaps implemented in a funky-but-consistent way on V2 and perhaps much better on V3) to etcd/client -- which itself will be backing etcdctl, so this is a fine feature request as we take a hard look at that in v2.2.

**Comment by xiang90** [comment]
After talk with @philips and @ecnahc515, we decided not to write a lock wrapper in etcdctl or client. The locking stuff will be supported by etcd v3 API natively. etcdctl will use that API then. Move this to etcd 3.0 milestone.

**Comment by xiang90** [comment]
Now we got a lock cmd in etcdctl here https://github.com/coreos/etcd/tree/master/etcdctlv3#lock-lockname.

We can close this issue. Right now, this is a client side implementation. We probably will move the impl to server side as a proxy when we feel the impl is stable enough.

**Comment by tlvenn** [comment]
I might be missing something very obvious here but how exactly can you use the lock cmd etcdctl provides to accomplish what the OP wanted to do ? A concrete example would be super useful. Thanks in advance.

**Comment by grahamjenson** [comment]
This was a while ago but the idea was when starting a global service that runs on all boxes, for one to grab the lock and start, while the others wait on the lock. This way there will be a clear winner on which server is the "winner"

**Comment by heyitsanthony** [comment]
@tlvenn
```sh
mkfifo mylock.fifo
ETCDCTL_API=3 ./bin/etcdctl lock mylock >mylock.fifo &
pid=$!
if read lockname <mylock.fifo; then
    echo holding lock with key $lockname
    ... do whatever ...
fi
kill $pid
wait $pid
```

**Comment by tlvenn** [comment]
Thanks a lot for the snippet @heyitsanthony ! I had no idea about named pipe on linux.... It would be probably super useful to hint about it and provide the above snippet in the doc.

Is there any chance the lock command could be enhanced to accept a child argument similarly to what Consul does and take care of the above itself to simplify this ?

For reference: https://www.consul.io/docs/commands/lock.html

**Comment by JensRantil** [comment]
@tlvenn You've probably seen it, but that's now in place since #7983 was merged.

**Comment by tlvenn** [comment]
awesome, thanks for the notice @JensRantil !
