### ISSUE TITLE
Create /path/key if-and-only-if /path exists but key does not

### ISSUE THREAD

**Issue by schmichael** [coreos/etcd#2857]
### Current behavior

As of etcd 2.0.11 the following creates `/path/key` iff `/path/key` does not exist. However, it *will* create `/path/key` regardless of whether or not `/path` exists.

```sh
curl -XPUT localhost:2379/v2/keys/path/key?prevExist=false
{"action":"create","node":{"key":"/path/key","value":"","modifiedIndex":7,"createdIndex":7}}
```
### Desired behavior

Have an option (`recursive=false` perhaps?) to cause PUTs to *fail* if the parent path component doesn't exist.

### Workaround

Depending on your use case the following may be a sufficient workaround:

* PUT /path/key?prevExist=false
* GET /path
  * If `/path`'s CreatedIndex == `/path/key`'s CreatedIndex, then: DELETE /path?recursive=true

Obviously this method isn't an atomic operation, so it's not suitable for all cases the *Desired Behavior* above covers.

**Comment by barakmich** [comment]
More importantly, you might like the byte-keyspace (and atomic transactions!) of the [v3 API](https://github.com/coreos/etcd/pull/2675) which is underway.  We're holding off on extending v2 -- but if there is a clear bug here (ie, the creation of the `/path/key`) but I think that's documented that way -- if it's unexpected behavior then feel free to reopen!

**Comment by schmichael** [comment]
*Oops, I didn't mean to repoen this with an unrelated ticket in a totally different project! Sorry!*

However:

I don't see Create/PUT's recursive behavior documented anywhere, and other operations with recursive abilities (e.g. GET/DELETE) have the `recursive=...` option to toggle the behavior.

So I'd say this is a documentation "bug" and a missing feature. v3's atomic transactions is definitely a solution though, so feel free to re-close.
