### ISSUE TITLE
Add migration doc to the repo

### ISSUE THREAD

**Issue by barakmich** [coreos/etcd#2860]
We have the text of it here: 
https://coreos.com/etcd/docs/2.0.8/backward_compatibility.html#data-directory-migration

But it should maybe exist in the repo as well? Especially as we move to a docs-format.

**Comment by xiang90** [comment]
Do you mean this? https://github.com/coreos/etcd/blob/master/Documentation/backward_compatibility.md#data-directory-migration

**Comment by barakmich** [comment]
Yeah, fair enough. "backward compatibility" is an odd name. Closing the issue, and deferring it to a docs format.
