### ISSUE TITLE
Hardcoded timeouts make proxy nodes very likely to have failures

### ISSUE THREAD

**Issue by andymuldowney** [coreos/etcd#2862]
A combination of hardcoded and default timeouts makes rescheduling of `fleet` units on nodes utilizing `etcd` in proxy mode very likely in common failure scenarios.  This has been largely addressed in `master` (as far back as February), but not yet merged into a release.

### Configuration assumptions
 
* Default `fleet` `agent_ttl` of 30 seconds on all nodes in `fleet`
* A 3-node `etcd` cluster, with other hosts in proxy mode utilizing those endpoints configured via hostnames in the `initial-cluster` configuration string.  Let's assume `etcd` nodes are named `etcd-[1-3]`.

### Failure scenario

Host `host-1` is in `etcd` proxy mode and processes a request.  The proxy director selects `etcd-1`, which has just gone offline due to a reboot, network failure, etc.  Because of https://github.com/coreos/etcd/blob/master/proxy/director.go#L31, that node could be considered active for up to 30 seconds after failing.  https://github.com/coreos/etcd/blob/v2.0.11/pkg/transport/timeout_transport.go#L36 allows this request up to a 30 second dial timeout.  Combined, those two timeouts allow for an invalid node to remain as an active proxy endpoint for up to 60 seconds.  Due to the default `fleet` `agent_ttl` of 30 seconds, it's very likely that `host-1` units now get rescheduled.

In a cluster, with `etcd` configured as described above, a failure of a single `etcd-[1-3]` would likely result in approximately one-third of hosts having their units rescheduled in `fleet`.

- - -

This has been fixed in `master`, as seen at https://github.com/coreos/etcd/blob/master/pkg/transport/timeout_transport.go#L36

What is the timeline for merging this change into a release (preferably on the 2.0.x branch)?  I would consider it critical for anyone using proxy nodes.  One possible current fix is to increase `fleet` `agent_ttl`, but that has other implications.

**Comment by xiang90** [comment]
@andymuldowney What do you suggest us to do at etcd side?

**Comment by andymuldowney** [comment]
@xiang90 Merging of https://github.com/coreos/etcd/blob/master/pkg/transport/timeout_transport.go#L36, and related changes, will reduce the default timeout to 5s which is much more acceptable.  Doing this in a `2.0.12` release would be ideal.

Ultimately, moving forward, configurable proxy timeouts would be great.

**Comment by xiang90** [comment]
@andymuldowney Sure.

**Comment by andymuldowney** [comment]
https://github.com/coreos/etcd/blob/master/proxy/director.go#L28-L31 would both benefit from configurable values, in my opinion.

**Comment by yichengq** [comment]
I have backported dial timeout change in 2.0.12 as @andymuldowney suggests.
