### ISSUE TITLE
etcd2 not picking up on ETCD_TRUSTED_CA_FILE

### ISSUE THREAD

**Issue by ariddell** [coreos/etcd#2866]
I'm having trouble getting a TLS secured cluster running. I suspect there's a problem with specifying the ca file. For example, I see these lines in the etcd2 journal:
```
May 25 00:57:46 ark-cbd31b78-17a6-424e-8d0d-374f557ec788 etcd2[909]: 2015/05/25 00:57:46 etcd: peerTLS: cert = /etc/etcd/node.crt, key = /etc/etcd/node.key.insecure, ca =
May 25 00:57:48 ark-cbd31b78-17a6-424e-8d0d-374f557ec788 etcd2[909]: 2015/05/25 00:57:48 etcd: listening for peers on https://0.0.0.0:2380
May 25 00:57:48 ark-cbd31b78-17a6-424e-8d0d-374f557ec788 etcd2[909]: 2015/05/25 00:57:48 etcd: clientTLS: cert = /etc/etcd/node.crt, key = /etc/etcd/node.key.insecure, ca =
```
Despite the fact that I have these lines in the etcd2 service file:

```
Environment="ETCD_TRUSTED_CA_FILE=/etc/etcd/ca.crt"
Environment="ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd/ca.crt"
```

Coreos beta 668.3.0

**Comment by ariddell** [comment]
If I used the old version, ETCD_CA_FILE, everything works fine. Perhaps the documentation should be changed to reflect that ETCD_TRUSTED_CA_FILE isn't supported as of 2.0.10?

**Comment by yichengq** [comment]
@ariddell The 2.0 doc is checked through https://github.com/coreos/etcd/tree/release-2.0/Documentation, while 2.1 doc is checked through master branch.
We introduce new flags ETCD_TRUSTED_CA_FILE in 2.1, but they don't exist in 2.0.
Sorry for the confusion on the documentation. We don't have a good system to reflect the documentation for different versions nowadays.

**Comment by ariddell** [comment]
Got it. That makes sense. The url suggested that the docs were versioned: https://coreos.com/etcd/docs/2.0.8/configuration.html
