### ISSUE TITLE
Promote proxy to member

### ISSUE THREAD

**Issue by Telvary** [coreos/etcd#2869]
Hi,

Allowing a proxy to be promoted could be usefull to replace a lost member of the etcd cluster. The lost node could come back later as a proxy. This will permit some sort of HA.

Also, being able to handle the localization of the nodes to force members distribution across datacenters would be a good complement to the previous feature.

Example : for 3 locations, I have 5 etcd nodes. 3 nodes per location should be member, while the other 2 are proxy which could be use for load balancing and replace a failing member.

**Comment by xiang90** [comment]
We have no plan to support auto promotion in etcd. In most cases, you should put your etcd cluster to a relative stable environment, replacing dead member shoud happen very rare. 

If you really want to automatic this process, you can implement a etcd-manager to do this via runtime reconfiguration API.

**Comment by xiang90** [comment]
Relative issue: https://github.com/coreos/etcd/issues/2752
