### ISSUE TITLE
how to build etcd in windows

### ISSUE THREAD

**Issue by IT-BB** [coreos/etcd#2873]
I run 'go build etcd' in cmd but has the error 

# github.com/coreos/etcd/Godeps/_workspace/src/github.com/coreos/pkg/capnslog
github.com\coreos\etcd\Godeps\_workspace\src\github.com\coreos\pkg\capnslog\sysl
og_formatter.go:7: undefined: syslog.Writer
github.com\coreos\etcd\Godeps\_workspace\src\github.com\coreos\pkg\capnslog\sysl
og_formatter.go:20: undefined: syslog.Writer

so I want to know how to build etcd in windows.

thinks.

**Comment by xiang90** [comment]
@IT-BB We will fix this issue when we release 2.1. You can build etcd in the release branch: https://github.com/coreos/etcd/tree/release-2.0

**Comment by IT-BB** [comment]
@xiang90  I had compiled successfully when i ignore this file(syslog_formatter.go) beacause is file is suppored in linux but don't suppored windows.
