### ISSUE TITLE
Can I compare and swap with empty previous value?

### ISSUE THREAD

**Issue by pacasrc** [coreos/etcd#2880]
Hi ,

paca> /usr/bin/curl -L http://127.0.0.1:2379/v2/keys/a
{"action":"get","node":{"key":"/a","value":"","modifiedIndex":42,"createdIndex":42}}

paca> /usr/bin/curl http://127.0.0.1:2379/v2/keys/a?prevValue= -XPUT -d value=123
{"errorCode":201,"message":"PrevValue is Required in POST form","cause":"\"prevValue\" cannot be empty","index":0}

Is there a way to compare and swap with a previous value "" to another new value?
Thanks.

**Comment by yichengq** [comment]
etcd doesn't support to compare and swap an empty value today.

**Comment by bohdantrotsenko** [comment]
As I just discovered, `etcdctl mk /key` does what `--swap-with-value ""` would do.
