### ISSUE TITLE
proxy leaks connections ?

### ISSUE THREAD

**Issue by superfell** [coreos/etcd#2884]
I'm testing a 3 node setup (all on one host, as per the supplied Procfile), built from master (at ce5e14e71362310680f67ca53016cb5f93713eb1) I have a client app that writes 20k keys using 10 concurrent connections, then reads all 20k values back, and repeats. [it re-uses key names, so the total number of keys doesn't change after the first run).

If i point this at the leader, or a member, it runs fine, if however i point this at the proxy, the proxy node seems to fairly quickly fold, with a log like

16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4002: dial tcp 127.0.0.1:4002: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: marked endpoint http://localhost:4002 unavailable
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4002: dial tcp 127.0.0.1:4002: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4002: dial tcp 127.0.0.1:4002: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4002: dial tcp 127.0.0.1:4002: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4003: dial tcp 127.0.0.1:4003: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: marked endpoint http://localhost:4003 unavailable
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4003: dial tcp 127.0.0.1:4003: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4001: dial tcp 127.0.0.1:4001: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: marked endpoint http://localhost:4001 unavailable
16:13:58 proxy | 2015/05/28 16:13:58 proxy: unable to get response from 3 endpoint(s)
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4001: dial tcp 127.0.0.1:4001: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: unable to get response from 1 endpoint(s)
16:13:58 proxy | 2015/05/28 16:13:58 proxy: failed to direct request to http://localhost:4001: dial tcp 127.0.0.1:4001: can't assign requested address
16:13:58 proxy | 2015/05/28 16:13:58 proxy: unable to get response from 1 endpoint(s)
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:13:58 proxy | 2015/05/28 16:13:58 proxy: zero endpoints currently available
16:14:00 etcd3 | 2015/05/28 16:14:00 etcdserver: failed to reach the peerURL(http://localhost:7001) of member a8266ecf031671f3 (Get http://localhost:7001/version: dial tcp 127.0.0.1:7001: can't assign requested address)
16:14:00 etcd3 | 2015/05/28 16:14:00 etcdserver: cannot get the version of member a8266ecf031671f3 (Get http://localhost:7001/version: dial tcp 127.0.0.1:7001: can't assign requested address)

This perhaps indicates a socket leak in the proxy ?

**Comment by yichengq** [comment]
What is your file descriptor limit? Could you enlarge it and give it another try? My guess is that it happens because proxy doesn't reuse connections wisely. If so, it should work when the file descriptor limit is large enough.

**Comment by yichengq** [comment]
My last comment is not right. The error line indicates that there is no ephemeral port available, so increasing file descriptor limit doesn't help. etcd proxy needs to be more connection-efficient to solve this problem.

**Comment by yichengq** [comment]
The issue has been solved in master.
