### ISSUE TITLE
Ordered keys sort question

### ISSUE THREAD

**Issue by jbdalido** [coreos/etcd#2886]
Hello everyone,

i'm running into an issue (might not be one at all sorry) with ordered keys. I have a directory
using atomic ordered keys to handle versionning of a value, the last one is the good 
one and previous are history.

It's working great until it don't. Here's a sample of the sorted keys sent by etcd :

    {
        "action": "get",
        "node": {
            "key": "/mykey/app/dev/maintenance",
            "dir": true,
            "nodes": [
                {
                    "key": "/mykey/app/dev/maintenance/10",
                    "value": "..."",
                    "modifiedIndex": 10,
                    "createdIndex": 10
                },
                ...
                {
                    "key": "/mykey/app/dev/maintenance/19",
                    "value": "...",
                    "modifiedIndex": 19,
                    "createdIndex": 19
                },
                {
                    "key": "/mykey/app/dev/maintenance/3",
                    "value": "...",
                    "modifiedIndex": 3,
                    "createdIndex": 3
                },
                {
                    "key": "/mykey/app/dev/maintenance/6",
                    "value": "...",
                    "modifiedIndex": 6,
                    "createdIndex": 6
                },
                ...
            ],
            "modifiedIndex": 3,
            "createdIndex": 3
        }
    }

I understand the sorted are sent by keys so the order makes sense based on a string sort, 
but from what i understood the all idea of the sort was to sent back the keys in creation order,
or if i understood wrong, we just have to implement a sort based of the CreatedIndex
in our client ?

Anyway thanks in advance for the help.

**Comment by xiang90** [comment]
Yes. If you want to sort in other orders, you need to implement it in your client.
