### ISSUE TITLE
Proxy Closes Body on First Failure

### ISSUE THREAD

**Issue by BlueDragonX** [coreos/etcd#2895]
Hi all. I am running a CoreOS cluster with a core etcd cluster of five instances. All of the other cluster members are running etcd in proxy mode.

The proxies lose connectivity with the etcd cluster frequently. What happens is the proxy will attempt to connect to the first endpoint and fail with `read tcp etcd1:2379: use of closed network connection`. The remaining endpoints then fail with `http: invalid Read on closed Body`.

This appears to be a bug in the way the reverseProxy's ServeHTTP function reuses the request. The `http.Transport.RoundTrip` function (called at https://github.com/coreos/etcd/blob/master/proxy/reverse.go#L101) closes the body on error. Thus if the first endpoint fails due to a transport issue all remaining endpoints will also fail.

Here's a log of this happening in my cluster:

    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd4:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd5:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd1:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd2:2379 available
    Jun 01 16:46:18 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:18 proxy: marked endpoint http://etcd3:2379 available
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd3:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd1:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd2:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd1:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd5:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: marked endpoint http://etcd4:2379 unavailable
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd2:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd5:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: failed to direct request to http://etcd4:2379: http: invalid Read on closed Body
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: unable to get response from 5 endpoint(s)
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: zero endpoints currently available
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: zero endpoints currently available
    Jun 01 16:46:29 ip-0-0-0-0.myawszone.compute.internal etcd2[610]: 2015/06/01 16:46:29 proxy: zero endpoints currently available

My etcd version:

    $ etcd2 --version
    etcd Version: 2.0.11
    Git SHA: 0678329
    Go Version: go1.4.2
    Go OS/Arch: linux/amd64

I should note that the other endpoints were indeed available during the above occurrence.

**Comment by xiang90** [comment]
@BlueDragonX I think this is probably a bug as you suggest. Do you want to send a pull request? Or I can look into it and try to fix it.

**Comment by BlueDragonX** [comment]
@xiang90 I plan on putting a PR together before EOD. I wanted to get this out there before I started to see if there was any other feedback.

**Comment by xiang90** [comment]
@BlueDragonX If you are sure it is caused by the reuse of http request, then it makes sense to me. Go for it. Thank you!

**Comment by BlueDragonX** [comment]
I ran the above PR in my prod cluster to compare behavior to master. It appears solve the problem. Requests through the proxy now succeed where before they failed. Case in point: `watch -n1 fleetctl list-units` no longer complains about 500 errors.

Here's the log output running my version:

    2015/06/1 23:57:11 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
    2015/06/1 23:57:11 etcdmain: no data-dir provided, using default data-dir ./default.etcd
    2015/06/1 23:57:12 discovery: Error querying DNS SRV records for _etcd-server-ssl lookup _etcd-server-ssl._tcp.localdomain: no such host
    2015/06/1 23:57:12 discovery: Got bootstrap from DNS for etcd-server at http://etcd2.localdomain:2380
    2015/06/1 23:57:12 discovery: Got bootstrap from DNS for etcd-server at http://etcd1.localdomain:2380
    2015/06/1 23:57:12 discovery: Got bootstrap from DNS for etcd-server at http://etcd3.localdomain:2380
    2015/06/1 23:57:12 discovery: Got bootstrap from DNS for etcd-server at http://etcd4.localdomain:2380
    2015/06/1 23:57:12 discovery: Got bootstrap from DNS for etcd-server at http://etcd5.localdomain:2380
    2015/06/1 23:57:12 etcdmain: proxy: using peer urls [http://etcd1.localdomain:2380 http://etcd2.localdomain:2380 http://etcd3.localdomain:2380 http://etcd4.localdomain:2380 http://etcd5.localdomain:2380] 
    2015/06/1 23:57:12 etcdmain: proxy: listening for client requests on 0.0.0.0:2379
    2015/06/1 23:57:12 etcdmain: proxy: listening for client requests on 0.0.0.0:4001
    2015/06/1 23:57:13 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:13 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:57:13 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:13 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:13 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:18 proxy: marked endpoint http://etcd3:2379 available
    2015/06/1 23:57:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:29 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:57:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:30 proxy: failed to direct request to http://etcd1:2379: read tcp etcd1:2379: use of closed network connection
    2015/06/1 23:57:30 proxy: marked endpoint http://etcd1:2379 unavailable
    2015/06/1 23:57:30 proxy: failed to direct request to http://etcd1:2379: read tcp etcd1:2379: use of closed network connection
    2015/06/1 23:57:30 proxy: failed to direct request to http://etcd1:2379: read tcp etcd1:2379: use of closed network connection
    2015/06/1 23:57:30 proxy: failed to direct request to http://etcd1:2379: read tcp etcd1:2379: use of closed network connection
    2015/06/1 23:57:31 proxy: failed to direct request to http://etcd1:2379: read tcp etcd1:2379: use of closed network connection
    2015/06/1 23:57:34 proxy: marked endpoint http://etcd3:2379 available
    2015/06/1 23:57:35 proxy: marked endpoint http://etcd1:2379 available
    2015/06/1 23:57:45 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:45 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:57:50 proxy: marked endpoint http://etcd3:2379 available
    2015/06/1 23:57:58 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:57:58 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:58:03 proxy: marked endpoint http://etcd3:2379 available
    2015/06/1 23:58:13 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:58:13 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:58:13 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:58:13 proxy: failed to direct request to http://etcd3:2379: use of closed network connection
    2015/06/1 23:58:13 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:58:13 proxy: failed to direct request to http://etcd3:2379: use of closed network connection
    2015/06/1 23:58:13 proxy: failed to direct request to http://etcd3:2379: use of closed network connection
    2015/06/1 23:58:18 proxy: marked endpoint http://etcd3:2379 available
    2015/06/1 23:58:18 proxy: marked endpoint http://etcd3:2379 available
    2015/06/1 23:58:29 proxy: failed to direct request to http://etcd3:2379: read tcp etcd3:2379: use of closed network connection
    2015/06/1 23:58:29 proxy: marked endpoint http://etcd3:2379 unavailable
    2015/06/1 23:58:30 proxy: failed to direct request to http://etcd1:2379: read tcp etcd1:2379: use of closed network connection
    2015/06/1 23:58:30 proxy: marked endpoint http://etcd1:2379 unavailable
