### ISSUE TITLE
Multiple cluster members with the same name should throw an error.

### ISSUE THREAD

**Issue by brendandburns** [coreos/etcd#2899]
I was trying to set up multi-node etcd and I accidentally left of the ```--name``` flag.

Etcd happily clustered itself up, and presented no errors with ```etcdctl cluster-health```

but the clustering itself didn't work correctly (obviously).

I think etcd should chose a random name for iteself, not ```default``` if no name is specified.

And regardless, a cluster shouldn't think it's healthy in this state (there were no followers)

**Comment by xiang90** [comment]
@brendandburns Which version of etcd were you running? Current master?

**Comment by brendandburns** [comment]
2.0.9

**Comment by xiang90** [comment]
@brendandburns How did you set up the multi-member cluster? We require explicitly initial cluster from 2.0. Did you add member one by one?

**Comment by brendandburns** [comment]
I used discovery using the etcd.io discovery service.

**Comment by brendandburns** [comment]
fwiw, this isn't about the cluster name, this is the node name

**Comment by xiang90** [comment]
@brendandburns Yes. OK. I understand.

**Comment by xiang90** [comment]
closed by #3094.
follow up thought at #3025.
