### ISSUE TITLE
improve logging message

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2905]
The runtime logging message is basically useless for the etcd users right now.

We need to translate the internal error message to more understandable message. 

For example, we need to translate the rafthttp layer error to a connection lost error and make the internal error to debugging level.

Also for requests timeout that caused by leader lost, we need to make it better to understand. 

If there is a leader election happened, the request lost will be reported after 5 seconds or so. It would be hard for people that are not quite familiar with raft/consensus to understand their relationship.

For raft message, we might want to completely hide them from user except the leader change ones.

**Comment by xiang90** [comment]
from @yichengq

```
People may open issue think this is a bug, but actually this indicates that proposal fails to be committed. In most cases, this happens because etcd cluster is unhealthy; sometimes, this happens because the leader just switched several seconds ago.

We need to improve the error log for this.
```

**Comment by yichengq** [comment]
We have done this step by step, and finished all of them now.
