### ISSUE TITLE
etcdhttp: unexpected error: etcdserver: request timed out

### ISSUE THREAD

**Issue by hyperbolic2346** [coreos/etcd#2917]
Having trouble with etcd version 2.0.10. I have a machine that is unhealthy and is causing other machines to be unable to publish data to etcd.
```
etcdctl cluster-health
cluster is healthy
member 3a752bcccdefffe9 is unhealthy
member 588e7deaa28fd696 is healthy
member 6a908ca1696ce9a4 is healthy
member bc72cb0ca1efaedb is healthy
member d9f8cf11e7fb2acd is healthy
```
```
etcdctl member list
3a752bcccdefffe9: name=catbert peerURLs=http://10.0.1.19:2380 clientURLs=http://10.0.1.19:2379
588e7deaa28fd696: name=dilbert peerURLs=http://10.0.1.23:2380 clientURLs=http://10.0.1.23:2379
6a908ca1696ce9a4: name=wally peerURLs=http://10.0.1.21:2380 clientURLs=http://10.0.1.21:2379
bc72cb0ca1efaedb: name=dogbert peerURLs=http://10.0.1.22:2380 clientURLs=http://10.0.1.22:2379
d9f8cf11e7fb2acd: name=ratbert peerURLs=http://10.0.1.20:2380 clientURLs=http://10.0.1.20:2379
```
```
core@dilbert ~ $ etcdctl set /some/data
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

I have dropped full logs here: http://www.burntsheep.com/logs.tgz

**Comment by xiang90** [comment]
@hyperbolic2346 I looked through your log. 

> I have a machine that is unhealthy and is causing other machines to be unable to publish data to etcd.

This is incorrect. Other machines still happily process requests. The request rate is stable at 1K writes requests/minute.

Only the unhealthy one stops to process requests. 

From what I can tell, there is a network issue stops the leader talking to the unhealthy machine.

**Comment by hyperbolic2346** [comment]
I'm only saying it is unhealthy because etcdctl says that 3a752bcccdefffe9 is unhealthy. I am also unable to write from mutliple machines at this point:
```
core@catbert ~ $ etcdctl --debug set /data/bob 1
Cluster-Endpoints: http://10.0.1.19:2379, http://10.0.1.20:2379, http://10.0.1.21:2379, http://10.0.1.22:2379, http://10.0.1.23:2379
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```
```
core@dilbert ~ $ etcdctl --debug set /data/bob 1
Cluster-Endpoints: http://10.0.1.19:2379, http://10.0.1.20:2379, http://10.0.1.21:2379, http://10.0.1.22:2379, http://10.0.1.23:2379
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Curl-Example: curl -X PUT http://10.0.1.19:2379/v2/keys/data/bob -d value=1
Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```
From that debug output I guess my problem is that each machine tries to talk to the first machine in the cluster and that is the one that I'm having trouble with.

I don't see how it could be a networking issue as all of these machines are sitting in the same rack on the same switch and can ping/ssh/etc without trouble.

**Comment by xiang90** [comment]
@hyperbolic2346 Take a look at the debug line: they all tried to write to the same unhealthy one.

**Comment by hyperbolic2346** [comment]
@xiang90 I totally see that and I wouldn't expect it. Is this a bug in etcdctl that it doesn't try other machines in the cluster?

I still have the issue of machine 3a752bcccdefffe9 being marked as unhealthy. Any suggestions on how to get it back? My only course of action would be to remove it from the cluster, nuke /var/lib/etcd2/* and add it back. If this is a networking issue though that won't fix it.

**Comment by xiang90** [comment]
@hyperbolic2346 

I think there is a "bug" in etcdctl. 

> Any suggestions on how to get it back?

I think there is a network issue or a misconfiguration. You need to fix that. If you cannot fix it. Then you have to stop the unhealthy member and remove it.

**Comment by hyperbolic2346** [comment]
@xiang90 I'm able to reach the leader without issue from the unhealthy machine:
```
core@catbert ~ $  curl -X GET http://10.0.1.23:2379/v2/keys/data/bob
{"action":"get","node":{"key":"/data/bob","value":"1","modifiedIndex":5653898,"createdIndex":5653898}}
```
I'm not sure why it is unable to communicate with the leader, but it is timing out. 10.0.1.23 is one of my faster machines as well, so I don't get how it could be a latency issue
```
core@catbert ~ $ ping 10.0.1.23
PING 10.0.1.23 (10.0.1.23) 56(84) bytes of data.
64 bytes from 10.0.1.23: icmp_seq=1 ttl=64 time=0.122 ms
64 bytes from 10.0.1.23: icmp_seq=2 ttl=64 time=0.145 ms
64 bytes from 10.0.1.23: icmp_seq=3 ttl=64 time=0.081 ms
^C
--- 10.0.1.23 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 0.081/0.116/0.145/0.026 ms
```

**Comment by xiang90** [comment]
@hyperbolic2346 From the log, I found this member has never been able to talk with the leader. So I highly suspect there was a misconfiguration.

**Comment by xiang90** [comment]
@hyperbolic2346 Which version of etcd are you running?

**Comment by hyperbolic2346** [comment]
2.0.10 currently

**Comment by xiang90** [comment]
@hyperbolic2346 

The server port is 2380. I do not know why xx:19 always fails to connect xx:23. (:23 is able to connect :19 though, since it can send snapshot successfully to :19).

@yichengq Can you take a look? Any potential bug in rafthttp?

**Comment by hyperbolic2346** [comment]
@xiang90 Thanks for the help so far. I'm having trouble getting this machine added back into the cluster now. Do you see something wrong with my config here?
```
core@catbert ~ $ sudo /usr/bin/etcd2 --name 'catbert' --listen-peer-urls 'http://10.0.1.19:2380,http://10.0.1.19:7001' --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --initial-advertise-peer-urls 'http://10.0.1.19:2380,http://10.0.1.19:7001' --initial-cluster 'dilbert=http://10.0.1.23:2380,wally=http://10.0.1.21:2380,dogbert=http://10.0.1.22:2380,ratbert=http://10.0.1.20:2380,catbert=http://10.0.1.19:2380' --initial-cluster-state 'existing' --advertise-client-urls 'http://10.0.1.19:2379,http://10.0.1.19:4001'
2015/06/05 02:48:06 etcd: no data-dir provided, using default data-dir ./catbert.etcd
2015/06/05 02:48:06 etcd: listening for peers on http://10.0.1.19:2380
2015/06/05 02:48:06 etcd: listening for peers on http://10.0.1.19:7001
2015/06/05 02:48:06 etcd: listening for client requests on http://0.0.0.0:2379
2015/06/05 02:48:06 etcd: listening for client requests on http://0.0.0.0:4001
2015/06/05 02:48:06 etcdserver: datadir is valid for the 2.0.1 format
2015/06/05 02:48:06 etcdserver: name = catbert
2015/06/05 02:48:06 etcdserver: data dir = catbert.etcd
2015/06/05 02:48:06 etcdserver: member dir = catbert.etcd/member
2015/06/05 02:48:06 etcdserver: heartbeat = 100ms
2015/06/05 02:48:06 etcdserver: election = 1000ms
2015/06/05 02:48:06 etcdserver: snapshot count = 10000
2015/06/05 02:48:06 etcdserver: advertise client URLs = http://10.0.1.19:2379,http://10.0.1.19:4001
2015/06/05 02:48:06 etcdserver: start member ef68f0928384f7f2 in cluster 992fd61c39b78ed0
2015/06/05 02:48:06 raft: ef68f0928384f7f2 became follower at term 0
2015/06/05 02:48:06 raft: newRaft ef68f0928384f7f2 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/05 02:48:06 raft: ef68f0928384f7f2 became follower at term 1
2015/06/05 02:48:06 raft: ef68f0928384f7f2 [term: 1] received a MsgHeartbeat message with higher term from 588e7deaa28fd696 [term: 41]
2015/06/05 02:48:06 raft: ef68f0928384f7f2 became follower at term 41
2015/06/05 02:48:06 raft.node: ef68f0928384f7f2 elected leader 588e7deaa28fd696 at term 41
2015/06/05 02:48:08 raft: ef68f0928384f7f2 [commit: 0, lastindex: 0, lastterm: 0] starts to restore snapshot [index: 6592418, term: 41]
2015/06/05 02:48:08 raftlog: log [committed=1, applied=0, unstable.offset=0, len(unstable.Entries)=0] starts to restore snapshot [index: 6592418, term: 41]
2015/06/05 02:48:08 raft: ef68f0928384f7f2 restored progress of 588e7deaa28fd696 [next = 6592419, match = 0, wait = 0]
2015/06/05 02:48:08 raft: ef68f0928384f7f2 restored progress of 6a908ca1696ce9a4 [next = 6592419, match = 0, wait = 0]
2015/06/05 02:48:08 raft: ef68f0928384f7f2 restored progress of bc72cb0ca1efaedb [next = 6592419, match = 0, wait = 0]
2015/06/05 02:48:08 raft: ef68f0928384f7f2 restored progress of d9f8cf11e7fb2acd [next = 6592419, match = 0, wait = 0]
2015/06/05 02:48:08 raft: ef68f0928384f7f2 restored progress of ef68f0928384f7f2 [next = 6592419, match = 6592418, wait = 0]
2015/06/05 02:48:08 raft: ef68f0928384f7f2 [commit: 0] restored snapshot [index: 6592418, term: 41]
2015/06/05 02:48:09 etcdserver: saved incoming snapshot at index 6592418
2015/06/05 02:48:09 rafthttp: starting client stream to 588e7deaa28fd696 at term 41
2015/06/05 02:48:09 etcdserver: recovered from incoming snapshot at index 6592418
2015/06/05 02:48:11 etcdserver: publish error: etcdserver: request timed out
2015/06/05 02:48:14 rafthttp: encountered error reading the client log stream: read tcp 10.0.1.23:2380: i/o timeout
2015/06/05 02:48:14 rafthttp: client streaming to 588e7deaa28fd696 at term 41 has been stopped
2015/06/05 02:48:16 etcdhttp: unexpected error: etcdserver: request timed out
2015/06/05 02:48:16 etcdserver: publish error: etcdserver: request timed out
^C2015/06/05 02:48:17 received interrupt signal, shutting down...
2015/06/05 02:48:17 etcdhttp: unexpected error: etcdserver: server stopped
2015/06/05 02:48:17 etcdserver: aborting publish because server is stopped
```

The i/o timeout is very puzzling to me.

**Comment by xiang90** [comment]
@hyperbolic2346 I looked through the rafthttp code. There is probably a potential "bug" that can cause the issue you just saw. I will dig into that tomorrow.

**Comment by hyperbolic2346** [comment]
@xiang90 Thank you, I appreciate your time and help.

**Comment by yichengq** [comment]
@hyperbolic2346 Do you have the configuration of the initial 5 members in the cluste? have you ever set the -heartbeat-interval and -election-timeout value explicitly?

**Comment by hyperbolic2346** [comment]
I did setup custom values because of the previous trouble I had with etcd I wanted to give my cluster all the chance to survive I could. I actually have this setup on all the members:
```
    discovery: my_url
    advertise-client-urls: http://10.0.1.20:2379
    initial-advertise-peer-urls: http://10.0.1.20:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://10.0.1.20:2380,http://10.0.1.20:7001
    name: ratbert
    heartbeat-interval: 100
    election-timeout: 10000
```

**Comment by xiang90** [comment]
@hyperbolic2346 

We spent quite a well to debug this since the configuration you gave us last time
was
```
core@catbert ~ $ sudo /usr/bin/etcd2 --name 'catbert' --listen-peer-urls 'http://10.0.1.19:2380,http://10.0.1.19:7001' --listen-client-urls 'http://0.0.0.0:2379,http://0.0.0.0:4001' --initial-advertise-peer-urls 'http://10.0.1.19:2380,http://10.0.1.19:7001' --initial-cluster 'dilbert=http://10.0.1.23:2380,wally=http://10.0.1.21:2380,dogbert=http://10.0.1.22:2380,ratbert=http://10.0.1.20:2380,catbert=http://10.0.1.19:2380' --initial-cluster-state 'existing' --advertise-client-urls 'http://10.0.1.19:2379,http://10.0.1.19:4001' --data-dir '/var/lib/etcd2'
```

Please try to give the correct configuration, so it can reduce the latency that we can help you to find out the issue.

The problem here is the default timeout of network layer is 5 second. If the election timeout is larger tha  n that it might cause the problem you have seen. We will try to find a way to "fix" it.

**Comment by hyperbolic2346** [comment]
@xiang90 I apologize, the configuration you saw was how I tried to rejoin the machine to the cluster. How everything was configured is in my last comment. Any suggestion on changes to that would be most welcome.

**Comment by xiang90** [comment]
@hyperbolic2346 You need to reduce the election timeout to 1 second (restart the members one by one with new election timeout configuration). Everything should be fine after that.

**Comment by xiang90** [comment]
@hyperbolic2346 I am closing this due to low activity. Let me know if you still have problems running etcd.

**Comment by hyperbolic2346** [comment]
Sorry I didn't close it or update. I am back going again once I reduced my election timeout.

**Comment by osterman** [comment]
Fwiw, after upgrading to etcd2, most of my etcd issues have gone away. Still minor issues under high server load (more election timeouts), but consensus is reached pretty quickly nonetheless. 
I'm grateful for this thread because I was about to give up on etcd! For others experiencing these issues, I was also using high election timeouts (30 seconds) on etcd v1.x because it was the only way I could get things to work consistently on heavily loaded servers. After upgrading to etcd2, using the high election timeouts had the opposite effect. I could get nothing to work. After bumping it back down to 1 second everything has been stable for the past month.

**Comment by yichengq** [comment]
@osterman Good to know that! We have our own testing etcd cluster running on GCE, and it has run well for less than half year. And we are also improving performance, stability and scalability more to fit bigger requirements. Thanks for companying with us so far! :)
