### ISSUE TITLE
ttl not work

### ISSUE THREAD

**Issue by jiangsongHW** [coreos/etcd#2927]
i use one command to 

1.create a node with ttl=6;
2. sleep 1
3. get this node 

result is this node can not found.can any one tell me why?

test step below:

js@linux-0vmq:~/StreamSMART/local/etcd-v2.0.4-linux-amd64> 
date;curl http://9.96.1.75:4001/v2/keys/test?prevExist=false -XPUT -d value=`date -u +%N` -d ttl=6;sleep 1;curl http://9.96.1.75:4001/v2/keys/test?consistent=true 
Sat Jun  6 17:59:31 CST 2015
{"action":"create","node":{"key":"/test","value":"241035506","expiration":"2015-06-06T09:59:37.245207201Z","ttl":6,"modifiedIndex":65,"createdIndex":65}}
{"errorCode":100,"message":"Key not found","cause":"/test","index":66}

**Comment by jiangsongHW** [comment]
i used three nodes  as a etcd cluster,

and here is etcd server log of one:
2015/06/06 17:12:21 etcdserver: name = e1
2015/06/06 17:12:21 etcdserver: data dir = e1.etcd
2015/06/06 17:12:21 etcdserver: member dir = e1.etcd/member
2015/06/06 17:12:21 etcdserver: heartbeat = 100ms
2015/06/06 17:12:21 etcdserver: election = 1000ms
2015/06/06 17:12:21 etcdserver: snapshot count = 10000
2015/06/06 17:12:21 etcdserver: advertise client URLs = http://9.96.1.75:4001
2015/06/06 17:12:21 etcdserver: initial advertise peer URLs = http://9.96.1.75:7001
2015/06/06 17:12:21 etcdserver: initial cluster = e1=http://9.96.1.75:7001,e2=http://9.96.1.89:7001,e3=http://9.96.1.90:7001
2015/06/06 17:12:21 etcdserver: start member 25e51b213a29bd3 in cluster acd49047cde76195
2015/06/06 17:12:21 raft: 25e51b213a29bd3 became follower at term 0
2015/06/06 17:12:21 raft: newRaft 25e51b213a29bd3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/06 17:12:21 raft: 25e51b213a29bd3 became follower at term 1
2015/06/06 17:12:21 etcdserver: added local member 25e51b213a29bd3 [http://9.96.1.75:7001] to cluster acd49047cde76195
2015/06/06 17:12:21 etcdserver: added member 2be72d7c7a1108ca [http://9.96.1.90:7001] to cluster acd49047cde76195
2015/06/06 17:12:21 etcdserver: added member 9871cd55a42a16a4 [http://9.96.1.89:7001] to cluster acd49047cde76195
2015/06/06 17:12:22 raft: 25e51b213a29bd3 [term: 1] received a MsgVote message with higher term from 2be72d7c7a1108ca [term: 2]
2015/06/06 17:12:22 raft: 25e51b213a29bd3 became follower at term 2
2015/06/06 17:12:22 raft: 25e51b213a29bd3 [logterm: 1, index: 3, vote: 0] voted for 2be72d7c7a1108ca [logterm: 1, index: 3] at term 2
2015/06/06 17:12:22 raft.node: 25e51b213a29bd3 elected leader 2be72d7c7a1108ca at term 2
2015/06/06 17:12:22 rafthttp: starting client stream to 2be72d7c7a1108ca at term 2
2015/06/06 17:12:23 etcdserver: published {Name:e1 ClientURLs:[http://9.96.1.75:4001]} to cluster acd49047cde76195
2015/06/06 17:15:19 rafthttp: encountered error reading the client log stream: unexpected EOF
2015/06/06 17:15:19 rafthttp: client streaming to 2be72d7c7a1108ca at term 2 has been stopped
2015/06/06 17:17:25 no data-dir provided, using default data-dir ./e1.etcd
2015/06/06 17:17:25 etcd: listening for peers on http://9.96.1.75:7001
2015/06/06 17:17:25 etcd: listening for client requests on http://9.96.1.75:4001
2015/06/06 17:17:25 etcdserver: name = e1
2015/06/06 17:17:25 etcdserver: data dir = e1.etcd
2015/06/06 17:17:25 etcdserver: member dir = e1.etcd/member
2015/06/06 17:17:25 etcdserver: heartbeat = 100ms
2015/06/06 17:17:25 etcdserver: election = 1000ms
2015/06/06 17:17:25 etcdserver: snapshot count = 10000
2015/06/06 17:17:25 etcdserver: advertise client URLs = http://9.96.1.75:4001
2015/06/06 17:17:25 etcdserver: initial advertise peer URLs = http://9.96.1.75:7001
2015/06/06 17:17:25 etcdserver: initial cluster = e1=http://9.96.1.75:7001,e2=http://9.96.1.89:7001,e3=http://9.96.1.90:7001
2015/06/06 17:17:25 etcdserver: start member 25e51b213a29bd3 in cluster acd49047cde76195
2015/06/06 17:17:25 raft: 25e51b213a29bd3 became follower at term 0
2015/06/06 17:17:25 raft: newRaft 25e51b213a29bd3 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2015/06/06 17:17:25 raft: 25e51b213a29bd3 became follower at term 1
2015/06/06 17:17:25 etcdserver: added local member 25e51b213a29bd3 [http://9.96.1.75:7001] to cluster acd49047cde76195
2015/06/06 17:17:25 etcdserver: added member 2be72d7c7a1108ca [http://9.96.1.90:7001] to cluster acd49047cde76195
2015/06/06 17:17:25 etcdserver: added member 9871cd55a42a16a4 [http://9.96.1.89:7001] to cluster acd49047cde76195
2015/06/06 17:17:26 raft: 25e51b213a29bd3 [term: 1] received a MsgVote message with higher term from 2be72d7c7a1108ca [term: 2]
2015/06/06 17:17:26 raft: 25e51b213a29bd3 became follower at term 2
2015/06/06 17:17:26 raft: 25e51b213a29bd3 [logterm: 1, index: 3, vote: 0] voted for 2be72d7c7a1108ca [logterm: 1, index: 3] at term 2
2015/06/06 17:17:26 raft.node: 25e51b213a29bd3 elected leader 2be72d7c7a1108ca at term 2
2015/06/06 17:17:26 rafthttp: starting client stream to 2be72d7c7a1108ca at term 2
2015/06/06 17:17:26 etcdserver: published {Name:e1 ClientURLs:[http://9.96.1.75:4001]} to cluster acd49047cde76195
2015/06/06 17:18:03 sender: error posting to 2be72d7c7a1108ca: read tcp 9.96.1.90:7001: connection reset by peer
2015/06/06 17:18:03 sender: the connection with 2be72d7c7a1108ca became inactive
2015/06/06 17:18:03 sender: the connection with 2be72d7c7a1108ca became active
2015/06/06 17:19:04 sender: error posting to 2be72d7c7a1108ca: read tcp 9.96.1.90:7001: connection reset by peer
2015/06/06 17:19:04 sender: the connection with 2be72d7c7a1108ca became inactive
2015/06/06 17:19:04 sender: the connection with 2be72d7c7a1108ca became active
2015/06/06 17:19:33 sender: error posting to 2be72d7c7a1108ca: read tcp 9.96.1.90:7001: i/o timeout
2015/06/06 17:19:33 sender: the connection with 2be72d7c7a1108ca became inactive
2015/06/06 17:19:33 sender: the connection with 2be72d7c7a1108ca became active
2015/06/06 17:22:23 sender: error posting to 2be72d7c7a1108ca: read tcp 9.96.1.90:7001: i/o timeout
2015/06/06 17:22:23 sender: the connection with 2be72d7c7a1108ca became inactive
2015/06/06 17:22:23 sender: the connection with 2be72d7c7a1108ca became active
2015/06/06 17:22:49 sender: error posting to 2be72d7c7a1108ca: read tcp 9.96.1.90:7001: i/o timeout
2015/06/06 17:22:49 sender: the connection with 2be72d7c7a1108ca became inactive
2015/06/06 17:22:49 sender: the connection with 2be72d7c7a1108ca became active
2015/06/06 17:24:29 sender: error posting to 2be72d7c7a1108ca: EOF

**Comment by xiang90** [comment]
@jiangsongHW Are times on the three machines synced at second level?

**Comment by xiang90** [comment]
@jiangsongHW The timeout operation was started by 2be72d7c7a1108ca [http://9.96.1.90:7001] in your case. Check the time difference between that member and 9.96.1.75.

**Comment by jiangsongHW** [comment]
@xiang90 1. yes time is not synced.   2.  how you found out the timeout operation was started by 2be72d7c7a1108ca ? from this "error posting to 2be72d7c7a1108ca: read tcp 9.96.1.90:7001" ??
thank you !

**Comment by xiang90** [comment]
@jiangsongHW It was started by the leader. And your leader is 2be72d7c7a1108ca.
