### ISSUE TITLE
safety feature for protecting against faulty clients resulting 'too many open files'

### ISSUE THREAD

**Issue by difro** [coreos/etcd#2928]
My 8-node etcd cluster started dying one by one with logs like this.
```
2015/06/06 21:52:41 sender: error posting to 6b7bf4d1bfed0b88: dial tcp: lookup machine1 on 10.22.64.7:53: dial udp 10.22.64.7:53: too many open files
2015/06/06 21:52:41 sender: the connection with 6b7bf4d1bfed0b88 became inactive
2015/06/06 21:52:41 etcdserver: failed to purge wal file open /etcd-data/member/wal: too many open files
```

After re-starting the cluster, I found out that it was one of the clients that were not closing the tcp sessions. Doing a netstat on one of the client machines, shows some hundred lines of these.
```
tcp        0      0 10.20.81.228:46329          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:34365          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:44023          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:44853          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:46100          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:55834          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:49015          10.118.104.37:2379          ESTABLISHED -                   
tcp        0      0 10.20.81.228:44655          10.118.104.37:2379          ESTABLISHED 
```

My question is,
Is there any way that I can setup etcd servers to protect against these faulty clients using up all my fd's?  Maybe set a shorter timeout for established TCP sessions? Set a limit per ip?

**Comment by philips** [comment]
Now that we have an authorization API one thing we can do is limit the number of connections a single client can make (thoughts @barakmich?). We also intend to reserve fds in the future (https://github.com/coreos/etcd/issues/2477#issuecomment-87766974).

**Comment by philips** [comment]
Help on either of these ideas would be appreciated @difro

**Comment by difro** [comment]
ok. I still have the faulty client binary lying around here, so maybe I can test new stuff ?

**Comment by yichengq** [comment]
etcd stop accepting client conns when it reaches pre-set limit and leaves enough fds for internal usage now. See https://github.com/coreos/etcd/pull/3219 for more details.

You are welcome to test this with your client binary. I have tested it with amounts of clients at the same time and it works fine. :)
