### ISSUE TITLE
always start a new election when system is under heavy IO

### ISSUE THREAD

**Issue by pacasrc** [coreos/etcd#2929]
Hi All,

I found that etcd always start a new election when system encountering heavy I/O.

etcdctl version 2.0.9
two etcd node on one host(1 sata disk)

1. heavy write:
> dd if=/dev/zero of=qoo bs=1G count=5 &
> dd if=/dev/zero of=qoo2 bs=1G count=5 &

2. etcd start election, can not read/write etcd anymore until election finished:
==> /var/log/upstart/etcd_0.log <==
2015/06/08 11:40:25 raft: 513ce2d0b3493116 is starting a new election at term 2
2015/06/08 11:40:25 raft: 513ce2d0b3493116 became candidate at term 3
2015/06/08 11:40:25 raft: 513ce2d0b3493116 received vote from 513ce2d0b3493116 at term 3
2015/06/08 11:40:25 raft: 513ce2d0b3493116 [logterm: 2, index: 143] sent vote request to d126df603320d99f at term 3
2015/06/08 11:40:25 raft.node: 513ce2d0b3493116 lost leader d126df603320d99f at term 3

==> /var/log/upstart/etcd_0.log <==
2015/06/08 11:40:27 raft: 513ce2d0b3493116 [term: 3] ignored a MsgApp message with lower term from d126df603320d99f [term: 2]
2015/06/08 11:40:27 raft: 513ce2d0b3493116 [term: 3] ignored a MsgHeartbeat message with lower term from d126df603320d99f [term: 2]

==> /var/log/upstart/etcd.log <==
2015/06/08 11:40:28 raft: d126df603320d99f [term: 2] received a MsgVote message with higher term from 513ce2d0b3493116 [term: 3]
2015/06/08 11:40:28 raft: d126df603320d99f became follower at term 3
2015/06/08 11:40:28 raft: d126df603320d99f [logterm: 2, index: 145, vote: 0] rejected vote from 513ce2d0b3493116 [logterm: 2, index: 143] at term 3
2015/06/08 11:40:28 raft.node: d126df603320d99f lost leader d126df603320d99f at term 3

==> /var/log/upstart/etcd_0.log <==
2015/06/08 11:40:28 rafthttp: encountered error reading the client log stream: read tcp 192.168.11.226:2380: use of closed network connection
2015/06/08 11:40:28 rafthttp: client streaming to d126df603320d99f at term 2 has been stopped

==> /var/log/upstart/etcd_0.log <==
2015/06/08 11:40:29 raft: 513ce2d0b3493116 is starting a new election at term 3
2015/06/08 11:40:29 raft: 513ce2d0b3493116 became candidate at term 4
2015/06/08 11:40:29 raft: 513ce2d0b3493116 received vote from 513ce2d0b3493116 at term 4
2015/06/08 11:40:29 raft: 513ce2d0b3493116 [logterm: 2, index: 143] sent vote request to d126df603320d99f at term 4
2015/06/08 11:40:29 raft: 513ce2d0b3493116 [term: 4] ignored a MsgHeartbeat message with lower term from d126df603320d99f [term: 2]

Can I adjust the etcd IO timeout to mitigate this syndrome?
Thanks.

**Comment by philips** [comment]
@pacasrc You can increase the heartbeat interval and election timeouts on all of the members in the cluster. Or you can tell the other applications to consume less disk i/o via cgroups. Or you can put etcd on a different disks or if you can rely on your system members to be in different failure domains tmpfs.

**Comment by yichengq** [comment]
etcd needs to persist data, so it can recover it fully when restart.
@pacasrc Does philips's suggestion help?

**Comment by pacasrc** [comment]
Hi philips, yichengq,

yes, the answer is helpful.
Finally, I choose 'cfq' io scheduler, and set realtime ionice to etcd process
to prevent etcd-write fail.

Thanks.

**Comment by xiang90** [comment]
@pacasrc I am glad you figured it out! Thanks for reporting!

**Comment by ssergiienko** [comment]
Inspired by this ticket and my slow setup: https://github.com/coreos/etcd/issues/6555  :)
