### ISSUE TITLE
Documentation Suggestions

### ISSUE THREAD

**Issue by ecnahc515** [coreos/etcd#2932]
The `runtime-reconfiguration` doc is well named, but also not what I would look for when I was trying to find how to add/remove members from an existing cluster. It would probably be helpful to name it `node-membership-management.md` or something similar.

Given that one of the largest sources of errors we see is in misconfiguration, the configuration documentation could use more attention. A lot of flags come in "pairs". An example is the `-listen-client-urls` and the `-advertise-client-urls` flags, I think it would be good to group these together, and specifically mention which flags should be updated together (it's very common for someone to change one flag, and not realize they need to update another now).

A troubleshooting doc page would be really good too. Demonstrating common problems with the typical deployment, or how to debug problems. Examples: Querying the `stats` API to determine if there's a latency problem. A very common problem that some people still don't know of is reusing a discovery url, it would be simple to have an FAQ of errors and common reasons these errors occur.

Finally, we really need a dedicated docs page for etcd, but it sounds like that's in the works already.

@robszumski

**Comment by xiang90** [comment]
> The runtime-reconfiguration doc is well named, but also not what I would look for when I was trying to find how to add/remove members from an existing cluster. It would probably be helpful to name it node-membership-management.md or something similar.

I think the naming is good. The real problem is we should link to that doc more enough and tell people bootstrap and reconfiguration are quite different. We have improved that a lot.

> Given that one of the largest sources of errors we see is in misconfiguration, the configuration documentation could use more attention. 

Agree.

> A troubleshooting doc page would be really good too. 

Working on this.

**Comment by xiang90** [comment]
@ecnahc515 The second issue is resolved. We are working on the 3rd one on https://github.com/coreos/etcd/pull/3354. It is just a starter. We will add more faq and troubleshooting stuff there. I think we can close this issue now.

**Comment by ecnahc515** [comment]
@xiang90 sounds good.
