### ISSUE TITLE
etcd fails to connect after update from CoreOS 647.2.0 to 681.0.0: "transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field" and "[vote] Error: nil response"

### ISSUE THREAD

**Issue by devurandom** [coreos/etcd#2945]
After updating CoreOS from 647.2.0 (last stable) to 681.0.0 (current stable) I have the same issue as in #884 - etcd fails to start.

The leader outputs:
```
transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
```

While everyone else outputs:
```
[vote] Error: nil response
```

Apparently the update screwed something up big time:
```
$ etcdctl member list
unexpected status code 404
core@localhost ~ $ etcdctl cluster-health
cluster is unhealthy
```

As @fleiner also mentioned in https://github.com/coreos/etcd/issues/884#issuecomment-48556633, `sudo find / -name standby_info` finds no standby_info file at all in the entire system, so the proposed workaround cannot be executed.

etcd seems to be a version 2.0.10:
```
$ etcdctl -v
etcdctl version 2.0.10
```

**Comment by devurandom** [comment]
Luckily this system was not yet used in production, so I ran `rm -fr /var/lib/etcd/*` as recommended somewhere. Afterwards etcd started up without abovementioned issues, but still appears to be broken in some way:
```
$ etcdctl member list
unexpected status code 404
core@localhost ~ $ etcdctl cluster-health
cluster is healthy
member 1ca8450… is healthy
member 5f83387f… is healthy
member 8eb9530c… is healthy
member efdda47ca… is healthy
```

**Comment by xiang90** [comment]
@devurandom member cmd only works on etcd2. There is a bug in the previous etcd 0.4.x. I suggest you to upgrade your cluster to etcd2 if you can.

**Comment by devurandom** [comment]
Works.
