### ISSUE TITLE
advertise-client-urls required in proxy mode?

### ISSUE THREAD

**Issue by JoeOrtiz** [coreos/etcd#2947]
In the proxy documentation it mentions it just requires -listen-client-urls, this worked fine on 2.0.10 , now seems beta in AWS is set to 2.0.11 , which breaks many of our configs that are missing advertise-client-urls in the cloud-config setup for proxy boxes.

Is advertise-client-urls really required in proxy mode?

**Comment by yichengq** [comment]
@JoeOrtiz Could you share the commands to run for your problem?

**Comment by yichengq** [comment]
I think you run the command `bin/etcd -name proxy1 -proxy=on -listen-client-urls http://localhost:8080 -initial-cluster 'infra1=http://localhost:7001,infra2=http://localhost:7002,infra3=http://localhost:7003'`, and it fails, right?

It is a bug that needs to be fixed. proxy doesn't require advertise-client-urls to be set.

**Comment by JoeOrtiz** [comment]
Yeah:

Cloud-Config setup like so:

  etcd2:
      listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
      initial-cluster: infra:xxx:xxx....
      proxy: on

Kinda curious if we can keep the CoreOS Beta release from promoting etcd 2.0.10 ? heh

**Comment by yichengq** [comment]
@JoeOrtiz idk. We plan to cut a stable release next week, which includes this fix.
