### ISSUE TITLE
TestPurgeFileHoldingLock fails

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#2969]
--- FAIL: TestPurgeFileHoldingLock-4 (0.02s)
	purge_test.go:123: filenames = [5.test 6.test 7.test 8.test 9.test], want [7.test 8.test 9.test]
FAIL
coverage: 80.3% of statements
FAIL	github.com/coreos/etcd/pkg/fileutil	0.147s

**Comment by xiang90** [comment]
@yichengq We probably need to make it wait longer...
