### ISSUE TITLE
Raft docs code sample seems stale

### ISSUE THREAD

**Issue by cespare** [coreos/etcd#2971]
In the top-level doc comment [here](https://github.com/coreos/etcd/blob/ea3c7d1d31de2a0109c7a2c8a4be5d778dbb6b0a/raft/doc.go#L23):

```
n := raft.StartNode(0x01, []raft.Peer{{ID: 0x02}, {ID: 0x03}}, 3, 1, storage)
```

That doesn't match the `raft.StartNode` signature. Perhaps it should be something like this (I'm just guessing at what those parameters are):

```
config := &raft.Config{
	ID:            0x01,
	ElectionTick:  3,
	HeartbeatTick: 1,
	Storage:       storage,
}
n := raft.StartNode(config, []raft.Peer{{ID: 0x02}, {ID: 0x03}})
```

**Comment by xiang90** [comment]
I will update the doc soon. Thanks for point it out.
