### ISSUE TITLE
create a connectivity checker

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#2980]
We want to detect any connectivity between each etcd members.

An idea is to have each member ping all other members' peerURL periodically (O(10second)) and generate a connectivity table. 

This helps #1440 and detect any other potential connectivity problem.

**Comment by yichengq** [comment]
I can foresee that the info can become a nice graph to indicate the connectivity in the cluster.

Maybe it could also rely on some external network monitor package to report all details, including network  latency and drop package rate.

**Comment by xiang90** [comment]
@yichengq We should start with something really simple.

**Comment by xiang90** [comment]
Additional thought: contain timestamp in the ping message and detect absolute out of time sync members (>3second or more).

**Comment by xiang90** [comment]
Here is a pkg I just created: https://github.com/xiang90/probing

We would like to use it to let one peer probe every other peer periodically and print out warning/debug information when necessary. 

For example:
Warning:
clockdiff > second 
2 out of 3 peers are unhealthy
SRTT > heartbeat interval

Debug
1 out of 3 peers is unhealthy
