### ISSUE TITLE
Very long read / write times when one of the members are unhealthy

### ISSUE THREAD

**Issue by mariusgrigaitis** [coreos/etcd#2984]
```
admin@ip-172-27-0-152:~$ time etcdctl get /a
b

real	0m9.104s
user	0m0.004s
sys	0m0.000s
admin@ip-172-27-0-152:~$ time etcdctl set /a "foo"
foo

real	0m8.309s
user	0m0.004s
sys	0m0.000s
```
I expect it to be faster.

**Comment by xiang90** [comment]
@mariusgrigaitis etcdctl will try to sync members and then do the actual get. If one member is stuck (due to hard stop), it has to wait for a timeout. In the future, we will make that timeout configurable in etcdctl. Now it is several seconds.

**Comment by mariusgrigaitis** [comment]
Can etcdctl only sync majority of nodes and don't wait for unhealthy nodes?

**Comment by yichengq** [comment]
@mariusgrigaitis etcdctl sends request to etcd member one by one, so it may wait some time for halted member.

it cannot send requests to all members. If it sends requests to all members at the same time, all requests need to be replicated and go through quorum in the cluster, which introduces big overhead to the cluster.

**Comment by xiang90** [comment]
This is duplicated with https://github.com/coreos/etcd/issues/1515. We will solve this issue in 2.2 release.
