### ISSUE TITLE
Automatically testing tolerances to node failures

### ISSUE THREAD

**Issue by mariusgrigaitis** [coreos/etcd#2985]
We've found issues #2984 #2983 #2838 regarding tolerance to node failures / shut-downs.

I think it would be great if etcd could do some jespen testing (like consul https://www.consul.io/docs/internals/jepsen.html) or chaos monkey (https://github.com/Netflix/SimianArmy/wiki/Chaos-Monkey) to test such issues automatically?

**Comment by xiang90** [comment]
@mariusgrigaitis 

We are doing more harsh testing continuously. See https://coreos.com/blog/new-functional-testing-in-etcd/. 

We have been fixing issues in 2.1 branch. We refactor the transportation layer a lot and had hard time to back port it back to 2.0 branch. 

Some "bugs" you found are related to etcdctl, not etcd server itself. 

Thanks for your reporting. We treat testing very seriously.
