### ISSUE TITLE
Question: Recommended storage limits

### ISSUE THREAD

**Issue by jpillora** [coreos/etcd#2992]
I couldn't find anything on this other than [this comment](https://github.com/coreos/etcd/issues/1548#issuecomment-61316755) saying there are no enforced limits. Given there are no set limits, what is the *recommended* value size limit, maximum number of keys and overall database limit? Like most, I use etcd for configuration, which is currently less than 10KB. How would etcd deal with 1K keys totalling 1MB? 1M keys at 1GB?

**Comment by yichengq** [comment]
The recommended value size is < 1MB. As @xiang90 says, etcd targets at 'a consistent data store that serves small value', so we don't expect users will put large value into etcd.

the overall database limit is < 25MB. This is restricted by memory usage overhead(#2662, #2657) and slow snapshot recovery now. We are working hard at https://github.com/coreos/etcd/issues/2647 to improve this.

**Comment by jpillora** [comment]
Thanks for the info @yichengq and keep up the good work :+1:

**Comment by jmdots** [comment]
@yichengq 

What are "recommended value size" and "overall database limit" for etcdv3 current release (v3.1.1)?

Please let me know if I should open a new issue for this.

**Comment by HYmian** [comment]
> What are "recommended value size" and "overall database limit" for etcdv3 current release (v3.1.1)?

I want to know this too

**Comment by jpbetz** [comment]
> > What are "recommended value size" and "overall database limit" for etcdv3 current release (v3.1.1)?
> 
> I want to know this too

https://coreos.com/etcd/docs/latest/dev-guide/limit.html
