### ISSUE TITLE
Cannot connect to the cluster

### ISSUE THREAD

**Issue by gridpocketuser** [coreos/etcd#2995]
Hello,

I've installed CoreOS 681.0.0 on 2 machines (bare metal).

The cloud-config file used for node1 machine (only the IPs and the hosname are changed for the other one):

    #cloud-config
    #
    # Set hostname
    hostname: node1

    # Set ssh key
    ssh_authorized_keys:
    - ssh-rsa KEY
    coreos:
      etcd:
        name: node1
        discovery: https://discovery.etcd.io/TOKEN
        addr: 192.168.1.7:4001
        peer-addr: 192.168.1.7:7001
      fleet:
        public-ip: 192.168.1.7
      units:
        - name: etcd.service
          command: start
        - name: fleet.service
          command: start

I can log to the machine and issue some basic commands without problem
    - etcdctl ls / --recursive
    - fleetctl list-machines

When I boot the second machine, those commands give an error message:

    etcdctl ls / --recursive
    Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379

    fleetctl list-machines
    Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd    

Any idea what can be wrong ?
Thanks a lot

**UPDATE**

Seems like etcd has not started on boot.

    $ sudo systemctl status etcd
    ● etcd.service - etcd
       Loaded: loaded (/usr/lib64/systemd/system/etcd.service; static; vendor preset: disabled)
      Drop-In: /run/systemd/system/etcd.service.d
               └─20-cloudinit.conf
       Active: activating (auto-restart) (Result: exit-code) since Wed 2015-06-17 11:29:05 ; 8s ago
      Process: 746 ExecStart=/usr/bin/etcd (code=exited, status=1/FAILURE)
     Main PID: 746 (code=exited, status=1/FAILURE)

    Jun 17 11:29:05 node2 systemd[1]: Unit etcd.service entered failed state.
    Jun 17 11:29:05 node2 systemd[1]: etcd.service failed.

    $ journalctl -u etcd

    Jun 17 11:34:28 node2 systemd[1]: Started etcd.
    Jun 17 11:34:28 node2 systemd[1]: Starting etcd...
    Jun 17 11:34:28 node2 etcd[1028]: [etcd] Jun 17 11:34:28.099 INFO      | Discovery via https://discovery.etcd.io using prefix /15e12f4ce6d2972b198e3274f0d19f6e.
    Jun 17 11:34:30 node2 etcd[1028]: [etcd] Jun 17 11:34:30.500 WARNING   | Discovery encountered an error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
    Jun 17 11:34:30 node2 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
    Jun 17 11:34:30 node2 systemd[1]: Unit etcd.service entered failed state.
    Jun 17 11:34:30 node2 systemd[1]: etcd.service failed.

**Comment by yichengq** [comment]
I didn't see any machine registered in discovery service(http://discovery.etcd.io/15e12f4ce6d2972b198e3274f0d19f6e), and that might be the reason. What I expect to see is that the first machine has been registered in discovery token.

Could you remove the etcd data dir and start from the beginning? You need to use a new discovery token.

Moreover, it is more recommended to move to etcd2 service.

**Comment by gridpocketuser** [comment]
I've tested with several token but it was the same thing: first machine ok, second one ko. I noticed a quite important latency on the second machine (even when issuing a ping "google.com"), could this be a network pb then ?
Regarding etcd2, is it shipped with CoreOS 681.0.0 ?
Thanks for your help.

**Comment by yichengq** [comment]
@gridpocketuser If the machine cannot connect to the discovery service, it cannot use discovery service to bootstrap itself.

Yes, it is in coreos 681.0.0. You could check the details here: https://coreos.com/blog/etcd2-in-stable-channel/

In etcd2 world, you could try the https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static bootstrap way, which is explicit and clear.

**Comment by gridpocketuser** [comment]
I changed the cloud-config to use etcd2 and took a new discovery token:

First node (eris)

    #cloud-config
    #
    # Set hotname
    hostname: eris

    # Set ssh key
    ssh_authorized_keys:
    - ssh-rsa KEY
    coreos:
      etcd2:
        discovery: https://discovery.etcd.io/df0ea6475b46a404d65dbce8a37b3024
        advertise-client-urls: http://192.168.1.7:2379
        initial-advertise-peer-urls: http://192.168.1.7:2380
        listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
        listen-peer-urls: http://192.168.1.7:2380,http://192.168.1.7:7001
      fleet:
        public-ip: 192.168.1.7
      units:
        - name: etcd2.service
          command: start
        - name: fleet.service
          command: start

Seems that the connection to etcd was ok:

    sudo systemctl status etcd2
    ● etcd2.service - etcd2
       Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; static; vendor preset: disabled)
      Drop-In: /run/systemd/system/etcd2.service.d
               └─20-cloudinit.conf
       Active: active (running) since Thu 2015-06-18 10:00:45 ; 3min 9s ago
     Main PID: 614 (etcd2)
       Memory: 2.9M
       CGroup: /system.slice/etcd2.service
               └─614 /usr/bin/etcd2

    Jun 18 10:00:45 eris etcd2[614]: 2015/06/18 10:00:45 etcdserver: datadir is valid for the 2.0.1 format
    Jun 18 10:00:47 eris etcd2[614]: 2015/06/18 10:00:47 discovery: found self 8b970da3064fe308 in the cluster
    Jun 18 10:00:47 eris etcd2[614]: 2015/06/18 10:00:47 discovery: found 1 peer(s), waiting for 1 more
    Jun 18 10:01:47 eris etcd2[614]: 2015/06/18 10:01:47 discovery: during waiting for other nodes connection to https://discovery.etcd.io timed out, retrying in 2s
    Jun 18 10:01:49 eris etcd2[614]: 2015/06/18 10:01:49 discovery: found self 8b970da3064fe308 in the cluster
    Jun 18 10:01:49 eris etcd2[614]: 2015/06/18 10:01:49 discovery: found 1 peer(s), waiting for 1 more
    Jun 18 10:02:49 eris etcd2[614]: 2015/06/18 10:02:49 discovery: during waiting for other nodes connection to https://discovery.etcd.io timed out, retrying in 4s
    Jun 18 10:02:53 eris etcd2[614]: 2015/06/18 10:02:53 discovery: found self 8b970da3064fe308 in the     Jun 18 10:02:53 eris etcd2[614]: 2015/06/18 10:02:53 discovery: found 1 peer(s), waiting for 1 more
    Jun 18 10:03:53 eris etcd2[614]: 2015/06/18 10:03:53 discovery: during waiting for other nodes connection to https://discovery.etcd.io timed out, retrying in 8s

Seems to be fine then, but fleet cannot communicate with etcd:

    $ sudo fleetctl list-machines
    Error retrieving list of active machines: googleapi: Error 503: fleet server unable to communicate with etcd

Then second node (ziemia) does not manage to connect to etcd it seems (I've checked the network is find this time).

    $ sudo systemctl status etcd2
    ● etcd2.service - etcd2
       Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; static; vendor preset: disabled)
      Drop-In: /run/systemd/system/etcd2.service.d
               └─20-cloudinit.conf
       Active: active (running) since Thu 2015-06-18 10:02:16 ; 2min 21s ago
     Main PID: 607 (etcd2)
       Memory: 3.4M
       CGroup: /system.slice/etcd2.service
               └─607 /usr/bin/etcd2

    Jun 18 10:04:35 ziemia etcd2[607]: 2015/06/18 10:04:35 raft: 108558ba0e19454f [logterm: 1, index: 2] sent vote request to 283bd17cd2fb34d1 at term 3561
    Jun 18 10:04:36 ziemia etcd2[607]: 2015/06/18 10:04:36 etcdserver: publish error: etcdserver: request timed out
    Jun 18 10:04:36 ziemia etcd2[607]: 2015/06/18 10:04:36 raft: 108558ba0e19454f is starting a new election at term 3561
    Jun 18 10:04:36 ziemia etcd2[607]: 2015/06/18 10:04:36 raft: 108558ba0e19454f became candidate at term 3562
    Jun 18 10:04:36 ziemia etcd2[607]: 2015/06/18 10:04:36 raft: 108558ba0e19454f received vote from 108558ba0e19454f at term 3562
    Jun 18 10:04:36 ziemia etcd2[607]: 2015/06/18 10:04:36 raft: 108558ba0e19454f [logterm: 1, index: 2] sent vote request to 283bd17cd2fb34d1 at term 3562
    Jun 18 10:04:38 ziemia etcd2[607]: 2015/06/18 10:04:38 raft: 108558ba0e19454f is starting a new election at term 3562
    Jun 18 10:04:38 ziemia etcd2[607]: 2015/06/18 10:04:38 raft: 108558ba0e19454f became candidate at term 3563
    Jun 18 10:04:38 ziemia etcd2[607]: 2015/06/18 10:04:38 raft: 108558ba0e19454f received vote from 108558ba0e19454f at term 3563
    Jun 18 10:04:38 ziemia etcd2[607]: 2015/06/18 10:04:38 raft: 108558ba0e19454f [logterm: 1, index: 2] sent vote request to 283bd17cd2fb34d1 at term 3563

    core@ziemia ~ $ sudo etcd ls / --recursive
    [etcd] Jun 18 10:05:08.875 WARNING   | Using the directory ziemia.etcd as the etcd curation directory because a directory was not specified.
    [etcd] Jun 18 10:05:08.876 INFO      | ziemia is starting a new cluster
    [etcd] Jun 18 10:05:08.879 INFO      | etcd server [name ziemia, listen on :4001, advertised url http://127.0.0.1:4001]
    [etcd] Jun 18 10:05:08.879 CRITICAL  | Failed to create listener: listen tcp :4001: bind: address already in use

Anything I missed ?
Thanks a lot for your help.

**Comment by yichengq** [comment]
etcd process and etcd2 service use the same port, so you need to kill the original etcd process. Moreover, the cluster in static bootstrap will not work until all members join the cluster.

**Comment by gridpocketuser** [comment]
I do not run etcd service, in the cloud-config I only run etcd2 on reboot.

How would you do dynamic bootstrap on bare metal so the cluster can work on
a single node ?

**Comment by yichengq** [comment]
@gridpocketuser I misunderstood your last command `sudo etcd ls / --recursive`, you should use `etcdctl`.

If you want to bootstrap a cluster of two members, use a discovery token with size=2. Then the cluster will wait for 2 members ready before serving. If there is still a problem, please share the full command line and log of the etcd processes with us.

**Comment by gridpocketuser** [comment]
I've just deleted the eris.etcd folder and restarted one single machine with a new token (single machine token):

I got the following status for etcd2

    core@eris ~ $ systemctl status etcd2
    ● etcd2.service - etcd2
       Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; static; vendor preset: disabled)
      Drop-In: /run/systemd/system/etcd2.service.d
               └─20-cloudinit.conf
       Active: active (running) since Tue 2015-06-23 12:20:15 ; 6min ago
     Main PID: 613 (etcd2)
       Memory: 9.6M
       CGroup: /system.slice/etcd2.service
               └─613 /usr/bin/etcd2
    Jun 23 12:24:40 eris etcd2[613]: 2015/06/23 12:24:40 rafthttp: request ignored due to cluster ID mismatch got 47501b6c52dad5bb want a4bbec9326f58813
    Jun 23 12:24:52 eris etcd2[613]: 2015/06/23 12:24:52 rafthttp: request ignored due to cluster ID mismatch got 47501b6c52dad5bb want a4bbec9326f58813


The journal gives the following output:

journalctl -u etcd2

    Jun 23 12:20:04 eris systemd[1]: Started etcd2.
    Jun 23 12:20:04 eris systemd[1]: Starting etcd2...
    Jun 23 12:20:05 eris systemd[1]: etcd2.service: main process exited, code=exited, status=1/FAILURE
    Jun 23 12:20:05 eris systemd[1]: Unit etcd2.service entered failed state.
    Jun 23 12:20:05 eris systemd[1]: etcd2.service failed.
    Jun 23 12:20:15 eris systemd[1]: etcd2.service holdoff time over, scheduling restart.
    Jun 23 12:20:15 eris systemd[1]: Started etcd2.
    Jun 23 12:20:15 eris systemd[1]: Starting etcd2...
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcd: already initialized as member before, starting as etcd member...
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcd: listening for peers on http://192.168.1.7:2380
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcd: listening for peers on http://192.168.1.7:7001
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcd: listening for client requests on http://0.0.0.0:2379
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcd: listening for client requests on http://0.0.0.0:4001
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: datadir is valid for the 2.0.1 format
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: discovery token ignored since a cluster has already been initialized. Valid log found at "/var/lib/etcd2/member/wal"
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: recovered store from snapshot at index 850085
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: name = a180a4ac14ec40baae53818361ffbd93
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: data dir = /var/lib/etcd2
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: member dir = /var/lib/etcd2/member
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: heartbeat = 100ms
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: election = 1000ms
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: snapshot count = 10000
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: discovery URL= https://discovery.etcd.io/834977fe58bb7d1b0ecfe21f085b8933
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: advertise client URLs = http://192.168.1.7:2379
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: loaded cluster information from store: a180a4ac14ec40baae53818361ffbd93=http://192.168.1.7:2380
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 etcdserver: restart member ee14edad7cc18509 in cluster a4bbec9326f58813 at commit index 856652
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 raft: ee14edad7cc18509 became follower at term 3
    Jun 23 12:20:15 eris etcd2[613]: 2015/06/23 12:20:15 raft: newRaft ee14edad7cc18509 [peers: [ee14edad7cc18509], term: 3, commit: 856652, applied: 850085, lastindex: 856652, lastterm: 3]
    Jun 23 12:20:16 eris etcd2[613]: 2015/06/23 12:20:16 rafthttp: request ignored due to cluster ID mismatch got 47501b6c52dad5bb want a4bbec9326f58813
    Jun 23 12:20:17 eris etcd2[613]: 2015/06/23 12:20:17 raft: ee14edad7cc18509 is starting a new election at term 3
    Jun 23 12:20:17 eris etcd2[613]: 2015/06/23 12:20:17 raft: ee14edad7cc18509 became candidate at term 4
    Jun 23 12:20:17 eris etcd2[613]: 2015/06/23 12:20:17 raft: ee14edad7cc18509 received vote from ee14edad7cc18509 at term 4
    Jun 23 12:20:17 eris etcd2[613]: 2015/06/23 12:20:17 raft: ee14edad7cc18509 became leader at term 4
    Jun 23 12:20:17 eris etcd2[613]: 2015/06/23 12:20:17 raft.node: ee14edad7cc18509 elected leader ee14edad7cc18509 at term 4
    Jun 23 12:20:17 eris etcd2[613]: 2015/06/23 12:20:17 etcdserver: published {Name:a180a4ac14ec40baae53818361ffbd93 ClientURLs:[http://192.168.1.7:2379]} to cluster a4bbec9326f58813
    Jun 23 12:20:27 eris etcd2[613]: 2015/06/23 12:20:27 rafthttp: request ignored due to cluster ID mismatch got 47501b6c52dad5bb want a4bbec9326f58813
    Jun 23 12:20:39 eris etcd2[613]: 2015/06/23 12:20:39 rafthttp: request ignored due to cluster ID mismatch got 47501b6c52dad5bb want a4bbec9326f58813

no new eris.etcd folder has been created

**Comment by yichengq** [comment]
One discovery token represents one unique etcd cluster, and members in different etcd cluster cannot talk to each other for the sake of data integration in both clusters.

Destroy both nodes and use a discovery token with size=2

**Comment by gridpocketuser** [comment]
I used a new size 2 token and rebooted the machines. Both nodes show the 2 ips through fleet.

    core@eris ~ $ fleetctl list-machines
    MACHINE		IP		METADATA
    a180a4ac...	192.168.1.7	-
    d62acd1d...	192.168.1.6	-

Thanks a lot.

**Comment by sachingharge** [comment]
Hi All,

I am facing similar kind of issues where can not able to see two nodes in cluster using fleetctl list-machines.

Discovery URL: https://discovery.etcd.io/e50179b42721cc640b50b11d5a0604d0

I have used discovery token with size=2 due to two machines.
I can see that both member are listed using etcdctl member list command, please take look below output:
etcdctl member list
776e37ff9ceebba1: name=a098599e8ae7604f85f0a2bf141387a3 peerURLs=http://172.17.2.20:2380,http://172.17.2.21:2380 clientURLs=http://172.17.2.20:2379

However, I can not see the two nodes using fleetctl list-machines command.
leetctl list-machines
MACHINE		IP		METADATA
a098599e...	172.17.2.20	-

Please let me know your inputs on this.
Thanks in advance!

**Comment by yichengq** [comment]
@sachingharge If you can see both members through etcdctl(though i just saw one in your log, but i think you didn't paste all log), this is a fleet issue and should be reported at https://github.com/coreos/fleet. I would suggest you to check fleet log to see what is happening as the first step.

**Comment by itsNikolay** [comment]
`size=2` for 3 digitalocean droples resolved my issue also
ty!
