### ISSUE TITLE
Improved Metrics for Etcd v2

### ISSUE THREAD

**Issue by mwitkow-io** [coreos/etcd#3002]
We've been trying out Etcd V2.1 aplha1 to see whether we actually get good insights into what's going on in the cluster.

The `etcd_server_proposal_durations_milliseconds` is useful to track latency of writes, but we've found that we need to track how our Etcd is used. The use case we have is a set of Core Etcd nodes participating in Raft, and hundreds of Proxies.

https://github.com/coreos/etcd/pull/3001 has a stab that we're taking at it:
 - metrics  from `/stats/store`
 - http (on etcdhttpd) handling metrics
 - proxy handling metrics

**Comment by mwitkow-io** [comment]
@xiang90 would you like me to revisit https://github.com/coreos/etcd/pull/3093 ?

**Comment by xiang90** [comment]
@mwitkow-io Yes. We can do that now. Have you enabled those metrics in you production environment? My primary concern is that we might introduce some unnecessary metrics.

**Comment by mwitkow-io** [comment]
@xiang90, yes, we've been running all of our production clusters with #3093 for 2 months now.. They've been incredibly useful, especially the alerts around the latency of reads and writes.

The latency of writes, especially, has been a good indicator when services depending on etcd (e.g. fleet, or SkyDNS) could start misbehaving (e.g. due to refreshes of TTLs taking a long time).

**Comment by xiang90** [comment]
@mwitkow-io Can you rebase that branch on top of master? Then we can start to review it? Thanks!

**Comment by mwitkow-io** [comment]
Done! I'm really looking forward to this, managing an out of tree patched etcd is a pain and prevents us from being more on the bleeding edge :)

**Comment by xiang90** [comment]
#3093 is merged.
