### ISSUE TITLE
rolling upgrade docs for 2.0.x to 2.1

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3004]

**Comment by xiang90** [comment]
reference: 
http://docs.basho.com/riak/latest/ops/upgrading/rolling-upgrades/
http://docs.mongodb.org/manual/release-notes/2.6-upgrade/

**Comment by yichengq** [comment]
For note: rolling upgrade test is done at here: https://github.com/coreos/mantle/pull/66
