### ISSUE TITLE
wrong watchers number in v2/stats/store [v2.0.0]

### ISSUE THREAD

**Issue by hx8563** [coreos/etcd#3010]
We have a 3-nodes etcd cluster, the "watchers" stat in  v2/stats/store is a very huge number (the real watchers should be less than 10):

curl 127.0.0.1:4001/v2/stats/store
{"getsSuccess":2469202717,"getsFail":1662035,"setsSuccess":412896,"setsFail":0,"deleteSuccess":513,"deleteFail":2,"updateSuccess":1,"updateFail":0,"createSuccess":2,"createFail":0,"compareAndSwapSuccess":0,"compareAndSwapFail":0,"compareAndDeleteSuccess":0,"compareAndDeleteFail":0,"expireCount":18446744073709542424,"watchers":18446744073709551484}

In this case, the watching client cannot get watch event without create a new tcp connection.
Restart any node in cluster can not recover the problem.

**Comment by xiang90** [comment]
@hx8563 This has been solved in current release 2.0.12. Please give it a try.

**Comment by hx8563** [comment]
@xiang90 thank for your quick replay ~

Can you tell me which commit had solved this issue?
