### ISSUE TITLE
discovery not trying forever

### ISSUE THREAD

**Issue by philips** [coreos/etcd#3012]
The code makes it seem like discovery should retry forever but it doesn't in practice. Trying to hunt this one down myself...

```
13:03:00 etcd1 | Starting etcd1 on port 5000
13:03:00 etcd2 | Starting etcd2 on port 5001
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: no data-dir provided, using default data-dir ./infra2.etcd
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: no data-dir provided, using default data-dir ./infra1.etcd
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: listening for peers on http://127.0.0.1:7002
13:03:00 etcd2 | 2015/06/19 13:03:00 etcdmain: listening for client requests on http://127.0.0.1:4002
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: listening for peers on http://127.0.0.1:7001
13:03:00 etcd1 | 2015/06/19 13:03:00 etcdmain: listening for client requests on http://127.0.0.1:4001
13:03:05 etcd2 | 2015/06/19 13:03:05 discovery: duringcluster status checkconnection tohttps://discovery.etcd.iotimed out, retrying in2s
13:03:05 etcd1 | 2015/06/19 13:03:05 discovery: duringcluster status checkconnection tohttps://discovery.etcd.iotimed out, retrying in2s
13:03:15 etcd1 | 2015/06/19 13:03:15 discovery: found self ef911c27b232ea14 in the cluster
13:03:15 etcd1 | 2015/06/19 13:03:15 discovery: found peer 1d1be50d7bc0ab50 in the cluster
13:03:15 etcd1 | 2015/06/19 13:03:15 discovery: found 2 peer(s), waiting for 1 more
13:03:20 etcd2 | 2015/06/19 13:03:20 discovery: found peer ef911c27b232ea14 in the cluster
13:03:20 etcd2 | 2015/06/19 13:03:20 discovery: found self 1d1be50d7bc0ab50 in the cluster
13:03:20 etcd2 | 2015/06/19 13:03:20 discovery: found 2 peer(s), waiting for 1 more
13:04:16 etcd1 | 2015/06/19 13:04:16 etcdmain: stopping listening for client requests on http://127.0.0.1:4001
13:04:16 etcd1 | 2015/06/19 13:04:16 etcdmain: stopping listening for peers on http://127.0.0.1:7001
13:04:16 etcd1 | 2015/06/19 13:04:16 etcdmain: unexpected end of JSON input
13:04:16 etcd1 | Terminating etcd1
13:04:21 etcd2 | 2015/06/19 13:04:21 etcdmain: stopping listening for client requests on http://127.0.0.1:4002
13:04:21 etcd2 | 2015/06/19 13:04:21 etcdmain: stopping listening for peers on http://127.0.0.1:7002
13:04:21 etcd2 | 2015/06/19 13:04:21 etcdmain: unexpected end of JSON input
```

**Comment by yichengq** [comment]
This happens because 1. watch waits on reading response body 2. it gets empty body and nil error as result 3. it fails to unmarshal empty string to json 4. it prints out error and exits

My self deployed discovery service doesn't have this problem, so I guess there is some trick when deploying public discovery service. will talk with @jedsmith when he finishes his firefight.

**Comment by jedsmith** [comment]
I don't know what trick there would be. Public discovery should be identical to any private one. I just logged in to public and had a look and everything seems healthy.

Could this have been an ELB blip or something?

**Comment by yichengq** [comment]
It seems that ELB has some setting about timeout on long-polling connection in this article: https://aws.amazon.com/cn/blogs/aws/elb-idle-timeout-control/ 

When ELB hits the timeout, ELB will close the long-polling connection in normal way. So the client may receive empty body and no error after watch, and fatal when trying to unmarshal empty body.

The easiest way to fix it IMO is to set longer connection timeout in ELB, like 1 hour(is this enough? /cc @philips ). It could be complicated if etcd starts to understand ELB behavior and bypass empty body.

**Comment by blalor** [comment]
I just ran into this, I believe.  I'm trying to bootstrap a cluster with terraform and am unable to because the etcd2 on the first instance dies before the next instance comes up, and the first instance can't reuse the discovery token.

**Comment by yichengq** [comment]
Based on the discussion OOL, adjusting ELB is not ideal and it is better to handle it as a common problem. For reference, the raw response returned from client.simpleHTTPClient.Do in this case is `resp: &{Status:504 GATEWAY_TIMEOUT StatusCode:504 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[0] Connection:[keep-alive]] Body:0x208d25240 ContentLength:0 TransferEncoding:[] Close:false Trailer:map[] Request:0x208bd0a90 TLS:0x208b0c580}, body: , err: <nil>`. 

In cluster error PR(https://github.com/coreos/etcd/pull/3181), we improved the logic to retry discovery on all connection errors returned from client call. That is the good solution for this.

The left part is that the log today is not accurate. I will send the PR to fix it.
