### ISSUE TITLE
ETCD v2.0.12

### ISSUE THREAD

**Issue by Richard-FogCreek** [coreos/etcd#3013]
The systems I am using are part of an automated build system.  As such we need to clean build systems through automation totally hands off.  For a cluster this means automating the removal of an old system and adding a new one in it's place.  All while the cluster is healthy.

The initial cluster is built using "random" node names and discovered through the discovery service. https://discovery.etcd.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

The cluster is functional and healthy.  

Now comes the rebuild of one of the cluster with Member ID yyyyyyyyyyyyyyyy

1. etcdctl member remove yyyyyyyyyyyyyyyy
2. curl -X DELETE https://discovery.etcd.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/yyyyyyyyyyyyyyyy

Now the system of yyyyyyyyyyyyyyyy is decommissioned, data shredded etc. (automated)

Then a new system comes online, new IP and fired up with the following options

      -name NEW_RANDOM_NAME
      -discovery https://discovery.etcd.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      -initial-advertise-peer-urls http://NEW_IP:2379
      -advertise-client-urls http://NEW_IP:2380
      -listen-peer-urls http://0.0.0.0:2379
      -listen-client-urls http://0.0.0.0:2380
      -data-dir /etcd_data

A new Member ID of zzzzzzzzzzzzzzzz is created by etcd and the node is successfully registered in https://discovery.etcd.io/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/zzzzzzzzzzzzzzzz

However, the unchanged cluster members who are still healthy do not show the new membership, and the new Node complains of a bad cluster ID (ie the new node has not started with the old cluster ID discovered from the existing nodes, it has created a new cluster ID).

    2015/06/19 19:34:19 etcdserver: conflicting cluster ID with the target cluster (d7396c11b1fd7454 != 2a6268cf187dc9db)
    2015/06/19 19:34:19 etcdserver: the data-dir used by this member must be removed.

The ideal behavior would be to have the new member add to the cluster and bring the membership back up to the full rank as defined in the discovery setup.

Please advise as we are now running on a degraded cluster, and we need this to be automated as we do rolling upgrades and re-provisioning.

**Comment by xiang90** [comment]
@Richard-FogCreek 

Discovery service is only used for initial bootstrap. After that, it is the users' responsibility to control the cluster configuration.

For runtime reconfiguration, you can follow the doc https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md.

**Comment by yichengq** [comment]
@Richard-FogCreek Have you tried the runtime reconfiguration way that @xiang90 suggests?

**Comment by xiang90** [comment]
@Richard-FogCreek I am closing this due to low activity. Reopen if you still have the same issue. Thanks for reporting!

**Comment by Richard-FogCreek** [comment]
Basically there is a need for a trusted resilient source of data to build a machine from.  Right now I'm using the discovery service as an authoritative list of membership to go an "integrate" with.

Rebuilding cluster members (with full disk wipes - a reality of EC2 environments) drives a need for autonomous membership management.

Given the feedback received I've written a python program to manage cluster and discovery records for now.  It would be much better to have a supportable solution as I'm not sure this is supportable for us beyond the short term.
