### ISSUE TITLE
advertise-client-urls has to be set if listen-client-urls is set when fallback to proxy

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3018]
The behavior today:

```
$ etcd --listen-client-urls http://10.0.0.1:2379 -discovery xxx (-discovery-fallback proxy)
```

will fail anyway, regardless of whether discovery service is full:

```
2015/06/19 14:08:03 etcdmain: error verifying flags, -advertise-client-urls is required when -listen-client-urls is set explicitly. See 'etcd --help'.
2015/06/19 14:08:03 etcdmain: When listening on specific address(es), this etcd process must advertise accessible url(s) to each connected client.
```

This command will not fail at 2.0.10

@xiang90 points out that etcd should not fail due to unset advertise-client-urls if the discovery service is full and etcd falls back to proxy.

/cc @crawford This may be a regression, please check.

**Comment by crawford** [comment]
@yichengq please check what?

**Comment by yichengq** [comment]
@crawford Whether this is a regression for coreos.

**Comment by crawford** [comment]
@yichengq Umm, no? You tell me if it's a regression and I will help you get a fix into the OS.

**Comment by yichengq** [comment]
@crawford It is an etcd regression. And this will be fixed in next stable release.

**Comment by crawford** [comment]
@yichengq what version do you want me to ship in Stable? I don't understand which version is correct and which one introduced the regression.

**Comment by yichengq** [comment]
@crawford 2.0.10 doesn't have this problem, and 2.0.11 and 2.0.12 has this problem.

**Comment by xiang90** [comment]
@yichengq To be more clear, 2.0.11 introduces the regression issues.
2.0.12 fixed the majority of the regression issue. We still need to fix another part.

**Comment by crawford** [comment]
@yichengq ok. 2.0.10 is currently in Stable. I will keep Beta on 2.0.10 and wait for a 2.0.13 for Alpha.
