### ISSUE TITLE
default name should be (random)etcd.default?

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3025]
Discovery service requires a unique name. We probably can generate random default name to make discovery configuration even more simpler. 

/cc @philips @kelseyhightower @yichengq

**Comment by yichengq** [comment]
My concern is that the data will be stored in a (random)etcd.default, and people may even not notice that. If they restart etcd without discovery flag(because they know that discovery flag is only for bootstrap), etcd cannot target data dir then.

**Comment by xiang90** [comment]
@yichengq Note: I am not suggesting to change the data dir. Just the name.

**Comment by damm** [comment]
It should let the user know when they use the default name; maybe a link to a page that explains why you should set a name?

**Comment by yichengq** [comment]
@xiang90 I misunderstood it. You mean that generating a random name only for discovery service. I think it is doable. Users may infer that there is no need to set name in static bootstrap, but they will fail early because they need to set -initial-cluster.

**Comment by xiang90** [comment]
After thinking more about this, we probably want a reliable default name even after restart. Probably we can hash peerURLs (and clientURLs)?

**Comment by philips** [comment]
Lets document it for name and suggest that a name should be a unique hostname, or machine-id.
