### ISSUE TITLE
Working .service for single node cluster

### ISSUE THREAD

**Issue by knodir** [coreos/etcd#3028]
@barakmich and I just spent an hour getting single node etcd2 cluster up and running. Here is the final working etcd2.service config file

```config
[Unit]
Description=etcd daemon

[Service]
Environment="ETCD_INITIAL_CLUSTER_STATE=new"
Environment="ETCD_INITIAL_CLUSTER=yao=http://10.20.20.111:7001"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.20.20.111:7001"
Environment="ETCD_NAME=yao"
Environment="ETCD_LISTEN_CLIENT_URLS=http://10.20.20.111:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://10.20.20.111:7001"
ExecStart=/usr/bin/etcd2`
```

Just to tie knits back: this question was initially posted on Google CoreOS [group](https://groups.google.com/forum/#!topic/coreos-user/P3N0XtYaki0), too. 

Huge thanks to @barakmich!

**Comment by knodir** [comment]
Update: bad news.

It seems even if etcd running, I cannot set key values to it. Here is the error message I get:

```shell
$ sudo etcdctl --debug set foo 42
Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379
```

@barakmich any ideas?

**Comment by barakmich** [comment]
You want the command line option `-C <address>` -- help has more details

**Comment by knodir** [comment]
Update: good news. I was able to resolve this issue by referring to the working examples in the [main docs](https://github.com/coreos/etcd/blob/master/Documentation/clustering.md). 

I had to add http://127.0.0.1:2379 to ETCD_LISTEN_CLIENT_URLS. Here is the updated fully working version (also updated port numbers to reflect etcd2)

```config
[Unit]
Description=etcd daemon

[Service]
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.20.20.111:2380"
Environment="ETCD_LISTEN_PEER_URLS=http://10.20.20.111:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://10.20.20.111:2379,http://127.0.0.1:2379"
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.20.20.111:2379"
Environment="ETCD_INITIAL_CLUSTER_STATE=new"
Environment="ETCD_INITIAL_CLUSTER=yao=http://10.20.20.111:2380"
Environment="ETCD_NAME=yao"
ExecStart=/usr/bin/etcd2

[Install]
```

**Comment by xiang90** [comment]
@knodir As @barakmich mentioned, you can give `etcdctl` an endpoint (by default it tries to reach 127.0.0.1:4001). Your etcdserver does not have to listen to 127.0.0.1:4001
