### ISSUE TITLE
sorry to trouble SergeyZh,help me with my AP650

### ISSUE THREAD

**Issue by wifihell** [coreos/etcd#3029]
https://forums.networkinfrastructure.info/motorola-wireless-lan-switches/error-setting-country-of-operation/15/  i came here from uplink post .i need a 4.4.2 AP650 firmware .  i  serached without answers. and can not connect to moto.

**Comment by wifihell** [comment]
@SergeyZh  thanks

**Comment by yichengq** [comment]
@wifihell This repo is just for etcd project. You should find other better ways for this question. Thanks!
