### ISSUE TITLE
Asking for suggestions about using etcd

### ISSUE THREAD

**Issue by shafreeck** [coreos/etcd#3036]
Hi:  
I am planning to use etcd to build our service discovery service. I looked through the source code and found that the `storage` package is unused. Is there a big change for the storage engine in the future ? If there is , what's the roadmap? Which version do you suggest that I should use in production ?

Thanks in advance!

**Comment by xiang90** [comment]
Yes. We are working on a new backend. The design goal is here: https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md. 

You should use current etcd. The release date of the new backend/api is still TBD.
