### ISSUE TITLE
Silent failure when `-discovery` and `-initial-cluster-token` specified

### ISSUE THREAD

**Issue by olix0r** [coreos/etcd#3038]
Full disclosure: I don't entirely know what I'm doing with Etcd.  I'm trying to set up my first clustered etcd configuration (initially by-hand so that I understand how it works).

During the process of trial and error, I accidentally specified both `-discovery` and `-initial-cluster-token` which causes etcd to exit with no explanation of what the problem is:

    export disco=$(curl -s https://discovery.etcd.io/new) ip=$(boot2docker ip)

    docker run -it --rm --net=host quay.io/coreos/etcd:v2.1.0-alpha.1 -initial-cluster-token=testetcd -discovery=$disco -initial-advertise-peer-urls=http://$ip:2380 -advertise-client-urls=http://$ip:2379 -listen-peer-urls=http://$ip:2380 -listen-client-urls=http://$ip:2379
    2015/06/23 17:06:49 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
    2015/06/23 17:06:49 etcdmain: no data-dir provided, using default data-dir ./default.etcd
    2015/06/23 17:06:49 etcdmain: listening for peers on http://192.168.59.103:2380
    2015/06/23 17:06:49 etcdmain: listening for client requests on http://192.168.59.103:2379
    2015/06/23 17:06:49 etcdmain: stopping listening for client requests on http://192.168.59.103:2379
    2015/06/23 17:06:49 etcdmain: stopping listening for peers on http://192.168.59.103:2380
    2015/06/23 17:06:49 etcdmain: x509: failed to load system roots and no roots provided

Removing `-initial-cluster-token` appears to resolve the issue.

This is fairly confusing behavior.

**Comment by olix0r** [comment]
I think my initial description of the problem isn't entirely correct.  Removing `initial-cluster-token` allowed me to see an error message:

    2015/06/23 17:11:24 discovery: duringcluster status checkconnection tohttps://discovery.etcd.iotimed out, retrying in2s

but now I am back to the same behavior of it just exiting immediately ;/  Any pointers are appreciated.

**Comment by yichengq** [comment]
etcd failed to do HTTPS request to discovery service due to lack of certificate. You should give docker it.

Maybe this will help you: https://github.com/zenazn/goji/issues/126

**Comment by olix0r** [comment]
that's obvious now that i look at this again.  thanks for the help
