### ISSUE TITLE
etcd doesn't provide a structured way of learning the history's first valid index

### ISSUE THREAD

**Issue by rkd-msw** [coreos/etcd#3056]
I hit a case where:

* I read a value, which had changed at index 80
* I wanted to watch for changes to this value, so set a watch from index 81
* A snapshot had occurred since index 81, invalidating that index, so I got back a 401 error ('The event in requested index is outdated and cleared : the requested history has been cleared [268/81]')

I think what I want to do in that case is to watch from index 268 (the last valid index), as watching without an index leaves a small window where the value could change without me noticing. However, as far as I can tell, there's no structured way to learn that I want index 268 - I have to parse the returned string.

Is it possible to learn the first valid index in the history somehow, or could this be added?

**Comment by xiang90** [comment]
@rkd-msw We probably will not change v2 API anymore. Can you look at https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.proto and give us some feedback?

**Comment by xiang90** [comment]
@rkd-msw I am closing this due to low activity. Feel free to reopen if you have a follow-up.

**Comment by rkd-msw** [comment]
Apologies for the slow response - unfortunately I'm struggling a bit to understand https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.proto. I think the "index" field of the ResponseHeader could give me what I want, but it's hard to say without seeing the implementation - am I right in thinking that that value would be '268' in the scenario above?

**Comment by yichengq** [comment]
@rkd-msw In v3api, we plan to let users decide when to compact the history: https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.proto#L28 So most of the time you will not meet the out-of-index case.

And yes, the "index" field could tell you the current store index.

**Comment by rkd-msw** [comment]
Actually, from experimenting further, I think that X-Etcd-Index gives me what I need in v2 (https://github.com/coreos/etcd/blob/d86e94b8248f707b76d8434b65768c95e7141edb/Documentation/api.md#response-headers).

**Comment by yichengq** [comment]
@rkd-msw For watch case, we refresh our doc to represent the way to use it best: https://github.com/coreos/etcd/blob/master/Documentation/api.md#waiting-for-a-change. I hope this helps.
