### ISSUE TITLE
No disk space causes etcd to stall

### ISSUE THREAD

**Issue by calummoore** [coreos/etcd#3068]
I ran into an issue when the leader of the cluster ran out of disk space. It made the entire cluster unreachable for etcd and it seems that it couldn't re-elect a different leader.

I was able to fix the issue by simply removing the offending (leader) instance, but this is not an ideal situation.

Here's the last journal message I had on the no disk space instance (note: that peer relates to a follower): `warning: heartbeat time out peer="e6ee689cb13e28ec6219cb0d131f979d`

On the follower instance the log shows as follows (Jun 26 22:33:25 is when the leader ran out of space):

    [etcd] Jun 26 22:33:24.764 INFO      | e6ee689cb13e28ec6219cb0d131f979d: term #20 started.
    [etcd] Jun 27 09:24:52.703 INFO      | e6ee689cb13e28ec6219cb0d131f979d: term #21 started.
    [etcd] Jun 27 09:24:52.703 INFO      | e6ee689cb13e28ec6219cb0d131f979d: leader changed from 'b1105d6b63f75e122ab33eaa3779a776' to ''.

At Jun 27 09:24:52 I removed the leader from the cluster and it seems to have triggered a new leadership election - everything started working again.

**Comment by xiang90** [comment]
Please monitor your disk space. etcd 0.4 will not handle this situation. etcd2 will error on this situation and exit.
