### ISSUE TITLE
 etcd.service started, stopping etcd2.service #2908 

### ISSUE THREAD

**Issue by fugumaki** [coreos/etcd#3072]
I'm having the issue reported in #2908 (closed for inactivity).

The results of issuing the systemctl commands requested in the original issue are as follows.

Thanks

-----

core@core-01 ~ $ systemctl cat etcd.service
# /usr/lib64/systemd/system/etcd.service
[Unit]
Description=etcd
Conflicts=etcd2.service

[Service]
User=etcd
PermissionsStartOnly=true
Environment=ETCD_DATA_DIR=/var/lib/etcd
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd
Restart=always
RestartSec=10s
LimitNOFILE=40000
core@core-01 ~ $ systemctl list-dependencies --reverse etcd.service
etcd.service
core@core-01 ~ $

**Comment by yichengq** [comment]
@marineam @crawford can you take a look at this?

**Comment by fugumaki** [comment]
As a workaround, masking etcd by adding the following lines to user-data seems to prevent etcd from starting:

  units:
  - name: etcd.service
    mask: true

**Comment by crawford** [comment]
Double check to make sure that no other units depend on etcd.service. You can use `systemctl list-dependencies --reverse etcd.service`.

**Comment by fugumaki** [comment]
There don't seem to be any dependencies.  Output is as follows:

core@core-01 ~ $ systemctl list-dependencies --reverse etcd.service
etcd.service

Thanks.

**Comment by crawford** [comment]
Something is starting etcd.service? Is it coreos-cloudinit?

**Comment by fugumaki** [comment]
It looks like deis-logspout starts etcd.service explicitly.

Sorry to be such a newb.
