### ISSUE TITLE
etcd doesn't start with ssl SRV records using DNS discovery

### ISSUE THREAD

**Issue by raoofmd** [coreos/etcd#3087]
I'm trying to start a 3 node cluster using ssl SRV records using DNS discovery and it complains below, though I'm passing the correct name.
etcd: couldn't find local name "node01" in the initial cluster configuration

I'm using 2.1.0-alpha

service etcd start
Starting etcd shared configuration and service discovery daemon (etcd):
Command is : su etcd -c nohup /var/lib/etcd/etcd  -advertise-client-urls https://node01.etcd.dev.com:2379 -initial-cluster-state new -name node01 -data-dir /var/lib/etcd/cluster/datadir -listen-peer-urls http://node01.etcd.dev.com:2380 -initial-advertise-peer-urls http://node01.etcd.dev.com:2380 -listen-client-urls https://node01.etcd.dev.com:2379 -discovery-srv etcd.dev.com -trusted-ca-file /var/home/rmd/ca.cert.pem -cert-file /var/home/rmd/node01.etcd.dev.com.cert.pem -key-file /var/home/rmd/node01.etcd.dev.com.pem -heartbeat-interval 200 -election-timeout 2000 >>/var/log/etcd/etcd.out 2>&1 &

Logs
2015/07/01 16:01:11 discovery: Got bootstrap from DNS for etcd-server-ssl at https://node02.etcd.dev.com:2379
2015/07/01 16:01:11 discovery: Got bootstrap from DNS for etcd-server-ssl at https://node03.etcd.dev.com:2379
2015/07/01 16:01:11 discovery: Got bootstrap from DNS for etcd-server-ssl at https://node01.etcd.dev.com:2379
2015/07/01 16:01:12 discovery: Error querying DNS SRV records for _etcd-server lookup _etcd-server._tcp.etcd.dev.com: no such host
2015/07/01 16:01:12 etcd: listening for peers on http://node01.etcd.dev.com:2380
2015/07/01 16:01:12 etcd: clientTLS: cert = /var/home/rmd/node01.etcd.dev.com.cert.pem, key = /var/home/rmd/node01.etcd.dev.com.pem, ca =
2015/07/01 16:01:13 etcd: listening for client requests on https://node01.etcd.dev.com:2379
2015/07/01 16:01:13 etcdserver: datadir is valid for the 2.0.1 format
2015/07/01 16:01:13 etcd: stopping listening for client requests on https://node01.etcd.dev.com:2379
2015/07/01 16:01:13 etcd: stopping listening for peers on http://node01.etcd.dev.com:2380
2015/07/01 16:01:13 etcd: couldn't find local name "node01" in the initial cluster configuration

The configuration and logs are same on all 3 nodes (except for respective node02, node03 in place of node01)

**Comment by xiang90** [comment]
@raoofmd Can you do 
```
 dig +noall +answer SRV _etcd-server-ssl._tcp.example.com
```
for me?

**Comment by raoofmd** [comment]
# dig +noall +answer SRV _etcd-server-ssl._tcp.etcd.dev.com
_etcd-server-ssl._tcp.etcd.dev.com. 86400 IN SRV 0 0 2379 node02.etcd.dev.com.
_etcd-server-ssl._tcp.etcd.dev.com. 86400 IN SRV 0 0 2379 node03.etcd.dev.com.
_etcd-server-ssl._tcp.etcd.dev.com. 86400 IN SRV 0 0 2379 node01.etcd.dev.com.

**Comment by xiang90** [comment]
@raoofmd 

OK.

Seem like you gave etcd wrong configuration. 

```
 -initial-advertise-peer-urls http://node01.etcd.dev.com:2380
```
Should be 
```
 -initial-advertise-peer-urls https://node01.etcd.dev.com:2380
```

The scheme is wrong.

**Comment by raoofmd** [comment]
i think peer should be http and on 2380 
and client should be on https and on 2379

**Comment by xiang90** [comment]
@raoofmd Then you should not use ssl dns srv discovery.

**Comment by raoofmd** [comment]
but my question is my dns discovery ssl srv is based on port 2379 and i want peers to communicate on 2380
so I'm bootstrapping on 2379 and then advertising peer on 2380

does it make sense

**Comment by raoofmd** [comment]
or If I'm using ssl dns srv discovery, then is it that I should have both peer and client use https

**Comment by xiang90** [comment]
@raoofmd dns srv discovery has nothing to do with your client communication. If you want to use ssl between etcd servers, use ssl discovery.

**Comment by raoofmd** [comment]
i think i got u, let me try

**Comment by xiang90** [comment]
@raoofmd You need to read and follow the doc here https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#dns-discovery.

**Comment by raoofmd** [comment]
Works like a charm and tried the proxy too. I was having incorrect SRV mapped to 2379 instead of 2380.

Thanks a ton.
