### ISSUE TITLE
"couldn't find local name "etcd1" in the initial cluster configuration" when using DNS SRV record discovery

### ISSUE THREAD

**Issue by jcmturner** [coreos/etcd#3100]
Hi,
I have been trying to get cluster discovery working using DNS SRV records but I cannot get past the error below. I have read through the document https://github.com/coreos/etcd/blob/master/Documentation/clustering.md but I can't see what I'm missing.

```
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 discovery: Got bootstrap from DNS for etcd-server at http://etcd1.coreip.intranet:2380
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 discovery: Got bootstrap from DNS for etcd-server at http://etcd2.coreip.intranet:2380
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: listening for peers on http://10.80.31.11:2380
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: listening for client requests on http://10.80.31.11:4001
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: listening for client requests on http://127.0.0.1:4001
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcdserver: datadir is valid for the 2.0.1 format
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: stopping listening for client requests on http://127.0.0.1:4001
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: stopping listening for client requests on http://10.80.31.11:4001
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: stopping listening for peers on http://10.80.31.11:2380
Jul  6 18:34:22 localhost bash: 2015/07/06 18:34:22 etcd: couldn't find local name "etcd1" in the initial cluster configuration
Jul  6 18:34:22 localhost systemd: etcd.service: main process exited, code=exited, status=1/FAILURE
Jul  6 18:34:22 localhost systemd: Unit etcd.service entered failed state.
```

I am setting these environment variables:
```
# [member]
ETCD_NAME=etcd1
ETCD_DATA_DIR="/var/lib/etcd/coreip1.etcd"
ETCD_LISTEN_PEER_URLS="http://10.80.31.11:2380"
ETCD_LISTEN_CLIENT_URLS="http://10.80.31.11:4001,http://127.0.0.1:4001"

ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.80.31.11:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="coreip1"
ETCD_ADVERTISE_CLIENT_URLS="http://10.80.31.11:4001"
ETCD_DISCOVERY_SRV="coreip.intranet"
```

Below are the results to the relevant dig commands

```
dig @10.80.10.11 +noall +answer SRV _etcd-server._tcp.coreip.intranet
_etcd-server._tcp.coreip.intranet. 300 IN SRV	0 0 2380 etcd1.coreip.intranet.
_etcd-server._tcp.coreip.intranet. 300 IN SRV	0 0 2380 etcd2.coreip.intranet.
```
```
dig @10.80.10.11 +noall +answer etcd1.coreip.intranet. etcd2.coreip.intranet.
etcd1.coreip.intranet.	86400	IN	A	10.80.31.11
etcd2.coreip.intranet.	86400	IN	A	10.80.31.12
```

**Comment by xiang90** [comment]
@jcmturner What is the version of etcd were you running?

**Comment by xiang90** [comment]
@jcmturner 

I think this should work. 
But I am not sure if your etcd server was using `10.80.10.11` as its name server.

**Comment by jcmturner** [comment]
I am using the version that comes in the centos 7 repos (2.0.11):
```
/usr/bin/etcd --version
etcd Version: 2.0.11
Git SHA: 0678329
Go Version: go1.4.2
Go OS/Arch: linux/amd64
```

My /etc/resolv.conf is using that nameserver
```
cat /etc/resolv.conf 
domain intranet
nameserver 10.80.10.11
```

Thanks.

**Comment by jcmturner** [comment]
Had a bit of a break through

Looks like if I change this line...
from
```
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.80.31.11:2380"
```
to
```
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://etcd1.coreip.intranet:2380"
```
It works.

**Comment by xiang90** [comment]
@jcmturner 

```etcd1.coreip.intranet``` was probably resolved to a IP address other than `10.80.31.11`. Then etcd complaints that it cannot find self in the list. When you changed `10.80.31.11` to `etcd1.coreip.intranet`, they resolved to the same IP addr and it worked. 

The code is easy to read here: https://github.com/coreos/etcd/blob/v2.0.11/discovery/srv.go#L40-L68
There might be a bug, and you can help to look into it. I will try to reproduce the problem too.

**Comment by jcmturner** [comment]
My machines do have two interfaces so your theory about what etcd1.coreip.intranet resolves to could be right. I'll double check.

**Comment by xiang90** [comment]
@jcmturner Any update?

**Comment by jcmturner** [comment]
Hi, sorry it's taken a while to get back on this. I have looked into this more and the combination that does not work is:

* Use an IP address for ETCD_INITIAL_ADVERTISE_PEER_URLS
* Use SRV DNS discovery returning the name of the host
* The host file on that host has a record for the name returned by the SRV discovery but not with the IP in the ETCD_INITIAL_ADVERTISE_PEER_URLS.

So the reason it did not work for me was that this was my host file:
```
# cat /etc/hosts
127.0.0.1   etcd1.coreip.intranet etcd1 localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

I assume when looking up the name returned from SRV to get the IP to check against the ETCD_INITIAL_ADVERTISE_PEER_URLS the host file entry means that 127.0.0.1 is returned rather than the publicly routable IP of the machine and therefore they don't match.

**Comment by xiang90** [comment]
@jcmturner OK. So basically, you have to make sure the returned domain name would be resolved to an IP address that matched to the peer url. Thanks for reporting. I think our doc around this is OK. If you think it confuses you, feel free to send us a pull request to improve it.

**Comment by jcmturner** [comment]
I think the only improvement that would make sense would be some improved logging. For example if the logs informed me it was looking for a loopback IP it would have helped troubleshooting.

**Comment by tomkcpr** [comment]
Just to reiterate on @jcmturner posted earlier, having better logging for this message would be a big plus.

I was getting this error as well and the hostnames and IP's in my case match perfectly.  There is only one IP on the host.  Yet the error persists.   Short of having to review the code and follow the logic, which takes hours if not days for anyone starting off with etcd, it is extremely difficult to figure out.

Would love to see something like this in the error messages:

- Does the error mean that the ETCD_NAME value is being compared?  If so, what is it being compared to?

- What does "initial luster configuration" mean?  Is it trying to create the "etcd" cluster and it can't write the cluster "ocgo" into etcd?  Is it missing a config it needs?  Config is identical to another, separate, cluster that is working. 

- Is it looking for ocgo in the hostname?

- Is it looking for "ocgo" as the cluster name in the etcd cluster list ( etcdctl ls ) ?

- Is it not detecting hostnames it feels are missing from the ETCD_INITIAL_CLUSTER line?

- etc.

I'll be digging into the code for more context of when the error is thrown to figure this out.   In the meantime I would like to suggest that context and a more clear explanation w/ possible resolutions be applied to any etcd log messages.  I'm seeing quite a bit of hesitation in adaptation of this, which makes it an uphill battle, due to the difficulty in interpreting errors and hence in the time and consequently cost, to resolve these.

**Comment by shyamsunderrai** [comment]
I had the same issue, thought of sharing the "solution". It was a typo in the hostname when defining the --initial-cluster values. Instead of using "node-1", I was trying "node1" which the system was obviously unable to resolve. Trying to launch the command from CLI did really help.

**Comment by RolanS** [comment]
> I wanted to statically bootstrap from a yaml config file
> 
> initial-cluster: etcd-01=http://10.89.0.11:2380,etcd-02=http://10.89.0.12:2380,etcd-03=http://10.89.0.13:2380
> The only thing that worked for me was switching to configuration with command line flags. 😖

It helped me too.
