### ISSUE TITLE
Start etcd.service or etcd2.service?

### ISSUE THREAD

**Issue by Dynom** [coreos/etcd#3103]
Hi,

This might seem too obvious to ask, but I'm starting with a new cluster. Some tutorials depend on etcd.service:

Unit file
```
After=etcd.service
Requires=etcd.service
```

The documentation mentions to start either `etcd.service` or `etcd2.service`. I figure that people new to Etcd, who start with a new cluster should never start or depend on `etcd.service` but instead switch entirely to `etcd2.service`, right?

**Comment by yichengq** [comment]
We strongly recommend users to use etcd2.service because it is better than etcd.service. You could change the dependency to etcd2.service if you use etcd2.service. The etcd.service listed in the tutorial should be changed step by step. Where do you see the dependency?

/cc @robszumski @crawford

**Comment by robszumski** [comment]
@Dynom what documentation are you referencing? Everything should be referencing etc2.

**Comment by Dynom** [comment]
@robszumski Well for starters, the getting started guide here: https://coreos.com/docs/launching-containers/launching/getting-started-with-systemd/ (In the section "Advanced Unit Files")

But there are also plenty "outdated" resources to be found online. I just wanted to create some clarity for myself and hopefully some others that might struggle with this.

This section is "Entirely" outdated (also refers to older ports, etc.) ->
https://coreos.com/docs/running-coreos/cloud-providers/ec2/

**Comment by Dynom** [comment]
Again, it might seem very obvious but running both etcd2.service and etcd.service results in awkward behaviour.

If there is one unit file, that references `etcd.service`,  which is scheduled in a cluster, it might automatically result in `etcd2` being stopped and `etcd` being started. This will cause that machine to leave the cluster according to fleetctl.

The result is all kind of errors, like:

- Failed getting response from SOME_IP
- HTTP 404 errors without response body


It's very easily reproduced, just run this unit file in an etcd2 cluster:
```
[Unit]
Description=BAD unit file
After=etcd.service
Requires=etcd.service

[Service]

ExecStop=/bin/bash -c "echo 'STOPPED, stop etcd and start etcd2 on this machine!'"
ExecStart=/bin/bash -c "echo 'STARTED, the cluster should be getting wonky now.'"
```

**Comment by xiang90** [comment]
@Dynom I do not think this is actually an etcd issue. As @yichengq mentioned, we suggest you run etcd2 instead of etcd 0.4. And we strongly suggest you not run etcd2 and etcd0.4 side by side on the same machine. 

If you think the docs can be improved, can you please open up an issue at https://github.com/coreos/docs?

**Comment by Dynom** [comment]
It might not be an Etcd issue strictly speaking. But since Etcd and Etcd2 are both available on CoreOS, it's trivial to make a mistake. Based on when a certain unit is scheduled to be launched it can bring a cluster down.

While it is an error by the author of the unit files, it's an easy one to make, with unintuitive consequences. I do feel you take this matter too lightly.

**Comment by yichengq** [comment]
Thanks for open the coreos/docs issue! We definitely want to clear all docs and provide users a good path to play with. If there is other out-of-date docs, please let us know and we will help with that.

I have opened an issue in joukou-fleet to update the doc: https://github.com/joukou/joukou-fleet/issues/1

**Comment by Alino** [comment]
is there any easy solution how to bring up the cluster back after I made a mistake and required etcd.service inside a unit instead of etcd2.service?
It is big overkill for me to recreate the whole cluster everytime I accidently run etcd.service
For production really dangerous if you dont know how to easily revert the cluster quick enough :(

**Comment by philips** [comment]
@xiang90 etcd v0.4.9 doesn't have a member/wal directory, right?

@mischief I think we should add a `ConditionPathExists=!/var/lib/etcd/member/wal` to etcd.service to help people not make this mistake.
