### ISSUE TITLE
how to recover from an unhealthy cluster state in production.

### ISSUE THREAD

**Issue by raoofmd** [coreos/etcd#3109]
what if the cluster goes unhealthy in production, will restarting fix the issue and sync up the nodes - which I dont think so

**Comment by xiang90** [comment]
@raoofmd If there is a machine failure you might need to do this:https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#replace-a-failed-machine

If there are more than majority of machine failures, you might need to do this:
https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery
