### ISSUE TITLE
How to embed /run/systemd/system/etcd2.service.d/20-cloudinit.conf ?

### ISSUE THREAD

**Issue by Dynom** [coreos/etcd#3110]
The file `/run/systemd/system/etcd2.service.d/20-cloudinit.conf` contains all the information I need regarding Etcd's connection strings. Most snippets I see simply hard-core the ports, which is not something I prefer. How can I make the contents of `20-cloudinit.conf` available in my unit file?
I've tried the obvious:

EnvironmentFile=/run/systemd/system/etcd2.service.d/20-cloudinit.conf

However since `20-cloudinit.conf` contains the following syntax, it's not supported by Systemd (as it expects `key="value"` and not `Environment="key=value"`, if I understand correctly. http://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile=)

contents of 20-cloudinit.conf:
```
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.29.115.197:2379,http://10.29.115.197:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/a9d42be514b49f04f02479ec1e151b03"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.29.115.197:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://10.29.115.197:2380"
```

In my unit file I'd like something like this:
```
..
EnvironmentFile=/run/systemd/system/etcd2.service.d/20-cloudinit.conf

ExecStartPre=/usr/bin/echo "ETCD_MACHINES=${ETCD_ADVERTISE_CLIENT_URLS}"
..
```

**Comment by yichengq** [comment]
This is much more related to systemd/coreos instead of CoreOS. I would recommend to open the issue in coreos/bugs for better solution.

**Comment by Dynom** [comment]
Okay, moved the question.
