### ISSUE TITLE
clientURLs field is ignored on node addition

### ISSUE THREAD

**Issue by banjiewen** [coreos/etcd#3112]
If I attempt to add a node to an existing cluster via the HTTP API subsequent requests to `/v2/members` don't show that node's `clientURLs` as specified in the addition `POST`. E.g.,:

```
 $ curl localhost:2379/v2/members -Hcontent-type:application/json -XPOST -d '{"peerURLs":["http://172.31.29.26:2380"], "clientURLs":["http://172.31.29.26:2379"]}'
{"id":"1fc44190276f5167","name":"","peerURLs":["http://172.31.29.26:2380"],"clientURLs":[]}
```

Is this intended? I noticed that the [example](https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#add-a-member) in the node lifecycle document only specifies `peerURLs`.

Furthermore, does the lack of `clientURLs` in the output of `/v2/members` actually represent an issue with cluster state?

**Comment by xiang90** [comment]
@banjiewen This is intended. All non cluster related information will be published by the newly added member itself when it starts.

**Comment by banjiewen** [comment]
@xiang90 Thanks.

**Comment by banjiewen** [comment]
@xiang90 How long should I expect that publish to take? I've got a cluster where it hasn't been added 5 minutes after the `POST` was accepted. The leader logged the following after the `POST`, but nothing since:

```
2015/07/10 19:34:16 etcdserver: added member 4ac859bd865ce090 [http://172.31.39.178:2379] to cluster 4febde5f3f48fa31
2015/07/10 19:34:16 sender: error posting to 4ac859bd865ce090: unexpected http status Not Found while posting to "http://172.31.39.178:2379/raft"
2015/07/10 19:34:16 sender: the connection with 4ac859bd865ce090 became inactive
```

**Comment by yichengq** [comment]
@banjiewen The publish happens when you run the etcd process of that newly joined member.

**Comment by banjiewen** [comment]
@yichengq etcd was already running on the newly joined member at join time.

**Comment by xiang90** [comment]
@banjiewen You should give it peer url not client. This is wrong `http://172.31.39.178:2379`. It should be 2380.

**Comment by banjiewen** [comment]
@xiang90 Good catch, that was my mistake. Deleting and re-adding with the peer URL results in similar results:

```
2015/07/10 21:20:10 etcdserver: added member b2302fb2571e9dbc [http://172.31.39.178:2380] to cluster 4febde5f3f48fa31
2015/07/10 21:20:10 sender: error posting to b2302fb2571e9dbc: dial tcp 172.31.39.178:2380: connection refused
2015/07/10 21:20:10 sender: the connection with b2302fb2571e9dbc became inactive
```

It appears that the new node is not listening on 2380, and `ss -ant` on the new node confirms. What determines whether or not a node listens on the peer port? I've observed that my proxy nodes don't (though I can't figure out how to determine if a node is indeed configured as a proxy or not).

**Comment by xiang90** [comment]
@banjiewen You should follow the doc here https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member step by step.
