### ISSUE TITLE
Set GOMAXPROCS to a high-performance default

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#3119]
Currently etcd sets GOMAXPROCS to 1 if it is not set in the environment.  That means the operator has to find and edit the the etcd startup configuration each time they install etcd.  In addition, it means that etcd doesn't get much multi-threaded exposure.

Why not set GOMAXPROCS to the number of CPUs or some simple function thereof so that this just works out of the box and the code gets a lot more exposure in multi-threaded environment?

**Comment by yichengq** [comment]
I think this is a good suggestion. I would like to set it to the number of cores when go1.5 comes out because that is the default setting for GOMAXPROCS in go1.5(https://docs.google.com/document/d/1At2Ls5_fhJQ59kDK2DFVhFu3g5mATSXqqV5QrxinasI/edit).

**Comment by xiang90** [comment]
@fasaxc I agree with @yichengq  on this. We have documented this at https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#maximum-os-threads.
