### ISSUE TITLE
I would like to manage global configuration with etcd between 2 more datacenters.

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#3122]
I have some configuration settings that should be the same across multiple datacenters. This includes things such as my stripe username and password, and the service URL. I would like to push this data to one cluster and have it made available on the "other side". This means I only need to write global configuration data to one cluster.

**Comment by philips** [comment]
Some examples of how the UX might work would be helpful. For example is this sufficient:

```
etcd-replicate --target-clusters b.datacenter.corp/v2/keys/global,c.datacenter.corp/v2/keys/global --source a.datacenter.corp/v2/keys/global
```

**Comment by yichengq** [comment]
The tool cannot guarantee any level of consistency then. It just likes a replication daemon. Is this expected?

**Comment by xiang90** [comment]
This seems to be duplicate with https://github.com/coreos/etcd/issues/1749. Can you move your requirement to #1749 if you think they are the similar? @kelseyhightower

**Comment by collinmsn** [comment]
where's etcd-replicate? I can not find it in latest source directory.

**Comment by jonboulle** [comment]
@collinmsn etcd-replicate does not exist - that was just a proposal of what the UX might look like.

I'm going to close this in favour of #1749
