### ISSUE TITLE
tuning guide on coreos.com is out of date

### ISSUE THREAD

**Issue by mischief** [coreos/etcd#3124]
https://coreos.com/docs/cluster-management/debugging/etcd-tuning/ is incorrect for etcd2.

**Comment by yichengq** [comment]
@robszumski I checked the doc on repo: https://github.com/coreos/etcd/blob/master/Documentation/tuning.md, and it is fine (use flag ETCD_ELECTION_TIMEOUT instead of ETCD_PEER_ELECTION_TIMEOUT). Is the one in website out-of-date?

**Comment by robszumski** [comment]
Sorry about this! You caught us in an upgrade. We now have more robust scripts to handle this documentation sync and this should now be fixed and live.
