### ISSUE TITLE
start an etcd proxy example in proxy guide does not work

### ISSUE THREAD

**Issue by gouyang** [coreos/etcd#3135]
`$ ./etcd -proxy on -listen-client-urls 127.0.0.1:8080 -initial-cluster "infra0=http://10.66.11.39:2380,infra1=http://10.66.11.70:2380,infra2=http://10.66.102.87:2380"` just get the usage here.

Adding "http://" in `-listen-client-urls` make it work, is it just a document bug or a proxy functional bug? I'd prefer the later, fix the proxy to accept the short urls.

**Comment by gouyang** [comment]
it seems to be a doc bug

**Comment by yichengq** [comment]
We decide to use url with schema because it could make etcd and user clear about which address is used. Users could use HTTPS for the urls.

Feel free to review the PR.

> it seems to be a doc bug as everywhere is using "http" except "etcdctl --peers", which accept the short url. It is an inconsistency.

Where did you see these? It needs to be fixed then.

**Comment by gouyang** [comment]
just in the usage:
```
$ ./etcdctl -h | grep peers
   --peers, -C 			a comma-delimited list of machine addresses in the cluster (default: "127.0.0.1:4001,127.0.0.1:2379")
[guohua@gbox bin]$ etcdctl --peers 10.66.11.39L2379 ls
Error:  cannot sync with the cluster using endpoints http://10.66.11.39L2379
$ etcdctl --peers 10.66.11.39:2379 ls
/gh
/discovery
```

**Comment by gouyang** [comment]
> We decide to use url with schema because it could make etcd and user clear about which address is used. Users could use HTTPS for the urls.

I agree it would make stuff clear to user, but people are used to write url without schema, just like this guide does. It's not a problem to me, I can go with either way.

**Comment by yichengq** [comment]
etcd could be the critical heart of a cluster, so we makes every step as clear as possible to avoid operation error.
