### ISSUE TITLE
Proposal: initialize as a member by default and initialize as proxy when proxy is set to on

### ISSUE THREAD

**Issue by gouyang** [coreos/etcd#3142]
if the server is already initialized as proxy before, it always run as a proxy.
is it the design? I'd like to propose only intialize as proxy when the proxy flag is set, otherwise intialized as cluster member.

initialized as proxy without proxy on currently:
```
$ etcd -name infra1 -initial-advertise-peer-urls http://10.66.11.70:2380 \
> -listen-peer-urls http://10.66.11.70:2380 \
> -listen-client-urls http://10.66.11.70:2379,http://127.0.0.1:2379 \
> -advertise-client-urls http://10.66.11.70:2379 \
> -initial-cluster-token etcd-cluster-1 \
> -initial-cluster $ETCD_INITIAL_CLUSTER \
> -initial-cluster-state $ETCD_INITIAL_CLUSTER_STATE
2015/07/16 01:59:27 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
2015/07/16 01:59:27 etcdmain: no data-dir provided, using default data-dir ./infra1.etcd
2015/07/16 01:59:27 etcdmain: the server is already initialized as proxy before, starting as etcd proxy...
2015/07/16 01:59:27 etcdmain: proxy: using peer urls [http://10.66.102.87:2380 http://10.66.11.39:2380 http://10.66.11.70:2380] from cluster file ./infra1.etcd/proxy/cluster
2015/07/16 01:59:27 etcdmain: proxy: listening for client requests on 10.66.11.70:2379
2015/07/16 01:59:27 etcdmain: proxy: listening for client requests on 127.0.0.1:2379
```

**Comment by gouyang** [comment]
also notice this 
```
$ ./etcd 
2015/07/16 02:09:22 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
2015/07/16 02:09:22 etcdmain: no data-dir provided, using default data-dir ./default.etcd
2015/07/16 02:09:22 etcdmain: invalid datadir. Both member and proxy directories exist.
```

it should not be like this, initialize as a member by default and initialize as proxy when proxy is set to on.

**Comment by yichengq** [comment]
> if the server is already initialized as proxy before, it always run as a proxy.

This is intentional. We expect users to use different data dir for member mode and proxy mode. One etcd data dir is always used in one mode in its life.

**Comment by gouyang** [comment]
> This is intentional. We expect users to use different data dir for member mode and proxy mode. One etcd data dir is always used in one mode in its life.

I'm fine with the design at present. Propose this because I can see both member and proxy under the data dir.

```
$ ls test.etcd/
member  proxy
$ ls default.etcd/
member  proxy
```
in the long term, if the proposal is accepted would be much better, put all data in one dir is the practice way to go.

**Comment by gouyang** [comment]
When try to fix #3149, I even have a strong feeling to fix this.  And it seems very simple:
```
$ git diff
diff --git a/etcdmain/etcd.go b/etcdmain/etcd.go
index 5bdc289..1085578 100644
--- a/etcdmain/etcd.go
+++ b/etcdmain/etcd.go
@@ -90,12 +90,7 @@ func Main() {
                plog.Warningf("no data-dir provided, using default data-dir ./%s", cfg.dir)
        }
 
-       which := identifyDataDirOrDie(cfg.dir)
-       if which != dirEmpty {
-               plog.Noticef("the server is already initialized as %v before, starting as etcd %v...", which, which)
-       }
-
-       shouldProxy := cfg.isProxy() || which == dirProxy
+       shouldProxy := cfg.isProxy()
        if !shouldProxy {
                stopped, err = startEtcd(cfg)
                if err == discovery.ErrFullCluster && cfg.shouldFallbackToProxy() {
```
and func `identifyDataDirOrDie` can be cleanup, less code enables more!

The current logic about member mode and proxy mode depend on the dirname under data dir, if we expect user to use different data dir, why not use "dir.member" and "dir.proxy" as data dir?

So I propose two options:
1. Enable both member and proxy in the same data dir, less code and easy to use.
2. Use the mode as the data dir suffix.

**Comment by yichengq** [comment]
> Enable both member and proxy in the same data dir

I am against it because:
1. using different dir could make users aware that proxy mode and member mode are two totally different things, and should not switched between each other
2. we ask users to remove the data dir after removing the member. If we enabling both, we need to expose the internal file organization to end users, which becomes inflexible

> Use the mode as the data dir suffix.

data dir name has been the convention of etcd, and it cannot be changed easily. Moreover, using suffix to data dir name adds indirection and may bring more inconvenience.

**Comment by gouyang** [comment]
> I am against it because:
> 1. using different dir could make users aware that proxy mode and member mode are two totally different things, and should not switched between each other
we let user to understand the difference by the flag already, they can only run as proxy mode when the proxy flag is on, otherwise they are always run as member mode. there is no switch. member mode always use data-dir/member folder, proxy mode use data-dir/proxy, pretty clear to me.
The changes removes the logical decision, the current logical decision already have several issues, and to fix #3149 is actually not so easy.

> 2. we ask users to remove the data dir after removing the member. If we enabling both, we need to expose the internal file organization to end users, which becomes inflexible
I don't understand, could you explain a bit more how it come to inflexible?

**Comment by yichengq** [comment]
> member mode always use data-dir/member folder, proxy mode use data-dir/proxy,

Normal user doesn't know the subdir structures, so he may think these two things are mixed together

> I don't understand, could you please explain a bit more how it come to inflexible?

If we make the change, we will ask users to remove /dir/member directory then. But we don't want to say this because we don't want to let /dir/member become conventions, and we want to reserve the rights to change it in the future.

**Comment by xiang90** [comment]
@gouyang  The intention here is: if etcd is initialized as a member, it will always be a member unless you remove the initialized data dir; if etcd is initialized as proxy, it will always be a proxy unless you remove the initialized data dir. See #3154.
