### ISSUE TITLE
2.1.0-alpha.1 enters futex_wait spinning

### ISSUE THREAD

**Issue by mwitkow-io** [coreos/etcd#3143]
We've just run into issues across multiple Etcd clusters after upgrading to `CoreOS alpha (738.1.0)`, while keeping the same, manually overlaid `2.1.0-alpha.1` of Etcd.

The situation is as follows, at some point a peer dies. We see something like:

```
Jul 16 00:32:44 eu2-prod-core-2 etcd[1663]: 2015/07/16 00:32:44 rafthttp: the connection with efe82db5d6cb17e3 became inactive
Jul 16 00:32:44 eu2-prod-core-2 etcd[1663]: 2015/07/16 00:32:44 rafthttp: failed to read efe82db5d6cb17e3 on stream MsgApp v2 (read tcp 10.152.3.29:2380: i/o timeout)
Jul 16 00:32:44 eu2-prod-core-2 etcd[1663]: 2015/07/16 00:32:44 rafthttp: failed to read efe82db5d6cb17e3 on stream Message (read tcp 10.152.3.29:2380: i/o timeout)
```
This happens across many peers.

At the same time, the machine that failed `10.152.3.29` doesn't post much in terms of logs, the last log entry is:
```
Jul 16 00:27:10 eu2-prod-core-3 etcd[696]: 2015/07/16 00:27:10 etcdserver: compacted raft log at 805137
Jul 16 00:27:38 eu2-prod-core-3 etcd[696]: 2015/07/16 00:27:38 fileutil: purged file /var/lib/etcd2/member/snap/0000000
```
However, all local calls to `etcdctl ls /` hang forever. But Etcd is *up* on that node and is taking 100% of CPU:
```
michal@eu2-prod-core-3 ~ $ sudo netstat -putnl | grep etcd
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 10.152.3.29:7001        0.0.0.0:*               LISTEN      696/etcd            
tcp      129      0 10.152.3.29:2380        0.0.0.0:*               LISTEN      696/etcd            
tcp6     129      0 :::4001                 :::*                    LISTEN      696/etcd            
tcp6     129      0 :::2379                 :::*                    LISTEN      696/etcd   
```

Stracing the binary shows why it's taking 100% of CPU, it seems to be spinning like crazy:
```
strace -p 696 -f
[pid   715] futex(0xb8c330, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid   715] clock_gettime(CLOCK_MONOTONIC, {66600, 405112897}) = 0
[pid   715] clock_gettime(CLOCK_MONOTONIC, {66600, 405235097}) = 0
[pid   715] futex(0xb8c330, FUTEX_WAIT, 0, {0, 100000}) = -1 ETIMEDOUT (Connection timed out)
[pid   715] clock_gettime(CLOCK_MONOTONIC, {66600, 405634822}) = 0
[pid   715] clock_gettime(CLOCK_MONOTONIC, {66600, 405710085}) = 0
```

I tried getting a `go` stacktrace, but doing `kill -s SIGSEGV 696` didn't help. Any idea how I can get a better set of debug info next time it wedges?

We did manage to unwedge Etcd by doing `systemctl restart etcd2.service` and it happily rejoined the cluster. We saw no networking issues in Dmesg nor in our machine-level monitoring.

We run the same version of Etcd for the past few weeks (`2.1.0-alpha.1`), and since upgrading to CoreOS `738.1.0` we saw 3 peer failures across ~20h.

**Comment by yichengq** [comment]
> The situation is as follows, at some point a peer dies.

Did that machine really die? A sudden shutdown?

> However, all local calls to etcdctl ls / hang forever

The next time you could try to use `etcdctl cluster-health`, and `etcdctl
-C $certain_peer ls /` to check the status. etcdctl does request to all
etcd members one by one, and may hang on one member for one minute.

> I tried getting a go stacktrace, but doing kill -s SIGSEGV 696 didn't
help.

kill -SIGQUIT 696  could print out go stack. A full log and command line
does help too. Moreover, we improve log printout hugely in 2.1.0-rc.0.

> and it happily rejoined the cluster.

nit: the member is always in the cluster, it just offlined for some time.

On Thu, Jul 16, 2015 at 12:43 AM, Michal Witkowski <notifications@github.com

**Comment by mwitkow-io** [comment]
The machines (VMs) didn't die. They were responsive to networking pings, ssh etc. The etcd2 process. We did try `etcdctl cluster-health`, as expected the peer was unhealthy. 

Regarding the stack trace, where would it have printed it? It wasn't in the `journalctl`.

We did roll back to `CoreOS 723` (current beta, also the previous alpha we were running) and everything returned to normal. We had similar issues with Prometheus segfaulting and misbehaving on `CoreOS 738.1.0` (see https://github.com/prometheus/prometheus/issues/895), and these too were caused by teh version.

**Comment by yichengq** [comment]
> Regarding the stack trace, where would it have printed it? It wasn't in the journalctl.

Maybe journald miss these lines.(https://github.com/coreos/bugs/issues/373) Try `journalctl -f -t etcd`

**Comment by yichengq** [comment]
@mwitkow-io After talking with @crawford , he thinks the problem may come from 738.1 OS. We have known that it affects Go 1.3, so it may affect Go 1.4 too. Do you have time to give a try to 745.1.0, and tell us whether it is still a problem?

**Comment by yichengq** [comment]
@mwitkow-io Have you ever tried 745.1.0 to see whether it is fixed? We will cut 2.1 very soon, and hope to confirm that your spinning is caused from OS instead of etcd.

**Comment by mwitkow-io** [comment]
@yichengq, sorry we were busy fighting other fires over the last week. For the immediate term we're planning to stick to the Core OS Beta Channel. Sorry :(

Our Etcd load is mostly driven by Fleet though, so a sufficiently large cluster would allow you to repro if you need to.

**Comment by crawford** [comment]
@mwitkow-io thanks for the pointer. We are going to try to verify that the issue is with the OS, not etcd.

**Comment by yichengq** [comment]
I tried to reproduce it. I started two 3-member 2.1.0-alpha.1 etcd cluster in AWS using m3.large machine. One runs 738.1.0 and the other one uses 745.1.0. Then set up one machine for each cluster to send requests, and keeps 2000 writes per second. After 21 hours, both of them still work well. I guess maybe there is difference on workload or platform.

This is not the blocker for 2.1 after discussion. 1. etcd cluster runs well after switching back to 723, and 738 is known to have vDSO problem. 2. we run etcd functional tests for several weeks and it works well

**Comment by xiang90** [comment]
@mwitkow-io @yichengq @crawford Do we have any plan to move forward this issue? Or should we close it? 

Actually I really want to find out the root cause. But it seems like we have tried hard and failed. Probably @mwitkow-io can help to reproduce and let us debug it? (by logging into the machine?)

**Comment by yichengq** [comment]
@xiang90 No plan from me.

**Comment by xiang90** [comment]
@mwitkow-io At this point, I think we can close this issue. If you meet this again or you can reproduce it, we can reopen it. Thanks!
