### ISSUE TITLE
Memory leak - remove key would not release memory?

### ISSUE THREAD

**Issue by vtxyer** [coreos/etcd#3145]
Firstly etcd is awesome and help us project a lot.

We have tested running two node etcd cluster and find it may have memory leak issue.

Environment:
- two machine are 1G memory
- close snapshot and start cluster by env ETCD_SNAPSHOT="false" (but it seems still have snapshot)

Experiment:
We writed script try to create 1000 new key and each contain value 100k size. Each time we would run 5 process to create the key with 100k size value. And after create just remove the key. So in the same time there are at most 500k data in the store.

But we found that the memory usage would from 7k growth around to 300M and it would not release the memory after the whole script finished.

The etcd data structure is like following:
.:
drwxr-xr-x    1 root     root          12 Jul 16 21:05 .
drwxr-xr-x    1 root     root          34 Jul 16 20:52 ..
drwx------    1 root     root          14 Jul 16 21:05 member

./member:
drwx------    1 root     root          14 Jul 16 21:05 .
drwxr-xr-x    1 root     root          12 Jul 16 21:05 ..
drwx------    1 root     root         152 Jul 16 23:23 snap
drwx------    1 root     root         222 Jul 16 23:23 wal

./member/snap:
drwx------    1 root     root         152 Jul 16 23:23 .
drwx------    1 root     root          14 Jul 16 21:05 ..
-rw-r--r--    1 root     root       97.8M Jul 16 21:59 0000000000000002-0000000000002711.snap
-rw-r--r--    1 root     root       97.8M Jul 16 23:23 0000000000000002-0000000000004e22.snap

./member/wal:
drwx------    1 root     root         222 Jul 16 23:23 .
drwx------    1 root     root          14 Jul 16 21:05 ..
-rw-------    1 root     root       98.5M Jul 16 21:59 0000000000000000-0000000000000000.wal
-rw-------    1 root     root      937.0K Jul 16 23:23 0000000000000001-0000000000002712.wal
-rw-------    1 root     root       98.1M Jul 16 23:57 0000000000000002-0000000000004e23.wal

And the gcvis image is like following:
![image](https://cloud.githubusercontent.com/assets/1001118/8728323/094ad476-2c17-11e5-9c97-c1cd10cccc39.png)

Thanks for any advises.

**Comment by yichengq** [comment]
@vtxyer etcd v2 keeps a copy of snapshot in memory, so it accounts for 100mb memory size. And v2 store keeps 1000 recent events, which keeps the value of the related key, so it accounts for 100mb memory size.

We will improve this in v3 by using in-disk backend.

**Comment by vtxyer** [comment]
Thanks so much for your information. But we still have the other problem from the website it seems that ETCD_SNAPSHOT="false" would close the snapshot or I misunderstanding the meaning of this option?

**Comment by yichengq** [comment]
ETCD_SNAPSHOT has been deprecated in etcd 2.0. It is dangerous to run etcd without snapshot because it will eat up all of your disk.

We just updated the related doc, could you check it again? Sorry for the confusion.

**Comment by yichengq** [comment]
ping @vtxyer

**Comment by xiang90** [comment]
I think @yichengq has answered the question pretty well. I am closing this. If you have any further question, feel free to ask.
