### ISSUE TITLE
Too many open files retrying in 1s

### ISSUE THREAD

**Issue by feicheche** [coreos/etcd#3151]
Hi,
I have a 5 nodes cluster.When i add a proxy it doesn't work well.
Here is my etcd proxy boot opts.
```
ETCD_OPTS="-proxy on -initial-cluster-token etcd-cluster -data-dir /data/etcd/ -initial-cluster infra1=http://192.168.1.2:2380,infra2=http://192.168.1.5:2380,infra3=http://192.168.1.6:2380,infra4=http://192.168.1.7:2380,infra5=http://192.168.1.8:2380 -advertise-client-urls http://172.30.42.1:4001,http://127.0.0.1:4001,http://172.30.42.1:2379,http://127.0.0.1:2379 -listen-client-urls http://172.30.42.1:4001,http://127.0.0.1:4001,http://172.30.42.1:2379,http://127.0.0.1:2379"
```
And the one of member nodes boot opts like this:
```
ETCD_OPTS="-name infra5 -initial-advertise-peer-urls http://192.168.1.8:2380 -listen-peer-urls http://192.168.1.8:2380 -initial-cluster-token etcd-cluster -initial-cluster infra1=http://192.168.1.2:2380,infra2=http://192.168.1.5:2380,infra3=http://192.168.1.6:2380,infra4=http://192.168.1.7:2380,infra5=http://192.168.1.8:2380 -initial-cluster-state existing -data-dir /data/etcd/ -advertise-client-urls http://172.30.42.1:4001,http://127.0.0.1:4001,http://172.30.42.1:2379,http://127.0.0.1:2379 -listen-client-urls http://172.30.42.1:4001,http://127.0.0.1:4001,http://172.30.42.1:2379,http://127.0.0.1:2379"
```
On the member node,run this command "etcdctl cluster-health" it show:
```
cluster is healthy
member 263907d174dd4a2e is healthy
member 6f123658aa23ee2f is healthy
member 2214a480a3a93e0b is healthy
member gder028790d3de6b is healthy
member cv236123431ba9db is healthy
```
But on the proxy node it hang,and many warning in the log
```
2015/07/18 00:00:10 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 320ms
2015/07/18 00:00:11 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 640ms
2015/07/18 00:00:11 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 1s
2015/07/18 00:00:12 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 1s
2015/07/18 00:00:13 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 1s
2015/07/18 00:00:14 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 1s
2015/07/18 00:00:15 proxy: failed to direct request to http://172.30.42.1:4001: read tcp 172.30.42.1:4001: use of closed network connection
2015/07/18 00:00:15 proxy: marked endpoint http://172.30.42.1:4001 unavailable
2015/07/18 00:00:15 http: Accept error: accept tcp 127.0.0.1:2379: too many open files; retrying in 5ms
2015/07/18 00:00:15 proxy: failed to direct request to http://172.30.42.1:4001: read tcp 172.30.42.1:4001: use of closed network connection
2015/07/18 00:00:15 proxy: failed to direct request to http://172.30.42.1:4001: read tcp 172.30.42.1:4001: use of closed network connection
2015/07/18 00:00:15 proxy: failed to direct request to http://172.30.42.1:4001: read tcp 172.30.42.1:4001: use of closed network connection
2015/07/18 00:00:15 proxy: failed to direct request to http://172.30.42.1:4001: read tcp 172.30.42.1:4001: use of closed network connection
2015/07/18 00:00:15 proxy: failed to direct request to http://172.30.42.1:4001: read tcp 172.30.42.1:4001: use of closed network connection
```
So how can i slove this problem? If can't , should i take a 7-nodes cluster or use something what proxy local 4001 port?

**Comment by yichengq** [comment]
You need to remove http://127.0.0.1:4001,http://127.0.0.1:2379 from --advertise-client-urls flag to make it work.

Proxy grabs all advertised client urls from the etcd cluster, and try to connect to the endpoint one by one. If it is told to connect to http://127.0.0.1:4001, it will proxy the request to itself, which results in infinite loop. Mostly it is useless to set localhost address as advertised url.

We are find ways to avoid this problem here: https://github.com/coreos/etcd/issues/2772

**Comment by feicheche** [comment]
@yichengq thank you, i remove http://127.0.0.1:4001,http://127.0.0.1:2379 from --advertise-client-urls flag. The first i run etcdctl cluster-health it's work well . But the second time it's hang again.The log show like this 
2015/07/18 00:49:58 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 160ms
2015/07/18 00:49:58 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 320ms
2015/07/18 00:49:59 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 640ms
2015/07/18 00:49:59 http: Accept error: accept tcp 172.30.42.1:4001: too many open files; retrying in 1s
2015/07/18 00:50:00 etcdserver: could not get cluster response from http://192.168.1.2:2380: Get http://192.168.1.2:2380/members: dial tcp 192.168.1.2:2380: too many open files
2015/07/18 00:50:00 etcdserver: could not get cluster response from http://192.168.1.5:2380: Get http://192.168.1.5:2380/members: dial tcp 192.168.1.5:2380: too many open files
2015/07/18 00:50:00 etcdserver: could not get cluster response from http://192.168.1.6:2380: Get http://192.168.1.6:2380/members: dial tcp 192.168.1.6:2380: too many open files
2015/07/18 00:50:00 etcdserver: could not get cluster response from http://192.168.1.7:2380: Get http://192.168.1.7:2380/members: dial tcp 192.168.1.7:2380: too many open files
2015/07/18 00:50:00 etcdserver: could not get cluster response from http://192.168.1.8:2380: Get http://192.168.1.8:2380/members: dial tcp 192.168.1.8:2380: too many open files

Please let me know if there is more info you need.Thanks you very much.

**Comment by yichengq** [comment]
Yes. please remove it from member node too. The member node registers the advertised urls into etcd cluster.

**Comment by feicheche** [comment]
Thank you @yichengq ,the cluster work well now, you’ve been a big help to me.
