### ISSUE TITLE
Cannot update member name and clientURLs via API

### ISSUE THREAD

**Issue by linfan** [coreos/etcd#3155]
It looks like all data except 'peerURLs' is ignored when adding new node into cluster, E.g.

```
$ curl http://127.0.0.1:2379/v2/members -XPOST -H "Content-Type: application/json" --data-ascii '{"clientURLs":["http://172.31.15.73:2379"], "name":"NewNode", "peerURLs":["http://172.31.15.73:2380"]}'
```

I specified also clientURLs and name when adding the node, but when I do list member, only peerURLs applied.

```
$ curl http://127.0.0.1:2379/v2/members
... {"id":"c01dce2d778dc21e","name":"","peerURLs":["http://172.31.15.73:2380"],"clientURLs":[]} ...
```

That's kind of "reasonable", but then I tried to update those values via PUT operation. And again only peerURLs value get updated:

```
$ curl http://127.0.0.1:2379/v2/members/c01dce2d778dc21e -XPUT -H "Content-Type: application/json" --data-ascii '{"clientURLs":["http://172.31.15.74:2379"], "name":"NewNode", "peerURLs":["http://172.31.15.74:2380"]}'

$ curl http://127.0.0.1:2379/v2/members
... {"id":"c01dce2d778dc21e","name":"","peerURLs":["http://172.31.15.74:2380"],"clientURLs":[]} ...
```

So I believe it's designed as that. But actually fleet have recognised all the nodes correctly (at least the name of the node):

```
$ etcdctl member list
81ac40c058724abf: name=289c44a9755044818c6e03a9c909882a peerURLs=http://172.31.14.96:2380 clientURLs=http://172.31.14.96:2379
bb63e3b152c238b9: name=0b98c08c5b4a464f9c43f6d0ef3454cc peerURLs=http://172.31.30.200:2380 clientURLs=http://172.31.30.200:2379
c202773e90d58251: name=513578c26d0f46388e38cc53afd7e4a7 peerURLs=http://172.31.14.97:2380 clientURLs=http://172.31.14.97:2379
c01dce2d778dc21e: name= peerURLs=http://172.31.15.1:2380 clientURLs=

$ fleetctl list-machines
MACHINE		IP		METADATA
0b98c08c...	172.31.30.200	-
289c44a9...	172.31.14.96	-
513578c2...	172.31.14.97	-
5a6b174d...	172.31.15.73	-

cluster is healthy
member 81ac40c058724abf is healthy
member bb63e3b152c238b9 is healthy
member c202773e90d58251 is healthy
member c01dce2d778dc21e is unhealthy
```

Also I tried to manually stop etcd2 service on that node, and restart with parameters `-listen-client-urls http://172.31.15.73:2379 -advertise-client-urls http://172.31.15.73:2379  -listen-peer-urls http://172.31.15.73:2380 -initial-advertise-peer-urls http://172.31.15.73:2380`, but it doesn't seems to work.

Question is, why etcd cannot correctly register this node, and what is the correct way to fully add a node into cluster?

**Comment by xiang90** [comment]
@linfan I think you have two questions:

1. how to correctly add a member into etcd

2. how to update client URL

To answer 1, please refer our doc at https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member

To answer 2, you can update client url by restart the member. The member will republish it information to the cluster while start.

**Comment by linfan** [comment]
> To answer 1, please refer our doc 

Yes, I was followed this doc. The different part was, I added the node via API and started the etcd2 in the new node via systemd, with below configure.

```
$ sudo systemctl cat etcd2
# /usr/lib64/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
LimitNOFILE=40000

# /run/systemd/system/etcd2.service.d/10-oem.conf
[Service]
Environment=ETCD_ELECTION_TIMEOUT=1200
# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://172.31.15.73:2379"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/8f8d4d1b584900a814a5a3cd26a51172"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.31.15.73:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://172.31.15.73:2380"
```

Is there anything suspicious?

> To answer 2, you can update client url by restart the member. 

Have tried that, both restart etcd2 service (`sudo systemctl restart etcd2`) and restart the node (`sudo reboot`).

But not since to work..

**Comment by xiang90** [comment]
> Yes, I was followed this doc. 

I mean you have to follow the doc strictly. You specify both `discovery` and `initial-cluster` flags. etcd will not accept that. You have to tell etcd exactly how you want it to bootstrap.

> Any suggestion?

You have to make sure the member is restarted correctly. A wrongly configured member will not even successfully join into the cluster.
