### ISSUE TITLE
New added node do not have clientURLs and name properly

### ISSUE THREAD

**Issue by linfan** [coreos/etcd#3156]
I was followed doc at https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member to add node into Etcd Cluster. While the clientURLs always recognised as empty in `etcdctl member list` result.

Have tried several times with both via Etcd API and etcdctl tool. Below is output from etcdtool:

```
core@ip-172-31-14-97 ~ $ etcdctl member add node04 http://172.31.15.73:2380
Added member named node04 with ID cb7b92d817788c90 to cluster
ETCD_NAME="node04"
ETCD_INITIAL_CLUSTER="289c44a9755044818c6e03a9c909882a=http://172.31.14.96:2380,0b98c08c5b4a464f9c43f6d0ef3454cc=http://172.31.30.200:2380,513578c26d0f46388e38cc53afd7e4a7=http://172.31.14.97:2380,node04=http://172.31.15.73:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"

core@ip-172-31-14-97 ~ $ etcdctl member list
81ac40c058724abf: name=289c44a9755044818c6e03a9c909882a peerURLs=http://172.31.14.96:2380 clientURLs=http://172.31.14.96:2379
bb63e3b152c238b9: name=0b98c08c5b4a464f9c43f6d0ef3454cc peerURLs=http://172.31.30.200:2380 clientURLs=http://172.31.30.200:2379
c202773e90d58251: name=513578c26d0f46388e38cc53afd7e4a7 peerURLs=http://172.31.14.97:2380 clientURLs=http://172.31.14.97:2379
cb7b92d817788c90: name= peerURLs=http://172.31.15.73:2380 clientURLs=
```

The Etcd in the new node was started up via systemd, with below configure. Please note that, I HAVE ADD THE NECESSARY VARIABLES IN THE CONF CUSTOMER FILE ` /run/systemd/system/etcd2.service.d/30-user.conf`.

```
$ sudo systemctl cat etcd2
# /usr/lib64/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
LimitNOFILE=40000

# /run/systemd/system/etcd2.service.d/10-oem.conf
[Service]
Environment=ETCD_ELECTION_TIMEOUT=1200
# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://172.31.15.73:2379"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/8f8d4d1b584900a814a5a3cd26a51172"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.31.15.73:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://172.31.15.73:2380"
# /run/systemd/system/etcd2.service.d/30-user.conf
[Service]
Environment="ETCD_NAME=node04"
Environment="ETCD_INITIAL_CLUSTER=289c44a9755044818c6e03a9c909882a=http://172.31.14.96:2380,0b98c08c5b4a464f9c43f6d0ef3454cc=http://172.31.30.200:2380,513578c26d0f46388e38cc53afd7e4a7=http://172.31.14.97:2380,node04=http://172.31.15.73:2380"
Environment="ETCD_INITIAL_CLUSTER_STATE=existing"
```

Have tried both restart etcd2 service (`sudo systemctl restart etcd2`) and restart the node (`sudo reboot`) after added the new node. But none of those solve the problem.

Do I made any mistake above? Or is there anything missing in the doc?

**Comment by linfan** [comment]
I find a error `etcd2[11820]: 2015/07/19 09:58:35 error verifying flags, multiple discovery or bootstrap flags` in etcd2's log.

Guess there are some flag conflict, I have removed the `ETCD_DISCOVERY` variable from '20-cloudinit.conf', the etcd2 start up on the new node. But it doesn't fix the issue still..

**Comment by xiang90** [comment]
@linfan 

As I mentioned before, the newly added member will publish its own information. You just need to start it. And then list the member again, you should see the published name and clientURL. 

I think you made a mistake somewhere. It should work.
