### ISSUE TITLE
raft: commit index should be tracked in `Progress`

### ISSUE THREAD

**Issue by tamird** [coreos/etcd#3170]
In the event of an empty append (used to advance the commit index) being rejected, the follower will appear to be caught up despite the commit index not having been advanced. In our experience, this can happen when replies arrive out of order, especially when testing with the new scheduler in go1.5beta1.

A resilient solution to this would probably require tracking the commit index in `Progress` and adding the commit index of the rejecting node to `MsgAppResp`. Some WIP code: https://github.com/tamird/etcd/tree/track-commit-progress

Continuation of #3111.

**Comment by xiang90** [comment]
@tamird Do we still want this happen?

**Comment by tamird** [comment]
We worked around this by ensuring that replies arrive in order, so it's not strictly needed for CockroachDB.z

**Comment by xiang90** [comment]
We do not need this neither.  We are trying to keep raft minimum. We can revisit this if other people have hard requirement or adding this feature will make their life MUCH easier.
