### ISSUE TITLE
Cluster node appears in member list, can't be removed

### ISSUE THREAD

**Issue by kieranmanning** [coreos/etcd#3182]
Hi. I started a three node cluster using the initial-cluster options and tried to add a fourth node, following the instructions at https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#add-a-member. I didn't cop that the example POST does not include a name variable. Should it? At any rate, I now can't remove that node from the node list. It shows up in `etcdctl member list` and through the API but I cannot remove it through either. 

	 curl -X GET <our-etcd-url>:4001/v2/members/
	{"members": [
		{"id":"19fb066f0e9fbad9","name":"<host1>","peerURLs":["<ipaddress1>:7001"],"clientURLs":["<ipaddress1>:4001"]},
		
		{"id":"1eeb57f0c047c949","name":"<host2>","peerURLs":["<ipaddress2>:7001"],"clientURLs":["<ipaddress2>:4001"]},
		
		{"id":"4e731f0f2f175c29","name":"","peerURLs":["http://<ipaddress4>:7001"],"clientURLs":[]},
		
		{"id":"ed0be6765092ead1","name":"<host4>","peerURLs":["<ipaddress3>:7001"],"clientURLs":["<ipaddress3>:4001"]}
		]
	}

	curl -X GET <our-etcd-url>:4001/v2/members/4e731f0f2f175c29
	{"message":"Not found"}

How can I remove the entry for this node, or update it such that it has a name and I can try start etcd on the machine in question? Also, should there be some validation on the member add API endpoint to prevent creating node entries without name?

**Comment by xiang90** [comment]
@kieranmanning You can go ahead and start the member. It will publish the name and client url information itself.

**Comment by kieranmanning** [comment]
Ah, cool. I had an error in my configuration as well so I didn't realize it picked up the name automatically. 

Thanks for the help, closing
