### ISSUE TITLE
The directory modifiedIndex doesn't change.

### ISSUE THREAD

**Issue by fatduo** [coreos/etcd#3188]
Hi, all
Why I change a node's value in a directory, the directory's modifiedIndex doesn't change.

In my project, I have persist all the global settings in database and a etcd directory. And I persist the etcd directory modifiedIndex in the database.
Now, I need a sync from database to etcd. I don't want to compare every node instead of the modifiedIndex of the directory

**Comment by fatduo** [comment]
@philips @xiang90

**Comment by yichengq** [comment]
> Why I change a node's value in a directory, the directory's modifiedIndex doesn't change.

This is the design of etcd store. If you want to know the difference between the database and etcd, you could watch on the directory and it will notify whenever there is a change: https://github.com/coreos/etcd/blob/master/Documentation/api.md#waiting-for-a-change

**Comment by xiang90** [comment]
@fatduo The modified index of a directory only changes when you add/remove nodes into/from it. @yichengq has an answer for your use case. I am closing this issue. If you have any further questions, please feel free to follow up. Thanks!
