### ISSUE TITLE
Timeline for v3 api

### ISSUE THREAD

**Issue by wojtek-t** [coreos/etcd#3191]
Do you have any timeline for v3 API:
https://github.com/coreos/etcd/blob/master/ROADMAP.md

In particular, when do you expect e.g. protocol-buffer API be supported (we are planning some work in Kubernetes now, so it would be good to have some rough estimates for it).

cc @xiang90 @yichengq

**Comment by xiang90** [comment]
Here is a rough roadmap with timeline: 

1. mid Sept. non-clustered demo version of v3 key-value api support
2. late Sept. basic client, watch api, leasing api support

Then we will see the feedback and the early adopters's timeline to decide:

1. release a not backward compatible version of etcd v3 as soon as possible and then fix the backward compatibility issue

2. or release a backward compatible version of etcd v3 (which takes more than than option 1)

/cc @philips @yichengq @kelseyhightower

**Comment by wojtek-t** [comment]
Thanks a lot for the update @xiang90 

FYI @timothysc @lavalamp @davidopp

**Comment by timothysc** [comment]
cc @eparis @smarterclayton - FYI on timeline.

**Comment by xiang90** [comment]
Closed by https://github.com/coreos/etcd/pull/3287
