### ISSUE TITLE
question re: etcd proxies and recommended production cluster architecture

### ISSUE THREAD

**Issue by krancour** [coreos/etcd#3192]
Seeking some minor clarification.

Is the recommended production cluster architecture documented here no longer necessary for the sake of performance with recent versions of etcd due to the fact that when using discovery, nodes > the number of nodes in the cluster automatically run etcd as a proxy?

https://coreos.com/os/docs/latest/cluster-architectures.html#production-cluster-with-central-services

**Comment by krancour** [comment]
After some experimentation, I think I can answer my own question now.  It seems that if a leader or follower dies, no proxy is ever promoted to fill the gap in the cluster.  I guess that would mean the architecture documented above is still recommended (but correct me if I am wrong) so that the actual etcd cluster running on a small, fixed number of nodes can be HA on its own, while the proxies that run elsewhere are purely for the convenience of other services and containers that need to connect to etcd.

**Comment by yichengq** [comment]
The recommended production cluster architecture suggests that production cluster should use dedicated machines for etcd members to ensure its hardware resources to work well. This is critical to prevent etcd member down. Your understanding for this is correct.

The fall-back-to-proxy behavior simplifies the use case that lots of etcd process are bootstrapped using the same discovery token and users expect that they could send requests to all.

There is no automatic promotion or removal of etcd member. Users are expected to do it explicitly through etcdctl or HTTP API.
