### ISSUE TITLE
use fast unmarshalJson code in etcd/client

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3193]
from https://github.com/coreos/go-etcd/pull/218

`ugorji codec` is a preferred choice.

It is critical for latency requirement in k8s scenario. We plan to let k8s use etcd/client instead of go-etcd, so this needs to be improved.

/cc @fgrzadkowski @bcwaldon

**Comment by wojtek-t** [comment]
We should reevalute if ugorij code is still the best. We've seen in some place that ffjson can now be faster. We should reevaluate it and use the better one.

**Comment by timothysc** [comment]
cc @eparis probably want to cc Jan
