### ISSUE TITLE
improve the error returned from getLeaderStatus in etcdctl/cluster-health

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3201]
from https://github.com/coreos/etcd/pull/3178#discussion_r35718487

**Comment by xiang90** [comment]
I think I can help on this one.

**Comment by xiang90** [comment]
@yichengq We have to give more thought on this. So I am moving this to 2.2rc0

**Comment by xiang90** [comment]
closed via https://github.com/coreos/etcd/pull/3323
