### ISSUE TITLE
Clarity on how to run etcd-migrate on CoreOS cluster

### ISSUE THREAD

**Issue by fmaldonado-scea** [coreos/etcd#3205]
From the documentation, it sounds like the etcd-migrate tool is for distros that you install etcd on but not so much for CoreOS which comes with etcd.  The instructions do not seem possible on CoreOS, but it could be possible that I just do not understand how to run go code on CoreOS.  

https://github.com/coreos/etcd/tree/master/tools/etcd-migrate

**Comment by yichengq** [comment]
etcd 2.0 will detect 0.4.x data dir and update the data automatically (while leaving a backup, in case of emergency). So you don't need to manually run the go code to do it.

**Comment by yichengq** [comment]
it is documented here: https://github.com/coreos/etcd/blob/master/Documentation/backward_compatibility.md#data-directory-migration And snapshot migration is preferred because it could be more straightforward.

**Comment by fmaldonado-scea** [comment]
OK understood.  Thanks, thats actually the route I was going.  Is it possible to, stop etcd, start etcd2.0, then import snapshot using the same discovery token?  Also does the snapshot import need to be done on all nodes.

**Comment by yichengq** [comment]
It is possible to do what you have mentioned, but i don't understand the discovery token part. The workflow could be : 1. make snapshot from etcd0.4 2. stop etcd0.4 cluster 3. start brand-new etcd2.0 cluster using new discovery token 4. import snapshot into the etcd2.0 cluster

snapshot import just needs to run once.

**Comment by fmaldonado-scea** [comment]
OK understood.  Thanks.
