### ISSUE TITLE
Adding a new member kills the cluster.

### ISSUE THREAD

**Issue by damm** [coreos/etcd#3206]
Etcd 2.1.1; using DNS Discovery.  

```
2015-08-01_01:08:58.60949 2015/07/31 20:08:58 rafthttp: request sent was ignored (cluster ID mismatch: remote[f92953d55e622c7f]=5f72a9421d9f31ec, local=f709fd0e454bd1c6)
2015-08-01_01:08:58.62109 2015/07/31 20:08:58 rafthttp: request sent was ignored (cluster ID mismatch: remote[4df6172802fb1f9d]=5f72a9421d9f31ec, local=f709fd0e454bd1c6)
2015-08-01_01:08:58.62111 2015/07/31 20:08:58 rafthttp: failed to write 4df6172802fb1f9d on pipeline (cluster ID mismatch)
```

**Comment by xiang90** [comment]
You misconfigured your cluster. Discovery is only used for bootstrapping. Adding member requires a total different process. etcd successfully protect you from corrupting the cluster.

Check https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md for adding members.

Check https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md for filing a better bug report.

Thanks.

**Comment by damm** [comment]
I'm bootstrapping a new node; I have never in the past had to add the member using etcdctl; in fact I tried  and found it broke my cluster more often than just adding them to discovery.

**Comment by xiang90** [comment]
@damm 

> just adding them to discovery
As I mentioned, you should never use discovery to add a member. etcd2 can never let you do that. 

I am pretty sure you can successfully add a member into an existing cluster if you follow the doc.  If you have a problem, please file a issue with required information.

**Comment by xiang90** [comment]
> I have never in the past had to add the member using etcdct

I have no idea how you successfully did this for etcd2. We have never provided this feature.

**Comment by damm** [comment]
Maybe I had a ghost behind me fixing my work; but I don't think so.

1. Backup the cluster using etcdctl
1. Ensure DNS records exist; add new server to the DNS Discovery
1. Install etcd and run it; 

Command line is basically as follows.

```shell
./etcd -name #{node.name} -discovery-srv example.net -initial-advertise-peer-urls http://#{node.name}.example.net:2380 -initial-cluster-token etcd-example-1 -initial-cluster-state existing -advertise-client-urls http://0.0.0.0:2379 --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379 -cors '*'
```

I think as of 2.1 I have a few too many options; but has worked since 2.0.x; I have never been able to use `etcdctl member add` successfully; I always get cluster id mismatches.

**Comment by xiang90** [comment]
> I think as of 2.1 I have a few too many options; but has worked since 2.0.x;

You have only one option to add a member into etcd. And that is through runtime configuration API.

>  I have never been able to use etcdctl member add successfully; I always get cluster id mismatches.

If you do not want to follow what we designed and the doc, you will always get this error. It has nothing to do with 2.0 or 2.1. They are the same around runtime reconfiguration. 

I cannot really help you unless you would like to read through the doc and follow it first.

**Comment by damm** [comment]
That's fine I'll break my etcd cluster more and report more bugs; and hopefully you can dismiss them.

In the future; ask more soft questions and don't immediately dismiss someones bug report and close it.  You will get farther.
