### ISSUE TITLE
client: cancelling a Watcher causes ClusterError read tcp error

### ISSUE THREAD

**Issue by mwitkow** [coreos/etcd#3209]
With the following watching code 
```go
	for u.watching {
		resp, err := watcher.Next(u.context)
		if clusterErr, ok := err.(*etcd.ClusterError); ok {
			u.logger.Printf("!!! Got ClusterErr: %v", clusterErr.Errors)
			if len(clusterErr.Errors) > 0 && clusterErr.Errors[0] == context.Canceled {
				break
			} else {
				continue
			}
		}
      // do something else
   }
   u.logger.Printf("Exiting watch.")
```

When `context.cancel()` is called from a different thread, I get a tcp net dial first:
```
!! Got ClusterErr: [read tcp 127.0.0.1:57824: use of closed network connection]
!!! Got ClusterErr: [context canceled]
Exiting watch.
```

I think that the only think printed here should be `context.Cancelled`. Cancelling a watcher context shouldn't tear down the connection.

See https://github.com/coreos/etcd/issues/3208 for context.

**Comment by mwitkow-io** [comment]
Thanks for the quick fix, will poke around to see if it fixes my issue later this week! :)

**Comment by mwitkow** [comment]
Unfortunately this seems to be back after 2.3.0
"etcd ClusterError. Will retry. error #0: context canceled"

**Comment by gyuho** [comment]
Ok just got it reproduced `client: etcd cluster is unavailable or misconfigured` when canceling watch context. Will fix shortly.

**Comment by gyuho** [comment]
@mwitkow Thanks for reporting. I checked the release 2.3 also has this issue.

Please try with master branch. Should be fixed.
