### ISSUE TITLE
ETCD auth role problem

### ISSUE THREAD

**Issue by fatduo** [coreos/etcd#3212]
I used ETCD auth. (Enable auth and revoke all permissions of guest role)

1. Add r1 role
PUT: /v2/auth/roles/r1
{"role": "r1", "permissions": {"kv": {"read": ["/config/globalsetting/* "]}}}
response：
{"role":"r1","permissions":{"kv":{"read":["/config/globalsetting/* "],"write":null}}}

2. Add r2 role
PUT: /v2/auth/roles/r2
{"role": "r2", "permissions": {"kv": {"read": ["/config/servicecluster/7/* "]}}}
response：
{"role":"r2","permissions":{"kv":{"read":["/config/servicecluster/7/* "],"write":null}}}

3. Add user u1
PUT: /v2/auth/users/u1
{"user" : "u1", "password" : "u1"}
response:
{"user":"u1","roles":null}

4. Grant r2 to u1
PUT: /v2/auth/users/u1
{"user": "u1", "grant": ["r2"]}
response:
{"user":"u1","roles":["r2"]}

5. Use user u1 to visit the node
GET: /v2/keys/config/servicecluster/7/
header： Authorization: Basic dTE6dTE=             (base64 u1:u1)
Response Status 200 OK

6. Grant r1 to u1
PUT: /v2/auth/users/u1
{"user": "u1", "grant": ["r1"]}
response:
{"user":"u1","roles":["r1","r2"]}

7. Use user u1 to visit the same node
GET: /v2/keys/config/servicecluster/7/
header： Authorization: Basic dTE6dTE=             (base64 u1:u1)
Response Status 401 Unauthorized

8. Use user u1 to visit the node
GET: /v2/keys/config/globalsetting/
header： Authorization: Basic dTE6dTE=             (base64 u1:u1)
Response Status 200 OK

When u1 just have r2 role, it can visit r2's path.
Why does u1 have both r1 and r2 roles, it can visit r1's path, cannot visit r2's path?
And I add a role called r0, r1 and r2 roles are both useless.

**Comment by yichengq** [comment]
I tried to reproduce this on the official etcd 2.1.1 but failed:
```
unihorn@CoreOS ~/g/s/g/c/etcd> curl http://root:root@127.0.0.1:4001/v2/auth/roles/r1
{"role":"r1","permissions":{"kv":{"read":["/config/globalsetting/*"],"write":null}}}
unihorn@CoreOS ~/g/s/g/c/etcd> curl http://root:root@127.0.0.1:4001/v2/auth/roles/r2
{"role":"r2","permissions":{"kv":{"read":["/config/globalsetting/7/*"],"write":null}}}
unihorn@CoreOS ~/g/s/g/c/etcd> curl -XPUT http://root:root@127.0.0.1:4001/v2/auth/users/u1 -d '{"user":"u1","password":"u1"}'
{"user":"u1","roles":null}
unihorn@CoreOS ~/g/s/g/c/etcd> curl -XPUT http://root:root@127.0.0.1:4001/v2/auth/users/u1 -d '{"user": "u1", "grant": ["r2"]}'
{"user":"u1","roles":["r2"]}
unihorn@CoreOS ~/g/s/g/c/etcd> curl http://u1:u1@127.0.0.1:4001/v2/keys/config/globalsetting/7/
{"action":"get","node":{"key":"/config/globalsetting/7","dir":true,"nodes":[{"key":"/config/globalsetting/7/1","value":"","modifiedIndex":20,"createdIndex":20}],"modifiedIndex":20,"createdIndex":20}}
unihorn@CoreOS ~/g/s/g/c/etcd> curl -XPUT http://root:root@127.0.0.1:4001/v2/auth/users/u1 -d '{"user": "u1", "grant": ["r1"]}'
{"user":"u1","roles":["r1","r2"]}
unihorn@CoreOS ~/g/s/g/c/etcd> curl http://u1:u1@127.0.0.1:4001/v2/keys/config/globalsetting/7/
{"action":"get","node":{"key":"/config/globalsetting/7","dir":true,"nodes":[{"key":"/config/globalsetting/7/1","value":"","modifiedIndex":20,"createdIndex":20}],"modifiedIndex":20,"createdIndex":20}}
unihorn@CoreOS ~/g/s/g/c/etcd> curl http://u1:u1@127.0.0.1:4001/v2/keys/config/globalsetting/
{"action":"get","node":{"key":"/config/globalsetting","dir":true,"nodes":[{"key":"/config/globalsetting/7","dir":true,"modifiedIndex":20,"createdIndex":20}],"modifiedIndex":20,"createdIndex":20}}
```
Could you check your etcd version? Could you reproduce it on single-member etcd cluster?

**Comment by yichengq** [comment]
And I observe that you use `/config/servicecluster/` sometimes in your workflow. Is this a typo?

**Comment by fatduo** [comment]
Hi, @yichengq 
This is not a typo. Role r1 has /config/globalsetting/* read path and role r2 has /config/servicecluster/7/* read path.
PLS reproduce it using these two roles.
Thanks

**Comment by fatduo** [comment]
Hi, @yichengq 
Simplify the problem, suppose a role called role1 and it's read_path is "/rolePath1" and another role called role2 and it's read_path is "/rolePath2".
When I grant both role1 and role2 to a user, the user only can visit "/rolePath1". role2 is useless.

**Comment by yichengq** [comment]
@fatduo I could reproduce it now. It is a bug, and I will fix it.
