### ISSUE TITLE
`etcdctl ls` fails with "Error:  key required"

### ISSUE THREAD

**Issue by SamuelMarks** [coreos/etcd#3218]
```
$ etcdctl ls
Error:  key required
$ echo $?
1
```

Confirmed that it's an issue with `etcdctl` not `etcd`.

FYI: Latest commit where this error is still occurring is => ff5c3469c1d93bc7bd340d755cb7208826a65356

**Comment by xiang90** [comment]
As the error suggests, you need to specify the `key`. 
```
etcdctl ls /
```

or 

```
etcd ls /foo
```

**Comment by SamuelMarks** [comment]
But it works without the `/` in the 2.1.0 version (and earlier). Any chance of recovering that functionality?

**Comment by xiang90** [comment]
@SamuelMarks Hmm... Ok. It is possible. We probably will change it back.

**Comment by gouyang** [comment]
:+1:

**Comment by SamuelMarks** [comment]
:+1:
