### ISSUE TITLE
Issue with floating IP

### ISSUE THREAD

**Issue by gangadhars** [coreos/etcd#3226]
I have two machines, one is ubuntu VM and the other one is Openstack Ubuntu instance with floating IP. 
```
vs02 - 172.16.2.64
ubuntu1 - 10.0.0.2 (floating IP: 172.16.2.10) 
```
When I run the kuberntes cluster it's giving error on ubuntu1 node
```
ubuntu1:~# tail /var/log/upstart/etcd.log -f
2015/08/05 06:20:29 etcd: no data-dir provided, using default data-dir ./infra1.etcd
2015/08/05 06:20:29 etcd: listen tcp 172.16.2.10:2380: bind: cannot assign requested address
2015/08/05 06:20:29 etcd: no data-dir provided, using default data-dir ./infra1.etcd
2015/08/05 06:20:29 etcd: listen tcp 172.16.2.10:2380: bind: cannot assign requested address
2015/08/05 06:20:29 etcd: no data-dir provided, using default data-dir ./infra1.etcd
2015/08/05 06:20:29 etcd: listen tcp 172.16.2.10:2380: bind: cannot assign requested address
2015/08/05 06:20:29 etcd: no data-dir provided, using default data-dir ./infra1.etcd
```
How to solve this problem.

**Comment by yichengq** [comment]
You cannot let etcd listen on some address that it cannot assign address. You could let etcd listen on some address at -listen-peer-urls while let other etcds find it through -initial-advertise-peer-urls.

**Comment by gangadhars** [comment]
Have two nodes.
vs02- 172.16.2.64
ubuntu3 - 10.0.0.3 (openstack instance, floating ip: 172.16.2.10)

etcd options at vs02:
```
ETCD_OPTS="-name infra0   -initial-advertise-peer-urls http://172.16.2.64:2380   -listen-peer-urls http://172.16.2.64:2380   -initial-cluster-token etcd-cluster-1   -initial-cluster infra0=http://172.16.2.64:2380,infra1=http://172.16.2.10:2380   -initial-cluster-state new"
```
etcd options at ubuntu3:
```
ETCD_OPTS="-name infra1   -initial-advertise-peer-urls http://172.16.2.10:2380   -listen-peer-urls http://172.16.2.10:2380   -initial-cluster-token etcd-cluster-1   -initial-cluster infra0=http://172.16.2.64:2380,infra1=http://172.16.2.10:2380   -initial-cluster-state new"
```
etcd log says at ubuntu3:
```
2015/08/06 06:30:15 etcd: no data-dir provided, using default data-dir ./infra1.etcd
2015/08/06 06:30:15 etcd: listen tcp 172.16.2.10:2380: bind: cannot assign requested address
```

As you **suggested**, I canged the etcd configuration on ubuntu3 and now it's looks like:
```
ETCD_OPTS="-name infra1   -initial-advertise-peer-urls http://172.16.2.10:2380   -listen-peer-urls http://10.0.0.3:2380   -initial-cluster-token etcd-cluster-1   -initial-cluster infra0=http://172.16.2.64:2380,infra1=http://172.16.2.10:2380   -initial-cluster-state new"
```
Now logs at ubuntu3:
```
2015/08/06 06:43:54 raft: 98c13df7d9712b4f is starting a new election at term 18
2015/08/06 06:43:54 raft: 98c13df7d9712b4f became candidate at term 19
2015/08/06 06:43:54 raft: 98c13df7d9712b4f received vote from 98c13df7d9712b4f at term 19
2015/08/06 06:43:54 raft: 98c13df7d9712b4f [logterm: 1, index: 2] sent vote request to 70b3f0738a41bdd7 at term 19
2015/08/06 06:43:55 etcdserver: publish error: etcdserver: request timed out
2015/08/06 06:43:55 raft: 98c13df7d9712b4f is starting a new election at term 19
2015/08/06 06:43:55 raft: 98c13df7d9712b4f became candidate at term 20
2015/08/06 06:43:55 raft: 98c13df7d9712b4f received vote from 98c13df7d9712b4f at term 20
2015/08/06 06:43:55 raft: 98c13df7d9712b4f [logterm: 1, index: 2] sent vote request to 70b3f0738a41bdd7 at term 20
```
logs at vs02:
```
2015/08/05 23:45:03 raft: 70b3f0738a41bdd7 is starting a new election at term 640
2015/08/05 23:45:03 raft: 70b3f0738a41bdd7 became candidate at term 641
2015/08/05 23:45:03 raft: 70b3f0738a41bdd7 received vote from 70b3f0738a41bdd7 at term 641
2015/08/05 23:45:03 raft: 70b3f0738a41bdd7 [logterm: 1, index: 2] sent vote request to 98c13df7d9712b4f at term 641
2015/08/05 23:45:03 raft: 70b3f0738a41bdd7 [term: 641] ignored a MsgVote message with lower term from 98c13df7d9712b4f [term: 58]
2015/08/05 23:45:04 raft: 70b3f0738a41bdd7 is starting a new election at term 641
2015/08/05 23:45:04 raft: 70b3f0738a41bdd7 became candidate at term 642
2015/08/05 23:45:04 raft: 70b3f0738a41bdd7 received vote from 70b3f0738a41bdd7 at term 642
2015/08/05 23:45:04 raft: 70b3f0738a41bdd7 [logterm: 1, index: 2] sent vote request to 98c13df7d9712b4f at term 642
2015/08/05 23:45:04 raft: 70b3f0738a41bdd7 [term: 642] ignored a MsgVote message with lower term from 98c13df7d9712b4f [term: 59]
```

Thanks

**Comment by yichengq** [comment]
It has network problem between infra0 and infra1. infra1 cannot send message to infra0. Could you try to let infra1 ping to infra0's advertise-peer-urls http://172.16.2.64:2380?

**Comment by yichengq** [comment]
Close this due to low activity. Feel free to continue discussion if it is still a problem.

**Comment by sgysz** [comment]
为啥不用中文讨论？

**Comment by mg459046365** [comment]
怎么解决的啊，我的也会出现这个问题
2017-12-28 17:27:11.625937 I | etcdmain: etcd Version: 3.2.0+git
2017-12-28 17:27:11.626022 I | etcdmain: Git SHA: GitNotFound
2017-12-28 17:27:11.626027 I | etcdmain: Go Version: go1.9.2
2017-12-28 17:27:11.626032 I | etcdmain: Go OS/Arch: darwin/amd64
2017-12-28 17:27:11.626037 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2017-12-28 17:27:11.626046 N | etcdmain: failed to detect default host (default host not supported on darwin_amd64)
2017-12-28 17:27:11.626055 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2017-12-28 17:27:11.627977 C | etcdmain: listen tcp 211.98.71.195:2380: bind: can't assign requested address

**Comment by daiyoung** [comment]
@mg459046365 将master节点的DNS改成223.5.5.5(只要是非运营商提供的DNS都可以，如4个114，4个8等)试试，参考 https://github.com/coreos/etcd/issues/7559 While binding socket to 'localhost' it's always resolved by DNS servers only

**Comment by vgoldani** [comment]
Did anyone manage to fix this?

**Comment by vgoldani** [comment]
Im running a Bare Metal Ubuntu Server trying to make it work with a Openstack Ubuntu Instance

**Comment by hexfusion** [comment]
@vgoldani please open a new issue with full details of your problem including etcd startup logs and we can take a look.

**Comment by hongjyan** [comment]
have the same problem. Open [issue-10274](https://github.com/etcd-io/etcd/issues/10274)
