### ISSUE TITLE
Tiny issue with text formatting

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#3228]
When run etcd as proxy, it shows odd path for datadir:
```
etcdmain: proxy: using peer urls [http://192.168.122.67:2380] from cluster file .//var/lib/etcd2/proxy/cluster
```

https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L307

@yichengq @xiang90

**Comment by yichengq** [comment]
I think it is fine to remove `./` in all similar lines.
