### ISSUE TITLE
Keys command: Non-uniform behavior

### ISSUE THREAD

**Issue by rhuangab** [coreos/etcd#3230]
I am trying out etcd recently. I am confused by some edge cases about key commands.
Why do these two commands have different behaviors?
I can ***change a file to a directory*** with the following command:

    > curl localhost:4001/v2/keys/file?value=1 -XPUT
    {"action":"set","node":{"key":"/file","value":"1","modifiedIndex":124,"createdIndex":124}}
    > curl localhost:4001/v2/keys/file?dir=true -XPUT
    {"action":"set","node":{"key":"/file","dir":true,"modifiedIndex":125,"createdIndex":125},"prevNode":{"key":"/file","value":"1","modifiedIndex":124,"createdIndex":124}}

But if I add a `prevExist=true` here, it will ignore my `dir=true` tag, and just erase the `value` of `/file` into ***empty string***.

    > curl localhost:4001/v2/keys/file?value=1 -XPUT
    {"action":"set","node":{"key":"/file","value":"1","modifiedIndex":127,"createdIndex":127}}
    > curl 'localhost:4001/v2/keys/file?dir=true&prevExist=true' -XPUT
    {"action":"update","node":{"key":"/file","value":"","modifiedIndex":128,"createdIndex":127},"prevNode":{"key":"/file","value":"1","modifiedIndex":127,"createdIndex":127}}

Could you please explain me about this? Is it designed to behave in this way? If not, which one is the standard way?

**Comment by yichengq** [comment]
In the first case, the key is replaced totally, instead of update. You could check that the createdIndex in the second one is 125, which indicates it is a totally new key.

The second case assumes that you are working on a non-dir key. So it ignores `dir=true`, and parse `prevExist=true` to update the existing key. Because you don't give `value`, it sets the value to empty string.

**Comment by yichengq** [comment]
I suppose that you have read the answer and feel satisfied about it. Feel free to continue discussion here.

**Comment by rhuangab** [comment]
Yes, your answer make me more clear about it. Thanks!
