### ISSUE TITLE
etcd GPG signature 2.1.1

### ISSUE THREAD

**Issue by breser** [coreos/etcd#3234]
Can't find the key anywhere that this is signed with.  

$ gpg --verify ~/Downloads/etcd-v2.1.1-linux-amd64.tar.gz.gpg
gpg: Signature made Tue Jul 21 10:49:33 2015 PDT using RSA key ID CC22F12F
gpg: requesting key CC22F12F from hkps server hkps.pool.sks-keyservers.net
gpgkeys: key 8556AC44CC22F12F not found on keyserver
gpg: DBG: armor-keys-failed (KEY 0x8556AC44CC22F12F BEGIN
) ->0
gpg: DBG: armor-keys-failed (KEY 0x8556AC44CC22F12F FAILED 6
) ->6
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: Not found
gpg: keyserver communications error: Bad public key
gpg: Can't check signature: No public key

**Comment by yichengq** [comment]
I have uploaded my key to the sks-keyservers. Please check it again.
