### ISSUE TITLE
no errorCode returned from etcd, only message is returned, which is a problem for clients

### ISSUE THREAD

**Issue by raoofmd** [coreos/etcd#3235]
I wrote a http client in java which reads response in a json object.

I decide whether it is a success(I'm able to retrieve a value for a key) or failure based on errorCode, but I see that it doesn't always return an errorCode and just returns a message.

I dont think I should be doing this

	public boolean isError() {
		if (errorCode != null || message != null)
			return true;
		return false;
	}

I should only be doing this

	public boolean isError() {
		if (errorCode != null)
			return true;
		return false;
	}

**Example: Below response doesn't have errorCode**
{"message":"Insufficient credentials"}
Error response from etcd: ETCDResult [action=null, node=null, prevNode=null, errorCode=null, message=Insufficient credentials, cause=null, index=0]

Whereas this is how it should be
{"errorCode":100,"message":"Key not found","cause":"/test/api/123/dev/_secrets","index":72}

{"errorCode":104,"message":"Not a directory","cause":"/test/api/123/dev/_secret","index":72}

Comments?

**Comment by xiang90** [comment]
I mark it as a bug. And we will fix it.

**Comment by raoofmd** [comment]
@xiang90 Thanks. I'm petty sure you got what I meant but I'll still clarify it further.

I didn't mean only the message {"message":"Insufficient credentials"} but I mean that if etcd is not returning value of a key then it should return an errorCode. 

If there is no direct mapping for a faiure message to errrorCode then it should still be sending a default errorCode always.
