### ISSUE TITLE
all peers think all other peer connections are unhealthy

### ISSUE THREAD

**Issue by dannysauer** [coreos/etcd#3236]
Standing up an etcd 2.1.1 cluster on RHEL6 results in each etcd reporting this:

    rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy

for every other node in the cluster (with different node IDs for each other node, of course).  All nodes have problems with every other node.  The etcdctl cluster-health command reports messages like `raft is making progress [match: 146378->146380]` for all nodes, with identical values for each node.  The values continue increasing at a rate of roughly 12-13 every five seconds.  For a 5-node cluster running on five separate machines, it therefore looks like this:

    cluster is healthy: raft is making progress [commit index: 146500->146502]
    leader is 126d709c680387a5
    member 126d709c680387a5 is healthy: raft is making progress [match: 146500->146502]
    member 70e10bfbc55ed7a6 is healthy: raft is making progress [match: 146500->146502]
    member a238e808898348 is healthy: raft is making progress [match: 146500->146502]
    member aba177af7981101a is healthy: raft is making progress [match: 146500->146502]
    member fe214d33383f27e0 is healthy: raft is making progress [match: 146500->146502]

I can reproduce this down to a 2-node cluster running on different ports on the same machine.  I've packaged up my local builds of go and etcd (both from current git tags) in RPMs, and would be happy to provide those RPMs (offline; I can't make them public) to someone who wanted to duplicate this setup using a throw-away CentOS 6 build or something.  There's a little more information at https://groups.google.com/forum/#!topic/etcd-dev/elCUk0rQ1CE; please ask if I can provide anything else useful.

Version information:

    $ /srv/etcd/bin/etcd --version
    etcd Version: 2.1.1+git
    Git SHA: 487639b
    Go Version: go1.4
    Go OS/Arch: linux/amd64

    $ lsb_release -a
    LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch    Distributor ID: RedHatEnterpriseServer
    Description:    Red Hat Enterprise Linux Server release 6.6 (Santiago)
    Release:        6.6
    Codename:       Santiago

    $ uname -a
    Linux st74cf01 2.6.32-504.12.2.el6.x86_64 #1 SMP Sun Feb 1 12:14:02 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

Example of starting a 2-node cluster which consistently exhibits the behavior on this system:
  node 1:

    /srv/etcd/bin/etcd \
      --name $(hostname -s)1 \
      --data-dir /tmp/etcd_localtestt_1 \
      --listen-peer-urls   "http://$(hostname -s):2390" \
      --listen-client-urls "http://localhost:2389,http://$(hostname -s):2389" \
      --advertise-client-urls "http://$(hostname -s):2389" \
      \
      --initial-cluster-token 'localtest' \
      --initial-advertise-peer-urls "http://$(hostname -s):2390" \
      --initial-cluster "$(hostname -s)1=http://$(hostname -s):2390,$(hostname -s)2=http://$(hostname -s):2391" \
      --initial-cluster-state 'new'
    2015/08/6 14:09:53 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
    2015/08/6 14:09:53 etcdmain: listening for peers on http://st74cf01:2390
    2015/08/6 14:09:53 etcdmain: listening for client requests on http://localhost:2389
    2015/08/6 14:09:53 etcdmain: listening for client requests on http://st74cf01:2389
    2015/08/6 14:09:53 etcdserver: name = st74cf011
    2015/08/6 14:09:53 etcdserver: data dir = /tmp/etcd_localtestt_1
    2015/08/6 14:09:53 etcdserver: member dir = /tmp/etcd_localtestt_1/member
    2015/08/6 14:09:53 etcdserver: heartbeat = 100ms
    2015/08/6 14:09:53 etcdserver: election = 1000ms
    2015/08/6 14:09:53 etcdserver: snapshot count = 10000
    2015/08/6 14:09:53 etcdserver: advertise client URLs = http://st74cf01:2389
    2015/08/6 14:09:53 etcdserver: initial advertise peer URLs = http://st74cf01:2390
    2015/08/6 14:09:53 etcdserver: initial cluster = st74cf011=http://st74cf01:2390,st74cf012=http://st74cf01:2391
    2015/08/6 14:09:53 etcdserver: starting member 8887eaf3e329a3f8 in cluster 9e94874682ff203f
    2015/08/6 14:09:53 raft: 8887eaf3e329a3f8 became follower at term 0
    2015/08/6 14:09:53 raft: newRaft 8887eaf3e329a3f8 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
    2015/08/6 14:09:53 raft: 8887eaf3e329a3f8 became follower at term 1
    2015/08/6 14:09:53 etcdserver: starting server... [version: 2.1.1+git, cluster version: to_be_decided]
    2015/08/6 14:09:53 etcdserver: added member 830bc2abd256fd30 [http://st74cf01:2391] to cluster 9e94874682ff203f
    2015/08/6 14:09:53 etcdserver: added local member 8887eaf3e329a3f8 [http://st74cf01:2390] to cluster 9e94874682ff203f
    2015/08/6 14:09:53 rafthttp: the connection with 830bc2abd256fd30 became active
    2015/08/6 14:09:54 raft: 8887eaf3e329a3f8 [term: 1] received a MsgVote message with higher term from 830bc2abd256fd30 [term: 4]
    2015/08/6 14:09:54 raft: 8887eaf3e329a3f8 became follower at term 4
    2015/08/6 14:09:54 raft: 8887eaf3e329a3f8 [logterm: 1, index: 2, vote: 0] voted for 830bc2abd256fd30 [logterm: 1, index: 2] at term 4
    2015/08/6 14:09:54 raft: raft.node: 8887eaf3e329a3f8 elected leader 830bc2abd256fd30 at term 4
    2015/08/6 14:09:54 etcdserver: published {Name:st74cf011 ClientURLs:[http://st74cf01:2389]} to cluster 9e94874682ff203f
    2015/08/6 14:09:54 etcdserver: set the initial cluster version to 2.1.0
    2015/08/6 14:10:23 rafthttp: the connection to peer 830bc2abd256fd30 is unhealthy
    2015/08/6 14:10:53 rafthttp: the connection to peer 830bc2abd256fd30 is unhealthy
    2015/08/6 14:11:23 rafthttp: the connection to peer 830bc2abd256fd30 is unhealthy
    2015/08/6 14:11:53 rafthttp: the connection to peer 830bc2abd256fd30 is unhealthy

  node 2:

    /srv/etcd/bin/etcd \
      --name $(hostname -s)2 \
      --data-dir /tmp/etcd_localtestt_2 \
      --listen-peer-urls   "http://$(hostname -s):2391" \
      --listen-client-urls "http://localhost:2388,http://$(hostname -s):2388" \
      --advertise-client-urls "http://$(hostname -s):2389" \
      \
      --initial-cluster-token 'localtest' \
      --initial-advertise-peer-urls "http://$(hostname -s):2391" \
      --initial-cluster "$(hostname -s)1=http://$(hostname -s):2390,$(hostname -s)2=http://$(hostname -s):2391" \
      --initial-cluster-state 'new'
    2015/08/6 14:09:50 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 4
    2015/08/6 14:09:50 etcdmain: listening for peers on http://host1:2391
    2015/08/6 14:09:50 etcdmain: listening for client requests on http://localhost:2388
    2015/08/6 14:09:50 etcdmain: listening for client requests on http://host1:2388
    2015/08/6 14:09:50 etcdserver: name = host12
    2015/08/6 14:09:50 etcdserver: data dir = /tmp/etcd_localtestt_2
    2015/08/6 14:09:50 etcdserver: member dir = /tmp/etcd_localtestt_2/member
    2015/08/6 14:09:50 etcdserver: heartbeat = 100ms
    2015/08/6 14:09:50 etcdserver: election = 1000ms
    2015/08/6 14:09:50 etcdserver: snapshot count = 10000
    2015/08/6 14:09:50 etcdserver: advertise client URLs = http://host1:2389
    2015/08/6 14:09:50 etcdserver: initial advertise peer URLs = http://host1:2391
    2015/08/6 14:09:50 etcdserver: initial cluster = host11=http://host1:2390,host12=http://host1:2391
    2015/08/6 14:09:50 etcdserver: starting member 830bc2abd256fd30 in cluster 9e94874682ff203f
    2015/08/6 14:09:50 raft: 830bc2abd256fd30 became follower at term 0
    2015/08/6 14:09:50 raft: newRaft 830bc2abd256fd30 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
    2015/08/6 14:09:50 raft: 830bc2abd256fd30 became follower at term 1
    2015/08/6 14:09:50 etcdserver: starting server... [version: 2.1.1+git, cluster version: to_be_decided]
    2015/08/6 14:09:50 rafthttp: failed to dial 8887eaf3e329a3f8 on stream MsgApp v2 (dial tcp 10.97.50.35:2390: connection refused)
    2015/08/6 14:09:50 etcdserver: added local member 830bc2abd256fd30 [http://host1:2391] to cluster 9e94874682ff203f
    2015/08/6 14:09:50 rafthttp: failed to dial 8887eaf3e329a3f8 on stream Message (dial tcp 10.97.50.35:2390: connection refused)
    2015/08/6 14:09:50 etcdserver: added member 8887eaf3e329a3f8 [http://host1:2390] to cluster 9e94874682ff203f
    2015/08/6 14:09:52 raft: 830bc2abd256fd30 is starting a new election at term 1
    2015/08/6 14:09:52 raft: 830bc2abd256fd30 became candidate at term 2
    2015/08/6 14:09:52 raft: 830bc2abd256fd30 received vote from 830bc2abd256fd30 at term 2
    2015/08/6 14:09:52 raft: 830bc2abd256fd30 [logterm: 1, index: 2] sent vote request to 8887eaf3e329a3f8 at term 2
    2015/08/6 14:09:52 rafthttp: failed to write 8887eaf3e329a3f8 on pipeline (dial tcp 10.97.50.35:2390: connection refused)
    2015/08/6 14:09:53 raft: 830bc2abd256fd30 is starting a new election at term 2
    2015/08/6 14:09:53 raft: 830bc2abd256fd30 became candidate at term 3
    2015/08/6 14:09:53 raft: 830bc2abd256fd30 received vote from 830bc2abd256fd30 at term 3
    2015/08/6 14:09:53 raft: 830bc2abd256fd30 [logterm: 1, index: 2] sent vote request to 8887eaf3e329a3f8 at term 3
    2015/08/6 14:09:53 rafthttp: the connection with 8887eaf3e329a3f8 became active
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 is starting a new election at term 3
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 became candidate at term 4
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 received vote from 830bc2abd256fd30 at term 4
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 [logterm: 1, index: 2] sent vote request to 8887eaf3e329a3f8 at term 4
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 received vote from 8887eaf3e329a3f8 at term 4
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 [q:2] has received 2 votes and 0 vote rejections
    2015/08/6 14:09:54 raft: 830bc2abd256fd30 became leader at term 4
    2015/08/6 14:09:54 raft: raft.node: 830bc2abd256fd30 elected leader 830bc2abd256fd30 at term 4
    2015/08/6 14:09:54 etcdserver: setting up the initial cluster version to 2.1.0
    2015/08/6 14:09:54 etcdserver: published {Name:host12 ClientURLs:[http://host1:2389]} to cluster 9e94874682ff203f
    2015/08/6 14:09:54 etcdserver: set the initial cluster version to 2.1.0
    2015/08/6 14:10:20 rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy
    2015/08/6 14:10:50 rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy
    2015/08/6 14:11:20 rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy
    2015/08/6 14:11:50 rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy
    2015/08/6 14:12:20 rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy
    2015/08/6 14:12:50 rafthttp: the connection to peer 8887eaf3e329a3f8 is unhealthy

**Comment by xiang90** [comment]
First, you are trying current master. It is etcd 2.1.1 + git, not the release version of etcd. 

Second, I failed to reproduce your issue on my local mac. The behavior is a little bit wried to me. Are you able to reproduce the issue on other linux distro so that I can try to reproduce?

**Comment by dannysauer** [comment]
I checked out the 2.1.1 tag from git, so I assumed that matched the current release. :) Was that a bad assumption?

I do not have access to any other distributions at work; we are a RHEL shop. But it should be identical to CentOS 6, which you can get for free. I can test on Ubuntu at home, but I know that using the release tarball on two Ubuntu systems (one old, one new)  with Ubuntu's packaged golang does work.

**Comment by xiang90** [comment]
>  I can test on Ubuntu at home, but I know that using the release tarball on two Ubuntu systems (one old, one new) with Ubuntu's packaged golang does work.

Try to test on Ubuntu with the same git tag. The release tar and master are different. I will try to set up CentOS to reproduce soon.

**Comment by dannysauer** [comment]
Apparently you're right - the tag is *not* like the release.  I pulled the release file from //github.com/coreos/etcd/releases/download/v2.1.1/etcd-v2.1.1-linux-amd64.tar.gz and it's working properly as a 2-node local cluster which fails under the one I built from the tag.

So I got the source tarball from https://github.com/coreos/etcd/archive/v2.1.1.tar.gz, and ran the build script.  That resulting binary _also_ does not exhibit the same problem.  So, it's apparently the etcd code from the tag, not my machine, hardware, or go implementation.

I'll use the git tag on my Ubuntu machine at home sometime this evening (presuming my wife hasn't built a list of things that I need to do tonight :)) and see if I can reproduce the problem, though.

**Comment by xiang90** [comment]
>  my machine, hardware, or go implementation.

I am not sure. We added a stricter connection checker in the recent release. It works fine on my local env. I would suggest to check it on ubuntu. And as I said, I will try to reproduce it on CentOS6 on ec2.

**Comment by dannysauer** [comment]
I just updated etcd on one node from the five-node cluster which has been griping since it was stood up yesterday, and the cluster-health command on that node is showing all nodes as healthy.  It is not emitting the "connection to peer is unhealthy" messages either.  All of the other nodes still complain about the updated node, though.

**Comment by xiang90** [comment]
@dannysauer Can you try with current master again?

**Comment by dannysauer** [comment]
$ git describe
v2.1.1-114-g668a8a8

The individual nodes aren't dumping out the "unhealthy" logs anymore, but I still see this in the cluster-health output on both nodes:

    cluster is healthy: raft is making progress [commit index: 297->299]
    leader is 8887eaf3e329a3f8
    member 830bc2abd256fd30 is healthy: raft is making progress [match: 297->299]
    member 8887eaf3e329a3f8 is healthy: raft is making progress [match: 297->299]

**Comment by xiang90** [comment]
@dannysauer What is wrong with the output? It shows your member is healthy.

**Comment by xiang90** [comment]
@dannysauer It just explains why your cluster is healthy and why each member is healthy. I think your problem is solved. : )

**Comment by dannysauer** [comment]
Oh, I expected that the values would eventually converge, and that it would just say "member xxx is healthy" like in the older version.  Is it expected that it will always give the "is making progress" message now?

**Comment by xiang90** [comment]
@dannysauer Yes. We will cover it by doc when we release 2.2.

**Comment by dannysauer** [comment]
Awesome.  Thanks for the work. :)
