### ISSUE TITLE
Securing etcd

### ISSUE THREAD

**Issue by marclennox** [coreos/etcd#3237]
After trying to setup a secured etcd2 cluster, I've run into an issue where it appears it's not actually secured.

I'm running etcd as a docker container and have created and configured all the tls keys.  The etcd startup log echos the key files being used (client and peer) with no errors, and my etcd nodes can talk to each other (cluster is healthy).

However from a remote client I can get values from etcd using etcdctl over port 2379 WITOUT specifying any keys...  obviously not good.

Any ideas what i'm missing?

**Comment by xiang90** [comment]
@marclennox 

Please check https://github.com/coreos/etcd/blob/master/Documentation/security.md#example-2-client-to-server-authentication-with-https-client-certificates for client cert verification using TLS.

Please check https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md for client auth.

**Comment by marclennox** [comment]
OK I see there's a new additional argument to turn on cert auth.  Thanks.
