### ISSUE TITLE
etcdctl reports unhealthy cluster

### ISSUE THREAD

**Issue by raoofmd** [coreos/etcd#3238]
I reported similar issue in 
Inconsistent 2.1.0 behavior for v2/security #3099

Cluser becomes unhealthy after some days automatically. Though I dont see any problem accessing the cluster of 3 machines directly or using proxy - built using 2.1.0 rc 

All the flags and settings are exactly same as I reported in #3099

./etcd -version
etcd Version: 2.1.0-rc.0
Git SHA: 00c32ef
Go Version: go1.4.2
Go OS/Arch: linux/amd64

 ./etcdctl 
--peers="https://node01.etcd.dev.com:2379, https://node02.etcd.dev.com:2379, https://node03.etcd.dev.com:2379" 
--cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem 
--key-file=/var/home/rm/node01.etcd.dev.com.pem 
--ca-file=/var/home/rm/ca.cert.pem cluster-health
cluster is unhealthy

 curl -u root:pass http://node01.etcd.dev.com:2377/v2/stats/store
{"getsSuccess":2291,"getsFail":211,"setsSuccess":10,"setsFail":0,"deleteSuccess":7,"deleteFail":0,"updateSuccess":3,"updateFail":0,"createSuccess":24,"createFail":9,"compareAndSwapSuccess":0,"compareAndSwapFail":0,"compareAndDeleteSuccess":0,"compareAndDeleteFail":0,"expireCount":0,"watchers":0}

curl -u root:pass http://node01.etcd.dev.com:2377/v2/members
{"members":[{"id":"4c5854cca2fdc9c","name":"node03","peerURLs":["https://node03.etcd.dev.com:2380"],"clientURLs":["https://node03.etcd.dev.com:2379"]},{"id":"5f97c3330e24a56d","name":"node02","peerURLs":["https://node02.etcd.dev.com:2380"],"clientURLs":["https://node02.etcd.dev.com:2379"]},{"id":"f95caeae097ab105","name":"node01","peerURLs":["https://node01.etcd.dev.com:2380"],"clientURLs":["https://node01.etcd.dev.com:2379"]}]}

etcd     32131     1  1 Jul08 ?        09:57:30 /var/lib/etcd/etcd 
-advertise-client-urls https://node01.etcd.dev.com:2379 
-initial-cluster-state new 
-name node01 
-data-dir /var/lib/etcd/cluster/datadir 
-listen-peer-urls https://node01.etcd.dev.com:2380 
-initial-advertise-peer-urls https://node01.etcd.dev.com:2380 
-listen-client-urls https://node01.etcd.dev.com:2379 
-discovery-srv etcd.dev.com 
-trusted-ca-file /var/home/rm/ca.cert.pem 
-cert-file /var/home/rm/node01.etcd.dev.com.cert.pem 
-key-file /var/home/rm/node01.etcd.dev.com.pem 
-peer-trusted-ca-file /var/home/rm/ca.cert.pem 
-peer-cert-file /var/home/rm/node01.etcd.dev.com.cert.pem 
-peer-key-file /var/home/rm/node01.etcd.dev.com.pem 
-heartbeat-interval 200 
-election-timeout 2000 
-initial-cluster-token etcd-cluster-dev

Logs from node01 are here
https://gist.github.com/raoofmd/7ebd769b09b53f86b309

**Comment by raoofmd** [comment]
Figured out, I think it is a bug in etcdctl implementation of auth api or etcdhttp  [etcd/etcdserver/etcdhttp/client_auth.go!](https://github.com/coreos/etcd/blob/master/etcdserver/etcdhttp/client_auth.go)

seems that etcdctl is not honoring --username for cluster-health but it does use it for ls

**For etcdctl ls**
Below doesn't give any error in the logs and returns the result
./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --username="root" ls
Password:
/testKeysDir

Below returns this error in the logs - *2015/08/7 09:50:56 etcdhttp: auth: no such user: not_root.*
./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --username="not_root" ls
Password:
Error:  0: Insufficient credentials () [0]


**For etcdctl cluster-health**
./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --username="root" cluster-health
cluster is unhealthy
./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --username="not_root" cluster-health
cluster is unhealthy
./etcdctl --peers="https://node01.etcd.vonagedev.com:2379,https://node02.etcd.vonagedev.com:2379,https://node03.etcd.vonagedev.com:2379" --cert-file=/var/home/rmohammed/node01.etcd.vonagedev.com.cert.pem --key-file=/var/home/rmohammed/node01.etcd.vonagedev.com.pem --ca-file=/var/home/rmohammed/ca.cert.pem cluster-health
cluster is unhealthy

All the above 3 commands give the below in the logs
*2015/08/7 13:51:38 etcdhttp: auth: invalid access for unauthenticated user on resource /.*
*2015/08/7 13:51:47 etcdhttp: auth: invalid access for unauthenticated user on resource /.*
*2015/08/7 13:59:44 etcdhttp: auth: invalid access for unauthenticated user on resource /.*

**Comment by yichengq** [comment]
@raoofmd I could reproduce it on 2.1, and it is a bug as you say.

We have improved the workflow for cluster-health in master branch, and based on my test this is no longer a problem. Could you give it a try?

**Comment by xiang90** [comment]
@yichengq We still need to fix this for 2.1

**Comment by raoofmd** [comment]
@yichengq sure I will try that out.

On a separate note, we will be going to prod soon, should I wait till Aug 13th for 2.2. I mean does it have any critical fixes that I should hold my release for.

**Comment by xiang90** [comment]
@raoofmd Please note that the root cause `auth` is still a experimental feature.

**Comment by raoofmd** [comment]
@xiang90 @yichengq Ok I understand the risks with auth feature, i meant something other than auth.

Also I was wondering if this is related to #3178

**Comment by xiang90** [comment]
@raoofmd #3178 fixes a few things. The final release of 2.2 will be around mid Sept.

**Comment by xiang90** [comment]
@raoofmd We fixed this in 2.1.2 release. Feel free to give it a try. Thanks.
