### ISSUE TITLE
etcdctl doesn't honor dns discovery flag

### ISSUE THREAD

**Issue by raoofmd** [coreos/etcd#3244]
Documentation says --discovery-srv flag can be used instead of --peers but it doesn't seem to work.

./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --username=root cluster-health
cluster is unhealthy

./etcdctl --discovery-srv="etcd.dev.com" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --username=root cluster-health
Incorrect Usage.

**Comment by xiang90** [comment]
@raoofmd Are you trying with current master? Or the released version of etcdctl?

**Comment by raoofmd** [comment]
released version

**Comment by xiang90** [comment]
@raoofmd The released version does not support that. Doc is for the master. Can you try with current master please?

**Comment by xiang90** [comment]
@raoofmd This is the doc for the released version of etcdctl: https://github.com/coreos/etcd/tree/release-2.1/etcdctl
