### ISSUE TITLE
Etcd Key Value Limitation

### ISSUE THREAD

**Issue by kgrvamsi** [coreos/etcd#3253]
Lets take a scenario like this

Admin have gave access for User1 to add 4 keys on to the ETCD cluster and User1 infact added 10 Keys on to the ETCD Cluster so inorder not to give the user to add more keys how can we make a Key/Value Limitation for the User.

If the Limitation is possible then how does the changes reflect (meaning they reflect on runtime  or we need to restart the cluster).

**Comment by yichengq** [comment]
We don't have this kind of limitation. I think if you give the user the access, you should trust that it will do the right thing.

Could you explain your use cases in details? So we could evaluate more accurately.

We introduces auth feature in 2.1(https://github.com/coreos/etcd/blob/master/Documentation/authentication.md). Maybe this is helpful.

**Comment by kgrvamsi** [comment]
Hi @yichengq ,

Thanks for your reply and i'm looking out for a unified model of seeing the ETCD at a Hierarchy model inside a company to store user specific K/V and that too limited Keys to add.This can also be used to run user specific kubernetes cluster with limited nodes per user to add in the ETCD(this is the limitation of restricting the user not to add more minions on to their K/V which API Server Points to).

As of now i'm not sure if Kubernetes supports ETCD Auth based model but it will be good to know the scope of this.

On the other side i would like to know if there is any plugin framework for etcd to integrate some of the authentication mechanisms.(Like API key authentication )

**Comment by yichengq** [comment]
For kubernetes case, I think kubernetes master should take care of the node limitation instead of etcd, which can make workflow easy to understand and consistent. 

We don't support plugin framework for auth today. Which kind of integration do you refer or is useful to you? We would like to know how users think about it.

**Comment by kgrvamsi** [comment]
with the plugin framework was thinking if i have a logic which i does another layer of authentication with my own generated API keys or tokenid's or a auth middleware which takes the authentication creds from any database.

**Comment by yichengq** [comment]
@kgrvamsi Got it. We will consider about auth plugin framework in the future.

I think you have got the answer for limitation, so I close this issue.

**Comment by kgrvamsi** [comment]
Thanks @yichengq .....!!!!
