### ISSUE TITLE
Continuous writes to disk when idle

### ISSUE THREAD

**Issue by fbbdev** [coreos/etcd#3255]
I'm observing continuous small writes to disk from an idle etcd instance running in a docker container. Disk activity light blinks with a short period of ~500ms. This used to happen after some hours, but now starts immediately.
Strace shows a few writes to a WAL file followed by fsync. The server is bound to 127.0.0.1, there are no connected clients and Wireshark shows no traffic.

[Dockerfile, shell script and strace data](https://gist.github.com/fbbdev/aa8c6e9241983e13a9fd)

Container is started by the following command:
`docker run -d -p 127.0.0.1:4001:4001 fbbdev/etcd`

![screenshot from 2015-08-10 17-36-13](https://cloud.githubusercontent.com/assets/3287422/9175513/6dfb5a76-3f86-11e5-9b62-6c6fc53744c3.png)

![disk-activity](https://cloud.githubusercontent.com/assets/3287422/9175946/9b032952-3f88-11e5-9891-16a28e0b484c.gif)

**Comment by xiang90** [comment]
etcd syncs the cluster via internal commands every 500ms. So your observation is correct.

**Comment by dalu** [comment]
What if there is no cluster, it still writes to disk every 500ms, update or not.

**Comment by heyitsanthony** [comment]
@dalu this was fixed by fcbfff6a000c3c58e42caeb3ecc8b1398ea6fdf3; it will be included in 3.1.0.
