### ISSUE TITLE
running etcd under powershell on windows 2008 , sometimes it's blocked

### ISSUE THREAD

**Issue by cloudtrends** [coreos/etcd#3259]
hi team,

When I running etcd under powershell on windows 2008 , sometimes it's blocked .

It will continue to running after some random keyboard strike , powershell windows should get  focused.

Below is some of message on powershell windows screen :

etcdhttp: got unexpected response error (etcdserver: request timed out)
etcdhttp: got unexpected response error (etcdserver: request timed out)
etcdserver: saved snapshot at index 50005
etcdserver: compacted raft log at 45005
etcdhttp: got unexpected response error (etcdserver: request timed out)

BTW :
   version :  etcd-v2.1.1-windows-amd64

thanks

**Comment by yichengq** [comment]
could you fetch the metrics data of etcd? You could refer https://github.com/coreos/etcd/blob/master/Documentation/metrics.md for more details. I am wondering whether it is hardware resource problem.

**Comment by xiang90** [comment]
@cloudtrends Sorry I have no windows experience. No idea why the etcd process will be paused on windows.

**Comment by gyuho** [comment]
@cloudtrends Can you try our master branch?

**Comment by xiang90** [comment]
This is an old issue and has been inactive. I believe etcd 3 can run on Windows now. So closing.
