### ISSUE TITLE
Flannel Fails in creating a SubnetManager when its pointing to a ETCD Cluster via ETCD Proxy

### ISSUE THREAD

**Issue by kgrvamsi** [coreos/etcd#3260]
I have a Etcd proxy with three etcd nodes running and i made the proxy IP available inside the flannel variables to create the Keys but initially when the flannel service was trying to comeup its not creating the key as part of the systemd flow so i have created the routing keys manually and then when i restarted the flannel service i get a message saying that  it fails creating the subnetmanager and with some invalid character 'N' looking for beginning of value.

Output from the CLI

    core@dhcppc1 ~ $ systemctl status flannel.service -l
    ● flannel.service - flannel is an etcd backed network fabric for containers
    Loaded: loaded (/etc/systemd/system/flannel.service; enabled; vendor preset: disabled)
    Active: activating (start) since Tue 2015-08-11 09:38:04 UTC; 16s ago
     Docs: https://github.com/coreos/flannel
     Process: 1581 ExecStartPre=/opt/bin/etcdctl $FLANNEL_ETCDCTL_OPTS mk   $FLANNEL_ETCD_PREFIX ${FLANNEL_NETWORK_CONFIG} (code=exited, status=4)
    Main PID: 1587 (flanneld)
    Memory: 940.0K
      CPU: 10ms
    CGroup: /system.slice/flannel.service
           └─1587 /opt/bin/flanneld --ip-masq --etcd-endpoints=http://192.168.1.7

    Aug 11 09:38:04 dhcppc1 systemd[1]: flannel.service: Service hold-off time over, scheduling restart.
    Aug 11 09:38:04 dhcppc1 systemd[1]: Starting flannel is an etcd backed network fabric for containers...
    Aug 11 09:38:19 dhcppc1 etcdctl[1581]: Error:  501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
    Aug 11 09:38:19 dhcppc1 flanneld[1587]: go-etcd2015/08/11 09:38:19 DEBUG: get /coreos.com/network/config [http://192.168.1.7]
    Aug 11 09:38:19 dhcppc1 flanneld[1587]: go-etcd2015/08/11 09:38:19 DEBUG: Connecting to etcd: attempt 1 for keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
    Aug 11 09:38:19 dhcppc1 flanneld[1587]: go-etcd2015/08/11 09:38:19 DEBUG: send.request.to http://192.168.1.7/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false | method GET
    Aug 11 09:38:19 dhcppc1 flanneld[1587]: go-etcd2015/08/11 09:38:19 DEBUG: recv.response.from
    Aug 11 09:38:19 dhcppc1 flanneld[1587]: go-etcd2015/08/11 09:38:19 DEBUG: recv.success
    Aug 11 09:38:19 dhcppc1 flanneld[1587]: E0811 09:38:19.598492 01587 main.go:171] Failed to create SubnetManager: invalid character 'N' looking for beginning of value

ETCD values 

    root@e13067e196be:/# etcdctl -C=http://192.168.1.7 ls --recursive
    /registry
    /registry/ranges
    /registry/ranges/serviceips
    /registry/namespaces
    /registry/namespaces/default
    /registry/services
    /registry/services/specs
    /registry/services/specs/default
    /registry/services/specs/default/kubernetes
    /registry/services/specs/default/kubernetes-ro
    /registry/services/endpoints
    /registry/services/endpoints/default
    /registry/services/endpoints/default/kubernetes
    /registry/services/endpoints/default/kubernetes-ro
    /coreos.com
    /coreos.com/network
    /coreos.com/network/config

can't able to figure it out if its a ETCD issue or Flannel Issue

**Comment by yichengq** [comment]
could you try `curl -XGET http://192.168.1.7/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false`?

/cc @eyakubovich

**Comment by eyakubovich** [comment]
@kgrvamsi Can you paste teh value of `/coreos.com/network/config`? I think you have a syntax error somewhere there.

**Comment by kgrvamsi** [comment]
I wonder why the cluster health bad when i do it from other machine and it results as below

    Geetas-Mac-mini:etcd-v2.1.1-darwin-amd64 vamsikgr$ ./etcdctl -C=http://192.168.1.7 cluster-health
    cluster may be unhealthy: failed to connect [http://172.17.0.3:2379 http://172.17.0.2:2379   http://172.17.0.4:2379]

I'm running the backend servers on docker containers at this point and a etcd-proxy container to make the proxy running and i made this proxy service container expose port on to the host to 80

I ran this command and here is the output

    Geetas-Mac-mini:etcd-v2.1.1-darwin-amd64 vamsikgr$ curl -XGET     http://192.168.1.7/v2/keys/coreos.com/network/config?quorum=false&recursive=false&sorted=false
    [1] 26029
    [2] 26030
    Geetas-Mac-mini:etcd-v2.1.1-darwin-amd64 vamsikgr$ {"action":"get","node":{"key":"/coreos.com/network/config","value":"Network:10.10.0.0/16","modifiedIndex":17,"createdIndex":17}}

**Comment by eyakubovich** [comment]
@kgrvamsi Your value is `Network:10.10.0.0/16"` but it should be a JSON document so:

`{ "Network": "10.10.0.0/16" }`

I know this is user unfriendly, we have a `flannelctl` utility planned to make this nicer.

**Comment by kgrvamsi** [comment]
I did populated the values on to the key in a wrong way.

    etcdctl -C=http://192.168.1.7 set /coreos.com/network/config '{"Network": "10.10.0.0/16"}'

Infact i saw the quotes around the value solved my issue but would like to know if thats the problem for my issue before and thanks @eyakubovich  for referencing the issue i raised at the flannel community.

**Comment by xiang90** [comment]
@kgrvamsi I think your issue is solved. Thanks @eyakubovich !
