### ISSUE TITLE
RFE: Stats data in prometheus style format

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#3274]
Ideally I would like to just scrape the '/v2/stats/store' using tools like prometheus.  Currently they are not in that format.  

http://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by xiang90** [comment]
We already have them in prometheus format. But it is an experimental feature now.

See https://github.com/coreos/etcd/blob/master/Documentation/metrics.md#store
