### ISSUE TITLE
API to get users and roles with details

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3278]
I have a usecase where in I would like to get the users/roles and their details - something like we have for keys v2/keys?recursive=true

If we can get this then it will be very helpful in terms of administration.
/v2/auth/users?recursive=true
/v2/auth/roles?recursive=true

As an admin I would like to get a json dump that gives me the details of number of users. their roles and their permissions. In the current scenario i've to go manually to each user and see which role it belongs to and then again manually get the role permissions.

It grows uncontrollable in our production environment where we have hundreds of modules using the etcd cluster with each having its own user and role.

**Comment by xiang90** [comment]
This sounds like a reasonable requirement. Do you want to work on this?

**Comment by raoofm** [comment]
@xiang90 Though I would love too, but I'm not experienced in go programming. My expertise is on the java side. I'm looking towards contributing to etcd-viewer which is java based
Honestly I wish to contribute to etcd as well, but I think it will take some time for me to catch up with go =), sorry

Will be waiting to see this feature as it is very much needed to effectively use this in prod, as user and role management individually is a burden on operations team.

I understand that for small set of systems it is not a problem, but in a real world scenario, etcd a HA distributed key management system is used when many distributed systems talk to each other.
Thanks

**Comment by MSamman** [comment]
I can pick this up.

**Comment by xiang90** [comment]
@MSamman Awesome!

**Comment by MSamman** [comment]
How does these example response structures look?

GET /v2/auth/users?recursive=true

```
{
  users: [
    {
      user: "root",
      roles: [
        { 
          role: "root",
          permissions: {
            kv: {
              read: ["*"],
              write: ["*"]
            }
          }
        },
        ...
      ]
    },
    {
      user: "guest"
      roles: [
        { 
          role: "guest",
          permissions: {
            kv: {
              read: ["*"],
              write: ["*"]
            }
          }
        },
        ...
      ]
    },
    ...
  ]
}
```

GET /v2/auth/users/root?recursive=true

```
{
  user: "root",
  roles: [
    { 
      role: "root",
      permissions: {
        kv: {
          read: ["*"],
          write: ["*"]
        }
      }
    },
    ...
  ]
}
```


GET /v2/auth/roles?recursive=true

```
{
  roles: [
    { 
      role: "root",
      permissions: {
        kv: {
          read: ["*"],
          write: ["*"]
        }
      }
    },
    { 
      role: "guest",
      permissions: {
        kv: {
          read: ["*"],
          write: ["*"]
        }
      }
    },
    ...
  ]
}
```

**Comment by raoofm** [comment]
@MSamman lgtm

**Comment by MSamman** [comment]
I'm wondering if the responses above should just be the default case when user and role info is queried?

Is there any reason not to send down the full details of users and roles?
