### ISSUE TITLE
Some defect while using basic auth function

### ISSUE THREAD

**Issue by oscarrr110** [coreos/etcd#3280]
While using basic auth feature, I found that if a path has been granted to a role
I give the wrong auth header, it can still get related key. 
This behavior is different from etcdctl
Here is the my test step:

A. start etcd
  1) start etcd service on Ubuntu 14.04
	./etcd
B. user/role/path auth
1) add root user
	./etcdctl user add root
2) enable auth
        ./etcdctl auth enable
3) add new role
	./etcdctl -u root:1111 role add 0813
4) add new user
	./etcdctl -u root:1111 user add test
5) grant user to a role
	./etcdctl -u root:1111 user grant test -roles 0813
6)  Grant role to the path
	./etcdctl -u root:1111 role grant 0813 -path '/rootpath/*' -readwrite

C.get/set value

1）get/set key at rootpath
	./etcdctl -u test2:1111 get /rootpath/1
2) enable cache using url pattern
	curl -L http://127.0.0.1:2379/v2/auth/enable -XGET
3) get value without providing any user auth
	curl -L http://127.0.0.1:2379/v2/keys/rootpath/a -XGET
	{"action":"get","node":{"key":"/rootpath/a","value":"this is awesome","modifiedIndex":32,"createdIndex":32}}
**4) get value with auth header (right username and passward)**
curl -H "Authorization: Basic dGVzdDI6MTExMQ==" -L http://127.0.0.1:2379/v2/keys/rootpath/a -XGET
{"action":"get","node":{"key":"/rootpath/a","value":"this is awesome","modifiedIndex":32,"createdIndex":32}}
**5)  get value with auth header (wrong encode string), still get result**
curl -H "Authorization: Basic dGVzdDI6MTExMQ==xxxx" -L http://127.0.0.1:2379/v2/keys/rootpath/a -XGET
{"action":"get","node":{"key":"/rootpath/a","value":"this is awesome","modifiedIndex":32,"createdIndex":32}}
**6) if using etcdctl which giving random username and password, request will be denied**
./etcdctl -u 23232:1111 get /rootpath/1 
Error:  0: Insufficient credentials () [0]

**Comment by yichengq** [comment]
etcd auth fails to get username/password from Authorization field, so it uses guest role to check the read/write permission. Check guest role doc for more details: https://github.com/coreos/etcd/blob/master/Documentation/authentication.md#role-guest

**Comment by oscarrr110** [comment]
Yes, But if it got different result while using curl and etcdctl as below, It seems to be be confusing.

**5) get value with auth header (wrong encode string), still get result**
curl -H "Authorization: Basic dGVzdDI6MTExMQ==xxxx" -L http://127.0.0.1:2379/v2/keys/rootpath/a -XGET
{"action":"get","node":{"key":"/rootpath/a","value":"this is awesome","modifiedIndex":32,"createdIndex":32}}
**6) if using etcdctl which giving random username and password, request will be denied**
./etcdctl -u 23232:1111 get /rootpath/1 
Error: 0: Insufficient credentials () [0]

**Comment by yichengq** [comment]
I agree that if the user gives invalid authorization info, we should not use guest role to access the key and return value. Or the user, who get the guest key using wrong password, will be surprised when he fails to get non-guest key.

**Comment by MSamman** [comment]
If invalid authorization information is provided, then guest access should not be provided. What if no authorization information is provided. Should the user be given guest access at that point?

**Comment by MSamman** [comment]
What if guest access only allowed access to keys that do not have a required role?
