### ISSUE TITLE
Should give a more specific error message while using auth_api

### ISSUE THREAD

**Issue by oscarrr110** [coreos/etcd#3281]
**1 . if using error password, error msg as below**
 ./etcdctl -u test2:1111 get /rootpath2/key
Error:  0: Insufficient credentials () [0] 
**2 . if using right username and password,but  given the unauthorized path, error msg as below**
./etcdctl -u test2:1111 get /rootpath2/key
Error:  0: Insufficient credentials () [0]
**3. Wrong password or unauthorized path are different error, Shall we need to give more specific error message**

**Comment by yichengq** [comment]
etcd prints detailed log line at server side, which explains the reason why it has insufficient credentials. Could you check it and see if it is good for your use case?

**Comment by oscarrr110** [comment]
Yes, Server-side log got .
But actually my app's scenario is provided some services to client.
The customer can not see the server log actually. So the error information more accurate seems to be necessary

**Comment by xiang90** [comment]
@oscarrr110 We need to find a balance between what we should leak to the user and what we should not for security features. Differentiating bad user and unauthed path might be OK. But I would like to see a more concrete example and use case.

**Comment by xiang90** [comment]
@oscarrr110 Kindly ping

**Comment by oscarrr110** [comment]
Sorry for the missing.. : )

I know your mean. 

Actually I think that we should have got a balance between the user client and security feature.

But actually we expose the basic auth feature to the client user. I think that  he should know his own input(username and password) is correct

My app has been divided into two parts: Etcd cluster and Client User. They are a one-to-many relationship.
Actually client part does not have permission to access the etcd cluster. But client user still want to know what's wrong with his own behavior . Input invalid key or wrong username/password

**Comment by xiang90** [comment]
@barakmich How do you think about this?

**Comment by xiang90** [comment]
@barakmich Ping.

**Comment by xiang90** [comment]
We are probably not going to change this behavior for v2 api. We will keep this in mind when designing v3 auth. Thanks.

/cc @mitake

**Comment by mitake** [comment]
@xiang90 I understand. Thanks for your input.
