### ISSUE TITLE
If the path has been granted to the specified role, the user's request which does not provide username/password should be rejected? 

### ISSUE THREAD

**Issue by oscarrr110** [coreos/etcd#3282]
**1) rootpath has been granted to the role named 0813**
./etcdctl -u root:1111 role get 0813 
Role: 0813
KV Read:
        /rootpath/*
KV Write:
        /rootpath/*
**2) it can get the value using test2 which belong to the role named 0813**
./etcdctl -u test2:1111 get /rootpath/key
value
**3) but if  I got this key directly without given any username, it can still get the value**
 ./etcdctl get /rootpath/key
value

**Comment by yichengq** [comment]
etcd will create a guest role when enabling security, which has the full access to the key space. You can check the details here: https://github.com/coreos/etcd/blob/master/Documentation/authentication.md#role-guest This helps users to enable auth feature smoothly.

You can change the permission of guest role to disable this.

**Comment by oscarrr110** [comment]
Ok , Got it. thanks . 

This issue can be closed!
