### ISSUE TITLE
unfriendly higher version log line

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3288]
2015/08/13 13:17:57 etcdserver: the etcd version 2.1.1+git is not up-to-date
2015/08/13 13:17:57 etcdserver: member 924e2e83e93f2560 has a higher version &{2.2.0-alpha.0+git 2.1.0}

**Comment by xiang90** [comment]
why this is unfriendly? what is your expectation?

**Comment by yichengq** [comment]
The higher versions gives two version, which doesn't say their meanings.

**Comment by xiang90** [comment]
Do you mean at the end of the second line?

**Comment by yichengq** [comment]
yes.

**Comment by xiang90** [comment]
Thanks. Now I understand it. We need to improve.
