### ISSUE TITLE
explore automated/standard release procedure

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3294]
Several goals:
- should find potential problems before tag, including build error
- fewer steps to make a release

jenkins is a option.

**Comment by yichengq** [comment]
jenkins could be a good option for this. It could build before tagging, and run release procedures automatically. When making the release procedure, I will record and publish the way to config job in jenkins (and maybe alternative commands).

One further problem is that etcd-project-specific key/cert is needed to sign release binaries.

We need more time to make it work with existing testing/release platform because existing platform is under some changes. Delay it to 2.3.0-alpha

/cc @crawford

**Comment by yichengq** [comment]
based on discussion OOL, the existing jenkins platform is fine. will work on this.

**Comment by yichengq** [comment]
After digging into it, I would stage it into two phases:
1. standard release procedure. It needs a document about the standard procedure from tag to release binaries. Also I would make it as clear and simple as possible. And maybe some precheck script.
2. automated release procedure. It needs to integrate with jenkins.

I think it doesn't deserve efforts to build an automated release procedure with jenkins today. several reasons: 1. the release happens once per two weeks, whose frequency is low 2. I can foresee that I can generate all binaries in one script after stage 1, which is convenient enough. Set up jenkins could take much more time and get little benefit today. @crawford

**Comment by crawford** [comment]
Jenkins setup should take no more than 5 minutes. The tricky part is writing the scripts (which you will need either way). I'm happy to show you exactly how to set up Jenkins, but we need to get the build procedure squared away first. Jenkins will have more of a benefit once we add Windows and OS X builders.

**Comment by yichengq** [comment]
For jenkins integration, i have implemented a jenkins job that could build all binaries and upload them to github release at https://jenkins.coreos.systems/job/etcd-release/ . It is a good first step. The left part is at  #3472. /cc @crawford 

The release script has been merged, and waiting for release guide to be merged.

**Comment by xiang90** [comment]
I do not think people outside coreos can access to https://jenkins.coreos.systems/job/etcd-release/

**Comment by yichengq** [comment]
@xiang90 This is used to facilitate the procedure inside coreos, and its manual steps are all recorded in the release guide.

**Comment by xiang90** [comment]
@yichengq Then we should not bring it up on github at all.

**Comment by yichengq** [comment]
@xiang90 ok

**Comment by yichengq** [comment]
Close it because release guide is merged.
