### ISSUE TITLE
doc the relationship between RTT, heartbeat interval and election timeout

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3312]
Some overview:
0 < heartbeat < 1.5RTT
RTT << election timeout

We should instruct the way for users to set most appropriate timeout, and doc the potential problems when they are set wrong.

**Comment by xiang90** [comment]
I would say around 0.5RTT < heartbeat < 1.5RTT would be a good option. 0.5RTT is about the ping result.

**Comment by xiang90** [comment]
Or we can simply suggest 1 rtt, which is 2 * ping result.

**Comment by yichengq** [comment]
@xiang90 nit: the ping time is a round trip time. It sends out ICMP ECHO_REQUEST with local time, receives ECHO_RESPONSE, and calculate the passed time.

**Comment by xiang90** [comment]
@yichengq You are right.
