### ISSUE TITLE
docs: add env vars for each configuration flag

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#3318]
From the website anonymous feedback (paraphrased):

> I wish this page include the fully expanded environment variable for each cli flag.

For the [configuration doc](https://github.com/coreos/etcd/blob/master/Documentation/configuration.md) we should add these kinda like this:

##### -data-dir
+ Path to the data directory.
+ default: "${name}.etcd"
+ env variable: ETCD_DATA_DIR

**Comment by xiang90** [comment]
@robszumski I think we mentioned this in the doc you linked.

```
The format of environment variable for flag -my-flag is ETCD_MY_FLAG. It applies to all flags.
```

Do you think this is not clear enough?

**Comment by robszumski** [comment]
Yes, we do mention it, but it's easy to miss. It'd be friendlier to list them out, then you could copy/paste, etc.

**Comment by ecnahc515** [comment]
Isn't etcd now using cobra? Cobra can generate docs, and we could possibly contribute upstream to also support generating env variables in docs if using viper or something..

**Comment by xiang90** [comment]
no we do not use cobra

**Comment by ecnahc515** [comment]
Ah, my mistake. I guess then writing a tool to generate this type of doc might be a bit more work than it's worth, for now.

**Comment by robszumski** [comment]
we don't have to do this in the help output, but doing this in the markdown docs is cheap and easy.
