### ISSUE TITLE
better logging for timeouts

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#3328]
Users often run into issues with request timeouts. I know there is work underway (or just completed) to make more of these tunable. In addition, can we output the configured timeout value in the log? For example, something like this:

Before:

```
$ etcd2: sender: error posting to 1.2.3.4: dial tcp i/o timeout
```

After:

```
$ etcd2: sender: error posting to 1.2.3.4: dial tcp i/o timeout (30 sec)
```

**Comment by AdoHe** [comment]
configured timeout? you mean dial timeout in proxy mode or RPC timeout between nodes?

**Comment by robszumski** [comment]
If possible, any timeout, but most people are hitting this when a proxy is communicating back to the peers participating in consensus.

**Comment by xiang90** [comment]
@robszumski The timeout message is from go stdlib. It would be hard for us to attach the exact timeout for all possible timeout error. We have to compare it is a timeout error and do bookkeeping for all setting all over the codebase. I would consider this to be a low priority one.

/cc @yichengq

**Comment by gyuho** [comment]
@robszumski The code snipper seems outdate. Anyway, is still the valid use case?
For today's code base, one good example that I can think of is this:

https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L945-L949

```go
if ms[i].Type == raftpb.MsgHeartbeat {
	ok, exceed := s.r.td.Observe(ms[i].To)
	if !ok {
		// TODO: limit request rate.
		plog.Warningf("failed to send out heartbeat on time (deadline exceeded for %v)", exceed)
		plog.Warningf("server is likely overloaded")
	}
}
```

After

```go
if ms[i].Type == raftpb.MsgHeartbeat {
	ok, exceed := s.r.td.Observe(ms[i].To)
	if !ok {
		// TODO: limit request rate.
		plog.Warningf("failed to send out heartbeat on time (deadline exceeded %v over limit %v)", exceed, s.cfg.TickMs)
		plog.Warningf("server is likely overloaded")
	}
}
```

But printing out time-outs to all RPCs might not be impossible, as @xiang90 said. For example, Go stdlib http package uses non-configurable logger. Similar in gRPC.

**Comment by robszumski** [comment]
Those two messages seems like they do address at least one use-case of this problem. If more generic logging isn't possible, would it be realistic to add similar messages for the discovery operations?

Addressing the heartbeat and discovery requests would solve most of the confusion I've seen.

**Comment by xiang90** [comment]
@gyuho Let's check the codebase and probably print out the limit where we can?

**Comment by gyuho** [comment]
@xiang90 Sure, I will come up with some lists so we can discuss on Wednesday. Thanks.

**Comment by gyuho** [comment]
Users can set their own timeouts and will see the related context timeout 
in client side. Below are my proposals to add more time-out loggings in
server side:


1. https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L959
plog.Warningf("failed to send out heartbeat on time (deadline exceeded %v over limit %v)", exceed, s.cfg.TickMs)

2. https://github.com/coreos/etcd/blob/master/etcdserver/cluster_util.go#L69
plog.Warningf("could not get cluster response from %s in %v (%v)", u, timeout, err)

3. https://github.com/coreos/etcd/blob/master/etcdserver/cluster_util.go#L229
plog.Warningf("failed to reach the peerURL(%s) of member %s in %v (%v)", u, m.ID, cc.Timeout, err)

4. https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L931
plog.Errorf("publish error: %v in %v", err, timeout)

5. https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L1302
plog.Errorf("error updating cluster version in %v (%v)", s.cfg.ReqTimeout(), err)

6. https://github.com/coreos/etcd/blob/master/rafthttp/probing_status.go#L51
plog.Warningf("the connection to peer %s is unhealthy for the last %v", id, statusMonitoringInterval)

7. https://github.com/coreos/etcd/blob/master/etcdserver/etcdhttp/client.go#L279
plog.Errorf("error updating member %s in %v (%v)", m.ID, h.timeout, err)

/cc @xiang90
