### ISSUE TITLE
Can't replace unhealthy member

### ISSUE THREAD

**Issue by mborho** [coreos/etcd#3329]
My cluster got somehow in an unhealthy state, so I wanted to replace unhealthy instances from the cluster with 

    core@ip-10-0-1-12 ~ $ etcdctl member remove e25938377bdd2340
    Recieved an error trying to remove member e25938377bdd2340: context deadline exceeded

Same when I try to add a member:

     core@ip-10-0-1-12 ~ $ etcdctl member add infra4 http://10.0.1.13:2380
     context deadline exceeded

My goal was to replace 2 of 3 instances with new nodes, I'm running CoreOS stable (723.3.0). Initial cluster had 3x etcd-nodes and 2 proxy instances, I'm using dns-SRV for discovery.

10.0.1.12 is the only healthy etcd2 machine. Do I need at last 2 healthy members to add new members?

**Comment by JacekLach** [comment]
You need a quorum to perform cluster membership modifications, as they involve writing to the cluster. See https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md

If you don't expect any of these nodes to come back up, you'll have to use -force-new-cluster to recover: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#restoring-a-backup

**Comment by xiang90** [comment]
@mborho What @JacekLach mentioned is true. Please read the doc he referred. I think you will get your problem solved.

**Comment by eaoliver** [comment]
I realize that we get what we pay for, but this remains a terrible design.  It's as if usage/deployment of etcd has never been considered.  The user should have the ability to override quorum and force state into the cluster. 

Given that quorum is lost, he should be able to do: 

etcdctl --force member add infra4 http://10.0.1.13:2380  

and force any known, reachable nodes to add the given node to their member list.  The call can even be blocking to make sure all healthy nodes get the new forced member.  

Similarly, 
etcdctl --force member remove <id> 

should connect to every reachable node and remove the member from its list.   

I cannot think of a valid reason why someone with root access to every box has to jump through the hoops documented in the above URLs. The user should be able to override quorum whenever necessary.

**Comment by xiang90** [comment]
> I realize that we get what we pay for, but this remains a terrible design. 

I think this is a too harsh word. We treat consistency and correctness of your cluster seriously. Reconfiguration is basically not as simple as you might think. And we have thought it for quite a while and have no intention to change the fundamental principle any time soon. 

> It's as if usage/deployment of etcd has never been considered. 

Your assumption is wrong. We wrote docs to talk about the reason. Please check https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#permanent-loss-of-quorum-requires-new-cluster.

In a word, we might provide better UX in the near future (see https://github.com/coreos/etcd/pull/2366), but we probably will never let our user to change anything bypass raft at runtime.

**Comment by xiang90** [comment]
@eaoliver Moreover, if you are considering to run etcd under an environment that will lost quorum frequently (within a day), you should probably decide not run etcd. etcd is simply not designed for this kind of environment. It introduces too much operational overhead.

**Comment by eaoliver** [comment]
I see the reasoning, but I still disagree.  Bypassing the consensus mechanism when there is no consensus is fine.  In these rare circumstances, you can connect to every node, block, and wait for everyone to commit the new member (that may be assumed to have no state), and be done.  

I'm all in on the CoreOS stack. I think it's fantastic. However, every time my etcd2 cluster gets unhealthy and I get cryptic "context deadline exceeded" messages when I try to recover, it's maddening!

**Comment by xiang90** [comment]
@eaoliver 

> you can connect to every node, block, and wait for everyone to commit the new member (that may be assumed to have no state), and be done.

We cannot make this kind of assumption in a distributed system. We are not going to let you bypass consensus at runtime. Sorry.

>  However, every time my etcd2 cluster gets unhealthy and I get cryptic "context deadline exceeded" messages.

As I said, if you are consistently losing your quorum, you probably should not run etcd at all.

**Comment by AdoHe** [comment]
@eaoliver I think maybe you need to check why your etcd2 instances consistently gets unhealthy, this is such a rare case, I agree with @xiang90, if you are consistently losing your quorum, maybe you should not run etcd. And I think a better cluster management UI tool is necessary, how about this @xiang90 ?

**Comment by eaoliver** [comment]
I didn't say it was constantly happening and I know exactly how it happened.  The fact is is can happen due to hardware failure, and it is hard to recover from. 

The product would be better if the user could manually force members into an existing unhealthy, unusable cluster.

**Comment by xiang90** [comment]
@mborho I am closing this due to low activity. I think @JacekLach gave you a correct answer. Please give it a try. If you still have questions, feel free to reopen this issue. Thanks for reporting!

**Comment by xiang90** [comment]
@eaoliver If you have more thoughts on this, please leave it to https://github.com/coreos/etcd/issues/3203. 

@AdoHe We would like to have a ui to show cluster status. But we do not have the bandwidth to work on that now. If you would like to, can you send a proposal as a pull request?

**Comment by mborho** [comment]
@xiang90 yes, I think so. As I'm using etcd with CoreOS and the cluster was running for test/demo purposes, I've set up a new one. I do not want to fall in the habit of manually changing things on the cluster.... if possible.

It was only a cluster of 3 instances, which caused the problem... after one instance got corrupted and another one failed...

Nonetheless, perhaps "context deadline exceeded" could be replaced with something more telling, so it would be easier to grasp an idea of what gone wrong.

**Comment by xiang90** [comment]
@mborho I totally agree that we should improve the `context deadline exceed` thing. And actually, the error message has been improved in current master. 2.2 will be released soon.

**Comment by AdoHe** [comment]
@xiang90 I will do that as soon as possible.
