### ISSUE TITLE
etcd can't start due to status=1/FAILURE or status=200/CHDIR

### ISSUE THREAD

**Issue by JackChen255** [coreos/etcd#3331]
I can't start etcd service now, and it always said "etcd.service start request repeated too quickly, refusing to start". No sure whether the etcd service runs well or not. How to solve it?

[root@localhost ~]# etcd -version
etcd Version: 2.0.13
Git SHA: 92e3895
Go Version: go1.4.2
Go OS/Arch: linux/amd64
[root@localhost ~]# etcdctl -version
etcdctl version 2.0.13

[root@localhost ~]# systemctl restart etcd
[root@localhost ~]# systemctl status etcd
etcd.service - Etcd Server
Loaded: loaded (/etc/systemd/system/etcd.service; enabled)
Active: failed (Result: start-limit) since Wed 2015-08-19 09:35:17 EDT; 1h 1min ago
Process: 5403 ExecStart=/bin/bash -c GOMAXPROCS=$(nproc) /usr/bin/etcd (code=exited, status=1/FAILURE)
Main PID: 5403 (code=exited, status=1/FAILURE)
CGroup: /system.slice/etcd.service

Aug 19 09:35:17 localhost.localdomain systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 19 09:35:17 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.
Aug 19 09:35:17 localhost.localdomain systemd[1]: etcd.service holdoff time over, scheduling restart.
Aug 19 09:35:17 localhost.localdomain systemd[1]: Stopping Etcd Server...
Aug 19 09:35:17 localhost.localdomain systemd[1]: Starting Etcd Server...
Aug 19 09:35:17 localhost.localdomain systemd[1]: etcd.service start request repeated too quickly, refusing to start.
Aug 19 09:35:17 localhost.localdomain systemd[1]: Failed to start Etcd Server.
Aug 19 09:35:17 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.

[root@localhost ~]# journalctl -u etcd
Aug 19 09:35:17 localhost.localdomain systemd[1]: Stopping Etcd Server...
Aug 19 09:35:17 localhost.localdomain systemd[1]: Starting Etcd Server...
Aug 19 09:35:17 localhost.localdomain systemd[1]: Started Etcd Server.
Aug 19 09:35:17 localhost.localdomain bash[5403]: 2015/08/19 09:35:17 etcd: ETCD_LISTEN_CLIENT_URLS set but ETCD_ADVERTISE_CLIENT_URLS not, setting ETCD_ADVERTISE_CLIENT_URLS to ETCD_ADVERTISE_CLIENT_URLS
Aug 19 09:35:17 localhost.localdomain bash[5403]: 2015/08/19 09:35:17 etcd: error listing data dir: /var/lib/etcd/default.etcd
Aug 19 09:35:17 localhost.localdomain systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 19 09:35:17 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.
Aug 19 09:35:17 localhost.localdomain systemd[1]: etcd.service holdoff time over, scheduling restart.
Aug 19 09:35:17 localhost.localdomain systemd[1]: Stopping Etcd Server...
Aug 19 09:35:17 localhost.localdomain systemd[1]: Starting Etcd Server...
Aug 19 09:35:17 localhost.localdomain systemd[1]: etcd.service start request repeated too quickly, refusing to start.
Aug 19 09:35:17 localhost.localdomain systemd[1]: Failed to start Etcd Server.
Aug 19 09:35:17 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.

**Comment by xiang90** [comment]
Sorry, but this does not seem like an etcd issue.

**Comment by crawford** [comment]
```
etcd: error listing data dir: /var/lib/etcd/default.etcd
```

What are the file permissions on /var/lib/etcd?

**Comment by JackChen255** [comment]
@crawford There is no /var/lib/etcd folder now. I am running the etcd and kubernetes command with root so there should be no permission issue.
If I manually create /var/lib/etcd, the error is "code=exited, status=1/FAILURE". If there is no /var/lib/etcd, the error is "code=exited, status=200/CHDIR"

**Comment by crawford** [comment]
etcd needs that directory to exist. What does the log show when that directory does exist?

**Comment by JackChen255** [comment]
@crawford 
I manually create  /var/lib/etcd/default.etcd and set the permission as 777. But it still said permission denied even I use root user.

[root@localhost ~]# sudo systemctl status etcd
etcd.service - Etcd Server
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled)
   Active: failed (Result: start-limit) since Wed 2015-08-19 14:44:55 EDT; 5s ago
  Process: 10048 ExecStart=/bin/bash -c GOMAXPROCS=$(nproc) /usr/bin/etcd (code=exited, status=1/FAILURE)
 Main PID: 10048 (code=exited, status=1/FAILURE)

Aug 19 14:44:55 localhost.localdomain bash[10048]: 2015/08/19 14:44:55 etcdserver: initial cluster = default=http://localhost:2380,default=http://localhost:7001
Aug 19 14:44:55 localhost.localdomain bash[10048]: 2015/08/19 14:44:55 etcdserver create snapshot directory error: mkdir /var/lib/etcd/default.etcd/member: permission denied
Aug 19 14:44:55 localhost.localdomain systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 19 14:44:55 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.
Aug 19 14:44:55 localhost.localdomain systemd[1]: etcd.service holdoff time over, scheduling restart.
Aug 19 14:44:55 localhost.localdomain systemd[1]: Stopping Etcd Server...
Aug 19 14:44:55 localhost.localdomain systemd[1]: Starting Etcd Server...
Aug 19 14:44:55 localhost.localdomain systemd[1]: etcd.service start request repeated too quickly, refusing to start.
Aug 19 14:44:55 localhost.localdomain systemd[1]: Failed to start Etcd Server.
Aug 19 14:44:55 localhost.localdomain systemd[1]: Unit etcd.service entered failed state.
[root@localhost ~]# systemctl enable etcd
Failed to issue method call: File exists

**Comment by crawford** [comment]
@JackChen255 Your permissions are still not right. Since you aren't running on CoreOS, I really can't help you much further. Your setup is going to be very different, but I can tell you that you need to make sure that the etcd service is able to fully manipulate that directory (read, write, execute).

**Comment by philips** [comment]
@JackChen255 what does your service file look like?

**Comment by JackChen255** [comment]
@philips 
/etc/etcd/etcd.conf is as below. Is it service file?
ETCD_NAME=default
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:4001"

**Comment by JackChen255** [comment]
@philips @crawford 
Eventually solve this issue. Thanks for your help. The User in service file is etcd. I change it to root and now etcd is running well.

[root@localhost ~]# cat /usr/lib/systemd/system/etcd.service
[Unit]
Description=Etcd Server
After=network.target
[Service]
Type=simple
WorkingDirectory=/var/lib/etcd/
EnvironmentFile=-/etc/etcd/etcd.conf
User=etcd
# set GOMAXPROCS to number of processors
ExecStart=/bin/bash -c "GOMAXPROCS=$(nproc) /usr/bin/etcd"
Restart=on-failure
LimitNOFILE=65536
[Install]
WantedBy=multi-user.target

**Comment by Suranga-nizi** [comment]
how change it as root. it's a read only file
