### ISSUE TITLE
After rebooting a etcd container i get a message about a wal

### ISSUE THREAD

**Issue by j-mcnally** [coreos/etcd#3335]
wal: failed to allocate space when creating new wal file (operation not supported)

Not really sure what this means the host has plenty of space.

**Comment by xiang90** [comment]
@j-mcnally Your file system does not support pre allocate space for new file. If your system does not support this, we should simply skip it rather than fail you. Will fix before 2.2 release.

**Comment by xiang90** [comment]
@j-mcnally Got it fixed. It would be great if you can try it again. Thanks. (Kindly remind you that we have stable version of etcd at release branch. Master is under development and testing)

**Comment by j-mcnally** [comment]
Will check it out thnx for the quick reply . Sorry for being short on info I didn't really understand the problem

**Comment by xiang90** [comment]
@j-mcnally Not a problem at all. You already provide a lot of information and help us discover a bug.
