### ISSUE TITLE
ETCDCTL_PEERS is a confusing env name

### ISSUE THREAD

**Issue by bkleef** [coreos/etcd#3341]
Because default etcd **peer** port (server-to-server communication) is 2380 and this value should get an etcd (client communication) record with as default port 2379.

Let's rename it into `ETCDCTL_ENDPOINT` like `FLEETCTL_ENDPOINT`.

**Comment by xiang90** [comment]
@robszumski Any suggestion?

**Comment by robszumski** [comment]
Sounds ok to me, but we'll need to leave in support for the old one.

**Comment by xiang90** [comment]
Closed via #3390
