### ISSUE TITLE
etcd cluster not communicating

### ISSUE THREAD

**Issue by ilackarms** [coreos/etcd#3343]
I set up a CoreOS using vagrant per https://github.com/coreos/coreos-vagrant

I vagrant ssh into each host in a separate terminal.
on node-1 i run:
```core@core-01 ~ $ etcdctl set foo bar```
on node 2 and 3:
```core@core-02 ~ $ etcdctl get foo
Error:  100: Key not found (/foo) [238]```
```core@core-03 ~ $ etcdctl get foo
Error:  100: Key not found (/foo) [241]```

running `journalctl -u etcd` on each machine produces 3 identical outputs. all nodes have elected themselves leader (does not appear they are communicating).
```
core@core-01 ~ $ journalctl -u etcd
-- Logs begin at Thu 2015-08-20 18:47:42 UTC, end at Thu 2015-08-20 18:51:49 UTC. --
Aug 20 18:47:56 core-01 systemd[1]: Started etcd.
Aug 20 18:47:56 core-01 systemd[1]: Starting etcd...
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.140 INFO      | 97c12d68c4fe4c188d26e79b681a7d2a is starting a new cluster
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.142 INFO      | etcd server [name 97c12d68c4fe4c188d26e79b681a7d2a, listen on :4001, advertised url http://172.17.8.1
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.142 INFO      | peer server [name 97c12d68c4fe4c188d26e79b681a7d2a, listen on :7001, advertised url http://172.17.8.1
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.142 INFO      | 97c12d68c4fe4c188d26e79b681a7d2a starting in peer mode
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.142 INFO      | 97c12d68c4fe4c188d26e79b681a7d2a: state changed from 'initialized' to 'follower'.
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.143 INFO      | 97c12d68c4fe4c188d26e79b681a7d2a: state changed from 'follower' to 'leader'.
Aug 20 18:47:56 core-01 etcd[1084]: [etcd] Aug 20 18:47:56.144 INFO      | 97c12d68c4fe4c188d26e79b681a7d2a: leader changed from '' to '97c12d68c4fe4c188d26e79b681a7d2a'.

core@core-02 ~ $ journalctl -u etcd
-- Logs begin at Thu 2015-08-20 18:48:06 UTC, end at Thu 2015-08-20 18:51:13 UTC. --
Aug 20 18:48:19 core-02 systemd[1]: Started etcd.
Aug 20 18:48:19 core-02 systemd[1]: Starting etcd...
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.032 INFO      | 49b4026aee4c4cfda04daf58a115e53d is starting a new cluster
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.033 INFO      | etcd server [name 49b4026aee4c4cfda04daf58a115e53d, listen on :4001, advertised url http://172.17.8.1
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.034 INFO      | peer server [name 49b4026aee4c4cfda04daf58a115e53d, listen on :7001, advertised url http://172.17.8.1
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.034 INFO      | 49b4026aee4c4cfda04daf58a115e53d starting in peer mode
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.034 INFO      | 49b4026aee4c4cfda04daf58a115e53d: state changed from 'initialized' to 'follower'.
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.034 INFO      | 49b4026aee4c4cfda04daf58a115e53d: state changed from 'follower' to 'leader'.
Aug 20 18:48:20 core-02 etcd[1093]: [etcd] Aug 20 18:48:20.034 INFO      | 49b4026aee4c4cfda04daf58a115e53d: leader changed from '' to '49b4026aee4c4cfda04daf58a115e53d'.

core@core-03 ~ $ journalctl -u etcd
-- Logs begin at Thu 2015-08-20 18:48:30 UTC, end at Thu 2015-08-20 18:52:37 UTC. --
Aug 20 18:48:42 core-03 systemd[1]: Started etcd.
Aug 20 18:48:42 core-03 systemd[1]: Starting etcd...
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.652 INFO      | 3f8acdb002ec462b92ad92d61be66de1 is starting a new cluster
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.653 INFO      | etcd server [name 3f8acdb002ec462b92ad92d61be66de1, listen on :4001, advertised url http://172.17.8.1
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.653 INFO      | peer server [name 3f8acdb002ec462b92ad92d61be66de1, listen on :7001, advertised url http://172.17.8.1
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.653 INFO      | 3f8acdb002ec462b92ad92d61be66de1 starting in peer mode
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.653 INFO      | 3f8acdb002ec462b92ad92d61be66de1: state changed from 'initialized' to 'follower'.
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.654 INFO      | 3f8acdb002ec462b92ad92d61be66de1: state changed from 'follower' to 'leader'.
Aug 20 18:48:42 core-03 etcd[1027]: [etcd] Aug 20 18:48:42.654 INFO      | 3f8acdb002ec462b92ad92d61be66de1: leader changed from '' to '3f8acdb002ec462b92ad92d61be66de1'.
```

let me know if there is any more information i can provide for debugging.

**Comment by ilackarms** [comment]
there was a type in the discovery token i was using in my user-data file

**Comment by xiang90** [comment]
@ilackarms 
Glad you figured it out! 
I would suggest you to try etcd2 instead of etcd if you are trying etcd. Thanks!
