### ISSUE TITLE
explore to use `git describe` to replace hardcoded version strings

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3345]
from @crawford : [Ignition](https://github.com/coreos/ignition) might be a good model to use. It uses `git describe` to [generate the version number](https://github.com/coreos/ignition/blob/master/build#L6) (no more hardcoded version strings). It also [reports itself in the log](https://github.com/coreos/ignition/blob/master/src/main.go#L85).

It is a good thing, so we dont' need to bump version manually.

Some concerns:
1. it doesn't strictly follow semver
2. if user doesn't use build script, he will end up with no etcd version.

/cc @crawford @vcaputo

**Comment by vcaputo** [comment]
One limitation in the ignition model is that we can't export releases for consumption outside of a git tree which use the existing build script as-is, now that our build script integrates with git for deriving the version.

This should be easily remedied with a release script sticking the git-derived version in a file and some minor changes to the build script to use the file when present.

**Comment by xiang90** [comment]
@yichengq More thoughts on this one? Or shall we simply keep today's approach?

**Comment by yichengq** [comment]
@vcaputo we want etcd to work fine when people `go get github.com/coreos/etcd`, so we don't have the assumption that build will always go through build script.

It could be easy to forget to update the git-derived version file when commiting.

**Comment by crawford** [comment]
@yichengq why? That seems like an arbitrary (and silly) requirement. What is the use-case?

**Comment by yichengq** [comment]
`go get` is the standard way in Go to download and install(https://golang.org/cmd/go/), and we would like to be a good citizen in Go.

This could enable fast try master by simply:
```
go get github.com/coreos/etcd
etcd
```

**Comment by crawford** [comment]
`go get` is for downloading packages and their dependencies. In this case, the user is downloading the project and building the binary. It seems completely reasonable to require the user to download _all_ of the necessary pieces, not just the code.

I understand what you are saying though. Other tools are installed via `go get` (which is incredibly misguided) so it's reasonable for us to do the same.

**Comment by xiang90** [comment]
@yichengq @crawford I hope we can make go tool chain work for etcd even if it is not perfect. If there is a huge disadvantage for making go tool chain work, then we may consider dropping the support of it.

**Comment by crawford** [comment]
I spoke with @yichengq yesterday about the versioning (unrelated to this) and realized that you are also using the version numbers on the wire (the combination of version and minVersion determines who is allowed to communicate). Hard-coding the version number is the only safe way to do this. A mixture of git tags and hard-coded strings is asking for trouble. You should stick with what you have.

**Comment by yichengq** [comment]
@crawford Agree.
