### ISSUE TITLE
Unexpected EOF 

### ISSUE THREAD

**Issue by dalanlan** [coreos/etcd#3347]
###scenario
- Running an etcd container for k8s 
- version:2.0.9

###startup param
docker -H unix:///var/run/docker-bootstrap.sock run --restart=on-failure:10 --net=host -d -v /mnt/etcd:/var/etcd/data/ gcr.io/google_containers/etcd:2.0.9 /usr/local/bin/etcd  --addr=${PRIVATE_IP}:4001 --bind-addr=0.0.0.0:4001 --data-dir=/var/etcd/data

###logs for etcd
It complains "on space on device", which is *not* the case since i'm aware. 
```
2015/08/21 02:04:22 etcdserver: save state and entries error: write /var/etcd/data/member/wal/0000000000000010-0000000000027111.wal: no space left on device
2015/08/21 02:04:24 etcd: already initialized as member before, starting as etcd member...
2015/08/21 02:04:24 etcd: listening for peers on http://localhost:2380
2015/08/21 02:04:24 etcd: listening for peers on http://localhost:7001
2015/08/21 02:04:24 etcd: listening for client requests on http://0.0.0.0:4001
2015/08/21 02:04:24 etcdserver: datadir is valid for the 2.0.1 format
2015/08/21 02:04:25 etcdserver: recovered store from snapshot at index 160016
2015/08/21 02:04:25 etcdserver: name = default
2015/08/21 02:04:25 etcdserver: data dir = /var/etcd/data
2015/08/21 02:04:25 etcdserver: member dir = /var/etcd/data/member
2015/08/21 02:04:25 etcdserver: heartbeat = 100ms
2015/08/21 02:04:25 etcdserver: election = 1000ms
2015/08/21 02:04:25 etcdserver: snapshot count = 10000
2015/08/21 02:04:25 etcdserver: advertise client URLs = http://10.168.123.53:4001
2015/08/21 02:04:25 etcdserver: loaded cluster information from store: default=http://localhost:2380,default=http://localhost:7001
2015/08/21 02:04:25 etcdserver: read wal error: unexpected EOF
```

**Comment by xiang90** [comment]
@dalanlan Do you want to know there is the no space left error or you want to know why there is a EOF error after restart?

**Comment by dalanlan** [comment]
I'm fully aware that etcd wont recover from wal read error even after restart in this case.
My main concern is how etcd detects the space usage while it attempts to write data.

**Comment by xiang90** [comment]
@dalanlan 

1. etcd is able to recover from this error if you make space available for etcd again after 2.1 release. 

2. etcd will detect potential disk space issue by preallocating space for newly created wal file after 2.2 release.

The go io library (or to be more specific write syscall if you were running linux) returned the no space to etcd.

**Comment by dalanlan** [comment]
Fair enough. 
Yet i assume 2.1.x is still under test for k8s for now.
Thank you for your concern.

**Comment by xiang90** [comment]
@dalanlan 

Thanks for reporting. 
Glad to see people from ZJU(I graduated from ZJU in 2012) are helping on etcd and k8s.

**Comment by dalanlan** [comment]
Cool :)

**Comment by yichengq** [comment]
P.S.: -addr and -bind-addr have been deprecated, and we recommend to use xxx-urls. You could check  https://github.com/coreos/etcd/blob/master/Documentation/configuration.md for more details. And here is bootstrap example: https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static

**Comment by dalanlan** [comment]
Ic.
Yet i'll bet the new flags are introduced for 2.1.x version, i'll upgrade it as long as k8s does officially(See also [this comment](https://github.com/kubernetes/kubernetes/pull/11960#issuecomment-126487128). 
I dont mind taking a step ahead, just worried that some components would get unhappy.
Again thank you for your time.

**Comment by yichengq** [comment]
@dalanlan These flags have been introduced since 2.0. Feel free to try it. :)

**Comment by dalanlan** [comment]
If that's the case, sure i will :)
