### ISSUE TITLE
Too much data is returned on a successful CompareAndSwap

### ISSUE THREAD

**Issue by fraenkel** [coreos/etcd#3363]
We noticed that when you successfully compare and swap, we receive both the previous and current node information. This is overkill in most situations since I knew what I cared about from the previous and I provided the data for the new node. What is most useful is the new modification index.

Would it be possible to add a new flag to just fill out the new modification index and not provide the previous node information nor the current node's data?

**Comment by sykesm** [comment]
It appears the same is true for CompareAndDelete.

**Comment by xiang90** [comment]
@fraenkel @sykesm We are OK for adding a feature flag and preserving the previous behavior by default. Also I would like to see efficiency and performance increment number to justify we do need it.  

However, we do not think this would be a high priority thing for etcd team right now. v2 API is in maintenance mode and we are working on v3 api. We would love to see a pull request from you guys if you want to make it happen.

**Comment by fraenkel** [comment]
We wanted to discuss it before we did anything.
In our case we have become sensitive to any unnecessary data flowing. When we operate against a large number of items each approximately 6k in size, the cost to encode/decode JSON is costing us valuable time. We know the cost when we use a recursive GET retrieving 100k items, while it's not nearly as high for our CAS/CAD usage, it can be on the order of 1000s for some of our cases. Having the data come back at all and then 2x is basically a cost. We can get some exact numbers for you.

**Comment by xiang90** [comment]
@fraenkel 

Let me make this more clear:

1. we need some number and use case to justify the additional flag for v2

2. we are designing v3 api. we will keep this in mind. The main goal of v3 is flexibility and efficiency.

**Comment by fraenkel** [comment]
I am in the process of doing the performance testing to see the cost of the extra data.

I have been struggling to generate new protobufs and run a build. It seems I can do one or the other but not both on OSX.
If I run genproto one too many times, I get 
`cp: /Users/fraenkel/workspace/etcd/gopath/src/github.com/coreos/etcd/./wal/walpb/record.proto and record.proto are identical (not copied).`

I also noticed that genproto installs many of the protobuf tool but the build tries to use it from Godeps. 
genproto assumes gopath is not a symlink and build assumes its a symlink. But neither do proper cleanup or recovery.

Just trying to figure out how to generate and build.

**Comment by fraenkel** [comment]
Did figure out the magic to get a build going. Not going to say it was obvious but anyhow here are the results.

My test was pretty straightforward,

Perform 15k sets with 7k of data.
Perform 15k CompareAndSwap with the same 7k using prevIndex only.

Using SHA 008f988f6bbac3cf777fe783992636326b8de2bf (master)

Operation | Original | No Nodes
------------- | ----------  | ----------
set time | +1.381558e+001 | +1.353714e+001
update time | +1.762903e+001 | +1.270849e+001

You can see almost a 5s savings just on the updates.
I am not thrilled how I had to do this since there are many places that rely on the Nodes being available, but I did manage to scope the copy to cloning events since thats the only safe place to do it when you are copying for the result.

**Comment by xiang90** [comment]
@fraenkel If you want to add a feature flag without affecting other stuff, I think it would be fine.

**Comment by xiang90** [comment]
basically, before marshaling the response, check the flag. If the flag is set, then set prevNode or whatever you think is unnecessary to nil.

**Comment by xiang90** [comment]
@fraenkel Are you still interested in working on this issue?

**Comment by fraenkel** [comment]
Sure. Let me see what I can do in a few days.
