### ISSUE TITLE
ETCD strange errors when starting with the opts

### ISSUE THREAD

**Issue by kgrvamsi** [coreos/etcd#3364]
The same settings which my other clusters are using fine but when i tried launching the etcd on a new server i get this error 

[root@masterv1 opt]# etcd -name infra1 -listen-client-urls http://127.0.0.1:4001 -advertise-client-urls http://127.0.0.1:4001 -listen-peer-urls http://127.0.0.1:7001 -initial-advertise-peer-urls http://127.0.0.1:7001
2015/08/24 11:14:45 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2015/08/24 11:14:45 etcdmain: no data-dir provided, using default data-dir ./infra1.etcd
2015/08/24 11:14:45 etcdmain: listening for peers on http://127.0.0.1:7001
2015/08/24 11:14:45 etcdmain: listening for client requests on http://127.0.0.1:4001
2015/08/24 11:14:45 etcdmain: stopping listening for client requests on http://127.0.0.1:4001
2015/08/24 11:14:45 etcdmain: stopping listening for peers on http://127.0.0.1:7001
2015/08/24 11:14:45 etcdmain: advertise URLs of "infra1" do not match in --initial-advertise-peer-urls [http://127.0.0.1:7001] and --initial-cluster [http://localhost:2380 http://localhost:7001]

**Comment by xiang90** [comment]
> etcdmain: advertise URLs of "infra1" do not match in --initial-advertise-peer-urls [http://127.0.0.1:7001] and --initial-cluster [http://localhost:2380 http://localhost:7001]

This log line points out the error. Please try to set `--initial-cluster` correctly. For more information, please check https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static.

**Comment by kgrvamsi** [comment]
@xiang90  i'm not setting a cluster ok let me put the error without the cluster option

Aug 24 11:46:56 masterv1 systemd[1]: etcd.service holdoff time over, scheduling restart.
Aug 24 11:46:56 masterv1 systemd[1]: Stopping etcd...
Aug 24 11:46:56 masterv1 systemd[1]: Starting etcd...
Aug 24 11:46:56 masterv1 systemd[1]: Started etcd.
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: found invalid file/dir default.etcd under data dir /opt/ (Ignore this if you are upgrading etcd)
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: found invalid file/dir nimsoft under data dir /opt/ (Ignore this if you are upgrading etcd)
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: listening for peers on http://localhost:2380
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: listening for client requests on http://localhost:2379
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: listening for client requests on http://localhost:4001
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: stopping listening for client requests on http://localhost:4001
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: stopping listening for client requests on http://localhost:2379
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: stopping listening for peers on http://localhost:2380
Aug 24 11:46:56 masterv1 etcd[17308]: 2015/08/24 11:46:56 etcdmain: advertise URLs of "default" do not match in --initial-advertise-peer-urls [http://local...host:7001]
Aug 24 11:46:56 masterv1 systemd[1]: etcd.service: main process exited, code=exited, status=1/FAILURE
Aug 24 11:46:56 masterv1 systemd[1]: Unit etcd.service entered failed state.

**Comment by xiang90** [comment]
@kgrvamsi Make sure the `advertise-url` matches the `initial-cluster`

**Comment by kgrvamsi** [comment]
i'm not running a cluster its a standalone service

here are the parameters i'm sending for the etcd

    ETCD_OPTS="--data-dir /opt/ \
     --advertise-client-urls http://localhost:2379,http://localhost:4001 \
     --listen-client-urls http://localhost:2379,http://localhost:4001 \
     --initial-advertise-peer-urls http://localhost:2380 \
     --listen-peer-urls http://localhost:2380"

**Comment by xiang90** [comment]
@kgrvamsi Standalone etcd is still an one member cluster. Could you please make sure the `--initial-advertise-peer-urls` matches with the `--initial-cluster`. I can help you more if you could try what I just told you. Thanks.

**Comment by kgrvamsi** [comment]
@xiang90  thanks its working with the below settings

    etcd -name test -initial-advertise-peer-urls http://localhost:2380 --listen-peer-urls http://0.0.0.0:2380 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://localhost:2379 --initial-cluster-token client-uri-test --initial-cluster-state new --initial-cluster test=http://localhost:2380
