### ISSUE TITLE
Use old data to start new cluster

### ISSUE THREAD

**Issue by AdoHe** [coreos/etcd#3379]
@xiang90 I have an old etcd 2.0.4 cluster, but now I want to setup a new etcd 2.0.4 cluster, I copy the data dir from the old cluster and put it on one instance of the new cluster, and then try to start the new cluster with `-initial-cluster existing`, but just failed. etcd has write the cluster info into log, so when use old data, etcd will still load the old cluster info and just ignore the command line options.

**Comment by xiang90** [comment]
I do not quite sure what do you mean by it `just failed`. Any log output? Can you reproduce?

**Comment by AdoHe** [comment]
@xiang90 More info about this, I have an old etcd 2.0.2 cluster, which contains three node: `10.5.6.10 10.5.6.11 10.5.6.12`, and the startup script like this:
```
etcd1: bin/etcd -name infra1 -data-dir machines/machines1 -listen-client-urls http://10.5.6.10:4001 -advertise-client-urls http://10.5.6.10:4001 -listen-peer-urls http://10.5.6.10:7001 -initial-advertise-peer-urls http://10.5.6.10:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://10.5.6.10:7001,infra2=http://10.5.6.11:7001,infra3=http://10.5.6.12:7001' -cors="*" -initial-cluster-state new
etcd2: bin/etcd -name infra2 -data-dir machines/machine2 -listen-client-urls http://10.5.6.11:4001 -advertise-client-urls http://10.5.6.11:4001 -listen-peer-urls http://10.5.6.11:7001 -initial-advertise-peer-urls http://10.5.6.11:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://10.5.6.10:7001,infra2=http://10.5.6.11:7001,infra3=http://10.5.6.12:7001' -cors="*" -initial-cluster-state new
etcd3: bin/etcd -name infra3 -data-dir machines/machine3 -listen-client-urls http://10.5.6.12:4001 -advertise-client-urls http://10.5.6.12:4001 -listen-peer-urls http://10.5.6.12:7001 -initial-advertise-peer-urls http://10.5.6.12:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://10.5.6.10:7001,infra2=http://10.5.6.11:7001,infra3=http://10.5.6.12:7001' -cors="*" -initial-cluster-state new
```
and this cluster has been working for a long time, but now I try to setup a new etcd 2.0.4 cluster with three nodes: `10.5.7.40 10.5.7.41 10.5.7.42`. First I copy the `machines/machine1` data dir to one node `10.5.7.40` and then I start the cluster with such script
```
etcd1: bin/etcd -name infra1 -data-dir machines/machines1 -listen-client-urls http://10.5.7.40:4001 -advertise-client-urls http://10.5.7.40:4001 -listen-peer-urls http://10.5.7.40:7001 -initial-advertise-peer-urls http://10.5.7.40:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://10.5.7.40:7001,infra2=http://10.5.7.41:7001,infra3=http://10.5.7.42:7001' -cors="*" -initial-cluster-state existing 1>/etcd_logs/out.log 2>/etcd_logs/err.log 
etcd2: bin/etcd -name infra2 -data-dir machines/machine2 -listen-client-urls http://10.5.7.41:4001 -advertise-client-urls http://10.5.7.41:4001 -listen-peer-urls http://10.5.7.41:7001 -initial-advertise-peer-urls http://10.5.7.41:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://10.5.7.40:7001,infra2=http://10.5.7.41:7001,infra3=http://10.5.7.42:7001' -cors="*" -initial-cluster-state existing 1>/etcd_logs/out.log 2>/etcd_logs/err.log
etcd3: bin/etcd -name infra3 -data-dir machines/machine3 -listen-client-urls http://10.5.7.42:4001 -advertise-client-urls http://10.5.7.42:4001 -listen-peer-urls http://10.5.7.42:7001 -initial-advertise-peer-urls http://10.5.7.42:7001 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://10.5.7.40:7001,infra2=http://10.5.7.41:7001,infra3=http://10.5.7.42:7001' -cors="*" -initial-cluster-state existing 1>/etcd_logs/out.log 2>/etcd_logs/err.log 
```
I just found I can not startup the cluster, and there is no etcd process on three nodes, I checked the `err.log` on `10.5.7.40` and found it still load old cluster information from data file. But if I don't copy the data to the new cluster, and startup the cluster with `-initial-cluster-state new`, the cluster will startup successfully.

**Comment by xiang90** [comment]
@AdoHe Ah... So the cluster identification and member identification are actually tight to the data dir. So when you restart with the old data dir, you are actually restarting the old member... So do not do that. Please read the doc here https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#lifecycle

What you should do is to online upgrade your cluster, you can follow the doc here https://github.com/coreos/etcd/blob/master/Documentation/upgrade_2_1.md.

Or if you wish to spin out a new cluster with the same data, you have to force out a new cluster(treat the old cluster dead...). You can follow the doc here: https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#disaster-recovery.

**Comment by AdoHe** [comment]
@xiang90, this seems OK, thanks very much.

**Comment by xiang90** [comment]
@AdoHe Great! I am closing this issue.
