### ISSUE TITLE
client: randomize client list

### ISSUE THREAD

**Issue by philips** [coreos/etcd#3386]
go-etcd now randomizes the client list when the client is created: https://github.com/coreos/go-etcd/pull/231

github.com/coreos/etcd/client should do this too

I discovered this as a user reported that fleet tries all members in the same order and thus most fleet load goes to a single member.

**Comment by yichengq** [comment]
@philips I think it has been improved at https://github.com/coreos/etcd/commit/ea2347a40f3e4778a29e4ec31e44d9333652bdd0

Which version of etcd/client is fleet using?

**Comment by mischief** [comment]
93002caca591fb51e0796813903c4fc1239f3ce7

**Comment by yichengq** [comment]
@mischief I think bump etcd/client should solve this problem.

**Comment by mischief** [comment]
@yichengq on it.

**Comment by xiang90** [comment]
Fixed by https://github.com/coreos/fleet/issues/1336
