### ISSUE TITLE
Etcd log can not be redirected, Why?

### ISSUE THREAD

**Issue by hyper-carrot** [coreos/etcd#3393]
I tried the following several kinds of methods:

```bash
./etcd >> etcd.log 2&>1 
```

```bash
./etcd | tee -a etcd.log
```

```bash
./etcd | cronolog etcd_%Y%m%d.log
```

But they are invalid. Any suggestion? Thanks!

**Comment by xiang90** [comment]
@hyper-carrot Since you used a wrong command, try `./etcd >> etcd.log 2>&1 `

**Comment by hyper-carrot** [comment]
@xiang90 e...It's a clerical mistake only. ;-)

**Comment by mengzhuo** [comment]
try 
```
./etcd &>> etcd.log
```
