### ISSUE TITLE
proxy: client 127.0.0.1:6155 closed request prematurely

### ISSUE THREAD

**Issue by f0** [coreos/etcd#3405]
Hi,

i am running a cluster version 2.1.1 and have some local proxys version 2.1.1 running, sometimes the etcdctl connection via proxy fails with this errors, then i need to restart the proxy to get it working again.

  etcdctl  -u root user list
 Password: 
  context deadline exceeded

this is in the logs
Aug 29 18:22:03 example.com etcd2[2646]: 2015/08/29 18:22:03 proxy: client 127.0.0.1:6155 closed request prematurely
Aug 29 18:22:03 example.com etcd2[2646]: 2015/08/29 18:22:03 proxy: client 127.0.0.1:6156 closed request prematurely
Aug 29 18:22:03 example.com etcd2[2646]: 2015/08/29 18:22:03 proxy: client 127.0.0.1:6157 closed request prematurely
Aug 29 18:22:03 example.com etcd2[2646]: 2015/08/29 18:22:03 proxy: client 127.0.0.1:6158 closed request prematurely
Aug 29 18:22:03 example.com etcd2[2646]: 2015/08/29 18:22:03 proxy: client 127.0.0.1:6159 closed request prematurely

At the same time when using etcdctl with the real cluster , it does work

**Comment by f0** [comment]
ok you can reproduce this with

while true ; do etcdctl ls  ; done 

btw. i have removed all localhost client urls from the cluster, now i do not need to restart the proxy to get it working again

**Comment by xiang90** [comment]
You have to provide more information. I do not have the configuration of your cluster. See https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

But this `all localhost advertised client urls` looks very suspicious. See https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-advertise-client-urls

**Comment by floriankoch** [comment]
Hi,

this is my cluster config, i have eliminated all localhost advertise client urls

[member]
ETCD_NAME="zkm1"
ETCD_DATA_DIR="/var/lib/etcd/etcd1.etcd"
ETCD_LISTEN_PEER_URLS="http://zkm01.example.net:2380"
ETCD_LISTEN_CLIENT_URLS="http://zkm01.example.net:2379,http://127.0.0.1:2379"

[cluster]
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://zkm01.example.net:2380"
ETCD_INITIAL_CLUSTER="zkm1=http://zkm01.example.net:2380,zkm6=http://zkm6.example.net:2380,zkm4=http://zkm4.example.net:2380,zkm2=http://zkm02.example.net:2380,zkm5=http://zkm5.example.net:2380,zkm3=http://zkm03.example.net:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"
ETCD_ADVERTISE_CLIENT_URLS="http://zkm01.example.net:2379"

**Comment by xiang90** [comment]
@f0 @floriankoch Still see the same issue after removing localhost client endpoints? Are you sure zkm01.example.net does not resolve to localhost?

**Comment by floriankoch** [comment]
yes
if i list my cluster members, no localhost are shown. 

bfd4023b0c6e8d6: name=zkm1 peerURLs=http://zkm01.example.net:2380 clientURLs=http://zkm01.example.net:2379
1f029defcea02404: name=zkm6 peerURLs=http://zkm6.example.net:2380 clientURLs=http://zkm06.example.net:2379
a80cff776210b15c: name=zkm2 peerURLs=http://zkm02.example.net:2380 clientURLs=http://zkm02.example.net:2379
bd19b4ffc2b7182d: name=zkm3 peerURLs=http://zkm03.example.net:2380 clientURLs=http://zkm03.example.net:2379
d8f2630822b402e5: name=zkm5 peerURLs=http://zkm5.example.net:2380 clientURLs=http://zkm05.example.net:2379

**Comment by xiang90** [comment]
@f0 @floriankoch OK. I will try to reproduce this myself. Ideally, you can try to run the Procfile in etcd repo to set up a local cluster with proxy and verify you can reproduce this issue.

**Comment by soellman** [comment]
We're seeing this too but I can't replicate it using etcdctl (on the proxy nodes). I can say that we're doing a lot of watches on the proxy nodes and using the claws/aioetcd python client (which is probably doing something weird).

Also 2.1.1.

**Comment by michalmedvecky** [comment]
The same thing started happening to me after upgrade from coreos stable to coreos beta.
Sep 07 13:02:02 test etcd2[677]: 2015/09/7 13:02:02 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:02 test etcd2[677]: 2015/09/7 13:02:02 proxy: marked endpoint http://10.240.135.37:4001 unavailable
Sep 07 13:02:02 test etcd2[677]: 2015/09/7 13:02:02 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:07 test etcd2[677]: 2015/09/7 13:02:07 proxy: marked endpoint http://10.240.135.37:4001 available
Sep 07 13:02:10 test etcd2[677]: 2015/09/7 13:02:10 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:10 test etcd2[677]: 2015/09/7 13:02:10 proxy: marked endpoint http://10.240.135.37:4001 unavailable
Sep 07 13:02:10 test etcd2[677]: 2015/09/7 13:02:10 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:10 test etcd2[677]: 2015/09/7 13:02:10 proxy: client 127.0.0.1:41939 closed request prematurely
Sep 07 13:02:15 test etcd2[677]: 2015/09/7 13:02:15 proxy: marked endpoint http://10.240.135.37:4001 available
Sep 07 13:02:16 test etcd2[677]: 2015/09/7 13:02:16 proxy: client 127.0.0.1:41941 closed request prematurely
Sep 07 13:02:17 test etcd2[677]: 2015/09/7 13:02:17 proxy: client 127.0.0.1:41936 closed request prematurely
Sep 07 13:02:17 test etcd2[677]: 2015/09/7 13:02:17 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:17 test etcd2[677]: 2015/09/7 13:02:17 proxy: marked endpoint http://10.240.135.37:4001 unavailable
Sep 07 13:02:17 test etcd2[677]: 2015/09/7 13:02:17 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:18 test etcd2[677]: 2015/09/7 13:02:18 proxy: client 127.0.0.1:41948 closed request prematurely

Sep 07 13:02:22 test etcd2[677]: 2015/09/7 13:02:22 proxy: marked endpoint http://10.240.135.37:4001 available
Sep 07 13:02:24 test etcd2[677]: 2015/09/7 13:02:24 proxy: client 127.0.0.1:41952 closed request prematurely
Sep 07 13:02:25 test etcd2[677]: 2015/09/7 13:02:25 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:25 test etcd2[677]: 2015/09/7 13:02:25 proxy: marked endpoint http://10.240.135.37:4001 unavailable
Sep 07 13:02:25 test etcd2[677]: 2015/09/7 13:02:25 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:26 test etcd2[677]: 2015/09/7 13:02:26 proxy: client 127.0.0.1:41958 closed request prematurely
Sep 07 13:02:27 test etcd2[677]: 2015/09/7 13:02:27 proxy: client 127.0.0.1:41960 closed request prematurely
Sep 07 13:02:28 test etcd2[677]: 2015/09/7 13:02:28 proxy: client 127.0.0.1:41962 closed request prematurely
Sep 07 13:02:30 test etcd2[677]: 2015/09/7 13:02:30 proxy: marked endpoint http://10.240.135.37:4001 available
Sep 07 13:02:30 test etcd2[677]: 2015/09/7 13:02:30 proxy: client 127.0.0.1:41964 closed request prematurely
Sep 07 13:02:32 test etcd2[677]: 2015/09/7 13:02:32 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:32 test etcd2[677]: 2015/09/7 13:02:32 proxy: marked endpoint http://10.240.135.37:4001 unavailable
Sep 07 13:02:32 test etcd2[677]: 2015/09/7 13:02:32 proxy: client 127.0.0.1:41950 closed request prematurely
Sep 07 13:02:32 test etcd2[677]: 2015/09/7 13:02:32 proxy: client 127.0.0.1:41954 closed request prematurely
Sep 07 13:02:32 test etcd2[677]: 2015/09/7 13:02:32 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout
Sep 07 13:02:32 test etcd2[677]: 2015/09/7 13:02:32 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout

**Comment by xiang90** [comment]
@f0 @soellman @micahhausler I failed to reproduce with a 3 member cluster + 1 proxy setup. Can you provide me a way to reproduce this issue? From the logging, this simply means the client closed a http request before it gets the response.

**Comment by xiang90** [comment]
@michalmedvecky 

> Sep 07 13:02:02 test etcd2[677]: 2015/09/7 13:02:02 proxy: failed to direct request to http://10.240.135.37:4001: dial tcp 10.240.135.37:4001: i/o timeout

Your proxy cannot connect to the etcd cluster you set. You have to check your configuration.

**Comment by soellman** [comment]
No I can't reproduce it with a test cluster.. I'm guessing that the client I'm using is buggy.

However I think that the message "proxy: client xxx closed request prematurely", if the operation isn't actually a problem for etcd, should be at debug level and not show up in the regular log.

**Comment by xiang90** [comment]
@soellman I am still not sure if this is a client error or a proxy error. My best guess is that: this is a client error. So I want to reproduce it make sure. However I failed :(

**Comment by michalmedvecky** [comment]
> @soellman <https://github.com/soellman> I am still not sure if this is a client error or a proxy error. My best guess is that: this is a client error. So I want to reproduce it make sure. However I failed :
> 
> 
Sorry guys, my problem was that one of my etcd nodes was really down.

**Comment by xiang90** [comment]
@michalmedvecky Ah. OK. No problem. I have to count on @f0 then. :)

**Comment by xiang90** [comment]
@fasaxc @webner @mwitkow-io @sorah 

I know you guys are running etcd with proxy in production. Have you tried etcd 2.1? Do you see this behavior?

**Comment by xiang90** [comment]
@f0 Kindly ping.

**Comment by webner** [comment]
I have etcd 2.1.2 in production and see some of these (every couple of hours):
`proxy: client 127.0.0.1:37676 closed request prematurely`
But the proxy seems to be rock stable.

**Comment by xiang90** [comment]
@webner Do you think they are actually client issues?

**Comment by shenshouer** [comment]
I have etcd 2.0.12 and see some of these , just like:

  Sep 15 15:14:16 core-1-85 etcd2[1091]: 2015/09/15 15:14:16 proxy: client 127.0.0.1:51512 closed request prematurely
  Sep 15 15:14:22 core-1-85 etcd2[1091]: 2015/09/15 15:14:22 proxy: client 127.0.0.1:51495 closed request prematurely
  Sep 15 15:17:26 core-1-85 etcd2[1091]: 2015/09/15 15:17:26 proxy: client 127.0.0.1:51758 closed request prematurely
  Sep 15 15:19:13 core-1-85 etcd2[1091]: 2015/09/15 15:19:13 proxy: client 127.0.0.1:51743 closed request prematurely
  Sep 15 15:20:56 core-1-85 etcd2[1091]: 2015/09/15 15:20:56 proxy: client 127.0.0.1:51760 closed request prematurely
  Sep 15 15:20:57 core-1-85 etcd2[1091]: 2015/09/15 15:20:57 proxy: client 127.0.0.1:51787 closed request prematurely
  Sep 15 15:21:00 core-1-85 etcd2[1091]: 2015/09/15 15:21:00 proxy: client 127.0.0.1:51799 closed request prematurely
  Sep 15 15:21:01 core-1-85 etcd2[1091]: 2015/09/15 15:21:01 proxy: client 127.0.0.1:51800 closed request prematurely

when this appeared , I cannot read data from etcd with etcdctl, and report as :

  Error from server: 501: All the given peers are not reachable (failed to propose on members [http://127.0.0.1:4001] twice [last error: Unexpected HTTP status code]) [0]

**Comment by f0** [comment]
@xiang90   

ok now i am using 2.1.3 on all sides (server , proxy, client (etcdctl)) i can NOT reproduce the problem any longer! 

Using a proxy 2.1.1, i can reproduce it!

So it seems fixed.

regards f0

**Comment by xiang90** [comment]
@shenshouer Can you reliable reproduce this? After reading through all these, I think it is not a proxy issue. Probably you have set some timeout on the client side, and the client reaches its timeout and closes connection. We should probably move the proxy logging level to debug.

**Comment by shenshouer** [comment]
@xiang90 

    core@core-1-85 ~ $ systemctl status -l etcd2
    ● etcd2.service - etcd2
       Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; disabled; vendor preset: disabled)
      Drop-In: /run/systemd/system/etcd2.service.d
               └─20-cloudinit.conf
       Active: active (running) since Wed 2015-09-09 19:28:58 CST; 6 days ago
      Main PID: 1091 (etcd2)
       Memory: 7.1M
      CPU: 14min 1.571s
       CGroup: /system.slice/etcd2.service
               └─1091 /usr/bin/etcd2

    Sep 16 10:03:53 core-1-85 etcd2[1091]: 2015/09/16 10:03:53 proxy: client 127.0.0.1:56653 closed request prematurely
    Sep 16 10:07:58 core-1-85 etcd2[1091]: 2015/09/16 10:07:58 proxy: client 127.0.0.1:56651 closed request prematurely
    Sep 16 10:09:37 core-1-85 etcd2[1091]: 2015/09/16 10:09:37 proxy: client 127.0.0.1:56588 closed request prematurely
    Sep 16 10:10:39 core-1-85 etcd2[1091]: 2015/09/16 10:10:39 proxy: client 127.0.0.1:56695 closed request prematurely
    Sep 16 10:12:59 core-1-85 etcd2[1091]: 2015/09/16 10:12:59 proxy: client 127.0.0.1:56623 closed request prematurely
    Sep 16 10:16:55 core-1-85 etcd2[1091]: 2015/09/16 10:16:55 proxy: client 127.0.0.1:56561 closed request prematurely
    Sep 16 10:18:00 core-1-85 etcd2[1091]: 2015/09/16 10:18:00 proxy: client 127.0.0.1:56703 closed request prematurely
    Sep 16 10:20:07 core-1-85 etcd2[1091]: 2015/09/16 10:20:07 proxy: client 127.0.0.1:56675 closed request prematurely
    Sep 16 10:20:08 core-1-85 etcd2[1091]: 2015/09/16 10:20:08 proxy: client 127.0.0.1:56677 closed request prematurely
    Sep 16 10:23:01 core-1-85 etcd2[1091]: 2015/09/16 10:23:01 proxy: client 127.0.0.1:56721 closed request prematurely


and in /run/systemd/system/etcd2.service.d/20-cloudinit.conf
      core@core-1-85 ~ $ cat /run/systemd/system/etcd2.service.d/20-cloudinit.conf
      [Service]
      Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.12.1.85:2379,http://10.12.1.85:4001"
      Environment="ETCD_DISCOVERY=https://discovery.etcd.io/c741d71c1d69fd82b0d1ce90f342de3b"
      Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.12.1.85:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://10.12.1.85:2379,http://10.12.1.85:4001,http://127.0.0.1:2379,http://127.0.0.1:4001"
      Environment="ETCD_LISTEN_PEER_URLS=http://10.12.1.85:2380,http://10.12.1.85:7001"
      Environment="ETCD_NAME=core-1-85"


and in /var/lib/coreos-install/user-data

    coreos:
      etcd2:
        name: core-1-85
        discovery: https://discovery.etcd.io/c741d71c1d69fd82b0d1ce90f342de3b
        listen-client-urls: http://10.12.1.85:2379,http://10.12.1.85:4001,http://127.0.0.1:2379,http://127.0.0.1:4001
        advertise-client-urls: http://10.12.1.85:2379,http://10.12.1.85:4001
        listen-peer-urls: http://10.12.1.85:2380,http://10.12.1.85:7001
        initial-advertise-peer-urls: http://10.12.1.85:2380
      update:
        group: stable
        reboot-strategy: off
      fleet:
        public-ip: 10.12.1.85
        metadata: "role=minion"
      flannel:
        interface: 10.12.1.85
      units:
        - name: etcd2.service
          command: start
        - name: setup-network-environment.service
          command: start
          content: |
            [Unit]
            Description=Setup Network Environment
            Documentation=https://github.com/kelseyhightower/setup-network-environment
            Requires=network-online.target
            After=network-online.target
            [Service]
            ExecStartPre=/usr/bin/timedatectl set-timezone Asia/Shanghai
            #ExecStartPre=/usr/bin/ntpdate -u cn.pool.ntp.org
            ExecStart=/opt/bin/setup-network-environment
            RemainAfterExit=yes
            Type=oneshot
        - name: fleet.service
          command: start
        - name: flanneld.service
        ......

**Comment by f0** [comment]
@xiang90   can i something? For me the Probem is gone with the update to 2.1.3

**Comment by soellman** [comment]
For posterity, this blog post exactly describes the problem. The engineer on our team who first saw this agrees that this is our exact issue.

http://www.projectclearwater.org/adventures-in-debugging-etcd-http-pipelining-and-file-descriptor-leaks/

**Comment by f0** [comment]
@xiang90  do you still need more infos?

**Comment by xiang90** [comment]
@f0 I think @soellman has a reasonable explanation. We need to wait for the upstream to solve https://github.com/golang/go/issues/13165 before looking into this again.

**Comment by xiang90** [comment]
@f0 @soellman

Basically, HTTP pipelining behavior does not work well with go's http close notification. Please take a look at golang/go#13165 for more information. The best fix is to disable pipelining in the client library you are using. etcd/client does not use pipelining.
