### ISSUE TITLE
Build script exit with error "Syntax error: redirection unexpected"

### ISSUE THREAD

**Issue by fatih** [coreos/etcd#3417]
Hi,

We use etcd for our project Kite (https://github.com/koding/kite). We saw that our latest PR all failed because we couldn't start up ETCD on travis.  Here is on of the failed builds: https://travis-ci.org/koding/kite/jobs/78066380

Investigating more it seems the build script doesn't execute well because the `<<<` herestring are not supported on `sh`. I think this was introduced two days ago with:

https://github.com/coreos/etcd/commit/dd4317db434ba36c0b39c74fffee8cd6c9e0769f

More info about this can be also find in this SO question: http://stackoverflow.com/questions/2462317/bash-syntax-error-redirection-unexpected

I assume changing the script reference to `/bin/bash` would solve this problem. Another solution would be not using `<<<` at all.

**Comment by AdoHe** [comment]
@fatih I think both options will solve this problem, maybe the second one is much better. I just create a new pull request, you may have a look: https://github.com/coreos/etcd/pull/3418

**Comment by yichengq** [comment]
@fatih This should have been fixed by @AdoHe . Welcome to check it in your project!

**Comment by fatih** [comment]
@yichengq thanks much! I'll try it asap. It's weird I didn't get a single notification from this at all. Just checked the spam folder, nope no e-mail from Github there too.

**Comment by fatih** [comment]
Confirmed, fix works well: https://github.com/koding/kite/pull/128 Thanks @AdoHe & @yichengq
