### ISSUE TITLE
add link for github issue in release page

### ISSUE THREAD

**Issue by gouyang** [coreos/etcd#3426]
Where is the ChangeLog or release file? I search the repository and could not find it.

When read https://github.com/coreos/etcd/releases, it's inconvenient to browse the github issue as it has no link.

eg:
v2.1.2 ChangeLog
 [GH 3143] improve output for command line flag parsing errors

and in this particular issue, the number 3143 should be 3141.

**Comment by xiang90** [comment]
> Where is the ChangeLog or release file? 

We stop maintaining one. We use release to manage it.

> it's inconvenient to browse the github issue as it has no link.

We will add link in the next release.

Thanks for reporting.
