### ISSUE TITLE
docs: elaborate on cluster failure scenarios

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#3428]
SRV:
 - when do you need to set up the record
 - what happens if this is done incorrectly
 - what do you need to do when a node fails
 - what happens during a DNS outage

Discovery:
 - what happens when the service is down

**Comment by joshix** [comment]
(note to self: related and/or Cf. https://github.com/coreos/etcd/tree/master/contrib/systemd/etcd2-backup-coreos)

**Comment by joshix** [comment]
related https://github.com/coreos/docs/pull/734

**Comment by joshix** [comment]
Moved to 3.0 milestone to re-examine after 2.3.0 release. The links in my previous comments show where we've solved about half of this issue already.
