### ISSUE TITLE
Release page docker instructions fail

### ISSUE THREAD

**Issue by bboreham** [coreos/etcd#3455]
I tried the command shown to run etcd using docker [on the release page](https://github.com/coreos/etcd/releases/tag/v2.1.3)

> docker run -p 2379:2379 -v /usr/share/ca-certificates/:/etc/ssl/certs quay.io/coreos/etcd:v2.1.3

But trying to use my new etcd fails:

    $ ./etcdctl set mykey "this is awesome"
    Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379

Following the longer example [at the top of this page](https://coreos.com/etcd/docs/latest/docker_guide.html) worked.

Test was run on Ubuntu 15.04, Docker 1.7.1

**Comment by xiang90** [comment]
@bboreham By default, etcd listen on localhost. It does run inside the container. Just the network setup is not correct. In the next release doc we will point it to the docker guide.

**Comment by bboreham** [comment]
This seems to have been forgotten.

**Comment by yichengq** [comment]
@bboreham Updated. I have even made it simpler to start.
