### ISSUE TITLE
Proxy doesnt specify in the logs whether it is listening on http or https

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3460]
Proxy doesnt specify in the logs whether it is listening on http or https.

It just specifies the host name on which it is listening on but not the type of connection http or https

**Comment by xiang90** [comment]
Do you want to send a pull request to make it clear?

**Comment by raoofm** [comment]
sure i will

**Comment by raoofm** [comment]
tested this... works fine

**Comment by xiang90** [comment]
can you send a pull request? the change looks good to me.

**Comment by xiang90** [comment]
Fixed by #3465
