### ISSUE TITLE
Improve etcd usability

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#3470]
Main goal is to add "join" command for etcd daemon:

```
user@mynewnode: $ etcd2 --join-cluster %existing_cluster_node_ip%
```

Second goal is create web interface where you can:

* join existing cluster
* create new cluster
* if you run cluster, add node to your existing cluster

As an example you can review this couchbase doc: http://docs.couchbase.com/admin/admin/Tasks/rebalance-adding-nodes.html

p.s. din't have time to think more on implementation details

/cc @robszumski @yichengq

**Comment by xiang90** [comment]
@kayrus Sorry we are not going to support this. See https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#two-phase-config-changes-keep-you-safe. 

We are aware of this design and intentionally do not support it.

**Comment by yichengq** [comment]
I think first goal is not good, and current workflow is what we learn after interacting with users.

The web interface one is a good one, and it could make users to monitor and update the cluster easily.
