### ISSUE TITLE
use etcd-project specific key/cert to sign binaries

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3472]
etcd project needs a etcd-project specific key/cert, and use it to sign built release binaries. I use my personal key/cert to sign binaries today.

/cc @crawford

**Comment by yichengq** [comment]
@crawford and @mjg59 are in the process to figure out the most secure and standard way to provide key/cert. It is expected to have some result at the end of next week. I don't want to build some temporary key/cert for just two or three weeks, so I will let this issue pend on their works now.

**Comment by xiang90** [comment]
Sounds like we should move this out of 2.3 alpha1

**Comment by gyuho** [comment]
Any updates on this? We are still using my personal key (under my coreos.com email) to sign binaries.

**Comment by dghubble** [comment]
@yichengq we've started issuing subkeys to projects, as outlined in the internal security repo. I can get this for you next week. https://github.com/coreos-inc/security/issues/5

**Comment by gyuho** [comment]
https://github.com/coreos/etcd/releases/tag/v2.3.0 was released with etcd project key.
