### ISSUE TITLE
Etcd fails to upgrade from 0.4.6 to 2.13 

### ISSUE THREAD

**Issue by liangsuilong** [coreos/etcd#3475]
Here is etcd log. Converting data from 0.4 to 2.0 looks OK. But when the program loads cluster information, it is down. 

The etcd is not configured for cluster. It runs standalone. 

2015/09/10 02:36:41 etcdmain: etcd Version: 2.1.3
2015/09/10 02:36:41 etcdmain: Git SHA: 30801de
2015/09/10 02:36:41 etcdmain: Go Version: go1.5
2015/09/10 02:36:41 etcdmain: Go OS/Arch: linux/amd64
2015/09/10 02:36:41 etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 2
2015/09/10 02:36:41 etcdmain: found invalid file/dir conf under data dir /etcd.etcd (Ignore this if you are upgrading etcd)
2015/09/10 02:36:41 etcdmain: found invalid file/dir log under data dir /etcd.etcd (Ignore this if you are upgrading etcd)
2015/09/10 02:36:41 etcdmain: found invalid file/dir snap under data dir /etcd.etcd (Ignore this if you are upgrading etcd)
2015/09/10 02:36:41 etcdmain: found invalid file/dir snapshot under data dir /etcd.etcd (Ignore this if you are upgrading etcd)
2015/09/10 02:36:41 etcdmain: listening for peers on http://localhost:2380
2015/09/10 02:36:41 etcdmain: listening for peers on http://localhost:7001
2015/09/10 02:36:41 etcdmain: listening for client requests on http://localhost:2379
2015/09/10 02:36:41 etcdmain: listening for client requests on http://localhost:4001
2015/09/10 02:36:41 etcdserver: converting v0.4 log to v2.0
2015/09/10 02:36:41 Decoding snapshot from /etcd.etcd/snapshot/100_34037068.ss
2015/09/10 02:36:41 Using suggested name etcd
2015/09/10 02:36:41 Assigning etcd the ID e52ada62956ff923
2015/09/10 02:36:41 Found snapshot: lastIndex=34037068
2015/09/10 02:36:41 Found 4790 log entries: firstIndex=56890327 lastIndex=56895116
2015/09/10 02:36:41 Log migration successful
2015/09/10 02:36:41 Snapshot migration successful
2015/09/10 02:36:41 etcdserver: recovered store from snapshot at index 34037068
2015/09/10 02:36:41 etcdserver: name = etcd
2015/09/10 02:36:41 etcdserver: data dir = /etcd.etcd
2015/09/10 02:36:41 etcdserver: member dir = /etcd.etcd/member
2015/09/10 02:36:41 etcdserver: heartbeat = 100ms
2015/09/10 02:36:41 etcdserver: election = 1000ms
2015/09/10 02:36:41 etcdserver: snapshot count = 10000
2015/09/10 02:36:41 etcdserver: advertise client URLs = http://localhost:2379,http://localhost:4001
2015/09/10 02:36:41 etcdserver: loaded cluster information from store: <nil>
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/coreos/etcd/wal.(*WAL).ReadAll(0xc8200a88f0, 0xc8203e6920, 0xf, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/wal/wal.go:237 +0xe6b
github.com/coreos/etcd/etcdserver.readWAL(0xc820240820, 0x15, 0x2075d4c, 0x65, 0x0, 0x0, 0x0, 0xc8200a88f0, 0xc820022070, 0xa10f00, ...)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/storage.go:85 +0x227
github.com/coreos/etcd/etcdserver.restartNode(0xc8201760c0, 0xc820070630, 0x29, 0xc8202a8bd8, 0x0, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/raft.go:260 +0xff
github.com/coreos/etcd/etcdserver.NewServer(0xc8201760c0, 0xc8201760e0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdserver/server.go:280 +0x2afc
github.com/coreos/etcd/etcdmain.startEtcd(0xc820074900, 0x0, 0x0, 0x0)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:224 +0x1545
github.com/coreos/etcd/etcdmain.Main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/etcdmain/etcd.go:113 +0xdd2
main.main()
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/main.go:29 +0x14

goroutine 17 [chan receive]:
github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.(*loggingT).flushDaemon(0xced880)
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog.init.1
	/Users/unihorn/gopath/src/github.com/coreos/etcd/scripts/release/etcd/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 13 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

**Comment by yichengq** [comment]
etcd only supports snapshot migration well from 0.4 to 2.1: https://github.com/coreos/etcd/blob/master/Documentation/04_to_2_snapshot_migration.md

Sorry for the inconvenience.

**Comment by liangsuilong** [comment]
My etcd snapshot migrates from 0.4.6 to 2.1.3. The range should be in the range as you say. l think it should works. 

First time, I try to upgrade etcd from 0.4.6 to 2.0.13. It fails. The error log is the same as the one I post. And I continue try to upgrade to 2.1.3. It fails again. 

But I tested another etcd instance. Upgrading from 0.4.6 to 2.0.13, it works fine.

**Comment by yichengq** [comment]
@liangsuilong You could not use the same data directory for the new etcd. Use a new data dir, then it should be fine.

**Comment by xiang90** [comment]
@liangsuilong Or you can remove your old 0.4 data-dir before you start etcd again.
