### ISSUE TITLE
Doc fix to mention IANA assignments for 2379/2380

### ISSUE THREAD

**Issue by dkiser** [coreos/etcd#3480]
When reading https://github.com/coreos/etcd/blob/master/Documentation/configuration.md it was confusing to see the old deprecated port numbers of 4001/7001 being used.  

I hopped onto IRC to learn that https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=etcd happened.

Could we add a notice banner somewhere so reader's aren't confused why some doc examples show both old/new port mappings and/or update docs to get rid of the old port references?

**Comment by gyuho** [comment]
Any updates on this? What's the best place to put the notice about it?

**Comment by xiang90** [comment]
Fixed via #4717
