### ISSUE TITLE
Needless fork: github.com/rakyll/pb

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#3485]
New release 2.2.0 bundles [github.com/rakyll/pb](http://github.com/rakyll/pb) which appears to be an outdated fork of [github.com/cheggaaa/pb](http://github.com/cheggaaa/pb). The latter seems to be better maintained.
Please consider using original project.

**Comment by yichengq** [comment]
@onlyjob I need some time to try it out to see whether they perform the same/meet our requirements.

**Comment by onlyjob** [comment]
Thank you. At least _etcd-2.2.0_ builds just fine with github.com/cheggaaa/pb.
IMHO using only well-maintained projects is important -- file a bug if it doesn't meet your requirements but please be very reluctant to integrate (seemingly) unmaintained forks where you can't even open a ticket if something goes wrong...

**Comment by onlyjob** [comment]
Thank you. :)

**Comment by onlyjob** [comment]
This is still a problem in 2.2.5: https://github.com/coreos/etcd/blob/v2.2.5/tools/v3benchmark/main.go#L24

Please reopen...

**Comment by xiang90** [comment]
@onlyjob Thanks. Reopened. Will fix.

**Comment by xiang90** [comment]
@onlyjob Just fixed https://github.com/coreos/etcd/commit/9f5189cd001593cf304ce45ad319777b2fe884f8

**Comment by onlyjob** [comment]
Thank you!
