### ISSUE TITLE
unable to remove member; unable to setup cluster

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#3491]
On etcd-2.2.0 I'm trying to setup cluster for the very first time (I'm new to etcd). It is so incredibly hard that after 5+ hours of continuous effort I still can't bootstrap second node. Could someone please point out clear setup instructions or better update documentation (particularly "Add New Member" section) with working example please?

Anyway, local _etcd_ works fine and responds to `ls`, `set`, and `get` commands.
But when I `etcdctl member add node2 http://node2:2380` cluster becomes unhealthy and `cluster-health` report unreachable member (node2, because it is not bootstraped yet). I fail to initialise _node2_: suggested `ETCD_INITIAL_CLUSTER="node2=http://node2:2380,deblab=http://localhost:2380,deblab=http://localhost:7001` (where `localhost` comes from?) does not work and alterations to `ETCD_INITIAL_CLUSTER` cause failure of  etcd to start on node2 due to "error validating peerURLs", "unmatched member while checking PeerURLs".

I'm giving up and trying to remove "[unstarted]" member with `etcdctl member remove` and getting "Recieved an error trying to remove member 69d73025e8d31e13: client: etcd cluster is unavailable or misconfigured" at which point etcd on first node seems broken beyond recovery... :(

Is there a way to remove uninitialised member i.e. revert `etcdctl member add`??
Thanks.

**Comment by AdoHe** [comment]
@onlyjob could you provide much more information? how you setup your first node and setup the initial cluster?

**Comment by onlyjob** [comment]
@AdoHe, I believe details of my "wrongdoings" won't be much of help...

After some more hours I believe I found number of problems with static clustering setup:

#### Clustering instructions imply non-default configuration.

This is the main reason why it is so hard to setup a new member.
I found that `member add` command uses value of `ETCD_INITIAL_ADVERTISE_PEER_URLS` for initialisation of new member. 

#### Invalid defaults

When `ETCD_INITIAL_ADVERTISE_PEER_URLS` is not explicitly given its default value is used (!) to initialise new member which is meaningless since defaults refer to `localhost` hence new member is doomed to fail without explicitly defined `ETCD_INITIAL_ADVERTISE_PEER_URLS` where externally connectable URL of this node is expected.

#### Counter-intuitive procedure

`ETCD_INITIAL_ADVERTISE_PEER_URLS` has to be defined prior to `etcdctl member add`.

#### Once new member is added, its setup cannot(?) be changed

New member will fail to connect with `error validating peerURLs`, `unmatched member while checking PeerURLs` if its `ETCD_INITIAL_CLUSTER` is not matches exactly the value as it is printed on `member add`.
However it seems to be impossible(?) to re-initialise new member once it is added with default (or incorrect) value of `ETCD_INITIAL_ADVERTISE_PEER_URLS` (which is embedded to printed `ETCD_INITIAL_CLUSTER`).
This is extraordinary counter-intuitive; too easy to make mistake and recovery is hard: apparently "unstarted" member can't be removed until it is started #3505 but it may be not possible to start if it was added incorrectly...

#### Conflict between documentation and behaviour

[Clustering Flags](https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#clustering-flags) documentation says:

> `-initial` prefix flags are used in bootstrapping a new member, and ignored when restarting an existing member.

However value of `ETCD_INITIAL_ADVERTISE_PEER_URLS` (or its default value) is used to configure new member on already bootstrapped node. According to documentation, `INITIAL` values should be ignored unless node is bootstrapping...

**Comment by xiang90** [comment]
> Conflict between documentation and behaviour

I have no idea what do you mean actually. After reading through your reply, I think etcd does the correct thing.

Can you pleas point out where do you think we can improve?

**Comment by xiang90** [comment]
Also I really suggest you to read our doc here https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#static and https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md. 

I agree some of the stuff is not intuitive enough. But actually, most of them are by design. 

> On etcd-2.2.0 I'm trying to setup cluster for the very first time (I'm new to etcd). It is so incredibly hard that after 5+ hours of continuous effort I still can't bootstrap second node.

I talked with a few etcd first users. Most of them can set up an etcd cluster within one hour when following the doc. 

Let me know how we can improve our doc and reduce the time for you to set up a cluster.

**Comment by xiang90** [comment]
Also if you do not want to read any doc and just want to give etcd a try. You can run goreman start instead of reading and doing all these yourself.

**Comment by onlyjob** [comment]
> Can you pleas point out where do you think we can improve?

I don't have enough eloquence to express it any better than I already did. :(

  https://github.com/coreos/etcd/issues/3491#issuecomment-139794858

> Let me know how we can improve our doc and reduce the time for you to set up a cluster. 

The above link to my summary explains it all.

> Also if you do not want to read any doc

Why wouldn't I want to read docs and what my supposed (un-)willingness to read docs have to do with reported problems?

**Comment by xiang90** [comment]
@onlyjob Can you please do not cross link between your multiple issues. Or you can please combine into one? You made me confused.

**Comment by xiang90** [comment]
> I don't have enough eloquence to express it any better than I already did. :( #3491 (comment)

Our doc already covered what you wrote about. I do not think that is useful. 

Have you successfully setup the cluster?

**Comment by onlyjob** [comment]
> Have you successfully setup the cluster?

Yeah, I figured it out in the end but it was a very frustrating experience...

FYI I have experience setting up Ceph clusters where minimum quorum of 3 is also required. Ceph configuration is more sophisticated but easier than etcd to set up.

**Comment by xiang90** [comment]
> Yeah

Glad to hear that.

Thanks for your patient and information.

**Comment by onlyjob** [comment]
@xiang90, It was not a support bug to close once I succeed with my set-up.

I wish you'd consider addressing at least some of 5 issues that I highlighted in my report. I fail to comprehend how could you just close this without any action...
I feel discouraged from reporting any further issues... :(

**Comment by xiang90** [comment]
@onlyjob 

This issue is about `unable to remove member; unable to setup cluster`. And clearly it is resolved.

Can you please file separate issues for other stuff you wish to discuss? I strongly dislike having 5 issues in one issue. Sorry.

**Comment by xiang90** [comment]
@onlyjob 

> I feel discouraged from reporting any further issues... :(

I would encourage you to report bug following this https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md. 

We want the isolation since: 

1. it is easier for the community to track the one problem per issues than a lot of problems per issue

2. it is easier for the community to send a pull request to close an issue than sending a lot of pull requests to fix different issues mentioned in one github issue.

3. the discussion is more focused and easy to follow.

**Comment by yichengq** [comment]
@onlyjob I cannot understand 5 issues that you reported too. A better way is to ask them separately and provide more details, or it is hard to help.
