### ISSUE TITLE
keeping 3 node cluster health

### ISSUE THREAD

**Issue by spyrospph** [coreos/etcd#3493]
Hi,

Using coreos 766.3.0 with

etcd Version: 2.1.2
Git SHA: ff8d1ec
Go Version: go1.4.2
Go OS/Arch: linux/amd64

Actions:

1) Bring up 3 node cluster which is healthy.
2) One of the nodes terminates due to machine failure
3) ASG brings another node up

Issue:

The cluster goes immediately into unhealthy mode and systemctl commands break:

etcdctl member list
client: etcd cluster is unavailable or misconfigured

On the new machine, etcd2 is still trying to find the new node (10.30.1.120):

Sep 11 11:13:05 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:05 etcdserver: cannot get the version of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: dial tcp 10.30.1.120:2380: i/o timeout)
Sep 11 11:13:11 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:11 etcdserver: failed to reach the peerURL(http://10.30.1.120:2380) of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: dial tcp 10.30.1.120:2380: i/o timeout)
Sep 11 11:13:11 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:11 etcdserver: cannot get the version of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: dial tcp 10.30.1.120:2380: i/o timeout)
Sep 11 11:13:17 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:17 etcdserver: failed to reach the peerURL(http://10.30.1.120:2380) of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: net/http: request canceled while waiting for connection)
Sep 11 11:13:17 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:17 etcdserver: cannot get the version of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: net/http: request canceled while waiting for connection)
Sep 11 11:13:23 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:23 etcdserver: failed to reach the peerURL(http://10.30.1.120:2380) of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: dial tcp 10.30.1.120:2380: i/o timeout)
Sep 11 11:13:23 ip-10-30-2-111.ec2.internal etcd2[935]: 2015/09/11 11:13:23 etcdserver: cannot get the version of member 2e91fd4f1285776 (Get http://10.30.1.120:2380/version: dial tcp 10.30.1.120:2380: i/o timeout)

Since resilience is (N-1)/2 a 3 node cluster should be able to auto heal -  however even with 1 failure my cluster is dead.

Is this something wrong in my set up?

**Comment by xiang90** [comment]
@spyrospph From the log, your etcd cluster is fine. etcd will always try to find the "dead" member. That is basically why etcd can recover from member failure. I am not sure why etcdctl does not work. I guess it is not configured correctly. Can you do etcdctl --debug member list?

**Comment by spyrospph** [comment]
thx @xiang90 qwill retry experiment and let you know

**Comment by xiang90** [comment]
@spyrospph Probably we can change the logging to debug level. What do you think?

**Comment by spyrospph** [comment]
ok how do i enable logging level to debug?

**Comment by xiang90** [comment]
@spyrospph I mean we can change the error logging at etcdserver (what made you think the entire cluster is unhealthy to debug mode).

**Comment by spyrospph** [comment]
hi @xiang90 

retried my test and it seems to work - therefore i do not know why it did not function as expected before.

When I do etcdctl member list I get 3 nodes as expected.

Then I etcdctl member remove <killed node>.

So I have 2 nodes.

Another question is: when I add a member it succeeds:

sudo etcdctl member add infra3  http://10.30.1.163:2380
Added member named infra3 with ID 61f1fcd52903d29c to cluster

ETCD_NAME="infra3"
ETCD_INITIAL_CLUSTER="8bfe795f8d91446a89c3c1370da1302f=http://10.30.2.82:2380,118b5e074f2e4ad0b461f2399f08f72d=http://10.30.2.83:2380,infra3=http://10.30.1.163:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"


SO closing this ticket as it seems ok.
