### ISSUE TITLE
snapshot file is empty after power outage and etcd can not start. 

### ISSUE THREAD

**Issue by minjs** [coreos/etcd#3498]
etcd will fail to start.

------------
etcd.log
STARTING ETCD...at name: 
localhost.22F89E6E
localhost.22F89E6E
-data-dir=/var/shape/data/localhost.22F89E6E
2015/09/10 16:25:10 etcd: listening for peers on http://127.0.0.1:7001
2015/09/10 16:25:10 etcd: listening for client requests on http://127.0.0.1:4001
2015/09/10 16:25:10 snap: unexpected empty snapshot
2015/09/10 16:25:10 etcd: stopping listening for client requests on http://127.0.0.1:4001
2015/09/10 16:25:10 etcd: stopping listening for peers on http://127.0.0.1:7001
2015/09/10 16:25:10 etcd: snap: empty snapshot

The snapshot file is exist, but without any data with size 0. 

[root@sse-C3606536 wal]:# ls -la
total 1092
drwx------. 2 root root 4096 Sep 9 23:43 .
drwx------. 4 root root 4096 Sep 10 17:21 ..
rw------. 1 root root 1101563 Sep 9 23:43 0000000000000000-0000000000000000.wal
rw------. 1 root root 2285 Sep 9 23:44 0000000000000001-0000000000002712.wal
[root@sse-C3606536 wal]:# ls ../snap/0000000000000003-0000000000002711.snap -lat
rw-rr-. 1 root root 0 Sep 9 23:43 ../snap/0000000000000003-0000000000002711.snap

**Comment by minjs** [comment]
I am not sure if this is root cause.  But Snapshotter.go save() use ioutil.WriteFile(), which is not atomically. Could it be atomically by writing a temp file and move to snapshot file or has some way to validate snapshot file?

**Comment by yichengq** [comment]
We ignore broken snapshot in current etcd: https://github.com/coreos/etcd/blob/master/snap/snapshotter.go#L108

I guess you are using a old version etcd, and etcd 2.2 should work well with this case. Could you check etcd version for confirmation?

**Comment by minjs** [comment]
We are using 2.0.1.   Can we upgrade from 2.0.1 to 2.2 without downtime?

**Comment by xiang90** [comment]
You can first upgrade to 2.1 without a downtime. Then to 2.2.

**Comment by xiang90** [comment]
20 -> 21 https://github.com/coreos/etcd/blob/release-2.1/Documentation/upgrade_2_1.md

**Comment by xiang90** [comment]
21 -> 22 https://github.com/coreos/etcd/blob/release-2.2/Documentation/upgrade_2_2.md

**Comment by xiang90** [comment]
sounds like your concern is resolved?

**Comment by minjs** [comment]
Yes, from latest code, his issue should be resolved.

**Comment by xiang90** [comment]
@minjs Thanks!
