### ISSUE TITLE
etcd: add a --dump-file parameter

### ISSUE THREAD

**Issue by philips** [coreos/etcd#3502]
The basic idea would be to create a dump of all requests and responses. It seems that the httputil package already has something that can do this: http://golang.org/pkg/net/http/httputil/#DumpRequest

We would need to figure out something similar for the v3 API.

After creating the dump thing we could do something similar to etcd-top with TLS encrypted versions of etcd.

**Comment by xiang90** [comment]
I really like this idea.

**Comment by xiang90** [comment]
This is now tracked in gRPC: https://github.com/grpc/grpc-go/issues/335. We will probably just use the stuff they develop.
