### ISSUE TITLE
panic: tocommit(138789) is out of range [lastIndex(0)]

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#3504]
On 2.2.0 in clustered setup with two static members I've initialised second member using `ETCD_INITIAL_CLUSTER_STATE="existing"` and `ETCD_INITIAL_CLUSTER` variables.  Second member was successfully restarted several times. Then to simulate data loss scenario I've stopped second member and deleted its data files. Attempted (re-)start ended up with crash and a long backrace:

~~~~
2015-09-13 00:45:30.785618 I | rafthttp: the connection with dd3b0cb0cf32bcef became active
2015-09-13 00:45:30.786353 I | raft: c8a988b91c9c29a1 [term: 1] received a MsgApp message with higher term from dd3b0cb0cf32bcef [term: 1676]
2015-09-13 00:45:30.786421 I | raft: c8a988b91c9c29a1 became follower at term 1676
2015-09-13 00:45:30.786491 I | raft: raft.node: c8a988b91c9c29a1 elected leader dd3b0cb0cf32bcef at term 1676
2015-09-13 00:45:30.786509 C | raft: tocommit(138789) is out of range [lastIndex(0)]
panic: tocommit(138789) is out of range [lastIndex(0)]
[...]
~~~~

I expected second member to be able to recover and re-load data (just like it initialised/loaded its data from first member initially).
Even if it such scenario is not intended to work, exit with meaningful error is better than crash.
Also I can't recover from this situation as cluster now is unhealthy and attempt to `etcdctl member remove` an unavailable (crashing) member fails with `Recieved an error trying to remove member c8a988b91c9c29a1: client: etcd cluster is unavailable or misconfigured`. It feels fragile as loss of any member (of two) leaves cluster without obvious means to recover or switch to non-clustered (single daemon) setup.

**Comment by xiang90** [comment]
@onlyjob 

etcd did the correct thing and protected you from potential corruption. In one word, do not try to use restart a member with broken data dir.

Please read https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#data-directory for more details.

**Comment by onlyjob** [comment]
Data directory could be lost due to file system corruption.
Besides the point of this bug is segfault instead of meaningful error message so the bug is legitimate.

**Comment by xiang90** [comment]
> Data directory could be lost due to file system corruption.

Then you need to remove this member and add a new one. data lost = member lost.

We might improve the logging message.

**Comment by onlyjob** [comment]
> Then you need to remove this member

It is not clear to me how to remove unavailable member on degraded cluster...

Improving error message would be helpful, thank you.

**Comment by xiang90** [comment]
> It is not clear to me how to remove unavailable member from degraded cluster...

You should read the docs before you try to build up your etcd cluster and put it into production. I think our docs covers most of your questions. 

> Improving error message would be helpful, thank you.

Yes. We are considering to improve raft related logging.

**Comment by onlyjob** [comment]
> You should read the docs before you try to build up your etcd cluster and put it into production. I think our docs covers most of your questions. 

With all due respect you should be paying more attention to bug report(s). I've been testing probable situation when data folder is gone (it can happen due to various reasons) while configuration is not. I did not say anything about production and frankly presence of problems I highlighted is not very helpful to build confidence in etcd technology...

**Comment by yichengq** [comment]
@onlyjob No database could run without data directory, and this is the same case for etcd.

**Comment by onlyjob** [comment]
> No database could run without data directory, and this is the same case for etcd.

Except bootstrapping. In conjunction with `ETCD_INITIAL_CLUSTER_STATE="existing"` lack of data directory is what seems to kickstart bootstrapping. One might expect that easiest way to re-initialise node is to remove its data directory... Fair enough, that's not how etcd works, but segfault I'm trying to report is a bug.

I appreciate your openness to improvement ideas. However "play around it and try to break it" approach allows to test how well etcd handles disasters. So far It did not stand well enough in my testing so please excuse me if I'm not satisfied with segfault or disappointed with replies suggesting that there is no problem other than me doing something wrong... :(

**Comment by xiang90** [comment]
> With all due respect you should be paying more attention to bug report(s).

How do you want us to do better? I have clearly told you how you should expect etcd to work and we are going to improve the logging as you suggested.

We just cannot help you more now. And raft logging is a low priority thing. If you want to track the issue see the last item of https://github.com/coreos/etcd/issues/1808. 

Thanks.

**Comment by philips** [comment]
On Sat, Sep 12, 2015 at 8:05 AM Dmitry Smirnov <notifications@github.com>
wrote:

> I expected second member to be able to recover and re-load data (just like
> it initialised/loaded its data from first member initially).
>
I think two things are causing confusion:

1) etcd cannot reload your data to the member with list data because we
expect that a member that claims to have a WAL file on disk up to version X
cannot then join the cluster and say it has version 0. If we allowed this
to happen we could create full cluster inconsistency, etcd is trying to
protect you from adding members with corrupted or truncated data.

2) Running a cluster of size 2 does not allow for any fault tolerance. See
the fault tolerance table here:
https://coreos.com/etcd/docs/latest/admin_guide.html#cluster-management

I agree we should improve the error message you encountered when starting
with an empty data directory but etcd is operating correctly and protecting
the cluster from misconfiguration.

>

**Comment by philips** [comment]
list data -> lost data

**Comment by onlyjob** [comment]
Thanks for all improving panic message. The only thing everyone seems to forget is long backtrace from 10 threads that follows error message. Is it normal/necessary?

**Comment by yichengq** [comment]
> The only thing everyone seems to forget is long backtrace from 10 threads that follows error message.

@onlyjob As xiang said, the backtrace logging is tracked in the issue #1808 .

> However "play around it and try to break it" approach allows to test how well etcd handles disasters.

I know that is a normal pattern to test most softwares, but it is not a good way on etcd. etcd guarantees strong consistency through replicated state machine between all etcd members, and checks itself internally to ensure its correctness. This reveals potential problem early and ensures etcd users achieve what etcd promises to give.

We would expect deployers follow the documentation to play around it. If you have read the `life cycle of data directory` at https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#lifecycle, you will not jump into this panic.

**Comment by onlyjob** [comment]
This is not a panic. All segfaults are ought to be reported as bugs hence I reported segfault (and its context) because I do my best to use software responsibly.
Re-creating member on loss of data folder makes sense although re-initialisation of data-less member could have been easier...

**Comment by yichengq** [comment]
@onlyjob This is called a panic in Go.

Maybe you can think it in this way: all etcd members in the cluster is like a big distributed database, and deleting one data dir is like removing part of the database files. You cannot imagine what may happen then, right?

**Comment by onlyjob** [comment]
> This is called a panic in Go.

Ha! :) I get it now... :) :)

> all etcd members in the cluster is like a big distributed database, and deleting one data dir is like removing part of the database files.

I was thinking about members as about data servers accommodating desirable amount of replicas. When data is one replica short and data server becomes available one would expect data to be replicated to new member without remove/re-add dance. Perhaps it is my background in distributed storage is talking...

**Comment by yichengq** [comment]
> members as about data servers accommodating desirable amount of replicas

We are totally different than that. etcd guarantees consensusin a network of unreliable processors. You could check Paxos algorithm for more details.

**Comment by FarzanRNobakht** [comment]
> etcd did the correct thing and protected you from potential corruption. In one word, do not try to use restart a member with broken data dir.

it happends to me even when i start etcd in docker (data dir is restarted)
