### ISSUE TITLE
client - NewClientFromFile 

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#3515]
Given the previous library (go-etcd), is there any plan to provide an equivalent functionality?

**Comment by xiang90** [comment]
@timothysc Can you describe the use case? We also deprecated configuration file in etcd server side. We suggest users to use service file (systemd) or just use env variable to do configuration.

**Comment by timothysc** [comment]
It just appears in the code paths, when I trace backwards it appears only as an input option so I suppose we could rip it out.
