### ISSUE TITLE
raft doc improvement

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3522]
some feedback 

> My only feedback is I wonder if it would be worth including a few lines at the start explaining what a censensus protocol is, what kind of problems it solves, and what it can be used to build. I guess it all depends on what type of person arrives at the page - someone who knows what it is all about and needs an implementation, or someone who just heard about something called etcd's Raft and that it is "cool". 

Another feedback I got is that we should document how to do reconfiguration. It is not super clear right now.

**Comment by vmattos** [comment]
I started writing a didatic blog post about Raft in my language (Portuguese).
I would be happy translate it to english and send a pull request

**Comment by xiang90** [comment]
@vmattos About etcd/raft? Or about raft in general?

**Comment by vmattos** [comment]
About raft in general, for folks who don't want to read the whole paper

**Comment by xiang90** [comment]
@vmattos I would love to help on the blog post. But we are talking about etcd's raft implementation here.

**Comment by gyuho** [comment]
I think https://github.com/coreos/rkt/blob/master/Documentation/devel/architecture.md is a good example.  I am interested in this as well. Where would be the good place to put this? `Documentation/dev`? Thanks!

**Comment by gyuho** [comment]
I have been learning raft and etcd keeping logs in my personal repository.

https://github.com/gyuho/learn/tree/master/doc/etcd_architecture
