### ISSUE TITLE
Starting etc under Docker fails with "different advertised URLs in the cluster and advertised peer URLs list"

### ISSUE THREAD

**Issue by jcragin** [coreos/etcd#3523]
Trying to start a three node test cluster under docker, on the same host, using port forwarding with the following command for the first instance, the second and third are identical just with incremented ports:

docker run -d -p 2281:2280 -p 2381:2380 --name test-etcd1 \
                quay.io/coreos/etcd:v2.0.3 
                --name test-etcd1 \
                --advertise-client-urls http://10.0.0.184:2381 \
                --listen-client-urls http://0.0.0.0:2380 \
                --initial-advertise-peer-urls http://10.0.0.184:2281,http://10.0.0.184:2282,http://10.0.0.184:2283 \
                --listen-peer-urls http://0.0.0.0:2280 \
                --initial-cluster-token test-etcd-token \
                --initial-cluster test-etcd1=http://10.0.0.184:2281,test-etcd2=http://10.0.0.184:2282,test-etcd3=http://10.0.0.184:2283 \
                --initial-cluster-state new

I get the following in return:

015/09/14 17:16:31 no data-dir provided, using default data-dir ./test-etcd1.etcd
2015/09/14 17:16:31 etcd: listening for peers on http://0.0.0.0:2280
2015/09/14 17:16:31 etcd: listening for client requests on http://0.0.0.0:2380
2015/09/14 17:16:31 etcd: stopping listening for client requests on http://0.0.0.0:2380
2015/09/14 17:16:31 etcd: stopping listening for peers on http://0.0.0.0:2280
2015/09/14 17:16:31 etcd: test-etcd1 has different advertised URLs in the cluster and advertised peer URLs list

**Comment by xiang90** [comment]
@jcragin `--initial-advertise-peer-urls` and `--initial-cluster-token test-etcd-token` should match. 

In your case, `--initial-advertise-peer-urls` should only contain the peer url of local member. ( http://10.0.0.184:2281)
