### ISSUE TITLE
`etcd` keyspace is fundametally insecure

### ISSUE THREAD

**Issue by benwilber** [coreos/etcd#3542]
It's impossible to treat `etcd` as a "key/value" store, since `etcd`:

* [Expands paths](https://github.com/coreos/etcd/blob/f51c2f471beaef104580b1e38dd67d73c5da9f88/client/keys.go#L468)
  * ../../foo (how is this useful as a key?  huge security vulnerability.)
* /prefix/foo bar baz/bat
  * `etcd` key -> /prefix/foo%20bar%20baz/bat

Even if the key that I wrote was "foo bar baz" (not escaped), `etcd` escapes it internally.  `etcd` does not treat keys as opaque values (a la Redis), but instead does urlencoding, which causes all manner of issues.

**Comment by yichengq** [comment]
Different key/value store may have different decisions on key support.

```
key -> /prefix/foo%20bar%20baz/bat
```

That is the expected behavior of HTTP request. You could use `etcdctl` instead and it works well.

**Comment by benwilber** [comment]
@yichengq I closed this issue because I don't think it would be fixed in `etcd`, but I think the issue is still valid.  URL escaping is something that should be done by the client, not by the server for purpose of normalized storage, especially when the value is used from lookup.  This means that the key that I wrote the `etcd` is not necessarily valid for lookup, since it was possibly escaped implicitly.  The issue that arises from this is that an application might want to store a key with a space (or any other escaped value `foo bar`  -> `foo%20bar`) in their database and also in `etcd`.  This requires the application to account for **three** possible representations of the key:

Unescaped: `foo bar`
The raw value written to the application's database.

Escaped:
`foo%20bar`
The value the application must lookup in `etcd` if it wants to retrieve it.

Double-escaped:
`foo%2520bar`
The double-escaped key in `etcd` if the application (correctly) wrote a URL-escaped key to etcd.


The core problem is that `etcd` server implicitly URL-escapes keys when it really shouldn't.  No other HTTP server on the planet does this (or at least they shouldn't).

**Comment by xiang90** [comment]
@benwilber I understand the problem. But can you explain why this makes etcd insecure?

**Comment by benwilber** [comment]
The path expansion is actually the security issue that I was referencing.  The keyspace being addressed as URLs makes it very difficult to code defensively against malicious inputs.  I can't just accept a value as an opaque blob and assume that it will be written/read as-is.  I have to do all manner of sanitization on the key in order to guarantee that it's not going a traverse a path and overwrite something in `etcd`'s private keyspace.

**Comment by xiang90** [comment]
> The keyspace being addressed as URLs makes it very difficult to code defensively against malicious inputs.

It sounds like you are saying it is hard to protect etcd due to the path escaping. I still cannot say why etcd itself is fundamentally insecure. 

And you are right, we are not going to change the url based resource model in v2. However, we are designing a new API to solve the exact issue you just mentioned. Feel free to give it a review: https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md

**Comment by xiang90** [comment]
@benwilber 

I am closing this due to low activity. Also we have already taken action to make key space simpler in v3 design. Thanks for bringing this up!
