### ISSUE TITLE
Watch always returns: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by mdmarek** [coreos/etcd#3557]
I am trying to use a watch, setup in the following way:

    res, err = k.Get(context.Background(), key, &etcd.GetOptions{Quorum: true})
    if err != nil {
        ...
    }

    w := k.Watcher(key, &etcd.WatcherOptions{AfterIndex: res.Index, Recursive: true})
    ctx, cancel := context.WithCancel(context.Background())
    go func() {
        <-stopc
        cancel()
    }()
    for {
        res, err := w.Next(ctx)
        ...
    }

This watch always fails with the error:

    client: etcd cluster is unavailable or misconfigured

I believe that I am configuring the watch correctly, and I know that the key, which is a directory, does exist.

Reworking the code to use the old go-etcd client, the watch works, using the new etcd client the watch returns the error mentioned above.

**Comment by yichengq** [comment]
You could call Details() to get more info using http://godoc.org/github.com/coreos/etcd/client#ClusterError.

Could you show us the details?

**Comment by mdmarek** [comment]
@yichengq 

Thanks for the tip. Logging the `Detail()` string, shows:

    client: etcd cluster is unavailable or misconfigured, detail: error #0: context canceled 

That helped me understand what was going on. The watch is getting canceled. What confused me is that it returns an error. I was not expecting that.

I guess the `Watcher` does not have much choice, since it can only return a `*Response` or an `error` to anything blocked calling `Next()` method.

That's kind of unfortunate because the only way to know that the error is from a cancel is to dig deep into the err returned using type switch-blocks.

**Comment by xiang90** [comment]
@mdmarek Do you think this helps at all? https://github.com/coreos/etcd/tree/master/client#error-handling

**Comment by mdmarek** [comment]
@xiang90 

That would help if the example block below worked when examining an error from `Next()`:

    var w *client.Watcher

    ...

    res, err := w.Next()
    if err != nil {
        if err == context.Canceled {
            // ctx is canceled by another routine
        } else if err == context.DeadlineExceeded {
            // ctx is attached with a deadline and it exceeded
        } else if cerr, ok := err.(*client.ClusterError); ok {
            // process (cerr.Errors)
        } else {
            // bad cluster endpoints, which are not etcd servers
        }
    }

Is that supposed to work now? Am I examining the error incorrectly in my code?

**Comment by xiang90** [comment]
It should. Is there an issue?

**Comment by mdmarek** [comment]
Ah perfect. Probably no issue, just me not reading the manual.

Thanks @xiang90

**Comment by xiang90** [comment]
@mdmarek Thanks. Let us know if you have any issues. :)
