### ISSUE TITLE
TestPublishRetry fail

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3559]
2015-09-19 23:20:18.085649 I | etcdserver: aborting publish because server is stopped
--- FAIL: TestPublishRetry (0.00s)
	server_test.go:1049: len(action) = 1, want >= 2
2015-09-19 23:20:18.086041 I | etcdserver: setting up the initial cluster version to 2.0
FAIL
coverage: 48.4% of statements

It doesn't wait long enough for timer to be triggered in travis.

**Comment by xiang90** [comment]
@yichengq Can you file an issue in travis? Ask them why it is getting slower and slower?

**Comment by yichengq** [comment]
@xiang90 I will send an email to the travis pro guys.

**Comment by xiang90** [comment]
We are not using travis pro, btw. We are using the travis.org.

**Comment by xiang90** [comment]
We do not run integration test on travis any more. We have not seen this for a long time, so closing.
