### ISSUE TITLE
Set() ignores SetOptions.PrevExist with SetOptions.Dir = true

### ISSUE THREAD

**Issue by stensonb** [coreos/etcd#3569]
Trying to ensure, idempotently, that a directory exists with this:

```golang
package main

import (
    "log"
    "time"

    "github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context"
    "github.com/coreos/etcd/client"
)

func main() {
    cfg := client.Config{
        Endpoints:               []string{"http://127.0.0.1:2379"},
        Transport:               client.DefaultTransport,
        // set timeout per request to fail fast when the target endpoint is unavailable
        HeaderTimeoutPerRequest: time.Second,
    }
    c, err := client.New(cfg)
    if err != nil {
        log.Fatal(err)
    }

    kapi := client.NewKeysAPI(c)

    // build cidrd branch, if it doesn't already exist
    opts := client.SetOptions{Dir: true, PrevExist: client.PrevIngore}
    resp, err := kapi.Set(context.Background(), "cidrdy", "", &opts)

    if err != nil {
        log.Fatal(err)
    } else {
        log.Print(resp)
    }
}
```

If the directory doesn't exist, the directory is created:
```bash
Bryans-MBP:etcplayground bryan$ go run play.go 
2015/09/21 16:11:55 &{set {Key: /cidrdy, CreatedIndex: 57, ModifiedIndex: 57, TTL: 0} <nil> 57}
```

On the next run, the directory exists, but the Set() function throws an error:
```bash
Bryans-MBP:etcplayground bryan$ go run play.go 
2015/09/21 16:12:00 102: Not a file (/cidrdy) [57]
exit status 1
```

I expect when PrevExist==client.PrevIngore, the Set() function should not fail when I try to Set() an existing directory.

**Comment by stensonb** [comment]
This appears to only affect root-level nodes...

For example, trying to ensure the "/cidrdy" directory exists fails with the above message.

However, if "/cidrdy" exists, and I then try to ensure a "/cidrdy/classes" directory exists, the Set() function seems to honor PrevExist==client.PrevIgnore

**Comment by cchamplin** [comment]
I believe this is expected behavior, you cannot update an existing directory (other than changing the TTL). If you want to ensure that a directory exists as a single command (Create or NOOP) you could get close by performing a SET on a short lived key underneath the directory you want to ensure is created.

```sh
# Ensures that cidrdy exists as a directory
curl -L http://127.0.0.1:4001/v2/keys/cidrdy/auto_expire -XPUT -d ttl=0
```

**Comment by stensonb** [comment]
Thanks for the feedback @cchamplin 

The purist in me is frustrated by the lack of "elegance" in this. :)  It's strange to think that I have to perform another SET just to prove the directory exists...not to mention, what if my subsequent SET call fails for some reason NOT related to the directory's existence...my code would falsely assume the directory doesn't exist, even though it might.  Ugh!

Anyway, thank you for the recommendation.  I'll work with it, but I suggest we (the etcd community!) come up with a better solution for idempotent directory creation.

**Comment by xiang90** [comment]
@stensonb 

As @cchamplin mentioned, this works as intended. 
Set means delete and then create a new one. So set a key means to delete the old key and create a new one.

Set does not work with directory since you cannot simply remove a non-empty directory. That is dangerous.

This is probably not going to change for v2 api. In v3 api, we do not have a concept of directory.
