### ISSUE TITLE
etcd client readme reference Godeps/ package

### ISSUE THREAD

**Issue by miekg** [coreos/etcd#3581]
Hi,

The etcd `etcd/client/README.md` has this:

```
"github.com/coreos/etcd/Godeps/_workspace/src/golang.org/x/net/context"
```

This strikes me as a somewhat non-optimal way to get `net/context`. Is this really needed?

**Comment by yichengq** [comment]
Yes, if you don't use `godep`.

We would like to expose original context error to follow canonical workflow. But we do packaging in the project, so you need to use packaged context.

Original discussion: https://github.com/coreos/etcd/issues/3208

**Comment by yichengq** [comment]
This could be improved when `go vendor` becomes official.

@miekg Let me know if you have more thoughts.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [etcd] etcd client readme refer..." ]
>This could be improved when `go vendor` becomes official.

Ack.

>@miekg Let me know if you have more thoughts.

I never (really) liked Godeps and it is unfortunate that it shows up in
such a public way in the README. :(

/Miek

--
Miek Gieben

**Comment by yichengq** [comment]
> I never (really) liked Godeps and it is unfortunate that it shows up in
such a public way in the README. :(

etcd needs packaging, and we support `go get github.com/coreos/etcd`. So that is our solution to fit both requirements.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [etcd] etcd client readme refer..." ]
>> I never (really) liked Godeps and it is unfortunate that it shows up in
>such a public way in the README. :(
>
>etcd needs packaging, and we support `go get github.com/coreos/etcd`. So that is our solution to fit both requirements.

yes, I totally understand. I also don't have anything better to offer.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
*evil idea time* ... maybe drop this dependency from Godeps and have a `go get` step that gets the proper context package (which is rather stable) from the interwebs.

**Comment by yichengq** [comment]
@miekg One problem that I could see is that we use cilent package in etcd program, and etcd program has to have packaging management.
