### ISSUE TITLE
New node cant join cluster

### ISSUE THREAD

**Issue by willejs** [coreos/etcd#3589]
Hi, I am running a 3 node cluster of etcd version 2.0.3. One node failed today, and I removed the node from the cluster (this caused instability for 10 minutes, but eventually the cluster nodes returned to healthy).
I then booted a new node, and ran 
``` etcdctl member add node3 http://10.0.12.247:7001 ```
when running etcdctl member list i see:
```etcdctl member list                                              
39269617b6a9882b: name= peerURLs=http://10.0.12.247:7001 clientURLs=
ae297d066a248092: name=node2 peerURLs=http://10.0.13.254:7001 clientURLs=http://10.0.13.254:4001
e43556ce643d3742: name=node1 peerURLs=http://10.0.14.62:7001 clientURLs=http://10.0.14.62:4001 ```
The new node has an empty node name. Is that an issue? Or at bootstrap is that filled?

When i then try and start etcd on the new node after adding it on the healthy node, i receive this error:
```
https://gist.github.com/willejs/14e9bd0c587b122435ed
```
I upgraded to 2.0.13 and it informs me of this instead:
```
2015/09/24 20:57:04 etcd: stopping listening for client requests on http://10.0.12.247:4001
2015/09/24 20:57:04 etcd: stopping listening for peers on http://10.0.12.247:7001
2015/09/24 20:57:04 etcd: couldn't find local name "node3" in the initial cluster configuration
```

**Comment by yichengq** [comment]
> Is that an issue? Or at bootstrap is that filled?

It will be filled in when the new member bootstraps and connects to the cluster.

For the error, I think you use the wrong `-initial-cluster` flag. Could you share your command line and the instruction printed out by `etcdctl member add` to me?

**Comment by willejs** [comment]
I just performed the same steps on my staging cluster with success. 

The output from the healthy node, member add is below:
```
ubuntu@node2:~$ etcdctl member add node3 http://10
.0.12.247:7001
Added member named node3 with ID 39269617b6a9882b to cluster

ETCD_NAME="node3"
ETCD_INITIAL_CLUSTER="node3=http://10.0.12.247:7001,node2=http://10.0.13.254:7001,node1=http://10.0.14.62:700
1"
ETCD_INITIAL_CLUSTER_STATE="existing"
```

**Comment by yichengq** [comment]
I guess you lacked `node3=http://10.0.12.247:7001` part in initial cluster when you did it the first time.

**Comment by willejs** [comment]
Nope, ive repeatedly removed the node from the cluster and tried the exact config that the add member node outputs. Any ideas? I cant believe that an identical setup in staging works, but doesent work in production?

**Comment by willejs** [comment]
Ive also ensured that the state directory is empty too.

**Comment by yichengq** [comment]
@willejs Please show me your command line to start etcd, and `etcdctl member list` when you start etcd in your production.

**Comment by willejs** [comment]
```
exec /usr/local/bin/etcd  --name node3 --initial-advertise-peer-urls=http://10.0.12.247:7001 --advertise-client-urls=http://10.0.12.247:4001 --listen-peer-urls=http://10.0.12.247:7001 --listen-client-urls=http://10.0.12.247:4001 -data-dir /var/cache/etcd/state \
--initial-cluster node3=http://10.0.12.247:7001,node2=http://10.0.13.254:7001,node1=http://10.0.14.62:7001 \
--initial-cluster-state existing
```

Thanks for your help!

**Comment by willejs** [comment]
I give up on this, i had to migrate to another cluster, and am now going to upgrade to 2.2 as i think this is a real problem in 2.0.x.
