### ISSUE TITLE
docs: add more security info to clustering guide

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#3595]
It would be great to have more examples for adding the TLS related flags when clustering. I'm not looking for instructions on generating certs or background on the design, but there should be 3 code blocks that list the required flags and values, similar to the other clustering guides. This way you at least know that flags are required on each machine. Link off to the other stuff.

**Comment by philips** [comment]
@robszumski What SSLa tool should we use so we are consistent across our k8s guides and etcd guides?

Also, this can be a starting place: https://github.com/coreos/etcd/blob/13cfb4284faa6056a1771b847b71e6429e627e56/Documentation/security.md#security-model

**Comment by xiang90** [comment]
@robszumski Do you mean add the TLS related stuff into https://github.com/coreos/etcd/blob/master/Documentation/clustering.md?

**Comment by robszumski** [comment]
@xiang90 yes, have a full list of the flags required to get started with TLS. Link off for background info and actually generating the certs.

**Comment by robszumski** [comment]
@philips Not sure I'm the one to make that call, but I know of 3: openssl for k8s, etcd-ca and cfssl for general os stuff.

**Comment by joshix** [comment]
Related: coreos/docs#674, coreos/docs#702, et al

**Comment by gyuho** [comment]
Kindly ping @joshix 

We would like to look into this with high priority for our upcoming `v2.3.0` release.
Any status updates on this?

Thanks for help.

**Comment by joshix** [comment]
working on this currently, fyi

**Comment by xiang90** [comment]
moved to 3.0

**Comment by xiang90** [comment]
reassigned to @heyitsanthony
