### ISSUE TITLE
what does an etcd2 config file look like?

### ISSUE THREAD

**Issue by streamnsight** [coreos/etcd#3597]
Using CoreOS to deploy Kubernetes. I want to secure ectd with TLS, but then Kubernetes pods need to be ableto authenticate. To do so, the etcd config can be passed as a config file which would i guess include links to certs. 

I see doc for the FLAGs that can be used but nothing about the format of a 'config file'

Can someone share an example?
Thanks

**Comment by yichengq** [comment]
etcd don't support config file.

We supports to config TLS related stuffs through command line, and I think this could fit your requirements. Read this for flag usage: https://github.com/coreos/etcd/blob/master/Documentation/security.md

**Comment by yichengq** [comment]
Close it because I think this is solved.
