### ISSUE TITLE
documentation of etcd2 proxy tls settings

### ISSUE THREAD

**Issue by roboll** [coreos/etcd#3599]
Spent a number of hours trying to figure out how etcd2 proxy works with tls. Finally after combing through the code, I realized that the proxy uses peer tls settings to communicate with the cluster peers over the client port. This is definitely not straight forward and as far as I can tell entirely undocumented. I'll be happy to help with a PR containing documentation, but I want to verify that this is actually expected behavior and intended.

Succinctly:

in a cluster:
configured with tls and client certificate auth
configured with no peer tls or authentication

the etcd proxy must specifiy __peer__ client credentials in order to proxy connections to cluster - on the __client__ port. it must also specify client certificate options in order to __serve__ tls itself.

**Comment by yichengq** [comment]
That would be rather helpful. :+1:  A good start point is the security doc AFAIK: https://github.com/coreos/etcd/blob/master/Documentation/security.md

**Comment by yichengq** [comment]
@roboll After reading the issue again with xiang, current usage is a wrong one, and this should be a bug. It is impossible to reason about why it uses peer cert to do requests for client port. It needs to be fixed at etcd side.

**Comment by roboll** [comment]
@yichengq thats what I initially thought as well, I agree.

I think the desired behavior should _actually_ be that proxy uses an entirely different flag for it's proxying, i.e. introduce `proxy-` flags. The reason behind that is because we still need to be able to specify `client` for incoming connections, `peer` for connecting to the etcd cluster to get the members on the peer port, and then finally `proxy` for the connections that are proxied to the `client` port of the cluster.

**Comment by roboll** [comment]
also, do you want me to close the pull request with documentation, or should it be included in the interim in which case i can create a link in the docs to an issue tracking progress on that issue.

**Comment by xiang90** [comment]
@roboll I agree with you.

Proxy cannot transparently forward tls since it operates at HTTP layer currently with this library https://golang.org/pkg/net/http/httputil/#ReverseProxy.

So proxy uses its own transport with its own cert/key to connect with etcd cluster. 

To make this clear, we probably want to have proxy-to-etcd-client-* that is used to connect to etcd cluster client port. And we also need to introduce proxy-to-etcd-peer-* that is used to connect to etcd cluster peer port. The peer-* flags on proxy will be ignored and client-* flag will be used to serve the proxy's client port.

**Comment by roboll** [comment]
@xiang90 makes sense.

I submitted a PR to address the lack of documentation on the way etcd operates today - do you want to include that in the interim or should I close the PR?

**Comment by yichengq** [comment]
@roboll The added part is good, but I don't want to let users use something fundamentally wrong. I would prefer to close the PR and submit a correct one when it is fixed.

**Comment by roboll** [comment]
cool. closed the pr. can you update this ticket with a link to the new issue when it's around? i'd like to track that.

**Comment by yichengq** [comment]
@roboll Sure. Thanks for fast reply and the PR.

**Comment by gyuho** [comment]
What's the status of this? Do we still have the wrong implementation in `proxy` package? Does any other ticket address this issue?

**Comment by urzds** [comment]
I'm confused...

So there are `advertise-client-urls` corresponding to `listen-client-urls`, which are the endpoints to be used by clients wanting to store data in etcd and for cluster members communicating with each other. Then there are `initial-advertise-peer-urls`, `initial-cluster` and `listen-peer-urls`, which are for discovering the `*-client-urls` only?

On the security side we have `cert-file`, `key-file`, `trusted-ca-file` and `client-cert-auth`, which are the server certificates corresponding to `listen-client-urls`? And finally `peer-cert-file`, `peer-key-file`, `peer-trusted-ca-file` and `peer-client-cert-auth`, which are the server certificates corresponding to `listen-peer-urls`? (And they are only used for initial discovery, as described in my previous paragraph?)

That leaves me with two questions:
1. Why have the peer-urls at all?
2. How do I specify the client certificates, which one cluster member uses to authenticate himself to another, or which a proxy or client uses to authenticate himself to a cluster member?
