### ISSUE TITLE
etcdv3: how does it behave under swap-constrainted or swap free environments

### ISSUE THREAD

**Issue by philips** [coreos/etcd#3603]
boltdb will use a large amount of virtual memory to work-around https://github.com/boltdb/bolt/issues/378.  How does this affect etcd in practice with swap-constrainted environments?

**Comment by xiang90** [comment]
@philips Talked with @eyakubovich about this. Seems fine to me. mmap backed virtual memory should use the file as swap and should not affect other applications.

**Comment by xiang90** [comment]
I have tested this on linux box. The mmaped region does consume swap space since it is backed by a file on disk.
