### ISSUE TITLE
etcdctl breaks when enable SSL

### ISSUE THREAD

**Issue by utahcon** [coreos/etcd#3605]
When I create a cluster with SSL enabled using the following flags:

> {{ short_name }} would be infraops-etcd-001
> {{ fqdn }} would be infraops-etcd-001.iad.prod.zulily.com

```
    name: {{ short_name }}
    discovery: http://internal-discovery.example.com:2379/v2/keys/discovery/cluster-with-ssl-id-6
    advertise-client-urls: https://{{ fqdn }}:2379
    initial-advertise-peer-urls: https://{{ fqdn }}:2380
    listen-client-urls: https://0.0.0.0:2379
    listen-peer-urls: https://{{ fqdn }}:2380
    peer-cert-file: /etc/ssl/certs/example.com.crt
    peer-key-file: /etc/ssl/keys/example.com.key
    peer-trusted-ca-file: /etc/ssl/certs/example-ca-chain.crt
    cert-file: /etc/ssl/certs/example.com.crt
    key-file: /etc/ssl/keys/example.com.key
    trusted-ca-file: /etc/ssl/certs/example-ca-chain.crt
    endpoint: https://{{ fqdn }}:2379
```
`etcdctl` is broken:
```
infraops-etcd-003 adbarrett # etcdctl member list
client: etcd cluster is unavailable or misconfigured
```
unless I pass in the CA file, and list of peers using SSL
```
infraops-etcd-003 adbarrett # etcdctl --ca-file /etc/ssl/certs/zulily-ca-chain.crt --peers https://infraops-etcd-003.iad.prod.zulily.com:2379 member list
d684d0d4c6fca3a: name=infraops-etcd-001 peerURLs=https://infraops-etcd-001.iad.prod.zulily.com:2380 clientURLs=https://infraops-etcd-001.iad.prod.zulily.com:2379
d96dd85d5f4da673: name=infraops-etcd-003 peerURLs=https://infraops-etcd-003.iad.prod.zulily.com:2380 clientURLs=https://infraops-etcd-003.iad.prod.zulily.com:2379
fab039c426c3fce8: name=infraops-etcd-002 peerURLs=https://infraops-etcd-002.iad.prod.zulily.com:2380 clientURLs=https://infraops-etcd-002.iad.prod.zulily.com:2379
```
It seems to be the default of expecting `http://127.0.0.1` to work after enabling SSL, at a minimum I would expect `https://127.0.0.1` (which would require a cert that allows both the FQDN and the loopback) 

How can I force `etcdctl` to use these peers without having to pass them on the cli everytime?

**Comment by yichengq** [comment]
> It seems to be the default of expecting http://127.0.0.1 to work after enabling SSL, at a minimum I would expect https://127.0.0.1

`etcdctl` has no knowledge that users are using HTTPS. I think you mentioned that the error message is confusing, right?

You could use environment variables. It should be ETCD_PEERS.

**Comment by raoofm** [comment]
The flag has changed

Please use ETCDCTL_ENDPOINT
https://github.com/coreos/etcd/tree/master/etcdctl#endpoint

**Comment by yichengq** [comment]
@raoofm You are right. Please use ETCDCTL_ENDPOINT

**Comment by utahcon** [comment]
Running version 2.1.2

```
infraops-etcd-001 adbarrett # etcdctl -v
etcdctl version 2.1.2
```

with ETCDCTL_ENDPOINT set:

```
infraops-etcd-001 adbarrett # echo $ETCDCTL_ENDPOINT
https://infraops-etcd-001.iad.prod.zulily.com:2379
```

fails

```
infraops-etcd-001 adbarrett # etcdctl member list
client: etcd cluster is unavailable or misconfigured
```

must still pass as argument on command line

```
infraops-etcd-001 adbarrett # etcdctl -C https://infraops-etcd-001.iad.prod.zulily.com:2379 member list
79aa592a607fc1f: name=infraops-etcd-001 peerURLs=https://infraops-etcd-001.iad.prod.zulily.com:2380 clientURLs=https://infraops-etcd-001.iad.prod.zulily.com:2379
a3cac43c0505d4af: name=infraops-etcd-003 peerURLs=https://infraops-etcd-003.iad.prod.zulily.com:2380 clientURLs=https://infraops-etcd-003.iad.prod.zulily.com:2379
b050140d9657b842: name=infraops-etcd-002 peerURLs=https://infraops-etcd-002.iad.prod.zulily.com:2380 clientURLs=https://infraops-etcd-002.iad.prod.zulily.com:2379
```

**Comment by raoofm** [comment]
I can confirm that this is issue

**Comment by raoofm** [comment]
Works for me. I dont see any issue. 
It works for both ETCDCTL_ENDPOINT and ETCDCTL_PEERS

[rm@server-111 etcd]$ ./etcdctl -v
etcdctl version 2.2.0
[rm@server-111 etcd]$ pwd
/var/lib/etcd
[rm@server-111 etcd]$ export ETCDCTL_ENDPOINT=https://node03.etcd.dev.com:2379
[rm@server-111 etcd]$ echo $ETCDCTL_ENDPOINT
https://node03.etcd.dev.com:2379
[rm@server-111 etcd]$ ./etcdctl --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health
member 4c5854cca2fdc9c is healthy: got healthy result from https://node03.etcd.dev.com:2379
member 5f97c3330e24a56d is healthy: got healthy result from https://node02.etcd.dev.com:2379
member f95caeae097ab105 is healthy: got healthy result from https://node01.etcd.dev.com:2379
cluster is healthy

**Comment by yichengq** [comment]
`ETCDCTL_ENDPOINT` is introduced in 2.2.0, so it doesn't work for 2.1.2.

@utahcon For 2.1.2, you still need to use ETCDCTL_PEERS

**Comment by utahcon** [comment]
That worked. Thanks!
