### ISSUE TITLE
--recursive etcdctl option is not documented

### ISSUE THREAD

**Issue by arthur-c** [coreos/etcd#3618]
Hi,
The --recursive flag option in etcdctl is very convenient but is not documented at all, that's too bad.
Regards,

Arthur

**Comment by yichengq** [comment]
Which part do you think is missing? I find `ls --recursive` is documented at https://github.com/coreos/etcd/tree/master/etcdctl#listing-a-directory

**Comment by xiang90** [comment]
I think @yichengq is correct.
