### ISSUE TITLE
etcdserver: what would be the best way to ensure PeerURLs are URLs.

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#3619]
https://github.com/coreos/etcd/blob/master/etcdserver/member.go#L38 notes:

```go
// RaftAttributes represents the raft related attributes of an etcd member.
type RaftAttributes struct {
	// TODO(philips): ensure these are URLs
	PeerURLs []string `json:"peerURLs"`
}
```

Is this `TODO` still valid? I was working on changing the types into `types.URLs` as below:

```go
type RaftAttributes struct {
	PeerURLs types.URLs `json:"peerURLs"`
}
```

But this requires a lot of code change, especially in test cases with `nil`
PeerURLs string slices, and urls without port. What would be the best way
to ensure PeerURLs be valid URLs? Did you consider any regex (e.g. https://github.com/asaskevich/govalidator/blob/master/validator.go#L43-L60),
or is etcd ok with changing the types into `types.URLs`? I have a code
but haven't submitted PR yet.

Thanks,

**Comment by yichengq** [comment]
My first thought is that etcd should have validated all peer URLs either when bootstrap or when adding/updating member. If this is true, we could just add comments about how this is ensured.

**Comment by gyuho** [comment]
@yichengq Makes sense.

I added a comment to clarify this: https://github.com/coreos/etcd/pull/3622

**Comment by gyuho** [comment]
Closing this for https://github.com/coreos/etcd/pull/3622
