### ISSUE TITLE
etcdctl doesn't honor dns discovery flag

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3620]
I had opened this in #3244 but at that time I was not using the latest code.

[Documentation](https://github.com/coreos/etcd/tree/release-2.2/etcdctl#dns-discovery) says --discovery-srv flag can be used instead of --endpoint but it doesn't seem to work.

$ ./etcdctl --peers="https://node01.etcd.dev.com:2379,https://node02.etcd.dev.com:2379,https://node03.etcd.dev.com:2379" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health
member 4c5854cca2fdc9c is healthy: got healthy result from https://node03.etcd.dev.com:2379
member 5f97c3330e24a56d is healthy: got healthy result from https://node02.etcd.dev.com:2379
member f95caeae097ab105 is healthy: got healthy result from https://node01.etcd.dev.com:2379
cluster is healthy

$ ./etcdctl --discovery-srv="etcd.dev.com" --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health
cluster may be unhealthy: failed to list members
Error:  unexpected status code 404

$ export ETCDCTL_DISCOVERY_SRV=etcd.dev.com
$ echo $ETCDCTL_DISCOVERY_SRV
etcd.dev.com

$ ./etcdctl --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem cluster-health        
cluster may be unhealthy: failed to list members
Error:  unexpected status code 404

**Comment by yichengq** [comment]
Could `--debug` flag tell you more?

/cc @MSamman

**Comment by raoofm** [comment]
I checked this last time as well and traced it back to code where it is using incorrect url. I checked on how etcd is doing discovery and saw that it is doing a substring of the url.

Notice the . dot after dns name and before port.

Also it is using the peer URLs instead of client

$ ./etcdctl --cert-file=/var/home/rm/node01.etcd.dev.com.cert.pem --key-file=/var/home/rm/node01.etcd.dev.com.pem --ca-file=/var/home/rm/ca.cert.pem --debug cluster-health

Cluster-Endpoints: https://node01.etcd.dev.com.:2380, https://node03.etcd.dev.com.:2380, https://node02.etcd.dev.com.:2380

cURL Command: curl -X GET https://node01.etcd.dev.com.:2380/v2/members
cluster may be unhealthy: failed to list members
Error:  unexpected status code 404

**Comment by yichengq** [comment]
@raoofm I confirm this is bug.
@MSamman Do you want to fix this?

**Comment by MSamman** [comment]
Yea I'll give it a go.

**Comment by yichengq** [comment]
@MSamman Thanks!

**Comment by MSamman** [comment]
> ...traced it back to code where it is using incorrect url
>
 > Notice the . dot after dns name and before port.

@raoofm Just so I understand what you mean when you say both of the preceding.

You are saying that https://github.com/coreos/etcd/blob/master/client/srv.go#L47 is creating the wrong URL due to the srv target having the extra dot at the end?

> Also it is using the peer URLs instead of client

I don't think this is an issue with SRV. That has to do with cluster health command?

**Comment by MSamman** [comment]
@yichengq It also seems like the SRV record should have an A or AAA record as a target so I think I will also remove the tests in https://github.com/coreos/etcd/blob/master/client/srv_test.go that use IP address strings in the mock srv records.

**Comment by raoofm** [comment]
@MSamman right

**Comment by yichengq** [comment]
> I don't think this is an issue with SRV. That has to do with cluster health command?

I think it is the problem of `getDomainDiscoveryFlagValue` usage. The value fetched from discovery SRV is peer urls, and they are used as client urls in etcdctl.

**Comment by MSamman** [comment]
@yichengq Should there be a separate SRV record for client endpoints then?

Maybe something like `_etcd-server-ssl-client._tcp.example.com` and `_etcd-server-client._tcp.example.com`? And then we lookup the correct SRV records depending on whether client or peer urls are requested?

**Comment by yichengq** [comment]
> Should there be a separate SRV record for client endpoints then?

This would be a different workflow/feature then.

**Comment by MSamman** [comment]
> This would be a different workflow/feature then.

I don't see how else you can get client endpoints from an SRV record? Please advise on how I could get client endpoints from an SRV record that provides peer endpoints.

**Comment by yichengq** [comment]
> I don't see how else you can get client endpoints from an SRV record? Please advise on how I could get client endpoints from an SRV record that provides peer endpoints.

I cannot find a good way to implement that. Maybe we should rollback the feature.

@xiang90 Thoughts?

**Comment by raoofm** [comment]
@yichengq @MSamman @xiang90 We get the hostname from the SRV records right, can we try the default client port 2379 to get the members and continue. 

This is in sync with what we do currently for etcdctl cluster-health(or any) command when no endpoints are passed, we try the default host:port. Now that we have SRV we dont need to try the default host, but we can still try the default port.

**Comment by MSamman** [comment]
@raoofm That feels a bit weird to me, particularly because SRV has the capability to specify the target port. The discovery srv flag would then only work correctly if the client port is the default port. 

@yichengq @xiang90 Are there downsides to looking for a different SRV record for client endpoint information?  This makes sense. The client and peers endpoints service two different purposes and should be two separate SRV records?

**Comment by raoofm** [comment]
@MSamman agree on srv usage for target and port.
I just thought this to be a quick fix and something that can be used in the same workflow till we figure out a permanent solution, which in this case seems like what u suggested as client srv records (which rightly @yichengq said will be a different feature then).

@yichengq @xiang90 In case we go ahead with client srv records then probably it makes sense to get away with -client-urls and -peer-urls flags if discovery-srv is being used (why will we need these flags then).

**Comment by xiang90** [comment]
@raoofm @yichengq @MSamman I would also suggest to add a client srv target. It seems to be simple and we need to add documentation for that.

**Comment by MSamman** [comment]
@xiang90 I'll work on adding the ability to read client endpoints from a different SRV record. Would you like me to update #3626 or create a separate pull request for SRV discovery of client endpoints.

The way I see it, this thread is addressing two separate issues.

1) Incorrect construction of URL from SRV record- fixed by #3626 
2) SRV records return peer endpoints but not client endpoints - fixed by some future pull request

**Comment by nixn** [comment]
I would suggest the SRV record _etcd._tcp.example.com, like in confd (https://github.com/kelseyhightower/confd/blob/master/docs/dns-srv-records.md).

**Comment by nixn** [comment]
Also the target of an SRV record is a domain name, not an ip address (see RFC 2782).

Further the trailing dot in a domain name is not an error, it's just the other way: domain without a trailing dot are not fully qualified (see RFC 1034, or http://www.dns-sd.org/TrailingDotsInDomainNames.html).

**Comment by raoofm** [comment]
@nixn I understand that the trailing dot in a domain name is not an error. It is not an issue. Issue is that we were using that exactly as is in the curl http call, which is incorrect. We should trim before making a call.

**Comment by nixn** [comment]
@raoofm Why is this incorrect? That would change an already resolved domain name. If curl cares about the trailing dot (I didn't check that), it would again try to resolve the relative domain name, which imho would be wrong.

**Comment by raoofm** [comment]
@nixn I did more research on what you were referring to and I now understand your point about the fully qualified domain names. The only issue that I got is then etcd needs to be modified as well to use the fully qualified domain names rather than relative.

For the issue I reported - When I tried to see what is different in the way etcdctl is handling SRV and etcd, is the trimming of the trailing dot and actually using the peers urls instead of client urls

If I have a certificate with node01.etcd.dev.com then I will not be able to use it for node01.etcd.dev.com. 
So etcd needs to stop removing the trailing dot and users need to pass the config for peer and client urls with a dot and need to have certs with the dot too.

**Comment by MSamman** [comment]
@xiang90 @yichengq Is there any reason etcdctl would want peer urls as well as client urls?

**Comment by roboll** [comment]
shouldn't this apply to proxy as well? if we have client discovery then we shouldn't need to expose peer port to the proxy, and it can act as a pure client.

**Comment by xiang90** [comment]
@raoofm @MSamman @roboll @nixn I think we should add another srv endpoints for client. So the client can look it up. I will try to get it done this week. Thanks!
