### ISSUE TITLE
etcdctl no longer reports a nonzero exit status when cluster-health fails

### ISSUE THREAD

**Issue by mischief** [coreos/etcd#3624]
#3323 removed some calls to os.Exit(1) in etcdctl. it broke a test in kola.

the following code proceeds to check for (2*n)+1 instances of the word 'healthy' in etcdctl cluster-health output, but only when etcdctl cluster-health returns a 0 status. now that the behavior is changed, err is always nil due to a zero exit status.

https://github.com/coreos/mantle/blob/master/kola/tests/coretest/etcd.go#L92

**Comment by yichengq** [comment]
I check the meaning of exit code, and find that code 0 indicates `Program suseccfully completed.` But in practice, I find the `diff` returns 1 when some differences are found(http://stackoverflow.com/questions/6971284/what-are-the-error-exit-values-for-diff). Given the returned code defined here: https://github.com/coreos/etcd/tree/master/etcdctl#return-codes, it seems that returning 0 is more reasonable.

/cc @xiang90

**Comment by xiang90** [comment]
@yichengq @mischief This is tricky since `cluster is not healthy` does not mean that etcdctl health command fails. Also this command output is not designed to be programmatically consumed. You probably should not rely on this at all.

**Comment by mischief** [comment]
if that is the case, can you show me a documented method of checking cluster health of all nodes that works in a programmatic fashion?

**Comment by xiang90** [comment]
@mischief 

We do not provide that feature at the moment. You can try https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#health-monitoring. But this is also an experimental feature. We will break it probably.

**Comment by philips** [comment]
Setting a return code that is non-zero is perfectly fine and doesn't necessarily mean that the command itself failed. For example see the `test` builtin/command.

Exiting with a 1 is an appropriate thing to do if the cluster is non-healthy I think.

**Comment by yichengq** [comment]
@philips Setting it with 1 when non-healthy would not match `1    Malformed etcdctl arguments` documented in https://github.com/coreos/etcd/tree/master/etcdctl#return-codes . Any thoughts about how to make them consistent then?

**Comment by mischief** [comment]
why don't we follow systemd? https://github.com/systemd/systemd/blob/master/src/basic/exit-status.h

**Comment by yichengq** [comment]
@mischief etcdctl is not systemd, so there is no need to follow it. Anything good that we could learn from systemd case?

**Comment by philips** [comment]
@yichengq lets make it 6 then, it just needs to be some number that isn't 0.

**Comment by philips** [comment]
6 for degraded, 7 for unhealty, I am fine with this.

**Comment by philips** [comment]
cc @colhom
