### ISSUE TITLE
Only one out of two client urls used when in proxy mode

### ISSUE THREAD

**Issue by balboah** [coreos/etcd#3641]
Even when /v2/members returns something like:
```
"clientURLs":["http://10.0.2.14:4001","https://ec2-123-123-123-123.ap-southeast-1.compute.amazonaws.com:2379"]
```

etcd 2.1.2 only tries one out of two, 
```
proxy: failed to direct request to http://10.0.2.14:4001: dial tcp 10.0.2.14:4001: i/o timeout
```

I would expect it to also try
```
https://ec2-123-123-123-123.ap-southeast-1.compute.amazonaws.com:2379
```

But neither of the 5 etcd members where all are also listening on TLS port 2379 is tried. Only 4001 is.
I failed to find out what part of the code is causing this, and I apologize if it's already fixed in higher versions, this is what is running on CoreOS stable.

**Comment by yichengq** [comment]
I cannot reproduce that at my side using etcd v2.1.2.

1. I start etcd that reports multiple advertised client urls and listens on none of them:
```
./bin/etcd -advertise-client-urls http://127.0.0.1:2379,http://127.0.0.1:4001 -listen-client-urls http://127.0.0.1:5001
```
2. I start etcd proxy:
```
./bin/etcd -name proxy -proxy=on -listen-client-urls http://localhost:8080 -initial-cluster 'infra1=http://localhost:2380,infra1=http://localhost:7001'
```
3. When I make request to it:
```
2015/10/5 10:06:53 proxy: failed to direct request to http://127.0.0.1:2379: dial tcp 127.0.0.1:2379: getsockopt: connection refused
2015/10/5 10:06:53 proxy: marked endpoint http://127.0.0.1:2379 unavailable
2015/10/5 10:06:53 proxy: failed to direct request to http://127.0.0.1:4001: dial tcp 127.0.0.1:4001: getsockopt: connection refused
2015/10/5 10:06:53 proxy: marked endpoint http://127.0.0.1:4001 unavailable
2015/10/5 10:06:53 proxy: unable to get response from 2 endpoint(s)
```

Could you give detailed instructions about how I could reproduce it?

**Comment by balboah** [comment]
That log output looks correct, I'll try to reproduce it similar to how you did soon.
meanwhile, one idea could be that we use TLS for the 2379 port but non-tls for the 4001

**Comment by yichengq** [comment]
@balboah How is the reproduction going?

**Comment by balboah** [comment]
I simply skipped advertising the non-TLS client url and didn't try to reproduce the problem. You may close this if it's a dead end as I will unfortunately not have the time to debug it further in a while

**Comment by yichengq** [comment]
I have tried to start etcd with non-TLS url and TLS url, and proxy will try both of them. So I fail to reproduce the problem.

@balboah Let me know if you reproduce this problem successfully.
