### ISSUE TITLE
no errorCode returned from etcd, only message is returned, which is a problem for clients

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3646]
I opened this earlier as well  #3235

$ curl http://node01.etcd.dev.com:2377/v2/members/nonExistentPath
{"message":"Not found"}

**Comment by raoofm** [comment]
I mentioned below in #3235 :smile: 

>@xiang90 Thanks. I'm petty sure you got what I meant but I'll still clarify it further.

>I didn't mean only the message {"message":"Insufficient credentials"} but I mean that if etcd is not returning value of a key then it should return an errorCode.

>If there is no direct mapping for a faiure message to errrorCode then it should still be sending a default errorCode always.*

**Comment by xiang90** [comment]
@raoofm Only key space will return the errorCode. Member space will not.

**Comment by raoofm** [comment]
So if we are not going to have default errorCode then I can go ahead and close it. I thought if there is no errorCode mapped then it should at least return a default errorCode, to be consistent.

**Comment by xiang90** [comment]
We probably are not going to fix this for v2. sorry.

**Comment by raoofm** [comment]
@xiang90 no problem, makes sense, thanks
