### ISSUE TITLE
proxy in `goreman start` needs a long time to find endpoint list

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3647]
https://gist.github.com/philips/7d58b20399baecfeeaa0

When `goreman start`, proxy fails to get endpoint list at the first time, and it may wait 30s to give it another try, which leads to the result that proxy may have 30s that cannot redirect correctly.

This should be improved.

/cc @philips

**Comment by gyuho** [comment]
from https://github.com/coreos/etcd/pull/3736#issuecomment-150708197

> If you try the redirect feature of proxy just after starting the cluster, it doesn't work:
> $ curl http://127.0.0.1:2379/v2/keys/foo
> {"message":"proxy: zero endpoints currently available"}

This happens when used with `goreman start` from master branch (SHA https://github.com/coreos/etcd/commit/4f47b08cf688663a4fccbb2930d797d6938cf6a5)

**Comment by gyuho** [comment]
This only happens with `goreman start` for me. I will investigate more.

<br>
Just tried with regular shell commands, and I don't see any issue with proxy:

```
./etcd -name infra1 -listen-client-urls http://127.0.0.1:12379 -advertise-client-urls http://127.0.0.1:12379 -listen-peer-urls http://127.0.0.1:12380 -initial-advertise-peer-urls http://127.0.0.1:12380 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' -initial-cluster-state new
./etcd -name infra2 -listen-client-urls http://127.0.0.1:22379 -advertise-client-urls http://127.0.0.1:22379 -listen-peer-urls http://127.0.0.1:22380 -initial-advertise-peer-urls http://127.0.0.1:22380 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' -initial-cluster-state new
./etcd -name infra3 -listen-client-urls http://127.0.0.1:32379 -advertise-client-urls http://127.0.0.1:32379 -listen-peer-urls http://127.0.0.1:32380 -initial-advertise-peer-urls http://127.0.0.1:32380 -initial-cluster-token etcd-cluster-1 -initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380' -initial-cluster-state new
./etcd -name infra-proxy1 -proxy=on -listen-client-urls http://127.0.0.1:2379 -initial-cluster 'infra1=http://127.0.0.1:12380,infra2=http://127.0.0.1:22380,infra3=http://127.0.0.1:32380'
```

with:

```
curl http://127.0.0.1:2379/v2/keys/foo
curl http://127.0.0.1:2379/v2/keys/message
curl http://127.0.0.1:2379/v2/keys/message -XPUT -d value="Hello world";
```

**Comment by yichengq** [comment]
@gyuho When etcd starts, it have empty cluster before applying any entry, so it may return proxy with empty cluster info.

**Comment by gyuho** [comment]
@yichengq Right, I think it's from `goreman` implementation:

https://github.com/mattn/goreman/blob/master/proc.go#L85-L87

It starts process from a map, which means there is no order.
So `goreman` might start proxy first, and when the proxy starts and
tries `refresh`, it doesn't get any endpoints for the first time, so it will
wait another 30 seconds.

**Comment by gyuho** [comment]
According to https://github.com/ddollar/foreman/issues/392#issuecomment-41108898, I don't think `goreman` would support ordered execution in Procfile. Currently, all processes get launched at the same time or without order, and the proxy node misses to grab the endpoints in the first `refresh` attempt and waits another 30-second. I can only think of forking `goreman` to support ordered execution, or decreasing the refresh interval for the first few tries, but they are all hacky.

@yichengq , how would you resolve this issue? Any suggestion? Thanks,

**Comment by yichengq** [comment]
@gyuho One possible way is to sleep 1s before starting proxy in Procfile. So cluster is running when proxy starts.

/cc @xiang90

**Comment by philips** [comment]
I am reopening this. I don't think it is reasonable to have random sleeps in the Procfile. We should fix the proxy by having it do an exponential backoff up to 30 seconds max or something.

**Comment by gyuho** [comment]
My first approach was https://github.com/coreos/etcd/pull/3736/files forcing it to refresh with much shorter intervals if the refresh interval is equal to or greater than 30 seconds for the first 5 trials. Would this help?

**Comment by yichengq** [comment]
@xiang90 @philips @gyuho I notice that proxy uses empty endpoint if it cannot connect to any member in the cluster(https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L395). So this is a general case instead of a bootstrap case that I thought before.

It may be reasonable to retry more frequently when the proxy doesn't have any endpoint. We need to find a clear way to tell users about this behavior.

**Comment by gyuho** [comment]
@yichengq Do you think the refresh should be done in `proxy` package level, or in `etcdmain`?
I think it makes more sense to expedite some director `refresh` method in `proxy` package,
which should be a simple tweak. What do you think?

**Comment by yichengq** [comment]
@gyuho That sounds good to me if this could be documented clearly.

**Comment by gyuho** [comment]
@yichengq Ok, I can work on it. I will add clear notes to Documentation as well. Thanks,
