### ISSUE TITLE
Benchmarking doesn't work as intended using boom

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3661]
I ran the same tests on my etcd cluster, what I figured out i that the boom tool that is used here is not setting the value. It is setting an empty value ""

So the tests we are running are not representing the stats based on keysize. It is always defaulted to empty string and not honoring -d flag.

Not sure if this issue should be opened in boom but I opened it here as it impacts etcd benchmarks.

$ ./boom -m PUT -n 1 -c 1 -d value="aaaa" http://test-vm-01:2379/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo -v
-v Requests/sec: 40.0509 Latency distribution:
$ curl http://test-vm-01:2379/v2/keys/foo
{"action":"get","node":{"key":"/foo","value":"","modifiedIndex":122143,"createdIndex":122143}}

**Comment by raoofm** [comment]
@yichengq any thoughts?

I ran the same tests as mentioned in hack too. Same result

**Comment by yichengq** [comment]
@raoofm boom sends PUT request with `Content-Type: text/html`, and this is cannot be parsed by etcd. It should use `Content-Type: application/x-www-form-urlencoded` to make requests. So the benchmark request is incorrect. :(

**Comment by raoofm** [comment]
@yichengq 
I referred the hack mentioned in https://github.com/coreos/etcd/blob/master/hack/benchmark/bench.sh,
to compoare our performance with the benchmarked.

The script doesn't set the Content-Type too.

**Comment by raoofm** [comment]
@yichengq So you mean we need to correct and try and then if it works I'll send a pull request. Right?

**Comment by yichengq** [comment]
@raoofm It needs to be updated with correct boom instructions. It would be awesome if you could help. Or I will do it soon.

**Comment by raoofm** [comment]
@yichengq Sure, I will do it. Thanks

**Comment by raoofm** [comment]
@yichengq ok thanks for confirming, as you mentioned in #3665 I'll wait here for the updated benchmarks

**Comment by raoofm** [comment]
@yichengq I see that the benchmarks are not present for v2.2.0
Is it possible to consider v2.2.0 for new benchmarking :) ?

**Comment by raoofm** [comment]
@yichengq ping

**Comment by xiang90** [comment]
@raoofm etcd 2.2 and etcd 2.2 rc are almost the same in terms of performance. We still want to do the benchmark for sure. But we do not have time currently.

**Comment by raoofm** [comment]
@xiang90 I understand that you guys might be really busy with v3

Agree that 2.2 and rc are almost same in perf but the reason I asked is, the rc bench-marking is incorrect as well and as per this defect in script, the value size was 0 for all tests, so there is no bench to compare our perfs against.

Also it would make a lot of sense if https and auth are also bench-marked as the perf goes down a lot. I understand there is no time right now but these features should be bench-marked as well.

**Comment by yichengq** [comment]
@raoofm Check this for the updated benchmark. https://github.com/coreos/etcd/pull/3738

**Comment by gyuho** [comment]
@xiang90 Isn't this resolved by https://github.com/coreos/etcd/pull/3665? Any more tasks to close this?
