### ISSUE TITLE
Can I judge a member is isolated from the cluster based on Self Statistics?

### ISSUE THREAD

**Issue by mqliang** [coreos/etcd#3669]
If my client connected to a etcd member, but unfortunately it is isolated from the cluster, then the client may retrieve outdated data. As we all know, we can get a number of internal statistics by run:
```sh
curl http//hostip:2379/v2/ststs/self
```
It seems that `recvAppendRequestCnt` and `sendAppendRequestCnt` will never change if the member is isolated from the cluster. On the other hand, those two number will change frequently if the member is healthy. Can we judge whether a member is isolated based on those information? If we can, what is the change frequency of those two numbesr?

**Comment by yichengq** [comment]
You can use the experimental `health` endpoint to get the health status of this member: https://github.com/coreos/etcd/blob/804d80387d3fc75cdd5481039095df56268afe6f/Documentation/admin_guide.md#health-monitoring . It can tell whether member is connected with the majority of the cluster. Could this satisfy your requirements?

/cc @xiang90

**Comment by mqliang** [comment]
Oh, I know there is an experimental `health` endpoint after release 2.1.0, which is very helpful. But unfortunately, we use 2.0 version. 
BTW, I read the source code of command `etcdctl cluster-health` to see how it implement heath monitoring. However, according to my experiment, the result of command `etcdctl cluster-health` is not stable, there are three possible result we can get when a member is ioslated:
* cluster is unhealthy
* cluster may be unhealthy: fail to connect 
* cluster is healthy: member XXX is healthy; member YYY is unhealthy....

**Comment by mqliang** [comment]
It seems that the experimental `health` endpoint is available after release 2.1.0. Unfortunately, we use v2.0

BTW, I read the implementation of command `etcdctl cluster-health` in v2.0, but the method it used is not stable, there are three possible response we can get if a member is isolated:
* cluster is unhealthy
* cluster may be unhealthy: failed to connect 
* cluster is healthy:  member XXX is healthy; healthy YYY is unhealthy, etc

Is there any method can return a stable and definite response? Is my idea which based on `recvAppendRequestCnt` and `sendAppendRequestCntidea` feasible?

**Comment by xiang90** [comment]
@mqliang We best suggestion is to upgrade to 2.1. Your idea is not feasible since some low level transportation constrains: if one side dies without finishing TCP closing, it might takes a long time to detect the failure. We fix it in 2.1.
