### ISSUE TITLE
Embedding etcd into an existing golang project

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#3670]
I like etcd and so far it has been working great! w00t...
I'd like to "embed" it into an existing golang project, in that it would get compiled into the same single golang binary, and that project could start/stop/etc the etcd server without having to run exec calls to a standalone /usr/bin/etcd binary. Any pointers about how to do this would be greatly appreciated. I've heard this isn't a standard supported scenario at the moment, but I think it would be extremely useful. I'm happy to be the testcase/first user.

Cheers!
James

**Comment by gyuho** [comment]
Couldn't we use [`etcdmain`](https://github.com/coreos/etcd/tree/master/etcdmain), which is used to compile into a single binary? As far as I know, `etcd` begins starting a new web server. But not sure about stopping etcd servers.

**Comment by xiang90** [comment]
@purpleidea We embed etcd for integration test. Here is an example of embedding etcd: https://github.com/coreos/etcd/blob/master/integration/cluster_test.go#L393-L395

**Comment by xiang90** [comment]
You can also try https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L196.

**Comment by mischief** [comment]
here's another very basic example.

https://github.com/coreos/mantle/blob/master/platform/local/etcd.go

**Comment by xiang90** [comment]
@purpleidea Actually I am closing this due to low activity. @mischief @gyuho and I provided a few examples. Please give them a try. Thanks!

**Comment by purpleidea** [comment]
> @purpleidea Actually I am closing this due to low activity. @mischief @gyuho and I provided a few examples. Please give them a try. Thanks!

That is quite alright, and thank you for your help. I will try and send some doc patches if you wish in the future once I've implemented my etcd embedding. Thanks for all your work.

**Comment by xiang90** [comment]
> I will try and send some doc patches if you wish in the future once I've implemented my etcd embedding

Excellent!

**Comment by purpleidea** [comment]
Sorry for the giant delay, but I've actually started hacking on this now, and am going through some etcd internals and will ultimately prepare some patches if needed...

Question: Is targeting git master okay, or should I branch off of v2.3.0 ? I'm happy to use git master as long as I'm correct in understanding that this will eventually become the v2.3.x or v2.4.x release, at some point.

Thanks again

**Comment by xiang90** [comment]
git master is OK. We will back-port bug fixes. New features will usually not be back-ported though. Master will become a new minor or major release eventually.
