### ISSUE TITLE
Discovery url : flush all nodes 

### ISSUE THREAD

**Issue by goacid** [coreos/etcd#3671]
I read that nodes register into discovery url have a lifetime of 7 days. And are remove if they are no more alive.
So if I have a cluster with many nodes, and at a moment the 3 firsts cluster members are removed, so the discovery url contains no more information, the discovery url become useless.
Is there a way to add manually nodes to discovery url, via a POST or a PUT ?
If no, how to continue working if the url is useless without creating a new cluster ?

**Comment by yichengq** [comment]
@goacid Discovery url is only used in bootstrap stage. See https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#lifetime-of-a-discovery-url for more details.

You should NOT manually add nodes to discovery url.

**Comment by yichengq** [comment]
If you are still using etcd 0.4, I would recommend you to upgrade to etcd v2.x, which is more stable and maintained than 0.4.

If you are using etcd 0.4, you should not rely on discovery url to monitor the cluster information.

**Comment by goacid** [comment]
I'm using etcd v2.x
I do understand the bootstrap process. I also imagine a case when all nodes used in the bootstrap sequence are removed. so the cluster become no more scalable, that is my point, even if other 'member' added manually to the cluster still exist.

**Comment by xiang90** [comment]
@goacid The public discovery service is only used for the discovery phase. After discovery, the whole cluster is under your own control. See https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#do-not-use-public-discovery-service-for-runtime-reconfiguration for reasons that public discovery service does not provide extensive features.

You can save the cluster information from etcd itself. You can publish etcd cluster information to your internal service. Or you can build your own discovery service to do whatever you want: https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#custom-etcd-discovery-service.

**Comment by yichengq** [comment]
I think xiang has fully answered your question.
