### ISSUE TITLE
Deliver all deleted objects to watcher if whole directory is removed

### ISSUE THREAD

**Issue by wojtek-t** [coreos/etcd#3672]
[I don't know whether this is supported or not - filing this issue so that I understand the plans].

In the "go-etcd" client if you have an open watch and in the meantime the whole (sub)directory is removed the watcher is notified only about deletion of that directory (watch doesn't give you individual objects that were deleted).
It will be extremely useful in Kubernetes, if the new client would expose the option (possibly switched off by default) to switch on delivering all deleted objects when the whole directory was removed?

I think we talked about it at some point, but just wanted to understand the current status of it.

@xiang90 @yichengq

**Comment by xiang90** [comment]
This is not a client side issue. This is actually a server side issue. We are going to solve in v2. For v3, we have already solved it.

**Comment by wojtek-t** [comment]
@xiang90 - thanks for the response; do you have any ETA for solving it in v2?

**Comment by xiang90** [comment]
@wojtek-t Sorry. I lied... I wanted to say "we are not going to solve it in v2".

**Comment by wojtek-t** [comment]
@xiang90 - got it. Thanks for the update.

**Comment by wojtek-t** [comment]
Ohh - actually one more question. What is the solution in v3? Is is send by default or is it possible to set it?

**Comment by xiang90** [comment]
@wojtek-t So in v3, the store is a flat one. There is no dir operation. You can remove a range of keys. The watchers watching on a related prefix or a key will be notified with all key changes.

**Comment by wojtek-t** [comment]
@xiang90 - got it. thanks!
