### ISSUE TITLE
docs: document maximum size of values

### ISSUE THREAD

**Issue by xtaci** [coreos/etcd#3686]
what is the maximum size of value?
cannot find in any document.

**Comment by gyuho** [comment]
I am curious about this as well. BoltDB has maximum key, value size as constants [1]. Would etcd be bound by this as well, since the same database is being used as a backend storage for etcd?


<hr>
[1] https://godoc.org/github.com/boltdb/bolt#pkg-constants

**Comment by raoofm** [comment]
Is there a max for key/path as well?

**Comment by xtaci** [comment]
still waiting for clarification...

**Comment by yichengq** [comment]
The recommended value size is < 1MB at this time. Though there is no hard limitation currently, the goal of etcd is a consistent data store that serves small value.

**Comment by xtaci** [comment]
actually, I need to store an xlsx file encoded in base64, perhaps it would easily break that limit.

**Comment by xtaci** [comment]
please! make this limit larger, >16MB is required.

**Comment by xiang90** [comment]
dup with https://github.com/coreos/etcd/issues/1978
