### ISSUE TITLE
Why does etcd have a dependency on Prometheus?

### ISSUE THREAD

**Issue by bmhatfield** [coreos/etcd#3688]
https://github.com/coreos/etcd/tree/master/Godeps/_workspace/src/github.com/prometheus

What's the relationship from `etcd` to prometheus? What does it mean to folks who don't want to use prometheus?

**Comment by jonboulle** [comment]
It's used to expose various metrics about etcd's performance: https://github.com/coreos/etcd/blob/9534b11ad2ee87a266255f42f1f682bd06a03f85/Documentation/metrics.md

Is the dependency causing you problems?

**Comment by xiang90** [comment]
> What does it mean to folks who don't want to use prometheus?

It means a little overhead when collecting these metrics. Prometheus is a pulling based metrics system. At etcd server side, it exposes a simple http endpoint. So even if you do not use Prometheus, you can have a http client that pulling metrics from that endpoint to collect performance metrics for etcd. That is useful for you to monitor etcd.

See https://github.com/coreos/etcd/blob/master/Documentation/metrics.md for more details. Also this is a experimental features for now. We would love to hear feedback from you. 

Thanks!

**Comment by bmhatfield** [comment]
Thank you so much for all the context! This is the answer I was looking for. I really appreciate it!
