### ISSUE TITLE
Can we have both ssl and non-ssl SRV records?

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3693]
Can we have both ssl and non-ssl SRV records for discovery?

If yes then how will etcd behave, I mean will the peers communicate on ssl or non-ssl?

**Comment by xiang90** [comment]
@raoofm etcd will be misconfigured. Do you think it make sense to prioritize ssl ones over non-ssl? Or do you want to try weights? There are todos for srv discovery.

See  https://github.com/coreos/etcd/blob/master/discovery/srv.go#L31-L33

**Comment by xiang90** [comment]
@raoofm Closing due to low activity. If you are still interested in making this happen, please reopen it.

**Comment by raoofm** [comment]
@xiang90 I opened this issue based on our prod experiences and extensive performance testing.

We figured that etcd performance degrades in two cases (auth & https)

etcd is fast enough for our usage but in case we hit a point where we wanted to disable https or auth then it shouldn't be a multi layer change, u should be allowed to just flip a flag to use https or not. It shouldn't be a change in SRV records managed by other teams, it should be local to etcd.

Keeping that in mind, if it is allowed to have ssl and non ssl SRV records and having a flag in etcd to indicate whether https is required or not will be great.

I understand it is not possible for v2. If it is an acceptable usecase then it will be good if you guys consider this for v3.
----------------------------------------------
Also what i meant by saying "can we have both ssl and non-ssl" is within a same cluster can we have a mixed cluster with ssl and non-ssl records

node1 -> node2 ssl
node2 -> node1 ssl
node1 -> node3 non-ssl
node2 -> node3 non-ssl
node3 -> node1 ssl
node3 -> node2 ssl

**Comment by xiang90** [comment]
> Also what i meant by saying "can we have both ssl and non-ssl" is can we have a mixed cluster with ssl and non-ssl records

What is the use case for this? Cross DC cluster? To support this, we need to change a few things, not just srv records.

**Comment by raoofm** [comment]
yes

**Comment by raoofm** [comment]
Another thing that i wanted to propose is - why do we have different SRV records for ssl and non ssl records

As of now we specify
_etcd-server._tcp.example.com. 300 IN   SRV 0 0 2380 infra0.example.com.
or
_etcd-server-ssl._tcp.example.com 300 IN   SRV 0 0 2380 infra0.example.com.
and start etcd like
$ etcd -name infra0 -discovery-srv example.com 


Instead we can always specify only 
_etcd-server._tcp.example.com. 300 IN   SRV 0 0 2380 infra0.example.com.
and start etcd like
$ etcd -name infra0 -discovery-srv example.com -peer-mode ssl
or
$ etcd -name infra0 -discovery-srv example.com -peer-mode non-ssl


Another option is we can always specify only 
_etcd-server._tcp.example.com. 300 IN   SRV 0 0 2380 infra0.example.com.
and start etcd like
$ etcd -name infra0 -discovery-srv example.com 
and determine whether ssl is required or not from -listen-peer-urls and/or -initial-advertise-peer-urls

By doing this, we keep the change of etcd peer communication ssl/non-ssl local to etcd and not on DNS SRV

**Comment by raoofm** [comment]
Same thing for something you recently proposed for new SRV for client

**Comment by xiang90** [comment]
@raoofm 

The first proposal requires additional flag and it is just for srv discovery.

The second proposal requires for smart etcd configuration, which we try hard to avoid.

Is there any trouble for you to switch from non-ssl SRV records to ssl ones?

**Comment by xiang90** [comment]
@raoofm In another word, I feel a SRV discovery configuration should deterministically define one etcd cluster configuration. Restarting etcd or changing etcd flags should not affect the cluster configuration. Mixing ssl and non-ssl might be acceptable, but that requires other changes. Changing a flag in etcd to change the entire cluster configuration seems to be not acceptable.

**Comment by raoofm** [comment]
agree, thanks

**Comment by xiang90** [comment]
@raoofm No problem. It would be great if you can create an issue for mixing https and http member cluster? I can do that later.

**Comment by raoofm** [comment]
sure
