### ISSUE TITLE
Private etcd-discovery with ssl

### ISSUE THREAD

**Issue by arpanps** [coreos/etcd#3698]
Can I have private ssl enabled etcd-discovery?

I tried client to server and peer to peer etcd ssl communication but was not able to work with a ssl enabled etcd-discovery

I have started discoveryIP with certificates. Added 
curl --cacert ../certs/certs/ca.crt --cert ../certs/certs/node-infra0-client.crt --key ../certs/private/node-infra0-client.key -X PUT https://discovery:2379/v2/keys/_etcd/registry/${ETCD_CLUSTER_UUID_TOKEN}/_config/size -d value=3

now while trying to add peer I am getting following error.

2015-10-17 06:10:23.263736 I | etcdmain: clientTLS: cert = ../certs/certs/node-infra3-client.crt, key = ../certs/private/node-infra3-client.key, ca = ../certs/certs/ca.crt, trusted-ca = , client-cert-auth = false
2015-10-17 06:10:23.265712 I | etcdmain: listening for client requests on https://MYIP:7001
2015-10-17 06:10:23.266622 I | etcdmain: listening for client requests on https://127.0.0.1:7001
2015-10-17 06:10:23.300918 E | discovery: error #0: x509: certificate signed by unknown authority
2015-10-17 06:10:23.300988 I | discovery: cluster status check: error connecting to https://discoveryIP:2379, retrying in 2s

**Comment by xiang90** [comment]
> 2015-10-17 06:10:23.300918 E | discovery: error #0: x509: certificate signed by unknown authority

Seems that you are using a self-signed cert for your discover server?

**Comment by arpanps** [comment]
Yes. How do i test otherwise?

**Comment by raoofm** [comment]
@arpanps @xiang90 If you are using a self signed cert then to make that acceptable you need to append your ca to the actual ca

**Comment by arpanps** [comment]
@raoofm @xiang90 is this documented anywhere? Can you please provide more details. 
Thanks for prompt answers.

**Comment by Neverous** [comment]
Hi I've got a question that probably goes along with this one. 
Is it possible to use custom discovery service that requires client certificates ?
I can get past "certificate signed by unknown authority" by adding my CA to the system certs, but I can't find if it's possible to somehow provide client cert for discovery connection.

Thanks in advance.

**Comment by xiang90** [comment]
For discovery service related question, please file an issue here: https://github.com/coreos/discovery.etcd.io.

It seems that discovery uses an empty config https://github.com/coreos/discovery.etcd.io/blob/master/handlers/new.go#L36. So if you want to connect to a secure server, you need to add the cert into your system or you will get untrusted cert complaint.
