### ISSUE TITLE
saving snapshot should not block raftNode loop

### ISSUE THREAD

**Issue by jonboulle** [coreos/etcd#3714]

**Comment by xiang90** [comment]
v3 snapshot saving already does not blocking raft at all. The actual saving happens in a goroutine in rafthttp library(https://github.com/coreos/etcd/blob/master/rafthttp/http.go#L173-L179). And that routine send the raft.MsgSnap to raft. Now we only need to make sure the snapshot recovery does not block raft/etcdserver loop.

Moreover, we assume v2 snapshot is small so it does not matter a lot although it still blocks.
