### ISSUE TITLE
After 2.2.1 update (from 2.1.3 ) auth: no authorization provided, checking guest access

### ISSUE THREAD

**Issue by floriankoch** [coreos/etcd#3728]
Hi,

after updating the cluster from 2.1.3 to 2.2.1 i got the following errors in the log. I can access the cluster without any problems, so what does these errors for?

Oct 21 07:52:08 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:08 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:09 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:09 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:10 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:10 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:11 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:11 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:12 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:13 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:13 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:14 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access
Oct 21 07:52:14 zkm01.example.net etcd[43027]: auth: no authorization provided, checking guest access

regards Florian

**Comment by yichengq** [comment]
@floriankoch The auth feature of the etcd cluster is enabled, but no authorization info is provided for HTTP request. It falls back to guest access to make it happen, and prints warnings about it.

Read https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#roles and https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#enable-and-disable-authentication for more details.

**Comment by floriankoch** [comment]
ah  thx for the hint
