### ISSUE TITLE
etcdctl 2.2.x 404's trying to talk to etcd 0.4.9

### ISSUE THREAD

**Issue by wday** [coreos/etcd#3752]
Running etcd 0.4.9 on coreos-beta 835.1.0, etcdctl 2.2.0 and 2.2.1 are unable to work with etcd. I can curl it directly to get and set keys. etcdctl 2.1.3 works fine.

```
core@core-01 ~/etcd-v2.2.1-linux-amd64 $ ./etcdctl ls --recursive
Error:  unexpected status code 404
core@core-01 ~/etcd-v2.2.1-linux-amd64 $ ./etcdctl --debug ls --recursive
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
Error:  unexpected status code 404
core@core-01 ~/etcd-v2.2.1-linux-amd64 $ curl http://127.0.0.1:4001/v2/members
404 page not found
```

whereas using etcdctl 2.1.3

```
core@core-01 ~/etcd-v2.1.3-linux-amd64 $ ./etcdctl ls --recursive
/foobar
/foobar/615

core@core-01 ~/etcd-v2.1.3-linux-amd64 $ curl http://127.0.0.1:4001/v2/keys/foobar
{"action":"get","node":{"key":"/foobar","dir":true,"nodes":[{"key":"/foobar/615","value":"baz","modifiedIndex":615,"createdIndex":615}],"modifiedIndex":615,"createdIndex":615}}
```

**Comment by xiang90** [comment]
@wday etcd 2.2.x (including etcdctl) is not compatible with etcd 0.4.x. Try to use an old version of etcdctl instead. Sorry for the inconvenience.

**Comment by wday** [comment]
Is it intended that 0.4.9 is the default etcd in the current beta channel? What is the expected process for launching 835.1.0 with an older etcdctl?

**Comment by wday** [comment]
Never mind, looks like our fork of coreos-vagrant has diverged from upstream. Didn't realize etcd2 was the default now.
