### ISSUE TITLE
Proxy does SRV look up for restart and then reads cluster file. It should do only 1 of file/SRV

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3753]
Proxy does SRV look up for restart and then reads cluster file whereas it should not do SRV lookup when already initialized as proxy before.

2015-09-10 22:20:08.900929 I | etcdmain: etcd Version: 2.2.0
2015-09-10 22:20:08.901042 I | etcdmain: Git SHA: e4561dd
2015-09-10 22:20:08.901059 I | etcdmain: Go Version: go1.5
2015-09-10 22:20:08.901074 I | etcdmain: Go OS/Arch: linux/amd64
2015-09-10 22:20:08.901089 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2015-09-10 22:20:08.902284 N | discovery: got bootstrap from DNS for etcd-server-ssl at https://node02.etcd.dev.com:2380
2015-09-10 22:20:08.902329 N | discovery: got bootstrap from DNS for etcd-server-ssl at https://node03.etcd.dev.com:2380
2015-09-10 22:20:08.902361 N | discovery: got bootstrap from DNS for etcd-server-ssl at https://node01.etcd.dev.com:2380
2015-09-10 22:20:08.903795 I | etcdmain: proxy: using peer urls [https://node01.etcd.dev.com:2380 https://node02.etcd.dev.com:2380 https://node03.etcd.dev.com:2380]
2015-09-10 22:20:08.988075 I | etcdmain: proxy: listening for client requests on http://node01.etcd.dev.com:2377

2015-09-29 20:37:13.564817 N | osutil: received terminated signal, shutting down...

2015-09-29 20:37:14.895808 I | etcdmain: etcd Version: 2.2.0
2015-09-29 20:37:14.895879 I | etcdmain: Git SHA: e4561dd
2015-09-29 20:37:14.895890 I | etcdmain: Go Version: go1.5
2015-09-29 20:37:14.895901 I | etcdmain: Go OS/Arch: linux/amd64
2015-09-29 20:37:14.895913 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2015-09-29 20:37:14.908633 N | etcdmain: the server is already initialized as proxy before, starting as etcd proxy...
2015-09-29 20:37:14.925592 N | discovery: got bootstrap from DNS for etcd-server-ssl at https://node01.etcd.dev.com:2380
2015-09-29 20:37:14.925637 N | discovery: got bootstrap from DNS for etcd-server-ssl at https://node02.etcd.dev.com:2380
2015-09-29 20:37:14.925677 N | discovery: got bootstrap from DNS for etcd-server-ssl at https://node03.etcd.dev.com:2380
**2015-09-29 20:37:15.046338 I | etcdmain: proxy: using peer urls [https://node01.etcd.dev.com:2380 https://node02.etcd.dev.com:2380 https://node03.etcd.dev.com:2380] from cluster file "/var/lib/etcdProxy/proxy/datadir/proxy/cluster"**

I actually prefer being able to give an option "bootstrap from" SRV/file so that proxy can refresh itself from SRV (#3743). In any case, it should be from 1 of the two and not from both.

**Comment by raoofm** [comment]
Does it make sense that proxy should always look at SRV rather than file on restart (or) lookup up member file only if SRV lookup fails.

The reason I created this issue is proxy on restart gives a wrong impression from logs that it is going to use members from SRV lookup but it is actually using members from the file that it wrote.

In my opinion,

* On Start up use SRV/inital-cluster
* On ReStart use SRV/initial-cluster
* While running if all the nodes are not reachable 
 * Panic - may be the whole cluster is down
 * Refresh SRV to see if a new cluster is rolled up
 * This makes sense wrather then someone going manually and deleting data-dir for proxy to reconfigure itself
 * It is unacceptable to say that all clients (may be thousands) should stop their local proxy, delete data-dir and restart.

**Comment by raoofm** [comment]
ping ?

**Comment by xiang90** [comment]
@raoofm 

We do not really want to make this complicated. Now both DNS SRV and discovery service are only designed to work for bootstrapping.

> Proxy does SRV look up for restart and then reads cluster file whereas it should not do SRV lookup when already initialized as proxy before.

We should fix this by not looking up SRV if there is configuration file.

We might need to find a way to change the cluster location for proxy dynamically when the cluster changes dramatically. But we do not have plan now.

**Comment by xiang90** [comment]
@raoofm Sorry for the long delay on this thread.

**Comment by raoofm** [comment]
@xiang90 I appreciate that you fixed the issue of not looking up SRV for restarts.

Consider this use case of a 3 member cluster:

SRV is based on example.com
    node1.example.com
    node2.example.com
    node3.example.com

Usually etcd is used by hundreds to thousands of apps for config management.Best practice is to have a local proxy with each app. 

If the cluster goes down and a new cluster is rolled up
    node4.example.com
    node5.example.com
    node6.example.com

Is it a wrong expectation that proxy should refresh SRV with example.com?

Always reading from the file will cause a major issue. A manual intervention is really a minus and impractical. 

I think it is really safe for proxies to refresh using SRV if whole cluster goes down, though I understand that same logic cannot be applied to cluster as I agree with your earlier discussion that member add/delete should be managed more carefully.

**Comment by raoofm** [comment]
I think I misunderstood you, if you agree should I open another issue for this use case?

**Comment by xiang90** [comment]
@raoofm SRV discovery is only designed for bootstrapping. We do not have any mechanism to swap a proxy from one cluster to another one without removing the configuration file and it is not designed that way currently. I understand your requirement. Our general suggestion is to restart the proxy since the cluster is basically gone and the clusterID/memberID are changed. The app/proxy should be aware of that. 

But we are OK to add an endpoint to let administer to stop the current proxy and refresh the cluster information. 

What we do not want is to make etcd proxy smart enough to do cluster discovery at runtime by itself.

**Comment by raoofm** [comment]
@xiang90 I understand your point too regarding SRV usage for only boot up, but there has to be a practical solution to this problem.

>Our general suggestion is to restart the proxy since the cluster is basically gone and the clusterID/memberID are changed. The app/proxy should be aware of that.

It is not just a restart, it requires the data-dir to be deleted as well. Now this gives a problem as this has to be done 
* manually by admin or 
* we impose that any app using proxy should on failure stop | delete data-dir | restart
* a script that continuously monitors proxy and does stop | delete data-dir | restart

Practically impossible for a production scenario with hundreds/thousands of services, they will have an unacceptable downtime.

> But we are OK to add an endpoint to let administrators to stop the current proxy and refresh the cluster information.

As I mentioned above, proxy usage in most scenarios are usually not a bunch of 5 machines like an etcd cluster which can be managed by an admin. I disagree with the solution, but with all due respect accept if etcd-dev doesn't think this way.

**Comment by xiang90** [comment]
@raoofm This will be the exact same issue with using etcd without proxy, right? All your client needs to be reconfigured in some way when your old cluster is gone. 

Trust me I understand this issue. I know it is painful for people to restart their etcd/zookeeper client to refresh cluster configuration cache. However, current we do not really have a solution for cluster swapping. I believe this is a separate issue from today's bootstrapping discovery one and deserves a careful design.

**Comment by raoofm** [comment]
>This will be the exact same issue with using etcd without proxy, right? All your client needs to be reconfigured in some way when your old cluster is gone.

Right, that's the reason we love etcdProxy :smiley: 

>Trust me I understand this issue. I know it is painful for people to restart their etcd/zookeeper client to refresh cluster configuration cache.

It really is for a number of applications having local proxy.

>However, current we do not really have a solution for cluster swapping. I believe this is a separate issue from today's bootstrapping discovery one and deserves a careful design.

Honestly I understand you, but we have a solution by refreshing proxy from SRV - simple and effective.

**Rethink**
I went back to think from a different perspective as to why etcd is so reluctant to just refresh. Does it give a benefit or does it bring in more failure points by bringing in more problems while solving one.

(Let me be clear that I agree cluster reconfiguration should require manual intervention and should not be handled through SRV changes, but proxy can)

Lets look at it

- etcd and proxy both look at SRV only during bootstrap, beyond that point they don't care if the SRV records exist or the DNS is available. Irrespective of it, the cluster and proxy will work fine. Beyond bootstrap the cluster config comes from its local data store and a failure point(DNS/SRV) is eliminated.
 - This can be handled, if SRV lookup fails then use local proxy data file for config.

- You can bootstap multiple clusters using SRV in the same domain.
Example: 
node1.example.com, node2.example.com node3.example.com
then change SRV mapping to
node4.example.com, node5.example.com node6.example.com
.......
......go on to bootstap as many clusters as you want using SRV

This way you can have multipe clusters in the same domain, serving different services for different applications and proxyies knowing to which cluster to talk to.
**BUT refresh would cause undesirable effects and will switch the proxy to a different cluster**

Unfortunately even after careful thought, this is the only scenario that I feel is stopping etcd team from refreshing using SRV.

Dont want to sound pushy, sorry, still feel that this is not a common case and can be handled by providing a flag whether to autoRefresh proxy to cluster mapping or not, or by bootstrapping with a different dns domain.

Compare it to the advantage it would give when a cluster is completely replaced, none of the proxies/apps requires manual intervention of stop, delete data-dir, restart.

Amazing work done guys, respect your opinion, just wanted to present a point that this problem has a solution (which fits well for proxy and not for reconfig cluster itself).

Cheers
