### ISSUE TITLE
treating applied entries in v3 KV as nop is a little weird

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3761]
I find treating all operations as nop in v3 KV is a little weird. If we apply a transaction with compare in etcdserver apply loop, it relies on the return value of the operation to decide the path, so it may execute in different path (success/failure) with different operations. But it doesn't affect the correctness because apply result is not used at all.

from https://github.com/coreos/etcd/pull/3746#issuecomment-151376068

**Comment by xiang90** [comment]
I am working on this one. This requires some work...

**Comment by xiang90** [comment]
Fixed by #4908
