### ISSUE TITLE
etcd fatal with `storage: cannot commit tx (tx closed)`

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3773]
This is a 3-member cluster, and 2 of them are alive. When writing keys into the cluster, one member fatals with this log:

```
2015-10-29 06:20:37.104497 W | etcdserver: cannot get the version of member 651d96b5b5f28e25 (Get http://10.240.0.8:2380/version: dial tcp 10.240.0.8:2380: getsockopt: connection refused)
2015-10-29 06:20:40.923310 I | etcdserver: start to snapshot (applied: 751677, lastsnap: 741645)
2015-10-29 06:20:40.953893 I | etcdserver: saved snapshot at index 751677
2015-10-29 06:20:40.954225 I | etcdserver: compacted raft log at 746677
2015-10-29 06:20:41.027386 I | storage: cannot commit tx (tx closed)
```

**Comment by xiang90** [comment]
Can you try to reproduce this issue?

**Comment by jonboulle** [comment]
```
2015-10-29 06:20:41.027386 I | storage: cannot commit tx (tx closed)
```
`storage` here indicates the V3 backend; the V2 backend is `store`

**Comment by xiang90** [comment]
@yichengq Ping on this one. Can you please try to reproduce it?

**Comment by yichengq** [comment]
The way to reproduce it:
1. start 3-member cluster with member A,B,C
2. stop B
3. propose 20000 requests to the cluster
4. restart B, and B is recovered from incoming snapshot
5. stop A, C
6. restart A and let B becomes the leader
7. propose requests to B
8. B fatal

The root cause is the `kv` variable in `snapshotStore` is not updated in time when recovering from incoming snapshot, and keeps `kv` as old closed KV storage. So when that member wants to create snapshot for slow follower, it will commit to a closed KV storage. I could write a patch for it.

**Comment by yichengq** [comment]
When fixing the problem, it turns out that `snapshotStore` needs to obey some rules:
1. stop using and creating snapshot before KV is closed(https://godoc.org/github.com/boltdb/bolt#DB.Close)
2. cannot create unless its kv var is updated to the new one

**Comment by xiang90** [comment]
> 2. cannot create unless its kv var is updated to the new one

I think this is exact the same as 1? No?

**Comment by yichengq** [comment]
This means that snapshotStore still cannot create snapshot after KV is closed. It has to wait new kv is set before new creation.

**Comment by yichengq** [comment]
After discussion with xiang, `stop using and creating snapshot before KV is closed` is a separate problem. So I open a new issue for it. This issue will only focus on update snapshot.kv var correctly.
