### ISSUE TITLE
Rapid leader elections and request timeouts causing write failures

### ISSUE THREAD

**Issue by jenspinney** [coreos/etcd#3779]
Hello,

While running ETCD in the Diego project of Cloud Foundry, we've noticed problems when we insert many records into the store. We've seen the ETCD nodes apparently failing to communicate with each other and rapidly increasing the raft term. During these time periods, some writes fail.

In the logs, we see many messages like:

```
2015/10/29 18:56:40 etcdhttp: got unexpected response error (etcdserver: request timed out)
```

We've created a small executable that reproduces the issues we're seeing on our environment, and have created a repo with that source code and a fuller description of our environment: https://github.com/jenspinney/etcdstress

Would you be able to take a look and let us know if this repros in your environment? This is causing us a lot of problems at the moment when we increase the amount of data we store in ETCD.

Let us know if you need other information. Thank you!

@jenspinney & @andrew-edgar

**Comment by yichengq** [comment]
@jenspinney What is the average size of the record that is stored into etcd? I see it says that it meets the degration when having 120K record in the cluster, but have no idea about the size.

Which etcd version are you running? The latest 2.2 version is recommended.

We do some memory benchmark for 2.2, and it gives some lights about the usage: https://github.com/coreos/etcd/blob/master/Documentation/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md

BTW, we are developing v3 to address data scalability problem. We plan to support 1million entries in etcd store.

**Comment by jenspinney** [comment]
Hi @yichengq,

Each record we're inserting in our repro setup is about 550 bytes.

We're not using the latest ETCD (I believe we're using < v2), but I'll get back to you on the exact version.

**Comment by jenspinney** [comment]
@yichengq,

I double checked, and we're using v2.1.1.

**Comment by jenspinney** [comment]
@yichengq,

In the document you linked to, what does "data size threshold" refer to? Is that the total size of everything in the ETCD store? 48 MB seems small for that, but I'm not sure what else it would refer to.

Does the table at the bottom of that document mean "if you have <key number> keys, with <value bytes> bytes in each, we recommend you only have <suggested data threshold> in total data stored by etcd"?

**Comment by xiang90** [comment]
@jenspinney Do you run etcd with all your cores? Or just one core? By default, etcd 2.1.1 will start with 1 core. We can also try to reproduce your issue. 

> 48 MB seems small for that, but I'm not sure what else it would refer to.

Yes. etcd2 was designed for storing a small amount of data. In your setup, I think etcd should be able to hold 100MB or so. 

We are working on a new disk backend and v3 API, which can enable you to store million of keys and xGB data into etcd.

**Comment by jenspinney** [comment]
Hi @xiang90,

We are setting GOMAXPROCS to 16 (the number of cpus on our vm). We're starting to think this might be more related to slow disk i/o, and we're playing around with switching it from a magnetic disk to an SSD.

**Comment by xiang90** [comment]
@jenspinney OK. Let me know the result. We could help to dig into that too when you have more information.

**Comment by jenspinney** [comment]
@xiang90,

We experimented with different disk types and speeds, and while certain volume types were able to increase the speed of etcd, we didn't see an obvious improvement in the number of rejected insertions or the rapid elections.

We set up prometheus to explore various metrics, but we didn't see anything obvious (to our eyes) that would explain the problems. We did see "etcd_server_proposal_failed_total" skyrocket, but I'm not sure if that tells us much.
![screen shot 2015-11-02 at 5 03 44 pm](https://cloud.githubusercontent.com/assets/3200507/10898894/18ce50ea-8184-11e5-9f0a-5115a4a778b2.png)

Any specific metrics you would recommend we look at? We tried looking at all of them, but we might not have had the context to notice something abnormal.

It could be that we're just hitting the data size threshold, and there's no getting around that. Do you know when v3 is supposed to come out?

Thanks,
@jenspinney & @SocalNick

**Comment by gyuho** [comment]
@jenspinney Kindly ping. Sorry to get back to this late. I am trying to take another look
at this issue. Are you still seeing this error? Was there any network partition or any kind
of network issue that might have made one node lose its leader (as seen in your log)?

I have seen similar case in recent functional-tests https://github.com/coreos/etcd/issues/4855#issuecomment-200970476, but it's resolved. We are pretty confident now that this won't happen in v3, of which alpha release is coming
in a few weeks.

If you can provide simpler way to reproduce this issue, it would be very helpful. Thanks!

**Comment by xiang90** [comment]
@gyuho I think there is a reproduce instruction: https://github.com/jenspinney/etcdstress. Have you tried it?

**Comment by gyuho** [comment]
@xiang90 I will try that now. Thanks.

**Comment by gyuho** [comment]
I tried with master branch with https://github.com/jenspinney/etcdstress:

- [etcd-1-database.txt](https://github.com/coreos/etcd/files/209372/etcd-1-database.txt)
- [etcd-2-database.txt](https://github.com/coreos/etcd/files/209373/etcd-2-database.txt)
- [etcd-3-database.txt](https://github.com/coreos/etcd/files/209375/etcd-3-database.txt)
- [etcd-stress.txt](https://github.com/coreos/etcd/files/209374/etcd-stress.txt)

Works fine on GCE.

**Comment by xiang90** [comment]
@gyuho 

The initial tesing env is

> We run a 3-node ETCD cluster
We have both peer and client/server SSL enabled.
Our election timeout is 2000ms and our hearbeat interval is 200ms.
Our ETCD nodes are hosted on c4.4xlarge VMs in AWS (30 GB memory, 16 cores), each using a 10gb magnetic disk for the ETCD store.

What is your testing env?

**Comment by gyuho** [comment]
@xiang90 

- 8 vCPUs + 16GB Memory + 375GB local SSD (SCSI)
- Ubuntu 15.10
- Go 1.6 with etcd master branch as of testing date
- all in the same zone

**Comment by xiang90** [comment]
@jenspinney It seems that we are not able to reproduce the problem with similar setup. Is there anything we missed?

**Comment by gyuho** [comment]
@jenspinney I just tried again with the same configuration in etcd v2.1.1 and go 1.4, but I don't see errors.

Please try again (preferably with latest version), and feel free to reopen if you still have the same issue.

Thanks.

**Comment by gyuho** [comment]
And just to note,

in our internal benchmark with etcd **v2** (latest version), we found putting more than 400K keys (8-byte key) in very fast rate could trigger leader elections--200K keys are handled with no problem.

**Comment by xiang90** [comment]
@gyuho That result matches the limitation here: https://github.com/coreos/etcd/blob/master/Documentation/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md.

But this can vary from configuration to configuration.
