### ISSUE TITLE
Cannot remove initial permission for guest role

### ISSUE THREAD

**Issue by msimon** [coreos/etcd#3784]
```
$> etcdctl -u root:root role get guest
Role: guest
KV Read:
	*
KV Write:
	*
$> etcdctl -u root:root role revoke guest -path=/* -readwrite
auth: Role not updated. Use grant/revoke to update the role.

$> etcdctl -u root:root role grant guest -path=* -readwrite
Not canonical path; please use `-path=/*`
```
The issue seems to be the initial permission are * and not /*, and * cannot be edited.
```
> etcdctl -u root:root role grant guest -path=/* -readwrite
Role guest updated

> etcdctl -u root:root role get guest
Role: guest
KV Read:
	*
	/*
KV Write:
	*
	/*

$> etcdctl -u root:root role revoke guest -path=/* -readwrite
Role guest updated.

$> etcdctl -u root:root role get guest
Role: guest
KV Read:
	*
KV Write:
	*
```
I don't see how I can remove permission for *.

I tested on etcd 2.2.0 and etcd 2.2.1.

Thanks

**Comment by yichengq** [comment]
We use canonical path at https://github.com/coreos/etcd/blob/master/pkg/pathutil/path.go#L9 to sanitize the read/write permission path. But the predefined guest role doesn't follow the format: https://github.com/coreos/etcd/blob/master/etcdserver/auth/auth.go#L62

We need to fix the predefined roles.
