### ISSUE TITLE
improve warning-level message drop log

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3806]
A slow-snapshot-recovery follower acts like this:

```
2015-11-03 13:07:29.926853 W | rafthttp: dropped MsgHeartbeatResp to 8211f1d0f64f3269 since pipeline's sending buffer is full
2015-11-03 13:07:29.926912 W | rafthttp: dropped MsgAppResp to 8211f1d0f64f3269 since pipeline's sending buffer is full
2015-11-03 13:07:29.927124 W | rafthttp: dropped MsgProp to 8211f1d0f64f3269 since pipeline's sending buffer is full
2015-11-03 13:07:31.789354 W | rafthttp: dropped MsgHeartbeatResp to 8211f1d0f64f3269 since pipeline's sending buffer is full [merged 45 repeated lines in 1.862264185s]
2015-11-03 13:07:31.789416 W | rafthttp: dropped MsgAppResp to 8211f1d0f64f3269 since pipeline's sending buffer is full [merged 17 repeated lines in 1.862202598s]
```

Possible problems:
1. users probably cannot understand what MsgXXX means
2. no instructions for the expected behavior for it

from https://github.com/coreos/etcd/pull/3783#issuecomment-153805331

**Comment by gyuho** [comment]
@yichengq I first approached by describing the `raftpb.MessageType` in the logging message
but we think it makes debugging too verbose. If we want debugging or warning messages
to be more helpful, we could create a wiki for debugging and improve the documentation.

For this issue, I will try to improve the raft documentation that people can refer while debugging
(e.g. A `MessageType` means B).

**Comment by yichengq** [comment]
@gyuho I think for this warning messages to be more useful, it could tell users that raft internal messages are dropped due to XXX, and prints out detailed info in debug-level logging.

MsgProp is a special type. It is used to redirect proposals. If one MsgProp is dropped, the corresponded user request cannot finish. So users may want to know about the dropping status of MsgProp. But we may add retry mechanism for MsgProp in the future, so it may be ok to just categorize it into raft internal messages.

For user instructions, I would expect users to notice that either etcd is under high load or network doesn't work well.

**Comment by gyuho** [comment]
I see what you mean. I will try again tomorrow. Thanks!

**Comment by gyuho** [comment]
Can somebody close this? I think this can be closed for now from https://github.com/coreos/etcd/pull/3890. Thanks,

**Comment by yichengq** [comment]
@gyuho Thanks for the improvement! :+1:

**Comment by gyuho** [comment]
Thanks!

On Sun, Nov 22, 2015, 11:18 Yicheng Qin <notifications@github.com> wrote:

> @gyuho <https://github.com/gyuho> Thanks for the improvement! [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/etcd/issues/3806#issuecomment-158790648>.
>
-- 
Sincerely,
Gyu-Ho Lee
