### ISSUE TITLE
etcd v2.2.1 and journald 225 doesn't recognize log tag

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#3828]
CoreOS 845.0.0

```
etcd Version: 2.2.1
Git SHA: 75f8282
Go Version: go1.5.1
Go OS/Arch: linux/amd64
```

```sh
$ journalctl -t etcd2
-- No entries --
$ journalctl -t etcd 
-- No entries --
```

This command still works `journalctl -u etcd2` but it doesn't show logs which were shown with `-t` flag. Also `journalctl _EXE=/usr/bin/etcd2` works but it is too long to type.

**Comment by yichengq** [comment]
@kayrus It has been reported at https://github.com/coreos/bugs/issues/373#issuecomment-150679781 . I see that @jonboulle has fixed the issue in capnslog. etcd needs to update deps then.

**Comment by jonboulle** [comment]
I'll take this.
