### ISSUE TITLE
Very basic built-in fileserver?

### ISSUE THREAD

**Issue by xaduha** [coreos/etcd#3831]
Just running this idea up the flag pole, since etcd already has "net/http" as a dependency.

Optional and off by default. This https://github.com/golang/go/wiki/HttpStaticFiles and a couple of flags for specifying a folder and a port should do it.

**Comment by philips** [comment]
what is a use case?

**Comment by xaduha** [comment]
Serving ACIs, for example. Static html pages with ACI discovery meta tags. Just static files in general.

In a cluster mode it wouldn't be half-bad too, if files are to be synced somehow.

**Comment by xiang90** [comment]
@xaduha etcd is not designed for serving the large amount of data. It is designed for serving meta data and doing coordination. You can build another layer on top of etcd to serve static file in a consistent manner and you can control the replication pretty easily by using 2PC with the help of etcd.
