### ISSUE TITLE
Simple DNS A record discovery

### ISSUE THREAD

**Issue by errordeveloper** [coreos/etcd#3832]
Having assumed an overlay network, one can simply use default ports and lookup cluster members as DNS A record, without having to use SRV. This would make etcd extremely easy to deploy (and scale) on Weave.

**Comment by philips** [comment]
I don't follow. Can you provide an example.

**Comment by errordeveloper** [comment]
As an alternative to current SRV discovery...

**Comment by jonboulle** [comment]
Well, why can't you do this today by specifying (resolvable-by-DNS) hostnames instead of IP addresses?

**Comment by errordeveloper** [comment]
Sure, but what I am talking about is A records with multiple answers, like
the SRV that is currently supported.

**Comment by xiang90** [comment]
@errordeveloper Why not just SRV? DNS A record is not designed for the purpose you want to achieve here I think.

**Comment by errordeveloper** [comment]
Well, SRV is only needed when port number has to be discovered, if default
ports are okay to use (like on Weave Net), there is no need to use SRV.

**Comment by xiang90** [comment]
My question is why SRV is difficult for you but A record is not? More steps?

**Comment by xiang90** [comment]
I do not see a clear need here. We do not want to add endless discovery mechanisms into core etcd.

We are considering adding `etcd init` and `etcd dicsovery` subcommand. So users can easily add whatever discovery mechanism they want into etcd subcommands.

**Comment by xiang90** [comment]
@errordeveloper https://github.com/coreos/etcd/issues/5208
