### ISSUE TITLE
client authentication without activating HTTPS ?

### ISSUE THREAD

**Issue by sterfield** [coreos/etcd#3840]
Hi,

I'm doing some tests around ETCD and more specifically with the client authentication.

## Context
ETCD version : 2.2.1
OS : Debian stable

## Steps to reproduce

I'm trying to do this:

* 3 etcd nodes in the same subnet, peer connection is http
* one load balancer that is doing HTTPS termination, then round-robin on each 3 node in http, port 2379
* each etcd node have the client authentication activated

My current configuration is like this:
````
#!/bin/bash
export ETCD_NAME=$(hostname)
export ETCD_INITIAL_ADVERTISE_PEER_URLS="http://<PRIVATE_IP>:2380"
export ETCD_ADVERTISE_CLIENT_URLS="https://etcd.mydomain.example.com:443"
export ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
export ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
export ETCD_DATA_DIR="/opt/etcd"
export ETCD_DISCOVERY_SRV="mydomain.example.com"
export ETCD_CLIENT_CERT_AUTH="true"
export ETCD_TRUSTED_CA_FILE="/tmp/etcd-ca.crt"
# export ETCD_CERT_FILE="/tmp/etcd-test.crt"
# export ETCD_KEY_FILE="/tmp/etcd-test-free.key"
export ETCD_HEARTBEAT_INTERVAL="500"
export ETCD_ELECTION_TIMEOUT="20000"
exec /usr/local/bin/etcd
```

## Actual results

The cluster start just fine, but it doesn't seems to activate the client authentication.

A quick curl on localhost on /v2/members shows some information.

However, if I activate the HTTPS transport by:

* changing client listen url from http to https
* setting a cert file
* setting a key file

Then I can see in the log:
```
2015-11-10 00:13:57.736042 I | etcdmain: clientTLS: cert = /tmp/etcd-test.crt, key = /tmp/etcd-test-free.key, ca = , trusted-ca = /tmp/etcd-ca.crt, client-cert-auth = true
2015-11-10 00:13:57.745220 I | etcdmain: listening for client requests on https://0.0.0.0:2379
```

And then the curl on localhost failed as expected, with bad certificate alert.

## Expected results

Is there a way to activate the client authentication without the HTTPS transport ? It seems that some work has been done in #2499 to split the two cases, so it seems strange that I can't activate one feature without the other.

Or maybe I'm doing something plain stupid ?

Either way, thanks for your help !

**Comment by yichengq** [comment]
@sterfield I would recommend you to read our security doc first, and understand it totally before any discussion: https://github.com/coreos/etcd/blob/master/Documentation/security.md

/cc @gtank

**Comment by sterfield** [comment]
@yichengq Thanks for your answer.

I did read the security doc, and re-read it again after your message, just to be sure. I still don't know what could be my error (if any).

There's two mention in the security doc:
* activate the HTTPS transport
* activate the HTTPS transport and the client authentication

I understand them both, and I managed to make both works. However, this is not what I want to do. I want to do client authentication *without* activating the HTTPS transport.

As I understand it, it's possible to verify the client certificate through plain HTTP. However, if I activate the `--client-cert-auth` and `--trusted-ca-file` but keep the listen URL in HTTP, the client authentication is not working.

The documentation is not explicit about this specific case. It's not said that it's supported nor unsupported, but the different set of flags allow to do it.

Thanks,

**Comment by sterfield** [comment]
Quick discussion with a colleague, and he thinks that the client certificate authentication is done by the SSL layer.
That would explain why without HTTPS, etcd is not doing client certificate authentication.

If that's confirmed, then I have my answer ("it's not possible") and the ticket can be closed.

Thanks,

**Comment by gtank** [comment]
@sterfield Yes, as far as I know it's not possible to do what you want. In Go, the TLS connection is the only part that pays attention to client certs at all.

The way this is usually handled is by terminating the SSL connection at a load balancer and injecting HTTP headers that contain the information from the client cert. [This post](http://serverfault.com/questions/437705/is-it-possible-to-do-client-certificate-authentication-without-running-https-on) goes into a little more detail.

**Comment by sterfield** [comment]
That's what I feared.

Many thanks for your explanation and your link.

Best,
