### ISSUE TITLE
user guide outdated

### ISSUE THREAD

**Issue by HuKeping** [coreos/etcd#3843]
Since the latest release is no longer v2.0.8, I hope someone could help update the docs ;)

 https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md#etcd0

**Comment by gyuho** [comment]
@HuKeping I updated [the doc](https://github.com/coreos/etcd/pull/3844/files) as you suggested, to pull etcd from the latest images. Please try (now merged in master branch) and let me know if you find any other issues.

I tried it and it worked for me. Thanks,

**Comment by HuKeping** [comment]
Wow, thanks for the quickly fixing!

**Comment by gyuho** [comment]
Np!
