### ISSUE TITLE
etcd v2.2.1 with enabled authentication allows modify any key without credentials

### ISSUE THREAD

**Issue by weldpua2008** [coreos/etcd#3846]
Hi,

I created a 3 node cluster.
```
etcdctl user add root 
etcdctl user add df
etcdctl role add dfrole
etcdctl role grant dfrole -path '/client/*' -readwrite
etcdctl role grant dfrole -path '/host/*' -read
etcdctl auth enable

etcdctl -u root:rootpw role get df

curl -u root:rootpasswd -L http://127.0.0.1:2379/v2/keys/host/xx -XPUT -d value="Root Some val"
```
it's ok
```
curl -u df:dfpasswd -L http://127.0.0.1:2379/v2/keys/host/xx -XPUT -d value="Some val"
```
errorCode: 110

```
curl -u df:dfpasswd -L http://127.0.0.1:2379/v2/keys/host/xx
```
returns Root Some val

```
curl  -L http://127.0.0.1:2379/v2/keys/host/xx -XPUT -d value="Some val"
```
changes value

How to avoid that non-authenticated user can change values? **Or it's a bug**?

**Comment by raoofm** [comment]
@weldpua2008 as mentioned in the [docs](https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#roles)

>There is also a special GUEST role, named 'guest'. These are the permissions given to unauthenticated requests to etcd. This role will be created automatically, and by default allows access to the full keyspace due to backward compatibility. (etcd did not previously authenticate any actions.). This role can be modified by a ROOT role holder at any time, to reduce the capabilities of unauthenticated users.

guest role has read * and write * access.

so when you are passing a user in the curl statement with a -u flag, this means that you want the user to be authenticated. But in the last case where you are not passing any user, then etcd by default uses guest role and provides read and write access to the full store.

to prevent this, just follow the [doc](https://github.com/coreos/etcd/blob/master/Documentation/auth_api.md#modify-guest-role-revoke-write-permission) and disable guest role

Create a file guest.json with below content
{"role":"guest","revoke":{"kv":{"read":["*"],"write":["*"]}}}

curl -u root:rootpasswd -L http://127.0.0.1:2379/v2/auth/roles/guest -XPUT -d "@guest.json"

**Comment by jonboulle** [comment]
thanks @raoofm !
@weldpua2008 closing as that should have addressed your question - please re-open if not.

**Comment by DeamonMV** [comment]
Hi. i got some problem, but i could not find role user 
what do i have
```
# etcd --version                 
etcd Version: 3.2.9                                
Git SHA: f1d7dd8                                   
Go Version: go1.8.4                                
Go OS/Arch: linux/amd64
```
etcd in cluster mode
```
 # etcdctl member list  --endpoints="http://192.168.1.226:2379"    
353fa030a31e7ba2, started, etcd-02, http://192.168.1.227:2380, http://192.168.1.227:2379           
e04c798a70fa518e, started, etcd-01, http://192.168.1.226:2380, http://192.168.1.226:2379      
fc14940bd3e08a50, started, etcd-03, http://192.168.1.228:2380, http://192.168.1.228:2379 
```
auth was enabled

i have created guest.json file and run command

```
#  curl -u root:passwd -L http://192.168.1.227:2379/v2/auth/roles/guest -XPUT -d "@guest.json"                                                                                           
{"message":"auth: Role guest does not exist."}
```

etcdctl show me the same thing
```
# etcdctl role list --user root  --endpoints="http://192.168.1.226:2379"   
Password:
root  
```
and there are only user root
```
# etcdctl user list --user root  --endpoints="http://192.168.1.226:2379"                                                                                                                   
Password: 
root  
```
