### ISSUE TITLE
extensive CPU usage when gRPC clients timeout

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3859]
I create 5000 clients and 10 stream per clients to an etcd server. And then I close all gRPC connection at client side. After a while, the server starts to kill the streams and the CPU usage starts to increase. I have not investigated more into this issue at all.

**Comment by xiang90** [comment]
It turns out that this is not a grpc issue. Watch cancellation at etcd side uses most of the CPU. I am still investigating

**Comment by xiang90** [comment]
OK. Cancellation is O(N^2) (N is the watchers on the same key). https://github.com/coreos/etcd/blob/master/storage/watchable_store.go#L208

I guess we should avoid the extensive copy at least.

**Comment by gyuho** [comment]
Should we try map on synced?

**Comment by xiang90** [comment]
@gyuho yes. you should. but be careful about memory usage implication.

**Comment by gyuho** [comment]
Sure I will try that with comparison with current implementation. Thanks.

**Comment by xiang90** [comment]
Fixed by https://github.com/coreos/etcd/pull/3899
