### ISSUE TITLE
Proxy cannot recover after hard reset

### ISSUE THREAD

**Issue by zadoryzsolt** [coreos/etcd#3861]
Hello,

I have a standalone etcd cluster and a proxy on separate virtual machines.
When I make a hard reset on both machines the cluster can recover but the proxy cannot.
It seems that it leaves the cluster file in the data dir unreadable or empty.

It would be really nice if the proxy could recover as well, not just the cluster.

Etcd version: 2.2.1
Error from journal: "etcdmain: unexpected end of JSON input"

**Comment by xiang90** [comment]
@zadoryzsolt Right. The proxy is not that solid right now. We should fix this issue.

**Comment by jonboulle** [comment]
@gyuho mind taking a look at this?

**Comment by gyuho** [comment]
@jonboulle Sure, I will work on this.

@xiang90 Current proxy implementation stores `initial-cluster` information in JSON format in text format in data directory. So as far as I know, this is how proxy comes back if shut-down. It's not clear to me what @zadoryzsolt means by `It seems that it leaves the cluster file in the data dir unreadable or empty.`?

**Comment by xiang90** [comment]
@gyuho When updating the file, we should first write a tmp file then rename it. Direct writing to the file can cause half written issue when there is a hard shutdown.

**Comment by gyuho** [comment]
@xiang90 +1. Good idea. I will try that. Thanks,

**Comment by gyuho** [comment]
@xiang90 
https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L409-L414

**Comment by xiang90** [comment]
@gyuho I did not remember we have already done this... Probably you need to find other potential cause?

**Comment by gyuho** [comment]
Sure I will try to replicate this. Thanks!

**Comment by xiang90** [comment]
any progress on this one?

**Comment by gyuho** [comment]
I couldn't reproduce this yet :(  @zadoryzsolt could you be more specific about `data dir unreadable or empty`?

@xiang90 If an user sets this https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L357 as temp directory and reboots its machine, the files will be gone. How about setting this `cfg.dir` to local path that won't be deleted even after machine reboot?

**Comment by gyuho** [comment]
@zadoryzsolt could you share your configurations to set up your etcd cluster, so that I can reproduce the issue?

**Comment by zadoryzsolt** [comment]
I cannot share the full configuration, but this should be sufficient to reproduce the issue. What I meant about the data dir is that with the attached proxy settings the /var/lib/etcd/proxy.etcd/proxy/cluster file is empty when I open it in a text editor after a hard reset. It should contain the initial-cluster info in JSON as you said, but it does not.

[etcd-cluster.conf.txt](https://github.com/coreos/etcd/files/50590/etcd-cluster.conf.txt)
[etcd-proxy.conf.txt](https://github.com/coreos/etcd/files/50591/etcd-proxy.conf.txt)

**Comment by xiang90** [comment]
@zadoryzsolt Fixed now. Thanks for reporting!
