### ISSUE TITLE
v3 benchmark tool

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3863]
- [x] refactor existing code
- [x] merge in watch memory bench code

-------- 

Brief design summary / implementation status

### Global options
- [x] `--conns` - Number of connections to make to the etcd cluster. If a cluster with multiple members is specified, the connections will be evenly spread across the members (avoid conn is smaller than the number of members).
- [x] `--clients` - Number of clients that share one connection

##### Options
- [x] `--total` - Total number of put requests to be issued
- [x] `--key-size` - Key size of put requests
- [x] `--value-size` - Value size of put requests
- [x] `--async` - If async is true, the client will not wait for the reply before issuing the next put request
- [x] `--key-n` - If key-n is greater than 0, then at most key-n keys will be created by put requests. Or each put request creates a new key.

##### Output:
- avg rate
- avg latency
- latency histogram
- any errors

##### Options
- [x] `--total` - Total number of range requests to be issued
- [x] `--max-key-range` - The max key range to be requested.
- [x] `--min-key-range` - The min key range to be requested.

##### Output
- avg rate
- avg latency
- latency histogram
- any errors

##### Options
- [x] `--streams` -Number of streams per clients
- [x] `-n`  - Total number of watch requests to be issued
- [x] `--max-key-range` - The max key range to be requested.
- [x] `--min-key-range` - The min key range to be requested.

**Comment by gyuho** [comment]
@xiang90  Could you explain what we mean by `max-key-range`, `min-key-range` ? `range` command already sets `range key [end-range]`, where first argument is the minimum key and last argument is the maximum key of the range. So I think it's already done in `range` benchmark command. Did you mean something else?  Thanks.

**Comment by xiang90** [comment]
@gyuho We want bench watch to be able to watch on different keys, not just one key.

**Comment by gyuho** [comment]
Ok, then how about:

```go
	rangeCmd.Flags().IntVar(&minKeyRange, "min-key-range", 0, "The min key range to be requested.")
	rangeCmd.Flags().IntVar(&maxKeyRange, "max-key-range", 1024*1024, "The max key range to be requested.")
	rangeCmd.Flags().IntVar(&numKeys, "number-keys",  1, "The number of keys that range would watch.")
```

Then the benchmark auto-generates(puts) keys depending on the range (before it measures the range performance), so that user can specify the length of key and `numKeys` to send range requests to.

**Comment by gyuho** [comment]
Talked with Xiang. Will try similar thing as `range key [end-range]` for `watch`. Thanks.

**Comment by gyuho** [comment]
@xiang90 Current watch benchmark already does watch on different keys:

1. https://github.com/coreos/etcd/blob/master/tools/benchmark/cmd/watch.go#L69
2. https://github.com/coreos/etcd/blob/master/tools/benchmark/cmd/watch.go#L76-L79

```go
watched := make([]string, watchedKeyTotal)
for i := range watched {
	watched[i] = string(mustRandBytes(32))
}
```

So that it automatically puts random keys on watchable store and watch those random keys for testing. 

I think we should do the same thing in `range`. Current `range` benchmark only ranges on one or two keys.

Thanks.
