### ISSUE TITLE
Does the etcdctl need insecure flag?

### ISSUE THREAD

**Issue by qq690388648** [coreos/etcd#3878]
I set up an etcd server with <code>trusted-ca-file</code> flag and other flags about security mentioned in https://github.com/coreos/etcd/blob/master/Documentation/security.md, and it worked well with <code>curl</code>, but when I used etcdctl, it reported <code>etcd cluster is unavailable or misconfigured</code>.
I thought it is because of the certificate I used is self-generated, so I thought <code>etcdctl</code> need a flag like <code>insecure</code> that can skip the validation of server's certificate.
Or is there something wrong with my thought? please tell me.

**Comment by gyuho** [comment]
Can you provide more detail about how you set up etcd in first place? `etcd` or `etcdctl` does not have `insecure` flag, as far as I know. Did you try `etcdctl -h`? It will show you how to specify your cert/ca/key file.

**Comment by xiang90** [comment]
@qq690388648 For curl, you added the -k flag?

**Comment by qq690388648** [comment]
@gyuho  @xiang90 
Sorry for my lazy..
I set up the <code>etcd</code> with command below:
``` shell
etcd -name infra0 -initial-advertise-peer-urls http://192.168.99.240:2380 -listen-peer-urls http://192.168.99.240:2380 -listen-client-urls https://192.168.99.240:2379,https://127.0.0.1:2379 -advertise-client-urls https://192.168.99.240:2379 -initial-cluster-token etcd-cluster-1 -initial-cluster infra0=http://192.168.99.240:2380 -initial-cluster-state new -client-cert-auth -trusted-ca-file=/home/docker/ssl/ca.crt -cert-file=/home/docker/ssl/server.crt -key-file=/home/docker/ssl/server.key
```
And use <code>curl</code> to access <code>etcd</code>:
``` shell
curl --insecure --cacert /home/docker/ssl/ca.crt --cert /home/docker/ssl/ca.crt --key /home/docker/ssl/ca.key -L https://127.0.0.1:2379/v2/keys/foo -XGET
```
The <code>etcd</code> return:
``` json
{"action":"get","node":{"key":"/foo","value":"bar","modifiedIndex":9,"createdIndex":9}}
```
But when I use <code>etcdctl</code> to access <code>etcd</code>:
``` shell
etcdctl --peers=https://192.168.99.240:2379 --ca-file=/home/docker/ssl/ca.crt --cert-file=/home/docker/ssl/ca.crt --key-file=/home/docker/ssl/ca.key ls
```
The <code>etcd</code> return:
``` logs
Error:  client: etcd cluster is unavailable or misconfigured
```

**Comment by qq690388648** [comment]
Oh, sorry for my misunderstanding of the <code>--ca-file</code> flag of <code>etcdctl</code>, setting this flag to the certificate of server can solve the security problem introduced by self signed certificate.
I will close this issue soon, thanks again, @gyuho @xiang90

**Comment by gyuho** [comment]
Awesome! Thanks

**Comment by qq690388648** [comment]
New Development。

The reason for the <code>curl</code> can access <code>etcd</code> successfully but the <code>etcdctl</code> cannot is that the self signed certificates I used is not safe enough and <code>curl</code> ignores it but the <code>etcdctl</code> does not.

Below is the steps to generating safe certificates(copyed from document of (kubernetes)[https://github.com/kubernetes/kubernetes/blob/master/docs/admin/authentication.md#creating-certificates] and modified).

Firstly, you should modify <code>/etc/ssl/openssl.cnf</code>: set the <code>basicConstraints</code> flag to `CA:TURE` and add `subjectAltName = IP:<MASTER_IP>` under `v3_ca`.

Then you can generate certificates following below steps.
```` shell
    #1.	Generate a ca.key with 2048bit 
    openssl genrsa -out ca.key 2048
    #2.	According to the ca.key generate a ca.crt. (-days set the certificate effective time). 
    openssl req -x509 -new -nodes -key ca.key -subj "/CN=${MASTER_IP}" -days 10000 -out ca.crt
    #3.	Generate a server.key with 2048bit 
    openssl genrsa -out server.key 2048
    #4.	According to the server.key generate a server.csr. 
    openssl req -new -key server.key -subj "/CN=${MASTER_IP}" -out server.csr
    #5.	According to the ca.key, ca.crt and server.csr generate the server.crt.
    openssl x509 -req -days 1000 -in server.csr -signkey server.key -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -extensions v3_req -extensions v3_ca -extfile /etc/ssl/openssl.cnf
    #6.	View the certificate. 
    openssl x509 -noout -text -in ./server.crt
````
Then run `etcd` with below command:
```` shell
    etcd -name infra0 -initial-advertise-peer-urls http://192.168.99.240:2380 -listen-peer-urls http://192.168.99.240:2380 -listen-client-urls https://192.168.99.240:2379,https://127.0.0.1:2379 -advertise-client-urls https://192.168.99.240:2379 -initial-cluster-token etcd-cluster-1 -initial-cluster infra0=http://192.168.99.240:2380 -initial-cluster-state new -client-cert-auth -trusted-ca-file=ca.crt -cert-file=server.crt -key-file=server.key
````
Now we can access `etcd` with below command:
```` shell
    etcdctl --peers=https://192.168.99.240:2379 --ca-file=ca.crt --cert-file=ca.crt --key-file=ca.key ls
````
Notice that the `--ca-file` flag of `etcdctl` is `ca.crt`, not `server.crt`.
