### ISSUE TITLE
'Error: client: no endpoints available' when etcdctl talks to etcd

### ISSUE THREAD

**Issue by dalanlan** [coreos/etcd#3886]
- Error msg

 ```
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).
Error:  client: no endpoints available
```
- etcd flags

single etcd 2.2.1 
```
ETCD_OPTS="-name infra -listen-client-urls http://0.0.0.0:4001 -advertise-client-urls http://127.0.0.1:4001"
```

I was thinking `http://0.0.0.0:4001` is the so-called involved non-published client endpoint, apparently not in this case(`http://127.0.0.1:2379,http://127.0.0.1:4001` instead), which seems confusing to me. 
Could you please kindly clarify this for me?

**Comment by xiang90** [comment]
@dalanlan 

> I was thinking http://0.0.0.0:4001 is the so-called involved non-published client endpoint,

No. Please check the error message from etcdctl. It says `non-published client endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379).`

etcd should publish a reachable url rather than local loopback as you did. If you want to use localhost for some reason, please use no-sync.

**Comment by dalanlan** [comment]
yeah, indeed. 
What bothers me is that it's very likely (at least from the doc) `-listen-client-urls` is so-called flag that used here.

**Comment by dalanlan** [comment]
@xiang90 My humble thought is that if `--advertise-client-urls` has anything to do with this, it should not be considered as [a clustering flags](https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-advertise-client-urls).
