### ISSUE TITLE
Gauges about total key counters are always reporting 0

### ISSUE THREAD

**Issue by crisidev** [coreos/etcd#3888]
Hello, I am working on monitoring etcd using prometheus. I am currently using version 2.2.1, but all the gauge counters for key numbers are always returning 0. I have keys set by fleet and I have also tried to set keys manually, but the numbers are not changing.

Example:
```
# HELP etcd_storage_keys_total Total number of keys.
# TYPE etcd_storage_keys_total gauge
etcd_storage_keys_total 0
# HELP etcd_storage_put_total Total number of puts seen by this member.
# TYPE etcd_storage_put_total counter
etcd_storage_put_total 0
# HELP etcd_storage_range_total Total number of ranges seen by this member.
# TYPE etcd_storage_range_total counter
etcd_storage_range_total 0
# HELP etcd_storage_txn_total Total number of txns seen by this member.
# TYPE etcd_storage_txn_total counter
etcd_storage_txn_total 0
# HELP etcd_store_expires_total Total number of expired keys.
# TYPE etcd_store_expires_total counter
etcd_store_expires_total 468
```

The only counter reporting is the expired one.

Am I missing somenthing? From the code, I can see you are increasing these counters on put.

**Comment by crisidev** [comment]
After some digging, the problem is that storage metrics are updated just for v3 API. 

I think it would be really nice to have these values also for v2 API, which is the most used right now (AFAIK).

Something like 
```
# HELP etcd_v2_storage_keys_total Total number of keys (v2).
# TYPE etcd_v2_storage_keys_total gauge (v2)
etcd_v2_storage_keys_total 0
# HELP etcd_v2_storage_put_total Total number of puts seen by this member (v2).
# TYPE etcd_v2_storage_put_total counter (v2)
etcd_v2_storage_put_total 0
# HELP etcd_v2_storage_range_total Total number of ranges seen by this member (v2).
# TYPE etcd_v2_storage_range_total counter (v2)
etcd_v2_storage_range_total 0
# HELP etcd_storage_txn_total Total number of txns seen by this member. (v2)
# TYPE etcd_storage_txn_total counter (v2)
etcd_v2_storage_txn_total 0
# HELP etcd_v2_store_expires_total Total number of expired keys (v2).
# TYPE etcd_v2_store_expires_total counter (v2)
etcd_v2_store_expires_total 468
```

What do you think?

**Comment by xiang90** [comment]
@crisidev They are useful metrics for sure. So we added them to new store. We will not actively work on v2 store unfortunately. 

We will make the metrics more clear: https://github.com/coreos/etcd/issues/3833

**Comment by barakmich** [comment]
Look; we have tons of users on v2 -- I'm sitting next to @crisidev right now -- and they care about, you know, backwards compatibility.

v3 will be ready soon, sure, but it will be super useful for monitoring for current v2 users as they migrate  -- things like fleet, say. Adding them as tags (`{version="2"}`) means they can be deprecated as time moves on.

It'd be good to do. If it needs to be a PR from someone else, eg, "help wanted" tag, fine.

**Comment by crisidev** [comment]
I completely stand with @barakmich as this product is used by a lot of people, which might be not switching immediately to v3. Monitoring is nice and important guys ;)

**Comment by xiang90** [comment]
@barakmich We need to make the metrics clear (maybe adding tag or prefix). That includes in #3833.We do not need to care about backward compatibility right now since the whole metrics endpoint is still pretty experimental.

I am closing this since it is already covered by #3833. 

@crisidev Adding more metrics to v2 store is a totally separate issue. You probably should open up another issue for it.
