### ISSUE TITLE
kv.Close in apply loop may block on KV snapshot send

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#3891]
1. A as a leader starts sending snapshot to B
2. For some reason, C becomes leader now
3. C sent snapshot to B and makes progress with B
4. C starts sending snapshot to A
5. A needs to recover from incoming snapshot, but block because snapshot to B is still sending.

This should happen rarely in real life, but it deserves to be considered and prevented.

from https://github.com/coreos/etcd/issues/3773#issuecomment-157888741

**Comment by xiang90** [comment]
There are a few other issues that I am aware of:

1. the swap of newly recovered kv and old kv should be atomic since multiple routines might access it.

2. not only the snapshot store but also other struct like kv api should not use closed kv.

**Comment by yichengq** [comment]
> the swap of newly recovered kv and old kv should be atomic since multiple routines might access it.
not only the snapshot store but also other struct like kv api should not use closed kv.

ack. both of them are problems.

**Comment by xiang90** [comment]
Both of the issues are solved.

https://github.com/coreos/etcd/pull/4151
https://github.com/coreos/etcd/blob/59bf83c7f4086c5c31be202dfad1f925d9fa95c3/etcdserver/server.go#L617-L625
