### ISSUE TITLE
etcdv3: backup design plan

### ISSUE THREAD

**Issue by philips** [coreos/etcd#3896]
etcd's v2 storage is easy to backup because the snapshot is write once and the WAL is append only. So, a user can use tools like rclone, rsync, etc to backup etcd and know that they got a good backup. Moving forward with the new storage system do we need to write or document new tools?

**Comment by xiang90** [comment]
@philips Even for v2, we do not encourage people to write their own tool:

1. We are not ready to give them any file level guarantees at runtime (for example, etcd will hold a file lock or etcd will help to mark a removable file.). 

2. We want to wipe out the configuration for backup. Simply copy the file can be dangerous.

So people should use etcdctl backup. And we know a few people successfully using it. We do not have a plan to support "easy" backup yet.

/cc @colhom

**Comment by xiang90** [comment]
close in favor of https://github.com/coreos/etcd/issues/4896
