### ISSUE TITLE
etcdctl should not return 0 when not properly used

### ISSUE THREAD

**Issue by fridim** [coreos/etcd#3901]
Context: we use etcdctl in scripts with set -e mode.  It is expected that etcdctl returns something different of 0 when used with wrong arguments.
(I think standard exit status is 2?)

The issue:

    etcdctl -vsdfa
    [ ... display usage... ]
    echo $?
    0

**Comment by fridim** [comment]
It seems etcdctl is based on   codegansta/cli. There is a bug open there also for that :
   https://github.com/codegangsta/cli/issues/276

**Comment by xiang90** [comment]
@fridim Thanks for reporting. There is not much we can do for now. We will update the upstream pkg when the issue is fixed.

**Comment by jonboulle** [comment]
I would love to see someone put up a PR to convert to spf13/cobra which we're trying to use everywhere else :-)

**Comment by gyuho** [comment]
@jonboulle I am interested. Is `spf13/cobra` the preferred choice for etcd?
I think either way, it's good to have one library for all cmd interface.

**Comment by jonboulle** [comment]
@gyuho We're trying to use it for all CoreOS Go projects: https://github.com/coreos/docs/blob/master/golang/README.md#cli

**Comment by gyuho** [comment]
Got it. I have wanted to play with cobra. I will try this for etcd. Thanks @jonboulle !
