### ISSUE TITLE
why do not make applysnapshot  asynchronous

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#3908]
When snapshot relatively large, generate Snapshot and ApplySnapshot will take more time.

etcd generated snapshot has been modified into an asynchronous way. But apply still synchronized. Why keep apply synchronized?

another problem is that if etcd determine the snapshot is invalid, it will ignore the snapshot , but did not return an error to the caller. We call function multinode.Step -> stepFollower -> raft.handleSnapshot -> raft.restore.  In raft.restore function, snapshot will be verified, if it returns false, handleSnapshot will discard this snapshot. But we can not get this. Is there some way to get this?

**Comment by xiang90** [comment]
@YuleiXiao 

Why do you want apply to be async? When a member receives a snapshot, it means it is not synced (and have a huge lag) with the current leader, it cannot make progress anyway. Also restore a snapshot should not take long in v2 (you can at most have a 100MB snapshot). In v3, it might take 10 seconds if you have a > 2GB snapshot we might make it non-blocking for better io utilization.

For your second question, etcd does not use multiNode at all. And I do not really follow your question either.

**Comment by YuleiXiao** [comment]
@xiang90 

For second question:
I mean in handleSnapshot, when restore functio return false, handleSnapshot ignore the snapshot. But we do not know this. It do not return any error to caller.

func (r *raft) handleSnapshot(m pb.Message) {                                                                                                                                                              
        sindex, sterm := m.Snapshot.Metadata.Index, m.Snapshot.Metadata.Term                                                                                                                               
        if r.restore(m.Snapshot) {                                                                                                                                                                         
                r.logger.Warningf("%x [commit: %d] restored snapshot [index: %d, term: %d]",                                                                                                               
                        r.id, r.Commit, sindex, sterm)                                                                                                                                                     
                r.send(pb.Message{To: m.From, Type: pb.MsgAppResp, Index: r.raftLog.lastIndex()})                                                                                                          
        } else {                                                                                                                                                                                           
                r.logger.Warningf("%x [commit: %d] ignored snapshot [index: %d, term: %d]",                                                                                                                
                        r.id, r.Commit, sindex, sterm)                                                                                                                                                     
                r.send(pb.Message{To: m.From, Type: pb.MsgAppResp, Index: r.raftLog.committed})                                                                                                            
        }

**Comment by xiang90** [comment]
@YuleiXiao 

Who is "we"? Are you trying to use etcd or use raft pkg? Why do you care about the internal raft level msg?

**Comment by YuleiXiao** [comment]
@xiang90 
Sorry, let me explain.
I am working on cockroach. cockroach use etcd multinode in etcd. We have a problem now. Cockroach generate snapshot, apply snapshot and handle heartbeat in the same goroutine. 
If snapshot is large(we test it about 800M), it need 11s to generate that exceed raft heartbeat timeout time(3s). So I want make it async to avoid this situation.

Now, async apply snapshot is that when receive a snapshot msg, I mark it "pending snapshot" and notify another goroutine to apply it. Before apply snapshot complete, ignore all receiving msg except heartbeat.

But when I debug it. I found some snapshot msg was ignored by etcd inside. cockroach as caller can not get error from multinode.Step() so that I can not remark "pending snapshot". 
That is why I need some way to get this situation.

**Comment by xiang90** [comment]
@YuleiXiao OK. cockroach shares the same raft as etcd, but not the same node implementation. How to apply the snapshot is out of the scope, since it depends on the node and statemachine level implementation. I am closing this issue. 

For your follow up question about raft, can you please open a separate issue?

**Comment by bdarnell** [comment]
`ApplySnapshot` is defined in `cockroach/multiraft/storage.go`, not `etcd/raft`, so let's move this discussion to the cockroach issue tracker.
