### ISSUE TITLE
Feature request to support microservices / serviceDiscovery / cloud

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#3910]
Sorry, it is not an issue, it is a feature request.

I think there should be many more like me who are waiting on etcd to start supporting service discovery.
We are already using a 5 member cluster in production and following etcd desperately for this additional use cases other than just kv storage for more than a year. :smile:  

etcd is amazing and the only 2 things that would make it absolutely useful across the domains imo are service discovery and multi data center support.

Something like consul services to register and discover. I'm aware that there are solutions available but none are stable and not at all customizable. In this age of micro services architecture, if etcd starts supporting service discovery, it will be amazing.

Can we have something like below for etcd as well?
http://cloud.spring.io/spring-cloud-consul/

**Comment by xiang90** [comment]
@raoofm You can use skydns (https://github.com/skynetservices/skydns) to achieve the similar thing. We do not have plan to support this directly in etcd project at the moment.

**Comment by raoofm** [comment]
@xiang90 Thanks
