### ISSUE TITLE
doc: doc should be pronoun-less and imperative?

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#3914]
From https://github.com/coreos/etcd/pull/3913#discussion_r45673900

We need a better discussion about this. If we all agree on it, we need to start fixing all docs.

@jonboulle @joshix

**Comment by joshix** [comment]
I strongly agree with @jonboulle's comment on #3913. Documentation remains clearer and less idiomatic if it is impersonal and imperative. It is especially easy to gain layers of indirection with the second person pronoun ("you").

I try to write new content in an active imperative voice, and expect we will make the wider existing documentation conform more with that style with iterations over time.

General, loose guidance to this effect probably belongs in the coreos/docs#633 style guide once it is established for simpler matters of text formatting.

**Comment by joshix** [comment]
https://github.com/joshix/docs/blob/styledir-hdings/STYLE.md#eschew-you

**Comment by xiang90** [comment]
Closing since this is already in https://github.com/coreos/docs/blob/master/STYLE.md#eschew-you.
