### ISSUE TITLE
etcdv3: TTL-less keys

### ISSUE THREAD

**Issue by eyakubovich** [coreos/etcd#3919]
This issue is to track a design decision about having no TTL on the keys but rather switch to using leases.

While flannel uses TTLs to implement subnet leases, these leases are not really owned by a process. It is a lease that's owned by a node (actually tied host IP). The lease can be manipulated by flannel daemon as well as administratively (e.g. etcdctl; flannelctl in the future). It is useful that the addition/removal of TTL is observable via a watch.

It would be helpful to hear if others have a need for v2 TTL functionality.

**Comment by xiang90** [comment]
@eyakubovich After thinking this more carefully and tweaking the API back and forth, I tend to add a Lease field to keys. So the leasing operations of keys can be watchable. 

This is a compromise of a cleanly separated key and lease API. Perviously only lease API knows about keys API. After we add lease field into a key, key API now has an idea of a lease. But I feel this compromise does make v3 API more easy to work with, which is our primary goal.

**Comment by eyakubovich** [comment]
I think this is great. Will you still have the ability to have one lease be attached to multiple keys?

**Comment by xiang90** [comment]
@eyakubovich 

>  Will you still have the ability to have one lease be attached to multiple keys?

Yes. So we create a lease, get a lease ID, and then we can attach lease to keys. But the semantics changes to put(foo, bar, leaseID). The lease on key is key-api centric rather than lease-api centric. Lease api only takes care of creating/destroying/keep-alive leases.
