### ISSUE TITLE
race condition between etcd and flannel

### ISSUE THREAD

**Issue by dalanlan** [coreos/etcd#3924]
We expect `flannel` belonging to the same public ip to reuse the subnet within expiration when it's restarted. Yet it sometime doesn't. Turns out `etcd` doesn't give out all of the data. 

- How to reproduce

It's hard to trace and could use a little luck.
1. Use `upstart` to manage `etcd` and `flannel`, bringing `flannel` up and down along with `etcd`. Ref [configuration file](https://github.com/kubernetes/kubernetes/blob/master/cluster/ubuntu/master/init_conf/flanneld.conf)
2. set up `/coreos.com/network/config` for `flannel`
3. restart `etcd`

- How it goes

```
$ ./etcdctl ls /coreos.com/network/subnets --recursive
/coreos.com/network/subnets/172.16.55.0-24
/coreos.com/network/subnets/172.16.16.0-24
/coreos.com/network/subnets/172.16.87.0-24
/coreos.com/network/subnets/172.16.14.0-24
```
Among which, `172.16.55.0-24` & `172.16.14.0-24` correspond to the same host ip. None of them is out of expiration.
```
$ ./etcdctl get /coreos.com/network/subnets/172.16.14.0-24
{"PublicIP":"10.10.0.21"}
$ ./etcdctl get /coreos.com/network/subnets/172.16.55.0-24
{"PublicIP":"10.10.0.21"}
```
Here is the log of flannel.
I hack flannel and print out the subnet lease it caught.
Only `172.16.16.0-24` and `172.16.87.0-24` are returned, that's why it misses `172.16.14.0/24`.

```
I1126 14:38:34.287913 17767 main.go:275] Installing signal handlers
I1126 14:38:34.288263 17767 main.go:130] Determining IP address of default interface
I1126 14:38:34.300132 17767 main.go:188] Using 10.10.0.21 as external interface
I1126 14:38:34.300366 17767 main.go:189] Using 10.10.0.21 as external endpoint
I1126 14:38:34.413520 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.16.0-24","value":"{\"PublicIP\":\"10.10.105.59\"}","nodes":null,"createdIndex":654,"modifiedIndex":654,"expiration":"2015-11-27T03:23:15.022094458Z","ttl":74681}
I1126 14:38:34.413578 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.87.0-24","value":"{\"PublicIP\":\"10.10.103.101\"}","nodes":null,"createdIndex":121,"modifiedIndex":121,"expiration":"2015-11-27T03:07:38.69724457Z","ttl":73745}
I1126 14:38:34.413640 17767 etcd.go:127] [{"Subnet":"172.16.16.0/24","Attrs":{"PublicIP":"10.10.105.59"},"Expiration":"2015-11-27T03:23:15.022094458Z"},{"Subnet":"172.16.87.0/24","Attrs":{"PublicIP":"10.10.103.101"},"Expiration":"2015-11-27T03:07:38.69724457Z"}]
I1126 14:38:34.413646 17767 etcd.go:206] Picking subnet in range 172.16.1.0 ... 172.16.255.0
I1126 14:38:34.837943 17767 etcd.go:84] Subnet lease acquired: 172.16.55.0/24
I1126 14:38:34.838351 17767 udp.go:222] Watching for new subnet leases
I1126 14:38:34.838958 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.16.0-24","value":"{\"PublicIP\":\"10.10.105.59\"}","nodes":null,"createdIndex":3074,"modifiedIndex":3074,"expiration":"2015-11-27T06:17:06.529680882Z","ttl":85112}
I1126 14:38:34.838997 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.87.0-24","value":"{\"PublicIP\":\"10.10.103.101\"}","nodes":null,"createdIndex":121,"modifiedIndex":121,"expiration":"2015-11-27T03:07:38.69724457Z","ttl":73744}
I1126 14:38:34.839016 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.14.0-24","value":"{\"PublicIP\":\"10.10.0.21\"}","nodes":null,"createdIndex":3337,"modifiedIndex":3337,"expiration":"2015-11-27T06:37:21.336546325Z","ttl":86327}
I1126 14:38:34.839032 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.55.0-24","value":"{\"PublicIP\":\"10.10.0.21\"}","nodes":null,"createdIndex":3365,"modifiedIndex":3365,"expiration":"2015-11-27T06:38:34.413759083Z","ttl":86400}
I1126 14:38:34.839065 17767 udp.go:247] Subnet added: 172.16.16.0/24
I1126 14:38:34.839088 17767 udp.go:247] Subnet added: 172.16.87.0/24
I1126 14:38:34.839095 17767 udp.go:247] Subnet added: 172.16.14.0/24
```

- ENV

ubuntu 12.04 
etcd: 2.2.1
flannel: 0.5.3

**Comment by AdoHe** [comment]
@dalanlan from the log you offered, the `flanneld` daemon has received the `172.16.14.0/24` subnet added notification.

**Comment by dalanlan** [comment]
I' m afraid you mixed it up. That happened later.
Please focus on here
```
I1126 14:38:34.413520 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.16.0-24","value":"{\"PublicIP\":\"10.10.105.59\"}","nodes":null,"createdIndex":654,"modifiedIndex":654,"expiration":"2015-11-27T03:23:15.022094458Z","ttl":74681}
I1126 14:38:34.413578 17767 etcd.go:240] {"key":"/coreos.com/network/subnets/172.16.87.0-24","value":"{\"PublicIP\":\"10.10.103.101\"}","nodes":null,"createdIndex":121,"modifiedIndex":121,"expiration":"2015-11-27T03:07:38.69724457Z","ttl":73745}
```

**Comment by AdoHe** [comment]
@dalanlan I think you can try to print out the `key` used to acquire subnet lease and also print the `resp` of the acquire request.

**Comment by dalanlan** [comment]
@AdoHe  Why? I think it's pretty clear that `etcd` didn't give back all the data and made `flannel` suffer.

**Comment by xiang90** [comment]
@dalanlan etcd might give you stale, but sequential consistent data. Consistency != Linearizability.

**Comment by dalanlan** [comment]
What i expect is etcd would give all the data within expiration that it stores, by which i mean, 
`172.16.16.0-24`, `172.16.87.0-24`, and `172.16.14.0/24` in this particular case, hence flannel can get rid of a new lease (`172.16.55.0-24`).
This is exactly what we call consistency, right?

**Comment by xiang90** [comment]
> What i expect is etcd would give all the data 

Again, etcd would return you "stale" data unless you specify quorum=true. All data at time-t1 does not equal to all data at time-t2.

**Comment by eyakubovich** [comment]
I think this should be a flannel issue -- change to use quorum=true. Considering flannel getting a lease is meant to be a rare operation, this should not be a problem.

I actually knew in the back of my mind that not having quorum reads might bite someone at some point. I guess it finally happened. I'll file and issue.

**Comment by xiang90** [comment]
@dalanlan Let's track the issue in flannel repo.
