### ISSUE TITLE
Question regarding clients and ssl

### ISSUE THREAD

**Issue by cristifalcas** [coreos/etcd#3925]
Let me first explain the setup:

* host1, host2, host3 are cluster members
* hosts4,host5, etc are set as proxies to the above cluster
* all etcd servers have for clients the listen urls and advertise urls set to 127.0.0.1 without ssl and for peers 0.0.0.0 with ssl

Can a client installed on the same machine with a proxy connect to the cluster through localhost with no ssl?

When I tried it failed, complaining that the certificate (there where no certificates involved for clients, obviously) was not good.

I was expecting for this setup to work.

**Comment by xiang90** [comment]
> all etcd servers have for clients the listen urls and advertise urls set to 127.0.0.1

This does not work. Proxy needs to use the advertised client url to contact etcd members. If you set it to localhost, proxy will try to talk with localhost(which is probably proxy itself in your case). So it fails to connect to the real etcd members.

You should set the advertised url correctly. Then everything should works.

Please check https://github.com/coreos/etcd/blob/master/Documentation/proxy.md for more information.
