### ISSUE TITLE
Clustering two diffrent channels

### ISSUE THREAD

**Issue by MichalMankowski** [coreos/etcd#3926]
I was trying to make cluster with few machines from alpha channel and few from stable , and I was unable to create that environment. There is no information in documentation that user cannot make environment like this .I suppose that main factor is diffrent etcd2 (version 2.1.2 and 2.2.1). 

Logs saying that server is already initialized as member before ,but I remove few times /var/lib/etcd2/*  ,and after that logs are the same. 

Logs from alpha:
Nov 26 13:38:37 localhost systemd[1]: Starting etcd2...
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://x.x.x.x:2379,http://x.x.x.x:4001
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/xxxxxxxxxxxxxxxxxxxxxxxxxxx
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://x.x.x.x:2380
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://x.x.x.x:2380
Nov 26 13:38:37 localhost etcd2[1782]: recognized and used environment variable ETCD_NAME=fd570bcd45794220900167d68f6bb3dd
Nov 26 13:38:37 localhost etcd2[1782]: etcd Version: 2.2.1
Nov 26 13:38:37 localhost etcd2[1782]: Git SHA: 75f8282
Nov 26 13:38:37 localhost etcd2[1782]: Go Version: go1.4.3
Nov 26 13:38:37 localhost etcd2[1782]: Go OS/Arch: linux/amd64
Nov 26 13:38:37 localhost etcd2[1782]: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 26 13:38:37 localhost etcd2[1782]: the server is already initialized as member before, starting as etcd member...
Nov 26 13:38:37 localhost etcd2[1782]: listening for peers on http://x.x.x.x:2380
Nov 26 13:38:37 localhost etcd2[1782]: listening for client requests on http://0.0.0.0:2379
Nov 26 13:38:37 localhost etcd2[1782]: listening for client requests on http://0.0.0.0:4001
Nov 26 13:38:37 localhost etcd2[1782]: stopping listening for client requests on http://0.0.0.0:4001
Nov 26 13:38:37 localhost systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 13:38:37 localhost systemd[1]: Failed to start etcd2.
Nov 26 13:38:37 localhost systemd[1]: etcd2.service: Unit entered failed state.
Nov 26 13:38:37 localhost systemd[1]: etcd2.service: Failed with result 'exit-code'.
Nov 26 13:38:47 localhost systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Nov 26 13:38:47 localhost systemd[1]: Stopped etcd2.

**Comment by gyuho** [comment]
Could you share the command that you used to start your etcd?
And `the server is already initialized as...` indicates you did not empty the 
data directories, I think.

**Comment by MichalMankowski** [comment]
As I mentioned before I'm sure that /var/lib/etcd2/* was empty.

I stopped etcd2 ,clear /var/lib/etcd2/* ,then start it again ```systemctl start etcd2```

**Comment by xiang90** [comment]
@MichalMankowski We need to have full log to help you more, especially the log right before the exit. See https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md#how-to-get-etcd-configuration-and-log-when-it-runs-as-systemd-service-etcd2service.

**Comment by MichalMankowski** [comment]
conf:
```
# /usr/lib64/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
LimitNOFILE=40000

[Install]
WantedBy=multi-user.target

# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.1.x.x:2379,http://10.1.x.x:4001"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/1da53758cc76c432eb29cxxxxxxxxx"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.1.x.x:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://10.1.x.x:2380"
```

2 more intresting logs I think : 

```
Nov 26 11:35:57 localhost systemd[1]: Starting etcd2...
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.1.x.x:2379,http://10.1.x.x:4001
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/1da53758cc76c432eb29c4xxxxxxxxxx
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.1.x.x:2380
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.1.x.x:2380
Nov 26 11:35:57 localhost etcd2[1898]: recognized and used environment variable ETCD_NAME=050f492063ea43aa8caee9ad39db3de0
Nov 26 11:35:57 localhost etcd2[1898]: etcd Version: 2.2.1
Nov 26 11:35:57 localhost etcd2[1898]: Git SHA: 75f8282
Nov 26 11:35:57 localhost etcd2[1898]: Go Version: go1.4.3
Nov 26 11:35:57 localhost etcd2[1898]: Go OS/Arch: linux/amd64
Nov 26 11:35:57 localhost etcd2[1898]: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 26 11:35:57 localhost etcd2[1898]: the server is already initialized as member before, starting as etcd member...
Nov 26 11:35:57 localhost etcd2[1898]: listening for peers on http://10.1.x.x:2380
Nov 26 11:35:57 localhost etcd2[1898]: listening for client requests on http://0.0.0.0:2379
Nov 26 11:35:57 localhost etcd2[1898]: listening for client requests on http://0.0.0.0:4001
Nov 26 11:35:57 localhost etcd2[1898]: stopping listening for client requests on http://0.0.0.0:4001
Nov 26 11:35:57 localhost etcd2[1898]: stopping listening for client requests on http://0.0.0.0:2379
Nov 26 11:35:57 localhost etcd2[1898]: stopping listening for peers on http://10.1.x.x:2380
Nov 26 11:35:57 localhost etcd2[1898]: member "050f492063ea43aa8caee9ad39db3de0" has previously registered with discovery service token (https://discovery.etcd.io/1da5375xxxxx76c432eb29c4165fxxxxx).
Nov 26 11:35:57 localhost systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 11:35:57 localhost systemd[1]: Failed to start etcd2.
Nov 26 11:35:57 localhost systemd[1]: etcd2.service: Unit entered failed state.
Nov 26 11:35:57 localhost systemd[1]: etcd2.service: Failed with result 'exit-code'.
Nov 26 11:36:07 localhost systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Nov 26 11:36:07 localhost systemd[1]: Stopped etcd2.
```

```

Nov 26 11:36:28 localhost systemd[1]: Starting etcd2...
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.1.x.x:2379,http://10.1.x.x:4001
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/1da53758cc76c432eb29c41xxxxxx
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.1.x.x:2380
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.1.x.x:2380
Nov 26 11:36:28 localhost etcd2[1924]: recognized and used environment variable ETCD_NAME=050f492063ea43aa8caee9ad39db3de0
Nov 26 11:36:28 localhost etcd2[1924]: etcd Version: 2.2.1
Nov 26 11:36:28 localhost etcd2[1924]: Git SHA: 75f8282
Nov 26 11:36:28 localhost etcd2[1924]: Go Version: go1.4.3
Nov 26 11:36:28 localhost etcd2[1924]: Go OS/Arch: linux/amd64
Nov 26 11:36:28 localhost etcd2[1924]: setting maximum number of CPUs to 1, total number of available CPUs is 48
Nov 26 11:36:28 localhost etcd2[1924]: the server is already initialized as member before, starting as etcd member...
Nov 26 11:36:28 localhost etcd2[1924]: listening for peers on http://10.1.x.x:2380
Nov 26 11:36:28 localhost etcd2[1924]: listening for client requests on http://0.0.0.0:2379
Nov 26 11:36:28 localhost etcd2[1924]: listening for client requests on http://0.0.0.0:4001
Nov 26 11:36:28 localhost etcd2[1924]: stopping listening for client requests on http://0.0.0.0:4001
Nov 26 11:36:28 localhost etcd2[1924]: stopping listening for client requests on http://0.0.0.0:2379
Nov 26 11:36:28 localhost etcd2[1924]: stopping listening for peers on http://10.1.x.x:2380
Nov 26 11:36:28 localhost etcd2[1924]: member "050f492063ea43aa8caee9ad39db3de0" has previously registered with discovery service token (https://discovery.etcd.io/1da53758cc76c432eb29c4165xxxxxxxx).
Nov 26 11:36:28 localhost etcd2[1924]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).
Nov 26 11:36:28 localhost systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Nov 26 11:36:28 localhost systemd[1]: Failed to start etcd2.
```

**Comment by gyuho** [comment]
Seems like you got duplicate IDs. Did you set the same token? Or `initial-cluster-state`?

```
--initial-cluster-token etcd-cluster-1
--initial-cluster-state new
```

**Comment by MichalMankowski** [comment]
Token was the same from the beginning , with first run logs shows that. 
It's only appears on alpha coreos from my cluster , all nodes with stable seems ok from the beginning.

cloudconfig:
```
#cloud-config
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/1da53758cc76c432eb29c4165xxxxxxx
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://10.1.x.x:2379,http://10.1.x.x:4001
    initial-advertise-peer-urls: http://10.1.x.x:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://10.1.x.x:2380
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

    - name: eno1.network
      runtime: true
      content: |
        [Match]
        Name=eno1

        [Network]
        DNS=8.8.8.8
        Address=10.1.x.x/23
        Gateway=10.1.x.x
```

**Comment by xiang90** [comment]
@MichalMankowski There are two issues:

1. You should remove the pervious data dir

2. You should not reuse previous discovery token.

**Comment by xiang90** [comment]
`ETCD_DATA_DIR=/var/lib/etcd2` This is your data dir. I do not know how you "clear" it, but it was not removed when you started etcd.

**Comment by MichalMankowski** [comment]
So how nodes are in the list under my discovery key? I really don't know. If I didn't remove my old dir they shouldn't show up in the next one (if i'm right).

**Comment by xiang90** [comment]
@MichalMankowski 

> So how nodes are in the list under my discovery key? I really don't know. 

I do not know exactly how you put the node under the discovery token. And I really cannot help you to figure that out. Probably you started etcd twice the same discovery token.

The result is that you reused the discovery token.

> If I didn't remove my old dir they shouldn't show up in the next one (if i'm right).

You probably did not clear entire `/var/lib/etcd2`, but the actual wal was cleared. I cannot know what you have done exactly.

Again here is my suggestion:

1. do not reuse the discovery token

2. clear entire data dir

If you still have the same issue, please report back.

**Comment by xiang90** [comment]
@MichalMankowski 

And it is OK to run etcd 2.1 with 2.2. The problem is that you:

cleared the wal and reused the discovery token. Once you remove the wal, your member is basically gone. If you want to add it back, you need to use runtime reconfiguration. See https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member
