### ISSUE TITLE
does etcd supports adding new node(peer) dynamically into the etcd cluster with tls?

### ISSUE THREAD

**Issue by SrinivasChilveri** [coreos/etcd#3943]
Hi,
     I am new to etcd.Its a query related to etcd cluster with tls. does etcd supports adding new node dynamically into the etcd cluster? in that case are we using dynamic reconfiguration or how we are updating the peer info which we are using while bringing up a node?

do we need to re generate the certificates?(https://github.com/coreos/etcd/blob/master/Documentation/security.md             mentioned  as  "If you need your certificate to be signed for your member's FQDN in its Subject Name then you could use Subject Alternative Names (short IP SANs) to add your IP address. The etcd-ca tool provides --domain= option for its new-cert command, and openssl can make it too.")

**Comment by xiang90** [comment]
> does etcd supports adding new node dynamically into the etcd cluster? in that case are we using dynamic reconfiguration or how we are updating the peer info which we are using while bringing up a node?

Yes. Doc is here: https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md

You can read more about its design here: https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md.

> do we need to re generate the certificates?

You do not have to re-generate existing certs.

**Comment by xiang90** [comment]
@SrinivasChilveri I think your question is answered. Closing this due to low activity.
