### ISSUE TITLE
systemctl status etcd report errors

### ISSUE THREAD

**Issue by gzliudan** [coreos/etcd#3961]
When I run systemctl status etcd, it has 2 red lines marked red as below:
failed to notify systemd for readiness: No socket
forgot to set Type=notify in systemd service file?
How to resolve this problem?
My system is oracle linux 7.1, and I use below commands to install etcd:
yum -y install etcd
curl -L  https://github.com/coreos/etcd/releases/download/v2.2.2/etcd-v2.2.2-linux-amd64.tar.gz -o etcd-v2.2.2-linux-amd64.tar.gz
tar xzvf etcd-v2.2.2-linux-amd64.tar.gz
cp etcd-v2.2.2-linux-amd64/etcd* /usr/bin

below is full output
# systemctl status etcd
etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled)
   Active: active (running) since Sun 2015-12-06 02:22:51 CST; 1min 54s ago
 Main PID: 9551 (etcd)
   CGroup: /system.slice/etcd.service
           └─9551 /usr/bin/etcd

Dec 06 02:22:51 mongo3 etcd[9551]: restarting member 66b1b294f7bc5329 in cluster 2493d8de9468bced at commit index 11632
Dec 06 02:22:51 mongo3 etcd[9551]: 66b1b294f7bc5329 became follower at term 37
Dec 06 02:22:51 mongo3 etcd[9551]: newRaft 66b1b294f7bc5329 [peers: [35b892882eaf2f23,66b1b294f7bc5329,6cbd0470a845650c], term: 37, comm...term: 37]
Dec 06 02:22:51 mongo3 etcd[9551]: the connection with 35b892882eaf2f23 became active
Dec 06 02:22:51 mongo3 etcd[9551]: starting server... [version: 2.2.2, cluster version: 2.2]
Dec 06 02:22:51 mongo3 etcd[9551]: failed to notify systemd for readiness: No socket
Dec 06 02:22:51 mongo3 etcd[9551]: forgot to set Type=notify in systemd service file?
Dec 06 02:22:51 mongo3 etcd[9551]: raft.node: 66b1b294f7bc5329 elected leader 35b892882eaf2f23 at term 37
Dec 06 02:22:51 mongo3 etcd[9551]: the connection with 6cbd0470a845650c became active
Dec 06 02:22:51 mongo3 etcd[9551]: published {Name:mongo3 ClientURLs:[http://mongo3:2379]} to cluster 2493d8de9468bced
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by xiang90** [comment]
> How to resolve this problem?

The log line already told you how to resolve the issue:

```
failed to notify systemd for readiness: No socket
forgot to set Type=notify in systemd service file?
```

You need to set type=notify.
