### ISSUE TITLE
backup/restore docs are currently incorrect

### ISSUE THREAD

**Issue by nelsonenzo** [coreos/etcd#3982]
Currently the docs specify:
```
 etcd \
      -data-dir=%backup_data_dir% \
      -force-new-cluster \
```
"-force-new-cluster" is not a valid flag in version 2.2

Older versions of etcd2 that do support -force-new-cluster, do not support 
`etcdctl member update`
which is required change the advertised peer url.

I currently have no path to restore an etcd cluster from a backed up data directory.  Any help on the current way to do this would be appreciated.

**Comment by gyuho** [comment]
@nelsonenzo 

> I currently have no path to restore an etcd cluster from a backed up data directory. 

Could you tell us which version of etcd you are running?

And I will look into ways to document this issue. Thanks,

**Comment by xiang90** [comment]
@gyuho 

> "-force-new-cluster" is not a valid flag in version 2.2

I believe it is etcd 2.2.

**Comment by gyuho** [comment]
Sorry for delay.

So the problem is:
- `force-new-cluster` flag is introduced since the [version 2.0](https://github.com/coreos/etcd/blob/release-2.0/etcdmain/config.go#L182).
- `etcdctl member update` is introduced since the [version 2.2](https://github.com/coreos/etcd/blob/release-2.2/etcdctl/command/member_commands.go).
- But the [doc](https://github.com/coreos/etcd/blob/master/Documentation/admin_guide.md#restoring-the-cluster) explains to use `etcdctl member update`.

I will update that `admin_guide` documentation explaining how to restore a backup without
`etcdctl member update` command.

**Comment by xiang90** [comment]
@gyuho 

I think his problem is ""-force-new-cluster" is not a valid flag in version 2.2". But I believe --force-new-cluster is still a valid flag in 2.2. Can you also give it a try to confirm?

**Comment by gyuho** [comment]
Yeah we released 2.2 with `force-new-cluster` flag [here](https://github.com/coreos/etcd/blob/release-2.2/etcdmain/config.go#L211).

I see the problem that if one has version 2.1 that has `force-new-cluster` but no `etcdctl member update`, he/she cannot restore the back-ed up data in the way we describe in the `admin_guide` documentation.

**Comment by xiang90** [comment]
@nelsonenzo Both me and @gyuho have confirmed `--force-new-cluster` is still a valid flag in 2.2. Can you please make sure you are using etcd 2.2 and try again. @gyuho is working on improving the doc. But I think that is a separate issue.

**Comment by xiang90** [comment]
@gyuho Our API doc is actually also versioned. The 2.1 doc is here: https://github.com/coreos/etcd/blob/release-2.1/Documentation/admin_guide.md. We also do not maintain 2.1 branch anymore. So there is really nothing we can do here.

**Comment by gyuho** [comment]
Thanks @xiang90 .

@nelsonenzo If your etcd is v2.0+, `force-new-cluster` should be valid flag.
But if your `etcdctl` is lower than v2.2, `etcdctl member update` is not supported.

Please let us know while we are working on updating the docs in a separate PR.
I will keep you updated.

**Comment by gyuho** [comment]
Got it @xiang90 . I will work on the docs for the future branches then.
