### ISSUE TITLE
EtcdResult.__repr__ should not include __dict__

### ISSUE THREAD

**Issue by gst** [coreos/etcd#3996]
Hi,

I just started trying etcd..

I'm suprised to see that the \_\_repr\_\_ of an EtcdResult include the repr() of its whole \_\_dict\_\_, which is rather counter-producive when you evaluate/test the library in an interactive session.. especially if the returned EtcdResult was one with recursive=True..

Would you mind changing the \_\_repr\_\_ to not anymore include the whole instance \_\_dict\_\_ but only subparts of it (if/when necessary) ??

**Comment by gyuho** [comment]
@gst Looks like python code. What etcd client are you using?

**Comment by gst** [comment]
@gyuho  : yes that's python, sorry I thought I was on the good repository..

this is this one :  http://python-etcd.readthedocs.org/

Guess I'm gonna /move/ this ticket where appropriate..

**Comment by gyuho** [comment]
Got it. Thanks.
