### ISSUE TITLE
etcd 2.2.2 auth password CPU usage is too high  

### ISSUE THREAD

**Issue by chang290** [coreos/etcd#4005]
To reproduce
 
terminal 1：
./etcd

terminal 2:
./etcdctl user add root
./etcdctl auth enable
for i in `seq 0 1000` ; do ./etcdctl --peers "http://127.0.0.1:2379" -u root:root set /zcs 100; done

now monitor etcd's cpu usage, it is over 90;

**Comment by xiang90** [comment]
This is kind of duplicate with #3223. @chang290 Do you mind closing this and add more info to #3223?
