### ISSUE TITLE
raftexample: support log snapshots

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#4019]
raftexample appends key-value updates to the raft replicated log. Superseded key-value pairs remain in the log indefinitely; the log maintains a complete history of all updates. Maintaining this entire history is impractical due to space and replay costs. Instead, the log should be compacted as a point-in-time snapshot; the most recent values are stored to the snapshot and all log entries recorded prior to the snapshot may be safely discarded.

**Comment by doodles526** [comment]
I'm working through Snapshots in a similar manner in my own project right now. It would probably be fairly trivial to port that over the the raftexample. Most likely I can find time to start this within the next 2 weeks and a PR within 3

**Comment by doodles526** [comment]
I'm working through Snapshots in a similar manner in my own project right now. It would probably be fairly trivial to port that over the the raftexample. Most likely I can find time to start this within the next 2 weeks and a PR within 3

**Comment by xiang90** [comment]
@doodles526 Great! Thank you!

**Comment by xiang90** [comment]
@doodles526 Any progress on this one?

**Comment by doodles526** [comment]
@xiang90: I finished the project I was doing, and started making the port to the kvstore application. But I got held up on other time requirements. Hoping to get around to it this weekend. Otherwise, I can point to the application I built once I open source it, and make it public facing

**Comment by xiang90** [comment]
@doodles526 any progress?

**Comment by doodles526** [comment]
Some. I got distracted with other work. The project I use snapshots with though was just put up today though. Not totally prod ready. But the reference for someone wanting to do snapshotting is there.

Hopefully I will get to a point of not being too busy soon to finish it up. 

https://github.com/compose/canoe
