### ISSUE TITLE
Etcd 2.2 'etcdctl user list' and 'etcdctl role list' return "cannot unmarshal object" error

### ISSUE THREAD

**Issue by Osmonde** [coreos/etcd#4023]
Running Etcd 2.2 and attempting to setup authentication. Users and roles can be added with <tt>etcdctl user add</tt> and <tt>etcdctl role add</tt> but attempting to list either users or roles with <tt>etcdctl role list</tt> or <tt>etcdctl user list</tt> returns the error: <tt>json: cannot unmarshal object into Go value of type string</tt>
This issue also appears to exist in Etcd 2.3 alpha. 

Full command line output:
<pre>
[root@prlx05]/opt/etcd-2.2/bin#>./etcdctl user list
json: cannot unmarshal object into Go value of type string
</pre>

**Comment by jonboulle** [comment]
Can you give an example of the add commands you ran?

**Comment by xiang90** [comment]
I can reproduce this issue by adding a random user and then doing a list.

**Comment by Osmonde** [comment]
The error is also returned when you 'get' a user that has a role assigned to it, but not when the user has no role assigned. See output below:

Adding user successfully:
<pre>
[root@tslx98]/opt/etcd-2.2/bin#>./etcdctl user add test2
New password:
User test2 created
</pre>

Show the details of the new user:
<pre>
[root@tslx98]/opt/etcd-2.2/bin#>./etcdctl user get test2
User: test2
Roles:
</pre>

Make a new role and assign it to test2
<pre>
[root@tslx98]/opt/etcd-2.2/bin#>./etcdctl role add test2
Role test2 created
[root@tslx98]/opt/etcd-2.2/bin#>./etcdctl user grant test2 -roles test2
User test2 updated
</pre>

Show the details of the user again, and it returns the error
<pre>
[root@tslx98]/opt/etcd-2.2/bin#>./etcdctl user get test2
json: cannot unmarshal object into Go value of type string
</pre>

You can still show the details of the role though:
<pre>
[root@tslx98]/opt/etcd-2.2/bin#>./etcdctl role get test2
Role: test2
KV Read:
KV Write:
</pre>

And since when you create the initial root user, it automatically assigns it the root role, trying to show the details of the root user, even right after creation will fail with the error.

**Comment by xiang90** [comment]
@Osmonde I think this is probably just a small issue somewhere. Do you mind looking into it in the code and fixing it? I think you already have a pretty good idea about what is wrong.

**Comment by xiang90** [comment]
@Osmonde This is actually a duplication with https://github.com/coreos/etcd/issues/3702. Let's track this issue there.
