### ISSUE TITLE
ETCD 2.2.2 cluster mode:temp nodes disappeared when shutdown a vm 

### ISSUE THREAD

**Issue by HuangWHWHW** [coreos/etcd#4031]
Hi all,
There is a project of mine using etcd to manager the cluster.The etcd printed errors following when I shutdowned one of the VMs:
![image](https://cloud.githubusercontent.com/assets/13193847/11930689/c7a05d6c-a820-11e5-8efd-c7e7abfeac73.png)

I found when the etcd got the error "no route to host" all the temp nodes in etcd disappeared immediately. As a result , my project was abnormal.
Does anyone help?

BTW:to prove the abnormal of my project related to the error "no route to host", I did a experiment following:
1.Run the project in cluster mode and it was working normally.
2.Kill the etcd process in one VM(there were two other etcd process rest), the etcd leader printed "connect refuse" but the temp nodes are still exist, and the project was normally.
3.Shutdown the VM which killed the etcd process before,  the etcd leader printed "no route to host" and all temp nodes disappeared meanwhile.The project was abnormal finally.

**Comment by gyuho** [comment]
@HuangWHWHW  `no route to host` is error from `golang.org/x/sys/unix` package. How did you set up your cluster?
And what do you mean by `temp nodes`?

Thanks,

**Comment by HuangWHWHW** [comment]
Hi, @gyuho 

1.`How did you set up your cluster?`
Here is the command I use to set up etcd cluster:
`nohup ./etcd -name e${VM_NUM} -initial-advertise-peer-urls http://${LOCAL_IP}:${LEAD_PORT} -listen-peer-urls http://${LOCAL_IP}:${LEAD_PORT} --advertise-client-urls http://${LOCAL_IP}:${LEAD_PORT} --listen-client-urls http://${LOCAL_IP}:${LEAD_PORT} -initial-cluster-token etcd-cluster-1 -initial-cluster ${ENV} -initial-cluster-state new >> log.out 2>&1 &`

and about the ${ENV}:
`for each VM_NUM`
`ENV+="e${VM_NUM}=http://${LOCAL_IP}:${LEAD_PORT}"`


2.`And what do you mean by temp nodes?`
They are  just nodes not dir.

**Comment by xiang90** [comment]
@HuangWHWHW 

I think the behavior is expected. You stopped the physical vm, then etcd should report `no host to route` since there is actually no host to route. 

I have no idea what is `temp nodes`. I do not think that has anything to do with that VM shutdown. etcd treats process dies and VM shutdown the same. And from the logging, everything works fine.

Can you please provide more information to clearly show the problem?

**Comment by gyuho** [comment]
@HuangWHWHW 

1, 2 are expected.

Regarding 3, as Xiang said, we need more information so that we can reproduce the issue.

> all the temp nodes in etcd disappeared immediately. 

You mean all members in cluster failed? Are you running all members in one VM?

I still doubt that this is an etcd issue.

**Comment by gyuho** [comment]
@HuangWHWHW Any updates on this?

**Comment by HuangWHWHW** [comment]
Hi, the problem has been confirmed after these days.It's a bug in my project.
Thanks for the information!
:-)
