### ISSUE TITLE
Support for managing revoked certs

### ISSUE THREAD

**Issue by stensonb** [coreos/etcd#4034]
Authentication via x509 certs are great...until one of the certs is compromised, needs to be revoked, or is no longer required.

[CRL](https://en.wikipedia.org/wiki/Revocation_list) offers a way to this by distributing a blacklist.
[OCSP](https://en.wikipedia.org/wiki/Online_Certificate_Status_Protocol) offers a way to verify each request's authenticity cert against a service, denying validity for certs which have been "revoked".

ETCD should support either CRL, OCSP, or both to ensure that SSL keys can be guaranteed "valid", despite being signed with a common CA.

**Comment by stensonb** [comment]
Maybe this is desired approach: https://en.wikipedia.org/wiki/OCSP_stapling

**Comment by gtank** [comment]
@stensonb Are you talking about revoking client certificates, or clients being able to check an etcd peer's certificate?

**Comment by stensonb** [comment]
The case I had in mind was the revoking client certificates...

**Comment by philips** [comment]
This is related on TLS authentication for the servers: https://github.com/coreos/etcd/issues/4022

**Comment by gtank** [comment]
I think dependency on an OCSP server (or _being_ an OCSP server) is out of scope for etcd. However it would be completely reasonable for peers to check a CRL if the admin supplies one. Go provides functions for handling CRLs already, we will just need to build the logic around them.

**Comment by philips** [comment]
So, the idea would be a periodic polling routine that checks the CRL URL? What happens if the CRL URL is unreachable? What is the normal policy for that?

**Comment by gtank** [comment]
I was thinking about a static/out-of-band CRL for emergency revocation. "Normal" policy for online revocation of all kinds is soft fail, which is dubiously useful (chronicled by various agl pieces, such as https://www.imperialviolet.org/2014/04/19/revchecking.html).
