### ISSUE TITLE
question: how to pass etcd client TLS certs/key

### ISSUE THREAD

**Issue by streamnsight** [coreos/etcd#4044]
Hello,

Trying to get the client working with TLS, but I don't see how I'm supposed to pass the certs and key to it.
I only see a `TLSHandshake` option.

Can someone share an example on how to do this?
Thanks

**Comment by jonboulle** [comment]
TLS configuration is provided by the supplied [`Transport`](https://github.com/coreos/etcd/blob/master/client/client.go#L69)

For an example, check out how etcdctl sets it up: it creates a [transport that might have TLS](https://github.com/coreos/etcd/blob/289de69632be061b1b04858d090acd47026b28a8/etcdctl/command/util.go#L139) and uses that in its [client config](https://github.com/coreos/etcd/blob/master/etcdctl/command/util.go#L263).
