### ISSUE TITLE
why the logs are getting to stderr

### ISSUE THREAD

**Issue by PavelPolyakov** [coreos/etcd#4052]
Hi,

I run my etcd server through supervisor ( http://supervisord.org/ ) , here is the config:

```
[program:etcd]
command=/home/vagrant/etcd-v2.2.2-linux-amd64/etcd --listen-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001' --advertise-client-urls='http://0.0.0.0:2379,http://0.0.0.0:4001' --debug=true --cors='*'
directory=/home/vagrant/etcd-v2.2.2-linux-amd64/
autostart=true
autorestart=true
stopsignal=KILL
killasgroup=true
stopasgroup=true
stdout_logfile=/var/log/supervisor/%(program_name)s-stdout.log
stderr_logfile=/var/log/supervisor/%(program_name)s-stderr.log
user=vagrant
environment=
```

Everything is pretty usual, except the thing, that all the etcd output goes to the `etcd-browser-stderr.log` file.

I don't think that it is supervisor issue, because all of the other applications are passing the output to the "correct" output stream.

Any thoughts if it is correct behaviour?

Regards,

**Comment by jonboulle** [comment]
What is your expected behaviour? What is the "correct" output stream?

**Comment by PavelPolyakov** [comment]
I think debug messages should get to regular stdout, because those are not errors.

**Comment by jonboulle** [comment]
`stderr` is not just for errors, it's for _any_ diagnostic information. With all CoreOS projects we try to follow the Unix tool approach of results going to `stdout` and everything else going to `stderr`. In the case of `etcd` it so happens that there's no "results" to report to stdout in most cases, but for example `etcdctl` will write user-/machine-parseable information to `stdout` and any other diagnostics (including logs) to `stderr`. AIUI all logging should be written to a single stream, and the logging framework should provide the necessary information for users to subsequently partition that information as they wish (or alternatively, the tool should expose configuration to filter at runtime, e.g. log levels). I can't really speak to why elasticsearch/logstash act that way, but IMO they're doing it wrong :-)

References/prior art:
http://pubs.opengroup.org/onlinepubs/9699919799/functions/stdin.html ("diagnostic output")
https://github.com/golang/glog/blob/master/glog.go#L42
http://monkey.org/~marius/unix-tools-hints.html
http://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout

I would suggest either redirecting `stderr` to `stdout`, or filing a feature request if you'd like to have more configurability in the logging options.

**Comment by PavelPolyakov** [comment]
@jonboulle 

Thanks for the detailed explanation, I agree with your arguments.  I think redirect output option is quite ok.

Regards,
