### ISSUE TITLE
map etcd filesystem to linux filesystem

### ISSUE THREAD

**Issue by yuankui** [coreos/etcd#4067]
I try a project https://github.com/xetorthio/etcd-fs

But It stop update and cannot run anymore in my machine.

does etcd support mount its filesystem to linux filesystem?

**Comment by gyuho** [comment]
This often comes up as https://github.com/coreos/etcd/issues/3831.

> etcd is not designed for serving the large amount of data. It is designed for serving meta data and doing coordination. You can build another layer on top of etcd to serve static file in a consistent manner and you can control the replication pretty easily by using 2PC with the help of etcd. (by Xiang Li)

**Comment by jonboulle** [comment]
As Gyu-Ho pointed out, this isn't a recommended use case for etcd or something we'll support within the project.
