### ISSUE TITLE
mk runs over existing keys (bug/documentation issue ?)

### ISSUE THREAD

**Issue by amimimor** [coreos/etcd#4068]
I'm having an issue (or docs miss understanding)
My etcdctl version is 2.2.0
See the bug below:

## Setting the kv:
`core@ip-10-0-2-185 /var/lib/docker/log/smoove/seed-1 $ etcdctl set /smoove/local/cluster/test/access-conf/database-host test `
`test`
## Getting the kv:
`core@ip-10-0-2-185 /var/lib/docker/log/smoove/seed-1 $ etcdctl get /smoove/local/cluster/test/access-conf/database-host`
`test`

## 'mk' should not have overrun the existing kv, at least according to docs: "Create a new key /foo/bar, only if the key did not previously exist"

`core@ip-10-0-2-185 /var/lib/docker/log/smoove/seed-1 $ etcdctl mk /smoove/local/cluster/test/access-conf/database-host problem`
`problem`

`core@ip-10-0-2-185 /var/lib/docker/log/smoove/seed-1 $ etcdctl get /smoove/local/cluster/test/access-conf/database-host`
`problem`

**Comment by gyuho** [comment]
@amimimor Yes, this was a know bug in [v2.2.0](https://github.com/coreos/etcd/releases/tag/v2.2.0) but it's [fixed](https://github.com/coreos/etcd/pull/3685) in later versions. I will try to cherry-pick this patch into that release.

**Comment by gyuho** [comment]
Actually it seems like `v2.2.0` is released under release tag. The fix is introduced in release 2.2.0 branch. Best way is to update your etcdctl to any version later than 2.2.0.

**Comment by xiang90** [comment]
@amimimor As @gyuho mentioned, this is fixed in the latest version of etcd (etcd2.2.2). Please upgrade and give it a try! Thanks!
