### ISSUE TITLE
There is no easy way to determine if a key does not exist using the new client

### ISSUE THREAD

**Issue by kelseyhightower** [coreos/etcd#4080]
When using the new etcd client libs the only way to determine if a key does not exist is to parse a string error. The following code snippet:

```
resp, err := kapi.Get(context.Background(), key, nil)
if err != nil {
    return c, err
}
```

produces the following error:

```
2015/12/27 21:15:55 100: Key not found (/app) [3]
```

While using strings as errors allows me to print a helpful error message, it does not really allow me to handle the error in my application. In this case I would rather ignore errors where the key does not exist.

Is parsing the error as a string the only way to do this?

**Comment by kelseyhightower** [comment]
I'm using the following code snippet as a workaround:

```
resp, err := kapi.Get(context.Background(), key, nil)
if isKeyNotExist(err) {
    continue
}

func isKeyNotExist(err error) bool {
	if err == nil {
		return false
	}
	return strings.HasPrefix(err.Error(), "100: Key not found")
}
```

I'm sure this does not cover all cases, but it works for now.

**Comment by ecnahc515** [comment]
@kelseyhightower I think you probably want this (note: just wrote & untested, but have used something similar previously):
```
func IsKeyNotExist(err error) bool {
    if etcdErr, ok := err.(etcdClient.Error); ok {
        return etcdErr.Code == etcdClient.ErrorCodeKeyNotFound
    }
    return false
}
```

**Comment by kelseyhightower** [comment]
@ecnahc515 I think I tried that and it seems a string is returned and not an etcd err.

**Comment by AdoHe** [comment]
@kelseyhightower really? I used such method in my code, guess I have to test this case.

**Comment by jonboulle** [comment]
@kelseyhightower e.g. [here](https://github.com/coreos/etcd/blob/133f46246e129c5474df83e538c58d8635a55a45/discovery/discovery.go#L220)

**Comment by gyuho** [comment]
@kelseyhightower It returns error interface and gets printed as a string by `Error` method
in `client` package.

As @ecnahc515 mentioned, if you type-assert on error, you can get `client.Error.Code`.
But I agree there should be easier interface to do this, which is addressed in https://github.com/coreos/etcd/pull/4194.

```go
func isKeyNotFound(err error) bool {
	if cErr, ok := err.(Error); ok {
		return cErr.Code == ErrorCodeKeyNotFound
	}
	return false
}
```

**Comment by gyuho** [comment]
Closing this. You can now have `IsKeyNotFound(error)` function (https://github.com/coreos/etcd/pull/4194)
to check if client error is `ErrorCodeKeyNotFound`.

Thanks!

**Comment by purpleidea** [comment]
This is fixed for v3 with this patch: https://github.com/coreos/etcd/pull/7417

Adding this comment b/c this seems to come up in search results a lot.
