### ISSUE TITLE
Can we start etcd container via NAT network mode?

### ISSUE THREAD

**Issue by fatduo** [coreos/etcd#4088]
Hi all,

When I use 
`-p 1001:4001 -p 1380:2380 -p 1379:2379`
to start a etcd container via NAT network mode.
How to set these value below?

ETCD_ADVERTISE_CLIENT_URLS
ETCD_INITIAL_ADVERTISE_PEER_URLS
ETCD_INITIAL_CLUSTER
...

Container port or host port?

**Comment by gyuho** [comment]
@fatduo 

You can do `docker run` setting those values with flags.

https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md#running-etcd-in-standalone-mode

Please let us know if you have any other question.

**Comment by fatduo** [comment]
Hi @gyuho 
Yes. I have already read this wiki page, but it just talk about one to one port mapping, but when the host ports are different from container ports, such as

`-p 1001:4001 -p 1380:2380 -p 1379:2379`

How to set -advertise-client-urls-

`-advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001`
or
`-advertise-client-urls http://${HostIP}:1379,http://${HostIP}:1001`

and -initial-advertise-peer-urls-

`-initial-advertise-peer-urls http://${HostIP}:2380`
or
`-initial-advertise-peer-urls http://${HostIP}:1380`

Using container port or host port?

And I think ${HostIP} should be the hostname outside container.

**Comment by gyuho** [comment]
@fatduo I think ports `2379` and `2380` should be used. Those flags (`-advertise-client-urls`, `-initial-advertise-peer-urls`) are for etcd, not for docker. I would try `-advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001`.

**Comment by AdoHe** [comment]
@gyuho @fatduo I guess you are talking about using the `bridge` network mode, first the container internal port has no need to be the same as host side port, then I think when we configure etcd parameters, we should use host side ports, the container internal ports are not visible to outside actually.

**Comment by gyuho** [comment]
Kindly ping @fatduo .

Did you resolve this issue?

As @AdoHe explains, container port is only internal to its container.
etcd only receives the flags that follows `etcd` executable command.
You should just use host ports.

**Comment by gyuho** [comment]
@fatduo I am closing this due to low activity. Please feel free to ping us back if you still have any issues.

Thanks,
