### ISSUE TITLE
Enable backup to instantiate a snapshot operation

### ISSUE THREAD

**Issue by sjpotter** [coreos/etcd#4095]
In order for backups to be as good as possible (especially with an etcd instance that isn't under heavy write load) we need to have an api call that can cause a snapshot to be created at backup time.

**Comment by sjpotter** [comment]
As a thought, I don't know how snapshots are done now, but have we given any thought to doing incremental snapshots?

**Comment by xiang90** [comment]
@sjpotter We will support point-in-time snapshot retrieval.

>  but have we given any thought to doing incremental snapshots?

We already do incremental snapshots at the server side. But we only keep one giant snapshot file.

We can support sending incremental snapshot to client too. But the first step might still be support point-in-time snapshot.

**Comment by xiang90** [comment]
@sjpotter For incremental snapshot retrieval, the clients need to calculate the next offset to get, assemble the snapshots it got once a while, also does some gc once a while. But we can probably provide a ctl command to do that for our users. I feel a full point-in-time snapshot support would do the job for most of the users.

**Comment by sjpotter** [comment]
@xiang90 agreed, I was thinking out loud.

**Comment by xiang90** [comment]
close in favor of https://github.com/coreos/etcd/issues/4896
