### ISSUE TITLE
Improve backup storage reseliency

### ISSUE THREAD

**Issue by sjpotter** [coreos/etcd#4097]
Currently backup the offsite etcd backup uses rclone to copy the backup directory to a remote service (Amazon S3 bucket....).  However, it can fail.  Right now we make a backup first (which can also fail).  And if 2 fail in a row we will be left without a backup.

rclone is getting a move operation (if not already done, at least in progress - https://github.com/ncw/rclone/issues/35) so something to consider

**Comment by heyitsanthony** [comment]
@xiang90 would this be snapshot verification?

**Comment by xiang90** [comment]
@heyitsanthony Yea, we need to able to verify a (remote) snapshot.
