### ISSUE TITLE
server endpoint to know sync state

### ISSUE THREAD

**Issue by sjpotter** [coreos/etcd#4099]
Currently the restore procedure tells users to do

```bash
for node in e{2..3};do
    ssh core@$node "sudo systemctl start etcd2-join.service && sudo systemctl start etcd2.service"
    sleep 10
done
```

and it sleep to allow the client time to sync, but the note later says to wait until the sync is done and might vary.

could be good to have a etcdctl command that can return the sync status and just loop on that until its ready and then proceed to the next machine.

**Comment by xiang90** [comment]
There is a metrics in kafka called syncLag to determine the rough sync lag duration between follower and leader. We probably can do similar things for etcd.

**Comment by sjpotter** [comment]
So one thing I was wondering.  when a node joins the cluster is it able to be used by clients before it finishes its initial sync?

**Comment by xiang90** [comment]
> when a node joins the cluster is it able to be used by clients before it finishes its initial sync

It is. But we should probably disable it? See https://github.com/coreos/etcd/issues/3879

**Comment by sjpotter** [comment]
ok, then perhaps as part of that have an endpoint perhaps /ready that returns if its ready to be used?

**Comment by xiang90** [comment]
Now, endpoint status is exposed. User can do endpoint status to check the raft syncing status.
