### ISSUE TITLE
v3api: set max number of operations per txn

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4109]
We need to limit the number of operations in one txn so that each request will not be huge (we need to limit the max size of value too) and involves too many allocations.

**Comment by liqlin2015** [comment]
@xiang90 We were using etcd v3.2.18 in our case. And we recently see error `etcdserver: too many operations in txn request`.
I know in etcd v3.2.18, the `MaxOpsPerTxn` was hard coded to 128. Do you have any idea how can we extend the value without upgrading etcd to v3.3.0+? Is there any way to check the current operations in the txn?
