### ISSUE TITLE
TestBackendBatchIntervalCommit fails

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4110]
```
--- FAIL: TestBackendBatchIntervalCommit (0.53s)
	backend_test.go:116: bucket test does not exit
--- FAIL: TestBackendBatchIntervalCommit (0.53s)
	backend_test.go:116: bucket test does not exit
--- FAIL: TestBackendBatchIntervalCommit (0.32s)
	backend_test.go:116: bucket test does not exit
```

```
go version go1.5.2 linux/amd64

model name	: Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz

Linux gyuho 3.19.0-42-generic #48~14.04.1-Ubuntu SMP Fri Dec 18 10:24:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

```

**Comment by gyuho** [comment]
And this is HDD machine.

**Comment by gyuho** [comment]
It's weird that I can only reproduce this by running test script but `go test -timeout 3m -cover -cpu 1,2,4 -v github.com/coreos/etcd/storage/backend` passes. Will investigate more.

**Comment by gyuho** [comment]
Actually `go test -timeout 3m -cover -cpu 1,2,4 -v github.com/coreos/etcd/storage/backend` fails as well but much less frequently.

**Comment by AkihiroSuda** [comment]
I also hit this.

```
--- FAIL: TestBackendBatchIntervalCommit (0.14s)
        backend_test.go:116: bucket test does not exit
```

**Comment by gyuho** [comment]
I think this is just my disk I/O being slow on HDD. So test script always fails with current test:

```
	// give time for batch interval commit to happen
	time.Sleep(time.Nanosecond)
	testutil.WaitSchedule()
	// give time for commit to finish, including possible disk IO
	time.Sleep(50 * time.Millisecond)
```

But if I change to give more time to commit, it succeeds:

```
	// give time for batch interval commit to happen
	time.Sleep(time.Nanosecond)
	testutil.WaitSchedule()
	// give time for commit to finish, including possible disk IO
	time.Sleep(100 * time.Millisecond)
```

@AkihiroSuda can you provide your test environment? This never happens in CIs,
which I assume have SSDs.

**Comment by AkihiroSuda** [comment]
@gyuho
I'm using an EBS magnetic volume on AWS. (t2.large, Ubuntu 15.04 amd64)

I think this test should always succeed even with very slow disks.

Of course we should test that any operation can finish in a moderate time.
However, for such a performance evaluation, I guess we can use the benchmark tool with some modification.
(perhaps benchmark tool should receive some parameters about disk configuration?)

**Comment by AkihiroSuda** [comment]
I artificially built an extreme-slow disk (100ms-300ms delay) with our fuzzing+fault-injection tool: [osrg/earthquake](https://github.com/osrg/earthquake) (joint work with @mitake).

However, the test does *NOT* deterministically fail!

I'll continue to look into this.


    $ go get github.com/osrg/earthquake
	$ mkdir -m 777 /tmp/eqfs-mnt /tmp/eqfs-orig
	$ cat > /tmp/eq-config.toml << EOF
	explorePolicy = "random"
    [explorePolicyParam]
      minInterval = "100ms"
      maxInterval = "300ms"
    EOF
	$ earthquake inspectors fs -autopilot /tmp/eq-config.toml -mount-point /tmp/eqfs-mnt -original-dir /tmp/eqfs-orig
	$ (cd ~/WORK/etcd; TMPDIR=/tmp/eqfs-mnt go test -timeout 3m -cover -cpu 1,2,4 -v github.com/coreos/etcd/storage/backend)

**Comment by gyuho** [comment]
@AkihiroSuda Thanks for looking into this.
In my case, the test fails 100% when the whole test script runs.
