### ISSUE TITLE
TestSyncTrigger fails on CI

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4119]
--- FAIL: TestSyncTrigger-2 (0.01s)
	server_test.go:741: len(action) = 0, want 1

**Comment by heyitsanthony** [comment]
More `testutil.WaitSchedule()` flapping?

**Comment by xiang90** [comment]
@heyitsanthony Probably. We need to spend some time to fix all infra(testing/building/scripting) related issues. :)

**Comment by heyitsanthony** [comment]
I see how to do the `server_test.go` ones in a sane way, so I'll give nuking `WaitSchedule` there a shot.

**Comment by AkihiroSuda** [comment]
For `WaitSchedule`, I have an idea: #4121
