### ISSUE TITLE
TestPipelineKeepSendingWhenPostError fails; need to split performance testing from liveness testing

### ISSUE THREAD

**Issue by AkihiroSuda** [coreos/etcd#4121]
```
--- FAIL: TestPipelineKeepSendingWhenPostError (0.01s)
        pipeline_test.go:74: request count = 19, want 50
```

https://github.com/coreos/etcd/blob/336d177c82a062d6cd02a5f9fb0926e693f01071/rafthttp/pipeline_test.go#L73-L75

The test requires 50 requests performed in just 10 msecs, which cannot be guaranteed in certain environments.

So I suggest to split the performance aspect from "liveness" test cases (including this `TestPipelineKeepSendingWhenPostError`, but there are also many similar things) by introducing some retries.
The performance evaluation should be done in another tool.

## Example
```go
package testutil

// f should be idempotent
func TryWithRetries(t time.Duration, retries int, f func() error) error {
	var err error
	for i := 0; i < retries; i++ {
		err = f()
		if err == nil {
			return nil
		}
		time.Sleep(t)
	}
	return err
}
```

```go
package rafthttp
func TestPipelineKeepSendingWhenPostError(t *testing.T) {
      ..
	err := testutil.TryWithRetries(10 * time.Milliseconds, 100, func() error {
		if tr.reqCount != 50 {
			return fmt.Errorf("request count = %d, want 50", tr.reqCount)
		}
	})
	if err != nil {
		t.Error(err)
	}
}
```

**Comment by heyitsanthony** [comment]
I've seen other tests do something similar but so far it's all ad-hoc. Ideally we wouldn't want to poll at all (e.g., count events via `testutil.RecorderStream`) but implementing interfaces to support `Recorder` is a chore. Overall, this suggestion is certainly better than the `WaitSchedule` stuff that's there now.

**Comment by xiang90** [comment]
After some work, we made our tests pretty stable. We always can switch to a more stable env to do the CI work. We will see how it goes. If it does not go well, we might want to separate the tests.
