### ISSUE TITLE
etcdctl 2.2.3 updatedir fails without extraneous argument.

### ISSUE THREAD

**Issue by mhenniges** [coreos/etcd#4139]
As of 2.2, etcdctl updatedir seems to want another argument, but it doesnt do anything with it.

To reproduce:
   etcdctl setdir /foo -ttl 60
   etcdctl  updatedir /foo -ttl 90 
   <ctrl-d>
Error:  value required

If at an interactive console, this will wait on stdin for the value, ctrl-d will end that and cause the failure. If in a non-interactive context, it will fail immediately with the message.

Im not very famliar with the etcd code, but it seems like these 4 lines at the end of the pasted code fragment below should be removed.

func updatedirCommandFunc(c *cli.Context, ki client.KeysAPI) {
	if len(c.Args()) == 0 {
		handleError(ExitBadArgs, errors.New("key required"))
	}
	key := c.Args()[0]
	value, err := argOrStdin(c.Args(), os.Stdin, 1)
	if err != nil {
		handleError(ExitBadArgs, errors.New("value required"))
	}

...

**Comment by gyuho** [comment]
@mhenniges You need two arguments `<key> <value>` for `updatedir` command.

**Comment by xiang90** [comment]
@mhenniges etcd does not support partial update. You can only update both value and ttl at same time. You can do a read and then compare and awap to update if you want do atomic partial update.

**Comment by mhenniges** [comment]
The value seems ignored in any case for updatedir though, so im not sure why it would be required...My colleague described this issue better than i did in https://github.com/coreos/etcd/issues/4145; I'll just watch the progress over there.

**Comment by xiang90** [comment]
@mhenniges Sorry. I misunderstood your original one. Let's track this in #4145.
