### ISSUE TITLE
etcdctl updatedir requires value

### ISSUE THREAD

**Issue by hypergig** [coreos/etcd#4145]
We have upgraded to 2.2.0 and previous processes that use the `updatedir` subcommand with `etcdctl` fail.

After further investigation, we have discovered `updatedir` now requires a value to function.  This doesn't make sense to me as directories don't have values.  I believe `ttl` is the only changeable bit of data on a directory and it is accessible via the `--ttl=n` command switch.

## Repro steps
_does not work_
```
etcdctl setdir --ttl=60 /foo
etcdctl updatedir --ttl=60 /foo
```
The second command will hang, waiting for standard input. If you `^d` the command will successfully complete.

_will work_
```
etcdctl setdir --ttl=60 '/foo'
etcdctl updatedir --ttl=60 '/foo' 'bar'
```

`bar` isn't used at all.  Infact, if you use the `--debug` switch you see no evidence of `bar` in the provided curl command.
```
etcdctl --debug updatedir --ttl=60 '/foo' 'bar' 
start to sync cluster using endpoints(http://etcd:2379)
cURL Command: curl -X GET http://etcd:2379/v2/members
got endpoints(http://etcd:2379) after sync
Cluster-Endpoints: http://etcd:2379
cURL Command: curl -X PUT http://etcd:2379/v2/keys/foo?dir=true&prevExist=true -d "ttl=60"
```

We even ran tcpdump while executing this command, and again see no evidence of the `bar` value.
```
tcpdump -A -s 0 'tcp port 2379 and (((ip[2:2] - ((ip[0]&0xf)<<2)) - ((tcp[12]&0xf0)>>2)) != 0)'
<tcpdump jibber jabber>
{"action":"update","node":{"key":"/foo","dir":true,"expiration":"2016-01-06T12:33:00.474562958Z","ttl":60,"modifiedIndex":2605,"createdIndex":2604},"prevNode":{"key":"/foo","dir":true,"expiration":"2016-01-06T12:32:52.592657605Z","ttl":53,"modifiedIndex":2604,"createdIndex":2604}}
```

So if the value isn't used, why is it required?

I traced it down to this commit ae1669de266c40dc01b6c9747aae72fbd7889ad4 from @xiang90.
```
	key := c.Args()[0]
	value, err := argOrStdin(c.Args(), os.Stdin, 1)
	if err != nil {
		handleError(ExitBadArgs, errors.New("value required"))
	}
```

Thanks!

**Comment by xiang90** [comment]
I believe this is a bug. Would you like to send a pull request to fix it?

**Comment by gyuho** [comment]
@hypergig This is fixed currently in our master branch. We will apply this patch in our next release, which would be `v2.2.4` (sometime around next week).

**Comment by gyuho** [comment]
@hypergig  The fix was https://github.com/coreos/etcd/pull/4150. Thanks for reporting.
I will close this, and will let you know personally when the fix is applied in the next release.

**Comment by hypergig** [comment]
@xiang90 never had a chance to, @gyuho beat me to the punch. Thank you all, much appreciated.  Look forward to the next release.

**Comment by gyuho** [comment]
Np. Thanks for reporting!
