### ISSUE TITLE
go vet fails when running in Go 1.4

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4149]
https://semaphoreci.com/coreos/etcd/branches/master/builds/240

```
package go/constant: unrecognized import path "go/constant"
package go/importer: unrecognized import path "go/importer"
package go/types: unrecognized import path "go/types"
```

**Comment by gyuho** [comment]
I tried to do something like go get gopkg.in/golang/tools.release-branch.go1.4 but this is not supported.
I will find a work around.

**Comment by xiang90** [comment]
I dropped go 1.4.2 test on semaphoreci. When we release 2.3, most people should already move to go1.5.

**Comment by gyuho** [comment]
Got it. Thanks!!
