### ISSUE TITLE
does etcd have such opration "increament a key value and return the new value"?

### ISSUE THREAD

**Issue by better0332** [coreos/etcd#4168]
the opration should be atomic like CompareAndSwap

**Comment by xiang90** [comment]
No, v2 api does not support it. You need to do a read first, then do a Compare and Swap.

We are considering to add this to v3.

**Comment by better0332** [comment]
can I use "Creating In-Order Keys" to instead?

**Comment by xiang90** [comment]
@better0332 Creating in-order keys creates increasing order of keys, not increase the value of a key. Also it does not ensure the increase is continuous. So it depends on your use case.
