### ISSUE TITLE
Too much TIME_WAIT connection

### ISSUE THREAD

**Issue by aga20** [coreos/etcd#4172]
Hello!

I try to use your benchmark script with boom. Unfortunatelly my result verry different as yours, So I try to detect the problem and I found many TIME_WAIT tcp connection to the etcd server. I can't modify your script just what I have to (leader and server). I think the boom can reuse the connection but etcd can be able to reuse tcp connections?

https://github.com/coreos/etcd/tree/master/hack/benchmark

Example:

...
tcp        0      0 172.17.42.1:47340       172.17.0.4:2379         TIME_WAIT
tcp        0      0 172.17.42.1:54238       172.17.0.4:2379         TIME_WAIT
tcp        0      0 172.17.42.1:60169       172.17.0.4:2379         TIME_WAIT
....

**Comment by gyuho** [comment]
what benchmark command are you using?

**Comment by aga20** [comment]
Just run your bech.sh (link in description).

**Comment by xiang90** [comment]
@aga20 What are the versions of boom and etcd you used?

**Comment by gyuho** [comment]
I think `boom` fixed it last November. https://github.com/rakyll/boom/commit/5d051b61ca6c098f77137c4f6224fa263da365b2

I tried the benchmark script with the latest boom, but don't see any TIME_WAITs anymore.

**Comment by aga20** [comment]
@xiang90 sorry I forget this.
boom: last I found on github: https://github.com/rakyll/boom (run installation command)
etcd: I try it with a docker container https://quay.io/repository/coreos/etcd?tab=tags from this and without docker 2.1.1 (latest redhat rpm what we found).

@gyuho Then I try to build boom manually and I will try it on Monday because I'm on holiday now. Thanks for your link!

**Comment by xiang90** [comment]
@gyuho @aga20 The default behavior of boom will still cause the TCP connection not able to be reused. You need to pass in the flag `readall=true`

**Comment by gyuho** [comment]
I am verifying that right now if the newer boom resolves this issue. I will
keep you updated.

On Fri, Jan 8, 2016 at 9:57 AM, Sandor Szombat <notifications@github.com>
wrote:

> @xiang90 <https://github.com/xiang90> sorry I forget this.
> boom: last I found on github: https://github.com/rakyll/boom (run
> installation command)
> etcd: I try it with a docker container
> https://quay.io/repository/coreos/etcd?tab=tags from this and without
> docker 2.1.1 (latest redhat rpm what we found).
>
> @gyuho <https://github.com/gyuho> Then I try to build boom manually and I
> will try it on Monday because I'm on holiday now. Thanks for your link!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/etcd/issues/4172#issuecomment-170074479>.
>



-- 
Sincerely,
Gyu-Ho Lee

**Comment by gyuho** [comment]
WIth newer version, I still see lots of `TIME-WAIT`s.

@aga20 Could you also try the newest `boom` with `-readall=true` and
check if you still see those `TIME-WAIT`s? I will investigate more.

Thanks!

**Comment by gyuho** [comment]
You can do something like:

```bash
#!/bin/bash -e

leader=http://127.0.0.1:12379
# assume three servers
servers=( http://127.0.0.1:12379 http://127.0.0.1:22379 http://127.0.0.1:32379 )

keyarray=( 64 256 )

for keysize in ${keyarray[@]}; do

  echo write, 1 client, $keysize key size, to leader
  ./boom_new -readall=true -m PUT -n 10 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 1 -T application/x-www-form-urlencoded $leader/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo write, 64 client, $keysize key size, to leader
  ./boom_new -readall=true -m PUT -n 640 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 64 -T application/x-www-form-urlencoded $leader/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo write, 256 client, $keysize key size, to leader
  ./boom_new -readall=true -m PUT -n 2560 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 256 -T application/x-www-form-urlencoded $leader/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo write, 64 client, $keysize key size, to all servers
  for i in ${servers[@]}; do
    ./boom_new -readall=true -m PUT -n 210 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 21 -T application/x-www-form-urlencoded $i/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo &
  done
  # wait for all booms to start running
  sleep 3
  # wait for all booms to finish
  for pid in $(pgrep 'boom'); do
    while kill -0 "$pid" 2> /dev/null; do
      sleep 3
    done
  done

  echo write, 256 client, $keysize key size, to all servers
  for i in ${servers[@]}; do
    ./boom_new -readall=true -m PUT -n 850 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 85 -T application/x-www-form-urlencoded $i/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo &
  done
  sleep 3
  for pid in $(pgrep 'boom'); do
    while kill -0 "$pid" 2> /dev/null; do
      sleep 3
    done
  done

  echo read, 1 client, $keysize key size, to leader
  ./boom_new -readall=true -n 100 -c 1 $leader/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo read, 64 client, $keysize key size, to leader
  ./boom_new -readall=true -n 6400 -c 64 $leader/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo read, 256 client, $keysize key size, to leader
  ./boom_new -readall=true -n 25600 -c 256 $leader/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo read, 64 client, $keysize key size, to all servers
  # bench servers one by one, so it doesn't overload this benchmark machine
  # It doesn't impact correctness because read request doesn't involve peer interaction.
  for i in ${servers[@]}; do
    ./boom_new -readall=true -n 21000 -c 21 $i/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo
  done

  echo read, 256 client, $keysize key size, to all servers
  for i in ${servers[@]}; do
    ./boom_new -readall=true -n 85000 -c 85 $i/v2/keys/foo | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo
  done

done

```

**Comment by gyuho** [comment]
Mine's went up to 2248 time-waits from 400. You can check with:

```
ss -tan state time-wait | wc -l
2248
```

**Comment by gyuho** [comment]
With old boom, it's worse:

```
ss -tan state time-wait | wc -l
30500
```

**Comment by aga20** [comment]
@gyuho I tried <code>-readall=true<code> with old bloom and I've got higher qps. But what this parameter exactly mean?

**Comment by xiang90** [comment]
@aga20 It means it reads out the previous response body so that the TCP connection can be reused and can be properly closed at client side. So it reduces timewait and improves qps.

**Comment by gyuho** [comment]
@aga20 Can you try with the new `boom`, not the old one. `readall` flag lets you consume the entire request body so that TCP conn can be reused as Xiang explains. So we should expect lower time-waits.

**Comment by aga20** [comment]
@xiang90 Hm I see thanks. But this isn't modify the real qps? Just because you measured without this parameter. Maybe it is a stupid question but unfortunatelly thi is a really important question in my situation (now this is a "battle" between and an another software).
@gyuho Yes I will try it on monday, I can't acces to my work from home. Thanks :)

**Comment by xiang90** [comment]
> But this isn't modify the real qps? 

It does affect qps since you do not have to create a new TCP connection each time, which reduce the e2e latency and thus increases qps.

**Comment by gyuho** [comment]
I got breakdown per node:


With `readall=true` flag:

```
server_1_client_wait_time_count: 2218
server_1_server_wait_time_count: 852

server_2_client_wait_time_count: 803 
server_2_server_wait_time_count: 400

server_3_client_wait_time_count: 353
server_3_server_wait_time_count: 35
```


Without `readall` flag and with old boom:

```
server_1_client_wait_time_count: 64286
server_1_server_wait_time_count: 42169

server_2_client_wait_time_count: 42104 
server_2_server_wait_time_count: 21104

server_3_client_wait_time_count: 21045
server_3_server_wait_time_count: 45
```

And this causes a bunch of I/O timeout on server side.

```
server_1_client_wait_time_count=$(ss -tan state time-wait dport ge :12379 | wc -l)
server_1_server_wait_time_count=$(ss -tan state time-wait dport ge :12380 | wc -l)

server_2_client_wait_time_count=$(ss -tan state time-wait dport ge :22379 | wc -l)
server_2_server_wait_time_count=$(ss -tan state time-wait dport ge :22380 | wc -l)

server_3_client_wait_time_count=$(ss -tan state time-wait dport ge :32379 | wc -l)
server_3_server_wait_time_count=$(ss -tan state time-wait dport ge :32380 | wc -l)

echo "
server_1_client_wait_time_count: $server_1_client_wait_time_count
server_1_server_wait_time_count: $server_1_server_wait_time_count

server_2_client_wait_time_count: $server_2_client_wait_time_count 
server_2_server_wait_time_count: $server_2_server_wait_time_count

server_3_client_wait_time_count: $server_3_client_wait_time_count
server_3_server_wait_time_count: $server_3_server_wait_time_count
"
```

**Comment by gyuho** [comment]
@aga20 Please try this https://github.com/coreos/etcd/pull/4182/files.
And this has been addressed in the past as well https://github.com/coreos/etcd/issues?q=is%3Aissue+time_wait+is%3Aclosed.

With `readall` flag, I don't see many time waits anymore. 

But we might not merge the script because it is non-etcd issue, and
that benchmark script is not the best to measure the performance right now.

Please re-open this when you still see many time waits.
