### ISSUE TITLE
etcdmain: unit test tls connection in client side

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4177]
To test the following issues:
- https://github.com/coreos/etcd/issues/4135
- https://github.com/coreos/etcd/issues/4171

For https://github.com/coreos/etcd/issues/4135#issuecomment-169274382

> Would you be able to write a unit test to cover this?

We need some unit test in etcdmain to test these feature.

**Comment by heyitsanthony** [comment]
@xiang90 and I were discussing how we probably should have some bash script tests / bash script testing infra to end-to-end test the commands like this instead of going through the effort of writing go unit tests.

**Comment by gyuho** [comment]
Yeah I agree it will be better. 
For this one, I just write a simple test for the purpose of next release. Thanks

**Comment by gyuho** [comment]
Closing this in favor of @heyitsanthony's integration testing.
