### ISSUE TITLE
V2.2.2 benchmark with TLS  .

### ISSUE THREAD

**Issue by ringtail** [coreos/etcd#4181]
<pre><code>
write, 1 client, 64 key size, to leader
Requests/sec: 5.5734 Latency distribution: 90% in 0.2877 secs.
write, 64 client, 64 key size, to leader
Requests/sec: 92.8946 Latency distribution: 90% in 1.0950 secs.
write, 256 client, 64 key size, to leader
Requests/sec: 166.3471 Latency distribution: 90% in 1.9445 secs.
write, 64 client, 64 key size, to all servers
Requests/sec: 327.8294 Latency distribution: 90% in 0.0794 secs.
Requests/sec: 314.8779 Latency distribution: 90% in 0.0881 secs.
Requests/sec: 23.2999 Latency distribution: 90% in 1.3650 secs.
write, 256 client, 64 key size, to all servers
Requests/sec: 224.6460 Latency distribution: 90% in 0.5860 secs.
Requests/sec: 219.9514 Latency distribution: 90% in 0.5417 secs.
Requests/sec: 218.9553 Latency distribution: 90% in 0.6216 secs.
read, 1 client, 64 key size, to leader
Requests/sec: 36.2026 Latency distribution: 90% in 0.0368 secs.
read, 64 client, 64 key size, to leader
Requests/sec: 390.9239 Latency distribution: 90% in 0.2577 secs.
read, 256 client, 64 key size, to leader
Requests/sec: 564.5470 Latency distribution: 90% in 0.7996 secs.
read, 64 client, 64 key size, to all servers
Requests/sec: 82.9941 Latency distribution: 90% in 0.4037 secs.
Requests/sec: 81.5476 Latency distribution: 90% in 0.4010 secs.
Requests/sec: 88.2975 Latency distribution: 90% in 0.3784 secs.
read, 256 client, 64 key size, to all servers
Requests/sec: 590.7409 Latency distribution: 90% in 0.1973 secs.
Requests/sec: 612.7586 Latency distribution: 90% in 0.1935 secs.
Requests/sec: 618.5782 Latency distribution: 90% in 0.1910 secs.
write, 1 client, 256 key size, to leader
Requests/sec: 33.1125 Latency distribution: 90% in 0.0438 secs.
write, 64 client, 256 key size, to leader
Requests/sec: 270.9540 Latency distribution: 90% in 0.2580 secs.
write, 256 client, 256 key size, to leader
Requests/sec: 531.5982 Latency distribution: 90% in 0.5671 secs.
write, 64 client, 256 key size, to all servers
Requests/sec: 297.7204 Latency distribution: 90% in 0.0857 secs.
Requests/sec: 290.8756 Latency distribution: 90% in 0.0965 secs.
Requests/sec: 286.8749 Latency distribution: 90% in 0.0942 secs.
write, 256 client, 256 key size, to all servers
Requests/sec: 320.9579 Latency distribution: 90% in 0.4136 secs.
Requests/sec: 313.6593 Latency distribution: 90% in 0.4245 secs.
Requests/sec: 308.8697 Latency distribution: 90% in 0.4297 secs.
read, 1 client, 256 key size, to leader
Requests/sec: 91.6368 Latency distribution: 90% in 0.0120 secs.
read, 64 client, 256 key size, to leader
Requests/sec: 612.1461 Latency distribution: 90% in 0.1456 secs.
read, 256 client, 256 key size, to leader
Requests/sec: 612.0311 Latency distribution: 90% in 0.5647 secs.
read, 64 client, 256 key size, to all servers
Requests/sec: 557.5632 Latency distribution: 90% in 0.0493 secs.
Requests/sec: 592.2563 Latency distribution: 90% in 0.0499 secs.
Requests/sec: 610.4016 Latency distribution: 90% in 0.0486 secs.
read, 256 client, 256 key size, to all servers
Requests/sec: 592.4667 Latency distribution: 90% in 0.1954 secs.
Requests/sec: 610.2113 Latency distribution: 90% in 0.1930 secs.
</code></pre>
I simply extend boom and add cert in benchmark test. machine group are 3 (4Core 8G) ECS in aliyun.  
The boom tester is 8Core 8G.the result is very confused.Anyone who has tested the scenario with https and certs.  you can use this for test.
<pre>
<code>
https://github.com/ringtail/boom
</code>
</pre>
the scripts is below 
<pre>
<code>
#!/bin/bash -e

leader="https://etcd1"
# assume three servers
servers=("https://etcd1" "https://etcd2" "https://etcd3")

keyarray=( 64 256 )

for keysize in ${keyarray[@]}; do

  echo write, 1 client, $keysize key size, to leader
  ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -m PUT -n 10 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 1 -T application/x-www-form-urlencoded $leader/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo write, 64 client, $keysize key size, to leader
  ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -m PUT -n 640 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 64 -T application/x-www-form-urlencoded $leader/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo write, 256 client, $keysize key size, to leader
  ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -m PUT -n 2560 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 256 -T application/x-www-form-urlencoded $leader/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo write, 64 client, $keysize key size, to all servers
  for i in ${servers[@]}; do
    ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -m PUT -n 210 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 21 -T application/x-www-form-urlencoded $i/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo &
  done
  # wait for all booms to start running
  sleep 3
  # wait for all booms to finish
  for pid in $(pgrep 'boom'); do
    while kill -0 "$pid" 2> /dev/null; do
      sleep 3
    done
  done

  echo write, 256 client, $keysize key size, to all servers
  for i in ${servers[@]}; do
    ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -m PUT -n 850 -d value=`head -c $keysize < /dev/zero | tr '\0' '\141'` -c 85 -T application/x-www-form-urlencoded $i/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo &
  done
  sleep 3
  for pid in $(pgrep 'boom'); do
    while kill -0 "$pid" 2> /dev/null; do
      sleep 3
    done
  done

  echo read, 1 client, $keysize key size, to leader
  ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -n 100 -c 1 $leader/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo read, 64 client, $keysize key size, to leader
  ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -n 6400 -c 64 $leader/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo read, 256 client, $keysize key size, to leader
  ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -n 25600 -c 256 $leader/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo

  echo read, 64 client, $keysize key size, to all servers
  # bench servers one by one, so it doesn't overload this benchmark machine
  # It doesn't impact correctness because read request doesn't involve peer interaction.
  for i in ${servers[@]}; do
    ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -n 21000 -c 21 $i/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo
  done

  echo read, 256 client, $keysize key size, to all servers
  for i in ${servers[@]}; do
    ./boom -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -key /root/benchmark/key.pem -cert /root/benchmark/cert.pem -allow-insecure -n 85000 -c 85 $i/v2/keys/buzz/data | grep -e "Requests/sec" -e "Latency" -e "90%" | tr "\n" "\t" | xargs echo
  done

done

</code>
</pre>

**Comment by xiang90** [comment]
> the result is very confused.

Why do you think this is confusing? Do you have the result without TLS to compare the result with?

**Comment by ringtail** [comment]
Compare with the official benchmark. TLS make it to slow

**Comment by xiang90** [comment]
@ringtail What is the result of the official benchmark on your env?

**Comment by xiang90** [comment]
@ringtail You probably need to patch boom to read all the response body or the connection cannot get reused. So basically you will need to do one TLS handshake for each request. That will slow down your benchmark quite a lot.

**Comment by gyuho** [comment]
@ringtail any updates on this? As Xiang mentioned, you want to pass `--readall` flag to `boom` to reuse tcp connections, otherwise it will be slow.

**Comment by ringtail** [comment]
@gyuho .  update to v2.2.2 .much better.    
<pre>
<code>
root@iZ23uf1cf04Z:~/benchmark# ./official.sh
write, 1 client, 64 key size, to leader
Requests/sec: 54.5492 Latency distribution: 90% in 0.0203 secs.
write, 64 client, 64 key size, to leader
Requests/sec: 522.7351 Latency distribution: 90% in 0.1604 secs.
write, 256 client, 64 key size, to leader
Requests/sec: 501.2922 Latency distribution: 90% in 0.5347 secs.
write, 64 client, 64 key size, to all servers
Requests/sec: 347.5272 Latency distribution: 90% in 0.0814 secs.
Requests/sec: 289.1655 Latency distribution: 90% in 0.0958 secs.
Requests/sec: 274.7300 Latency distribution: 90% in 0.0903 secs.
write, 256 client, 64 key size, to all servers
Requests/sec: 271.1769 Latency distribution: 90% in 0.5956 secs.
Requests/sec: 268.5350 Latency distribution: 90% in 0.5575 secs.
Requests/sec: 256.2387 Latency distribution: 90% in 0.5929 secs.
read, 1 client, 64 key size, to leader
Requests/sec: 95.3512 Latency distribution: 90% in 0.0113 secs.
read, 64 client, 64 key size, to leader
Requests/sec: 598.3787 Latency distribution: 90% in 0.1409 secs.
read, 256 client, 64 key size, to leader
Requests/sec: 618.8104 Latency distribution: 90% in 0.5875 secs.
read, 64 client, 64 key size, to all servers
Requests/sec: 572.0939 Latency distribution: 90% in 0.0489 secs.
Requests/sec: 606.0264 Latency distribution: 90% in 0.0489 secs.
Requests/sec: 605.9736 Latency distribution: 90% in 0.0492 secs.
read, 256 client, 64 key size, to all servers
Requests/sec: 614.0621 Latency distribution: 90% in 0.1875 secs.
Requests/sec:                                 吗 Latency distribution: 90% in 0.1942 secs.
Requests/sec: 614.0880 Latency distribution: 90% in 0.1930 secs.
write, 1 client, 256 key size, to leader
Requests/sec: 56.7835 Latency distribution: 90% in 0.0196 secs.
write, 64 client, 256 key size, to leader
Requests/sec: 345.6743 Latency distribution: 90% in 0.1664 secs.
write, 256 client, 256 key size, to leader
Requests/sec: 566.7788 Latency distribution: 90% in 0.5544 secs.
write, 64 client, 256 key size, to all servers
Requests/sec: 280.2472 Latency distribution: 90% in 0.2043 secs.
Requests/sec: 252.1817 Latency distribution: 90% in 0.2072 secs.
Requests/sec: 156.5707 Latency distribution: 90% in 0.2039 secs.
write, 256 client, 256 key size, to all servers
Requests/sec: 322.0245 Latency distribution: 90% in 0.4410 secs.
Requests/sec: 286.1807 Latency distribution: 90% in 0.4607 secs.
Requests/sec: 225.2498 Latency distribution: 90% in 0.4416 secs.
read, 1 client, 256 key size, to leader
Requests/sec: 93.5862 Latency distribution: 90% in 0.0117 secs.
read, 64 client, 256 key size, to leader
Requests/sec: 620.5162 Latency distribution: 90% in 0.1446 secs.
read, 256 client, 256 key size, to leader
Requests/sec: 614.9794 Latency distribution: 90% in 0.5830 secs.
read, 64 client, 256 key size, to all servers
Requests/sec: 567.5796 Latency distribution: 90% in 0.0488 secs.
Requests/sec: 605.8268 Latency distribution: 90% in 0.0491 secs.
Requests/sec: 606.1919 Latency distribution: 90% in 0.0492 secs.
read, 256 client, 256 key size, to all servers
Requests/sec: 614.9418 Latency distribution: 90% in 0.1871 secs.
Requests/sec: 615.6456 Latency distribution: 90% in 0.1921 secs.
Requests/sec: 616.9257 Latency distribution: 90% in 0.1906 secs.
</code>
</pre>

**Comment by ringtail** [comment]
I'll check go 1.6 beta later.I think the problem is about the performance of TLS

**Comment by xiang90** [comment]
@ringtail It is about not creating new TLS connections each time. See my previous reply.

**Comment by ringtail** [comment]
@xiang90 yes,I'll check it .3q~

**Comment by xiang90** [comment]
@ringtail I am closing this due to low activity. Reopen if you have more data.
