### ISSUE TITLE
etcd core: there should be way to know whether etcd is initialized properly or not

### ISSUE THREAD

**Issue by gaurav36** [coreos/etcd#4183]
Hi Team,
Currently i am writing one application in Golang, i am starting etcd daemon using go code by executing exec.Command.Start("/bin/etcd") and just after starting i am using etcd application and initializing my central store. But its giving me an error that etcd is not initialized properly. If i use  < 1 second sleep time then etcd is initializing properly. Just after issuing "exec.Command.Start" i checked the status of etcd process (ps aux | grep etcd) and its properly showing its pid and process was running but initialization didn't happen properly.

I would like to know that is there any way to get to know whether etcd initialization finished or not ?

Thanks in advance :)

**Comment by gyuho** [comment]
@gaurav36 You might want to check `check-health` command here https://github.com/coreos/etcd/blob/master/Documentation/other_apis.md#checking-health-of-an-etcd-member-node. etcd has `/health` endpoint.

**Comment by gyuho** [comment]
@gaurav36 Kindly ping.

There are various endpoints you can use for your use case: https://github.com/coreos/etcd/blob/master/Documentation/api.md.

Please let me know if you have any question. Thanks,

**Comment by gaurav36** [comment]
@gyuho  

Thanks for the reply.

we are using libkv store and i am doing get call to get the /health endpoint value. 

err := Store.CheckETCDHealth("/health")

func (s *GDStore) CheckETCDHealth(p string) error {                                                               
        for {                                                                      
                pairs, e := s.List(p)                                              
                if e != nil {                                                      
                        log.Info(e.Error())                                        
                        continue                                                   
                }                                                                  
                for _, pair := range pairs {                                       
                        log.Info(pair.Value)                                       
                        if string(pair.Value) == "true" {                          
                                break                                              
                        }                                                       
                }                                                               
        }                                                                       
       return nil                                                              
} 

but i am getting continuous error key not found in store

**Comment by gyuho** [comment]
@gaurav36 You don't need bindings or client to do that. Just do:

```
curl http://YOUR_HOST:YOUR_PORT/health
```

**Comment by gaurav36** [comment]
@gyuho   i can issue "curl http://YOUR_HOST:YOUR_PORT/health" command using exec but there should be way for getting /health endpoint value.

**Comment by gyuho** [comment]
@gaurav36 I understand but `libkv` is not an official etcd client. Please file an issue to `libkv`.

And we do have health-check command in our etcdctl. Please check https://github.com/coreos/etcd/blob/master/etcdctl/command/cluster_health.go.

**Comment by gyuho** [comment]
Closing this for now. Please feel free to reach out for any other questions.

Thanks,

**Comment by gaurav36** [comment]
Thank you @gyuho  :)
issue solved :+1:

**Comment by gyuho** [comment]
No problem. I am glad that it worked. Thanks!

On Tue, Jan 12, 2016, 02:57 Gaurav Kumar Garg <notifications@github.com>
wrote:

> Thank you @gyuho <https://github.com/gyuho> :)
> issue solved [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coreos/etcd/issues/4183#issuecomment-170875422>.
>
-- 
Sincerely,
Gyu-Ho Lee
