### ISSUE TITLE
Cluster should support both ssl and non-ssl members/peers

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#4189]
Cluster should support both ssl and non-ssl members/peers

This applies to dns discovery using -discovery-srv flag

Currently we can give
_etcd-server._tcp.example.com. 300 IN SRV 0 0 2380 infra0.example.com.
or
_etcd-server-ssl._tcp.example.com 300 IN SRV 0 0 2380 infra0.example.com.

Cluster should have the ability to mix them up, may be a possible use case is a Cross DC cluster

**Comment by raoofm** [comment]
Related discussion https://github.com/coreos/etcd/issues/3693

**Comment by raoofm** [comment]
thanks @xiang90

**Comment by xiang90** [comment]
@raoofm I discussed with the team. The general agreement is that we will push etcd forward to the auto-tls direction. So etcd will enforce TLS connection someday. So I guess we will not put effort onto this one.

**Comment by philips** [comment]
@xiang90 this is right, the current thinking is that the new etcdv3 API will only exist on TLS.

With that said I agree we should support having both TLS and non-TLS communication for clients of v2 as a migration path. I imagine it would essentially look like:

ETCD_LISTEN_CLIENT_URLS="http://10.0.0.1:2379,https://10.0.0.1:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://10.0.0.1:2379,https://10.0.0.1:2379"

We would obviously need to use something like [cmux](https://github.com/soheilhy/cmux) to make this possible but I think easing this migration path onto TLS is worth the trouble.

**Comment by philips** [comment]
Oops, sorry, I thought this was for clients.

For peers I don't know if we should support this. The peers use long-lived TCP connections between themselves and there are a small number of peers. So the cost of a TLS connection is very low after the connection is established so it seems easier and more consistent to just say it is either on or off for the entire cluster.

**Comment by raoofm** [comment]
sounds good
