### ISSUE TITLE
etcdctl flags should be able to passed as env vars

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#4197]
etcdctl should function just like etcd itself: you can provide either a flag or environment variable for all config options.

https://github.com/coreos/etcd/pull/4196 adds a little bit more documentation about the current set of flags that have env vars, but it also highlights the gaps.

**Comment by xiang90** [comment]
@robszumski I think for configuration related flags, we should enable env. But we do not need to do this for all flags. For example, we have -i (interactive mode) flag for watch subcommand. Making -i an env does not really make sense to me.

/cc @heyitsanthony

**Comment by heyitsanthony** [comment]
@xiang90 Agreed; that's what `curl` does.
