### ISSUE TITLE
applying configuration changes asynchronously [documentation clarification request]

### ISSUE THREAD

**Issue by andres-erbsen** [coreos/etcd#4203]
The `etcd/raft` documentation says:

> 3\. [...] If any committed Entry has Type EntryConfChange, call Node.ApplyConfChange() to apply it to the node [...].
> 4. Call Node.Advance() to signal readiness for the next batch of updates. **This may be done at any time after step 1**, although all updates must be processed in the order they were returned by Ready.

(emphasis mine)

Does this mean that applying configuration changes can be delayed until after signaling Advance? Are there any requirements on this delay, or is it okay for an application to be arbitrarily far behind with applying committed entries? A pedantic reading of the quoted paragraph seems to imply that arbitrary delays are okay. If so, would the following sentence be accurate in the documentation: "entries (configuration changes and application data) can be applied at any time after they were committed as long as it is done in the same order at all nodes."?

**Comment by xiang90** [comment]
@andres-erbsen I am trying to make this clear on https://github.com/coreos/etcd/pull/4049. Can you please give it a look? If it does not help, I can try to make it better.

**Comment by andres-erbsen** [comment]
@xiang90 That looks like an improvement, but could you mention configuration changes explicitly as well?

Also, the new comment you wrote for Advance() (in 9767c12) doesn't make it clear whether it's okay to fall multiple steps behind in applying. It says it's okay "to call Advance before finish applying the last ready" (also, that should be "finishing applying"), but is it also okay to call Advance when there are many that you have not applied yet?

**Comment by xiang90** [comment]
@andres-erbsen 

> could you mention configuration changes explicitly as well?

Sure. I will clarify this.

> doesn't make it clear whether it's okay to fall multiple steps behind in applying.

I will clarify. 

For a quick reply, you can have arbitrary delay as long as you apply the all types committed entries in order by raft index. However, arbitrary delay is generally bad since your application state machine can be far behind raft.

For configuration changes, the turning point is when you applied the change. Note that, if you do not apply the current configuration change, no further configuration change can be committed. So delay the apply of configuration change is safe but it will have even worse effect.

**Comment by xiang90** [comment]
@andres-erbsen Basically, you can apply and run raft concurrently to get some performance gain. But try to control the gap between raft and application when you start to do so.

**Comment by xiang90** [comment]
@andres-erbsen There is another tricky part: there should be at most one unapplied configuration changes in followers log when it tries to become candidate. raft pkg does not check it. I guess if you receive a configuration change, you'd better force apply all previous entries (including the configuration) for safety.

**Comment by andres-erbsen** [comment]
1. Would it then be fair to state that a configuration change in a Ready (if any) must be applied before Advance is signaled?

2. Are you sure it is necessary to apply all previous non-configuration-change entries as well? It seems to me that as long as there is a consistent log order (which raft, when used correctly, should guarantee), it should not really matter when in real time committed entries are applied. In particular, if it was mandatory to apply them immediately, I could imagine defining this "apply" as putting the entry in a persistent log that would be processed by a separate (and asynchronous) process.

**Comment by xiang90** [comment]
> Would it then be fair to state that a configuration change in a Ready (if any) must be applied before Advance is signaled?

If there is one in ready, then it is probably fair.

> Are you sure it is necessary to apply all previous non-configuration-change entries as well? It seems to me that as long as there is a consistent log order

If you are sure that your application is OK with breaking the executing order of configuration and normal entries, then it is fine.

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/pull/4049
