### ISSUE TITLE
v3api: limit the number of keys that can be delete in deleteRange

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4207]
Deleting a large number of keys (>10k) in one txn might kill our backend. Each deletion will append a tombstone for a key and for each txn we batch all operations. Committing a txn which has a lot of ops will consume a lot of memory and might cause issues with boltdb. 

We'd better limit the number of keys to remove in on deleteRange or find a way to separate it into smaller ranges internally.

/cc @heyitsanthony @gyuho

**Comment by gyuho** [comment]
What number do we want to put as a limit? Or do we need this find out how many deletions hurt backend performance?

**Comment by heyitsanthony** [comment]
I feel like this should be handled internally. I don't think there's much a client will do for a partial deletion case aside from panicking or hammering on delete until all the keys are gone.

Why shouldn't deleterange be best-effort? If a user asks for a costly operation, that's on them.

**Comment by xiang90** [comment]
@heyitsanthony I agree that the user should be able to remove a range with little effort. But that should not blocking the entire backend as it is today. We should try our best to protect the reliability of etcd cluster.

**Comment by heyitsanthony** [comment]
It's still reliable, but availability will suffer since it can't service other ops. There could be a QoS mode that will fail large operations (DeleteRange, Txns, etc), but this is not ideal.

**Comment by xiang90** [comment]
> It's still reliable, but availability will suffer since it can't service other ops. 

Suddenly consuming a large amount of memory is not. But we can solve this internally.

**Comment by raoofm** [comment]
+1

Something consul is trying to fix https://github.com/hashicorp/consul/issues/1278

**Comment by xiang90** [comment]
@heyitsanthony Can you try to test how slow it is to delete 1M keys in a deleteRange in today's etcd?

**Comment by heyitsanthony** [comment]
@xiang90 will do

**Comment by heyitsanthony** [comment]
```
$ ./benchmark put --total=1000000 --sequential-keys=true --clients=32 --conns=8 --key-space-size=10000000 --endpoint=127.0.0.1:12378
$ time ./etcdctlv3 --endpoint=127.0.0.1:12378 delete-range `echo -e -n "\x01"`  `echo -e -n "\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
real	0m13.328s
user	0m0.008s
sys	0m0.014s
```

It seems like there's a bug in cobra that ignores empty / \x00 strings so I had to start with \x1. Assuming linear overhead, 1m keys will be ~15s on my machine.

**Comment by xiang90** [comment]
@heyitsanthony Seems it is reasonably fast... How about de-prioritizing this to 3.0 maybe?

**Comment by heyitsanthony** [comment]
@xiang90 yeah perf seems acceptable. RSS is at ~740MB which also seems OK

**Comment by heyitsanthony** [comment]
Additional data: after compaction, RSS is 903MB -- 947MB.

**Comment by xiang90** [comment]
it seems this is a non-issue. etcd is fast enough to remove large chunk of data. And we have added some warnings when etcd takes a long time to execute one command.
