### ISSUE TITLE
improve watch integration test

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4216]
- [X] make revision start as 1 (Anthony is working on this): https://github.com/coreos/etcd/pull/4217
- [X] fix header's revision comparison test (currently header test skips unmatched cases): https://github.com/coreos/etcd/pull/4218
- [X] test watch cancel operation in synced: https://github.com/coreos/etcd/pull/4223
- [X] test multiple, concurrent synced watchers on the same key: https://github.com/coreos/etcd/pull/4225
- [X] test synced, multiple events (need Txn to receive batch events): https://github.com/coreos/etcd/pull/4235
- [X] test synced watchers on multiple streams on the same key: https://github.com/coreos/etcd/pull/4237
- [X] test watch cancel operation in unsynced: https://github.com/coreos/etcd/pull/4247
- [X] test multiple concurrent unsynced watchers on the same key: https://github.com/coreos/etcd/pull/4248
- [X] test unsynced watchers on multiple streams on the same key: https://github.com/coreos/etcd/pull/4248
- [X] test unsynced, multiple events with `PUT` request: https://github.com/coreos/etcd/pull/4242
   - when a watcher gets behind, it queries multiple events and send them to receiver channel at once. We need to test this specific behavior without using `Txn`.

**Comment by xiang90** [comment]
We also need to test cancellation.

**Comment by gyuho** [comment]
Just added. Thanks.
