### ISSUE TITLE
invariant for Node.Ready/CommitedEntries

### ISSUE THREAD

**Issue by srijs** [coreos/etcd#4226]
Hi.

I'm currently trying to use the `coreos/etcd/raft` library to write a consensus-based database system. Although the documentation of the `Node` interface is quite extensive, I'm still missing a bit of information about the invariants after applying `CommitedEntries`. I'd be happy to improve the documentation and/or send a PR your way as soon as I know more.

Here's my use-case: I want my system to support conditional updates (like CAS), such as "if the state of the state machine is such-and-such, make this change, otherwise don't". Now, the easiest way to get there is to include that condition in the proposed entry, and then evaluate it when applying the entry to the state machine. However, there should be a simpler way to do it with less overhead: If it can be determined that at one point in time the state machine is 100% up to date (so `lastAppliedIndex == commitedIndex`), the leader can evaluate the condition _before_ proposing it and (if it doesn't hold) reject the write altogether before even sending the propose messages to followers. Since only an up-to-date node will be able to successfully propose changes, I can be confident that (if the local up-to-dateness between commit log and state machine holds), the change was correctly applied or rejected.

In order for that to work, however, one of these two things would need to be possible:

a) I can pass the `lastAppliedIndex` to `Node.Propose`, as a "conditional propose", so only if the current commit index equals that argument, the leader goes and proposes the change, otherwise returns early with an error.
b) There is a point in time where I can be certain that my state machine is up to date. This could be, for instance, after all the `CommitedEntries` returned from `Node.Ready` have been applied, and before `Node.Advance` is called.

My question is, is that feasible with the current state of the library, or would changes needed to be made?

**Comment by xiang90** [comment]
> the leader can evaluate the condition before proposing it 

This is not a common use case.  But give the decoupled design of etcd/raft, this should not be hard to implement. 

First, the leader should be able to record all the proposals before letting it go to raft. This part should be straightforward forward. 

The tricky part is that when there is a leader election, the new leader has to get all previous pending proposals and record them since the previous proposals were not proposed through it. We might need a hook for that part. I can dig into it.

But my question is that why do you think it is cost-efficient to add this feature. Have you tested how much overhead it would bring you if you just let everything go through raft and evaluate when it is committed?

**Comment by srijs** [comment]
Sure. I haven't done any benchmarks yet, but I'm planning on having a decent number of database clients competing for a conditional update, to the point where a CAS _failure_ will be the common case, and want to achieve a low latency to reduce contention, enabling them to try again as soon as possible.

I'm unsure whether I understand your comment about the hook we need in case of a leader election. Is it not true that when a new leader gets elected, it either has a previously proposed entry already committed, or it will be discarded (because the term has increased since)?

**Comment by xiang90** [comment]
> or it will be discarded (because the term has increased since)? 

The newly elected leader will only discard the conflict ones. Say the previous leader A is at term 1, and it proposed 10 entries, none of them get committed. Follower B receives 8 of all proposals. Then leader A dies, and follower B promotes as leader. The 9th proposal will have term 2 and will overwrite the previous 9th entry which has term 1. But the pervious 8 entries of term 1 will get committed.

**Comment by xiang90** [comment]
> but I'm planning on having a decent number of database clients competing for a conditional update, to the point where a CAS failure will be the common case, and want to achieve a low latency to reduce contention, enabling them to retry as soon as possible.

If that is the case you want to optimize

> b) There is a point in time where I can be certain that my state machine is up to date. This could be, for instance, after all the CommitedEntries returned from Node.Ready have been applied, and before Node.Advance is called.

will not work. Waiting for ALL previous proposal get applied will introduce additional latency. This conflicts with your proposal. If you want to reduce disk IO for writing log entries or network IO for replication, then it probably fits you well.

**Comment by xiang90** [comment]
@srijs I would suggest you to do some benchmark first. You do not need raft at all to begin in my opinion.

Probably just assume a commit latency like 10ms and a reject latency like 100us, then for any given proposal rate and conflict rate we can know the latency reduction.

If you believe it worth the effort and you want to make it happen, I think we probably can achieve that.

**Comment by srijs** [comment]
Thanks for you advise. It's great to hear that it is feasible to implement if necessary.

I will start out with the condition evaluation on read (i.e. after commit) first and see how far I can take that in terms of latency and congestion control.

Feel free to close this issue, I will open a new one and reference this when I have more to report :)

**Comment by xiang90** [comment]
> Thanks for your advice. It's great to hear that it is feasible to implement if necessary.

There are still some trick issues we need to think carefully before implementing this. For example, the CAS might be false positive when there is a leader election happens right after the reporting. But it wont be a huge issue in general since the failure rate should be low and client should prepare for retry anyway. There might be other minor things to consider. 

But, yea, let's talk more when you have more details. Thanks!
