### ISSUE TITLE
HTTP query: no keepalive support? as res.headers["Connection"] is returning nil

### ISSUE THREAD

**Issue by louiekwan** [coreos/etcd#4233]
Trying to use an OpenResty/ ngx_lua http client, lua-resty-http 

etcd seems not to have keepalive support yet. 

Just tried....
ngx.say(res.headers["Connection"]) is returning me a nil 
and the httpc:set_keepalive() is returning nil, err.

May be the COREOS ETCD thinks that it is too heavy too keep the permanent connection? Any insight?

**Comment by xiang90** [comment]
@louiekwan I think in HTTP 1.1, all connection are keepalive by default. http://tools.ietf.org/html/rfc7230#section-6.3
