### ISSUE TITLE
Should ETCD_VERSION be considered as a recognized environment variable?

### ISSUE THREAD

**Issue by danlenar** [coreos/etcd#4234]
Should ETCD_VERSION be considered as a recognized and used environment variable?
There are a couple Dockerfiles that set ETCD_VERSION as an env to help build the image.

docker run -it --env ETCD_VERSION=2.2.4 quay.io/coreos/etcd:v2.2.4                                                                                                                                                          
2016-01-19 19:49:41.046653 I | flags: recognized and used environment variable ETCD_VERSION=2.2.4
2016-01-19 19:49:41.046752 C | etcdmain: invalid value "2.2.4" for ETCD_VERSION: strconv.ParseBool: parsing "2.2.4": invalid syntax

**Comment by gyuho** [comment]
@danlenar Could you give us more clarification? I don't see any use case of `ETCD_VERSION`
when you can just specify the version at the end.

**Comment by danlenar** [comment]
@gyuho I accidentally discovered this issue with my own custom dockerfile for etcd, which uses ETCD_VERSION to set the version I want to build etcd.

For example, I only use ETCD_VERSION in the following case:

FROM centos:7
ENV ETCD_VERSION 2.2.4
RUN git clone http://github.com/coreos/etcd.git /go/src/github.com/coreos/etcd \
    && cd /go/src/github.com/coreos/etcd \
    && git checkout $ETCD_VERSION \
    && ....

Since I didn't unset the value for ETCD_VERSION in my dockerfile, etcd complains about ETCD_VERSION being a recognized environment variable and won't start. I wanted to check if this is desired behavior, since I would have figured that etcd would just ignore my usage of ETCD_VERSION that comes from my Dockerfile.

**Comment by gyuho** [comment]
Yeah the `ETCD_VERSION` flag should be ignored, but it seems to error.
I am not sure if this is an expected behavior. Defer to @xiang90.

https://github.com/coreos/etcd/blob/master/pkg/flags/flag.go#L83-L88 grabs all environment variables and tries to set it in `flag.Flag` object, and this can fail when you try to parse string (e.g. `2.2.4`) to boolean value for `usedEnvKey := make(map[string]bool)` defined a few lines above.

**Comment by xiang90** [comment]
@danlenar I feel this is a documentation issue. Is it possible for you not to set ETCD_VERSION?

**Comment by xiang90** [comment]
I am going to close this. Please reopen if you still feel etcd should ignore ETCD_VERSION. We might change this if more users report the same issue.
