### ISSUE TITLE
Remove ETCD_NAME variable in systemd set to machine-id

### ISSUE THREAD

**Issue by quentinsch** [coreos/etcd#4244]
I use CoreOS to PXE-boot the OS and use a custom script to set all the parameters. I am unable to use custom hostnames or any custom variable because ETCD_NAME is set to the machine-id. Since /usr is read-only the systemd script is not editable for customization and this is a problem in a set up like I use.
I want to set the name variable by myself instead of using the machine id.

**Comment by philips** [comment]
You should be able to use a systemd drop-in to fix this. https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html

**Comment by quentinsch** [comment]
Ok, I'll try that, but I was wondering why it was set in the default systemd config anyway.

**Comment by crawford** [comment]
We use the machine ID as the name because, in its absence, etcd uses "default" as the name.  This naming conflict doesn't work well when you have more than one etcd node in your cluster.

**Comment by xiang90** [comment]
@quentinsch I think @crawford got a reasonable answer for you. Closing due to low activity.

**Comment by quentinsch** [comment]
@xiang90, yes I understand. We use CoreOS in a PXE only environment (without installing it) and we could manage the variable with a drop-in through the cloud config, but if you use cloud config as a script it is a challenge to replace this variable.
Anyway, thanks for the explanations.
