### ISSUE TITLE
Key with \ in it's name creates a folder

### ISSUE THREAD

**Issue by petterek** [coreos/etcd#4245]
This is probably not an error, but i file it anyway. 
If you try to make a key e.q http%3A%2F%2Fsome%3A1010 (http://some:1010) 
this will make a folder named http and then a key named some:1010 

Just an observation

**Comment by gyuho** [comment]
@petterek 

Are you requesting through `curl`?

Please see https://github.com/coreos/etcd/issues/3845.

> need to encode as in URL when we send request through curl.

**Comment by petterek** [comment]
Actually I'm using .net 

    Dim content As New FormUrlEncodedContent(value)
    Dim result = webclient.PutAsync(info.ServiceIdentifier & "/" & System.Web.HttpUtility.UrlEncode(info.EndPointAddress) & "?dir=false&ttl=" & info.Heartbeat.ToString, content).Result

**Comment by gyuho** [comment]
@petterek Can you post your raw http request?

**Comment by gyuho** [comment]
We has a whole conversation on this here https://github.com/coreos/etcd/issues/669.

https://github.com/coreos/etcd/issues/669#issuecomment-39377135

> I absolutely agree we should restrict slashes in keynames. But, we need to tell a user how they can encode slashes and other unacceptable names.

> The root question of this bug is whether URL encoding is an acceptable encoding of slashes for us.

> I think we need to think about it a bit more. Is it too much trouble for you to encode the slashes as - or something for now? That will be backwards compatible and solve the issue for you for now.


I will defer to @philips and @jonboulle 

/cc @xiang90

**Comment by petterek** [comment]
ok for me
