### ISSUE TITLE
etcdctl mk not behaving as indicated in docs

### ISSUE THREAD

**Issue by mwhooker** [coreos/etcd#4255]
```
etcdctl --version
etcdctl version 2.2.0
```

Hi all,

I hope I'm interpreting the [docs](https://github.com/coreos/etcd/blob/master/etcdctl/README.md) correctly. the readme says

> Create a new key `/foo/bar`, only if the key did not previously exist:

> ```
$ etcdctl mk /foo/new_bar "Hello world"
Hello world
```

reading this, I expect calling `etcdctl mk` twice with the same key to fail the second time. However, I can call it as many times as I want, and the key will always hold the value of the last invocation.

```
$ etcdctl mk /foo/new_bar "Hello world"
Hello world
$ etcdctl mk /foo/new_bar "Hello world2"
Hello world2
$ etcdctl get /foo/new_bar
Hello world2
```

**Comment by mwhooker** [comment]
in case there's a better way to do this, my use-case is leader election. I have a homogenous group of machines, and I want some action to happen only on one of them. I'm hoping to have all of them try to grab the same key, and let only the host that manages to acquire the key do the work.

**Comment by xiang90** [comment]
@gyuho Can you please take a look?

**Comment by gyuho** [comment]
Ok I will take a look at this. Thanks for reporting @mwhooker

**Comment by gyuho** [comment]
@mwhooker Please update your `etcdctl` later than `2.2.0`, which came out on  Sep 10, 2015.

It works for me.

```
./etcdctl --version
etcdctl version 2.3.0-alpha.0+git

./etcdctl  mk a b

./etcdctl  mk a b
Error:  105: Key already exists (/a) [8]

./etcdctl mk /foo/new_bar "Hello world"
Hello world

./etcdctl mk /foo/new_bar "Hello world2"
Error:  105: Key already exists (/foo/new_bar) [10]

```

If you are still having the same issue, please let us know.

**Comment by mwhooker** [comment]
thanks for taking a look all
