### ISSUE TITLE
Aws fresh spawn of CoreOS - etcd2 single node does not start.

### ISSUE THREAD

**Issue by rradecki** [coreos/etcd#4288]
Hi.

I try to initialize CoreOS:

$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=835.11.0
VERSION_ID=835.11.0
BUILD_ID=
PRETTY_NAME="CoreOS 835.11.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

$ etcd2 --version
etcd Version: 2.2.0
Git SHA: e4561dd
Go Version: go1.4.2
Go OS/Arch: linux/amd64

on Aws. I am using ami-7e72c70d for Ireland and UserData:

#cloud-config

coreos:
  etcd2:
    discovery: "https://discovery.etcd.io/aa..."
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

ssh_authorized_keys:
  - "ssh-rsa ..."

I generated the token for "discovery" using https://discovery.etcd.io/new?size=1 url.
When I start etcd2 using systemctl start etcd2 I get in journalctl:

Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal systemd[1]: Starting etcd2...
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.82:2379
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/aa..
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1200
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.82:2380
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.0.0.82:2380,http://10.0.0.82:7001
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: recognized and used environment variable ETCD_NAME=xxx
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: etcd Version: 2.2.0
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: Git SHA: e4561dd
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: Go Version: go1.4.2
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: Go OS/Arch: linux/amd64
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: setting maximum number of CPUs to 1, total number of available CPUs is 2
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: the server is already initialized as member before, starting as etcd member...
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: listening for peers on http://10.0.0.82:2380
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: listening for peers on http://10.0.0.82:7001
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: listening for client requests on http://0.0.0.0:2379
Jan 26 15:44:21 ip-10-0-0-82.eu-west-1.compute.internal etcd2[949]: listening for client requests on http://0.0.0.0:4001
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal unknown[949]: stopping listening for client requests on http://0.0.0.0:4001
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal unknown[949]: stopping listening for client requests on http://0.0.0.0:2379
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal unknown[949]: stopping listening for peers on http://10.0.0.82:7001
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal unknown[949]: stopping listening for peers on http://10.0.0.82:2380
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal unknown[949]: context deadline exceeded
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal systemd[1]: Failed to start etcd2.
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal systemd[1]: etcd2.service: Unit entered failed state.
Jan 26 15:44:26 ip-10-0-0-82.eu-west-1.compute.internal systemd[1]: etcd2.service: Failed with result 'exit-code'.

So I do not see a clean source of the problem.

$ cat /usr/lib64/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
LimitNOFILE=40000
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target

$ cat /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.82:2379"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/aa.."
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.82:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001"
Environment="ETCD_LISTEN_PEER_URLS=http://10.0.0.82:2380,http://10.0.0.82:7001"

Can someone help?

BR,
Rafal.

**Comment by xiang90** [comment]
This is already fixed in a later version of etcd. (>2.2.1)

**Comment by rradecki** [comment]
I changed CoreOS version to beta to get etcd in version 2.2.3:

$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=899.5.0
VERSION_ID=899.5.0
BUILD_ID=2016-01-22-1100
PRETTY_NAME="CoreOS 899.5.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

$ etcd2 --version
etcd Version: 2.2.3
Git SHA: 05b564a
Go Version: go1.4.3
Go OS/Arch: linux/amd64

User Data:

#cloud-config

coreos:
  etcd2:
    discovery: "https://discovery.etcd.io/aa..."
    advertise-client-urls: "http://$private_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    listen-client-urls: "http://127.0.0.1:2379,http://127.0.0.1:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

ssh_authorized_keys:
  - "ssh-rsa AAAA..."

I got https://discovery.etcd.io/aa... after invoking discovery.etcd.io/new?size=1 and am starting only one node.

When I try to start etcd2 I get in journalctl:

-- Logs begin at Wed 2016-01-27 13:30:17 UTC. --
Jan 27 13:31:59 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: Starting Garbage Collection for rkt...
Jan 27 13:31:59 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: Started Garbage Collection for rkt.
Jan 27 13:32:08 ip-10-0-0-64.eu-west-1.compute.internal systemd-timesyncd[607]: Timed out waiting for reply from 86.43.77.42:123 (3.coreos.pool.ntp.org).
Jan 27 13:32:14 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: Started OpenSSH per-connection server daemon (10.0.0.204:50455).
Jan 27 13:32:14 ip-10-0-0-64.eu-west-1.compute.internal sshd[871]: Accepted publickey for core from 10.0.0.204 port 50455 ssh2: RSA SHA256:xo0LdLyurs/Srf551ozDDbkZv6fWrSprHfKdRqHJ8ds
Jan 27 13:32:16 ip-10-0-0-64.eu-west-1.compute.internal locksmithd[646]: [etcd.service etcd2.service] are inactive
Jan 27 13:32:16 ip-10-0-0-64.eu-west-1.compute.internal locksmithd[646]: Unlocking old locks failed: [etcd.service etcd2.service] are inactive. Retrying in 1m20s.
Jan 27 13:32:18 ip-10-0-0-64.eu-west-1.compute.internal sudo[880]:     core : TTY=pts/1 ; PWD=/home/core ; USER=root ; COMMAND=/bin/su -
Jan 27 13:32:18 ip-10-0-0-64.eu-west-1.compute.internal su[880]: Successful su for root by root
Jan 27 13:32:18 ip-10-0-0-64.eu-west-1.compute.internal su[880]: + /dev/pts/1 root:root
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal polkitd[662]: Registered Authentication Agent for unix-process:888:14758 (system bus name :1.31 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: Starting etcd2...
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.64:2379
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/aa...
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1200
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.64:2380
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://127.0.0.1:2379,http://127.0.0.1:4001
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10.0.0.64:2380,http://10.0.0.64:7001
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: recognized and used environment variable ETCD_NAME=87f09ea6b18f4077982b09dcfbbacdec
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: etcd Version: 2.2.3
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: Git SHA: 05b564a
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: Go Version: go1.4.3
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: Go OS/Arch: linux/amd64
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: setting maximum number of CPUs to 1, total number of available CPUs is 2
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: listening for peers on http://10.0.0.64:2380
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: listening for peers on http://10.0.0.64:7001
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: listening for client requests on http://127.0.0.1:2379
Jan 27 13:32:43 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: listening for client requests on http://127.0.0.1:4001
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: stopping listening for client requests on http://127.0.0.1:4001
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal polkitd[662]: Unregistered Authentication Agent for unix-process:888:14758 (system bus name :1.31, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: stopping listening for client requests on http://127.0.0.1:2379
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: stopping listening for peers on http://10.0.0.64:7001
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: stopping listening for peers on http://10.0.0.64:2380
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: failed to join discovery cluster (context deadline exceeded)
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: discovery token https://discovery.etcd.io/aa... was used, but failed to bootstrap the cluster.
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal etcd2[893]: please generate a new discovery token and try to bootstrap again.
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: Failed to start etcd2.
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: etcd2.service: Unit entered failed state.
Jan 27 13:32:48 ip-10-0-0-64.eu-west-1.compute.internal systemd[1]: etcd2.service: Failed with result 'exit-code'.
Jan 27 13:32:51 ip-10-0-0-64.eu-west-1.compute.internal systemd-timesyncd[607]: Timed out waiting for reply from 54.72.7.175:123 (0.coreos.pool.ntp.org).

So overall etcd2 does not start correctly also in this case. Can someone tell what should be done?

**Comment by xiang90** [comment]
@rradecki Does your machine have access to discovery.etcd.io?
