### ISSUE TITLE
TestApplySnapshotAndCommittedEntries failed on travis

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4296]
```
FAIL: TestApplySnapshotAndCommittedEntries (0.02s)
server_test.go:1051: len(action) = 1, want 2
```

/cc @heyitsanthony Not sure how this happens. I remember we do wait until there are enough events...

**Comment by xiang90** [comment]
Hmm... Probably we should check error at https://github.com/coreos/etcd/blob/master/etcdserver/server_test.go#L1047

**Comment by heyitsanthony** [comment]
The error says that it expected some length but got a shorter one. It won't be helpful.

I see the bug, will post PR with fix.
