### ISSUE TITLE
etcd fails to start

### ISSUE THREAD

**Issue by tobilg** [coreos/etcd#4303]
When I try to use my `cloud_config`

```
...
coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: https://discovery.etcd.io/{here_is_my_token}
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://192.168.200.168:2379
    initial-advertise-peer-urls: http://192.168.200.168:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://192.168.200.168:2380,http://192.168.200.168:7001
```

 to start etcd, it constantly fails:

```
$ sudo systemctl status etcd2.service
â etcd2.service - etcd2
   Loaded: loaded (/usr/lib64/systemd/system/etcd2.service; disabled; vendor preset: disabled)
  Drop-In: /run/systemd/system/etcd2.service.d
           ââ20-cloudinit.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2016-01-27 12:51:28 UTC; 1s ago
  Process: 15890 ExecStart=/usr/bin/etcd2 (code=exited, status=1/FAILURE)
 Main PID: 15890 (code=exited, status=1/FAILURE)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/etcd2.service
```
Service logs:
```
$ sudo journalctl -u etcd2.service 
Jan 27 11:47:02 coreos-node-2 systemd[1]: Starting etcd2...
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.200.168:2379
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/0e4e76f0cc9f23f066765f42085553e7
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.200.168:2380
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.200.168:2380,http://192.168.200.168:7001
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: recognized and used environment variable ETCD_NAME=8dbf97f4282d4a8298459f1421a6b577
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: etcd Version: 2.2.3
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: Git SHA: 05b564a
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: Go Version: go1.4.3
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: Go OS/Arch: linux/amd64
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: setting maximum number of CPUs to 1, total number of available CPUs is 2
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: listening for peers on http://192.168.200.168:2380
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: listening for peers on http://192.168.200.168:7001
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: listening for client requests on http://0.0.0.0:2379
Jan 27 11:47:02 coreos-node-2 etcd2[1343]: listening for client requests on http://0.0.0.0:4001
Jan 27 11:47:03 coreos-node-2 systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Jan 27 11:47:03 coreos-node-2 systemd[1]: Failed to start etcd2.
Jan 27 11:47:03 coreos-node-2 systemd[1]: etcd2.service: Unit entered failed state.
Jan 27 11:47:03 coreos-node-2 systemd[1]: etcd2.service: Failed with result 'exit-code'.
```

CoreOS version info:
```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=899.5.0
VERSION_ID=899.5.0
BUILD_ID=2016-01-22-1100
PRETTY_NAME="CoreOS 899.5.0"
```

I'm puzzled about what could be the actual problem...

**Comment by gyuho** [comment]
@tobilg We need the full configuration to see what could be wrong. Please see https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

As you can see `coreos-node-2 systemd[1]:`, your cloud-config might be wrong.
Did you run in Google cloud? This is the sample configuration that works in google cloud.

```
coreos:
  etcd2:
    # https://discovery.etcd.io/new?size=3
    discovery: https://discovery.etcd.io/YOUR_TOKEN
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
```

**Comment by tobilg** [comment]
@gyuho Thanks for the feedback. Unfortunately I don't really see a difference in the configuration other than the usage of $private_ipv4. My cluster is running in bare metal, so I can't use this as of the docs at

https://coreos.com/os/docs/latest/cloud-config.html

> Note: The $private_ipv4 and $public_ipv4 substitution variables referenced in other documents are only supported on Amazon EC2, Google Compute Engine, OpenStack, Rackspace, DigitalOcean, and Vagrant.

Where exactly so you see a problem?

**Comment by gyuho** [comment]
@tobilg Sorry for late response. Actually there's another issue with almost the same behavior as you https://github.com/coreos/etcd/issues/4308. That thread will give you a better idea.

This looks like `systemd` configuration issue. Can you just execute `etcd` directly, without using `systemd`? As you see, it crashes **in** `systemd`.

Please let me know if you have any other question.

Thanks,

**Comment by gyuho** [comment]
Kindly ping @tobilg. Did you get it to work? Is there anything else that we can help?

**Comment by tobilg** [comment]
@gyuho I read through the issue you linked. As I showed in my configuration above, the https://github.com/coreos/etcd/issues/4308#issuecomment-179995493 stating that `--advertise client needs to be set to http://host_ip:4001` is already there (`192.168.200.168` *is* the `host_ip`)...

Also, I think my config is consistant with the [CoreOS docs](https://coreos.com/os/docs/latest/cloud-config.html#coreos).

**Update**: If I use my IP address instead of `0.0.0.0`with `listen-client-urls` and use a new discovery token, I'm successful starting my etcd2 cluster again.

**Comment by gyuho** [comment]
Great that you figured out. Please let us know if there's anything else that we can improve in etcd side (docs, error logs).

Thanks.

**Comment by tobilg** [comment]
@gyuho Thanks again... I think it might be waothwhile to check if the CoreOS docs I linked in my last comment are valid with current versions of etcd.

I also wonder if there was a change in etcd, because I run my production cluster with the same settings like my test cluster (where I had these problems). The only difference is that the production runs on the latest stable version of CoreOS, and my test cluster runs on the latest beta version.

**Comment by gyuho** [comment]
Ok we will check. Thanks.
