### ISSUE TITLE
Steps for upgrading 2.1->2.2 with more than 100MB of data

### ISSUE THREAD

**Issue by zerojames** [coreos/etcd#4310]
The 2.1 -> 2.2 upgrade documentation states "If you have a data size larger than 100MB you should contact us before upgrading, so we can make sure the upgrades work smoothly".

What steps need to be taken for a successful upgrade with more than 100MB of data?

**Comment by xiang90** [comment]
@zerojames The main issue is that while upgrading if etcd is under high load, the restarted member might require a snapshot. etcd does not handle large snapshot well under very high load for v2 backend. 

So if you have a large snapshot, please make sure the etcd cluster is not under high writes pressure (<500 requests/second) during the upgrade.

Sorry for the inconvenience. This issue has been solved by our v3 backend.

**Comment by zerojames** [comment]
Thanks for the explanation.
