### ISSUE TITLE
etcd needs a secondary port to allow listening to both secure and insecure client connections

### ISSUE THREAD

**Issue by omkensey** [coreos/etcd#4311]
Currently the recommended configuration for etcd clustering uses TLS communications on the IANA-registered port 2379/tcp.  If, however, clients that do not support TLS need to be allowed to connect to etcd alongside TLS-capable clients, there are a few options, none ideal:

* Pick an arbitrary secondary port and bind it to listen to insecurely.  This is strongly frowned on as many times those ports will conflict with IANA-registered ports.  It also leads to a situation where there is no consistency in the full set of ports etcd can be expected to listen on.
* Run an etcd proxy on the client host that binds 2379/tcp and listens insecurely on localhost only.  This breaks the common expectation that HTTPS and HTTP will always be listening on different ports.
* Run completely insecurely.

I propose we apply for a new IANA port (12379/tcp is currently unassigned and was suggested by @xiang90) and modify our standard usage as follows: 
* HTTPS clients always connect on 2379/tcp
* HTTP clients always connect on 12379/tcp (or whatever other port we end up getting assigned).

It is probably not necessary to have a secondary port for peers, since I can't imagine a situation in which some peers can connect via TLS and some can't, but if we do think we should have it, 12380/tcp is also currently unassigned.

**Comment by xiang90** [comment]
@omkensey Now etcd can listen on the same port for both TLS and non-TLS. 

I guess some people might still want the TLS and non-TLS separation though. Not sure if we need another official port.

/cc @philips @brianredbeard Opinions?

**Comment by omkensey** [comment]
I think if that's working, we should just scrub all references to other ports in the docs, stop etcd listening on those ports by default, and forget they were ever used.

**Comment by xiang90** [comment]
@omkensey Sure. We will check if we suggest other ports to users and we will add the tls/non-tls on the same port doc soon.

**Comment by philips** [comment]
The current practice of having TLS and non-TLS on the same port, if configured, is fine with me.

**Comment by brianredbeard** [comment]
+1 to @omkensey and @philips comments
