### ISSUE TITLE
Does etcd client have interface instead of AddChild in go-etcd?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#4319]
We want use official etcd client instead of go-etcd in my program. My program use go-etcd ```AddChild``` function, I do not find it in official etcd client, does it have other interface instead of ```AddChild```

**Comment by jonboulle** [comment]
Yep, check out CreateInOrder, part of the KeysAPI interface:
https://github.com/coreos/etcd/blob/7adb8442ba7a1b7800ab939fbe9aabfeafd3e4ae/client/keys.go#L120

**Comment by YuleiXiao** [comment]
@jonboulle 
```AddChild``` comment is ```// Add a new file with a random etcd-generated key under the given path.```

but ```CreateInOrder``` comment is ```// CreateInOrder is used to atomically create in-order keys within the given directory.```

Is it the same?

**Comment by jonboulle** [comment]
Yes. The fact that the "random" key is generated by the etcd server is what
provides the automatic atomic creation.
