### ISSUE TITLE
etcd discovery problem

### ISSUE THREAD

**Issue by imtheghoul** [coreos/etcd#4347]
Hello!
I can't understand how to bootstrap cluster in according to guide https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#etcd-discovery.
When I do "curl -X PUT https://192.168.7.9/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/_config/size -d value=2" I have got: "curl: (7) Failed to connect to 192.168.7.9 port 443: Connection refused"
Also tried with self-signed certificates. Same for http.
I tried to run etcd before curl with command from first message and also tried just run "etcd &" - curl doesn't works. It works only this way: "curl -X PUT http://127.0.0.1:4001/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83/_config/size -d value=2", but then how can I add a remote member if on IP 192.168.7.9 any requests is refused?
Also I don't understand what is this ID 6c007a14875d53d9bf0ef5a6fc0257c817f0fb83. Can I use any ID instead this, or maybe I must to generate it somehow?
Unfortunately I can't find enough information about etcd cluster. Most helpful was youtube video "CoreOS: Bootstrapping etcd", but it's don't touched case with personal discovery system.
Grateful for helping.

**Comment by gyuho** [comment]
Documentation on discovery can be found here https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#etcd-discovery.

And if you want to set up TLS-enabled cluster, please read https://github.com/coreos/etcd/blob/master/Documentation/security.md.

Your connection is refused because you ` just run "etcd &" ` without any security flags.

But it's still not clear what you did. Could you share the full command?

**Comment by imtheghoul** [comment]
Yes, sorry.
My command on first node (192.168.7.9) is:
etcd -name infra0 -initial-advertise-peer-urls http://192.168.7.9:2380 \
-listen-peer-urls http://192.168.7.9:2380 \
-listen-client-urls http://192.168.7.9:2379,http://127.0.0.1:2379 \
-advertise-client-urls http://192.168.7.9:2379 \
-discovery https://192.168.7.9/v2/keys/discovery/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83

And as you can read in my message, I've read clustering.md#etcd-discovery and was failed to reproduce.
Also actually I don't want to use secure connection, but don't know how to bootstrap anyway.

**Comment by gyuho** [comment]
@imtheghoul You have to generate discovery token first. Please click https://discovery.etcd.io/8c5aee1b8e744fe9277d63d8d1b8e7bd.

But your token is not found  https://discovery.etcd.io/6c007a14875d53d9bf0ef5a6fc0257c817f0fb83.

And make sure generate with the size of cluster: `https://discovery.etcd.io/new?size=3`.

**Comment by imtheghoul** [comment]
@gyuho 
> You have to generate discovery token first. 
But according the guide, I have a possibility to make own etcd discovery service, isn't? https://discovery.etcd.io is a public service and it does not acceptable to our security policy.

**Comment by gyuho** [comment]
@imtheghoul Yes, https://discovery.etcd.io is a public service. You can specify your own DNS server with `discovery` or  `discovery-srv` flag.

**Comment by imtheghoul** [comment]
@gyuho DNS is another way of discovery.
Could you please explain a few moments? I found https://github.com/coreos/etcd/blob/master/Documentation/discovery_protocol.md (last week this page was 404). Quite understandable, but I still can't catch: to bootstrap cluster, first of all we have to set cluster size by curl -X PUT http://example.com/v2/keys/_etcd/registry/${UUID}/_config/size -d value=${cluster_size}. Let's say, I have UUID environment, instead ${cluster_size} I set 3 and I want to set it on localhost. But...
`$ curl -X PUT http://127.0.0.1/v2/keys/_etcd/registry/${UUID}/_config/size -d value=2
curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused`
Ok, etcd is stopped, maybe it has to be started (guide doesn't says)? So I start it:
`$ etcd >> etcdlog 2>&1 &`
I'm repeating command and still get:
`curl: (7) Failed to connect to 127.0.0.1 port 80: Connection refused`
Hmm... Maybe etcd is really doesn't listening to port 80? But it's listening to 4001 for sure. I change my command and it's passed:
`$ curl -X PUT http://127.0.0.1:4001/v2/keys/_etcd/registry/${UUID}/_config/size -d value=3
{"action":"set","node":{"key":"/_etcd/registry/1353ccbf-08cd-4e20-b352-b970dee50263/_config/size","value":"3","modifiedIndex":3,"createdIndex":3}}`
What should I do now? Restart etcd with parameter "-discover"? I can't do that, because:
`etcd: dial tcp 127.0.0.1:4001: connection refused` - of course! Etcd daemon is stopped as far!
Ok. Run etcd again, without parameters. Maybe I should connect from another node? But how? Even if I want connect to my eth0 instead localhost (for example: "curl -L http://192.168.0.1:4001/version") - it refuses to connect.
So, main questions is:
1. What is the order of actions when I'm specifying the expected cluster size?
2. How etcd should listen to 80 port?
3. How to run etcd on eth0 instead localhost? It should listen 192.168.0.1 to catch connections from another hosts in network.
The answers I can't find in manuals that I've been mentioned.
Thank you for your attention.

**Comment by gyuho** [comment]
@imtheghoul If you don't have any web server running in your localhost, you cannot `curl` to your loopback ip `127.0.0.1`. etcd is not a DNS server. Not a web server either. You need to set up your own discovery server with your own DNS configuration in your local machine.

**Comment by xiang90** [comment]
@imtheghoul 

Please try to use the public discovery service to start with https://github.com/coreos/etcd/blob/master/Documentation/clustering.md#public-etcd-discovery-service.

If you want to use a private one, you have to setup your etcd cluster first.
