### ISSUE TITLE
integration: TestV3PutMissingLease times out

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4350]
- https://semaphoreci.com/coreos/etcd/branches/pull-request-4348/builds/8
- https://semaphoreci.com/coreos/etcd/branches/pull-request-4348/builds/9
- https://semaphoreci.com/coreos/etcd/branches/master/builds/359
- https://semaphoreci.com/coreos/etcd/branches/master/builds/360

**Comment by gyuho** [comment]
The test is hanging in:

```go
		// ignore bad lease in failure on success txn
		func() {
			txn := &pb.TxnRequest{}
			rreq := &pb.RangeRequest{Key: []byte("bar")}
			txn.Success = append(txn.Success, &pb.RequestUnion{
				Request: &pb.RequestUnion_RequestRange{
					RequestRange: rreq}})
			txn.Failure = append(txn.Failure, &pb.RequestUnion{
				Request: &pb.RequestUnion_RequestPut{
					RequestPut: preq}})
			if tresp, err := kvc.Txn(context.TODO(), txn); err != nil {
				t.Errorf("failed good txn. req: %v. resp: %v", txn, tresp)
			}
		},
```

Possibly related to https://github.com/coreos/etcd/commit/69abdf8144086c85aa47194b4e28b14eb614c196.

**Comment by gyuho** [comment]
Just confirmed that it's from the `applyRange` response header change. Will investigate more.

**Comment by xiang90** [comment]
the pr is reverted. so this is fixed.
