### ISSUE TITLE
offline migration tool

### ISSUE THREAD

**Issue by philips** [coreos/etcd#4365]
etcd has a live rolling upgrade policy that generally supports X.(N).* to X.(N-1).* upgrades. But, in cases where a user might have an old version of etcd (say 2.0.0), doesn't want to roll through a large number of releases (say to 2.5.0), and can withstand an outage we should provide an offline migration tool that can be ran on every machine and then the cluster can be brought back up.

This would require a few things:

- [ ] A test set of older versions of etcd WAL/snap directories. Perhaps stored in git or a tool that can generate old versions.
- [ ] A new tool, perhaps `etcd offline-migrate`, that could migrate from 2.0 WAL/snap directories to the current version.
- [ ] Documentation on how to use this tool and how it differs from the live upgrade tool.

Without this tool users are rather stuck in having to do N*machines number of upgrades to use the latest and best version of etcd. With this tool they will have an easier experience getting onto the latest release.

**Comment by philips** [comment]
cc @crawford

**Comment by raoofm** [comment]
+1

**Comment by xiang90** [comment]
It seems that no one is really interested enough to implement it. On the other side, for etcd3 the snapshot is already decoupled with WAL and has version attached. We now should support snapshot recover across version in etcd3. So I am wondering if we should just close this issue.

/cc @philips @heyitsanthony @gyuho

**Comment by xiang90** [comment]
Closing. Will reopen if anyone is still interested in working on this for etcd2.
