### ISSUE TITLE
Use only 127.0.0.1 access, using the host IP (192.xx.xx.xx) can not access

### ISSUE THREAD

**Issue by 247687009** [coreos/etcd#4377]
![image](https://cloud.githubusercontent.com/assets/5880317/12744630/3d68ac0e-c9d0-11e5-9bc7-1d98016c4925.png)

**Comment by xiang90** [comment]
@247687009 etcd listend on 127.0.0.1:2379. So you cannot access it via other ip. Try to listen on 0.0.0.0 or the IP you want.

**Comment by 247687009** [comment]
How to configure ? Thanks!

**Comment by xiang90** [comment]
@247687009 https://github.com/coreos/etcd/blob/master/Documentation/configuration.md#-listen-client-urls

**Comment by wuyongxiu** [comment]
How to configure? The link has expired. @xiang90

**Comment by heyitsanthony** [comment]
@wuyongxiu https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--listen-client-urls

**Comment by wuyongxiu** [comment]
@heyitsanthony  Thanks for your reply. I have followed the instruction to set the env ETCD_LISTEN_CLIENT_URLS and ETCD_ADVERTISE_CLIENT_URLS, but the port can't be accessed by other hosts  yet. I don't know what I did was wrong.
![36](https://cloud.githubusercontent.com/assets/17407521/17390796/e2ad6a94-5a42-11e6-9a09-b4d1d11073e1.png)
![37](https://cloud.githubusercontent.com/assets/17407521/17390797/e5fa7d36-5a42-11e6-94ae-3535ac2cfa61.png)

**Comment by gyuho** [comment]
It says `bind: address already in use`. Think some other process is using that port. Try again after reboot?

**Comment by heyitsanthony** [comment]
@wuyongxiu Could you try verifying the connection on port 2379 between the two machines? This may be a network configuration issue.

Set up a listener on the etcd server host:
```
kduser@v-app1-cloud]$ nc -l -p 2379
```
then, send a message from the client machine to the server host:
```
kduser@v-app2-cloud]$ echo testmsg | nc 172.20.176.36 2379
```
Does `testmsg` appear on `v-app1-cloud`?

**Comment by wuyongxiu** [comment]
@heyitsanthony @gyuho  Thank you very much! I fixed it. It is caused by "address already in use". I started an etcd server and didn't shut it down before I rebuilded and run it. Now I can access the 2379 port in other hosts. Thanks all!
