### ISSUE TITLE
Can we upgrade directly from 2.2.0 to 2.2.5

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#4379]
Can we upgrade directly from 2.2.0 to 2.2.5 or do we need to do it 6 times, 1 step at a time (painful)? 
2.2.0 -> 2.2.1
2.2.1 -> 2.3.0-alpha.0
2.3.0-alpha.0 -> 2.2.2
2.2.2 -> 2.2.3
2.2.3 -> 2.2.4
2.2.4 -> 2.2.5

I thought only if you are skipping a major version then it might require to handle 1 major upgrade at a time, but it seems I'm wrong. For example if I like to upgrade from 0.4 to 3.0
0.4 -> 2.0
2.0 -> 3.0

Actually I'm more worried about upgrading from 2.2 to 3.0(whenever that's available). Will that require me to upgrade all the 2.* versions and then to 3.0. If this is the case then probably I should start upgrading now, rather than waiting untill v3

**Comment by gyuho** [comment]
`v2.2.0` to `v2.2.x+` is fine. That's what we test before we do the release. Upgrade from `v2.2` to `v3.0` needs to be documented like https://github.com/coreos/etcd/blob/master/Documentation/upgrade_2_2.md. We don't have any documentation on that yet.

Defer to @xiang90.

Thanks,

**Comment by xiang90** [comment]
@raoofm For patch version, you can just upgrade. The minimum rule is we will support zero-down time upgrade from a.b.x to a.(b+1).0.

**Comment by raoofm** [comment]
Thanks @gyuho @xiang90 .

I understand that 2.2.a can go to 2.2.x directly.

>The minimum rule is we will support zero-down time upgrade from a.b.x to a.(b+1).0

Can 2.a.a go to 2.x.x?(From your comment 2.a has to go to 2.b and then to 2.c.... to 2.x, this requires releases in production with no good reason to convince the support teams)

Can 2.a go to 3.a without upgrading from 2.a to 2.x?

**Comment by raoofm** [comment]
Another question is

v2.3 will be released on Feb 08. Can I assume that all the fixes done in 2.2.x series are also fixed in  2.3?

**Comment by raoofm** [comment]
ping?

**Comment by gyuho** [comment]
@raoofm Sorry for late response.
- We will have documentation ready when we release 3.0. Especially about how to migrate from 2.x.
- All 'known' bugs from the previous release should be fixed in next patch, major release.

**Comment by raoofm** [comment]
@gyuho thanks.

When can we expect 2.3 to be released? Milestone and roadmap dates are already missed and are not updated.
Should I open an issue to update milestones?

**Comment by gyuho** [comment]
Our plan is this or next week. I will double-check. Thanks.

/cc @xiang90
