### ISSUE TITLE
v3 functional-test : Phase I

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4380]
- [X] Add `Hash` method to KV API: https://github.com/coreos/etcd/pull/4404
- [X] Put data into v3 storage: https://github.com/coreos/etcd/pull/4406
- [X] Check data consistency over cluster using `Hash` method: https://github.com/coreos/etcd/pull/4412
  - stop all inputs
  - wait for a moment
  - compare the storage by hashing
- [X] Compact v3 storage periodically (for every failure round): https://github.com/coreos/etcd/pull/4448

**Comment by xiang90** [comment]
we probably still need to store the bad data dir on to a cloud storage rather than a database.

**Comment by gyuho** [comment]
Just changed. Thanks.

**Comment by xiang90** [comment]
Add another requirement: Compact v3 storage periodically

**Comment by gyuho** [comment]
@xiang90 Just added. Thanks!

**Comment by gyuho** [comment]
`Feed logs, bad data-dir into cloud storage for debugging purpose` will be done in a separate repo.
