### ISSUE TITLE
Public etcd playground: play.etcd.io

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4381]
- set up an actual 5-node cluster, served publicly at `play.etcd.io` or something else
- users can kill, recover nodes and see the real-time logs and status of cluster
- resources and features will be limited for the first version

**Comment by jonboulle** [comment]
shameless driveby :+1:

**Comment by gyuho** [comment]
Thanks!

**Comment by gyuho** [comment]
Done. http://play.etcd.io/ is live.
