### ISSUE TITLE
please use stable release of google protobuf

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#4446]
There are some `.proto` files (e.g. [storage/storagepb/kv.proto](https://github.com/coreos/etcd/blob/master/storage/storagepb/kv.proto#L1) and others) that use `syntax = "proto3"` supported by yet to be released `protoc`. Latest stable release of [protobuf compiler](https://github.com/google/protobuf/releases) 2.6.1 supports only `syntax = "proto2"`.

Whenever possible please consider to use only stable dependencies for stable releases of Etcd.

**Comment by xiang90** [comment]
@onlyjob We are using proto3 for gPRC. And it is for our alpha version of v3 api. So I am not worry about it until we decide to release stable version of etcd3.

**Comment by jonboulle** [comment]
I guess the concern here is for packaging the dependencies without this?
@xiangli I wonder if we should make it easier for packagers to build etcd
without any of the v3 stuff linked in.

Xiang Li <notifications@github.com> schrieb am Sa., 6. Feb. 2016 16:56:

**Comment by onlyjob** [comment]
> I guess the concern here is for packaging the dependencies without this?

Yes, for downstream packaging here in Debian it is quite a problem as since recent update of vendored `github.com/gogo/protobuf` _Etcd_ FTBFS when built with stable release of protobuf compiler:

~~~~
src/github.com/coreos/etcd/storage/storagepb/kv.pb.go:84: undefined: proto.RegisterType 
src/github.com/coreos/etcd/storage/storagepb/kv.pb.go:85: undefined: proto.RegisterType 
~~~~

**Comment by onlyjob** [comment]
Thanks for understanding, @jonboulle.

**Comment by xiang90** [comment]
protobuf 3 is release: https://github.com/google/protobuf/releases/tag/v3.0.0

proto3 syntax is in the stable release. so closing.
