### ISSUE TITLE
cannot add member to existing cluster

### ISSUE THREAD

**Issue by lslaslo** [coreos/etcd#4451]
When following documentation here: https://coreos.com/etcd/docs/latest/runtime-configuration.html#cluster-reconfiguration-operations to add a member, when running 
`etcd -listen-client-urls http://10.0.191.151:2379 -advertise-client-urls http://10.0.191.151:2379 -listen-peer-urls http://10.0.191.151:2379 -initial-advertise-peer-urls http://10.0.191.151:2379 -data-dir %data_dir%`
I get an error message: `flag provided but not defined: -listen-client-urls`

When I check etcd version with `etcd --version` I get  etcd version 0.4.9

But if I `curl http://127.0.0.1:2379/version` I get {"etcdserver":"2.1.2","etcdcluster":"2.1.0"}

I understand that the flag was added to version 2, but I'm not clear about the version differences I'm seeing.

**Comment by xiang90** [comment]
I think on CoreOS, you should try etcd2, not etcd.  @crawford will have a better answer for you on this one.

**Comment by lslaslo** [comment]
@xiang90 that was it -- thank you!

**Comment by xiang90** [comment]
@lslaslo No problem.
