### ISSUE TITLE
etcd-tester: stresser does not fully stop after cancellation

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4465]
I observed a few hash inconsistency issue from the testing log.

After examining the wal, I found etcd-tester still issued a few PUT requests after it finished checking Revision. We must stop all inputs before we check the hash, or we might get inconsistent hashes.

```
  23	    223064	norm	ID:11220809473183802613 range:<key:"foo" >
  23	    223065	norm	ID:12805232117071983489 range:<key:"foo" >
  23	    223066	norm	ID:7778933457946078688 range:<key:"foo" >
  23	    223067	norm	method=SYNC time="2016-02-08 18:56:51.566567727 -0800 PST"
  23	    223068	norm	ID:11220809473183802614 put:<key:"foo75233" value:"yilatbmpcaumpvpwcwrrxbmgkiklxgdzkcodzapmyqwwddkupfunqysmpsqbjudrqzbodlkdvhxedkgxopdbxiihranrkbfwnatb" >
  23	    223069	norm	ID:11220809473183802615 put:<key:"foo168007" value:"xraaejhheoslvhejtvqprzsacnaphnwplupekkxitzmtsysuafumaglptbkylslwipstxdaxlchtpmfvzqlafztgfiiwnanrtcyn" >
```

223064 - 223066 are the rev checking by getting key foo.

223068-223069 are PUTs that caused the hash inconsistent failure in tests among members.

**Comment by xiang90** [comment]
@gyuho I manually reverted the two puts and then the hashes of all member become consistent. So I am sure the two additional PUTs from stresser were the real cost.

**Comment by gyuho** [comment]
I think https://github.com/coreos/etcd/pull/4466 should resolve this, by disconnecting the gRPC connection. Any thoughts? Thanks

**Comment by xiang90** [comment]
@gyuho I do not think it is related. I have no idea why it still sends puts to etcd after cancellation. Probably you can do more investigation on this one.

**Comment by gyuho** [comment]
Ok will investigate more. Thanks

**Comment by xiang90** [comment]
Seems to be fixed.
