### ISSUE TITLE
ssh tunnelling requires no-sync to be turned on

### ISSUE THREAD

**Issue by grahamjenson** [coreos/etcd#4496]
I like to tunnel through a NAT to a node in my etcd cluster eg `ssh -A -N  -L 2379:$NODE_IP:2379 user@$NAT_IP`. This way I can execute `etcdctl` on my local machine and the query will tunnel to the remote computer. 

```
etcdctl --debug ls
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://10.0.1.1:2379) after sync
Cluster-Endpoints: http://10.0.1.1:2379
cURL Command: curl -X GET http://10.0.1.1:2379/v2/keys/?quorum=false&recursive=false&sorted=false
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://10.0.1.1:2379 exceeded header timeout
```

Even if I set the endpoint to be local:

```
etcdctl --debug --endpoint=http://127.0.0.1:2379 ls
start to sync cluster using endpoints(http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://10.0.1.1:2379) after sync
Cluster-Endpoints: http://10.0.1.1:2379
cURL Command: curl -X GET http://10.0.1.1:2379/v2/keys/?quorum=false&recursive=false&sorted=false
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://10.0.1.1:2379 exceeded header timeout
```

However if I use no-sync it works

```
etcdctl --no-sync --debug ls
Cluster-Endpoints: http://127.0.0.1:2379, http://127.0.0.1:4001
cURL Command: curl -X GET http://127.0.0.1:2379/v2/keys/?quorum=false&recursive=false&sorted=false
/coreos.com
```

Is this the correct behaviour? I would have thought that setting the endpoint would have been enough to fix this. What is no-sync doing, and what side effects will this have?

**Comment by gyuho** [comment]
@grahamjenson Do you have a proxy in your cluster? Is `http://127.0.0.1:2379` proxy?

`no-sync` flag does not synchronize the cluster information and send request to proxy, which then reverse-proxy the request to the actual cluster.

https://github.com/coreos/etcd/blob/cb7ebe81a88e21ca3860f4b830cc2ee7304f6b2f/etcdctl/main.go#L34

**Comment by grahamjenson** [comment]
No proxy, just a NAT. It seems that I should have a proxy or VPN into the nodes so that their private IP addresses can be found. Is this the common solution?

**Comment by gyuho** [comment]
@grahamjenson I am not sure how you set up NAT because I don't have your etcd configuration.
Did you set `http://10.0.1.1:2379` when you start `etcd`? Your logs tell the client(local) machine has no
access to `http://10.0.1.1:2379`. 

And proxy is optional. You can use it however you need reverse proxy.

**Comment by grahamjenson** [comment]
Yes. I set up using cloud_config so `advertise-client-urls: http://$private_ipv4:2379"`. And my local machine does not have access to the IP address.

It is just mostly annoying that etcdctl rewrites who I am trying to communicate with by syncing. but if this is meant to be like this for other reasons then I can live with `--no-sync` and will close the issue

**Comment by gyuho** [comment]
I see. That explains the problem.
And sorry that it was confusing. I will make the documentation clearer.

**Comment by grahamjenson** [comment]
All good :)

**Comment by fghibellini** [comment]
@gyuho

> Without `--no-sync` flag, this will be overwritten by etcd cluster when it does internal sync.

Is there some place in the docs where I can find more about the internal sync - what is its purpose and why it replaces the endpoint url?
