### ISSUE TITLE
Compiling master on Raspberry-Pi: constant overflows int

### ISSUE THREAD

**Issue by lechat** [coreos/etcd#4519]
Hi,

Compiling 'master' on Raspberry PI 2 Model B:

```
# github.com/coreos/etcd/storage/backend
storage/backend/backend.go:38: constant 10737418240 overflows int
```

This caused by commit 26c645f04. Perhaps some checks for `int` size need to be made before setting that constant.

**Comment by xiang90** [comment]
@lechat https://github.com/coreos/etcd#32-bit-systems

etcd does not support 32bit machines well at this point.
