### ISSUE TITLE
Raftexample how can I notify leader election

### ISSUE THREAD

**Issue by izouxv** [coreos/etcd#4522]
My raft leader need add or remo

**Comment by xiang90** [comment]
@izouxv In the Ready.SoftState you can get the state change, like https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L143-L162.

You can add that into the example codebase if you want. Thanks!

**Comment by izouxv** [comment]
My leader service need delete or add some data , so i need to know which raft node is leader
