### ISSUE TITLE
Using this Raft implementation in my project, not over HTTP

### ISSUE THREAD

**Issue by peterbourgon** [coreos/etcd#4531]
Hey, I'd like to try and use this Raft impl in my project, something like contrib/raftexample. It seems the Transporter abstraction bakes in the assumption that [I'm going to be serving over HTTP](https://github.com/coreos/etcd/blob/fe5500228a2574f499390f54c84883cf0df82cdd/rafthttp/transport.go#L47-L52
), with [peers addressable as URLs](https://github.com/coreos/etcd/blob/fe5500228a2574f499390f54c84883cf0df82cdd/rafthttp/transport.go#L65-L66
). But I'm not; I'm using a stateless, packet-oriented transport, effectively UDP. Is there a lower-level abstraction for the transport that I can try, or will I need to use the raft.Node directly, and manage all peer communication myself?

**Comment by xiang90** [comment]
> or will I need to use the raft.Node directly, and manage all peer communication myself?

Here is also an in-mem implementation you might want to look at https://github.com/coreos/etcd/blob/master/raft/rafttest/network.go.

And Yes. You need to implement your own transport layer if you want to use UDP. It should not be hard. etcd/raft uses a message based communication model and handles message reordering.

**Comment by peterbourgon** [comment]
Thanks for the tip. I'll see what I can do.

**Comment by xiang90** [comment]
@peterbourgon Let us know if you have any further issues or anything we could help. Thanks!
