### ISSUE TITLE
I have a problem in client/client.go line346 when my code import net/context and etcd use godep net/context.

### ISSUE THREAD

**Issue by zhangdaoling** [coreos/etcd#4544]
I have a problem in client/client.go line346 when my code import net/context and etcd use godep net/context.

I need "err == context.Canceled"  when my code cancel father ctx, but err.Error() = context.Canceled.Error() = "context canceled"

[line 346](https://github.com/coreos/etcd/blob/master/client/client.go#L344-L349) is "if err == context.Canceled || err == context.DeadlineExceeded {"
should it be "if err.Error() == context.Canceled.Error() || err.Error() == context.DeadlineExceeded.Error() {"

**Comment by gyuho** [comment]
It's correct comparison in `client` package. When the error returns, you can compare the error string in your code, right?

**Comment by zhangdaoling** [comment]
it will return ClusterError, ClusterError.Error() is ErrClusterUnavailable not context.Canceled

**Comment by xiang90** [comment]
@zhangdaoling Can you please clarify your issue? 

> line 346 is "if err == context.Canceled || err == context.DeadlineExceeded {"
should it be "if err.Error() == context.Canceled.Error() || err.Error() == context.DeadlineExceeded.Error() {"

I do not really understand what you were trying to say here.

**Comment by gyuho** [comment]
@zhangbaitong Any updates?

**Comment by gyuho** [comment]
@zhangbaitong Ping?

**Comment by xiang90** [comment]
This is covered by https://github.com/coreos/etcd/issues/4784.
