### ISSUE TITLE
etcdctlv3: txn command enhancement 

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4559]
Now txn command support a basic interactive mode.

There are a few TODOs:

1. improve the user experience in interactive mode. (use same commands in success and failure list as normal put,get,del for example)

2. define the non-interactive mode input/output format.

/cc @heyitsanthony can you take this one?

**Comment by heyitsanthony** [comment]
I think 1 is covered. Not sure what to do about 2; I think the interactive mode format is good enough for non-interactive-- is something missing aside from updating the docs and not complaining about a missing `-i` flag?

**Comment by xiang90** [comment]
-i input seems fine. I think we just need to make it work and add doc around it.
