### ISSUE TITLE
etcdserver.NewMember does not take name into account

### ISSUE THREAD

**Issue by sttts** [coreos/etcd#4573]
The member ID is supposed to depend on the node name. But it doesn't. It only depends on the peer URLs on cluster join. Moreover, the timestamp is nil as well.

I imagine that this is on-purpose such that a new node joining (with pre-added peer URL entry) chooses the same cluster ID and therefore finds its member entry. The name is not stored for the pre-added member, i.e. the prepared member entry work for any name.

But then at least the comment is wrong in the code about the name dependency: https://github.com/coreos/etcd/blob/master/etcdserver/member.go#L56

**Comment by xiang90** [comment]
> The member ID is supposed to depend on the node name. 

It is supposed not. User can change name as they want when restart.

**Comment by sttts** [comment]
Make sense. Then only the comment is wrong.
