### ISSUE TITLE
v3api: delete should return number of key removed.

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4576]
We should add a n filed in https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L154 to return the number of key removed. Right now, user has to do this in a txn that get the remove range first. But I feel this is a common use case/info. So we should just add this.

@gyuho  Do you want to take this one?

**Comment by gyuho** [comment]
Sure, I will take a look.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/4583.
