### ISSUE TITLE
list and watch dir in a transaction

### ISSUE THREAD

**Issue by JaySWang** [coreos/etcd#4587]
Hi there,

I am wondering is there a way to put list and watch a dir in a transaction so that i would not miss any changes to its childnodes. 

Just like watch a key with the modifiedIndex. But the modifiedIndex of the dir would not update when its children change.

As for X-Etcd-Index, any update to nodes under other dirs would also change this index.

Happy to hear any solution.

Thx~

**Comment by xiang90** [comment]
@JaySWang 

Can you please provide an example of what you want to achieve. It is not quite clear to me what exactly you want to achieve.

Probably you can get the nodes under dir, then watch from the index returned by get operation.

**Comment by JaySWang** [comment]
@xiang90 

I want to use etcd to be a service registry. Let's take XXX.DemoService for example. For consumers,they would watch for XXX.DemoService(a dir node).  For providers,they could add service info(URLs) under XXX.DemoService as child nodes.

After getting the URLs,consumers need to watch the dir again for update. In this case,they may miss some updates between get and watch.

Thx~

**Comment by xiang90** [comment]
> After getting the URLs,consumers need to watch the dir again for update. In this case,they may miss some updates between get and watch.

You should watch again from the modified index of the update you got.

**Comment by JaySWang** [comment]
@xiang90 

But the modified index of the dir would not update when  adding child nodes to it.

**Comment by xiang90** [comment]
@JaySWang 

> After getting the URLs,consumers need to watch the dir again for update.

When you get the URL, you should know the latest modifiedIndex. Can you explain why does the modified index of the dir matters?

**Comment by JaySWang** [comment]
@xiang90    so when i watch for a dir with modifiedIndex(got from response)+1,the watcher will be notified when a new child node being added under the dir?     If so,the modifiedIndex means the latest modifiedIndex of that dir and its child nodes?

**Comment by xiang90** [comment]
@JaySWang 

>  the watcher will be notified when a new child node being added under the dir

Yes.

> If so,the modifiedIndex means the latest modifiedIndex of that dir and its child nodes?

I do not totally understand what you asked. Probably it is not clear to you that etcd only has one global increasing index? Each operation will increase that index. It has nothing to do with dir or its node,

**Comment by JaySWang** [comment]
@xiang90  Yes,i am new to etcd,thx for your patience.

In this case,the watcher for a dir with the modifiedIndex will also be notified when other dir changed?

**Comment by xiang90** [comment]
I would suggest you read https://github.com/coreos/etcd/blob/master/Documentation/api.md#waiting-for-a-change first and try it out.

**Comment by JaySWang** [comment]
@xiang90   thx!   i  misunderstood the watch mechanism.  It is clear now.
