### ISSUE TITLE
etcdctl cannot add key with "in order" feature

### ISSUE THREAD

**Issue by jmcollin78** [coreos/etcd#4588]
Hello,

The etcdctl always create key using -XPUT http verb. So it's not possible to use it with what is known as "in order" feature (cf. https://github.com/coreos/etcd/blob/master/Documentation/api.md#atomically-creating-in-order-keys)
It should be great if this feature will be available throught high level etcdctl and not only with curl.

JM.

**Comment by xiang90** [comment]
etcdctl does not provide all features in the client or matches all API items provided by etcd. If you are interested in this feature and you have time, then send a pull request. Thanks!

**Comment by jmcollin78** [comment]
Sorry but I don't know programing in Go and I have no time for learning
this language.
Thank's for your answer anyway.

2016-02-24 20:18 GMT+01:00 Xiang Li <notifications@github.com>:

**Comment by AdoHe** [comment]
This should be easy to do, `etcd.KeysAPI` has `CreateInOrder` method, the only thing left is to add a new command implementation.
