### ISSUE TITLE
etcdctlv3: end to end testing

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4589]
We, now, do not have any tests for etcdctl. This is terrible.

We need to do a few things before we release stable version of etcdctlv3

1. basic functionality testing
2. output compatibility testing

/cc @heyitsanthony

**Comment by heyitsanthony** [comment]
The main blocker on this is unifying the v2 and v3 etcdctl binaries since building the etcdctlv3 binary for e2e as an interim solution got shot down (cf. 4332).

**Comment by gyuho** [comment]
Yeah for testing purposes, we can build `etcdctlv3` and integrate later, since it might take awhile to integrate since the CLI interface is totally different.

**Comment by heyitsanthony** [comment]
According to #3922 (referencing #2892) etcdctlv2 can't be ported to use cobra because of some subtle flag breakage; it's unclear to me how we'd get one binary out of this without porting etcdctlv3 to use `codegangsta/cli`.

**Comment by ajityagaty** [comment]
@heyitsanthony Is there a plan to port v3 to use codegansta? Or if you folks have figured out how to go about testing etcdctl please let me know. I can find sometime to help you guys write the tests given a template.

**Comment by heyitsanthony** [comment]
@ajityagaty v3 isn't being ported to codegangsta/cli; see #4877. v3 e2e testing is already in progress.

**Comment by xiang90** [comment]
@heyitsanthony @ajityagaty 

Actually we want to use cobra not `codegangsta/cli` in the future. So we will not do the port. As @heyitsanthony mentioned, you can check the current progress in https://github.com/coreos/etcd/blob/master/e2e/etcdctlv3_test.go. 

Probably you want to coordinate with @gyuho to see what needs to be done.

**Comment by ajityagaty** [comment]
Thanks @xiang90 @heyitsanthony !

@gyuho Please let me know if there is anything that I can help with.

**Comment by gyuho** [comment]
@ajityagaty Sure, we would very much appreciate it.

If you would like to help, you can start with `ETCDCTL_API=3 ./etcdctl user`?
`user` feature is pretty new, so having tests would be very helpful!

I am working on e2e tests on other commands. I will let you know if I need more help.

**Comment by ajityagaty** [comment]
@gyuho Thanks ! I will start looking into it.

**Comment by ajityagaty** [comment]
@gyuho If I try to run "go test" within the e2e folder the test doesn't complete. Is there anything else that needs to be done in order to run e2e tests?

**Comment by gyuho** [comment]
@ajityagaty What branch are you in? You can `./build` in etcd root directory (builds binaries into `bin`directory), and then `go test`.

**Comment by ajityagaty** [comment]
@gyuho Thanks !
I am on a private branch on my fork. But running `INTEGRATION=1 ./test` from the root worked for me.

**Comment by ajityagaty** [comment]
@gyuho Please let me know if I could help with anything else.

**Comment by gyuho** [comment]
@ajityagaty Do you want to try `role` command tests? Would be similar to https://github.com/coreos/etcd/blob/master/e2e/ctl_v2_test.go#L159. Thanks!

**Comment by ajityagaty** [comment]
@gyuho Sure ! Will give it a try. Thanks !

**Comment by gyuho** [comment]
Think the first phase should be done with https://github.com/coreos/etcd/pull/5114. Some commands are missing (`auth disable`, `make mirror`, `alarm`) though.

**Comment by gyuho** [comment]
@xiang90 I think we can close this? Please let me know if we still need more tests.

**Comment by xiang90** [comment]
@gyuho Sure. Closing.
