### ISSUE TITLE
docs: fix dashes in etcd parameters in the docs

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#4595]
i.e. replace `-initial-cluster` with the `--initial-cluster`

I'm actually not quite sure whether it is correct.

/cc @joshix @xiang90

**Comment by joshix** [comment]
Related https://github.com/coreos/docs/issues/650

The goal is to be [eventually] consistent across CoreOS projects with short option single hyphen: `-o`, long option double: `--option`

**Comment by kayrus** [comment]
Have to fix dashes [here](https://github.com/endocode/etcd/blob/kayrus/relink/Documentation/configuration.md)

**Comment by kayrus** [comment]
@joshix https://github.com/coreos/etcd/pull/4607

**Comment by kayrus** [comment]
@xiang90 please reopen, we have to fix it also here and probably in other places https://github.com/endocode/etcd/blob/kayrus/relink/Documentation/security.md

**Comment by xiang90** [comment]
@kayrus Yea. Do not use Fix #XXX next time in a pull request. This is closed due to https://github.com/coreos/etcd/pull/4607. Github auto close any issue marked with Fix once the pull request is closed.

**Comment by kayrus** [comment]
Here too: https://github.com/coreos/etcd/blob/master/Documentation/proxy.md

**Comment by xiang90** [comment]
@gyuho take a look at this one?

**Comment by gyuho** [comment]
ack. Will take a look.
