### ISSUE TITLE
Problem with setdir

### ISSUE THREAD

**Issue by r0j4z0** [coreos/etcd#4596]
Hi, i think this is related to https://github.com/coreos/etcd/issues/1519

Environment:
etcd version: v2.2.5
Configured 3 nodes cluster.
Running on docker 1.8.2

Im trying to use setdir to update a directory ttl without asking etcd if the directory already exists.

On the first run all goes fine:

```
# etcdctl --debug setdir -ttl=30 /lol
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://172.16.50.11:2379,http://172.16.50.15:2379,http://172.16.50.14:2379) after sync
Cluster-Endpoints: http://172.16.50.11:2379, http://172.16.50.15:2379, http://172.16.50.14:2379
cURL Command: curl -X PUT http://172.16.50.11:2379/v2/keys/lol?dir=true -d "ttl=30"
```

But if i run it again to update the ttl when directory exists i get the following error:

```
# etcdctl -debug setdir -ttl=30 /lol
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
cURL Command: curl -X GET http://127.0.0.1:2379/v2/members
got endpoints(http://172.16.50.11:2379,http://172.16.50.15:2379,http://172.16.50.14:2379) after sync
Cluster-Endpoints: http://172.16.50.11:2379, http://172.16.50.15:2379, http://172.16.50.14:2379
cURL Command: curl -X PUT http://172.16.50.11:2379/v2/keys/lol?dir=true -d "ttl=30"
Error:  102: Not a file (/lol) [9899]
```

And the ttl isn´t updated on the folder. (expires normally after 30 seconds)

**Comment by xiang90** [comment]
@r0j4z0 https://github.com/coreos/etcd/issues/1519#issuecomment-67053097

**Comment by r0j4z0** [comment]
I can update the ttl of an existing folder with:

`curl -XPUT -d ttl=30 -d dir=true -d prevExist=true /lol`

i want to achieve the same with etcdctl.

I expect setdir use prevExist=true

**Comment by xiang90** [comment]
@r0j4z0 Why not using updatedir?

**Comment by r0j4z0** [comment]
@xiang90 Because i dont know if the directory exists or not. I want to avoid to ask to etcd for each folder i want to update the TTL.

**Comment by xiang90** [comment]
> I expect setdir use prevExist=true

>  Because i dont know if the directory exists or not.

This seems to be contradict with what you just said. etcd do not allow you blindly replace a dir, so what you want is not achievable. You have to check first.

**Comment by r0j4z0** [comment]
My usecase is:

I have a function that receives an etcd key and value

for the key i will set the ttl to 15 seconds, for the "path" i want to set the ttl to 30 seconds, this function is called every 5 seconds so it will update the ttl's or leave it expires if no key/value was received.

As i understand, the documentation says setdir parameter can be used to create or update a directory, thats is why i thought i can use setdir without worrying to check if the directory exists or not. So if setdir can't make an update over a directory that already exists, what is the difference with mkdir?
