### ISSUE TITLE
v3: watch over ranges

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#4599]
Right now Watch only supports watching on single keys and prefixes. If Watch supports ranges, it could act like a long-lived GET. Likewise, it would improve the Watcher interface's compatibility with the clientv3 `With*` options.

**Comment by xiang90** [comment]
Marked this as unplanned since this is not a blocker for v3 initial release. This is def a nice thing to have!

**Comment by heyitsanthony** [comment]
Supported as of #4614
