### ISSUE TITLE
v3 curl API 

### ISSUE THREAD

**Issue by JaySWang** [coreos/etcd#4603]
Could you provide v3  API( like lease) in curl style?  
many thanks

**Comment by xiang90** [comment]
What do you want to achieve? Can you explain your use case in more detail?

**Comment by JaySWang** [comment]
Use etcd for service discovery.  The etcdclient（JAVA based） would encapsulate the curl APIs.

**Comment by xiang90** [comment]
@JaySWang If you want to implement an etcd client, we would suggest you to use https://github.com/grpc/grpc-java client.

**Comment by JaySWang** [comment]
@xiang90  Thx~   I will have a look at that. But,i currently use Dubbo as the RPC framework and got a light-weight etcdclient that encapsulates  Restful APIs.   

I just want to know the Restful APIs for V3 at this stage. 

Thx for your help.

**Comment by xiang90** [comment]
@JaySWang We might suggest use grpc-gateway(https://github.com/gengo/grpc-gateway) to proxy restful to grpc. So you can have a "restful" API.

**Comment by JaySWang** [comment]
@xiang90   Great.   Do the new features like lease in V3 support JSON/HTTP request? or they just support  gRPC?        

How can i  try the lease feature on command line using curl?

**Comment by xiang90** [comment]
@JaySWang It does not support JSON natively. If you want to use command line tool, try etcdctlv3.

**Comment by JaySWang** [comment]
I see. Thx~

**Comment by JaySWang** [comment]
@xiang90   Hi,  the etcdctl in v2.3.0-alpha.1 for windows seems does not support the new APIs?

**Comment by heyitsanthony** [comment]
You'll need to use etcdctlv3. You can build it by running `go build` in the `etcdctlv3/` directory.

**Comment by JaySWang** [comment]
@heyitsanthony Thx~
