### ISSUE TITLE
Network glitch causes Proxies to fail connectity and Fleet rescheduling

### ISSUE THREAD

**Issue by mwitkow** [coreos/etcd#4606]
Running `CoreOS beta (899.5.0)` `etcdctl version 2.2.3` with 5 machine member cluster and hundreds of etcd in Proxy mode. For the sake of clarity, here is the etcd member list + hostnames (used in logs)

```
3bf4b50a2282ae25: name=eu1-prod-core-4 peerURLs=http://10.150.0.6:2380 clientURLs=http://10.150.0.6:2379
41c15e3bc9afb0fa: name=eu1-prod-core-2 peerURLs=http://10.150.0.4:2380 clientURLs=http://10.150.0.4:2379
893f5d7781d58414: name=eu1-prod-core-0 peerURLs=http://10.150.0.5:2380 clientURLs=http://10.150.0.5:2379
bac745d91241438a: name=eu1-prod-core-3 peerURLs=http://10.150.0.3:2380 clientURLs=http://10.150.0.3:2379
fc4c2f3a06359c3c: name=eu1-prod-core-1 peerURLs=http://10.150.0.2:2380 clientURLs=http://10.150.0.2:2379
```

We've seen 2 temporary networking glitches (for the sake of this post `0:17` and `0:22`), which we're quite sure were caused by our Cloud provider's networking issues (GCE in `europe-west1-d`). We know that these were underlying networking glitches because there were non-etcd errors reporting lack of connectivity:

`0:17` on `eu1-prod-core-0`:
```
Feb 24 00:17:30 eu1-prod-core-1 accounts-from-metadata[2332]: WARNING Error while trying to fetch attribute: HTTP Error 503: Service Unavailable
Feb 24 00:17:30 eu1-prod-core-1 google-address-manager[1566]: ERROR SyncAddresses exception: HTTP Error 503: Service Unavailable
```
`0:22` on `eu1-prod-core-3`:
```
Feb 24 00:22:49 eu1-prod-core-3 docker[1371]: ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='elasticsearch', port='9200'): Read timed out. (read timeout=10))
````

These two issues one by one caused a ripple effect across our `etcd` + `fleet` cluster that caused **(almost) everything to restart**

![coreos-issue](https://cloud.githubusercontent.com/assets/9655971/13288592/8b81a04a-db04-11e5-9dd2-41a225a5ccc7.png)
. 

These were driggered first by `eu1-prod-core-1` at `0:17`
```
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: error writing event (write tcp 10.150.0.8:42450: broken pipe)
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: the connection with 893f5d7781d58414 became active
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: the connection with 893f5d7781d58414 became inactive
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: the connection with bac745d91241438a became active
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: the connection with bac745d91241438a became active
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: the connection with bac745d91241438a became inactive
Feb 24 00:17:31 eu1-prod-core-1 etcd2[1792]: the connection with bac745d91241438a became inactive
```

and later  by `eu1-prod-core3` at `0:23`
```
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: error writing event (write tcp 10.150.0.14:48368: broken pipe)
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: error writing event (write tcp 10.150.0.14:48388: broken pipe)
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: error writing event (write tcp 10.150.0.24:39354: broken pipe)
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: error writing event (write tcp 10.150.0.24:39436: broken pipe)
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: error writing event (write tcp 10.150.0.7:60944: broken pipe)
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: error writing event (write tcp 10.150.0.8:57524: broken pipe)
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: failed to read fc4c2f3a06359c3c on stream Message (http: unexpec
```

The logs on the machines were full of messages with lower term:

```
Feb 24 00:23:35 eu1-prod-core-1 etcd2[1792]: fc4c2f3a06359c3c [term: 25] ignored a MsgApp message with lower term from bac745d91241438a [term: 24]
Feb 24 00:23:35 eu1-prod-core-1 etcd2[1792]: fc4c2f3a06359c3c [term: 25] ignored a MsgApp message with lower term from bac745d91241438a [term: 24]
Feb 24 00:23:35 eu1-prod-core-1 etcd2[1792]: fc4c2f3a06359c3c [term: 25] ignored a MsgApp message with lower term from bac745d91241438a [term: 24]
```

And weird timing issues in etcd:
```
b 24 00:24:19 eu1-prod-core-1 etcd2[1792]: the clock difference against peer bac745d91241438a is too high [3.711407949s > 1s]
Feb 24 00:24:23 eu1-prod-core-2 etcd2[1229]: the clock difference against peer bac745d91241438a is too high [26.563543281s > 1s]
Feb 24 00:24:23 eu1-prod-core-2 etcd2[1229]: the clock difference against peer fc4c2f3a06359c3c is too high [22.855697838s > 1s]
Feb 24 00:24:25 eu1-prod-core-4 etcd2[1086]: the clock difference against peer bac745d91241438a is too high [26.556863943s > 1s]
Feb 24 00:24:25 eu1-prod-core-4 etcd2[1086]: the clock difference against peer fc4c2f3a06359c3c is too high [22.855742901s > 1s]
Feb 24 00:24:40 eu1-prod-core-0 etcd2[1204]: the clock difference against peer fc4c2f3a06359c3c is too high [22.855811769s > 1s]
```

Full logs attached from all `member` machines here: [combined.txt](https://github.com/coreos/etcd/files/144792/combined.txt)

Now, the etcd clusters **recovered** after ~5min. But *the real problem* was `fleet` unscheduled machines running on instances with Etcd Proxy instances. It seems that Proxy instances don't retry connections against other Peers:
```
michal@eu1-prod-simmon-0 ~ $ sudo journalctl --since 00:15 --until 00:28 -u etcd2.service
-- Logs begin at Mon 2016-01-25 11:54:07 UTC, end at Wed 2016-02-24 14:49:27 UTC. --
Feb 24 00:17:36 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:56360 closed request prematurely
Feb 24 00:17:36 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:56728 closed request prematurely
Feb 24 00:17:36 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:56779 closed request prematurely
[...]
Feb 24 00:17:49 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:56842 closed request prematurely
Feb 24 00:23:37 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:57878 closed request prematurely
Feb 24 00:23:37 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:58152 closed request prematurely
Feb 24 00:23:37 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:58154 closed request prematurely
[...]
Feb 24 00:23:48 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:58200 closed request prematurely
Feb 24 00:23:50 eu1-prod-simmon-0 etcd2[1063]: proxy: client 127.0.0.1:58214 closed request prematurely
```

and this causes `fleet` to miss out on it's updates triggering a reschedule of pretty much the whole world

```
INFO reconciler.go:164: EngineReconciler completed task: {Type: UnscheduleUnit, JobName: simmon@eu1-prod-simmon-0.service, MachineID: 6301045cf1ed6affe28db3ebc33d8a81, Reason: "target Machine(6301045cf1ed6affe28db3ebc33d8a81) went away"}
```

Few questions:
 * is there a way to make `etcd` peer connectivity TCP timeout be more aggressive than 5s?
 * is there a way to force `etcd` in `proxy=on` mode to retry connections against other peers?
 * where does the `the clock difference against peer` come from? I checked, the ntp on the machines was in line, and so where the messages. Were these just stale messages in a buffer somewhere?
 * it seems that the problems were only caught by the `etcd_server_proposal_failed_total` metric, but not by `etcd_rafthttp_message_sent_failed_total`, is this correct?

**Comment by xiang90** [comment]
@mwitkow Thanks for reporting. Can you provide more logs? I want to know when the error starts and when it ends for etcd-side.

>  is there a way to make etcd peer connectivity TCP timeout be more aggressive than 5s?

It is not configurable right now. We do have plan. But we also want to learn about why do you want to set it shorter. Why do you think this is related to the issue you reported?

> is there a way to force etcd in proxy=on mode to retry connections against other peers?

This is a requests from multiple users. We will probably add. But why do you think this is related to the issue you reported?

> where does the the clock difference against peer come from? 

Probably a buffer issue. I will check.

**Comment by mwitkow** [comment]
@xiang90 thanks for the quick reply!

The `combined.txt` (attached above) contains all `etcd2.service` journalctl logs for the period of the outage for all of etcd members. We checked `dmesg` as well and so nothing unusual. What other logs would you be interested in? :)

> > is there a way to make etcd peer connectivity TCP timeout be more aggressive than 5s?

> It is not configurable right now. We do have plan. But we also want to learn about why do you want to set it shorter. Why do you think this is related to the issue you reported?

There's a lot of `(Get http://10.150.0.2:2380/version: read tcp 10.150.0.2:2380: i/o timeout)`, and the network issue lasted only a few seconds. Maybe if the TCP timeout was more aggressive than `5s` it would have recovered quicker?

> > is there a way to force etcd in proxy=on mode to retry connections against other peers?

 > This is a requests from multiple users. We will probably add. But why do you think this is related to the issue you reported?

We observed the following: `fleet` units on member machines weren't rescheduled, except for the ones on the machines with networking connectivity. the `etcd2.service` logs of proxy machines are full of connectivity issues, and a majority of `fleet` units on proxy machines got restarted due to machine healtchchecks failing.
From this, I'm guessing here, it seems that if the proxy machines were retying fleet heartbeat writes against healthy etcd members, the ripple effect across all machines would be significantly smaller.

**Comment by xiang90** [comment]
@mwitkow 

After examining the log, the ~20second clock diff is a real thing among your machines. 

All other 4 peers elected around fc4c2f3a06359c3c as leader 00:23:34 

```
Feb 24 00:23:32 eu1-prod-core-3 etcd2[1103]: raft.node: bac745d91241438a elected leader fc4c2f3a06359c3c at term 25
Feb 24 00:23:34 eu1-prod-core-4 etcd2[1086]: raft.node: 3bf4b50a2282ae25 elected leader fc4c2f3a06359c3c at term 25
...
```

But it self reported at 00:23:11.

```
Feb 24 00:23:11 eu1-prod-core-1 etcd2[1792]: fc4c2f3a06359c3c became leader at term 25
```

This is impossible to happen unless the clock is wrong.

eu1-prod-core-1's was also experiencing network issues. But it recovered pretty fast. Each time it takes a few seconds to recover. I do not think we need to tune the TCP timeout. 5 seconds are usually good enough.

On the other hand, fleet probably should be smarter about health checking. Temp unavailability should not cause massive rescheduling in my opinion.

**Comment by mwitkow** [comment]
@xiang90 thanks for taking a look :) I agree, these don't look like state

I double checked our `systemd-timesyncd.service configuration` and on all machines: 
 * it has been running happily for a long time on
 * is configured correctly to go against `169.254.169.254:123`, the GCE's VM-attached [Metadata Service](https://cloud.google.com/compute/docs/tutorials/building-images#osrecommended)
 * there were no `migrateOnHostMaintenance` events due to [GCE live migration](https://cloud.google.com/compute/docs/instances/setting-instance-scheduling-options#live_migrate)

So I totally don't know where the clock drift came from. Any ideas here? :)

The time drift problem aside, it seems that the fact that Etcd Proxies were black-holing requests because it couldn't reach one of the peers caused the massive failure. Any estimates when the retry logic will ship? We'd love to test it :)

**Comment by xiang90** [comment]
>  it seems that the fact that Etcd Proxies were black-holing requests because it couldn't reach one of the peers caused the massive failure. Any estimates when the retry logic will ship? We'd love to test it :)

The proxy is supposed to retry other peers. Do you have log/fact to back up this assumption?

**Comment by xiang90** [comment]
@mwitkow Any updates?

**Comment by mwitkow** [comment]
We found that a out staging etcd cluster that runs in the same GCE zone had
similar, but way less impactful, connectivity issues. Given that, and the
fact that our ntp mechanism is correctly configured, I think it was a
temporary glitch with our provider's hosting environment, but there's no
way for us to confirm.

Thanks for the help, feel free to close.

**Comment by xiang90** [comment]
@mwitkow OK. Thanks. Please report back if this kind of things happen again. Hopefully we will have more info to dig into.
