### ISSUE TITLE
integer overflow on ARM 32bit (Raspberry Pi)

### ISSUE THREAD

**Issue by abaumhauer** [coreos/etcd#4608]
# github.com/coreos/etcd/storage/backend
gopath/src/github.com/coreos/etcd/storage/backend/backend.go:38: constant 10737418240 overflows int

Fails to compile on 32 bit ARM processor due to a large constant.

// InitialMmapSize is the initial size of the mmapped region. Setting this larger than
        // the potential max db size can prevent writer from blocking reader.
        // This only works for linux.
        InitialMmapSize = 10 * 1024 * 1024 * 1024

**Comment by xiang90** [comment]
32bit is broken. And this is a known issue. We have no plan to support it right now. See https://github.com/coreos/etcd#32-bit-systems

**Comment by xiang90** [comment]
We will revisit this if there is a growing needs for 32bit.

**Comment by kneufeld** [comment]
We were about to use etcd on an embedded arm target but now it looks like we cannot. Is there still no plan to get etcd working on 32 bit platforms?.
