### ISSUE TITLE
Watch API should check start revision

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4610]
Discussed in https://github.com/coreos/etcd/pull/4593.

> Since we now export the start revision to clientv3 package, if a client
passes a bad revision (like 5 when the current revision is 1), it will
panic the whole node. We should print out warning message instead.

Better way is to prevent this in the first place in `clientv3` or `etcdctlv3`.
Or change `Watch` API to return error for wrong start revision.

**Comment by heyitsanthony** [comment]
I'm not sure if an explicit error is necessary. The failure state can be inferred from the header revision in the watch response; the API will return a watch channel, send a message with an empty event list, then close the channel. The client can interpret the empty event list as an error condition then work out what went wrong from the watch response.

Future revisions definitely shouldn't panic the node, of course.

**Comment by xiang90** [comment]
@heyitsanthony Probably we can set created and cancelled both to true in this case :https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L280-L287

**Comment by gyuho** [comment]
@heyitsanthony Agree. I will see if we can indicate such case in the `WatchResponse` as @xiang90 suggested.

Thanks.

**Comment by heyitsanthony** [comment]
@xiang90 the client knows the initial request revision, if it sees the watcher request failed then it can soundly infer it was because of a future revision based on the header response. Setting the cancelled flag on the server side if there isn't a cancel request seems broken to me (maybe the client could set it if it's really needed).
