### ISSUE TITLE
lease client panic

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#4622]
I just have a panic "nil address" on lease client.
Here's the scenario

- I got client from cluster.RandClient() and created a lease client. But I didn't used the lease client at all.
- When the cluster is shutting down, the lease client panic [here](https://github.com/coreos/etcd/blob/afa0368dcca68df711691bcba2384517115129a2/clientv3/lease.go#L262)

Note that this happened on on [this test](https://github.com/kubernetes/kubernetes/blob/aee2eb3977cd7f9edab58c5e5f2226f9e6e0f30f/pkg/master/master_test.go#L176). I am sharing to collect any thoughts.

**Comment by heyitsanthony** [comment]
I have the fix for this as part of a larger patch set. I'll split it out to another PR since it can stand alone.

**Comment by hongchaodeng** [comment]
@heyitsanthony 

Looks like you know the reason. Can you clarify why it panic? Client couldn't connect?

**Comment by xiang90** [comment]
@hongchaodeng The client failed to connection and the retry also failed.
