### ISSUE TITLE
Client responses (and client error) do not contain a string that the server is stopping

### ISSUE THREAD

**Issue by smarterclayton** [coreos/etcd#4625]
When the server is shutting down (the run() loop exits) for a period of time afterwards the server returns 500 due to `ErrStopped`, but that info is not passed back to the client, which means the error message the client prints is `has no leader`, which is technically correct, but makes it very hard to debug clean shutdown from a network failure or other etcd server shutdown.  We rely on etcd extensively in unit and integration tests in Kube, and so that distinction is potentially useful.  I think #4503 would be a first step to returning this.

**Comment by xiang90** [comment]
We do not really parse http response in v2 for error. We only parse http status code. So 500 is the thing you will get. For the unit test, I assume you actually control the behavior etcd. Then we can assume that 500 is caused by shutdown? No?

**Comment by xiang90** [comment]
Low activity. Please reopen if this is still an issue for you.
