### ISSUE TITLE
Watch won't close channel if cancel before

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#4626]
The scenario goes as:

- I had `ctx, cancel =context.WithCancel(...)`
- cancel() was called
- Then the `wch = Watch(ctx, key)`
- `resp, ok = <-wch` is blocked. I'm expecting that it should close and returns !ok.

**Comment by heyitsanthony** [comment]
@hongchaodeng It's returning a nll channel because of the canceled context. I can change it so it returns a closed channel instead if you'd like.

**Comment by hongchaodeng** [comment]
Returning a closed channel would make user logic look like:
```Go
resp, ok = <-wch:
if !ok {
  ...
  return
}
... handle event ...
```

Otherwise, user have to check context himself:
```Go
select {
case resp, ok = <-wch:
if !ok {
  ...
  return
}
... handle event ...

case <- ctx.Done():
}
```

It makes more sense to have context cancelling logic and other stopping logic in one place.
I would vote for returning a closed channel.
Thanks!

**Comment by xiang90** [comment]
Or you can check if ch == nil {return error}

**Comment by heyitsanthony** [comment]
I found the nil checking to be cumbersome too. I'm fine with just returning a closed channel. Will post a PR to return closed channels.
