### ISSUE TITLE
etcdctl : wrong exit codes

### ISSUE THREAD

**Issue by arteal** [coreos/etcd#4636]
Hello, i have problem, that etcdctl returns different exit codes that I assume it will from documentation :
```
0    Success
1    Malformed etcdctl arguments
2    Failed to connect to host
3    Failed to auth (client cert rejected, ca validation failure, etc)
4    400 error from etcd
5    500 error from etcd
```
When i query working etcd cluster and non-existing key i get exit code 4, which is okay :
```  
root@redis:/# etcdctl get /runtime/redis
Error:  100: Key not found (/runtime/redis) [4401167]
root@redis:/# echo $?
4
```
But when I configure ETCDCTL_ENDPOINT to localhost, where not ETCD is running :
` root@redis:/# export ETCDCTL_ENDPOINT=http://127.0.0.1:2379`
... and therefore query this key with wrongly configured etcd cluster connection I also get exit code 4, but from doc I assume it will be **exit code 2 - Failed to connect to host**, or am I wrong? :)
```
root@redis:/# etcdctl get /runtime/redis
Error:  dial tcp 127.0.0.1:2379: getsockopt: connection refused
root@redis:/# echo $?
4
```
I have etcdctl version 2.2.4 :
```
root@redis2:/# etcdctl -v
etcdctl version 2.2.4
```

**Comment by gyuho** [comment]
Error code 2 means bad connection. Error code 4 means server error.
So error 4 is expected because it's error from misconfigured cluster.

**Comment by gyuho** [comment]
If you want to look at the code, https://github.com/coreos/etcd/blob/master/etcdctl/command/error.go.

Please let me know if you have any other question.

Thanks!

**Comment by heyitsanthony** [comment]
@arteal it's a bad connection because etcdctl can't establish a connection to etcd because it's being passed an address that doesn't point to an etcd server instance. The client is misconfigured (hence, bad connection), not the sever.

**Comment by arteal** [comment]
Ok, then text is a bit misleading, at least for me, because I have i see "etcd" as etcd server/cluster and "400 error" as return code, so I will just think that I will never get return code from server that I can not reach, but that kinda my "personal problem" and big thanks for your clarifiation.
Still I want to ask you if, you guys, can help to solve my original problem, i need something like this :
```
etcdctl get /runtime/redis 2>/dev/null
if [ $? -eq 4 ];then
 echo "var not found, create it"
  if [[ $(etcdctl set /runtime/redis "set") != "set" ]];then
    echo "cannot setup runtime var, exiting"
    exit 1
  fi
elif [ $? -eq 1 ]; then
  echo "error connection to ETCD cluster, exiting"
  exit 1
fi
````
Is this functionality possible with etcdctl or should I have to use some, for instance, Ruby client?

Thanks very much for patiance and answer!

**Comment by heyitsanthony** [comment]
@arteal Yes, use `elif [ $? -eq 2 ];` instead.

**Comment by arteal** [comment]
@heyitsanthony : yeah, this is typo and there should have been `elif [ $? -eq 2 ];`, but still, there is problem why i created this issue : when connection to ETCD fail, etcdctl get return exit code 4, so my code is not working, because first if will be true if key is not found and also if connection fails and I need to make difference between these situations.

**Comment by heyitsanthony** [comment]
@arteal Right, I fixed that bug two months ago. I see the fix is in 2.3.0.alpha-1 but not 2.2.5.

@gyuho should 4477ef636e43fa6c8f9e45523a11377764c873df be backported?

**Comment by gyuho** [comment]
Oh we might have forgot to include that patch. We can backport in the next release. Thanks!

**Comment by xiang90** [comment]
This issue is fixed in master. We are doing a 2.3 release. It will come out probably next week.
