### ISSUE TITLE
etcd search feature

### ISSUE THREAD

**Issue by dbubs** [coreos/etcd#4659]
There have been many times where it would've come in handy to have a search or find feature in etcd. For example, if you want to find a specific machine ID based on IP address and use that machine ID in a unit file. If we could do something like this, it would be awesome:
```
$ etcdctl find /_coreos.com/fleet/machines "172.17.8.101"
{"ID":"219239f2eee8410993d29d78d1ceed2e","PublicIP":"172.17.8.101","Metadata":{},"Version":"0.11.5"}
# or even
$ etcdctl find /_coreos.com/fleet/machines "*101*"
{"ID":"219239f2eee8410993d29d78d1ceed2e","PublicIP":"172.17.8.101","Metadata":{},"Version":"0.11.5"}
```
In javascript this is easy to do in code by getting all objects in the dir, but in bash it's not so trivial. That is where a find command would be very useful IMO.

**Comment by xiang90** [comment]
@dbubs It seems like this is out of the scope of etcd or etcdctl. You can pipe the output to some other user program to parse the result.
