### ISSUE TITLE
When is 2.3 planned for a release

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#4662]
Sorry not an issue, but it is overdue and just want to have an upgrade plan in place.

Does an upgrade of etcd cluster from 2.2.0 to 2.3 requires an upgrade to proxies as well, or is it optional?

**Comment by xiang90** [comment]
It is optional. We will release it in the middle of March. Sorry for the delay.

**Comment by raoofm** [comment]
@xiang90 Thanks, np just checking to plan :smile:
