### ISSUE TITLE
functional-tester: simulate network partition

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4667]
Currently functional-tester only *isolates one node* and doesn't
inject network partitions of more than one node.

1. set up 5-node
2. network partition (e.g.  isolate nodes `1` and `2` from rest of the cluster)
3. remove the network partition
4. compare revision and hashes

Good reference: https://aphyr.com/posts/281-call-me-maybe-carly-rae-jepsen-and-the-perils-of-network-partitions.

**Comment by xiang90** [comment]
We do simulate network partitions by isolate nodes today.

**Comment by gyuho** [comment]
I meant network partition of 3 / 2 nodes (out of 5)--where two nodes can still talk to each other.
Currently it drops all traffic to the port `2380`, isolating it from the whole cluster.
But I agree it's the same thing.

Thanks!

**Comment by xiang90** [comment]
@gyuho It is only because we have 3 nodes. So isolate one == partition with others.

**Comment by gyuho** [comment]
Got it.
