### ISSUE TITLE
integration: network partition + membership change

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4668]
1. 5 node at the beginning
2. remove one member to change it into 4 node cluster
3. network partition into two groups (2 nodes, other 2 nodes)
4. add node to the group with no leader 
5. Wait until that group elects a new leader
6. remove network partition
7. ensure the cluster elects only one leader and consistent revision, hash values

Reference:
- https://aphyr.com/posts/281-call-me-maybe-carly-rae-jepsen-and-the-perils-of-network-partitions
- https://aphyr.com/posts/330-jepsen-rethinkdb-2-2-3-reconfiguration

**Comment by xiang90** [comment]
We do not have to put this into functional tester. Let's make an integration test for this?

**Comment by gyuho** [comment]
@xiang90 Ok, I will write integration tests instead. Thanks.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/issues/6140.

network partition tests are enough, because when there's no leader (2 / 2 partition in 4 node cluster), cluster cannot progress anyway.

In addition, now strict-reconfig is set by default.
