### ISSUE TITLE
etcdctl: auth issues

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4692]
- [ ] etcdctl role list does not work
- [ ] etcdctl user list does not work

Do we want etcdctl also return the detailed role information for user list/get as HTTP API?

/cc @heyitsanthony

**Comment by heyitsanthony** [comment]
Hesitant to add extra role information because it'll mean meddling with the current clientv2 interfaces. Supporting that would mean either adding new functions with the "extended" information (ugly) or changing the current function return types (breaks clientv2 consumers).

**Comment by xiang90** [comment]
@heyitsanthony Agreed.
