### ISSUE TITLE
testing: TestBasicOpsPeerTLS

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4694]
```
--- FAIL: TestBasicOpsPeerTLS (2.58s)
	etcd_test.go:117: failed get with curl (expected "{\"action\":\"get\",\"node\":{\"key\":\"/testKey\",\"value\":\"foo\",\"", got "\x00{\"errorCode\":100,\"message\":\"Key not found\",\"cause\":\"/testKey\",\"index\":6}\r")
```

/cc @gyuho

**Comment by gyuho** [comment]
ok will take a look. thanks.

**Comment by gyuho** [comment]
@xiang90 I don't think there's any problem in etcd. If we have some sleep time between `set` and `get`, it should help. Currently we:

```
if err := etcdctlSet(epc, key, value, noSync); err != nil {
	t.Fatalf("failed set (%v)", err)
}

if err := etcdctlGet(epc, key, value, noSync); err != nil {
	t.Fatalf("failed get (%v)", err)
}
```

You can fairly easily reproduce this error:

```
# this cluster elected "http://127.0.0.1:12379" as a leader

./etcdctl --endpoints "http://127.0.0.1:32379" set foo bar
bar

./etcdctl --endpoints "http://127.0.0.1:32379" get foo
Error:  100: Key not found (/foo) [18]
```

The `set` request will be forwarded to leader and replicated back to `:32379`,
but sometimes it's not fast enough, especially we run `get` instantly after `set` in test.

**Comment by xiang90** [comment]
Probably we just need to retry in e2e for this? /cc @heyitsanthony

**Comment by gyuho** [comment]
I think retry should work? @heyitsanthony might have better way to handle this.

**Comment by heyitsanthony** [comment]
Maybe just have single node test clusters for tests with gets that don't go through quorum?

**Comment by xiang90** [comment]
Yea. Sure

**Comment by gyuho** [comment]
Ok that sounds good to me. @heyitsanthony Could you change the e2e test settings? Thanks!
