### ISSUE TITLE
watch prefix issues

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4697]
In client library and storage range/delete, we treat `/x00` as the largest key if it is in "end".

However in interval tree, we treat empty as the largest key.https://github.com/coreos/etcd/blob/master/pkg/adt/interval_tree.go#L474

So now watch("", WithPrefix()) does not work.

@heyitsanthony What is your opinion on this one? Shall we convert /x00 to empty string and empty string to /x00 before pass into watch? This seems to be the easies fix, but it also makes range/delete and watch different.

**Comment by heyitsanthony** [comment]
@xiang90 I think the simplest fix is to use "\x00" as the affine point instead of "" for StringAffineComparable

**Comment by xiang90** [comment]
@heyitsanthony But that also means \x00 in start will be larger than all keys.

**Comment by heyitsanthony** [comment]
@xiang90 right... converting from "\x00" to "" seems reasonable

**Comment by xiang90** [comment]
will try
