### ISSUE TITLE
It would be nice if --proxy / ETCD_PROXY would support boolean arguments

### ISSUE THREAD

**Issue by urzds** [coreos/etcd#4702]
It would be nice if --proxy / ETCD_PROXY would support boolean arguments. I.e. if it would support the string "readonly" or a boolean "on/off", "yes/no", "true/false" argument.

Why I think this way: I wrote a bootcfg YAML file where I put `etcd_proxy: on` in the metadata section. The metadata file generated by bootcfg contains `ETCD_PROXY=true` (well, modulo bugs: coreos/coreos-baremetal#85). Thus I assume that bootcfg's YAML parser interprets "on" as "true", which requires me to use string quoting for that particular value. If etcd would be a bit more relaxed, I would never have noticed about this.

**Comment by xiang90** [comment]
@urzds Proxy flag has three values, so boolean is not enough. We do not want to introduce more flags and make one flag (proxy needs to support the old string and the boolean you proposed) accept multiple set of values at this point.
