### ISSUE TITLE
clientv3: embedded client

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#4709]
In the future, some features implemented through the client may be "embedded" in the server for better performance (e.g., locks). Ideally, these features should work on the server without additional modification. Right now clientv3 expects to connect via gRPC to an etcd v3 server. In order to get good performance for the embedded case, the embedded client implementation should directly call the interfaces in api/v3rpc instead of going through grpc.

**Comment by heyitsanthony** [comment]
done in #7444 via etcdserver/api/v3client

**Comment by xiang90** [comment]
@heyitsanthony Do we have an example or doc to talk about how to embed client?

**Comment by heyitsanthony** [comment]
@xiang90 no. Is this a feature that should be advertised with examples or a doc? I think the usage is kind of straightforward, but an example could be added to v3client's doc.go...

**Comment by xiang90** [comment]
@heyitsanthony Initially an example would be good. If people start to ask about it, we can add a doc. What do you think?

**Comment by heyitsanthony** [comment]
ok will add something to doc.go

**Comment by timothysc** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/43088
