### ISSUE TITLE
Difficult to get stats of failing nodes from client without knowing leader

### ISSUE THREAD

**Issue by haneefkassam** [coreos/etcd#4722]
etcd is a pretty neat piece of software.  I'm getting into using it's full functionality (to use it with Kubernetes), but I'm running into a challenging problem that should be much easier.  Let me run you through my setup:

I have a 3 master etcd cluster set up (s1, s2, s3), running as docker containers in 3 separate vms.  as a test, I destroy 1 VM (suppose the leader, s3) and re-create it.  I'm trying to do all of this through a script to provision a master machine and add it to the etcd cluster.

However, now when I try to startup the etcd docker container (with `--initial-cluster-state existing`), I get a Index out of range (another ticket mentioned this is because the data directory is corrupt, so the member needs to be removed and re-added).  Great, this works.

My problem is it's kinda tough to find out which machine to remove.  I could randomly pick a server and call self stats on it `http://s1/v2/stats/self` to find out the leader id, but now I can't call `http://s1/v2/stats/leaderId`.  I need to somehow call leader stats on the right machine.  Ok, so I get the members (i can use s1 cause it returned a valid response so I know it's up), `http://s1:2379/v2/members`.  I now have to find the json document for the member associated with leaderId.  Now I have the clientUrl, so I can get leader stats, `http://leaderClientUrl:2379/v2/stats/leader`.  Now I can check the fail count to know the id of the member to remove, but still need to call `[DELETE] http://s1:2379/v2/members/<failingMemberid>`.

Why do I have to go through so many hoops just to remove a member?  I can add/remove a member from any other member in the cluster.  I should be able to get the stats of any member, and the leader as well, from any member of the cluster, not to mention use their ids to get/set/manipulate them.  sure, `/v2/stats/self` and `/v2/stats/leader` are nice vanity paths, but why can't i use the actual ID of the member to get its stats, or information about it? I have to use the ID to delete it from the cluster.

**Comment by gyuho** [comment]
@haneefkassam 


> I can add/remove a member from any other member in the cluster. I should be able to get the stats of any member, and the leader as well, from any member of the cluster


Are you suggesting something like?

```
[DELETE]  http://failingMemberURL:2379/v2/members/<failingMemberid>
```

Thanks.

**Comment by haneefkassam** [comment]
No, I'm suggesting the following:

`[GET]  http://<anyRunningMemberURL:2379/v2/members/<anyMemberId>` (to get info about that member, like the stuff returned from /v2/members, but specific for that member)

`[GET]  http://<anyRunningMemberURL:2379/v2/stats/<anyMemberId>` (to get stats about that member, including if it's running or not)

Also,

`[GET]  http://<anyRunningMemberURL:2379/v2/stats/leader`

should give me the information about the leader; I should not need to go to the leaderURL to get this information.  If etcd is supposed to be distributed, it shouldn't matter which url I go to to obtain the information.  Forcing the user to go to the leader's URL to obtain information about the network means etcd is not really distributed.

Since the leader stats will tell me which members are failing, it can allow me to take down a member (if the fail count is too high), remove it from the cluster, and start up a new member and add it to the cluster.

**Comment by gyuho** [comment]
I understand. 

We have some real-time data in [`stats`](https://github.com/coreos/etcd/blob/0fde354eba7c301302ffb3be10b915ae8a683efc/etcdserver/stats/server.go#L31-L43), so I think replicating them to nodes other than leader
won't be accurate. Any thoughts?

/cc @xiang90 @heyitsanthony

**Comment by haneefkassam** [comment]
They don't necessarily need to be propagated to the other nodes; just proxy the request to the leader.  Reduces the number of calls to remove a member from a cluster by half.
(sorry, had to throw that in. I will wait for input from cc'd members)

**Comment by haneefkassam** [comment]
After thinking about it, an alternative solution would be to provide the leaderURL in the leader object in /stats/self.  Either option work; both make it much easier to get at the cluster health/status.

**Comment by xiang90** [comment]
@haneefkassam We are not going to change v2 API unfortunately. I think there are work arounds like doing one more API calls as you mentioned. And you can actually use etcdctl cluster-health to figure out which member fails. 

In etcd3, we also provide a tool to figure out which member is failing: etcdctl endpoints health.

**Comment by xiang90** [comment]
We already have the etcdctl endpoints heath command supported. So I am closing this one.
