### ISSUE TITLE
go vet fails in go tip branch

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4723]
From this change https://github.com/golang/go/commit/867910ea170cad67ef929ae472f1e19052da7d7c:

https://travis-ci.org/coreos/etcd/jobs/114625304

```
github.com/coreos/etcd/etcdmain/config.go:178: no formatting directive in Panicf call
```

Problem is it complains about capnslog too, even if it formats correctly:

https://github.com/coreos/etcd/blob/master/etcdmain/config.go#L178

```
plog.Panicf("unexpected error setting up discovery-fallback flag: %v", err)
```

**Comment by xiang90** [comment]
Can you try to fix it?

**Comment by gyuho** [comment]
Yeah I looked into it. Need to look at the source code more. Will fix. 

Thanks.

**Comment by gyuho** [comment]
The original author has acknowledged the issue here https://github.com/golang/go/issues/14754. Will wait on that.

**Comment by xiang90** [comment]
I am closing this one since it seems like this is a go issue, not etcd issue.

**Comment by gyuho** [comment]
Agree. I will keep an eye on the upstream issue https://github.com/golang/go/issues/14754.
