### ISSUE TITLE
client listening supports tls and non-tls

### ISSUE THREAD

**Issue by philips** [coreos/etcd#4737]
I thought I already filed this issue but I can't find it now.

We should support having both TLS and non-TLS communication for clients of v2 as a migration path. I imagine it would essentially look like:

```
ETCD_LISTEN_CLIENT_URLS="http://10.0.0.1:2379,https://10.0.0.1:2379"
ETCD_ADVERTISE_CLIENT_URLS="http://10.0.0.1:2379,https://10.0.0.1:2379"
```

We would obviously need to use something like cmux to make this possible but I think easing this migration path onto TLS is worth the trouble.

**Comment by raoofm** [comment]
+1
