### ISSUE TITLE
Use different ectdctrl exit code

### ISSUE THREAD

**Issue by jmcollin78** [coreos/etcd#4740]
Hello,

etcdctl exit code is always 4 on error (etcd not responding or key absent or -maybe more-).
It should be possible to know if ectd was not present or if the key was not found just with the exit code.
Now we must deal with the error string which is not accurate.

Thanks for all of your works. It's rocks :!

**Comment by heyitsanthony** [comment]
@jmcollin78 what version of etcdctl are you using? this may already be fixed. Cf. #4053 and #4636

**Comment by xiang90** [comment]
@heyitsanthony I assume this is already fixed by the issue you mentioned. The new etcdctl is also released in 2.3 release branch. So I'm going to close this issue.
