### ISSUE TITLE
raft.Node can forget ConfChange Remove proposals

### ISSUE THREAD

**Issue by peterbourgon** [coreos/etcd#4759]
I'm using raft.Node in my project to run etcd over a gossip (UDP-like) transport. For me, peers are ephemeral: they come and go frequently, when they go they're gone permanently, and when they start up they're always empty. So far this works OK by making the Raft node ID be basically a UUID. But I think I've discovered a bug in how the raft.Node handles ConfChange Remove proposals.

Let's say I have a cluster of 4 peers, everything working well. I hard kill one of the followers, it will never come back :) Immediately, the UDP transport of the leader starts failing to deliver Heartbeat messages to the dead follower. It dutifully calls node.ReportUnreachable for each failed message — please tell me if that's not right. After a few hundred milliseconds, the transport subsystem detects the peer is gone, and _every remaining node in the cluster_ including the leader emits a ConfChange Remove proposal to remove the dead peer. But those proposals never get committed! They appear to be simply lost. The leader continues to spam failed Heartbeat messages forever.

However, if instead of immediately emitting the ConfChange Remove, I buffer it and continuously submit it every second until I receive a committed ConfChange Remove entry with the corresponding peer ID, then everything seems to work OK. To me, this looks like a timing bug in the raft.Node.

[Here's a link to the interesting bit of the code](https://github.com/weaveworks/mesh/blob/3fa02068b12abd0c111a3e1b6d5adacf06a4e9c4/examples/raft-on-mesh/membership.go#L101-L116). And here are steps to reproduce. First, install the code.

``` sh
mkdir -p $GOPATH/src/github.com/weaveworks
cd $GOPATH/src/github.com/weaveworks
git clone https://github.com/weaveworks/mesh
cd mesh
git checkout raft-on-mesh # 3fa0206 at time of writing
go install github.com/weaveworks/mesh/examples/raft-on-mesh
```

Then, to see the failing behavior, launch some nodes in separate terminals with -buffer=false.

``` sh
raft-on-mesh -quicktest=1 -buffer=false
raft-on-mesh -quicktest=2 -buffer=false
raft-on-mesh -quicktest=3 -buffer=false
raft-on-mesh -quicktest=4 -buffer=false
```

Inspect the logs to find a follower, and ctrl-C that node. Observe the ConfChange proposal is submitted but never committed, and the leader gets into an infinite loop.

Now, to see the working behavior, do the same thing with -buffer=true.

``` sh
raft-on-mesh -quicktest=1 -buffer=true
raft-on-mesh -quicktest=2 -buffer=true
raft-on-mesh -quicktest=3 -buffer=true
raft-on-mesh -quicktest=4 -buffer=true
```

Repeat and see that the ConfChange proposal is both submitted and committed, and the leader spams Heartbeats for about a second before moving on to the new, stable configuration.

**Comment by xiang90** [comment]
@peterbourgon I believe raft only forgets about proposals if there the leader is dead and everyone else still believe it is the leader (they are not timeout yet). This is because the followers will still forward the proposals to the dead leader until there is a new leader elected (or someone becomes a candidate). Can you try to kill a follower and check if any proposal will get lost?

**Comment by peterbourgon** [comment]
In the example, that's what I do:

> I hard kill one of the followers

And anyway if I kill the leader I still need some way of getting feedback that my proposals are lost/rejected, don't you think?

**Comment by xiang90** [comment]
@peterbourgon Is there still a problem for you?

If you kill the follower, no proposal should be lost. Conf change is the same as any other proposals. We never see this happen in our test. So I guess there is an issue with your code.

> And anyway if I kill the leader I still need some way of getting feedback that my proposals are lost/rejected, don't you think?

The application should be able to figure this out. If the network layer fails to deliver it, it gets lost. If term changes, but the proposal does not get committed, then application knows there is a conflicting proposal and this proposal is rejected.

**Comment by peterbourgon** [comment]
I haven't touched this code in 9 months and am unlikely to pick it up again. To reproduce, please see the quite explicit steps above; I hope I've been clear enough :) If killing a follower no longer results in hanging (as described) then I guess you've fixed the bug in the interim.

**Comment by xiang90** [comment]
@peterbourgon There is no raft-on-mesh branch anymore. If you do not plan to work on it again, I guess I do not need to help at the moment. Let us know if you want to work on it more in the future. Thanks.
