### ISSUE TITLE
clientv3: polish naming conventions

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#4767]
I've been noticing inconsistent naming when writing code against the v3 client (namely for modified revisions, but there are likely similar problems elsewhere). A quick grep on 'Mod' returns:
```
clientv3.WithSort(clientv3.SortByModifiedRev,
v3.ModifiedRevision(newKey)
v3.WithRev(kv.ModRevision)
wr.Events[0].Kv.ModRevision
```
`Rev` or `Revision`? `Mod` or `Modified`? `ModRev`, `ModifiedRevision`, `ModRevision`, or `ModifiedRev`? I usually have to look it up or guess.

**Comment by xiang90** [comment]
Move to alpha. We probably should solve this soon.

**Comment by ajityagaty** [comment]
I can give this a try if nobody is looking into it at the moment.
Please let me know what should be the naming convention that we need to stick to.

**Comment by xiang90** [comment]
@heyitsanthony I vote for modRevision.

**Comment by heyitsanthony** [comment]
@xiang90 fine by me

**Comment by ajityagaty** [comment]
@xiang90 @heyitsanthony Please clarify my following doubts:

[1] @xiang90 Any specific reason why you mentioned a lowercase ‘m’ in modRevision? The ModRevision field of the KeyValue struct (generated from kv.proto file) is an exposed field. So shouldn’t we use an upper case ‘M’ in all places for consistency?

[2] If we change 'SortByModifiedRev' to 'SortByModRevision' then we should probably change 'SortByCreateRev' to 'SortByCreateRevision'?

**Comment by xiang90** [comment]
@ajityagaty In go, the first letter indicates if the field is private or public. For kv struct, M needs to be capitalized since we need to expose that field.

[2] Yes. we should. but let's do one by one?

**Comment by ajityagaty** [comment]
@xiang90 Yes, I understand the private/public part. I got a little confused when you mentioned "I vote for modRevision".

I agree, doing the changes one by one would be better. Will try to put out the first patch tonight.

**Comment by xiang90** [comment]
>  I got a little confused when you mentioned "I vote for modRevision".

Sorry about that.
