### ISSUE TITLE
Cannot add a new member to the existed cluster

### ISSUE THREAD

**Issue by whelan957** [coreos/etcd#4789]
I followed the steps here to add a new member:
https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#cluster-reconfiguration-operations 

It was successful to finish the first step:

$ etcdctl member add zcm2alter http://10.5.0.8:2380
Added member named zcm2alter with ID ca29fb857800f591 to cluster

ETCD_NAME="zcm2alter"
ETCD_INITIAL_CLUSTER="b75689dad64949ff85a0e1c176e30d99=http://10.5.0.5:2380,6122e5b977df4cf39b43cf314a9dcef7=http://10.5.0.6:2380,=http://10.5.0.7:2380,zcm2alter=http://10.5.0.8:2380,da9966450d6845cab6a0f167943d4a00=http://10.5.0.4:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"

But when I tried to start this new member with
$ etcd -listen-client-urls http://10.5.0.8:2379 -advertise-client-urls http://10.5.0.8:2379  -listen-peer-urls http://10.5.0.8:2380 -initial-advertise-peer-urls http://10.5.0.8:2380

I kept receiving error message:  flag provided but not defined: -listen-client-urls

If I directly used : $etcd zcm2alter
I got message as followed

[etcd] Mar 17 03:33:30.752 WARNING   | Using the directory zcm2alter.etcd as the etcd curation directory because a directory was not specified. 
[etcd] Mar 17 03:33:30.761 INFO      | zcm2alter is starting a new cluster
[etcd] Mar 17 03:33:30.763 INFO      | etcd server [name zcm2alter, listen on :4001, advertised url http://127.0.0.1:4001]
[etcd] Mar 17 03:33:30.764 CRITICAL  | Failed to create listener: listen tcp :4001: bind: address already in use

I operated those instructions on a available member of the existed Azure VM cluster  and the etcd version is 
$ etcd -version
etcd version 0.4.9

Am I missing something?
Please help, thanks!!!

**Comment by xiang90** [comment]
@whelan957 Are you on CoreOS? you should try etcd2, not etcd.

**Comment by whelan957** [comment]
Yes, I'm using CoreOS. Thanks!

I tried etcd2 and got the message
 $  etcd2 -listen-client-urls http://10.5.0.9:2379 -advertise-client-urls http://10.5.0.9:2379  -listen-peer-urls http://10.5.0.9:2380 -initial-advertise-peer-urls http://10.5.0.9:2380
2016-03-17 06:38:11.982416 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=b75689dad64949ff85a0e1c176e30d99=http://10.5.0.5:2380,6122e5b977df4cf39b43cf314a9dcef7=http://10.5.0.6:2380,zcm3alter=http://10.5.0.9:2380,da9966450d6845cab6a0f167943d4a00=http://10.5.0.4:2380
2016-03-17 06:38:11.982560 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
2016-03-17 06:38:11.982625 I | flags: recognized and used environment variable ETCD_NAME=zcm3alter
2016-03-17 06:38:11.982732 I | etcdmain: etcd Version: 2.2.0
2016-03-17 06:38:11.982785 I | etcdmain: Git SHA: e4561dd
2016-03-17 06:38:11.982821 I | etcdmain: Go Version: go1.4.2
2016-03-17 06:38:11.982878 I | etcdmain: Go OS/Arch: linux/amd64
2016-03-17 06:38:11.982914 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
2016-03-17 06:38:11.982962 W | etcdmain: no data-dir provided, using default data-dir ./zcm3alter.etcd
2016-03-17 06:38:11.983081 C | etcdmain: listen tcp 10.5.0.9:2380: bind: cannot assign requested address

The new member's status remains unstarted.
$ etcdctl member list
880b7ade4abf4cc: name=b75689dad64949ff85a0e1c176e30d99 peerURLs=http://10.5.0.5:2380 clientURLs=http://10.5.0.5:2379,http://10.5.0.5:4001
3f2a2551adfd53cd: name=6122e5b977df4cf39b43cf314a9dcef7 peerURLs=http://10.5.0.6:2380 clientURLs=http://10.5.0.6:2379,http://10.5.0.6:4001
641165bfc5faed34[unstarted]: peerURLs=http://10.5.0.9:2380
f4be4c7676891b9f: name=da9966450d6845cab6a0f167943d4a00 peerURLs=http://10.5.0.4:2380 clientURLs=http://10.5.0.4:2379,http://10.5.0.4:4001

And the discovery web only shows three original members.
https://discovery.etcd.io/c662b94688740272690815e81a3d705e

But I can find the new member at fleetctl list-machines.
$ fleetctl list-machines
MACHINE		IP		METADATA
6122e5b9...	10.5.0.6	-
b75689da...	10.5.0.5	-
da996645...	10.5.0.4	-
f79c5f91...	10.5.0.9	-

The new member's cloud config is the same with the existing members.

Is this working correctly or I just miss something?

**Comment by whelan957** [comment]
And then I removed member 10.5.0.6. (My intention is to replace a member)
$etcdctl member remove 3f2a2551adfd53cd

But fleetctl still can find it.
$ fleetctl list-machines
MACHINE IP METADATA
6122e5b9... 10.5.0.6 -
b75689da... 10.5.0.5 -
da996645... 10.5.0.4 -
f79c5f91... 10.5.0.9 -

So I shut down the VM 10.5.0.6 and deploy my services on the new member 10.5.0.9.
My services were fine on the new member 10.5.0.9 so I thought I can continue to replace next member by adding another new member 10.5.0.7 first.
When I tried to add the second new member, error occured:
$ etcdctl member add zcm1alter http://10.5.0.7:2380
client: etcd cluster is unavailable or misconfigured

And etcdctl member list now looks like this
$ etcdctl member list
3f2a2551adfd53cd: name=6122e5b977df4cf39b43cf314a9dcef7 peerURLs=http://10.5.0.6:2380 clientURLs=http://10.5.0.6:2379,http://10.5.0.6:4001
641165bfc5faed34[unstarted]: peerURLs=http://10.5.0.9:2380
e5faa48c28e7328d[unstarted]: peerURLs=http://10.5.0.7:2380
f4be4c7676891b9f: name=da9966450d6845cab6a0f167943d4a00 peerURLs=http://10.5.0.4:2380 clientURLs=http://10.5.0.4:2379,http://10.5.0.4:4001

And now I cannot do anything with fleetctl since this error keeps showing up
$ fleetctl list-units
Error retrieving list of units from repository: googleapi: Error 503: fleet server unable to communicate with etcd

And I cannot remove member from the cluster, too.
$ etcdctl member remove e5faa48c28e7328d
Recieved an error trying to remove member e5faa48c28e7328d: client: etcd cluster is unavailable or misconfigured

Please help, thanks!

**Comment by xiang90** [comment]
@whelan957 

> 2016-03-17 06:38:11.983081 C | etcdmain: listen tcp 10.5.0.9:2380: bind: cannot assign requested address

There is something wrong with your configuration. Please make sure the listen addr can be bind by etcd.

**Comment by whelan957** [comment]
Here is my configuration.

#cloud-config

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: "https://discovery.etcd.io/c662b94688740272690815e81a3d705e"
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380
    heartbeat-interval: 600
    election-timeout: 6000
  fleet:
    public-ip: $private_ipv4
    engine-reconcile-interval: 10
    etcd-request-timeout: 5
    agent-ttl: 120s
  units:
    - name: etcd.service
      mask: true
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start

How can I fix it?
Or where can I find more information about this issue?

**Comment by xiang90** [comment]
@whelan957 

We cannot really help since this is not an etcd issue I believe. All we can know from the log is that the IP/port address you in your configuration for etcd cannot be assigned. You have to check if the IP is assigned to any network interfaces of the machine. 

To be more specific, you need to know where that `10.5.0.9:2380` come from and why it does not belong to the machine you were running etcd on.

**Comment by xiang90** [comment]
@whelan957 Please check the IP in your configuration. Probably you can try to bind the ip:port via `nc -l 10.5.0.9 2380`. I believe it will compliant the same thing. Report back if it is not and you believe this is an etcd specific issue.

**Comment by horizon365** [comment]
in my case ,i find can't  `ping 127.0.0.1` , so i run `ifconfig lo up` ,it works !
