### ISSUE TITLE
etcdctlv3: version command proposal

### ISSUE THREAD

**Issue by mqliang** [coreos/etcd#4796]
@xiang90 
`etcdctl --version` in etcdv2 just show client version. It would be much helpful if it can demonstrate server side version(for example all members' version).

I'd like `etcdctl version` command in etcdv3  print as follows:
```
Client Version: etcdctl version 3.0.0
Server Version: infra1 version 3.0.0
                infra2 version 3.0.0
                infra3 version 3.0.0
```

 Does this sounds good?

**Comment by xiang90** [comment]
etcdctl version is not a good place for this sort of thing. To get the server version, ctl needs to communicate with the server over the network. etcdctl version, on the other side, should be as simple as possible.

Another issue is that server version is not even exposed by v3 rpc (https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto). probably the first step is to define a memberStatus rpc in cluster service https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L65 to expose some server status.

**Comment by mqliang** [comment]
Agree. Close this in favour of https://github.com/coreos/etcd/issues/4797
