### ISSUE TITLE
v3: add memberStatus rpc in cluster service

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4797]
We should start with the simplest status: version.

1. add new rpc into https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L76

2. generate the proto by running ./script/genproto.sh

3. implement the rpc in pkg etcdserver/api/v3rpc pkg

4. implement client side api in pkg clientv3

5. implement etcdctl command member status 

We can expose more member status like its raft status, db size, etc..

**Comment by xiang90** [comment]
@mqliang Do you want to take this one?

**Comment by mqliang** [comment]
@xiang90 Interesting, I am in.

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/pull/4957
