### ISSUE TITLE
X-Etcd-Index should be the state of the reponse

### ISSUE THREAD

**Issue by DanielYWoo** [coreos/etcd#4799]
The official doc says

> X-Etcd-Index is the * **current** * etcd index as explained above.

But this is not true with wait query.

If I issue a GET /somekey and it returns X-Etcd-Index=5, that's correct and conforms the official doc,  the index 5 is just the index represents the current value in the response body, it's cool and I can increment the index by one to wait for a change
```
GET /somekey?wait=true?waitIndex=6
```
So far, everything is cool.

However, if the key has been changed, in our case let's say the index has been rolled from 5 to 6, the wait query returns the new value which is in version 6, but the response header X-Etcd-Index is still 5 which is not consistent with the value in the response body, and violates the official doc. The returned index  is actually *before* the waitIndex I asked, it's the index starts the watch, not the current state of the response. 

This inconsistency definition of X-Etcd-Index makes wait query very tricky, if I don't want to miss a thing or encounter duplicated events for the next wait, I have to increment the returned index by two, which is 5 + 2 = 7. The rule is:

1. normal query returns index X
2. wait for X + 1
3. something changes, you get the change along with an "earlier index" X
4. wait for X + 2
5. something changes, you get the change along with an "earlier index" X, loop to step 4
 
If we can make X-Etcd-Index return consistent value, this process will be simplified and we always wait for X + 1, done.

 
Affected version: 2.3.0-alpha.0+git

**Comment by xiang90** [comment]
@DanielYWoo Please check the doc here https://github.com/coreos/etcd/blob/master/Documentation/api.md#waiting-for-a-change. You should use modified index. If you check the next section after it, it talks about when you should use etcdindex.

etcdindex is the current index when etcd receives the request for watch.
