### ISSUE TITLE
No changelog in v2.3.0 and v2.3.0-alpha.1

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#4804]
A small thing though but to be consistent, I thought it was agreed to have a changelog for each release.

**Comment by xiang90** [comment]
@raoofm We usually keep detailed change log for minor release. For major release like 2.3, there are over 2000+ commits. So we just highlights the new features and major improvements. github keeps all the commit history anyway. So I do not think it worth the effort to catalog all the 2000 commits for now. We might improve this in the future.

**Comment by raoofm** [comment]
@xiang90 ok thanks
