### ISSUE TITLE
How etcd client to use https api?

### ISSUE THREAD

**Issue by zhuqunzhou** [coreos/etcd#4818]
Under `etcd` client source,i don't find any `https` api.

How i to use the client to do the same thing such as `curl --cacert /path/to/ca.crt --cert /path/to/client.crt --key /path/to/client.key -L https://127.0.0.1:2379/v2/keys/foo`?

Thanks!

**Comment by xiang90** [comment]
@zhuqunzhou Pass in the tls config here https://github.com/coreos/etcd/blob/master/clientv3/client.go#L68.
