### ISSUE TITLE
a new etcd node failed to join discovery cluster

### ISSUE THREAD

**Issue by wpengcheng** [coreos/etcd#4820]
when a was execute etcd.sh,At that time happens failed to join discovery cluster (context deadline exceeded),discovery token https://discovery.etcd.io/7cd332f0b753d6852b6e1cc121668dcc was used, but failed to bootstrap the cluster. please generate a new discovery token and try to bootstrap again.

attach:this is my etcd.sh
etcd -name xcloud230 -initial-advertise-peer-urls http://172.18.1.230:2380 \
-listen-peer-urls http://172.18.1.230:2380 \
-listen-client-urls http://172.18.1.230:2379,http://127.0.0.1:2379 \
-advertise-client-urls http://172.18.1.230:2379 \
-discovery https://discovery.etcd.io/7cd332f0b753d6852b6e1cc121668dcc

**Comment by xiang90** [comment]
@wpengcheng You can follow the the instruction and generate a new token. Do not reuse the discovery token (always use new one in your etcd.sh).

For more information, you can read https://github.com/coreos/etcd/blob/master/Documentation/runtime-reconf-design.md#do-not-use-public-discovery-service-for-runtime-reconfiguration

**Comment by xiang90** [comment]
I am closing this due to low activity. Please reopen if this is still an issue.
