### ISSUE TITLE
unreleased bundled components

### ISSUE THREAD

**Issue by onlyjob** [coreos/etcd#4821]
Latest release 2.3.0 bundles unreleased "boltdb" so Etcd FTBFS when built with latest stable release of BoltDB: https://github.com/boltdb/bolt/releases

Please, pretty please only bundle/vendor official semantic releases of Etcd dependencies.

That kind of issues waste time and cause a lot of pain to downstream package maintainers effectively preventing packaging of latest Etcd release.

Same problem is with `github.com/codegangsta/cli` and some other dependencies...

Thanks.

**Comment by xiang90** [comment]
@onlyjob Some dependencies (gRPC/bolt/proto3) are for the experimental v3 API. And some dependencies do not really do releases regularly like `codegangsta/cli`. For some dependencies, they are some simple that do not really even do releases at all like `https://github.com/jonboulle/clockwork`.

We now do not have a good policy around these. We can try to resolve them. Or you can propose a policy that you think are both reasonable and doable for a fast moving project like etcd. 

Thanks.

**Comment by onlyjob** [comment]
Is there a way to build without v3 API? How can one disable a component in Golang? I wish there were something like `--without=v3api`...
It is true that some dependency don't have formal release.
But it would be great to rely on semantic versioning for those libraries that version their releases.

As for policy there should be rule to use only stable releases of dependencies whenever possible... I'd like to stress that as hard as possible.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning
 * [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions)

**Comment by philips** [comment]
@onlyjob you cannot disable components in Golang without changing code.

We can't slow down the release cadence of etcd based on downstream libraries, I am sorry. Is there a problem you are trying to solve for?

**Comment by onlyjob** [comment]
> Is there a problem you are trying to solve for?

I'm trying to maintain [Etcd package](https://packages.qa.debian.org/e/etcd.html) in [Debian](http://debian.org) and now it feels like problem due to irresponsible use of dependencies...

> We can't slow down the release cadence

It would be truly terrible if the only priority of Etcd development is rapid releasing.
It is _stable releases_ I'm talking about. Semantic versioning is there for good reasons.
You can't just ignore release process of your dependencies without running into problems.

Ask BoltDB to release a new version if you need one. Stop throwing away 20+ years of best practice in software engineering. Also it would be nice to be a bit friendlier to downstream maintainers... Thanks.

**Comment by xiang90** [comment]
> It would be truly terrible if the only priority of Etcd development is rapid releasing.

The first priority of etcd development is reliability/stability. We do fast release to fix users issues. If there is a unreleased version of dependency that fix users issues, we might compromise the just use it. We cannot force downstream to do release and we do not really enjoy forking. Moreover, etcd does not rely on external package for core functionality. We usually carefully choose dependencies and keep an eye on their development.

On the other side, we do understand your concerns and respect your opinion. We will try to use stable release when possible. I agree we should have put more effort into this. But as you mentioned in your proposal, it is a best effort thing. There is no guarantees that we will ALWAYS use the stable release of the dependency or ONLY use stable release of any dependency.

**Comment by onlyjob** [comment]
Thank you.

**Comment by onlyjob** [comment]
boltdb 1.2.0 is released so it should be safe to re-vendor it by tag.

**Comment by xiang90** [comment]
@onlyjob Thanks for the head up. We already updated the dep a few days ago: https://github.com/coreos/etcd/pull/4946.

We will release a new version of etcd with this update soon.

**Comment by onlyjob** [comment]
That's very nice, thank you. :)

**Comment by xiang90** [comment]
@onlyjob I will keep this issue open until we figure out a reasonable policy around managing our dependencies.

**Comment by onlyjob** [comment]
Much appreciated. :)

**Comment by xiang90** [comment]
@onlyjob Do you have a script to check the using of unreleased dependencies? Or you do this manually?

**Comment by onlyjob** [comment]
No script. However that kind of errors are quite visible to us in Debian because we review differences between releases (hence it is easy to spot changes to vendored libs). Also dependencies are not vendored but provided by reusable packages that are usually versioned properly so discrepancies are easy to notice especially when they are manifested as FTBFS...

**Comment by xiang90** [comment]
@onlyjob I was wondering if there is a script that we can run to find any usage of unreleased dependencies or out-of-data dependencies (only track release, not head).

**Comment by gyuho** [comment]
@xiang90 glide has interactive mode that suggests vendoring with semantic version or git SHA, so that one can choose one when running glide.

**Comment by onlyjob** [comment]
Tools like gopkg.in, getgb.io, gophers, etc. can vendor properly _by tag_. Here is some info:

 * http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases
 * http://dave.cheney.net/2016/06/26/automatically-fetch-your-projects-dependencies-with-gb

**Comment by onlyjob** [comment]
By the way _github.com/jonboulle/clockwork_ tagged a  release. :)

**Comment by gyuho** [comment]
Closing this.

We've been using semantic versioning for dependencies wherever possible, but not every project follows this practice (e.g. `golang.org/x/net`).
