### ISSUE TITLE
functional-testing: continuous deployment

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#4823]
Currently we stopped the whole cluster to redeploy either Go or etcd binaries to testing cluster.
This is necessary, but test results should be continuous. Cluster needs to be deployed without resetting the testing metrics.

**Comment by xiang90** [comment]
This does not really like an etcd issue. This is a deployment issue for our testing infra. It should be tracked somewhere else I think.

**Comment by gyuho** [comment]
agree. let's close this. it's in my todolist anyway.
