### ISSUE TITLE
etcdctlv3: add insecure-skip-tls-verify flag

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4837]
Add insecure-skip-tls-verify flag to skip cert verification when TLS is using.

**Comment by ajityagaty** [comment]
@xiang90 I am kind of new to this so please bear with me. If a user specifies --insecure-skip-tls-verify flag to etcdctlv3 then I presume this will be mutually exclusive to the other security related flags and all we have to do is set the "InsecureSkipVerify" to true in TLS config struct? Is my understanding correct?

**Comment by xiang90** [comment]
@ajityagaty Yes. You are right.

**Comment by ajityagaty** [comment]
I was trying my hand at it. I made changes to accept the flag and passed this info down to the transport.ClientConfig method via the transport.TLSConfig struct. Now ClientConfig method sets the "InsecureSkipVerify" to true in tls.Config and returns the config structure back. With this change if I try to run the etcdctlv3 command against etcd running with self signed certificates then I get the following errors:

2016/03/24 12:28:57 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/24 12:28:57 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
2016/03/24 12:28:57 transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.

Are the changes outlined above enough? Is there anything specific that needs to be done for gRPC in this regard? I am sure I am missing something.

**Comment by xiang90** [comment]
@ajityagaty Can you put up your pr as wip? then i can take a look at the code?

**Comment by ajityagaty** [comment]
@xiang90 I also have a doubt about the way to test this change. The following is the command line used to start etcd (followed the example provided in the documentation):

./etcd -name infra0 -data-dir infra0 -cert-file './certs/cert.pem' -key-file './certs/key.pem' -advertise-client-urls=https://127.0.0.1:2379 -listen-client-urls=https://127.0.0.1:2379

With this when I run "etcdctlv3 --insecure get ..." (which takes the gRPC route) it fails with the error that I mentioned above. Just to make sure I tried "curl --insecure" to the "version" REST endpoint and it worked fine.

So am I missing anything in the way I am testing this?

**Comment by xiang90** [comment]
@ajityagaty rebase with master and 

first try 
```
./etcdctlv3 --insecure-transport=false get foo bar
# you should see it is failing due to untrusted cert
```

then try

```
./etcdctlv3 --insecure-transport=false --insecure-skip-tls-verify get foo bar
# you should see it is failing due to untrusted cert
```

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/pull/4869
