### ISSUE TITLE
proposal: combine etcdctl and etcdctlv3 into one binary

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4877]
Now we have two binaries for v2/v3 API. We want to combine them into one binary to make it easy to deliver released binary to users. But we also do not want to confuse users with some magics to guess with version of API the user intend to use. Sometimes it is also impossible to infer from user input without being explicitly (for example, getting a key when the server-side has both v2 and v3 API enabled).

The proposed solution is simple (implementation and usage).

To use v3 API, user explicitly set env `ETCDCTL_V3`
```
ETCDCTL_V3=true ./etcdctl put foo bar
```

To use v3 API, user set nothing.

```
./etcdctl set foo bar
```

To implement this, we just need to add a few lines into main func

```go
isV3 := os.Getenv("ETCDCTL_V3")
os.Setenv("ETCDCTL_V3", "") // clear env after use. so it will not affect any command parsing.
if useV3(isV3) {
    v3()
    return
}
v2()
```

**Comment by xiang90** [comment]
/cc @heyitsanthony @philips @robszumski @robszumski 

Any opinion?

**Comment by gyuho** [comment]
sounds good to me. Would it work with flag parsing? Think CLI parses the flag in `init` function?

**Comment by xiang90** [comment]
We can also be smart about the naming of the etcdctl. If the binary is called etcdctlv3 we can assume user wants to use v3.

@gyuho We can make it work.

**Comment by robszumski** [comment]
The environment variable sounds ok, but I don't like relying on the name of the binary.

**Comment by xiang90** [comment]
@robszumski OK. Sure.

**Comment by heyitsanthony** [comment]
@xiang90 approach seems OK but maybe have it as `ETCDCTL_API=3` instead?
