### ISSUE TITLE
discovery.etcd.io/new - enable CORS

### ISSUE THREAD

**Issue by EgoAleSum** [coreos/etcd#4878]
I'm not sure if this is the right repository to post the issue.

I'm writing a web app that generates a config file for etcd2. The app runs in any web browser. In the app, I'm making an async request to https://discovery.etcd.io/new to generate a new token, but that request fails because the Access-Control-Allow-Origin header is missing.

Could you add a header for CORS so the /new endpoint can be called by anywhere?

**Comment by xiang90** [comment]
Please open an issue here: https://github.com/coreos/discovery.etcd.io
