### ISSUE TITLE
document - how many recent events kept by default 

### ISSUE THREAD

**Issue by DanielYWoo** [coreos/etcd#4881]
https://github.com/coreos/etcd/blob/master/Documentation/api.md#waiting-for-a-change
The docs says

> Note: etcd only keeps the responses of the most recent 1000 events across all etcd keys. It is recommended to send the response to another thread to process immediately instead of blocking the watch while processing the result.
> 

Is it the DefaultSnapCount? I guess it should be 10K, not 1K.

BTW, currently generating a snapshot is blocking ( store.clone() ), does it mean smaller snapCount pauses shorter while larger snapCount pauses longer but less  frequently?

**Comment by xiang90** [comment]
It has nothing to do with snapshot count.

> BTW, currently generating a snapshot is blocking ( store.clone() ), does it mean smaller snapCount pauses shorter while larger snapCount pauses longer but less frequently?

store.Clone() should be fast since it is just a memory copy. If you have a large dataset, yes it might block longer.
