### ISSUE TITLE
make maxdb size configurable

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4894]
I would suggest to configure it as 2GB by default and 8GB as max (internally we have 10GB limitation).

We can extend the limitation once we feel more confident about larger data set.

**Comment by heyitsanthony** [comment]
@xiang90 sure, this seems fine (although 32-bit gets crashy around 1GB...)

 How is it going to be configurable, though? etcd argument? etcdctl command?

**Comment by xiang90** [comment]
@heyitsanthony etcd argument for now. right now, we do not have any cluster wide configuration enforcement. we should support this in the future (heartbeat, election, maxdb etc. should be cluster wide consistent)
