### ISSUE TITLE
etcdctlv3: snapshot/recover design

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4896]
#### Snapshot

Snapshot command should get a point-in-time consistent snapshot of the v3 KV space

Snapshot command should not snapshot any configuration related data like clusterID or memberID.
 
TODO: handle lease?

TODO: support incremental snapshot?

#### Recover

Recover command should write configuration data provided by user like (--initial-cluster, --initial-token, etc..) and create correct member dir.

Recover command should take a snapshot and put it into the right location in the created member dir.

**Comment by colhom** [comment]
@xiang90 it looks to me like `recover` command is roughly what we called `set-config` command [here](https://github.com/coreos/etcd/pull/2366#issuecomment-157844590).

Will `recover` do integrity verification of the snapshot and return a zero exit code only if it's good? Is that even necessary?

**Comment by xiang90** [comment]
>  it looks to me like recover command is roughly what we called set-config command here, plus some additional logic to set up the data directory?

Right.

> Will recover do integrity verification of the snapshot and return a zero exit code only if it's good? Is that even necessary?

Probably we can add a --verify flag? So etcdctl can help to verify the snapshot. Or the verification will delay to server startup time. On the other side, we do expect user to verify snapshot after they store it somewhere. So a force verification seems to be redundant for some use case.

**Comment by colhom** [comment]
@xiang90 how much validation is done on `etcdctl backup`? Assuming that whatever `backup` creates with exit code 0 is "gauranteed" to be valid for `restore` on any etcd 2.x, the `--verify` flag would be redundant. Verifying the snapshot hasn't been corrupted between `backup` and `restore` is out of scope, for sure.

**Comment by xiang90** [comment]
@colhom etcdctl backup guarantees to return a good snapshot when exit with 0.

**Comment by colhom** [comment]
Ok then, imho we don't need a `--verify` flag for restore.

**Comment by xiang90** [comment]
@colhom I feel so. Thanks!

**Comment by heyitsanthony** [comment]
I think auth and alarms would need special handling too.

Maybe it'd make sense to have a special etcd KV space and use the KV machinery already in place (watchers, get) instead of managing custom buckets?

**Comment by xiang90** [comment]
@heyitsanthony In most of the cases (if not all), users just want to backup the static data not dynamic ones like leases, watcher or alarm I think.

**Comment by xiang90** [comment]
@heyitsanthony Shall we close this one?

**Comment by heyitsanthony** [comment]
@xiang90 yeah seems like it's all hammered out
