### ISSUE TITLE
etcdctl: timeouts flags questions

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#4897]
When we are trying to connect to an unavailable host, i.e.

```sh
time etcdctl --debug --timeout 5s --endpoint http://example.com:1234 ls /
```

`timeout` flag doesn't work as expected (`defaultDialTimeout` is being used by default + `--timeout` value):

```sh
start to sync cluster using endpoints(http://example.com:1234)
cURL Command: curl -X GET http://example.com:1234/v2/members
Error:  dial tcp 93.184.216.34:1234: i/o timeout

real    0m35.016s
user    0m0.011s
sys     0m0.004s
```

It works only with the `--no-sync` flag:

```sh
time etcdctl --no-sync --debug --timeout 5s --endpoint http://example.com:1234 ls /
Cluster-Endpoints: http://example.com:1234
cURL Command: curl -X GET http://example.com:1234/v2/keys/?quorum=false&recursive=false&sorted=false
Error:  context deadline exceeded

real    0m5.015s
user    0m0.008s
sys     0m0.007s
```

Is it supposed to be so?

Another related question: why is it not possible to define timeouts through the environments variables?

**Comment by gyuho** [comment]
I see the same behavior. Will take a look.

**Comment by kayrus** [comment]
Well, I wanted to fix that myself, but then decided to ask first.

**Comment by gyuho** [comment]
I think it happens when it does not use specified timeouts from flags. If you want to fix I was going to update as below. 

```go
ctx, cancel := context.WithTimeout(context.Background(), c.GlobalDuration("timeout"))
# etcdctl/ctlv2/util.go line 218
```

/cc @xiang90 @kayrus

**Comment by kayrus** [comment]
@gyuho I think we have to remove `defaultDialTimeout` variable, and use `return transport.NewTransport(tls, c.GlobalDuration("timeout")` on the 171th line in `etcdctl/ctlv2/command/util.go`.

But it is not quite clear for me yet. Probably it is necessary to implement that in function, and add parsing of the env variables.

**Comment by gyuho** [comment]
@kayrus Agree that we can just remove the default dial timeout var.
And adding helper function sounds good.
Would you like to work on that?

Thanks!

**Comment by kayrus** [comment]
@gyuho let's get @xiang90 opinion first.

**Comment by xiang90** [comment]
@kayrus 

There are two configurable timeouts for v2 client ct. ReqeustTimeout for finishing a request from an endpoint. Total timeout for finishing a command request. 

We need to make the sync honors `requstTimetout` and `totalTiemout`. check https://github.com/coreos/etcd/blob/master/etcdctl/ctlv2/command/util.go#L218.

**Comment by xiang90** [comment]
@kayrus Kindly ping.

**Comment by kayrus** [comment]
don't have time yet. can take a look later if necessary.

**Comment by kayrus** [comment]
@gyuho thanks a lot!

**Comment by gyuho** [comment]
Np! Thanks for reporting.
