### ISSUE TITLE
simplifying raft progress inflights

### ISSUE THREAD

**Issue by ongardie** [coreos/etcd#4899]
Hope this is an ok place to discuss. I came across some, shall we say, "clever", data structure for the "inflights" defined in this file: https://github.com/coreos/etcd/blob/v2.3.0/raft/progress.go#L66

My basic question is: what is the purpose of it? Is it only used for application-level flow control, to prevent the leader from sending too many entries to a follower too quickly? If that's all, would just an integer counting how many messages/entries/bytes have been sent recently get the job done?

cc @superfell

**Comment by xiang90** [comment]
> what is the purpose of it? Is it only used for application-level flow control, to prevent the leader from sending too many entries to a follower too quickly? 

Yes.

>  If that's all, would just an integer counting how many messages/entries/bytes have been sent recently get the job done?

Counting how many bytes have been sent is not enough. We want to know how many bytes are inflight. So we need to know how many bytes have been sent and how many bytes have been received. The sliding buffer is a map from index to its size. So by sliding that window, we can calculate the inflight number of bytes.

**Comment by xiang90** [comment]
@ongardie If we only want to count the inflight number of entries, then we do not need this window. A simple counter is fine.

**Comment by ongardie** [comment]
Ah, I didn't realize you were tracking bytes per message. Can you make that clear in the code comments? I see why an integer isn't enough now. I'm still confused as to which variables represent log indexes and which ones represent bytes.

Also, is inflights.size the same as len(inflights.buffer)? If so, I'd suggest removing it, and if not, please teach me Go :)

**Comment by xiang90** [comment]
> Also, is inflights.size the same as len(inflights.buffer)? If so, I'd suggest removing it, and if not, please teach me Go :)

Obviously, you know that better than me. I will try to clean inflight up and make the doc better. Thanks for bringing this up.

**Comment by ongardie** [comment]
> >  if not, please teach me Go :)

> Obviously, you know that better than me.

No way! I'm pretty sure I've written under 500 lines of Go in total still. I'm a noob.

Thanks for clarifying and working to clean this up.

**Comment by xiang90** [comment]
Closed by #6513
