### ISSUE TITLE
*: failpoints

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#4924]
There are many error conditions in etcd that are difficult to exercise but important to test for correctness. For instance, a recovery path may be exercised by inducing a crash under particular circumstances (e.g., right before a sync). However, crash cases and other exceptional states at the moment are only being chanced upon by stress testing.

Failpoints provide a way to deterministically exercise exceptional paths. Failpoints allow for injecting fake errors into running code on the fly. For etcd testing, integration tests and functional tests could set failpoints on nodes to simulate interesting failures.

I'm unaware of any go support for this yet, but I have some ideas about how it could be cleanly implemented.

Related:
https://www.bsdcan.org/2009/schedule/attachments/113_ZachLoafman.pdf
http://www.freebsd.org/cgi/man.cgi?query=fail
http://api.mongodb.org/cplusplus/2.6.1/classmongo_1_1_fail_point.html

**Comment by AkihiroSuda** [comment]
Hi, I'm working on an AOP framework for Go.
Do you think AOP is helpful for failpoints?
https://github.com/AkihiroSuda/golang-exp-aspectgo/tree/v20160401/aspectgo

There are also other existing AOP implementations for Go:
* https://github.com/deferpanic/goweave
* https://github.com/gogap/aop

**Comment by xiang90** [comment]
We have initial support already. Shall we break this up into multiple issues now?

**Comment by heyitsanthony** [comment]
@xiang90 yeah, we can close this and open individual issues as they come up. The only missing bit right now is there are no integration tests using failpoints.

**Comment by xiang90** [comment]
@heyitsanthony I am closing this out. Feel free to create smaller issues. Thanks!
