### ISSUE TITLE
redundant addNode calls will case the ProposeConfChange disabled

### ISSUE THREAD

**Issue by thundercw** [coreos/etcd#4927]
Redundant addNode calls will case the ProposeConfChange disabled because  the `r.pendingConf ` is not set to false.
```
func (r *raft) addNode(id uint64) {                                             
    if _, ok := r.prs[id]; ok {                                                 
        // Ignore any redundant addNode calls (which can happen because the     
        // initial bootstrapping entries are applied twice).                    
        return                                                                  
    }                                                                           
                                                                                
    r.setProgress(id, 0, r.raftLog.lastIndex()+1)                               
    r.pendingConf = false                                                       
}      
```

**Comment by xiang90** [comment]
@thundercw Why do you call addNode multiple times? I feel this is the user's responsibility to do this correctly.

**Comment by thundercw** [comment]
@xiang90 Yes,user has the responsibility to do this correctly. But in some scenarios, for example user`s command timeout ,will lead to issue a new command.  The new request enters the raft before the older one reach to consensus.   
I think redundant addNode have no harm to the cluster, so we always set the `r.pendingConf` to false will avoid this incorrect state.

**Comment by xiang90** [comment]
> @xiang90 Yes,user has the responsibility to do this correctly. But in some scenarios, for example user's command timeout ,will lead to issue a new command. The new request enters the raft before the older one reach to consensus.

That is fine. One addNode per command is OK as long as all your commands go through raft correctly. What is not good is that you call addNode randomly.

**Comment by xiang90** [comment]
I am closing this since it does not seem like a problem. Reopen if you have more thoughts. Thanks!
