### ISSUE TITLE
do not complaint about db file

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4935]
Now v2 snapshot does not understand db file and complaints about it
```
2016-04-01 16:32:27.050616 W | snap: skipped unexpected non snapshot file db
```

**Comment by xiang90** [comment]
@ajityagaty Do you want to look into this a little bit? This is checked in snapshot.go checkSuffix in snap pkg. We need to make db a valid filename with no suffix.

**Comment by ajityagaty** [comment]
@xiang90 Sure, I'll give it a try. Thanks !
