### ISSUE TITLE
store cluster configuration into storage

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#4943]
Now we still store all cluster configuration into v2 store. It is OK as long as we still use v2 and v3 at the same time. However it will be a problem when we want to completely disable v2 or drop v2 support in long term.

We should consider storing the configuration into storage pkg.

**Comment by ajityagaty** [comment]
@xiang90 Could you please provide more details as to how to go about this? I can give it a try if it's fairly straight forward.

**Comment by ajityagaty** [comment]
@xiang90 Oh sorry. I didn't notice that you had assigned it to yourself.

**Comment by xiang90** [comment]
@ajityagaty Sorry. Yes... I actually just finished this.
