### ISSUE TITLE
e2e: Undefined fmt in etcdctlv3_test.go

### ISSUE THREAD

**Issue by ajityagaty** [coreos/etcd#4953]
The SemaphoreCI test failed with the following error:

Running integration tests...
(github.com/coreos/etcd/e2e)
gopath/src/github.com/coreos/etcd/e2e/etcdctlv3_test.go:378: undefined: fmt in fmt.Sprintf
FAIL	github.com/coreos/etcd/e2e [build failed]

Was found while running test for PR #4952

**Comment by gyuho** [comment]
Yeah this is very strange. Somehow `fmt` got removed with multiple merges. Should be added back with https://github.com/coreos/etcd/pull/4951.

Thanks.

**Comment by heyitsanthony** [comment]
Fixed by #4955
