### ISSUE TITLE
Horizontally scalable proxy layer? What it means to end user?

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#4960]
Apologies, it is not an issue, just wanted to understand what it means to an end user as it is planned for a future etcd release.

Is there a better place to ask questions or is it expected to open an issue?

**Comment by xiang90** [comment]
@raoofm 

There are two things proxy can do:
1. caching
2. watch coalescing

If the user of can tolerant some additional latency, then we can build a proxy layer to do caching aggressively and also broadcast watch result in a much more scalable way.

**Comment by xiang90** [comment]
@raoofm Does this answer your question?

**Comment by raoofm** [comment]
Yes thanks.
