### ISSUE TITLE
Is etcd health endpoint served via http when authenticated TLS certs are used?

### ISSUE THREAD

**Issue by codefx9** [coreos/etcd#4973]
I am using Example 2 mode from here: https://github.com/coreos/etcd/blob/master/Documentation/security.md#example-2-client-to-server-authentication-with-https-client-certificates

Is etcd health endpoint served via http in that mode? I could not find any information on that in the docs.

Thanks.

**Comment by gyuho** [comment]
@codefx9 Sorry for late response.

If I understand your question correctly.

If you specify TLS for client-to-server communication, the client must call `https` like:


> etcd --name infra1 --listen-client-urls https://localhost:2379 --advertise-client-urls https://localhost:2379 --listen-peer-urls http://localhost:2380 --initial-advertise-peer-urls http://localhost:2380 --initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://localhost:2380' --initial-cluster-state new --cert-file=certs/etcd1.pem --key-file=certs/etcd1-key.pem

```
curl --cacert certs/etcd1.pem https://localhost:2379/health

# curl http://localhost:2379/health WON'T WORK.
```

Please let me know if you have any other question.

**Comment by gyuho** [comment]
@codefx9 I assume this is resolved. Please feel free to reopen or ask us any other question.
