### ISSUE TITLE
etcdctlv3: interactive flag to user add command

### ISSUE THREAD

**Issue by ajityagaty** [coreos/etcd#4977]
This is more of a usability thing.

By default when a user executes "ETCDCTL_API=3 etcdctl user add xyz" command, the password will be accepted in interactive mode. So just specifying --interactive is kind of redundant.

Setting the interactive mode as a default behavior is preferred. But wouldn't be better to have a flag that overrides the default behavior?

What was the initial thinking while adding the --interactive flag to the user command?

**Comment by mitake** [comment]
@ajityagaty The assumed usage of the flag is `--interactive=false` and let the command read password from stdin. Its main target is testing. It enables fully automated creation of a user in a test script.

**Comment by ajityagaty** [comment]
Thanks @mitake ! 
I am attempting to write the test cases for it now and I just wanted to confirm that is was mainly meant for testing :)

I think I should have posted this is in the discussion forum rather than opening an issue. Will close it.

**Comment by mitake** [comment]
@ajityagaty the test cases are helpful, thanks! But the v3 auth is in early stage so things won't be stable for a while. Please forgive me if I break things :)

**Comment by ajityagaty** [comment]
@mitake No worries! All for good cause :)

**Comment by mitake** [comment]
@ajityagaty please let me know via @ mention when you submit PRs for test cases :)
