### ISSUE TITLE
etcd returns "Key not found" error when issuing GET request soon after the etcd has started

### ISSUE THREAD

**Issue by tomek-cz** [coreos/etcd#4978]
While testing etcd-2.0.9 and etcd-2.2.5 I noticed that etcd returns invalid response when it's queried a fraction of second after the etcd daemon has started. Tested on Fedora 22 and OpenSuse 13.2

Reproduction steps:
In one terminal window on the Linux PC:
$ cd etcd-v2.2.5-linux-amd64
$ for i in {1..100}; do timeout 3 ./etcd ; done

In second terminal window on the same Linux PC:
$ CURL="curl -X GET http://127.0.0.1:4001/v2/keys/local/settings/key1"
$ for i in {1..100}; do $CURL; sleep 0.1; done

Actual  result:
{"errorCode":100,"message":"Key not found","cause":"/local","index":10}
{"action":"get","node":{"key":"/local/settings/key1","value":"testvalue,"modifiedIndex":397,"createdIndex":397}}
{"action":"get","node":{"key":"/local/settings/key1","value":"testvalue,"modifiedIndex":397,"createdIndex":397}}
(..and so on..)

Expected result:
{"key":"/local/settings/key1","value":"testvalue,"modifiedIndex":397,"createdIndex":397}}
{"action":"get","node":{"key":"/local/settings/key1","value":"testvalue,"modifiedIndex":397,"createdIndex":397}}
(..and so on..)
The REST API should not respond if the etcd has not initialised its database correctly.
Instead of valid HTTP response (but misleading) :
{"errorCode":100,"message":"Key not found","cause":"/local","index":10}
the CURL should not be able to get anything from the etcd at that time.

Implications:
On my side, imagine a function that checks for a specific critical key and if it's not there, recreating that with default value. If I am told "key not found" that means to me:
- etd is reachable and works correctly
and
- the key does not exist

...whereas it is not true. It is crucial that if etcd is available via REST API it passes valid information.

Thanks,
Tomasz

**Comment by mitake** [comment]
Hi @tomek-cz ,

I saw a similar situation in the past. How about read the key with `etcdctl get --quorum key1`? Because the get of v2 API doesn't processed by a leader in default, you might be able to see the situation that the key doesn't exist direct after creation (it heavily depends on timing).

BTW, how do you initialize the `key1`?

**Comment by tomek-cz** [comment]
Thanks @mitake 

> how do you initialize the key1?

I did it once few hours earlier and I am not modifying that.
$ curl -X PUT http://127.0.0.1:4001/v2/keys/local/settings/key1 -d value="testvaule"

> How about read the key with etcdctl get --quorum key1

When adding ?quorum=true to the CURL's URL it actually helps a lot.

I am getting either of two:
curl: (7) Failed to connect to 127.0.0.1 port 4001: Connection refused
or
curl: (52) Empty reply from server

But that's something I would expect and I can handle that by looking at the curl error codes.

Note I am using only one etcd server. I am not planning to use a cluster. 
I believe in such case quorum=true would be advised?

Many thanks,
Tomasz

**Comment by mitake** [comment]
> I am getting either of two:
> curl: (7) Failed to connect to 127.0.0.1 port 4001: Connection refused
> or
> curl: (52) Empty reply from server

Can you read the value successfully?

> I believe in such case quorum=true would be advised?

Yes. But it is a little bit strange because in a single server mode the quorum flag won't affect the result. In addition, the inconsistent state shouldn't continue for a long time (hours). Do you have any idea, @xiang90 ?

**Comment by mitake** [comment]
I missed about the timeout command. You are quickly booting and halting etcd. Maybe etcd accepts request before completing log replay?

**Comment by tomek-cz** [comment]
>Can you read the value successfully?

Yes, on the next GET attempt. And because I am restarting the service I expect its unavailability for a moment. So that is fine to me.

> In addition, the inconsistent state shouldn't continue for a long time (hours

The inconsistent state continues for a fraction of a second only. The next GET returns expected output.

I will get the logs from my single server and paste it here tomorrow so we can see if that gives us a hint about  why the quorum flag has helped.

Many thanks

**Comment by xiang90** [comment]
@tomek-cz 

This is related to https://github.com/coreos/etcd/issues/3879.

As suggested by @mitake, you can do a qget to work around this for now.

**Comment by tomek-cz** [comment]
Thank you @mitake and @xiang90, the workaround works well for me.

**Comment by xiang90** [comment]
@tomek-cz No problem! I am closing this one since this is kind of a dup of #3879.
