### ISSUE TITLE
Making watch event type recognized in client library

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#4981]
Currently in v3 watch event type is recognized by using "storagepb".DELETE/EXPIRE/PUT.

This is not very straightforward from user's perspective. Should we have it in client library to do something like:
```
clientv3.IsDeleteEvent(event)
or
event.Type == clientv3.EventDelete
```

**Comment by xiang90** [comment]
@hongchaodeng Probably you can send a pull request for this utility func for clientv3?
