### ISSUE TITLE
ID from LeaseCreateResponse should be able to used directly in WithLease

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#4988]
Currently if you use the ID from LeaseCreateResponse in WithLease option:
```
lcr := client.lease.Create(...)
client.kv.Put(..., clientv3.WithLease(lcr.ID))
```

It will complain:
```
cannot use lcr.ID (type int64) as type clientv3.LeaseID in argument to clientv3.WithLease
```

That's awkward -- both are int64 though. In order to make it work, users have to cast it:
```
clientv3.WithLease(clientv3.LeaseID(lcr.ID))
```

It would be nice from user's perspective to not cast it.

**Comment by xiang90** [comment]
I agree. /cc @heyitsanthony

**Comment by ajityagaty** [comment]
@xiang90 Would it be enough if we remove the type LeaseID and use int64 instead to address this issue?

**Comment by xiang90** [comment]
@ajityagaty We want to use LeaseID throughout the API, not int64.

**Comment by ajityagaty** [comment]
@xiang90 there are places where we are using the ID field (which is int64) directly from the protobuf generated structs (LeaseGrantResponse for example). So can you please let me know what's the thinking on handling such occurrences?

**Comment by ajityagaty** [comment]
@xiang90 Are you suggesting that we shall accept it as int64 and internally convert it into LeaseID?

**Comment by xiang90** [comment]
@ajityagaty We should use LeaseID for any public API. We need to convert it to int64 internally. Right now the returned LeaseResponse contain lease id as int64 not LeaseID.

**Comment by ajityagaty** [comment]
@xiang90 Could you please let me know how you are thinking of solving this? I see that currently LeaseGrantResponse is really mapped to (typedef) to pb.LeaseGrantResponse and hence the users will be able to see ID as int64. In order for the public API to see LeaseID we would have to redefine LeaseGrantResponse as a struct with a field of type LeaseID and other necessary fields?

**Comment by xiang90** [comment]
@ajityagaty I can see two ways:

1. we convert the protobuf lease responses to responses defined in client library, which has leaseID type instead of int64

2. we use customized type for protobuf. doc is here http://gogo.github.io/doc/

**Comment by xiang90** [comment]
@heyitsanthony Opinions? I do not have strong preference. maybe slightly prefer 2.

**Comment by heyitsanthony** [comment]
@xiang90 Option 2 might be problematic if LeaseID is defined in a package outside of clientv3. It could lead to a situation like #4987 where the `storagepb.Event` type had to be manually recast into `clientv3.Event` by the client code.

**Comment by xiang90** [comment]
@heyitsanthony well... then probably we have to do 1.

**Comment by heyitsanthony** [comment]
@xiang90 yeah, seems like it can't be avoided

**Comment by ajityagaty** [comment]
@xiang90 @heyitsanthony I am trying to make the changes for this. Would it be better to put out separate PRs for the fix and the necessary changes needed in integration tests?

**Comment by heyitsanthony** [comment]
@ajityagaty the PR without the test updates wouldn't pass CI; just do one

**Comment by ajityagaty** [comment]
@heyitsanthony Sure! Thanks!
