### ISSUE TITLE
etcd 2.3.0 does not print anything

### ISSUE THREAD

**Issue by alban** [coreos/etcd#4993]
```
sudo rkt --debug run --stage1-name=coreos.com/rkt/stage1-coreos:1.3.0 coreos.com/etcd:v2.3.0
```

rkt starts etcd but it does not print anything. Same issue with v2.3.1.

Strace says that it is waiting on `epoll_wait(4,`

```
# ls -l /proc/7569/fd/
total 0
lr-x------. 1 root root 64 Apr  7 19:21 0 -> /dev/null
lrwx------. 1 root root 64 Apr  7 19:21 1 -> socket:[6659175]
lr-x------. 1 root root 64 Apr  7 19:21 10 -> /opt/stage2/etcd/rootfs/data-dir/member/wal/0000000000000000-0000000000000000.wal
lrwx------. 1 root root 64 Apr  7 19:21 2 -> socket:[6659175]
lrwx------. 1 root root 64 Apr  7 19:21 3 -> socket:[6657393]
lrwx------. 1 root root 64 Apr  7 19:21 4 -> anon_inode:[eventpoll]
lrwx------. 1 root root 64 Apr  7 19:21 5 -> socket:[6654658]
lrwx------. 1 root root 64 Apr  7 19:21 6 -> socket:[6654659]
lrwx------. 1 root root 64 Apr  7 19:21 7 -> socket:[6654678]
lrwx------. 1 root root 64 Apr  7 19:21 8 -> socket:[6654679]
l-wx------. 1 root root 64 Apr  7 19:21 9 -> /opt/stage2/etcd/rootfs/data-dir/member/wal/0000000000000000-0000000000000000.wal
```

When trying with an older version (coreos.com/etcd:v2.0.10), it successfully prints the usual output:
```
[347548.946795] etcd[4]: 2016/04/07 17:28:39 etcd: no data-dir provided, using default data-dir ./default.etcd
[347548.950747] etcd[4]: 2016/04/07 17:28:39 etcd: listening for peers on http://localhost:2380
...
```

Is there something preventing etcd from printing its usual output?

/cc @jonboulle

**Comment by alban** [comment]
- coreos.com/etcd:v2.3.1 works fine with rkt-v1.1.0 but it fails with a recent rkt.
- coreos.com/etcd:v2.0.10 works on both versions of rkt.

Recent images of etcd were built with acbuild. Maybe it's related?

It might not be a but in etcd then...

**Comment by gyuho** [comment]
```
sudo ./rkt trust --prefix coreos.com/etcd
sudo ./rkt --debug run --volume data-dir,kind=host,source=/tmp --mds-register=false coreos.com/etcd:v2.3.1;
```

This works with rkt 1.0.0, but no output with rkt 1.3.0

**Comment by xiang90** [comment]
@alban Shall we close this at etcd side? I feel this is probably a regression on rkt, given the fact rkt 1.0 works. We would like to look into this if you believe this is something that etcd needs to resolve.

**Comment by alban** [comment]
@xiang90 ok, I filed https://github.com/coreos/rkt/issues/2417
