### ISSUE TITLE
Unable to refresh key with value

### ISSUE THREAD

**Issue by schmichael** [coreos/etcd#5003]
In etcd 2.3 with the latest go client I'm unable to use the new refresh feature to refresh a key with a value.

This should build against the latest etcd client and run against a local etcd with no options required:
 
https://github.com/schmichael/etcdtest/blob/master/etrefresh/main.go

If you run it as is, the final compare-and-delete fails because a refresh cleared the key's value.

Changing [line 65](https://github.com/schmichael/etcdtest/blob/master/etrefresh/main.go#L65) to have a value in an effort to *not* clear the key's value *also* fails because the client rejects refreshes with a value here:

https://github.com/coreos/etcd/blob/f31105bc08339bb92ec112815ec1d50bec929ace/etcdserver/api/v2http/client.go#L576-L581

The docs make it sound like calling set with an empty value is what's required, which makes the value clearing a bug in the server.

**Comment by xiang90** [comment]
@schmichael You can only refresh TTL, not value. Check https://github.com/coreos/etcd/blob/master/Documentation/api.md#refreshing-key-ttl.

**Comment by schmichael** [comment]
I'm confused by the following line of documentation:

> You cannot update the value of a key when refreshing it

I'm not trying to update or change the value of the key when refreshing. I
just want to maintain the existing value while refreshing the TTL.

Does the new refresh feature only work on file keys with no value?

If so I'll probably just have to continue living without it until v3 is out
and this whole issue is moot.
On Apr 7, 2016 5:16 PM, "Xiang Li" <notifications@github.com> wrote:

@schmichael <https://github.com/schmichael> You can only refresh TTL, not
value. Check
https://github.com/coreos/etcd/blob/master/Documentation/api.md#refreshing-key-ttl
.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/coreos/etcd/issues/5003#issuecomment-207146604>

**Comment by xiang90** [comment]
> I'm not trying to update or change the value of the key when refreshing. I
just want to maintain the existing value while refreshing the TTL.

Then we need to do 
```
curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d ttl=5 -d refresh=true -d prevExist=true
```

Basically, we should not specify any value besides refresh and prevExist.

**Comment by schmichael** [comment]
That seems to be impossible with the current go client as at least the curl
command it logs includes "value=" and sets the value to empty.

**Comment by krish7919** [comment]
@xiang90 : Thanks for pointing to this post.
I am facing a similar issue. Using watcher for events for the first time, I assumed I was doing something wrong. :)

When I set the value to a null string, it clears the value from the key.
I also tried setting the Dir = true in SetOptions, assuming that it would cause the API to ignore the value and just refresh the TTL. I also have PrevExist set to true, to specify that I only want a refresh.

**Comment by xiang90** [comment]
@schmichael 
```
➜  etcdctl git:(b) ✗ curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d value=bar -d ttl=5
{"action":"set","node":{"key":"/foo","value":"bar","expiration":"2016-04-08T22:14:35.554942826Z","ttl":5,"modifiedIndex":6,"createdIndex":6}}
➜  etcdctl git:(b) ✗ curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d ttl=5 -d refresh=true -d prevExist=true -d value=
{"action":"update","node":{"key":"/foo","value":"bar","expiration":"2016-04-08T22:14:39.113701892Z","ttl":5,"modifiedIndex":7,"createdIndex":6},"prevNode":{"key":"/foo","value":"bar","expiration":"2016-04-08T22:14:35.554942826Z","ttl":2,"modifiedIndex":6,"createdIndex":6}}
➜  etcdctl git:(b) ✗ curl http://127.0.0.1:2379/v2/keys/foo -XPUT -d ttl=5 -d refresh=true -d prevExist=true -d value=
{"action":"update","node":{"key":"/foo","value":"bar","expiration":"2016-04-08T22:14:42.187235758Z","ttl":5,"modifiedIndex":8,"createdIndex":6},"prevNode":{"key":"/foo","value":"bar","expiration":"2016-04-08T22:14:39.113701892Z","ttl":2,"modifiedIndex":7,"createdIndex":6}}
```

It seems that empty value with refresh set works for me. Can you try it again and confirm it does not work for you? What is the version of etcd you are running?

**Comment by xiang90** [comment]
@schmichael Now I am trying to see if it is because of etcd/client.

**Comment by xiang90** [comment]
@schmichael 

I tried your programmer and changed https://github.com/schmichael/etcdtest/blob/master/etrefresh/main.go#L61

to 
```go
refreshopts := &client.SetOptions{Refresh: true, PrevExist: client.PrevExist, TTL: ttl}
```

by removing the prevValue.

And now it works. So I feel everything is just fine.

**Comment by schmichael** [comment]
@xiang90 Unfortunately I need this operation to be a compare-and-swap. The value may have changed between refresh calls, and the refresh should fail if the value changes.

I guess I can't use refresh for my use case.

I'll have to change my code again when v3 is finalized, so I'll just ignore refresh. It's a nice optimization, but not strictly necessary for my use case.

**Comment by xiang90** [comment]
@schmichael You are right, it does not work for CAS.

**Comment by krish7919** [comment]
@xiang90 
As suggested above, I have tried the SetOptions for refresh operation as:
refreshOptions := client.SetOptions{
        Refresh:   true,
        TTL:       time.Second * 60, 
        PrevExist: client.PrevExist,
    }

I refresh the key like this:
_, err = ctx.keysAPI.Set(context.Background(), key, "", refreshOptions)

And the value gets set to empty string.

**Comment by horkhe** [comment]
The problem is in the deficiency of the KeysAPI the doc for the SetOptions.Refresh [says](https://github.com/coreos/etcd/blob/master/client/keys.go#L187-L190):

>  A value must not be provided when refreshing a key.

But since the value in [KeysAPI.Set](https://github.com/coreos/etcd/blob/master/client/keys.go#L107-L110) is of type string there is no way not to provide it. Specifying an empty string just sets the value to empty string.

**Comment by horkhe** [comment]
Disregard my comment. I was just running version 2.2.4 after upgrade to 2.3.7 it started to work as expected.
