### ISSUE TITLE
raft - questions regard to membership change

### ISSUE THREAD

**Issue by EasonLiao** [coreos/etcd#5004]
Hi etcd team, 

I was reading the raft code regards to dynamic membership change and I have a question about it. I have limited familiarity with the raft code so first I want to verify if my understanding about current membership implementation is correct:

- Only one node reconfiguration at a time and one node change per reconfiguration. This guarantees two consecutive configurations has at least one node overlap in quorums.
- Raft proposes the reconfiguration as "normal" command and adopts the new configuration only after it's committed in old quorum.

This implies that the membership is something in "state" because raft only uses it after it's committed, however, raft uses log history for leader election and I wonder if it's possible that current "applied membership" and the latest membership in log differs more than one node? If so, is this safe?

One example:

Let's say there're 3 consecutive reconfigurations:
```
S1: [A, B, C]
S2: [A, B, C, D]
S3: [A, B, C, D, E]
```

And this is current log state:
```
A(Term: 1): S1, S2, S3 [S1]
B(Term: 1): S1, S2, S3 [S3]
C(Term: 1): S1, S2, S3 [S3]
D(Term: 1): S1, S2, S3 [S3]
E(Term: 1): S1, S2, S3 [S3]
```
Configuration S3 is committed because it has been persisted on the quorum of S2, besides that, it has been persisted by all nodes in S3 as well. However, S3 is not applied to A yet, S2 is not applied to A as well(this is possible that A received entry S2 and S3 but has not received the commit message yet)so A thinks it's still belong to S1. 

Now let's say B is partitioned from rest of the cluster and C, D, E form a new quorum in next term and C is the leader: 
```
A(Term: 1): S1, S2, S3 [S1]
B(Term: 1): S1, S2, S3 [S3]
C(Term: 2): S1, S2, S3 [S3] L
D(Term: 2): S1, S2, S3 [S3]
E(Term: 2): S1, S2, S3 [S3]
```
Then A starts a leader election and it got the vote from B because A has a sufficient log history(it has S3 in log). So A thinks it's the leader of term2.
```
A(Term: 2): S1, S2, S3 [S1] L
B(Term: 2): S1, S2, S3 [S3]
C(Term: 2): S1, S2, S3 [S3] L
D(Term: 2): S1, S2, S3 [S3]
E(Term: 2): S1, S2, S3 [S3]
```

I was wondering can this happen? Thanks in advance!

**Comment by xiang90** [comment]
> however, raft uses log history for leader election and I wonder if it's possible that current "applied membership" and the latest membership in log differs more than one node? If so, is this safe?

This should not be possible.

> Then A starts a leader election and it got the vote from B because A has a sufficient log history(it has S3 in log). So A thinks it's the leader of term2.

Before A starts the election, it MUST apply all pending configuration entries.

**Comment by xiang90** [comment]
please check the doc here: https://github.com/coreos/etcd/blob/master/raft/node.go#L130-L135
