### ISSUE TITLE
Please add ARM binaries

### ISSUE THREAD

**Issue by mingfang** [coreos/etcd#5023]
I'm trying to run etcd on raspberry pi.

**Comment by xiang90** [comment]
@mingfang Can you build arm binary yourself for the moment?

**Comment by mingfang** [comment]
@xiang90 I would like to try.  Are there any instructions available?

**Comment by xiang90** [comment]
Setup your GO env and GOPATH. Then you should be able to build etcd by using build script.

**Comment by xiang90** [comment]
I am closing this. etcd does not officially support arm right now. We might support arm64 and release binary soon.
