### ISSUE TITLE
storage: consider using F_FULLSYNC for HFS/OSX systems

### ISSUE THREAD

**Issue by philips** [coreos/etcd#5029]
I was talking with Mikeal Rogers who used to work on couchdb and one thing he learned is that sync on OSX lies and that you need to use F_FULLSYNC instead: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/fcntl.2.html#//apple_ref/doc/man/2/fcntl

Low priority as I don't think anyone is using etcd on HFS in-prod, but something to document/consider for the future.

**Comment by ajityagaty** [comment]
@xiang90 Will it be enough if I add a new darwin specific `FDatasync` function under `fileutil` package (and compile it of course)? Is this the required approach or does this involve something else?

**Comment by xiang90** [comment]
@ajityagaty Yea. I think we need a new FDatasync for HFS/oxs.

**Comment by ajityagaty** [comment]
@xiang90 Thanks ! I'll give this a try.

**Comment by xiang90** [comment]
@ajityagaty Great. Thanks!

**Comment by heyitsanthony** [comment]
I believe all `file.Sync` calls would have to be replaced with a `fileutil` version. I don't think it's as simple as adding a new fdatasync platform.

**Comment by ajityagaty** [comment]
@heyitsanthony Yes, you are right ! There are a few places where we are calling `file.Sync` and they need to be replaced with `fileutil` wrapper.
