### ISSUE TITLE
HTTP2 was not enable in the connection between proxy and member

### ISSUE THREAD

**Issue by ZhuPeng** [coreos/etcd#5033]
I was do some test with HTTP2 in etcd, and I want the connection between proxy and member use http2. But it was not, and I found the http2 in go1.6 was not enable by default which has some restriction. The restriction was below.
https://github.com/golang/go/blob/master/src/net/http/transport.go#L166-L200
when etcd enable https, then the transport's TLSClientConfig was not `nil` in proxy. Then the http2 will not enable. Be conservative for now (for Go 1.6) at least and don't automatically enable http2 if they've specified a custom TLS config. (Issue https://github.com/golang/go/issues/14275)

My solution was use `http2.ConfigureTransport` enable http2 when invoking the NewHandler in `proxy.go`, just like this PR https://github.com/RobotsAndPencils/buford/pull/27/files#diff-60fc849ee35f905d324099fcd641e25bR20 . It worked.

**Comment by xiang90** [comment]
@ZhuPeng Can you send a pr to fix the problem in etcd/proxy for http2? It should be a simple fix by providing tls conf as you mentioned.

**Comment by xiang90** [comment]
This is solved by #5034
