### ISSUE TITLE
etcdctl panics when trying to add existing role to user 

### ISSUE THREAD

**Issue by kciepluc** [coreos/etcd#5045]
_From @kciepluc on April 10, 2016 20:28_

core@core2 ~ $ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.1.0
VERSION_ID=1010.1.0
BUILD_ID=2016-04-07-0355
PRETTY_NAME="CoreOS 1010.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

core@core2 ~ $ etcd2 -version
etcd Version: 2.3.1
Git SHA: 2b67f52
Go Version: go1.5.3
Go OS/Arch: linux/amd64

core@core2 ~ $ **etcdctl user add test**
New password:
User test created
core@core2 ~ $ **etcdctl user grant --roles root test**
User test updated
core@core2 ~ $ **etcdctl user grant --roles root test**
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a9418]

goroutine 1 [running]:
github.com/coreos/etcd/etcdctl/command.userGrantRevoke(0xc820127680, 0x1)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/user_commands.go:204 +0xa28
github.com/coreos/etcd/etcdctl/command.actionUserGrant(0xc820127680)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdctl/command/user_commands.go:174 +0x26
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0xd47ef8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe02180, 0x1b, 0x0, ...)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc820127440, 0xc820127320, 0x0, 0x0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:282 +0x11a0
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.startApp(0xd4b868, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2d1a0, 0x26, 0x0, ...)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:215 +0x7cc
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0xd4b868, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe2d1a0, 0x26, 0x0, ...)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:59 +0x197d
github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc820127200, 0xc82000a120, 0x6, 0x6, 0x0, 0x0)
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
        /build/amd64-usr/var/tmp/portage/dev-db/etcd-2.3.1/work/gopath/src/github.com/coreos/etcd/etcdctl/main.go:69 +0x1ce9

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 27 [IO wait]:
net.runtime_pollWait(0x7f8d4aceda50, 0x72, 0xc820010160)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820156ae0, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820156ae0, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820156a80, 0xc820165000, 0x1000, 0x1000, 0x0, 0x7f8d4ace7050, 0xc820010160)
        /usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026540, 0xc820165000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f8d4aceea08, 0xc820026540, 0xc8201387e8, 0xc820165000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820155f80, 0xc820165000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82000ba40)
        /usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82000ba40, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820138790)
        /usr/lib/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:685 +0xc78

goroutine 15 [syscall]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 28 [select]:
net/http.(*persistConn).writeLoop(0xc820138790)
        /usr/lib/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:686 +0xc9d

goroutine 32 [IO wait]:
net.runtime_pollWait(0x7f8d4aced990, 0x72, 0xc820010160)
        /usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820156e60, 0x72, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820156e60, 0x0, 0x0)
        /usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820156e00, 0xc82017d000, 0x1000, 0x1000, 0x0, 0x7f8d4ace7050, 0xc820010160)
        /usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026550, 0xc82017d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f8d4aceea08, 0xc820026550, 0xc820138948, 0xc82017d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82017e5a0, 0xc82017d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820182060)
        /usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820182060, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8201388f0)
        /usr/lib/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:685 +0xc78

goroutine 33 [select]:
net/http.(*persistConn).writeLoop(0xc8201388f0)
        /usr/lib/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:686 +0xc9d

journalctl shows:
Apr 10 20:27:30 core2 etcd2[962]: granting duplicate role root for user test

_Copied from original issue: coreos/bugs#1214_

**Comment by heyitsanthony** [comment]
can repro with e2e tests. looking into it
