### ISSUE TITLE
etcdctl cannot list users after enabling auth - json: cannot unmarshal object into Go value of type string

### ISSUE THREAD

**Issue by kciepluc** [coreos/etcd#5046]
_From @kciepluc on April 10, 2016 20:41_

core@core2 ~ $ **cat /etc/os-release**
NAME=CoreOS
ID=coreos
VERSION=1010.1.0
VERSION_ID=1010.1.0
BUILD_ID=2016-04-07-0355
PRETTY_NAME="CoreOS 1010.1.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

core@core2 ~ $ **etcd2 -version**
etcd Version: 2.3.1
Git SHA: 2b67f52
Go Version: go1.5.3
Go OS/Arch: linux/amd64
core@core2 ~ $

core@core2 ~ $ **etcdctl auth enable**
Authentication Enabled
core@core2 ~ $ **etcdctl user list**
Insufficient credentials
core@core2 ~ $ **etcdctl -u root user list**
Password:
json: cannot unmarshal object into Go value of type string

after disabling auth:
core@core2 ~ $ **etcdctl -u root auth disable**
Password:
Authentication Disabled
core@core2 ~ $ **etcdctl user list**
json: cannot unmarshal object into Go value of type string

but:

core@core2 ~ $ **curl -s http://localhost:2379/v2/auth/users**
{"users":[{"user":"root","roles":[{"role":"root","permissions":{"kv":{"read":["/*"],"write":["/*"]}}}]},{"user":"test","roles":[{"role":"root","permissions":{"kv":{"read":["/*"],"write":["/*"]}}}]}]}

_Copied from original issue: coreos/bugs#1215_

**Comment by heyitsanthony** [comment]
can repro, investigating
