### ISSUE TITLE
etcd environment variable naming convention?

### ISSUE THREAD

**Issue by jackiesyu** [coreos/etcd#5047]
I have a configuration as following --
env ETCD_NAME="etcd-01"
env ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.5.0.128:2380"
env ETCD_LISTEN_PEER_URLS="http://10.5.0.128:2380"
env ETCD_LISTEN_CLIENT_URLS="http://10.5.0.128:2379,http://127.0.0.1:2379"
env ETCD_ADVERTISE_CLIENT_URLS="http://10.5.0.128:2379"
env ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
env ETCD_INITIAL_CLUSTER="etcd-01=http://10.5.0.128:2380,etcd-02=http://10.5.0.127:2380,etcd-03=http://10.5.0.126:2380"
env ETCD_INITIAL_CLUSTER_STATE="new"
env ETCD_DATA_DIR="/var/etcd"

And with this, I can bring the cluster up, but I can't get etcdctl to work -- always returning 
*dial tcp 127.0.0.1:2379: connection refused*
However, curl http://10.5.0.128:2379/version works fine...

Now, when I change the ETCD_NAME and the corresponding ETCD_INITIAL_CLUSTER variable to the following:
env ETCD_INITIAL_CLUSTER="infra0=http://10.5.0.128:2380,infra1=http://10.5.0.127:2380,infra2=http://10.5.0.126:2380"
env ETCD_NAME="infra0"

Then it works fine. So, having the '-' seems to be making a difference here. Maybe I am just taking it too liberal in my naming for the cluster?

**Comment by xiang90** [comment]
@jackiesyu Sorry for the delay on this one. @gyuho Can you please take a look?

**Comment by gyuho** [comment]
@jackiesyu Can you share your `etcdctl` command? 

> dial tcp 127.0.0.1:2379: connection refused

Seems like it tries to connect to your localhost. You need to specify the endpoint with `endpoints` flag.

**Comment by gyuho** [comment]
And the hyphen `-` in node name should be ok. 

Current code parses it with `=` character. https://github.com/coreos/etcd/blob/master/pkg/types/urlsmap.go#L74

Please let me know if you still have this issue.

Thanks.

**Comment by jackiesyu** [comment]
So, I have 3 nodes running the cluster and I am running the etcdctl from one of the node in the cluster. The localhost should work without the endpoints flag, true?

The only thing I changed to make it work is ETCD_NAME and ETCD_INITIAL_CLUSTER env and nothing else. I am in the middle of something and I can change them back to my previous version and see whether it will work or not in a day or two...

**Comment by gyuho** [comment]
Oh if you `etcdctl` *inside* one of the nodes, `localhost` should work. You are right.

But `etcdctl` has default values for `endpoints` which could be different than yours.
So in production, you should always specify `endpoints` just to be safe.

And not sure why it didn't work with different names... Please try again as you say and get back to us if it still errors.

Thanks.

**Comment by gyuho** [comment]
@jackiesyu Ping? Please let me know if you have any other question. Thanks.

**Comment by gyuho** [comment]
@jackiesyu I am closing this due to low activity. But please feel free to re-open or ask us any other question. Thanks.
