### ISSUE TITLE
etcd can't advertise URLs with paths, and therefore can't be run behind an HTTP proxy using location directives

### ISSUE THREAD

**Issue by kgilpin** [coreos/etcd#5052]
In my application, I would like to run `etcd` (particularly the peer URLs) behind an Nginx proxy. The primary reason I want to do this is that operators are already instructed to open port 443; I don't want to require the opening of additional ports on my application. A secondary reason is to handle SSL termination and SSL mutual auth in Nginx, since there are more configuration options there.

Therefore, what I want to do is create location directives in nginx such as `/etcd/client` and `/etcd/peer`. Each of these locations will proxy to the local etcd instance which is listening 127.0.0.1 and the standard ports. For example:

```
location /etcd/peer {
  if ($ssl_client_verify != SUCCESS) {
    return 401;
  }

  rewrite /etcd/peer/(.*) /$1 break;
  proxy_pass http://localhost:2380;
}
```

After configuring nginx, the next step is to start the etcd servers, each of which will advertise the Nginx URL, like so : `--initial-advertise-peer-urls https://host-01.app/etcd/peer`.

Unfortunately, `pkg/types/urls.go` does not permit URLs with paths. Therefore, my configuration is not accepted by etcd. 

Is there a particular reason why `advertise-peer-urls` is not allowed to contain a path?

**Comment by philips** [comment]
We just have never anticipated a need for it and all use cases assume that etcd owns the "root" path. So your use case is that you want to proxy many etcd peers behind the nginx load balancer at host-01.app?

**Comment by kgilpin** [comment]
Hi Brandon. Actually, we will only have one peer behind host-01.app. Behind host-02.app there will be another peer, host-03.app similarly. The reason for proxying etcd behind Nginx is that we don't have to instruct operators to open additional ports between the machines. They have 443 open already and we want to piggyback etcd on that, under a base URL e.g. `https://host-01.app/etcd/peer`.

**Comment by kgilpin** [comment]
We can also use the SSL settings and mutual auth that's built into Nginx.

**Comment by xiang90** [comment]
@kgilpin I guess this is not hard for peer communication or v2 client communication. However, to support this we need to ensure we can support for all urls passed in. I do not want to make the support inconsistent. 

etcdv3 api uses gRPC (which supports http2 transport under the hood). Can you explore how to do the same thing for gRPC?

**Comment by philips** [comment]
@kgilpin could you use HTTP "virtual hosts" so call it host-01-etcd.app instead or rewriting the path? Or maybe have your etcd client put in a special "etcd" header like X-Kgilpin-Etcd-Hack. Dunno, this is just something we haven't considered.

**Comment by kgilpin** [comment]
Thanks for the discussion.  Would it be possible to identify inbound etcd peer traffic by the User-Agent?

**Comment by philips** [comment]
@kgilpin sure, depending on your clients. What clients are you using?

**Comment by kgilpin** [comment]
This is just for the peers

**Comment by philips** [comment]
@kgilpin so, the traffice between peers?

@xiang90 Could we set a User-Agent for the communication between peers to say "etcdserver/VERSION" so that @kgilpin can munge and route the requests as he wishes?

**Comment by kgilpin** [comment]
Yes, traffic between peers.

**Comment by xiang90** [comment]
> Yes, traffic between peers.

You can check header for `X-Etcd-Cluster-ID`. If it is set, then it is etcd traffic between peers. It does not seem like a common request. If this work around is OK, I am inclined to close the issue.

**Comment by kgilpin** [comment]
Thanks, I think you can close it then.

**Comment by xiang90** [comment]
@kgilpin OK. We might switch to gRPC for internal communication in the middle/long term. We will figure out a better way to distinguish etcd internal traffic.

**Comment by kgilpin** [comment]
Hi, I’m sorry it was seven years ago - I don’t remember.

**Comment by sbijendra** [comment]
NP @kgilpin , @xiang90 - Is there a better way to determine the etcd requests now? I don't think we pass the X-Etcd-Cluster-ID in the /raft/probing requests among peers. Correct me please if I am wrong here. I am using etcd 3.4 version.

**Comment by jmhbnz** [comment]
> Is there a better way to determine the etcd requests now? I don't think we pass the X-Etcd-Cluster-ID in the /raft/probing requests among peers. Correct me please if I am wrong here. I am using etcd 3.4 version.

Hi @sbijendra - Thanks for your interest in etcd, however please do not necro post on ancient issues.  If you have questions you would like to raise please raise a fresh topic via https://github.com/etcd-io/etcd/discussions.
