### ISSUE TITLE
Max watchers supported by etcd2

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#5058]
The documentation is not there on the max number of watchers for etcd2 or how this is related to memory or the infrastructure or a relation between the number of keys and number of watchers.

I'm trying a solution for which I'll need a high number of keys and a watcher for each key. (Say a milliion)

**Comment by xiang90** [comment]
Probably you need to test this out yourselves at the moment for v2. If you need 1m watchers on same key, you have to wait for our proxy for v3. broadcasting one million requests pre write will slow down or probably kill etcd cluster for sure.

**Comment by xiang90** [comment]
here is some memory data on v3: https://github.com/coreos/etcd/blob/master/Documentation/benchmarks/etcd-3-watch-memory-benchmark.md

**Comment by raoofm** [comment]
Thanks, v3 looks really amazing, but for v3 to be production ready with supported language implementations to talk to etcd, it will be a few months. I guess the solution I'm looking at has to wait till v3.

My use case is  1-to-1, I mean 1m watchers for 1m keys. Is it worth to try it out or etcd team is sure that v2 cannot support and I should wait for v3.

**Comment by xiang90** [comment]
@raoofm What language are you expecting?

**Comment by xiang90** [comment]
> My use case is 1-to-1, I mean 1m watchers for 1m keys. Is it worth to try it out or etcd team is sure that v2 cannot support and I should wait for v3.

I am not sure. The only probably is memory I guess. You'd better give it a try.

**Comment by raoofm** [comment]
>@raoofm What language are you expecting?

java

>I am not sure. The only probably is memory I guess. You'd better give it a try.

Ok, thanks though

**Comment by raoofm** [comment]
fyi https://github.com/coreos/etcd/pull/5064

**Comment by xiang90** [comment]
@raoofm Actually, do you have any interest working on the java binding for etcd3?

**Comment by raoofm** [comment]
Yes

**Comment by raoofm** [comment]
we use a v2 cluster with 5 machines, running for an year now, in house java client here in prod (we didn't knew Adohe and boon had v2 solutions as well :smile: ), but I can work towards v3.

**Comment by raoofm** [comment]
you can close this thread. If I test a million wathchers and keys then I'll find this thread and update.

**Comment by xiang90** [comment]
@raoofm Can you create a java client issue for v3? Then we can start to track that? I know there are other people that are interested in helping us with java client.

**Comment by raoofm** [comment]
fyi https://github.com/coreos/etcd/issues/5067

**Comment by xiang90** [comment]
@raoofm 

> we use a v2 cluster with 5 machines, running for an year now, i

Is is possible to add your case to this doc? https://github.com/coreos/etcd/blob/master/Documentation/production-users.md

**Comment by xiang90** [comment]
@raoofm Any update?

**Comment by raoofm** [comment]
>Is is possible to add your case to this doc?

Added the use case https://github.com/coreos/etcd/pull/5226

>@raoofm Any update?

@xiang90 Are you looking for the update on adding the useCase or java client or testing million watchers on v2?

**Comment by xiang90** [comment]
ah. This: testing million watchers on v2.

**Comment by raoofm** [comment]
We are still reviewing our considerations as we have both zookeeper and etcd in prod. We are already using kafka with zookeeper and are open to use hazelcast (which supports clustering, maps/queues with ttl and watch)

So instead of having >million watchers in etcdV2 which we are not sure of, we can use kafka with custom ttl logic which is proven to support millions of messages, or hazelcast, or mongo collections with ttl and listeners.

This is a future solution and I got dragged into something else, so didn't test this out with v2 but I've this on my todo list. I'll test it out at some point for sure. In case you wanna close this request feel free, I'll find it and update when i have results.

**Comment by xiang90** [comment]
Thanks! I will close this for now. We will provide more information for etcd3 on watching side.
