### ISSUE TITLE
raft: add a README of users

### ISSUE THREAD

**Issue by philips** [coreos/etcd#5063]
We should add a README into the raft package directory. Two things should be:

Users:
- cockroachdb
- etcd
- dgraph.io
- https://github.com/pingcap/tikv
  - TiKV uses Raft to support Geo-Replication. We have ported etcd's raft implementation to Rust.  By using raft, Key-Value regions always stay consistent. Placement driver (or pb) is also important for Geo-Replication. Pd collects state 
- github.com/yahoo/coname
- https://github.com/weaveworks/mesh/tree/master/metcd
- https://github.com/chzchzchz/raftsql
- others?

Docs:
https://godoc.org/github.com/coreos/etcd/raft

**Comment by xiang90** [comment]
https://github.com/pingcap/tikv

```
TiKV uses Raft to support Geo-Replication. We have ported etcd's raft implementation to Rust. By using raft, Key-Value regions always stay consistent. Placement driver (or pb) is also important for Geo-Replication. Pd collects state 
```

**Comment by xiang90** [comment]
https://github.com/weaveworks/mesh/tree/master/metcd

**Comment by xiang90** [comment]
https://github.com/yahoo/coname

**Comment by xiang90** [comment]
Fixed by https://github.com/coreos/etcd/pull/5419. Only added 3 non-toy projects and an example project as initial users, which I am familiar with. i will ping the authors of other projects to add it to readme themselves if they would like to.
