### ISSUE TITLE
Need a Java client for etcd v3

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#5067]

**Comment by philips** [comment]
Are you interested in working on this @raoofm ?

**Comment by AdoHe** [comment]
This is in my plan, I will start doing this.

**Comment by ajityagaty** [comment]
@AdoHe Please let me know if I can be of any help.

**Comment by AdoHe** [comment]
@ajityagaty how about creating a new repo for this v3 client? Though I already have a repo https://github.com/AdoHe/etcd4j

**Comment by ajityagaty** [comment]
@AdoHe Wouldn't it be better to use the repo that you already have? Then folks can find both versions of the client at the same place.

**Comment by AdoHe** [comment]
@ajityagaty Ok, we can reuse the old repo, and put this in a new branch.

**Comment by AdoHe** [comment]
@ajityagaty would you mind giving me your email? I think it's better to reach each other through email.

**Comment by ajityagaty** [comment]
@Adohe it's ajityagaty@gmail.com

**Comment by raoofm** [comment]
Yes

**Comment by raoofm** [comment]
raoof.md@gmail.com

**Comment by Randgalt** [comment]
It would be interesting to write it in a way so that Apache Curator (http://curator.apache.org) could possibly be ported.

**Comment by lburgazzoli** [comment]
I'm also interested to develop a java binding for v3, is there any chance to have client related protobuf files in a separate repo so we can add them as git sub-module?

**Comment by sijie** [comment]
@xiang90 yup I am interested in helping.

**Comment by cdancy** [comment]
If anyone is interested in helping out with [etcd-rest](https://github.com/cdancy/etcd-rest/tree/etcd-v3), which is java client based on [apache-jclouds](https://github.com/jclouds/jclouds), I could certainly use the help. We are targeting the [grpc-to-json api](https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md). Feel free to reach out if you're at all interested in learning how jclouds works and want to learn by hacking on an etcd provider. Thanks!

**Comment by linsimiao** [comment]
We are starting to do this,is there any discussion board?

**Comment by sijie** [comment]
@linsimiao how much work do you guys already start? I am just starting this week though. If you guys already start a lot, I'd like to coordinate with you guys somewhere.

**Comment by AdoHe** [comment]
@linsimiao @sijie actually in this repo [https://github.com/AdoHe/etcd4j/tree/v3](https://github.com/AdoHe/etcd4j/tree/v3) I have added some beginning code, you may take a  look.

**Comment by linsimiao** [comment]
we started our work two days ago, and our repo is [https://github.com/enncloud/j2etcdV3](https://github.com/enncloud/j2etcdV3).It is totally new now, and we will gradually commit code into it.
Happy to have your help.

**Comment by linsimiao** [comment]
@sijie we started our work two days ago, and our repo is [https://github.com/enncloud/j2etcdV3](https://github.com/enncloud/j2etcdV3) . It is totally new now, and we will gradually commit code into it.
Happy to have your help.

**Comment by linsimiao** [comment]
@AdoHe  THx. I will have a look at your commits.

**Comment by xiang90** [comment]
@linsimiao @AdoHe @raoofm @cdancy @lburgazzoli @Randgalt @ajityagaty 

We created a java client repo for etcd: https://github.com/coreos/jetcd. Let's move the discussion there.
