### ISSUE TITLE
auth: v3 Role grant results in index out of range

### ISSUE THREAD

**Issue by ajityagaty** [coreos/etcd#5077]
I was testing the `etcdctl role` commands in order to write the test cases. That's when I stumbled upon this issue.

The following commands were executed:
`ETCDCTL_API=3 ./etcdctl role add root`
`ETCDCTL_API=3 ./etcdctl role grant root read foo`

I am not sure if I gave the right parameter values albeit it should not result in a crash.
The etcd server was started using the following `./etcd --data-dir .`

The following is the stack trace that I could collect:

panic: runtime error: index out of range

goroutine 7 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth.(*authStore).RoleGrant(0xc8201e1670, 0xc820591200, 0x0, 0x0, 0x0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth/store.go:282 +0xde0
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*applierV3backend).RoleGrant(0xc8201084f8, 0xc820591200, 0x10c02, 0x0, 0x0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/apply.go:514 +0x65
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*quotaApplierV3).RoleGrant(0xc8201eb1c0, 0xc820591200, 0xc8ffffffff, 0x0, 0x0)
	<autogenerated>:98 +0x65
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyV3Request(0xc8201281e0, 0xc82040bb00, 0xc8205911a0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/apply.go:101 +0x12a8
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).apply(0xc8201281e0, 0xc820411c20, 0x1, 0x1, 0xc820013300, 0x0, 0x0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:1052 +0x5c0
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyEntries(0xc8201281e0, 0xc820013300, 0xc8205cc4d0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:683 +0x2cc
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).applyAll(0xc8201281e0, 0xc820013300, 0xc8205cc4d0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:579 +0x78
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func2(0x14b7170, 0xc8200132c0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/server.go:559 +0x32
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc82001a4e0)
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:160 +0x322
created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
	/mine/work/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x275

**Comment by mitake** [comment]
@ajityagaty sorry for that, I made a PR that fixes this problem https://github.com/coreos/etcd/pull/5079

**Comment by ajityagaty** [comment]
@mitake Thanks !
