### ISSUE TITLE
Rejoining node after dataloss when using DNS Discovery

### ISSUE THREAD

**Issue by maximecaron** [coreos/etcd#5087]
If we have a setup with DNS SRV records :

- _etcd-server._tcp.example.com. 300 IN  SRV  0 0 2380 infra0.example.com.
- _etcd-server._tcp.example.com. 300 IN  SRV  0 0 2380 infra1.example.com.
- _etcd-server._tcp.example.com. 300 IN  SRV  0 0 2380 infra2.example.com.

And the etcd server at infra0.example.com crash and its hard-disk need to be replaced.
After the etcd server restart my understand is that we cannot simply use 
"--discovery-srv example.com" and "--initial-cluster-state new" or the quorum will be lost.

But instead need to first perform 
1- "etcdctl --discovery-srv  example.com member remove \<infra0 id\>" 
2- "etcdctl --discovery-srv  example.com member add \<infra0 info\>" 
3- start etcd on infra0 using -initial-cluster= \<list from step#2\>  -initial-cluster-state=existing

It is not clear to me what would happen if infra1.example.com restart would it use the previously agreed on list of members if cluster already have quorum of machine or will it use the list of member from DNS SRV records instead.

Could someone please suggest the correct way to rejoin a node automatically using DNS discovery after it's state have been lost.

**Comment by xiang90** [comment]
@maximecaron Discovery is only designed for first time bootstrapping. For DNS SRV, you can use it to discovery any running etcd cluster as you want, but it wont help on reconfiguration. You need to do runtime reconfiguration afterwards, see https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#replace-a-failed-machine

**Comment by maximecaron** [comment]
To answer the question, I tested the behavior and the server at Infra1 after restarting would ignore data from discovery since it still have non-empty data on disk. It will then try to contact the server it knew about before restart and after getting in sync, will find that "infra0" was removed.

**Comment by xiang90** [comment]
@maximecaron Yes. Then you need to re-add it back if you want to restore that member.
