### ISSUE TITLE
Benchmark v3 watch fails

### ISSUE THREAD

**Issue by IlyaMarkov** [coreos/etcd#5099]
I got problem with etcd v3 benchmarking.

When I launch benchmark watch, it loops forever and outputs following:

```
./benchmark watch
100000 / 100000 100.00%1s
Watch creation summary:

Requests/sec:  79632.6743
51109208 / 100000 51109.21% -3m51s
```

But sometimes(rarely) it works fine. It finishes with some results.

Once it fails with panic:
```
 100000 / 100000  100.00%2s
Watch creation summary:
 Requests/sec:  33895.3791
 100006 / 100000 100.01%1s
Watch events received summary:
panic: send on closed channel
```

Details:
1 node
default parameters 

etcd Version: 2.3.0+git
Go Version: devel +89a1f02 Fri Apr 15 10:17:17 2016 +0000
Go OS/Arch: linux/amd64

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.04
DISTRIB_DESCRIPTION="Ubuntu 15.04"

go version:
go version go1.6.1 linux/amd64

Other benchmarks(put, stm, etc.) work fine.

**Comment by gyuho** [comment]
@IlyaMarkov Please try again the master branch and let us know if you still see the same behavior.

The problem was we did not wait for all watchers to finish receives, and later events were being sent to closed channel. I fixed it by making them wait for all watchers to finish. I tested in my local machine and the issues seems resolved.

Thanks for reporting!

**Comment by IlyaMarkovMipt** [comment]
@gyuho Sorry for late answer. 
At first it worked well. But now the problem has returned. Sometimes it loops forever.
If I launch benchmark watch first time it runs as expected, but on some of next times it fails. 
Also it sometimes outputs:
panic: send on closed channel
And sometimes error with rpc happens:
rpc error: code = 13 desc = context deadline exceeded

**Comment by IlyaMarkov** [comment]
@gyuho Sorry for late answer. 
At first it worked well. But now the problem has returned. Sometimes it loops forever.
If I launch benchmark watch first time it runs as expected, but on some of next times it fails. 
Also it sometimes outputs:
panic: send on closed channel
And sometimes error with rpc happens:
rpc error: code = 13 desc = context deadline exceeded

**Comment by gyuho** [comment]
@IlyaMarkov sorry for late response. Could you open a new issue or reopen this with detailed environments? Like etcd version, how it's deployed, benchmark command to reproduce that issue.

Thanks.

**Comment by IlyaMarkovMipt** [comment]
@gyuho I'm sorry again for late response. 
I launch the etcd servers following way:

$GOPATH/bin/etcd --data-dir $MY_DIR/etcdlogs \
  --name at02 --initial-advertise-peer-urls http://10.125.150.146:2380 \
  --listen-peer-urls http://10.125.150.146:2380 \
  --listen-client-urls http://10.125.150.146:2379,http://127.0.0.1:2379 \
  --advertise-client-urls http://10.125.150.146:2379 \
  --initial-cluster-token etcd-cluster-1 \
  --initial-cluster el01=http://10.125.150.45:2380,el04=http://10.125.150.149:2380,at02=http://10.125.150.146:2380 \
  --initial-cluster-state new

  On the side of client I use:
 bin/benchmark --endpoints 10.125.150.146:2379 --clients 64 --conns 64 watch  --total 50000

And got following:

Watch creation summary:
 Requests/sec:  59087.3715
 1108926 / 50000 ("long bar string") 2217.85% -5s
failed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded
failed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded
failed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded

Other benchmark modes work fine.

**Comment by IlyaMarkov** [comment]
@gyuho I'm sorry again for late response. 
I launch the etcd servers following way:

$GOPATH/bin/etcd --data-dir $MY_DIR/etcdlogs \
--name at02 --initial-advertise-peer-urls http://10.125.150.146:2380 \
--listen-peer-urls http://10.125.150.146:2380 \
--listen-client-urls http://10.125.150.146:2379,http://127.0.0.1:2379 \
--advertise-client-urls http://10.125.150.146:2379 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster el01=http://10.125.150.45:2380,el04=http://10.125.150.149:2380,at02=http://10.125.150.146:2380 \
--initial-cluster-state new

On the client side I use:
bin/benchmark --endpoints 10.125.150.146:2379 --clients 64 --conns 64 watch --total 50000

And got following:

Watch creation summary:
Requests/sec: 59087.3715
1108926 / 50000 ("long bar string") 2217.85% -5s
failed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded
failed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded
failed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded

The other benchmark modes work fine.
I'm not sure, whether I have rights to reopen issue. Should I open new one, though the problem is still the same?

**Comment by gyuho** [comment]
@IlyaMarkov Are you running benchmark in the master branch? Thought it was fixed. I will investigate.

**Comment by IlyaMarkov** [comment]
Yes I'm on master branch. Latest commit is 11th May.
It seems like not all watchers finish there.

**Comment by gyuho** [comment]
@IlyaMarkov Ok sorry about that. I will try to reproduce with your command `benchmark --endpoints 10.125.150.146:2379 --clients 64 --conns 64 watch --total 50000`.

**Comment by gyuho** [comment]
Reproducible in master branch:

```
benchmark --endpoints 127.0.0.1:2379 --clients 64 --conns 64 watch --total 50000
 50000 / 50000 Boooooooooooooooooooooooooooooooooooooo! 100.00%1s
Watch creation summary:
 Requests/sec:	50654.1505
 703755 / 50000 Boooooooooooooooooooooooooooooooooo! 1407.51% -4sfailed to Put for watch benchmark: rpc error: code = 13 desc = context deadline exceeded
```

Working on to fix this.
