### ISSUE TITLE
etcdctl cluster-health falsely reports cluster as unhealthy

### ISSUE THREAD

**Issue by kblcuk** [coreos/etcd#5102]
I have an empty etcd cluster at Compose.io

Running latest etcdctl (2.3.1) cluster-health reports cluster as unhealthy, even though compose's dashboard says it's ok.
Running
```
etcdctl --debug --ca-file /tmp/etcd2.cert --no-sync --peers  HOSTS -u "${ETCD_USERNAME}:${ETCD_PASSWORD}" cluster-health
```
says that all nodes fail with `dial tcp IP:PORT: i/o timeout`, and all members are unreachable.

However, if I issue curl command similar (I think) to what etcdctl does, response is fine:

```
curl -v -X GET https://<host>/v2/members --cacert /tmp/etcd2.cert --user "root:KDDPNZRAFGCNYHED"
*   Trying IP...
* Connected to ...
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* Server certificate:
* Server auth using Basic with user 'root'
> GET /v2/members HTTP/1.1
> Host: <host>
> Authorization: Basic ..er.
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 489
< Content-Type: application/json
< Date: Fri, 15 Apr 2016 18:02:12 GMT
< X-Etcd-Cluster-Id: 60b9cf04888a7184
<
{"members":[{"id":"5dd04f7bd24439a9","name":"name","peerURLs":["http://10.56.177.3:7001"],"clientURLs":["http://10.56.177.3:4001"]},{"id":"b9dbdbddc4fc8a4c","name":"name.com","peerURLs":["http://10.56.177.4:7001"],"clientURLs":["http://10.56.177.4:4001"]},{"id":"d4d43afddae59223","name":"name.com","peerURLs":["http://10.56.177.2:7001"],"clientURLs":["http://10.56.177.2:4001"]}]}

```
So is there some issue with my commands? Or if it is indeed looks like a bug, then how can I debug it further?

**Comment by xiang90** [comment]
@kblcuk Can you please show me the output of etcdctl?

**Comment by kblcuk** [comment]
Oh yea, forgot to paste that.

```
~/Downloads/etcd-v2.3.1-darwin-amd64/etcdctl --debug --ca-file /tmp/etcd2.cert --no-sync --peers  https://<host1>,https://<host2> -u "${ETCD_USERNAME}:${ETCD_PASSWORD}" cluster-health
Cluster-Endpoints: https://<host2>, https://<host1>
cURL Command: curl -X GET https://<host2>/v2/members
failed to check the health of member 5dd04f7bd24439a9 on http://10.56.177.3:4001: Get http://10.56.177.3:4001/health: dial tcp 10.56.177.3:4001: i/o timeout
member 5dd04f7bd24439a9 is unreachable: [http://10.56.177.3:4001] are all unreachable
failed to check the health of member b9dbdbddc4fc8a4c on http://10.56.177.4:4001: Get http://10.56.177.4:4001/health: dial tcp 10.56.177.4:4001: i/o timeout
member b9dbdbddc4fc8a4c is unreachable: [http://10.56.177.4:4001] are all unreachable
failed to check the health of member d4d43afddae59223 on http://10.56.177.2:4001: Get http://10.56.177.2:4001/health: dial tcp 10.56.177.2:4001: i/o timeout
member d4d43afddae59223 is unreachable: [http://10.56.177.2:4001] are all unreachable
cluster is unhealthy
```

I noticed that cUrl is showed only for one of the clusters (<host2>), but changing peers to include only `<host1>` produces the same result.

**Comment by xiang90** [comment]
It seems that the endpoints etcdctl tried to were all timed out. Probably you need to check the connectivity first.

**Comment by kblcuk** [comment]
@xiang90 but that's the thing -- curl requests pass just fine. 
I also tried running the same command from server located in the same region etcd cluster is, with the same result.
Or what exactly you mean by connectivity?

**Comment by xiang90** [comment]
@kblcuk You tried to curl http://10.56.177.3:4001 directly? I am not sure what exactly happened then. Probably open a ticket on Compose.io instead?

**Comment by kblcuk** [comment]
@xiang90 yea, I already did, but so far didn't get far in understanding what exactly is wrong there. I mean I can read and write keys to and from cluster just fine, but `cluster-health` check fails, and for instance Terraform can't update it's state from etcd claiming that cluster is unhealthy as well. :/
Also can't really curl 10.56.x -- looks like an internal IP to me (probably internal to etcd cluster itself?), and I don't have direct access to cluster machines in compose.

I'll update this when I know more.
Thanks anyway!

**Comment by xiang90** [comment]
@kblcuk It seems compose has a load-balancer in between. So you cannot really check the health of the cluster directly. This is not something we can do :(

**Comment by kblcuk** [comment]
Yea, I got confirmation about that from one of Compose engineers:

```
Ah, I see what's happening. The problem is that cluster-health attaches to the public IP address of the deployment and then individually gets the IP addresses of the etcd members. Those etcd members are shielded by the haproxy front end, and the etcd members themselves have no internet presence. They only have private IP addresses. However etcdctl attempts to them route to those private IPs so therefore it fails.

It appears that when using curl to get information from the etcd API, say https://aws-us-east-1-portal.10.dblayer.com:10956/v2/members, will of course only access the single haproxy endpoint at Compose, which then passes that request back to the members. Looks like etcdctl expects the members to be either on the same subnet, or routable themselves, not proxied. In that case, cluster-health won't work for an etcd cluster at Compose.
```
