### ISSUE TITLE
doc: documentation structure for etcd3

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5106]
Here is my proposal for our documentation structure

Get started

* Download and Build OK

* Concepts

* Developing
  * Local setup - OK
  * Interact with etcd - OK
  * API reference

* Operating
  * Clustering Setup
  * Configuration
  * Security
  * Monitoring
  * Maintenance (including backup)
  * Disaster Recovery

* Upgrading and Compatibility

* Troubleshooting

/cc @joshix @heyitsanthony @gyuho

**Comment by gyuho** [comment]
Should `etcdctl` documentation belong `Operating` or be separate?

**Comment by xiang90** [comment]
@gyuho etcdctl has its own doc i think.

**Comment by ajityagaty** [comment]
Would it make sense to add `proxy` details under `Operating`? Proxy for etcd3 is not there yet I think but add a placeholder for it for now?

**Comment by xiang90** [comment]
@ajityagaty I feel that should be a sub section of clustering in clustering setup? also we should mention in the basic concepts section in developing?

**Comment by ajityagaty** [comment]
@xiang90 Sure, putting it under clustering makes sense. A mention about it in the basic concepts section will be helpful. Thanks !

**Comment by xiang90** [comment]
@weiliendang opinions?

**Comment by xiang90** [comment]
@heyitsanthony Can you take a look at the Maintenance part in operating section? How to get a backup (the recovery part should be in disaster recovery part), how to do defrag and why. Any other maintenance work we should mention?

**Comment by heyitsanthony** [comment]
@xiang90 I think it'll need information about quota/alarm stuff, possibly something about compaction. Will writeup

**Comment by xiang90** [comment]
@heyitsanthony Right!

**Comment by weiliendang** [comment]
@xiang90 I think some re-ordering of the topics could be done here. Not sure what "Developing" refers to. Here is a suggested structure:

Getting Started
- Basic concepts
- Download & build
- Local setup
- Interact with etcd
- API reference
Clustering
- Setup
- Configuration
Security
Monitoring
Maintenance (what does this cover; do we need it?)
Backup & recovery
Upgrades
Troubleshooting

Please take these as suggestions. Let me know what you think.

**Comment by weiliendang** [comment]
@xiang90 I think some re-ordering of the topics could be done here. Not sure what "Developing" refers to. Here is a suggested structure:

Getting Started

- Basic concepts
- Download & build
- Local setup
- Interact with etcd
- API reference

Clustering
- Setup
- Configuration 

Security 
Monitoring 
Maintenance (what does this cover; do we need it?) 
Backup & recovery 
Upgrades
Troubleshooting

Please take these as suggestions. Let me know what you think.

**Comment by heyitsanthony** [comment]
@weiliendang I understood the "developing" part to indicate a section that's only relevant to handling the etcd code. People using `etcd` through `etcdctl` aren't necessarily going to be interested in the details of the RPC APIs or building from source.

**Comment by xiang90** [comment]
@heyitsanthony @weiliendang Yea. I feel etcd has two set of audiences: developers and system operators. Developers care more about how to write code against etcd and they want to have a simple etcd setup. On the other side, operators do not care the API details of etcd. They care more about how to set up a cluster in secure and maintainable way.

**Comment by xiang90** [comment]
Like as a developers they do not really care about how to upgrade etcd since its not their responsibility. But operators need to care about how to upgrade etcd from one version to another.

**Comment by weiliendang** [comment]
Ok I understand what you guys are saying. What if we renamed the headings to something like "Developing with etcd" and "Cluster Operations"?  In the first heading, maybe just move up "Basic Concepts". In the second heading, I would keep all of the bullets you have but re-order a bit along the lines I suggested. Does that work?

**Comment by weiliendang** [comment]
I think generally you understand my directional feedback. It doesn't have to be implemented literally.

**Comment by xiang90** [comment]
@weiliendang Yes. Sure. The order was pretty random previously. I will rework this as you suggested.

**Comment by xiang90** [comment]
@weiliendang I re-structured the doc as you suggested. I am not sure if we want to put concept at the second place. Not everyone has to read the concept... (Or most people will just want to learn as they go). For example, in riak doc they put Learning at the end: http://docs.basho.com/riak/kv/2.1.4/learn/

**Comment by weiliendang** [comment]
Looks fine. Minor thing: would make Troubleshooting one word.

**Comment by joshix** [comment]
* Quickstart
** Download and Build OK

* Developing (building apps atop etcd)
** Local setup - OK
** Interact with etcd - OK
** API reference

* Operating
** (HA) Clustering Setup
** Configuration
** Security
** Monitoring
** Maintenance (including backup)
** Disaster Recovery
** Upgrading and Compatibility
** Troubleshooting

* Concepts (for those contributing to etcd itself)
