### ISSUE TITLE
RFE: update directory modifiedIndex on any child modifications.

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#5148]
Currently the kubernetes data model represents "resources" (replication controllers, endpoints, etc), by creating directories per resource, and elements are added or removed from that directory based on user interactions.  

Each kubernetes controller keeps a cache of it's respective directory that it's responsible for, and rectifies their state accordingly.  There are no guarantees that the controller has the full state of the directory so it forces a periodic relist.  The problem that exists, is that these directories can become large, making a list arguably the most expensive operation in the system.  

A simple fix that would prevent this re-list from occurring would be to update the parent directories modified index whenever a new item is added, changed, or removed.  This would allow the controller to only need to perform a periodic get on the directory and relist only when it's state differs.  

/cc @xiang90 @rrati @hongchaodeng @wojtek-t @jeremyeder

**Comment by timothysc** [comment]
It may be possible to model this behavior in the etcd helper within kubernetes, but this would force an extra round-trip per write.

**Comment by wojtek-t** [comment]
So actually, I think that there is a guarantee that a controller has a full state (assuming there weren't any errors returned from a watch, etc.). If there aren't, then there is a bug (most probably on our (k8s) side) and we should fix that.

That said, what @timothysc described above would be a nice feature, but in my opinion it has relatively low priority.

**Comment by smarterclayton** [comment]
Wouldn't this create a constant multiplication of the cost of all writes (since the index would need to be propagated up the chain), and thus reduce the throughput of etcd by a constant factor relative to the depth of the write?

**Comment by timothysc** [comment]
So yes, it would add a fixed cost per write, but we're not write heavy.  

But there is still a heavy penalty that we will pay on situations like a net-split, or potential ELB timeouts.  If the watch exits for any reason we force the relist.  This RFE would mitigate that issue.

**Comment by smarterclayton** [comment]
We're not write heavy?  I thought we were 20% writes

**Comment by timothysc** [comment]
The change is trivial, PR inbound.

**Comment by wojtek-t** [comment]
I'm still not convinved the the performance will not suffer on that (in a healthy situation).

**Comment by timothysc** [comment]
@wojtek-t provided we don't round-trip over the wire I see the cost as a small % increase per write, which we can easily benchmark, and we don't need it for * resources.  We can also reduce the number of unnecessary writes and batch where possible.

That being said, I agree that in a healthy environment this would almost be unnecessary.  The problem is we see watch breaks from a number of other issues  (network hiccups, timeouts, mis-configurations), and every watch break is far more expensive then the cost of this change.  

My goal would be to make it option-enabled.

**Comment by wojtek-t** [comment]
>
@wojtek-t provided we don't round-trip over the wire I see the cost as a small % increase per write, which we can easily benchmark, and we don't need it for * resources. We can also reduce the number of unnecessary writes and batch where possible.

Sorry - I didn't look into your PR. I was assuming that you want to round-trip. If that's not the case, then I'm not that sceptical. But we definitely need a benchmark before enabling it by default.

**Comment by xiang90** [comment]
This https://github.com/coreos/etcd/pull/5283#issuecomment-217296167 solves the problem posted here. So closing this one.
