### ISSUE TITLE
separate metrics for users and metrics for developers/debugging

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5161]
### Problems

We want to expose metrics that user should use to monitor their cluster, like number of API calls/second, latencies of API calls and network communication metrics between members. These metrics should be high level and as implementation independent as possible.

On the other side, we also want to expose some very implementation depend metrics for developing and debugging. Users should usually not do dashboard over these metrics. We might want to change them one we change the implementation or we do not feel we really need this over time.

In a word, we really have two different sets of metrics for different purposes.

## Solution???

We can use labels or add prefix to metrics names. But it does not seems clean since when users do normal /metrics, they will still see the debugging metrics. They might accidentally build things that depend on these metrics that we might change over time. 

Ideally, we can serve them on different path. But it seems like we cannot do this in today's go library of prometheus.

Opinion? /cc @heyitsanthony @gyuho @fabxc @mwitkow @mischief

**Comment by mwitkow** [comment]
Please correct me if I'm wrong, your primary goal here is to make it clear
to users which metrics are "stable" and supported and which are internal
and can change with code?

In that case I think a prefix solution + documentation is an easy and
simple solution. Use  'etcd_internal' (or something similar) as namespace
and use documentation to explicitly distinguish that prefix as
"unsupported" as opposed to well documented and "stable" metrics.

Thanks for bringing it up for a wider discussion ☺️

**Comment by xiang90** [comment]
@mwitkow 

> Please correct me if I'm wrong, your primary goal here is to make it clear
to users which metrics are "stable" and supported and which are internal
and can change with code?

Yes.

> In that case I think a prefix solution + documentation is an easy and
simple solution

However, when user does /metrics, the internal ones will still be there. But I guess it is OK.

**Comment by fabxc** [comment]
This sounds the most reasonable to me as well.

As you said a separate registry is also an option but currently not
supported.

An advantage of the prefix is that all users will ingest them by default.
So they will be at hand to investigate bug reports from users.
The overhead is not as significant as one only has a few etcd instances. If
users are worried about it though, the metrics can easily be dropped from
ingestion in the Prometheus configuration.

**Comment by mwitkow** [comment]
Fabian has a point. By keeping the internal metrics in the same collection
by default, it is easier for operators  to plot debugging graphs (e.g. When
filing bugs upstream).

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/pull/5190
