### ISSUE TITLE
Unexpected change in release tarball

### ISSUE THREAD

**Issue by jbotelho2-bb** [coreos/etcd#5166]
I was just installing etcd on a new server using one of the release tarballs from GitHub (`etcd-v2.3.1-linux-amd64.tar.gz`), and noticed that my install script failed because the SHA256 hash has changed. I was able to grab an older copy of the tarball to confirm:

```bash
$ sha256sum etcd-v2.3.1-linux-amd64.tar.gz.*
696c76c55fff63fa7c8e14d98021af82c442f078f54a3097853653c0ae48397e  etcd-v2.3.1-linux-amd64.tar.gz.new
0f2881797398be9b89e3c5592ac71976633b21c287231eea010dd71911428fc7  etcd-v2.3.1-linux-amd64.tar.gz.old
```

As far as I can tell, the contents of the two tarballs are the same, and the new one passes GPG verification, but why would the tarball have changed since release?

**Comment by xiang90** [comment]
@gyuho Did we ever update the released tar? I do not think we did...

**Comment by gyuho** [comment]
@jbotelho2-bb In short, all the contents of release binaries and build environments are the same.

I was editing the release note of `v2.3.1` and clicked `Discard Draft` expecting GitHub to revert the change, but it actually deletes the whole release note. So I had to rebuilt the release binaries. The docker image doesn't change, but in the process of doing this, the SHA256 of tarball files seemed to change.


Please let me know if you have any other concerns. I will explain as much as I can.

And this won't happen again. Sorry about that.

**Comment by xiang90** [comment]
@gyuho We probably should keep a copy of these released files somewhere safely next time. So even if we did something wrong on github or github does something unexpectedly, we can recover the exact same tar files.

@jbotelho2-bb Sorry for the inconvenience.

**Comment by gyuho** [comment]
@xiang90 Ok I will store those in separate storage.
