### ISSUE TITLE
If dir=true and prevExist=true but the target node is a key it turns into a dir

### ISSUE THREAD

**Issue by philips** [coreos/etcd#518]
If `dir=true` and `prevExist=true` PUT only if the target node is a directory. Otherwise return "Not a directory".

Via: https://github.com/coreos/go-etcd/issues/90

/cc @onsi

**Comment by iankronquist** [comment]
I'm doing some work to address this.

**Comment by iankronquist** [comment]
Thoughts on the PR?

**Comment by xiang90** [comment]
@philips It seems like this does not really cause any issue in practice. Fixing this needs some effort (see https://github.com/coreos/etcd/pull/2147). I prefer to mark this won't fix.

**Comment by gyuho** [comment]
Closed via https://github.com/coreos/etcd/blob/master/Documentation/v2/README.md#known-bugs.
