### ISSUE TITLE
Discovery usage recursion problem

### ISSUE THREAD

**Issue by TrurlMcByte** [coreos/etcd#5180]
How to better to start etcd2 cluster with DNS discovery if my DNS based on this etcd?

**Comment by TrurlMcByte** [comment]
I mean currently it's like waving a dead chicken:

1.  starting simple static DNS (bind)
2.  starting Etcd2
3.  stopping bind
4.  starting SkyDNS+Register

**Comment by xiang90** [comment]
What is the problem with your current solution?

**Comment by TrurlMcByte** [comment]
It's manual and ugly. Don't known how to run as service chain in systemd

**Comment by xiang90** [comment]
@TrurlMcByte Which part is ugly? What is the idea workflow for you? It seems to me that to bootstrap something there has to be a manual part. Another thing is that if you can statically set up a dns server, why you cannot statically set up an etcd cluster at the first place?

**Comment by TrurlMcByte** [comment]
@xiang90 like "if provided DNS not available at all then don't check initial-advertise-peer-urls and use it as is", may be with some "force" key

**Comment by xiang90** [comment]
>  if provided DNS not available at all then don't check initial-advertise-peer-urls and use it as is

I do not think I understand this. Do you mean that if the DNS server for discovery is not available, you want etcd to just bypass discovery and start as a standalone cluster?

**Comment by TrurlMcByte** [comment]
last 2 days was trying to start cluster with doubled dns (primary pair is currently "dead", secondary pair is standalone with "hardcoded" _etcd-server._tcp records), but always getting errors like 
"rafthttp: failed to dial 57e249da6a0f92dd on stream MsgApp v2 (dial tcp: i/o timeout)"
and
"etcdserver: publish error: etcdserver: request timed out" 

With IP instead of fqdn hostnames it's just can't start, because initial-advertise-peer-urls did't match SRV records in case of fqdn name, or don't known self own name in case of direct IP's in SRV records.

With initial-cluster options in case of fqdn names - same problem "etcdserver: request timed out"

In case of initial-cluster and IP's instead of fqdn, starting immediately and all working fine (so it's not network problem). Resolving bit slow (because first pair is dead, but working everywhere, including any containers).

So this way (with 4 nameservers, where first two currently is dead) don't work at all.
After removing first two (dead, both only) of them - "cluster is healthy"  (on standalone only)

May be possible to setup different timeouts on bootstrap only?
heartbeat-interval and election-timeout don't relevant to this timeout.

**Comment by xiang90** [comment]
> May be possible to setup different timeouts on bootstrap only?

No. It is not possible.

**Comment by TrurlMcByte** [comment]
so found solution to start skydns first in proxy mode (just with fake domain), after this start etcd cluster using skydns, wait LONG time (minimum few minutes, or etcd will loose cluster), restart skydns in real dns mode
