### ISSUE TITLE
grant role to user will clean user password

### ISSUE THREAD

**Issue by lanzhiheng** [coreos/etcd#5182]
I have a 
1. user `tom` with password `tom`
```
curl -L -X PUT  http://127.0.0.1:2379/v2/auth/users/tom -d '{"user":"tom", "password":"tom"}'
```
2. role `tom` with permission read : /tom/*
```
 curl -L -X PUT  http://127.0.0.1:2379/v2/auth/roles/tom -d '{"role":"tom", "permissions": {"kv": {"read": ["/tom/*"]}}}'
```
3. grant role to user
```
curl -L -X PUT  http://127.0.0.1:2379/v2/auth/users/tom -d '{"user": "tom", "grant": ["tom"]}'
```
but now I assess the `tom/*`
```
curl -L -u tom:tom  http://127.0.0.1:2379/v2/keys/tom/
```
I get 
```
{"errorCode":110,"message":"The request requires user authentication","cause":"Insufficient credentials","index":0}
```
If I assess without password
```
curl -L -u tom:  http://127.0.0.1:2379/v2/keys/tom/
```
It's OK
```
{"errorCode":100,"message":"Key not found","cause":"/tom","index":17}
```
Is it the bug for etcd or that is the feature? If any time I grant the role to user, I must provide password for the user, it is not very convenient for programming。 Is there any API to get the password for the user, which save in etcd server 。

*In the early version 2.2.X doesn't have this problem*

**Comment by gyuho** [comment]
Are you sure that you wrote the key `tom`?

This works:

```
# user tom with password tom
curl -L -X PUT  http://127.0.0.1:2379/v2/auth/users/tom -d '{"user":"tom", "password":"tom"}'

# role tom with permission read : /tom/*
curl -L -X PUT  http://127.0.0.1:2379/v2/auth/roles/tom -d '{"role":"tom", "permissions": {"kv": {"read": ["/tom/*"]}}}'

# grant role to user
curl -L -X PUT  http://127.0.0.1:2379/v2/auth/users/tom -d '{"user": "tom", "grant": ["tom"]}'

# write the key
./bin/etcdctl set tom value

# assess the tom/*
curl -L -u tom:tom  http://127.0.0.1:2379/v2/keys/tom/
```

If you never wrote that key, `"Key not found"` is expected.

**Comment by gyuho** [comment]
Wait, I missed the line `{"errorCode":110,"message":"The request requires user authentication","cause":"Insufficient credentials","index":0}`. Will try to reproduce.

**Comment by gyuho** [comment]
@lanzhiheng Was there any other warning messages before `The request requires user authentication`? I Cannot reproduce this. https://github.com/coreos/etcd/blob/master/etcdserver/api/v2http/client_auth.go#L90

**Comment by gyuho** [comment]
reproduced. Will fix by tonight.

**Comment by lanzhiheng** [comment]
@gyuho ok, Thank you very mush!
