### ISSUE TITLE
clientv3: error types

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5211]
To make our users live better, we should define what errors etcd client might return and what are their types. So user can handle errors more easily. 

Right now we return raw gRPC errors most of the time. Hopefully we can return errors defined in this package.

**Comment by xiang90** [comment]
After a quick talk with @heyitsanthony, we decide to do the following:

There are three main types of errors client library might return:

1. gRPC transportation/server related errors: like connection refused, tls issue, server is closing...

2. etcdserver rpc related errors: lease not found, revision is compacted...

3. client side context error: context canceled...

For 1 and 3, the client library does not parse them and should return the original error.

For 2, the client library will parse the error by error string and translate it corresponding error defined in rpctypes.

**Comment by xiang90** [comment]
Also we should add an error type so that user can do type assertion on rpc error.

**Comment by gyuho** [comment]
Curious how we would decide if `case #1` is from grpc? `reflect.TypeOf`? Just plain string parsing?

**Comment by xiang90** [comment]
@gyuho We just detect case2, all others are either 1 or 3....

**Comment by xiang90** [comment]
@gyuho Can you take this one?

**Comment by gyuho** [comment]
@xiang90 Sure, I can work on this. And one more question:

https://github.com/coreos/etcd/blob/master/clientv3/integration/kv_test.go#L366

So some clientv3 already returns in `rpctypes` type. Then what do we mean by:

> For 2, the client library will parse the error by error string and translate it corresponding error defined in rpctypes.

client library doesn't really need to parse in this case.
