### ISSUE TITLE
etcdserver: grpc stream error flooding

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5213]
Cycle the cluster a few times with the put benchmark in the background:
```sh
tools/benchmark/benchmark  --endpoints=localhost:2379,localhost:22379,localhost:32379 put --conns=16 --clients=64 --key-space-size=10000 --total=100000
goreman -f V3DemoProcfile start
# wait a second, ctrl+c
goreman -f V3DemoProcfile start
# wait a second, ctrl+c
goreman -f V3DemoProcfile start
# repeat a few times...
```
eventually gets a server that floods error messages:
```
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport: write tcp 127.0.0.1:2379->127.0.0.1:56369: use of closed network connection"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status: connection error: desc = "transport: write tcp 127.0.0.1:2379->127.0.0.1:56374: use of closed network connection"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled"
12:01:38 etcd1 | 2016/04/27 12:01:38 grpc: Server.processUnaryRPC failed to write status: stream error: code = 1 desc = "context canceled"
[until server reset]
```

**Comment by xiang90** [comment]
@heyitsanthony It seems like these errors are caused by dead clients? Our benchmark client does not handle any errors I assume. If you stop the benchmark tool, the errors will go away?

**Comment by heyitsanthony** [comment]
@xiang90 I don't think it's a benchmark or client bug. It still goes through the clientv3 retry logic. If I kill the benchmark after seeing the log spew (which stops the messages) and start the benchmark again then it stalls trying to Put. If I reset the cluster when the benchmark is stalled, the benchmark resumes.

**Comment by heyitsanthony** [comment]
Can't reproduce this any more with current master. Closing.

**Comment by xiang90** [comment]
@heyitsanthony Interesting..... Did we do anything to fix this?

**Comment by heyitsanthony** [comment]
@xiang90 probably. We changed connection retry handling, added timeouts to the raft processing, and when requests can be served. I can reproduce the bug in e50df7c19b298608642ff6d0205b3d0e46586982 but it's gone by 29eca4eb88c159d31562c9dfdfec29d7863804b2.

**Comment by purpleidea** [comment]
Could this be at all related to:

> rpc error: code = 2 desc = grpc: the client connection is closing

of type: grpc.rpcError (UNEXPORTED)

which I'm seeing and I'm trying to track down.

**Comment by tejasmanohar** [comment]
any update here? would be nice to know the cause

**Comment by heyitsanthony** [comment]
@tejasmanohar the grpc connection logic has undergone a major rewrite since this was reported; it's not worth investigating if it can't be reproduced.

**Comment by tejasmanohar** [comment]
hm alright. i've seen it in another grpc project, that's why i was wondering haha

**Comment by tejasmanohar** [comment]
just wondering, were you able to determine if this was a client or server issue w/ grpc?

**Comment by heyitsanthony** [comment]
@tejasmanohar probably the interaction between both.

**Comment by Colstuwjx** [comment]
We also faced this issue, and it caused that our production etcd cluster cannot contact with api server, even cannot perform `put` action, finally we saddly cleaned up all data in etcd cluster, and things worked again.
