### ISSUE TITLE
Use _total only for counter metrics

### ISSUE THREAD

**Issue by brian-brazil** [coreos/etcd#5229]
Hi,

I noticed that in https://github.com/coreos/etcd/blob/26e52d2bce9e3e11b77b68cc84bf91aebb1ef637/etcdserver/metrics.go that there's two Gauges with a `_total` suffix. By [convention](https://prometheus.io/docs/instrumenting/writing_exporters/#naming) in Prometheus _total indicates a counter (there's several examples in this codebase. including one in this file), so to avoid confusion this suffix should be removed.

You could also remove `etcd_debugging_server_file_descriptors_used_total`, Prometheus clients provide that out of the box as `process_open_fds`.

**Comment by xiang90** [comment]
Can you please send prs to fix it?

**Comment by brian-brazil** [comment]
I'd be happy to
