### ISSUE TITLE
local-tester: WAL corruption

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5230]
Run local-tester for a while and an etcd member will stop booting due to WAL CRC errors. Keep it running and a majority of members will refuse to start because of CRC errors and the cluster is dead.

**Comment by xiang90** [comment]
on mac or linux?

**Comment by heyitsanthony** [comment]
linux+tmpfs

**Comment by heyitsanthony** [comment]
Looks like write tearing-- the last valid WAL offset is `0x30efe6` (also got `0x7bdfd7` and `0x182fdd`). The average record length is 55 bytes so the WAL is probably writing to a page boundary, crashing, then comes back to find the write only went through half way and panics.

**Comment by xiang90** [comment]
@heyitsanthony If I understand this correctly, it is not an etcd issue?

**Comment by heyitsanthony** [comment]
@xiang90 this is definitely an etcd / wal issue. It wasn't a problem before because the file size wasn't updated until the entry was entirely persisted to disk so there was no possibility of reading back a torn write.
