### ISSUE TITLE
2.3.3 v2/auth/users api fails to return if a role doesn't exist

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#5246]
2016-05-02 12:43:11.809296 I | etcdmain: etcd Version: 2.3.3
2016-05-02 12:43:11.809388 I | etcdmain: Git SHA: c41345d
2016-05-02 12:43:11.809402 I | etcdmain: Go Version: go1.6.2

if a user is assigned a role that doesn't exist then the users api is not returning anything....

I think this is an incorrect behavior - is this intentional?

curl -u root https://node05.etcd.dev.com:2379/v2/auth/users
{"message":"auth: Role role1 does not exist."}

**Comment by raoofm** [comment]
@heyitsanthony @xiang90 
Is this an intended behavior? 
If yes, then how is the end user supposed to get the user details to see where the issue is? 
If it is mandatory to create a role then the workflow should be to create the role first else etcd should stop from the user being created with non-existent role?
How is the behavior if there are more than 1 role that are assigned to user and roles doesn't exists?

The error only talks about the role and not about the users who have this assigned. Admin will need this info to correct the user.

**Comment by xiang90** [comment]
I feel this is a bug we need to fix. etcd tries to get the details of that role but fails... I believe this was introduced by the recent API change. Probably we should just return an empty role if the role does not exist.

**Comment by raoofm** [comment]
@xiang90  Or to have early detection of human errors, enforce role creation before assigning role to user.

I'm not sure how the existing problem could be solved as currently there is no way to get user details to know which user has this issue and needs correction.

Can we have both behaviors?

**Comment by raoofm** [comment]
Sorry, we will be grateful if you guys can provide an estimated release date so that we can plan as well, as a prod release is hanging :stuck_out_tongue_winking_eye:

**Comment by xiang90** [comment]
We will fix this in two weeks with a new release.

**Comment by raoofm** [comment]
@xiang90 Thanks

**Comment by gyuho** [comment]
Reproducible in master branch:

```
./bin/etcdctl user add root:a
# auth: created user root

curl -L -X PUT  http://127.0.0.1:2379/v2/auth/users/root -d '{"user": "root", "grant": ["foo"]}'
# auth: updated user root

curl -L -u root http://127.0.0.1:2379/v2/auth/users
```

Will fix next week.
