### ISSUE TITLE
etcdctl backup is missing WAL dir option

### ISSUE THREAD

**Issue by farvour** [coreos/etcd#5258]
When attempting to backup an etcd node using `etcdctl backup`, I am greeted with an error about being unable to locate the write ahead log files. This makes sense, as in our configuration, we split them using `--wal-dir` parameter.

Unfortunately, `etcdctl backup` doesn't understand a `--wal-dir` parameter, and thus fails to backup the node.

```
etcdctl backup --data-dir /var/lib/etcd --backup-dir /ephemeral1/etcd-backup
2016-05-03 09:43:45.631805 I | open /var/lib/etcd/member/wal: no such file or directory
```

Trying with `--wal-dir`:
```
etcdctl backup --data-dir /var/lib/etcd --wal-dir /ephemeral0/etcd --backup-dir /ephemeral1/etcd-backup
Incorrect Usage.

NAME:
   backup - backup an etcd directory

USAGE:
   command backup [command options] [arguments...]

OPTIONS:
   --data-dir 		Path to the etcd data dir
   --backup-dir 	Path to the backup dir
```

Is there an alternative here I'm not seeing?

**Comment by ajityagaty** [comment]
@xiang90 This is for etcd2 right? Is this just about accepting a `--wal-dir` option and initializing the `srcWAL` variable with it in `backup_command.go` file?
