### ISSUE TITLE
Etcd 2.3.3 proxy panic - CloseNotify called after ServeHTTP finished

### ISSUE THREAD

**Issue by Soulou** [coreos/etcd#5267]
An etcd instance running 2.3.3 on linux has panicked this morning. The node was a proxy node and it failed with the following trace:

```
panic: net/http: CloseNotify called after ServeHTTP finished

goroutine 35455 [running]:
panic(0xbeaea0, 0xc8204262b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
net/http.(*response).CloseNotify(0xc8200721a0, 0x0)
        /usr/local/go/src/net/http/server.go:1535 +0x9d
github.com/coreos/etcd/proxy.(*reverseProxy).ServeHTTP.func1(0x7f623aa76f48, 0xc8200721a0, 0xc820444008, 0xc820197a40, 0xc820444160, 0xc8207de070)
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/proxy/reverse.go:116 +0x39
created by github.com/coreos/etcd/proxy.(*reverseProxy).ServeHTTP
        /home/gyuho/go/src/github.com/coreos/etcd/release/etcd/gopath/src/github.com/coreos/etcd/proxy/reverse.go:122 +0xa1d
```

No special operation (cluster has been running for a while without any problem)

Do you have any hint?

Thanks a lot,

**Comment by gyuho** [comment]
Is there any easy way that we can reproduce this? The panic message is from https://github.com/golang/net/blob/master/http2/server.go#L2064, but I think etcd proxy does something wrong.

**Comment by Soulou** [comment]
Apologies for my lack of answer, it is reproduced from time to time, no way so far to get it willingly =\
