### ISSUE TITLE
etcdctl: don't use fancy tables for list

### ISSUE THREAD

**Issue by philips** [coreos/etcd#5296]
etcd v3.0.0-beta

Using member list etcdctl draws a fancy table:

```
+------------------+---------+--------+------------------------+------------------------+
|        ID        | STATUS  |  NAME  |       PEER ADDRS       |      CLIENT ADDRS      |
+------------------+---------+--------+------------------------+------------------------+
| 8211f1d0f64f3269 | started | infra1 | http://127.0.0.1:12380 | http://127.0.0.1:2379  |
| 91bc3c398fb3c146 | started | infra2 | http://127.0.0.1:22380 | http://127.0.0.1:22379 |
| fd422379fda50e48 | started | infra3 | http://127.0.0.1:32380 | http://127.0.0.1:32379 |
+------------------+---------+--------+------------------------+------------------------+
```

This makes doing trivial stuff like using awk/grep/etc much more awkward on the data. I know there is a JSON output but for quick hacky operations stuff tables like these are annoying. It reminds of the OpenStack nova-client which does this by default and makes doing trivial stuff harder.

**Comment by gyuho** [comment]
How about adding a `--plain` flag? /cc @xiang90 @heyitsanthony

**Comment by heyitsanthony** [comment]
@gyuho a separate flag seems fine to me; it'd be trivial to have a table printer separate from a simple printer. I think there's probably better wording than `plain`/`simple` though (`human`/`text`? `pretty`/`simple`?).

**Comment by gyuho** [comment]
`simple` sounds clearer. I will add that flag if nobody's working on it. Thanks.

**Comment by gyuho** [comment]
@philips Now etcdctl default to simple printer. If someone needs table printer, one can pass `-w table` flag (https://github.com/coreos/etcd/blob/master/etcdctl/READMEv3.md#examples-5).
