### ISSUE TITLE
etcdctl: member list advertises protobuf but it doesn't work 

### ISSUE THREAD

**Issue by philips** [coreos/etcd#5297]
```
$ etcdctl member list -w protobuf
Error:  only support simple or json as output format
$ etcdctl member list -h
NAME:
	member list - list is used to list all members in the cluster

USAGE:
	etcdctl member list

GLOBAL OPTIONS:
  -w, --write-out="simple"						set the output format (simple, json, protobuf)
```

**Comment by xiang90** [comment]
I feel this is a documentation issue. -w is a global flag, so right now it shows all possible options. It makes sense for some commands to support protobuf, whose responses are direct got back from gRPC like put, get or del. For composite commands, it does not make sense to support protobuf since there is no defined proto for them.

**Comment by heyitsanthony** [comment]
@xiang90 `member list` isn't a composite command though-- it maps directly to a single grpc command. I guess it should support protobuf output, then?

**Comment by xiang90** [comment]
@heyitsanthony Oh... You are right.  For this one we can add protobuf. But what about endpoint status one for example?

**Comment by heyitsanthony** [comment]
@xiang90 yeah, for composite commands there's no way to sanely protobuf it

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony We have 3 commands that do not support protobuf write-out:

```go
func (pb *pbPrinter) MemberList(r v3.MemberListResponse) {
	ExitWithError(ExitBadFeature, errors.New("only support simple or json as output format"))
}

func (pb *pbPrinter) EndpointStatus(statusList []epStatus) {
	ExitWithError(ExitBadFeature, errors.New("only support simple or json as output format"))
}

func (pb *pbPrinter) DBStatus(r dbstatus) {
	ExitWithError(ExitBadFeature, errors.New("only support simple or json as output format"))
}
```

What was the conclusion of resolving this? Can't remember what we had come up for this.

Is anybody working on this?
