### ISSUE TITLE
3 node etcd2 cluster fails, when one node reboots: rejecting vote to new leader

### ISSUE THREAD

**Issue by ralfbecker** [coreos/etcd#5299]
We run a 3 node CoreOS cluster on bare metal.

Roughly 2 out of 3 times when we reboot a node, etcd is not able to elect a new leader, because both remaining nodes seem to reject each others candidation. 

After some time fleetd then stops all units, because it lost contact to fleet :(

I attached etcd2 and fleetd log showing that situation:

[etcd2-fleetd-2015-03-15.txt](https://github.com/coreos/etcd/files/255411/etcd2-fleetd-2015-03-15.txt)

While the log is from mid march, problem still persists with current CoreOS version from stable channel.

**Comment by philips** [comment]
Can you confirm the version of CoreOS and etcd? 

```
cat /etc/os-release
etcd2 --version
```

**Comment by philips** [comment]
Under how much load is the machine under? If you do `touch /etc/foo` and then type `time sync` what is the timing?

**Comment by philips** [comment]
@xiang90 Did 2.2.3 have the bug with log truncation issues? They are saying it happens when they reboot.

(The folks in this report are at CoreOS Fest in Berlin, let me know what information they should gather and I can see)

**Comment by xiang90** [comment]
@philips Not I am aware of. We need more logs from all other members to have an idea of what is going on in the cluster.

**Comment by ralfbecker** [comment]
Here are the logs of the other two members:

[node8-etcd2-fleetd-2015-03-15.txt](https://github.com/coreos/etcd/files/257034/node8-etcd2-fleetd-2015-03-15.txt)
[node9-etcd2-fleetd-2015-03-15.txt](https://github.com/coreos/etcd/files/257035/node9-etcd2-fleetd-2015-03-15.txt)

**Comment by xiang90** [comment]
@ralfbecker It seems like the network latency was very high from the log, one etcd member receives a message after more than a second since the other member sent the message. If you are on a slow network, you should tune the election timeout. See https://github.com/coreos/etcd/blob/release-2.2/Documentation/tuning.md#time-parameters
