### ISSUE TITLE
Request: Add a "set if not equal to" operation

### ISSUE THREAD

**Issue by perj** [coreos/etcd#5307]
I have a key in etcd where I'm the only writer. The value is one of a limited set of values. Periodically I want to make sure the key has the correct value, and wasn't rolled back for example by a cluster master switch.

There doesn't seem to be any way to do this in a single operation. I can set the value unconditionally, but this pushes out a "set" event to all listeners, and this is potentially a lot of bandwidth for no change if there's a lot of listeners.

Instead I have to first do a get to fetch the current value, and if it wasn't what I expected, I then do a set. This works, but is two roundtrips, and is not atomic.

I'd like to request an "set if not equal to" feature, which updates a value if it's not equal to what I expected.

**Comment by gyuho** [comment]
Are you running etcd v2? Or have you looked at our `txn` https://github.com/coreos/etcd/blob/master/etcdctl/READMEv3.md#txn-options?

**Comment by heyitsanthony** [comment]
@perj this is how to do it with the v3 api:
```go
client.Txn()
.If(clientv3.Compare(clientv3.Value("yourKey"), "correctValue", "="))
.Else(clientv3.OpPut(clientv3.Value("yourKey"), "correctValue"))
```

**Comment by perj** [comment]
Ah, thanks. We're not using api v3 yet, and probably won't for a while. But it's good to know it has a solution. Any chance for a v2 version?

**Comment by xiang90** [comment]
@perj Sorry, no. We are not going to add more features of v2. One of the problems with v2 is what you have seen, and you can image that there will be endless transactional requests people want to add into v2 API. We just cannot take more.
