### ISSUE TITLE
etcdctl v3 get with empty prefix should return all keys

### ISSUE THREAD

**Issue by joelnn** [coreos/etcd#5323]
I expected to be able to provide an empty key prefix in order to get all they keys, but:

>$ ETCDCTL_API=3 etcdctl get --prefix=true ""
>Error:  etcdserver: key is not provided

#4697 seems related but I can't exactly understand what the resolution was there.

**Comment by heyitsanthony** [comment]
I tried this with a nul byte too and it gives me `Error:  range command needs arguments.`. It looks like there's no way to do this with the current `etcdctl`.

**Comment by joelnn** [comment]
While this is being considered, it would be great to have the range behavior with respect to prefixes and sort order documented. I am actually developing against the grpc api (generated for ruby) and was checking results against what etcdctl produces.

**Comment by xiang90** [comment]
@gyuho Would you like to fix this one?

**Comment by gyuho** [comment]
Sure.

**Comment by gyuho** [comment]
@joelnn Please update etcd with current master branch and try:

```
ETCDCTL_API=3 etcdctl get "" --prefix=true
ETCDCTL_API=3 etcdctl get "" --from-key
```

**Comment by joelnn** [comment]
@gyuho Thanks!

**Comment by ehlxr** [comment]
@gyuho it's work
