### ISSUE TITLE
Auto configuration with SSL configured

### ISSUE THREAD

**Issue by xuant** [coreos/etcd#5330]
etcd seems to be using SAN (Subject Alternative Names) if configured to use SSL.
I notice that we can configure an etcd cluster at runtime without SSL.
My question is, how can we do runtime reconfiguration for etcd with SSL configured?

**Comment by xiang90** [comment]
I do not think I understand your question. Can you provide more detail?

**Comment by xuant** [comment]
@xiang90 
For example, I have a etcd cluster of 3 nodes with ips 192.168.0.1, 192.168.0.2, 192.168.0.3. To secure the traffic from/to the cluster, I generate some cert files by specifying SAN=192.168.0.1,192.168.0.2, 192.168.0.3. And run the three etcd nodes with the generated certs.

Now I want to add two more nodes to the cluster with ips 192.168.0.4, 192.168.0.5. Since the certs used by the existing cluster are generated with SAN=192.168.0.1,192.168.0.2, 192.168.0.3, the certs will not work for the two new nodes.

I am having this problem because I'm trying to auto-scale my etcd cluster, but needing to regenerate the certs every time a node comes seem to be a big problem for auto-scaling the etcd cluster. Is there any way I can make the cert not relating to the ip of the nodes?

**Comment by xiang90** [comment]
> I am having this problem because I'm trying to auto-scale my etcd cluster, but needing to regenerate the certs every time a new node comes seem to be a big problem for auto-scaling the etcd cluster. Is there any way I can make the cert not relating to the ip of the nodes?

I think the best way is to generate cert with correct SAN. This is out of the scope of etcd though. I do not think we should ignore SAN verification or probably go's TLS library will just enforce that checking anyway. 

 /cc @gtank any idea?

**Comment by xiang90** [comment]
@xuant BTW, I assume you want to verify the cert. Or you can just use self-gen cert when you start the newly added member with correct SAN. That should be easy.

**Comment by gtank** [comment]
@xuant Unfortunately this is one of the classic problems with generating certificates. The solution is a bit out of scope for etcd- usually you generate certs on the fly as you provision new nodes. You could also make generating a new cert part of your node scaling process. 

There are a hundred projects that handle this in as many different ways. Two good ones I know of are Hashicorp's [Vault](https://www.vaultproject.io/docs/secrets/pki/index.html) and Cloudflare's cfssl (more DIY; we use it in [hack/tls-setup](../tree/master/hack/tls-setup/)).

**Comment by xiang90** [comment]
@gtank Thanks. I think the reply answers the question.

**Comment by xuant** [comment]
@xiang90 @gtank Thanks.
