### ISSUE TITLE
Nightly builds for testing purposes

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5331]
Some people want to test etcd with latest features. It will be useful to have nightly builds (either compiled binaries or container image) for testing purposes.

For example, @hongchaodeng wants to test this script https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/etcd/etcd.manifest#L22.

My suggestion is to have separate quay repo with this script:

```
FROM alpine:latest
RUN apk update
RUN apk --update add bash

# in case we need to run functional-tester
RUN apk --update add iptables iproute2

ADD bin/etcd /usr/local/bin/
ADD bin/etcdctl /usr/local/bin/

EXPOSE 2379 2380

# Define default command.
CMD ["bash"]
```

```
./build

export VERSION=v2016051201
sudo docker build -t quay.io/coreos/etcd-k8s:${VERSION} .
sudo docker run quay.io/coreos/etcd-k8s:${VERSION} ls /
sudo docker run quay.io/coreos/etcd-k8s:${VERSION} /usr/local/bin/etcd --version
sudo docker push quay.io/coreos/etcd-k8s:${VERSION}
```

/cc @xiang90 @heyitsanthony @hongchaodeng

**Comment by hongchaodeng** [comment]
One more issue. We want to support the exact command:
```
"/usr/local/bin/etcd --listen-peer-urls http://127.0.0.1:{{ server_port }} --addr 127.0.0.1:{{ port }} --bind-addr 127.0.0.1:{{ port }} --data-dir /var/etcd/data{{ suffix }} 1>>/var/log/etcd{{ suffix }}.log 2>&1"
```
Just replace:
- "server_port" -> 2380
- "port" -> 4001

**Comment by heyitsanthony** [comment]
@hongchaodeng why 4001 instead of 2379?

**Comment by hongchaodeng** [comment]
@heyitsanthony 
Not a good reason, but that's what it is:
https://github.com/kubernetes/kubernetes/blob/f6dc06bdc7e15edf70789f75714744f65d2b0685/cluster/saltbase/salt/etcd/init.sls#L55-L83

**Comment by xiang90** [comment]
i am ok with nightly build. we should keep the original image. for k8s, they has their own image assumptions. @hongchaodeng should use https://github.com/kubernetes/kubernetes/tree/master/cluster/images/etcd to build the image from etcd/master.

**Comment by hongchaodeng** [comment]
With Gyuho's help, I have built the image successfully with "cluster/image/etcd". 
We have a public etcd3 image at `gcr.io/coreos-k8s-scale-testing/etcd:3.0.0-beta.0`
At first I will build it manually along with the release. If there is any need, we can have a CI job to do it.

**Comment by gyuho** [comment]
Yeah, please let me know if you need any other help. It would be good if we can automate that in the next v3 release. I will close this for now.

**Comment by hongchaodeng** [comment]
Sure. Also thanks for the help!
