### ISSUE TITLE
gateway: make monitoring interval configurable

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5335]
We mark a failed endpoint to be unavailable for a fixed interval right now. 

https://github.com/coreos/etcd/blob/master/proxy/tcpproxy/userspace.go#L140

We want to make this configurable and add a flag into gateway to configure it.

/cc @gyuho can you take a look?

**Comment by xiang90** [comment]
we called this flag https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md#--proxy-failure-wait in the old proxy. probably we need a better name? failure wait is not that descriptive i feel.

**Comment by gyuho** [comment]
Ok, will take a look.
