### ISSUE TITLE
TestKVPutStoppedServerAndClose fails

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5343]
https://semaphoreci.com/coreos/etcd/branches/pull-request-5328/builds/7

```
--- FAIL: TestKVPutStoppedServerAndClose (5.39s)
	kv_test.go:587: rpc error: code = 13 desc = transport is closing
```

**Comment by heyitsanthony** [comment]
I burned this for more than 100 rounds on two different machines with and without -race and I'm not seeing this failure (600+ rounds). It looks like the client reconnect changes fixed this.

**Comment by gyuho** [comment]
Ok thanks! Let's close it for now. And reopen if that happens again.

**Comment by xiang90** [comment]
@heyitsanthony 

In this branch, there is still this failure: https://semaphoreci.com/coreos/etcd/branches/pull-request-5350/builds/1.

I think this branch https://github.com/xiang90/etcd/commits/fix_test contains the reconnect fix?

**Comment by gyuho** [comment]
Actually just found this out too https://semaphoreci.com/coreos/etcd/branches/master/builds/274.

**Comment by xiang90** [comment]
@gyuho OK. Reopen.
