### ISSUE TITLE
[Help]: etcd cluster data disorder, and `X-Etcd-Index` value of node is different with each other

### ISSUE THREAD

**Issue by hustcat** [coreos/etcd#5347]
We have a etcd cluster with 3 nodes in production environment. The leader node is changed because some unkown reason by accident, and result is  data of etcd cluser became disorder.

We found etcd node's `X-Etcd-Index` value is different with each other:
```
# curl http://10.x.x.x:4001/v2/keys/registry -vv &&
> curl http://10.y.y.y.y:4001/v2/keys/registry -vv
...
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Index: 25452
< X-Raft-Index: 33523881
< X-Raft-Term: 12
< Date: Fri, 13 May 2016 04:38:06 GMT
< Transfer-Encoding: chunked

...
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Index: 22691
< X-Raft-Index: 33523881
< X-Raft-Term: 12
< Date: Fri, 13 May 2016 04:38:06 GMT
< Transfer-Encoding: chunked
```

Is that means the data of node is not consistent? How could this can happen ? What shall I do? Can anyone gave me some suggestions?

etcd version is v0.4.6.

Many thanks.

**Comment by xiang90** [comment]
Please use etcd2.x instead of 0.x. Thanks.

**Comment by xiang90** [comment]
Here is how you can import your data: https://github.com/coreos/etcd/blob/release-2.3/Documentation/04_to_2_snapshot_migration.md

**Comment by hustcat** [comment]
@xiang90 Can you gave me some suggestion to find the reason? Can you promise to me that I will not run into the same problem even if I migrate to v2.x? 

It's reckless to use etcd 2.x before I got the real reason. We are using etcd in production environment, not test or development environment.

**Comment by xiang90** [comment]
>  Can you gave me some suggestion to find the reason? 

etcd 0.x has a few issues with its raft library. We have rewrote the core part in 2.x.

> Can you promise to me that I will not run into the same problem even if I migrate to v2.x?

I am not the operator of your cluster, thus I cannot promise you anything. It is your responsibility to correctly do backup and upgrade your software.

> It's reckless to use etcd 2.x before I got the real reason. 

I feel it is irresponsible to use a out-of-date software. etcd 2.x has been release for more than a year. If you follow etcd release actively, you should already know there are a few issues that can cause 0.4 into bad situation.

**Comment by xiang90** [comment]
My suggestion is to upgrade your cluster. We have seen a few inconsistent issues in 0.x and are aware of these issues. We have never seen a single issue with etcd 2.x. However I still suggest you do backup when necesary even if you upgrade your cluster.
