### ISSUE TITLE
Question: how to watch for cluster events?

### ISSUE THREAD

**Issue by celevra** [coreos/etcd#5357]
Hi,

i'm on a 3 node CoreOS and i want to listn to cluster events, i think fleet does this allready, doesn't it?

I need to know as fast as possible if one node is down, so that i can switch my ClusterIP's
etcd knows allready when a node is available or not so how can i listn to that events?
I don't want to call /health every few seconds, i think there must be a elegant way.

regards

celevra

**Comment by xiang90** [comment]
There is no magic way to do that actually. Internally, etcd also does simple health checking between every pairs of nodes. Externally, you have to ping each node to know its status against your local node since connectivity it per node not per cluster.

**Comment by xiang90** [comment]
If you are talking about actual cluster events like remove/add nodes, there is already an issue for it :https://github.com/coreos/etcd/issues/5277

**Comment by celevra** [comment]
Thanks for the answer 
If Polling for /health is the right way how fast can I do it without disturbing etcd? Every 2 seconds?


________________________________
Von: Xiang Li <notifications@github.com>
Gesendet: 17.05.2016 4:58 vorm.
An: coreos/etcd
Cc: Philipp Zeitschel; Author
Betreff: Re: [coreos/etcd] Question: how to watch for cluster events? (#5357) 

If you are talking about actual cluster events like remove/add nodes, there is already an issue for it :#5277
