### ISSUE TITLE
v2.3.4 was supposed to have pull #5265

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#5365]
@xiang90 @gyuho 
[v2.3.4](https://github.com/coreos/etcd/releases/tag/v2.3.4) was supposed to have the fix #5265 for #5246 

Was waiting so eagerly for past 2 weeks. :disappointed: 

Also wondering if #5345 should be part of it too.

**Comment by xiang90** [comment]
Sorry. We will do another release this week...

**Comment by gyuho** [comment]
@raoofm I am so sorry. Totally missed it. Will do it tomorrow.

**Comment by raoofm** [comment]
@xiang90 np, thanks

@gyuho np, no hurries, this week is fine too :smile:

**Comment by raoofm** [comment]
will #5345 be included as well

**Comment by raoofm** [comment]
@gyuho ?

**Comment by gyuho** [comment]
@raoofm Sure, I will double check on that.

**Comment by gyuho** [comment]
@raoofm Please try https://github.com/coreos/etcd/releases/tag/v2.3.5.

Thanks!
