### ISSUE TITLE
can't compile successful

### ISSUE THREAD

**Issue by blackbeans** [coreos/etcd#5369]
# Bug reporting

when i  compile etcd/client  using  "go get github.com/coreos/etcd/client" command ,the command line shows me   thess error messages  

../../github.com/coreos/etcd/client/keys.generated.go:40: undefined: codec.GenVersion
../../github.com/coreos/etcd/client/keys.generated.go:43: undefined: codec.GenVersion
../../github.com/coreos/etcd/client/keys.generated.go:54: undefined: codec.GenHelperEncoder
../../github.com/coreos/etcd/client/keys.generated.go:146: undefined: codec.GenHelperDecoder
../../github.com/coreos/etcd/client/keys.generated.go:176: undefined: codec.GenHelperDecoder
../../github.com/coreos/etcd/client/keys.generated.go:233: undefined: codec.GenHelperDecoder
../../github.com/coreos/etcd/client/keys.generated.go:314: undefined: codec.GenHelperEncoder
../../github.com/coreos/etcd/client/keys.generated.go:546: undefined: codec.GenHelperDecoder
../../github.com/coreos/etcd/client/keys.generated.go:576: undefined: codec.GenHelperDecoder
../../github.com/coreos/etcd/client/keys.generated.go:671: undefined: codec.GenHelperDecoder
../../github.com/coreos/etcd/client/keys.generated.go:671: too many errors

**Comment by gyuho** [comment]
@blackbeans Works fine in my machine.

```
go get -v github.com/coreos/etcd/client
github.com/coreos/etcd (download)
github.com/coreos/etcd/pkg/pathutil
github.com/coreos/etcd/pkg/types
github.com/coreos/etcd/client
```

What go version are you running?

**Comment by blackbeans** [comment]
use vendor to solve this problem ...
