### ISSUE TITLE
Possible issue with adding a new member to an existing cluster?

### ISSUE THREAD

**Issue by kabudu** [coreos/etcd#5370]
I'm running a 3 node etcd cluster, with etcd running in a docker container on each host server.

etcd version: 2.2.4

I have recently had to replace one of the members of the cluster so I went through the following process:

**On the new member host server, I ran the following:**

```
 docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs -p 4001:4001 -p 2380:2380 -p 2379:2379 \
    --name etcd quay.io/coreos/etcd:v2.2.4 \
    -name etcd2 \
    -advertise-client-urls http://192.168.10.100:2379,http://192.168.10.100:4001 \
    -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
    -listen-peer-urls http://0.0.0.0:2380
```

I then verified that the container was up and running.

**On the cluster leader host server, I ran the following:**
    
    curl -X DELETE http://127.0.0.1:2379/v2/members/cccccccccccccccc
    curl -X POST http://127.0.0.1:4001/v2/members -H 'Content-Type: application/json' -d '{"name":"etcd2", "peerURLs": ["http://192.168.10.100:2380"]}'

**I then checked the list of members on the cluster leader host server:**
    
    curl http://127.0.0.1:2379/v2/members

```
{
	"members": [{
		"id": "bbbbbbbbbbbbbbbb",
		"name": "etcd1",
		"peerURLs": ["http://192.168.10.99:2380"],
		"clientURLs": ["http://192.168.10.99:2379", "http://192.168.10.99:4001"]
	}, {
		"id": "cccccccccccccccc",
		"name": "",
		"peerURLs": ["http://192.168.10.100:2380"],
		"clientURLs": []
	}, {
		"id": "aaaaaaaaaaaaaaaa",
		"name": "etcd0",
		"peerURLs": ["http://192.168.10.98:2380"],
		"clientURLs": ["http://192.168.10.98:2379", "http://192.168.10.98:4001"]
	}]
}
```

I immediately noticed that the name I supplied as an argument was ignored, and also that the clientURLs data element was empty, so I removed the new member and re-created it by running the following on the cluster leader host server:

    curl -X POST http://127.0.0.1:4001/v2/members -H 'Content-Type: application/json' -d '{"name":"etcd2", "peerURLs": ["http://192.168.10.100:2380"], "clientURLs": ["http://192.168.10.100:2379", "http://192.168.10.100:4001"]}'

but it didn't make a difference as listing the members again gave a similar output to the above without the name or client URLs.

So... moving along, I decided to check the registered keys

**On the cluster leader host server:**

    curl http://127.0.0.1:2379/v2/keys

```
{
	"action": "get",
	"node": {
		"dir": true,
		"nodes": [{
			"key": "/Repository",
			"dir": true,
			"modifiedIndex": 9,
			"createdIndex": 9
		}]
	}
}
```

**On the new member host server:**

    curl http://127.0.0.1:2379/v2/keys

```
{
	"action": "get",
	"node": {
		"dir": true
	}
}
```

Based on the above, it appears that the new member hasn't *really* been recognised as a cluster member, or replication hasn't happened.

Is there something obvious I'm missing here, or have I performed one or more of the steps incorrectly?

Thanks

**Comment by xiang90** [comment]
@kabudu Name and ClientURLs are self-published. It is added successfully. To start replication, you need to actually start a etcd process with the new configuration.

**Comment by kabudu** [comment]
@xiang90 thanks for the insight, but just to confirm, when you say start a process, do you basically mean something like post an update to the cluster leader and the cluster will then synchronise the new member?

**Comment by xiang90** [comment]
@kabudu I mean to start the etcd process on the new server that you want to run etcd on.

**Comment by kabudu** [comment]
@xiang90 The etcd container on the new server is already running but the replication did not kick in. I tried restarting the container but that didn't make a difference. Is there something else I need to do on the new member for it to *find* the cluster?

**Comment by xiang90** [comment]
@kabudu Please read https://github.com/coreos/etcd/blob/release-2.3/Documentation/runtime-configuration.md#add-a-new-member.
