### ISSUE TITLE
etcdctl v3 backup command hidden by ETCDCTL_API=3

### ISSUE THREAD

**Issue by joelnn** [coreos/etcd#5372]
With the env var ETCDCTL_API=3, there is no 'etcdctl backup' command. Seems it should be there regardless of what API version we are using. Otherwise, it makes one doubt whether backing up v3 data is supported.

Maybe a similar argument could be made for 'etcdctl cluster-health'.

**Comment by joelnn** [comment]
I guess 'backup' really isn't supported for v3, supposed to use snapshot save/restore. Disregard.

**Comment by timoreimann** [comment]
For those ending up at this issue as well trying to find the proper etcd v3 approach to creating backups: it's documented here: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md
