### ISSUE TITLE
TestSendMessageWhenStreamIsBroken fails on go tip

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5381]
```
--- FAIL: TestSendMessageWhenStreamIsBroken (0.09s)
	functional_test.go:135: disconnection time = 12ms, want < 10ms
```

https://travis-ci.org/coreos/etcd/jobs/130984316

**Comment by xiang90** [comment]
Can you fix this? Probably just increase timeout to 50ms... CI does not like 10ms.

**Comment by gyuho** [comment]
Yeah it's only 2ms over. Will change it to 50ms.
