### ISSUE TITLE
Question: Why does rafthttp use custom message formats?

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#5389]
It seems that rafthttp uses custom image formats e.g. messageEncoder and msgAppV2Encoder. Is there a reason of not using protobuf directly? Just curious.

/cc @xiang90

**Comment by xiang90** [comment]
Protobuf is not delimited. So you have to have your own encoder. On the other side, when we were doing this there were no gRPC. Even with gRPC we might want to have better encoder for append request where we can compact a lot of metadata.

**Comment by mitake** [comment]
@xiang90 so the motivation is performance. I understand, thanks for your answer.
