### ISSUE TITLE
comments on V3: watch directory for changes of children

### ISSUE THREAD

**Issue by yy2008** [coreos/etcd#5399]
There were a lot of discussions about watching directory for changes of children. Issue 633 was closed as v3 moves to flat k-v space. But the question also applies to v3 -- What's the plan to support watching directory for changes of children (but not grandchildren and etc.)?

**Comment by xiang90** [comment]
There is no directory in v3. Why does it still apply?

**Comment by yy2008** [comment]
while there is no directory in v3, the hierarchy can be simulated in the form of prefix, I assume? for example, we can have:
/dir
/dir/dir1
/dir/dir2
dir/dir1/dir11
The use case is to watch prefix /dir if /dir/dir3 is added, or /dir/dir1 is removed...but not /dir/dir1/dir12 is added.

**Comment by xiang90** [comment]
That is not the best way to fully simulate directory. You need to put depth first, then you can do things like ls easily. It applies to watch. V3 API itself does not need to understand the separator or directory.

**Comment by yy2008** [comment]
didn't see the depth mentioned in the v3api.md -- how should it be used?

**Comment by xiang90** [comment]
Again, simulation of directory is on users, not etcd. I just suggest one way that you may use to achieve what you want.

**Comment by yy2008** [comment]
It's true this can be done on client side, but I do think it will be useful to have this capability on the server side -- I believe the motivation (not solution) discussed in https://github.com/coreos/etcd/issues/633,  applies to v3 as well. :-)
It would be great if the v3 API can support this as you originally suggested:

> https://github.com/coreos/etcd/issues/633#issuecomment-37921585

**Comment by xiang90** [comment]
@yy2008 Unfortunately, v3 API will be a flat kv structure and will not do anything related to directory.

**Comment by philips** [comment]
@xiang90 This is becoming a common enough problem that I think we need to document, step-by-step, how you use the v3 prefixing to find a list of related keys like you could do with directories.

**Comment by xiang90** [comment]
> document, step-by-step, how you use the v3 prefixing to find a list of related keys like you could do with directories.

This is a different problem in my opinion. Prefix/ranging query should be documented. How to migrate from v2 directory to v3 should be documented. And we can also write about how to do full directory simulation, which is a medium term goal.

However, we are not going to add directory support in native v3 API as @yy2008 suggest in this issue. The reason is that user can build it in user space or in the proxy layer in the future.

**Comment by xiang90** [comment]
@philips created a separate issue: https://github.com/coreos/etcd/issues/5401
