### ISSUE TITLE
comment on v3: watch prefix change with depth control or regex

### ISSUE THREAD

**Issue by yy2008** [coreos/etcd#5402]
while https://github.com/coreos/etcd/issues/5399 was closed, I do think there is a need to support prefix watch with a depth/level control.

Here is the use case -- assume we use etcd to configure servers. Whenever a new server is added,  app1 needs to be triggered, and whenever an existing server is updated, app2 needs to be triggered.

The server config can share same prefix and follow a patent as /servers/server-<id>. 

Certainly, app1 can watch prefix "/servers" and app2  watches "/servers/server-".

The issue is whenever a specific server is updated, app1 will get notifications as well. Intelligence has to be put into app1 to decide if a new server is added, or just a modification of existing server. It seems not a big deal.

At-a-glance, this seems simplifying the design of the etcd. But IMO, this could be at the cost of performance (on both client and server sides). -- Every time, when there is a change, etcd needs to send notification to the app1. If there are a big number of servers, and frequent changes of their configuration states, a lot of unnecessary watch event are generated. 

I agree with Philips's comment, > https://github.com/coreos/etcd/issues/5399#issuecomment-220375670, this is a common enough issue. Allowing a depth control or regex with prefix watch on the server side will benefit both server and client.

**Comment by xiang90** [comment]
@yy2008 

I think you can do

app1 watches on /servers/*
app2 watches on /servers-confs/*

When adding a new server, you can write to both servers and confs in a txn. When updating the conf, yo u can write to confs.

If you want to do regex, you can implement that in your client or add a simple proxy layer in front of etcd.

**Comment by yy2008** [comment]
What if there is network config under server-config? and IP config under network config, IPv4 and IPv6 config under IP config .... and have applications watch such changes on each level?

This seems indicating, whenever there is a change on the specific config, there has to be a txn to touch all the general config.

**Comment by heyitsanthony** [comment]
@yy2008 do you just need a way to watch the immediate children of a directory?

**Comment by xiang90** [comment]
> This seems indicating, whenever there is a change on the specific config, there has to be a txn to touch all the general config.

I do not think I understand this. Can you provide more examples? What I was suggesting is that you can always grouping your keys in a more flat way and uses pointer to point to other related prefixes. That is how directory itself is implemented. If you would love to think in the directory way, then you can always implement directory in your apps with appending depth before the key and adding pointer inside the prefix.

**Comment by yy2008** [comment]
@heyitsanthony yes.

**Comment by xiang90** [comment]
@yy2008 Here is an example of how to add depth to simulate directories i application:

https://github.com/chzchzchz/zetcd/blob/master/path.go#L7-L19

and here is how to get the first level children: https://github.com/chzchzchz/zetcd/blob/master/zketcd.go#L331-L352

**Comment by heyitsanthony** [comment]
@yy2008 the main idea to what @xiang90 is pointing to is structuring the keys like:

[directory-depth]/[path]

so that the directory depth can be used in the v3 `Watch()` call to range over a given directory's children.

For example, consider the keys (this is similar to what `mkPath` does in zetcd):
"\x01/servers/"
"\0x2/servers/server-a"
"\0x3/servers/server-a/some-data"
"\0x3/servers/server-a/some-more-data"
"\0x2/servers/server-b"
"\0x2/servers/server-c"

To watch on `/servers/` (e.g., to see when `/servers/server-d` is added)
```go
client.Watch("\x02/servers/", clientv3.WithPrefix())
```

To watch on `/servers/server-a/` (e.g., updates to `some-data` and `some-more-data`):
```go
client.Watch("\x03/servers/server-a/", clientv3.WithPrefix())
```

**Comment by yy2008** [comment]
@heyitsanthony @xiang90 got it. Thanks!! 👍

**Comment by xiang90** [comment]
Seems like you already got the answer. So closing.

**Comment by zonghaishang** [comment]
I'm using jetcd (version 0.0.1), How to use  api client.Watch("\x02/servers/", clientv3.WithPrefix()) and  client.Watch("\x03/servers/server-a/", clientv3.WithPrefix()) ? @heyitsanthony
