### ISSUE TITLE
etcd v3 API doc

### ISSUE THREAD

**Issue by yy2008** [coreos/etcd#5403]
Any document available for etcd v3 API, like this, https://coreos.com/etcd/docs/latest/api.html?

**Comment by gyuho** [comment]
We have API spec doc here https://github.com/coreos/etcd/blob/master/Documentation/api_v3.md. If you are looking for etcdctl usage https://github.com/coreos/etcd/blob/master/etcdctl/READMEv3.md.

For client https://github.com/coreos/etcd/tree/master/clientv3.

For demo, there's a pending PR https://github.com/coreos/etcd/pull/5279.

**Comment by yy2008** [comment]
I don't think the API spec provides much insights about new features -- For example, what's the REST API to create a transaction? how to do a range search?...

**Comment by gyuho** [comment]
@yy2008 Currently we don't support cURL-able endpoints as in v2. It's in the roadmap though.

Agree, we need better documentation on new features.

/cc @xiang90 @heyitsanthony

**Comment by xiang90** [comment]
@yy2008 Are you trying to write a client library for etcd? Or you want to write an application with an etcd client?

**Comment by yy2008** [comment]
To write an app. But go may not be the choice.

**Comment by xiang90** [comment]
@yy2008 OK. Then the API reference is not the right thing for you. It is for client binding writers. What language binding do you plan to sue?

**Comment by yy2008** [comment]
It will be python initially.

**Comment by xiang90** [comment]
@fasaxc is probably working on a python client for etcd3. So you should discuss with python binding people about how they are going to write the API guide. Now we only have doc for go-client, etcdctl and API reference for client binding developers. We might add a restful API in the future as a cross language generic thing with doc like v2 API.
