### ISSUE TITLE
v3api: range/watch with {min,max}{create,mod}revision

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5412]
For mutexes I'd like to be able to `Get(prefix, WithPrefix(), WithMaxCreateRev(myRev-1), WithLimit(1), WithSort(CreateRev, DESCEND))` to save some bandwidth on the slow path. There are probably use cases for the other permutations.

The watcher interface already implements (to some extent) MinModRev and MaxModRev via startRev and progress notifications respectively. MaxCreateRev could ignore newer keys and notify+close the watcher once all older revs are deleted. MinCreateRev would ignore updates to older keys.

Could be useful.

**Comment by xiang90** [comment]
This was inside the original API design. And I removed them since I think it is complicated. Probably we should add some of them back or all of them if there is a clear use case.

**Comment by xiang90** [comment]
Fixed by #6411 and #6424
