### ISSUE TITLE
V2 vs V3 http:// prefixes?

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#5427]
I suppose I'm a bit confused about the V2 -> V3 transition. It used to be that http:// prefixes were required for the client endpoints, but now they seem to cause:

```
2016/05/22 03:57:56 grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: too many colons in address http://localhost:2379"; Reconnecting to "http://localhost:2379"
```

Similarly are peerUrls and clientUrls (in the golang API) supposed to have these or not? It's a little inconsistent in my mind, so some clarity would help. Or perhaps I'm just awake for too long.

Thanks

**Comment by xiang90** [comment]
@purpleidea I am aware of this issue. Probably we should trim the http header in v3 client automatically. also if it is https, we should use secure connection. Can you send a patch to fix this?

/cc @heyitsanthony @hongchaodeng

**Comment by purpleidea** [comment]
On Sun, May 22, 2016 at 11:34 AM, Xiang Li <notifications@github.com> wrote:

> @purpleidea <https://github.com/purpleidea> I am aware of this issue.
> Probably we should trim the http header in v3 client automatically. also if
> it is https, we should use secure connection. Can you send a patch to fix
> this?


Yeah I'm happy to write a patch once I've fully wrapped my head around
this. I don't know too much about grpc and how you specify whether it's
https or not since you don't pass in the protocol in the endpoint string.
If you guide me I'll try and write it.

Cheers,
James

**Comment by purpleidea** [comment]
To further this discussion, some notes:

The endpoints must not have a http:// prefix in the client endpoints, but also in the Maintenance.Status endpoints parameter. Other locations might also have this issue.

**Comment by purpleidea** [comment]
@heyitsanthony Sweet, however AFAICT, I don't think this handles the Maintenance.Status endpoint parameter, or am I mistaken?

Thanks! Will try and test shortly.

**Comment by heyitsanthony** [comment]
@purpleidea maintenance dials through the client (https://github.com/coreos/etcd/blob/master/clientv3/maintenance.go#L137), so it should work...

**Comment by purpleidea** [comment]
@heyitsanthony Lovely, thanks! Any chance you'd want to accept a patch to unify all the interfaces to take the etcdtypes URLs as an argument instead of some taking strings, and others taking urls?

Might be nice for v3.

**Comment by heyitsanthony** [comment]
I don't think adding a special type for URLs will be any better than just using a `string`-- it'll probably be more cumbersome than helpful. The golang net interfaces (e.g., Dial) use `string` so the hostnames / urls should probably stay as `string`s.
