### ISSUE TITLE
RFC: support multi store in single cluster

### ISSUE THREAD

**Issue by mqliang** [coreos/etcd#5428]
@xiang90 @hongchaodeng 

IIUC, currently one etcd cluster just has one store. I think we should support multi store in single cluster: user create a store first, and then CRUD keys in that store.

The reason I want to support multi-store is: the current k8s put different resource into different etcd cluster(for example, use a dedicate cluster to save hot data Event/Pod/Node). I'd like put different resource in different store(but a in single etcd cluster), and different store could have its own global index, instead of a cluster-global index.

Putting all data in one cluster bring some maintenance benefit, for example, if I want upgrade etcd from v2 to v3, I just need upgrade one cluster.

I can work on it if you guys think this is a good idea.

**Comment by mqliang** [comment]
According to my understanding, the serializable isolation requirement should apply to store, instead of cluster, just like traditional DBMS, we could create several DBs in one server, and configure each's isolation level.

**Comment by xiang90** [comment]
We do not have any plan to support multiple store/raft inside one etcd cluster. It will significantly complicate the design of etcd and bring little benefits in my opinion. User can always set up multiple etcd clusters and shard the data themselves. 

One etcd cluster can sever millions of keys and 10,000s requests per second. Can you provide me a use case that you need a metadata store that requires more than this scale? 

For Kubernetes, the current bottleneck is not etcd. There are tons of thing we want to solve inside kubernetes before we want to look at etcd. However, that is separate discussion that should happen inside kubernetes repo.

>  According to my understanding, the serializable isolation requirement should apply to store, instead of cluster, just like traditional DBMS, we could create several DBs on one server, and configure each DB's isolation level.

You can set up multiple etcd clusters on one server, just like you can setup multiple MySQL instances (or other traditional DBMS) on one physical server.

**Comment by xiang90** [comment]
@mqliang 

f you want to help us improving the scalability of etcd, the best place is the proxy. We do want to scale read/watch through proxy layer. I

Right now, we have a "working" kv proxy doing basically anything: https://github.com/coreos/etcd/blob/master/proxy/grpcproxy/kv.go#L34.

We want to cache the data we write through the proxy. For range queries, we want to read through the cache first. Also there will be cache invalidation involved. 

Moreover, we want to have a watch proxy that coalesce multiple watchers into one watcher. 

For you multiple stores idea, we will consider it if there is a strong need from the community. Kubernetes use case is not valid in my opinion.

**Comment by mqliang** [comment]
@xiang90 
> If you want to help us improving the scalability of etcd, the best place is the proxy.

Ok, I will take a look.

> For you multiple stores idea, we will consider it if there is a strong need from the community. Kubernetes use case is not valid in my opinion.

Ok. The reason I'd like to use multiple store is because we use high performance server, one single cluster just use a small part of resource. Then we setup multi cluster on one physical server, but it brings some maintenance burden to us. It's not a really strong need.

**Comment by raoofm** [comment]
:+1: 

Agree with both of you. 

A very simple use case to think of is to support multiple training/testing environments within an org with the same etcd cluster which simplifies maintainability and cost, instead of going for prefixes that signify environment name (which seems like a hack).

Though I agree that a hack is available easily so this change may not be needed.
