### ISSUE TITLE
Document etcd v3 benchmark

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5433]
In [performance.md](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/performance.md#benchmarks), we need to document how to run benchmark tests.

- [ ] how to run per-package benchmark tests (`go test -bench=xxx`)
- [ ] Instructions on how to run benchmark CLI
- Sample testing results + Memory usage with graphs
 - [ ] Write (PUT)
 - [ ] Read (GET)

Reference https://github.com/coreos/etcd/tree/master/Documentation/benchmarks

**Comment by xiang90** [comment]
I do not think we need CPU and watch. We only need a simple bench about PUT + Memory and Get.

**Comment by gyuho** [comment]
@xiang90 Ok. Will just benchmark PUT/GET with memory usage for performance.md.
