### ISSUE TITLE
Old data being returned in response to v2 wait api call using waitIndex

### ISSUE THREAD

**Issue by sycal** [coreos/etcd#5442]
[etcd-corruption.zip](https://github.com/coreos/etcd/files/279723/etcd-corruption.zip)

Had this issue on version 2.3.2 of etcd, but am also now seeing it on version 2.3.4.
Essentially all was working ok for a day or so of testing, then I started getting spurious data being returned from a wait v2 api call (with a lower index that the waitIndex passed into the wait call).

This zip contains the data files and a python script "demoissue.py" which demonstrates the issue. The output should be similar to the following:

`$ ./demoissue.py`
`{u'createdIndex': 11270, u'modifiedIndex': 11270, u'nodes': [{u'createdIndex': 11272, u'modifiedIndex': 11272, u'value': u'v1', u'key': u'/components/resultslive/rl1'}], u'dir': True, u'key': u'/components/resultslive'}`
`Waiting from index=11271`
`{u'action': u'set', u'node': {u'createdIndex': 10569, u'modifiedIndex': 10569, u'value': u'{"timestamp":1464082470.7153270245,"ref":"f586eb4e-8721-e69b-b080-27474860_2","data":null}', u'expiration': u'2016-05-24T09:35:30.752422783Z', u'key': u'/components/resultslive/f586eb4e-8721-e69b-b080-27474860_2', u'ttl': 60}}`

Here, we set some node data into '/components/resultslive/rl1', then read from '/components/resultslive' and use the returned modifiedIndex + 1 to do a subsequent 'wait' call. This returns straight away, but rather than returning the data for the previous write, it returns old data (index 10569).

If the etcd data files are deleted, then everything works as it should and returns the newly written child node.

**Comment by xiang90** [comment]
which python library do you use? do you use the ttl refresh feature?

**Comment by xiang90** [comment]
OK. I examined the WAL you provided and confirmed the issue. Got a fix at #5448.

**Comment by sycal** [comment]
Thanks for jumping on this so quickly.
