### ISSUE TITLE
”refresh key + watch“ brings some strange problems

### ISSUE THREAD

**Issue by johnyannj** [coreos/etcd#5460]
# NORMAL CASE:

curl http://192.168.22.161:2379/v2/keys/watchKey -XPUT -d value=bar
{"action":"set","node":{"key":"/watchKey","value":"bar","modifiedIndex":4,"createdIndex":4}}

curl -v http://192.168.22.161:2379/v2/keys/watchKey

< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 4
< X-Raft-Index: 74
< X-Raft-Term: 2
< Date: Thu, 26 May 2016 05:22:37 GMT
< Content-Length: 93
<
{"action":"get","node":{"key":"/watchKey","value":"bar","modifiedIndex":4,"createdIndex":4}}

curl http://192.168.22.161:2379/v2/keys/watchKey -XPUT -d value=bar2

{"action":"set","node":{"key":"/watchKey","value":"bar2","modifiedIndex":5,"createdIndex":5},"prevNode":{"key":"/watchKey","value":"bar","modifiedIndex":4,"createdIndex":4}}

curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=5'
{"action":"set","node":{"key":"/watchKey","value":"bar2","modifiedIndex":5,"createdIndex":5},"prevNode":{"key":"/watchKey","value":"bar","modifiedIndex":4,"createdIndex":4}}
curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=5'
{"action":"set","node":{"key":"/watchKey","value":"bar2","modifiedIndex":5,"createdIndex":5},"prevNode":{"key":"/watchKey","value":"bar","modifiedIndex":4,"createdIndex":4}}
curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=5'
{"action":"set","node":{"key":"/watchKey","value":"bar2","modifiedIndex":5,"createdIndex":5},"prevNode":{"key":"/watchKey","value":"bar","modifiedIndex":4,"createdIndex":4}}

erverything is ok.

# ERROR CASE:

now do this:

curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d value=bar -d ttl=60
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true
curl http://192.168.22.161:2379/v2/keys/foo -XPUT -d ttl=60 -d refresh=true -d prevExist=true

then do:

curl -v http://192.168.22.161:2379/v2/keys/watchKey

< Content-Type: application/json
< X-Etcd-Cluster-Id: 7e27652122e8b2ae
< X-Etcd-Index: 8
< X-Raft-Index: 625
< X-Raft-Term: 2
< Date: Thu, 26 May 2016 05:27:07 GMT
< Content-Length: 94
<
{"action":"get","node":{"key":"/watchKey","value":"bar2","modifiedIndex":5,"createdIndex":5}}

curl http://192.168.22.161:2379/v2/keys/watchKey -XPUT -d value=bar3
{"action":"set","node":{"key":"/watchKey","value":"bar3","modifiedIndex":14,"createdIndex":14},"prevNode":{"key":"/watchKey","value":"bar2","modifiedIndex":5,"createdIndex":5}}

curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=9'
curl: (52) Empty reply from server

curl http://192.168.22.161:2379/v2/keys/watchKey -XPUT -d value=bar4
{"action":"set","node":{"key":"/watchKey","value":"bar4","modifiedIndex":15,"createdIndex":15},"prevNode":{"key":"/watchKey","value":"bar3","modifiedIndex":14,"createdIndex":14}}

curl -v http://192.168.22.161:2379/v2/keys/watchKey

< X-Etcd-Index: 16
< X-Raft-Index: 440
< X-Raft-Term: 2
< Date: Thu, 26 May 2016 05:36:29 GMT
< Content-Length: 96
<
{"action":"get","node":{"key":"/watchKey","value":"bar4","modifiedIndex":15,"createdIndex":15}}

same time do:  curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=17'  and 	curl http://192.168.22.161:2379/v2/keys/watchKey -XPUT -d value=bar5

watch return:
{"action":"set","node":{"key":"/watchKey","value":"bar5","modifiedIndex":17,"createdIndex":17},"prevNode":{"key":"/watchKey","value":"bar4","modifiedIndex":15,"createdIndex":15}}

continue do again:

curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=17' 

curl: (52) Empty reply from server

curl 'http://192.168.22.161:2379/v2/keys/watchKey?wait=true&waitIndex=17' 

curl: (52) Empty reply from server

**Comment by johnyannj** [comment]
version 2.3.0 to 2.3.5

**Comment by xiang90** [comment]
see https://github.com/coreos/etcd/pull/5448
