### ISSUE TITLE
waitIndex for rarely updated keys

### ISSUE THREAD

**Issue by DanielYWoo** [coreos/etcd#5466]
We have two keys, foo/x and foo/y. We are updating a key like **foo/x** periodically, and we are also watching a key like **/foo/y** which almost never change.
After a couple of hours we see watching on **/foo/y** returns 401 error because etcd only keeps 1000 recent events (we have updated **/foo/x** 1000 times).

According to the api doc, when watching we should use Etcd-Index+1 (or modifiedIndex+1) for the next waitIndex. But, since **/foo/y** is not changed, the watch will never return, how can I know the most recent waitIndex for **/foo/y**?

Currently I set "--proxy-read-timeout" as 10 seconds, so every 10 seconds the watch on **/foo/y** has a chance to see etcd-index from the response header and increase the waitIndex. But, is this the *etcd way* to do that?

I am confused because the doc does not suggest using "--proxy-read-timeout", it says 

> Don't change this value if you use watches because they are using long polling requests

How can I get the latest index for a rarely updated key then?

**Comment by xiang90** [comment]
v2 API really sucks at this. There is no way to do it in v2. Sorry.

In v3, we add a new concept called progress notification. So even if there is no events, etcd will make progress for that watcher and send notification. If you want, you can add similar features into v2 with a feature flag to enable it.

**Comment by xiang90** [comment]
I do not think anyone has interests in making this working for v2, so I am closing it. As I mentioned, this feature is already available for v3.
