### ISSUE TITLE
V3 error detecting is difficult

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#5481]
A number of public API's return errors, which is very useful, however it is difficult or impossible to match on errors without importing lots of packages or often is only possible with string parsing. Visually the errors are fine, but I'd like to programatically detect things and respond accordingly.

I wish I had an exhaustive list, but I don't. The latest example was:

    _, err := MemberRemove(context.Background(), mID)

err is NOT a

    etcdserver/membership ErrIDNotFound

as I would have expected. I also tried a

    etcdserver/api/v3rpc/rpctypes ErrGRPCMemberNotFound

after I searched through the code.

Turned out %T says it's an

    rpctypes.EtcdError

I eventually had to

    e, ok := err.(rpctypes.EtcdError)
    e.Code() == codes.NotFound ...

I really hope there is a better way, or that someone could consider something for the code base. Some other types of errors are actually private, therefore matching is actually impossible without string parsing.

I'm also happy to contribute some code to this effort if someone wants to help guide it.

Thanks!

**Comment by xiang90** [comment]
@purpleidea 

I am wondering if you read the doc here: https://github.com/coreos/etcd/blob/master/clientv3/README.md#error-handling?

**Comment by xiang90** [comment]
Also the doc here: https://godoc.org/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes#pkg-variables
listed all possible client-side errors.

**Comment by purpleidea** [comment]
@xiang90 I've seen this, however it's not clear at least to me how to match on any of those errors. Only on the codes. Maybe I could submit a doc update if you could let me know?

**Comment by purpleidea** [comment]
(Perhaps those only apply to KV, in my example I was using the MemberRemove API for example, which didn't seem to match on rpctypes.Foo...)

**Comment by xiang90** [comment]
@purpleidea I do not quite understand actually. Why do not want to match the code instead of doing a direct match like err == rpctypes.ErrEmptyKey. For your case, why not do err == ErrMemberNotFound? The codes are from gRPC. For our client library, we want to hide gRPC details as much as possible.

**Comment by purpleidea** [comment]
Ah, I'm sorry, I somehow missed the wrapped client versions of the gPRC errors. My bad for hacking at 2am. Perhaps this is a bad example. I'll close and make a new issue next time I hit a private error.

**Comment by purpleidea** [comment]
@xiang90 Is this type of error worthy of a new issue?

*errors.errorString: listen tcp 127.0.0.1:2386: bind: address already in use

not public API afaict. many others that are *errors.errorString too.

**Comment by gyuho** [comment]
All errors defined with Go built-in error type will have that errorString type. And bind already use error is not an etcd error.

**Comment by purpleidea** [comment]
@gyuho Good point, sorry.

How about this one: still type: *errors.errorString
error text is: "rpc error: code = 13 desc = raft: stopped"
What is the recommended way to match on it?

**Comment by gyuho** [comment]
@purpleidea No problem.

Regarding `raft: stopped`, try https://github.com/coreos/etcd/blob/master/raft/node.go#L35?

**Comment by purpleidea** [comment]
Thanks! I was starting to get the hang of this until... one more...

```
grpc.rpcError: rpc error: code = 13 desc = etcdserver: server stopped
```

This doesn't match etcdserver.ErrStopped unfortunately.

**Comment by gyuho** [comment]
For that I think you need to `grpc.ErrorDesc(err) == etcdserver.ErrStopped.String()`

**Comment by purpleidea** [comment]
@gyuho That didn't work since there isn't a .String() method for error, but this did work (similar error):

	grpc.ErrorDesc(err) == fmt.Sprintf("%s", grpc.ErrClientConnClosing)

So the rule I have in my head is if it's a grpc type error, wrap it in the ErrorDesc method, and then string compare...

If there's a better way to do this, please let me know! Also, perhaps this grpc wrapping rule should be added to the docs section. If you agree, let me know and I'll send a patch.

**Comment by gyuho** [comment]
@purpleidea Right. I meant `.Error()` method https://golang.org/pkg/builtin/#error
