### ISSUE TITLE
Etcd V3 is missing PrevNode feature

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#5496]
I'm porting some etcd V2 code to V3. In watch events there was the concept of PrevNode:

eg:
```
response.Node and response.PrevNode
```

This was useful to track changes easily. Is there an equivalent in V3? If not, are there any recommendations on how to emulate the behaviour?

Thanks!

**Comment by gyuho** [comment]
You can range with revision to get previous value.

**Comment by xiang90** [comment]
> If not, are there any recommendations on how to emulate the behaviour?

Use a txn that gets the key first, then do a delete/put.

Also this is a dup of https://github.com/coreos/etcd/issues/4620.

I would suggest you read https://github.com/coreos/etcd/blob/master/Documentation/op-guide/v2-migration.md#migrate-client-library and search the existing issues. It might save you some time. Thanks.

**Comment by purpleidea** [comment]
Interesting, how would this work? When you get your response, you'd have to
initiate a Get to get that information, right? Or is there a way to do this
without having to execute an additional request per incoming event?

**Comment by xiang90** [comment]
@purpleidea I think I have told you how to do it. Use a txn with one get and one write/delete requests. For example, see https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd3/store.go#L169-L182

**Comment by purpleidea** [comment]
@xiang90 I sent that previous message before getting your initial reply. GH email has a long processing delay for both sending and receiving, sorry.

**Comment by purpleidea** [comment]
@xiang90 I didn't know about this guide till now. Looks like it's brand new in git master. Thanks for the Txn tip, I wrote a patch to fix the ordering issue. Good idea! https://github.com/coreos/etcd/pull/5497

**Comment by purpleidea** [comment]
As an aside, while transactions are nice, they don't actually solve this problem for watch events AFAIK. When you receive the events, there's no way to have it also contain the previous revision without adding another call. If i'm mistaken, please let me know.
