### ISSUE TITLE
New Txn Member Ops

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#5500]
I love the V3 Txn API. Works great! I'd like to know if it can be extended to support MemberAdd/Remove/List Ops too? I think this would be an excellent feature!

Thanks!

**Comment by gyuho** [comment]
Sounds too complicated to support atomic member operations, roll backs, etc... 

@xiang90 @heyitsanthony should have better ideas.

**Comment by purpleidea** [comment]
On Tue, May 31, 2016 at 2:44 PM, Gyu-Ho Lee <notifications@github.com>
wrote:

> Sounds too complicated to support atomic member operations, roll backs,
> etc...
>
> @xiang90 <https://github.com/xiang90> @heyitsanthony
> <https://github.com/heyitsanthony> should have better ideas.
>


Could be. I don't know about the internals, but from a programmers point of
view it would be immensely helpful :) Thanks for your consideration.

**Comment by xiang90** [comment]
@purpleidea Probably not. etcd/raft implements the simplified version of configuration changes protocol. It is not worth the effort to make it transactional in most the cases due to the significant complexity we need to deal with.
