### ISSUE TITLE
can we make the tls version configurable?

### ISSUE THREAD

**Issue by magicwang-cn** [coreos/etcd#5501]
now, etcd accepts tls's connection with low version(`TLS1.0`), see [this](https://github.com/coreos/etcd/blob/master/pkg/transport/listener.go#L187),can we make this configurable? because TLS1.0 has some security flaw.

**Comment by xiang90** [comment]
@gtank Opinions?

**Comment by xiang90** [comment]
SSLv3 -> POODLE and BEAST
TLSv1.0 -> POODLE and BEAST using CBC cipher
TLSv1.1 -> RC4 cipher usage

I think probably we should bump default to TLS 1.2 directly instead of making it configurable.

**Comment by gtank** [comment]
I agree with @xiang90. Since we control both endpoints here there's actually not any reason to allow most of the negotiation options in TLS. If we can afford to (check compatibility + perfomance) then we should use something like

```
// Note: in the wild this pretty much only works for talking to Google
var tightTLSConfig = tls.Config{
    RootCAs: nil, // be explicit about using system bundle
    CipherSuites: []uint16{
        tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
        tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    },
    MinVersion:               tls.VersionTLS12,
    CurvePreferences: []tls.CurveID{
        tls.CurveP256,
        tls.CurveP384,
    },
}
```

**Comment by magicwang-cn** [comment]
@xiang90 @gtank ,thanks for your apply. since it is a simple modify for this, then will it be a patch or just support in the master branch?
