### ISSUE TITLE
Compilation error in generated c++ rpc.pb.h

### ISSUE THREAD

**Issue by mauiarches** [coreos/etcd#5504]
Hi,

I got a following compilation error in rpc.pb.h
rpc.pb.h:1110:9: error: ‘etcdserverpb::RequestUnion::RequestUnion’ has the same name as the class in which it is declared
   union RequestUnion {

Generated RequestUnion:
class RequestUnion : public ::google::protobuf::Message {
...
  union RequestUnion {
    RequestUnion() {}
    ::etcdserverpb::RangeRequest* request_range_;
    ::etcdserverpb::PutRequest* request_put_;
    ::etcdserverpb::DeleteRangeRequest* request_delete_range_;
  } request_;
...
}

Based on rpc.proto RequestUnion is defined like this:
message RequestUnion {
  // request is a union of request types accepted by a transaction.
  oneof request {
    RangeRequest request_range = 1;
    PutRequest request_put = 2;
    DeleteRangeRequest request_delete_range = 3;
  }
}

Can someone share how to solve this issue?

**Comment by gyuho** [comment]
Yeah I've seen this before when I tried to generate proto with official protobuf https://github.com/golang/protobuf. And etcd uses https://github.com/gogo/protobuf. etcd might have to change the name, or take it out of message struct. I will play around to see if I can fix it.

Thanks for reporting.

**Comment by gyuho** [comment]
@mauiarches Actually, this looks like your C++ protobuf generator issue (`‘etcdserverpb::RequestUnion::RequestUnion’ has the same name as the class ...`).

Could you report this to the upstream? Thanks.

Please feel free to reopen this if you still think it's an etcd issue.

**Comment by mauiarches** [comment]
Hi,

I wrote in protobuf github and there is an error on how requestUnion is declared in rpc.proto(https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto)

See the discussion in protobuf github here:
https://github.com/google/protobuf/issues/1637#issuecomment-223087430

See also how oneof is declared here:
https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#oneof

We need to change "oneof request" to "oneof oneof_request"

So i would like to reopen this issue.

**Comment by gyuho** [comment]
@mauiarches Thanks for reporting. I will try that.

**Comment by gyuho** [comment]
I tried it and works fine for me. I just remove `gogo/proto` parts and run `protoc --cpp_out=. *.proto`. How do you generate proto files using `rpc.proto`?

Also tried to change the name with prefix `oneof_` and it requires a lots of changes and complicated naming (https://github.com/coreos/etcd/pull/5549).

If you want to look at the proto files that I generated, please download this file

[etcdserverpb.tar.gz](https://github.com/coreos/etcd/files/298136/etcdserverpb.tar.gz)

**Comment by gyuho** [comment]
Please let me know if you still think this is an etcd issue. Then I will re-open it.

Closing for now.

**Comment by mauiarches** [comment]
Hi,

There is no problem with the rpc.proto generation. However when you try to use rpc.pb.h in your program then the c++ compilation occurs as I've described above.

**Comment by gyuho** [comment]
@mauiarches I see. We tried to change the naming as here https://github.com/coreos/etcd/pull/5549. Just changing the name of it would solve that issue? Sorry, I haven't run the C++ code. I just know that proto generates fine.

**Comment by mauiarches** [comment]
Yeah. I tried it on my machine and changing the name resolves the compilation error. Please take note that we should also double check other unions declared in rpc.proto if it will generate the same compilation errors.

**Comment by gyuho** [comment]
```bash
etcdserverpb $ g++ -std=c++11 rpc.pb.cc 
In file included from rpc.pb.cc:5:0:
rpc.pb.h:1095:9: error: ‘etcdserverpb::RequestUnion::RequestUnion’ has the same name as the class in which it is declared
   union RequestUnion {
         ^
rpc.pb.h:1216:9: error: ‘etcdserverpb::ResponseUnion::ResponseUnion’ has the same name as the class in which it is declared
   union ResponseUnion {
         ^
rpc.pb.h: In member function ‘void etcdserverpb::RequestUnion::clear_request_range()’:
rpc.pb.h:7440:21: error: request for member ‘request_range_’ in ‘((etcdserverpb::RequestUnion*)this)->etcdserverpb::RequestUnion::request_’, which is of non-class type ‘int’
     delete request_.request_range_;
                     ^
rpc.pb.h: In member function ‘const etcdserverpb::RangeRequest& etcdserverpb::RequestUnion::request_range() const’:
rpc.pb.h:7447:19: error: request for member ‘request_range_’ in ‘((const etcdserverpb::RequestUnion*)this)->etcdserverpb::RequestUnion::request_’, which is of non-class type ‘const int’
       ? *request_.request_range_
                   ^
rpc.pb.h: In member function ‘etcdserverpb::RangeRequest* etcdserverpb::RequestUnion::mutable_request_range()’:
rpc.pb.h:7454:14: error: request for member ‘request_range_’ in ‘((etcdserverpb::RequestUnion*)this)->etcdserverpb::RequestUnion::request_’, which is of non-class type ‘int’
     request_.request_range_ = new ::etcdserverpb::RangeRequest;
              ^
rpc.pb.h:7457:19: error: request for member ‘request_range_’ in ‘((etcdserverpb::RequestUnion*)this)->etcdserverpb::RequestUnion::request_’, which is of non-class type ‘int’
   return request_.request_range_;
                   ^
rpc.pb.h: In member function ‘etcdserverpb::RangeRequest* etcdserverpb::RequestUnion::release_request_range()’:
rpc.pb.h:7463:51: error: request for member ‘request_range_’ in ‘((etcdserverpb::RequestUnion*)this)->etcdserverpb::RequestUnion::request_’, which is of non-class type ‘int’
     ::etcdserverpb::RangeRequest* temp = request_.request_range_;

...
```

Yeah I am getting the same errors. Changing the name in our proto files is trivial, but requires some possible breaking changes.

What do you think? Any better suggestion?

/cc @xiang90 @heyitsanthony

**Comment by mauiarches** [comment]
Hi,

What are the breaking changes you are pertaining to? Is it interface changes? For me renaming oneof is the most straightforward one since we don't have control how the code is generated.

**Comment by gyuho** [comment]
@mauiarches Sorry, I was unclear. I was talking about breaking changes for etcd internal package. For client side, it won't break anything, I think.

I will try to fix this issue this week.

Thanks for reporting.

**Comment by mauiarches** [comment]
@gyuho , thanks!
