### ISSUE TITLE
Readme example need a fix

### ISSUE THREAD

**Issue by mkumatag** [coreos/etcd#5516]
In README.md says : 
ETCDCTL_API=3 etcdctl put mykey "this is awesome"

which is wrong, when I execute I got following error 

[root@jupiter-vm1164 ~]# ETCDCTL_API=3 etcdctl put mykey "this is awesome"
No help topic for 'put'
[root@jupiter-vm1164 ~]#

so above command needs a modification to set as following
ETCDCTL_API=3 etcdctl set mykey "this is awesome"

**Comment by heyitsanthony** [comment]
@mkumatag `set` is for v2. What is your `etcdctl --version`?

**Comment by mkumatag** [comment]
@heyitsanthony 

[root@jupiter-vm1164 ~]# etcdctl --version
etcdctl version 2.3.6
[root@jupiter-vm1164 ~]# 

seems like I've 2.3.6.

**Comment by mkumatag** [comment]
put works fine with v3.0.0-beta.0
