### ISSUE TITLE
etcd v3: add a grpc-gateway endpoint

### ISSUE THREAD

**Issue by philips** [coreos/etcd#5525]
To make it possible, although potentially not comfortable, for folks to interact with etcd v3 we should provide an HTTP + JSON interface to the v3 API. The easiest way to do this is to add a grpc-gateway in front of our gRPC API.

We can probably just steal code from here and put it into our mux: https://coreos.com/blog/gRPC-protobufs-swagger.html

I am OK putting this behind some endpoint like `/v3alpha/` or something

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/pull/5669
