### ISSUE TITLE
go client Compile error

### ISSUE THREAD

**Issue by evildecay** [coreos/etcd#5531]
### etcd 2.3.6 client compile error 
```
..\..\..\golocal\src\github.com\coreos\etcd\client\keys.generated.go:136: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
..\..\..\golocal\src\github.com\coreos\etcd\client\keys.generated.go:136: too many errors
```
go version 1.6.2

**Comment by heyitsanthony** [comment]
@evildecay it seems the code is building against an old version of the github.com/ugorji/go/codec package, try updating or using etcd's vendored packages?

**Comment by evildecay** [comment]
@heyitsanthony update codec from github.com/ugorji/go to compile success! thanks! etcd v3.6.2 release source package compile error, please update release version source.
