### ISSUE TITLE
NFS v4 Locking Leads to EBADF on Initial Startup

### ISSUE THREAD

**Issue by fwiesel** [coreos/etcd#5537]
Hi,

I am trying to get etcd (v2.3.6) to run with its data dir on an NFS v4 mount. The directory is empty.
This however fails with the error: `etcdserver: open wal error: bad file descriptor`.
This applies at least also to etcd v2.3.1.

An strace seems to indicate, that etcd is trying to get an exclusive lock on a file, which has been opened in read-only mode, which is apparently not possible on NFSv4, since it is emulated with `fcntl`, which requires [write rights](
https://git.devuan.org/CenturionDan/util-linux/blob/caf1ba11a367ad702fb774653daf9ebdcca49d7b/sys-utils/flock.c#L253).

But for me it looks strange, as I read the etcd code, the only place where it _tries_ to get a lock is when 
it opens a file in [write-only mode](https://github.com/coreos/etcd/blob/310ebdd3e15c073606a91f8786de96ed1508f904/wal/wal.go#L176), while in the part where it opens it for reading, no lock seems to explicitly acquired.

The strace is as follows:
```
openat(AT_FDCWD, "/var/lib/kubelet/pods/aee1fed5-2895-11e6-ac84-d2f798530d4e/volumes/kubernetes.io~nfs/pv-020/member/wal", O_RDONLY|O_CLOEXEC) = 8
getdents64(8, /* 3 entries */, 4096)    = 112
getdents64(8, /* 0 entries */, 4096)    = 0
close(8)                                = 0
openat(AT_FDCWD, "/var/lib/kubelet/pods/aee1fed5-2895-11e6-ac84-d2f798530d4e/volumes/kubernetes.io~nfs/pv-020/member/wal/0000000000000000-0000000000000000.wal", O_RDONLY|O_CLOEXEC) = 8
openat(AT_FDCWD, "/var/lib/kubelet/pods/aee1fed5-2895-11e6-ac84-d2f798530d4e/volumes/kubernetes.io~nfs/pv-020/member/wal/0000000000000000-0000000000000000.wal", O_RDONLY|O_CLOEXEC) = 9
flock(9, LOCK_EX|LOCK_NB)               = -1 EBADF (Bad file descriptor)
write(2, "2016-06-02 08:21:40.424460 C | e"..., 792016-06-02 08:21:40.424460 C | etcdserver: open wal error: bad file descriptor
) = 79
```

Thanks for your attention,
  Fabian

P.S: It seems also odd to me, that the file is opened twice.

**Comment by heyitsanthony** [comment]
@fwiesel is this on a linux kernel <3.15? etcd needs OFD locks for NFS

a lock call should look like:
```
fcntl(7, F_OFD_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
```

**Comment by SchwarzM** [comment]
it's on coreos stable

**Comment by heyitsanthony** [comment]
@SchwarzM @fwiesel OK, I see the problem. The OFD support for NFS locking didn't make it to 2.3.x, but it's in 3.0-beta.

**Comment by fwiesel** [comment]
Ah, I see, we will give it as spin. Thanks for the quick response.
