### ISSUE TITLE
tmpfs: create wal error: interrupted system call

### ISSUE THREAD

**Issue by mfojtik** [coreos/etcd#5558]
When using the `tmpfs` as the data-dir for etcd, the result is:

```
C0603 17:10:17.795926 347 raft.go:296] 2016/06/3 17:10:17 etcdserver: create wal error: interrupted system call
```

I saw a recent changes to fallocate() done here: https://github.com/coreos/etcd/pull/4785
This might be a regression. (this is a RHEL7 with `3.10.0-229.7.2.el7.x86_64` kernel)

@heyitsanthony FYI

**Comment by mfojtik** [comment]
@heyitsanthony do you know if there is an easy workaround to restore the old behavior?

**Comment by heyitsanthony** [comment]
@mfojtik it's a kernel bug-- http://marc.info/?l=linux-mm&m=146271329001929&w=2

**Comment by mfojtik** [comment]
@heyitsanthony is there a simple way to workaround this? I'm thinking something like:

```go
func preallocExtend(f *os.File, sizeInBytes int64) error {
	// use mode = 0 to change size
	err := syscall.Fallocate(int(f.Fd()), 0, 0, sizeInBytes)
	if err != nil {
		errno, ok := err.(syscall.Errno)
		if !ok {
			return err
		}
		switch errno {
		// treat not support and interrupted (running on tmpfs) as nil error
		case syscall.ENOTSUP, syscall.EINTR:
			return preallocExtendTrunc(f, sizeInBytes)
		}
	}
	return err
}
```

**Comment by smarterclayton** [comment]
I assume that it will take a while for the kernel bug to propagate to all systems - in the meantime, anyone on those older kernels would no longer be able to use tmpfs (if you were using a ephemeral etcd, like we do in Kube for events)

**Comment by heyitsanthony** [comment]
@mfojtik I have another fix in mind. Would you happen to know what is interrupting fallocate? I've only seen fallocate interruption in our stress tests.

**Comment by mfojtik** [comment]
@heyitsanthony I don't :-( I can reproduce this consistently in local VM and in AWS.

**Comment by heyitsanthony** [comment]
@mfojtik ok I put up a PR which falls back on EINTR to truncate() like you suggested, let me know if it works

**Comment by mfojtik** [comment]
@heyitsanthony perfect, thanks!
