### ISSUE TITLE
Clientv3: Watches stop working permanently after Close()

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#5568]
I'm experiencing what I'm pretty sure must be some sort of strange etcd bug. I've tried with both current git master, as well as a commit right after https://github.com/coreos/etcd/issues/5495 was fixed.

What happens:

I startup one server, and a client that connects to it. It runs some watches. Then I startup a second client and connect it to the first server. It then runs some watches too. Then I startup a second server and have it join the cluster. At this point I'd like for client two to also know about the new endpoint (server 2). This would be nice natively as #5491, but in the meantime let's emulate it. I then run a Close() on client 2's connection, and then try and Connect again.

It seems that whenever I do a Close() it causes all existing watches to go crazy. They report events repeatedly, but in particular: 

* response.Canceled == false
* response.Err() == nil
* response.Header.Revision == 0

The last one is particularly mysterious! Unfortunately, they continue to spawn events, and this never ends. Fine, however, even after the new Connect() happens they still spawn these empty events...

If anyone could recommend some things to try or has seen something similar, I'd appreciate the help.

It's also worth pointing out that this issue is probably a blocker for: https://github.com/coreos/etcd/issues/5491 which I am encountering by attempting to emulate that feature.

**Comment by purpleidea** [comment]
Actually please hold off on investigating, I think this might be related to re-using of a context... I'm investigating. If anyone has information related to that sort of thing and how it might manifest itself, please let me know. Thanks!

**Comment by heyitsanthony** [comment]
@purpleidea `Close()` on what? `Watcher.Close()` and `Client.Close()` will close all associated watch channels (that response data looks like it's reading from a closed channel).

**Comment by purpleidea** [comment]
AFAICT, this bug was due to a mistake on my part:

The issue: if you use a certain context (call it ctx) and then you Close() and then You Connect a brand new connection, but reuse ctx for the Watch, then it causes this error. It's probably worth mentioning this somewhere if you think it's useful information. It wasn't obvious to me anyhow.

Sorry for the noise, hopefully this is useful info.
