### ISSUE TITLE
etcdctl(version3) watch command does not accept range_end

### ISSUE THREAD

**Issue by saxenaks** [coreos/etcd#5575]
In rpc.proto, WatchCreateRequest is defined as follows  :
message WatchCreateRequest {
  // key is the key to register for watching.
  bytes key = 1;
  // range_end is the end of the range [key, range_end) to watch. If range_end is not given,
  // only the key argument is watched. If range_end is equal to '\0', all keys greater than
  // or equal to the key argument are watched.
  bytes range_end = 2;
  // start_revision is an optional revision to watch from (inclusive). No start_revision is "now".
  int64 start_revision = 3;
  // progress_notify is set so that the etcd server will periodically send a WatchResponse with
  // no events to the new watcher if there are no recent events. It is useful when clients
  // wish to recover a disconnected watcher starting from a recent known revision.
  // The etcd server may decide how often it will send notifications based on current load.
  bool progress_notify = 4;
}

This specifies that range_end can be specified for watch request. However etcdctl command does have support to specify range_end :
NAME:
	watch - Watch watches events stream on keys or prefixes.

USAGE:
	etcdctl watch [key or prefix]

OPTIONS:
  -i, --interactive[=false]	interactive mode
      --prefix[=false]		watch on a prefix if prefix is set
      --rev=0			revision to start watching

It allows user to specify whether key is a prefix, however no such variable in available in WatchCreateRequest. So there is gap between what etcdctl supports vs what is specified in rpc.proto.

To me it looks like a bug. Please correct me if I am wrong.

**Comment by xiang90** [comment]
This is not a bug, it is a lack of feature. We have not implemented range in etcdctl watch command yet.

For prefix, it is just a range request with key, key+1 (https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L169-L170). So, there is no gap.

**Comment by saxenaks** [comment]
Agreed this is an enhancement and not a bug.

I did not understand your comment on range request. You will use WatchCreateRequest to create a watch. Correct? How is the boolean value of "prefix" captured in WatchCreateRequest?

**Comment by heyitsanthony** [comment]
@saxenaks the prefix request is converted into a range. See https://github.com/coreos/etcd/blob/master/clientv3/op.go#L189

**Comment by saxenaks** [comment]
Got it. Thanks!
