### ISSUE TITLE
Client Set returns ErrClusterUnavailable but succeeds

### ISSUE THREAD

**Issue by xh4n3** [coreos/etcd#5577]
Hi, I'm using KeysAPI provided by the client v2 library to Get some keys and Set them if not exist.
When I build and run the code in the gist immediately after starting etcd in a localhost Docker container, it returns
https://gist.github.com/xh4n3/c5207ff5dd63886a4e5f2b4a8b00a404
```
2016/06/07 22:31:51 job.go:58: 100: Key not found (/test) [1]
2016/06/07 22:31:52 job.go:62: client: etcd cluster is unavailable or misconfigured
2016/06/07 22:31:52 job.go:71: 100: Key not found (/test) [1]
2016/06/07 22:31:53 job.go:75: 102: Not a file (/test) [3]
```
Above we can see, the key was not found at first, and the Set command was fired, but returns an ErrClusterUnavailable error. A second Get still return a Not found error, but when a second Set applied, it tells the key is already there.

When I put a time sleep in the middle of two Gets, the second Get returns the correct key.

I think if the etcd would continue to Set the key, it shouldn't return an ErrClusterUnavailable.

Is this by design or I did something wrong? Please let me know.

**Comment by xiang90** [comment]
@xh4n3 Can you fix the gist?

**Comment by xh4n3** [comment]
@xiang90 Done.

**Comment by xiang90** [comment]
```
2016/06/07 19:51:20 etcdt.go:58: 100: Key not found (/test) [3]
2016/06/07 19:51:20 etcdt.go:79: <nil>
exit status 1
```

I tried your program. It works fine for me. The output is exactly what I would expect. How to reproduce the issue you mentioned?

**Comment by xh4n3** [comment]
Just tested it with v2.3.6 etcd, it works, probably I should upgrade my etcd to latest. Seems like a resolved issue?

Here is my script to reproduce this in v2.0.8 etcd, ./etcd is the compiled gist.

Thanks!

```
#!/bin/bash -x

HostIP=192.168.0.144

docker rm -f etcd > /dev/null 2>&1 || true

docker run -d -v /usr/share/ca-certificates/:/etc/ssl/certs -p 4001:4001 -p 2380:2380 -p 2379:2379  --name etcd quay.io/coreos/etcd:v2.0.8  -name etcd0  -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001  -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001  -initial-advertise-peer-urls http://${HostIP}:2380  -listen-peer-urls http://0.0.0.0:2380  -initial-cluster-token etcd-cluster-1  -initial-cluster etcd0=http://${HostIP}:2380  -initial-cluster-state new

./etcd
```
