### ISSUE TITLE
Does etcd keep order by event occur order when send watch event?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#5592]
I watch a key, and delete and add. etcd will send two event. Does these two event message order is same to operation order? Is it possible add message arrive first?

**Comment by xiang90** [comment]
etcd preserves the event ordering. 

> Does these two event message order is same to operation order?

Yes.

> Is it possible add message arrive first?

No, unless there is a bug.

**Comment by inksink** [comment]
@xiang90   But how to understand :

> etcd does not ensure linearizability for watch operations. Users are expected to verify the revision of watch responses to ensure correct ordering.

from https://coreos.com/etcd/docs/latest/learning/api_guarantees.html  

thx.
