### ISSUE TITLE
Test case fails on Fedora without ptmx patch

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#5593]
Many tests fail on Fedora (and apparently CentOS, RHEL, etc...) due to the kr/pty library.

The upstream issue is:

https://github.com/kr/pty/issues/21#issuecomment-224487979

I manually patched my local version to use `/dev/pts/ptmx` instead of `/dev/ptmx` and everything worked.

**Comment by heyitsanthony** [comment]
@purpleidea I tried to reproduce this on a fresh fedora24 VM and the e2e pty tests work fine. Fedora seems to have an issue with the test certs, though. Closing.

**Comment by purpleidea** [comment]
On Tue, Jun 21, 2016 at 9:54 PM, Anthony Romano <notifications@github.com>
wrote:

> @purpleidea <https://github.com/purpleidea> I tried to reproduce this on
> a fresh fedora24 VM and the e2e pty tests work fine. Fedora seems to have
> an issue with the test certs, though. Closing.



I have only tested on F23. Glad to hear it seems to be working in F24 :)
