### ISSUE TITLE
etcd ACI signature should be armored instead of binary

### ISSUE THREAD

**Issue by lucab** [coreos/etcd#5594]
According to ACI spec, `Image archives SHOULD be signed using PGP, the format MUST be ascii-armored detached signature mode`.

Up to etcd v2.3.6, `.aci.asc` file is a binary signature (despite the extension). As per https://github.com/coreos/rkt/issues/2581 rkt is currently a bit loose on that, but we plan to start warning on non-armored signatures.

Would you mind moving to armor signatures for ACIs? I think the "binary signature in .asc file" is also a bit confusing, but I'm not sure if it's there on purpose; would you like a small amendent/PR against your release guide?

**Comment by xiang90** [comment]
@lucab 

The release guide is here: https://github.com/coreos/etcd/blob/master/Documentation/dev-internal/release.md.

It would be helpful if you can send a PR.
