### ISSUE TITLE
[feature] option to return only keys from v3 "etcdctl get"

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#5611]
Currently when I do `ETCDCTL_API=3 etcdctl get --prefix /`, it returns both keys and values.
I will want to have better control over this, like returning only keys, returning keys and versions.
The other option is to use etcd client library to write a program to do this. But programming and compiling took a lot of time :)
It would be great if etcdctl can provide options to control the output.

**Comment by ajityagaty** [comment]
@xiang90 As we receive the `GetResponse` object can we just filter the output based on what the user has asked for (like `--keys` or `--values` or `--with-version`). If we are to just filter the `GetResponse` object then this would make sense for `SimplePrinter` only right? For JSON and protobuf the user will have access to the `GetResponse` object and they can filter it themselves.

**Comment by xiang90** [comment]
@ajityagaty I think we'd better to do this in the server-side. People would like to avoid huge traffic going through decoding + network path.

**Comment by ajityagaty** [comment]
@xiang90 Yes, makes sense. Would it be ok if I look at it?

**Comment by xiang90** [comment]
@ajityagaty Sure. Go ahead. Thanks! Probably we want to add a optional field in the range request (no_value or only_key).

**Comment by ajityagaty** [comment]
@xiang90 Thanks! Will look into it.

**Comment by ajityagaty** [comment]
@xiang90 I was looking at the changes that I'll have to make. The `RangeRequest` will have a flag to indicate "keys only". If the flag is set then in `kvServer.Range` method, after reading the keys from the store, would it be enough if we set the `Value` field of every `mvccpb.KeyValue` to nil?

**Comment by xiang90** [comment]
@ajityagaty That is how I would expect it to work.
