### ISSUE TITLE
functional-tester: simulate stresser with real-world use cases

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5618]
Current functional-tester only writes to the cluster (etcd-tester with stresser, local-tester with benchmark put). But this doesn't simulate all the real-world use cases. Workloads to etcd should include:

- write
- delete
- read
- optional: watch, lock, lease

**Comment by heyitsanthony** [comment]
It'd be nice if it could use tools/benchmark to generate the load so that the functional-tester isn't on another planet, but I understand it may not be easy to do this with the current functional-tester design.

**Comment by gyuho** [comment]
Yeah... right now they don't share any code. Maybe we can implement `benchmark stress` command for `benchmark`. I will work on etcd-tester part.

Thanks.

**Comment by heyitsanthony** [comment]
@gyuho the benchmarks are already stress tests so it wouldn't need additional commands-- the functional tester would use what's there to generate load

**Comment by gyuho** [comment]
Yeah right, we can just use different commands.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/5626.
