### ISSUE TITLE
functional-tester: continuous tester prometheus metrics count

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5627]
Current problem is whenever we redeploy testing cluster, we reset all the metrics in tester (number of rounds, cases, etc.).

I asked Grafana mailing list if there's any way to use previous metrics data to make Grafana graphs continuous, even after prometheus redeployment, because Grafana stores some historical data on disk. 

And response was:

> Grafana does not store any data itself it only saves to query that's being used to query Prometheus.

Which means it only stores the results of the query, and there's no way to count the prometheus metrics continuously with the previous deployment. We could just write the metrics count to disk, and read it back when the tester restarts.

**Comment by chancez** [comment]
I believe you can handle this with prometheus. For counts you use Increase() https://prometheus.io/docs/querying/functions/#increase(). If your calculating an average, rate() does the same too.

However, be sure to read the note if your using rate():
> Note that when combining rate() with an aggregation operator (e.g. sum()) or a function aggregating over time (any function ending in _over_time), always take a rate() first, then aggregate. Otherwise rate() cannot detect counter resets when your target restarts.

**Comment by gyuho** [comment]
@chancez Thanks for looking it up.

I once tried `sum` but didn't work. `increase` seems like what we want.

`increase(etcd_funcational_tester_round_total[9999h])`

![screenshot from 2016-07-02 14-36-15](https://cloud.githubusercontent.com/assets/6799218/16542562/65b76df4-4062-11e6-8fc4-9ff55a38b961.png)

I will match those numbers next week if it's accurate.

**Comment by gyuho** [comment]
Confirmed that query `increase(etcd_funcational_tester_round_total[1y])` gives what we want. It's running the query for every refresh, so it's a bit slow, though.

But for now, it's good enough.

Will work on detailed information on failure cases later.

Thanks Chance!
