### ISSUE TITLE
pacing between apply routine and raft routine

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5628]
The previous assumption was apply routine can alway run faster than raft routine. So there should not be a lot of entries that are pending for apply.

Now etcd3 support l-range and delete-range query, which can be expensive to apply.

We definitely do not want raft replication to overload etcd server apply loop. Apply loop need to feedback to raft when raft goes too fast.

**Comment by heyitsanthony** [comment]
@xiang90 would the fix be as simple as having a scheduler that blocks if overloaded instead of pure FIFO? If raft floods etcd then writes to etcd's apply channel will block and therefore force raft processing to stall.

**Comment by xiang90** [comment]
@heyitsanthony Could be. Ultimately, we need the pacing between API layer and raft too. Probably we need to think about this a little bit more carefully.

**Comment by xiang90** [comment]
@heyitsanthony We cannot drop any raft entries if raft already accepts it. We can drop API layer requests though.
