### ISSUE TITLE
Hard to set ETCDCTL_API for etcdctl in Docker image

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5653]
Current `etcdctl` reads environment variable `ETCDCTL_API` to decide which version to run.

The problem is that 

```
docker run --name etcd quay.io/coreos/etcd:v3.0.0
ETCDCTL_API=3 docker exec etcd /etcdctl put foo bar
```

won't work.

Currently there's no easy way to set environment variables inside container, as far as I know.

We need to resolve or document this when we release `v3.0.0`.

**Comment by heyitsanthony** [comment]
It seems like people get around this with something like:
```
docker exec etcd /bin/bash -c "export ETDCCTL_API=3 &&  /etcdctl put foo bar"
```
but that assumes bash is available in the container and it's unwieldy.

An alternative could be shipping the container with a `etcdctl3` that will run etcdctl with `ETCDCTL_API=3`.

**Comment by gyuho** [comment]
Yeah separate binary with `etcdctl3` sounds good, or ship a bash script or executable `/bin/bash` for those workarounds. Currently, we only ship `etcd` and `etcdctl` binaries, nothing else.

**Comment by xiang90** [comment]
@gyuho @heyitsanthony 

```
docker exec -e "ETCDCTL_API=3" etcd /etcdctl put foo bar
```

wont work?

**Comment by xiang90** [comment]
Sorry you need to do docker run -e ...

**Comment by gyuho** [comment]
Yeah people set env for `exec` with bash script file inside container. There seems to be no easy way now...

**Comment by xiang90** [comment]
@gyuho So shall we just close this one? And in the docker example, add the `/bin/bash -c "export ETDCCTL_API=3 &&` thing? We control the container image anyway.

**Comment by gyuho** [comment]
Sure, I will include bash script to enable that starting in the v3 releases.

**Comment by gyuho** [comment]
*We will update the documentation about how to run v3 ctl in the next release.
