### ISSUE TITLE
Will etcdctl3 still support backup?

### ISSUE THREAD

**Issue by xinxiaogang** [coreos/etcd#5665]
Saw this https://github.com/coreos/etcd/issues/4896.

My questions are:
- Will etcdctl3 still support backup? I could not see backup command code under etcdctl3.
- What's the main purpose of snapshot/recover in #4896? What's the different with backup?

**Comment by xiang90** [comment]
Snaphost = backup: check out https://github.com/coreos/etcd/blob/master/etcdctl/README.md#snapshot-subcommand
