### ISSUE TITLE
v3 ONLY has support for protobuf? json gone for good?

### ISSUE THREAD

**Issue by cdancy** [coreos/etcd#5668]
While I understand the change and all its benefits just wondering if json is going out the window entirey for v3?

**Comment by gyuho** [comment]
Think this is addressed in this issue https://github.com/coreos/etcd/issues/5525?

**Comment by xiang90** [comment]
@cdancy There will be json support for languages that do not have grpc support yet. https://github.com/coreos/etcd/pull/5669

**Comment by cdancy** [comment]
@gyuho @xiang90 thanks. I'm the owner of [etcd-rest](https://github.com/cdancy/etcd-rest) and we use jclouds in the backend for communicating with etcd v2 api. I was looking to start prototyping the v3 api but jclouds does not currently have support for this which is why I asked.

**Comment by xiang90** [comment]
@cdancy The v3 JSON API is not that restful. It is more like a JSON rpc over HTTP.

**Comment by cdancy** [comment]
@xiang90 fair enough. That's better than nothing and something I can more easily cope with than trying to coerce that library into producing protobuf data which may be more work than it's worth.

**Comment by cdancy** [comment]
@xiang90 is there, or do you guys plan on, putting together any documentation for the v3 json API? Perhaps it's similar enough to v2 or at least follows the same semantics that changing the version endpoint is all that is necessary?

**Comment by xiang90** [comment]
@cdancy We do not have an API specification for v2 API. The doc is the walk through of the etcd features using API. We have a specification style doc for gRPC API at  https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md. 

We might generate similar thing for the current JSON/HTTP based RPC too. But do not expect us to provide API usage examples in JSON in short term.

**Comment by cdancy** [comment]
@xiang90 the "v2 API doc walk through" was what I was referring to. It was good enough for me to fully build out an http based client and was wondering if there was something planned for v3.

If and when you guys have something going I'd be more than happy to look over your docs and flesh them out a bit more if only for my own purposes. I've written quite a few java based clients now for http API's and would be more than happy to help out and write things in such a way as to make it easier for others like myself to code against.

Just let me know as I love the project, use it heavily, and have 2 projects, [etcd-rest](https://github.com/cdancy/etcd-rest) and [gradle-etcd-rest-plugin](https://github.com/cdancy/gradle-etcd-rest-plugin), and more than happy/willing to contribute back upstream if I can.

**Comment by philips** [comment]
@xiang90 are we generating and publishing the swagger / open APIs document for the grpc-gateway?

**Comment by philips** [comment]
@cdancy @xiang90 Filed a bug to add docs for this: https://github.com/coreos/etcd/issues/5686

**Comment by cdancy** [comment]
Sounds good and thanks.
