### ISSUE TITLE
vendor: gRPC, proto-gen would complain about grpc.SupportPackageIsVersion2

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#5671]
```
../etcdserver/etcdserverpb/rpc.pb.go:1995: undefined: grpc.SupportPackageIsVersion2
```

With latest gRPC dependency, it will complain about this (https://github.com/grpc/grpc-go/commit/e78224b060cf3215247b7be455f80ea22e469b66)

**Comment by jwierzbo** [comment]
I get same error on  `go get github.com/coreos/etcd/clientv3`
