### ISSUE TITLE
Documentation: grpc-gateway documentation

### ISSUE THREAD

**Issue by philips** [coreos/etcd#5686]
A short doc that covers the following:

- [X] Explains the grpc-gateway functionality at a high level and its use case (languages that don't have gRPC)
- [X] How to use the endpoint, curl/bash is fine
- [X] Shows where the swagger document is

**Comment by philips** [comment]
This was introduced in https://github.com/coreos/etcd/pull/5669

**Comment by gyuho** [comment]
Next week, we will set up a simple web site to serve API docs. Something like http://kubernetes.io/kubernetes/third_party/swagger-ui/.

**Comment by xiang90** [comment]
I think we can close this issue now. The hosted API thing is an enhancement.
