### ISSUE TITLE
etcdmain: listen tcp [::1]:2380: socket: address family not supported by protocol

### ISSUE THREAD

**Issue by wynnfynn** [coreos/etcd#5691]
I disabled ipv6 in ubuntu14.04, i want to use ipv4 , but etcd can not start with 

/opt/bin/etcd  -name infra -addr 10.100.xx.xx:4001  -bind-addr 0.0.0.0:4001 -data-dir /var/lib/etcd/

Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
/opt/bin/etcd --version
etcd Version: 2.3.1
Git SHA: 2b67f52
Go Version: go1.5.3
Go OS/Arch: linux/amd64

strace 

futex(0xc820034590, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
mmap(0xc820200000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc820200000
mmap(0xc81ffe8000, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc81ffe8000
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820034590, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0x13eda90, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820060110, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820034590, FUTEX_WAKE, 1)      = 1
futex(0xc820034a10, FUTEX_WAKE, 1)      = 1
futex(0xc820034590, FUTEX_WAKE, 1)      = 1
futex(0xc820034590, FUTEX_WAKE, 1)      = 1
openat(AT_FDCWD, "/etc/localtime", O_RDONLY) = 3
read(3, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\3\0\0\0\3\0\0\0\0"..., 4096) = 405
read(3, "", 4096)                       = 0
close(3)                                = 0
write(2, "2016-06-16 11:49:51.591501 I | e"..., 612016-06-16 11:49:51.591501 I | etcdmain: etcd Version: 2.3.1
) = 61
write(2, "2016-06-16 11:49:51.592754 I | e"..., 582016-06-16 11:49:51.592754 I | etcdmain: Git SHA: 2b67f52
) = 58
write(2, "2016-06-16 11:49:51.593004 I | e"..., 612016-06-16 11:49:51.593004 I | etcdmain: Go Version: go1.5.3
) = 61
write(2, "2016-06-16 11:49:51.593248 I | e"..., 652016-06-16 11:49:51.593248 I | etcdmain: Go OS/Arch: linux/amd64
) = 65
write(2, "2016-06-16 11:49:51.593494 I | e"..., 1142016-06-16 11:49:51.593494 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
) = 114
openat(AT_FDCWD, "/var/lib/etcd/", O_RDONLY|O_CLOEXEC) = 3
getdents64(3, /* 2 entries */, 4096)    = 48
getdents64(3, /* 0 entries */, 4096)    = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/nsswitch.conf", O_RDONLY|O_CLOEXEC) = 3
read(3, "# /etc/nsswitch.conf\n#\n# Example"..., 1024) = 475
read(3, "", 1024)                       = 0
close(3)                                = 0
openat(AT_FDCWD, "/etc/resolv.conf", O_RDONLY|O_CLOEXEC) = 3
read(3, "nameserver 172.16.40.1\n# Dynamic"..., 4096) = 222
read(3, "", 3874)                       = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
stat("/etc/mdns.allow", 0xc8200dc480)   = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/hosts", O_RDONLY|O_CLOEXEC) = 3
read(3, "127.0.0.1 SN-201606-05\t\n\n# The f"..., 4096) = 269
read(3, "", 3827)                       = 0
read(3, "", 4096)                       = 0
close(3)                                = 0
socket(PF_INET6, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
write(2, "2016-06-16 11:49:51.601048 C | e"..., 1132016-06-16 11:49:51.601048 C | etcdmain: listen tcp [::1]:2380: socket: address family not supported by protocol
) = 113
exit_group(1)                           = ?
+++ exited with 1 +++

**Comment by xiang90** [comment]
Can you pass in the etcd log startup? From the strace, it seems like etcd tried to listen on an ipv6 addr "[::1]:2380". And you disabled ipv6, so that kernel complaints. Did you set any environments for etcd?

**Comment by gyuho** [comment]
@wynnfynn As Xiang said, the etcd log indicates that it still tries to listen to ipv6 address. Can you check `env | grep "ETCD"` to see you have any environmental variables?

Also I tried the same version of etcd and it works fine with ipv6

```
./etcd --listen-peer-urls "http://[::]:2380"
```

I am also running ubuntu 14.04. Kernel version is 3.19.0-51.

**Comment by gyuho** [comment]
@wynnfynn Ping?

**Comment by gyuho** [comment]
Closing this. Please fill free to ping us if you still have issues.
