### ISSUE TITLE
e2e: mismatched etcd versions for rolling upgrades

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5697]
Partially in response to #5696, where a missing field from an older version crashes the newer etcd. Right now there's no infrastructure for testing configurations with mismatched etcd server versions.

This case could be covered to some extent by having all e2e tests with more than one member run (either by default or some configuration option) some members on the last stable release and the rest on the current branch.

**Comment by gyuho** [comment]
This is good. We only do once right before the release. It would be great if we do this for every e2e test runs, going forward with v3 releases.

**Comment by xiang90** [comment]
closed by https://github.com/coreos/etcd/issues/5697
