### ISSUE TITLE
etcv3: high value of mvcc_pending_events_total

### ISSUE THREAD

**Issue by nekto0n** [coreos/etcd#5717]
Hi!
I have etcd (from master) ensemble with 5 members and 5 clients. Each client sets up 2 watches (which is correctly reported in `mvcc_watcher_total`) and starts updating keys / receiving events. I think I manage to have some clients consistently staggering, i.e. last seen index from watch stream is increasing, but lags behind other clients.
While investigating I found that `etcd_debugging_mvcc_pending_events_total` shows numbers like `77812` and slowly increases. Lurking through sources I found that this gauge is decremented only in one place (which is `mvcc.ReportEventReceived()`) and decrement value is always one. Strangely this value is incremented in several places with number of events (`pendingEventsGauge.Add(float64(len(eb.evs)))`). Is it intended?
Is non-zero `pending_events_total` a sign of something going wrong in my installation?

**Comment by xiang90** [comment]
@nekto0n There is probably a bug somewhere. Will investigate. And the meantime, you can try to play with light watch load to see if the counter behaves correctly. If not, you can try to figure out what is happening and send us a pull request to fix it!

**Comment by nekto0n** [comment]
Fixed version is running for over an hour and gauge is `0`. I guess we can assume issue is fixed.

**Comment by xiang90** [comment]
> starts updating keys / receiving events. I think I manage to have some clients consistently staggering, 

How do you manage to do this? Do you think this is also an etcd issue? I manage to make some watcher slower but that requires some high workload to slow down both watcher and etcd server.

**Comment by nekto0n** [comment]
> How do you manage to do this? Do you think this is also an etcd issue?

Not quite sure. Every client is a server, which
- receives updates and `put`s them into etcd.
- starts watch which continuously  updates in-memory index for web UI to query and saves last seen `revision`

UI polls servers via balancer which uses round-robin. And I can see that some instances return outdated information (UI jitters). If I restart such instance, then it lists keys and starts watching correctly.

Maybe there is a problem on my side. I am investigating it, by adding logging and metrics.

>I manage to make some watcher slower but that requires some high workload to slow down both watcher and etcd server.

Load is moderate, maybe 200 rps (put requests). What happens to watches, that have slow receivers? Is there an upper bound of pending events after which watch would seize to serve and return an error?

**Comment by xiang90** [comment]
> What happens to watches, that have slow receivers?

etcd will put these watchers into a slow watch list. etcd will periodically check the list and tries to deliver events in a batch for better throughput.  

>  Is there an upper bound of pending events after which watch would seize to serve and return an error?

No. etcd will always try its best until the requested key revision is compacted.
