### ISSUE TITLE
auth v3: revision aware permission checking

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#5719]
Current permission checking mechanism of auth v3 does not care about revision of KV. It means if a user is granted a permission of `/k`, the user can access any revision of `/k`. It would not enough for permission checking of multi version storage system like etcd. auth v3 should be revision aware in the near future.

/cc @xiang90 @heyitsanthony

**Comment by xiang90** [comment]
Actually I do not think we need to have pre revision permission.

I was talking about adding revision control for username, password combination.

Basically, we need to invalid tokens if the password of the user changes.

**Comment by mitake** [comment]
@xiang90 I see. Then can we close this issue after https://github.com/coreos/etcd/pull/5793 is merged?

**Comment by xiang90** [comment]
@mitake Yes. We should.
