### ISSUE TITLE
api v3 calls doesn't work

### ISSUE THREAD

**Issue by jwierzbo** [coreos/etcd#5726]
I use api v2 client in golang to do standard GET/SET/DELETE calls, which works fine, but I have problem with v3 client which returns me following error all the time:
`context deadline exceeded`

I've tried to verify v3 endpoints using etcdctl, but problem still exists (v2 calls works fine):
`>> ETCDCTL_API=3 ./etcdctl  put foo bar`
Returns:
`No help topic for 'put'`

In my OS ports 2382 and 4001 are in use, so I'm using following command to run etcd server:
`./etcd --listen-peer-urls=http://localhost:2382 --advertise-client-urls http://localhost:2379 -listen-client-urls=http://localhost:2379
`

Any thoughts?

**Comment by gyuho** [comment]
@jwierzbo You would need to run https://github.com/coreos/etcd/tree/release-2.3/etcdctlv3 if you run etcd 2.3.x.

Or I recommend to run etcd and etcdctl from our master branch.

Thanks.

**Comment by jwierzbo** [comment]
I've binary pointed in documentation:
`curl -L  https://github.com/coreos/etcd/releases/download/v2.3.6/etcd-v2.3.6-linux-amd64.tar.gz -o etcd-v2.3.6-linux-amd64.tar.gz`

so etcdctlv3  can fix problem with CLI client but what about with golang v3 api (github.com/coreos/etcd/clientv3)?

**Comment by gyuho** [comment]
Did you try `clientv3` in release-2.3 branch or master branch? The v3 code and binaries in 2.3.6 was pre-alpha, which means it might contain a lot of bugs. But if you just want to try out, either 2.3.6 or master branch should work, although master branch clientv3 code is much more stable.

Thanks.

**Comment by jwierzbo** [comment]
Everything works fine with version from master branch.
@gyuho thanks for help!
Closing

**Comment by gyuho** [comment]
np!
