### ISSUE TITLE
ETCD cluster unavailble intermittently.

### ISSUE THREAD

**Issue by maverick-racheal** [coreos/etcd#5746]
I am trying to bring up a Kuberenetes Master with ETCD in clustered mode. The etcd cluster is brought up using discovery url and has 3 members. Once the cluster is setup and the leader is elected, we are seeing intermittent connection loss with one of the members. 

Logs
{"log":"2016-06-21 08:38:22.828340 I | raft: cc62d2c6a48fa5f6 became follower at term 5\n","stream":"stderr","time":"2016-06-21T08:38:22.828674403Z"}
{"log":"2016-06-21 08:38:22.828354 I | raft: cc62d2c6a48fa5f6 [logterm: 3, index: 30, vote: 0] voted for c623ae22731206f [logterm: 3, index: 31] at term 5\n","stream":"stderr","time":"2016-06-21T08:38:22.828699568Z"}
{"log":"2016-06-21 08:38:22.836032 D | raft: cc62d2c6a48fa5f6 [logterm: 0, index: 31] rejected msgApp [logterm: 3, index: 31] from c623ae22731206f\n","stream":"stderr","time":"2016-06-21T08:38:22.836403569Z"}
{"log":"2016-06-21 08:38:22.836074 I | raft: raft.node: cc62d2c6a48fa5f6 elected leader c623ae22731206f at term 5\n","stream":"stderr","time":"2016-06-21T08:38:22.836422772Z"}
{"log":"2016-06-21 08:38:23.992333 D | etcdhttp: [GET] /v2/keys/coreos.com/network/subnets?recursive=true\u0026wait=true\u0026waitIndex=11 remote:127.0.0.1:37352\n","stream":"stderr","time":"2016-06-21T08:38:23.99250607Z"}
{"log":"2016-06-21 08:38:28.502640 I | rafthttp: the connection with aa4358db9106fdec became inactive\n","stream":"stderr","time":"2016-06-21T08:38:28.503181225Z"}
{"log":"2016-06-21 08:38:28.502704 E | rafthttp: failed to read aa4358db9106fdec on stream Message (read tcp 10.18.3.134:42070-\u003e10.18.3.135:4000: i/o timeout)\n","stream":"stderr","time":"2016-06-21T08:38:28.503268783Z"}
{"log":"2016-06-21 08:38:28.502877 E | rafthttp: failed to read aa4358db9106fdec on stream MsgApp v2 (read tcp 10.18.3.134:42068-\u003e10.18.3.135:4000: i/o timeout)\n","stream":"stderr","time":"2016-06-21T08:38:28.503282736Z"}
{"log":"2016-06-21 08:38:29.803291 E | rafthttp: failed to dial aa4358db9106fdec on stream Message (dial tcp 10.18.3.135:4000: i/o timeout)\n","stream":"stderr","time":"2016-06-21T08:38:29.803524397Z"}
{"log":"2016-06-21 08:38:29.803676 E | rafthttp: failed to dial aa4358db9106fdec on stream MsgApp v2 (dial tcp 10.18.3.135:4000: i/o timeout)\n","stream":"stderr","time":"2016-06-21T08:38:29.803851584Z"}
{"log":"2016-06-21 08:38:30.294227 I | rafthttp: the connection with aa4358db9106fdec became active\n","stream":"stderr","time":"2016-06-21T08:38:30.294787627Z"}
{"log":"2016-06-21 08:38:30.665300 I | raft: cc62d2c6a48fa5f6 [term: 5] ignored a MsgApp message with lower term from aa4358db9106fdec [term: 2]\n","stream":"stderr","time":"2016-06-21T08:38:30.665619804Z"}
 
Around the same time the K8 labels are being set from Kuberenetes master and the same fails with the following error

+ kubectl -s http://IP:8080 label node VM <Role>=<mgmt>
Error from server: client: etcd cluster is unavailable or mis configured

/ # etcd --version
etcd Version: 2.2.1
Git SHA: 75f8282
Go Version: go1.5.1
Go OS/Arch: linux/amd64

It looks to be same as #5210 but wanted to confirm.

**Comment by xiang90** [comment]
There are quite a few transportation related improvements since 2.2.1. But from the log, I still suspect that it was caused by connectivity issues between your machines. 

Please try with the etcd 2.3.7 to see if you can reproduce it. Reopen if you can, then we will be happy to look into the issue. Thanks!

**Comment by maverick-racheal** [comment]
One more point to note is that just after the member is added to the cluster, we try to update the flannel configuration.

++ curl -s -w '%{http_code}' -m 10 -L http://127.0.0.1:4001/v2/keys/coreos.com/network/subnets/ -o /dev/null
+ status=000
+ '[' 000 -eq 200 ']'

+ docker -H unix:///var/run/docker-bootstrap.sock run --net=host etcd-amd64:2.2.1 etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16", "Backend": {"Type": "udp"}}'
Error:  client: etcd cluster is unavailable or misconfigured
The above happened at Tue Jun 21 08:37:32 UTC 2016 Set Host Flannel Subnet to 10.1.0.0/16 and tunnel to udp

Kuberenetes installation proceeds and around 2016-06-21 08:38:12.519663 Leader is lost and ETCD cluster elects a new leader.

**Comment by maverick-racheal** [comment]
Sure. Shall try with 2.3.7.  Is etcd 2.3.7 a stable release?

**Comment by gyuho** [comment]
@maverick-racheal Yes, `2.3.7` is the latest stable release.
