### ISSUE TITLE
etcd2 fails to start of two nodes in 3 node cluster

### ISSUE THREAD

**Issue by kanaskaa** [coreos/etcd#5759]
I have just started setting up CoreOS 3 node cluster on virtual Box.
followed instructions from https://coreos.com/os/docs/latest/booting-on-virtualbox.html

I have created 3 machines on virtual box corevm-6 , corevm-7 ,corevm-8
All three machines uses below cloud-config

#cloud-config

coreos:
  etcd2:
    name: corevm-6
    advertise-client-urls: http://127.0.0.1:2379,http://127.0.0.1:4001
    initial-advertise-peer-urls: http://127.0.0.1:2380
    discovery: https://discovery.etcd.io/2879ee5656dbc8da3a186ec482e8351d
    listen-peer-urls: http://127.0.0.1:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuD+DTwCvIuXn229E4mcnK1TL0Ptw505htJH3q6CcEyeoTGVV/Ju3imuWTD5HcTgYsehJnW9eYPYUAVmBr2w0cMd6po57em8BO5WBdMqgJYBCJZYOtWtqDSdEsSwOkNzkORhQqvye4bI0uxUB6mk+6beUjh **@*******
hostname: corevm-6

I started the first machines (corevm-6) and i cloud see etcd2 and fleet started but when i started rest 2 machines corevm-7 and corevm-8 i see below errors on both machines.

Starting etcd2...
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:2379,http://127.0.0.1:4001
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/2879ee5656dbc8da3a186ec482e8351d
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://127.0.0.1:2380
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://127.0.0.1:2380
Jun 23 15:09:10 corevm-7 etcd2[2332]: recognized and used environment variable ETCD_NAME=corevm-7
Jun 23 15:09:10 corevm-7 etcd2[2332]: etcd Version: 2.3.1
Jun 23 15:09:10 corevm-7 etcd2[2332]: Git SHA: 2b67f52
Jun 23 15:09:10 corevm-7 etcd2[2332]: Go Version: go1.5.3
Jun 23 15:09:10 corevm-7 etcd2[2332]: Go OS/Arch: linux/amd64
Jun 23 15:09:10 corevm-7 etcd2[2332]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Jun 23 15:09:10 corevm-7 etcd2[2332]: listening for peers on http://127.0.0.1:2380
Jun 23 15:09:10 corevm-7 etcd2[2332]: listening for client requests on http://0.0.0.0:2379
Jun 23 15:09:10 corevm-7 etcd2[2332]: listening for client requests on http://0.0.0.0:4001
Jun 23 15:09:12 corevm-7 etcd2[2332]: stopping listening for client requests on http://0.0.0.0:4001
Jun 23 15:09:12 corevm-7 etcd2[2332]: stopping listening for client requests on http://0.0.0.0:2379
Jun 23 15:09:12 corevm-7 etcd2[2332]: stopping listening for peers on http://127.0.0.1:2380
Jun 23 15:09:12 corevm-7 etcd2[2332]: member "corevm-7" has previously registered with discovery service token (https://discovery.etcd.io/2879ee5656dbc8da3a186ec482e8351d).
Jun 23 15:09:12 corevm-7 etcd2[2332]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).
Jun 23 15:09:12 corevm-7 etcd2[2332]: Please check the given data dir path if the previous bootstrap succeeded
Jun 23 15:09:12 corevm-7 etcd2[2332]: or use a new discovery token if the previous bootstrap failed.
Jun 23 15:09:12 corevm-7 systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Jun 23 15:09:12 corevm-7 systemd[1]: Failed to start etcd2.
Jun 23 15:09:12 corevm-7 systemd[1]: etcd2.service: Unit entered failed state.
Jun 23 15:09:12 corevm-7 systemd[1]: etcd2.service: Failed with result 'exit-code'.
Jun 23 15:09:22 corevm-7 systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.

Can anyone help whats the issue?

Thanks,
Akhil Kanaskar

**Comment by xiang90** [comment]
@kanaskaa 

your etcd servers should not advertise localhost like this

```
advertise-client-urls: http://127.0.0.1:2379,http://127.0.0.1:4001
initial-advertise-peer-urls: http://127.0.0.1:2380
```

Each etcd server should advertise different urls.

**Comment by kanaskaa** [comment]
So what should be the advertise url? What ip address?

**Comment by xiang90** [comment]
> So what should be the advertise url? What ip address?

I cannot figure this out for you. You need to know the IP addresses of the machines. It depends on how you config your vm.

**Comment by krish7919** [comment]
@kanaskaa You need to use the private_ipv4/public_ipv4 if working with vagrant/ec2/gce/digitalocean.
If you are doing this as a local standalone cluster, I am afraid you have to put in hardcoded IPs. I assign static IPs to the nodes where etcd is going to run apriori to configure this parameter correctly.

**Comment by xiang90** [comment]
@krish7919 Correct. Basically, users have to figure out the reachable ip address themselves. 

@kanaskaa If you feel this is a coreos related doc issue, please file a bug here: https://github.com/coreos/docs/issues
