### ISSUE TITLE
Values in rafthttp encode/decode

### ISSUE THREAD

**Issue by nekto0n** [coreos/etcd#5810]
Hi!
Found that `encode`/`decode` methods in `rafthttp` module accept/return `raftpb.Message` by value instead of by pointer:

```
func (enc *messageEncoder) encode(m raftpb.Message) error {
	if err := binary.Write(enc.w, binary.BigEndian, uint64(m.Size())); err != nil {
		return err
	}
	_, err := enc.w.Write(pbutil.MustMarshal(&m))
	return err
}
```
Seems like there is no need to pass object copy for encoding. Simple test like this:

```
func BenchmarkEncodeMemoryUsage(b *testing.B) {
	m := raftpb.Message{
		Type:    raftpb.MsgApp,
		From:    1,
		To:      2,
		Term:    1,
		LogTerm: 1,
		Index:   3,
		Entries: []raftpb.Entry{{Term: 1, Index: 4}},
	}
	b.ReportAllocs()
	buf := &bytes.Buffer{}
	enc := &messageEncoder{w: buf}
	for i:=0; i< b.N; i++ {
		enc.encode(m)
		buf.Reset()
	}
}
```
shows that passing pointer does show performance improvements if we pass pointer to encode:

```
benchmark                        old ns/op     new ns/op     delta
BenchmarkEncodeMemoryUsage-4     668           526           -21.26%

benchmark                        old allocs     new allocs     delta
BenchmarkEncodeMemoryUsage-4     4              3              -25.00%

benchmark                        old bytes     new bytes     delta
BenchmarkEncodeMemoryUsage-4     320           64            -80.00%

```

(I had to hack a little to make test work with pointers because changing interface here requires a lot of changes all over the code).

I'd like to work on pull request to move to pointers but not quite sure if this interface is accidental or it is intended.

**Comment by xiang90** [comment]
This is not intended. Probably you want to try larger values? In your test, there is no entries so the overhead is HUGE. But we can take this change anyway even if the performance gain is little.

**Comment by nekto0n** [comment]
Yep, you're right. Using 4kb byte slice as `.Data` reveals that gain is not that big

```
benchmark                        old ns/op     new ns/op     delta
BenchmarkEncodeMemoryUsage-4     2620          2363          -9.81%

benchmark                        old allocs     new allocs     delta
BenchmarkEncodeMemoryUsage-4     4              3              -25.00%

benchmark                        old bytes     new bytes     delta
BenchmarkEncodeMemoryUsage-4     4880          4624          -5.25%
```
I'll try to concoct a patch in a few days, thanks!

P.S. Playing with pointers in `.decode()` only makes things worse. Seems like compiler does a decent job optimizing extra copies.
