### ISSUE TITLE
support encrypting values in data store

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5816]
There have been requests to optionally encrypt values before writing them down to disk. Presumably most of this would be done at the API layer since the WAL entries can't be plaintext.

**Comment by xiang90** [comment]
@gtank Do you have any suggestion on how we should do this?

**Comment by gtank** [comment]
@xiang90 I don't really know enough about how etcd works to answer this. Systematically encrypting things is extermely application specific. For instance, what are WAL entries? Who would manage the keys, and what data should be protected from what potential readers? Should it be bound to access control?

**Comment by xiang90** [comment]
After an offline discussion with @gtank, we figured it out that etcd is probably not the best place to support encryption. We will coordinate with k8s people to see the next steps.
