### ISSUE TITLE
Please switch to versioned gopkg.in/cheggaaa/pb.v1

### ISSUE THREAD

**Issue by petercolberg** [coreos/etcd#5820]
The author of cheggaaa/pb recently begun tagging releases following semantic versioning (cheggaaa/pb#73). Could you please adapt the import path accordingly, by renaming/replacing

github.com/cheggaaa/pb → gopkg.in/cheggaaa/pb.v1

**Comment by gyuho** [comment]
@petercolberg Is there any specific reason to change the import path? `gopkg.in` was once down, and breaking our tests before. We already vendor with the version https://github.com/coreos/etcd/blob/master/cmd/Godeps/Godeps.json#L272-L273.

**Comment by gyuho** [comment]
Sorry, we already use `gopkg.in/cheggaaa/pb.v1`

**Comment by petercolberg** [comment]
I am sorry. I filed this exact issue three months ago (#4832).

**Comment by gyuho** [comment]
np.
