### ISSUE TITLE
docker guide in v3 release is unreachable. 

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#5831]
In [v3 release](https://github.com/coreos/etcd/releases/tag/v3.0.0), the docker guild 
https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md is unreachable.

**Comment by xiang90** [comment]
@gyuho can you fix this please?

**Comment by gyuho** [comment]
Sure fixing now.

**Comment by gyuho** [comment]
Just fixed. The correct link was https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker. (https://github.com/coreos/etcd/blob/release-3.0/Documentation/op-guide/container.md#docker for release 3.0)

Thanks a lot @siddontang
