### ISSUE TITLE
better failure handling during etcd2 -> etcd3 upgrades

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#5833]
When etcd2 sends snapshot to etcd3, etcd3 would expect a db snapshot which will not exist. 

Now etcd3 panics. This is usually not a problem when user ensures everything is OK before upgrading. But it would be a nice thing to have to make the upgrade process safer.

**Comment by pholbrook** [comment]
Can you say more about what symptoms you see when you say "Etcd3 panics?"

I was seeing a problem trying to upgrade test etcd V2 clusters today where I was getting an error message in the logs:

etcdmain: database file ('/var/etcd/member/snap/db) of the backend is missing.

I was wondering if this was related.

**Comment by xiang90** [comment]
@pholbrook This one is only for failure handling. The issue you mentioned is already fixed here: https://github.com/coreos/etcd/commit/ff55e5a1886af03586e4a18003c0b461edb92db3. 

We will do a fix release today.

**Comment by xiang90** [comment]
No one really reported/hit this. Very low priority. So closing.
