### ISSUE TITLE
clientv3: won't connect if any endpoint is down

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#5842]
How to reproduce: start one etcd server on `2379`, then `ETCDCTL_API=3 etcdctl put abc def`. It will fail to connect to `127.0.0.1:{2,3}2379` and never send the command.

**Comment by westhood** [comment]
Why not disable `grpc.WithBlock` ?  It seems `grpc` can handle connection issues like this automatically in the background if  `grpc.WithBlock` is disabled.

**Comment by heyitsanthony** [comment]
@westhood I think the code should confirm it can connect to some endpoint before returning a client, but non-blocking connect is a possible alternative.
