### ISSUE TITLE
Server crash - panic: not implemented 

### ISSUE THREAD

**Issue by tejohnso** [coreos/etcd#5856]
Empty object on a watch command brings down the server.

Running etcd Version: 3.0.1 from fresh download:

` curl -L http://localhost:2379/v3alpha/watch -d "{}"`

>panic: not implemented
>
>goroutine 211 [running]:
>panic(0xd44e00, 0xc821147220)
>        /usr/local/go/src/runtime/panic.go:481 +0x3e6
>github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*serverWatchStream).recvLoop(0xc8201916c0, 0x0, 0x0)
>        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:204 +0x940
>github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch.func2(0xc8211682a0, 0xc8201916c0)
>        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x21
>created by github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.(*watchServer).Watch
>        /home/gyuho/go/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/watch.go:126 +0x26d

**Comment by xiang90** [comment]
will fix shortly
