### ISSUE TITLE
Can't specify flags to etcd with docker

### ISSUE THREAD

**Issue by sctlee** [coreos/etcd#5858]
Is it a better choice using ENTRYPOINT instead of CMD in [Dockerfile-release](https://github.com/coreos/etcd/blob/master/Dockerfile-release)? 
#5771

**Comment by gyuho** [comment]
Closinv via https://github.com/coreos/etcd/pull/5876.

I tried `ENTRYPOINT` and confirmed that all docker commands in our etcd docs would work as same.

I will double-check in the next release.
