### ISSUE TITLE
Support for retrieving Lease details information?

### ISSUE THREAD

**Issue by fbdlampayan** [coreos/etcd#5868]
Hi!

With etcdv3, is there a way to retrieve existing lease information and/or lease "items" themselves on demand?

For example, we would want to know the TTL-equivalent values for the keys attached to a certain lease. Is there a way to retrieve these details?

In the file rpc.proto there are these comments in the Lease service...

> // TODO(xiangli) List all existing Leases?
> // TODO(xiangli) Get details information (expirations, leased keys, etc.) of a lease?

So was wondering if this is not yet supported and when is it planned to be supported.

**Comment by xiang90** [comment]
Can you provide more detailed use case? For example, you do you want to list the all the leases? Why do you want to get the expiry of a lease. Then we can consider to add the APIs.

**Comment by fbdlampayan** [comment]
Hi xiang!

Hmm basically is there a way to get TTL value from LeaseId currently in etcdv3?
In a nutshell, is there something like this:

> TTl ttlValue = etcdv3.RequestTtl(keyAssociatedWithALeaseId)

Where a client to etcdv3 can request the TTL associated with a key (or with a leaseId).



**Rationale/Use case:**
To be more specific, our current project's DNS-nature for announcement and service discovery is built on top of etcdv2.
And at the moment we are migrating/refactoring to utilize etcdv3.

With etcdv2, the Response struct's Node field has TTL. 
This TTL value is included to the DNS response back to the DNS client querying our side.

However with etcdv3, please correct me if I am wrong, improved the concept to Leases for this TTL-like information. 
But this TTL information can only be retrieved from etcdv3's Lease either through LeaseGrantResponse and LeaseKeepAliveResponse, these are returned by etcdv3 via Grant() and KeepAlive()
which are not actual "request" actions, rather more of "creation" actions.

So for this DNS-natured module, if it receives a DNS query whose information are stored in etcdv3, 
there seems to be no way now to know/fetch what's the TTL value for the key being queried... 
unless it is forced to Grant() or do KeepAlive(), but it will be intrusive and not query-like in nature.

**Comment by xiang90** [comment]
@fbdlampayan 

Just try to summary the use case:

The lease owner does not need to query TTL, since it creates the lease, keeps the lease alive.
However, there are other clients besides the lease owner want to query the TTL of the lease. Right? 

In your current project, here is no centralized server that can do information caching but fully rely on etcd to do information propagation and coordination?

**Comment by fbdlampayan** [comment]
@xiang90 

Yes, the other clients besides the lease owner requires to query the TTL of the lease and it fully relies on etcd.

**Comment by xiang90** [comment]
@fbdlampayan Added this as TODO. Also it would be great if you can contribute to this feature!
