### ISSUE TITLE
report snapshot finish cause process active false and check quorum causes leader step down.

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#5879]
Hi @xiang90 

When we open check quorum, after leader 1 send snapshot finished to follower 2, the report snapshot may cause 2 progress active to false. so in tickHeartbeat, before 1 sends heartbeat to 2, the check quorum may cause 1 step down, because now checkQuorumActive will return false. 

Although later 1 may become leader too, this is unnecessary. 

/cc @swingbach

**Comment by xiang90** [comment]
> When we open check quorum, after leader 1 send snapshot finished to follower 2, the report snapshot may cause 2 progress active to false. so in tickHeartbeat, 

Snapshot will not change the progress activity. The progress becomes inactive only if the follower does not response to the leader for the most recent election timeout.

While 1 sends the snapshot to 2, 1 should still send heartbeat messages. I suspect that your application somehow pause heartbeat sending while sending snapshot?

**Comment by siddontang** [comment]
No, if sending snapshot ok, the report snapshot finish will set progress active to false. 
So the leader may step down before sending heartbeat. 

Here https://github.com/coreos/etcd/blob/master/raft/raft.go#L730 may set progress to false. 
And here https://github.com/coreos/etcd/blob/master/raft/raft.go#L454 will cause leader to step down.

**Comment by xiang90** [comment]
OK. I see. We should fix this. Basically, not all state changes should cause active reset. I will try to find sometime this week or so.
