### ISSUE TITLE
Can etcd v3 GetResponse contains prevKv as Put/DeleteResponse do?

### ISSUE THREAD

**Issue by m1093782566** [coreos/etcd#5884]
I feel excited about etcd v3 supporting ` preKv` in the Put/DeleteResponse and Event, I think it's really useful. However, I find there is no `prevKv` in the `GetResponse`.

In etcd v2, I find `Response` for Get/Put/Delete requests all have `PrevNode` to represents the previous state of the Node. 

So I wonder if we can support prevKv(s) in etcd v3 `GetResponse`?  Because some clients might want to know the changes before he get the Kv.

Thanks!

**Comment by gyuho** [comment]
Did you try https://godoc.org/github.com/coreos/etcd/clientv3#WithRev?

**Comment by xiang90** [comment]
@m1093782566 Why get should have prevValue? It does not change the value. v2 does not support it either. There is no reason to support it.
