### ISSUE TITLE
etcd 3.0.1 can not run on centos7 and os x

### ISSUE THREAD

**Issue by inetkiller** [coreos/etcd#5893]
I installed etcd followed the guide(https://github.com/coreos/etcd/releases) ,when try etcdctl i got following error:
2016/07/07 03:49:25 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:2379: getsockopt: connection refused"; Reconnecting to {"127.0.
0.1:2379" <nil>}
Error:  grpc: timed out when dialing

**Comment by gyuho** [comment]
Can you share the `etcd` and `etcdctl` commands to reproduce this?

**Comment by inetkiller** [comment]
etcd:
```shell
curl -L https://github.com/coreos/etcd/releases/download/v3.0.1/etcd-v3.0.1-linux-amd64.tar.gz -o etcd-v3.0.1-linux-amd64.tar.gz
tar xzvf etcd-v3.0.1-linux-amd64.tar.gz
cd etcd-v3.0.1-linux-amd64
./etcd
```
etcdctl:
```shell
ETCDCTL_API=3 ./etcdctl put foo "bar"
ETCDCTL_API=3 ./etcdctl get foo
```

**Comment by gyuho** [comment]
Did you try that command in os x? Or centos?

**Comment by inetkiller** [comment]
I tryed both

**Comment by gyuho** [comment]
Please try `ETCDCTL_API=3 ./etcdctl --endpoints=localhost:2379 put foo bar`. It should work.

We will update the release notes.

**Comment by inetkiller** [comment]
it works. thx

**Comment by gyuho** [comment]
np!
