### ISSUE TITLE
Grant-permissions with wildcards in V3

### ISSUE THREAD

**Issue by sergeyfd** [coreos/etcd#5896]
Hello,

How can I grant permissions to all keys, or to keys wit a certain prefix, in V3 etcd to some role? I created a role with the following permissions:

```
Role etcd
KV Read:
	*
	[*, *)
	.*
	/*
	etcd
	etcd*
KV Write:
	*
	[*, *)
	.*
	/*
	etcd
	etcd*
```

But so far this role is only able to get/put `etcd` key and nothing else.

**Comment by xiang90** [comment]
we do not support widecard for auth right now. only explicit range is supported

**Comment by sergeyfd** [comment]
What is a range in this context?

**Comment by xiang90** [comment]
@sergeyfd Permission on a range of keys like from foo to foo10.

**Comment by sergeyfd** [comment]
But:

```
get etcd
Role etcd
KV Read:
	*
	[*, *)
	.*
	/*
	etcd
	etcd*
	[etcd0, etcd100)
KV Write:
	*
	[*, *)
	.*
	/*
	etcd
	etcd*
	[etcd0, etcd100)
```

```
-bash-4.2$ etcdctl --user etcd:etcd get etcd20
Error:  etcdserver: permission denied
```

**Comment by xiang90** [comment]
etcd20 is not in any range I think. etcd20 > etcd100.

**Comment by sergeyfd** [comment]
Kind of weird but Ok. get on etcd020 works. Thanks for the explanation.

**Comment by xiang90** [comment]
@sergeyfd Shall we close this issue? Or you still want the wide card support?

**Comment by sergeyfd** [comment]
Will you add it if I keep it open? :-)

If you have no plans for adding such support, then yes, it's Ok to close it.

**Comment by xiang90** [comment]
@sergeyfd We do not have plan. But if there is a strong use case, we might consider. If you think range can achieve what you want for now, we shall close it. Based on your reply, seems that range is good enough for you.

**Comment by sergeyfd** [comment]
I should be Ok for now. But I bet you that eventually you'll have to add that support.
