### ISSUE TITLE
Why does etcdctl assume that the endpoint is on port 22379, whereas etcd starts up on port 2379?

### ISSUE THREAD

**Issue by tebello-thejane** [coreos/etcd#5907]
Following the etcd README page, this happens:

    $ ./etcd
    ...
    2016-07-09 13:20:55.952752 I | etcdmain: listening for peers on http://localhost:2380
    2016-07-09 13:20:55.952778 I | etcdmain: listening for client requests on localhost:2379

but

    $ ETCDCTL_API=3 ~/etcd-v3.0.2-linux-amd64/etcdctl put mykey "this is awesome"
    2016/07/09 13:21:39 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:22379: getsockopt: connection refused"; Reconnecting to {"127.0.0.1:22379" <nil>}

The (I'm assuming default) port numbers are different from each other.

Is this a bug? At best it's a failing of the documentation.

**Comment by xiang90** [comment]
This is just for local cluster setup, which listens on 2379:22379:32379. We should probably make the default just 2379. Can you send a pull request to fix this?

**Comment by journeycheng** [comment]
today, i meet the same question as you.
when only enter etcdctl command, it returns HELP PAGE, information like this
`
./etcdctl
...
GLOBAL OPTIONS:
--endpoints value                a comma-delimited list of machine addresses in the cluster (default: "http://127.0.0.1:2379,http://127.0.0.1:4001")
`
Clearly write that listening on 2379 default, but the fact is (I think there is a bug.):
some people upgrade etcd from v2 to v3 on 1st, July facing the similar trouble, and the endpoints are
`
--endpoints=[127.0.0.1:2379,127.0.0.1:22379,127.0.0.1:32379]
`
it should listen on three endpoints

There are two ways may help you:
1. add --endpoints in etcdctl command:
`
$ etcdctl --endpoints=localhost:2379 put meykey "hello"
` 
it would return "OK".
2. or you can add other ports in etcl command:
`
$ etcd -listen-client-urls http://127.0.0.1:2379,http:127.0.0.1:22379,http:127.0.0.1:32379
`
