### ISSUE TITLE
clientv3: support sync membership of etcd cluster

### ISSUE THREAD

**Issue by westhood** [coreos/etcd#5920]
In client v2, we can use `client.Sync` or `client.AutoSync` to sync cluster membership.  Is there any plan to implement this feature in client v3 ?

**Comment by xiang90** [comment]
Yes. There is a plan. First we need to implement changing endpoints: https://github.com/coreos/etcd/issues/5491. Then we can add a simple monitor for loop to update the endpoints. Do you want to work on this?

**Comment by westhood** [comment]
Yes. I am glad to work on this. I will create a PR to fix #5491 first.

If my understanding is correct,  we need new a method `client.UpdateEndpoints` maybe for #5491.  I think it needs some modification on [balancer.go](https://github.com/coreos/etcd/blob/master/clientv3/balancer.go), which is related to #5845.

**Comment by xiang90** [comment]
correct
