### ISSUE TITLE
etcdhttp: etcdserver: request timed out, possibly due to previous leader failure

### ISSUE THREAD

**Issue by nshubhy** [coreos/etcd#5936]
Hi,

We have a 3 node etcd cluster and seeing this error on two nodes once the cluster has formed. This is one time error and later all the etcd write work. I also tried to run a script for infinite etcd write to see if I hit this error but all the writes were successful. Could you please help me understand the reason this error occurs and write fails?

**Comment by heyitsanthony** [comment]
@nshubhy what version of etcd is this? can you provide the etcd server logs with the error?

**Comment by heyitsanthony** [comment]
@nshubhy any updates?

**Comment by xiang90** [comment]
I am closing this due to the low activity. Reopen if you can provide more information.
