### ISSUE TITLE
Etcd publish error: etcdserver: request timed out

### ISSUE THREAD

**Issue by liuxiaopiao** [coreos/etcd#5940]
## Preparation:
1. Have 2 hosts: 10.244.201.121,10.244.201.122
2. ETCD version: 3.0.2

###  I used the below scripts to install etcd on master host 10.244.201.121:
cd /scratch
curl -L  https://github.com/coreos/etcd/releases/download/v3.0.2/etcd-v3.0.2-linux-amd64.tar.gz -o etcd-v3.0.2-linux-amd64.tar.gz
tar xzvf etcd-v3.0.2-linux-amd64.tar.gz
ln -s /scratch/etcd-v3.0.2-linux-amd64 /scratch/etcd
useradd -s /sbin/nologin -d /scratch/etcd-data -M etcd
mkdir /scratch/etcd-data
chown etcd /scratch/etcd-data
chmod 700 /scratch/etcd-data

cat >/etc/sysconfig/etcd <<EOF1
ETCD_DATA_DIR=/scratch/etcd-data
ETCD_NAME=docker-master
ETCD_ADVERTISE_CLIENT_URLS="http://10.244.201.121:2379,http://10.244.201.121:4001"
ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.244.201.121:2380"
ETCD_INITIAL_CLUSTER="docker-master=http://10.244.201.121:2380,docker-node1=http://10.244.201.122:2380"
ETCD_INITIAL_CLUSTER_STATE=new
EOF1

cat >/scratch/etcd/start-etcd <<EOF1
#!/bin/sh
export ETCD_INITIAL_CLUSTER_TOKEN=micropo3
exec /scratch/etcd/etcd > /tmp/etcd.log 2>&1
EOF1

cat >/usr/lib/systemd/system/etcd.service <<EOF1
[Unit]
     Description=Etcd
     After=syslog.target network.target
     [Service]
     User=etcd
     ExecStart=/scratch/etcd/start-etcd
     EnvironmentFile=-/etc/sysconfig/etcd
     KillMode=process
     Restart=always
     [Install]
     WantedBy=multi-user.target
EOF1

systemctl daemon-reload
systemctl enable etcd
systemctl start etcd

### After executing the above script, I checked "systemctl status -l etcd" and got the below output:
etcd.service - Etcd
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled)
   Active: active (running) since Wed 2016-07-13 23:38:29 PDT; 5min ago
 Main PID: 4649 (etcd)
   CGroup: /system.slice/etcd.service
           └─4649 /scratch/etcd/etcd

Jul 13 23:43:50 testVM etcd[4649]: 3d59df4b226e3e76 [logterm: 1, index: 2] sent vote request to 523049613b318fc7 at term 224
Jul 13 23:43:51 testVM etcd[4649]: 3d59df4b226e3e76 is starting a new election at term 224
Jul 13 23:43:51 testVM etcd[4649]: 3d59df4b226e3e76 became candidate at term 225
Jul 13 23:43:51 testVM etcd[4649]: 3d59df4b226e3e76 received vote from 3d59df4b226e3e76 at term 225
Jul 13 23:43:51 testVM etcd[4649]: 3d59df4b226e3e76 [logterm: 1, index: 2] sent vote request to 523049613b318fc7 at term 225
### Jul 13 23:43:52 testVM etcd[4649]: publish error: etcdserver: request timed out
Jul 13 23:43:52 testVM etcd[4649]: 3d59df4b226e3e76 is starting a new election at term 225
Jul 13 23:43:52 testVM etcd[4649]: 3d59df4b226e3e76 became candidate at term 226
Jul 13 23:43:52 testVM etcd[4649]: 3d59df4b226e3e76 received vote from 3d59df4b226e3e76 at term 226
Jul 13 23:43:52 testVM etcd[4649]: 3d59df4b226e3e76 [logterm: 1, index: 2] sent vote request to 523049613b318fc7 at term 226

### And the output of "etcdctl cluster-health" is like this:
etcdctl cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured
error #0: client: endpoint http://127.0.0.1:2379 exceeded header timeout
error #1: client: endpoint http://127.0.0.1:4001 exceeded header timeout

**Comment by biganan2012** [comment]
Hi 

Basically when you configure ETCD, please make sure that you have configured both master and slave machines. Otherwise, there will be problems.

***********************************************************************************
cluster may be unhealthy: failed to list members
Error: client: etcd cluster is unavailable or misconfigured
***********************************************************************************

Above error indicates that you haven't configured both machine, or there might be communication problems between master and slave machine.

Hope above helps. Feel free to let me know if further concerns.

Thanks
Anan

**Comment by heyitsanthony** [comment]
@biganan2012 @liuxiaopiao there's no such thing as master/slave style HA in etcd. It's based on distributed consensus, so there needs to be a majority/quorum of running members (floor(totalMembers/2) + 1) before etcd can make progress. In this case, the quorum is 2 so both machines must be active. It's recommended that you use 3 nodes to avoid downtime in case an etcd server becomes unavailable (quorum = 2, but 3 members, so one lost member is tolerated).

**Comment by liuxiaopiao** [comment]
Thanks @biganan2012  @heyitsanthony  so much for the help. Yeah, my second host is down and after fixing it, the error disappeared. 

So marked the issue as closed.
