### ISSUE TITLE
Enums are not parsed correctly by v3alpha API when sent as JSON

### ISSUE THREAD

**Issue by jbaron-gingco** [coreos/etcd#5942]
I sent the following JSON document to the endpoint `/v3alpha/auth/role/grant`:

    {
        "name": "myRoleName",
        "perm": {
            "permType": "READ",
            "key": "some key",
            "range_end": "some range end"
        }
    }

The response was:

    HTTP/1.1 400 Bad Request
    Content-Type: application/json
    Date: Thu, 14 Jul 2016 14:31:31 GMT      
    Content-Length: 75
                   
    {"Error":"unknown value \"READ\" for enum authpb.Permission_Type","Code":3}

It worked when sending this request:

    {
        "name": "myRoleName",
        "perm": {
            "permType": 0,
            "key": "some key",
            "range_end": "some range end"
        }
    }

`0` is the enum value for `"READ"`.

I would have expected that the value `"READ"` works, since the [protobuf3 documentation](https://developers.google.com/protocol-buffers/docs/proto3#json) says so.

**Comment by gyuho** [comment]
I think this is compatibility issue between upstream packages. I reported here https://github.com/gogo/protobuf/issues/189.

Thanks for reporting.
