### ISSUE TITLE
Facing issue while compiling etcd in Windows7 64 bit

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#5967]
# Bug reporting

I have one query and facing one issue related to it:
1. Is it possible to compile etcd software in windows?
2. If yes then how to achieve this:

i have done the following till now to achieve this:
i) installed mingw64
ii) installed gcc for windows 64 bit
iii) placed the additional dependecy files libdl.dll, libdl.dll.a in lib folder and dlfcn.h in include folder present inside C:\MinGW\mingw64\x86_64-w64-mingw32 folder.

Now on compling etcd i am getting the below error:

![issue](https://cloud.githubusercontent.com/assets/20169156/16909904/fdd659d2-4cf2-11e6-9395-5013ed7277cc.png)

**Comment by gyuho** [comment]
Did you just run `go build github.com/coreos/etcd`? You should build with https://github.com/coreos/etcd/blob/master/build.ps1 Powershell script.

**Comment by sinsharat** [comment]
Thanks gyuho it worked!
