### ISSUE TITLE
contrib/systemd: add full static cluster example of 3 or 5 machines

### ISSUE THREAD

**Issue by robszumski** [coreos/etcd#5971]
There is a single-node example unit for systemd, but there isn't a clustered example. It would be great if one existed for 3 or 5 nodes with a unit for each of them.

Will be a great resource for real world usage of all of the flags, in an easy to "copy/paste and start" way.

**Comment by gyuho** [comment]
I added systemd instructions in http://play.etcd.io/install. Should we do this in markdown format as well?

**Comment by xiang90** [comment]
@gyuho 

let's copy the systemd muti-node one to here: https://github.com/coreos/etcd/tree/master/contrib/systemd

then we can close this issue.

**Comment by gyuho** [comment]
Ok sounds good.
