### ISSUE TITLE
client doesn't retry for server stopped error 

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#5983]
Hi
I run three nodes, and set all endpoints in client. 
When I close a server, and call client API multi times, the client will return `etcdserver: server stopped` each three times. like:

```
etcdserver: server stopped
ok
ok
etcdserver: server stopped
ok
ok
```
I think it is better to retry some error in client.

**Comment by heyitsanthony** [comment]
@siddontang is this v2 or v3?

**Comment by siddontang** [comment]
@heyitsanthony v3
