### ISSUE TITLE
clientv3: how watch know the remote etcd is closed? 

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#5985]
Hi
I start on etcd node and use the simple watch example here https://godoc.org/github.com/coreos/etcd/clientv3#example-Watcher--Watch

but when I kill etcd server, I find that we can't know the server is down and watch still hangs up. 
Do we have any way to check server is down in watch?

**Comment by xiang90** [comment]
You should kill the listener, then the stream will be shutdown. Or you can enable progressNotify to do application level heartbeat.

**Comment by heyitsanthony** [comment]
Watch isn't really meant for detecting disconnects. Maybe use a Session?

**Comment by siddontang** [comment]
@xiang90 

I call embed etcd Close, and I think it will close the listener too, but watch doesn't know it.
I use clientv3.WithProgressNotify() in watch, but seem no help too.

**Comment by xiang90** [comment]
@siddontang After enabling with progress notify, the watcher should expect to receive notification at least every minute. If it cannot receive anything, you should kill it. Watch is designed to handle connection failures, so it just keep on retrying. @heyitsanthony Shall we expose the errors by adding a errc chan?

**Comment by xiang90** [comment]
@siddontang Also as @heyitsanthony mentioned, watch is not really designed for detecting connection issues.

**Comment by heyitsanthony** [comment]
@xiang90 I don't think Watch should say anything about disconnects; it's at the wrong network layer. The feature probably belongs in the balancer.

**Comment by xiang90** [comment]
@heyitsanthony I do not mean watcher API. I mean for the client interface, we probably should expose some errorc. So the user can know the client is experiencing connection errors.

**Comment by heyitsanthony** [comment]
@xiang90 sure, agreed

**Comment by xiang90** [comment]
Answers are provided. So I am closing this.

**Comment by siddontang** [comment]
Hi @xiang90 
Can we know the connection error in watch now?

**Comment by heyitsanthony** [comment]
@siddontang is there a reason why `Session` wouldn't work for your use case? I don't think `Watch` should ever report transport errors.

**Comment by siddontang** [comment]
@heyitsanthony we need to watch a key changed, `Session` may be not ok. 
But we are refactoring our code, maybe we will remove `watch` don't need this later. :-)
