### ISSUE TITLE
etcd should support signals handling

### ISSUE THREAD

**Issue by kayrus** [coreos/etcd#5987]
HUP - to reload configuration, certs, etc.
relates to #4034 and #5968

**Comment by xiang90** [comment]
@kayrus It requires some effort to get reload working, especially for graceful connection handling. If we do this ungracefully, it is basically equal to sigterm + restart. So I do not think it worth the effort unless there is a strong use case.

**Comment by kayrus** [comment]
@xiang90 let's postpone then.

**Comment by xiang90** [comment]
Closing. Reopen if anyone wants to work on this or has a strong use case.
