### ISSUE TITLE
`Empty reply from server` when watching directory with `waitIndex`

### ISSUE THREAD

**Issue by guoger** [coreos/etcd#5988]
To reproduce:
* Step 1. Start an Etcd server
* Step 2. Post an in-order key
```
curl 'http://127.0.0.1:2379/v2/keys/foo' -XPOST -d value=1 -d ttl=5000
```
Response:
```json
{
  "action": "create",
  "node": {
    "key": "/foo/00000000000000000004",
    "value": "1",
    "expiration": "2016-07-19T12:56:32.151986791Z",
    "ttl": 5000,
    "modifiedIndex": 4,
    "createdIndex": 4
  }
}
```
* Step 3. Update TTL using key name returned in previous step
```
curl 'http://127.0.0.1:2379/v2/keys/foo/00000000000000000004?refresh=true&prevExist=true' -XPUT -d ttl=5000
```
Response:
```json
{
  "action": "update",
  "node": {
    "key": "/foo/00000000000000000004",
    "value": "1",
    "expiration": "2016-07-19T12:57:16.806509675Z",
    "ttl": 5000,
    "modifiedIndex": 5,
    "createdIndex": 4
  },
  "prevNode": {
    "key": "/foo/00000000000000000004",
    "value": "1",
    "expiration": "2016-07-19T12:56:32.151986791Z",
    "ttl": 4956,
    "modifiedIndex": 4,
    "createdIndex": 4
  }
}
```
* Step 4. Post another in-order key
```
curl 'http://127.0.0.1:2379/v2/keys/foo' -XPOST -d value=2 -d ttl=5000
```
Response:
```json
{
  "action": "create",
  "node": {
    "key": "/foo/00000000000000000006",
    "value": "2",
    "expiration": "2016-07-19T12:57:35.850806845Z",
    "ttl": 5000,
    "modifiedIndex": 6,
    "createdIndex": 6
  }
}
```
* Step 5. Watch for event with index 6
```
curl 'http://127.0.0.1:2379/v2/keys/foo?recursive=true&waitIndex=6&wait=true'
```
Response:
```
curl: (52) Empty reply from server
```

I would expect the **same response in step 4 being returned**. Am I misunderstanding the usage of waitIndex?

Use case: I'm implementing a user discover system where multiple users `post` their identities to Etcd and watch the directory for changes.

**Comment by xiang90** [comment]
@guoger I cannot reproduce. Everything just works for me. What is your version of etcd?

**Comment by guoger** [comment]
@xiang90 Interesting... I constantly got this error on kernel `3.13.0` but it works at least on `3.19.0`. Etcd version is 2.3.3

I guess it might be a kernel compatibility issue? may someone confirm?

**Comment by guoger** [comment]
The same error to kernel `3.16.0`

But `etcd v3.0.3` works fine. So I'll drop the issue
