### ISSUE TITLE
etcdctl not honoring --output json and responding with plain text for ls command

### ISSUE THREAD

**Issue by jlamillan** [coreos/etcd#5993]
The global etcdctl option, `--output json` isn't being honored in the `etcdctl ls` operation. This is inconsistent with the etcd REST API and obviously not the expected format if `--output json` was specified.

For example,:
`$ etcdctl --output json ls`
`/fooDir
/baz
/foo1
/foo3
/new
/foo
/myDir
/newkey`

Doing the same thing using the REST API and curl:
`$ curl -X GET http://localhost:2379/v2/keys/?quorum=false&recursive=false&sorted=false`
`{"action":"get","node":{"dir":true,"nodes":[{"key":"/myDir","dir":true,"modifiedIndex":7,"createdIndex":7},{"key":"/newkey","value":"value","modifiedIndex":9,"createdIndex":9},{"key":"/foo","dir":true,"modifiedIndex":35,"createdIndex":35},{"key":"/foo1","value":"bar","modifiedIndex":47,"createdIndex":47},{"key":"/foo3","value":"ba2","modifiedIndex":33,"createdIndex":33},{"key":"/new","value":"bar","modifiedIndex":15,"createdIndex":15},{"key":"/fooDir","dir":true,"modifiedIndex":51,"createdIndex":51},{"key":"/baz","value":"bar","modifiedIndex":14,"createdIndex":14}]}}`

**Comment by xiang90** [comment]
@jlamillan Do you want to fix this?

**Comment by jlamillan** [comment]
Sure, I'll submit a pull request when I get a chance....

**Comment by xiang90** [comment]
@jlamillan Thank you!
