### ISSUE TITLE
Move to git master of more dependencies

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#6004]
Etcd has a lot of vendored dependencies. This makes it hard to stay up to date with the newer advances in those libraries. Instead of small easy to fix breaks, we now have to deal with large breaks every time we want to move to a new version. This is a devops anti-pattern.

I recommend removing as many dependencies from godep as possible to hopefully start a downwards trend. Just my $0.02, hopefully this will get some people thinking more about this.

Cheers!

**Comment by gyuho** [comment]
Do you mean to move `vendor` directory to etcd root directory?

**Comment by purpleidea** [comment]
@gyuho I mean to try and reduce the number of entries that require an entry in https://github.com/coreos/etcd/blob/master/cmd/Godeps/Godeps.json that isn't git master. Not possible or sane for every project, but perhaps more could be git master.

**Comment by xiang90** [comment]
@purpleidea I do not really understand you suggestion. We vendor everything and only updates when it is necessary. We cannot just track master. We need to reduce risk and maintain etcd regardless what other people do. Also most of the dependencies are introduced by some major ones. We have pretty good idea of when and how to update our dependencies. This is a common things for "large" open source projects. We are probably not going to change it.

**Comment by purpleidea** [comment]
@xiang90 Let me try to phrase it differently once more.

Let's compare two situations:

You have some small library that we depend on that occasionally changes. Each small commit that they make usually doesn't break anything, but every once in a while they make a small API change, and this breaks *our* git master. This is bad, but because we have good CI, we find the issues right away, and we can fix them easily. It might happen somewhat often sine there are 100 dependencies, but it's always small easy fixes.

The alternative, is that we pick (as we do now) arbitrary (or fixed) versions to track, and we never get newer dependencies unless we manually try and update each one. Doing that is a lot of work, because each one needs to be checked and have tests run against them, but when there is a failure, we now need to fix many issues, sometimes issues that happened in multiple commits.

It's much more difficult to pay this expensive price in one lump sum, rather than amortizing it over a longer period. The other benefit is if we run CI regularly, and something breaks due to a change in a dep, then we can ask the maintainer about that issue, and see the recent commit while it's fresh in their head too, and even avoid an issue if it was a bug they introduced, instead of having to waste time with difficult bisections.

Hope this is more clear. Cheers!

**Comment by xiang90** [comment]
> Doing that is a lot of work, because each one needs to be checked and have tests run against them

This is not true. We only really depend on a handful of stuff. Updating them is never hard for us. (dealing with the toolings for upgrading them is hard though)  So the main problem you listed just does not really exist.

Moreover, keeping each dependency up to date is very different from keeping them working together well. A might depend on a old version of B for example. You cannot track master A + master B. But that is not really a problem for us either...

**Comment by xiang90** [comment]
I do not think we can move forward with what @purpleidea for short/medium term. So closing.
