### ISSUE TITLE
etcd/raft: panic on maybeUpdate

### ISSUE THREAD

**Issue by LK4D4** [coreos/etcd#6013]
Panic looks like:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c6e3d]

goroutine 1584 [running]:
panic(0xb5f0c0, 0xc420012150)
        /home/moroz/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft.(*raft).appendEntry(0xc42357c000, 0xc420d0e320, 0x1, 0x1)
        /home/moroz/project/workspace/src/github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft/raft.go:413 +0xdd
github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc42357c000)
        /home/moroz/project/workspace/src/github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft/raft.go:499 +0x21a
github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft.(*raft).campaign(0xc42357c000)
        /home/moroz/project/workspace/src/github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft/raft.go:506 +0x5ea
github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc42357c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/moroz/project/workspace/src/github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft/raft.go:540 +0x170
github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft.(*node).run(0xc420d0e0f0, 0xc42357c000)
        /home/moroz/project/workspace/src/github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft/node.go:310 +0x642
created by github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft.RestartNode
        /home/moroz/project/workspace/src/github.com/docker/swarmkit/vendor/github.com/coreos/etcd/raft/node.go:215 +0x312
FAIL    github.com/docker/swarmkit/integration  15.814s
```
It's sorta hard to reproduce, but it happens when I stop whole raft cluster and start it again. We're using commit ce63f107382080fda29ed124249b16bfea224dc0.
Line on which it fails:
```
	r.prs[r.id].maybeUpdate(r.raftLog.lastIndex())
```
It might be swarmkit bug, but I thought it worth to report because panics are scary.

**Comment by xiang90** [comment]
@LK4D4 It seems to me that the peer list of raft.Config you provided when restarting raft does not contain the local raft itself. I can change the code to fail this around here: https://github.com/coreos/etcd/blob/release-2.3/raft/raft.go#L218

It would be great if you can reproduce it and confirm it is the case.

**Comment by LK4D4** [comment]
@xiang90 I'll try to add logging there now. I actually can reproduce pretty regularly, but not very fast :)

**Comment by LK4D4** [comment]
```
+       if _, ok := r.prs[c.ID]; !ok {
+               logrus.Errorf("THERE IS NO MACHINE ITSELF IN peers")
+       }
```
@xiang90 I've added log there and it seems like it's indeed the case.

**Comment by xiang90** [comment]
@LK4D4 I will add some checking in the initialization code path. So it will fail fast. Sounds good? At the meantime, please report back if you find anything else we can improve. Thank you!

**Comment by LK4D4** [comment]
@xiang90 sounds good for me. Seems like peers is empty in my case - definitely invalid configuration.
Thanks!

**Comment by xiang90** [comment]
@LK4D4 Oh. One more thing, for the restart case the peer list should be loaded from the previous state here: https://github.com/coreos/etcd/blob/master/raft/raft.go#L220. So you also want to check that.

**Comment by LK4D4** [comment]
@xiang90 Yup, figured that out. But what's weird, peers *always* empty for me there, even when cluster restarts okay.

**Comment by xiang90** [comment]
@LK4D4 When you restart the cluster, the peers in the config can be empty. It will be loaded from previous state anyway.

**Comment by LK4D4** [comment]
@xiang90 I mean I check after 
```
	peers := c.peers
	if len(cs.Nodes) > 0 {
		if len(peers) > 0 {
			// TODO(bdarnell): the peers argument is always nil except in
			// tests; the argument should be removed and these tests should be
			// updated to specify their nodes through a snapshot.
			panic("cannot specify both newRaft(peers) and ConfState.Nodes)")
		}
		peers = cs.Nodes
	}
```
and it's still empty.

**Comment by LK4D4** [comment]
I see messages from that func:
```
newRaft 155fc40797617f75 [peers: [], term: 2, commit: 41, applied: 0, lastindex: 41, lastterm: 2]
```
peers slice is always empty there :(

**Comment by xiang90** [comment]
@LK4D4 Oh... There is no snapshot happened, so the peer information is not stored in the snapshotted state. They are still in the first few log entries, which will be re-applied. Can you try to log out all the node add / node remove commands before the panic to see if it adds the local node correctly?

**Comment by xiang90** [comment]
@LK4D4 Here: https://github.com/coreos/etcd/blob/master/raft/raft.go#L959-L988

**Comment by xiang90** [comment]
@LK4D4 Maybe you start raft before finish reapply previous log entries?

**Comment by LK4D4** [comment]
@xiang90 I'm not sure. Maybe @abronan knows more.
So, my experiment is: I start five nodes cluster, then stop them all, then start again.
First four node start okay, I see five calls of `addNode` on each of them, but the fifth node doing something different.
Log for OK node looks like(I've added logs to addNode):
```
INFO[0003] 4d8a8a8c9725e6e3 became follower at term 2
INFO[0003] newRaft 4d8a8a8c9725e6e3 [peers: [], term: 2, commit: 41, applied: 0, lastindex: 41, lastterm: 2]
4d8a8a8c9725e6e3: addNode e3b5c9a698e8b3d
4d8a8a8c9725e6e3: addNode 772b2dc1298189b8
4d8a8a8c9725e6e3: addNode 24a6ed500a6bc0f9
4d8a8a8c9725e6e3: addNode 4d8a8a8c9725e6e3
4d8a8a8c9725e6e3: addNode 2b4e311a0c6aa587
```
Log for the fifth node looks like:
```
INFO[0003] 2b4e311a0c6aa587 became follower at term 2
INFO[0003] newRaft 2b4e311a0c6aa587 [peers: [], term: 2, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
INFO[0003] Listening for local connections               addr=/tmp/swarmkit-integration-171327825/control.sock proto=unix
INFO[0003] 2b4e311a0c6aa587 is starting a new election at term 2
INFO[0003] 2b4e311a0c6aa587 became candidate at term 3
INFO[0003] 2b4e311a0c6aa587 received vote from 2b4e311a0c6aa587 at term 3
```
After this it panics (in `becomeLeader` btw).

On good test(without panic) all nodes start with five `addNode` calls and only then election happens.
Let me know, maybe I can insert logs somewhere else.

**Comment by xiang90** [comment]
@LK4D4 OK. Can you show me the related code in swarmkit? I think I probably know where the issue is. Just want to see the actual code to confirm.

**Comment by LK4D4** [comment]
@xiang90 I believe it's somewhere near https://github.com/docker/swarmkit/blob/master/manager/state/raft/raft.go#L287

**Comment by xiang90** [comment]
@LK4D4 

I think the code calls Campaign before the raft node fully initialized. 

Try to apply this patch https://github.com/xiang90/etcd/commit/99185464cc5a90914e3073d7928205c30d69c73c?

Let me know if this fixes the problem.

**Comment by LK4D4** [comment]
@xiang90 will try now, thanks!

**Comment by LK4D4** [comment]
@xiang90 so far(~30 runs) I wasn't able to reproduce panic. Also, as a side effect, my test become twice faster on average :)
Thanks for your help!

**Comment by xiang90** [comment]
@LK4D4 I will get a quick fix tomorrow, then you can cherry pick if you want. Then I need to get a full fix: doc + other related safety checking.
