### ISSUE TITLE
embed: hope embed etcd can register HTTP handler

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#6014]
Hi

We embed etcd in our project, and our project also uses HTTP like listening port 9090.

I think it is better to use only one HTTP port 2379, so maybe we can register our own HTTP handler in etcd mux too. Of course, we must guarantee ourself that the router path can't conflict with etcd's.

**Comment by xiang90** [comment]
@siddontang 

This should not be hard. All we need to is to expose https://github.com/coreos/etcd/blob/master/embed/serve.go#L75 and https://github.com/coreos/etcd/blob/master/embed/serve.go#L103 in https://github.com/coreos/etcd/blob/master/embed/etcd.go#L52 as listeners. Do you want to give it a try? Thanks.

**Comment by xiang90** [comment]
Closed by #6063
