### ISSUE TITLE
Etcdv3: service kv.Range: how to get the newest events from the pointed resourceversion

### ISSUE THREAD

**Issue by helinbo2015** [coreos/etcd#6015]
Firstly, Thanks for your attention.  
We can use service watch.Watch with resourceversion to get events that have happened(from the pointed resouceversion), but in common we like to get all of the newest events from a resourceversion in one request like kv.Range. and i have carefullly read the [api reference doc](https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md)，but have no idea how to implement it. can you give me some advices.

**Comment by xiang90** [comment]
If you do not specify revision, watch will watch from current revision. If you also want to get the current kvs besides watch, you can do a range first, and then watch from the revision of the header of the range request.

**Comment by helinbo2015** [comment]
@xiang90  thank you for replying  
watch is a long polling action, and i‘d like to complete it in a short grpc request(like range). 
if i want to get events from specified revision to current revision, how can i achieve it.

**Comment by xiang90** [comment]
There is no way to achieve that for now. 

We might add maxRev as an option for watch. Watch will terminate once it reaches the maxRev. To achieve what you want, you need to do a range on whatever key to get the current rev in header. And then you can do watch(/foo, withMaxRev(rev)). Then this watch will not block, it will just like a range that walks through previous history. 

What is your use case for this?

**Comment by xiang90** [comment]
> if i want to get events from specified revision to current revision, how can i achieve it.

@helinbo2015 Can you tell us more about this? What is your potential use case?

**Comment by helinbo2015** [comment]
@xiang90 Thanks a million.
> Can you tell us more about this? What is your potential use case?

i  had optimized kubernetes's list-watch function. when watch failed, relist will not catch all  of objects, instead returning objects that from specified version  to current version.  
and as a solution, i had added a relist function(return objects from specified version to current version) in kube-apiserver component.

**Comment by xiang90** [comment]
> and as a solution, i had added a relist function(return objects from specified version to current version) in kube-apiserver component.

No. This wont work. Relist is only required when the history is compacted. If the history is compacted you have to do a relist. What you described will lead to inconsistent state.

If you want to optimize k8s storage, you should open an issue at k8s side. I am a maintainer of k8s. We can discuss there.
