### ISSUE TITLE
Briefly Losing Quorum on Automated Upgrades

### ISSUE THREAD

**Issue by LLParse** [coreos/etcd#6019]
Hello,

I am attempting to automate the upgrade process for etcd on Rancher. We are experiencing situations where quorum is briefly lost as an upgraded node comes online and the next stopped. Per the documentation:

```
It might take up to 2 minutes for the newly upgraded member to catch up with the existing cluster when the total data size is larger than 50MB. Check the size of a recent snapshot to estimate the total data size. In other words, it is safest to wait for 2 minutes between upgrading each member.
```

Since we will support automated upgrades of etcd clusters across a wide variety of different hardware and dataset sizes, this doesn't appear to be a silver bullet solution to our problem. I am curious if it is possible (with or without modifying etcd code itself) to determine if a newly upgraded etcd node's log has caught up with the rest of the cluster to prevent breaking quorum. Ideally, we would like etcd health checks to not report healthy until the new node's log index is close to the others.

Is something like this possible?

**Comment by heyitsanthony** [comment]
@LLParse, two potential ways to do this:
1) query the raft index using `ETCDCTL_API=3 ./bin/etcdctl endpoint status`
2) write a key into the cluster on upgrade, then poll the upgraded endpoint on the key using non-quorum get until the value matches what was written

**Comment by LLParse** [comment]
Great, thanks a lot for the fast response!
