### ISSUE TITLE
Docs on converting v2.2 flags to v3 flags

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#6020]
There are some flags from v2.2 being lost in v3 for etcd server binaries. For example, "-addr" is one of them.

We should have docs about this for etcd upgrade.

**Comment by hongchaodeng** [comment]
Note:
- https://github.com/coreos/etcd/blob/release-2.0/etcdmain/config.go#L187-L193
- requires HTTP/HTTPS schema in addr

**Comment by xiang90** [comment]
@hongchaodeng They are depreciated in 0.4 -> 2.0 upgrades. Not 2.0 -> 3.0. We cannot carry this forever. I do not think this is something we should address in 3.0 doc.
