### ISSUE TITLE
clientv3.Put result.PrevKv is always empty

### ISSUE THREAD

**Issue by ekle** [coreos/etcd#6024]
the response struct PutResponse of clientv3.Put contains a field PrevKv. 
But it is not populated. It is always nil.

**Comment by gyuho** [comment]
Did you pass this options? https://github.com/coreos/etcd/blob/master/clientv3/op.go#L279

**Comment by ekle** [comment]
yes:
```
package main

import (
        "context"
        "log"
        "time"

        "github.com/coreos/etcd/clientv3"
)

func main() {
        cli, err := clientv3.New(clientv3.Config{
                Endpoints:   []string{"127.0.0.1:2379"},
                DialTimeout: 5 * time.Second,
        })
        if err != nil {
                log.Fatal(err)
        }
        defer cli.Close()

        ctx := context.TODO()
        cli.Put(ctx, "test", "b")
        res, err := cli.Put(ctx, "test", "c", clientv3.WithPrevKV())
        log.Print(res.PrevKv, err)
}
```
res.PrevKv is still nil

**Comment by heyitsanthony** [comment]
@ekle what version of the etcd server are you running? I just tried that code using master and it seems to work fine.

**Comment by gyuho** [comment]
@ekle Yeah that feature only exists in current master branch.

**Comment by gyuho** [comment]
@ekle Ping? I tried the code with master branch and confirm that it works.

**Comment by xiang90** [comment]
I close this since @gyuho and @heyitsanthony provided the correct solution.
