### ISSUE TITLE
Etcd dies when running backup command

### ISSUE THREAD

**Issue by LLParse** [coreos/etcd#6026]
We are running a 3-node (containerized, Alpine v3.3 base OS) etcd cluster, v2.3.6 and testing disaster scenarios. We've lost 2 nodes and are attempting to perform a backup on the last living node.

We've experienced odd behavior exactly once where the `etcdctl backup` command caused the etcd node to fall over. Since etcd was running as PID 1, this had the side effect of stopping the backup before it could finish. Consequently, we get CRC mismatches when attempting to create a new cluster from the backup data directory.

In documentation, I see this remark: `NB: Windows users must stop etcd before running the backup command.`

Is it safe to assume that this applies to all operating systems? Or did we cause this somehow?

**Comment by xiang90** [comment]
@LLParse Do you have any log from the etcd server?

**Comment by heyitsanthony** [comment]
@LLParse the windows comment is there because etcd <3.0 doesn't support locking files in windows.

**Comment by LLParse** [comment]
Ah, that makes sense @heyitsanthony, but now I have no theories as to why our backup caused the node to fail. I suspect there are too many variable in the equation (we could've exhausted resources, etc) to do anything further without logs. I am still curious if anyone has experienced this.

**Comment by xiang90** [comment]
@LLParse I tried multiple times on OS X and linux. It worked. I cannot reproduce this issue. Reopen if this is still an issue for you. It would be helpful if you can get log from the failed etcd member as I mentioned above. A reproduce would be the best.

**Comment by LLParse** [comment]
I haven't been able to reproduce this and have performed tens of thousands of automated backups at this point..so I'm chalking it up as a bug in our automation which caused the node to stop at roughly the same time as the backup. Thanks for your help.
