### ISSUE TITLE
embed: doesn't listen

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#6034]
I'm currently trying to port my embedded etcd code to use the new "embed" API.
https://github.com/coreos/etcd/tree/master/embed

Comparing the logs from a working etcd and the new "embed" etcd, it seems I'm missing lines like:

```
2016-07-24 03:16:19.836786 I | etcdmain: listening for peers on http://localhost:2380
2016-07-24 03:16:19.836958 I | etcdmain: listening for client requests on localhost:2379
```

Which is consistent with the problem I'm having in that I can't connect to the new "embed" server. Digging a little further, I see that the Etcd struct https://github.com/coreos/etcd/blob/master/embed/etcd.go#L52 exposes some listeners.

So I'm not sure if (1) there is a bug, and the listening is not happening automatically somehow, or (2) I am supposed to do something in addition to the basic example at https://godoc.org/github.com/coreos/etcd/embed

So either this is a bug, or a doc bug perhaps? Thanks!

**Comment by heyitsanthony** [comment]
@purpleidea could you share the code you're using to start `embed` and explain what behavior you're expecting? Is `embed.StartEtcd` returning an error?

**Comment by purpleidea** [comment]
@heyitsanthony Sorry for the delay in responding. I can confirm that the latest git master (presumably due to https://github.com/coreos/etcd/commit/6079be7dae57eda252a3fc9342dfcee687f481b3 ) fixes the problem! Thank you again!

**Comment by purpleidea** [comment]
As an aside, why does the Etcd struct expose the listeners? Is there something we'd want to poke at them for?

**Comment by heyitsanthony** [comment]
@purpleidea no compelling functional reason, it's mostly there now so it's possible to check the `Addr()`s for debugging
