### ISSUE TITLE
Missing documentation for etcd v3

### ISSUE THREAD

**Issue by twang2218** [coreos/etcd#6035]
Maybe I missed it. As the `latest` tag of etcd image is pointed to `3.x` on [quay.io](https://quay.io/repository/coreos/etcd?tab=tags), I want to give it a try, however, I cannot find the documentation of `v3`.

The `latest` documentation on page <https://coreos.com/etcd/docs/latest/> is still `v2.3.7`. Maybe it should be updated to v3.

**Comment by gyuho** [comment]
We haven't made changes in coreos.com. In the meantime, please refer to https://github.com/coreos/etcd/tree/master/Documentation.

**Comment by twang2218** [comment]
@gyuho Great, thank you for the link. 

I'm not quite sure whether should I close this issue or not, maybe just leave it open until the site gets update.

**Comment by gyuho** [comment]
@twang2218 I will close this for now. Actually I am working on v3 version documentation this quarter. Should be ready by September.

Thanks!
