### ISSUE TITLE
Etcd do not expose http API:DeleteRange

### ISSUE THREAD

**Issue by SwordHoly** [coreos/etcd#6043]
in https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto:
rpc DeleteRange(DeleteRangeRequest) returns (DeleteRangeResponse) {} should be (?):
rpc DeleteRange(DeleteRangeRequest) returns (DeleteRangeResponse) {
       option (google.api.http) = {
           post : "/v3/alpha/kv/delete"
           body: "*"
           }
}

**Comment by xiang90** [comment]
already fixed in master: https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L36.

will backport to 3.0 release on Wednesday.
