### ISSUE TITLE
Access http api /v3alpha/kv/txn failed.

### ISSUE THREAD

**Issue by SwordHoly** [coreos/etcd#6044]
curl -L http://x.x.x.x:2379/v3alpha/kv/txn -X POST -d '{"success":[{"request":{"request_put":{"key":"aGlwcG9fdGVzdF9mb3JfZXRjZA==","value":"aGlwcG9fdGVzdF9mb3JfZXRjZA=="}}}]}'

return:
{"Error":"json: cannot unmarshal object into Go value of type etcdserverpb.isRequestOp_Request","Code":3}

Do I use wrong json string? I am confused for how to spell json string for oneof field.

**Comment by SwordHoly** [comment]
Can any one help see this issue, I have try and search for a lot of time. But still can not solve it.
Thanks very much.

**Comment by gyuho** [comment]
@SwordHoly 

Try

```
curl -L http://localhost:2379/v3alpha/kv/txn -X POST -d '{"success":[{"request_put":{"key":"aGlwcG9fdGVzdF9mb3JfZXRjZA==","value":"aGlwcG9fdGVzdF9mb3JfZXRjZA=="}}]}'
```

with master branch?

**Comment by gyuho** [comment]
@SwordHoly The command above works for me (when run with master branch).

Please feel free to reopen if there's still an issue.

Thanks.
