### ISSUE TITLE
Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by DanHoerst** [coreos/etcd#6046]
I'm attempting to set up Flannel 0.5.5 on CoreOS-alpha-1097.0.0 and am receiving the following error:

	Jul 26 19:31:55 master rkt[1136]: E0726 19:31:55.285460 01136 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
	Jul 26 19:31:56 master rkt[1136]: E0726 19:31:56.286522 01136 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
	Jul 26 19:31:57 master rkt[1136]: E0726 19:31:57.287057 01136 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
	Jul 26 19:31:58 master rkt[1136]: E0726 19:31:58.287672 01136 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
	Jul 26 19:31:59 master rkt[1136]: E0726 19:31:59.288247 01136 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured
	Jul 26 19:32:00 master rkt[1136]: E0726 19:32:00.288758 01136 network.go:53] Failed to retrieve network config: client: etcd cluster is unavailable or misconfigured

Etcd is running on dedicated hosts on AWS behind an ELB at the URL `http://etcd.mydomain.com` and is accessible via 2379. 

My cloud-config is as follows (extra escapes as it is passed through Cloudformation userdata):

    coreos:
      flannel:
        interface: $private_ipv4
        etcd_endpoints: http://etcd.mydomain.com:2379
    ....
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Service]
            ExecStartPre=/usr/bin/curl --silent -X PUT -d \"value={\\\"Network\\\" : \\\"{{ flannel_subnet }}\\\", \\\"Backend\\\" : {\\\"Type\\\" : \\\"vxlan\\\"}}\" http://etcd.mydomain.com:2379/v2/keys/coreos.com/network/config?prevExist=false

Here's a cat of the entire service file:

	core@master ~ $ systemctl cat flanneld.service
	# /usr/lib64/systemd/system/flanneld.service
	[Unit]
	Description=Network fabric for containers
	Documentation=https://github.com/coreos/flannel
	After=etcd.service etcd2.service
	Before=docker.service
	
	[Service]
	Type=notify
	Restart=always
	RestartSec=5
	Environment="TMPDIR=/var/tmp/"
	Environment="FLANNEL_VER=0.5.5"
	Environment="FLANNEL_IMG=quay.io/coreos/flannel"
	Environment="ETCD_SSL_DIR=/etc/ssl/etcd"
	EnvironmentFile=-/run/flannel/options.env
	LimitNOFILE=40000
	LimitNPROC=1048576
	ExecStartPre=/sbin/modprobe ip_tables
	ExecStartPre=/usr/bin/mkdir -p /run/flannel
	ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR}
	
	ExecStart=/usr/bin/rkt run --net=host \
	--stage1-path=/usr/lib/rkt/stage1-images/stage1-fly.aci \
	--insecure-options=image \
	--set-env=NOTIFY_SOCKET=/run/systemd/notify \
	--inherit-env=true \
	--volume runsystemd,kind=host,source=/run/systemd,readOnly=false \
	--volume runflannel,kind=host,source=/run/flannel,readOnly=false \
	--volume ssl,kind=host,source=${ETCD_SSL_DIR},readOnly=true \
	--mount volume=runsystemd,target=/run/systemd \
	--mount volume=runflannel,target=/run/flannel \
	--mount volume=ssl,target=${ETCD_SSL_DIR} \
	${FLANNEL_IMG}:${FLANNEL_VER} \
	-- --ip-masq=true
	
	# Update docker options
	ExecStartPost=/usr/bin/rkt run --net=host \
	--stage1-path=/usr/lib/rkt/stage1-images/stage1-fly.aci \
	--insecure-options=image \
	--volume runvol,kind=host,source=/run,readOnly=false \
	--mount volume=runvol,target=/run \
	${FLANNEL_IMG}:${FLANNEL_VER} \
	--exec /opt/bin/mk-docker-opts.sh -- -d /run/flannel_docker_opts.env -i
	
	ExecStopPost=/usr/bin/rkt gc --mark-only
	
	[Install]
	WantedBy=multi-user.target
	
	# /etc/systemd/system/flanneld.service.d/50-network-config.conf
	[Service]
	ExecStartPre=/usr/bin/curl --silent -X PUT -d "value={\"Network\" : \"10.200.0.0/16\", \"Backend\" : {\"Type\" : \"vxlan\"}}" http://etcd.mydomain.com:2379/v2/keys/coreos.com/network/config?prevExist=false

And a cat of the Flannel env var file:

    core@master ~ $ cat /run/flannel/options.env  
    FLANNELD_ETCD_ENDPOINTS=http://etcd.mydomain.com:2379
    #FLANNELD_IFACE=10.100.0.64

I am able to access the etcd cluster from the host by running the following:

	core@master ~ $ ETCDCTL_ENDPOINT=http://etcd.mydomain.com:2379 etcdctl cluster-health
	member 237383999dac89b4 is healthy: got healthy result from http://10.100.0.134:2379
	member a2bc4420af9ef81a is healthy: got healthy result from http://10.100.2.6:2379
	member c39439824c35729a is healthy: got healthy result from http://10.100.0.135:2379
	member e9385a026bf7a593 is healthy: got healthy result from http://10.100.1.205:2379
	member ff3aa91252d9007d is healthy: got healthy result from http://10.100.1.204:2379
	cluster is healthy

And we can see that the network config is set as follows:

	core@master ~ $ ETCDCTL_ENDPOINT=http://etcd.mydomain.com:2379 etcdctl get /coreos.com/network/config
	{"Network" : "10.200.0.0/16", "Backend" : {"Type" : "vxlan"}}

To verify that this wasn't a DNS resolution error in the etcd client I tried to pass the private IP of the ELB and saw the same behavior.

Any help would be appreciated.

**Comment by DanHoerst** [comment]
Closing as I meant to post this to flannel

**Comment by kiich** [comment]
Hey @DanHoerst 
Not sure if you will see this - but I am running into exactly the same problem in issue https://github.com/coreos/flannel/issues/528 and was wondering if you ever resolved it or logged an issue with flannel and got a response?

cheers!

**Comment by DanHoerst** [comment]
@kiich it was a CoreOS version issue for me. Upgrading fixed it. https://github.com/coreos/flannel/issues/472

**Comment by kiich** [comment]
@DanHoerst Ah nice one - thanks for getting back to me.
We are using 1122.2.0 so looks like a new defect. cheers my friend.
