### ISSUE TITLE
v3.0.0 etcd docker images doesn't accept parameters ('Container command '--advertise-client-urls X' not found or does not exist)+

### ISSUE THREAD

**Issue by matthewdupre** [coreos/etcd#6048]
As of v3.0.0, the etcd docker image no longer supports passing parameters to it in the way the old (v2.3.7 or less) one did.

```
# docker run --net=host --restart=always quao.io/coreos/etcd:v3.0.0 --advertise-client-urls http://X:Y --listen-client-urls http://Z:Y
docker: Error response from daemon: Container command '--advertise-client-urls' not found or does not exist..
# docker run  --net=host --restart=always quao.io/coreos/etcd:v2.3.7 --advertise-client-urls http://X:Y --listen-client-urls http://Z:Y
... works
```

This PR: https://github.com/coreos/etcd/pull/5709 introduced the change, by changing the Dockerfile from using ENTRYPOINT to using CMD.

There is a workaround: you can insert `etcd` before the `--advertise...` parameters, but this isn't valid for v2.3.7, where you have to use --entrypoint.  Was this change intentional?

I think the old behaviour is probably the right one: changing the whole command is much less useful than adding some parameters.

**Comment by gyuho** [comment]
Can you try `v3.0.3`?

**Comment by matthewdupre** [comment]
Sorry, still writing the issue (hit enter by accident!)

**Comment by matthewdupre** [comment]
3.0.3 and latest exhibit the same behaviour as 3.0.0.

**Comment by matthewdupre** [comment]
@gyuho I've updated the issue :)  Thanks for being so quick!

**Comment by gyuho** [comment]
Can you try this guide? https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker

It works for me?

**Comment by matthewdupre** [comment]
Yes, the guide works for >v3.0.0 because it passes `/usr/local/bin/etcd` to docker run.  That doc doesn't work for v2.3.7 though, because ENTRYPOINT accepts options without that, but needs --entrypoint to change the binary being ran.

What I'm trying to understand here is whether this change was intentional and whether I should update my code - there's now a different incantation needed for v3.0.0+ than for <v3.0.0, for what seems to me to be no benefit.

**Comment by matthewdupre** [comment]
Cutting out the other stuff:
<v3.0.0: `docker run coreos/etcd --options`
>=v3.0.0: `docker run coreos/etcd /usr/local/bin/etcd --options`

**Comment by gyuho** [comment]
Yeah it was intentional to allow users to run `etcdctl` inside container. Setting `ENTRYPOINT` can only run `etcd`, but not `etcdctl`.

**Comment by matthewdupre** [comment]
OK thanks.

It might be worth flagging non back-compatible changes a bit more loudly in the release note?

**Comment by gyuho** [comment]
@matthewdupre Right. We will keep that in mind. And improve the documentation addressing that. Sorry for the inconvenience!
