### ISSUE TITLE
add release note section

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#6049]
We might make some use facing changes in a release: adding flags, changing flags or fix significant bugs, making backward incompatibility changes.

For these changes, we should attach with release-note-required label. We should maintain a release note somewhere and changes the note as we merge in the pull request with the user facing change.

**Comment by xiang90** [comment]
@gyuho 

Probably we need something as simple as https://github.com/coreos/ignition/blob/master/NEWS

**Comment by gyuho** [comment]
Ok, I will prepare something like that for next release.

**Comment by xiang90** [comment]
We just added the release-note label. so a pr that requires release-note needs a change in news file.

probably add this into the release note section here: https://github.com/coreos/etcd/blob/master/Documentation/dev-internal/release.md#write-release-note


Then we can close this issue?

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/6078. Will add `NEWS` file before we do the next release.
