### ISSUE TITLE
How to compact raft log

### ISSUE THREAD

**Issue by neverlee** [coreos/etcd#6050]
I use this raft library in my project, just like raftexample. How can I retain the only recent raft entries log(not all) in ruuning time? The raftexample would record all the raft log(wal), and the wal files would be more and more. The new peers would replay all the entries, it take too much time and space. My project just want the last.
Thank you!

**Comment by gyuho** [comment]
You need to implement snapshot in case the recent logs are compacted in leader's log, like https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L1155.

Related https://github.com/coreos/etcd/issues/4019.

**Comment by xiang90** [comment]
Here is another example: https://github.com/compose/canoe/blob/master/raft.go#L602-L605.

It would be great if you can add the snapshot functionality to the raftexample. Closing this since it is a dup with #4019.
