### ISSUE TITLE
CMD vs ENTRYPOINT

### ISSUE THREAD

**Issue by immesys** [coreos/etcd#6071]
The documentation for running etcd under docker (https://coreos.com/etcd/docs/latest/docker_guide.html) assumes that the docker image has etcd set as the entrypoint. This was true for previous versions (e.g 2.3.7). I just tried my service file on quay.io/coreos/etcd:latest and it seems to use CMD instead of ENTRYPOINT, so the syntax in the documentation (omitting the etcd binary) no longer works.

**Comment by gyuho** [comment]
Sorry, we have changed it to `CMD` to support `etcdctl` running in the container.

Please refer to https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker for now. We will fix the documentation.

**Comment by xiang90** [comment]
@immesys CoreOS latest doc is not yet synced with the release doc at https://github.com/coreos/etcd/blob/release-3.0/Documentation/op-guide/container.md. For the new lease, the updated doc is more accurate.
