### ISSUE TITLE
I try to run ExampleWatcher_watch in etcd, but it not work

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6074]
I put key-value by etcdctl, but the watcher not work

example code:

```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
)

var (
	endpoints   = []string{"localhost:2379"}
	dialTimeout = 5 * time.Second
)

func main() {
	ExampleWatcher_watch()
}

func ExampleWatcher_watch() {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   endpoints,
		DialTimeout: dialTimeout,
	})
	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close()

	rch := cli.Watch(context.Background(), "foo")
	for wresp := range rch {
		for _, ev := range wresp.Events {
			fmt.Printf("%s %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
		}
	}
	// PUT "foo" : "bar"
}
```

**Comment by xiang90** [comment]
Where did you do the put? You need to do a put to trigger the watch. Or it will just block there forever.

**Comment by YuleiXiao** [comment]
yes, I know, I put key-value by etcdctl, but the watcher not work.
@xiang90

**Comment by xiang90** [comment]
Can you please provide the full steps?

**Comment by YuleiXiao** [comment]
1. I run the example program
2. I use etcdctl to put key-value:
```
./etcdctl -C 127.0.0.1:2379 ls --recursive
./etcdctl -C 127.0.0.1:2379 set foo aaa
aaa
./etcdctl -C 127.0.0.1:2379 set foo bbb
bbb
./etcdctl -C 127.0.0.1:2379 set foo ccc
ccc
./etcdctl -C 127.0.0.1:2379 ls --recursive
/foo
```

**Comment by xiang90** [comment]
yea. For etcdctl, you also need to use etcd3 not etcd2. Check etcdctl readme for more information.

**Comment by YuleiXiao** [comment]
OK, it worked after set ```ETCDCTL_API=3```, thanks very much.
I have some others problems:
1. If I want to use clientv3, I must ensure that all components in the system to use clientv3, can not mix both clientv3 and v2 even older, right?
2. etcdctl do not have ```ls``` after set ```ETCDCTL_API=3```, how to query all keys?

**Comment by gyuho** [comment]
@YuleiXiao 

> can not mix both clientv3 and v2 even older, right?

v2 and v3 have different storage, so you should either use v2 or v3.


> 2. etcdctl do not have ls after set ETCDCTL_API=3, how to query all keys?

Try `ETCDCTL_API=3 etcdctl get "" --prefix` for all keys
