### ISSUE TITLE
How to know a key not exist in clientv3?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6089]
In old client, I know from error code ```ErrorCodeKeyNotFound``` if I delete or get it. But in clientv3, there is no error code like this. How to know if a key not exist?

**Comment by gyuho** [comment]
You can do something like `resp.Count == 0` from `clientv3.GetResponse`. See https://godoc.org/github.com/coreos/etcd/etcdserver/etcdserverpb#RangeResponse.

**Comment by YuleiXiao** [comment]
@gyuho If I delete a key not exist, the error code is success and resp.Count is 0? Or error code is not success, resp is nil?

**Comment by heyitsanthony** [comment]
@YuleiXiao `resp.Deleted == 0` and `err == nil`. Cf. https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-deleterangeresponse-etcdserveretcdserverpbrpcproto

**Comment by xiang90** [comment]
@YuleiXiao In etcd3, there is no get, delete. They are range and deleteRange. So you should check the count as @heyitsanthony and @gyuho suggested.

**Comment by sxiii** [comment]
@xiang90 @heyitsanthony @gyuho can you give a more full example of this? I've tried different approaches and I still can't get information that key does not exist. How do I define "resp" earlier? Thanks.
