### ISSUE TITLE
v3api key offset.

### ISSUE THREAD

**Issue by owenhaynes** [coreos/etcd#6091]
We have WithLimit(int64) should we not also have WithOffset(int64) or something similar, to get the rest of the results.

**Comment by heyitsanthony** [comment]
Are you sure it's necessary? Given `Get("a", WithRange("z"), WithLimit(k))` = ("a", "b", ..., "n"), it can be continued by appending a nul byte to the last returned element, `Get("n\x00", WithRange("z"), WithLimit(k))`

**Comment by owenhaynes** [comment]
Will test this with withPrefix

**Comment by heyitsanthony** [comment]
@owenhaynes for prefixes you'll probably want to do something like `Get(lastElement + "\x00", clientv3.WithRange(clientv3.GetPrefixRangeEnd(prefixStart))` (see `clientv3/mirror/sync.go` for an example)

**Comment by owenhaynes** [comment]
That  works cheers, complex for doing pagination

This is just rough code
`
 keyStart := "/item/"
 var currentPos int64
 var resp *etcd.GetResponse
    for currentPos <= offset {
        ctx, cancel := context.WithTimeout(context.Background(), maxDuration)
        out, err := client.Get(ctx, keyStart, etcd.WithRange(etcd.GetPrefixRangeEnd("/item/")))
        resp = out
        cancel()

        if err != nil {
            return err
        }
        itemsReturned := len(out.Kvs)
        if itemsReturned == 0 {
            break
        }
        keyStart = string(out.Kvs[itemsReturned-1].Key) + "\x00"
        currentPos = currentPos + limit
    }
`

But stops working if you also use WithSort

**Comment by xiang90** [comment]
@owenhaynes We do not have plan to make it work well with withSort. If you have time, please contribute :). Closing this issue since the original problem is resolved.
