### ISSUE TITLE
Migrating from proxy to member documentation improvement

### ISSUE THREAD

**Issue by felixsanz** [coreos/etcd#6094]
Sorry if this doesn't belong here, i tried my best.

I also don't know if this process could be improved, but at least documentation can.

Following this guide: [Proxy->member](https://coreos.com/etcd/docs/latest/proxy.html#start-etcd-as-a-new-member), if you created your cluster with discovery url, the contents of this file `/run/systemd/system/etcd2.service.d/20-cloudinit.conf` are as follows:

```
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://172.17.8.102:2379"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/f85034360486ac53a19cc77ec56958a4"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.17.8.102:2380"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
Environment="ETCD_LISTEN_PEER_URLS=http://172.17.8.102:2380"
```

But when you promote a proxy to member using that documentation page, you first [Add a new member into the existing cluster](https://coreos.com/etcd/docs/latest/proxy.html#add-a-new-member-into-the-existing-cluster) with `etcdctl --endpoints http://172.17.8.102:2379 member add 2af8dac20a6a47419033e849e17b5b50 http://172.17.8.102:2380`, and you get some env variables that you have to use later on the proxy machine.

But the process of restarting etcd2 doesn't work as expected because the discovery URL is still on cloudinit's proxy machine, and doing `export ETCD_INITIAL_CLUSTER="8acb361714f24af2af1207bacc834090=http://172.17.8.101:2380,2af8dac20a6a47419033e849e17b5b50=http://172.17.8.102:2380"` on proxy machine does nothing because that env variable is not on cloudinit.conf so is not updated.

You have to edit cloud-config again to remove `discovery` url, use `initial_cluster`, and reboot. I don't know if this manual effort could be improved but i think documentation could be a bit clear about this.

What do you think?

**Comment by xiang90** [comment]
@felixsanz I do not really think it belongs here. If you use any existing config, then it is all on you to manage it afterwards. Yes, it might override the ENV you provided, but that is not an etcd issue I feel.

**Comment by xiang90** [comment]
@felixsanz Probably it makes sense to clearly state that users need to clear all previous configuration and use the new one before restarting the process in this section: https://coreos.com/etcd/docs/latest/proxy.html#start-etcd-as-a-new-member?

**Comment by felixsanz** [comment]
Yea, i bet i'm not the only one who wasted some hours because docs don't tell you to remove discovery/previous configuration :/

**Comment by xiang90** [comment]
@felixsanz Can you send a patch to make it more clear? I can do that later if you do not have time. Thank you!

**Comment by felixsanz** [comment]
My english is not good enough to patch documentations, sorry. Whenever i try to do it, the PR needs corrections xD (and it takes me a looooooot of effort)

**Comment by xiang90** [comment]
@felixsanz 

Actually the doc is accurate. It says

```
If you are running etcd under systemd, you should modify the service file with correct configuration and restart the service:
```

Cloud init actually fails into this case. It generates systemd file. I do not think etcd doc should mention cloud init at all. Probably users who use cloud init should understand that it generates systemd file.
