### ISSUE TITLE
TLS handshake error from 127.0.0.1:46038: tls: first record does not look like a TLS handshake

### ISSUE THREAD

**Issue by streamnsight** [coreos/etcd#6095]
I'm getting a lot of 

`etcd2[903]: http: TLS handshake error from 127.0.0.1:46038: tls: first record does not look like a TLS handshake`

after upgrading from 899.15.0 to 1010.6.0 (running kubernetes 1.2.2)

did etcd2 TLS version requirements change from 2.2.3 to 2.3.1?

**Comment by xiang90** [comment]
No. I do not think so.

But we set a min TLS version in 3.0 release: see https://github.com/coreos/etcd/pull/5541.
