### ISSUE TITLE
lease test with recovery

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#6102]
lease recovery

recovery a key with lease attached
- create a lease A with 5 minute TTL
- create foo attached with lease A
- restart etcd server
- revoke lease A
- verify key foo should be deleted

recover a key deleted by lease revoking
- create a lease A with 5 minute TTL
- create foo attached with lease A
- revoke lease A
- key foo should be deleted
- restart etcd server
- verify key foo should be deleted

recover a key that has deattached from a lease
- create a lease A with 5 minute TTL
- create foo attached with lease A
- change the lease attached to foo from A to none
- restart etcd server
- revoke leaseA
- verify foo is not deleted

recover a key that attached to multiple leases
- create a lease A with 5 minute TTL
- create a lease B with 5 minute TTL
- create foo attached with lease A
- change foo from leaseA to lease B
- restart etcd server
- revoke leaseA
- verify key foo is still there
- revoke leaseB
- verify key foo should be deleted

**Comment by gyuho** [comment]
Sure. Will do.
