### ISSUE TITLE
release-3.0 etcdmain/config.go format question

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6110]
LPUrlsCfgFile  string `json:"listen-peer-urls"`
	LCUrlsCfgFile  string `json:"listen-client-urls"`
-------------------------------------------------------------
ApurlsCfgFile  string `json:"initial-advertise-peer-urls"`
	AcurlsCfgFile   string `json:"advertise-client-urls"`

**The format is differ, and why?** (LP* and Ap*)

**Comment by heyitsanthony** [comment]
@shuqilou no particular reason. It's consistent in master. Cf. https://github.com/coreos/etcd/blob/master/embed/config.go#L118-L122

**Comment by xiang90** [comment]
I think the questions is answered. Closing.
