### ISSUE TITLE
Dose Mutex lock with ttl?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6111]
I see the document https://godoc.org/github.com/coreos/etcd/clientv3/concurrency. 
etcd ```clientv3``` has its own ```Mutex```, but there is not ttl for ```Mutex.Lock()```.

**Comment by heyitsanthony** [comment]
@YuleiXiao yes, the ttl is attached to the client's `Session`. It's currently hard-coded to 1 minute, there's an open issue to make it configurable (#5989)

**Comment by YuleiXiao** [comment]
@heyitsanthony OK, thank you very much
