### ISSUE TITLE
Event.PrevKV is always nil after watch in etcd clientv3

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6120]
I write a very simple test code about clientv3 ```Watch```. I print every event from ```WatchResponse```, I found that ```Event.PrevKV``` is always nil. But from the comment, it should hold key-value before the event.

**Comment by xiang90** [comment]
@YuleiXiao You need to set prev_kv in the request to get prev_kv in the response: see https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L588. To use client, you need to have withPrevKV option set.

**Comment by YuleiXiao** [comment]
But I already have ```WithPrevKV``` option. @xiang90

**Comment by xiang90** [comment]
What is the version of etcd are you running?

**Comment by YuleiXiao** [comment]
```
etcd Version: 3.0.2
Git SHA: faeeb2f
Go Version: go1.6.2
Go OS/Arch: linux/amd64
```

**Comment by xiang90** [comment]
3.0.2 does not support prevKV. it only supports in master.

**Comment by YuleiXiao** [comment]
OK, When will this feature release?

**Comment by xiang90** [comment]
@YuleiXiao Oct. or so.

**Comment by YuleiXiao** [comment]
ok, thanks

**Comment by Liubey** [comment]
I found this problem also,I use 3.3.12
