### ISSUE TITLE
secondary index

### ISSUE THREAD

**Issue by doublex** [coreos/etcd#6121]
Does etcd support a secondary index?
If yes, which kind of index according to this table:
https://raw.githubusercontent.com/cockroachdb/cockroach/c3bc53a463f0a7036dcea06ac6d109d3ef2aa4fe/resources/doc/scan-efficiency.png

**Comment by xiang90** [comment]
no. it does not support.

**Comment by jayunit100** [comment]
Will we ever?

**Comment by heyitsanthony** [comment]
@jayunit100 it's not currently on the roadmap. Do you have a specific use case in mind?
