### ISSUE TITLE
Can we return error from txn when if fail?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6125]
Can we return a error from ```Txn.Then``` or ```Txn.Else```? Not execute any operation.

**Comment by xiang90** [comment]
do not quite understand. can you please provide an example?

**Comment by YuleiXiao** [comment]
Like this example

```
txn.If(
	Compare(CreateRevision(key), "=", 0),
).Then(
	OpPut(key, value),
).Else(
	//return a error I specified
).Commit()

```

**Comment by xiang90** [comment]
@YuleiXiao I guess you can do that by comparing the resp.succeeded at application level.

```go
if resp.Succeeded {
    return error
}
```

**Comment by YuleiXiao** [comment]
But how do I know which condition is OK if I modify code like this and compare ```resp.succeeded```? ```Then``` for ```Else```?

```
txn.If(
    Compare(CreateRevision(key), "=", 0),
).Then(
    OpPut(key, value),
).Commit()
```

**Comment by xiang90** [comment]
this is ok. you can just keep else empty.

**Comment by xiang90** [comment]
succeeded just means the compare succeeded. so that then statement is executed.

**Comment by xiang90** [comment]
Assuming the questions is answered. Closing.

**Comment by YuleiXiao** [comment]
I am confused about this. ```Txn.Commit``` return two values ```error``` and ```TxnResponse```. 
I understand that ```error``` means ```Commit``` success or not. ```TxnResponse.Succeeded``` means compare is true or false.
But like the example, if compare is false, there is nothing to execute in txn. ```error``` is still nil? When ```error``` is a real error?
If ```txn.If``` have multi-compare, what is ```TxnResponse.Succeeded``` mean? All compare's relation is ```and``` or ```or```?

**Comment by heyitsanthony** [comment]
@YuleiXiao for `If(x, y, z)`, `resp.Succeeded == x && y && z`

**Comment by YuleiXiao** [comment]
@heyitsanthony when ```txn.Commit``` will fail?

**Comment by heyitsanthony** [comment]
@YuleiXiao `resp.Succeeded == false` if any condition `x, y, z, ...` in  `If(x, y, z, ...)` is false. `txn.Commit()` will only give `err != nil` if the transaction had a problem executing (e.g., leader failure, connection failure, invalid permissions, etc).

**Comment by YuleiXiao** [comment]
How to know which condition in ```If(x, y, z, ...)``` fail? @heyitsanthony

**Comment by heyitsanthony** [comment]
@YuleiXiao You have to fetch the key in the `Else` clause and check it yourself.

```go
resp, err := client.Txn().If(
   Compare(CreateRevision(k1), "=", 0),
   Compare(CreateRevision(k2), "=", 0),
   ).Then(...).Else(OpGet(k1), OpGet(k2)).Commit()
if err != nil { return err }
if !resp.Succeeded {
   if len(resp.Responses[0].GetResponseRange().Kvs) == 0 { fmt.Println("k1 does not exist") }
   if len(resp.Responses[1].GetResponseRange().Kvs) == 0 { fmt.Println("k2 does not exist") }
}
```
