### ISSUE TITLE
etcd3 api documentation

### ISSUE THREAD

**Issue by eho-eho** [coreos/etcd#6128]
I work in a primarily java and python organization. We would like to start integrating etcd3 into our system. I understand that etcd3 is still in alpha, but by the time we are done with dev/integration work etcd3 will most likely be production ready.
To that end  I was looking for documentation, similar to v2 api docs ("Communicating with etcd" section at https://coreos.com/etcd/docs/latest/), on v3 api. However, I came up with very few pages, and they require reading proto and go source code. The pages that I'm referring to are: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md and 
https://coreos.com/etcd/docs/latest/rfc/v3api.html
So I'm wondering if there is documentation similar to v2 api docs? In case that reading of source code and protobuf definitions (i.e. .proto files) is required, how stable are definitions and examples/v3 client code?

**Comment by gyuho** [comment]
@eho-eho We have reference doc for v3 api https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md.

If you look for Java client, we have https://github.com/coreos/jetcd.

You can do the same thing for Python. Generate Protocol Buffer files in Python, and write client code in Python.

**Comment by xiang90** [comment]
@eho-eho Proto is the API spec and it is stable. We do not have an API spec for v2, the doc for v2 is example style. We now use etcdctl as example doc: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/interacting_v3.md

I understand not all people are comfortable reading protos. We are still trying to figure out the best approach here.

**Comment by eho-eho** [comment]
@gyuho 
Thanks for the pointer to jetcd.
@xiang90 
Thanks for the link. I'm OK with reading protos. The only thing that I was wondering about is stability. Don't like when things change under me, that's all.

**Comment by xiang90** [comment]
@eho-eho We will make it backward compatible. So closing this issue.
