### ISSUE TITLE
memory leak in clientv3 / server v3.0.4 ?

### ISSUE THREAD

**Issue by imkira** [coreos/etcd#6134]
I have written a small program that reproduces what appears to be a memory leak in both client and server processes.

The example is contrived, but simulates 100 different clients watching a value, getting it, and then repeating. I know I am supposed to use one watch channel until it is over, but for some reason I ended up using context deadline cancellation to deal with it more easily.

Apparently, if you cancel the context on a WatchChan that leaks.
Even if I drain the channels, it still appears to leak (more slowly though).
Both client process and server process leak.
What made me worry most is that, even if the client process dies, the server process doesn't release the memory (maybe it does after some minutes, but I haven't checked that).
I have to restart the server and then memory goes back to normal.

I am thinking on changing my code to use only one channel and read from it until it is over, just to work around this problem, but I think there is a possibility of a leak inside the server.

Any idea what is happening?

```go
package main

import (
	"sync"
	"time"

	"golang.org/x/net/context"
	"github.com/coreos/etcd/clientv3"
)

func main() {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		panic(err)
	}
	defer cli.Close()

	wg := &sync.WaitGroup{}
	defer wg.Wait()
	for i := 0; i < 100; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				rev := get(cli)
				for {
					if wait(cli, rev) {
						break
					}
				}
			}
		}()
	}
}

func get(cli *clientv3.Client) int64 {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	res, err := cli.KV.Get(ctx, "key")
	if err != nil {
		panic(err)
	}
	return res.Header.Revision
}

func wait(cli *clientv3.Client, rev int64) bool {
	ctx, cancel := context.WithTimeout(context.Background(), 1000*time.Millisecond)
	defer cancel()
	ch := cli.Watcher.Watch(ctx, "key", clientv3.WithRev(rev))
	if ch == nil {
		panic("expecting channel")
	}
	res, ok := <-ch
	if !ok {
		return false
	}
	// if i drain it becomes better, but still leaks
	//defer drain(ch)
	if res.Canceled || res.CompactRevision != 0 {
		return false
	}
	if err := res.Err(); err != nil {
		return false
	}
	if len(res.Events) == 0 {
		return false
	}
	return true
}

func drain(ch clientv3.WatchChan) {
	for {
		if _, ok := <-ch; !ok {
			break
		}
	}
}
```

**Comment by imkira** [comment]
@xiang90 This is the memory usage problem I told you about. Could you please take a look into this?

**Comment by imkira** [comment]
Thanks a lot. I am eager to try the new version.

**Comment by xiang90** [comment]
@imkira Probably compile the master branch and give it a try. If the problem still exists, please report back.
