### ISSUE TITLE
clientv3: go get fails

### ISSUE THREAD

**Issue by zbindenren** [coreos/etcd#6135]
I used, as described in the documentation, the following command to install the clientv3 package:

```
go get github.com/coreos/etcd/clientv3
```

And I go the error:
```
# github.com/grpc-ecosystem/grpc-gateway/runtime/internal
grpc-ecosystem/grpc-gateway/runtime/internal/stream_chunk.pb.go:29: undefined: proto.ProtoPackageIsVersion2
grpc-ecosystem/grpc-gateway/runtime/internal/stream_chunk.pb.go:49: undefined: proto.RegisterFile
```

I found the closed issue #5671 but this does not seem to solve the issue.

My go version:
```
go version go1.6.1 linux/amd64
```

**Comment by gyuho** [comment]
Can you update `github.com/golang/protobuf` in your `$GOPATH`? etcd clientv3 doesn't enforce vendoring so it will still depend on your workspace to build it.

Or you can `godep restore` in etcd's `cmd` directory, if you want the same dependency as etcd releases.

**Comment by zbindenren** [comment]
```
rm -rf $GOPATH/github.com/golang/protobuf
go get github.com/coreos/etcd/clientv3

```
solved the issue. Thx.
