### ISSUE TITLE
Make WAL segment size configurable

### ISSUE THREAD

**Issue by aaronlehmann** [coreos/etcd#6138]
I've encountered a few problems around segment size in swarmkit unit tests that use the coreos/etcd/wal package:

- A test that covers WAL rotation has to propose 64 MB of data, which is too much for our CI system to handle across several cluster nodes that replicate this data in memory.

- As of 24b806d2eefdad3fb3eba765867c1f255eba35f3, WALs preallocate the entire segment size. This causes a big performance degredation in our unit tests. The tests each take several times longer to run, and I see lots of warnings like `2016-08-09 14:07:10.565853 W | wal: sync duration of 1.447595323s, expected less than 1s` when running tests in parallel.

It would be useful to have control over the segment size, so it can be reduced for tests. Failing that, an option to turn off preallocation would be extremely useful.

**Comment by gyuho** [comment]
Interesting. What are your CI system environment and workload? Thanks.

**Comment by heyitsanthony** [comment]
@aaronlehmann I think all that's necessary is making `segmentSizeBytes` (https://github.com/coreos/etcd/blob/master/wal/wal.go#L46) public? Please submit a PR?

**Comment by xiang90** [comment]
@aaronlehmann We call pre-allocate internally, which should almost like a noop in advanced fs. Also this is done in parallel with other disk operations. However, on some fs it might equal to a huge write. The huge write might block other on going small writes.

**Comment by aaronlehmann** [comment]
>  @aaronlehmann We call pre-allocate internally, which should almost like a noop in advanced fs. Also this is done in parallel with other disk operations. However, on some fs it might equal to a huge write. The huge write might block other on going small writes.

Yes, I think this is what's happening. I was testing on OS X, which has a very primitive filesystem. I just tested on Linux, and I'm not seeing the same problem there. The tests appear to run significantly *faster* with the newer etcd repo vendored.

Still, I'd like to find a resolution for this, since it's causing problems with the test on Macs (and the other issue about making it easier to test WAL rotation would be nice to fix). Would you accept a PR to export `segmentSizeBytes`, so tests could override it in `init`?

**Comment by xiang90** [comment]
@aaronlehmann Yes. Please send a patch. Thank you!
