### ISSUE TITLE
raft: raft log `must_check_outofbounds` may meet overflow error.

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#6143]
@xiang90 

We try port raft in https://github.com/pingcap/tikv/pull/912 but find the overflow panic. Seem that https://github.com/coreos/etcd/blob/master/raft/log.go#L342, if the peer has no log, the first index is 1 and last index is 0.
If go, `0 - 1 + 1` is ok, but in rust, this causes panic. 
Do we need to check this case here?

**Comment by xiang90** [comment]
@siddontang Sending a patch to make the checking stricter is fine with me

**Comment by xiang90** [comment]
already fixed by #6157
