### ISSUE TITLE
etcd range response count attribute is coming as limit + 1

### ISSUE THREAD

**Issue by shyamradhakrishnan** [coreos/etcd#6145]
The scenario is as follow. I do few put requests with keys as follows
./etcdctl put key1 value1
./etcdctl put key2 value2
./etcdctl put key3 value3
./etcdctl put key4 value4
./etcdctl put key5 value5

Then I do  a  range response as follows
./etcdctl --write-out="json" get --limit="2" key1 key5

In the resulting response, the count variable is coming as 3("count":3)

Is this expected? I think the count either should be the number of keys in the range which is 5, or the limit value which is 2. I am not sure if a count of 3 will be helpful in this case. Please provide your comments.

**Comment by xiang90** [comment]
It is not expected. Seems like a bug. We will look into this.
