### ISSUE TITLE
etcd transaction returning incremented index even though the operation did not happen

### ISSUE THREAD

**Issue by shyamradhakrishnan** [coreos/etcd#6146]
If an etcd transaction is executed which could not delete the specified key, then in the return response, the revision is incremented, even though the revision is not actually incremented in the etcd store.
suppose the index before this operation is 6
For example
./etcdctl --write-out="json" txn -i
compares:

success requests (get, put, delete):
del "key8" 

failure requests (get, put, delete):

Here key8 does not exist. In the resultant response, the index is incremented
{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":7,"raft_term":2},"succeeded":true,"responses":[{"Response":{"ResponseDeleteRange":{"header":{"revision":6}}}}]}

But if I do another get operation, the index is still at 6.

**Comment by xiang90** [comment]
Your txn does not fail. It is executed with deleting nothing. Txn only fails if the operations are invalid (attaching a non existing lease to a key for example).

**Comment by shyamradhakrishnan** [comment]
Sorry, I dont think I made myself clear. The transaction did not fail, but since ther was no operation performed(i.e. the key could not be deleted), the revision in the transaction response should not be incremented. 
So for example the transaction response in my case was 
{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":28,"raft_term":3},"succeeded":true,"responses":[{"Response":{"ResponseDeleteRange":{"header":{"revision":27}}}}]}

and another put request immediately after the txn request has following response
{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":28,"raft_term":3}}

Please note that the same revisions, which should not have happened

**Comment by xiang90** [comment]
@shyamradhakrishnan Now I see what you were saying. I will take a closer look.
