### ISSUE TITLE
Question about etcd3 security

### ISSUE THREAD

**Issue by eho-eho** [coreos/etcd#6148]
How did etcd3 security model change from etcd2? 
I could not find any documentation or examples of how to use TLS with etcd3. The only doc that talks about security model in any depth that I have managed to find is: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md which talks about etcd2 security model.
Is etcd3 peer to peer security model the same as in etcd2?
How to configure etcd3 client and server to use TLS with client certs?
Thanks.

**Comment by gyuho** [comment]
@eho-eho 

> How to configure etcd3 client and server to use TLS with client certs?

For users, setup should be pretty much the same as etcdv2 as in https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md#basic-setup.

If you try out with example, please try https://github.com/coreos/etcd/tree/master/hack/tls-setup.

**Comment by eho-eho** [comment]
Thank you for your response. If I understand you answer correctly, the security model did not change from v2 to v3, correct? 
How would you pass client certificates to the etcd3 client?

**Comment by gyuho** [comment]
This is frequently asked. I will document exactly how you can do it with code examples, shortly.

**Comment by xiang90** [comment]
> If I understand you answer correctly, the security model did not change from v2 to v3, correct? 
How would you pass client certificates to the etcd3 client?

Yes. It is correct. I am closing this issue.

**Comment by eho-eho** [comment]
How would you pass client certificates to the etcd3 client?

**Comment by heyitsanthony** [comment]
@eho-eho By setting the `TLS` field in `clientv3.Config` (https://godoc.org/github.com/coreos/etcd/clientv3#Config)
