### ISSUE TITLE
why become so slower when enable auth?

### ISSUE THREAD

**Issue by johnyannj** [coreos/etcd#6159]
time curl -H "Authorization: Basic XXXXXXXXXXXX" http://192.168.22.161:2379/v2/keys/a
{"errorCode":100,"message":"Key not found","cause":"/a","index":8162}

**real    0m0.137s**
user    0m0.000s
sys     0m0.000s

time curl  http://192.168.22.161:2379/v2/keys/a
{"errorCode":100,"message":"Key not found","cause":"/a","index":8162}

**real    0m0.003s**
user    0m0.004s
sys     0m0.000s

**Comment by johnyannj** [comment]
v2.3.6

**Comment by mitake** [comment]
It is because v2 auth executes costly bcrypt function in every request processing. You would be able to avoid the overhead with TLS certification that can be enabled by `--client-cert-auth`.

**Comment by xiang90** [comment]
@johnyannj As @mitake mentioned, etcd v2 auth check auth per request. You can enable client-cert-auth and add username into CN of the client cert. Then it should be much faster.
