### ISSUE TITLE
Revisiting clientv3.New() connection model

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#6162]
In v2 client New(), it just creates some http transports and connections happen when you make an api call. Hence it won't block on New().

In v3 client New(), it dials out to establish the grpc connection. It blocks and returns error if it failed to connect.

It would be ideal if we can support non-blocking clientv3.New() for some use cases.

**Comment by hongchaodeng** [comment]
@xiang90 @heyitsanthony @timothysc

**Comment by timothysc** [comment]
This was the root of the UT failures when enabling v3client, but it also exposed suppositions on some of the k8s tests.  
/cc @wojtek-t

**Comment by wojtek-t** [comment]
Great catch - thanks for letting me know.

**Comment by timothysc** [comment]
@smarterclayton do we have any requirements on apiserver startup behavior blocking vs. non-blocking?

**Comment by smarterclayton** [comment]
Right now we do polling to see if the etcd server is up before continuing, then we fail if it never responds in X seconds.
