### ISSUE TITLE
TestNetworkPartition5MembersLeaderInMajority: member has no leader

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6176]
via https://semaphoreci.com/coreos/etcd/branches/master/builds/770

```
--- FAIL: TestNetworkPartition5MembersLeaderInMajority (7.29s)
    cluster_test.go:451: create on unix://127.0.0.1:21206.23388.sock error: client: etcd member unix://127.0.0.1:21206.23388.sock has no leader
```

**Comment by gyuho** [comment]
Currently we disable all etcd logs below `CRITICAL` level when testing.

https://github.com/coreos/etcd/blob/master/integration/v2_http_kv_test.go#L34-L36

Tests like this are hard to reproduce (I have been running this around 7,000 rounds with no failure in my machine).

Should we enable this to `INFO` level to make it easier?

**Comment by gyuho** [comment]
nvm. turning on log in INFO level takes test too long to finish.

**Comment by fanminshi** [comment]
failing via https://semaphoreci.com/coreos/etcd/branches/pull-request-7443/builds/10

**Comment by gyuho** [comment]
Haven't seen for awhile. Will reopen when it happens.
