### ISSUE TITLE
does etcd support mutual authentication?

### ISSUE THREAD

**Issue by yorksen** [coreos/etcd#6178]
As I know, etcd supports SSL authentication between client and etcd,  etcd peers as well.  but the official documents doesn't mention whether it support mutual authentication and how to configure it.  

please give me some suggestion.

**Comment by xiang90** [comment]
Client can provide its own TLS configuration in go client(https://golang.org/pkg/crypto/tls/#Config). Client should verify servers by default with the given cert. You can disable it by setting skipInsecure to false though. 

It should be similar in other language bindings that supports TLS.

For curl, you can do -k to skip server verification. It verifies server with the cert on your local machine by default.
