### ISSUE TITLE
etcdctl not reading username from environment

### ISSUE THREAD

**Issue by cskarby** [coreos/etcd#6180]
According to https://github.com/coreos/etcd/blob/master/etcdctl/READMEv2.md#username-and-password the environment variable ETCDCTL_USERNAME should be used if set, but it seems to have no impact. Autentication is enabled for etcd and all permissions for role guest are removed.

$ etcdctl --version
etcdctl version 2.3.2
$ export ETCDCTL_USERNAME=root:password
$ etcdctl ls /
Error:  110: The request requires user authentication (Insufficient credentials) [0]
$ etcdctl -u $ETCDCTL_USERNAME ls /
/coreos.com
$ etcdctl -u $ETCDCTL_USERNAME role get guest
Role: guest
KV Read:
KV Write:

**Comment by heyitsanthony** [comment]
@cskarby This feature is not in the 2.3 branch (cf. https://github.com/coreos/etcd/blob/release-2.3/etcdctl/README.md); it was introduced in 3.0.

**Comment by xiang90** [comment]
@heyitsanthony is right. You can get a new version of etcdctl from current release branch (3.0).
