### ISSUE TITLE
request cluster ID mismatch (got  $id_a want $id_b )

### ISSUE THREAD

**Issue by workhardcc** [coreos/etcd#6181]
version:3.04
There is a vm I used to be one node of a etcd cluster. Now I want to change this vm to be a independent etcd cluster(just itself). I stop the etcd service first, then remove the previous data-dir to clean up the member information(`rm -rf /home/etcd_data/*`, even last reboot the vm). However,  when I start it (`systemctl start etcd`) there are a lots of error log such as : 

> request cluster ID mismatch (got dfc9373077e01b35 want 3b7efc3170756a6b)

my etcd.conf as below:

> ETCD_DATA_DIR="/home/etcd_data"
> 
> ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
> ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379,http://0.0.0.0:4001"
> 
> ETCD_INITIAL_ADVERTISE_PEER_URLS="http://100.1.1.1:2380"
> 
> ETCD_ADVERTISE_CLIENT_URLS="http://100.1.1.1:2379"
> ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
> 
> ETCD_NAME="node1"
> ETCD_INITIAL_CLUSTER="node1=http://100.1.1.1:2380"
> ETCD_INITIAL_CLUSTER_STATE="new"

**Comment by heyitsanthony** [comment]
@workhardcc did you remove the VM from the cluster with `etcdctl member remove`? The members from the old cluster are probably still trying to connect to the VM.

**Comment by workhardcc** [comment]
It worked! Thanks a lot!
