### ISSUE TITLE
TestCtlV3MemberRemove: expected 2, got 3

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6192]
via https://semaphoreci.com/coreos/etcd/branches/master/builds/786

```
--- FAIL: TestCtlV3MemberRemove (3.23s)
	ctl_v3_member_test.go:100: expected 2, got 3
```

The remove ack is coming from one machine but a member list request goes to another machine. This means the list response may be returned after the member remove raft commit but before the remove is applied, leading to stale data.

It is fairly easy to reproduce:
```patch
-                       f := func(context.Context) { s.applyAll(&ep, &ap) }
+                       f := func(context.Context) {
+                               if rand.Intn(2) == 0 {
+                                       time.Sleep(100 * time.Millisecond)
+                               }
+                               s.applyAll(&ep, &ap)
+                       }
```

**Comment by xiang90** [comment]
@heyitsanthony Do you have a solution to this in mind? we can do a l-read, then do member list.

**Comment by heyitsanthony** [comment]
@xiang90 yeah, that's the way to do it. Some extra care is needed to ensure the l-read is on the same member that runs the member list rpc, though.
