### ISSUE TITLE
Issue about logs

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6201]
As we all know, etcd makes many logs when the cluster is running, but I can't find the logs about user's operations. I wonder that etcd has specified the directory of logs about operations. Can it record the operations of user, just like Mysql? 
I'm looking forward to the reply!

**Comment by xiang90** [comment]
We do not log user operations. There is a feature request here: https://github.com/coreos/etcd/issues/5019. Please comment there. Closing this one since it is a dup.
