### ISSUE TITLE
Issue about client-server logs

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6202]
When a connection is established between the client and the server，will the server record logs? I believe that the source code contains the logic but I didn't find it.

**Comment by heyitsanthony** [comment]
Yes, but it will only log when `--debug` is enabled:
https://github.com/coreos/etcd/blob/master/etcdserver/api/v2http/client.go#L133
https://github.com/coreos/etcd/blob/master/etcdserver/api/v2http/http.go#L89-L94

**Comment by xiang90** [comment]
No audit logging, just debug logging as @heyitsanthony pointed out. If you want to see audit logging, comment at https://github.com/coreos/etcd/issues/5019. Thanks.
