### ISSUE TITLE
query :raft:/storage.go Term func not handling index out of bound exception and allowing panic for same

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6203]
I wanted to know if there is any specific reason for not handling index out of bound exception in raft/storage.go Term(i uint64) for index > memory storage entires?

**Comment by xiang90** [comment]
I do not quite understand the question. Can you be more specific?

**Comment by sinsharat** [comment]
@xiang90 : 
// Term implements the Storage interface.
func (ms *MemoryStorage) Term(i uint64) (uint64, error) {
	ms.Lock()
	defer ms.Unlock()
	offset := ms.ents[0].Index
	if i < offset {
		return 0, ErrCompacted
	}
	return ms.ents[i-offset].Term, nil
}
In the above code if [i-offset] > len(ms.ents) index out of bound exception will occur. and its not handled.

Even in the test case for this it is tested assuming it will throw panic for index out of bound exception. So wanted to know if its delibrately not handled for a specific reason.
