### ISSUE TITLE
Shoud WatchResponse carry the key with watch_id when created is true?

### ISSUE THREAD

**Issue by feidao2002** [coreos/etcd#6213]
# Shoud WatchResponse carry the key with watch_id when created is true?

When I create a watch, etcd would response with watch_id and created is true, but I can't get the key from this response.

Shoud WatchResponse carry the key with watch_id when created is true?

in rpc.proto:
message WatchResponse {
  ResponseHeader header = 1;
  // watch_id is the ID of the watcher that corresponds to the response.
  int64 watch_id = 2;
  // created is set to true if the response is for a create watch request.
  // The client should record the watch_id and expect to receive events for
  // the created watcher from the same stream.
  // All events sent to the created watcher will attach with the same watch_id.
  bool created = 3;
  // canceled is set to true if the response is for a cancel watch request.
  // No further events will be sent to the canceled watcher.
  bool canceled = 4;
  // compact_revision is set to the minimum index if a watcher tries to watch
  // at a compacted index.
  //
  // This happens when creating a watcher at a compacted revision or the watcher cannot
  // catch up with the progress of the key-value store. 
  //
  // The client should treat the watcher as canceled and should not try to create any
  // watcher with the same start_revision again.
  int64 compact_revision  = 5;

  repeated mvccpb.Event events = 11;
}

**Comment by heyitsanthony** [comment]
If there's only one outstanding watch create request on a watch stream, then that isn't necessary. Returning only the key isn't enough for correctly supporting overlapping watch create requests; the create response would need to embed the entire watch create request to correctly map from request to response. By then you'll need to keep track of all the outstanding watch requests on that single watch stream to figure out how to dispatch the create responses, which is as difficult (if not more) as serializing in the first place.

So, no.

**Comment by xiang90** [comment]
@feidao2002 I close this since @heyitsanthony already provided the answer. Let us know if it is not good enough for you.
