### ISSUE TITLE
raft: a doubt about why not call pr.pause() when receiving  pb.MsgUnreachable

### ISSUE THREAD

**Issue by es-chow** [coreos/etcd#6214]
In `stepLeader`, `pr.pause()` is called after receiving `pb.MsgSnapStatus`, but is not called after receiving `pb.MsgUnreachable`, is there any specific reason?

`pr.pause` can be called in `sendAppend()` if a `MsgApp` with entries is sent out. But before that, many `MsgApp` without entries but carry increased `Commit` may be sent out. If we add `pr.pause()` after  after receiving `pb.MsgUnreachable`, those message can be discarded too.

**Comment by xiang90** [comment]
@es-chow 

We only pause the probing when it is certain that the probing will fail or when we want to ensure the only one inflight property. 

If we receive a msgUnreachable, raft should continue to probe. That is how raft leader can find a failed follower back online.

Do you have an issue with the current behavior? Is it causing problems to your application? If so, can you write a simple program to illustrate it? Thanks!

**Comment by es-chow** [comment]
It's not produced in our application, it may be a cornor case. It may be reproduced by the following snippet under `raft_test.go.`
```
func TestSuspiciousMsgsForUnreachableNode(t *testing.T) {
    nt := newNetwork(nil, nil, nil, nil)
    nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgHup})

    for i := 0; i < 3; i++ {
        nt.sendOnly(pb.Message{From: 1, To: 1, Type: pb.MsgProp, Entries: []pb.Entry{{}}})
    }
    // send MsgApp to 2,3,4
    nt.stepOneRound(1)
    // node 4 send MsgAppReso to 1.
    nt.stepOneRound(4)
    nt.send(pb.Message{From: 4, To: 1, Type: pb.MsgUnreachable})
    nt.stepOneRound(1, 2, 3)
    // 3 more MsgApp with commit without entries will send to node 4.
}
func (nw *network) sendOnly(msgs ...pb.Message) {
    for _, m := range msgs {
        p := nw.peers[m.To]
        p.Step(m)
    }
}

func (nw *network) stepOneRound(ids ...uint64) {
    var msgs []pb.Message
    for _, id := range ids {
        p := nw.peers[id]
        msgs = append(msgs, nw.filter(p.readMessages())...)
    }
    for _, m := range msgs {
        p := nw.peers[m.To]
        p.Step(m)
    }
}
```

**Comment by xiang90** [comment]
@es-chow I do not think it is a problem actually. it does not really hurt to call pause either. If it causes a problem to your application, then I am fine with adding a pause.

**Comment by es-chow** [comment]
As of now it didn't cause any problem, so just close it.
