### ISSUE TITLE
[logic] Issue about the connection between client and server

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6216]
I'm using the etcd whose version is 3.0.1 and I know that v3 uses grpc for connection between client and server. Where shoud I insert code if I want to record the logs when connection is built or broken between client and server  ** on server side**? I have tried to add codes in the function `grpcHandlerFunc`  , but the result is not the same as expected.

**Comment by heyitsanthony** [comment]
I don't think the TCP connection details are reliably exposed through grpc on the server side. Ask on https://github.com/grpc/grpc-go/?

**Comment by xiang90** [comment]
@shuqilou It can be done at net.Listener level. You can build your own listener that logs every connection creation. We do not have plan to do this in etcd upstream at least for now.
