### ISSUE TITLE
units for latency metrics from stats endpoint

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [coreos/etcd#6217]
Hey all,

The etcd leader stats endpoint returns metrics for latency to followers.  The field is simply called "Latency" and so neither the field name nor the API docs [0] make it clear what unit these metrics are reported in.  The code [1] suggests it's a time.Duration being divided by 1000000.0, so I take that to mean the units are milliseconds [2], but maybe there are layers between that code and what the API Handler func actually does that multiplies or divides the number again before responding.

Are the units in the response payload indeed milliseconds?

[0] https://coreos.com/etcd/docs/latest/api.html#leader-statistics
[1] https://github.com/coreos/etcd/blob/66e5e4f298e66bdd72307336935e192aa66097c0/etcdserver/stats/leader.go#L92-L101
[2] https://play.golang.org/p/D2keryRnnY

Thanks,
Amit

**Comment by xiang90** [comment]
Yes. It is ms. We now have a much better metrics: see https://github.com/coreos/etcd/blob/master/Documentation/metrics.md.

The old one will be depreciated eventually.

**Comment by Amit-PivotalLabs** [comment]
Thanks @xiang90 

Do you have a rough ETA on when the old ones will be deprecated.  On the order of days, weeks, months, years?

**Comment by xiang90** [comment]
When we start to deprecate v2 API. Probably months to years.

**Comment by Amit-PivotalLabs** [comment]
Great, thanks.
