### ISSUE TITLE
v2/keys: support content-type text/plain

### ISSUE THREAD

**Issue by slawosz** [coreos/etcd#623]
Hi,
have you considered to return just value of key? It would be easier to use etcd in scripts. 

Example:
```
curl --header Content-Type:"text/xml" -L http://127.0.0.1:4001/v2/keys/message
```
would return
````
some_value
```

Thanks!

**Comment by johnjansen** [comment]
+1

**Comment by philips** [comment]
@yaronr Could you clarify what features `etcdctl` is missing by filing a new issue against it?

**Comment by philips** [comment]
@johnjansen Could you use etcdctl here to get this feature instead?

**Comment by xiang90** [comment]
We probably are not going to change v2 API. I suggest you to try etcdctl to interactive with etcd if you want to do something really simple.

**Comment by kazhang** [comment]
What if I want to retrieve a value on a machine without etcdctl installed?  One has to grep the result to get the value in a shell script :(

**Comment by cmoad** [comment]
+1 as many docker images include curl but not etcdctl.

**Comment by marcellodesales** [comment]
:+1: @cmoad @kazhang
