### ISSUE TITLE
How to deploy etcd in kubernetes?

### ISSUE THREAD

**Issue by GregoryIan** [coreos/etcd#6246]
We are currently experiencing some problems about deploying etcd in kubernetes. 
1. The main is  how to auto-scaling etcd ,  if I  have inited cluster A,B,C(node), how to add D into the cluster through k8s replication.
2. etcd is stateful, then how to recover from fail and upgrade in k8s.

 **_Only manual now?_**

Maybe you have encountered these problems, have a better suggestion? Or please support it. :):)

**Comment by xiang90** [comment]
Why do you want to auto-scaling etcd? What is your use case?

**Comment by GregoryIan** [comment]
Our master control plane embed etcd, we don't want a different scaling-out ,  in addition change the replication count to scale service is cool for user.

**Comment by xiang90** [comment]
@GregoryIan You probably do not want to scale etcd with your master. The more etcd nodes you have the worse write performance it would have. The suggested etcd deployment should be as static as possible. So it is probably a bad idea to couple etcd with your master component.

With all these said, we are working on a etcd controller for k8s. However, that is a separate project and out of the scope of etcd itself.

**Comment by GregoryIan** [comment]
Got it! Thanks!
Ignoring the scaling problem, do you have suggestions for etcd recover  from fail and upgrade in k8s? (In K8s one old etcd pod fail, it will restart a new one, how to  keep the old one state elegantly?)

**Comment by GregoryIan** [comment]
@xiang90 can you give me a etcd controller for k8s project url? Thanks

**Comment by hongchaodeng** [comment]
@GregoryIan 
This is out of scope of etcd.
Please ask your questions in kubernetes community: https://github.com/kubernetes/community/tree/master/sig-apps

**Comment by xiang90** [comment]
@GregoryIan We are still working on it. It is not open sourced yet. We plan to do so. @hongchaodeng will give a demo in early setp on k8s community hangout. If you are interested, please attend :)

**Comment by GregoryIan** [comment]
@xiang90 Thanks again! 
@hongchaodeng Thanks!
