### ISSUE TITLE
Issue about client connection

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6250]
I have found the logical of connection between client and server just like below. If I send a request to server then I will obtain a log such as "Received a client connection from: IP:Port", but when the request is interrupted, then the connection should be closed, but where is the specific place to close the connection in the code below?What I want to do is to record logs when the connection between client and server is interrupted and I have added some records after close function but they didn't work.
`func (m *cMux) Serve() error {
	var wg sync.WaitGroup

	defer func() {
		close(m.donec)
		fmt.Println("#####################################")
		wg.Wait()

		for _, sl := range m.sls {
			close(sl.l.connc)
			// Drain the connections enqueued for the listener.
			for c := range sl.l.connc {
				_ = c.Close()
			}
		}
		fmt.Printf("The client connection has been closed......")
	}()

	for {
		c, err := m.root.Accept()
		fmt.Println(c)
		if err != nil {
			fmt.Println("Error accepting:", err.Error())
			if !m.handleErr(err) {
				return err
			}
			continue
		}

		fmt.Printf("Received a client connection from: %s\n", c.RemoteAddr().String())
		wg.Add(1)
		go m.serve(c, m.donec, &wg)
	}
}

func (m *cMux) serve(c net.Conn, donec <-chan struct{}, wg *sync.WaitGroup) {
	defer wg.Done()

	muc := newMuxConn(c)
	for _, sl := range m.sls {
		for _, s := range sl.ss {
			matched := s(muc.getSniffer())
			if matched {
				select {
				case sl.l.connc <- muc:
					fmt.Println(muc)
				case <-donec:
					fmt.Printf("The client connection %s has been closed......", c.RemoteAddr().String())
					_ = c.Close()
				}
				return
			}
		}
	}

	_ = c.Close()
	fmt.Printf("The client connection %s has been closed......", c.RemoteAddr().String())
	err := ErrNotMatched{c: c}
	if !m.handleErr(err) {
		_ = m.root.Close()
	}
}`

**Comment by xiang90** [comment]
Can you please tell us your motivation first? What are the features you want? Are you trying to submit a patch to etcd for a feature? Are you trying to add some features on a forked version of etcd? 

etcd uses gRPC which hides all connection details for both server and client. And we do not want to expose these details.

**Comment by xiang90** [comment]
@shuqilou I close this since it is inactive and seems not an etcd related issue. Please reopen if you want a further discussion. Thank you!
