### ISSUE TITLE
documentation/ops_guide: References an issue that is probably a etcd/dep issue, not go issue

### ISSUE THREAD

**Issue by kardianos** [coreos/etcd#6256]
On current master 1c989edb476457369d936ed180d1995f55e77e8e
/Documentation/op-guide/supported-platform.md
says
> etcd has known issues on 32-bit systems due to a bug in the Go runtime

This seems incorrect. Unless you are suggesting that all int64 in structs should be aligned to 64-bit boundaries and lead to increased memory usage for the common case. Likewise, it seems impossible for a compile to check all uses of an exported symbol to check if it is used with "sync/atomic". 

Unless I'm misunderstanding the scope of the issue, an initial grep only shows 14 files that use "sync/atomic", it should be easy to do a check for alignment on these files.

At the very least, it seems incorrect to blame this on a bug in the Go runtime. I do understand there may be limits with how memory is mapped and that there isn't a builder for those archs or other limits may apply for general "support".

**Comment by heyitsanthony** [comment]
@kardianos No. It's a Go problem.

See:
https://github.com/golang/go/issues/599
https://github.com/golang/go/issues/11891
https://golang.org/pkg/sync/atomic/#pkg-note-BUG
