### ISSUE TITLE
Possible to use CLIENT_CERT_AUTH in etcd cluster

### ISSUE THREAD

**Issue by sachincab** [coreos/etcd#6258]
Hi Team,

We are trying to setup TLS for 3 nodes etcd cluster behind AWS ELB used by Kubernetes.

As per below document, it is possible to use client_auth for peer communication within cluster. However is it possible to use client_cert_auth for the communication from kube-apiserver in this case?

https://coreos.com/etcd/docs/latest/security.html#example-3-transport-security--client-certificates-in-a-cluster

I tried to generate client certificate using same CA  but it does not seems to be working.
Enabled this flag: Environment="ETCD_CLIENT_CERT_AUTH=true"

Another thing to confirm, I guess it is possible to generate and use individual TLS assets for peer to peer communication using same CA? 

All environment variables for reference:
Environment="ETCD_ADVERTISE_CLIENT_URLS=https://$private_ipv4:2379"
Environment="ETCD_DATA_DIR=/mnt/data"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=https://$private_ipv4:2380"
Environment="ETCD_INITIAL_CLUSTER=etcd1=https://${host1}:2380,etcd2=https://${host2}:2380,etcd3=https://${host3}:2380"
Environment="ETCD_INITIAL_CLUSTER_STATE=new"
Environment="ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd"
Environment="ETCD_LISTEN_CLIENT_URLS=https://$private_ipv4:2379,https://127.0.0.1:2379"
Environment="ETCD_LISTEN_PEER_URLS=https://$private_ipv4:2380"
Environment="ETCD_NAME=${etcd_name}"
Environment="ETCD_PEER_TRUSTED_CA_FILE=/etc/etcd3/ssl/kube-ca.pem"
Environment="ETCD_PEER_CERT_FILE=/etc/etcd3/ssl/kube-etcd.pem"
Environment="ETCD_PEER_KEY_FILE=/etc/etcd3/ssl/kube-etcd-key.pem"
Environment="ETCD_PEER_CLIENT_CERT_AUTH=true"
Environment="ETCD_TRUSTED_CA_FILE=/etc/etcd3/ssl/kube-ca.pem"
Environment="ETCD_CERT_FILE=/etc/etcd3/ssl/kube-etcd.pem"
Environment="ETCD_KEY_FILE=/etc/etcd3/ssl/kube-etcd-key.pem"
Environment="ETCD_CLIENT_CERT_AUTH=true"

Please let me know if you need any more information on this.
Thanks!

**Comment by gyuho** [comment]
Do you have error message?

**Comment by sachincab** [comment]
To be more specific:
We are using AWS elb in front 3 etcd nodes.

**Scenario-1:** When we use TCP passthrough on ELB then etcd connections is working fine with valid client certificates.

**ELB listener details:**
Load Balancer Protocol: TCP
Load Balancer Port: 2379
Instance Protocol: TCP
Instance Port: 2379
Cipher: N/A
SSL Certificate: N/A

**Scenario-2:** When we use HTTPS on ELB with valid certificate on ELB and ETCD nodes, it just hangs after TLS handshake using client certificates.

**ELB listener details:**
Load Balancer Protocol: HTTPS
Load Balancer Port: 2379
Instance Protocol: HTTPS
Instance Port: 2379
Cipher: Default
SSL Certificate: etcd-cert-experiment (IAM

Please find below curl output:
```
curl -v https://kube-experiment-etcd.dev.xxxxx.net:2379/v2/members --cacert kube-ca.pem --cert kube-etcd-client.pem --key kube-etcd-client-key.pem
*   Trying 172.18.2.236...
* Connected to kube-experiment-etcd.dev.xxxxxx.net (172.18.2.236) port 2379 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: kube-ca.pem
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  start date: Aug 25 13:08:58 2016 GMT
*  expire date: Jan 27 13:08:58 2020 GMT
*  subjectAltName: host "kube-experiment-etcd.dev.xxxxx.net" matched cert's "kube-experiment-etcd.dev.xxxxxx.net"
*  SSL certificate verify ok.
> GET /v2/members HTTP/1.1
> Host: kube-experiment-etcd.dev.xxxxxx.net:2379
> User-Agent: curl/7.50.1
> Accept: */*

```

Is it AWS ELB changing some behaviour while sending request to ETCD nodes over HTTPS?
I am not 100% sure how to verify what AWS ELB is sending back to ETCD nodes.

TCP passthrough from AWS ELB works fine with client certificate.

```
curl -i https://kube-experiment-etcd.dev.xxxxxx.net:2379/v2/members --cacert kube-ca.pem --cert kube-etcd-client.pem --key kube-etcd-client-key.pem
HTTP/1.1 200 OK
Content-Type: application/json
X-Etcd-Cluster-Id: 10fa2a2548bbce72
Date: Thu, 25 Aug 2016 15:45:51 GMT
Content-Length: 383

{"members":[{"id":"236f16c86ebc97fe","name":"etcd3","peerURLs":["https://172.18.2.12:2380"],"clientURLs":["https://172.18.2.12:2379"]},{"id":"4dad3925286aaf0c","name":"etcd2","peerURLs":["https://172.18.2.11:2380"],"clientURLs":["https://172.18.2.11:2379"]},{"id":"ca3c0b268a7506b8","name":"etcd1","peerURLs":["https://172.18.2.10:2380"],"clientURLs":["https://172.18.2.10:2379"]}]}
```

Hope this clarifies a bit.
Please let me know if you need any more information on this.

**Comment by gyuho** [comment]
> HTTPS on ELB with valid certificate on ELB and ETCD nodes

I am not familiar with ELB, but does ELB connect to etcd with static IPs? How do you generate certs? If etcd doesn't print out any errors, I think it should be misconfiguration in your kubernetes?

**Comment by gyuho** [comment]
@sachincab Any updates?

**Comment by gyuho** [comment]
I assume this is Kubernetes specific configuration issue.

Please reopen when you have more details (etcd error logs will be helpful). 

Thanks!
