### ISSUE TITLE
etcd tls and dns resolution

### ISSUE THREAD

**Issue by sks** [coreos/etcd#6262]
Hi team!

We are attempting to use the latest etcd v2 and we are running into some issues, coming from v2.1.1.

We are trying to start an etcd cluster in TLS mode using something like:
```
$ etcdctl
...
 --listen-peer-urls 'https://0.0.0.0:7001' \
 --listen-client-urls 'https://0.0.0.0:4001' \
 --initial-advertise-peer-urls 'https://etcd-z1-0.etcd.service.cf.internal:7001' \
 --advertise-client-urls 'https://etcd-z1-0.etcd.service.cf.internal:4001' \
 --initial-cluster 'etcd-z1-0=https://etcd-z1-0.etcd.service.cf.internal:7001' \
```

however we get the following error:

```
2016/08/24 23:15:10 etcdmain: listening for client requests on https://0.0.0.0:4001
2016/08/24 23:15:10 netutil: could not resolve host etcd-z1-0.etcd.service.cf.internal:7001
2016/08/24 23:15:10 etcdmain: stopping listening for client requests on https://0.0.0.0:4001
2016/08/24 23:15:10 etcdmain: stopping listening for peers on https://0.0.0.0:7001
2016/08/24 23:15:10 etcdmain: advertise URLs of "etcd-z1-0" do not match in --initial-advertise-peer-urls [https://etcd-z1-0.etcd.service.cf.internal:7001] and --initial-cluster [https://etcd-z1-0.etcd.service.cf.internal:7001]
```

After some debugging , we found that [this change](https://github.com/coreos/etcd/compare/v2.1.1...v2.1.2#diff-8ce200179d9471fe878deb75be213f23R96) seems to be causing us trouble because of how our dns service discovery mechanism works.

We only serve DNS once we can see that the process is up and running, so that means we can't resolve `https://etcd-z1-0.etcd.service.cf.internal:7001` until etcd is running. Although with the latest version etcd won't run until it is able to resolve.

It seems like there could be a wait period before etcd validates the `initial-advertise-peer-urls/initial-cluster URLs`?

Or make the check optional?

Any other suggestions are appreciated.

Thanks,
@christianang and @sks

**Comment by heyitsanthony** [comment]
Bootstrap using IP then `etcdctl member update` with DNS names?

**Comment by xiang90** [comment]
@sks 

> ow our dns service discovery mechanism works.

Why not change the dns mechanism? It makes more sense to setup DNS first, then start etcd which depends on that DNS. No?

**Comment by sks** [comment]
Thanks @xiang90 & @heyitsanthony for the assistance,

We ended up disabling the dns health_check.

**Comment by akamalov** [comment]
@sks, wondering where did you disable health_check? I am having exactly the same issue...

**Comment by sks** [comment]
we disabled the dos health_check for the registered service as it was one of a use case
