### ISSUE TITLE
"latest" security model doc invalid examples

### ISSUE THREAD

**Issue by michael-px** [coreos/etcd#6268]
https://coreos.com/etcd/docs/latest/security.html

describes how to setup etcd to use single node server-client configurations using keys generated by 

https://coreos.com/os/docs/latest/generate-self-signed-certificates.html

The security page says to use Certificate Signing Requests instead of Certificate files.  When I attempt to start my cluster with CSRs, it won't start.  If I switch to pem files tied to the IP addresses for the machine (AWS internal and external, plus DNS name), the node will start.

Where can I find directions that are up to date?  

http://blog.skrobul.com/securing_etcd_with_tls/

says much of the security information on the CoreOS site is just plain wrong.

**Comment by michael-px** [comment]
I also took the code from

https://coreos.com/os/docs/latest/generate-self-signed-certificates.html

> echo '{"CN":"CA","key":{"algo":"rsa","size":2048}}' | cfssl gencert -initca - | cfssljson -bare ca -
> echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json
> export ADDRESS=192.168.122.68,ext1.example.com,coreos1.local,coreos1
> export NAME=server
> echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -hostname="$ADDRESS" - | cfssljson -bare $NAME
> export ADDRESS=
> export NAME=client
> echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' | cfssl gencert -config=ca-config.json -hostname="$ADDRESS" - | cfssljson -bare $NAME

This barfs too.

I've been able to get a cluster up and running using peer certificates between themselves, but I can't seem to generate a wildcard client cert that will allow me to do a simple **etcdctl member list**.

https://coreos.com/etcd/docs/latest/security.html

has examples but I get errors:

curl --cacert /etc/ssl/etcd/px-ca.pem --cert /etc/ssl/etcd/px-client.pem --key /etc/ssl/etcd/px-client-key.pem -L https://127.0.0.1:2379/health -v
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/ssl/etcd/px-ca.pem
  CApath: none
* NSS error -12263 (SSL_ERROR_RX_RECORD_TOO_LONG)
* SSL received a record that exceeded the maximum permissible length.
* Closing connection 0
curl: (35) SSL received a record that exceeded the maximum permissible length.

**Comment by michael-px** [comment]
I found that 2379 wasn't listening, so I fixed that. Now I get

etcdctl --key-file /etc/ssl/etcd/px-client-key.pem --cert-file /etc/ssl/etcd/px-client.pem --debug member list 
start to sync cluster using endpoints(http://127.0.0.1:4001,http://127.0.0.1:2379)
cURL Command: curl -X GET http://127.0.0.1:4001/v2/members
got endpoints(https://52.43.85.104:2379,https://52.42.14.15:2379,https://52.43.243.25:2379) after sync
Cluster-Endpoints: https://52.43.85.104:2379, https://52.42.14.15:2379, https://52.43.243.25:2379
cURL Command: curl -X GET https://52.43.85.104:2379/v2/members
cURL Command: curl -X GET https://52.42.14.15:2379/v2/members
cURL Command: curl -X GET https://52.43.243.25:2379/v2/members
client: etcd cluster is unavailable or misconfigured

**Comment by gyuho** [comment]
How do you create client certs?

**Comment by michael-px** [comment]
from
https://coreos.com/os/docs/latest/generate-self-signed-certificates.html


echo '{"CN":"px-client","hosts":[""],"key":{"algo":"rsa","size":2048}}' | \
        cfssl gencert -ca=px-ca.pem -ca-key=px-ca-key.pem
-config=px-ca-config.json \
                -hostname="*" -profile=client - | cfssljson -bare px-client

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
@michael-px What is your etcd version? Can you please attach configuration and logs from all your etcd servers?

**Comment by michael-px** [comment]
I’m running 2.3.7.  Can’t run V3 due to product requirements. The logs are quite long.

There are three nodes. I’ve included the non-ssl and the ssl configs that I’ve gotten working so far.  I can’t currently connect with etcdctl.

I’m not willing to put the log files into a public github discussion.  If you give me a private email address, I can make them viewable to you on Google Docs. You’ll need a google account to access them.


Like the famous philosopher said, when you stare into the void, the void stares also; but if you *cast* into the void, you get a type conversion error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

On Fri, Aug 26, 2016 at 9:23 AM, Xiang Li <notifications@github.com <mailto:notifications@github.com>> wrote:
@michael-px <https://github.com/michael-px> What is your etcd version? Can you please attach configuration and logs from all your etcd servers?

**Comment by michael-px** [comment]
This is the script I'm using to generate a self-signed CA, peer certs, and a client cert.  The peer certs work. The client cert, not at all.  I've tried all sorts of iterations with -hostname "*" or "*.jrandomco.com" or omitting it altogether.  Nothing works 

`
#!/bin/bash
# following examples from https://coreos.com/os/docs/latest/generate-self-signed-certificates.html
# get tools from https://github.com/cloudflare/cfssl
# 201608.26MeV

#defaults
ca=px-ca
ca_csr="${ca}-csr.json"
ca_config="${ca}-config.json"
key_size=2048

[ ! -e /usr/local/bin/ ] && mkdir -P /usr/local/bin
case $(uname) in
	Darwin)
		if [ ! -e  /usr/local/bin/cfssl ]; then
			curl -s -L -o /usr/local/bin/cfssl \
				https://pkg.cfssl.org/R1.2/cfssl_darwin-amd64
		fi
		if [ ! -e  /usr/local/bin/cfssljson ]; then
			curl -s -L -o /usr/local/bin/cfssljson \
				https://pkg.cfssl.org/R1.2/cfssljson_darwin-amd64
		fi
		;;
	Linux)
		if [ ! -e  /usr/local/bin/cfssl ]; then
			curl -s -L -o /usr/local/bin/cfssl \
				https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
		fi
		if [ ! -e  /usr/local/bin/cfssljson ]; then
			curl -s -L -o /usr/local/bin/cfssljson \
				https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
		fi
		;;
	*)
		echo "OS $(uname) not supported"
		exit 2
		;;
esac
chmod +x /usr/local/bin/{cfssl,cfssljson}

cat <<-EOFCACSR > ${ca_csr}
	{
		"CN": "jrandomco.com",
		"hosts": [ "*.jrandomco.com" ],
		"key": {
			"algo": "rsa",
			"size": ${key_size} 
		},
		"names": [
			{
				"C": "US",
				"L": "CA",
				"ST": "Anytown"
			}
		]
	}
EOFCACSR

cat <<-EOFCACONFIG > ${ca_config}
	{
		"signing": {
			"default": {
				"expiry": "43800h"
			},
			"profiles": {
				"server": {
					"expiry": "43800h",
					"usages": [
						"signing",
						"key encipherment",
						"server auth"
					]
				},
				"client": {
					"expiry": "43800h",
					"usages": [
						"signing",
						"key encipherment",
						"client auth"
					]
				},
				"client-server": {
					"expiry": "43800h",
					"usages": [
						"signing",
						"key encipherment",
						"server auth",
						"client auth"
					]
				}
			}
		}
	}
EOFCACONFIG

echo "================================================== generating self-signed CA cert+key"
cfssl genkey -initca ${ca_csr} | cfssljson -bare ${ca} -
#cfssl gencert -initca ${ca_csr} | cfssljson -bare ${ca} - # CFSSL signs this
openssl verify -purpose sslserver -CAfile ${ca}.pem ${ca}.pem

echo "================================================== generating west-2 certs+keys"
# list the AWS internal, elastic IP, and DNS names to assign to each certificate
# these certs work for connecting between nodes [201608.25MeV]
for host in                                      \
	"10.0.0.5,52.1.1.1,etcdb.jrandomco.com"   \
	"10.0.2.123,52.2.1.1,etcdc.jrandomco.com"  \
	"10.0.4.187,52.3.1.1,etcdd.jrandomco.com" \
	; do                                         \
	etcd=`echo $host | awk -F"," '{print $3}' | sed -e 's/.jrandomco.com//'`
		cfssl gencert -ca=${ca}.pem -ca-key=${ca}-key.pem -config=${ca_config} \
			-hostname="${host}" -profile=client-server ${ca_csr} | cfssljson -bare px-${etcd}
	openssl verify -purpose sslserver -CAfile ${ca}.pem px-${etcd}.pem
done

echo "================================================== generating client cert+key (will show warning)"
# below is the "subject" field 
echo '{"CN":"jrandomco.com","hosts":[""],"key":{"algo":"rsa","size":2048}}' | \
	cfssl gencert -ca=${ca}.pem -ca-key=${ca}-key.pem -config=${ca_config} \
		-profile=client-server - | cfssljson -bare px-client

echo "================================================== signing client cert"
echo '{"CN": "jrandomco.com","names":[{"C":"US","L":"Anytown,"ST":"California"}]}' | \
cfssl sign -ca ${ca}.pem -ca-key ${ca}-key.pem -hostname "*.jrandomco.com" \
	px-client.csr | cfssljson -bare px-client
openssl verify -purpose sslclient -CAfile ${ca}.pem px-client.pem

rm -f ${ca_csr} ${ca_config}
chmod 644 *.pem *.csr
`

**Comment by xiang90** [comment]
@michael-px Sorry for the delay. We are going to take a look at this today.

**Comment by xiang90** [comment]
@michael-px 

OK. So after reading the the log you sent me, etcd complained about 

```
x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
```

Go by default will validate hostnames/SANs. You can take a look at the example we provided here: https://github.com/coreos/etcd/tree/master/hack/tls-setup as listed in the doc you refer.

**Comment by xiang90** [comment]
widecard does not work for SAN /cc @gtank to double check my word.

**Comment by michael-px** [comment]
I’ve changed the certs significantly according to this

https://www.digitalocean.com/community/tutorials/how-to-secure-your-coreos-cluster-with-tls-ssl-and-firewall-rules

The CN for each server is the internal IP address of the AWS instance with
SANs containing the internal and external IP address of each host.  I’m not
using a client cert.

The error I keep getting is

curl --cacert /etc/ssl/etcd/px-ca.pem https://10.0.0.5:2379/v2/stats/self -v
* About to connect() to 10.0.0.5 port 2379 (#0)
*   Trying 10.0.0.5...
* Connected to 10.0.0.5 (10.0.0.5) port 2379 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/ssl/etcd/px-ca.pem
  CApath: none
* NSS: client certificate not found (nickname not specified)
* NSS error -12271 (SSL_ERROR_BAD_CERT_ALERT)
* SSL peer cannot verify your certificate.
* Closing connection 0
curl: (58) NSS: client certificate not found (nickname not specified)

This was run on one of the servers. etcdctl (and curl) cannot connect to
etcd with a CA cert.  I’m stuck at what I have to specify for the CN.
According to the link above, the CN doesn’t need a hostname.

The nodes can authenticate between themselves with the certs being
generated. It’s accessing etcd as a client that doesn’t work because of SSL
stuff.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
@michael-px Are you saying that now the TLS at the peer side is working, but the TLS still does not work for the client side?

**Comment by michael-px** [comment]
Yep.  I’m sorting out the situation and will post log files and configs
shortly on my Google doc for Xiang to access.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
One quick question:

Have you tried 

curl --cacert /etc/ssl/etcd/px-ca.pem https://10.0.0.5:2379/v2/stats/self -v -k?

**Comment by michael-px** [comment]
curl --cacert /etc/ssl/etcd/px-ca.pem https://10.0.0.5:2379/v2/stats/self
-v -k
* About to connect() to 10.0.0.5 port 2379 (#0)
*   Trying 10.0.0.5...
* Connected to 10.0.0.5 (10.0.0.5) port 2379 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* NSS error -12271 (SSL_ERROR_BAD_CERT_ALERT)
* SSL peer cannot verify your certificate.
* Closing connection 0
curl: (58) NSS: client certificate not found (nickname not specified)

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by gyuho** [comment]
@michael-px Is wildcard-hosts working with `cfssl`? Just curious, because it didn't work for me.

**Comment by michael-px** [comment]
no, wildcards didn’t work for me.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
```
curl: (58) NSS: client certificate not found (nickname not specified)
```

I think this suggest that curl could not find the cert you provided here at `/etc/ssl/etcd/px-ca.pem` somehow. I do not really know why.

Probably you can try to curl www.google.com with same flag. it should complaint the same. I am not a curl expert. You need to search around on google for this.

**Comment by michael-px** [comment]
etcd is setup to use the host’s server certificate for both the client and
the server.  So, I’m stumped why this doesn’t work. Neither does etcdctl.


Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by michael-px** [comment]
A point of clarification please.

https://github.com/coreos/etcd/tree/master/hack/tls-setup

says to set the IP addresses for all the IP addresses for the hosts in the
cluster then run make.  There is no Makefile in any of the pages discussed
so far.

I wonder if we’re looking at the same stuff here.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
Now that the cluster TLS works, probably we can make sure cURL work. Then we know there is an etcdctl issue?

**Comment by michael-px** [comment]
Yep. Good plan. I’m assembling logs and configs.  Will get back to you
after 12:15pm PDT.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by gyuho** [comment]
@michael-px If that doesn't work out, you may want to try this sample TLS-setup workflow https://gist.github.com/gyuho/e3e4016654f4939dba2d78762a68049c.

Slightly different, but this works for me with no problem.

**Comment by michael-px** [comment]
Gyu-Ho,

your procedure didn’t work for me. I had hopes that setting the CN to the
same on the root CA and the servers would solve my problem.  No such luck.
But thanks for the suggestion.

openssl x509 -in px-ca.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            44:99:e2:e0:7b:e9:7e:0c:cc:ad:dd:12:77:39:f1:6a:e3:86:ec:a8
    Signature Algorithm: ecdsa-with-SHA384
        Issuer: C=US, ST=xxx, L=xx, O=xxx, OU=xxx, CN=etcd
        Validity
            Not Before: Aug 29 18:26:00 2016 GMT
            Not After : Aug 28 18:26:00 2021 GMT
        Subject: C=US, ST=xxx, L=xx, O=xxx, OU=xxx, CN=etcd
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:df:8e:fd:ed:d1:76:72:b3:d4:5d:b8:47:f9:34:
                    94:b4:55:28:3c:37:bf:6a:7b:56:7b:c3:4e:9b:1d:
                    57:22:03:16:5d:1c:4f:6d:a5:4f:84:28:5d:fd:09:
                    5a:42:64:5d:63:98:37:fd:39:13:f9:da:c6:3f:61:
                    0c:50:aa:39:cb:71:94:59:f7:4e:66:87:7c:59:b6:
                    70:5f:07:78:83:d6:ad:db:05:0f:22:43:6a:c7:15:
                    f9:92:e5:d0:79:28:ad
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:2
            X509v3 Subject Key Identifier:
                2A:77:B0:DA:54:A3:58:17:84:53:48:4F:6E:99:8C:73:F4:E8:DC:40
            X509v3 Authority Key Identifier:

keyid:2A:77:B0:DA:54:A3:58:17:84:53:48:4F:6E:99:8C:73:F4:E8:DC:40

    Signature Algorithm: ecdsa-with-SHA384
         30:64:02:30:5c:30:89:24:85:db:c2:1b:71:54:8a:88:c1:01:
         1e:86:6e:fb:4f:03:d1:62:81:b1:f9:9b:ae:09:bf:09:9d:7d:
         f4:59:b6:f8:c9:44:85:03:f3:d5:68:b9:5d:c4:9c:37:02:30:
         6c:f2:aa:de:f4:8f:44:24:aa:6e:5d:4f:2f:a2:f3:40:bb:55:
         fa:b5:6e:87:fe:c2:8b:28:a7:07:b0:11:fa:bd:2a:b8:81:1c:
         de:4c:6b:64:f5:ab:ce:e9:60:6f:02:de

$ openssl x509 -in px-etcdb.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            42:4a:09:3f:b7:dc:20:a2:f0:1d:b8:78:e8:eb:14:cf:9f:48:3f:07
    Signature Algorithm: ecdsa-with-SHA384
        Issuer: C=US, ST=xxx, L=xx, O=xxx, OU=West-2, CN=etcd
        Validity
            Not Before: Aug 29 19:06:00 2016 GMT
            Not After : Aug 28 19:06:00 2021 GMT
        Subject: CN=etcd
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:3e:ec:88:f3:46:4f:6d:75:13:66:e7:6b:56:9d:
                    da:76:0e:b8:8e:eb:d5:ec:39:81:a3:91:b0:60:2c:
                    ff:2e:73:8b:72:1b:4a:37:71:c3:fc:ee:c2:77:f6:
                    ae:a3:15:3e:6b:dc:2a:1f:53:32:b2:40:85:cd:83:
                    ee:62:7c:af:a2:99:5e:03:23:6c:72:bd:10:b9:c4:
                    9b:6e:23:a5:15:af:6f:af:d6:96:5c:c6:ee:85:d2:
                    76:10:5d:52:a9:2c:0b
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                61:95:95:28:7C:8A:8C:AB:7F:85:63:7B:55:81:44:9A:93:10:68:25
            X509v3 Authority Key Identifier:

keyid:2A:77:B0:DA:54:A3:58:17:84:53:48:4F:6E:99:8C:73:F4:E8:DC:40

            X509v3 Subject Alternative Name:
                DNS:xxx.internal, DNS:xxx.com, IP Address:xxx.xxx.xxx.xxx,
IP Address:xxx.xxx.xxx.xxx
    Signature Algorithm: ecdsa-with-SHA384
         30:64:02:30:38:03:6f:32:f5:28:4a:c6:61:e7:2a:62:5d:b7:
         36:52:89:3d:13:06:2e:08:89:e6:e2:69:6a:4e:b0:5c:8e:21:
         e0:9f:8a:9c:e7:55:04:70:24:45:2b:8e:87:d9:57:f6:02:30:
         76:8a:39:29:6d:a9:03:f7:96:94:7b:16:4b:16:94:fa:89:6a:
         27:36:f7:f8:9d:b7:41:bd:06:e8:dd:78:30:e8:9f:d4:42:23:
         c3:50:c5:2f:0e:e7:1c:7f:ab:0b:60:c0

[root@ip-10-0-0-5 centos]# curl --cacert /etc/ssl/etcd/px-ca.pem
https://10.0.0.5:2379/v2/stats/self -v -k
* About to connect() to 10.0.0.5 port 2379 (#0)
*   Trying 10.0.0.5...
* Connected to 10.0.0.5 (10.0.0.5) port 2379 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate not found (nickname not specified)
* NSS error -12271 (SSL_ERROR_BAD_CERT_ALERT)
* SSL peer cannot verify your certificate.
* Closing connection 0
curl: (58) NSS: client certificate not found (nickname not specified)

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by michael-px** [comment]
Gyu-Ho,

I followed your example more closely.  For one thing, I'm running etcd 2.3.7. I can't run 3.0 at this time, so I don't know if this issue is only with 2.3.x.

Also, I tried creating the ca_csr file with
```
cat <<-EOFCACSR1 > ca_csr.json
	{
	"CN": "etcd",
	"hosts": [ 
	"xxx.internal",
	"10.0.0.5",
	"xxx.xxx.xxx.xxx",
	"etcdb.xxx.com",
	"localhost"
	],
	"key": {
	"algo": "rsa",
	"size": 2048 
	},
	"names": [
	{
	"C": "US",
	"L": "CA",
	"O": "xxx",
	"ST": "xxx",
	"OU": "xxx"
	}
	]
	}
EOFCACSR1
cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca_config.json \
	-profile=client-server ca_csr.json | cfssljson -bare px-etcdb
```
when I run the code, I get
```
2016/08/29 13:16:50 [INFO] generate received request
2016/08/29 13:16:50 [INFO] received CSR
2016/08/29 13:16:50 [INFO] generating key: rsa-2048
2016/08/29 13:16:50 [INFO] encoded CSR
2016/08/29 13:16:50 [INFO] signed certificate with serial number 403163986611580533033022322791112032931060689918
2016/08/29 13:16:50 [WARNING] This certificate lacks a "hosts" field. This makes it unsuitable for
websites. For more information see the Baseline Requirements for the Issuance and Management
of Publicly-Trusted Certificates, v.1.1.6, from the CA/Browser Forum (https://cabforum.org);
specifically, section 10.2.3 ("Information Requirements").
```
I took out the tabs and spaces just in case cfssl didn't like them but cfssl 1.2 ignores the hosts field in a json file.  The certs generated don't work for peers because there's no host.  I got server keys to work by supplying the json in-line instead of through a file and over-riding the host in the json with -hosts on the command line.  Those peer certs work but don't work for a client.

**Comment by xiang90** [comment]
@michael-px Let's move on to the client side TLS. I checked the log you provided to me, the server side TLS works now. cURL complaints about not being able to pick up the cert you provided. You need to somehow figure out that first I think.

**Comment by michael-px** [comment]
I’m stuck there. Permissions are OK (I’m running as root).

cfssl isn’t your thing, is it?  If there’s a problem with the certs it’s
generating, it’s someone else’s issue, right?

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
@michael-px 

http://stackoverflow.com/questions/15773806/nss-client-certificate-not-found-nickname-not-specified

Probably this can help you?

**Comment by michael-px** [comment]
Thanks, but that wasn’t applicable.  Still stuck.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by michael-px** [comment]
OK, I followed Gyu-Ho's procedure for generating certs in this thread.  The certs generated by my script (with his mods) will generate peer certs that work.  All three nodes of the cluster talk to each other.

I was stuck getting etcdctl to talk to the cluster.  Then I used all three keys with etcdctl to connect to a node on the cluster.  And it worked...

```
etcdctl --cert-file /etc/ssl/etcd/px-etcdb.pem --key-file /etc/ssl/etcd/px-etcdb-key.pem --ca-file /etc/ssl/etcd/px-ca.pem cluster-healthetcdctl --cert-file /etc/ssl/etcd/px-etcdb.pem --key-file /etc/ssl/etcd/px-etcdb-key.pem --ca-file /etc/ssl/etcd/px-ca.pem cluster-health
```

Now the problem is how to reduced this down to a single key for a client application to connect to *any* node on the cluster?  Compose.io does it by supplying a single CA cert.  Any pointers on how to do it?

**Comment by gyuho** [comment]
@michael-px Do you mean using single key with fixed list of hosts?

I think it's better to have different keys per node, in case there is member reconfiguration (member remove, add). Or https://github.com/cloudflare/cfssl team should have answers for you.

**Comment by michael-px** [comment]
OK, I’ll ask there.  Compose.io provides a single CA key that works with
either end-node on their clusters, which is behind a load balancer.  We
want something like that so we only have to provide 1 key to a customer
rather than three.

Since compose.o’s etcd version is 2.2 (ancient, I know), I suspect they
used openssl to generate their certs rather than cfssl.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by michael-px** [comment]
I've got another cert issue but it's slightly different from this topic.  I got cfssl to generate peer certs and can use the same cert, plus it's key, and the CA to authenticate etcdctl on that node.  mkbundle (part of cfssl) allows me to combine all the certs into a single CRT file that I can use to access any of the nodes from a client.

So this issue is solved.

**Comment by xiang90** [comment]
@michael-px Free feel to submit patches to improve the cfssl doc/template. Thank you!

**Comment by gyuho** [comment]
Yeah we are planning on making the documentation better in general. Thanks!

**Comment by michael-px** [comment]
😀
I didn’t know I could do that.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde
