### ISSUE TITLE
embed: hangs on ReadyNotify with certain backing stores

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#6287]
Hi etcd folks and thanks again for your hard work!

I've been hitting what I thought was some weird heisenbug, but I spent some more time today tracking it down. I think I can now approximately reproduce it, but I don't know the underlying cause:

When using the embed package in Etcd, I would hang at StartEtcd:

```
cfg := embed.NewConfig()
...
obj.server, err = embed.StartEtcd(cfg)
```

I traced into that and found that it is waiting on:

```
<-e.Server.ReadyNotify()
```

which is here: https://github.com/coreos/etcd/blob/master/embed/etcd.go#L133

So what was causing this? I found that if I re-used the `cfg.Dir` location, and there was pre-existing data there it seemed to cause the hang. Obviously this doesn't happen in all situations, but I can't figure out which situations causes this and how to detect them.

Detecting this scenario is most important to me, because then if the end user is using a bad/corrupt data directory, then I can at least notify them of the issue.

As for what would cause a bad directory? I don't know which situations will cause this hang, but it's at least possible that I built a cluster, shut it down, and then built a _different_ cluster using the same directory. Again, this part is surely my fault, but I'd still like to be able to detect it, and know what types of situations are bad.

In parallel, perhaps for some reason it's just taking a long time to process the data dir and getting progress feedback would be useful. (Unlikely in this case because data dir is ~123MB.)

Thanks!!

**Comment by purpleidea** [comment]
Sorry: btw I'm using v.3 of the code base, and golang 1.5.4

I can currently reproduce this if there are some printf's you'd like me to insert anywhere to give feedback.

**Comment by purpleidea** [comment]
And lastly, some logs... The `XXX: ETCD INTERNAL WAITING...` happens on the line before the `<-e.Server.ReadyNotify()` and I also added a message on the line right after it which never appears.

The four line chunks that are approximately repeating (election attempts) repeat at the bottom indefinitely every second or so. My raft knowledge is too weak to definitely know the problem there, but I assume it's something to do with an old member that it's possibly expecting which isn't showing up or responding incorrectly?

```
22:01:35 etcd.go:75: (etcd) embed: listening for peers on http://127.0.0.1:2380
22:01:35 etcd.go:78: (etcd) embed: listening for client requests on 127.0.0.1:2379
22:01:35 config.go:155: (etcd) etcdserver: name = h1
22:01:35 config.go:159: (etcd) etcdserver: data dir = /var/lib/mgmt/etcd
22:01:35 config.go:160: (etcd) etcdserver: member dir = /var/lib/mgmt/etcd/member
22:01:35 config.go:164: (etcd) etcdserver: heartbeat = 100ms
22:01:35 config.go:165: (etcd) etcdserver: election = 1000ms
22:01:35 config.go:166: (etcd) etcdserver: snapshot count = 10000
22:01:35 config.go:173: (etcd) etcdserver: advertise client URLs = http://127.0.0.1:2379
22:01:35 raft.go:350: (etcd) etcdserver: restarting member b71f75320dc06a6c in cluster 1c45a069f3a1d796 at commit index 4800
22:01:35 raft.go:493: (etcd) raft: b71f75320dc06a6c became follower at term 130
22:01:35 raft.go:265: (etcd) raft: newRaft b71f75320dc06a6c [peers: [], term: 130, commit: 4800, applied: 0, lastindex: 4802, lastterm: 26]
22:01:35 server.go:468: (etcd) etcdserver: starting server... [version: 3.0.0+git, cluster version: to_be_decided]
XXX: ETCD INTERNAL WAITING...
22:01:35 cluster.go:294: (etcd) membership: added member b71f75320dc06a6c [http://127.0.0.1:2380] to cluster 1c45a069f3a1d796
22:01:35 cluster.go:365: (etcd) membership: set the initial cluster version to 3.0
22:01:35 cluster.go:294: (etcd) membership: added member 270bf835d78b8ec0 [http://127.0.0.1:2382] to cluster 1c45a069f3a1d796
22:01:35 peer.go:121: (etcd) rafthttp: starting peer 270bf835d78b8ec0...
22:01:35 pipeline.go:67: (etcd) rafthttp: started HTTP pipelining with peer 270bf835d78b8ec0
22:01:35 stream.go:144: (etcd) rafthttp: started streaming with peer 270bf835d78b8ec0 (writer)
22:01:35 stream.go:144: (etcd) rafthttp: started streaming with peer 270bf835d78b8ec0 (writer)
22:01:35 peer.go:206: (etcd) rafthttp: started peer 270bf835d78b8ec0
22:01:35 transport.go:249: (etcd) rafthttp: added peer 270bf835d78b8ec0
22:01:35 stream.go:291: (etcd) rafthttp: started streaming with peer 270bf835d78b8ec0 (stream Message reader)
22:01:35 stream.go:291: (etcd) rafthttp: started streaming with peer 270bf835d78b8ec0 (stream MsgApp v2 reader)

22:01:35 capability.go:75: (etcd) api: enabled capabilities for version 3.0

22:01:36 raft.go:578: (etcd) raft: b71f75320dc06a6c is starting a new election at term 130
22:01:36 raft.go:506: (etcd) raft: b71f75320dc06a6c became candidate at term 131
22:01:36 raft.go:560: (etcd) raft: b71f75320dc06a6c received vote from b71f75320dc06a6c at term 131
22:01:36 raft.go:548: (etcd) raft: b71f75320dc06a6c [logterm: 26, index: 4802] sent vote request to 270bf835d78b8ec0 at term 131

22:01:38 raft.go:578: (etcd) raft: b71f75320dc06a6c is starting a new election at term 131
22:01:38 raft.go:506: (etcd) raft: b71f75320dc06a6c became candidate at term 132
22:01:38 raft.go:560: (etcd) raft: b71f75320dc06a6c received vote from b71f75320dc06a6c at term 132
22:01:38 raft.go:548: (etcd) raft: b71f75320dc06a6c [logterm: 26, index: 4802] sent vote request to 270bf835d78b8ec0 at term 132

22:01:39 raft.go:578: (etcd) raft: b71f75320dc06a6c is starting a new election at term 132
22:01:39 raft.go:506: (etcd) raft: b71f75320dc06a6c became candidate at term 133
22:01:39 raft.go:560: (etcd) raft: b71f75320dc06a6c received vote from b71f75320dc06a6c at term 133
22:01:39 raft.go:548: (etcd) raft: b71f75320dc06a6c [logterm: 26, index: 4802] sent vote request to 270bf835d78b8ec0 at term 133

22:01:40 raft.go:578: (etcd) raft: b71f75320dc06a6c is starting a new election at term 133
22:01:40 raft.go:506: (etcd) raft: b71f75320dc06a6c became candidate at term 134
22:01:40 raft.go:560: (etcd) raft: b71f75320dc06a6c received vote from b71f75320dc06a6c at term 134
22:01:40 raft.go:548: (etcd) raft: b71f75320dc06a6c [logterm: 26, index: 4802] sent vote request to 270bf835d78b8ec0 at term 134

22:01:42 server.go:942: (etcd) etcdserver: publish error: etcdserver: request timed out

22:01:42 raft.go:578: (etcd) raft: b71f75320dc06a6c is starting a new election at term 134
22:01:42 raft.go:506: (etcd) raft: b71f75320dc06a6c became candidate at term 135
22:01:42 raft.go:560: (etcd) raft: b71f75320dc06a6c received vote from b71f75320dc06a6c at term 135
22:01:42 raft.go:548: (etcd) raft: b71f75320dc06a6c [logterm: 26, index: 4802] sent vote request to 270bf835d78b8ec0 at term 135
```

**Comment by heyitsanthony** [comment]
@purpleidea `ReadyNotify()` won't trigger until etcdserver can publish its information into the cluster. From the logs, `b71f75320dc06a6c` is `restarting` using whatever cluster configuration that's been set up already in `/var/lib/mgmt/etcd`. The elections / publish errors are because `b71f75320dc06a6c` is in a 2 member cluster but can't contact `270bf835d78b8ec0`, so it can't establish quorum.

**Comment by purpleidea** [comment]
@heyitsanthony Great diagnosis thank you!

After running the:

`embed.StartEtcd(cfg)`

call, how can we
1) Get status information on what's happening?
2) Run something to unblock it and get it to exit?

(In this sort of situation you analyzed above)

Thanks!

**Comment by purpleidea** [comment]
This should help resolve this: https://github.com/coreos/etcd/pull/6289

**Comment by purpleidea** [comment]
Still need a way to get some information, as mentioned in (1). Using a pure timeout is too much of a heuristic. :(

**Comment by xiang90** [comment]
Fixed by https://github.com/coreos/etcd/pull/6289

**Comment by purpleidea** [comment]
@xiang90 Part (1) is fixed :) W00t... However part (2) is still pending... Any ideas?

**Comment by heyitsanthony** [comment]
@purpleidea what sort of status information are you expecting?

**Comment by purpleidea** [comment]
@heyitsanthony Any sort of information about what state the system is in? Eg: "i'm busy re-running the huge mongous log of previous events, vs. i am trying to elect, i am trying to elect, i am trying to elect...

So maybe even a channel of events. This way if it's slow because it's busy processing a 1GB dataDir on disk, okay, keep waiting, but if it's constant elections, maybe I give up and kill it.

**Comment by xiang90** [comment]
@purpleidea Do you have time to help on part 2)?

**Comment by heyitsanthony** [comment]
I think this can be done already by polling etcdserver.Term() while waiting for the ready signal?

**Comment by xiang90** [comment]
@heyitsanthony I think to users still need to read logs to figure out what exactly is happening and why raft or etcdserver is failing. To be honest, I do not think there is much we can do here. It seems like a debugging issue to me and logging seems to be good enough.

**Comment by heyitsanthony** [comment]
@xiang90 yeah, I'm not crazy about this because there are so many failure modes

**Comment by xiang90** [comment]
@heyitsanthony I am inclined to close this.

**Comment by purpleidea** [comment]
I do think it's pretty important if etcd is going to be embedded in a robust way. As I said, using a timeout is a bad heuristic.

**Comment by xiang90** [comment]
part 1 is about

> 1) Get status information on what's happening?

This is what we wont fix.

I do not quite understand the timeout part.

**Comment by xiang90** [comment]
@purpleidea Also etcd itself use embed etcd too, so it has to be robust.

**Comment by heyitsanthony** [comment]
It seems embedded users as of now have a timeout on the ready channel and bail out if it takes too long. This makes sense from a MTTR point of view-- it doesn't really matter what etcd is doing so long as it recovers in time. Since it's not clear what to add here (nor is it clear that it's really needed), closing this.
