### ISSUE TITLE
Question: Fault Zones in Torus?

### ISSUE THREAD

**Issue by akamalov** [coreos/etcd#6291]
This is a question.

Question:

Let's say I have three racks of servers, each containing 40 servers. I want to run Torus across all of them. I would like to have 3 copies of data and want to place each copy in unique rack. Does Torus have a concept of Fault Zones where I can specify which node belongs to which fault zone and Torus would automatically select nodes in unique fault zone to store data? (a la ScaleIO) ? I am trying to avoid a scenario where Torus would pick nodes in the same rack unit.

**Comment by xiang90** [comment]
This is etcd repo. Torus repo is here: https://github.com/coreos/torus

**Comment by akamalov** [comment]
Sorry xiang90. I will re-file it with torus repo.
