### ISSUE TITLE
certs and dealing with an outage

### ISSUE THREAD

**Issue by michael-px** [coreos/etcd#6311]
I got a working ssl configuration that uses the cfssl tool to generate a CA and peer certs for a three node cluster on AWS.

Each AWS instance has an external IP address which is in DNS and an internal IP address that's used for peer<-->peer communication.  I put those into each instance's certs along with localhost and 127.0.0.1.  This makes those certs unique to the node they're generated for.

Then I used cfssl's mkbundle tool to take all the .pem files and build a bundle CRT that can be used by clients to access any node the etcd cluster.  Imagine that cert being distributed to thousands of nodes via docker containers, all to allow the software on that container to access the etcd cluster.

Now suppose there's an outage. AWS recently told us one of our production instances was running on failing hardware.  Unlike VMware, they didn't migrate the instance to good HW. Instead they said they were taking it off-line as of 8am that day.  etcd on that host had long since stopped responding and our cluster said it was "unhealthy".  It took most of the day with senior staff to create a replacement instance with the same external IP and assign the same IP to the new instance.  It's working for now.

I see a problem with SSL and the "remove bad node" workflow for a node failure.  If I remove a failed node from the cluster, generate a cert for a new node, and add it to the cluster, what about the 1000 docker clients accessing the cluster with the old cert bundle?  They won't be able to access the new node because the bundle they hold doesn't include the replacement node.  The only way to fix that is to shutdown each container, delete it, and pull an updated container from Dockerhub.  That's not an acceptable scenario.  We can't have downtime.

I tried generating certs with a wildcard in the CN field and the SAN field.  cfssl said they were unsuitable for web use but generated them anyway.  But when I tried to use this wildcard cert in a cluster, etcd wouldn't allow it.  The log file said

```
 30 13:20:26 ip-10-0-4-187 etcd[23025]: failed to dial 60113488fbd499 on stream Message (x509: cannot validate certificate for 10.0.2.123 because it doesn't contain any IP SANs)
```
If I can't generate SANs with wildcards (or no IPs), I can't create a blanket cert that will always work and not require my docker containers to reload a cert. bundle.

cfssl allows wildcards but etcd is architected to now allow it.  Unless I can use a blanket cert, I'll have an outage with my clients.  That's not an option.

What can be done to avoid the outage scenario?  I'm hoping I missed something here.

**Comment by xiang90** [comment]
@michael-px Can the client talk to etcd using DNS name instead of IP? Then we can point the old DNS (DNS of the dead member) to the newly created member?

**Comment by michael-px** [comment]
The client is given a connection string of all nodes in the cluster as DNS
names.  So in that scenario, the client would still be able to connect.

So, the new node, say hostname efcd-new, is given the DNS name
etcd2.example.com.  It’s cert is generated with the new internal IP,
external IP (which would be the SAME due to AWS elastic IP), and
etcd2.example.com DNS entry.

The cert in the bundle for the old machine has a different internal IP in
the SAN.  But the rest would be the same.  Will that work?

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
From my understanding, as long as DNS + external IP remain the same, the client should not have a problem connecting to it. Due to the internal IP changes, we need to update the cert of the other servers.

**Comment by michael-px** [comment]
“we” as in etcd itself will track this?  The setting for the initial
cluster will be different.

For example, before the outage, let’s say this is in each node in the
cluster:

ETCD_INITIAL_CLUSTER="etcdb=https://10.0.0.5:2380,etcdc=
https://10.0.2.123:2380,etcdd=https://10.0.4.187:2380”

etcdc dies.  So I removed it from the cluster with member remove.  Then add
a new node with member add and the new setting is

ETCD_INITIAL_CLUSTER="etcdb=https://10.0.0.5:2380,etcdcc=
https://10.0.2.35:2380,etcdd=https://10.0.4.187:2380”

The bad node will have a new cert generated with a different internal IP
different.  The bundle.pem file won’t have that.  But you’re saying that so
long as DNS still points to the same name (ectcd.example.com) and the
external IP is set, there won’t be a problem?

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
First, initial prefixed flag will ONLY affect new member (member without data dir). For restart existing members (member with existing data dir), you can simply ignore them.

In your example, the external IP and DNS do not change. So client should not be affected. No client facing stuff ever get changed.

The internal IP did change from 123 -> 35. So we need to update certs of all existing members and restart them with new certs. This process can be automated.

Again, I am not an expert on this.

**Comment by michael-px** [comment]
This scenario is doable with a change in the config files plus a systemctl
restart of etcd.  That’s all on the server side and the 1000 clients are
fine.

That’s also GREAT news.  I like making my boss happy.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
@michael-px I would suggest you to get it a try first. Also probably you should wait for @gtank's opinion.

**Comment by michael-px** [comment]
Yes, I’m setting up the cluster, then we’ll test our product

Then do the remove/add scenario.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde

**Comment by xiang90** [comment]
I am going to close this since it seems that the problem is resolved. Please reopen if there is any followup. Thanks.

**Comment by xiang90** [comment]
I am going to close this since it seems that the problem is resolved. Please reopen if there is any followup. Thanks.

**Comment by michael-px** [comment]
That works. I’ve been pull onto another more urgent project for the
meantime. I’ll tell my boss you guys are closing the issue and he can
either have me reopen it when we come back to this problem or I’ll open
another issue.

Like the famous philosopher said, when you stare into the void, the void
stares also; but if you *cast* into the void, you get a type conversion
error. Either way lies madness. -- Charles Stross
The pure and simple truth is rarely pure and never simple.--Oscar Wilde
