### ISSUE TITLE
TestWatchReconnRequest: request timed out

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6314]
via semaphore on #6310

```
--- FAIL: TestWatchReconnRequest (7.62s)
	watch_test.go:327: etcdserver: request timed out, possibly due to previous leader failure
```

**Comment by xiang90** [comment]
I  do not think there is much we can do here. We already set election timeout pretty high for the CI. But CI was still slow enough to trigger an election. This happens very infrequent. So I do not think it worth a fix.

**Comment by heyitsanthony** [comment]
@xiang90 it's still flakey, though. I suspect having an l-read before the put will fix this...
