### ISSUE TITLE
etcdctl v3 txn value does not honor %q formatting

### ISSUE THREAD

**Issue by chajath** [coreos/etcd#6315]
etcdctl txn key and value specs are given as:

```
<KEY> ::= (%q formatted string)
<VALUE> ::= (%q formatted string)
```

To me, it is not clear what `(%q formatted string)` exactly mean here. Running the very example given, i.e.

```
./etcdctl txn <<<'mod("key1") > "0"

put key1 "overwrote-key1"

put key1 "created-key1"
put key2 "some extra key"

'
FAILURE

OK

OK
```

When I do `etcdctl get key1` afterwards I get `"created-key1"` as a value with quotes intact. Shouldn't the value be `created-key1` without the enclosing quotes? Also, it does not seem to honor other standard %q formatting such as `\ ` space escaping.

**Comment by heyitsanthony** [comment]
The %q formatted strings are only for the `<CMP>*` part of the txn. Get/Put/Del are derived from the etcdctl `get`/`put`/`delete` command syntax. This is given in the grammar given from the etcdctl documentation: `<OP> ::= ((see put, get, del etcdctl command syntax)) "\n"`.

**Comment by chajath** [comment]
Ok I might have misunderstood the spec. But it looks like there is no easy way of escaping special characters or including whitespaces without putting quotes around, and when I do put the quotes around the quotes themselves are saved verbatim. Any recommendation around putting values that has spaces in it without putting quotes around?

**Comment by heyitsanthony** [comment]
Tried it out and even the plain quote handling seems broken. It should probably behave like %q if quotes are given. Will fix and add better testing around it. Thanks for reporting this!

**Comment by chajath** [comment]
Thanks for looking into this. The only workaround I can think of is to enter stdin mode and supply ^D at the end of the value. So I'd very much like the %q string support, please :)
