### ISSUE TITLE
how to set "PUT" with ttl and how to watch a directory

### ISSUE THREAD

**Issue by oikomi** [coreos/etcd#6318]
hi
after upgrade to cli V3, how to set "PUT" with ttl and how to watch a directory ?

thx

**Comment by gyuho** [comment]
@oikomi You need to attach lease to your key https://github.com/coreos/etcd/tree/master/etcdctl#lease-subcommand

And there's no key-hierarchy in v3. You can watch by prefix though.
https://github.com/coreos/etcd/tree/master/etcdctl#watch-options-key-or-prefix-range_end

**Comment by xiang90** [comment]
@oikomi This doc might be helpful too: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/v2-migration.md#migrate-client-library

**Comment by oikomi** [comment]
thx , resolved.
