### ISSUE TITLE
wal package generates files that cause old decoder to panic

### ISSUE THREAD

**Issue by aaronlehmann** [coreos/etcd#6323]
The WAL files generated by the current version of the code do not seem to be compatible with some older versions of the package. This causes problems when downgrading from a newer version to an older one.

1. Create a WAL using the latest version of the `github.com/coreos/etcd/wal` package.
2. Try to load the WAL using an old revision such as ce63f107382080fda29ed124249b16bfea224dc0.

`(*decoder).decode` panics with `panic: runtime error: makeslice: len out of range`. This seems to be caused by a record format change in #5250. Instead of storing the length of the record directly, it packs some information about padding into the upper bits. The old decoder doesn't handle this, and tries to allocate a slice with a negative size.

I'm not sure there's a good solution to this, since the format change has been in place for months and it may not make sense to change it again. One idea that comes to mind is adding the padding inside the protobufs so that the amount of padding needed at the frame level is always 0. However, this would involve adding extra fields to hold the padding, and making an extra call to the protobuf object's `Size` method to figure out how much padding is needed.

**Comment by xiang90** [comment]
@aaronlehmann For etcd, we do not want to commit to forward-compatibility for now. If you have a good idea about adding forward-compatibility for WAL pkg, we should love to take the patch if it does not significantly affect performance + code complexity.

**Comment by aaronlehmann** [comment]
The only idea I can think of is adding a padding field to `walpb.Record`. For example, `saveEntry` would look like this:

```go
func (w *WAL) saveEntry(e *raftpb.Entry) error {
        // TODO: add MustMarshalTo to reduce one allocation.
        b := pbutil.MustMarshal(e)
        rec := &walpb.Record{Type: entryType, Data: b}
        size := rec.Size()
        if size % 8 != 0 {
                // force 8 byte alignment so length never gets a torn write
                rec.Padding = make([]byte, 8 - (size % 8))
        }
        if err := w.encoder.encode(rec); err != nil {
                return err
        }
        w.enti = e.Index
        return nil
}
```

`saveState` would have the same logic (probably factored out to a common function).

This doesn't seem as bad as I feared in terms of complexity. It would avoid the need for computing padding in `encodeFrameSize`. In terms of performance, it would involve a call to `Size` (pretty trivial because there are no structs inside `Record`), and an extra allocation for the padding.

I can turn this into a full PR if there's interest. But if it's not worth the downsides, I understand.

**Comment by heyitsanthony** [comment]
I don't think the padding field can go in the record because that field is only computed after marshaling the record.

**Comment by aaronlehmann** [comment]
I think you're right that the code I scribbled above isn't quite correct - `8 - (size % 8)` isn't the right number of bytes to put inside the padding field because of encoding overhead. But I think it is possible to do it this way.

Here's the code from `(*Record).Size` that deals with the `Data` field. `Padding` should be the same, since it's also `[]byte`.

```go
        if m.Data != nil {
                l = len(m.Data)
                n += 1 + l + sovRecord(uint64(l))
        }
```

`sovRecord(n)` is always 1 for any value under 128.

So I need to account for 2 bytes of encoding overhead, but other than that, I think it would work.

**Comment by heyitsanthony** [comment]
I'm not sure compatibility is really possible between 2.x and 3.x. There are other differences between the 2.x wal and 3.x wal. How will you account for 2.x using `O_APPEND` and growing the file vs 3.x preallocating a full 64mb file?

**Comment by aaronlehmann** [comment]
Yikes, I didn't realize that would be an issue as well. Perhaps this is not worth pursuing.

Do you know if there are any wire-format incompatibilities between versions 2.x and 3.x of the `raft` package (i.e. can something with an old version of the `raft` package talk to something with a new version)?

**Comment by xiang90** [comment]
@aaronlehmann 
No. We are not aware of that.

For raft pkg and related stuff, we still have one or two more things to finish before we want to finally stabilize the API (say we have 1.0 API). At the same time, we really need to figure out a better story for backward and forward compatibility for raft pkg since there are a fair number of significant users.

We will get you or other swarmkit people involved. Also please let us know if you guys already have something in mind.

**Comment by aaronlehmann** [comment]
> No. We are not aware of that.

Thanks. I just did some compatibility testing between instances running different versions, and didn't find any problems.

> We will get you or other swarmkit people involved. Also please let us know if you guys already have something in mind.

I'd be happy to be involved in this.

Feel free to close this issue if you don't see a practical path to restoring WAL compatibility.

**Comment by xiang90** [comment]
@aaronlehmann Thanks for your understanding.
