### ISSUE TITLE
Watch directory for changes of children

### ISSUE THREAD

**Issue by mren** [coreos/etcd#633]
Querying a dictionary returns a list of the children of this directory.
If I watch the directory with `wait=true` I wont receive an answer if I add a new children.

As the normal query returns the children I would expect the wait to have the same behavior.

In [#603](https://github.com/coreos/etcd/issues/603#issuecomment-37367771) there was a similar discussion.

```bash
$ curl -L '33.33.33.11:4001/v2/keys/directory' -XPUT -d dir=true
{"action":"set","node":{"key":"/directory","dir":true,"modifiedIndex":48038,"createdIndex":48038}}
$ curl -L '33.33.33.11:4001/v2/keys/directory/key' -XPUT -d value=value
{"action":"set","node":{"key":"/directory/key","value":"value","modifiedIndex":48110,"createdIndex":48110}}
$ curl -L '33.33.33.11:4001/v2/keys/directory?wait=true&waitIndex=48039'
# wont return
```

Are there any plans on watching for changes of the children?

**Comment by drnic** [comment]
Any new discussions internally/escalation of road map for watching for new directories (and not all the other changes in a tree)?

**Comment by xiang90** [comment]
@drnic No. Sorry. We are working on v3. But for v3, etcd will only support flat key-value space and support watch on prefix or a key.

**Comment by drnic** [comment]
A WIP script that seems to do the trick:

```
#!/bin/bash

export ETCD_CLUSTER=${ETCD_CLUSTER:-10.244.4.2:4001}
event=$(curl -sL "http://${ETCD_CLUSTER}/v2/keys/service/?wait=true&recursive=true")

while :
do
  eventIndex=$(echo $event | jq -r ".node.modifiedIndex")
  nextEventIndex=$((eventIndex+1))
  if [[ ! -z "${event}" ]]; then
    if [[ "$(echo $event | jq -r .action)" == "create" ]]; then
      echo $event
    fi
  fi
  event=$(curl -sL "http://${ETCD_CLUSTER}/v2/keys/service/?wait=true&recursive=true&waitIndex=${nextEventIndex}")
done
```

**Comment by drnic** [comment]
@xiang90 what do you mean by "flat key-value space" relative to what we have now? happy to read a design doc/blog if that answers it (sorry to not know)

**Comment by xiang90** [comment]
@drnic https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md. Feedback is welcomed.

**Comment by drnic** [comment]
I guess first thing that pops to mind is "HTTP API supports a subset of APIs." - what won't be in HTTP API?

**Comment by xiang90** [comment]
@drnic Not sure yet. We will try best to support all.

**Comment by xiang90** [comment]
We are not going to implement this for v2. As already mentioned in this issue, v3 is a flag key-value space. So the children is irrelevant.
