### ISSUE TITLE
doc: specialized instruction links for administrating etcd

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6335]
Right now the etcd setup documentation is written generically and makes few assumptions about the underlying system. This is somewhat confusing for users wanting to know how to run etcd on coreos (or whatever). Instead, the etcd documentation should have clear links to admin instructions (managed outside the etcd repo) for specific systems.

/cc @cap10morgan

**Comment by gyuho** [comment]
I think http://play.etcd.io/install addresses this issue. Not sure how we should officialize.

**Comment by heyitsanthony** [comment]
@gyuho #7956 closes this?

**Comment by gyuho** [comment]
Yes. Thanks.
