### ISSUE TITLE
raft: rand.NewSource is bulky (allow configuration or share a singleton)

### ISSUE THREAD

**Issue by petermattis** [coreos/etcd#6347]
[`raft.newRaft`](https://github.com/coreos/etcd/blob/master/raft/raft.go#L247) currently hard codes the creation of a `rand.Rand` using `rand.New(rand.NewSource())`. `rand.NewSource` creates a surprisingly large object weighing in at 4872 bytes. With a small number of raft groups in a process this isn't a problem. But CockroachDB is now getting up to thousands of raft groups. With 10k raft groups we'd use 46MB for these random sources. And they are not performance critical. As far as I can tell, the only usage is in [`raft.resetRandomizedElectionTimeout`](https://github.com/coreos/etcd/blob/master/raft/raft.go#L1026-L1028).

Can we make `raft.rand` configurable via `raft.Config`? Alternately, could we change `raft` to have a singleton `rand.Rand` instead of one per `raft.raft`? I'm happy to implement either change and submit a PR.

**Comment by xiang90** [comment]
Singleton sounds reasonable. If you want to make this more fancy, we can try put that into config. Both are fine with me.
