### ISSUE TITLE
Is "snapshot save/restore" command supposed to restore V2 data store?

### ISSUE THREAD

**Issue by sergeyfd** [coreos/etcd#6363]
Hello,

I've been testing snapshot  save and restore command and it seems that it handles V3 data store only. Is it supposed to save/restore V2 data store? Is there a way to backup/restore both version of data store with a single set of commands?

Thanks.

**Comment by heyitsanthony** [comment]
@sergeyfd `snapshot` is for the v3 keyspace only. The v2 keyspace uses `backup`/`restore`. There's no single command pair that will do backup for both v2 and v3 at the moment.

**Comment by sergeyfd** [comment]
Let me ask one more question. What is the best way to recover a 3 node cluster if two members of it were lost along with data? Can I re-initialize the cluster using data from the survived member?

**Comment by heyitsanthony** [comment]
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md is the suggested way to do it.

**Comment by sergeyfd** [comment]
As you stated above that will restore V3 keystore, but not V2. What is the way to restore both? Am I supposed to run both snapshot and backup for that? What if I don't have backup copy or a snapshot but do have data on one of the nodes.

**Comment by xiang90** [comment]
@sergeyfd There is no way to do that. You need to do it separately. We do not suggest you to use v2 and v3 together for a long time . We support v2 + v3 running together mainly for migration reasons.

**Comment by xiang90** [comment]
I am going to close this due to low activity. @sergeyfd feel free to reopen if you have a follow up question. Thanks!
