### ISSUE TITLE
TestCtlV3Lock: Error: lost watcher waiting for delete

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6366]
via semaphore (https://semaphoreci.com/coreos/etcd/branches/master/builds/883)

```
--- FAIL: TestCtlV3Lock (0.90s)
	ctl_v3_lock_test.go:91: expected different lock name, got l1="a/186d56fd1a038e04\r\n", l2="Error:  lost watcher waiting for delete\r\n"
```

**Comment by xiang90** [comment]
Do you have any idea why this failed? I tried to reproduce this, but I cannot. I read through the code, but do not have any idea at the moment.

**Comment by heyitsanthony** [comment]
Possibly a subtle watcher bug. I doubt it's lock specific.

**Comment by xiang90** [comment]
I found a similar issue with elect. So probably a watcher bug.

**Comment by heyitsanthony** [comment]
@xiang90 Has this shown up again? I think we can close this.

**Comment by xiang90** [comment]
I never see it again. i think we can close this.

**Comment by heyitsanthony** [comment]
ack
