### ISSUE TITLE
i have some questions to ask why etcd can create a hidden node and when i need to use it?

### ISSUE THREAD

**Issue by cherylhan** [coreos/etcd#6375]
recently，i am reading zhe website https://coreos.com/etcd/docs/latest/api.html。and，i want ask some question？

**Comment by gyuho** [comment]
What do you mean by `hidden node`? And feel free to ask questions here.

**Comment by cherylhan** [comment]
like this curl http://127.0.0.1:2379/v2/keys/_message -XPUT -d value="Hello hidden world"
when i need to use this？ if i forget the path，how can i find it？

**Comment by xiang90** [comment]
The hidden was designed for security through obscurity. So you cannot find the hidden key from API which is by design. You can find it if you can access the local disk though.
