### ISSUE TITLE
etcdctl v3: Not able to verify transaction example via CMD

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6377]
I am not able to figure out how to verify the transaction example given in Readme.md of etcdctl via the command prompt.

On trying to execute the example i am getting the below error:
![image](https://cloud.githubusercontent.com/assets/20169156/18312201/2ce60514-7526-11e6-97a8-b8827050b136.png)

Can someone suggest how to verify it.

**Comment by heyitsanthony** [comment]
@sinsharat txns need newlines between the condition/success/failure blocks (this is given in the documentation).

```sh
$ ETCDCTL_API=3 ./bin/etcdctl txn -i
compares:
mod("key1") > "0"

success requests (get, put, delete):
put key1 "overwrote-key1"

failure requests (get, put, delete):
put key1 "created-key1"
put key2 "some extra key"

FAILURE

OK

OK
```

**Comment by sinsharat** [comment]
@heyitsanthony I had tried that as well, but the moment i put a new line it gives the same error.
![image](https://cloud.githubusercontent.com/assets/20169156/18338156/5e69ba20-75b4-11e6-9acc-91b847ae5a63.png)

Please let me know what i am doing wrong.
Thanks.

**Comment by gyuho** [comment]
@sinsharat Seems like we need Windows-specific code to read new line character

https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/txn_command.go#L76

`\n` is not going to work in Windows, I think.

Do you want to try fixing it? Think we just need to define `readCompares` separately in `txn_command_windows.go`.

**Comment by sinsharat** [comment]
@gyuho  sure will look into it and try and fix the issue.
