### ISSUE TITLE
Possible cluster unavailability on few file systems -- documenation issue?

### ISSUE THREAD

**Issue by ramanala** [coreos/etcd#6379]
1 rename(source="/data/etcd/infra0.etcd/member/wal/0000000000000001-000000000000001b.wal.tmp", dest="/data/etcd/infra0.etcd/member/wal/0000000000000001-000000000000001b.wal")
2 append("/data/etcd/infra0.etcd/member/wal/0000000000000001-000000000000001b.wal", offset=88, inode=14711139, count=4096, implied_deps={1: 160, 2: 159, 3: 20})
3 append("/data/etcd/infra0.etcd/member/wal/0000000000000001-000000000000001b.wal", offset=4184, inode=14711139, count=4242, implied_deps={1: 160, 2: 159, 3: 20})
4 fdatasync("/data/etcd/infra0.etcd/member/wal/0000000000000001-000000000000001b.wal", size=8426, inode=14711139, implied_deps={1: 160, 2: 159, 3: 20})

I see the above sequence of system calls when etcd appends a user data item to its wal file. If a crash happens just when the third append is in progress then during recovery, the server will crash with the following error in its debug-log-file.

...timestamp.... I | etcdmain: etcd Version: 2.3.0
...timestamp.... I | etcdmain: Git SHA: 3719912
...timestamp.... I | etcdmain: Go Version: go1.6
...timestamp.... I | etcdmain: Go OS/Arch: linux/amd64
...timestamp.... I | etcdmain: setting maximum number of CPUs to 40, total number of available CPUs is 40
...timestamp.... N | etcdmain: the server is already initialized as member before, starting as etcd member...
...timestamp.... I | etcdmain: listening for peers on http://172.17.0.2:2380
...timestamp.... I | etcdmain: listening for client requests on http://172.17.0.2:2379
...timestamp.... I | etcdserver: name = infra0
...timestamp... I | etcdserver: data dir = /data/etcd/infra0.etcd/
...timestamp... I | etcdserver: member dir = /data/etcd/infra0.etcd/member
...timestamp.... I | etcdserver: heartbeat = 100ms
...timestamp.... I | etcdserver: election = 1000ms
...timestamp.... I | etcdserver: snapshot count = 10000
...timestamp.... I | etcdserver: advertise client URLs = http://172.17.0.2:2379
...timestamp.... C | etcdserver: read wal error (walpb: crc mismatch) and cannot be repaired

The reason for the above is as follows: in file systems such as ext3 in writeback mode, a crash during an append of a file can leave the file with garbage or zeros. In ext4, only zeros are allowed but not garbage. When the wal contains garbage after a crash (possible in ext3-wb), etcd server will fail to recover. Notice that if there are only zeros resulting in the wal after the crash, etcd cleanly recovers from such a state with the following message in its log file:

...timestamp... I | etcdserver: repaired WAL error (unexpected EOF)
...timestamp... W | wal: ignored file 0000000000000000-0000000000000000.wal.broken in wal

Two nodes in a three node cluster can easily get into this state and so the majority of servers can go unusable. Thus, the third node in the cluster cannot make progress alone as there is no majority, rendering the cluster unavailable.

Since this bug can occur currently only ext3-writeback mode (and on any future file system this has this property), a fix may be overkill. I believe a note in the documentation saying that etcd would face these problems when run file systems such as ext3-wb would be great.

**Comment by heyitsanthony** [comment]
The WAL doesn't rely on O_APPEND in 3.0. Closing

**Comment by xiang90** [comment]
> When the wal contains garbage after a crash (possible in ext3-wb), etcd server will fail to recover. 

We are aware of this issue before.

We fixed this by always writing a full record or a full page to OS. file system seems never try to write garbage across pages. So we can assume that any garbage is from the last record, and we can truncate it. This issue seems to be fixed in our testing infrastructure.
