### ISSUE TITLE
functional-tests: stress leases

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6380]
We would like to ensure lease related operations are handled correctly in failure recovery path but currently there is no lease testing in the functional tester.

Invariants to test:
* Lease should not expire before the returned TTL
* Any key attached to an expired/revoked lease should be removed
* All members key + lease state should have same hash for the same revision

Implementation would be a new stresser, `leaseStresser`:
* creates N lease and attach M keys onto each lease it creates. Sends keeps alive to all created leases.
* randomly the leaseStresser drops leases from the set of leases it keeps; creates new lease to replace it.
* checks the dropped leases are expired, and the keys attached to them are deleted.
* checks the invariants

Work break down

1. Setup etcd locally with 3 etcd clusters including agent
2. Run functional tester on the local etcd clusters
3. Modify the code for lease testing
4. Testing the modification locally.
5. Send PR for review

**Comment by fanminshi** [comment]
Working on setting up the etcd cluster locally

**Comment by fanminshi** [comment]
Followed the instructions on https://github.com/coreos/etcd/tree/master/tools/functional-tester to get functional tester running locally.

**Comment by fanminshi** [comment]
Discovered a performance issue regarding to leases deletion after being expired. Performance increases code https://github.com/coreos/etcd/pull/6459

**Comment by fanminshi** [comment]
experiencing connection problem when running the functional tester. similar to the one as https://github.com/coreos/etcd/issues/6488

**Comment by fanminshi** [comment]
Found bug that causes a etcd node to die when `LeaseTimeToLive()` function is used in lease functional testing.  https://github.com/coreos/etcd/issues/6537.

**Comment by fanminshi** [comment]
find another bug on on inconsistent hash https://github.com/coreos/etcd/issues/6558.
