### ISSUE TITLE
etcd cluster issue

### ISSUE THREAD

**Issue by muralibandi** [coreos/etcd#6392]
I am trying to setup etcd cluster with 5nodes. Able to start etcd but when i try with etcdctl member list is showing individual etcd hosts. Spent hours fixing this issue but no luck.

master-01  # etcdctl member list
ce2a822cea30bfca: name=master peerURLs=http://localhost:2380,http://localhost:7001 clientURLs=http://10.90.3.57:2379 isLeader=true
master-01 #

**Comment by gyuho** [comment]
How did you set up etcd? Can you share your commands?

**Comment by muralibandi** [comment]
Here is my /var/lib/coreos_install/user_data file config with respect to etcd2


coreos:
  etcd2:
    name: master
    advertise-client-urls: http://10.90.3.57:2379
    initial-advertise-peer-urls: http://10.90.3.57:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://0.0.0.0:2380
    initial-cluster-token: coreOS-staging
    initial-cluster: master=http://10.90.3.57:2380,worker01=http://10.90.3.60:2380,worker02=http://10.90.3.61:2380,worker03=http://10.90.3.62:2380,worker04=http://10.90.3.63:2380
  units:
  - name: etcd2.service
    command: start
    enable: true

**Comment by muralibandi** [comment]
I just noticed that all the nodes in the cluster are showing the same member id, not sure how this is.

**Comment by xiang90** [comment]
There is a misconfiguration happened on your side. The configuration etcd accepted is different from what you showed in this thread

The two members you showed also have same urls
```
peerURLs=http://localhost:2380,http://localhost:7001
```

But you actually wants:

```
initial-advertise-peer-urls: http://10.90.3.57:2380
```

Please double check that you provide etcd the correct configuration file, env variable or flags.

Thank you!
