### ISSUE TITLE
add more jargon from the docs to glossary

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6394]
via irc,

The current glossary (https://github.com/coreos/etcd/blob/master/Documentation/learning/glossary.md) is skeletal. There's no mention of keys, keyspaces, revisions, versions, compaction, watches, transactions, etc.

**Comment by xiang90** [comment]
@sinsharat Can you help on this one a little bit? I think you already know most of the concept well.

**Comment by sinsharat** [comment]
@xiang90 sure will look into it.
Thank you!

**Comment by sinsharat** [comment]
@xiang90 @heyitsanthony I have identified as the below items which can be added to the glossary:
## Members
## Keys
## Keyspaces - not sure about its defination. (is it being referred for the flags?)
## Revisions
## Versions
## Snapshot
## Lease
## Compaction
## Watches
## Transactions
## Roles
## Users
## Authentication
## Endpoint
## Election
## Quorum
## Mirroring
## Migration
## Alarm

Let me know if i have missed any. Will add it to the glossary as well.

Thank you!

**Comment by sinsharat** [comment]
Also 
## Store
## Command

**Comment by sinsharat** [comment]
closing this since the task is completed.

**Comment by xiang90** [comment]
I think current glossary is good enough to close this issue.
