### ISSUE TITLE
simpleBalancer.Up: close of closed channel

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6395]
via semaphore (https://semaphoreci.com/coreos/etcd/branches/master/builds/908)

```
=== RUN   ExampleKV_putErrorHandling
panic: close of closed channel

goroutine 615 [running]:
panic(0x1041b60, 0xc823231f80)
	/usr/local/golang/1.6.3/go/src/runtime/panic.go:481 +0x3ff
github.com/coreos/etcd/clientv3.(*simpleBalancer).Up(0xc8232008c0, 0xc8201eeb07, 0x2d, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/balancer.go:79 +0xa5
google.golang.org/grpc.(*addrConn).resetTransport(0xc8233e0000, 0x0, 0x0, 0x0)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/clientconn.go:694 +0x10f6
google.golang.org/grpc.(*ClientConn).resetAddrConn.func1(0xc8233e0000)
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/clientconn.go:459 +0x38
created by google.golang.org/grpc.(*ClientConn).resetAddrConn
	/home/runner/workspace/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/clientconn.go:468 +0xb9
```

**Comment by xiang90** [comment]
@heyitsanthony It seems that balancer.Up is called even if balancer.Close is called. Shall we fix this at etcd side? Or grpc side?

**Comment by heyitsanthony** [comment]
@xiang90 if `Up` is being called after `Close`, that sounds like a grpc issue. I don't think it's a good idea to work around it.

**Comment by xiang90** [comment]
@heyitsanthony Their balancer: https://github.com/grpc/grpc-go/blob/master/balancer.go can deal with that. I have a simple fix for our balancer at hand. But I will see why this happen in gRPC first.

**Comment by heyitsanthony** [comment]
@xiang90 ok judging by the simple balancer close path, the fix on the etcd side would be about 3 lines of code? might as well have the workaround for now since rolling grpc forward will probably break something else
