### ISSUE TITLE
Possible to avoid recursive symlink?

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#6431]
The cmd directory of this repo contains a recursive symlink back to the parent directory.  Would it be possible to remove that?  I've found several tools either get caught in an infinite loop when searching the directory (for example, python's setuptools tooling), or they emit errors warning of the infinite loop (e.g. grep and find).

(If you're wondering why I'm using python setuptools in a go repo, it's because we're migrating some parts of the product to go for performance so we currently have a hybrid repo.)

**Comment by gyuho** [comment]
Do you import package in etcd or have the whole repo in your project?

We use symlinks for vendoring etcd dependencies, for official releases, and to avoid dependency conflicts. If you import e.g. clientv3 of etcd, you shouldn't need to worry about symlinks.

**Comment by fasaxc** [comment]
I'm using glide to manage my vendor directory.  I'm using this in my glide.yaml but it still seems to check out `cmd` and other directories:
```
- package: github.com/coreos/etcd
  subpackages:
  - client
  - pkg/transport
```
Is `github.com/coreos/etcd` the right import to use or is there a packaged version of jus the client somewhere?

**Comment by gyuho** [comment]
@fasaxc Not sure, you might ask `glide` team about it.

We have other projects that import etcd package with glide, with no problem.

https://github.com/coreos/etcd-play/blob/master/glide.yaml#L5-L14

**Comment by fasaxc** [comment]
I think I'm just going to adjust the repo structure so that the vendor dir is not in the same directory as our python code, that'll sidestep the main issue that I have.

**Comment by gyuho** [comment]
@fasaxc Ok, please feel free to re-open this if you still have issues. Thanks!
