### ISSUE TITLE
Metrics missing / documentation outdated

### ISSUE THREAD

**Issue by discordianfish** [coreos/etcd#6432]
Hi,

looks like https://coreos.com/etcd/docs/latest/metrics.html is outdated.

It looks like some mentioned metrics were removed in 598fa7a10ead85398aa9317d3071d2b64ae0c75e.

What is the reason for the removal? I'm especially interested in proposal_duration_seconds which I consider important to monitor.

**Comment by xiang90** [comment]
See #6342. CoreOS doc is synced with etcd repo. The doc in etcd repo is the "official" doc. We should update CoreOS one.

**Comment by xiang90** [comment]
If you really want to see the duration for requests, probably you want to use unary_requests_duration_seconds instead. it provides more detailed data.
