### ISSUE TITLE
Basic auth configuration with kubernetes

### ISSUE THREAD

**Issue by johnbazan** [coreos/etcd#6442]
Hello guys, I have a question.

I'm currently working with kubernetes and I need a way to pass my credentials to it in the url / environment variables since kubernetes has no configuration parameters to set etcd credentials.

Back in etcdctl 2.1.3, I was able to do something like this:

export ETCDCTL_PEERS=export ETCDCTL_PEERS=http://root:toor@etcd2-0.etcd-server:2379

core@ip-172-32-65-56 ~/etcd-v2.1.3-linux-amd64 $ ./etcdctl --version
etcdctl version 2.1.3
core@ip-172-32-65-56 ~/etcd-v2.1.3-linux-amd64 $ ./etcdctl --no-sync set /private value
value

And it was working just fine, but in the 2.2.1 (the one that I think kubernetes is using) it doesn't work anymore

core@ip-172-32-65-56 ~ $ etcdctl --version
etcdctl version 2.2.3
core@ip-172-32-65-56 ~ $ etcdctl --no-sync set /private value
Error:  110: The request requires user authentication (Insufficient credentials) [0]

So, here's my question:

Given that kubernetes has no configuration to use something like -u root:toor, is there any environment variable that I could set in the docker container to authenticate against etcd?

If not, is there any other solution I could use to make my kubernetes api-server use my root user and role?

Thanks a lot guys.

**Comment by xiang90** [comment]
@johnbazan Does k8s use etcdctl? I think k8s use etcd client not its command line tool.

**Comment by xiang90** [comment]
@johnbazan kindly ping

**Comment by johnbazan** [comment]
I saw that they we're sticking with an specific version of etcdctl, but I was not able to keep on seeing their code since I ran out of time.
I'll close this since it was just a question for an alternative way to set the credentials in etcdctl.
