### ISSUE TITLE
Query: related to etcdctl/ctlv3 features

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6448]
Hi i had the below queries on the etcdctl/ctlv3 features:

1. **Lock** : What is the use of taking lock and how it can be used.

2. **Compaction**: How to find the various revisions for performing compaction.

3. **Elect**: Is Elect command used for montioring the elections or does it have some other purpose/benifits?

4. **Sanpshot**: How to findout which is the latest snapshot that can be taken. Since whenever i try to take snapshot with command  ./etcdctl --endpoints=<endpoint-url> snapshot save snapshot.db, i get the below error: 
Error:  could not rename snapshot.db.part to snapshot.db (rename snapshot.db.part snapshot.db: The process cannot access the file because it is being used by another process.)

**Comment by gyuho** [comment]
We have examples if you want to know how to use it

- https://github.com/coreos/etcd/blob/master/Documentation/demo.md#distributed-locks
- https://github.com/coreos/etcd/blob/master/Documentation/demo.md#elections

You can find compaction from get response (in JSON or protobuf). Example code can be found in our testing cluster code https://github.com/coreos/etcd/blob/master/tools/functional-tester/etcd-tester/cluster.go#L226-L240.

Regarding snapshot, it seems like Windows error?

**Comment by sinsharat** [comment]
@gyuho : **Lock,Elect**: I have already gone through these examples and used them, what i wanted to know is the practical scenario in which we can use locks and elect?
**Compaction** : Also for compaction,  wanted to know why don't we have an api for getting the revision for a particular machine in a cluster directly so that a 3rd party needn't write the code for the same to get the revision for performing compaction from external?

**Comment by gyuho** [comment]
I think just `Get` request to any machine is enough to query revision index? Do you have meaningful use case? We also have auto-compaction https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#history-compaction.

**Comment by gyuho** [comment]
Lock is useful for wherever distributed lock is needed. Elect, you can use it to elect database leader. 

If you want to know more of real-world use cases,

- Zookeeper recipes https://zookeeper.apache.org/doc/trunk/recipes.html
- Chubby paper http://static.googleusercontent.com/media/research.google.com/en//archive/chubby-osdi06.pdf

@heyitsanthony should have better explanation.

**Comment by gyuho** [comment]
@sinsharat Could you create a separate issue for Windows renaming error? Thanks!

**Comment by sinsharat** [comment]
@gyuho Thanks for help.
Yes sure will raise the windows issue seperately.
Thank you!

**Comment by gyuho** [comment]
@sinsharat Closing. Please post any questions if any.

**Comment by sinsharat** [comment]
@gyuho sure thanks!

**Comment by sinsharat** [comment]
@gyuho just needed one confirmation from you, Are distributed locks used for performing upgrades?

**Comment by heyitsanthony** [comment]
@sinsharat probably. Distributed shared locks have around for at least three decades, someone somewhere must have already used them to orchestrate some upgrade process.
