### ISSUE TITLE
Windows: Save snapshot giving command giving error.

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6451]
Steps to reproducce:
./etcdctl --endpoints=$ENDPOINT snapshot save snapshot.db
i get the below error: 
Error: could not rename snapshot.db.part to snapshot.db (rename snapshot.db.part snapshot.db: The process cannot access the file because it is being used by another process.)

**Comment by xiang90** [comment]
@sinsharat Probably you can help to fix this? I am not really familiar with windows :(.

**Comment by sinsharat** [comment]
@xiang90 sure will look into it and try to fix it.

**Comment by xiang90** [comment]
Fixed by #6454. Thanks @sinsharat

**Comment by sinsharat** [comment]
@xiang90 You are most welcome :-)
