### ISSUE TITLE
wal/wal.go:  WAL.Save can be optimized to do Marshal outside the mutex lock

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#6452]
In wal package, the WAL.Save and WAL.SaveSnapshot aquire a mutex at the beginning of the method.

The entries and snapshot need to be marshalled before encoding. I think the Marshal step can be done without aquiring the mutex. This will improve throughput.

**Comment by xiang90** [comment]
The snapshot one is already fixed.
