### ISSUE TITLE
Test: Getting timeout error for make-mirror modify dest prefix

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6468]
I wrote one test case as specified below:

```go
func TestCtlV3MakeMirrorModifyPrefix(t *testing.T) { testCtl(t, makeMirrorModifyPrefixTest) }
func makeMirrorModifyPrefixTest(cx ctlCtx) {
	// set up another cluster to mirror with
	cfg := configAutoTLS
	cfg.clusterSize = 1
	cfg.basePort = 10000
	cx2 := ctlCtx{
		t:           cx.t,
		cfg:         cfg,
		dialTimeout: 7 * time.Second,
	}

	epc, err := newEtcdProcessCluster(&cx2.cfg)
	if err != nil {
		cx.t.Fatalf("could not start etcd process cluster (%v)", err)
	}
	cx2.epc = epc

	defer func() {
		if err = cx2.epc.Close(); err != nil {
			cx.t.Fatalf("error closing etcd processes (%v)", err)
		}
	}()

	cmdArgs := append(cx.PrefixArgs(), "make-mirror", "--prefix o_", "--dest-prefix d_", fmt.Sprintf("localhost:%d", cfg.basePort))
	proc, err := spawnCmd(cmdArgs)
	if err != nil {
		cx.t.Fatal(err)
	}
	defer func() {
		err = proc.Stop()
		if err != nil {
			cx.t.Fatal(err)
		}
	}()

	var kvs = []kv{{"o_key1", "val1"}, {"o_key2", "val2"}, {"o_key3", "val3"}}
	for i := range kvs {
		if err = ctlV3Put(cx, kvs[i].key, kvs[i].val, ""); err != nil {
			cx.t.Fatal(err)
		}
	}

	if err = ctlV3Get(cx, []string{"o_key", "--prefix"}, kvs...); err != nil {
		cx.t.Fatal(err)
	}

	var kvs2 = []kv{{"d_key1", "val1"}, {"d_key2", "val2"}, {"d_key3", "val3"}}

	if err = ctlV3Watch(cx2, []string{"d_key", "--rev", "1", "--prefix"}, kvs2...); err != nil {
		cx.t.Fatal(err)
	}
}
```

But on executing the test case i am getting the error: test timeout for 7s

I put some logs in the execution flow and below is the logs which i am getting:
`=== RUN   TestCtlV3MakeMirrorModifyPrefix
Going to execute cmd : [./etcd --name testname0 --listen-client-urls http://localhost:20000 --advertise-client-urls http://localhost:20000 --listen-peer-urls https://localhost:20001 --initial-advertise-peer-urls https://localhost:20001 --initial-cluster-token new --data-dir /tmp/testname0.etcd868156682 --snapshot-count 10000 --peer-auto-tls=true --initial-cluster testname0=https://localhost:20001]
Going to execute cmd : [./etcd --name testname0 --listen-client-urls http://localhost:10000 --advertise-client-urls http://localhost:10000 --listen-peer-urls https://localhost:10001 --initial-advertise-peer-urls https://localhost:10001 --initial-cluster-token new --data-dir /tmp/testname0.etcd832967905 --snapshot-count 10000 --peer-auto-tls=true --initial-cluster testname0=https://localhost:10001]
Going to execute cmd : [./etcdctl --endpoints localhost:20000 --dial-timeout 7s make-mirror --prefix o_ --dest-prefix d_ localhost:10000]
Going to execute cmd : [./etcdctl --endpoints localhost:20000 --dial-timeout 7s put o_key1 val1]
Going to execute cmd : [./etcdctl --endpoints localhost:20000 --dial-timeout 7s put o_key2 val2]
Going to execute cmd : [./etcdctl --endpoints localhost:20000 --dial-timeout 7s put o_key3 val3]
Going to execute get command with args : [./etcdctl --endpoints localhost:20000 --dial-timeout 7s get o_key --prefix --consistency s] and expected result is : [o_key1 val1 o_key2 val2 o_key3 val3]
Going to execute cmd : [./etcdctl --endpoints localhost:20000 --dial-timeout 7s get o_key --prefix --consistency s]
Going to execute cmd : [./etcdctl --endpoints localhost:10000 --dial-timeout 7s watch d_key --rev 1 --prefix]
--- FAIL: TestCtlV3MakeMirrorModifyPrefix (16.17s)
        ctl_v3_test.go:138: test timed out for 7s`

When i execute the same set of steps manually in shell i am getting the expected output.

Is there anything i am doing wrong? Please help.
Thank you.

**Comment by sinsharat** [comment]
@gyuho Request you to look into this. Need your help.
Thank you!

**Comment by sinsharat** [comment]
@gyuho i think the issue is happening due to usage of new flags while executing the make-mirror command. Since for the old test case as well when i used these flags with prefix and dest-prefix same, it started timing out.

**Comment by gyuho** [comment]
@sinsharat Try `"--prefix", "o_"`, not `"--prefix o_"`

**Comment by sinsharat** [comment]
@gyuho Thanks a lot! it worked. :)
