### ISSUE TITLE
Add NewWithTimeout(cfg Config) (*Client, error)

### ISSUE THREAD

**Issue by zbindenren** [coreos/etcd#6479]
Hi

First of all: thanks for that great software!

I tried to write a etcd cluster health check for a tool we are creating.

I was inspired by the code in [etcdctl](https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/ep_command.go). And I noticed a strange behavior in the clients `New` method, when the etcd daemon is not running.

Here the test:
```go

var endoints = []string{"localhost:1111"} // nothing is listening here

func TestHealth(t *testing.T) {
	ep := endoints[0]
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{ep},
	})
	fmt.Println("code never gets here")
	if err != nil {
		t.Errorf("ep %s unhealthy: %s", ep, err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	_, err = cli.Get(ctx, "/mule-test/health")
	fmt.Println("never gets called")
	cancel()
	if err != nil {
		t.Errorf("ep %s unhealthy: %s", ep, err)
	}
	fmt.Printf("ep %s is healthy", ep)

}
```

I see the following endpoint:
```
2016/09/20 07:32:23 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:1111: getsockopt: connection refused"; Reconnecting to {"localhost:1111" <nil>}
2016/09/20 07:32:24 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:1111: getsockopt: connection refused"; Reconnecting to {"localhost:1111" <nil>}
2016/09/20 07:32:26 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp [::1]:1111: getsockopt: connection refused"; Reconnecting to {"localhost:1111" <nil>}
```

Test hangs until timeout.

As workaround I can use `net.DialTimeout(network, address string, timeout time.Duration)`.

It was just surprising to me and I was wondering if this is wanted behavior.

**Comment by heyitsanthony** [comment]
It's hanging because `clientv3.New` used to block until it could establish a connection to the cluster. It now only blocks if a `DialTimeout` is given. Cf. #6162 for more background. Thanks!
