### ISSUE TITLE
Query: ctlv3 get

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6480]
I had few queries regarding get command:
1. when output is requested in json format, the key and value returned are encrypted values always. What is the reason for always returning encrypted value? What is the encryption being used?
2. with -w=json option --hex doesn't work. Can we give error for such things to maintain consistency as we are giving for -w=table.
3. Would like to know about an example for fromkey to understand the main purpose for using it.
4. Also how would range be used. Example to test it would be great.
Screenshot attached below:
![image](https://cloud.githubusercontent.com/assets/20169156/18666966/31a9af80-7f4c-11e6-951e-3ba4f9e935b0.png)

**Comment by xiang90** [comment]
> encrypted values always

they are not encrypted. They are in base64 format. JSON encodes bytes array into base64 string.

> with -w=json option --hex doesn't work.

It does not work since JSON already encodes it as base64 string. We should not overwrite it.

> Would like to know about an example for fromkey to understand the main purpose for using it.

fromKey is an open ending range. You can get all keys that are larger than "foo" for example

> Also how would range be used. Example to test it would be great.


If you have keys: foo1, foo2, foo3...foo9
You can use range to get keys rang from `foo1` to `foo9`. Then you can see keys foo1, foo2, ... foo8. You can organize your keys with prefix or in some ranges. Then you can use range to query them.

**Comment by sinsharat** [comment]
@xiang90 Thanks for the information. Just still not clear what is meant by larger than foo for fromKey?

**Comment by xiang90** [comment]
>  larger than foo for fromKey?

a is larger b -> bytes.Compare(a, b) >0

In the previous example, if you do --from-key foo, you will see all keys that are larger than foo. They are: foo1, foo2 ..., foo9

**Comment by sinsharat** [comment]
@xiang90 thanks a lot for clarification. Will try it out.
Thanks!

**Comment by xiang90** [comment]
Closing this out. Please help improving our documentation :) Thank you!

**Comment by sinsharat** [comment]
@xiang90 sure!
Thanks!

**Comment by sinsharat** [comment]
@xiang90 Can we add examples for --fromkey and range end examples to the doc. I feel without these many can get confused. What do you suggest?

**Comment by sinsharat** [comment]
Or at-least modify the descriptions to make it more clear. Like the explaination which you provided?

**Comment by xiang90** [comment]
> Can we add examples for --fromkey and range end examples to the doc. I feel without these many can get confused. What do you suggest?

In which doc? https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/interacting_v3.md#read-keys? Feel free to update it. I can do it later this week or next week if you are busy.

**Comment by sinsharat** [comment]
@xiang90 sure will do it no issues.
