### ISSUE TITLE
Certificate format: pem only?

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6482]
Hi~
I just wonder whether the etcd only supports certificate or key whose format is **pem**? Can I use some other certificate whose format is different from pem, such as **keystore**? We want to ensure a more secure SSL communication with specificed certificate, and as far as I know, **etcd does not support to encrypt certificate in PEM format**. 
Looking forward to your reply.
@xiang90  @gyuho @heyitsanthony

**Comment by heyitsanthony** [comment]
> We want to ensure a more secure SSL communication with specificed certificate

What is your threat model?

**Comment by xiang90** [comment]
Closing this due to low activity. Please reopen if this is still an issue.
