### ISSUE TITLE
keepalive when network reset

### ISSUE THREAD

**Issue by woodcutter007** [coreos/etcd#6483]
I use keepalive, when the network is break, call client.Grant is block. But after a long time, the network is reset, Grant is not continue. Is it a bug. I use version 3.0.0. and watch is ok.
tks.

**Comment by xiang90** [comment]
Can you provide a simple script to reproduce the issue?

**Comment by woodcutter007** [comment]
I break the network by manual, and the keepalive code is below.

func EtcdKeepAlive(key, value string, ttl int64) {

	fmt.Println("[EtcdKeepAlive]")
	client := Etcd_Manager.Client
	//create ttl node with 10s and keepalive forever
	if (ttl == 0) {
		ttl = 5
	}
	lease := clientv3.NewLease(client)
	resp, err := lease.Grant(context.TODO(), ttl)
	if err != nil {
		fmt.Println("[EtcdKeepAlive]", err)

		return
	}

	_, err = client.Put(context.TODO(), key, value, clientv3.WithLease(resp.ID))
	if err != nil {
		fmt.Println("[EtcdKeepAlive]", err)

		return
	}

	// the key 'foo' will be kept forever
	ch, kaerr := lease.KeepAlive(context.TODO(), resp.ID)
	if kaerr != nil {
		fmt.Println("[EtcdKeepAlive]", err)

		return
	}
	go func() {
		for {
			resp := <-ch
			if resp == nil {
				lease.Close()
				break
			}else {
				fmt.Println(resp.TTL)
			}
		}
		EtcdKeepAlive(key, value, ttl)
	}()
}

**Comment by xiang90** [comment]
> I break the network by manual

How? Modify IP tables? Or unplug wire?

**Comment by woodcutter007** [comment]
disable the network card, and the  phenomena is not  necessary

**Comment by xiang90** [comment]
>  phenomena is not necessary

What does this mean?

**Comment by woodcutter007** [comment]
This is not inevitable

**Comment by heyitsanthony** [comment]
@woodcutter007 there were some bugs in grpc and reconnect handling in 3.0.0; try this again with 3.0.9?

**Comment by woodcutter007** [comment]
ok, I will try it.   thanks

**Comment by xiang90** [comment]
@woodcutter007 Any update?

**Comment by woodcutter007** [comment]
yes, I have try sometimes, using v3.0.9, keepalive is ok. thanks
