### ISSUE TITLE
etcd server timeout error

### ISSUE THREAD

**Issue by Rucongzhang** [coreos/etcd#6490]
Hi:
I am a newer to ETCD. I find a ETCD bug. The bug is described following:
we use etcd 2.1.1 version. We install server alone. we create a temporary node with ttl=5S by etcd client and update the ttl every sercond. At same time, we wirte flie .Every record is 1MB, the write rate is about 250MB per Second. When write persist about 5 mins, the client occur error that is the temporary node is not find and the server log is all following error:
etcdhttp: got unexpected response error(etcdserver:request timed out).

The write flie code is attachment "test.txt"
[test.txt](https://github.com/coreos/etcd/files/484493/test.txt)

How disk IO affect the ETCD server? Does the server write something? What is the max write rate and persist time that the etcd server can process the client request without timeout?
Thank you very much!

**Comment by xiang90** [comment]
@Rucongzhang etcd is designed to store metadata, not data. etcd2 has a total size limit round 250MB, and total key limit around 100K. Please make sure you do not write huge amount of data into etcd2. etcd3 can do better but still you cannot expect etcd to store > 10GB of data. It is not designed for that.

**Comment by Rucongzhang** [comment]
Hi Xiang:
              Thank you for your quick answer. But I do not write data to ETCD. I write data to disk. I test how the disk IO affect the etcd server. Thank you.

**Comment by Rucongzhang** [comment]
@xiang90 :Thank you for your quick answer. But I do not write data to ETCD. I write data to disk. I test how the disk IO affect the etcd server. Thank you.

**Comment by xiang90** [comment]
@Rucongzhang Sorry. I misunderstood your question. It depends on how OS schedule the writes. If etcd cannot fsync to disk for 1 second, then there will be issues. It might trigger leader election for example. etcd is very disk latency sensitive. We usually suggest users to use separate disk for etcd WAL file for reliable performance.

**Comment by Rucongzhang** [comment]
@xiang90  Do you have any detail material which introduce why etcd is very disk latency sensitive? Thank you!

**Comment by xiang90** [comment]
@Rucongzhang No. I do not have. etcd relies on Raft to maintain its leadership and replicate data. If you are interested, I would suggest you to read raft paper. Thanks.

**Comment by xiang90** [comment]
Question are answered. Closing this issue. Let us know if you have any further questions.
