### ISSUE TITLE
Watch chan fails with "client connection closing" under stress test

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#6503]
After #6476 is fixed,  rerunning the stress test for a long time (~1h) still gives out error:
```
rpc error: code = 9 desc = grpc: the client connection is closing
```

This is from the watch chan err response:
```
        for resp := range wch {
                if resp.Err() != nil {
                    t.Fatal(resp.Err())
                }
        ...
```

Script to keep test running:
```shell
while [ 1 ] ; do
  go test -v ./etcdbench -count 20 || break
done
```

**Comment by hongchaodeng** [comment]
cc @xiang90 @heyitsanthony

**Comment by heyitsanthony** [comment]
I added `clus.Members[0].DropConnections()` after the `Watch` in `TestWatchOverlapContextCancel` to stress the reconnect path with ctx cancelation and got unexpected closed channels. Probably related.
