### ISSUE TITLE
raft: Expose checkQuorumActive

### ISSUE THREAD

**Issue by doodles526** [coreos/etcd#6509]
Is there a particular reason why checkQuorumActive isn't exposed? Currently we can get this by `Status()` -> `map[id]Progress` -> iterate over `Progress.RecentActive`. 

But that's just what checkQuorumActive already does. Is there any objection to a PR to change checkQuorumActive to CheckQuorumActive?

**Comment by gyuho** [comment]
Do you mean adding a method `CheckQuorumActive` to `raft.Node` interface?

I don't have objection. Defer to @xiang90

**Comment by doodles526** [comment]
Correct. That's what I'm intending

**Comment by xiang90** [comment]
@doodles526 Sure. Can you send a pr to add that into the Node interface? Thanks!

**Comment by doodles526** [comment]
After trying to implement this, I don't think it will work as intended. Only the leader will know if the quorum is active, since it's the only one who is receiving heartbeats and AppResps from followers

**Comment by xiang90** [comment]
@doodles526 Right. This is the constraint. etcd actually uses prober to do health checking outside raft. If you still think this is useful, go ahead and implement it. Or you can close this.
