### ISSUE TITLE
Predicate writing a key with another's modifiedIndex

### ISSUE THREAD

**Issue by bmizerany** [coreos/etcd#652]
Scenario:

Client A wants to write a key iff another critical key's value has not changed since it last read its value.

```
GET /schema/version
{value: 2, modifiedIndex: 66}
```

Client A determines it can update another key `/foo` because of its arbitrary rule based on `/schema/version` being `2` at the time the write is applied to the store. To avoid a race where Client B updates `/schema/version` between Client A's read of `/schema/version` and its write of `/foo`, we need a write-predicate.

Example:
```
PUT /foo
value=bar&predicatePath=/schema/version&predicateIndex=66

200 OK
```

If the `PUT` fails then:

```
412 Precondition Failed
```

This API is purely for demonstration and likely needs more thought.

**Comment by xiang90** [comment]
Addressed by v3 api rfc.
