### ISSUE TITLE
raft: PreVote RPC

### ISSUE THREAD

**Issue by bdarnell** [coreos/etcd#6522]
We'd like to implement the Pre-Vote RPC for Raft. CheckQuorum solves a lot of the same problems as PreVote, but for various reasons we're thinking about turning that off (to take more control of time-related operations at the higher levels of the application). 

Do you have any objections or thoughts before I get started on this? Should this be implemented as a new StatePreCandidate, or is it just some kind of flag within the existing candidate state?

**Comment by xiang90** [comment]
I do not have objection as long as we can make it optionally.

**Comment by xiang90** [comment]
@bdarnell It probably would be cleaner if we add a pre vote state? Have you looked at other impls? I think mongodb/raft, copycat/raft already implemented pre-vote. Maybe we shall see how they do it?
