### ISSUE TITLE
Does not build under Debian 8 32-bit, also repo problem

### ISSUE THREAD

**Issue by raindog308** [coreos/etcd#6526]
No 32-bit releases of etcd?  Bummer, heavy sigh.

Tried to follow [these directions](https://github.com/coreos/etcd/blob/master/Documentation/dl_build.md#build-the-latest-version)...sadness ensued.

**Problem 1 - git clone directions don't work**

```
root@compiler:/usr/local/src/go# export GOPATH=`pwd`
root@compiler:/usr/local/src/go# go version
go version go1.7.1 linux/386
root@compiler:/usr/local/src/go# echo $GOPATH
/usr/local/src/go
root@compiler:/usr/local/src/go# mkdir -p $GOPATH/src/github.com/coreos
root@compiler:/usr/local/src/go# cd $GOPATH/src/github.com/coreos
root@compiler:/usr/local/src/go/src/github.com/coreos# git clone github.com:coreos/etcd.git
Cloning into 'etcd'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Problem 2 - build from source doesn't work**

```
root@compiler:/usr/local/src# tar xzf etcd-3.0.10.tar.gz 
root@compiler:/usr/local/src# cd etcd-3.0.10/
root@compiler:/usr/local/src/etcd-3.0.10# export GOPATH=`pwd`
root@compiler:/usr/local/src/etcd-3.0.10# ./build
fatal: Not a git repository (or any of the parent directories): .git
can't load package: package github.com/coreos/etcd/cmd: cannot find package "github.com/coreos/etcd/cmd" in any of:
	/usr/local/go/src/github.com/coreos/etcd/cmd (from $GOROOT)
	/usr/local/src/etcd-3.0.10/src/github.com/coreos/etcd/cmd (from $GOPATH)
can't load package: package github.com/coreos/etcd/cmd/etcdctl: cannot find package "github.com/coreos/etcd/cmd/etcdctl" in any of:
	/usr/local/go/src/github.com/coreos/etcd/cmd/etcdctl (from $GOROOT)
	/usr/local/src/etcd-3.0.10/src/github.com/coreos/etcd/cmd/etcdctl (from $GOPATH)

```

Maybe if I try this...

```
root@compiler:/usr/local/src/etcd-3.0.10# go get github.com/coreos/etcd
# github.com/coreos/etcd/clientv3
src/github.com/coreos/etcd/clientv3/client.go:290: cannot use client.balancer (type *simpleBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
	*simpleBalancer does not implement grpc.Balancer (wrong type for Start method)
		have Start(string) error
		want Start(string, grpc.BalancerConfig) error

```

This is on a very generic 32-bit DigitalOcean Debian 8 VM with build-essential and git installed.

**Comment by xiang90** [comment]
GitHub isn't able to authenticate you. So, either you aren't setup with an SSH key, because you haven't set one up on your machine, or your key isn't associated with your GitHub account.

You can try to do git clone https://github.com/coreos/etcd.git instead.

**Comment by raindog308** [comment]
Apparently, the documentation is broken (I was copy/pasting it, as demonstrated above).

Also, I'm not sure why the documentation would expect me to log into Github to clone a public repo.

Also, cloning and building with your correctly git works (just did it), but manually running downloading a release and following the directions (as demonstrated above) does not work on 32-bit Deb 8.

But hey, party on...

**Comment by xiang90** [comment]
@raindog308 Can you send a patch to change the clone command? Thanks.

**Comment by heyitsanthony** [comment]
This doc bug / build bug hasn't been fixed. Reopening.
