### ISSUE TITLE
clientv3 go get failing.

### ISSUE THREAD

**Issue by lacion** [coreos/etcd#6528]
using go get is currently resulting in an error.

this is happening to me locally using OSX El Capitan and go 1.7.1 and in travis ci using go 1.7.1
```
go get github.com/coreos/etcd/clientv3
# github.com/coreos/etcd/clientv3
../../coreos/etcd/clientv3/client.go:245: cannot use client.balancer (type *simpleBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
	*simpleBalancer does not implement grpc.Balancer (wrong type for Start method)
		have Start(string) error
		want Start(string, grpc.BalancerConfig) error
```

**Comment by xiang90** [comment]
gRPC breaks the API. We will update etcd client later. You need to revert your gRPC dependency to their most recent release 1.0 instead of using head for now.
