### ISSUE TITLE
clientv3 compile fail

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6529]
It looks like grps.Balancer modify interface.
```
# github.com/coreos/etcd/clientv3
../../coreos/etcd/clientv3/client.go:290: cannot use client.balancer (type *simpleBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
	*simpleBalancer does not implement grpc.Balancer (wrong type for Start method)
		have Start(string) error
		want Start(string, grpc.BalancerConfig) error
github.com/stretchr/testify/mock
```

**Comment by gyuho** [comment]
This was introduced via https://github.com/grpc/grpc-go/pull/899.

/cc @heyitsanthony

**Comment by xiang90** [comment]
@gyuho gRPC does not have any release after 1.0. We should not update the dependency at the moment.

**Comment by nitinmuppalaneni** [comment]
I had to do this. 

etcd> git diff                                                                     nmuppalaneni@nmuppalaneni-vm etcd> git diff
diff --git a/clientv3/balancer.go b/clientv3/balancer.go                                                        diff --git a/clientv3/balancer.go b/clientv3/balancer.go
index 011f6cf..16df457 100644                                                                                   index 011f6cf..16df457 100644
--- a/clientv3/balancer.go                                                                                      --- a/clientv3/balancer.go
+++ b/clientv3/balancer.go                                                                                      +++ b/clientv3/balancer.go
@@ -72,7 +72,9 @@ func newSimpleBalancer(eps []string) *simpleBalancer {                                        @@ -72,7 +72,9 @@ func newSimpleBalancer(eps []string) *simpleBalancer {
        return sb                                                                                                       return sb
 }                                                                                                               }
                                                                                                                
-func (b *simpleBalancer) Start(target string) error { return nil }                                             -func (b *simpleBalancer) Start(target string) error { return nil }
+//func (b *simpleBalancer) Start(target string) error { return nil }                                           +//func (b *simpleBalancer) Start(target string) error { return nil }
+                                                                                                               +
+func (b *simpleBalancer) Start(target string, cfg grpc.BalancerConfig) error { return nil }                    +func (b *simpleBalancer) Start(target string, cfg grpc.BalancerConfig) error { return nil }
                                                                                                                
 func (b *simpleBalancer) ConnectNotify() <-chan struct{} {                                                      func (b *simpleBalancer) ConnectNotify() <-chan struct{} {
        b.mu.Lock()

**Comment by SuhasAnand** [comment]
cc @SuhasAnand

**Comment by akaspin** [comment]
Any moves? This code on godoc. You are released it. Four days! Are you absolutely do not respect yourself?

**Comment by xiang90** [comment]
@akaspin You totally do not understand the problem and do not read my previous reply. You should respect others in the community.

As I mentioned, gRPC broke their API and has not released a version with this API. Users should vendor the correct version of gRPC. There is nothing we can do much now.

**Comment by akaspin** [comment]
@xiang90 Oh no! I totally understand the problem. What I see? I see totally dead code. Four day. **Four working days.** I see `go get github.com/coreos/etcd/clientv3` in docs. What I don't see? I don't see any mentions or workarounds. No reaction. I see completely disregard. "This is introduced ... Google not released new version ...". This is a joke? There are two versions. Last - in August. Who here does not respect the community?

**Comment by xiang90** [comment]
@akaspin

Your last response confirmed that you do not understand how go vendor/dependency management works at the moment. Your project needs to vendor all dependencies. Or any indirect dependencies breakage can break the library you depend on (like gRPC broke their API and your etcd client broke). You need to vendor your dependencies. This is not workaround, this is something you have to do.

Again, we are not going to update etcd/clientv3 until gRPC release a version with the new API. The current API change is in the unreleased version. And you are getting that unreleased version for your project, which you probably should not do as I mentioned.

**Comment by akaspin** [comment]
@xiang90 Wow! I'm right enlightened! "You need to vendor your dependencies ..." Wow! Really! (however, that vendor breaks the types and it can not be excluded if the test directory. and much better to override GOPATH. never mind) But ... It ... Uh ... [`go get github.com/coreos/etcd/clientv3`](https://github.com/coreos/etcd/tree/master/clientv3#install). Hour of my life is trashed.

**Comment by xiang90** [comment]
@akaspin 

In the go get doc:

```
Get downloads the packages named by the import paths, along with their
dependencies. It then installs the named packages,
```

So it downloads both package itself and the missing dependencies. This is not ideal since it is not versioning aware. But this is not an etcd specific issue. Go developers should be aware of that.

If you believe we should improve the doc, can you please open another issue? Probably we can make clear that go get also download dependencies, which might not be what you want. Or you can help to improve it directly by opening a pull request? Thanks.

**Comment by Son-Lam** [comment]
We are stuck right now. Would you recommend any work around? I am using godep too. But if the got get fails then how I can use godep to save the vendor package anyway. I already roll back to version 3.0.8 without any luck.

**Comment by gyuho** [comment]
@Son-Lam `go get` doesn't handle the dependency as far as I know.

You should try `go get -d` that skips compiling. And vendor your project with etcd's gRPC git SHA.

**Comment by oikomi** [comment]
This problem seems to cause a lot of trouble to etcd newer

Need to pay attention to this bad influence

**Comment by Son-Lam** [comment]
Hi,

To be clear, it is not coreos/etcd' problem. The problem is the gRPC guys changed interfaces. It affecting new users. I got it work by vendoring my dependencies to the exact snapshot of grpc (SHA 231b4cfea0e79843053a33f5fe90bd4d84b23cd3).

Maybe, coreos/etcd should put up some work-around instruction and/or update to match up with grpc 1.1.0 interface.

Thanks,

**Comment by junweiyang** [comment]
many people are stuck right now!
i think u should gix this problem!

**Comment by felix** [comment]
If you are using the [gvt](https://github.com/FiloSottile/gvt) vendoring tool just ensure your manifest has the following:
```json
{
    "importpath": "google.golang.org/grpc",
    "repository": "https://github.com/grpc/grpc-go",
    "vcs": "git",
    "revision": "231b4cfea0e79843053a33f5fe90bd4d84b23cd3",
    "branch": "master",
    "notests": true
},
```
The importat part being the revision hash obviously.

**Comment by gyuho** [comment]
Sorry for the delay.  Should work now.

Again we recommend:

> etcd uses cmd/vendor directory to store external dependencies, which are to be compiled into etcd release binaries. client can be imported without vendoring. For full compatibility, it is recommended to vendor builds using etcd's vendored packages, using tools like godep, as in vendor directories. For more detail, please read Go vendor design.

Thanks,

**Comment by zaa** [comment]
Could you please backport the modification (https://github.com/coreos/etcd/pull/6617/files#diff-3ac56ebeb8ecf6f62729390be572416eR75) to 3.0.x branch? Otherwise build of the v3.0.12 version does not work. I would rather vendor v3.0.x in our code base than 3.1.x-alpha with the fix.

Thank you.

**Comment by gyuho** [comment]
@zaa Sorry, unlikely.

Our policy is to only backport bug patches. Is there any reason that your project does not use the same gRPC as `release-3.0` branch?
