### ISSUE TITLE
Query: apply entries took too long for 1 get request

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#6530]
Environment:
` 4 core, Intel i5 , 4 GB , Ubuntu 14.04`

started 3 node etcd cluster in local machine using

` goreman start`
the Procfile is the default provided, no changes.

did a get operation using root user
`./etcdctl get key1 --user=root`

get following text in the logs:

19:25:07 etcd3 | 2016-09-27 19:25:07.511023 I | auth: authorized root, token is xWyuAJdKSJYXpOne.1765
19:25:07 etcd3 | 2016-09-27 19:25:07.511068 W | etcdserver: apply entries took too long [79.880367ms for 1 entries]
19:25:07 etcd3 | 2016-09-27 19:25:07.511076 W | etcdserver: avoid queries with large range/delete range!
19:25:07 etcd2 | 2016-09-27 19:25:07.521366 I | auth: authorized root, token is xWyuAJdKSJYXpOne.1765
19:25:07 etcd2 | 2016-09-27 19:25:07.521439 W | etcdserver: apply entries took too long [90.269411ms for 1 entries]
19:25:07 etcd2 | 2016-09-27 19:25:07.521482 W | etcdserver: avoid queries with large range/delete range!
19:25:07 etcd1 | 2016-09-27 19:25:07.526534 I | auth: authorized root, token is xWyuAJdKSJYXpOne.1765
19:25:07 etcd1 | 2016-09-27 19:25:07.526579 W | etcdserver: apply entries took too long [95.582386ms for 1 entries]
19:25:07 etcd1 | 2016-09-27 19:25:07.526588 W | etcdserver: avoid queries with large range/delete range!

Memory Usage:
![top-etcd](https://cloud.githubusercontent.com/assets/3284044/18877375/ae7f681c-84ea-11e6-89fc-037210aabc95.png)

takes 10 GB per process

Query:
- why does a get operation generates this log, as if the nodes are under load ? did i miss to set some options?
- is the memory usage normal? what can i do to reduce it.
- using v3 api, does a get request go through the raft layer? is there a non-linearizable read option in v3 , which doesnt go through raft layer?

**Comment by vimalk78** [comment]
following log also appears after a while

19:40:46 etcd1 | 2016-09-27 19:40:46.747570 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 191.216803ms)
19:40:46 etcd1 | 2016-09-27 19:40:46.747599 W | etcdserver: server is likely overloaded
19:40:46 etcd1 | 2016-09-27 19:40:46.747605 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 191.271395ms)
19:40:46 etcd1 | 2016-09-27 19:40:46.747609 W | etcdserver: server is likely overloaded
19:46:21 etcd1 | 2016-09-27 19:46:21.443803 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 387.366925ms)
19:46:21 etcd1 | 2016-09-27 19:46:21.443828 W | etcdserver: server is likely overloaded
19:46:21 etcd1 | 2016-09-27 19:46:21.443838 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 387.411279ms)
19:46:21 etcd1 | 2016-09-27 19:46:21.443844 W | etcdserver: server is likely overloaded

**Comment by xiang90** [comment]
Does the machine have SSD or HDD?

**Comment by vimalk78** [comment]
It uses an HDD

vimal@Tardis /home/vimal $ sudo smartctl -i /dev/sda
smartctl 6.2 2013-07-26 r3841 [x86_64-linux-3.19.0-68-generic] (local build)
Copyright (C) 2002-13, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Western Digital Caviar Blue Serial ATA
Device Model:     WDC WD3200AAJS-60Z0A0
Serial Number:    WD-WMAV2HW06484
LU WWN Device Id: 5 0014ee 002bf71cf
Firmware Version: 03.03E03
User Capacity:    320,072,933,376 bytes [320 GB]
Sector Size:      512 bytes logical/physical
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ATA8-ACS (minor revision not indicated)
SATA Version is:  SATA 2.5, 3.0 Gb/s
Local Time is:    Tue Sep 27 21:04:48 2016 IST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled

**Comment by xiang90** [comment]
You probably cannot run 3 etcd members on the same machine that share the single HDD. It is too slow.

**Comment by vimalk78** [comment]
ok.

can you also pls respond about the other queries

Thanks !!

**Comment by xiang90** [comment]
> using v3 api, does a get request go through the raft layer? is there a non-linearizable read option in v3 , which doesnt go through raft layer?

use consistency=s, which is a local read.

**Comment by xiang90** [comment]
> is the memory usage normal? what can i do to reduce it.

it is 10GB virtual memory. The RSS is 2.7MB.

**Comment by xiang90** [comment]
@vimalk78 Can you please separate questions/issues into different github issues. it is easier for us to answer and easier for other people to search around. thanks.

**Comment by vimalk78** [comment]
> use consistency=s, which is a local read.

how to use this option from etcdctl

> it is 10GB virtual memory. The RSS is 2.7MB.

i am new to Go, still isnt 10 GB Virtual memory for a fresh process a bit much.

**Comment by xiang90** [comment]
> how to use this option from etcdctl?

--consistency=s

> i am new to Go, still isnt 10 GB Virtual memory for a fresh process a bit much.

etcd uses mmap. Is 10GB virtual memory causing you any issue?

**Comment by vimalk78** [comment]
> --consistency=s
but i dont see any such option in etcdctl GLOBAL OPTIONS

> etcd uses mmap. Is 10GB virtual memory causing you any issue?
no it is not causing any issue, i was expecting less mem usage from a Go process :)

**Comment by xiang90** [comment]
It is just for get. so it wont be in global options. you cannot do local write.

**Comment by vimalk78** [comment]
> It is just for get. so it wont be in global options. you cannot do local write.

ok, i see it in the `/etcdctl help get`

**Comment by vimalk78** [comment]
> @vimalk78 Can you please separate questions/issues into different github issues

ok , i will log different queries in different issues.

3q ^_^

**Comment by xiang90** [comment]
OK. For the latency warning, please try with SSD or run etcd on dedicated nodes. Thanks.

**Comment by vimalk78** [comment]
i tested on my macbook, i get same result.

Processor Name:	Intel Core i5
Processor Speed:	2.6 GHz
APPLE SSD 256 GB

01:47:46 etcd2 | 2016-09-28 01:47:46.876054 I | auth: authorized root, token is KcAXrUysCxYmDgYk.569
01:47:46 etcd2 | 2016-09-28 01:47:46.876082 W | etcdserver: apply entries took too long [99.955703ms for 1 entries]
01:47:46 etcd2 | 2016-09-28 01:47:46.876089 W | etcdserver: avoid queries with large range/delete range!
01:47:46 etcd3 | 2016-09-28 01:47:46.877533 I | auth: authorized root, token is KcAXrUysCxYmDgYk.569
01:47:46 etcd3 | 2016-09-28 01:47:46.877554 W | etcdserver: apply entries took too long [101.534968ms for 1 entries]
01:47:46 etcd3 | 2016-09-28 01:47:46.877560 W | etcdserver: avoid queries with large range/delete range!
01:47:46 etcd1 | 2016-09-28 01:47:46.878085 I | auth: authorized root, token is KcAXrUysCxYmDgYk.569
01:47:46 etcd1 | 2016-09-28 01:47:46.878102 W | etcdserver: apply entries took too long [102.362764ms for 1 entries]
01:47:46 etcd1 | 2016-09-28 01:47:46.878107 W | etcdserver: avoid queries with large range/delete range!

**Comment by xiang90** [comment]
Can you try to get the metrics from `clienturl/metrics` on each members in the cluster?

**Comment by vimalk78** [comment]
ok. i have restarted the cluster freshly, and performed following operations from `etcdctl`

```
vimal (master) bin $ ./etcdctl user add root
Password of root: 
Type password of root again for confirmation: 
User root created
vimal (master) bin $ ./etcdctl role add root
Role root created
vimal (master) bin $ ./etcdctl user grant-role root root
Role root is granted to user root
vimal (master) bin $ ./etcdctl auth enable
Authentication Enabled
vimal (master) bin $ ./etcdctl put key1 val1 --user=root
Password: 
OK
vimal (master) bin $ 
vimal (master) bin $ ./etcdctl member list -w table
+------------------+---------+--------+------------------------+------------------------+
|        ID        | STATUS  |  NAME  |       PEER ADDRS       |      CLIENT ADDRS      |
+------------------+---------+--------+------------------------+------------------------+
| 8211f1d0f64f3269 | started | infra1 | http://127.0.0.1:12380 | http://127.0.0.1:2379  |
| 91bc3c398fb3c146 | started | infra2 | http://127.0.0.1:22380 | http://127.0.0.1:22379 |
| fd422379fda50e48 | started | infra3 | http://127.0.0.1:32380 | http://127.0.0.1:32379 |
+------------------+---------+--------+------------------------+------------------------+
vimal (master) bin $ curl http://127.0.0.1:2379/metrics > metrics.2379.txt
vimal (master) bin $ curl http://127.0.0.1:22379/metrics > metrics.22379.txt
vimal (master) bin $ curl http://127.0.0.1:32379/metrics > metrics.32379.txt
```
which mertic you wanted me to check,"etcd_disk_wal_fsync_duration_seconds histogram" ?
i am attaching the metrics


[metrics.32379.txt](https://github.com/coreos/etcd/files/496967/metrics.32379.txt)
[metrics.22379.txt](https://github.com/coreos/etcd/files/496968/metrics.22379.txt)
[metrics.2379.txt](https://github.com/coreos/etcd/files/496969/metrics.2379.txt)

**Comment by xiang90** [comment]
```
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 310
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 311
```

There are a few fsyncs took more than 100ms, which triggered the warning. Typically, fsync takes <10ms on SSD.

**Comment by vimalk78** [comment]
is there a way to clear the metric after startup. so that it doesnt include startup fsync cost

**Comment by xiang90** [comment]
@vimalk78 No. But you can get the diff by querying it twice or setup Prometheus to monitor the metrics.

**Comment by vimalk78** [comment]
i added a log to print the cost of sync, in wal/wal.go

```
425 func (w *WAL) sync() error {
426     if w.encoder != nil {
427         if err := w.encoder.flush(); err != nil {
428             return err
429         }
430     }
431     start := time.Now()
432     err := fileutil.Fdatasync(w.tail().File)
433 
434     duration := time.Since(start)
435     plog.Warningf("wal/wal.go: WAL.sync: sync duration of %v", duration)
436     if duration > warnSyncDuration {
437         plog.Warningf("sync duration of %v, expected less than %v", duration, warnSyncDuration)
438     }   
439     syncDurations.Observe(duration.Seconds())
440         
441     return err
442 }   
```

i get the same result on macbook with SSD

for `./etcdctl put key1 val1 --user=root`

0:52:31 etcd1 | 2016-09-28 10:52:31.456417 W | wal: wal/wal.go: WAL.sync: sync duration of 12.658596ms
10:52:31 etcd2 | 2016-09-28 10:52:31.948671 W | wal: wal/wal.go: WAL.sync: sync duration of 4.862794ms
10:52:31 etcd1 | 2016-09-28 10:52:31.951545 W | wal: wal/wal.go: WAL.sync: sync duration of 7.972584ms
10:52:31 etcd3 | 2016-09-28 10:52:31.955170 W | wal: wal/wal.go: WAL.sync: sync duration of 11.371981ms
10:52:32 etcd2 | 2016-09-28 10:52:32.449009 W | wal: wal/wal.go: WAL.sync: sync duration of 4.99968ms
10:52:32 etcd3 | 2016-09-28 10:52:32.452911 W | wal: wal/wal.go: WAL.sync: sync duration of 8.894677ms
10:52:32 etcd1 | 2016-09-28 10:52:32.456783 W | wal: wal/wal.go: WAL.sync: sync duration of 12.960416ms
10:52:32 etcd2 | 2016-09-28 10:52:32.948676 W | wal: wal/wal.go: WAL.sync: sync duration of 4.765974ms
10:52:32 etcd3 | 2016-09-28 10:52:32.952293 W | wal: wal/wal.go: WAL.sync: sync duration of 8.249578ms
10:52:32 etcd1 | 2016-09-28 10:52:32.955854 W | wal: wal/wal.go: WAL.sync: sync duration of 12.112695ms
10:52:33 etcd1 | 2016-09-28 10:52:33.448450 W | wal: wal/wal.go: WAL.sync: sync duration of 4.644408ms
10:52:33 etcd2 | 2016-09-28 10:52:33.452029 W | wal: wal/wal.go: WAL.sync: sync duration of 7.99861ms
10:52:33 etcd3 | 2016-09-28 10:52:33.455826 W | wal: wal/wal.go: WAL.sync: sync duration of 11.711395ms
10:52:33 etcd3 | 2016-09-28 10:52:33.948967 W | wal: wal/wal.go: WAL.sync: sync duration of 4.966998ms
10:52:33 etcd2 | 2016-09-28 10:52:33.953003 W | wal: wal/wal.go: WAL.sync: sync duration of 8.979615ms
10:52:33 etcd1 | 2016-09-28 10:52:33.956981 W | wal: wal/wal.go: WAL.sync: sync duration of 13.186798ms
10:52:34 etcd2 | 2016-09-28 10:52:34.448828 W | wal: wal/wal.go: WAL.sync: sync duration of 4.808263ms
10:52:34 etcd3 | 2016-09-28 10:52:34.452370 W | wal: wal/wal.go: WAL.sync: sync duration of 8.279741ms
10:52:34 etcd1 | 2016-09-28 10:52:34.455875 W | wal: wal/wal.go: WAL.sync: sync duration of 12.065541ms
10:52:34 etcd2 | 2016-09-28 10:52:34.664349 W | wal: wal/wal.go: WAL.sync: sync duration of 4.730436ms
10:52:34 etcd3 | 2016-09-28 10:52:34.667901 W | wal: wal/wal.go: WAL.sync: sync duration of 8.268238ms
10:52:34 etcd1 | 2016-09-28 10:52:34.671326 W | wal: wal/wal.go: WAL.sync: sync duration of 11.857072ms
10:52:34 etcd1 | 2016-09-28 10:52:34.784484 I | auth: authorized root, token is GdAtUFqPLTleYqNp.120
10:52:34 etcd1 | 2016-09-28 10:52:34.784512 W | etcdserver: apply entries took too long [113.081608ms for 1 entries]
10:52:34 etcd1 | 2016-09-28 10:52:34.784544 W | etcdserver: avoid queries with large range/delete range!
10:52:34 etcd3 | 2016-09-28 10:52:34.786776 I | auth: authorized root, token is GdAtUFqPLTleYqNp.120
10:52:34 etcd3 | 2016-09-28 10:52:34.786851 W | etcdserver: apply entries took too long [115.183844ms for 1 entries]
10:52:34 etcd3 | 2016-09-28 10:52:34.786862 W | etcdserver: avoid queries with large range/delete range!
10:52:34 etcd3 | 2016-09-28 10:52:34.789645 W | wal: wal/wal.go: WAL.sync: sync duration of 3.977359ms
10:52:34 etcd2 | 2016-09-28 10:52:34.790052 I | auth: authorized root, token is GdAtUFqPLTleYqNp.120
10:52:34 etcd2 | 2016-09-28 10:52:34.790073 W | etcdserver: apply entries took too long [118.462242ms for 1 entries]
10:52:34 etcd2 | 2016-09-28 10:52:34.790079 W | etcdserver: avoid queries with large range/delete range!
10:52:34 etcd2 | 2016-09-28 10:52:34.792772 W | wal: wal/wal.go: WAL.sync: sync duration of 7.095156ms
10:52:34 etcd1 | 2016-09-28 10:52:34.795879 W | wal: wal/wal.go: WAL.sync: sync duration of 10.321791ms
10:52:34 etcd1 | 2016-09-28 10:52:34.948458 W | wal: wal/wal.go: WAL.sync: sync duration of 4.605493ms
10:52:34 etcd3 | 2016-09-28 10:52:34.951439 W | wal: wal/wal.go: WAL.sync: sync duration of 7.142112ms
10:52:34 etcd2 | 2016-09-28 10:52:34.954985 W | wal: wal/wal.go: WAL.sync: sync duration of 10.989116ms
10:52:35 etcd2 | 2016-09-28 10:52:35.448650 W | wal: wal/wal.go: WAL.sync: sync duration of 4.607731ms
10:52:35 etcd3 | 2016-09-28 10:52:35.452146 W | wal: wal/wal.go: WAL.sync: sync duration of 8.103521ms
10:52:35 etcd1 | 2016-09-28 10:52:35.455960 W | wal: wal/wal.go: WAL.sync: sync duration of 12.13561ms
10:52:35 etcd2 | 2016-09-28 10:52:35.948631 W | wal: wal/wal.go: WAL.sync: sync duration of 4.587029ms
10:52:35 etcd3 | 2016-09-28 10:52:35.952361 W | wal: wal/wal.go: WAL.sync: sync duration of 8.335277ms
10:52:35 etcd1 | 2016-09-28 10:52:35.955832 W | wal: wal/wal.go: WAL.sync: sync duration of 12.023144ms
10:52:36 etcd1 | 2016-09-28 10:52:36.446303 W | wal: wal/wal.go: WAL.sync: sync duration of 3.777395ms
10:52:36 etcd3 | 2016-09-28 10:52:36.449250 W | wal: wal/wal.go: WAL.sync: sync duration of 6.534771ms
10:52:36 etcd2 | 2016-09-28 10:52:36.451876 W | wal: wal/wal.go: WAL.sync: sync duration of 9.231175ms
10:52:36 etcd1 | 2016-09-28 10:52:36.948093 W | wal: wal/wal.go: WAL.sync: sync duration of 4.261986ms
10:52:36 etcd3 | 2016-09-28 10:52:36.951330 W | wal: wal/wal.go: WAL.sync: sync duration of 7.293265ms
10:52:36 etcd2 | 2016-09-28 10:52:36.951345 W | wal: wal/wal.go: WAL.sync: sync duration of 7.320416ms
10:52:37 etcd2 | 2016-09-28 10:52:37.447551 W | wal: wal/wal.go: WAL.sync: sync duration of 4.776849ms
10:52:37 etcd3 | 2016-09-28 10:52:37.450481 W | wal: wal/wal.go: WAL.sync: sync duration of 7.577574ms
10:52:37 etcd1 | 2016-09-28 10:52:37.453904 W | wal: wal/wal.go: WAL.sync: sync duration of 11.384875ms
10:52:37 etcd3 | 2016-09-28 10:52:37.948483 W | wal: wal/wal.go: WAL.sync: sync duration of 4.701587ms
10:52:37 etcd2 | 2016-09-28 10:52:37.952001 W | wal: wal/wal.go: WAL.sync: sync duration of 8.164684ms
10:52:37 etcd1 | 2016-09-28 10:52:37.956100 W | wal: wal/wal.go: WAL.sync: sync duration of 12.57509ms
10:52:38 etcd3 | 2016-09-28 10:52:38.448869 W | wal: wal/wal.go: WAL.sync: sync duration of 4.851255ms
10:52:38 etcd1 | 2016-09-28 10:52:38.452629 W | wal: wal/wal.go: WAL.sync: sync duration of 8.928099ms
10:52:38 etcd2 | 2016-09-28 10:52:38.456082 W | wal: wal/wal.go: WAL.sync: sync duration of 12.133325ms


for `./etcdctl get key1 --user=root`

0:53:12 etcd1 | 2016-09-28 10:53:12.454510 W | wal: wal/wal.go: WAL.sync: sync duration of 11.518357ms
10:53:12 etcd3 | 2016-09-28 10:53:12.949365 W | wal: wal/wal.go: WAL.sync: sync duration of 5.306564ms
10:53:12 etcd2 | 2016-09-28 10:53:12.952978 W | wal: wal/wal.go: WAL.sync: sync duration of 8.91461ms
10:53:12 etcd1 | 2016-09-28 10:53:12.956686 W | wal: wal/wal.go: WAL.sync: sync duration of 12.865763ms
10:53:13 etcd3 | 2016-09-28 10:53:13.448642 W | wal: wal/wal.go: WAL.sync: sync duration of 4.679865ms
10:53:13 etcd2 | 2016-09-28 10:53:13.452054 W | wal: wal/wal.go: WAL.sync: sync duration of 8.06083ms
10:53:13 etcd1 | 2016-09-28 10:53:13.455902 W | wal: wal/wal.go: WAL.sync: sync duration of 12.128368ms
10:53:13 etcd2 | 2016-09-28 10:53:13.949335 W | wal: wal/wal.go: WAL.sync: sync duration of 5.307033ms
10:53:13 etcd3 | 2016-09-28 10:53:13.952472 W | wal: wal/wal.go: WAL.sync: sync duration of 8.447069ms
10:53:13 etcd1 | 2016-09-28 10:53:13.955682 W | wal: wal/wal.go: WAL.sync: sync duration of 11.882526ms
10:53:14 etcd3 | 2016-09-28 10:53:14.448097 W | wal: wal/wal.go: WAL.sync: sync duration of 4.037797ms
10:53:14 etcd2 | 2016-09-28 10:53:14.451212 W | wal: wal/wal.go: WAL.sync: sync duration of 7.048039ms
10:53:14 etcd1 | 2016-09-28 10:53:14.454530 W | wal: wal/wal.go: WAL.sync: sync duration of 10.804351ms
10:53:14 etcd1 | 2016-09-28 10:53:14.949136 W | wal: wal/wal.go: WAL.sync: sync duration of 5.580599ms
10:53:14 etcd3 | 2016-09-28 10:53:14.952719 W | wal: wal/wal.go: WAL.sync: sync duration of 8.898662ms
10:53:14 etcd2 | 2016-09-28 10:53:14.956459 W | wal: wal/wal.go: WAL.sync: sync duration of 12.709476ms
10:53:15 etcd3 | 2016-09-28 10:53:15.447986 W | wal: wal/wal.go: WAL.sync: sync duration of 4.716571ms
10:53:15 etcd2 | 2016-09-28 10:53:15.451476 W | wal: wal/wal.go: WAL.sync: sync duration of 8.207759ms
10:53:15 etcd1 | 2016-09-28 10:53:15.455391 W | wal: wal/wal.go: WAL.sync: sync duration of 12.354475ms
10:53:15 etcd3 | 2016-09-28 10:53:15.949384 W | wal: wal/wal.go: WAL.sync: sync duration of 5.354992ms
10:53:15 etcd2 | 2016-09-28 10:53:15.952506 W | wal: wal/wal.go: WAL.sync: sync duration of 8.455025ms
10:53:15 etcd1 | 2016-09-28 10:53:15.955690 W | wal: wal/wal.go: WAL.sync: sync duration of 11.901307ms
10:53:16 etcd3 | 2016-09-28 10:53:16.448889 W | wal: wal/wal.go: WAL.sync: sync duration of 4.90439ms
10:53:16 etcd2 | 2016-09-28 10:53:16.452347 W | wal: wal/wal.go: WAL.sync: sync duration of 8.276212ms
10:53:16 etcd1 | 2016-09-28 10:53:16.456222 W | wal: wal/wal.go: WAL.sync: sync duration of 12.428219ms
10:53:16 etcd1 | 2016-09-28 10:53:16.777123 W | wal: wal/wal.go: WAL.sync: sync duration of 4.995624ms
10:53:16 etcd3 | 2016-09-28 10:53:16.780212 W | wal: wal/wal.go: WAL.sync: sync duration of 7.990027ms
10:53:16 etcd2 | 2016-09-28 10:53:16.782789 W | wal: wal/wal.go: WAL.sync: sync duration of 10.587943ms
10:53:16 etcd1 | 2016-09-28 10:53:16.896965 I | auth: authorized root, token is wCMSWsQOgVAtMoWK.206
10:53:16 etcd1 | 2016-09-28 10:53:16.897005 W | etcdserver: apply entries took too long [116.484704ms for 1 entries]
10:53:16 etcd1 | 2016-09-28 10:53:16.897013 W | etcdserver: avoid queries with large range/delete range!
10:53:16 etcd2 | 2016-09-28 10:53:16.899351 I | auth: authorized root, token is wCMSWsQOgVAtMoWK.206
10:53:16 etcd2 | 2016-09-28 10:53:16.899374 W | etcdserver: apply entries took too long [116.514504ms for 1 entries]
10:53:16 etcd2 | 2016-09-28 10:53:16.899384 W | etcdserver: avoid queries with large range/delete range!
10:53:16 etcd3 | 2016-09-28 10:53:16.899937 I | auth: authorized root, token is wCMSWsQOgVAtMoWK.206
10:53:16 etcd3 | 2016-09-28 10:53:16.899961 W | etcdserver: apply entries took too long [119.322986ms for 1 entries]
10:53:16 etcd3 | 2016-09-28 10:53:16.899967 W | etcdserver: avoid queries with large range/delete range!
10:53:16 etcd3 | 2016-09-28 10:53:16.947336 W | wal: wal/wal.go: WAL.sync: sync duration of 3.613783ms
10:53:16 etcd1 | 2016-09-28 10:53:16.950621 W | wal: wal/wal.go: WAL.sync: sync duration of 7.143281ms
10:53:16 etcd2 | 2016-09-28 10:53:16.953870 W | wal: wal/wal.go: WAL.sync: sync duration of 10.167636ms
10:53:17 etcd3 | 2016-09-28 10:53:17.449356 W | wal: wal/wal.go: WAL.sync: sync duration of 5.36266ms
10:53:17 etcd2 | 2016-09-28 10:53:17.452788 W | wal: wal/wal.go: WAL.sync: sync duration of 8.790674ms
10:53:17 etcd1 | 2016-09-28 10:53:17.456590 W | wal: wal/wal.go: WAL.sync: sync duration of 12.806633ms
10:53:17 etcd3 | 2016-09-28 10:53:17.948637 W | wal: wal/wal.go: WAL.sync: sync duration of 4.64875ms
10:53:17 etcd2 | 2016-09-28 10:53:17.952177 W | wal: wal/wal.go: WAL.sync: sync duration of 8.131906ms
10:53:17 etcd1 | 2016-09-28 10:53:17.955932 W | wal: wal/wal.go: WAL.sync: sync duration of 12.170315ms
10:53:18 etcd1 | 2016-09-28 10:53:18.451360 W | wal: wal/wal.go: WAL.sync: sync duration of 8.827427ms
10:53:18 etcd2 | 2016-09-28 10:53:18.454598 W | wal: wal/wal.go: WAL.sync: sync duration of 11.86562ms
10:53:18 etcd3 | 2016-09-28 10:53:18.457453 W | wal: wal/wal.go: WAL.sync: sync duration of 14.596357ms
10:53:18 etcd1 | 2016-09-28 10:53:18.947245 W | wal: wal/wal.go: WAL.sync: sync duration of 3.751213ms
10:53:18 etcd3 | 2016-09-28 10:53:18.950735 W | wal: wal/wal.go: WAL.sync: sync duration of 7.001762ms
10:53:18 etcd2 | 2016-09-28 10:53:18.953634 W | wal: wal/wal.go: WAL.sync: sync duration of 9.984703ms
10:53:19 etcd1 | 2016-09-28 10:53:19.446148 W | wal: wal/wal.go: WAL.sync: sync duration of 3.553358ms
10:53:19 etcd2 | 2016-09-28 10:53:19.449994 W | wal: wal/wal.go: WAL.sync: sync duration of 7.097111ms
10:53:19 etcd3 | 2016-09-28 10:53:19.450021 W | wal: wal/wal.go: WAL.sync: sync duration of 7.088475ms
10:53:19 etcd2 | 2016-09-28 10:53:19.949220 W | wal: wal/wal.go: WAL.sync: sync duration of 5.190858ms
10:53:19 etcd3 | 2016-09-28 10:53:19.952641 W | wal: wal/wal.go: WAL.sync: sync duration of 8.533151ms
10:53:19 etcd1 | 2016-09-28 10:53:19.956298 W | wal: wal/wal.go: WAL.sync: sync duration of 12.514236ms

**Comment by xiang90** [comment]
> 10:53:16 etcd1 | 2016-09-28 10:53:16.896965 I | auth: authorized root, token is wCMSWsQOgVAtMoWK.206
10:53:16 etcd1 | 2016-09-28 10:53:16.897005 W | etcdserver: apply entries took too long [116.484704ms for 1 entries]
10:53:16 etcd1 | 2016-09-28 10:53:16.897013 W | etcdserver: avoid queries with large range/delete range!
10:53:16 etcd2

So here is another issue. Auth is computationally extensive by design. It introduces high latency. It can be improved by making it async. I think there is a todo somewhere.

/cc @mitake

**Comment by vimalk78** [comment]
yes, i tested put/get without auth, it doesn't generate any latency logs

i would like to work on this issue/todo

**Comment by mitake** [comment]
@xiang90 @vimalk78 yes, the auth needs a long time because it needs password checking that involves heavy bcrypt operation. If a client uses a long living connection, the cost can be amortized. But clients like `etcdctl` creates connections often and the cost can be problematic.

The bcrypt checking can be excluded from the state machine transition but it needs careful validation and retry based on the auth revision number. I can work on it but do you already have a concrete plan? @vimalk78

**Comment by sinsharat** [comment]
@mitake i think we will need some kind of authentication or encryption for sure. So if auth takes a long time may be having a long connection is a better option, else using it in live systems without any auth will pose risk of leaking data to third party.

**Comment by mitake** [comment]
@sinsharat sure, I thought the long connection is a realistic assumption for the v3 API (it is based on gRPC) but can also understand the concern of the authentication cost. Taking 100ms means a user can execute etcdctl only 10 times per second (it cannot be executed concurrently at all). etcdctl wouldn't be invoked many times in performance sensitive paths but operation miss and bugs in shell scripts might  cause DoS like performance degradation of etcd clusters.

**Comment by sinsharat** [comment]
@mitake i will think over it and try to find a solution on managing both auth, encryption together without taking a tall on performance, Will also think about whether managing encryption from application side will be better than at etcd to avoid performance issues.
Once i come up with solution will discuss with you.
Thanks!

**Comment by mitake** [comment]
@sinsharat I already have an idea for solving the issue so I can share my implementation in the near future (maybe this week or next week).

BTW do you work in the same team? @sinsharat @vimalk78

**Comment by sinsharat** [comment]
@mitake yes we do work together for the same team.

**Comment by mitake** [comment]
@sinsharat @vimalk78 thanks. I'll share it with both of you. Or do you want to work on it if you already have a solid idea (https://github.com/coreos/etcd/issues/6530#issuecomment-250076788)?

**Comment by vimalk78** [comment]
@mitake , no solid idea as of now, going through the code. you can share your thoughts also, we can discuss. then perhaps you can assign to me/sharat for implementation.

**Comment by mitake** [comment]
@vimalk78 ok I'll share my detailed design tomorrow. Please wait for a while.

**Comment by vimalk78** [comment]
just a thought, will it help if etcdctl spawns a shell. the grpc dial up happens at shell startup and for later operations, it uses same authentication token for every request to server.

**Comment by mitake** [comment]
It doesn't seem to be used for non interactive purpose. If we have a workaround in etcdctl side, how about this: add a new command `etcdctl auth` for just getting token and let other etcdctl commands receive the token as their argument?

**Comment by vimalk78** [comment]
this could also work. 
some points need to check though :
- need to check if grpc dialup can accept a token instead of username/password
- whether same token can be used across different grpc sessions?
- is printing the token back to user a security issue? (not too sure about this one)

**Comment by mitake** [comment]
> i checked, it is a security issue to print the token back to user.

I'd like to know the detailed reason. Is this really dangerous? I'm not sure it introduces the risk or not.

@xiang90 how do you think about the idea of the command for obtaining a token?

**Comment by xiang90** [comment]
@mitake Is it possible to make the token generation async? It does not have any side effect. So we do not have to make it blocking.

**Comment by vimalk78** [comment]
if token generation is async, how does the subsequent request, say Put, use
the token.

**Comment by xiang90** [comment]
@vimalk78 It should not block the following commands to be applied. But it blocks client response.

**Comment by mitake** [comment]
@xiang90 sure async auth and generation of token is possible. Validating revision number of auth store can ensure correctness of authentication. But I thought that if the problem is only limited to the case of etcdctl, recycling token can avoid the cost of bcrypt simply (though it cannot prevent other problems like operation misses and bugs in management scripts).

I want to have an agreement about which solution we should work on. The async one would be the optimal. How do you think?

**Comment by vimalk78** [comment]
@xiang90 , i am sorry i dont quite understand your idea
the `clientv3/Client.dial`  needs the Token to invoke `grpc.Dial()` 
or do you want to make the applying the Authenticate async in `EtcdServer.applyEntryNormal` or invoke `bcrypt` in a separate goroutine.
or something else i am totally missing.

thanks!

**Comment by xiang90** [comment]
>  i am sorry i dont quite understand your idea
the clientv3/Client.dial needs the Token to invoke grpc.Dial() 
or do you want to make the applying the Authenticate async in EtcdServer.applyEntryNormal or invoke bcrypt in a separate goroutine. or something else i am totally missing.

I never said it has anything to do with client. The logging you saw is from server side. What you can do it to make server side apply async for authentication by creating a go routine. You probably need to modify the applyResult struct to make it possible to receive on future event.

**Comment by vimalk78** [comment]
as i understand, this will only make the latency log disappear. but the time cost observed at etcdclient will remain same. right?

**Comment by mitake** [comment]
@vimalk78 
> but the time cost observed at etcdclient will remain same. right?

Yes, but the cost is limited to the single client. Other clients don't see the high latency.

**Comment by vimalk78** [comment]
@mitake , referring your comment here
https://github.com/coreos/etcd/issues/6530#issuecomment-250080152

> Taking 100ms means a user can execute etcdctl only 10 times per second (it cannot be executed concurrently at all)

the async solution will not help with this.

**Comment by mitake** [comment]
@vimalk78 yes, the async solution won't reduce the cost of bcrypt. But it will help to improve entire performance of etcd. A number of authnetication requests that can be served by etcd cluster will be increased.

**Comment by vimalk78** [comment]
yes, i t will improve the Autheticate throughput. 
But, the async part needs to be introduced in the ApplyEntries path. which i believe must maintain apply entries in-order. Since Authenticate is something which doesnt affect other operations, perhaps it is ok. 

i will send a PR with this change

**Comment by mitake** [comment]
@vimalk78 sorry but I still can't understand your design yet. Could you share your plan of avoiding the cost of bcrypt without sacrificing the order of applying (I have an idea based on version number validation but yours seems to be different from mine)?

**Comment by vimalk78** [comment]
@mitake  i dont have a design for saving the cost without sacrificing the order. i was simply trying to bring this point in the discussion.
perhaps Authenticate/bcrypt can tolerate out of order execution, so with this assumption i was going to implement

**Comment by xiang90** [comment]
@vimalk78 Please try with current master. @mitake just got this fixed :)

**Comment by vimalk78** [comment]
sure, thanks
