### ISSUE TITLE
etcd v3 client times out after storing 600K keys

### ISSUE THREAD

**Issue by nitinmuppalaneni** [coreos/etcd#6533]
Etcd v3 client is timing out on my test setup after creating ~600K keys (32B key, 0B value). 

Are there any tunables that I need to change to make etcd v3 scale to large number of keys?

Ideally I would like to use as many as 100M keys.

2016-09-27 03:48:49.868443 I | fileutil: purged file default.etcd/member/snap/0000000000000003-00000000002feadc.snap successfully
2016-09-27 05:11:23.137459 I | etcdserver: start to snapshot (applied: 3200322, lastsnap: 3190321)
2016-09-27 05:11:36.394093 W | etcdserver: apply entries took too long [50.23473ms for 1 entries]
2016-09-27 05:11:36.394126 W | etcdserver: avoid queries with large range/delete range!
2016-09-27 05:11:36.706836 W | etcdserver: apply entries took too long [10.798762ms for 1 entries]
2016-09-27 05:11:36.706867 W | etcdserver: avoid queries with large range/delete range!
2016-09-27 05:11:37.179202 W | etcdserver: apply entries took too long [19.277383ms for 1 entries]
2016-09-27 05:11:37.179232 W | etcdserver: avoid queries with large range/delete range!
2016-09-27 05:11:42.802266 I | etcdserver: saved snapshot at index 3200322
2016-09-27 05:11:42.802554 I | etcdserver: compacted raft log at 3195322

[etcd-make-keys.go.txt](https://github.com/coreos/etcd/files/496273/etcd-make-keys.go.txt)

```go
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strconv"
	"time"

	"crypto/rand"
	"io"

	"golang.org/x/net/context"
	//"net/http"

	//"github.com/coreos/etcd/client"
	"github.com/coreos/etcd/clientv3"

	"github.com/codahale/hdrhistogram"
)

const default_concurrency = 1
const default_etcd_url = "http://localhost:2379"

var (
	dialTimeout    = 100 * time.Second
	requestTimeout = 100 * time.Second
)

var (
	g_debug       bool
	g_etcd_url    string
	g_concurrency int64
)

func init() {
	flag.BoolVar(&g_debug, "debug", false, "print debugging information")
	flag.BoolVar(&g_debug, "d", false, "print debugging information")

	flag.StringVar(&g_etcd_url, "etcd", default_etcd_url, "specify etcd url")
	flag.StringVar(&g_etcd_url, "e", default_etcd_url, "specify etcd url")

	flag.Int64Var(&g_concurrency, "concurrency", default_concurrency, "concurrent ops")
	flag.Int64Var(&g_concurrency, "c", default_concurrency, "concurrent ops")
}

func show_usage() {
	fmt.Fprintf(os.Stderr,
		"Usage: %s [-d|--debug] [-c|concurrency=<num>] [-e|etcd=<url>] [ <command> [<args>]\n\n",
		os.Args[0])
	fmt.Fprintf(os.Stderr,
		"Flags:\n")
	flag.PrintDefaults()
	fmt.Fprintf(os.Stderr,
		"\nCommands:\n"+
			"  add-keys <num>   Add the specified numebr of keys (32B key, 0B val)\n"+
			"  list             List the keys\n"+
			"  clean            Remove all the keys\n"+
			"  help             Show usage help\n")
}

func newKey() (string, error) {
	key := make([]byte, 32)
	n, err := io.ReadFull(rand.Reader, key)
	if n != len(key) || err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", key), nil
}

func add_keys(cli *clientv3.Client, num_keys int, hist *hdrhistogram.Histogram) error {
	for i := 0; i < num_keys; i += 1 {
		key, err := newKey()
		if err != nil {
			return err
		}

		key = fmt.Sprintf("/nitin/%v", key)
		log.Printf("Setting '%v' key with 0 value", key)

		start := time.Now()
		ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
		presp, perr := cli.Put(ctx, key, "0")
		cancel()
		if perr != nil {
			log.Printf("Put failed, resp: %v, err: %v", presp, perr)
			return perr
		}
		latns := time.Since(start)
		hist.RecordValue(int64(latns))
	}
	return nil
}

func list_keys(cli *clientv3.Client) error {
	return nil
}

func delete_keys(cli *clientv3.Client) error {
	return nil
}

func NstoMs(ns int64) int64 {
	return ns / int64(time.Millisecond)
}

func main() {
	flag.Usage = show_usage
	flag.Parse()

	var num_keys int
	var err error

	var op string
	if flag.NArg() > 0 {
		op = flag.Arg(0)
		switch op {
		case "add-keys":
			if flag.NArg() <= 1 {
				err = fmt.Errorf("The number of keys is not specified")
				log.Fatal(err)
			}
			num_keys, err = strconv.Atoi(flag.Arg(1))
			if err != nil {
				log.Fatal(err)
			}
		case "list":
		case "clean":
		case "help":
			fallthrough
		default:
			show_usage()
			return
		}
	} else {
		show_usage()
		return
	}

	// Get a client handle to the etcd cluster (for now a single server)
	cfg := clientv3.Config{
		Endpoints:   []string{g_etcd_url},
		DialTimeout: dialTimeout,
	}
	var cli *clientv3.Client
	cli, err = clientv3.New(cfg)
	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close()

	hist := hdrhistogram.New(1, int64(time.Minute), 3)

	switch op {
	case "add-keys":
		err = add_keys(cli, num_keys, hist)
	case "list":
		err = list_keys(cli)
	case "clean":
		err = delete_keys(cli)
	}

	log.Println("Latency distribution:")
	log.Printf("Total: %v, Min: %v ms, Max: %v ms, Mean: %v ms, StdDev: %v\n",
		hist.TotalCount(),
		NstoMs(hist.Min()), NstoMs(hist.Max()), NstoMs(int64(hist.Mean())),
		hist.StdDev())

	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", err)
		os.Exit(1)
	}
}
```

**Comment by xiang90** [comment]
> Are there any tunables that I need to change to make etcd v3 scale to large number of keys?

You cannot store more than 10M keys or 8GB. etcd is not designed for storing large amount of data. It should be used as a metadata store.

**Comment by xiang90** [comment]
What is your setup? We can store 10M keys into etcd without a problem on ec2.xlarge equivalent machines with SSD.

**Comment by nitinmuppalaneni** [comment]
Thank you Xiang for the quick reply.

I am using a VM with 4 cores ( Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz) and 8GB of RAM.
I tried with an SSD and saw the same behavior.

Did you set any config parameters to sustain good latency with 10M keys? What type of key pattern did you use? I am using random 32B keys hitting timeouts much sooner (~600K keys).

**Comment by xiang90** [comment]
> I am using a VM with 4 cores ( Intel(R) Xeon(R) CPU E5-2690 0 @ 2.90GHz) and 8GB of RAM.
I tried with an SSD and saw the same behavior.

How large is your cluster? Are you running all members on the same machine?

**Comment by nitinmuppalaneni** [comment]
I am running a single instance (no redundancy) for this benchmark.

**Comment by gyuho** [comment]
@nitinmuppalaneni Can you share the etcd server side logs? Or client side errors if any.

I notice you set the timeout 30-second. There should be something wrong in server side if the client doesn't get response in 30-second.

I tried the script below, with the same machine type, and I got no error. What etcd version are you running? I ran your script with Go 1.7.1 and etcd master branch as of today.

```go
package main

import (
	"context"
	"crypto/rand"
	"fmt"
	"io"
	"time"

	"github.com/coreos/etcd/clientv3"
)

/*
nohup $HOME/go/src/github.com/coreos/etcd/bin/etcd --name test-1 --data-dir $HOME/test-1.data \
    --listen-client-urls http://10.240.0.26:2379 --advertise-client-urls http://10.240.0.26:2379 \
    --listen-peer-urls http://10.240.0.26:2380 --initial-advertise-peer-urls http://10.240.0.26:2380 \
    --initial-cluster test-1=http://10.240.0.26:2380 \
    --initial-cluster-token test-token --initial-cluster-state new > $HOME/etcd.log 2>&1 &

*/

var (
	dialTimeout    = 30 * time.Second
	requestTimeout = 30 * time.Second
)

func newKey() string {
	key := make([]byte, 32)
	n, err := io.ReadFull(rand.Reader, key)
	if n != len(key) || err != nil {
		panic(err)
	}
	return fmt.Sprintf("/nitin/%x", key)
}

func main() {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"10.240.0.26:2379"},
		DialTimeout: dialTimeout,
	})
	if err != nil {
		panic(err)
	}
	defer cli.Close()

	for i := 0; i < 1000000; i++ {
		if i%1000 == 0 {
			fmt.Println("Stressing", i)
		}

		ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
		_, err = cli.Put(ctx, newKey(), "0")
		cancel()
		if err != nil {
			panic(err)
		}
	}

	fmt.Println("DONE!")
}
```

Thanks.

**Comment by nitinmuppalaneni** [comment]
Sorry Gyu-Ho Lee for the late response. I was using etcd v3.0.10 and v3 client. I will try your script and report back. Thank you putting etcd in open source and so diligently supporting it.

**Comment by gyuho** [comment]
@nitinmuppalaneni Please let us know if you still have issues. From our stress and benchmark tests, we don't see this behavior.
