### ISSUE TITLE
Allow setting log level of other packages.

### ISSUE THREAD

**Issue by kevincox** [coreos/etcd#6538]
Currently the only control the user has over logging is [via the --log-package-levels flag](https://github.com/coreos/etcd/blob/9e9bbb829ef25181e5178138af6349f7971cba59/etcdmain/etcd.go#L381-L395) which can only set the log levels of the `github.com/coreos/etcd` and the `--debug` flag which can enable debug logs globally. However it is currently impossible to set the log level of other packages like `github.com/coreos/etcd/pkg`. This means that there is some noise which can't be turned off (even to warn!)

It would be nice if there was a way to specify the log level of other packages, ideally per-package but at least globally.

**Comment by gyuho** [comment]
We have tens of packages in etcd. What specific package do you need to configure?

**Comment by kevincox** [comment]
For my case it's github.com/coreos/etcd/pkg fileutil but a more general solution would be nice for others.

**Comment by gyuho** [comment]
Oh now I understand what you are suggesting. Currently we are setting either `capnslog.SetGlobalLogLevel(capnslog.INFO)` or `capnslog.SetGlobalLogLevel(capnslog.WARN)`.

Do you mean adding an option to set this global log level?
Maybe we can add a flag with `--global-log-level`?

**Comment by kevincox** [comment]
Yeah, that would be good. Although it would still be nice to have a way to control per-package log levels more control over the global log level would be very helpful.

**Comment by gyuho** [comment]
@heyitsanthony @xiang90 What do you think? This would be simple flag to add.

**Comment by xiang90** [comment]
@kevincox

I do not understand this issue. I think we already have a flag for that:

```
--log-package-levels ''
		specify a particular log level for each etcd package (eg: 'etcdmain=CRITICAL,etcdserver=DEBUG').
```

**Comment by gyuho** [comment]
@xiang90 You are right. I think it's already possible. https://github.com/coreos/pkg/blob/master/capnslog/logmap.go#L173-L190

**Comment by kevincox** [comment]
@xiang90 No, that flag only changes the log levels of packages inside a repo. It can't change the level of different repos.

**Comment by xiang90** [comment]
@kevincox Only pkg in etcd use this logging infra. You cannot change logging outside etcd repo anyway.

**Comment by kevincox** [comment]
`github.com/coreos/etcd/pkg` uses this infrastructure but according to the logger config is in a different repo. I would like to turn its logs off. This would literally be a one line source code patch. Please look at the code and you will see that this is not possible at the moment.

**Comment by xiang90** [comment]
@kevincox No. According to the logging config, they are in the same repo `etcd` but different pkgs. If it does not work, there is a bug. You can submit patch to fix it.

**Comment by kevincox** [comment]
Seeing that I issue I assume you understand what I mean now. Thanks for listening 😄
