### ISSUE TITLE
advertise-client-urls question

### ISSUE THREAD

**Issue by Lokicity** [coreos/etcd#6539]
Hi
I am running etcd on a docker container and currently it works. However, I dont think I understand the 
--advertise-client-urls=http://localhost:2379,http://localhost:4001 

Why does the node need to advertise its client? My understanding is that the client refers to whoever will query or post information to etcd. Your client can be anyone. Why are we setting this to localhost:2379?

**Comment by heyitsanthony** [comment]
@Lokicity that's the interface the etcd server uses to listen for client requests. For example if you run etcd on a server with IP's 1.2.3.4 and 4.5.6.7 but only want to serve client requests through 1.2.3.4:2379, you'd pass `--advertise-client-urls=http://1.2.3.4:2379` to etcd.

**Comment by Lokicity** [comment]
I thought thats what the --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001  options are for.
Here, I am setting 0.0.0.0 meaning all IPs the host has accepting incoming client calls. 

What is the difference of listen-client-urls and advertise-client-urls then? Thanks

**Comment by heyitsanthony** [comment]
Suppose etcd is listening on 127.0.0.1 and a public IP 1.2.3.4. If it advertises 127.0.0.1 and 1.2.3.4 then clients that synchronize their endpoints with the cluster will try to connect to the cluster through 127.0.0.1 in addition to 1.2.3.4.
