### ISSUE TITLE
scripts/genproto.sh fails on clean checkout

### ISSUE THREAD

**Issue by bdarnell** [coreos/etcd#6552]
I need to regenerate protobufs (as a part of my work on #6522), but `scripts/genproto.sh` is failing for me. Here's the output on a clean checkout: 

```
bdarnell@gceworker171:~$ mkdir etcd-gopath
bdarnell@gceworker171:~$ export GOPATH=$PWD/etcd-gopath
bdarnell@gceworker171:~$ go get -d github.com/coreos/etcd
bdarnell@gceworker171:~$ cd $GOPATH/src/github.com/coreos/etcd
bdarnell@gceworker171:~/etcd-gopath/src/github.com/coreos/etcd$ ./build
bdarnell@gceworker171:~/etcd-gopath/src/github.com/coreos/etcd$ scripts/genproto.shpackage github.com/gogo/protobuf/proto: directory "/home/bdarnell/etcd-gopath/src/github.com/coreos/etcd/gopath/src/github.com/gogo/protobuf/proto" is not using a known version control system
package github.com/gogo/protobuf/protoc-gen-gogo: /home/bdarnell/etcd-gopath/src/github.com/coreos/etcd/gopath/src/github.com/gogo/protobuf exists but /home/bdarnell/etcd-gopath/src/github.com/coreos/etcd/gopath/src/github.com/gogo/protobuf/.git does not - stale checkout?
package github.com/gogo/protobuf/gogoproto: cannot find package "github.com/gogo/protobuf/gogoproto" in any of:
	/home/bdarnell/go/src/github.com/gogo/protobuf/gogoproto (from $GOROOT)
	/home/bdarnell/etcd-gopath/src/github.com/coreos/etcd/gopath/src/github.com/gogo/protobuf/gogoproto (from $GOPATH)
bdarnell@gceworker171:~/etcd-gopath/src/github.com/coreos/etcd$ 
```

It looks like the `vendor` directory only has a partial copy of `gogo/protobuf`. I tried to fix this by editing `glide.yaml` and running `scripts/updatedep.sh`, but that just made more of a mess (glide wanted to delete a bunch of stuff), so I'm asking for help instead of digging further.

**Comment by xiang90** [comment]
@gyuho Can you take a look?

**Comment by gyuho** [comment]
@bdarnell Could you try again without `./build` command?

`./build` command would emit a bunch of dependencies in `gopath` directory in etcd repo.

Or running `rm -rf gopath/ && ./scripts/genproto.sh` should work.

**Comment by bdarnell** [comment]
That works, but it's weird that your different build scripts don't play nicely with each other. Do you just not use `./build` or `./test`, or do you delete `gopath` and redownload everything when you need to regenerate protos?

The genproto script is now succeeding, but it's not producing output that matches what was there before (the encoded FileDescriptorProto blob has changed, and there are minor formatting differences in the generated files). I must be picking up the wrong version of something, but I'm not sure what exactly.

**Comment by heyitsanthony** [comment]
Seconding that this is a total hassle. I always have to flail around some when I need this to work.
