### ISSUE TITLE
namespacing proxy

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6577]
If multiple applications wish to use etcd, they currently must prefix their data (e.g., "app1/...", "app2/"...) to avoid interfering with each others' data. This is not ideal since it puts a burden on the application to be prefix-aware.

A namespacing proxy exposes only a prefix of the etcd keyspace. With namespacing, applications can be pointed at a namespaced etcd instance for its prefix instead of having to worry about prefixing in the application logic. Likewise, it should help make implementing RPC services on top of etcd (e.g., #6285) somewhat tractable; user and service data would be separately namespaced to avoid key collision / namespace pollution but would still be served on the same base etcd instance.

**Comment by vimalk78** [comment]
if no one is working on this, may i take this up.

**Comment by dennwc** [comment]
It would be great to have a prefix as an optional parameter for Client as well. Currently most of our code uses wrapper with this functionality.

If it makes sense, I can file a PR for this part.

**Comment by heyitsanthony** [comment]
@dennwc the namespacing proxy code will be reusable enough to interact cleanly for the client-side case. It'll be ready in a few days.
