### ISSUE TITLE
client versioning

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6579]
If a new client is used with an old cluster, it may try to use options or flags the old server does not understand. Instead, there could be a `Config` option (or make it mandatory) to compare the client version against the cluster version; if the cluster is behind the client, the client will refuse to start.

Related: #6422

**Comment by heyitsanthony** [comment]
Really the server should reject unknown fields exactly for this reason (instead of having to roll out own crummy versioning system), but it seems that feature was removed from proto3 because [Google Knows Best](https://github.com/google/protobuf/issues/272).

**Comment by sinsharat** [comment]
@heyitsanthony @xiang90 if you give an insight on how exactly you want it to be implemented, then will start with it.
