### ISSUE TITLE
add watcher runner into etcd-runner

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#6584]
We hava an etcd runner tool: https://github.com/coreos/etcd/tree/master/tools/functional-tester/etcd-runner.

It is used to test etcd e2e functionality under high load (optionally with server side failure when running against a failure injecting cluster).

We want to add a new command into etcd running: watcher runner.

The goal of watcher runner is to ensure the watch functionality work correctly.

Here is the simple test I propose. We can extend it later on.

- Create m*n watchers watching on n prefixes. So for each prefixes we have m watchers.

loop 

- Set up n goroutines to put keys into m ranges in sequence with a fixed rate (x req / second).

- Cancel the put routines after X seconds. Check that the watchers receive the expected events. (probably we can have a map recording what has been put into each prefixes during the last cycle)

@sinsharat Do you want to help on this one?

**Comment by sinsharat** [comment]
@xiang90 I am more than happy to help on anything to improve out product :-) sure will look into it.

**Comment by sinsharat** [comment]
@xiang90 From what i understand we will need to create watchers on prefixes first, so that when keys are put, we can be definitive on how many updates were done for the prefixes and how many updates did the watches get. right? Also since i am generating the keys randomly which can have keys starting with any of [a-z][0-9] i was thinking of having 36 watches one for each prefix.
Then count the no of keys put in for a prefix in a map and then use it to check the output result from watchers. Is it fine?

**Comment by xiang90** [comment]
Right. This is fine.

**Comment by sinsharat** [comment]
@xiang90 ok. Will work on this one and raise a PR for this.
Thank you!

**Comment by xiang90** [comment]
@sinsharat 

Thanks for getting #6635 done!

Now we should try to run the runner against a fault injecting cluster.

- start a cluster with the instruction here: https://github.com/coreos/etcd/tree/master/tools/functional-tester#with-goreman

- run the runner against this cluster (modify the endpoints to point to the cluster just created)

We can start with making sure the tests can pass for 60 seconds duration. Eventually we need to make it a long running test that will never end.

**Comment by sinsharat** [comment]
@xiang90 sure will start working on it right away.

**Comment by sinsharat** [comment]
@xiang90 I tried running the watcher in the cluster created using goreman, and running the etcd runner with arguments:
./etcd-runner --endpoints="localhost:19027,localhost:29027,localhost:39027"

It starts executing and hangs at get request for getting revision and stays there forever.
Ideally the get request should have timed out no? if it didn't get response withing the stipulated timeout period?

**Comment by sinsharat** [comment]
@xiang90 it was my mistake i had mentioned wrong endpoints, but still expected timeout to happen for get request.

**Comment by sinsharat** [comment]
@xiang90 There are 4 ways in which we can ensure, the test case new fails. They are as follows:
1. Keep retrying for all the get and put requests until it passes.
2. Remove any put request failed from watcher verification
3. If the watcher doesn't match with expected value keep increment the expected value until it matches with the received value. 
4. Put only the values in the map which pass the put request and keep matching it with watchers. - This one i prefer since we can extend it to watch on multiple prefixes of variable lengths and also support watching on similar prefixes like abc and abcd.

Or is there any other way you want it to be handled?

Thanks!

**Comment by xiang90** [comment]
> 1. Keep retrying for all the get and put requests until it passes.

this seems to be the simplest one. and it achieve what we want. but please note that retry normal put request can cause side effect. you need to create a txn, and only do put if the key does not exist before. for get it does not matter, retry as you want.

**Comment by sinsharat** [comment]
sure will do the way you suggested.

**Comment by sinsharat** [comment]
@xiang90 if we use transaction and prevent any update on a key, it will cause issues, since we are directly comparing at watcher level and ignoring a key for transaction will cause a mismatch.

**Comment by xiang90** [comment]
@sinsharat I do not quite understand what you mean. Can you elaborate?

**Comment by xiang90** [comment]
what i want is

```
txn {
    if key exist {
          do thing
    } else {
        create key
    }
}
```

**Comment by sinsharat** [comment]
yes i am doing the same thing. The following is the issue:
In the last commit we did, we are not maintaining track of keys being put. We were putting a loop of keys and prefixes, and performing put operation.
It would have passed earlier since, for a watch on a prefix, these keys will come in sequence. But the keys can have duplicate values since they are being randomly generated.
For example:
1. we have prefix a, b, and c.
2. The pre-generated keys came as xxx, yyy, zzz, xxx, aaa.
3. So the final keys will be a-xxx, a-yyy, a-zzz, a-xxx and a-aaa for watcher a. 
4. In the existing case which we had committed, it would work, since the watcher will also recieve keys in the same sequence as a-xxx, a-yyy, a-zzz, a-xxx, a-aaa.
4. But once we put this transaction condition, the keys put and watcher will recieve as  a-xxx, a-yyy, a-zzz, a-aaa instead of a-xxx, a-yyy, a-zzz, a-xxx, a-aaa. This will cause mismatch.

**Comment by xiang90** [comment]
@sinsharat 

i do not understand why you want to put multiple keys into one transaction. in the transaction, you just should do exactly this

```
txn {
    if key exist {
          do thing
    } else {
        create key
    }
}
```

so there is one key in each transaction. the only difference is that you check the existence of key to not cause any side effect for retry.

**Comment by sinsharat** [comment]
@xiang90 i am putting only one key in a transaction. I will put the code to make it clear:

`func runWatcher(eps []string) {
	runningTime := 300000 * time.Second // time for which operation should be performed
	noOfPrefixes := 36                  // total number of prefixes which will be watched upon
	watchPerPrefix := 10                // number of watchers per prefix
	reqRate := 30                       // put request per second
	keyPrePrefix := 1000                // max number of keyPrePrefixs for put operation

	prefixes := generateUniqueKeys(5, noOfPrefixes)
	keys := generateRandomKeys(10, keyPrePrefix)

	var (
		revision int64
		wg       sync.WaitGroup
		gr       *clientv3.GetResponse
		txnr     *clientv3.TxnResponse
		err      error
	)

	ctx := context.Background()
	// create client for performing get and put operations
	client := randClient(eps)
	defer client.Close()

	// get revision using get request
	for {
		gr, err = client.Get(ctx, "non-existant")
		if err != nil {
			log.Println("Error occured while trying to get the revision.")
			continue
		}
		revision = gr.Header.Revision
		break
	}

	ctxt, cancel := context.WithDeadline(ctx, time.Now().Add(runningTime))
	defer cancel()

	// generate and put keys in cluster
	limiter := rate.NewLimiter(rate.Limit(reqRate), reqRate)

	go func() {
	Loop:
		for i := 0; i < len(keys); i++ {
			for j := 0; j < len(prefixes); j++ {
				key := prefixes[j] + "-" + keys[i]
				// limit key put as per reqRate
				if err = limiter.Wait(ctxt); err != nil {
					break
				}

				for {
					txn := client.Txn(ctxt)
					txn.If(clientv3.Compare(clientv3.ModRevision(key), ">", 0))
					txn.Then()
					txn.Else(clientv3.OpPut(key, key))
					txnr, err = txn.Commit()

					if err == context.DeadlineExceeded {
						fmt.Println("Context deadline exceeded")
						break Loop
					}

					if err != nil {
						log.Printf("Error: %v occured while trying perform put transaction for key: %v, value : %v.\n", err, key, key)
						continue
					}
					break
				}
			}
		}
	}()

	wg.Add(noOfPrefixes * watchPerPrefix)
	for i := 0; i < noOfPrefixes; i++ {
		for j := 0; j < watchPerPrefix; j++ {
			go func(prefix string) {
				defer wg.Done()

				rc := randClient(eps)
				defer rc.Close()

				wc := rc.Watch(ctx, prefix, clientv3.WithPrefix(), clientv3.WithRev(revision))
				for n := 0; n < len(keys); {
					select {
					case watchChan := <-wc:
						for _, event := range watchChan.Events {
							expectedKey := prefix + "-" + keys[n]
							recievedKey := string(event.Kv.Key)
							fmt.Println("Expected key : %q, got key : %q, for prefix : %q\n", expectedKey, recievedKey, prefix)
							if expectedKey != recievedKey {
								log.Fatalf("expected key %q, got %q for prefix : %q\n", expectedKey, recievedKey, prefix)
							}
							n++
						}
					case <-ctxt.Done():
						return
					}
				}
			}(prefixes[i])
		}
	}
	wg.Wait()
}`

**Comment by xiang90** [comment]
@sinsharat 

Why do you retry the entire loop? shouldnt you only retry the failed put?!

**Comment by sinsharat** [comment]
That can be changed. That's not a problem.
In the above code the issue is not with transaction, but the blind comparison we are doing at the watcher level, where we are blindly comparing with prefix+"-"+keys[n]. This issue is since keys[n] are pre-generated it may have duplicate values, hence during comparison if we don't put these duplicate values, the comparison will fail.

**Comment by xiang90** [comment]
@sinsharat I still do not really understand why you expect to see a-xxx twice. If you do txn correctly, we should never modify the same key TWICE.

**Comment by sinsharat** [comment]
@xiang90 watcher will not see it twice. but the comparison its being done with, i.e. prefix+keys[n] will have it twice.

**Comment by sinsharat** [comment]
transaction is only ensuring that keys are not put twice, hence the watcher will never receive the key twice. But we are comparing it with prefix+keys[n] which can have the value twice, and in that case the comparison will fail.

**Comment by xiang90** [comment]
@sinsharat OK. So can you simply remove duplicate keys?

**Comment by xiang90** [comment]
Or you can remember the previous revision of the key and compare against that instead of comparing against existence.

**Comment by sinsharat** [comment]
but how will comparing against previous revision help, since even if prev revision key was present, which is older than the revision we got in the first step, still there can be possibility of two keys having same prePrefixKey. So in that case as well we will need to remove the duplicate keys.
@xiang90 just wanted a clarity on why putting the same key multiple times can be a problem?

**Comment by xiang90** [comment]
Before you do the put, you remember its previous rev. then you do a put against it. if put succeeds but times out on the client side, the next retry will not write the key again since the rev is increased. if you do not protect it, retry will make you write the key twice which is unwanted.

> @xiang90 just wanted a clarity on why putting the same key multiple times can be a problem?

if you put it multiple times, watcher will see it multiple times. we do not want retry to have any side effect. if we want to do it exact once, it should be done exact once i guess.

**Comment by sinsharat** [comment]
@xiang90 so what i understand is, we will need to check revision for get, and also ensure no duplicate keys are there in keys slice. right?

**Comment by sinsharat** [comment]
Also from your inputs what i understand is we need if check rather than using transactions for the above operation.

**Comment by xiang90** [comment]
@sinsharat A simple solution is to

1.  ensure there is no dup key to put.
2. retry on put and make put a txn to check existence

A more complicated solution is to

1. retry on put and make put a txn that never overwrites the put before the retry if it actually succeeds. 

I am fine with both solution.

**Comment by xiang90** [comment]
@sinsharat The root problem here is:

if a put returns error (network issue or timeout) to client, it does not really mean the put failed. it might succeed, it might fail. we just do not know. so we cannot blindly retry.

we only know the status of put for sure if it succeeds.

**Comment by sinsharat** [comment]
@xiang90 i got your point. If you see in the above transaction we have used, the entire transaction was put in a for loop for the same reason, so that if in the first retry if it succeeds but we get error then in the next retry, again being a transaction, will get mod revision > 0 and hence will not perform the put operation and come out without any error.

**Comment by xiang90** [comment]
Can we retry on single put? the retry on the entire loop looks crazy actually. the first N requests will fail for sure.

**Comment by sinsharat** [comment]
what you mean is have a direct put operation and if it fails then have this transaction with check?

**Comment by xiang90** [comment]
I misread your code. I thought you were retrying on the LOOP tag.

So we need to change the code to

```go
go func() {
    for i := 0; i < len(keys); i++ {
        for j := 0; j < len(prefixes); j++ {
            key := prefixes[j] + "-" + keys[i]
            // limit key put as per reqRate
            if err = limiter.Wait(ctxt); err != nil {
                break
            }

            for {
                txn := client.Txn(ctxt)
                _, err = txn.If(clientv3.Compare(clientv3.ModRevision(key), ">", 0))
                     .Then()
                     .Else(clientv3.OpPut(key, key))
                     .Commit()

                if err == context.DeadlineExceeded {
                    return
                }

                if err != nil {
                    log.Printf("Error: %v occured while trying perform put transaction for key: %v, value : %v.\n", err, key, key)
                    continue
                }
                break
            }
        }
    }
}()
```

also we do not generate duplicate keys.

Or we need to change the code to 


```go
go func() {
    for i := 0; i < len(keys); i++ {
        for j := 0; j < len(prefixes); j++ {
            key := prefixes[j] + "-" + keys[i]
            // limit key put as per reqRate
            if err = limiter.Wait(ctxt); err != nil {
                break
            }

           modrev := getModRevForKey(key)

            for {
                txn := client.Txn(ctxt)
                _, err = txn.If(clientv3.Compare(clientv3.ModRevision(key), "==", modrev))
                     .Then(clientv3.OpPut(key, key))
                     .Commit()

                if err == context.DeadlineExceeded {
                    return
                }

                if err != nil {
                    log.Printf("Error: %v occured while trying perform put transaction for key: %v, value : %v.\n", err, key, key)
                    continue
                }
                break
            }
        }
    }
}()
```

**Comment by sinsharat** [comment]
@xiang90 ok. What do you suggest for removing duplicate tag, shall we call the unqiue generator which we are calling for the unique prefixes?

**Comment by xiang90** [comment]
@sinsharat Fine with me. We can always add the duplication stuff back when the whole thing works under failure cases.

**Comment by sinsharat** [comment]
ok sure will then do these changes, test it and will raise a PR for this.

**Comment by sinsharat** [comment]
@xiang90 what needs to be done next?

**Comment by xiang90** [comment]
@sinsharat If you take a look at other runners, they accept a round parameter. So they can run multiple rounds of tests. This is important for us since we basically want to run it forever. Can you make the watcher runner to respect rounds? After each round of test, we also need to clean up all the keys we created for the last round to make the key space clean. Also we might want a round prefix for the keys to put/watch in the round. A string integer would be good enough. For example for round 1, we put /watcher-runner/1/abc-xxx. for round2, we put /watcher-runner/2/abc-xxx

**Comment by sinsharat** [comment]
@xiang90 Sure will start analyzing and implementing it right away in the morning.
Thank you!

**Comment by sinsharat** [comment]
@xiang90 From what i understand is you expect the following:
**acquire method :** 
1. One watcher per round 
2. keys will be put for that watcher in a go-routine. (Note: keys will be generated before hand as well as prefix for watchers)

**validate method:**
1. received value will be validated against the expected value.

**release method**
1. The keys which were put needs to be removed.

Closing of watcher clients will be taken care by roundclient itself since it closes all clients by default.

Let me know if i have mis-understood anything. Will take care of that.
Thanks!

**Comment by sinsharat** [comment]
@xiang90 : Please find below the initial design i have thought of. I would have like to create watcher in the acquire method, but the problem is we will need the instance of each watcher response.
Alternatively if we want to achieve that may be we will need to use slice of watcher response to store all watchers and then in validate method range over the slice and validate them.

```
func runWatcher(eps []string, watchPerPrefix int) {
	rcs := make([]roundClient, 15)
	ctx := context.Background()
	runningTime := 30 * time.Second
	reqRate := 30
	keyPrePrefix := 30
	noOfPrefixes := 36

	for i := range rcs {

		var (
			revision int64
			wg       sync.WaitGroup
			gr       *clientv3.GetResponse
			err      error
		)

		prefixes := generateUniqueKeys(5, noOfPrefixes)
		keys := generateRandomKeys(10, keyPrePrefix)

		// create client for performing get and put operations
		rcs[i].c = randClient(eps)

		// get revision using get request
		gr = getWithRetry(rcs[i].c, ctx, "non-existant")
		revision = gr.Header.Revision

		ctxt, cancel := context.WithDeadline(ctx, time.Now().Add(runningTime))
		defer cancel()

		// generate and put keys in cluster
		limiter := rate.NewLimiter(rate.Limit(reqRate), reqRate)

		go func() {
			var modrevision int64
			for i := 0; i < len(keys); i++ {
				for j := 0; j < len(prefixes); j++ {
					key := prefixes[j] + "-" + keys[i]

					// limit key put as per reqRate
					if err = limiter.Wait(ctxt); err != nil {
						break
					}

					modrevision = 0
					gr = getWithRetry(rcs[i].c, ctxt, key)
					kvs := gr.Kvs
					if len(kvs) > 0 {
						modrevision = gr.Kvs[0].ModRevision
					}

					for {
						txn := rcs[i].c.Txn(ctxt)
						_, err = txn.If(clientv3.Compare(clientv3.ModRevision(key), "=", modrevision)).Then(clientv3.OpPut(key, key)).Commit()

						if err == nil {
							break
						}

						if err == context.DeadlineExceeded {
							return
						}
					}
				}
			}
		}()

		rcs[i].acquire = func() error {
			return nil
		}

		rcs[i].validate = func() error {
			wg.Add(noOfPrefixes)
			for i := 0; i < noOfPrefixes; i++ {
				go func(prefix string) {
					defer wg.Done()

					rc := randClient(eps)
					defer rc.Close()

					wc := rc.Watch(ctx, prefix, clientv3.WithPrefix(), clientv3.WithRev(revision))
					for n := 0; n < len(keys); {
						select {
						case watchChan := <-wc:
							for _, event := range watchChan.Events {
								expectedKey := prefix + "-" + keys[n]
								receivedKey := string(event.Kv.Key)
								if expectedKey != receivedKey {
									log.Fatalf("expected key %q, got %q for prefix : %q\n", expectedKey, receivedKey, prefix)
								}
								n++
							}
						case <-ctxt.Done():
							return
						}
					}
				}(prefixes[i])
			}
			wg.Wait()
			return nil
		}

		rcs[i].release = func() error {
			for i := 0; i < len(keys); i++ {
				for j := 0; j < len(prefixes); j++ {
					key := prefixes[j] + "-" + keys[i]

					for {
						txn := rcs[i].c.Txn(ctx)
						_, err = txn.If(clientv3.Compare(clientv3.ModRevision(key), ">", 0)).Then(clientv3.OpDelete(key)).Commit()

						if err == nil {
							break
						}
					}
				}
			}
			return nil
		}
	}
	doRounds(rcs, watchPerPrefix)
}
```
Request you to PTAL and provide your opinion.
Thank you!

**Comment by sinsharat** [comment]
Alternate way as i had mentioned earlier can be the below code:
```
func runWatcher(eps []string, watchPerPrefix int) {
	rcs := make([]roundClient, 15)
	ctx := context.Background()
	runningTime := 30 * time.Second
	reqRate := 30 // put request per second
	keyPrePrefix := 30
	noOfPrefixes := 36

	for i := range rcs {

		var (
			revision int64
			wg       sync.WaitGroup
			gr       *clientv3.GetResponse
			err      error
		)

		prefixes := generateUniqueKeys(5, noOfPrefixes)
		keys := generateRandomKeys(10, keyPrePrefix)

		// create client for performing get and put operations
		rcs[i].c = randClient(eps)

		// get revision using get request
		gr = getWithRetry(rcs[i].c, ctx, "non-existant")
		revision = gr.Header.Revision

		ctxt, cancel := context.WithDeadline(ctx, time.Now().Add(runningTime))
		defer cancel()

		// generate and put keys in cluster
		limiter := rate.NewLimiter(rate.Limit(reqRate), reqRate)

		go func() {
			var modrevision int64
			for i := 0; i < len(keys); i++ {
				for j := 0; j < len(prefixes); j++ {
					key := prefixes[j] + "-" + keys[i]

					// limit key put as per reqRate
					if err = limiter.Wait(ctxt); err != nil {
						break
					}

					modrevision = 0
					gr = getWithRetry(rcs[i].c, ctxt, key)
					kvs := gr.Kvs
					if len(kvs) > 0 {
						modrevision = gr.Kvs[0].ModRevision
					}

					for {
						txn := rcs[i].c.Txn(ctxt)
						_, err = txn.If(clientv3.Compare(clientv3.ModRevision(key), "=", modrevision)).Then(clientv3.OpPut(key, key)).Commit()

						if err == nil {
							break
						}

						if err == context.DeadlineExceeded {
							return
						}
					}
				}
			}
		}()

		randClients := make([]*clientv3.Client, 0)
		watchChans := make([]clientv3.WatchChan, 0)

		rcs[i].acquire = func() error {
			for j := 0; j < noOfPrefixes; j++ {
				rc := randClient(eps)
				randClients = append(randClients, rc)
				wc := rc.Watch(ctx, prefixes[j], clientv3.WithPrefix(), clientv3.WithRev(revision))
				watchChans = append(watchChans, wc)
			}
			return nil
		}

		rcs[i].validate = func() error {
			wg.Add(noOfPrefixes)
			for j := 0; j < noOfPrefixes; j++ {
				go func(prefix string, wc clientv3.WatchChan) {
					defer wg.Done()
					for n := 0; n < len(keys); {
						select {
						case watchChan := <-wc:
							for _, event := range watchChan.Events {
								expectedKey := prefix + "-" + keys[n]
								receivedKey := string(event.Kv.Key)
								if expectedKey != receivedKey {
									log.Fatalf("expected key %q, got %q for prefix : %q\n", expectedKey, receivedKey, prefix)
								}
								n++
							}
						case <-ctxt.Done():
							return
						}
					}
				}(prefixes[j], watchChans[j+rcs[i].progress])
			}
			wg.Wait()
			return nil
		}

		rcs[i].release = func() error {
			for i := 0; i < len(keys); i++ {
				for j := 0; j < len(prefixes); j++ {
					key := prefixes[j] + "-" + keys[i]

					for {
						txn := rcs[i].c.Txn(ctx)
						_, err = txn.If(clientv3.Compare(clientv3.ModRevision(key), ">", 0)).Then(clientv3.OpDelete(key)).Commit()

						if err == nil {
							break
						}
					}
				}
			}

			for _, c := range randClients {
				c.Close()
			}

			return nil
		}
	}
	doRounds(rcs, watchPerPrefix)
}
```

**Comment by sinsharat** [comment]
@xiang90 There seems to be some issue with watchers. when i run the round client for first round everything passes. But when the second round starts the watches receive the first event for each prefix correctly and then they start returning watchers with empty events.

**Comment by sinsharat** [comment]
@xiang90 can we close this issue or is there anything else which needs to be for this. If this is complete, is there anything else which i can look into?
Thanks!

**Comment by xiang90** [comment]
I think we can close this now. the next step is to run this test against failure injecting cluster 24 * 7. we will figure out how later.
