### ISSUE TITLE
Query: how to enable grpc logs while running etcd

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#6585]
hi, for hacking one issue, i have added some `fmt.Printf` statements in grpc.
how do see those prints when i run etcd
i have tried running etcd with `goreman start` and also `./etcd --debug==true`

but i am not able to see the printf,

can someone pls help

**Comment by gyuho** [comment]
`--debug=true`, not `==`?

Did you put in grpc vendor or the grpc in your GOPATH? It needs to be in grpc in our vendor directory.

**Comment by vimalk78** [comment]
yes, i used `--debug=true`

this is how my $GOPATH looks like
```
vimal vimal $ echo $GOPATH 
/home/vimal//gowork
vimal vimal $ cd $GOPATH
vimal gowork $ ls -a src/google.golang.org/
.  ..  grpc
vimal gowork $ 
```

do i need to add `grpc` folder also in `GOPATH` ?

thanks!!

**Comment by gyuho** [comment]
@vimalk78  If you run compiled etcd, change the grpc code in `/cmd/vendor/google.golang.org/grpc`.

It should work. Please let me know if you have more questions.

Thanks.

**Comment by vimalk78** [comment]
hi @gyuho 
yes i figured that out. thanks!!
