### ISSUE TITLE
etcdctl snapshot via load balanced url causes rpc error

### ISSUE THREAD

**Issue by chriscartlidge** [coreos/etcd#6597]
Cluster Version: v3.10
OS: Ubuntu 14-4

We have a 3 node cluster which is behind a load balanced URL. When we try to run the following command using the load balanced URL:

```
ETCDCTL_API=3 ./etcdctl --endpoints etcd-load-balanced.com:4001 snapshot save backup.db
```
 We get the following error returned:

````
Error:  rpc error: code = 13 desc = transport is closing
````

When running the same `etcdctl` command directly against a nodes URL everything works fine.

**Comment by xiang90** [comment]
If this works without lb, probably there is an issue in your lb. Do you set any timeout in the lb?

**Comment by chriscartlidge** [comment]
@xiang90 Yeah that was my first thought. I just wanted to know if there were any know issues with using a LB.

Our ideal timeouts are set at 60 seconds. Its definitely a strange one!

**Comment by xiang90** [comment]
I am not aware of any.

**Comment by chriscartlidge** [comment]
Cheers for that @xiang90 we'll keep investigating and post the results here. Thanks for your help 👍

**Comment by xiang90** [comment]
@chriscartlidge Do you have any result yet? Anything else we can help?

**Comment by chriscartlidge** [comment]
Hey @xiang90 unfortunately not. I'm planning to investigate this more over the next week fews.

Maybe is best to close this now and re-open once I have results?

**Comment by xiang90** [comment]
@chriscartlidge OK. Feel free to reopen if there is any issue.
