### ISSUE TITLE
clientv3: About the logger API

### ISSUE THREAD

**Issue by chzyer** [coreos/etcd#6603]
Hi, guys, I have some questions about the logger API.

In the function `clientv3.New`, it will set`logger.Set()` every time, which `logger` is a "singleton" variable, that's so weird. And I can't figure out a way that I can allocate a new client without touching `logger` ? Why not just provide a function that can set `logger` directly ?

https://github.com/coreos/etcd/blob/master/clientv3/client.go#L320-L325

And another problem, the code snippet above should moved before it called `client.dial`(L291)[https://github.com/coreos/etcd/blob/master/clientv3/client.go#L291].

Sorry for bothering.

**Comment by xiang90** [comment]
@chzyer You are right. Can you send a pr to fix this?

**Comment by gyuho** [comment]
@chzyer Ping? Maybe remove `Logger` field in `Config` and document how to set up logger?

**Comment by chzyer** [comment]
@gyuho LGTM
