### ISSUE TITLE
endpoint health(etcdctlv3): permission denied

### ISSUE THREAD

**Issue by lonelili** [coreos/etcd#6611]
## Environment
etcd --version
etcd Version: 3.0.6
Git SHA: 9efa00d
Go Version: go1.6.3
Go OS/Arch: linux/amd64

## Backgroud
I want to monitor the health of my production cluster. Then i find the command "endpoint health".

## Question
I'm confused with the endpoint health command.

The phenomenon is that if you enable authentication, you will get an error of "permission denied" when you use “endpoint health”.

eg:
./etcdctl --user user:pwd endpoint health --endpoints=ep1,ep2,ep3
ep1 is unhealthy: failed to commit proposal: etcdserver: permission denied
...

I find the code in etcd/etcdctl/ctlv3/command/ep_command.go line 73
cfg, err := newClientCfg([]string{ep}, dt, sec, nil)
Notice the fourth argument is nil, which means the function does not parse the authCfg.

So... is this a bug? or intentionally designed?

**Comment by xiang90** [comment]
@jy02471192 Seems like a bug. Can you help to fix?

/cc @mitake

**Comment by mitake** [comment]
@jy02471192 thanks for your report. Yes, current auth isn't considering the permission of maintenance services well.

@xiang90 I think letting the client consider the auth related parameter and limiting users who can call the RPCs of maintenance services to ones who have a root role would be the simplest solution. How do you think?

**Comment by xiang90** [comment]
@mitake ep health is actually a very simple command. it only tries to read a key (`health`) from etcd. so the easy fix is just to respect auth setting when creating the ep-health client.

I agree on the maintain service part. yea, probably we should only allow root to access it.

**Comment by mitake** [comment]
@xiang90 I missed the reading a key in health checking. Handling special keys in permission checking seems to be required. But this kind of work is a little bit dangerous. Maybe 

1. treating a case of permission denied as success of health checking
2. require admins to use a user with the root role for health check

would be safer. If we have many keys that need special rules, the mechanism of special keys would be suitable. But creating it just for health seems to be overkill for me.

**Comment by xiang90** [comment]
> But creating it just for health seems to be overkill for me.

Agree. I think we should just doc that ep health needs to access key `health`. or we can make ep heath checking key configurable.

**Comment by mitake** [comment]
@xiang90 ok, I'll enhance the doc later. I'll fix `endpoint health` for the root role first.
