### ISSUE TITLE
etcd cluster is unavailable or misconfigured

### ISSUE THREAD

**Issue by eyediy** [coreos/etcd#6614]
The etcd cluster crashed since i executed a command with etcdctl.
i am trying to get all keys by using:
`etcdctl --endpoints http://ip:port get keys`
the result returned is:
`Error: client: etcd cluster is unavailable or misconfigured`
`error #0: unsupported protocol scheme ""`
can anyone tell me why this command will cause a crash?

**Comment by xiang90** [comment]
@eyediy Do you have any crash log from the server side?

**Comment by eyediy** [comment]
i found it is my fault that it works well when use ip instead of domain.
