### ISSUE TITLE
[Docs] Docker Getting Started Guide breaks (still)

### ISSUE THREAD

**Issue by ElijahCaine** [coreos/etcd#6637]
The [Docker Getting Started Guide][docker-getting-started] breaks when pulling the etcd image at `>=quay.io/coreos/etcd:v3.0.0`. The commands in the tutorial do not break when running the `<=quay.io/coreos/etcd:v2.3.7` image.  The fix is to add a call to `/usr/local/bin/etcd`, but this ultimately breaks backward compatibility which is no bueno.

This (what happened, why it was changed, etc) was previously brought up in #6071 but the doc is still public and people are finding it / getting confused by it.  We need to do one of the following
- Update the doc
- Add a note about the breaking behavior being related to versioning
- Throw the [getting started with docker][docker-getting-started] guide away in favor of one of the alternatives listed in the above issue.

I'm willing to make any changes, just need to know what should be changed and how.

[docker-getting-started]: ../blob/master/Documentation/v2/docker_guide.md

**Comment by xiang90** [comment]
@ElijahCaine If you run etcd3, you should look at v3 doc at https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md, right?

**Comment by ElijahCaine** [comment]
@xiang90 Right!

My bad, I was linking to the GitHub pages, I meant to link to the [pages on coreos.com docs](https://coreos.com/etcd/docs/latest/docker_guide.html).

This is probably be an issue with how the site is built internally for CoreOS, so I'll look into updating that.

**Comment by xiang90** [comment]
@ElijahCaine This is duplication with https://github.com/coreos/etcd/issues/6342. So closing. Let's track there.
