### ISSUE TITLE
A performance test between go 1.7 and go 1.6.2

### ISSUE THREAD

**Issue by HardySimpson** [coreos/etcd#6638]
qps is near but lantency is better

| GO    | QPS     | 95%   | 99%   | slowest latency |
| :---- | :------ | :---- | :---- | :-------------- |
| 1.6.2 | 5955    | 6.4   | 15.5  | 194             |
| 1.6.2 | 6216    | 6.1   | 12.1  | 189             |
| 1.6.2 | 5987    | 6.4   | 13.9  | 122             |
| 1.6.2 | 6028    | 6.2   | 14.3  | 164             |
| 1.6.2 | 5991    | 6.4   | 12.0  | 177             |
| :---  | :------ | :---- | :---- | :-------------- |
| 1.7.0 | 6391    | 6.2   | 9.5   | 109             |
| 1.7.0 | 5912    | 6.6   | 10.4  | 129             |
| 1.7.0 | 6043    | 6.4   | 10.6  | 137             |
| 1.7.0 | 5894    | 6.7   | 11.5  | 112             |
| 1.7.0 | 6092    | 6.4   | 10.4  | 151             |

**Comment by HardySimpson** [comment]
Is go 1.7 affect any other problem? it seems will work well in our k8s performance test

**Comment by xiang90** [comment]
Are these numbers for v2 api or v3? We observed 10-20% improvement when complied against go 1.7 mainly due to go's SSA change. We are not aware other issues.

**Comment by xiang90** [comment]
closing since the question is well answered.
