### ISSUE TITLE
Question about ranges in the v3 API

### ISSUE THREAD

**Issue by kragniz** [coreos/etcd#6641]
Hi all, I've started writing a [python client for the v3 API](https://github.com/kragniz/python-etcd3) and I'm trying to figure out nice abstractions. I've been struggling a little with ranges, in particular the `range_end` field.

It seems there are a few distinct types of range request:

1. get single key - `range_end` is not set
2. get keys with a prefix - `range_end` is equal to `key` with the last byte incremented by 1
3. get keys larger than a given key - `range_end` is equal to `'\0'`
4. get all keys - both `key` and `range_end` are equal to `'\0'`

For these, I plan on making it easier for users and creating a separate function for each, `get(key)`, `get_prefix(key_prefix)`, `get_greater(initial_key)` and `get_all()`

So, some questions:

1. Do all the ranges work in the same way? The [description for DeleteRangeRequest](https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L437-L440) does not mention deleting keys with a prefix, however WatchCreateRequest does.
2. Are those functions a reasonable categorisation of the different types of range requests? Are there any other cases I've missed, or misinterpreted?

Cheers!

**Comment by xiang90** [comment]
> Do all the ranges work in the same way?

yes it should. if not, we should fix. can you help to test it out and maybe fix the doc?

> Are those functions a reasonable categorisation of the different types of range requests? Are there any other cases I've missed, or misinterpreted?

it depends on your client lib. in go client, we use range but we provide range options for prefix, all, etc..

**Comment by kragniz** [comment]
Okay, thanks. There are no other cases I've missed out?

**Comment by xiang90** [comment]
no, i think.

**Comment by kragniz** [comment]
>yes it should. if not, we should fix. can you help to test it out and maybe fix the doc?

I tested, and it works the same for DeleteRequest. I'll update the docs.

**Comment by xiang90** [comment]
great! thanks.
