### ISSUE TITLE
On comparing and swap with an empty previous value

### ISSUE THREAD

**Issue by bohdantrotsenko** [coreos/etcd#6642]
Hi,

I'd like to be able to "exclusively create values". I found --swap-with-value flag which is extremely close to what I want, except that I couldn't provide an empty (or null) value. And then I found [issue 2280](https://github.com/coreos/etcd/issues/2880) (`Can I compare and swap with empty previous value?`), with `etcd doesn't support to compare and swap an empty value` as of May 28, 2015.
I therefore conclude I'm not alone in my wish.

I'd like to ask:
1) Is this functionality left out by design? (maybe, there are some algorithmic issues is doing this)
2) Or maybe, there's simple workaround to akin to "--swap-with-null"?
3) Would you consider accepting a pull request with this functionality? (I'm asking just for a case, e.g., there's no point implementing this)

**Comment by xiang90** [comment]
We are not going to work on more features for v2 API. But, why do you want to compare the empty value? What is the use case? There is no way to work around it?

**Comment by bohdantrotsenko** [comment]
We have a set of servers; some actions have to be completed only once.
The idea is to the already available etcd this way:
Each server runs `etcdctl set /operationXcompletedBy "serverName" --swap-with-null` and performs the operation upon success. This way we'd like to ensure the operation is done only once.

**Comment by xiang90** [comment]
Can you use create in this case? create only succeeds if the key does not exist before.

**Comment by bohdantrotsenko** [comment]
... yes; that sounds like what I want.
I just found that `etcdctl mk /keyName` does what I want.
(I tried to google the solution; tried with 'create' and 'null', but, well, failed.)

Thanks!
