### ISSUE TITLE
No upper limit on discovery

### ISSUE THREAD

**Issue by crawford** [coreos/etcd#6648]
Discovery is failing with the following:

```
discovery: error #0: x509: failed to load system roots and no roots provided
```

This failure is understood and expected. The backoff, however, isn't behaving reasonably:

```
discovery: error #0: x509: failed to load system roots and no roots provided
discovery: cluster status check: error connecting to https://discovery.etcd.io, retrying in 34m8s
discovery: error #0: x509: failed to load system roots and no roots provided
discovery: cluster status check: error connecting to https://discovery.etcd.io, retrying in 1h8m16s
```

There should be a max backoff for any single attempt in addition to a maximum number of attempts before failure.

**Comment by xiang90** [comment]
The backoff is crazy. It should be fixed. /cc @gyuho @fanminshi

**Comment by gyuho** [comment]
```
var (
	// Number of retries discovery will attempt before giving up and erroring out.
	nRetries = uint(math.MaxUint32)
)
```

Do we want to make it configurable or set smaller value?

**Comment by xiang90** [comment]
@crawford I am not sure about the max number of retries... We had one. Users just suggest to make it unlimited... I do not really want to add another flag for it...

**Comment by crawford** [comment]
> I do not really want to add another flag for it...

I don't blame you. Do you have a link to the conversation about the unlimited backoff?

**Comment by xiang90** [comment]
@crawford I can search it. I do not remember where the conversation happened.

**Comment by crawford** [comment]
My gut tells me that unlimited isn't correct, but I haven't thought very much about it. I wanted to read through another's argument.

**Comment by xiang90** [comment]
https://github.com/coreos/etcd/issues/1798

There are other users reported back then. We had some internal discussion and decided just remove the retry timeout. Do you have a suggestion for setting the number of retry? 10? 100? 1000? 10000?

**Comment by fanminshi** [comment]
Will the upper limit waiting time 5min be reasonable?

**Comment by xiang90** [comment]
@fanminshi Yea. I think max limit could be 3 or 5 minutes or a little shorter. @crawford opinions?

**Comment by crawford** [comment]
I think 5 minutes is perfectly reasonable.

**Comment by xiang90** [comment]
@fanminshi Talked with @crawford offline, we still need to keep retry number unlimited for slow provisioning case. We should have a limit for max retry wait.
