### ISSUE TITLE
Go etcd v2 Watcher doesn't spot if cluster ID changes

### ISSUE THREAD

**Issue by fasaxc** [coreos/etcd#6652]
Using the v2 go client library, if you start a watch against etcd and the cluster is swapped (for example due to a backup/restore) then the client continues polling the new etcd cluster with the etcd index from the old cluster.  Since the new etcd cluster doesn't have synchronised etcd indexes, the watcher is polling the wrong index but it doesn't spot that it's out-of-sync.

In python-etcd, we check the cluster ID header on the response and raise an exception if it changes.  That resolves this case, as long as the new cluster has a distinct cluster ID.

**Comment by xiang90** [comment]
We are not actively working on v2 anymore. This would be an enhancement we want to make. I believe we should error out when the cluster ID changes optionally. Users should be able to configure it and recover from cluster ID change. It would be great, if you have time working on it.

**Comment by fasaxc** [comment]
Understood, I might get some time to work on this.

**Comment by fasaxc** [comment]
@xiang90 I had a go at this but it looks like it could be an invasive change to do it fully.  In particular, the check needs to happen after loading the headers from the server but before loading the body (or reading from a watch will block forever).  I've gone for the simple solution of returning the ClusterID so the calling code can check/log it.  That's enough for my use-case, which is just to cover a hopefully very rare edge case.

**Comment by xiang90** [comment]
OK. I am closing this out. We can add the error return part if other people also want it.
