### ISSUE TITLE
functional-tester: fault injection recovery does not ensure etcd is fully running

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd#6654]
I observe that leaseStresser checker encounters `etcdserver: request timed out` when making a linearized RPC call.

leaseStresser checker starts the moment after tester indicates that the fault injection has recovered. However, in some case, the fault injection is not truly recovered after tester prints out `recovered failure` because etcd node takes time restart. During the restarting period, the leaseStresser stresser on a follower node wants a linearized call such as `Range()`. Since the etcd node that's restarting/offline could be the leader, then`etcdserver: request timed out` error occurs for the linearized call. 

The workaround for this issue is to start the leaseStresser checking after hash checking. This works because the hashChecker has a waiting logic resulting etcd server to be in a quiescent state before leaseStresser starts to do its job .  

```go
func (hc *hashChecker) Check() (err error) {
	plog.Printf("%s fetching current revisions...", hc.tt.logPrefix())
	var (
		revs   map[string]int64
		hashes map[string]int64
		ok     bool
	)
	for i := 0; i < 7; i++ {
		time.Sleep(time.Second)

		revs, hashes, err = hc.tt.cluster.getRevisionHash()
		if err != nil {
			plog.Printf("%s #%d failed to get current revisions (%v)", hc.tt.logPrefix(), i, err)
			continue
		}
		if _, ok = getSameValue(revs); ok {
			break
		}

		plog.Printf("%s #%d inconsistent current revisions %+v", hc.tt.logPrefix(), i, revs)
	}
	if !ok || err != nil {
		return fmt.Errorf("checking current revisions failed [err: %v, revisions: %v]", err, revs)
	}
	plog.Printf("%s all members are consistent with current revisions [revisions: %v]", hc.tt.logPrefix(), revs)

	plog.Printf("%s checking current storage hashes...", hc.tt.logPrefix())
	if _, ok = getSameValue(hashes); !ok {
		return fmt.Errorf("inconsistent hashes [%v]", hashes)
	}

	plog.Printf("%s all members are consistent with storage hashes", hc.tt.logPrefix())
	return nil
}
```

We need a better way to ensure etcd server is fully recovered.

**Comment by xiang90** [comment]
@fanminshi Can you get this fixed? Thanks!

**Comment by fanminshi** [comment]
@xiang90 sure, do you want to do it after i merge the https://github.com/coreos/etcd/pull/6588 or before?
