### ISSUE TITLE
Does follower need to keep lease when leader starts a new election?

### ISSUE THREAD

**Issue by BusyJay** [coreos/etcd#6658]
Hi, in [this check](https://github.com/coreos/etcd/blob/master/raft/raft.go#L650), follower will ignore vote when it's still in lease. But what if the election is started by its leader? This can happen if follower is slow due to some reason (like accidentally attached by gdb or IO is busy sometime).

/cc @siddontang

**Comment by xiang90** [comment]
leader will never start election. it needs to step down, becomes follower, times out again. or can you write a simple test to show there is a problem?

**Comment by xiang90** [comment]
Closing. let us know if you have other related questions.
