### ISSUE TITLE
Stripped binaries in releases

### ISSUE THREAD

**Issue by nekto0n** [coreos/etcd#6664]
Currently, binaries built with `./build` and official releases are built stripped (`-s` flag), thus tool like `perf top` don't work if built with go1.7 and frame pointers enabled.
Could we add an option to build and distribute unstripped binaries alongside?

**Comment by gyuho** [comment]
You can build with `GO_LDFLAGS="" ./build` https://github.com/coreos/etcd/blob/master/build#L14?

**Comment by nekto0n** [comment]
Yes, that helps. I wonder if this should be used by default when releases are built with go1.7+.

**Comment by xiang90** [comment]
@nekto0n Can send a pr to add that option? I also feel we should probably enable it by default.

**Comment by nekto0n** [comment]
Sure, will do
