### ISSUE TITLE
Cannot create a new user within just one command input

### ISSUE THREAD

**Issue by johnbazan** [coreos/etcd#6668]
Currently, the etcdctl that are using the ctlv2, at least, are not allowing you to create a user specifying the password within the same command line.

Doing etcdtcl user add root:toor

Will result in etcdctl waiting for you to ingress a new password in a new prompt line.

root@jbazan-virtual-machine:/workspace# etcdctl user add root:toor
New password:

This makes a little bit more difficult automating infrastructure creation, like cloud config scripts, or cloudformation, etc...

I have a branch that makes this functional for ctlv2-based ctl (the one that I'm using).
If you think this is a valid issue, I'll go right away and create the pull request.

Cheers,
Jonathan

**Comment by heyitsanthony** [comment]
Huh?

```sh
$ ./bin/etcdctl user add root:toor
User root created
```

It's baked into the end-to-end tests too: 
```go
func etcdctlUserAdd(clus *etcdProcessCluster, user, pass string) error {
	cmdArgs := append(etcdctlPrefixArgs(clus), "user", "add", user+":"+pass)
	return spawnWithExpect(cmdArgs, "User "+user+" created")
}
```
(https://github.com/coreos/etcd/blob/master/e2e/ctl_v2_test.go#L399)

**Comment by johnbazan** [comment]
Well, that's strange.
Which version are you using @heyitsanthony ?

Did you build from the current master?

**Comment by xiang90** [comment]
@johnbazan Can you get the version of your etcdctl?

**Comment by johnbazan** [comment]
Oh my god...
I'm so, so sorry, I screwed up. :/

I was using an old version (2.1.3), and this bug seems not to be anymore :(

Sorry guys.
I'll close this.

**Comment by heyitsanthony** [comment]
it happens, no worries
