### ISSUE TITLE
etcdctlv3: get range sorted by create not working as expected

### ISSUE THREAD

**Issue by jlamillan** [coreos/etcd#6671]
etcd v3.0.12 single local node cluster. 

I am trying to use `etcdctl get` to get a range sorted by the creation time. However, I am seeing the range seems to be always sorted in _lexical_ order.

For example, if I create keys foo3, foo1, and foo2 in that order:

`
$ etcdctl put foo3 foo3val
OK
`
`
$ etcdctl put foo1 foo1val
OK
`
`
$ etcdctl put foo2 foo2val
OK
`

Then try and get them, sorting by CREATE, I expect foo3, foo1, and foo2, but instead I get foo1, foo2, and foo3:

`
$ etcdctl get --sort-by=CREATE foo foo4
`
`
foo1
foo1val
foo2
foo2val
foo3
foo3val
`

**Comment by gyuho** [comment]
Try 

```
ETCDCTL_API=3 etcdctl get --sort-by=CREATE --order=ASCEND 
```

**Comment by gyuho** [comment]
Probably we need better documentation around this.

**Comment by xiang90** [comment]
@gyuho why we should provide an order here? if i tell etcdctl to sort keys by created revision, it should either sort them ascend or descend. right?

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/6672.

**Comment by jlamillan** [comment]
Thanks guys.
