### ISSUE TITLE
curl http://127.0.0.1:2379/v2/machines  got something seems wrong

### ISSUE THREAD

**Issue by xiaolu11bnb** [coreos/etcd#6674]
we setup a cluster, app using python. I found the the result of curl http://127.0.0.1:2379/v2/machines used by the python-ectd lib, the result is: 
http://0.0.0.0:2379, http://0.0.0.0:2379, http://0.0.0.0:2379, http://0.0.0.0:2379.
I think that's a problem. did I do something wrong?

**Comment by xiang90** [comment]
Yes. You give etcd wrong advertise url. you should never let etcd advertise 0.0.0.0.
