### ISSUE TITLE
locker can not get lock

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6679]
I get a locker like below, and lock, but it can not get lock, always hang.
etcd version: etcd-v3.0.6-linux-amd64

```
session, _ = concurrency.NewSession(s.client)
concurrency.NewLocker(session, key)
```

```
github.com/coreos/etcd/clientv3/concurrency.waitDelete(0x7f1fe397b5c0, 0xc8201bb080, 0xc8201f4000, 0xc820370a20, 0x21, 0x41, 0x0, 0x0)
	/mnt/hdd1/xiaoyulei/work/kvstore/src/github.com/coreos/etcd/clientv3/concurrency/key.go:31 +0x1dc
github.com/coreos/etcd/clientv3/concurrency.waitDeletes(0x7f1fe397b5c0, 0xc8201bb080, 0xc8201f4000, 0xc82032f7e0, 0x11, 0x40, 0x0, 0x0)
	/mnt/hdd1/xiaoyulei/work/kvstore/src/github.com/coreos/etcd/clientv3/concurrency/key.go:60 +0x27d
github.com/coreos/etcd/clientv3/concurrency.(*Mutex).Lock(0xc820370540, 0x7f1fe397b5c0, 0xc8201bb080, 0x0, 0x0)
	/mnt/hdd1/xiaoyulei/work/kvstore/src/github.com/coreos/etcd/clientv3/concurrency/mutex.go:60 +0xa8a
github.com/coreos/etcd/clientv3/concurrency.(*lockerMutex).Lock(0xc8201542b8)
	/mnt/hdd1/xiaoyulei/work/kvstore/src/github.com/coreos/etcd/clientv3/concurrency/mutex.go:90 +0x5c
github.com/YuleiXiao/kvstore/testutils.testLockUnlockV3(0xc8201ea090, 0x7f1fe397bba0, 0xc820122298)
```

**Comment by xiang90** [comment]
@YuleiXiao What version of client are you using?

**Comment by YuleiXiao** [comment]
@xiang90 I used latest master client. Version not match?

**Comment by xiang90** [comment]
Yes. You need to use client in 3.0 release branch.

**Comment by YuleiXiao** [comment]
@xiang90 ok, I am going to download it. Thanks

**Comment by 21stio** [comment]
Same for me. I am using the golang client github.com/coreos/etcd/clientv3 version: ^3.1.0-rc.1 and the etcd server Version: 3.0.15.

Any hint what might be wrong? All the worker are hanging.. Would be nice if one would not :)

**Comment by heyitsanthony** [comment]
@21stio the 3.1 client is using API features that aren't supported by 3.0. Either downgrade the client or upgrade the cluster.

**Comment by 21stio** [comment]
thanks, so client v3.0.15 will work with server v3.0.15 then?

**Comment by heyitsanthony** [comment]
Yes. The v3.0.15 client will also work with 3.1.

**Comment by 21stio** [comment]
Thanks, got it to work! :) Great stuff, thanks a lot
