### ISSUE TITLE
clientv3/concurrency: session.Close() hangs forever

### ISSUE THREAD

**Issue by huachaohuang** [coreos/etcd#6681]
I reuse the same client to create sessions in a loop, like this:

```
client := clientv3.NewClient()
for {
    session := concurrency.NewSession(client)
    ....
    session.Close()
}
```

But the `session.Close()` may never return sometimes.

I investigate into the `clientv3/lease/lessor` and find out when some errors occur, the `recvKeepAliveLoop()` will return, then the client can not be reuse again.

Maybe I should create a new client every time?

**Comment by yudai** [comment]
As far as I know, `session.Close()` can block when your client has no active connections  to your etcd cluster (`Revoke()` in the function blocks). A workaround currently available is closing your client and recreate a new client.

**Comment by huachaohuang** [comment]
I do more tests and find out that even if I create a new client every time, `session.Close()` can still block, because some errors occur and the `recvKeepAliveLoop()` returns, and then the `keepAliveCtxCloser` will return without closing the keep alive channel.

**Comment by siddontang** [comment]
We  meet a data race when using relection resign
```
==================
WARNING: DATA RACE
Write at 0x00c424dcca58 by goroutine 335:
  github.com/pingcap/pd/vendor/github.com/coreos/etcd/clientv3/concurrency.(*Election).Resign()
      /home/travis/gopath/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/clientv3/concurrency/election.go:115 +0x15b
  github.com/pingcap/pd/server.(*Lessor).Resign()
      /home/travis/gopath/src/github.com/pingcap/pd/server/lessor.go:82 +0x11d
  github.com/pingcap/pd/server.(*Lessor).Close()
      /home/travis/gopath/src/github.com/pingcap/pd/server/lessor.go:53 +0x38
  github.com/pingcap/pd/server.(*Server).resignLeader()
      /home/travis/gopath/src/github.com/pingcap/pd/server/leader.go:114 +0xbf
  github.com/pingcap/pd/server.(*Server).leaderRound()
      /home/travis/gopath/src/github.com/pingcap/pd/server/leader.go:98 +0x27e
  github.com/pingcap/pd/server.(*Server).leaderLoop()
      /home/travis/gopath/src/github.com/pingcap/pd/server/leader.go:72 +0x61f
  github.com/pingcap/pd/server.(*Server).Run()
      /home/travis/gopath/src/github.com/pingcap/pd/server/server.go:186 +0x55
Previous write at 0x00c424dcca58 by goroutine 190:
  github.com/pingcap/pd/vendor/github.com/coreos/etcd/clientv3/concurrency.(*Election).Resign()
      /home/travis/gopath/src/github.com/pingcap/pd/vendor/github.com/coreos/etcd/clientv3/concurrency/election.go:115 +0x15b
  github.com/pingcap/pd/server.(*Lessor).Resign()
      /home/travis/gopath/src/github.com/pingcap/pd/server/lessor.go:82 +0x11d
  github.com/pingcap/pd/server.(*Lessor).Close()
      /home/travis/gopath/src/github.com/pingcap/pd/server/lessor.go:53 +0x38
  github.com/pingcap/pd/server.(*Server).resignLeader()
      /home/travis/gopath/src/github.com/pingcap/pd/server/leader.go:114 +0xbf
  github.com/pingcap/pd/server.(*Server).Close()
      /home/travis/gopath/src/github.com/pingcap/pd/server/server.go:163 +0x12c
  github.com/pingcap/pd/server/api.mustNewCluster.func2()
      /home/travis/gopath/src/github.com/pingcap/pd/server/api/server_test.go:99 +0x9d
  github.com/pingcap/pd/server/api.(*testMemberAPISuite).TestMemberList()
      /home/travis/gopath/src/github.com/pingcap/pd/server/api/member_test.go:83 +0x4e5
  runtime.call32()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/asm_amd64.s:479 +0x4b
  reflect.Value.Call()
      /home/travis/.gimme/versions/go1.7.linux.amd64/src/reflect/value.go:302 +0xc0
  github.com/pingcap/pd/vendor/github.com/pingcap/check.(*suiteRunner).forkTest.func1()
      /home/travis/gopath/src/github.com/pingcap/pd/vendor/github.com/pingcap/check/check.go:772 +0xab0
  github.com/pingcap/pd/vendor/github.com/pingcap/check.(*suiteRunner).forkCall.func1()
      /home/travis/gopath/src/github.com/pingcap/pd/vendor/github.com/pingcap/check/check.go:666 +0x89
```

@xiang90

**Comment by heyitsanthony** [comment]
@siddontang I think Resign should race when used concurrently because it's a good indicator that something is wrong. It's not much different from doing:

```go
mu.Lock()
go mu.Unlock()
go mu.Unlock()
```

The code to handle concurrent close is boilerplate (but rather tedious); it probably shouldn't go in the election resign code because it seems like it would mask legitimate bugs...

**Comment by yudai** [comment]
I think `NewSession()` can hang up as well in failure cases.
However adding `ctx` to the parameters requires an API change, so probably adding a timeout with the TTL just like #6698?

https://github.com/coreos/etcd/blob/master/clientv3/concurrency/session.go#L41

**Comment by heyitsanthony** [comment]
maybe could add `WithContext` to session options?

**Comment by yudai** [comment]
That's a smart solution. I think `Close()` should respect it as well.
TTL can be too long to abort requests in failure cases, we sometimes set 30 seconds ~ 1 minute to it.

**Comment by yudai** [comment]
Sorry, respecting the same context both in `NewSession()` and `Close()` could make things complicated. Deadline to `NewSession()` and Deadline to `Close()` would be different times in most cases.

We could add options to `Close()` as well? This is a similar situation that when you set a deadline to a context to `Watch()`.

**Comment by heyitsanthony** [comment]
The context should just cover the lifetime of the session like it does with watch; it's a long-running operation. If it's given a timeout, it should take down the session after that amount of time. If you need to bound the time it takes to create a session, it can be done with context cancelation and a timer outside the session code.

**Comment by yudai** [comment]
Yes, I understand that.

I think the complicated part is `Close()`, because there are "cancellation of the session" and "cancellation of requests to cancel the session" for failure cases. `NewSession()` would work simply with `WithContext`. However `Close()` need something else for `Revoke()` to bail out from internal retries, like TTL in #6698 or `grpc.FastFail(false)`. If we use the same `ctx` given to `WithContext`, `Revoke()` always gets canceled.

By the way, If we provide `WithContext` to `NewSession`, should we call `Close()` or call the `cancel()` of the context? If we implement like `Watch()`, `Close()` is unnecessary besides backward compatibility.

I'm currently using an internal fork of the concurrency package which I added `ctx context.Context` to both `NewSession()` and `Close()` to avoid unexpected hang up.

**Comment by heyitsanthony** [comment]
@yudai I think the `Revoke` request should hang off the given context. If the context is canceled, Close() won't send the `Revoke` and return `ctx.Err()`.

**Comment by yudai** [comment]
@heyitsanthony I see. Just let me clarify that not calling `Revoke()` doesn't leak resource in the server side. I thought that `Grant()` keeps something in the server side until `Revoke()` is called or the connection to the client gets lost.

**Comment by heyitsanthony** [comment]
@yudai a cancel would stop the session's goroutine for renewing the lease's TTL. If the renews stop, the TTL will eventually expire and the server will remove the lease.

**Comment by yudai** [comment]
@heyitsanthony I see. Then just skipping `Revoke()` makes sense 👍
