### ISSUE TITLE
etcd-dump-db: debug tool for boltdb db file (read with hash)

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#6686]
When debugging issues like https://github.com/coreos/etcd/issues/6685, we need a way to compare db, records by hash value, and way to find a point in time with specific hash.

**Comment by xiang90** [comment]
we should add a new tool called etcd-dump-db or something for this.

**Comment by gyuho** [comment]
Ok sounds good.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/6705
Leave reverting db feature as TODO for now.
