### ISSUE TITLE
can be the TTL expire time calculation based on relative time?

### ISSUE THREAD

**Issue by nenzhang** [coreos/etcd#6700]
Now looks etcd TTL expires based on system real time, which may not be reliable as system NTP service will do synchronization from server. 
yes, normally it shall not be big jump for system time, but it is really very good to know if it can be configured with relative time like MONOTONIC.

**Comment by nenzhang** [comment]
I used the etcd 3.0.12 version, but I found when the system time changes manually, the expire time will be changed also. shall I do some configuration to have this relative clock?

**Comment by heyitsanthony** [comment]
@nenzhang oh, I see your point. Leases use time.Now() to compute the expiry deadline and the system clock could jump around (probably broken for day light savings time?). Marking as a bug. Thanks!

**Comment by xiang90** [comment]
@heyitsanthony We probably can convert it to logical clock somehow. Do you think this is something we should fix soon?

**Comment by heyitsanthony** [comment]
Definitely should have a fix before November 6th...

**Comment by xiang90** [comment]
added into the most recent milestone.

**Comment by nenzhang** [comment]
Hi
ok, good to hear,

**Comment by xiang90** [comment]
Blocks on https://github.com/golang/go/issues/12914.

We do not want to roll out our own mono clock if it is already planned for go 1.8.

@heyitsanthony Can we move this out of 3.1 release?

**Comment by minjs** [comment]
Even with system real time, I assume it should use the master system time. 
In our case, the NTP was set to different NTP server accidentally. Whenever we set TTL key on local non master node, the key was deleted.  It turns out the expiring time is from local node, and it already behind master current time.

**Comment by gyuho** [comment]
@heyitsanthony @xiang90  The Go issue got delayed to Go 1.9, which is another 6+ months.
