### ISSUE TITLE
query: why curl easy perform returns success sometimes when leader etcd is down.

### ISSUE THREAD

**Issue by nenzhang** [coreos/etcd#6706]
pre-condition: etcd leader is down. trigger set operation continuously in etcd proxy node while etcd proxy itself is printing logs that connection to etcd leader is not available, this is normal.
 etcd[22843]: could not get cluster response from http://169.254.0.20:2380: Get http://169.254.0.20:2380/members: dial tcp 169.2
 etcd[22843]: proxy: could not retrieve cluster information from the given urls

However, the set operation via below curl command in most of times, it returns NOK and resp->err is NULL. But still many time it returns OK and the parser.resp 's ecode is 0x0. why?  
it will lead to user to consider the set operation succeed as mistake.

res = curl_easy_perform(curl);

```
//release the parser resource
sdsfree(parser.buf);
if (parser.json) {
    yajl_free(parser.json);
    array_destroy(&parser.ctx.keystack);
    array_destroy(&parser.ctx.nodestack);
}

if (res != CURLE_OK) {
    if (resp->err == NULL) {
        resp->err = calloc(1, sizeof(error_t));
        if (resp->err == NULL) {
            return resp;
        }
        resp->err->ecode = SEND_REQUEST_ERR;
        resp->err->message = sdsnew(curl_easy_strerror(res));
        resp->err->cause = sdsdup(req->url);
    }
    return resp;
}
return parser.resp;
```

**Comment by heyitsanthony** [comment]
Can you reproduce the problem server response with `curl -v`? Not really familiar with yajl or curl bindings.

**Comment by nenzhang** [comment]
ok, thanks. I will try when I have environment!

**Comment by nenzhang** [comment]
I tried, and I detected it received the different kinds of HTTP errors, like 400, 403, 500...etc.
so this is normal, right? as they all indicated that the HTTP server has problem...

**Comment by xiang90** [comment]
@nenzhang I do not really understand what you said. Can you provide more context and some examples?

**Comment by nenzhang** [comment]
Hi Xiang
see the below fake code, I mean I add log printing in _parse_response__r function to check the returned status like below. thanks.
I refer to cetd lib.

    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, _parse_response__r);
    res = curl_easy_perform(curl);

size_t _parse_response__r(char *ptr, size_t size, size_t nmemb, void *userdata)
{
parser = userdata;
........
            if (parser->http_status != 200 && parser->http_status != 201) {
               print the http_status to indicates the error happens here. and sometimes it is 400, sometimes it is 500. sometimes it is 403.
           }
.........
}

**Comment by gyuho** [comment]
Can you provide raw curl request with `-I` flag?
What's `cetcd`?

**Comment by nenzhang** [comment]
Hi
with raw curl command, I tried one time, the return code always 0 with $?, and it will print the same message with zero end points:
{"message":"httpproxy: zero endpoints currently available"}

cetcd means that there exist one open source code project to deliver commands to etcd via C function in github:
https://github.com/shafreeck/cetcd/blob/master/cetcd.c

could you kindly help check whether this kind of c code implementation works or not? thanks.

**Comment by xiang90** [comment]
> could you kindly help check whether this kind of c code implementation works or not? thanks.

Can you create an issue in its github repo instead? The author knows more than us and would help you better.

**Comment by nenzhang** [comment]
Hi
:)
do you have any official c development kit for using etcd? thanks

**Comment by xiang90** [comment]
@nenzhang 

No. we do not.

**Comment by nenzhang** [comment]
Hi
ok, then we can close this firstly
