### ISSUE TITLE
Correct setup documentation and fork me link.

### ISSUE THREAD

**Issue by gcavalcante8808** [coreos/etcd#6713]
Hello folks,

I was trying to setup a New Calico infrastructure and, for that, I need an  Etcd server running. Reading the https://coreos.com/etcd/docs/latest/docker_guide.html link, I just discovered that the correct command to run the container is:

[...] --name etcd quay.io/coreos/etcd  **etcd** -name etcd0 [...]

Instead of:

[...] --name etcd quay.io/coreos/etcd  -name etcd0 [...]

Alas, the link of the "Fork Me Link" is pointing to https://github.com/coreos/etcd/tree/master/Documentation/docker_guide.md, which gave 404 Errors.

With this in mind, I know that is a simple correction, but from a starter point of view it can be troublesome ...

PS: The CMD is /usr/local/etcd, but to run with the container **and** receive the args I think that the image need to use ENTRYPOINT instead. No? If not, why the command provided in the documentation wont work?

**Comment by gyuho** [comment]
Sorry, coreos.com docs are not up-to-date. It's in our queue.

In the meantime please try the docker guide here https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md

**Comment by gcavalcante8808** [comment]
@gyuho Just in time: There is support for calico on docker 1.12? I'm trying to use it, but I'm receiving "plugin not found" even if my vm's are not operating in swarm mode.

**Comment by xiang90** [comment]
@gyuho Is this fixed?

**Comment by gyuho** [comment]
@xiang90 Not yet. I will send a PR to fix it.

**Comment by xiang90** [comment]
OK. Thanks.

**Comment by gyuho** [comment]
I reported this to our UI team. Closing. Will keep you updated once fixed. Thanks!
