### ISSUE TITLE
how to get ttl from leaseID?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6716]
In clientv3, I ```Get``` kv pairs, there is a ```Lease``` in ```KeyValue```, how to get ttl from ```Lease```? I did not find the interface to use.

**Comment by gyuho** [comment]
Try https://github.com/coreos/etcd/tree/master/etcdctl#lease-timetolive-leaseid-options?

**Comment by xiang90** [comment]
Closing this since @gyuho provided the correct answer.

**Comment by YuleiXiao** [comment]
@gyuho Is there an api interface?

**Comment by xiang90** [comment]
@YuleiXiao https://github.com/coreos/etcd/blob/master/clientv3/lease.go#L80. You need to use both etcd 3.1 + client 3.1 though.

**Comment by YuleiXiao** [comment]
@xiang90 OK, I need upgrade version. I use 3.0 now. Thanks all of you.
