### ISSUE TITLE
clientv3: will Compare support "!=" ?

### ISSUE THREAD

**Issue by soyking** [coreos/etcd#6719]
In a transaction, the `if` support Compare condition.

In my case I want to confirm some k/v is not a specified value, but in [compare](https://github.com/coreos/etcd/blob/master/clientv3/compare.go#L36) the `result` don't support `!=`. So is there any way to make it possible?

And this is what I want:

```
txn.If(
    clientv3.Compare(
        clientv3.Value(someKey),
        "!=",
        someValue,
    )
).Then(
    clientv3.OpPut(otherKey, othervalue),
)
```

**Comment by sinsharat** [comment]
@soyking we don't support "!=" since what you want can be achieved using Else with "=".
You can use it as :
```
txn.If(
    clientv3.Compare(
        clientv3.Value(someKey),
        "=",
        someValue,
    )
).Then(
).Else(
clientv3.OpPut(otherKey, othervalue),
).Commit()
```

**Comment by soyking** [comment]
@sinsharat 

Actually I simplify the situation, and there are some other conditions with the "!=", just like:

* If other_conditions && some_key != some_value Then do_something

So if I want use `Else`, I should write:

* If other_conditions || some_key == some_value Then null Else do_something

But the conditions in `If` can just be calculated by `&&`, am I right? So is there any way to support `||` or `!=` ?

**Comment by xiang90** [comment]
It is not supported. But it is not hard to add. But we do not plan to make it complicated right now. Do you have a specific use case for it?

**Comment by heyitsanthony** [comment]
`!=` and OR'ing slices of conjunctions will buy a full boolean algebra via disjunctive normal form; there's no way to model implication with the current semantics.

**Comment by soyking** [comment]
@xiang90 

I just use it in my personal project. But I think supporting basic condition action is worthy, at lease `!=`. Hope to see it on your schedule.

**Comment by soyking** [comment]
@heyitsanthony 

alright… thank you.

**Comment by xiang90** [comment]
@fanminshi I assigned this to you per our offline discussion.

**Comment by soyking** [comment]
@fanminshi @xiang90 

I have a question. 

In the program:

```go
package main

import (
	"github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
)

func main() {
	clt, err := clientv3.New(clientv3.Config{
		Endpoints: []string{"127.0.0.1:2379"},
	})
	checkErr(err)

	key := "abc"
	value := "def"

	txn := clt.Txn(context.TODO())
	txn.If(
		clientv3.Compare(
			clientv3.Value(key),
			"!=",
			value,
		),
	)

	resp, err := txn.Commit()
	checkErr(err)

	println(resp.Succeeded)

	txn = clt.Txn(context.TODO())
	txn.If(
		clientv3.Compare(
			clientv3.Value(key),
			"=",
			value,
		),
	)

	resp, err = txn.Commit()
	checkErr(err)

	println(resp.Succeeded)
}

func checkErr(err error) {
	if err != nil {
		panic(err)
	}
}

```

return 

```
false
false
```

but they are opposite conditions. Notice that the key `abc` has not been set. So is it possioble that for `=` it will check the existence of a key but for `!=` it will not ？

**Comment by fanminshi** [comment]
@soyking both "!=" and "=" comparison will check for the existence of a key. However, in your case, the `abc` key is not set. Comparing value of a non-existent key will alway return false. It doesn't make any sense to compare value of a non-existent key.

more info:
https://github.com/coreos/etcd/blob/master/etcdserver/apply.go#L415-L418

**Comment by soyking** [comment]
@fanminshi 

I see. Thank you.
