### ISSUE TITLE
Memebers API on etcd v3

### ISSUE THREAD

**Issue by jszczepkowski** [coreos/etcd#6720]
According to the [members API documentation](https://coreos.com/etcd/docs/latest/members_api.html), one should use `/v2/members` endpoint to add/remove/list members of etcd cluster.

Is it a proper way of accessing members on etcd v3 release? 

Shouldn't it be changed to `/v3/members`?

**Comment by jszczepkowski** [comment]
CC @fgrzadkowski

**Comment by sinsharat** [comment]
@jszczepkowski it depends on which API you are using. ETCD supports both v2 and v3 versions for backward compatibility. So the API which you want to use depends on which version of API you want to use. The link you have mentioned clearly specifies the version as : etcd 2.3.7 Documentation.
Also the coreOS documentation haven't been updated for v3. Please refer the issue #6713.
Its in the queue.
Please refer the below documentation in the interim:
https://github.com/coreos/etcd/blob/master/etcdctl/README.md

**Comment by sinsharat** [comment]
@gyuho can this be labelled for kind/documentation as well?

**Comment by gyuho** [comment]
@sinsharat @jszczepkowski Yeah... coreos.com docs are outdate. We will update soon.

**Comment by xiang90** [comment]
@jszczepkowski There is no "official" http endpoint for v3. v3 is rpc based, it is defined here: https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L118, doc: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#service-cluster-etcdserveretcdserverpbrpcproto.

**Comment by fgrzadkowski** [comment]
Does it mean that the recommended way to add/remove member via commandline is using `etcdctl` as using `curl` is not support for `v3`?

**Comment by xiang90** [comment]
@fgrzadkowski Yes.

**Comment by xiang90** [comment]
Doc is updated. So closing.
