### ISSUE TITLE
etcd-runner: Not able to run etcd-runner for long periods against fault-injection-cluster

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6722]
**Issue:**
We are not able to test fault injection cluster for long periods of time due to fault-injection cluster making the cluster down for long periods. This results in grpc timeout err and the test case terminates.

**Steps to reproduce:** 
1. Start fault injection cluster using below link:
https://github.com/coreos/etcd/tree/master/tools/functional-tester#with-goreman

2. Executing etcd-runner with the below command:
./etcd-runner --endpoints="localhost:12379,localhost:22379,localhost:32379"

When the fault-cluster makes the cluster down, grpc timeout happens, especially for watcherRunner since it has to make a lot of client connections.

**Proposed Solution:** 
1. The solution which i can think of is to add a client-timeout flag and make the value quite high for getting the client connection or pass value as 0 to make it try till it gets the connection.

**Alternate Solution:**
2. Make getting client connection in retry mode so it keeps trying till it gets the connection from the cluster when the cluster comes back up.

/cc @xiang90 @heyitsanthony @gyuho @fanminshi opinions.
Thanks!

**Comment by xiang90** [comment]
> grpc timeout happens, especially for watcherRunner since it has to make a lot of client connections.

Do you have any log for this? I think the client should retry internally until you call client.Close.

**Comment by sinsharat** [comment]
@xiang90 since we are providing timeout as 5s only and if the cluster is down for more than 5s, it gives grpc timeout. In the logs only that error shows, since in client code we are returning the same if its not able to get connection by then.
ErrClientConnTimeout = errors.New("grpc: timed out when dialing")
In out etcd runner we are doing log.Fatalf(err). Hence the moment it gets err it terminates.
If you want logs of the fault-injection-cluster, let me know.
I am right now going to set up with the test case for etcd-runner for watch by adding client-timeout flag as 0 with fault injection cluster and check if it works fine. If it works fine for 1hr will raise the PR for this.
Thank you!

**Comment by xiang90** [comment]
> since we are providing timeout as 5s 

Where? Probably change this to 1 minute or so?

**Comment by sinsharat** [comment]
@xiang90 its present under newClient func in etcd-runner. My view was that rather than hard coding it for 1min, we make it configurable as a flag so that depending upon the test case we are running we can configure from command line accordingly. Since we don't know how the cluster will behave at what point of time and for how long the cluster will be down. What do you suggest?

**Comment by xiang90** [comment]
@sinsharat Sure. That is fine too. We should have an estimate upper bound for cluster failure duration. And we set timeout longer than that.

**Comment by sinsharat** [comment]
@xiang90 yes sure. Will test it running it for 5hrs as you had wanted and if after one hour its still running fine will raise a PR for this.
Thank you!

**Comment by xiang90** [comment]
Awesome. Great!

**Comment by sinsharat** [comment]
Guess this issue is solved now. Hence closing this.
Thank you!
