### ISSUE TITLE
etcd : Go get command giving interface implementation error for wserver

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#6726]
![image](https://cloud.githubusercontent.com/assets/20169156/19698496/220ab3bc-9b0d-11e6-8ce5-c592a87bc408.png)

**Comment by gyuho** [comment]
Can you use grpc-go v1.0.2?

It's from grpc upstream change. Should we update to grpc v1.0.3 https://github.com/grpc/grpc-go/releases/tag/v1.0.3?

/cc @xiang90 @heyitsanthony

**Comment by sinsharat** [comment]
@gyuho its not so much an issue for me since i use git for my code. Just found the issue so informed it.
Thanks for your suggestion though :-)
