### ISSUE TITLE
Question: leaseID in NewUniqueKV

### ISSUE THREAD

**Issue by cesarghali** [coreos/etcd#6731]
Is there a reason why `leaseID` is not passed to `putNewKV` function in `NewUniqueKV`: https://github.com/coreos/etcd/blob/12e4dfa9c47434e5d63d1cc0c230b78e8f06c3e4/contrib/recipes/key.go#L68? This makes passing a `leaseID` value to `NewUniqueKV` useless.

If that is not intentional, is there a plan to fix it?

**Comment by heyitsanthony** [comment]
That's not really meant to be a stable API; it probably shouldn't be exported at all...

**Comment by xiang90** [comment]
@heyitsanthony Can we make them private?

**Comment by cesarghali** [comment]
Thank you @heyitsanthony for the quick fix.
