### ISSUE TITLE
Documentation on wiping a cluster member from discovery.etcd.io

### ISSUE THREAD

**Issue by sriedel** [coreos/etcd#6734]
Hi,
I've been trying to set up a 3 member etcd cluster in coreos under virtualbox for a few days now, and I have a few issues. 

My main issue is that after fiddling around with the could-config.yml (in which I had a few mistakes, being a noob at etcd and coreos), now whenever I setup and start a new cluster two out of the three members throw an error during discovery, complaining that their member ID is already known in a different cluster and failing, while the third usually succeeds after a few Gateway timeouts or context deadline exceeded errors and is waiting for the other members in vain. 

So far I haven't found any documentation a) on how the member id is generated (i.e. how can I guarantee that in the next run I'll have completely new ids that haven't been referenced before? Does the IP address factor in? The MAC address? Hostname?) nor b) how to flush previously used member ids from discovery.etcd.io _if I don't know the cluster id anymore_ (I've had half a dozend tries before coming to this errors, so ~18 member ids of mine will be floating around discovery.etcd.io and I have no idea which ones and for what cluster id). 

So far I've tried over 30 times to set up a 3 member cluster and haven't had a single successful cluster bootstrap due to this. Since I don't have control over DNS in my testing environment, my only other option would be to set up a cluster manually, but that kind of defeats the purpose.

So it would be nice to have the knowledge of how to create a cluster in a way that allows one to use an environment as pristine regarding cluster and member ids as is possible.

**Comment by sinsharat** [comment]
@sriedel Hope this helps:
https://coreos.com/etcd/docs/latest/clustering.html
Also if you are not using it in production environment, would recommend you to delete the data dir created on etcd startup before you try again.

**Comment by sriedel** [comment]
@sinsharat: thank you for the pointer, however something still seems odd. 
I've already had the default "Environment=ETCD_NAME=%m" in the etcd2.service file. Acting on the documented passage "Each member must have a different name flag specified. Hostname or machine-id can be a good choice. Or discovery will fail due to duplicated name." I've tried changing the name for something I've never used before. And I still get the same error condition (one member joins the cluster, the other two get reported that the member id has already been used at the first attemt to join the cluster.

I've been working with the following cloud-config.yml:
```
#cloud-config
hostname: master-c
users: 
- name: admin
  passwd: $1$vtxa9PAw$PwlguxhqeN4wrgWHQ9.Zf.
  groups:
  - sudo
  - docker
ssh_authorized_keys: 
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDFXad5auihdMHEPR4cQhoyNakdYpZS1SCPZyY6zyPWqWuCF12+EjD0i14825Nd8nPNYLOzJS58xzfgSlsTvx5JR2+0iODgTD6H79v/xLkLh0kQKwEbAyJuwgxiyj7PDhwflx3hZU+GwC1gnexnfQHTpx8je+Zy4ZfvWHl3EcEYDZgR08FZe4IHnyzUe6hSqKivOuMW+F6m5qcgVl4xZ/rJGScQ/NGq+GNuCCMgY/eA+XWTHHwfdQX3VyiIY8+Q2DEXYwGWWGWeam027N4Y8ZTlqHozglpAx11ITA/wmyJ9Ji6arUPUQ7ox0U8VZKjbGN3vuTr/JJftu+ms6ugYsXYl sr@littlebrother
coreos:
  etcd2:
    name: zzz_core_master_c_zzz
    discovery: https://discovery.etcd.io/ec5ce901bbf286f6b976bd800f9a7b66
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://$private_ipv4:2380
    data-dir: /var/lib/etcd2
  units:
  - name: etcd2.service
    command: start
  - name: fleet.service
    command: start
```
(hostname and coreos.etcd2.name were changed for each host being set up)

The corresponding output of `journalctl -t etcd2` of a failing member:
```
-- Logs begin at Wed 2016-10-26 08:20:11 UTC, end at Wed 2016-10-26 08:28:29 UTC. --
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://:2379
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/ec
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://:23
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://:2380
Oct 26 08:20:17 master-c etcd2[873]: recognized and used environment variable ETCD_NAME=zzz_core_master_c_zzz
Oct 26 08:20:17 master-c etcd2[873]: etcd Version: 2.3.2
Oct 26 08:20:17 master-c etcd2[873]: Git SHA: ce63f10
Oct 26 08:20:17 master-c etcd2[873]: Go Version: go1.5.4
Oct 26 08:20:17 master-c etcd2[873]: Go OS/Arch: linux/amd64
Oct 26 08:20:17 master-c etcd2[873]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 26 08:20:17 master-c etcd2[873]: listening for peers on http://:2380
Oct 26 08:20:17 master-c etcd2[873]: listening for client requests on http://0.0.0.0:2379
Oct 26 08:20:17 master-c etcd2[873]: resolving :2380 to :2380
Oct 26 08:20:17 master-c etcd2[873]: resolving :2380 to :2380
Oct 26 08:20:17 master-c etcd2[873]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Oct 26 08:20:17 master-c etcd2[873]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 2s
Oct 26 08:20:20 master-c etcd2[873]: stopping listening for client requests on http://0.0.0.0:2379
Oct 26 08:20:20 master-c etcd2[873]: stopping listening for peers on http://:2380
Oct 26 08:20:20 master-c etcd2[873]: member "zzz_core_master_c_zzz" has previously registered with discovery service toke
Oct 26 08:20:20 master-c etcd2[873]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/
Oct 26 08:20:20 master-c etcd2[873]: Please check the given data dir path if the previous bootstrap succeeded
Oct 26 08:20:20 master-c etcd2[873]: or use a new discovery token if the previous bootstrap failed.
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://:2379
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/ec
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://:23
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://:2380
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_NAME=zzz_core_master_c_zzz
Oct 26 08:20:31 master-c etcd2[925]: etcd Version: 2.3.2
Oct 26 08:20:31 master-c etcd2[925]: Git SHA: ce63f10
Oct 26 08:20:31 master-c etcd2[925]: Go Version: go1.5.4
Oct 26 08:20:31 master-c etcd2[925]: Go OS/Arch: linux/amd64
Oct 26 08:20:31 master-c etcd2[925]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 26 08:20:31 master-c etcd2[925]: listening for peers on http://:2380
Oct 26 08:20:31 master-c etcd2[925]: listening for client requests on http://0.0.0.0:2379
Oct 26 08:20:31 master-c etcd2[925]: resolving :2380 to :2380
Oct 26 08:20:31 master-c etcd2[925]: resolving :2380 to :2380
Oct 26 08:20:36 master-c etcd2[925]: stopping listening for client requests on http://0.0.0.0:2379
Oct 26 08:20:36 master-c etcd2[925]: stopping listening for peers on http://:2380
Oct 26 08:20:36 master-c etcd2[925]: failed to join discovery cluster (context deadline exceeded)
Oct 26 08:20:36 master-c etcd2[925]: discovery token https://discovery.etcd.io/ec5ce901bbf286f6b976bd800f9a7b66 was used,
Oct 26 08:20:36 master-c etcd2[925]: please generate a new discovery token and try to bootstrap again.
```
This is with a freshly set up VM in virtualbox that has never had a cluster join attempt performed before.

Looking at the output of the discoveryd server for this cluster, it only knows the name of the one member that successfully joined:

```
{
  "action": "get",
  "node": {
    "key": "/_etcd/registry/ec5ce901bbf286f6b976bd800f9a7b66",
    "dir": true,
    "nodes": [
      {
        "key": "/_etcd/registry/ec5ce901bbf286f6b976bd800f9a7b66/8f664f5ab48a5085",
        "value": "zzz_core_master_a_zzz=http://:2380",
        "modifiedIndex": 1201165991,
        "createdIndex": 1201165991
      }
    ],
    "modifiedIndex": 1201162616,
    "createdIndex": 1201162616
  }
}
```

Any ideas what may be wrong here?

**Comment by sriedel** [comment]
One addendum: /var/lib/etcd2 is empty both for the failed hosts and for the host that successfully joined the cluster (probably because the cluster state is only written once all members have joined?).

**Comment by sinsharat** [comment]
@sriedel yes since you are trying to create a 3 member cluster, cluster will not be up unless atlease two members have joined.
One question i have is why you are trying to set the below as env variables:
ct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://:2379
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/ec
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://:23
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://:2380
Oct 26 08:20:31 master-c etcd2[925]: recognized and used environment variable ETCD_NAME=zzz_core_master_c_zzz
I think this might be causing the issue. Since till now what i have used is without setting any environment variable.
Can you try removing all env_variables which you have added for etcd and try starting a fresh cluster without it?

**Comment by sriedel** [comment]
@sinsharat: Those environments are created by cloudos-install from the cloud-config.yml configuration. According to https://coreos.com/os/docs/latest/cluster-discovery.html I understood that these configuration parameters need to be supplied (and ports 4001 and 7001 are deprecated, thus I removed the references to them). And the documentation that you pointed me to said that a unique name parameter must be provided, thus my attempt at setting this as well.

Did I misunderstand the documentation? If so, which (if any) parameters should I supply in the cloud-config.yml used by coreos-install beyond the discovery url?

**Comment by sriedel** [comment]
@sinsharat: I've tried again both with only coreos.etcd2.discovery and both coreos.etcd2.discovery and coreos.etcd2.name set, in both cases the results were the same originally described; log extract:

```
-- Logs begin at Wed 2016-10-26 10:36:59 UTC, end at Wed 2016-10-26 10:41:38 UTC. --
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: recognized and used environment variable ETCD_NAME=master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: etcd Version: 2.3.2
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: Git SHA: ce63f10
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: Go Version: go1.5.4
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: Go OS/Arch: linux/amd64
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: listening for peers on http://localhost:2380
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: listening for peers on http://localhost:7001
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: listening for client requests on http://localhost:2379
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: listening for client requests on http://localhost:4001
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: error #0: dial tcp: lookup discovery.etcd.io: Temporary failure in name resolution
Oct 26 10:37:05 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: cluster status check: error connecting to https://discovery.etcd.io, retrying in 2s
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: stopping listening for client requests on http://localhost:4001
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: stopping listening for client requests on http://localhost:2379
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: stopping listening for peers on http://localhost:7001
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: stopping listening for peers on http://localhost:2380
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: member "master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf" has previously registered with discovery service token (https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff).
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: Please check the given data dir path if the previous bootstrap succeeded
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: or use a new discovery token if the previous bootstrap failed.
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: recognized and used environment variable ETCD_NAME=master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: etcd Version: 2.3.2
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: Git SHA: ce63f10
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: Go Version: go1.5.4
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: Go OS/Arch: linux/amd64
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: listening for peers on http://localhost:2380
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: listening for peers on http://localhost:7001
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: listening for client requests on http://localhost:2379
Oct 26 10:37:18 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: listening for client requests on http://localhost:4001
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: stopping listening for client requests on http://localhost:4001
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: stopping listening for client requests on http://localhost:2379
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: stopping listening for peers on http://localhost:7001
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: stopping listening for peers on http://localhost:2380
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: failed to join discovery cluster (context deadline exceeded)
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: discovery token https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff was used, but failed to bootstrap the cluster.
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: please generate a new discovery token and try to bootstrap again.
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: recognized and used environment variable ETCD_DISCOVERY=https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: recognized and used environment variable ETCD_NAME=master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: etcd Version: 2.3.2
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: Git SHA: ce63f10
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: Go Version: go1.5.4
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: Go OS/Arch: linux/amd64
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: listening for peers on http://localhost:2380
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: listening for peers on http://localhost:7001
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: listening for client requests on http://localhost:2379
Oct 26 10:37:33 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: listening for client requests on http://localhost:4001
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: stopping listening for client requests on http://localhost:4001
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: stopping listening for client requests on http://localhost:2379
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: stopping listening for peers on http://localhost:7001
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: stopping listening for peers on http://localhost:2380
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: member "master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf" has previously registered with discovery service token (https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff).
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: Please check the given data dir path if the previous bootstrap succeeded
Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: or use a new discovery token if the previous bootstrap failed.
```

**Comment by sinsharat** [comment]
```Oct 26 10:37:34 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[977]: But etcd could not find valid cluster configuration in the given data dir (/var/lib/etcd2).```
@sriedel From what i understand from the logs its not getting the cluster configuration, in the path /var/lib/etcd2.
@gyuho can you help on this for the exact reason for the problem?
Thank you!

**Comment by gyuho** [comment]
@sriedel Did you use the same data directory previously for setting up another etcd cluster? You should delete all the data from previous cluster.

**Comment by xiang90** [comment]
@sriedel 

Did you reuse the discovery token? It is a one time token, you should not reuse it no matter if the cluster is bootstrapped or not

You cannot really wipe a member from discovery service. Again, it is one time token for bootstrapping ONLY. After that point, it is on the users to reconfigure the cluster. So you either successfully start the cluster or fail. But that token is over. And the cluster is at your hand. Discovery will not do anything after that point.

**Comment by sriedel** [comment]
@gyuho: After every try to set up the cluster I nuked the VMs and the filesystems associated with them, and set everything up again from scratch. So yes, I've installed coreos now over 100 times... I wanted to avoid all cross-contamination from the old, failed cluster attempt. So yes, I deleted all data from the previous cluster.

@xiang90: I did not reuse the token. I get that it's a one time token, but then: why does etcd keep telling me on the initial bootstrapping that the member is already part of a different cluster? This would mean that the _member id_ (or member token, or whatever you want to call it) is computed by some host attributes and is not a one-time token like the cluster token and discoveryd.etcd.io keeps records of what member ids it's already seen. OTOH, since I generated pretty unique names for the etcd instances (see my previous two messages) and I'm still getting that message that this host is already a member of another cluster on the very first attempt to join a cluster, I wonder just how much of the communication is actually comming from discovery.etcd.io. Are you guys sure that discovery.etcd.io doesn't have a bug in that regard?

**Comment by xiang90** [comment]
> Are you guys sure that discovery.etcd.io doesn't have a bug in that regard?

Well, I am sure there is something wrong at your end if all you described are accurate. If you use different discovery token, then it does not really matter what member id is or how local etcd generates member id.

For the log 
```
Oct 26 10:37:08 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[865]: member "master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf" has previously registered with discovery service token (https://discovery.etcd.io/9b3635fa1da52642b7a6aca94a2bbaff).
```
, it is pretty clear that you did reuse the token.

**Comment by xiang90** [comment]
@sriedel 

Also some log suggested that you machine has connection issues with discovery service:

```
Oct 26 10:37:23 master_b_1884e5bc970225f5f2f09dc61a845ab6a5760bcf etcd2[921]: failed to join discovery cluster (context deadline exceeded)
```

I think you need to first sort out issues at your end.

**Comment by sriedel** [comment]
@xiang90: No I most definitely did not reuse the token. But how do I prove a negative to you? 

And what does "context deadline exceeded" mean? What sort of issues am I looking for? What context? Whats the deadline? I can connect with curl on the command line just fine to discovery.etcd.io... I'll need a few pointers here since that message means next to nothing to me :(

**Comment by xiang90** [comment]
@sriedel 

The log clearly showed that you RESUE the token several times. You just need to read the log and see how many times the SAME token showed on different etcd startup.

 I do not know how you managed to do it. Maybe you just reused it or you configured systemd to restart etcd on failure. I think that is something you need to figure out first.

**Comment by sriedel** [comment]
@xiang90: Ok, here's what I did step by step for the log-snippet above. Please tell me where I went wrong:

1. Create a new cluster token url via https://discovery.etcd.io/new?size=3 (since I want a 3 node cluster, I used size=3).
2. I created a stub cloud-config.yml as shown above, with the output of step 1 in the coreos.etcd2.discovery attribute
3. I created a new virtual machine in virtual box with a blank virtual harddrive
4. I attached the coreos_production_iso_image.iso downloaded from the coreos website to the virtual CDROM drive of the VM
5. I booted the VM
6. Once obtaining the shellprompt, I copied the cloud-config.yml stub into a local file. 
7. I changed the hostname (and coreos.etcd2.name, if used) attributes so that it is unique to the VM
8. I ran `sudo coreos-install -d /dev/sda -C stable -c cloud-config.yml`
9. After it finished I shut down the VM via `sudo poweroff`
10. I detached the coreos ISO from the VMs virtual CDROM drive
11. Repeat steps 3.-10. for two more virtual machines. NOTE: each has a DIFFERENT hostname (and a different coreos.etcd2.name if used) but use the SAME coreos.etcd2.discovery token on each node, since all should be part of the same cluster (<- is this correct? Or would each machine need a different discovery token???)
12. I booted all three VMs within a few seconds of each other
13. I looked into `sudo journalctl -t etcd2` in each machine and see that the cluster bootstrap failed because usually: 1 host managed to register on discovery.etcd.io and the other two did not.
14. unless frustrated, shutdown VMs, delete VMs and goto 1. 

I am quite aware what the logs say, but I can tell you that I regenerate the discovery token for each and every cluster I try to set up and use this new cluster in the cloud-config.yml. 

The cloud-config.yml I pasted above is exactly what I used the last time I tried setting up the last two clusters from which the logs are pasted here -- except for the discovery token of course. In addition, I did not configure systemd in any way except telling the etcd2 and fleet services to startup automatically, as in the cloud-config.yml pasted above (which was copied from https://coreos.com/os/docs/latest/cluster-discovery.html - please verify yourself) . So the systemd/etcd2-restart/retry behaviour is the default of the coreos installation 1122.3. 

Also, you didn't answer regarding the context timeout: What is the context and what is the timeout duration? What kind of network problems am I looking for, if curl can access https://discovery.etcd.io?

**Comment by xiang90** [comment]
> Also, you didn't answer regarding the context timeout:

That happens after you reused the token. I do not really know what went wrong after that. So I suggest you to not reuse the token at the first place.

Can you please attach all etcd logs (from the very beginning to the end, not just part of it) of all three machines directly? Most of your 11 steps are out of etcd scope.

**Comment by sriedel** [comment]
So, after continuing on debugging with the help of some friends who already have an etcd2 cluster up and running in production, I got a cluster running. It turns out that the "context deadline exceeded" message is misleading; it must be part of the communication of the local etcd2 process trying to reach the discovery.etcd.io API and has nothing to do with token reuse as @xiang90 claims above. What got it up and running was to run the etcd2 command below in the commandline, disregard the "context deadline exceeded" message and just repeat the call _with the same cluster token_(!) until it succeeds (took me about 5 to 10 tries until both "broken" instances got a real connection to the discovery servers and after that everything went swimmingly. 

```
core@core-c ~ $ sudo /usr/bin/etcd2  --name $NODE_NAME --initial-advertise-peer-urls http://$IP:2380 --listen-client-urls http://$IP:2379,http://127.0.0.1:2379 --advertise-client-urls http://$IP:2379 --listen-peer-urls http://$IP:2380 --discovery $DISCOVERY_URL
2016-10-28 13:49:59.958738 I | etcdmain: etcd Version: 2.3.2
2016-10-28 13:49:59.960572 I | etcdmain: Git SHA: ce63f10
2016-10-28 13:49:59.961354 I | etcdmain: Go Version: go1.5.4
2016-10-28 13:49:59.961775 I | etcdmain: Go OS/Arch: linux/amd64
2016-10-28 13:49:59.962086 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
[...]
```

Again: just reuse the cluster token by re-issuing the command again if your primary error is "context deadline exceeded"). Surprise: it works. Dunno why, but between the "context timeout exceeded" messages and the surprisingly large number of "Gateway timeout" messages I was getting during the cluster bootstrapping, it seems to me that discovery.etcd.io is/was in not quite such a healthy situation. Maybe the servers are overloaded? Who knows...

@xiang90: it would be great if you could leave the mindset "user can't read logs, user is lying about cluster token reuse" behind; not for me, but for the others users who are having trouble setting up etcd. If you do a bit of coding on the side, you'd know that messages aren't neccessarily triggered by what the message says. Bugs and unexpected process states are known to happen, even during log message output... 

Also, if you read the log message closely:
```member "X" has previously registered with discovery service token (https://discovery.etcd.io/Y)```
it says that the member token X has previously registered, not that token Y is being reused. 

So the next time someone claims to not having reused the cluster token, try and give them the benefit of the doubt, ok? Sometimes people do tell the truth from time to time :)

**Comment by sinsharat** [comment]
@sriedel its not that @xiang90 was baised towards proving you wrong. All of our intention was to help you solve the issue. Please don't take it otherwise. We all are open to your opinions and suggestions. Also it may happen that what we deduce from the logs we try to convey to you. If you feel there is something wrong with the logs or which tend to mislead our users we are open to correct it. At the end of the day we strive to make it as informative to our users as possible. @xiang90 what he suggested was right from what he could deduce from the logs. To be honest its very difficult for us to know exactly what you are doing, so what we have is logs to conclude on what you are doing. If you feel something is wrong you are most welcome to point out whats wrong, and we will be happy to correct it. We also want to encourage you to help us in making it even more a better product. So any inputs from your side is valuable to us. So rather than getting into blaming game we would appreciate if you can contribute it into making it a better product. Since its an open source product i think its a responsibility for all its users to help make it better in every aspect. Would be great if you can contribute to it to make it even better than what it is now.
Thank you.
