### ISSUE TITLE
what is used for about ttl in session?

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6736]
What is ttl in session used for? I thought it is the timeout for lock.
But I create a locker by ```concurrency.NewLocker``` with ```concurrency.WithTTL```, and ```Lock```, sleep for some time over the ttl, and create another locker locked on the same key, but it blocked.
Do I understand not correct?

**Comment by heyitsanthony** [comment]
It's a lease wrapper that refreshes a lease until it is closed. It is blocking because the session that holds the lock is still alive and refreshing the underlying lease.

**Comment by YuleiXiao** [comment]
@heyitsanthony ok, it looks I understand not correct. But is there anything to make session release the lock when timeout?

**Comment by YuleiXiao** [comment]
I do not get why we need a session ttl in lock?
What is the scene to use it?

**Comment by heyitsanthony** [comment]
It's a distributed lock-- if there's no TTL / an infinite TTL and the lock holder crashes, the system can't make forward progress because the lock will never be released.

**Comment by YuleiXiao** [comment]
@heyitsanthony Sorry, I am confused now. 
You mean if I set TTL 1s, the lock will be released after 1s?

**Comment by heyitsanthony** [comment]
No. It's for liveness checking. If the lock owner does not refresh its session lease within 1s (e.g., the process crashed), etcd will revoke the lease and the next waiter can claim the lock. If the lock owner keeps refreshing its session lease, it will not lose the lock.

**Comment by YuleiXiao** [comment]
ok, understand it.
