### ISSUE TITLE
Is CreateRevision 0 means key was not exist

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#6740]
I want to do like that if a key is not exist then insert it. So I write txn like below. I put a key-value first, and execute this txn with different value, but I found that ```Succeeded``` is true.

```
resp, err := txn.If(etcd.Compare(etcd.CreateRevision(key), "=", 0)).Then(etcd.OpPut(key, value)).Commit()
if err != nil {
        return err
}

if resp.Succeeded {
        //key not exist
}
```

**Comment by heyitsanthony** [comment]
CreateRev=0 should mean the key doesn't exist. It works for me:
```sh
[anthony@etcd]$ ETCDCTL_API=3 ./bin/etcdctl txn -i
compares:
create("a") = "0"

success requests (get, put, delete):
put "a" "t"

failure requests (get, put, delete):
put "a" "f"

SUCCESS

OK
[anthony@etcd]$ ETCDCTL_API=3 ./bin/etcdctl get a
a
t
[anthony@etcd]$ ETCDCTL_API=3 ./bin/etcdctl txn -i
compares:
create("a") = "0"

success requests (get, put, delete):
put "a" "t"

failure requests (get, put, delete):
put "a" "f"

FAILURE

OK
[anthony@etcd]$ ETCDCTL_API=3 ./bin/etcdctl get a
a
f
```

**Comment by xiang90** [comment]
@heyitsanthony's answer is prefect. I am going to close this.

**Comment by YuleiXiao** [comment]
@heyitsanthony @xiang90 
My code is like this, I run it on yesterday master latest code. I thought ```Succeeded``` should be false, but it was true.
```
s.client.Put(s.client.Ctx(), "test", "world")
s.client.Get(s.client.Ctx(), "test") // I get the key, it is right

txn := s.client.Txn(s.client.Ctx())
resp, err := txn.If(etcd.Compare(etcd.CreateRevision(key), "=", 0)).Then(etcd.OpPut("test", "hello")).Commit()
if err != nil {
        return err
}

// problem is here, it should not be true
if resp.Succeeded {
        return nil
}
```

**Comment by xiang90** [comment]
what is key at line 5?

**Comment by YuleiXiao** [comment]
Sorry, key is "test"

**Comment by xiang90** [comment]
@YuleiXiao Can you reproduce this with a simple go program that can compile? (remove s reference and init the client). I can give it a try to see if it is a problem.

**Comment by YuleiXiao** [comment]
@xiang90 Thanks very much. When I was writing the simple go program, I found the problem. It is my code problem. I close this issue. Thanks again.

**Comment by xiang90** [comment]
no problem.
