### ISSUE TITLE
benchmark and improve watch latency

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6752]
The current watch benchmark doesn't say much about the latency between receiving a put ack and receiving the event; it is mostly focused on measuring watch throughput.

I measured the watch latencies for this case in zetcd/cetcd; zetcd is about 10x slower than zk and cetcd is about 2x slower than consul.

**Comment by xiang90** [comment]
@sinsharat 

Can you help with the benchmark side.

We want:

start ONE watcher

1. do one put (t')
2. record the time when we receive the put response (t0) start time
3. record the time when we receive the watch response (t1) end time
4. the watch latency is (t1-t0)
5. record the latency result

do this N times and print out the result.

Note that 2) actually includes watch processing time.

A fancier way is to run put without watch, find the avg latency. Then run put with watch, find avg latency' = t1-t'. then watch latency is latency' - latency.

See https://github.com/coreos/etcd/blob/master/tools/benchmark/cmd/put.go.

/cc @heyitsanthony Any other suggestions?

**Comment by sinsharat** [comment]
@xiang90 Sure will start working on it today.
Thank you!

**Comment by sinsharat** [comment]
@xiang90 Is there anything else required to be worked on for this?

**Comment by xiang90** [comment]
I am closing this out. This is good enough for now.
