### ISSUE TITLE
3.0.12-v2-mode snapshotting causing timeouts on leader election 

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#6753]
Running a load experiments on 3.0.12 against a v2 data set show leader election issues during snapshots.  

Running the exact same experiment, same gear, on 2.3.7 shows no issues.  

Logs can be obtained here: 
https://drive.google.com/file/d/0Bzq0eFfVveNqdjVlakNXOC1iMnM/view?usp=sharing

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1389804

/cc @wojtek-t @xiang90 @hongchaodeng

**Comment by xiang90** [comment]
@timothysc 

From the log I can see: 


```
Oct 27 16:10:10 svt-e-1 etcd: start to snapshot (applied: 6611212, lastsnap: 6601211)

...

Oct 27 16:10:18 svt-e-1 etcd: sync duration of 4.092797557s, expected less than 1s
```

It seems that the machine experienced with some disk contention issue? Once it starts to write snapshot, other fsync can be pending for 4 seconds and then triggers election.

**Comment by xiang90** [comment]
What is the size of the snapshot? If it is super large, probably you should put dedicated disk for WAL files by specifing wal-dir. I do not think we do anything difference since 2.3.7 about how we write snapshot.

**Comment by xiang90** [comment]
@heyitsanthony Is it possible that the perf regression is caused by how we handle WAL? I think that is the only thing we have changed.

**Comment by heyitsanthony** [comment]
@xiang90 the main difference is the fallocate preallocation / getting rid of O_APPEND, but there should be fewer "meaningful" writes overall since we fixed the buffer stuff. What filesystem is this?

**Comment by timothysc** [comment]
Should be xfs, and same experiment on 2.3.7 did not show this issue. 
/cc @mffiedler

**Comment by mffiedler** [comment]
Confirming data-dir is xfs and it is on its own volume with nothing else on it.   The cluster is running on OpenStack and the volumes are cinder provisioned.   Snapshot size is ~250MB

**Comment by xiang90** [comment]
@mffiedler @timothysc Can you get syscall tracing data for 2.3.7 vs 3.0.x?

**Comment by mffiedler** [comment]
@xiang90 Any special systrace options?   I assume you are looking for a representative sample on both versions under this workload - let me know if it is something else.

**Comment by xiang90** [comment]
@mffiedler 

>  a representative sample on both versions under this workload

Yes. Strace on fsync/fdatasync + timestamp. Thanks!

**Comment by xiang90** [comment]
Oh we also need the etcd log + timestampe. so we can figure out the relationship between strace and etcd behavior. Thanks!

**Comment by mffiedler** [comment]
@xiang90  I have 2.3.7 and 3.0.12 strace and logs.   Note the environment was a bit different and I did see leader changes in both versions.   In this env (AWS) I did not have /var/lib/etcd on its own volume.   It was on rootfs which was on xfs and had ~26GB free.   Let me know if you want another recreate with a separate volume.   This workload (Openshift 3.4/Kube 1.4) does seem to reproduce it pretty reliably.

Logs:  https://drive.google.com/file/d/0B0uTprBii7X4aXhLcnhIQjNodVE/view?usp=sharing  
/cc: @timothysc

**Comment by xiang90** [comment]
> I have 2.3.7 and 3.0.12 strace and logs. Note the environment was a bit different and I did see leader changes in both versions.

The the data is not useful. We need data from evn when 2.3.7 does not trigger election but 3.0.13 does.

**Comment by timothysc** [comment]
@mffiedler the variance on the distribution of snap times is wild.  less then 1 second to > 7 seconds?  

The only thing I can think of is if there is write contention on the VMs.  Could you check to make certain that the etcd nodes are landing on different hypervisors.  An easy way to do this in our environment is to make the instance sizes so large that the eat a whole host.

**Comment by xiang90** [comment]
@timothysc @mffiedler Any update on this? Is this a VM write contention issue?

**Comment by timothysc** [comment]
@xiang90 we have both been OOTO, and are digging into it this week.

**Comment by xiang90** [comment]
@timothysc Update?

**Comment by timothysc** [comment]
We created isolated experiments which have not reproduced, so i would say close for now and if/when we have more details, I'll reopen.
