### ISSUE TITLE
high percentage failures from health endpoint

### ISSUE THREAD

**Issue by jdfless** [coreos/etcd#6756]
We are running a 3 node etcd cluster, version 2.2.5 on Ubuntu 12.04. We have automated health checks that have noticed occasional failures, even when the cluster is in a 'healthy' state. 

To investigate further I ran a loop that continually hit the health endpoint with `curl -sL http://127.0.0.1:4001/health` on the different nodes. Doing this saw between 5-15% failures in 10,000 attempts on each of the nodes. Are there any known issues that could cause this?

Full version info:

```
etcd Version: 2.2.5
Git SHA: bc9ddf2
Go Version: go1.5.3
Go OS/Arch: linux/amd64

$ uname -a
Linux etcd1 3.2.0-60-generic #91-Ubuntu SMP Wed Feb 19 03:54:44 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xiang90** [comment]
Do you have server side logs for the time when health checking fails?

**Comment by jdfless** [comment]
Nothing looks out of the ordinary, when left default at --debug=false, nothing is logged after basic startup info. When I elevate to --debug=true, I just see the health check calls as expected. Below are the logs of 9 calls as seen in their logs and server responses.

Log output:
```2016-10-29 17:28:08.546292 D | etcdhttp: [GET] /health remote:127.0.0.1:47727
2016-10-29 17:28:08.870851 D | etcdhttp: [GET] /health remote:127.0.0.1:47730
2016-10-29 17:28:09.445407 D | etcdhttp: [GET] /health remote:127.0.0.1:47731
2016-10-29 17:28:09.770640 D | etcdhttp: [GET] /health remote:127.0.0.1:47732
2016-10-29 17:28:10.345437 D | etcdhttp: [GET] /health remote:127.0.0.1:47733
2016-10-29 17:28:10.919335 D | etcdhttp: [GET] /health remote:127.0.0.1:47734
2016-10-29 17:28:11.745707 D | etcdhttp: [GET] /health remote:127.0.0.1:47735
2016-10-29 17:28:12.569843 D | etcdhttp: [GET] /health remote:127.0.0.1:47736
2016-10-29 17:28:12.894893 D | etcdhttp: [GET] /health remote:127.0.0.1:47739```

Server response:
```{"health": "true"}
{"health": "true"}
{"health": "true"}
{"health": "true"}
{"health": "true"}
{"health": "false"}
{"health": "false"}
{"health": "true"}
{"health": "true"}```

**Comment by xiang90** [comment]
Is this a 3 node clusters? or just one node? can you provide the log from all servers? are the look the same?

**Comment by jdfless** [comment]
It is a 3 node cluster, I was just running `curl -sL http://127.0.0.1:4001/health` on one node at that time. I do not see any relevant log info on the other nodes while doing that.

When I run `etcdctl cluster-health` (which shows the same error rate per node, but where I haven't seen it return the whole cluster being unhealthy) - each node shows a log like `/health remote:192.168.0.14:42177`, with the ip being that of the host where I am running the etcdctl command from, and the port being different in each nodes log.

**Comment by xiang90** [comment]
There is a possibly related issue: https://github.com/coreos/etcd/pull/4968.

I am not sure about the root cause. The v2 health checking is time based. So it might not be accurate if you run etcd on slow machines. If there is no warning, error logging, I cannot help to debug unless you can reproduce it somehow on a env that we can access (awe, gce for example).

**Comment by jdfless** [comment]
Unfortunately we run on bare metal so not possible to share env. I appreciate you looking into it and I will look at #4968. Good to know about the v2 health checking being time based, is the health checking behavior different on newer versions? I will do some more investigation myself and update here if I find anything.

**Comment by xiang90** [comment]
>  is the health checking behavior different on newer versions? 

For v3, yes. But it is still time based (you will always have the time out there anyway), but it is a better guess.

**Comment by xiang90** [comment]
@jdfless How can we help you more on this one?

**Comment by jdfless** [comment]
Hi @xiang90 thanks for following up! We are testing a fix for this issue by adding more resources to our etcd nodes. I can let you know if that is successful, but it seems the likely issue. Given that, we can close this issue and re-open if we find anything different.

**Comment by xiang90** [comment]
Thanks!
