### ISSUE TITLE
can i buid etcd v3.0.13  by use go 1.7.3, is there any problem?

### ISSUE THREAD

**Issue by junweiyang** [coreos/etcd#6761]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on
[reporting bugs][report_bugs] before you submit your bug report. 

To ask a question, go ahead and ignore this.

[report_bugs]: ../Documentation/reporting_bugs.md

**Comment by xiang90** [comment]
Yes, you can. There is no known problem.
