### ISSUE TITLE
RFE on migrate to eliminate all TTL keys

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#6767]
**Request**
add a flag to migrate which will not convert TTL keys from v2 to v3

**Reason**
Some folks may wish to handle migration of TTL keys in a special fashion (hence custom migration tool), but there is a common pattern of wanting to simply bulk eliminate all TTL keys b/c they are more trouble then their worth.    

/cc @xiang90

**Comment by xiang90** [comment]
@timothysc I am fine with adding a no-ttl flag to migration tool. Do you want to work on this? Should be a simple one. /cc @hongchaodeng

**Comment by timothysc** [comment]
I'll get a PR in the a.m.
