### ISSUE TITLE
Issue: curl query command failed in proxy etcd node while one etcd instance gets hung

### ISSUE THREAD

**Issue by nenzhang** [coreos/etcd#6773]
etcd version:
etcdctl -v
etcdctl version: 3.0.12
API version: 2

configuration: three etcd instances and some etcd proxy node.

test condition: deliver SIGSTOP to one etcd instance which is not leader one.
start curl command with timeout 1second, it will continuously report failure.
curl -L http://127.0.0.1:2379/v2/keys/message -m 1
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received

the normal one:
curl -L http://127.0.0.1:2379/v2/keys/message -m 1
{"action":"get","node":{"key":"/message","value":"Hello world5","modifiedIndex":1334341,"createdIndex":1334341}}

when changed the IP from localhost to one which etcd instance works, then it is ok.
so I think the previous failure request from proxy has been delivered to the hung etcd instance and lead to timeout, while the internal connection is not broken yet.

two query questions:
1) whether the etcd has implemented the systemd watchdog function?
2) In this kind of failure case, whether etcd proxy has internal supervision mechanism to mark this hung etcd instance with temporately failure and deliver the request to normal one?

healthy check will also block when check the hung instance:
etcdctl cluster-health
member 2a7afdac888925e7 is healthy: got healthy result from http://169.254.0.27:2379
member 515c09e3f49d58cf is healthy: got healthy result from http://169.254.0.23:2379
-->blocks here.

the operation in other etcd instance node won't be problem for query and set commands, so looks when operates in instance nodes, it won't do sync before return back the request.

**Comment by xiang90** [comment]
> when changed the IP from localhost to one which etcd instance works, then it is ok.
so I think the previous failure request from proxy has been delivered to the hung etcd instance and lead to timeout, while the internal connection is not broken yet.

Do you have log from the proxy?

**Comment by nenzhang** [comment]
Hi Xiang
see operation steps and logs:
1. tail the log in proxy node:
journalctl -f |grep -i etcd >etcd.log

2. deliver SIGSTOP to one etcd instance, its pid is 23059 in another VM node. 
kill -19 23059

3. check the query CURL operations:
# curl -L http://127.0.0.1:2379/v2/keys/message -m 1
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received
# curl -L http://127.0.0.1:2379/v2/keys/message -m 1
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received

4. I can only see these logs from etcd proxy, is exist any method to configure some options to enable more logs?
Nov 02 14:17:57 etcd[2433]: client 127.0.0.1:59626 closed request prematurely
Nov 02 14:18:00 etcd[2433]: client 127.0.0.1:59627 closed request prematurely


Notes:
Sometimes the request will be succeed even the etcd instance is still hung there. not be permanent failure.
curl -L http://127.0.0.1:2379/v2/keys/message -m 1
{"action":"get","node":{"key":"/message","value":"Hello world5","modifiedIndex":1334341,"createdIndex":1334341}}

Also, it prints this continuously when I make previous etcd instance up, and another etcd instance hung, but not leader either.
----------------------------
Nov 02 14:28:05 etcd[2433]: could not get cluster response from http://169                                                                      .254.0.23:2380: Get http://169.254.0.23:2380/members: net/http: request canceled                                                                       (Client.Timeout exceeded while awaiting headers)
..
Nov 02 14:30:05 etcd[2433]: could not get cluster response from http://169.254.0.23:2380: Get http://169.254.0.23:2380/members: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Nov 02 14:30:45 etcd[2433]: could not get cluster response from http://169.254.0.23:2380: Get http://169.254.0.23:2380/members: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Nov 02 14:31:25 etcd[2433]: could not get cluster response from http://169.254.0.23:2380: Get http://169.254.0.23:2380/members: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by xiang90** [comment]
> deliver SIGSTOP to one etcd instance, its pid is 23059 in another VM node. 
kill -19 23059

This is wrong way to simulate a process failure. Basically you try to simulate high GC pause. The network layer is still buffering up packets. Try to SIGKILL etcd instead.

**Comment by xiang90** [comment]
@nenzhang I do not think this is high priority for us. If you want to get this fix, you can add timeout to proxy at https://github.com/coreos/etcd/blob/master/proxy/httpproxy/reverse.go#L139.

**Comment by nenzhang** [comment]
Hi Xiang
thanks.
 so you mean the etcd will be realible that it won't be hung forever? I don't think so, we shall cover and handle the problem in any situation.

If you want to get this fix, you can add timeout to proxy at https://github.com/coreos/etcd/blob/master/proxy/httpproxy/reverse.go#L139.
-> do you mean I add own local change for this? do etcd have plan to implement systemd watchdog function inside.

**Comment by xiang90** [comment]
What situation are you trying to simulate? Why do you want to send SIGSTOP to etcd?

It has nothing to do with watchdog or etcdserver itself. If you want the proxy to be able to fail fast, you can send a patch to upstream to add timeout.

**Comment by nenzhang** [comment]
Hi Xiang
SIGSTOP used to simulate the current etcd instance gets hung in some code place, or deadlock..etc.
so watchdog can detect this and configure recover action to make it automatic recovery from hung.

 If you want the proxy to be able to fail fast, you can send a patch to upstream to add timeout.
--> in fact when etcd instance gets hung, I want the function continue works in proxy node, but not failed continuously. I mean one instance has problem, and still have two instances including leader, it shall better not impact the proxy function .

Thanks.

**Comment by xiang90** [comment]
> SIGSTOP used to simulate the current etcd instance gets hung in some code place, or deadlock..etc.

You can do health checking against etcd with health checking API. Then you kill etcd. Everything should work again. I do not think we need to anything more inside etcd.

> in fact when etcd instance gets hung, I want the function continue works in proxy node,

As I said, the proxy still can connect to the etcd server since you just SIGSTOP it. The network stack still works. You need to add timeout to proxy to terminate the current connection and proxy will mark that endpoint as unhealthy.

**Comment by xiang90** [comment]
All you need to do now is to find a way to terminate the SIGSTOP etcd. You need to write your own health checking program on your node to do it if you feel it is necessary. We do health checking by simply using etcdctl and kill etcd if it is not responsive within X seconds.

**Comment by nenzhang** [comment]
Hi Xiang
we have this, and now we have same mechanism in etcd proxy node and this problem etcd instance node, then the recovery will happen in proxy node also which trouble us.
The only workaround for us is to change the health checking tolerance, for example, it is smaller in instance node, and bigger in proxy node.
