### ISSUE TITLE
etcd2 removing and adding member to live cluster 

### ISSUE THREAD

**Issue by darktall** [coreos/etcd#6776]
Hi guys I tried to add node to live etcd2 cluster . The node is configured in coreos/ user_data file  which is static.
I removed failed node from etcd2 master 
Fixed that node and tried to add again to live server following coreos documentation. 
In node i completely removed  data-dir  var/lib/etcd2/* files 
rebooted machine and started etcd2. It is up and running .  From node  flowing is the  log
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URL
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_INITIAL_CLUSTER=master=htt
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=core
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://10
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: recognized and used environment variable ETCD_NAME=worker03
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: etcd Version: 2.3.2
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: Git SHA: ce63f10
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: Go Version: go1.5.4
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: Go OS/Arch: linux/amd64
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: setting maximum number of CPUs to 8, total number of available CPUs is 8
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: the server is already initialized as member before, starting as etcd mem
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: listening for peers on http://10.98.8.97:2380
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: listening for client requests on http://0.0.0.0:2379
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: name = worker03
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: data dir = /var/lib/etcd2
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: member dir = /var/lib/etcd2/member
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: heartbeat = 100ms
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: election = 1000ms
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: snapshot count = 10000
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: advertise client URLs = http://10.98.8.97:2379
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: restarting member ce2a822cea30bfca in cluster 7e27652122e8b2ae at commit
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: ce2a822cea30bfca became follower at term 2
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: newRaft ce2a822cea30bfca [peers: [], term: 2, commit: 735, applied: 0, l
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: starting server... [version: 2.3.2, cluster version: to_be_decided]
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com systemd[1]: Started etcd2.
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: added local member ce2a822cea30bfca [http://localhost:2380 http://localh
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: set the initial cluster version to 2.3
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:40 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)
Nov 01 11:29:41 zhdev1-kubeworker03.bo3.e-dialog.com etcd2[1484]: request cluster ID mismatch (got 141fc2e6c70d61fc want 7e27652122e8b2ae)

from server side 
Nov 01 11:54:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:54:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:55:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: rejected the stream from peer 6927d3f5a16eba8f since it was removed
Nov 01 11:55:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: rejected the stream from peer 6927d3f5a16eba8f since it was removed
Nov 01 11:55:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 12:10:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: start to snapshot (applied: 29831334, lastsnap: 29821333)
Nov 01 12:10:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: saved snapshot at index 29831334
Nov 01 12:10:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: compacted raft log at 29826334
Nov 01 12:10:30 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: purged file /var/lib/etcd2/member/snap/000000000000172d-0000000001c66d51.s
Nov 01 12:13:17 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: removed member dbccc63e6a66bd9f from cluster 141fc2e6c70d61fc
...skipping...
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:26 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:27 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: request sent was ignored (cluster ID mismatch: remote[dbccc63e6a66bd9f]=7e
Nov 01 11:48:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:49:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:49:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:50:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:50:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:51:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:51:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:52:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:52:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:53:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:53:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:54:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:54:48 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 11:55:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: rejected the stream from peer 6927d3f5a16eba8f since it was removed
Nov 01 11:55:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: rejected the stream from peer 6927d3f5a16eba8f since it was removed
Nov 01 11:55:18 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: the connection to peer dbccc63e6a66bd9f is unhealthy
Nov 01 12:10:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: start to snapshot (applied: 29831334, lastsnap: 29821333)
Nov 01 12:10:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: saved snapshot at index 29831334
Nov 01 12:10:14 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: compacted raft log at 29826334
Nov 01 12:10:30 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: purged file /var/lib/etcd2/member/snap/000000000000172d-0000000001c66d51.s
Nov 01 12:13:17 zhdev1-kubemaster.bo3.e-dialog.com etcd2[1501]: removed member dbccc63e6a66bd9f from cluster 141fc2e6c70d61fc

Is their any way i can add node to live etcd2 cluster ?

**Comment by gyuho** [comment]
You can follow instructions here https://github.com/coreos/etcd/blob/master/Documentation/v2/runtime-configuration.md#add-a-new-member.

**Comment by gyuho** [comment]
Closing. Please let us know if you have more questions. Thanks.

**Comment by darktall** [comment]
as per documentation i followed  below are my steps 

zhdev1-kubemaster ~ # etcdctl member add worker03 http://10.98.8.97:2380
Added member named worker03 with ID 759e3253607c0812 to cluster

ETCD_NAME="worker03"
ETCD_INITIAL_CLUSTER="worker03=http://10.98.8.97:2380,master=http://10.98.8.94:2380,worker01=http://10.98.8.95:2380,worker02=http://10.98.8.96:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"
zhdev1-kubemaster ~ # export ETCD_NAME="worker03"
zhdev1-kubemaster ~ # export ETCD_INITIAL_CLUSTER="worker03=http://10.98.8.97:2380,master=http://10.98.8.94:2380,worker01=http://10.98.8.95:2380,worker02=http://10.98.8.96:2380"
zhdev1-kubemaster ~ # export ETCD_INITIAL_CLUSTER_STATE=existing
zhdev1-kubemaster ~ # etcd -listen-client-urls http://10.98.8.97:2379 -advertise-client-urls http://10.98.8.97:2379 -listen-peer-urls http://10.98.8.97:2380 -initial-advertise-peer-urls http://10.98.8.97:2380 -data-dir %data_dir%
etcd

still i am getting   flag provided but not defined: -listen-client-urls error. How to solver this.
