### ISSUE TITLE
/registry is not deleted when 'rpm -e etcd' and then 'rpm -i etcd'

### ISSUE THREAD

**Issue by tonyclam** [coreos/etcd#6783]
# Bug reporting
We create a key /registry. When we delete the etcd 'rpm -e' and then 'rpm -i', the /registry still exists. It should be deleted.
[root@localhost ~]# systemctl start etcd
[root@localhost ~]# etcdctl ls /registry/minions
/registry/minions/localhost.localdomain
[root@localhost ~]# rpm -e etcd
[root@localhost ~]# rpm -i etcd-3.0.10-1.0.1.dev.el7.x86_64.rpm
[root@localhost ~]# systemctl start etcd
[root@localhost ~]# etcdctl ls /registry/minions
/registry/minions/localhost.localdomain

A good bug report has some very specific qualities, so please read over our short document on
[reporting bugs][report_bugs] before you submit your bug report. 

To ask a question, go ahead and ignore this.

[report_bugs]: ../Documentation/reporting_bugs.md

**Comment by xiang90** [comment]
This is not an etcd issue. You should report to rpm maintainer mailing list.

**Comment by tonyclam** [comment]
thx for reply, Would you please let me know the link to file bug on rpm maintainer
