### ISSUE TITLE
introduce heartbeat on watch api response

### ISSUE THREAD

**Issue by chulkilee** [coreos/etcd#6810]
### Background

* watch api keeps HTTP connection open
* load balancer may closes idle connection - example: Amazon ELB ([ref](http://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html))

### Problem

When it happens, etcd client currently does not handle nicely - it just raises "etcd cluster is unavailable or misconfigured" error, which breaks clients calling the watch api. Example: coreos/flannel#528

### Proposal: introduce no-op heartbeat message

If etcd produces no-op heart beat message on idle watch api connection, this can be solved.

I don't know the current api spec and client code is flexible so that we can add no-op message without breaking existing clients.

### Alternative: let client retry with maximum retries

This is sub-optimal, since it is not possible for client to tell why the connection is closed.

**Comment by xiang90** [comment]
@chulkilee 

There is already something better than "heartbeat" exists for v3 API see: https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L604. It heartbeats and tells the watcher its progress in case of no interested events.

We do not plan to change v2 API. It is frozen.

**Comment by chulkilee** [comment]
@xiang90 Thanks for the info!
