### ISSUE TITLE
Error while installing clientv3

### ISSUE THREAD

**Issue by charlie** [coreos/etcd#6813]
I can't seem to install clientv3. Am I doing something wrong wrt version/dependency management?

    /usr/bin # go get github.com/coreos/etcd/clientv3
    # github.com/coreos/etcd/etcdserver/etcdserverpb
    /gopath/src/github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:2162: undefined: grpc.SupportPackageIsVersion3

Perhaps it's because of [this change to grpc/grpc-go](https://github.com/grpc/grpc-go/commit/727a60e4d135c53c4d62d708ac4528f7c077c0d0#diff-9d9af2a19a6c9f88d8535aa95b1f9c22)?

**Comment by heyitsanthony** [comment]
@charlie if you're using clientv3 with go-grpc's master branch (e.g., via go get), this will occasionally happen because go-grpc may merge in an breaking update. The best workaround is to vendor the grpc dependency in your project using the version vendored by etcd.

**Comment by charlie** [comment]
@heyitsanthony Got it -- thanks for letting me know what to expect & how to avoid. Closing this...

**Comment by heyitsanthony** [comment]
Reopening this to track updating the grpc dependency in etcd.

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/6832
