### ISSUE TITLE
is quorum read deprecated in etcd v3?

### ISSUE THREAD

**Issue by sandflee** [coreos/etcd#6829]
when a write/update op finished, we want to read the newest value for etcd immediately.
we could set quorum read option in etcd v2 client, but seems no way to set in etcd v3 client. is there any other way to do this, or is deprecated?

**Comment by heyitsanthony** [comment]
It's enabled by default. To get stale reads use `clientv3.WithSerialize()`.

**Comment by sandflee** [comment]
thanks @heyitsanthony !

**Comment by necro351** [comment]
It wasn't obvious from google searches and I wanted to note this here as this is where I found my answer (and maybe Google will index it better now). If you want to read from etcd when you are a node in the minority after a network partition, you will get this warning by default:

`etcdserver: timed out waiting for read index response`

...and your read will fail. If you don't mind getting stale read results, you can use WithSerializable and still read, even when your node is a member of the minority.

**Comment by fanminshi** [comment]
@xiang90 should we add this in faq?

**Comment by xiang90** [comment]
@heyitsanthony Add a faq about read consistency?
