### ISSUE TITLE
raft: use ReadOnlyOption dynamically? 

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#6845]
Hi @xiang90 

Now the ReadOnlyOption is fixed when starting Raft, can we switch it dynamically?

E.g, for most of the cases, we use LeaseBased configuration, but for sometime, when the leader thinks it is not safe to supply lease based read, it can use Safe configuration. 

I know that we can use raft log read instead of ReadIndex to ensure safety, but it is better that we can use ReadIndex for all read. 

If you think it is ok, we can try to support it. 

/cc @hhkbp2

**Comment by xiang90** [comment]
This complicates the implementation. In our testing, the benefit lease based brings is not significant (etcd mainly targets at single dc deployment though) and does not worth the risk. I would like to know how much benefits it can bring to you and what is your use case.

>  when the leader thinks it is not safe to supply lease based read,

How do you determine that?

**Comment by siddontang** [comment]
> How do you determine that?

We have not figured out a way to check it now. see https://github.com/pingcap/tikv/pull/1301

> the benefit lease based brings is not significant 

Could you show some benchmark results? Btw, we will do our own benchmark too.

**Comment by xiang90** [comment]
> We have not figured out a way to check it now. 

OK. I think we should first try to justify this is a useful feature. Basically, we need to show that dynamically change the options is useful before we add into our raft library.

**Comment by xiang90** [comment]
@siddontang Any update?

**Comment by siddontang** [comment]
No update @xiang90 :sob: 

I have already told @swingbach , he will see it later.

**Comment by xiang90** [comment]
@siddontang Do you still want this feature?

**Comment by siddontang** [comment]
Hi @xiang90 

We don't need this feature now, if we have, we will send you a PR.
