### ISSUE TITLE
etcd nodes have different modifiedIndex

### ISSUE THREAD

**Issue by ringtail** [coreos/etcd#6847]
I have a three nodes cluster and I found the same key path has different modifiedIndex on different servers.Are they working well?

**Comment by heyitsanthony** [comment]
@ringtail how are you reading from the cluster? If it's not a quorum / linearized read, some members may return stale data.

**Comment by ringtail** [comment]
It should be equal finally?

**Comment by heyitsanthony** [comment]
@ringtail provided the cluster is healthy, the update will eventually propagate to every server
