### ISSUE TITLE
v3api: detach lease from a key

### ISSUE THREAD

**Issue by louis-paul** [coreos/etcd#6848]
Is there a way to dissociate a key from its lease without removing it? My use-case is to save temporary data (with a lease) and keep it (i.e. detach the lease) when needed.

**Comment by xiang90** [comment]
Yes. Update the key without empty lease ID.

**Comment by louis-paul** [comment]
So with the Go client, that would be done with a `Put` with the key and its value, without passing a lease ID?

Letting a client remove a lease from a key without sending its value again could be a valuable feature.

**Comment by xiang90** [comment]
@louis-paul Sounds a reasonable feature to add. /cc @heyitsanthony

**Comment by heyitsanthony** [comment]
It's been requested before. Fix would probably be something like a `PreserveValue bool` in the Put RPC
