### ISSUE TITLE
Minor update is needed for Mac OS(Darwin) installation instruction in Releases page

### ISSUE THREAD

**Issue by leonliao** [coreos/etcd#6853]
In link https://github.com/coreos/etcd/releases/, the section describing the installation on Mac OS needs to be updated.  Following that, the `etcd` binary is not at  `/tmp/test-etcd`, but at ` /tmp/test-etcd/etcd-${ETCD_VER}-darwin-amd64`

The original
 `mkdir -p /tmp/test-etcd && unzip /tmp/etcd-${ETCD_VER}-darwin-amd64.zip -d /tmp && mv /tmp/etcd-${ETCD_VER}-darwin-amd64 /tmp/test-etcd` 

should be updated to 

 `mkdir -p /tmp/test-etcd && unzip /tmp/etcd-${ETCD_VER}-darwin-amd64.zip -d /tmp && mv /tmp/etcd-${ETCD_VER}-darwin-amd64/* /tmp/test-etcd` 

Adding /* at the source  in last `mv` statement.

**Comment by gyuho** [comment]
Just fixed. Thanks!
