### ISSUE TITLE
raft: node.Status method might block after Stop()

### ISSUE THREAD

**Issue by LK4D4** [coreos/etcd#6855]
I see that other methods have `n.done` checks to avoid deadlocks(i.e. 
https://github.com/coreos/etcd/blob/master/raft/node.go#L472), but Status method will block until it gets an answer. I wonder if it makes sense to just return empty `Status` struct in the case of closed `n.done` channel. It will prevent deadlocks, and people can check if `ID == raft.None` to know if the status is valid.
WDYT?
Thanks!

**Comment by xiang90** [comment]
@LK4D4 SGTM. Can you send a patch to fix this?

**Comment by LK4D4** [comment]
@xiang90 sure, will do right now. Thanks for feedback.
