### ISSUE TITLE
embed: Support running etcd as proxy

### ISSUE THREAD

**Issue by prashanthpai** [coreos/etcd#6859]
Currently, an embedded etcd can be only run in normal server mode and not as a [proxy](https://coreos.com/etcd/docs/latest/proxy.html).

The structures `embed.Config` and `etcdserver.ServerConfig` do not contain any proxy related fields.

**Comment by xiang90** [comment]
The v2 HTTP proxy is a standalone thing on its own. See https://github.com/coreos/etcd/tree/master/proxy/httpproxy. You can start embed in your project like etcd main does.
