### ISSUE TITLE
etcd-tester: fail to retrive max rev

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd#6863]
Setup:
OS X 10.11.6
Macbook pro 15
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/fanminshi/work"
GOROOT="/usr/local/Cellar/go/1.7.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.7.3/libexec/pkg/tool/darwin_amd64"

When I change the grpc connection with maxbackoff set to 1 in lease stresser(https://github.com/coreos/etcd/blob/master/tools/functional-tester/etcd-tester/lease_stresser.go#L117) to
`conn, err := grpc.Dial(ls.endpoint, grpc.WithInsecure(), grpc.WithBackoffMaxDelay(1))`

the functional tester fails with following error
`11:33:12 stresser | 2016-11-16 11:33:12.039275 W | etcd-tester: [round#0 case#4] functional-tester returning with error (injection error: cluster too slow: only commit -7720 requests in 30s)`

**Comment by xiang90** [comment]
@fanminshi 

> conn, err := grpc.Dial(ls.endpoint, grpc.WithInsecure(), grpc.WithBackoffMaxDelay(1))

This should only affect lease client, right? But somehow the client maxRev created is affected. There should be some lower layer resources that shared by both lease client and maxRev get affected.

**Comment by xiang90** [comment]
@fanminshi 

Even if I do not change the grpc.Dial line, the same problem can occur on current master. So it is irrelevant.

**Comment by xiang90** [comment]
I found the root cause. will send a pr to fix soon.

**Comment by fanminshi** [comment]
should be fixed by https://github.com/coreos/etcd/pull/6877 and https://github.com/coreos/etcd/pull/6867
