### ISSUE TITLE
i can't config the etcd by using the command flag

### ISSUE THREAD

**Issue by TUTUBIG** [coreos/etcd#6865]
![image](https://cloud.githubusercontent.com/assets/13084076/20375673/9205c958-acbb-11e6-8e7c-e7dd8f98b418.png)

**Comment by xiang90** [comment]
I do not understand you question. Can you elaborate? Also can you paste the text instead of using screenshots?

**Comment by TUTUBIG** [comment]
@xiang90  i want to set the listen-client-url to be 'http://0.0.0.0:2379' , but something seems to be wrong   
my command  `./etcd --listen-client-urls 'http://0.0.0.0:2379'` and the terminal gives the response
`2016-11-17 11:46:34.328536 E | etcdmain: error verifying flags, --advertise-client-urls is required when --listen-client-urls is set explicitly. See 'etcd --help'.`
`2016-11-17 11:46:34.328672 E | etcdmain: When listening on specific address(es), this etcd process must advertise accessible url(s) to each connected client.   
what's wrong ?
`

**Comment by TUTUBIG** [comment]
@xiang90   are you a chinese people ？

**Comment by heyitsanthony** [comment]
`./etcd --listen-client-urls 'http://0.0.0.0:2379' --advertise-client-urls='http://localhost:2379'` will work if you're not worried about configuring it correctly
