### ISSUE TITLE
v3/keys: add store stats

### ISSUE THREAD

**Issue by bmizerany** [coreos/etcd#687]
- [ ] Key Count
- [ ] Directory Count
- [ ] TTL Key Count

**Comment by philips** [comment]
Where should we add this? Are we going to put it into the metrics endpoint? So something like:

```
etcdstore_v2_key_count
etcdstore_v2_dir_count
etcdstore_v2_ttl_key_count
```

We also have the `/v2/stats/store` endpoint but that has counters on operations at the moment.

**Comment by xiang90** [comment]
This is for v3 api. see the label.

**Comment by philips** [comment]
@xiang90 I added a v3api label, the release milestone just says when we plan to make it happen.

**Comment by philips** [comment]
@xiang90 Is the plan to add it to the metrics endpoint though?

**Comment by xiang90** [comment]
@philips Yes we plan to.

**Comment by philips** [comment]
@xiang90 then why is this part of the v3api?

**Comment by xiang90** [comment]
@philips This is a separate problem. What I am saying is this issue was for v3, not for v2 api from the very beginning. 

If we want to add more stats into v2 stats, we need to create another issue for that.

**Comment by philips** [comment]
@xiang90 so this will be a `v3/stats` endpoint? This issue just doesn't have enough information for someone to know what it is about.
