### ISSUE TITLE
support for non-x86 ? 

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#6871]
Allow support for non-x86 arches where golang is supported. 

Do you have any official policy on this?

**Comment by xiang90** [comment]
@timothysc 

Yes. https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md

I know people are working on arm64 and ppc64le

**Comment by timothysc** [comment]
Should it be marked as unsupported then?  xref: https://bugzilla.redhat.com/show_bug.cgi?id=1396463

**Comment by xiang90** [comment]
@timothysc We only mark supported since we only support amd64, all others are unsupported. Once we support the majority, we will do the opposite...

**Comment by xiang90** [comment]
It seems the questions is addressed. I am closing this out. Reopen if you have any followup questions.

**Comment by houstar** [comment]
Error log in ppc64le. golang is currently supported on ppc64le. so I think we should strict/limited support x86/amd64 only. I strongly suggest that we should enable other platform to embrace the CoreOS eco-system.  Now we're testing the CoreOS@ppc64le platform.

core@CoreOS ~ $ cat /etc/os-release 
NAME=CoreOS
ID=coreos
VERSION=1248.0.0
VERSION_ID=1248.0.0
BUILD_ID=2017-01-06-1749
PRETTY_NAME="CoreOS 1248.0.0 (Ladybug)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
core@CoreOS ~ $ uname -a
Linux CoreOS 4.9.0-coreos #1 SMP Thu Dec 29 06:43:17 2016 ppc64le POWER8E (raw), altivec supported CHRP IBM pSeries (emulated by qemu) GNU/Linux

Attached the ppc64le log in the following.

Jan 06 19:10:40 CoreOS systemd[1]: etcd2.service: Service hold-off time over, scheduling restart.
Jan 06 19:10:40 CoreOS systemd[1]: Stopped etcd2.
-- Subject: Unit etcd2.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd2.service has finished shutting down.
Jan 06 19:10:40 CoreOS systemd[1]: Starting etcd2...
-- Subject: Unit etcd2.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd2.service has begun starting up.
Jan 06 19:10:40 CoreOS etcd2[3830]: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=ppc64le set.
Jan 06 19:10:40 CoreOS systemd[1]: etcd2.service: Main process exited, code=exited, status=1/FAILURE
Jan 06 19:10:40 CoreOS systemd[1]: Failed to start etcd2.
-- Subject: Unit etcd2.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit etcd2.service has failed.
-- 
-- The result is failed.
Jan 06 19:10:40 CoreOS systemd[1]: etcd2.service: Unit entered failed state.
Jan 06 19:10:40 CoreOS systemd[1]: etcd2.service: Failed with result 'exit-code'.

**Comment by houstar** [comment]
@marineam @xiang90  Could we support etcd on ppc64le platform ?  As you known, we've enabled CoreOS @ppc64le platform. And etcd is the infrastructure for CoreOS...Sooooooo... thanks

**Comment by heyitsanthony** [comment]
@houstar set the environment variable ETCD_UNSUPPORTED_ARCH=1 to run on an unsupported architecture. This flag won't go away until there's ppc64le CI; the platform is not well tested and so running etcd is risky. See https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md#supporting-a-new-platform

**Comment by houstar** [comment]
Thanks @heyitsanthony, so i'll take the responsibility of testing etcd on ppc64le. Once is stable enough. then i'll inform here ;-0
