### ISSUE TITLE
pipeline's sending buffer is full and failed to write d8343e712cfcb068 on stream MsgApp v2 ( i/o timeout) are to manny

### ISSUE THREAD

**Issue by ringtail** [coreos/etcd#6874]
I have a three nodes etcd cluster. And every few minutes.I'll get the message write timeout or send buffer is full. How can I reduce the problem.

**Comment by ringtail** [comment]
here is my cluster configuration: 

```
 /usr/aliyun/acs/etcd/etcd -name etcd3 --election-timeout=20000  --heartbeat-interval=1000 --snapshot-count=20000        --cos-cert-enable=true         -client-cert-auth         -trusted-ca-file=/var/etcd/certs/ca.pem         -cert-file=/var/etcd/certs/cert.pem         -key-file=/var/etcd/certs/key.pem         -advertise-client-urls https://ip:2379         -listen-client-urls https://0.0.0.0:2379         -initial-advertise-peer-urls http://:ip2380         -listen-peer-urls http://0.0.0.0:2380         -initial-cluster-token discovery-service-cluster         -initial-cluster etcd1=http://ip:2380,etcd2=http://ip:2380,etcd3=http://ip:2380         -initial-cluster-state new -data-dir=/data
```

**Comment by ringtail** [comment]
could I set a large num to  pipeline's sending buffer?

**Comment by xiang90** [comment]
Version of etcd server? full etcd server log?

**Comment by ringtail** [comment]
etcd 2.2.2

**Comment by ringtail** [comment]
16年11月19日
15时05分25秒

10.117.57.38
msg: I | rafthttp: the connection with 41f6d0b080755051 became inactive
time:2016-11-19 15:05:25.567568
16年11月19日
15时05分25秒

10.117.57.38
msg: E | rafthttp: failed to read 41f6d0b080755051 on stream MsgApp v2 (read tcp 10.117.57.38:35866->10.132.2.217:2380: i/o timeout)
time:2016-11-19 15:05:25.567638
16年11月19日
15时05分25秒

10.117.57.38
msg: I | rafthttp: the connection with 41f6d0b080755051 became active
time:2016-11-19 15:05:25.671998
16年11月19日
15时05分26秒

10.117.57.38
msg: I | raft: c8a56505a1f35cad [commit: 72745104784, lastindex: 72745104784, lastterm: 22281] starts to restore snapshot [index: 72745119340, term: 22281]
time:2016-11-19 15:05:26.070972
16年11月19日
15时05分26秒

10.117.57.38
msg: I | raft: log [committed=72745104784, applied=72745104784, unstable.offset=72745104785, len(unstable.Entries)=0] starts to restore snapshot [index: 72745119340, term: 22281]
time:2016-11-19 15:05:26.071017
16年11月19日
15时05分26秒

10.117.57.38
msg: I | raft: c8a56505a1f35cad restored progress of 41f6d0b080755051 [next = 72745119341, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
time:2016-11-19 15:05:26.071086
16年11月19日
15时05分26秒

10.117.57.38
msg: I | raft: c8a56505a1f35cad restored progress of c8a56505a1f35cad [next = 72745119341, match = 72745119340, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
time:2016-11-19 15:05:26.071100
16年11月19日
15时05分26秒

10.117.57.38
msg: I | raft: c8a56505a1f35cad restored progress of d8343e712cfcb068 [next = 72745119341, match = 0, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
time:2016-11-19 15:05:26.071118
16年11月19日
15时05分26秒

10.117.57.38
msg: I | raft: c8a56505a1f35cad [commit: 72745104784] restored snapshot [index: 72745119340, term: 22281]
time:2016-11-19 15:05:26.071128

16年11月19日
15时05分26秒

10.117.57.38
msg: I | etcdserver: raft applied incoming snapshot at index 72745119340
time:2016-11-19 15:05:26.248248
16年11月19日
15时05分27秒

10.117.57.38
msg: I | rafthttp: the connection with 41f6d0b080755051 became inactive
time:2016-11-19 15:05:27.186705
16年11月19日
15时05分27秒

10.117.57.38
msg: E | rafthttp: failed to read 41f6d0b080755051 on stream MsgApp v2 (net/http: request canceled)
time:2016-11-19 15:05:27.187168
16年11月19日
15时05分27秒

10.117.57.38
msg: I | rafthttp: the connection with d8343e712cfcb068 became inactive
time:2016-11-19 15:05:27.188710
16年11月19日
15时05分27秒

10.117.57.38
msg: E | rafthttp: failed to read d8343e712cfcb068 on stream MsgApp v2 (net/http: request canceled)
time:2016-11-19 15:05:27.188984
16年11月19日
15时05分27秒

10.117.57.38
msg: E | rafthttp: failed to read d8343e712cfcb068 on stream Message (net/http: request canceled)
time:2016-11-19 15:05:27.189114
16年11月19日
15时05分27秒

10.117.57.38
msg: I | etcdserver: recovered from incoming snapshot at index 72745119340
time:2016-11-19 15:05:27.193007
16年11月19日
15时05分27秒

10.117.57.38
msg: I | rafthttp: the connection with 41f6d0b080755051 became active
time:2016-11-19 15:05:27.195596
16年11月19日
15时05分27秒

10.117.57.38
msg: I | rafthttp: the connection with d8343e712cfcb068 became active
time:2016-11-19 15:05:27.198976
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266337

16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266378
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266391
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266404
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266417
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266426
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266439
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266451
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266465
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266483
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266497

16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266513
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266553
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266582
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266592
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266607
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266621
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266630
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266646
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266672
16年11月19日
15时05分27秒

10.117.57.38
msg: W | rafthttp: dropped MsgAppResp to 41f6d0b080755051 since pipeline's sending buffer is full
time:2016-11-19 15:05:27.266687

......

then the connection is active and recover

**Comment by ringtail** [comment]
I can reduce the error by adjust the value of pipeline buffer size and receive channel buffer size. But some times I still get list that "E | rafthttp: failed to write d8343e712cfcb068 on stream MsgApp v2 (write tcp ip:2380->ip:43724: i/o timeout)" .I would like to know is it a warning not a error?

**Comment by xiang90** [comment]
Try with etcd 2.3.7. We fixed a few transport related issues.

**Comment by ringtail** [comment]
I am going to merge code from etcd3.0.14，Is etcd2.3.7 is a better choice ?
