### ISSUE TITLE
upgrade from etcd2.2.2 to etcd3.0.9 modifiedIndex is different between nodes

### ISSUE THREAD

**Issue by ringtail** [coreos/etcd#6882]
After upgrade from 2.2.2 to 3.0.9. I found some keys is not consistency because the modifiedIndex is different. on one node the value is 97889699 on the other node is 96885367.

**Comment by ringtail** [comment]
I am really confused about the behavior.I can't figure out where should be the point.

**Comment by ringtail** [comment]
anyone can help me ?

**Comment by gyuho** [comment]
I just tried simple migration from 2.2.2 to 3.0.9 with only v2 keys. And modified indexes look all correct.

How did you migrate your cluster?

Do you have an easy way to reproduce this?

**Comment by ringtail** [comment]
I just restart cluster with new version etcd  and I found some time the X-ETCD-INDEX is different between nodes. If I recover a node, I will work correctly.

**Comment by gyuho** [comment]
Did you use `migrate` command to transfer v2 keys to v3 store? Or just rolling upgrade by replacing the etcd binary files? Providing an easy way to reproduce this would be helpful. Thanks!

**Comment by ringtail** [comment]
And I found etcdv3.0.13 v2 api performance is not as well as before. we use docker swarm and I can't create 7 overlay network containers one second with etcd2.2.2 but I can only create 2.6 overlay network containers one second with etcd3.0.13 with v2 api.

**Comment by ringtail** [comment]
@gyuho I just rolling upgrade with replacing the etcd binary.

**Comment by ringtail** [comment]
@gyuho I don't want to use v3 api.I just want to use v2 api with etcd3.0.13

**Comment by gyuho** [comment]
User-facing v2 API stays the same and we did not change any underline implementation in v2, so the performance should be same. If you can reproduce the regression in v2 API in v3.0.x, please create a separate issue.

And could you provide a simple script to reproduce that index issue?

It should be reproducible from fresh cluster for us to debug, and I couldn't reproduce.

Thanks!

**Comment by ringtail** [comment]
@gyuho I can't reproduce the case. But the scenario is the slave node etcd x-etcd-index is much large than the leader and if you modify a key and the modifiedIndex will increase in the leader and in the slave but they are different. I just remove the node and add the node back to de cluster.And It works well. I don't konw how to reproduce it but I think It shoud be caused by upgrading.

**Comment by gyuho** [comment]
Ok I will try again to reproduce it. Thanks.

**Comment by ringtail** [comment]
@gyuho I have some more information.The cluster is a 3 nodes cluster. It is in heavy load.

**Comment by xiang90** [comment]
@ringtail 

For index mismatch, we need a reproduce. index can be messed up with misconfiguration or bugs in etcd 2.2 releases. And these issues are all fixed by now. I am not sure what is your issue without a reproduce.

For performance regression, please open a new issue with information including your hardware configuration, etcd configuration, perf regression data.

> I can't create 7 overlay network containers one second

This is useless to us. We do not know how do you create overlay network and how does it relate to etcd.

**Comment by ringtail** [comment]
@xiang90 @gyuho thanks guys!
