### ISSUE TITLE
Downgrading 3.0.15 to 2.3.7 fails, experimental-v3demo cannot be disabled

### ISSUE THREAD

**Issue by rtoma** [coreos/etcd#6883]
I have a 3 node 2.3.7 etcd cluster. Its healthy.

I upgraded 1st and 2nd nodes to 3.0.15. 3rd node is leader and complains about versions:
```
etcd[13529]: the local etcd version 2.3.7 is not up-to-date
etcd[13529]: member 632c48c9b3985929 has a higher version 3.0.15
```
But the cluster is still healthy. 

Downgrading 1st node back to 2.3.7. This node will not start up, because of
```
etcd[3645]: experimental-v3demo cannot be disabled once it is enabled
```
Neither 2.3.7 or 3.0.15 config included `ETCD_EXPERIMENTAL_V3DEMO=true`.

Upgrading 1st node again and its happy. Great of course, but I need a working rollback plan.

What can you suggest?

Thanks!

**Comment by xiang90** [comment]
Will a backup before upgrading work for you?

**Comment by rtoma** [comment]
Yes, its downgrading-the-hard-way, but it will do.

Any idea why the normal downgrade path is not possible?

**Comment by rtoma** [comment]
I've upgraded our clusters without issues. Closing this ticket.

**Comment by JinsYin** [comment]
@rtoma You must be remove work-dir, then restart

**Comment by edevil** [comment]
@JinsYin Which "work-dir" would that be? This is the structure of the etcd2 data dir:
```
# find /var/lib/etcd2
/var/lib/etcd2
/var/lib/etcd2/member
/var/lib/etcd2/member/wal
/var/lib/etcd2/member/wal/0000000000000002-00000000000319b5.wal
/var/lib/etcd2/member/wal/0000000000000000-0000000000000000.wal
/var/lib/etcd2/member/wal/0000000000000001-0000000000018e6c.wal
/var/lib/etcd2/member/snap
/var/lib/etcd2/member/snap/0000000000000002-0000000000033465.snap
/var/lib/etcd2/member/snap/0000000000000002-0000000000035b76.snap
/var/lib/etcd2/member/snap/0000000000000002-0000000000038287.snap
/var/lib/etcd2/member/snap/db
/var/lib/etcd2/member/snap/0000000000000002-000000000003a998.snap
/var/lib/etcd2/member/snap/0000000000000002-0000000000030d54.snap
```
