### ISSUE TITLE
etcdctl v3 - keys lease ID should be in hex?

### ISSUE THREAD

**Issue by mwf** [coreos/etcd#6887]
Hi, guys!

I'm wondering why "lease" is not HEX value in GET response?

ETCDCTL_API=3 /usr/local/bin/etcdctl  get foo -w json
```json
{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":3096,"raft_term":3},"kvs":[{"key":"Zm9v","create_revision":3096,"mod_revision":3096,"version":1,"value":"YmFy","lease":7587818290816322434}],"count":1}
```

In order to use it in any ```lease <cmd>``` command I have to convert it to HEX first.
```
ETCDCTL_API=3 etcdctl lease revoke 7587818290816322434
Error:  bad lease ID arg (strconv.ParseInt: parsing "7587818290816322434": value out of range), expecting ID in Hex
```

Do you have any plans to fix this inconsistency?

**Comment by xiang90** [comment]
This is inconsistency since the output format is not default. It is from json. I do not think we should fix this. We can add a flag to range to output the lease of a key and output the lease id in hex format.

**Comment by gyuho** [comment]
Yeah printing out `range` response with lease in hex sounds better.

**Comment by mwf** [comment]
Maybe the best option - to add an option for ```lease``` command to recieve lease ID in int64 format? Just curious, what was the reason for HEX? :)

Otherwise you should also support HEX output in other commands, where lease ID may occur, like:

```
ETCDCTL_API=3 etcdctl lease timetolive 4F325888AB411E3D --keys -w json
{"cluster_id":1217629517487190609,"member_id":7566429884247002930,"revision":1032,"raft_term":2,"id":5706721021843807805,"ttl":4,"granted-ttl":5,"keys":["Zm9v"]}
```

**Comment by xiang90** [comment]
> Maybe the best solution - to add an option for lease command to recieve lease ID in int64 format? Just curious, what was the reason for HEX

HEX is short. All lease commands in etcdctl output HEX. JSON format is not the default output. And we do not plan to make it the default.

**Comment by mwf** [comment]
OK, got it :)

Then it would be great to add a new field with HEX. "lease_id" or "lease_hex" as it's more clear :)
And even no additional flag is needed, because there is no compatability break in adding a new field.
Looking forward for it!

**Comment by xiang90** [comment]
@mwf If you have time, can you contribute to this flag in range request?

**Comment by mwf** [comment]
Yeap, would be glad to! 

Let's make a decision about the field name ("lease_id" or "lease_hex")? And do we really need additional flag since the backwards compatability is not broken?

**Comment by xiang90** [comment]
@mwf 

we print out the get result here: https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/get_command.go#L74

The display func does not print out leaseID. So you have to get the json header. 

We need to keep backwards compatability. I suggest to have a --lease-id flag added into get sub command. Once it is enabled, we print out lease id after value. If no lease id is attached, print out 0. All in hex format. We always print out and receive ID in hex format, except non-default format like JSON which we do not control.

**Comment by mwf** [comment]
Ah, I see now, you want to add lease ID to the default output, not json. So additional flag is really needed.

But why not to add it to JSON output? Or this JSON is a plain gRPC response from etcd, encoded in JSON? That's why we can't add a new field there?

**Comment by xiang90** [comment]
@mwf We cannot json output. json should not represent int as hex i think.

**Comment by xiang90** [comment]
@heyitsanthony recently add the field format that will output lease in hex format. so closing this issue.

**Comment by mwf** [comment]
Thanks to him!
I think it's the best option, covering all possible needs.
