### ISSUE TITLE
cloud config with dynamic IP for etcd

### ISSUE THREAD

**Issue by sanjeevm0** [coreos/etcd#6889]
In cloud config, we need the following for etcd2 cluster.  However, if public_ipv4/private_ipv4 is being assigned by DHCP server, then what should be entered?  It seems it can easily be populated by looking at ip address which is assigned to the network interface after booting.  However, it is not known beforehand. Is it possible to populate /run/systemd/system/etcd2.service.d/20-cloudinit.conf with the assigned IP address and then start the etcd service?

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    discovery: "https://discovery.etcd.io/<token>"
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: "http://$public_ipv4:2379"
    initial-advertise-peer-urls: "http://$private_ipv4:2380"
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: "http://0.0.0.0:2379,http://0.0.0.0:4001"
    listen-peer-urls: "http://$private_ipv4:2380,http://$private_ipv4:7001"

**Comment by xiang90** [comment]
This seems like a cloud config question. If you are running CoreOS, you probably should open an issue here: https://github.com/coreos/bugs/issues .

For etcd, you'd either:
1. tell etcd the ip:port before you start etcd via command line configuration or config file
2. in the later version of etcd (>3), etcd will try to pick up the ip on the default route and use it as advertised ip if no ip is specified.

**Comment by xiang90** [comment]
I am closing this. Reopen if you have any follow-up questions.
