### ISSUE TITLE
etcd hangs on 2nd get status

### ISSUE THREAD

**Issue by aanm** [coreos/etcd#6892]
I was trying to get the cluster status of etcd. Calling `e.Status()` once works as expected. However, calling `e.Status()` again, it doesn't work and the client hangs forever. Do I need to create a new cliente instance in order to retrieve the endpoint status of each endpoint? Why?

```go
type EtcdClient struct {
	cli         *client.Client
}

func (e *EtcdClient) Status() (string, error) {
	eps := e.cli.Endpoints()
	for i, ep := range eps {
		if sr, err := e.cli.Status(ctx.Background(), ep); err != nil {
			return "", err
		} else if sr.Header.MemberId == sr.Leader {
			eps[i] = fmt.Sprintf("%s - (Leader) %s", ep, sr.Version)
		} else {
			eps[i] = fmt.Sprintf("%s - %s", ep, sr.Version)
		}
	}
	return strings.Join(eps, "; "), nil
}
```

version: `3.1.0-rc.1`

**Comment by gyuho** [comment]
Sure will try to reproduce.

**Comment by gyuho** [comment]
I can reproduce. Will fix soon.

**Comment by gyuho** [comment]
This should be fixed via https://github.com/coreos/etcd/issues/6892.

We were returning the original string slice, which is reference to the original string array. So when your code manipulates the `eps`, it was updating the actual endpoints in the client.

**Comment by aanm** [comment]
Cool, thanks! :-)
