### ISSUE TITLE
Interesting potential memory issue

### ISSUE THREAD

**Issue by Supernomad** [coreos/etcd#6893]
### Issue/Question
I have a brand new cluster running in my infrastructure, that has exactly a single key with a single value in the root of the key/value store.

```
/Hello -> "Production"
```

The topology of the setup is a 3 node etcd server cluster, plus etcd proxies distributed to ~400 servers across the globe. All of the etcd instances are running in a docker container based on ubuntu 14.04 and utilize `--net host`. The deployment and testing has gone over incredibly well, however I have noticed a single etcd server in the primary cluster is reporting 10+GB of VIRT memory usage. In before people point out RES is what to worry about, I know that, and I am very aware of how VIRT works. 

This issue is just something that stuck out during the setup's validation phase, and I would like to know if you guys have any idea why that would happen? And whether or not, from the standpoint of etcd, there is something to actually worry about here.

### Server configuration
CPU: 2x 8 Core (16 vCore) Xeon's
RAM: 16GB
NIC: 2 Port 10Gbit Fiber
HDD: 256GB SSD

### Applicable Versions
```
$ uname -a
Linux 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

$ etcd --version
etcd Version: 3.0.15
Git SHA: fc00305
Go Version: go1.6.3
Go OS/Arch: linux/amd64

$ etcdctl --version 
etcdctl version: 3.0.15
API version: 2
```

**Comment by xiang90** [comment]
>  there is something to actually worry about here.

No. We reserve 10GB VIRT memory for etcd on startup.

**Comment by Supernomad** [comment]
Well there you have it, super simple explanation. Thank you for the swift response.

**Comment by xiang90** [comment]
> The deployment and testing has gone over incredibly well,

This is awesome! Let us know how it goes and where we could help.
