### ISSUE TITLE
raft: pre-vote test may fail when porting in TiKV

### ISSUE THREAD

**Issue by mrmiywj** [coreos/etcd#6895]
Recently I'm porting raft's pre-vote part in TiKV. Then I found that `leader_election_pre_vote` test may fail on [this case](https://github.com/coreos/etcd/pull/6624/files#diff-ad12a9c9b66e1507ca04edc74b4b1e8aR319). Unfortunately, this test may fail at times. The log is listed as follows.

```
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:852 - INFO  -  is starting a new election at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:662 - INFO  -  became pre-candidate at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:735 - INFO  -  received MsgRequestPreVoteResponse from 1 at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:715 - INFO  -  [logterm: 1, index: 1] sent MsgRequestPreVote request to 3 at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:715 - INFO  -  [logterm: 1, index: 1] sent MsgRequestPreVote request to 2 at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:715 - INFO  -  [logterm: 1, index: 1] sent MsgRequestPreVote request to 4 at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:715 - INFO  -  [logterm: 1, index: 1] sent MsgRequestPreVote request to 5 at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:889 - INFO  -  [logterm: 2, index:1, vote:0] rejected MsgRequestPreVote from 1 [logterm: 1, index: 1] at term 2
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:869 - INFO  -  [logterm: 0, index: 0, vote: 0] cast MsgRequestPreVote for 1 [logterm: 1, index: 1] at term 0
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:869 - INFO  -  [logterm: 1, index: 1, vote: 0] cast MsgRequestPreVote for 1 [logterm: 1, index: 1] at term 1
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:869 - INFO  -  [logterm: 0, index: 0, vote: 0] cast MsgRequestPreVote for 1 [logterm: 1, index: 1] at term 0
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:789 - INFO  -  [term: 1] received a MsgRequestPreVoteResponse message with higher term from 3 [term: 2]
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:1582 - DEBUG -  reset election timeout 8 -> 7 at 0
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:644 - INFO  -  became follower at term 2
test_leader_election_pre_vote 2016-11-23 22:33:50,861 raft.rs:817 - INFO  -  [term: 2] ignored a MsgRequestPreVoteResponse message with lower term from 4 [term: 1]
```

In this test case, node1 will send out pre-vote request message with `term=2, last_log_index=1, last_log_term=1`. This message will be rejected by node3, due to [this statement](https://github.com/coreos/etcd/pull/6624/files#diff-a8629a0eb6da1c6c3805111f1f1af85eR774). If node1 has not received enough vote response, still in pre-candidate, it will receive a pre-vote reject message with `term=2`, while node1's term=1. [This statement](https://github.com/coreos/etcd/pull/6624/files#diff-a8629a0eb6da1c6c3805111f1f1af85eR707) will be executed. And then node1 will become follower.

The test may pass since node1 may receive majority response before the rejection arriving. Then it will increase its term and become candidate. The reject message's term will not be greater than the node's.

But etcd's test log shows that it does not perform pre-vote election... I'm not sure why..
```
raft2016/11/24 00:45:17 INFO: 1 became follower at term 1
raft2016/11/24 00:45:17 INFO: 1 is starting a new election at term 1
raft2016/11/24 00:45:17 INFO: 1 became candidate at term 2
raft2016/11/24 00:45:17 INFO: 1 received MsgVoteResp from 1 at term 2
raft2016/11/24 00:45:17 INFO: 1 [logterm: 1, index: 1] sent MsgVote request to 3 at term 2
raft2016/11/24 00:45:17 INFO: 1 [logterm: 1, index: 1] sent MsgVote request to 4 at term 2
raft2016/11/24 00:45:17 INFO: 1 [logterm: 1, index: 1] sent MsgVote request to 5 at term 2
raft2016/11/24 00:45:17 INFO: 1 [logterm: 1, index: 1] sent MsgVote request to 2 at term 2
raft2016/11/24 00:45:17 INFO: 3 [logterm: 2, index: 1, vote: 0] rejected MsgVote from 1 [logterm: 1, index: 1] at term 2
raft2016/11/24 00:45:17 INFO: 4 [term: 1] received a MsgVote message with higher term from 1 [term: 2]
raft2016/11/24 00:45:17 INFO: 4 became follower at term 2
raft2016/11/24 00:45:17 INFO: 4 [logterm: 1, index: 1, vote: 0] cast MsgVote for 1 [logterm: 1, index: 1] at term 2
raft2016/11/24 00:45:17 INFO: 5 [term: 0] received a MsgVote message with higher term from 1 [term: 2]
raft2016/11/24 00:45:17 INFO: 5 became follower at term 2
raft2016/11/24 00:45:17 INFO: 5 [logterm: 0, index: 0, vote: 0] cast MsgVote for 1 [logterm: 1, index: 1] at term 2
raft2016/11/24 00:45:17 INFO: 2 [term: 0] received a MsgVote message with higher term from 1 [term: 2]
raft2016/11/24 00:45:17 INFO: 2 became follower at term 2
raft2016/11/24 00:45:17 INFO: 2 [logterm: 0, index: 0, vote: 0] cast MsgVote for 1 [logterm: 1, index: 1] at term 2
raft2016/11/24 00:45:17 INFO: 1 received MsgVoteResp rejection from 3 at term 2
raft2016/11/24 00:45:17 INFO: 1 [quorum:3] has received 1 MsgVoteResp votes and 1 vote rejections
raft2016/11/24 00:45:17 INFO: 1 received MsgVoteResp from 4 at term 2
raft2016/11/24 00:45:17 INFO: 1 [quorum:3] has received 2 MsgVoteResp votes and 1 vote rejections
raft2016/11/24 00:45:17 INFO: 1 received MsgVoteResp from 5 at term 2
raft2016/11/24 00:45:17 INFO: 1 [quorum:3] has received 3 MsgVoteResp votes and 1 vote rejections
raft2016/11/24 00:45:17 INFO: 1 became leader at term 2
raft2016/11/24 00:45:17 INFO: found conflict at index 1 [existing term: 2, conflicting term: 1]
raft2016/11/24 00:45:17 INFO: replace the unstable entries from index 1
```

I'm not sure how to resolve it. Maybe the pre-candidate should not become follower when it receives a rejection?
@xiang90

**Comment by xiang90** [comment]
@bdarnell Can you take a look? Or I will take a look later this week. Thanks!

**Comment by bdarnell** [comment]
Working on it. The problem is that the `ents()` function used in this test always uses a default configuration instead of the one passed to `newNetworkWithConfig`, so the tests need some refactoring (and then once that's done there may be bugs to fix too).

**Comment by bdarnell** [comment]
This "logs converge" test case is strange; I don't think the situation it describes is actually possible. One of the nodes has an entry in its log with term 2. This can only happen if some node won an election at term 2, in which case a quorum of nodes would have `HardState.Term >= 2`. These nodes would be unable to vote for node 1 when it campaigns. @xiang90, what is this test case trying to prove? Should we improve it or just delete it?

**Comment by xiang90** [comment]
> One of the nodes has an entry in its log with term 2. 

I think it tries to test this sequences.

- Node A is the leader of term 1
- Node A replicates entry ("1", term: 1) to itself and one another node B
- Node A dies
- Node C becomes candidate
- Node C elects leader at term 2 by getting votes from A, B
- Node C replicates entry ("1", term: 2) to itself
- Node C dies

Now we have
Node A: ["1", 1] at term 2, Node B: ["1", 1] at term 2, Node C ["1", 2] at term 2, Node D: empty at term 1, Node E: empty at term 1

We want to test that Node A can elect as leader again and overwrite NodeC's log even if NodeC's log has a larger term.

The hardterm is set incorrectly I believe.

**Comment by bdarnell** [comment]
> We want to test that Node A can elect as leader again and overwrite NodeC's log even if NodeC's log has a larger term.

Right, but it doesn't actually test that we overwrite node C's log, only that A can become leader. And if we fix the terms so that C, D, and E have term 2 in their hardstate, the first election will fail (a second one could succeed, but this test is not set up for that). We test the log overwriting in TestLeaderSyncFollowerLog, but it looks like that doesn't include cases where one of the followers has a higher term. I'll remove this case from TestLeaderElection and make a separate test for it.

**Comment by xiang90** [comment]
@bdarnell 

Sounds good to me! Thanks for looking into this.
