### ISSUE TITLE
Panic (nil pointer dereference) in gRPCWatcher

### ISSUE THREAD

**Issue by olivere** [coreos/etcd#6900]
I am using gRPC resolver in a system with 3 services. The dependency graph is as follows:

A
B -> A
C -> A, B

Service A starts up and registers as follows:

```go
...
import (
	"github.com/coreos/etcd/clientv3"
	etcdnaming "github.com/coreos/etcd/clientv3/naming"
	"google.golang.org/grpc"
	"google.golang.org/grpc/naming"
)
...
func main() {
...
	etcdcli, err := clientv3.NewFromURL("http://localhost:2379")
	if err != nil {
		return err
	}
	resolver := &etcdnaming.GRPCResolver{Client: etcdcli}
	balancer := grpc.RoundRobin(resolver)
...
	r := &etcdnaming.GRPCResolver{Client: etcdcli}
	r.Update(context.TODO(), "service-a", naming.Update{Op: naming.Add, Addr: "127.0.0.1:10000"})
	defer r.Update(context.TODO(), "service-a", naming.Update{Op: naming.Delete, Addr: "127.0.0.1:10000"})
...
```

Service B registers like A, but retrieves a `grpc.ClientConn` to A from etcd like this:

```go
...
	resolver := &etcdnaming.GRPCResolver{Client: etcdcli}
	balancer := grpc.RoundRobin(resolver)

	var opts []grpc.DialOption
	opts = append(opts, grpc.WithInsecure())
	opts = append(opts, grpc.WithBalancer(balancer))
	conn, err := grpc.Dial("service-a", opts...)
	if err != nil {
		return fmt.Errorf("error connecting to service A: %v", err)
	}
	defer conn.Close()
	clienta := servicea.NewClient(conn)
...
```

Service C does the same as B, but uses separate resolvers and balancers for connecting to A and B.

Now when I start all services, everything works. However, if I stop service A, the `gRPCWatcher` crashes B and C:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x16324a]

goroutine 49 [running]:
panic(0x4f1040, 0xc420012170)
	/Users/oliver/go/src/runtime/panic.go:500 +0x1a1
github.com/meplato/cloud/vendor/github.com/coreos/etcd/clientv3/naming.(*gRPCWatcher).Next(0xc420155680, 0xc42015cf00, 0xc420139ed8, 0xc4200cb840, 0x1, 0x1)
	/Users/oliver/src/github.com/meplato/cloud/vendor/github.com/coreos/etcd/clientv3/naming/grpc.go:96 +0x2fa
github.com/meplato/cloud/vendor/google.golang.org/grpc.(*roundRobin).watchAddrUpdates(0xc42015cd80, 0x0, 0x0)
	/Users/oliver/src/github.com/meplato/cloud/vendor/google.golang.org/grpc/balancer.go:168 +0x64
github.com/meplato/cloud/vendor/google.golang.org/grpc.(*roundRobin).Start.func1(0xc42015cd80)
	/Users/oliver/src/github.com/meplato/cloud/vendor/google.golang.org/grpc/balancer.go:239 +0x2b
created by github.com/meplato/cloud/vendor/google.golang.org/grpc.(*roundRobin).Start
	/Users/oliver/src/github.com/meplato/cloud/vendor/google.golang.org/grpc/balancer.go:243 +0x148
```

The problem is that `e.PrevKv` in [line 96](https://github.com/coreos/etcd/blob/master/clientv3/naming/grpc.go#L96) of `grpc.go` is `nil`. If I add a check for the `nil` value, everything seems to be okay, and gRPC starts reconnecting to A.

Is there something I'm doing wrong in my code?

**Comment by xiang90** [comment]
@olivere What is the version of etcdServer are you running?

**Comment by olivere** [comment]
Hi there! Here you are:

```
$ etcd --version
etcd Version: 3.0.9
Git SHA: GitNotFound
Go Version: go1.7.1
Go OS/Arch: darwin/amd64

$ etcdctl version
etcdctl version: 3.0.9
API version: 3.0
```

**Comment by xiang90** [comment]
@olivere yea. etcd 3.0.9 does not support prevKV feature. Can you try with latest version of etcd server? At the other side, we should fix the client to at least not panic in this case.

**Comment by olivere** [comment]
Ah. I see. Will check.

BTW: Checking for `nil` seems to resolve the issue. No orphaned services registered, regardless of the order I stop the services.

```go
	updates := make([]*naming.Update, 0, len(wr.Events))
	for _, e := range wr.Events {
		switch e.Type {
		case etcd.EventTypePut:
			var jupdate naming.Update
			err := json.Unmarshal(e.Kv.Value, &jupdate)
			jupdate.Op = naming.Add
			if err == nil {
				updates = append(updates, &jupdate)
			}
		case etcd.EventTypeDelete:
			if e.PrevKv != nil {
				var jupdate naming.Update
				err := json.Unmarshal(e.PrevKv.Value, &jupdate)
				jupdate.Op = naming.Delete
				if err == nil {
					updates = append(updates, &jupdate)
				}
			}
		}
	}
	return updates, nil
```

**Comment by olivere** [comment]
I can confirm that etcd from HEAD works fine.

```
$ etcd --version
etcd Version: 3.1.0-rc.1+git
Git SHA: c31b1ab
Go Version: go1.7.3
Go OS/Arch: darwin/amd64
```

**Comment by xiang90** [comment]
@olivere Awesome. If you want to help us fix it, I think we should:

1. check nil
2. if nil, we can still fill in the addr field since we know the deleted key (metadata is in the value though)/

**Comment by olivere** [comment]
@xiang90 Hmm... I've tested [this change](https://github.com/olivere/etcd/commit/2e2b5274a342dbf9460b6438a5d8916b150e2c36) to see if it resolves the panic and correctly removes the services (I could create a PR from there).

Started 3 services that have this hierarchy: `cloud-distlock` -> `cloud-identity` -> `cloud-content`.

```sh
$ etcdctl get --prefix cloud
cloud-content/:62625
{"Op":0,"Addr":":62625","Metadata":null}
cloud-distlock/:62613
{"Op":0,"Addr":":62613","Metadata":null}
cloud-identity/:62618
{"Op":0,"Addr":":62618","Metadata":null}
```

Then I quit `cloud-distlock`. No panic, and the service is correctly removed. Two services trying to connect to `cloud-distlock`.

```sh
$ etcdctl get --prefix cloud
cloud-content/:62625
{"Op":0,"Addr":":62625","Metadata":null}
cloud-identity/:62618
{"Op":0,"Addr":":62618","Metadata":null}
```

If I restart `cloud-distlock` the service is back and correctly registered. Could you help in what you propose in step 2.

**Comment by xiang90** [comment]
@olivere It is correct at etcd side. But not correct at the resolver side. For delete event, we should fill in all the fields instead of just returning an empty delete event.

**Comment by olivere** [comment]
@xiang90 Oh. I see. Added a small debug output. This is what I see on DELETE.

```
&{Type:DELETE Kv:key:"cloud-distlock/:62345" mod_revision:5  PrevKv:<nil>}
```

So you want me to send a `naming.Delete` for `e.Kv.Key`, [like this](https://github.com/olivere/etcd/blob/master/clientv3/naming/grpc.go#L87-L102)? Sorry for all that ping pong, but I'm not too deep into the etcd code yet.

Notice that this change breaks the resolver tests:

```
 --- FAIL: TestGRPCResolver (0.19s)
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 82 [running]:
panic(0x83f960, 0xc42000c1b0)
	/Users/oliver/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42008c180)
	/Users/oliver/go/src/testing/testing.go:579 +0x25d
panic(0x83f960, 0xc42000c1b0)
	/Users/oliver/go/src/runtime/panic.go:458 +0x243
github.com/olivere/etcd/clientv3/naming.TestGRPCResolver(0xc42008c180)
	/Users/oliver/src/github.com/olivere/etcd/clientv3/naming/grpc_test.go:81 +0x796
testing.tRunner(0xc42008c180, 0x9c3140)
	/Users/oliver/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/Users/oliver/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/olivere/etcd/clientv3/naming	0.224s
```

**Comment by heyitsanthony** [comment]
@olivere for this to work without PrevKV support, it should do a `Get(gw.ctx, e.Key, clientv3.WithRev(e.ModRevision - 1))` when PrevKV is nil to get the value for the update slice instead of dropping the event on the floor.

**Comment by olivere** [comment]
@heyitsanthony @xiang90 Thanks guys for leading me into the right direction. Is [this](https://github.com/olivere/etcd/blob/master/clientv3/naming/grpc.go#L87-L112) better? Can we assume that the `Key` is a `string` in [line 102](https://github.com/olivere/etcd/blob/master/clientv3/naming/grpc.go#L102)?

**Comment by heyitsanthony** [comment]
@olivere yes, that will work. @xiang90 had some concerns about compaction causing the value to be lost, though. The alternative is ditch PrevKV entirely by keeping a map of known resolver keys to values and filling in the update with the value from the map when there's a delete.

**Comment by olivere** [comment]
@heyitsanthony I see. Let me know if you want me to squash a PR.

**Comment by heyitsanthony** [comment]
@olivere is this going to be a PR? I don't mind merging what's there since it's a relatively minor change. Would like to close out this issue...

**Comment by olivere** [comment]
@heyitsanthony It works fine with newer versions of etcd (e.g. 3.0.15). I don't know about your update/bug policy but AFAIC we could simply close the issue.

**Comment by heyitsanthony** [comment]
OK, it was alpha/mostly broken for 3.0 anyway so I guess it's not necessary. Thanks for looking into this!
