### ISSUE TITLE
`ls` command is missing in etcdctl v3 

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#6904]
The `ls` command is missing in etcdctl v3 APIs. Hope it can be back cause etcdctl stores is incompatible between v2 and v3.
e.g.
```
$ ./etcdctl set z 1
1
$ ETCDCTL_API=3 ./etcdctl get z
$ ./etcdctl get z
1
```

And after data migration, I can't find what the latest data is. Neither can I debug my business.

**Comment by xiang90** [comment]
You can use `ETCDCTL_API=3 ./etcdctl get z --prefix` to achieve similar goal. There is no directory in v3, thus no ls.

**Comment by armstrongli** [comment]
The `ETCDCTL_API=3 ./etcdctl get z --prefix` will show all keys and values which match the prefix. It's really not friendly to operators to check the keys in each level.
e.g. 
I want to know how many third party resources created in kubernetes, I need to know the exact path of the keys' prefix. All the values are returned at the same time.

**Comment by xiang90** [comment]
> I want to know how many third party resources created in kubernetes

You should use k8s tool set to do it, not etcdctl. etcd3 does not understand any path structure. we do not plan to add that feature in core etcd either.

**Comment by armstrongli** [comment]
We got this issue when we upgrade kubernetes from 1.2 to 1.3:
All third party resources should be rebuilt to match the none-namespace resources definition.
We need to delete the old resources from etcd directly and use new kubernetes API to rebuild those third party resources. The new kubernetes third party resource API can't get the old third party resources any more.
For such cases, we have to do operations directly on etcd as cluster operator.

**Comment by xiang90** [comment]
> All third party resources should be rebuilt to match the none-namespace resources definition.
We need to delete the old resources from etcd directly and use new kubernetes API to rebuild those third party resources. The new kubernetes third party resource API can't get the old third party resources any more.

Open an issue in k8s repo. Upgrading etcd should not break any k8s feature.

**Comment by armstrongli** [comment]
Thanks :)

**Comment by Sartner** [comment]
> You can use ETCDCTL_API=3 ./etcdctl get z --prefix to achieve similar goal. There is no directory in v3, thus no ls.
But how to list all keys ? @xiang90

**Comment by armstrongli** [comment]
@Sartner
`ETCDCTL_API=3 ./etcdctl get / --prefix --keys-only`

**Comment by oliebel** [comment]
sux

**Comment by gmcquillan** [comment]
I recognize that the underlying serialization and replication of data in etcd3 has very different semantics than it did with etcd2, however people still conceive of data as a hierarchical tree. 

Removing the commands to explore that hierarchy from the core of command-line client seems like a mistake to me.

There's an additional 40 characters needed for one of the most common operations an administrator could possibly have in etcd -- and it's not obvious without a google search how to list keys as you might've done before.

Is there a reason to make the UX for this much, much harder to use? Is querying partial keys (i.e. using `ls`) really that unsafe?

**Comment by heyitsanthony** [comment]
@gmcquillan `ls` was not removed; it was never supported in v3 in the first place. Use the v2 backend or the v2 emulation layer if you want a directory hierarchies.

**Comment by gmcquillan** [comment]
@heyitsanthony Thanks for responding. Those are two good choices. 

I'm just concerned that in v4, or v5, or v6 those kinds of feature bridges won't be available. 

I want to communicate that, like the original author of this issue and the 30 people who've found it and thumbs-up'ed the answer, this change (between v2 and v3) kinda violates our expectations about the UX. If it were my project, I'd want to know.

Thanks.

**Comment by heyitsanthony** [comment]
@gmcquillan we're trying to support sane migration paths with data model emulation. v4 will likely be a cleanup of v3, it won't be as much of a conceptual leap. There's no `ls` in etcdctl v3 because it'd be very expensive to support with the v3 data model and having special support for it would reduce performance for applications that don't need it.

Since v3 was a major revision bump, going by semver, all bets are off in terms of expectations of command carry-over. This shouldn't come as a surprise.

**Comment by peterwillcn** [comment]
ETCDCTL_API=3 etcdctl --endpoints=http://localhost:2379 get / --prefix --keys-only

**Comment by SamuelMarks** [comment]
>because it'd be very expensive to support with the v3 data model and having special support for it would reduce performance for applications that don't need it.
@heyitsanthony - How about hiding it behind a compiler flag? - We're in the Go world here, so it's possible without any efficiency drop.

(just don't know if the etcd people want to maintain two paradigms; it's like having InnoDB and TokuDB in the MySQL world. Abstracting out the engines into those two then letting the communities split could be a long-term maintenance option…)

**Comment by josue** [comment]
On environment:
- **macOS v10.13.1** _(High Sierra)_
- **etcd v3.2.10**    _(install via `brew install etcd`)_

The command `get / --prefix` will return an empty response. Instead you can do the following:

`ETCDCTL_API=3 etcdctl get "" --prefix --keys-only | sed '/^\s*$/d'`

_^ using the empty quote will returns all keys then pipe it to removes empty lines._

**Comment by tantjp** [comment]
@xiang90 Hi, I would like to get all keys by rest api, can you do me a favor?thx

**Comment by EasonFeng5870** [comment]
@tantjp  we have same problems...

**Comment by tantjp** [comment]
@EasonFeng5870   read this :
[https://github.com/etcd-io/etcd/issues/7484#issuecomment-408069279](url)

**Comment by SumuduLansakara** [comment]
For listing all keys `etcdctl --endpoints=http://localhost:2379 get --prefix --keys-only /` doesn't work on linux anymore.
But `etcdctl --endpoints=http://localhost:2379 get --prefix --keys-only ''` does.

**Comment by dabcoder** [comment]
> For listing all keys `etcdctl --endpoints=http://localhost:2379 get --prefix --keys-only /` doesn't work on linux anymore.
> But `etcdctl --endpoints=http://localhost:2379 get --prefix --keys-only ''` does.

Would it be worth adding a section in the docs https://etcd.io/docs/v3.3.12/dev-guide/interacting_v3/#find-versions that briefly explains how to list all keys i.e. run the above command?
