### ISSUE TITLE
single point failure on etcdctl commands

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#6908]
If there're multiple members in etcd v3 cluster, there is single point failure on etcdctl commands with multiple endpoints set.

e.g. 
`ectl=etcdctl --endpoints="a,b,c,d"`. `a`,`b`,`c`,`d` are member endpoints. 
All commands work well if all the members of the cluster are healthy.

```
/ # ectl endpoint status -w table
+-----------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
|                   ENDPOINT                    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-----------------------------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://tess-node-ojgs1-6199.*.*.*:4001 | 173a38c93ceeb51  | 3.0.4   | 25 kB   | true      |        12 |     196025 |
| https://tess-node-m8ioe-9321.*.*.*:4001 | 54d07ec2c4ec6017 | 3.0.4   | 25 kB   | false     |        12 |     196025 |
| https://tess-node-ppd1p-4549.*.*.*:4001 | 839afbecd56cf6cd | 3.0.4   | 25 kB   | false     |        12 |     196025 |
| https://tess-node-7so7r-5300.*.*.*:4001 | 8b8b8a1c73edbb68 | 3.0.4   | 25 kB   | false     |        12 |     196025 |
+-----------------------------------------------+------------------+---------+---------+-----------+-----------+------------+ 
```

After one of the member gets down, v3 commands don't work, v2 ones keep working:
```shell
# V2 commands here
/ # ectl member list
173a38c93ceeb51: name=etcd-3 peerURLs=http://172.20.43.46:2380 clientURLs=https://tess-node-ojgs1-6199.*.*.*:4001 isLeader=true
54d07ec2c4ec6017: name=etcd-2 peerURLs=http://172.20.43.47:2380 clientURLs=https://tess-node-m8ioe-9321.*.*.*:4001 isLeader=false
839afbecd56cf6cd: name=etcd-new peerURLs=http://172.20.43.50:2380 clientURLs=https://tess-node-ppd1p-4549.*.*.*:4001 isLeader=false
8b8b8a1c73edbb68: name=etcd-1 peerURLs=http://172.20.43.49:2380 clientURLs=https://tess-node-7so7r-5300.*.*.*:4001 isLeader=false

# V3 commands here
/ # ectl member list
2016/11/29 06:59:10 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.20.43.50:4001: getsockopt: connection refused"; Reconnecting to {"tess-node-ppd1p-4549.*.*.*:4001" <nil>}
Error:  grpc: timed out when dialing
```

**Comment by kldjaff** [comment]
is there anyone who are facing this?

**Comment by heyitsanthony** [comment]
> `| https://tess-node-ojgs1-6199.*.*.*:4001 | 173a38c93ceeb51  | 3.0.4   | 25 kB   | true      |        12 |     196025 |`

@armstrongli 3.0.4 is out of date. I believe this was partially fixed by 4a841459f1655a1b5ae88f7af8f4a2e3b9e9d4a5 and totally fixed in 1a8b295dabb926c2db27ca964ef6986cc8642433 which wasn't merged until 3.0.6. Please update to the latest 3.0.x and try it again.

**Comment by armstrongli** [comment]
@heyitsanthony 
After trying the latest version `3.0.15`, the commands work.  Thanks :)
However, there's always one grpc error message in etcdctl commands:
```
bash-4.3# ectl get /d
2016/11/30 07:10:05 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 172.20.43.47:4001: getsockopt: connection refused"; Reconnecting to {"tess-node-m8ioe-9321.*.*.*:4001" <nil>}
/d
4
```

ETCD has always a consensus algorithm and can get the value even only one member left. So why not hide the error message until all the members are down?

**Comment by heyitsanthony** [comment]
> ETCD has always a consensus algorithm and can get the value even only one member left. 

This is not true for linearized reads, which are the default; they must go through consensus which requires a cluster quorum. It's still possible to fetch stale data after losing quorum with `--consistency=s`, though.

The error messages are written out by grpc at the time of the error. The etcd client could defer the error messages by having a specialized logging backend in the client to intercept the errors and flush them based on grpc balancer feedback. It's not clear to me whether it's worth the trouble. If you think it's important, feel free to open a new issue for it. Thanks!

Closing since the original issue is already fixed.
