### ISSUE TITLE
Save error for key 'NC**',example'NC01612133'

### ISSUE THREAD

**Issue by coder0wang** [coreos/etcd#6909]
Some time the key for 'NC01**' is can't save;
Some time is saved,but have error code.
I just save a value that is string ,but  the value is "Ã\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083Ã\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083\u0083...".
The length more the 100 KB.
I think maybe the cause is string's enoding,i use UTF-8 for Chinese.
Please contact me,this is a very big problem in our product.
My e-mail wangyudi1@126.com.
Thinks for your hard work!

**Comment by heyitsanthony** [comment]
@coder0wang what version of etcd? can you give a script or some steps to reproduce the issue you're seeing? are there any warnings or errors in the etcd server logs?

**Comment by coder0wang** [comment]
The version is 3.0.14


I not know where the etcd's log in,and in my program have not error and log for this.
I using java for httpPut to save.


There two keys sometime can't save.Sometime saved ,but not found by RESTful.
url : http://*:2379/v2/keys/task/NC01360544
other two keys :NC01360544,NC136054434.

And for save error:
In the enclosure is value in etcd. (http://pan.baidu.com/s/1boNQQJX)
I saving "maintainer" value is "1111".


I guess the  different encode with some special string to trigger wrong circulation.
Just my guess.

I don't whether my description to enough,if not tell me what can I offer more.

Thanks for your help.

**Comment by gyuho** [comment]
@coder0wang How did you start etcd process?

**Comment by coder0wang** [comment]
--initial-cluster-state new &

**Comment by xiang90** [comment]
etcd2 API does not accept random bytes. You should base64 your random bytes before sending it to etcd.
