### ISSUE TITLE
etcdserver: sync less often

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6913]
etcd somewhat overeagerly sends out sync messages. For a single member idle cluster, the sync messages are the only traffic to the WAL and is the sole cause of fsyncs down to disk.

Two possible optimizations to avoid this:
1.  only send a sync proposal if the v2 store has TTL'd keys
2. only propose sync if cluster has more than one member, otherwise apply directly

**Comment by xiang90** [comment]
I think 1) is a better solution.

**Comment by xiang90** [comment]
Closed by https://github.com/coreos/etcd/pull/6958
