### ISSUE TITLE
New etcd2 cluster leader populates  peerURLs=http://localhost:7001,http://localhost:2380

### ISSUE THREAD

**Issue by alogoc** [coreos/etcd#6914]
While trying to restore the registry of a failed etcd2 cluster using an etcd2  backup (taken while the old cluster was still working) on a fresh node :

This is how I initiated the cluster on the first run after copying over data from backup: 

` sudo etcd2 --data-dir=/var/lib/etcd2  -name kuhumaster --initial-advertise-peer-urls  http://192.168.64.177:2380  --listen-peer-urls http://192.168.64.177:2380  --listen-client-urls http://192.168.64.177:2379,http://127.0.0.1:2379 --advertise-client-urls http://192.168.64.177:2379 --initial-cluster-token kube-etcd-1 --initial-cluster kuhumaster=http://192.168.64.177:2380 --force-new-cluster `

# Configuration  :
### 
etcd2 configuration from `systemctl cat etcd2` :

# /usr/lib/systemd/system/etcd2.service
[Unit]
Description=etcd2
Conflicts=etcd.service

[Service]
User=etcd
Type=notify
Environment=ETCD_DATA_DIR=/var/lib/etcd2
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd2
Restart=always
RestartSec=10s
LimitNOFILE=40000
TimeoutStartSec=0`

[Install]
WantedBy=multi-user.target

# /run/systemd/system/etcd2.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://192.168.64.177:2379"
Environment="ETCD_ELECTION_TIMEOUT=1500"
Environment="ETCD_HEARTBEAT_INTERVAL=200"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.64.177:2380"
Environment="ETCD_INITIAL_CLUSTER_STATE=existing"
Environment="ETCD_LISTEN_CLIENT_URLS=http://192.168.64.177:2379,http://127.0.0.1:2379"
Environment="ETCD_LISTEN_PEER_URLS=http://192.168.64.177:2380"
Environment="ETCD_NAME=kuhumaster"`

## 
Etcd2 part on  `/var/lib/coreos-install/user_data` :

coreos:
 update:
    reboot-strategy: etcd-lock
 units:
   - name: etcd.service
     command: stop
 etcd2:
   name: kuhumaster
   initial-advertise-peer-urls: "http://192.168.64.177:2380"
   advertise-client-urls: "http://192.168.64.177:2379"
   listen-client-urls: "http://192.168.64.177:2379,http://127.0.0.1:2379"
   listen-peer-urls: "http://192.168.64.177:2380"
   initial-cluster-token: kube-etcd-1
   initial-cluster-state: existing
   initial-cluster: "kuhumaster=http://192.168.64.177:2380"
   heartbeat-interval: 200
   election-timeout: 1500
 units:
   - name: etcd2.service
     enable: true
     command: start

	 
##
# Current status:

 >core@kuhumaster ~ $ etcdctl member list
57e4a5a49401: name=kuhumaster peerURLs=http://localhost:7001,http://localhost:2380 clientURLs=http://192.168.64.177:2379 isLeader=true
core@kuhumaster ~ $ etcdctl cluster-health
member 57e4a5a49401 is healthy: got healthy result from http://192.168.64.177:2379
cluster is healthy

>core@kuhumaster ~ $ etcdctl member add kubemaster http://192.168.64.243:2380
Added member named kubemaster with ID 8f5095fa05e04f5a to cluster
ETCD_NAME="kubemaster"
ETCD_INITIAL_CLUSTER="kuhumaster=http://localhost:7001,kuhumaster=http://localhost:2380,kubemaster=http://192.168.64.243:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"
core@kuhumaster ~ $ sudo systemctl is-enabled etcd2
enabled

Now, when I go to that other node and try to add it to the cluster  (of course previously I removed the `/var/lib/etcd2/*` and fixed the `/var/lib/coreos-install/user_data`  I get a `kubemaster etcd2[1127]: request cluster ID mismatch got 57e4a5a49402 want c5537ae30237a3c4)`  since I suppose it is expecting the leader to be `kuhumaster peerURLs=http://localhost:7001,http://localhost:2380 ` (!!!!). In the end cluster crashes on both nodes as it can't find the leader.

Any ideas would be appreciated, I am currently out of them.

**Comment by gyuho** [comment]
Did you stop the old node first?

https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#restoring-a-backup

> Note: If you are trying to restore your cluster using old failed etcd nodes, please make sure you have stopped old etcd instances and removed their old data directories specified by the data-dir configuration parameter.

**Comment by heyitsanthony** [comment]
I suspect it's related to https://github.com/coreos/etcd/blob/release-2.3/etcdserver/raft.go#L484

> `57e4a5a49401: name=zclientURLs=http://192.168.64.177:2379 isLeader=true`

Looks malformed?

**Comment by alogoc** [comment]
@heyitsanthony  yes it was malformed somehow, it is :

 >core@kuhumaster ~ $ etcdctl member list
57e4a5a49401: name=kuhumaster peerURLs=http://localhost:7001,http://localhost:2380 clientURLs=http://192.168.64.177:2379 isLeader=true

Edited also on original.

@gyuho 

Can it be that mismatch ID is due to the localhost peerURLs, since I am using static configuration can it be that 2nd node I am trying to add is expecting the leader to listen to http://localhost:7001 - http://localhost:2380, which of course is not going to work?

Yes I have wiped the data dir on all the old nodes and stopped etcd2 on them. Does this output below look normal to you?

core@kuhumaster ~ $ etcdctl member add  kubemaster http://192.168.64.243:2380
Added member named kubemaster with ID 3106107dfb5ee91 to cluster

ETCD_NAME="kubemaster"
**ETCD_INITIAL_CLUSTER="kuhumaster=http://localhost:7001,kuhumaster=http://localhost:2380,kubemaster=http://192.168.64.243:2380"**
ETCD_INITIAL_CLUSTER_STATE="existing"

Why is it populating the leader on http://localhost:7001 & http://localhost:2380?

**Comment by alogoc** [comment]
Seems after manually updating the member info `etcdctl member update kuhumaster http://192.168.64.177:2380  ` I was able to have the peerURLs populated properly and then start adding members to the cluster.

Still weird though...
