### ISSUE TITLE
build master code faild

### ISSUE THREAD

**Issue by kira8565** [coreos/etcd#6919]
# Bug reporting

I Clone the master code and run `go build` ,but  build fail and display this error

```
# github.com/coreos/etcd/etcdmain
etcdmain/etcd.go:170: not enough arguments in call to daemon.SdNotify
```

**Comment by gyuho** [comment]
@kira8565 You need to use our build script to compile etcd.

Do

```
cd ${GOPATH}/src/github.com/coreos/etcd
./build
./bin/etcd -h
```

**Comment by xiang90** [comment]
Also the systemd dependency is updated. So I am closing this issue.
