### ISSUE TITLE
client: user may freeze on KeepAlive

### ISSUE THREAD

**Issue by dennwc** [coreos/etcd#6922]
**etcd client version:** `3.1.0-rc.0` (git hash: 83347907)

**Issue can be reproduced in following way:**
1) Create an etcdv3 client.
2) Make `lessor.recvKeepAliveLoop()` fail with any server-side error (we got `"lease: unknown error(not a primary lessor )"`).
3) Create a new lease.
4) Try to keep it alive with `KeepAlive`.

**Expected behavior:**
We expected client to recover from `recvKeepAliveLoop` error after some time and continue to process leases. Alternatively we expected `KeepAlive` to return error immediately due to broken `recvKeepAliveLoop`, so we can restart client manually, at least.

**Observed behavior:**
User of `KeepAlive` freezes because returned channel is never closed, after `keepAliveCtxCloser` exits on [`<-l.donec`](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/lease.go#L275) case in select due to `recvKeepAliveLoop` [signal](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/lease.go#L333). User code assumes that keep alive still works and expects responses or close of the channel, but none of these events happens.

**Side notes**
We used `concurrency.Session` to control the lease, and in this case it leads to [goroutine leak](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/concurrency/session.go#L59) and freeze of `session.Close` (or more precisely [session.Orphan](https://github.com/coreos/etcd/blob/83347907774bf36cbb261c594a32fd7b0f5dd9f6/clientv3/concurrency/session.go#L84)).

**Comment by dennwc** [comment]
@heyitsanthony This issue still effects us on master branch. I'll provide a case to reproduce soon.

Also, #6929 is server-side and does not prevent `session.Orphan` to freeze on any other error returned by `recvKeepAliveLoop` internals.

I propose to include https://github.com/dennwc/etcd/commit/5cafc490d669491edb26e78ba717e6dac8ae5063 as a client-side fix as well, so clients can at least detect that something gone wrong.

**Comment by xiang90** [comment]
> . I'll provide a case to reproduce soon.

Ideally a test case?

**Comment by dennwc** [comment]
@xiang90 I'll provide a small reproducer, but I'm not familiar with etcd tests, thus it may take time to do it properly as a test case.

**Comment by heyitsanthony** [comment]
I think this can be reproduced by closing the lease interface and trying to open a new keepalive channel.

**Comment by dennwc** [comment]
@heyitsanthony Correct. But we also have a case for two-node cluster that will kill `recvKeepAliveLoop` while keeping client alive. In both cases I think client should be fixed to close channel always, or return an error, as in my quick-fix.

**Comment by heyitsanthony** [comment]
Wouldn't it be the same path? If the lease interface is closed iff donec is closed. If the keepalive loop gets a halting error, donec is closed so the interface is effectively closed as well.

**Comment by dennwc** [comment]
@heyitsanthony Sure, it's the same code path for deadlock. I'm just trying to say that there is a second bug with that loop.

**Comment by heyitsanthony** [comment]
@dennwc huh? Isn't the client bug that it's creating a keepalive channel after the loop is shutdown? If so, what is the difference between receiving a halting error and closing the interface?

**Comment by dennwc** [comment]
@heyitsanthony It's correct. But we also expect this loop to retry in case of non-fatal errors. Let me describe the case we hit today.

We could reproduce it with a cluster of 2 nodes. Client connects to first one, creates a new session each ~1min, closes it and keep doing it in a loop. If node 2 is shut down, and restarted after some time, client will observe that keep alive loop exited with `connection is closing` error, while etcd client is still alive and can serve other requests.

**Comment by dennwc** [comment]
something like this, I guess:
```Go
func TestV3LeaseFreeze(t *testing.T) {
	clus := NewClusterV3(t, &ClusterConfig{Size: 2})
	defer clus.Terminate(t)

	cli1 := clus.Client(0)

	sess, err := concurrency.NewSession(cli1)
	if err != nil {
		t.Fatal(err)
	}
	
	clus.Members[1].Stop(t)
	time.Sleep(time.Minute/2)
	clus.Members[1].Resume()
	
	ch := make(chan struct{})
	go func(){
		defer close(ch)
		sess.Close()
	}()
	select{
	case <-ch:
	case <-time.After(time.Second*30):
		t.Fatal("timeout")
	}
}
```

**Comment by heyitsanthony** [comment]
OK, interesting. You're right that a connection closing error shouldn't be treated as a halting error when the client's grpc connection still live.

**Comment by dennwc** [comment]
@heyitsanthony Here is the test that fails for me (on a9f72ee0d41247938cac81105482bfd810623c5c). It's a bit racy, so it might pass few times.

```Go
func TestV3LeaseFreezeS(t *testing.T) {
	clus := NewClusterV3(t, &ClusterConfig{Size: 2})
	defer clus.Terminate(t)

	cli := clus.Client(0)

	check := func(i int) error {
		sess, err := concurrency.NewSession(cli)
		if err != nil {
			return err
		}
		ch := make(chan struct{})
		go func(){
			defer close(ch)
			sess.Close()
		}()
		select{
		case <-ch:
		case <-time.After(time.Minute/4):
			return fmt.Errorf("timeout %d",i)
		}
		return nil
	}

	errc := make(chan error, 2)
	var wg sync.WaitGroup
	wg.Add(1)
	go func(){
		defer wg.Done()
		if err := check(-1); err != nil {
			errc <- err
		}
	}()

	clus.Members[1].Stop(t)
	time.Sleep(time.Second*5)
	clus.Members[1].Restart(t)
	time.Sleep(time.Second*5)

	select {
	case err := <-errc:
		t.Fatal(err)
	case <-time.After(time.Second*10):
	}
	for i:=0; i < 5; i++ {
		ch := make(chan struct{})
		go func(){
			if err := check(i); err != nil {
				errc <- err
			} else {
				close(ch)
			}
		}()
		select {
		case <-ch:
			time.Sleep(time.Second*2)
		case err := <-errc:
			t.Fatal(err)
		}
	}
	wg.Wait()
	select {
	case err := <-errc:
		t.Fatal(err)
	default:
	}
}
```

**Comment by heyitsanthony** [comment]
@dennwc does #7010 fix that test or only the close/halting error bug?

**Comment by dennwc** [comment]
It only returns an explicit error if keep alive loop exits, so there will be no resource leak at least.

**Comment by dennwc** [comment]
An error that makes loop fail in the test is `rpc error: code = 1 desc = context canceled (*grpc.rpcError)`

**Comment by heyitsanthony** [comment]
OK, I can repro with that test. I'll see if I can cook up a fix. Thanks!
