### ISSUE TITLE
Question about topology

### ISSUE THREAD

**Issue by Supernomad** [coreos/etcd#6927]
So I have a general question about etcd cluster topology. I currently have a 3 node server cluster running in new york city, with around 100 or so etcd proxy cluster members. Some of these proxy members are great distances away from each other, with proxies as far away as japan/singapore and south africa. 

My question is whether or not this is a scalable topology, and if it is not what would be recommended to replace it?

Some details:
- Highly geographically distributed system reaching all corners of the globe, running as one cluster of proxies/cluster nodes.
- The number and rate of change for the data within etcd is minimal.
- There will however be a large number of reads and lists over directories.
- There will also be a large amount of watches set from multiple clients on the same keys.
- The amount of data is trivial at a few hundred keys with small json blob values, _maybe_ reaching a thousand or two keys over time.

I appologize in advance if there is not enough information, or this is not the appropriate forum to ask this kind of question.

**Comment by gyuho** [comment]
Please see https://github.com/coreos/etcd/blob/master/Documentation/tuning.md#time-parameters?

**Comment by Supernomad** [comment]
Thank you for the direction, going to close this out as that gives me a good sense of the situation.

**Comment by xiang90** [comment]
I do not think it will really hurt the performance that much given your workload. The latency might be worse, but that should be expected anyway.

**Comment by xiang90** [comment]
@Supernomad So please give it a try. If there is any unexpected performance issue, please report back. We would love to look into it.
