### ISSUE TITLE
move data to another cluster

### ISSUE THREAD

**Issue by gitoverflow** [coreos/etcd#6939]
What is the easiest way, to move all data from one etcd cluster to another, which does already exist ?

Specifically:

I want the kubernetes api server to permanently use another etcd cluster right after the initial kubernetes/etcd cluster are created without loosing the initial stored data from the first cluster.

**Comment by heyitsanthony** [comment]
Have you tried snapshots? https://github.com/coreos/etcd/blob/master/etcdctl/README.md#snapshot-subcommand

**Comment by armstrongli** [comment]
@gitoverflow Please create another etcd cluster with the original data you have and configure the kubernetes apiserver to use the new etcd cluster.
Then there won't be any data lose and the new kubernetes cluster working on the old data.

**Comment by xiang90** [comment]
@gitoverflow As mentioned above, you can either:

1. do a backup and then restore (search in etcd repo to see how to do this for both v2 and v3)
2. copy the data dir and restart on the same node
