### ISSUE TITLE
Proper embedding to own program

### ISSUE THREAD

**Issue by vtolstov** [coreos/etcd#6940]
This is not bug, but question.
I don't want to run separate etcd instance, but want to integrate etcd into own program.
What is the proper way to do that (in case of master branch). I found some info about etcdmain and embed packages. What is the proper way now?

**Comment by heyitsanthony** [comment]
https://godoc.org/github.com/coreos/etcd/embed

**Comment by heyitsanthony** [comment]
Closing if no other questions...
