### ISSUE TITLE
Put take too long time

### ISSUE THREAD

**Issue by johnnyluo586** [coreos/etcd#6968]
➜  etcd ./etcd --version
etcd Version: 3.1.0-rc.1
Git SHA: 3d5ba43
Go Version: go1.7.3
Go OS/Arch: linux/amd64

➜  etcd ETCDCTL_API=3 ./etcdctl put /dlocker/aaa 1

when i run the etcdctl many times, there will be log this, and  i use clientv3 also have the problem.

2016-12-09 16:03:21.925822 W | etcdserver: apply entries took too long [202.238741ms for 1 entries]
2016-12-09 16:03:21.925846 W | etcdserver: avoid queries with large range/delete range!

**Comment by gyuho** [comment]
Does etcd run on HDD?

**Comment by johnnyluo586** [comment]
yes, so it must run on SSD when using etcd v3

**Comment by xiang90** [comment]
@johnnyluo586 https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean should provide enough information on this question.
