### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [coreos/etcd#6969]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product (if anything has been found) :)

Michiel

**Comment by philips** [comment]
Hello Michiel-

etcd has not had a third-party audit done by the etcd community itself. There are other users who have done independent audits but those results have not been made public. If you would be willing to publicize the results of your audit we would appreciate it.

However, if you do find an issue that you feel is security sensitive I would ask you give the CoreOS security team a chance to responsibly handle the issue and make a release: https://coreos.com/security/disclosure/

Thank You!

Brandon

(I am closing this as it is a question and not an issue)
