### ISSUE TITLE
enabling etcd AUTH without expect

### ISSUE THREAD

**Issue by michael-px** [coreos/etcd#6976]
I'm trying to automate a containerized (and maybe even the stand alone server version) of etcd. Our product uses etcd 2.3.7 for the time being and I've put it into the same container as our product to allow for an internal server if the customer doesn't want to provide their own.

But I can't seem to setup an AUTH password except by typing

**etcdctl user add root** 

on a terminal session.  This can't be automated without using expect.  How can users be added without a terminal session?

https://coreos.com/etcd/docs/latest/authentication.html

**Comment by gyuho** [comment]
You can interact with etcd using client https://godoc.org/github.com/coreos/etcd/client.

This is what `etcdctl` is using.

**Comment by michael-px** [comment]
So, I could use curl calls to create a root user as described here

https://coreos.com/etcd/docs/latest/auth_api.html

**Comment by gyuho** [comment]
Yeah `curl` should work as well. Thanks.
