### ISSUE TITLE
The roles: leader and follower

### ISSUE THREAD

**Issue by shuqilou** [coreos/etcd#6982]
situation:
1. If I cut down the leader, remove the data-dir, and then add the node to the cluster again with the -initial-cluster-state=existing, the node can add in the cluster successfully.  
2. If I cut down one follower, remove the data-dir, and then add the node to the cluster again with the -initial-cluster-state=existing, the node can not add in the cluster successfully.

what's the difference between the leader and the follower? The phenomenon is very weried which let me confused! Hope for your help!!!

**Comment by xiang90** [comment]
You should never do that. If you lost the data dir, you need to remove the node from the cluster.

If you remove the data dir, you should not add the member into the cluster again. etcd has some internal checking to detect that operational error. In some cases, it might not be accurate.

**Comment by shuqilou** [comment]
"In some cases, it might not be accurate." 
Which case can lead to unaccurate? BTW, I have tested for many times and the situation happened all the time. The difference between leader and follower does exist. It is not random.

**Comment by xiang90** [comment]
@shuqilou 

Please read https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#replace-a-failed-machine about how to replace a failed member.

I already told you what you did is wrong. The behavior is undefined. If you want to understand the internal, you can read the code in raft pkg.
