### ISSUE TITLE
RFC: add cache to serve range request?

### ISSUE THREAD

**Issue by mqliang** [coreos/etcd#6986]
The etcdv3 mvcc implementation saves all data to disk using boltdb(with revision as key in boltdb), and uses an in-memory btree to map key->revsions. When server serve a range request, it first fetch all revisions about a range from btree, the using the revisions to retreive data from boltdb. In other words, every range request actually needs to access disk.

It seems reasonable to maintain a in-memory lru cache(or a full cache, just save key and value with the latest revision), so that server can serve range request from memory directly

**Comment by xiang90** [comment]
No. Boltdb is a mmaped btree. OS will do page cache for us.
