### ISSUE TITLE
should clientv3.Client.Close method also close the Lease

### ISSUE THREAD

**Issue by chanxuehong** [coreos/etcd#6987]
see  
https://github.com/coreos/etcd/blob/master/clientv3/client.go#L88

should this also close the Client.Lease, like 

https://github.com/coreos/etcd/blob/master/clientv3/client.go#L90

thank you.

**Comment by chanxuehong** [comment]
@heyitsanthony I have not saw any problems. I just view the source code and have a little problem about this.
thank you for you response.

**Comment by xiang90** [comment]
@heyitsanthony @chanxuehong 

So should we add lease.Close to make the code more readable?
