### ISSUE TITLE
cluster performance validation script

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#6991]
Suppose someone sets up an etcd cluster on some virtual machines built from duct tape, bubble gum, and salvaged electrical wire. The cluster's accepting key writes from etcdctl so everything looks good. After running it for five minutes as production, the etcd cluster surprisingly topples over.

Instead, there should be a script to run beforehand to judge whether the new cluster can handle running etcd with some workload.

**Comment by xiang90** [comment]
The configuration should like

```
write qps/size
read qps/size
watch qps/size
```

The tool should also grep the metrics from etcd, and say either

```
OK.
Disk too slow.
CPU too slow.
Network too slow.
Not sure, but slow.
```

**Comment by xiang90** [comment]
fixed by https://github.com/coreos/etcd/pull/7591
