### ISSUE TITLE
etcd health is false

### ISSUE THREAD

**Issue by WhtAlpha** [coreos/etcd#6998]
**Dec 14 10:42:33 xt1 docker: 2016-12-14 02:42:33.263136 E | rafthttp: streaming request ignored (cluster ID mismatch got be2748a4855d6268 want 7ec315417ba8eeff)
Dec 14 10:42:33 xt1 journal: 2016-12-14 02:42:33.262905 E | rafthttp: streaming request ignored (cluster ID mismatch got be2748a4855d6268 want 7ec315417ba8eeff)
Dec 14 10:42:33 xt1 journal: 2016-12-14 02:42:33.263136 E | rafthttp: streaming request ignored (cluster ID mismatch got be2748a4855d6268 want 7ec315417ba8eeff)
Dec 14 10:42:33 xt1 lvm[1170]: Insufficient free space: 8602 extents needed, but only 81 available
Dec 14 10:42:33 xt1 lvm[1170]: Failed to extend thin rootvg-docker--pool.
Dec 14 10:42:33 xt1 docker: 2016-12-14 02:42:33.364342 E | rafthttp: streaming request ignored (cluster ID mismatch got be2748a4855d6268 want 7ec315417ba8eeff)
Dec 14 10:42:33 xt1 docker: 2016-12-14 02:42:33.364604 E | rafthttp: streaming request ignored (cluster ID mismatch got be2748a4855d6268 want 7ec315417ba8eeff)
Dec 14 10:42:33 xt1 journal: 2016-12-14 02:42:33.364342 E | rafthttp: streaming request ignored (cluster ID mismatch got be2748a4855d6268 want 7ec315417ba8eeff)**

my log like this, I have no idea.

**Comment by gyuho** [comment]
How did you start your etcd cluster?

**Comment by heyitsanthony** [comment]
@WhtAlpha this happens when members from one etcd cluster are pointed to another etcd cluster. Usually this happens after tearing down an old cluster then reusing the same addresses for the new cluster; if any processes from the old cluster are still running they'll try to contact the new cluster. The new cluster will ignore the request and emit this warning.

**Comment by xiang90** [comment]
@heyitsanthony 

Can you add the information you provided to https://github.com/coreos/etcd/blob/master/Documentation/faq.md?

Also probably we can try to make the error logging more obvious? [Contacting a member in other cluster] or something like that?

**Comment by xiang90** [comment]
@WhtAlpha @heyitsanthony recently add the answer to your issue to faq doc here: https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-request-ignored-cluster-id-mismatch-mean

so i am closing this question.
