### ISSUE TITLE
[root@bogon gofile]# which etcd &>/dev/null || go get github.com/coreos/etcd # github.com/coreos/etcd/proxy/grpcproxy src/github.com/coreos/etcd/proxy/grpcproxy/watch_client_adapter.go:36: cannot use wserver (type *ws2wcServerStream) as type etcdserverpb.Watch_WatchServer in argument to s.wserv.Watch:         *ws2wcServerStream does not implement etcdserverpb.Watch_WatchServer (missing SetHeader method)

### ISSUE THREAD

**Issue by wnaghuixin** [coreos/etcd#7000]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on
[reporting bugs][report_bugs] before you submit your bug report. 

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by gyuho** [comment]
What grpc version do you have? `SetHeader` is a new method in latest grpc version.

**Comment by heyitsanthony** [comment]
Huh? This was fixed in 7ef17d3e971366c870b842824fa5636dda4da22c. Pretty sure this issue duplicates #6726

Try `go get github.com/coreos/etcd/cmd/etcd` to use vendoring instead of building with gopath packages?

**Comment by xiang90** [comment]
closing. @heyitsanthony has the answer.
