### ISSUE TITLE
restart etcd panic with unexpected smaller revision in mvcc

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#7011]
I use docker-compose to start pd cluster (mount pd data to local directory), and when I recreate the cluster with `docker-compose up -d --force-recreate`, I meet following panic:

```
2016/12/15 09:43:35 util.go:329: [info] I | membership: [set the cluster version to 3.0 from store]
2016/12/15 09:43:36 util.go:321: [fatal] C | mvcc: [store.keyindex: put with unexpected smaller revision [{65178 0} / {65178 0}]]
```

The embed etcd version is e53b99588a05d1f4ef172c178d4ed8e8106b8be4

**Comment by xiang90** [comment]
Do you still have the data dir around. Mind sharing that broken data dir?

**Comment by xiang90** [comment]
If you can reproduce the problem, can you try to update the etcd version to current master and see if you can still reproduce?

**Comment by siddontang** [comment]
@xiang90 

[pd.tar.gz](https://github.com/coreos/etcd/files/653682/pd.tar.gz)

**Comment by siddontang** [comment]
We will update the etcd and try to reproduce it.

**Comment by xiang90** [comment]
Thanks

**Comment by xiang90** [comment]
@siddontang I can confirm this is a bug. Probably from upstream boltdb. We will investigate more.

**Comment by xiang90** [comment]
Opened an issue on upstream boltdb: https://github.com/boltdb/bolt/issues/632

**Comment by xiang90** [comment]
Never hit this again. It seems like a bug outside etcd system really. Closing.

**Comment by gaddamas** [comment]
I got similar message "mvcc: store.keyindex: put with unexpected smaller revision [{200001 0} / {200001 0}]. what does it mean? could you please give technical description.

**Comment by fOO223Fr** [comment]
any update on this problem?

**Comment by seamounts** [comment]
any update on this problem?

**Comment by liangguohun** [comment]
how did you do to fix it， and keep your data..

**Comment by drtechco** [comment]
https://gist.github.com/drtechco/3773a8e0e7a692fabe8cefd3ca102180
