### ISSUE TITLE
Errors when closing embedded etcd

### ISSUE THREAD

**Issue by necro351** [coreos/etcd#7019]
Hello,

I am trying to close an embedded etcd server and am getting error messages when doing so. I am using the github.com/coreos/etcd/embed package to run the embedded etcd server. I am using code that is pretty much the same as the example. First I start the server, then I close it, and while closing I see the error messages. Here is how I start the server:

```
   // Start embedded etcd server
   cfg := embed.NewConfig()
   cfg.Dir = LocalConfig
   cluster.etcd, err = embed.StartEtcd(cfg)
   if err != nil {
      plog.Fatal(err)
   }
   select {
   case <-cluster.etcd.Server.ReadyNotify():
      plog.Info("Server is ready!")
   case <-time.After(StartEtcdTimeoutSeconds * time.Second):
      cluster.etcd.Server.Stop() // trigger a shutdown
      err = fmt.Errorf("Etcd erver took too long to start!")
      return
   }
   cluster.etcdErrLoggerNotify = make(chan int)
   go func() {
      for {
         select {
         case err := <-cluster.etcd.Err():
            plog.Error(err)
         case <-cluster.etcdErrLoggerNotify:
            return
         }
      }
   }()
```

...and here is how I close it:

```
   c.etcd.Close()
   c.etcdErrLoggerNotify <- 1
```

...and here are the error messages I get when I do this:

```
2016-12-16 00:25:26.112883 E | shard: accept tcp 127.0.0.1:2380: use of closed network connection
2016-12-16 00:25:26.112921 E | shard: accept tcp 127.0.0.1:2379: use of closed network connection
2016-12-16 00:25:26.113062 E | shard: mux: listener closed
2016-12-16 00:25:26.113077 E | shard: mux: listener closed
```

I should point out that when I use the official stand-alone etcd binary in the same environment that I run my go program with embedded etcd that I do not get these error messages. I should also point out that I can connect to the embedded etcd server with the clientv3 within my go program, and based on log output, I only see these error messages when closing it. Finally, just to be clear, the error messages are coming to me from the error channel and then my package 'shard' prints them.

How do I close the embedded server without causing errors? Thanks!

**Comment by gyuho** [comment]
Try

```
c.etcd.Close()
<-c.etcd.Err()
```
?

**Comment by heyitsanthony** [comment]
@necro351 those errors are from shutting down the http handlers (e.g., https://github.com/coreos/etcd/blob/master/embed/serve.go#L87). They're to be expected given the way it's implemented now, but it could be changed to drop those errors if it's from an intentional close.

**Comment by necro351** [comment]
@gyuho I guess you mean that I can ignore any errors after calling Close(), but If there are any legitimate errors when Closing (i.e., an error other than http complaining about reset connections), they would be dropped this way right?

@heyitsanthony this is an intentional close: I am gracefully shutting down the surrounding application (which is also a server), and part of that is (gracefully) shutting down the embedded etcd. After your explanation, it looks like this is close to nitpicking I guess, but at least in cases where you expect log output to be clean (e.g., a regression test) it's not right now, unless I do something like what @gyuho recommends. I could do that, but it is not entirely clean either, and the best practice for closing the server w.r.t. this issue is undocumented. Your call. Thanks for the quick response!

**Comment by gyuho** [comment]
@necro351 I just noticed that your code waits on `Err`. Never mind.

**Comment by fanminshi** [comment]
Taking a look.
