### ISSUE TITLE
go-grpc-prometheus histograms are not enabled

### ISSUE THREAD

**Issue by crandles** [coreos/etcd#7024]
Prior to 3.1.0-rc.1, ETCD's prometheus metrics included histograms.

3.1.0-rc.1 uses go-grpc-prometheus, and requires users to [enable histograms manually](https://github.com/grpc-ecosystem/go-grpc-prometheus#histograms). Should ETCD enable that by default or provide a flag/env for users to enable that via the CLI?

**Comment by xiang90** [comment]
@crandles Probably we should disable by default as https://github.com/grpc-ecosystem/go-grpc-prometheus#histograms suggests. I am fine with a flag to enable it. 

@heyitsanthony opinions?

**Comment by heyitsanthony** [comment]
A flag sounds OK.

**Comment by xiang90** [comment]
@crandles Do you want to send a pull request to add the flag?

**Comment by crandles** [comment]
@xiang90 yes, I can do that.
