### ISSUE TITLE
raft: MemoryStorage.SetHardState() should be thread safe?

### ISSUE THREAD

**Issue by m1093782566** [coreos/etcd#7031]
```
// SetHardState saves the current HardState.
func (ms *MemoryStorage) SetHardState(st pb.HardState) error {
	ms.hardState = st
	return nil
}
```

See https://github.com/coreos/etcd/blob/master/raft/storage.go#L100

It seems that few application will use `MemoryStorage` directly, but should the method SetHardState() be thread safe?

**Comment by xiang90** [comment]
SetHardState usually happens when raft is not started. But it does not hurt to protect it to make code more readable and robust. Can you send a pull request to get it fixed?
