### ISSUE TITLE
NOT set e.Node.Dir attribute, when dir node expired

### ISSUE THREAD

**Issue by jl2005** [coreos/etcd#7033]
Consider the following:

```
$ curl http://127.0.0.1:2379/v2/keys/dir  -X PUT -d dir=true -d ttl=20
{"action":"set","node":{"key":"/dir","dir":true,"expiration":"2016-12-19T03:25:07.444794177Z","ttl":20,"modifiedIndex":23447730,"createdIndex":23447730}}

$ curl -L http://127.0.0.1:2379/v2/keys/dir?wait=true
{"action":"expire","node":{"key":"/dir","modifiedIndex":23447765,"createdIndex":23447730},"prevNode":{"key":"/dir","dir":true,"expiration":"2016-12-19T03:25:07.444794177Z","modifiedIndex":23447730,"createdIndex":23447730}}
```

When a directory node expired, the `prevNode` has a `"dir":true` attribute in the received expire event, but the `node` has no `"dir":true` attribute

**Comment by gyuho** [comment]
This is expected, because the node(key) that's expired does not exist in store anymore.

Is there any specific reason that you need `"dir": true` in `"expire"` node event?

**Comment by jl2005** [comment]
In my code, we need `"dir":true` to determine further operations. 
`Dir` is the basic attribute of a node. In the `Delete` action report, it contain the `Dir` attribute.

```
{"action":"delete","node":{"key":"/dir","dir":true,"modifiedIndex":3729,"createdIndex":3724},"prevNode":{"key":"/dir","dir":true,"modifiedIndex":3724,"createdIndex":3724}}
```

**Comment by gyuho** [comment]
Defer to @xiang90
