### ISSUE TITLE
raft: resume a paused follower after receiving a heartbeat

### ISSUE THREAD

**Issue by petermattis** [coreos/etcd#7037]
Currently, `bcastHeartbeatWithCtx` resumes any paused follower:

```
func (r *raft) bcastHeartbeatWithCtx(ctx []byte) {
	for id := range r.prs {
		if id == r.id {
			continue
		}
		r.sendHeartbeat(id, ctx)
		r.prs[id].resume()
	}
}
```

The upshot of doing this is that any subsequent activity on the Raft group which results in a call to `raft.sendAppend` (such as a proposal) will generate a `MsgApp` for the follower even though the Raft group hasn't received a heartbeat response yet. In CockroachDB we've noticed that an active Raft group with one follower on a temporarily down node will generate a significant amount of `MsgApp` traffic that we can be reasonably sure will be dropped at the RPC layer.

Is there a reason for resuming the follower when sending the heartbeat? It seems more natural to resume the follower when `MsgHeartbeatResp` is received and doing so would prevent the above unnecessary activity.

Cc @spencerkimball, @bdarnell

**Comment by xiang90** [comment]
@petermattis 

If I remember this correctly, we were worrying about systems like CockroachDB can drop/ignore heartbeats for various reasons (link layer health checking, heartbeat coalescing). So no response will be received.

**Comment by petermattis** [comment]
@xiang90 Leaving the follower "paused" while waiting for the heartbeat response only blocks append requests to that follower. That seems desirable to me. I must be missing something about your statement that "we do not want to block append requests".

**Comment by xiang90** [comment]
> Leaving the follower "paused" while waiting for the heartbeat response only blocks append requests to that follower. That seems desirable to me.

As I mentioned, the heartbeat response might not be received. The the append requests will be blocked for a long time for that peer.

If Cockroach use case is fine, I am OK. The only downside to us is that the caching up phase might delay for ~10ms, which is not a problem at all for us.

**Comment by petermattis** [comment]
> As I mentioned, the heartbeat response might not be received. The the append requests will be blocked for a long time for that peer.

Ah, got it. Blocked for a long time means blocked until we receive a `MsgHeartbeatResp`. That seems like a fine trade-off to me vs constantly generating `MsgApp` traffic which will be dropped on the floor. Curious to know what @bdarnell thinks.

**Comment by petermattis** [comment]
https://github.com/coreos/etcd/compare/master...petermattis:pmattis/resume-after-heartbeat-resp shows what would be required. I'll send the PR once discussion is concluded here.

**Comment by bdarnell** [comment]
Yes, I think the follower should be resumed when MsgHeartbeatResp is received, not when MsgHeartbeat is sent. In fact, I thought it already worked this way, and in all the special tricks we do with heartbeats we have made sure to send heartbeat responses to raft for this reason.
