### ISSUE TITLE
kubernetes deploy  

### ISSUE THREAD

**Issue by dearboll** [coreos/etcd#7038]
Hi all, 
    when I deploy the etcd cluster on kubernetes via the [guide](https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy), I find my pod cannot find each other.
![image](https://cloud.githubusercontent.com/assets/5729929/21336947/feed0f20-c6a3-11e6-9868-a9032cdd5a83.png)
    Should I modify the /etc/hosts file and add the mapping of etcd0, etcd1 and etcd2 with their IP?

**Comment by xiang90** [comment]
This issue is already resolved in etcd dev google group. this is a dup. so closing.
