### ISSUE TITLE
Query : etcdserver/server.go : compactor.Resume in case of not Leader

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#7040]
https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L637-L644
 ```
 etcdserver/server.go 
 624         leadershipUpdate: func() {
 625             if !s.isLeader() {
 626                 if s.lessor != nil {
 627                     s.lessor.Demote()
 628                 }
 629                 if s.compactor != nil {
 630                     s.compactor.Pause()
 631                 }
 632                 setSyncC(nil)
 633             } else {
 634                 setSyncC(s.SyncTicker)
 635             }
 636 
 637             // TODO: remove the nil checking
 638             // current test utility does not provide the stats
 639             if s.stats != nil {
 640                 s.stats.BecomeLeader()
 641             }
 642             if s.compactor != nil {
 643                 s.compactor.Resume()
 644             }
 645             if s.r.td != nil {
 646                 s.r.td.Reset()
 647             }
 648         },
 649     }

```

In the above code, L637-644 , shouldn't this code be in the else case of ` if !s.isLeader()` ? 
here it seems that if the server is not a leader, the compactor is Paused and immediately Resumed. same for stats.
i didn't understand why.

**Comment by heyitsanthony** [comment]
@vimalk78 `BecomeLeader` is OK since the stats code checks the leadership status. The `Resume` looks wrong, though.

**Comment by vimalk78** [comment]
the `ServerStats` changes the `raft State` based on invocation of `RecvAppendReq , SendAppendReq` , so it will eventually correct itself.

Also, the `lesser.Promote` is invoked after applying the `noop` entry from the new leader, but `server stat` and `compactor` leadership change is handled in the `etcdserver.raftNode` after reading the `Ready` channel. is it something to do with the order of applying entries? or the fact that the `lesser` is a part of user of raft library and any communication to user layer is via the apply channel?

**Comment by vimalk78** [comment]
and btw, should i move the compactor in the else block?

```
etcdserver/server.go :
 636             } else {
 637                 setSyncC(s.SyncTicker)
 638                 if s.compactor != nil {
 639                     s.compactor.Resume()
 640                 }
 641             }

```

**Comment by heyitsanthony** [comment]
@vimalk78 the comment explains why the lessor is promoted in `applyEntryNormal` instead of `leadershipUpdate`-- the promote only happens after the last committed entries are applied. I think the reason for this is to avoid accepting lease refreshes on a new leader if those leases that have already been deleted.

Please submit a PR for the compactor stuff. Thanks!
