### ISSUE TITLE
Query : quota-backend-bytes max value

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#7045]
hi, is there any reason for the 8 GB limit on the keyspace memory size? is it a boltdb limitation?

```
 46 const (
 47     // DefaultQuotaBytes is the number of bytes the backend Size may
 48     // consume before exceeding the space quota.
 49     DefaultQuotaBytes = int64(2 * 1024 * 1024 * 1024) // 2GB
 50     // MaxQuotaBytes is the maximum number of bytes suggested for a backend
 51     // quota. A larger quota may lead to degraded performance.
 52     MaxQuotaBytes = int64(8 * 1024 * 1024 * 1024) // 8GB
 53 )   

```

`--quota-backend-bytes` can have a default value of 2GB and if set to -ve, disable the quota, and let user define the limit by setting to some value.
so no need of Default and Max Quota. only one Quota value is enough.

**Comment by gyuho** [comment]
See this https://groups.google.com/d/msg/etcd-dev/vCeSLBKC_M8/2pPBXpc9BwAJ

> The main reason of the size limit is MTTR `mean time to recovery`.
> 
> etcd is designed to be a highly available storage. It replicates all data across all nodes. If you lose a etcd member, simply adding a member should bring
the cluster back to full health state within 10s of seconds with little impact on the overall performance.
> 
> Typically, we can recover 2GB of data within 20 seconds on good hardware. We cannot do that for 1TB data due to today's hardware limitation. If you do not care about MTTR, you can in theory to store 1TB in etcd.
> 
> There are people making multiple consistent kv groups into a logic unified kv space: see Tikv or Cockroachdb's kv layer. Basically the physical consistent storage layer is well partitioned, with a logic proxy layer to make the kv space seems to be unified. But that all comes with cost, and a pretty expensive cost for cross kv groups consistency.
> 
> etcd's main use case is for storing metadata. We want to ensure there is no additional cost for that use case. We might make etcd proxy to be able to talk to multiple actual etcd clusters with some API limitation in the future. So you can get the same feeling that etcd is horizontal scalable.

**Comment by xiang90** [comment]
@gyuho I will make this into faq soon.

**Comment by gyuho** [comment]
Yeah let's put this into FAQ.

**Comment by vimalk78** [comment]
thanks @gyuho  @xiang90 :+1:
