### ISSUE TITLE
Etcd database space exceeded exception for 8M keys

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#7047]
On setting up a cluster of 5 with 2grpc proxies and performed put operation using 5 clients putting, update and get on 1.6M keys on each client. While performing the operation its giving the error; rpctype.EtcdError=etcddserver:mvcc:database space exceeded. 
Is there anyway to increase the database size?

**Comment by gyuho** [comment]
https://github.com/coreos/etcd/blob/master/etcdmain/help.go#L61

`--quota-backend-bytes` flag can be used to configure quota size

**Comment by xiang90** [comment]
also see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota

**Comment by sinsharat** [comment]
@gyuho @xiang90 Thanks for help.

**Comment by sinsharat** [comment]
@xiang90 what is the suitable size you suggest to keep for around 10M keys for --quota-backend-bytes?

**Comment by xiang90** [comment]
@sinsharat Depends on your key size. You probably can do the calculation yourself. But if you can, keep total data size within 4GB.

**Comment by sinsharat** [comment]
@xiang90 Sure thanks!
