### ISSUE TITLE
There're no output of cluster info in etcdctl v3

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#7049]
There're output in v2
```go
...
	fmt.Printf("Added member named %s with ID %s to cluster\n", newName, newID)
...
	fmt.Print("\n")
	fmt.Printf("ETCD_NAME=%q\n", newName)
	fmt.Printf("ETCD_INITIAL_CLUSTER=%q\n", strings.Join(conf, ","))
	fmt.Printf("ETCD_INITIAL_CLUSTER_STATE=\"existing\"\n")
}
```

But they are gone in v3
```
...
	fmt.Printf("Member %16x updated in cluster %16x\n", id, resp.Header.ClusterId)
}
```

**Comment by armstrongli** [comment]
Finished in PR: https://github.com/coreos/etcd/pull/7050

**Comment by armstrongli** [comment]
@fanminshi The CI can't pass. Could you help re-trigger it?

**Comment by fanminshi** [comment]
@armstrongli sorry for the delay, let me check.

**Comment by fanminshi** [comment]
Usage of the v2 output is shown here, https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member

The v2 add member output generates necessary env variables to help user to start the newly added member. 

The v3 is missing that.
