### ISSUE TITLE
etcd v3 iops is much higher than etcd v2

### ISSUE THREAD

**Issue by ringtail** [coreos/etcd#7055]
I upgrade etcd from v2.2.2 to etcdv3.0.13 and I found the iops is much higher than before.

**Comment by ringtail** [comment]
![image](https://cloud.githubusercontent.com/assets/3116693/21446094/d59fcc42-c8fc-11e6-9396-d4aa308855f8.png)
![image](https://cloud.githubusercontent.com/assets/3116693/21446103/e0348602-c8fc-11e6-9040-7791297843e4.png)
![image](https://cloud.githubusercontent.com/assets/3116693/21446106/e96a437e-c8fc-11e6-98bd-ee4d71f90f21.png)

**Comment by xiang90** [comment]
why closed? maybe the throughput is also higher?

**Comment by ringtail** [comment]
I change vm.dirty_background_bytes to 200000000. I think that is the reason for high iops.
