### ISSUE TITLE
[Question] About etcd/raft wal replay

### ISSUE THREAD

**Issue by upccup** [coreos/etcd#7056]
Thanks for [raftexample](https://github.com/coreos/etcd/tree/master/contrib/raftexample). Now i can start a simple raft cluster, but there is a question about the wal.

  This func [replayWAL](https://github.com/coreos/etcd/tree/master/contrib/raftexample) will replay all my action that i propose before, event if i have been triggered the [saveSnap](https://github.com/coreos/etcd/tree/master/contrib/raftexample) and called rc.wal.ReleaseLockTo().

  In my mind, after called rc.wal.ReleaseLockTo(10), the replayWAL will replay begin at the  10th action.  

  Repaly all old actions is not my need, what can i do now?

**Comment by xiang90** [comment]
@upccup 

I do not think it should replay the entries in the WAL before the snapshot. Can you give us a code example to reproduce the issue?

Also it would be great if you can actually help us fix the bug.

/cc @gyuho @heyitsanthony

**Comment by upccup** [comment]
@xiang90  Thank you for your reply.   
this is the step of my opertation
1. chang [defaultSnapCount](https://github.com/coreos/etcd/blob/master/contrib/raftexample/raft.go#L73), [snapshotCatchUpEntriesN](https://github.com/coreos/etcd/blob/master/contrib/raftexample/raft.go#L327) to 10 that can trigger saveSnapshot quickly.
2. start a single node raft node
3 use **curl -X PUT 127.0.0.1:12380 -D "1111"** 10 times then trigger saveSnapshot and wal.ReleaseLockTo this is the log 
```
save sanpshot in Index:   11
ReleaseLockTo:  11
2016-12-29 11:13:49.273407 I | compacted log at index 1
```
4 now stop raftexample and restart . then a found this still have 11 entries when open wal.

**Comment by xiang90** [comment]
>  then a found this still have 11 entries when open wal.

Can you clarify this? How did you find it out? Logging?

**Comment by upccup** [comment]
@xiang90  yes.  I add a log in https://github.com/coreos/etcd/blob/master/contrib/raftexample/raft.go#L217
