### ISSUE TITLE
V3 "endpoint health" fails with "permission denied"

### ISSUE THREAD

**Issue by sergeyfd** [coreos/etcd#7057]
In V3 "endpoint health" fails with permission denied if authentication is enabled:

bash-4.2$ ETCDCTL_API=3 /usr/bin/etcdctl.sh --endpoints=XXXXXX:2379 --user root:PASSWORD endpoint health

https://XXXXXX:2379 is unhealthy: failed to commit proposal: etcdserver: permission denied

**Comment by mitake** [comment]
Which version are you using? I think your case is same to https://github.com/coreos/etcd/issues/6611
Could you try the latest master? It would solve the problem.

**Comment by sergeyfd** [comment]
Currently we are at 3.0.13. I'll check later versions, thanks.
