### ISSUE TITLE
client, clientv3 pkgs are hard to consume due to footprint, difficulty vendoring 

### ISSUE THREAD

**Issue by alexzorin** [coreos/etcd#7058]
Hi,

I've been using etcd on and off since 2013 - I hope this does not come over as overly critical or negative, sorry if so.

It looks like that at some point that the client and server were merged into one repo. I had been using go-etcd without any problems, it was a fairly [small package](https://godoc.org/github.com/coreos/go-etcd/etcd?import-graph&hide=2).

I'm currently trying to integrate etcd client into some services and unlike before, it has been a very trying experience:

* Pulling `client` or `clientv3` packages in something like Glide (which this project uses) pulls the entire etcd repo, around ~28MB along with the projects own deps. (Not that this is necessary this projects fault, but the tooling works poorly on monorepos like this one).
* clientv3: compile times are slow due to large `.pb.go` files. I am not sure the entire service definition is required for the client. Maybe it is, but is it worth checking? (Granted, pkg cache fixes this, but it does not help when building in Docker. go-etcd has a similar problem with the `go/codec` package too).
* client3 package tends to drag in [the kitchen sink](https://godoc.org/github.com/coreos/etcd/clientv3?import-graph&hide=2)). I understand its necessary for grpc, but some stuff like Prometheus seems questionable.
* Size of etcd client (especially on clientv3) often dwarfs the size of the project consuming it, both in SLOC and contribution to binary size.

My workaround so far has been to strip the etcd repo of all packages that are not required for the v2 client and pushing them to a fork ([v2](https://godoc.org/github.com/coreos/etcd/client?import-graph&hide=2)). Basically, reverting to go-etcd.

I understand that there was probably a good reason for moving the client into the same project. That said, I don't think its unreasonable to say that consuming this package as a client (notably, this this is the official client) is a huge PITA, which is disappointing, because it didn't used to be that way.

I recently used consul Go client package, and it was a pleasure in comparison. It has a [tiny footprint](https://godoc.org/github.com/hashicorp/consul/api?import-graph&hide=2) and compiles fast.

I think this pain is probably felt by others - I saw https://github.com/toqueteos/minietcd as I was researching this problem - it has a similar rationale for existing.

Would it be possible to drag the client back out of this repo? At least, I don't see any other way to address these practical issues of consuming the client, but perhaps others have some ideas.

**Comment by heyitsanthony** [comment]
I agree this is obnoxious. I would like to pull out yaml, grpc-gateway, and prometheus dependencies. Not much can be done about the pb.go files or the grpc dependency.

**Comment by xiang90** [comment]
@heyitsanthony @gyuho 

> Pulling client or clientv3 packages in something like Glide (which this project uses) pulls the entire etcd repo, 

is this true? i think glide supports sub pkg?

**Comment by heyitsanthony** [comment]
@xiang90 it will not pull all of etcd if you only import clientv3 (cf. the import graph) but there's still a lot of code in the deps. It's easy to mistakenly pull the entire repo if you're including etcd/integration for tests, though.

**Comment by xiang90** [comment]
@heyitsanthony I feel so. If most vendor tools pull entire etcd repo for etcd.clientv3, then we have to separate the repo NOW. Or the issue is less serious. And, yes, I agree we should keep the dependencies slim.

**Comment by heyitsanthony** [comment]
@xiang90 if vendor tools pull (for example) etcdserver for only a clientv3 import, they're pulling in more deps than go says it needs; there's even a CI check (https://github.com/coreos/etcd/blob/master/test#L237). I can confirm glide behaves as expected.

**Comment by alexzorin** [comment]
@heyitsanthony 

> I can confirm glide behaves as expected.

Could you show repro of glide doing the right thing wrt clientv3?

```
$pwd
$GOPATH/src/etcdtest

$ cat main.go
package main

import (
        _ "github.com/coreos/etcd/clientv3"
)

func main() {
}

$ glide i
// ... snip

$ du -hs vendor/
28M     vendor/

$ ls vendor/github.com/coreos/etcd
alarm      discovery      etcdserver   proxy     version          DCO                   main.go      test
auth       Documentation  hack         raft      wal              Dockerfile            MAINTAINERS  V2Procfile
client     e2e            integration  rafthttp  build            Dockerfile-release    NEWS
clientv3   embed          lease        scripts   build.bat        etcd.conf.yml.sample  NOTICE
cmd        error          logos        snap      build.ps1        glide.lock            Procfile
compactor  etcdctl        mvcc         store     CONTRIBUTING.md  glide.yaml            README.md
contrib    etcdmain       pkg          tools     cover            LICENSE               ROADMAP.md
```

**Comment by heyitsanthony** [comment]
@alexzorin try:
```sh
glide update --strip-vendor --skip-test
glide vc --only-code --no-tests
```

**Comment by alexzorin** [comment]
Ah, I did not know about `glide-vc`, I had only seen `trash` but it had not been working for me. `vendor`/ is down to 3.0M now, which is a huge improvement. Thanks!

Default behavior notwithstanding, I'm actually pretty happy with this - it's only one extra step in the `Makefile`. Maybe some improvements can be made after the the Go vendoring proposal is finalized.
