### ISSUE TITLE
Leap seconds

### ISSUE THREAD

**Issue by alikhajeh1** [coreos/etcd#7059]
I was just wondering if we need to do anything special with etcd and leap seconds, specifically 23:59:59 appearing twice on 12/31/2016 (https://forums.aws.amazon.com/ann.jspa?annID=4320)

```
etcd Version: 2.3.7
Git SHA: fd17c91
Go Version: go1.6.3
Go OS/Arch: linux/amd64
```

**Comment by heyitsanthony** [comment]
@alikhajeh1 At worst, v2 TTL keys might lose a second on the leap and expire early, depending on how the system clocks are set up. Nothing terribly catastrophic.
