### ISSUE TITLE
raft: Force raft to campaign with vote even preVote is enabled

### ISSUE THREAD

**Issue by es-chow** [coreos/etcd#7061]
In some scenario, by management means one raft member can get the information that another raft member was down, so it can trigger a `MsgVote` other than a `MsgPreVote` even `Config.Prevote` is true. 

Prefering to send `MsgVote` other than `MsgPreVote` is `MsgPreVote` cannot force other raft member to honor this vote to fast recovery from node failure. As other raft members receive `MsgPreVote`, they may ignore this message if their `r.electionElapsed < r.electionTimeout` condition are true when the `Config.ElectionTick` is reasonablely big to tolerating network jitter. 
But in current implementation it's not possible to trigger `MsgVote` as `MsgHup` always trigger a `MsgPreVote` if `Config.Prevote` is true. 

It may be possible to do this by set `Config.Prevote` to false, but prevote is a good feature to avoid disruptive server, so it's good to enable it.

So can we distinguish 2 contexts for `MsgHup` message? One is "Graceful", which is current behavior, another is "Forceful", which will force raft member to do vote by ignore the prevote phase.

**Comment by xiang90** [comment]
@es-chow Can you move this discussion to https://groups.google.com/forum/#!forum/rafte? We  just created a mailing list for raft related discussion.

If you can leave me your email address, I can invite you.

**Comment by es-chow** [comment]
updated in github profile and send an email to you.
Thanks.

**Comment by xiang90** [comment]
this is already posted to the mailing list. We will continue the discussion there.
