### ISSUE TITLE
The data is not big,Why always out of memory？

### ISSUE THREAD

**Issue by lixwlixw** [coreos/etcd#7063]
I installed the etcd of three nodes,Configuration is 2C 4G,version:2.3.7,There is a 2G data,Why always out of memory？

**Comment by xiang90** [comment]
etcd2 only supports 200MB data at most. See https://github.com/coreos/etcd/blob/master/Documentation/v2/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md#data-size-threshold.

Also it is incorrect to assume that 2GB raw data will only consume 2GB memory. Metadata, watchers and other internal components consume memory too.
