### ISSUE TITLE
Expose error type when adding duplicate member that already exists

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#7072]
When calling MemberAdd(), the req could succeed on server side but client side might fail -- e.g. context deadline exceeded. When it retries, client will probably get error message:
```
fail to add new member (test-etcd-bjpp0-0003): rpc error: code = 2 desc = etcdserver: re-configuration failed due to not enough started members
```

It would be better if server could expose an error type that tells if this member has already existed.

**Comment by hongchaodeng** [comment]
@heyitsanthony 
This also raise another question. Why adding the same member addr twice will cause it to add the member second time?

**Comment by xiang90** [comment]
we probably should check the peer url duplication first, then check the availability.

**Comment by gyuho** [comment]
@xiang90 Do we want a new error type? What would be different than `ErrMemberExist`? https://github.com/coreos/etcd/blob/master/etcdserver/api/v3rpc/rpctypes/error.go#L115
