### ISSUE TITLE
ETCD taking a lot of time for load test for put, update and read of 4M keys

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#7074]
**Machine Specifications** : 7 Machines(5 nodes + 2 proxy) of 12 core, 32 GB RAM
**No of concurrent operations for read, update and get operations** : 10
**Total No of keys : 4 Million**
**Total no of client connections** : 2000

**Configuration script for one machine of the cluster:**
ETCDCTL_API=3
TOKEN=token-01
NAME_1=machine-1
NAME_2=machine-2
NAME_3=machine-3
NAME_4=machine-4
NAME_5=machine-5
NAME_6=proxy-1
NAME_7=proxy-2
HOST_1=3.3.0.5
HOST_2=3.3.0.6
HOST_3=3.3.0.7
HOST_4=3.3.0.17
HOST_5=3.3.0.9
HOST_6=3.3.0.10
HOST_7=3.3.0.13
CLUSTER=${NAME_1}=http://${HOST_1}:2380,${NAME_2}=http://${HOST_2}:2380,${NAME_3}=http://${HOST_3}:2380,${NAME_4}=http://${HOST_4}:2380,${NAME_5}=http://${HOST_5}:2380
#For machine 1
THIS_NAME=${NAME_1}
THIS_IP=${HOST_1}
./etcd --quoata-backend-bytes-bytes=$((4*1024*1024*1024)) \
          --data-dir=data.etcd --name ${THIS_NAME} \
          --initial-advertise-peer-urls http://${THIS_IP}:2380 --listen-peer-urls http://${THIS_IP}:2380 \
          --advertise-client-urls http://${THIS_IP}:2379 --listen-client-urls http://${THIS_IP}:2379 \
          --initial-cluster ${CLUSTER} \
          --initial-cluster-state ${CLUSTER_STATE} --initial-cluster-token ${TOKEN}

**Configuration script for one of the two proxy machine:**
ETCDCTL_API=3
TOKEN=token-01
NAME_1=machine-1
NAME_2=machine-2
NAME_3=machine-3
NAME_4=machine-4
NAME_5=machine-5
NAME_6=proxy-1
NAME_7=proxy-2
HOST_1=3.3.0.5
HOST_2=3.3.0.6
HOST_3=3.3.0.7
HOST_4=3.3.0.17
HOST_5=3.3.0.9
HOST_6=3.3.0.10
HOST_7=3.3.0.13
CLUSTER=${NAME_1}=http://${HOST_1}:2380,${NAME_2}=http://${HOST_2}:2380,${NAME_3}=http://${HOST_3}:2380,${NAME_4}=http://${HOST_4}:2380,${NAME_5}=http://${HOST_5}:2380
./etcd grpc-proxy start --listen-addr="${HOST_6}:2379" --endpoints="${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379,${HOST_4}:2379,${HOST_5}:2379"

The load test code is as below:
```
package main

import (
	"context"
	"fmt"
	"log"
	"sync"
	"time"

	"github.com/coreos/etcd/clientv3"
)

func runLoadPUR(getClient getClientFunc, totalClients, noOfKeys, totalConcurrentOp int) {
	fmt.Println("starting load test for put update read operation")
	performPUR(getClient, totalClients, noOfKeys, totalConcurrentOp)
}

func performPUR(getClient getClientFunc, totalClients, noOfKeys, totalConcurrentOp int) {
	ctx := context.Background()
	noOfServices := 100
	prefix := "/ebus/instances/service"
	keys := generateRandomKeys(noOfKeys, noOfServices, prefix)
	val := "{\"serviceName\":\"testFileClientRead\",\"alive\":\"true\",\"type\":\"FILE\"}"

	cl := getClient()
	defer cl.Close()

	var (
		wg     sync.WaitGroup
		err    error
		ctxt   context.Context
		cancel func()
	)

	keysPerConcOp := int(noOfKeys / totalConcurrentOp)
	if noOfKeys%totalConcurrentOp != 0 {
		keysPerConcOp += 1
	}

	clientsPerConcOp := int(totalClients / totalConcurrentOp)

	ctxt, cancel = context.WithCancel(ctx)
	defer cancel()

	var subKeys []string
	//	Run 2 loops one for create and the other for put
	for limit := 0; limit < 2; limit++ {
		wg.Add(totalConcurrentOp)
		for i := 0; i < totalConcurrentOp; i++ {
                        // find start and end to slice keys for each concurrent operation
			start := i * keysPerConcOp
			end := (i * keysPerConcOp) + keysPerConcOp
			if len(keys) < end {
				subKeys = keys[start:]
			} else {
				subKeys = keys[start:end]
			}
                        
                         // create clients per conccurent operation
			subsclient := make([]*clientv3.Client, 0)
			for i := 0; i < clientsPerConcOp; i++ {
				rc := getClient()
				subsclient = append(subsclient, rc)
			}
                       
                         // start each conccurent operation for create/update
			go func(subKeys []string, val string, subsclient []*clientv3.Client) {
				stp := time.Now()
				defer wg.Done()
				clientIndex := 0
				for _, key := range subKeys {
					if clientIndex >= len(subsclient) {
						clientIndex = 0
					}
					client := subsclient[clientIndex]
					if _, err = client.Put(ctxt, key, val); err != nil {
						log.Fatalf("failed to put key: %v, got err : ", key, err)
					}
					clientIndex++
				}
				if limit == 0 {
					fmt.Printf("Time taken for put for keys: %v is : %v\n", len(subKeys), time.Since(stp))
				} else {
					fmt.Printf("Time taken for update for keys: %v is : %v\n", len(subKeys), time.Since(stp))
				}
				for _, rc := range subsclient {
					rc.Close()
				}
			}(subKeys, val, subsclient)
		}
		wg.Wait()
	}

	wg.Add(totalConcurrentOp)
	for i := 0; i < totalConcurrentOp; i++ {
		// find start and end to slice keys for each concurrent operation
                start := i * keysPerConcOp
		end := (i * keysPerConcOp) + keysPerConcOp
		if len(keys) < end {
			subKeys = keys[start:]
		} else {
			subKeys = keys[start:end]
		}

                // create client for each concurrent operation
		subsclient := make([]*clientv3.Client, 0)
		for i := 0; i < clientsPerConcOp; i++ {
			rc := getClient()
			subsclient = append(subsclient, rc)
		}

                // start concurrent operation for get
		go func(subKeys []string, val string, subsclient []*clientv3.Client) {
			str := time.Now()
			defer wg.Done()
			clientIndex := 0
			for _, key := range subKeys {
				if clientIndex >= len(subsclient) {
					clientIndex = 0
				}
				client := subsclient[clientIndex]
				if _, err = client.Get(ctxt, key); err != nil {
					log.Fatalf("failed to get key: %v, got err : ", key, err)
				}
				clientIndex++
			}
			fmt.Printf("Time taken for get for keys : %v, is : %v\n", len(subKeys), time.Since(str))
			for _, rc := range subsclient {
				rc.Close()
			}
		}(subKeys, val, subsclient)
	}
	wg.Wait()

	if err = deletePrefix(ctx, cl, prefix); err != nil {
		log.Fatalf("failed to clean up keys after test: %v", err)
	}
}

// generates unique numbers of specified length precceding with padding value
func generateNumbers(count, length, startnum int, padding bool) []string {
	var num string
	nums := make([]string, 0)

	for i := startnum; i < startnum+count; i++ {
		num = fmt.Sprintf("%v", i)
		if padding {
			padlen := length - len(num)
			if padlen > 0 {
				for j := 0; j < padlen; j++ {
					num = "0" + num
				}
			}
		}
		nums = append(nums, num)
	}
	return nums
}

// generates random keys by appending unique generated numbers to prefix
func generateRandomKeys(total, noOfUniqueServices int, prefix string) []string {
	keys := make([]string, 0)
	var key string
	prefixes := generateNumbers(noOfUniqueServices, 4, 0, true)
	postPrefix := "/eBUS#0.0#"
	ip := "#10.18.250.242:"
	uniqueServnames := generateNumbers(total/noOfUniqueServices, 8, 0, true)
	for i := 0; i < len(prefixes); i++ {
		for j := 0; j < len(uniqueServnames); j++ {
			key = prefix + prefixes[i] + postPrefix + uniqueServnames[j] + ip + prefixes[i]
			keys = append(keys, key)
		}
	}
	return keys
}
```

**Output:**
```
Time taken for put for 400000 keys is : 20m49.376515285s
Time taken for put for 400000 keys is : 21m16.679048051s
Time taken for put for 400000 keys is : 21m28.88142515s
Time taken for put for 400000 keys is : 21m56.642758672s
Time taken for put for 400000 keys is : 22m5.852617846s
Time taken for put for 400000 keys is : 22m11.719954898s
Time taken for put for 400000 keys is : 22m20.587677729s
Time taken for put for 400000 keys is : 22m38.743312184s
Time taken for put for 400000 keys is : 22m50.55610773s
Time taken for put for 400000 keys is : 32m56.334521029s
cont..
```

**Comment by sinsharat** [comment]
**Output:**
```
cont..
Time taken for update for 400000 keys is : 21m1.673990768s
Time taken for update for 400000 keys is : 22m14.325739383s
Time taken for update for 400000 keys is : 22m18.880771583s
Time taken for update for 400000 keys is : 22m18.728042344s
Time taken for update for 400000 keys is : 22m25.139205849s
Time taken for update for 400000 keys is : 22m29.728033914s
Time taken for update for 400000 keys is : 22m47.067299509s
Time taken for update for 400000 keys is : 22m55.69151013s
Time taken for update for 400000 keys is : 23m0.539246007s
Time taken for update for 400000 keys is : 33m25.84183154s
Time taken for get for 400000 keys is : 12m2.556162621s
Time taken for get for 400000 keys is : 12m16.160583617s
Time taken for get for 400000 keys is : 12m19.556767022s
Time taken for get for 400000 keys is : 12m28.354870754s
Time taken for get for 400000 keys is : 12m29.168836285s
Time taken for get for 400000 keys is : 12m31.552285431s
Time taken for get for 400000 keys is : 12m36.319027685s
Time taken for get for 400000 keys is : 12m36.654335609s
Time taken for get for 400000 keys is : 12m37.303862236s
Time taken for get for 400000 keys is : 21m18.898109771s
```
**Conclusion:**
From the above result since the max time can be considered since they are executiong 0.4M keys in parallel: The below are the results:
Max time for PUT: 32m56.334521029s
Max time for UPDATE : 33m25.84183154s
Max time for GET : 21m18.898109771s

While for zk using java client the below are the results for 4M keys:
Max time for PUT: 11m20s
Max time for UPDATE : 10m42.24s
Max time for GET : 3m25.74s

**Comment by sinsharat** [comment]
Let me know what i am doing wrong, since the difference is quite high :(

**Comment by xiang90** [comment]
@sinsharat Can you clean up your test script? There are a lot of commented out code. I am not sure what is going on there.

Why do you setup 2 gRPC proxies? Are you sending requests through these two proxies? If yes, it would slow down everything significantly. All your requests cannot take advantage of proxies. And you only have 10 out going request at any time. The parallelism is pretty low.

**Comment by xiang90** [comment]
Also note that, if you only have one test client, the client itself might be the bottleneck. And you will be comparing etcd client against zk client.

**Comment by sinsharat** [comment]
@xiang90 I have cleaned the test code and added comments to it. We were using 2 proxies and 5 node cluster since it was decided by the common team. The same config is being used for both zk and etcd. Also while testing both zk and etcd are using single client. Also since its a 12 core machine so 10 concurrent operation should not create problem. Even the logic of java based zk client is having the same logic and splitting the job into 10 threads.

**Comment by xiang90** [comment]
>  We were using 2 proxies and 5 node cluster

How do you config the client? Do all requests go through proxies? Or they go through random servers?

**Comment by xiang90** [comment]
> Also while testing both zk and etcd are using single client.

This contradicts with your original issue. You said you have 2000 clients?

**Comment by sinsharat** [comment]
@xiang90 Sorry by client i meant running from single machine and both using 2k clients.

**Comment by xiang90** [comment]
@sinsharat 

Basically, your test is equivalent to have 10 clients putting/getting keys without any limit. How many clients in total you created is irrelevant to your result. I can believe zk might run faster in light load on a slow HDD. But I am not sure.

I would suggest you to use tools/benchmark to configure the test with 10 clients + 10 connections, and get a more extensive result including latency, ave throughput, etc..

**Comment by sinsharat** [comment]
@xiang90 yes i agree that its almost equivalent. But the purpose of creating so many clients is to put load, and testing with each client in a round robin fashion, and check the CPU usage.
Sure will discuss about your suggestion with other members as well on this.

**Comment by xiang90** [comment]
> each client in a round robin fashion, and check the CPU usage.

Not sure it matters.

> Sure will discuss about your suggestion with other members as well on this.

I would suggest you to run etcd official benchmark tool to do 10 conns + 10 clients test. If the result matches the result your test script created, then it shows etcd has an avg 2x put/update latency than zk. So we can look into it. Also as I mentioned, it would be great if you can provide version + os info.

**Comment by sinsharat** [comment]
@xiang90 sure will provide it. Actually the purpose of creating 2k client connections was that, it will put a load on the server since its creating connection with the server.

**Comment by xiang90** [comment]
> 2k client connections was that

The test takes ~10m. Creating 2k clients take ~seconds. I guess you can safely ignore it.

**Comment by sinsharat** [comment]
@xiang90 what i observed that by reducing client connections, the operations were faster. So it may be that the no of client connection may be affecting it. My point is that its not about the time it takes in creating connections, its about when those connections are kept with the server for long time.

**Comment by xiang90** [comment]
It should not really matter. There might be something else going on.

**Comment by sinsharat** [comment]
May be but if you see the code, i am creating clients separately for each go routine, earlier i had created 2k connections in one go outside the for loop and was slicing it. With the same code and creating 2k connection before hand was causing it to not complete the operation at all and one of the go-routines was not coming out of it. On the other hand instead of using the client in round robin fashion, if we use the same client to perform all operations, it much faster. Hence i feel there is some relation with the client connections with the performance.

**Comment by sinsharat** [comment]
Also if you see the results the last go routine is taking 10mins longer than other go routines performing the same operation, the reason for that is other connections close by then from other go-routines. The pattern is similar for all put, update and get operations.

**Comment by xiang90** [comment]
@sinsharat Based on our recent test, zk is slight faster than etcd under light load: 

https://camo.githubusercontent.com/2c67023a926ce326b46f1a047ab4fe98fd45e370/68747470733a2f2f73746f726167652e676f6f676c65617069732e636f6d2f64627465737465722d726573756c74732f3230313651342d30312d657463642d7a6b2d636f6e73756c2f30332d77726974652d3530304b2d6b6579732d31434f4e4e2d6e6f2d7a657463642d63657463642f6176672d7468726f7567687075742e737667

**Comment by heyitsanthony** [comment]
> creating 2k connection before hand was causing it to not complete the operation at all 

@sinsharat what does `ulimit -a` show? With 2000 simultaneous clients, the client/proxy/server may be hitting fd limits (1024 is typical) because there are too many active connections. Are there any warnings or errors in the logs?

**Comment by sinsharat** [comment]
@xiang90 I don't think we are putting a light load, since its like 2k clients all sending request but 10 clients at a time and that too for 2M, 4M, 8M keys. In each of these cases the time taken by etcd is almost double to that of zk.
@heyitsanthony I didn't see any warning on the VMs we are running, but yes on a lighter single VM for etcd was giving grpc timeout after 1018 connections. But for the cluster we are running there wasn't any warning.  Also the ulimit is showing the value as 265535 which is way more than 1024.
Moreover, currently we are using approx 1k conncections for our clients and for few new customers its expected to reach 2k connections easily.

**Comment by xiang90** [comment]
> a light load

zk and etcd can handle 100s of concurrent operations, and reach 10,000s of requests/second. You only generated 1,000s of requests/second. So the load is light. 

Also if you really care about the request latency under light load, you should get the avg latency, max latency, min latency instead of just focusing on the total time. It will provide more details and help us understand what happened to etcd.

**Comment by heyitsanthony** [comment]
@sinsharat OK, just to confirm, every process involved in the slow setup has an fd limit much greater than 2000? The client processes, the proxy processes, and the etcd server processes?

**Comment by xiang90** [comment]
Moreover, zk read is very different from etcd read, which can return stale data. You need to config etcd's read to be serializable to make them the same. Also I am not sure how you config the clients. Probably they all connected to the same server?

**Comment by sinsharat** [comment]
@heyitsanthony yes it is. For client server, proxy we are using very high end VMs which our clients use.
@xiang90 No we are connecting to each node in cluster for zk uniformly. As for etcd as i had mentioned we  are passing all the endpoints to get client connection.

**Comment by xiang90** [comment]
> As for etcd as i had mentioned we are passing all the endpoints to get client connection.

I do not think etcd client will connect to all server uniformly, at least for now. We might improve that. I think you'd make sure etcd client does the right thing. An easy first step is to try give each client only one endpoint.

**Comment by sinsharat** [comment]
@xiang90 If you want will change it to 100 concurrent operations from 10 and check the result.

**Comment by xiang90** [comment]
@sinsharat 

1. we should figure out why there is the 30m thing (10 minutes more than others).

2. we should figure out if etcd clients connecting to all server evenly. 

3. we should change etcd client to use serializable read or change zk to do a put before read.

4. if you care about latency, we should get latency data as I mentioned. Total time is usually for measuring bulk load/get with no limit.

5.  zk does not have proxy. You probably set up two observers. So the comparison is slightly different.

**Comment by sinsharat** [comment]
@xiang90 sure will do those changes as well. Thanks!

**Comment by sinsharat** [comment]
@xiang90 As per your suggestion i tried the below things:
1. Did code changes to ensure each client is connecting to all servers evenly.
2. passed only cluster's 5 node endpoints to etcd-runner (i.e. ignored the cluster endpoints)
3. Increased the total number of concurrent operations to 25

The following were the observations:
1. The time taken by all go-routines became uniform unlike the old case where 1 of the go-routines was taking 10 mins longer.
3. With more concurrent go-routines it took lesser time.
2. The following is the time taken result for put, update and get operations respectively:
```
Time taken for put for 160000 keys is : 15m58.836489217s
Time taken for put for 160000 keys is : 16m0.681385884s
Time taken for put for 160000 keys is : 16m1.061424796s
Time taken for put for 160000 keys is : 16m2.157585944s
Time taken for put for 160000 keys is : 16m3.123044679s
Time taken for put for 160000 keys is : 16m2.809335469s
Time taken for put for 160000 keys is : 16m4.386891562s
Time taken for put for 160000 keys is : 16m5.469769831s
Time taken for put for 160000 keys is : 16m5.591077721s
Time taken for put for 160000 keys is : 16m5.933502421s
Time taken for put for 160000 keys is : 16m5.180525066s
Time taken for put for 160000 keys is : 16m5.273857379s
Time taken for put for 160000 keys is : 16m6.373758505s
Time taken for put for 160000 keys is : 16m6.364987941s
Time taken for put for 160000 keys is : 16m5.772407265s
Time taken for put for 160000 keys is : 16m6.103653258s
Time taken for put for 160000 keys is : 16m6.810706311s
Time taken for put for 160000 keys is : 16m5.858515121s
Time taken for put for 160000 keys is : 16m6.550722409s
Time taken for put for 160000 keys is : 16m7.376696267s
Time taken for put for 160000 keys is : 16m7.809695108s
Time taken for put for 160000 keys is : 16m7.990430573s
Time taken for put for 160000 keys is : 16m7.964177905s
Time taken for put for 160000 keys is : 16m8.311611442s
Time taken for put for 160000 keys is : 16m7.926187662s
Time taken for update for 160000 keys is : 16m19.790602512s
Time taken for update for 160000 keys is : 16m20.239284567s
Time taken for update for 160000 keys is : 16m21.310938384s
Time taken for update for 160000 keys is : 16m21.529811976s
Time taken for update for 160000 keys is : 16m21.298898476s
Time taken for update for 160000 keys is : 16m21.951777397s
Time taken for update for 160000 keys is : 16m22.063888171s
Time taken for update for 160000 keys is : 16m22.14562736s
Time taken for update for 160000 keys is : 16m22.482988005s
Time taken for update for 160000 keys is : 16m22.500968475s
Time taken for update for 160000 keys is : 16m22.152665s
Time taken for update for 160000 keys is : 16m22.684734706s
Time taken for update for 160000 keys is : 16m22.733210625s
Time taken for update for 160000 keys is : 16m22.68473879s
Time taken for update for 160000 keys is : 16m22.446470258s
Time taken for update for 160000 keys is : 16m23.202451902s
Time taken for update for 160000 keys is : 16m23.430441155s
Time taken for update for 160000 keys is : 16m23.925619071s
Time taken for update for 160000 keys is : 16m24.773647982s
Time taken for update for 160000 keys is : 16m24.396169957s
Time taken for update for 160000 keys is : 16m24.408983257s
Time taken for update for 160000 keys is : 16m25.185198498s
Time taken for update for 160000 keys is : 16m24.551806957s
Time taken for update for 160000 keys is : 16m25.081726715s
Time taken for update for 160000 keys is : 16m25.599843685s
Time taken for get for keys : 160000, is : 6m7.048625579s
Time taken for get for keys : 160000, is : 6m7.073413443s
Time taken for get for keys : 160000, is : 6m7.834174606s
Time taken for get for keys : 160000, is : 6m7.960211117s
Time taken for get for keys : 160000, is : 6m8.141333309s
Time taken for get for keys : 160000, is : 6m7.984188498s
Time taken for get for keys : 160000, is : 6m8.110439033s
Time taken for get for keys : 160000, is : 6m8.228354334s
Time taken for get for keys : 160000, is : 6m8.037065355s
Time taken for get for keys : 160000, is : 6m8.170506054s
Time taken for get for keys : 160000, is : 6m8.66473599s
Time taken for get for keys : 160000, is : 6m8.575321702s
Time taken for get for keys : 160000, is : 6m8.408022833s
Time taken for get for keys : 160000, is : 6m8.334288663s
Time taken for get for keys : 160000, is : 6m8.423875911s
Time taken for get for keys : 160000, is : 6m8.470186768s
Time taken for get for keys : 160000, is : 6m8.369605711s
Time taken for get for keys : 160000, is : 6m9.016582614s
Time taken for get for keys : 160000, is : 6m8.703387625s
Time taken for get for keys : 160000, is : 6m9.291392039s
Time taken for get for keys : 160000, is : 6m9.642255996s
Time taken for get for keys : 160000, is : 6m9.12125071s
Time taken for get for keys : 160000, is : 6m9.217003307s
Time taken for get for keys : 160000, is : 6m9.259694086s
Time taken for get for keys : 160000, is : 6m9.479297642s
```

**Comment by sinsharat** [comment]
Will try with 50 con-current operations today and see the result for 8M keys.

**Comment by sinsharat** [comment]
Results for 8M keys with 50 con-current operations:
```
Time taken for put for 160000 keys is : 24m12.341087604s
Time taken for put for 160000 keys is : 24m16.706200348s
Time taken for put for 160000 keys is : 24m18.751283028s
Time taken for put for 160000 keys is : 24m19.435882655s
Time taken for put for 160000 keys is : 24m21.849746827s
Time taken for put for 160000 keys is : 24m21.925212193s
Time taken for put for 160000 keys is : 24m22.375006972s
Time taken for put for 160000 keys is : 24m22.247934584s
Time taken for put for 160000 keys is : 24m22.779766652s
Time taken for put for 160000 keys is : 24m22.741913192s
Time taken for put for 160000 keys is : 24m22.841602997s
Time taken for put for 160000 keys is : 24m23.90831939s
Time taken for put for 160000 keys is : 24m23.197754992s
Time taken for put for 160000 keys is : 24m24.349680815s
Time taken for put for 160000 keys is : 24m25.741977694s
Time taken for put for 160000 keys is : 24m25.193964715s
Time taken for put for 160000 keys is : 24m26.098618228s
Time taken for put for 160000 keys is : 24m26.820820417s
Time taken for put for 160000 keys is : 24m25.448649463s
Time taken for put for 160000 keys is : 24m26.332633496s
Time taken for put for 160000 keys is : 24m26.751570097s
Time taken for put for 160000 keys is : 24m27.060034425s
Time taken for put for 160000 keys is : 24m27.596585243s
Time taken for put for 160000 keys is : 24m26.086401854s
Time taken for put for 160000 keys is : 24m27.598999508s
Time taken for put for 160000 keys is : 24m27.383161546s
Time taken for put for 160000 keys is : 24m26.554415286s
Time taken for put for 160000 keys is : 24m27.986101554s
Time taken for put for 160000 keys is : 24m27.386378463s
Time taken for put for 160000 keys is : 24m28.252335876s
Time taken for put for 160000 keys is : 24m28.191354982s
Time taken for put for 160000 keys is : 24m27.730293169s
Time taken for put for 160000 keys is : 24m28.641138547s
Time taken for put for 160000 keys is : 24m27.570349481s
Time taken for put for 160000 keys is : 24m28.185791695s
Time taken for put for 160000 keys is : 24m27.549201327s
Time taken for put for 160000 keys is : 24m28.833209535s
Time taken for put for 160000 keys is : 24m28.458855738s
Time taken for put for 160000 keys is : 24m28.524463577s
Time taken for put for 160000 keys is : 24m28.588347209s
Time taken for put for 160000 keys is : 24m28.381689561s
Time taken for put for 160000 keys is : 24m29.081686866s
Time taken for put for 160000 keys is : 24m28.886621297s
Time taken for put for 160000 keys is : 24m29.042917609s
Time taken for put for 160000 keys is : 24m29.485684323s
Time taken for put for 160000 keys is : 24m28.936818909s
Time taken for put for 160000 keys is : 24m29.229589704s
Time taken for put for 160000 keys is : 24m29.72753536s
Time taken for put for 160000 keys is : 24m30.190431911s
Time taken for put for 160000 keys is : 24m30.01770495s
Time taken for update for 160000 keys is : 24m59.001269275s
Time taken for update for 160000 keys is : 24m59.662171924s
Time taken for update for 160000 keys is : 25m0.478548125s
Time taken for update for 160000 keys is : 25m1.792350275s
Time taken for update for 160000 keys is : 25m2.650015673s
Time taken for update for 160000 keys is : 25m3.806522256s
Time taken for update for 160000 keys is : 25m4.487042117s
Time taken for update for 160000 keys is : 25m4.411995187s
Time taken for update for 160000 keys is : 25m4.732183037s
Time taken for update for 160000 keys is : 25m4.940150855s
Time taken for update for 160000 keys is : 25m5.370390972s
Time taken for update for 160000 keys is : 25m5.792259615s
Time taken for update for 160000 keys is : 25m5.251599028s
Time taken for update for 160000 keys is : 25m5.746610225s
Time taken for update for 160000 keys is : 25m6.242506138s
Time taken for update for 160000 keys is : 25m5.853413053s
Time taken for update for 160000 keys is : 25m6.039027953s
Time taken for update for 160000 keys is : 25m6.594614896s
Time taken for update for 160000 keys is : 25m6.73614671s
Time taken for update for 160000 keys is : 25m7.048182499s
Time taken for update for 160000 keys is : 25m7.078726516s
Time taken for update for 160000 keys is : 25m6.616175009s
Time taken for update for 160000 keys is : 25m6.801081612s
Time taken for update for 160000 keys is : 25m6.857539024s
Time taken for update for 160000 keys is : 25m7.531093211s
Time taken for update for 160000 keys is : 25m6.92747158s
Time taken for update for 160000 keys is : 25m7.183485963s
Time taken for update for 160000 keys is : 25m7.517490495s
Time taken for update for 160000 keys is : 25m7.218588188s
Time taken for update for 160000 keys is : 25m7.438721147s
Time taken for update for 160000 keys is : 25m7.678022899s
Time taken for update for 160000 keys is : 25m7.321638312s
Time taken for update for 160000 keys is : 25m7.391627858s
Time taken for update for 160000 keys is : 25m7.665743536s
Time taken for update for 160000 keys is : 25m7.381016352s
Time taken for update for 160000 keys is : 25m7.794965254s
Time taken for update for 160000 keys is : 25m8.241749295s
Time taken for update for 160000 keys is : 25m7.622787477s
Time taken for update for 160000 keys is : 25m8.040024424s
Time taken for update for 160000 keys is : 25m8.097451255s
Time taken for update for 160000 keys is : 25m8.003604082s
Time taken for update for 160000 keys is : 25m8.509876824s
Time taken for update for 160000 keys is : 25m8.021970368s
Time taken for update for 160000 keys is : 25m8.548971113s
Time taken for update for 160000 keys is : 25m8.958834672s
Time taken for update for 160000 keys is : 25m8.715611005s
Time taken for update for 160000 keys is : 25m8.851694016s
Time taken for update for 160000 keys is : 25m9.07860305s
Time taken for update for 160000 keys is : 25m9.575462941s
Time taken for update for 160000 keys is : 25m9.776323999s
Time taken for get for keys : 160000, is : 7m8.331421371s
Time taken for get for keys : 160000, is : 7m8.470060163s
Time taken for get for keys : 160000, is : 7m8.353188349s
Time taken for get for keys : 160000, is : 7m8.600480915s
Time taken for get for keys : 160000, is : 7m8.742074471s
Time taken for get for keys : 160000, is : 7m8.904810197s
Time taken for get for keys : 160000, is : 7m8.80831805s
Time taken for get for keys : 160000, is : 7m9.109915527s
Time taken for get for keys : 160000, is : 7m9.039894601s
Time taken for get for keys : 160000, is : 7m9.077297995s
Time taken for get for keys : 160000, is : 7m9.155951237s
Time taken for get for keys : 160000, is : 7m8.953546316s
Time taken for get for keys : 160000, is : 7m9.197539205s
Time taken for get for keys : 160000, is : 7m8.165659225s
Time taken for get for keys : 160000, is : 7m9.356798558s
Time taken for get for keys : 160000, is : 7m8.652887354s
Time taken for get for keys : 160000, is : 7m9.214660878s
Time taken for get for keys : 160000, is : 7m9.27207886s
Time taken for get for keys : 160000, is : 7m9.487540969s
Time taken for get for keys : 160000, is : 7m9.588622195s
Time taken for get for keys : 160000, is : 7m8.838059233s
Time taken for get for keys : 160000, is : 7m9.500570799s
Time taken for get for keys : 160000, is : 7m8.681921099s
Time taken for get for keys : 160000, is : 7m9.880473928s
Time taken for get for keys : 160000, is : 7m9.085393445s
Time taken for get for keys : 160000, is : 7m8.878359319s
Time taken for get for keys : 160000, is : 7m9.78431668s
Time taken for get for keys : 160000, is : 7m9.882385405s
Time taken for get for keys : 160000, is : 7m10.040615041s
Time taken for get for keys : 160000, is : 7m9.988767155s
Time taken for get for keys : 160000, is : 7m8.832519863s
Time taken for get for keys : 160000, is : 7m9.291165475s
Time taken for get for keys : 160000, is : 7m9.346317257s
Time taken for get for keys : 160000, is : 7m9.170916055s
Time taken for get for keys : 160000, is : 7m9.224108817s
Time taken for get for keys : 160000, is : 7m9.409143322s
Time taken for get for keys : 160000, is : 7m9.715879071s
Time taken for get for keys : 160000, is : 7m9.430585909s
Time taken for get for keys : 160000, is : 7m9.838894682s
Time taken for get for keys : 160000, is : 7m9.9109901s
Time taken for get for keys : 160000, is : 7m10.067533316s
Time taken for get for keys : 160000, is : 7m9.544873133s
Time taken for get for keys : 160000, is : 7m9.749242038s
Time taken for get for keys : 160000, is : 7m9.645207045s
Time taken for get for keys : 160000, is : 7m10.120732829s
Time taken for get for keys : 160000, is : 7m10.267053599s
Time taken for get for keys : 160000, is : 7m9.832179881s
Time taken for get for keys : 160000, is : 7m9.968018028s
Time taken for get for keys : 160000, is : 7m10.062377178s
Time taken for get for keys : 160000, is : 7m10.119101201s
```

**Comment by xiang90** [comment]
@sinsharat 

have you tried to change get using serializable option to match zk?

**Comment by sinsharat** [comment]
@xiang90 you want serialize option to be used for get operation right? Will this option make read faster?

**Comment by xiang90** [comment]
@sinsharat Yes. S-read is local read (zk only supports local read). So it should be faster in your case.

**Comment by sinsharat** [comment]
ok sure will do the changes and test it with 100 con-current threads. Thank you!

**Comment by sinsharat** [comment]
@xiang90 Sure, its important for us since we use ATAE R3 board on which we are currently running our tests. In the mean time i will integrate the kv operations performing load test with etcd-runner, so that its useful for anyone performing such tests in future on their systems and doing comparison.

**Comment by xiang90** [comment]
@sinsharat etcd-runner is not designed for load test. do not integrate this in.

**Comment by sinsharat** [comment]
@xiang90 ok. Btw would it not be better to have a tool to perform such load tests in future, so that everyone doesn't end up writing their own set of code for performing load test and may induce errors causing it to give wrong results?

**Comment by xiang90** [comment]
@sinsharat You can put it into your own repo or Huawei's, and add it into https://github.com/coreos/etcd/blob/master/Documentation/libraries-and-tools.md#libraries-and-tools

**Comment by sinsharat** [comment]
Sure!

**Comment by xiang90** [comment]
@sinsharat I am closing this out:

your two issues found in benchmark are better captured here:

https://github.com/coreos/etcd/issues/7156
https://github.com/coreos/etcd/issues/7083

**Comment by xiang90** [comment]
@sinsharat If there are other performance concerns, let us know.

**Comment by sinsharat** [comment]
@xiang90 sure will do that. We are yet to do load test for watchers. Let me discuss with the team on monday when do we plan to do it.
Thanks!
