### ISSUE TITLE
Public GPG keys

### ISSUE THREAD

**Issue by dradtke** [coreos/etcd#7086]
Would it be possible to make public the GPG keys used to sign each release so that we can automatically verify them in our tooling? I did find [this](https://coreos.com/security/image-signing-key/) after some searching, but it failed with a "signature made by unknown entity" error.

**Comment by gyuho** [comment]
We use sub-key with `CoreOS Application Signing Key <security@coreos.com>` to sign our releases. It might be different than the Container Linux signing keys.

@robszumski @dghubble @philips 
Any thoughts?

**Comment by xiang90** [comment]
@gyuho I think the first step to document which key we used to sign our release in the release note?

**Comment by crawford** [comment]
The signature already specifies which key was used to sign, so there is no need. The key is hosted on [coreos.com](https://coreos.com/security/app-signing-key/), but we should add it to other key servers if it isn't already there.

**Comment by xiang90** [comment]
@crawford 

> I did find this after some searching, but it failed with a "signature made by unknown entity" error.

This is the users' issue. Thera are two parts:

1. we should avoid searching. so we probably should add small notes linking to https://coreos.com/security/image-signing-key/ to make it explicitly as the first step

2. we should avoid `unknown entity` error thing. As you mentioned, we should add keys to other key servers.

**Comment by gyuho** [comment]
I will upload our pub keys to other servers when next release happens.

**Comment by dradtke** [comment]
Assuming the Application Signing Key works, then I'd be happy with simply documenting its existence in the project's README or as part of the notes for each release.

**Comment by xiang90** [comment]
@dradtke We will doc it in the release note.

**Comment by dradtke** [comment]
To clarify, I tested it again, and the [image signing key](https://coreos.com/security/image-signing-key/) fails with an error (which is expected since it's the wrong key), but the [app signing key](https://coreos.com/security/app-signing-key/) works. 👍 for linking to the app signing key in the release notes.

**Comment by gyuho** [comment]
We now include app signing key link in our release notes.

https://github.com/coreos/etcd/releases/tag/v3.0.16

Thanks!
