### ISSUE TITLE
ETCD Docker instruction page error - workaround found

### ISSUE THREAD

**Issue by arehmandev** [coreos/etcd#7088]
Hi guys, strange error happening over here but I found a workaround.

If I run the example docker run command found here it doesn't seem to work https://coreos.com/etcd/docs/latest/v2/docker_guide.html

Here is my script for running a solo development container on an AWS CoreOS instance 
- CoreOS-stable-1185.5.0-hvm (ami-7ee7e169)
- etcd container version - latest (v3.0.15)
- Docker version 1.11.2, build bac3bae
 
## The broken version

```
#!/bin/sh
HostIP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

docker run -d -p 4001:4001 -p 2380:2380 -p 2379:2379 \
 --name etcd quay.io/coreos/etcd \
 -name etcd0 \
 -advertise-client-urls http://${HostIP}:2379,http://${HostIP}:4001 \
 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
 -initial-advertise-peer-urls http://${HostIP}:2380 \
 -listen-peer-urls http://0.0.0.0:2380 \
 -initial-cluster-token etcd-cluster-1 \
 -initial-cluster etcd0=http://${HostIP}:2380 \
 -initial-cluster-state new
```

### The error given:
docker: Error response from daemon: Container command '-name' not found or does not exist..

## Now here's where it gets strange, the fix:

Just add 'etcd' after the container name so the parameters are passed to the etcd daemon (which shouldn't need to be done since its the entrypoint!?).

```
#!/bin/sh
hostip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
etcd0=172.31.26.54
etcd1=172.31.38.239
etcd2=172.31.55.94

docker rm -f etcd
docker run -d -p 4001:4001 -p 2380:2380 -p 2379:2379 \
 --name etcd quay.io/coreos/etcd etcd \  #### <- THE FIX - Add etcd here!
 -name etcd0 \
 -advertise-client-urls http://${hostip}:2379,http://${hostip}:4001 \
 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 \
 -initial-advertise-peer-urls http://${hostip}:2380 \
 -listen-peer-urls http://0.0.0.0:2380 \
 -initial-cluster-token etcd-cluster-1 \
 -initial-cluster etcd0=http://${etcd0}:2380 \
 -initial-cluster-state new
```

So am I going mad since I haven't slept or are the flags not being passed to the container entrypoint correctly for some reason.

**Comment by gyuho** [comment]
This is being addressed in https://github.com/coreos/etcd/pull/6901.

And see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker.
