### ISSUE TITLE
etcdserver, embed: make v2 endpoint optional

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7100]
Support pure v3 instances of etcd.

**Comment by vimalk78** [comment]
- v2 endpoints :
   - not started by default, and user need to configure to start OR 
   - started by default, but user can configure to disable it if needed
 - need to disable all v2 featues? v2 store/watch/ttl/proxy etc?

**Comment by heyitsanthony** [comment]
@vimalk78 it would be started by default, but there would be an option to disable it. Eventually v2 will be off by default, then after that totally removed from the core etcd code.

**Comment by vimalk78** [comment]
changes : 
embed/config.go - introduce a config item, disablev2, default value - false. (later default value changed to true)
embed/serve.go - serveCtx.serve : based on new config item, conditionally handle creating v2 endpoints

if no one is working on it, can you assign to me?

**Comment by heyitsanthony** [comment]
@vimalk78 I recall some etcd server internals needing a v2 endpoint to bootstrap, so it might not be that simple. You can give it a try, though.

Only remark on that approach is `serveCtx` shouldn't have direct knowledge of `embed.Config`. Probably make the cut at embed/Etcd.serve by nil'ing out the http handler based on the new config field and have `grpcHandlerFunc` check for nil.
