### ISSUE TITLE
How can I delete the value that is key is 'null'?

### ISSUE THREAD

**Issue by coder0wang** [coreos/etcd#7104]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on
[reporting bugs][report_bugs] before you submit your bug report. 

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by xiang90** [comment]
Do you have an example to show what you want to do? I do not quite understand the question.

**Comment by coder0wang** [comment]
For example :  the key is 'host/null' ,i want delete it.The result is success,but it always exist.

**Comment by gyuho** [comment]
@coder0wang Please be more specific? This works for me.

```
ETCDCTL_API=3 ./bin/etcdctl put host/null bar
# OK

ETCDCTL_API=3 ./bin/etcdctl get host/null
# host/null
# bar

ETCDCTL_API=3 ./bin/etcdctl del host/null
# 1

ETCDCTL_API=3 ./bin/etcdctl get host/null
# no output (deleted)
```

**Comment by gyuho** [comment]
@coder0wang I tried v2 API with v2.3.7 and latest v3 release.
They all work.

Please leave comments if you still have issues.

```
./etcdctl set host/null bar
bar

./etcdctl get host/null
bar

./etcdctl rm host/null
PrevNode.Value: bar

./etcdctl get host/null
Error:  100: Key not found (/host/null) [6]
```
