### ISSUE TITLE
linearizable reads spends most of the time in waiting for ReadIndex

### ISSUE THREAD

**Issue by vimalk78** [coreos/etcd#7109]
i have a 3 node cluster which has about 1000 keys

my test case involves mostly reading the keys and i am reading one key after another. At the moment of the read, there are no write happening, i.e. no Put/Delete operations.

adding timestamps in v3_server, i observe the following
```
linearizable Reads :
  16:26:50 etcd1 | 2017-01-06 16:26:50.836852 E | etcdserver: reading readStateC took 531.839µs
  16:26:50 etcd1 | 2017-01-06 16:26:50.836894 E | etcdserver: waiting linearizable 608.438µs
  16:26:50 etcd1 | 2017-01-06 16:26:50.836943 E | etcdserver: returning Range in 673.684µs
serializable Reads :
  16:26:48 etcd1 | 2017-01-06 16:26:48.664999 E | etcdserver: returning Range in 31.641975ms
```

i find that out of 600 odd micro seconds it takes to process the read, about 78% of time it is taking in reading the ReadState. But the ReadState it reads from leader has ReadIndex same as appliedIndex, (there is no `applyWait` happening) since there are no Put/Delete operations happening. This is a constant cost and its contribution to the overall Range cost reduces if the Range query results in multiple keys. But for Range queries done one after another in sequence, this constant cost adds up.

can this be optimized? instead of followers asking for the ReadIndex, the leader can send ReadIndex in AppendEntries RPC ? ( i am thinking wildly here, i am not a Raft expert)

the concurrent linearizable reads are optimized in `linearizableReadNotify/linearizableReadLoop` that if concurrent requests catch hold of same `readNotifier`, same ReadState will be applicable for those concurrent Read requests. can the same be done for requests which occur within a certain period of one another?

i just want to make the cost of linearizableReads under no writes, to be similar to serializable case (without setting that option in the request explicitly).

**Comment by heyitsanthony** [comment]
> ReadState it reads from leader has ReadIndex same as appliedIndex, (there is no applyWait happening) since there are no Put/Delete operations happening. 

A follower won't know there are no puts/deletes happening; it has to ask the leader to know if the cluster is in a quiescent state.

> instead of followers asking for the ReadIndex, the leader can send ReadIndex in AppendEntries RPC ?

I don't think the leader can broadcast (via appendentries or otherwise) a readindex since that can break linearizability:
1. Cluster begins with A=1
2. Leader broadcasts read index
3. Cluster accepts write proposal A=2
4. Client requests read, follower queues until readindex update.
5. Follower receives readindex broadcast, lets linearized read go through.
6. Client gets A=1, despite requesting a read after A=2 is committed.

> if concurrent requests catch hold of same readNotifier, same ReadState will be applicable for those concurrent Read requests. can the same be done for requests which occur within a certain period of one another?

That's effectively what the code already does. Requests that happen around the same time will batch on the same read index.

> i just want to make the cost of linearizableReads under no writes, to be similar to serializable case (without setting that option in the request explicitly).

There's always going to be overhead for linearized read on a 3 node cluster that simply isn't present for serialized reads because of the additional coordination.

**Comment by xiang90** [comment]
> i find that out of 600 odd micro seconds 

What is the round trip time between these node? Collect some ping results?

**Comment by vimalk78** [comment]
@xiang90 , the cluster is a 3 node cluster started with default Procfile using goreman. so all 3 nodes are on same ubuntu box

**Comment by xiang90** [comment]
@vimalk78 Can you try it on a more realistic setup, and get the latency information? I think the first step is to ensure l-read takes ~ 2 rtt (client to leader + leader to all followers) when serving from the leader, and takes ~3 rtt (client to follower + follower to leader + leader to all followers) when serving from the follower. If that works perfectly, then we can think of how to optimize it.

**Comment by vimalk78** [comment]
> 4. Client requests read, follower queues until readindex update.

follower doesnt need to queue up the request for next update of ReadIndex, it uses the value it has from the previous update and proceeds. i.e. waits for it to be applied. if already applied(which will be the case mostly), the reads can be served immediately.

> 6. Client gets A=1, despite requesting a read after A=2 is committed.

this situation can occur even when followers actively ask for ReadIndex from leader. by the time leader's response reaches the follower, the committed index at leader might have changed. ( not too sure though)
the problem i see with this approach is that the likelihood of read being stale goes up towards the end of the cycle, while requesting a new ReadIndex for each time reduces it.

> That's effectively what the code already does. Requests that happen around the same time will batch on the same read index.

but these requests must have been from different clients. subsequent requests from the same client will trigger a ReadIndex request to the leader.
can we atleast delay the switching of `readNotifier` till the response arrives from the leader? may be this will let more requests gather around the same ReadIndex.

**Comment by vimalk78** [comment]
@xiang90 , the time taken is captured at the server, i modified the v3_server to capture it. it doesnt include the rtt time. i will re run the test and capture the time taken at client.

**Comment by xiang90** [comment]
>  it doesnt include the rtt time.

It includes the communication time between servers at least.

**Comment by vimalk78** [comment]
@heyitsanthony is it ok to move the creation of new readNotifier to after receiving the ReadIndex response form the leader

i have prepared a patch, shall i send a PR

**Comment by vimalk78** [comment]
you can see the changes here
https://github.com/vimalk78/etcd/commit/18ead9fab40730c652b0ea1b7c02e4cebf943a07

**Comment by heyitsanthony** [comment]
@vimalk78 I don't understand the advantage to that patch and it is also has a data race. I'm not sure it's correct-- won't reads be notified based on requests made before the read was issued by the client, instead of after? That seems to violate linearizability.

**Comment by vimalk78** [comment]
> won't reads be notified based on requests made before the read was issued by the client, instead of after? That seems to violate linearizability.

hmm, a request which should have got a readIndex of 20 might get a readIndex of 15, which will be applied faster, and will make the range request be served faster than it should, so reads incorrect data. i see your point.
i was thinking it will make the batch size larger (of the requests waiting for a readIndex) but it will not. it will only affect the beginning of the next batch, not its size.
my point was to optimize the case when readIndex is not changing. but i guess nothing more can be done.

so closing the issue. thanks.
