### ISSUE TITLE
How to get the delete dir event?

### ISSUE THREAD

**Issue by XMAN-WOMBAT** [coreos/etcd#7114]
hello all :
        The etcd can watch a dir --recursive,when one  key is changed,the watcher can receive the event,but delete one dir,watcher could not get the event.in some case,delete dir event is important.
       how can i get the delete dir event?
       thanks!!!!

**Comment by heyitsanthony** [comment]
As you noticed, watch only works on keys, not directories. v2 is feature frozen so there's no plan to support watching on directory create/delete.
