### ISSUE TITLE
TestGRPCStreamRequireLeader: err = EOF, want nil

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7122]
via https://semaphoreci.com/coreos/etcd/branches/master/builds/1405
```
--- FAIL: TestGRPCStreamRequireLeader (3.66s)
	v3_grpc_test.go:1148: err = EOF, want nil
```

**Comment by gyuho** [comment]
Never seen it since, and etcd went through several major gRPC upgrades.
Will reopen when it happens again.
