### ISSUE TITLE
etcdctl v3: --write-out doesnt ignored on role/user get/list

### ISSUE THREAD

**Issue by idonin** [coreos/etcd#7129]
`etcdctl version: 3.0.15
API version: 3.0`

`# ETCDCTL_API=3 etcdctl -w json role get development
Role development
KV Read:
	[/datasources/development/, /datasources/development0)
KV Write:
	[/datasources/development/, /datasources/development0)`

Same with role get; role list; user get; user list

**Comment by mitake** [comment]
@idonin thanks for your report! It is on my todo list, I'll work on it ASAP.

**Comment by idonin** [comment]
I'm glad to hear it!

**Comment by heyitsanthony** [comment]
@mitake @idonin I overhauled etcdctl output the other week. JSON output for auth commands should be in master now and will be in 3.1.

**Comment by mitake** [comment]
@heyitsanthony sorry I missed the commit... and thanks a lot for doing this!
@idonin So the auth related commands of the latest master can handle `--write-out` already :) I'm closing this.
