### ISSUE TITLE
question: how can i prove that existing user have correct password?

### ISSUE THREAD

**Issue by idonin** [coreos/etcd#7130]
I working on [salt](https://saltstack.com) state for etcd v3 user management, so I need a way to test existing etcd user:password pairs in etcd with pair, stored in salt.

So two questions:
1. Which hash algorithm used for passwords in etcd v3?
2. How can i get user:password pairs from etcd v3?

**Comment by mitake** [comment]
> 1. Which hash algorithm used for passwords in etcd v3?

etcd is using bcyrpt for storing password in a safe manner. You can find a detail of the algorithm and the implementation here: https://godoc.org/golang.org/x/crypto/bcrypt

> 2. How can i get user:password pairs from etcd v3?

The password cannot be read from etcd for the security reason. Isn't getting a list of users enough for you?

**Comment by idonin** [comment]
List of users do not enough, because i want to test user have same password as I want to set or not.
Any other option to get password? Not necessary via etcd API, we can use unix utility as well

**Comment by mitake** [comment]
Then how about creating a small command that just calls `Authenticate()` RPC with given username and password? Password cannot be read directly but you can check the password is correct or not by the result of RPC (if it is successful, you can say correct password is configured).

**Comment by idonin** [comment]
You are genius! I think, thats will work, thanks. :)

**Comment by mitake** [comment]
Good, then I'm closing this issue. If you find problems in the future, please reopen or add another issue.

**Comment by idonin** [comment]
P.S. I found that all users have permissions to `member list` command(if login:password correct ofc), so if anyone else looking for same workaround, using `etcdctl member list` is viable.
