### ISSUE TITLE
waiting until capable

### ISSUE THREAD

**Issue by necro351** [coreos/etcd#7131]
Dear CoreOS developers,

I am writing a service that uses etcd clientv3 and embed packages. The service is written in go and has etcd embedded in it. I have some unit tests that start three etcd embed instances together, locally, on the same machine. I want to wait until requests to these instances will succeed and not fail with "etcdserver: not capable". Currently all three instances wait until '<-d.etcd.Server.ReadyNotify()' returns, but this was not sufficient. So then I had all client requests wait until all three instances got past ReadyNotify(), but it seems even this is not sufficient. To be clear, the test is indeterminate, depending on timing issues it seems, sometimes the client requests succeed and everything is fine, but if I am unlucky, the first request fails with "etcdserver: not capable". The only thing I am doing is re-running the test. Is there something I can wait on so that I know that requests will succeed after that point? Thanks.

FYI: I am starting the cluster in a static configuration, all three members have all three members in the InitialCluster variable in the config template returned from etcdembed.NewConfig(). Also to reiterate, the cluster works fine for some (most) runs of the test, its just occasionally that I get this "etcdserver: not capable" error. Finally, I completely delete all etcd files between runs (the files stored in the Dir variable). Please let me know if I am missing something, or if this is expected behavior, etc... Thanks.

**Comment by heyitsanthony** [comment]
@necro351 it's expected behavior. It's happening because the server defaults to only v2 then negotiates up to v3.  The easiest workaround is to poll `etcd.Server.ClusterVersion` until it's >=3.0, but that's not a long-term solution.

EtcdServer doesn't have an interface for waiting on a version, but I'm not sure it's the best thing to have since waiting like:
```go
<-e.WaitVersion("3.1.0")
```
would require a full cluster upgrade before making forward progress, but maybe that's OK.

@xiang90 is 3.1's `to_be_decided` going to default to 3.0 capabilities or should it default to <2.3 in perpetuity?

**Comment by xiang90** [comment]
@heyitsanthony for 3.1, the default version is 3.0. so users won's see not capable for 3.0 api.

**Comment by heyitsanthony** [comment]
@xiang90 are you sure? I believe there's a race-- the cluster version initializes to nil and is updated asynchronously in `monitorVersions`. There's no synchronization on that version update, so it seems there's a window where the client can make API requests and the cluster is still in `to_be_decided` so v3 requests will be rejected.

**Comment by xiang90** [comment]
@heyitsanthony You are right, there still can be a window that the version is "to_be_decided". I think we can change the default to 3.0 from "to_be_decided". Do you remember the reason we still set it to "to_be_decided" when we bump from 3.0 to 3.1-alpha?

**Comment by heyitsanthony** [comment]
@xiang90 there were a few versioning issues with the bump, so the `to_be_decided` bit was probably forgotten in the ensuing panic.

**Comment by necro351** [comment]
Thanks guys, this is very helpful! Based on your suggestion I stuck in some code like this:

   requiredVersion := semver.New("3.0.0")                                                           
   clusterVersion := d.etcd.Server.ClusterVersion()                                                 
   for clusterVersion == nil || clusterVersion.LessThan(*requiredVersion) {                         
      time.Sleep(time.Second)                                                                       
      clusterVersion = d.etcd.Server.ClusterVersion()                                               
   }  

Now my tests always run, magna gratia!
