### ISSUE TITLE
Cluster gets into readonly if adding another member but not starting the member

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#7134]
ETCD cluster gets into readonly mode if adding another member but not starting the member.

The member is in `unstarted` state, so it shouldn't be counted into raft mode before they become followers. Just like that teenagers don't have vote right until they grow up to adults.

```
LM-SHC-16501219:cmd armstrongli$ ETCDCTL_API=3 ./etcdctl1 member add t1 --peer-urls="http://localhost:111111"
Member dc9db47dbc7605b5 added to cluster cdf818194e3a8c32
LM-SHC-16501219:cmd armstrongli$ ETCDCTL_API=3 ./etcdctl1 get / --prefix
Error:  context deadline exceeded
LM-SHC-16501219:cmd armstrongli$ ETCDCTL_API=3 ./etcdctl1 member list
8e9e05c52164694d, started, default, http://localhost:2380, http://localhost:2379
dc9db47dbc7605b5, unstarted, , http://localhost:111111,
LM-SHC-16501219:cmd armstrongli$ ETCDCTL_API=3 ./etcdctl1 member remove dc9db47dbc7605b5
Error:  etcdserver: request timed out
```

**Comment by xiang90** [comment]
You should start etcd right after you added it into the cluster vie etcdctl. We do not feel it is necessary to introduce the additional stage. Basically, etcd does not need to grow up. It is born to be a adult.

**Comment by xiang90** [comment]
Additionally, if you want your etcd cluster to be highly available you should start a 3 members cluster. One member cluster is not recommended to be used in production. Even if you want to start etcd servers one by one, you should only consider the etcd server ready when you have all three members up.

**Comment by armstrongli** [comment]
@xiang90 the ETCD member shouldn't be adult directly until it starts the first time. 
the cluster doesn't have the client URLs until the member starts up.
so i think the cluster shouldn't take the unstarted members into raft members count

**Comment by armstrongli** [comment]
>You should start etcd right after you added it into the cluster vie etcdctl

What if the speed of typing is a little slow? Then I need to start everything again from the beginning. The root cause of that is `your typing is toooooooo sloooooow`.
What's more, I need to create a new cluster by force with the `old data`. That's nightmares for me

**Comment by heyitsanthony** [comment]
> so i think the cluster shouldn't take the unstarted members into raft members count

What counts as "started"? If the new member sends a "started" message to the cluster when it first boots, it seems like that's no different from issuing `etcdctl add member` when starting the new member; there'll still be a temporary window where quorum increases before the new member begins participating in raft. If that's the case, then an "unstarted" mode is unnecessary; it would complicate the state machine for essentially no gain over what it does now.

> What if the speed of typing is a little slow?

Write a script?

**Comment by armstrongli** [comment]
@heyitsanthony 
I propose to add another status for raft election which means the member hasn't been ready for vote.

> Write a script?

I run everything on kubernetes cluster. There're scripts to start new etcd members. But the network can be unstable, the headbeat can be lost, etc. So we can't assume that etcd is running in one ideal env. And etcd is designed to tolerant such cases.
Then I encounter such case when I configure the cluster in runtime. Unfortunately my 2nd member's network is unstable and fails to start within seconds. My cluster gets into `Readonly`. I have to recovery my cluster by creating another cluster with old data.

**Comment by xiang90** [comment]
> And etcd is designed to tolerant such cases.

It is not. If you have a two members cluster, when you lose one member you lose the cluster. So I suggest you to start with 3. What you have described has nothing to do what the state. It only means that a two members cluster is a bad idea.

**Comment by armstrongli** [comment]
@xiang90 
I need to expand the master nodes of kubernetes from 1 to 5. The count increases from 1 to 5. The cluster gets down when I adding 2nd master node.
The etcd in master node is in static pod. The 1st master node initializes etcd cluster, and 2nd master node join into the etcd cluster.

**Comment by xiang90** [comment]
That is fine, if your 2nd member dies you start all over again. You write a script and it should take you less than 1 minute. That is the drawback of your approach, and you have to realize it.

Adding the state is useless in your case. It just delays the failure, not solve it.

**Comment by armstrongli** [comment]
@xiang90 
If the member is teenager when it is added to the cluster, then the cluster keeps healthy. 
After it started, it sync cluster info to its local storage. It grows up to adult. It has its own member info, and cluster info.
The cluster can get back after the 2nd member restarts cause it has the cluster info already, and it can get back into the cluster.

If the configuration of the new member is wrong, it can't start. And the cluster keeps clean & healthy with teenager members.
