### ISSUE TITLE
question: does etcd v3 transfer password in plaintext or in hash over gRPC?

### ISSUE THREAD

**Issue by idonin** [coreos/etcd#7135]
In another words: etcd convert password in hash on client and then comparing hashes on server side or on server side?

(client: password --> hash; server: hash <-> hash_stored)  or (server: password_received --> hash; hash <-> hash_stored)

**Comment by heyitsanthony** [comment]
@idonin it's plaintext to authenticate and a token thereafter. See https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-authenticaterequest-etcdserveretcdserverpbrpcproto
