### ISSUE TITLE
etcd v3 client - getting the latest revision

### ISSUE THREAD

**Issue by mwf** [coreos/etcd#7140]
Hi!

A little question - how can I get the value with the latest revision? I don't care about the key, just the revision.

Logic tells it should work like this
`client.Get(context.Background(), "", clientv3.WithLastRev()...)`

But it returns an error "etcdserver: key is not provided"

Though we are able to get **all** keys using etcdctl:
`ETCDCTL_API=3 etcdctl get "" --prefix`

I'm using the latest client version, v3.1.0-rc.1

**Comment by mwf** [comment]
Tried another way `client.Get(context.Background(), "", clientv3.WithSort(clientv3.SortByModRevision, clientv3.SortDescend), clientv3.WithLimit(1))` - it returns the same error.

Though Watch works OK with empty key :)

**Comment by xiang90** [comment]
get whatever key, check the revision in the header?

**Comment by heyitsanthony** [comment]
@mwf the options for etcdctl are out of order-- it is interpreting `--prefix` as an argument, not a flag.

You want the value of the last key stored to the entire etcd cluster? That is a very expensive operation at the moment because it has to process every key, but OK:
```go
clientv3.Get(context.TODO(), "\x00", clientv3.WithLastRev())
```
or

```sh
ETCDCTL_API=3 ./bin/etcdctl get --order=DESCEND --sort-by=MODIFY --limit=1 --prefix ""
```

**Comment by mwf** [comment]
@heyitsanthony thank you, it's what I was looking for :) If it's so expensive I won't really use it, but anyway it's good to have such opportunity.
"\x00" is not obvious at all...

**Comment by jfbai** [comment]
> @mwf
> You want the value of the last key stored to the entire etcd cluster? That is a very expensive operation at the moment because it has to process every key, but OK:
> 
> ```go
> clientv3.Get(context.TODO(), "\x00", clientv3.WithLastRev())
> ```
> 
> or
> 
> ```shell
> ETCDCTL_API=3 ./bin/etcdctl get --order=DESCEND --sort-by=MODIFY --limit=1 --prefix ""
> ```

@heyitsanthony Nice solution, BTW, what does this `\x00` key mean in etcd?
