### ISSUE TITLE
V2 watch on the dir

### ISSUE THREAD

**Issue by XMAN-WOMBAT** [coreos/etcd#7143]
hi，all：
        What should i do ,when i watching on the machine(A) dir through curl  ,but the machine(B) is down。In this case, the client is still in a blocked state。

**Comment by heyitsanthony** [comment]
Put a timeout on curl and switch to the other machine's endpoint if the request times out? V2 watchers aren't reliable in this case so it'll probably miss events.

**Comment by XMAN-WOMBAT** [comment]
@heyitsanthony The miss event can be resolved through the watch event index？

**Comment by heyitsanthony** [comment]
@XMAN-WOMBAT yes, but it can lose the window.

V3 is a flat keyspace; it doesn't have directories (although they can be emulated by imposing some structure on the key names). The V3 data model ensures the watch window won't be lost unless there's an explicit compaction the store.

**Comment by XMAN-WOMBAT** [comment]
@heyitsanthony Thanks!
