### ISSUE TITLE
clientv3/naming: breaks with new 3.2.0+git version string

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#7152]
`TestGRPCResolver` fails 

```
--- FAIL: TestGRPCResolver (0.32s)
	grpc_test.go:49: failed to add foo etcdserver: not capable
```

And bunch others

https://semaphoreci.com/coreos/etcd/branches/master/builds/1428

**Comment by xiang90** [comment]
We need to add the capability map in api pkg.
