### ISSUE TITLE
#NEED HELP# got a revision less than expected

### ISSUE THREAD

**Issue by arthurkiller** [coreos/etcd#7161]
Sorry for bother, but I get a question here.
while I working with etcd3 transaction . I make a compare about key's revision and use as ctx.If() condition.

But I get the key's revision before commit and it is larger than the revision while ctx process to If()!!!

```
...
resp, _ := client.get(ctx, "test")
rev := resp.Header.Revision
client.ctx(context).if(etcd.Compare(etcd.ModRevision("test"),"=",rev)).Then(...).Commit()  // false!!!
client.ctx(context).if(etcd.Compare(etcd.ModRevision("test"),"=",rev-1)).Then(...).Commit()  // true !!!
...
``` 
just like codes above, only 1 write operation in this situation
 
But it doesn't equal ! 

And it equals to rev-1 !!!!!

So is there any possible reason to this ?

**Comment by arthurkiller** [comment]
But I can not repeat the test code beyond my project... How could this be.

**Comment by xiang90** [comment]
Resp.revision is the current revision of the store, not the revision of your key. You need to get the key's revision to compare against. kv.ModRev from get response is the key's revision.

**Comment by arthurkiller** [comment]
thx，and how can I find the difference between these revision? Is there any document to introduce them? @xiang90

**Comment by heyitsanthony** [comment]
@arthurkiller this is documented in at least two places already:

The glossary:
* etcd revision -- https://github.com/coreos/etcd/blob/0ca0260c89b52fd09af1d981842e1750c80339ac/Documentation/learning/glossary.md#revision
* modification revision -- https://github.com/coreos/etcd/blob/0ca0260c89b52fd09af1d981842e1750c80339ac/Documentation/learning/glossary.md#modification-revision

The v3 rpc API documentation:
* etcd revision in response header -- https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-responseheader-etcdserveretcdserverpbrpcproto
* modification revision in range response -- https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#message-keyvalue-mvccmvccpbkvproto

**Comment by arthurkiller** [comment]
thx dude @heyitsanthony
