### ISSUE TITLE
auth enabled/disabled state can be lost after node reboot

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#7165]
After node reboot, sometimes the state of auth enabled/disabled can be lost. Reported by @ekle https://github.com/coreos/etcd/issues/7012#issuecomment-272151232

**Comment by ekle** [comment]
i hope a fix gets also in v3.1.1. this problem is really annoying.

**Comment by mitake** [comment]
@ekle sorry I was busy with other work this week. I'll be able to resume this issue from next week.

BTW, this problem happens rarely on my environment. Do you have good procedures for reproducing it?

**Comment by ekle** [comment]
here i have a 50/50 chance of getting it. but i don't know what triggers it. i have a 3 node cluster behind a aws-lb which does ssl-offloading.

**Comment by mitake** [comment]
The problem was caused by snapshotting, small (e.g., 10) `--snapshot-count` option can reproduce the problem easily. It seems that current auth store cannot be recovered after node shutdown correctly. I'll work on it from tomorrow (hope it won't take a long time because the root cause is already known).
