### ISSUE TITLE
Start a Session with existing lease

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#7166]
A client uses a session for election, becomes the leader and then restarts. Would it be possible for the client to reclaim the leader role on restart? Assume the client can figure out the existing lease id after restart. If the session can be restarted with existing lease id, the client can maintain leadership for that election.

cc @xiang90

**Comment by ravigadde** [comment]
If there is interest, I can try to make the changes and submit a patch.

**Comment by xiang90** [comment]
@ravigadde Quick reply: I think this is a reasonable feature requirement. This is one of the reason we make lease ID logic so that multiple instances or a restarted instance can pick it up. Probably we can add a WithPreviousLease option into NewSession.

**Comment by ravigadde** [comment]
Thanks @xiang90

**Comment by xiang90** [comment]
@ravigadde Do you plan to work on this one?

**Comment by ravigadde** [comment]
@xiang90 Yes, I will take this up

**Comment by xiang90** [comment]
@ravigadde assigned. Thanks.

**Comment by ravigadde** [comment]
@xiang90 

I was trying to use this for running an election as I alluded to earlier. In the election API, why is Observe watching proposals? Aren't leader events more interesting? I dont see any API for that.

There is also a bug in observe (watch missing +1 for revision):

```
		wch := client.Watch(cctx, string(kv.Key), v3.WithRev(kv.ModRevision))
```
