### ISSUE TITLE
watch delete event

### ISSUE THREAD

**Issue by lijunfei** [coreos/etcd#7167]
clientv3: the delete event can return value of key?

**Comment by vimalk78** [comment]
i think the Watch event will not have the value of the key.
the Event will have the `ModRevision` which points to the latest revision (in which the key has been deleted).

**Comment by xiang90** [comment]
@lijunfei You can set PrevKV in watch: see https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto#L620-L622.

It is supported in the latest version of 3.0 and after.
