### ISSUE TITLE
How the etcdctl backup handle Disaster Recovery?

### ISSUE THREAD

**Issue by dearboll** [coreos/etcd#7168]
Hi all, I am reading the etcd admin doc but confused about the Disaster Recovery operations.  As the document says, the first step is backup the data directory, which will rewrite some metadata of the member such as ClusterID and MemberID. Second, to restore the backup, we should start etcd with the -force-new-cluster option and use the backup directory. This will initialize a new cluster but preserve the etcd data. The third step confused me as once the etcd  has started, shut it down and move the data back to previous location. Then start etcd with the original -data-dir. 

I think the new-starting etcd has the new Cluster ID and member ID, so it cannot joint onto the old cluster.  So why we kill the etcd and move the backup to old data directory and restart it? Just for convenient? 

And facing the major failover(data loss or disk corruption) fact, can I remove the failure members and add new idle members via MEMBER API? I think it is ok but will take a lot of network traffic because the news have no data and the leader will append entries for them frequently.  Am i right? 

Thank you very much!

**Comment by gyuho** [comment]
> I think the new-starting etcd has the new Cluster ID and member ID, so it cannot joint onto the old cluster. So why we kill the etcd and move the backup to old data directory and restart it? Just for convenient?

Restoring a cluster from backup snapshot launches a new cluster, so the former cluster identities are overwritten; see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster.


> And facing the major failover(data loss or disk corruption) fact, can I remove the failure members and add new idle members via MEMBER API?

It is recommended to remove a member first; see https://github.com/coreos/etcd/blob/master/Documentation/faq.md#should-i-add-a-member-before-removing-an-unhealthy-member.

**Comment by dearboll** [comment]
Thank you for your attention.
