### ISSUE TITLE
Upgrading etcd cluster 2.3 to 3.0 

### ISSUE THREAD

**Issue by berry2012** [coreos/etcd#7169]
I have 3nodes in my cluster 

1 returned
curl -L http://127.0.0.1:4001/version
curl: (7) Failed to connect to 127.0.0.1 port 4001: Connection refused

2 returned
curl -L http://127.0.0.1:4001/version
{"etcdserver":"2.3.7","etcdcluster":"2.3.0"}

As advised to upgrade the cluster to 3.0 to resolve the issue of the node returning connection refused since it couldn't start etcd2 service due to maybe broken snapshots. 

I am following this guide https://coreos.com/etcd/docs/latest/upgrades/upgrade_3_0.html#upgrade-procedure but I don't know how to achieve step 3
**3. Drop-in etcd v3.0 binary and start the new etcd process**

**Comment by gyuho** [comment]
`Drop-in` means start the same etcd command with same etcd flags (same `--data-dir` or `--wal-dir`).

Did you have any error logs in etcd2 service?

**Comment by xiang90** [comment]
it means replace your old binary with new binary file: copying the new file to the current etcd binary location.

**Comment by shamalco** [comment]
Do you guys have an example of a drop-in file for etcdv3? That would be a great help if you can

**Comment by heyitsanthony** [comment]
@shamalco what sort of configuration changes are you looking for with a systemd drop-in? Something like the [clustering guide](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md)?

**Comment by shamalco** [comment]
Yes something similar to that:

But more fundamental what in drop-in file is need to covert a etcd2 to etcd3

For example I am running HTTPs etcd2 cluster, what is the configuration need in that drop-in to successful shift to etcdv3? Similar style to  [https://coreos.com/etcd/docs/latest/etcd-live-http-to-https-migration.html](url) drop in files used as an example there would be perfect.

**Comment by heyitsanthony** [comment]
@shamalco so long as the configuration isn't using any flags marked as deprecated in 2.x, it should be the same for 3.x.

**Comment by gyuho** [comment]
@shamalco 

> Do you guys have an example of a drop-in file for etcdv3? That would be a great help if you can

We've just added systemd guide for v3 here https://github.com/coreos/etcd/pull/7956, if you use Container Linux.

**Comment by shamalco** [comment]
Great Thanks @gyuho
