### ISSUE TITLE
CoreOs cluster restarted all containers due to etcd errors

### ISSUE THREAD

**Issue by mshahpalerra** [coreos/etcd#7177]
Hello
  We just saw a pretty server issue on our production CoreOs setup. Details are:

- 3 CoreOs nodes running in AWS EC2 Us East1
- m3.2xlarge instance types
- CoreOS nodes - 2 are DISTRIB_RELEASE=1068.2.0 and 1 is at DISTRIB_RELEASE=1081.5.0
- etcd version 0.4.9
- we have auto update disabled on CoreOs
- Around 21:56 UTC on Jan 17 we saw all our containers go down and the logs seemed to suggest an issue with etcd

Jan 17 21:56:22 ip-10-26-31-100.ec2.internal fleetd[999]: ERROR server.go:189: Server monitor triggered: Monitor timed out before successful heartbeat
Jan 17 21:56:22 ip-10-26-31-100.ec2.internal fleetd[999]: INFO server.go:157: Establishing etcd connectivity
Jan 17 21:56:22 ip-10-26-31-100.ec2.internal fleetd[999]: ERROR engine.go:179: Engine leadership acquisition failed: context deadline exceeded
Jan 17 21:59:41 ip-10-26-31-100.ec2.internal fleetd[999]: INFO server.go:168: Starting server components
Jan 17 21:59:42 ip-10-26-31-100.ec2.internal fleetd[999]: INFO engine.go:185: Engine leadership acquired
Jan 17 21:59:43 ip-10-26-31-100.ec2.internal fleetd[999]: ERROR engine.go:254: Failed unscheduling Unit(kafka-broker-1.service) from Machine(6ca65ead2f164b2682c0d941c8a75d9b): context deadline exceeded
Jan 17 21:59:43 ip-10-26-31-100.ec2.internal fleetd[999]: ERROR reconciler.go:62: Failed resolving task: task={Type: UnscheduleUnit, JobName: kafka-broker-1.service, MachineID: 6ca65ead2f164b2682c0d941c
Jan 17 21:59:44 ip-10-26-31-100.ec2.internal fleetd[999]: ERROR engine.go:254: Failed unscheduling Unit(newNewApps.service) from Machine(6ca65ead2f164b2682c0d941c8a75d9b): context deadline exceeded

- We checked the CPU and disk IO for all 3 instances, there is NO indication of any CPU spike per AWS Cloudwatch
- ETCD config is as below
core@ip-10-26-33-251 ~ $ sudo systemctl cat etcd
# /usr/lib64/systemd/system/etcd.service
[Unit]
Description=etcd
Conflicts=etcd2.service

[Service]
User=etcd
PermissionsStartOnly=true
Environment=ETCD_DATA_DIR=/var/lib/etcd
Environment=ETCD_NAME=%m
ExecStart=/usr/bin/etcd
Restart=always
RestartSec=10s
LimitNOFILE=40000

# /run/systemd/system/etcd.service.d/10-oem.conf
[Service]
Environment=ETCD_PEER_ELECTION_TIMEOUT=1200
# /run/systemd/system/etcd.service.d/20-cloudinit.conf
[Service]
Environment="ETCD_ADDR=10.26.33.251:4001"
Environment="ETCD_CERT_FILE=/home/etcd/certs/cert.crt"
Environment="ETCD_DISCOVERY=https://discovery.etcd.io/<BLAH>"
Environment="ETCD_KEY_FILE=/home/etcd/certs/key.pem"
Environment="ETCD_PEER_ADDR=10.26.33.251:7001"
- Attached the fleet & etcd logs from all nodes

[etcd-10-26-31-100.txt](https://github.com/coreos/etcd/files/712606/etcd-10-26-31-100.txt)
[etcd-10-26-32-94.txt](https://github.com/coreos/etcd/files/712607/etcd-10-26-32-94.txt)
[etcd-10-26-33-251.txt](https://github.com/coreos/etcd/files/712604/etcd-10-26-33-251.txt)
[fleet-10-26-31-100.txt](https://github.com/coreos/etcd/files/712603/fleet-10-26-31-100.txt)
[fleet-10-26-32-94.txt](https://github.com/coreos/etcd/files/712605/fleet-10-26-32-94.txt)
[fleet-10-26-33-251.txt](https://github.com/coreos/etcd/files/712602/fleet-10-26-33-251.txt)
- AWS status dashboard does not show any errors or issues on their end

Appreciate if someone can take a look at the above and give us any pointers on what to look at and what we can do to mitigate this.

Thx
Maulik

**Comment by heyitsanthony** [comment]
A few things:

* Some clients are trying to access etcd either through an http endpoint or with the wrong certs:
```
http: TLS handshake error from 10.26.11.64:19866: EOF
...
http: TLS handshake error from 127.0.0.1:59032: tls: first record does not look like a TLS handshake
```

* The etcd cluster is still accepting writes; it appears healthy:
```
etcd] Jan 17 19:50:59.580 INFO      | 561f7d156ce24a5196696cc1c466fcea: snapshot of 10003 events at index 493628340 completed
```

* fleet appears to be spinning on very out-of-date revisions:
```
Jan 17 20:14:52 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282006 != 377975623]) [377975623]
Jan 17 20:14:56 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282050 != 377975657]) [377975657]
Jan 17 20:15:00 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282083 != 377975695]) [377975712]
Jan 17 20:15:04 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282137 != 377975733]) [377975753]
Jan 17 20:15:08 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282177 != 377975778]) [377975778]
Jan 17 20:15:12 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282201 != 377975812]) [377975812]
Jan 17 20:15:16 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282234 != 377975867]) [377975867]
Jan 17 20:15:20 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282288 != 377975926]) [377975931]
```

* 0.4.9 is ancient and is officially slated to be EOL'd: https://coreos.com/blog/toward-etcd-v3-in-container-linux.html

Is there any evidence the etcd cluster is broken? Looks like a fleet bug.

**Comment by mshahpalerra** [comment]
@heyitsanthony thanks for the quick response:

- Some clients are trying to access etcd either through an http endpoint
>> That is an AWS ELB we have and is mostly just healthchecks from the ELB

- When you say fleet is spinning on old revisions - can you provide some more insight here? Would we need to restart fleet daemon to recover? Sorry if these are dumb questions

- Point take on etcd update - will schedule that on our end (am guessing its a CoreOS upgrade in general)

- there is no evidence that etcd is broken other than the errors we see in fleet pointing to a leadership failure which I thought (perhaps incorrectly) was with etcd

**Comment by mshahpalerra** [comment]
Also should or can I move this issue to Fleet from etcd?

**Comment by heyitsanthony** [comment]
@mshahpalerra yes, probably file under http://github.com/coreos/fleet/issues 

fleet is using a compare and swap on based on key revision to safely renew leadership:
```
Jan 17 20:14:52 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282006 != 377975623]) [377975623]
Jan 17 20:14:56 ip-10-26-32-94.ec2.internal fleetd[985]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378282050 != 377975657]) [377975657]
```
Here, it's using a key that's behind by about 300k revisions. It's unclear to me why it's drifted by that much and why it's staying so far behind. It's possible etcd is returning bad indexes. @xiang90 might know whether something like that has ever been observed in the past.

From the logs, it looks like the etcd cluster is ingesting about 600--1000 writes per minute:
```
etcd-10-26-32-94.txt:Jan 17 18:56:29 ip-10-26-32-94.ec2.internal etcd[976]: [etcd] Jan 17 18:56:29.773 INFO      | 6ca65ead2f164b2682c0d941c8a75d9b: snapshot of 10046 events at index 493587348 completed
etcd-10-26-32-94.txt:Jan 17 19:09:50 ip-10-26-32-94.ec2.internal etcd[976]: [etcd] Jan 17 19:09:50.996 INFO      | 6ca65ead2f164b2682c0d941c8a75d9b: snapshot of 10005 events at index 493597353 completed
```
So the fleet member is behind by about five hours somehow.

I'm not a fleet expert so I don't know what the correct course of action would be. Resetting the fleet the daemon probably can't make things any worse, at least.

**Comment by mshahpalerra** [comment]
@heyitsanthony  thanks - we did restart fleet - however we are still seeing:

Jan 18 00:50:34 ip-10-26-31-100.ec2.internal fleetd[20619]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378128986 != 378128996]) [378129072]
Jan 18 00:50:37 ip-10-26-31-100.ec2.internal fleetd[20619]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378128996 != 378129075]) [378129075]
Jan 18 00:50:39 ip-10-26-31-100.ec2.internal fleetd[20619]: INFO engine.go:79: Engine leader is 0616336811914769b7f29e3bc5ea3c1b


Jan 18 00:55:21 ip-10-26-31-100.ec2.internal fleetd[20619]: ERROR server.go:189: Server monitor triggered: Monitor timed out before successful heartbeat
Jan 18 00:55:21 ip-10-26-31-100.ec2.internal fleetd[20619]: INFO server.go:157: Establishing etcd connectivity
Jan 18 00:55:24 ip-10-26-31-100.ec2.internal fleetd[20619]: INFO server.go:168: Starting server components
Jan 18 00:55:24 ip-10-26-31-100.ec2.internal fleetd[20619]: INFO engine.go:185: Engine leadership acquired
Jan 18 00:55:24 ip-10-26-31-100.ec2.internal fleetd[20619]: INFO engine.go:81: Engine leadership changed from 0616336811914769b7f29e3bc5ea3c1b to 561f7

where fleet leadership continues to move around. We can restart etcd if that helps (am not sure if the keys are ephemeral) - any comments?

Is there a way to move this issue in Github to fleet or I have to a file a new one with all the details?

**Comment by heyitsanthony** [comment]
@mshahpalerra just file a new one. This can stay open in case it's an etcd bug.

The fleet keys for leader election have a ttl, which is effectively ephemeral.

**Comment by mshahpalerra** [comment]
@heyitsanthony  thanks - opened another issue - however we are seeing the below errors:

10.26.32.94 shows
ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378459038 != 378157064]) [378157073]

10.26.33.251 shows
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO reconcile.go:330: AgentReconciler completed task: type=ReloadUnitFiles job=N/A reason="always reload unit files"
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO manager.go:246: Writing systemd unit apprity-home-data-3-unit-1.service (1924b)
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO manager.go:182: Instructing systemd to reload units
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO manager.go:127: Triggered systemd unit apprity-home-data-3-unit-1.service start: job=3981
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO reconcile.go:330: AgentReconciler completed task: type=LoadUnit job=apprity-home-data-3-unit-1.service reason="unit scheduled here but not loaded"
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO reconcile.go:330: AgentReconciler completed task: type=ReloadUnitFiles job=N/A reason="always reload unit files"
Jan 18 02:10:53 ip-10-26-33-251.ec2.internal fleetd[924]: INFO reconcile.go:330: AgentReconciler completed task: type=StartUnit job=apprity-home-data-3-unit-1.service reason="unit currently loaded but desired state is launched"
Jan 18 02:10:54 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166410 != 378166604]) [378166604]
Jan 18 02:10:58 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166417 != 378166610]) [378166610]
Jan 18 02:11:02 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166422 != 378166612]) [378166612]
Jan 18 02:11:06 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166423 != 378166752]) [378166752]
Jan 18 02:11:10 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166562 != 378166754]) [378166754]
Jan 18 02:11:14 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166563 != 378166756]) [378166756]
Jan 18 02:11:17 ip-10-26-33-251.ec2.internal fleetd[924]: WARN job.go:268: No Unit found in Registry for Job(feed_syslog.service)
Jan 18 02:11:17 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR job.go:108: Failed to parse Unit from etcd: unable to parse Unit in Registry at key /_coreos.com/fleet/job/feed_syslog.service/object
Jan 18 02:11:17 ip-10-26-33-251.ec2.internal fleetd[924]: WARN job.go:268: No Unit found in Registry for Job(feed_syslog.service)
Jan 18 02:11:17 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR job.go:108: Failed to parse Unit from etcd: unable to parse Unit in Registry at key /_coreos.com/fleet/job/feed_syslog.service/object
Jan 18 02:11:18 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166564 != 378166758]) [378166804]
Jan 18 02:11:22 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166611 != 378166898]) [378166898]
Jan 18 02:11:26 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166704 != 378166900]) [378166900]
Jan 18 02:11:31 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:149: Unable to determine cluster engine version
Jan 18 02:11:31 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR state.go:71: Failed fetching page of UnitStates: context deadline exceeded
Jan 18 02:11:32 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:217: Engine leadership lost, renewal failed: 101: Compare failed ([378166705 != 378166903]) [378166903]
Jan 18 02:11:35 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:149: Unable to determine cluster engine version
Jan 18 02:11:36 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR state.go:71: Failed fetching page of UnitStates: context deadline exceeded
Jan 18 02:11:37 ip-10-26-33-251.ec2.internal fleetd[924]: ERROR engine.go:149: Unable to determine cluster engine version

We are not seeing anything wrong on the nodes - rebooted 10.26.33.251 for kicks but no luck

**Comment by xiang90** [comment]
This is probably a fleet issue, not an etcd one. As an issue already created in fleet repo, I am closing the one here. Thanks for reporting.
