### ISSUE TITLE
How to Upgrade etcd.

### ISSUE THREAD

**Issue by tianxiaoliang** [coreos/etcd#7179]
If I want to upgrade from 3.0.15 to 3.0.16, Can I just use rolling update strategy? or just shutdown whole cluster and then upgrade? also in the future maybe I want to upgrade from 3.1 to 3.2. Is it possible to upgrade with  zero-downtime?

**Comment by gyuho** [comment]
See https://github.com/coreos/etcd/tree/master/Documentation#upgrading-and-compatibility.

Basically you can do rolling upgrade one node by one node.
