### ISSUE TITLE
"/x/net/context" in go1.7+

### ISSUE THREAD

**Issue by mwf** [coreos/etcd#7180]
Hello! 

I've got such a problem with go1.7+ and glide for vendoring.

If I set the only dependency on etcd and use "context" from go1.7 standart lib, I'm risking to hit a panic from grpc-go.
`panic: Unexpected error from context packet: context canceled`
It happens since they switch on context error: https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L573

It happens because etcd depends on old "golang.org/x/net" version, before go1.7 was released. 
I think you know that in newer "/x/net/context" versions aliasing to go1.7 "context" is used.

Current workaround is to set proper "/x/net/context" version directly in my project.

So I suggest updating "/x/net/context" version to make it easier to use etcd with go1.7+ out of box. What do you think about it?

PS Unfortunately, "golang.org/x/net" authors don't use SemVer, and I don't understand why :( So we still have to use the commit hashes and observe Glide warnings of version collisions...

**Comment by heyitsanthony** [comment]
@mwf So it'll still build with 1.6? Probably worth doing for 3.1, then.

**Comment by mwf** [comment]
@heyitsanthony yeap, it still builds under 1.6 - https://github.com/golang/net/tree/master/context

Does 3.1 client works good with 3.0.15 server? Or there are some features which won't work?
It's a pity I'm late for new 3.0.16 release :)

**Comment by heyitsanthony** [comment]
@mwf 3.1's locks/elections use some newer features that are incompatible with 3.0, but aside from that I'm unaware of any other incompatibilities.

**Comment by mwf** [comment]
@heyitsanthony unfortunately, I know nothing about this locks and elections :(
Is it some configuration feature of 3.1 cluster or something internal for 3.1 Client, used when doing Get, Put, Wait and other operations?

**Comment by heyitsanthony** [comment]
@mwf It's part of clientv3/concurrency. If you don't know about it, you're probably not using it.

**Comment by mwf** [comment]
Great, than I think it will be perfectly OK to have this update in 3.1
But if you ever release 3.0.17 (I doubt that), would be great to include this little fix there :)

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/7186.

It's backported to `release-3.1` branch. We will release v3.1 this Friday. Thanks.
