### ISSUE TITLE
feature request: support user defined grpc services for embed etcd.

### ISSUE THREAD

**Issue by disksing** [coreos/etcd#7200]
Hey,
Our project (https://github.com/pingcap/pd) is currently using etcd as an embed library, and sharing the same network port with etcd by setting up `UserHandlers`(https://github.com/coreos/etcd/blob/master/embed/config.go#L127).

Now our project needs to add gRPC support. It turns out that if we still want to reuse port, we need a way to register our grpc serivces to grpcServer which is created inside etcd.

I've roughly browsed the code. I guess we may add a `map[grpc.serviceDesc]interface{}` filed in `Config`, just like the `UserHandlers`, or do you have any suggestions?

**Comment by siddontang** [comment]
Hi  @xiang90 

We can define a gRPC user handler, if you think it is ok, we can send PR.

**Comment by heyitsanthony** [comment]
sounds reasonable

**Comment by xiang90** [comment]
@siddontang I am OK with it.
