### ISSUE TITLE
Query: Need command to auto-generate protobuf for rpc.proto

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#7201]
I need the command for generating rpc.pb.go and rpc.pb.gw.go using rpc.proto since while generating in the below way: 
```
protoc -Igithub.com\coreos\etcd\etcdserver\etcdserverpb\rpc.proto -Igithub.com\coreos -Igithub.com\gogo\protobuf -Igithub.com\grpc-ecosystem\grpc-gateway\third_party\googleapis --go_grpc_out=github.com\coreos\etcd\etcdserver\etcdserverpb
```

I am getting a lot of difference between the current rpc.pb.go and the newly generated one. Also want to know from which directory its being generated.
Thanks!

**Comment by gyuho** [comment]
@sinsharat You have to run this script https://github.com/coreos/etcd/blob/master/scripts/genproto.sh

```
# from etcd repo root directory
./scripts/genproto.sh
```

**Comment by sinsharat** [comment]
@gyuho Thanks a lot! Will try it out!

**Comment by gyuho** [comment]
Yeah let us know if you have any questions!
