### ISSUE TITLE
Q: is the etcd raft algorithm suitable for atomic transactions?

### ISSUE THREAD

**Issue by glycerine** [coreos/etcd#7202]
Q: is the etcd raft implementation suitable for transactions?

 - the fundamental idea of a transaction is that
   it either succeeds or fails atomically, *and*
   that the client accurately knows whether it has
   succeeded or failed in doing the transaction.

   If the system can falsely tell the client
   that the transaction failed when it actually
   succeeded, this does not seem to meet the
   prima facia requirements of a transaction.

 - Raft can report failure to clients when a
   transaction succeeded. Per https://raft.github.io/raft.pdf
   in section 8 "Client Interaction":

> Our goal for Raft is to implement linearizable seman-
tics (each operation appears to execute instantaneously,
exactly once, at some point between its invocation and
its response). However, as described so far Raft can exe-
cute a command multiple times: for example, if the leader
crashes after committing the log entry but before respond-
ing to the client, the client will retry the command with a
new leader, causing it to be executed a second time. The
solution is for clients to assign unique serial numbers to
every command. Then, the state machine tracks the latest
serial number processed for each client, along with the as-
sociated response. If it receives a command whose serial
number has already been executed, it responds immedi-
ately without re-executing the request.

Given that, the question becomes: does etcd implement
this aspect of de-duplication of requests by unique serial number?

 Or can clients get false information about transaction failure and end up with duplicate instead of atomic transactions?

**Comment by xiang90** [comment]
> is the etcd raft implementation suitable for transactions?

No. etcd/raft is a minimal raft implementation. This does not have to live inside core raft, so we leave it out.

> Or can clients get false information about transaction failure and end up with duplicate instead of atomic transactions?

Yes or no. etcd implements txn at its API layer. User can choose to use it if they care about what you mentioned.

For etcd API, if you use raw PUT, then you will not know if the request is committed or not when there is a network failure. Resubmit the PUT request can lead to duplicate commit.

But if you use the Txn API, you can do things like:

```go
Txn.If(foo.version==6),Then(put foo=bar)
```

Resubmit it until succeeding will not lead to duplicate put since it is guarded by the comparison.

**Comment by glycerine** [comment]
very helpful! thank you Xiang. etcd has really gotten so impressive. even a zookeeper replacement interface! wow.

**Comment by xiang90** [comment]
> even a zookeeper replacement interface! wow.

Credit goes to @heyitsanthony. But yea, please give it a try! I want some feedback on it.

**Comment by glycerine** [comment]
doesn't quite look ready for prime time yet -- https://github.com/coreos/zetcd/issues/11

there are plenty of java applications (hadoop etc) that use zookeeper; it shouldn't be difficult to get a rigorous set of tests.
