### ISSUE TITLE
Build : Getting error while updating and running integration test

### ISSUE THREAD

**Issue by sinsharat** [coreos/etcd#7212]
On performing go get -v second time for etcd, it gives  error. The same etcd/etcdserver/etcdserverpb/rpc.pb.go:2170: undefined: grpc.SupportPackageIsVersion4 error is coming while trying to run integration test.

![screenshot from 2017-01-21 20-52-43](https://cloud.githubusercontent.com/assets/20169156/22175497/b593046a-e01b-11e6-99c3-055e5522e308.png)

**Comment by glycerine** [comment]
go get will fetch master, which, as the documentation on the front page says, may be in a broken or inconsistent state. try a release instead.

**Comment by sinsharat** [comment]
@glycerine the problem is not alone with the build but also not able to run integration test.Can you suggest a way to test it?

**Comment by xiang90** [comment]
you need to do glide install to recover the vendor dir. 

```
install glide

cd $etcd
glide install
cd integration
go test -v
```
