### ISSUE TITLE
query: write a etcd data from proxy node

### ISSUE THREAD

**Issue by nenzhang** [coreos/etcd#7223]
Hi
when write the etcd data from proxy node, and received the HTTP request response is ok, and then use etcdctl to query the key, it looks not there sometimes.
we detect this occasionally after long times run in stability testing.

so is it because that the data actually not really synced into all etcd instances to disk so the query request gets failed from another etcd instance endpoint ip?

the version is
# etcdctl --version
etcdctl version: 3.0.12
API version: 2

**Comment by xiang90** [comment]
If you use v2 API, you might read stable data unless you explicitly specify quorum option. Or etcd server can serve read locally.

**Comment by nenzhang** [comment]
Hi
ok, so you mean we shall specify the quorum option, right? we will try.
