### ISSUE TITLE
Different sized backups when using "etcdctl backup" command

### ISSUE THREAD

**Issue by ApsOps** [coreos/etcd#7224]
# Question

When I take backup using `etcdctl`, I get different sized backups when running command repeatedly.

Is this expected behavior? What's the reason behind such huge difference?

```bash
/ # etcdctl backup --data-dir /var/etcd/ --backup-dir /tmp/bckup
/ # du -h /tmp/
59.3M   /tmp/bckup/member/wal
13.5M   /tmp/bckup/member/snap
72.7M   /tmp/bckup/member
72.7M   /tmp/bckup
/ # rm -rf /tmp/bckup/
/ # etcdctl backup --data-dir /var/etcd/ --backup-dir /tmp/bckup
/ # du -h /tmp/bckup/
5.6M    /tmp/bckup/member/wal
16.7M   /tmp/bckup/member/snap
22.3M   /tmp/bckup/member
22.3M   /tmp/bckup/
```

This is the actual data size:
```bash
/ # du -h /var/etcd/
305.2M  /var/etcd/member/wal
74.2M   /var/etcd/member/snap
379.4M  /var/etcd/member
379.4M  /var/etcd/
```

**Comment by xiang90** [comment]
etcdserver keeps N historical WAL + Snapshot files. See configuration. So if one of them is broken, your server might still be able to come up. Backup only saves the latest one. So there is a difference.
