### ISSUE TITLE
vendor: evaluate 'github.com/golang/dep'

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#7225]
Experiment with official Go's dependency management tool https://github.com/golang/dep

**Comment by gyuho** [comment]
We can't use this until this is addressed https://github.com/golang/dep/issues/120.
Currently `dep` would introduce extra >1million lines of vendor code.

**Comment by xiang90** [comment]
i do not believe this can happen in 3.3 release cycle based on the progress of golang/dep. @gyuho can we move this out of 3.3?

**Comment by olivere** [comment]
As asked in #8692, here's my very brief summary of checking with `dep` again, on my [fork of etcd](https://github.com/olivere/etcd) on a MBP.

```
$ uname -a
Darwin violet 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
$ glide -v
glide version 0.13.0
$ rm -rf vendor
$ glide i
...
$ du -h vendor | wc -l
     537
$ du -h vendor | tail -1
 43M	vendor
```

Next up, `dep`:

```
$ dep version
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.9.1
 go compiler : gc
 platform    : darwin/amd64
$ rm -rf vendor
$ dep init
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
Detected glide configuration files...
Converting from glide.yaml and glide.lock...
  Using * as initial constraint for imported dep github.com/bgentry/speakeasy
  Trying * (36e9cfd) as initial lock for imported dep github.com/bgentry/speakeasy
  Using ^1.3.0 as initial constraint for imported dep github.com/boltdb/bolt
  Trying v1.3.0 (583e893) as initial lock for imported dep github.com/boltdb/bolt
...
$ du -h vendor | wc -l
     688
$ du -h vendor | tail -1
 62M	vendor
```

**Comment by gyuho** [comment]
I remember we had to add some `[[override]]` rules.

**Comment by olivere** [comment]
@gyuho Sorry. I just updated my findings--I forgot to merge from upstream first. The numbers changed a bit, but the end result is basically the same.

**Comment by gyuho** [comment]
Plan to migrate to `dep`  after 3.3 release. I migrated another project with `dep`

1. https://github.com/coreos/dbtester/blob/master/scripts/updatedep.sh
2. https://github.com/coreos/dbtester/blob/master/Gopkg.toml
3. https://github.com/coreos/dbtester/blob/master/.gitignore

We need `.gitignore` updates until `dep` implements pruning.
