### ISSUE TITLE
4 to 5 x iops load.

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#7232]
When comparing v2 vs. v3 iop load under similar conditions we are seeing iop load that is between 4 to 5 times higher than v2.  

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1415839

/cc @wojtek-t @gmarek @xiang90 @hongchaodeng

**Comment by xiang90** [comment]
@timothysc 

etcd2 write path only touches WAL file. But when etcd2 does a snapshot, it would write out entire DB at once. So there will be IO spikes when it does snapshot. This can slow everything down unpredictably. This is VERY bad for large clusters with GB data, which can slow down all operations for ~10 seconds when doing a full snapshot.

etcd3 write path touches both WAL and on-disk DB (although batched). With this improvement, etcd3 never does full snapshot, thus no IO spikes. However, obviously it introduces more IOs on normal write path. I would expect etcd3 to issue 2-3x more iops on average. 

On the other side, I would suggest him to try etcd 3.1, which eliminates IOs on read path. That should reduce at least 30% Kubernetes I/Os.

If you can give us a more specific reproduce steps, we will try to see why there are 4-5x more IOPS. (Is it possible that the system goes faster when etcd3 is installed, which actually issues more requests?)

I looked at the issue in redhat bugzilla, it seems that the iops of the system is throttled heavily. Some IOs are queued for a few seconds. This is pretty abnormal.

**Comment by xiang90** [comment]
@timothysc One more question, do you know if he removes ALL data in v2? Or there will be double writes. (v2 periodically does the full snapshot)

**Comment by timothysc** [comment]
@xiang90 on that BZ it is etcd 3.0.15 running in v2 mode with no converted data to v3, compared to 2.3.7 iop behavior.

**Comment by xiang90** [comment]
@timothysc Oh. Interesting. Then I am not sure why. /cc @heyitsanthony Anything changed significantly between 2.3.7 to 3.0.x on WAL pkg that might introduce 5x iops?

**Comment by timothysc** [comment]
@xiang90 the test isn't ideal though, they upgraded openshift versions too :-/

**Comment by heyitsanthony** [comment]
@xiang90 @timothysc the only fundamental difference is it's preallocating via fallocate. There might be some interference caused by the fs implementation leading to bad latencies eventually triggering leader elections, followed by an application recovery phase compounding the problem.

If it's possible to deploy a custom etcd binary, this patch may fix it by never allocating up front:
```diff
diff --git a/pkg/fileutil/preallocate_unix.go b/pkg/fileutil/preallocate_unix.go
index 50bd84f..5620b74 100644
--- a/pkg/fileutil/preallocate_unix.go
+++ b/pkg/fileutil/preallocate_unix.go
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.

-// +build linux
+// +build dontbuild

 package fileutil

diff --git a/pkg/fileutil/preallocate_unsupported.go b/pkg/fileutil/preallocate_unsupported.go
index 162fbc5..f728847 100644
--- a/pkg/fileutil/preallocate_unsupported.go
+++ b/pkg/fileutil/preallocate_unsupported.go
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.

-// +build !linux,!darwin
+// +build linux,!darwin

 package fileutil
```

(if it does, fallocate can be made a tunable)

**Comment by timothysc** [comment]
So we got word from @mffiedler that v2 vs. v3 (in 2 mode) across the same release showed little/no iop difference so closing.  My apologies for the fire drill.

**Comment by timothysc** [comment]
I'm going to reopen this, but change the title slightly.  What we're see is a fairly large iop spike, but I'm not seeing excessive puts.  I have etcd-debug logs as well to correspond to this data: 

![image](https://cloud.githubusercontent.com/assets/169553/22741826/2d81eaec-edda-11e6-9dc7-4dcd2a87b66c.png)

**Comment by wojtek-t** [comment]
Is it possible that now object are larger? Actually, even if, would it result in more iops?

**Comment by timothysc** [comment]
I have the raw etcd-debug logs here: 

https://drive.google.com/file/d/0Bzq0eFfVveNqWUZCM3hEaVNad3c/view?usp=sharing

the graph corresponds to svt-e-1 dir.

**Comment by heyitsanthony** [comment]
@timothysc is this 4x--5x a comparison between 2.3 and 3.0 using the same openshift version?

**Comment by timothysc** [comment]
@heyitsanthony above is the high iop experimental data.  What I can't ascertain is, "why" the iop load is so high... there is not a high level of [PUT]s in the logs.  What else   

By comparison here is the previous experimental data: 

![image](https://cloud.githubusercontent.com/assets/169553/22745128/19d8df0e-ede5-11e6-87d1-75918cd95ff2.png)

**Comment by heyitsanthony** [comment]
I wasn't asking why, I wanted to know if this is an apples-to-apples comparison when claiming a 4x difference; what is being compared, exactly? Is it still different openshift versions?

**Comment by timothysc** [comment]
Yes it is two different openshift versions, but when enabling debug logs on etcd... I don't see an excessive number of [PUT]s that would lead me to understand why there are more writes.

**Comment by heyitsanthony** [comment]
@timothysc what about quorum gets? Those incur a write too in 2.3/3.0. Does the same behavior appear when using 2.3?

**Comment by timothysc** [comment]
k, closing this again, and moving this to kubernetes & openshift.

**Comment by gmarek** [comment]
@timothysc - secrets should go away in the head, as we stopped serving all the gets from etcd, and started serving them from the cache. Doing exactly the same thing for serviceaccounts should be trivial (pretty much copy-paste of the secret code). But that's for reads only...

EndpointController is being rewritten, so it may change the behavior soon-ish.

@wojtek-t

**Comment by wojtek-t** [comment]
What is reading/writing ServiceAccounts that intensively? It's not copy-paste, because I don't think kubelet is doing that...

**Comment by gmarek** [comment]
Aaah, sorry - I read serviceaccounts, and understood configmaps.

**Comment by timothysc** [comment]
@gmarek @wojtek-t lets move the conversation to https://github.com/kubernetes/kubernetes/issues/41143
