### ISSUE TITLE
How to limit /member/snap/db file size

### ISSUE THREAD

**Issue by vania-pooh** [coreos/etcd#7244]
Using ```etcd 3.0.15``` from container ```quay.io/coreos/etcd:v3.0.15```. My question is: is there any way to limit /member/snap/db file size? In my app there's no need to store any history of key values in etcd. My usage pattern is:
1) Save key from one application instance.
2) Delete key from another application instance. Other instances are watching for delete event.
When the key is deleted etcd should forget about it.

Currently I'm launching etcd with the following parameters:
```
        "Path": "/usr/local/bin/etcd",
        "Args": [
            "--name",
            "one",
            "--initial-advertise-peer-urls",
            "http://one.net:2380",
            "--listen-peer-urls",
            "http://one.net:2380",
            "--advertise-client-urls",
            "http://one.net:2379",
            "--listen-client-urls",
            "http://one.net:2379",
            "--initial-cluster",
            "one=http://one.net:2380,two=http://two.net:2380,three=http://three.net:2380",
            "--initial-cluster-state",
            "new",
            "--initial-cluster-token",
            "etcd",
            "--data-dir",
            "/var/lib/etcd",
            "--max-snapshots",
            "1",
            "--max-wals",
            "1",
            "--auto-compaction-retention",
            "1"
        ],
```
However the file above continues to grow. I expect that after I hour some snapshot entities should be deleted (and I see they are in log file) and some procedure (e.g. defrag) should reduce file size. Where is my error?

**Comment by gyuho** [comment]
See https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#defragmentation.

We do have `defrag` command.

**Comment by heyitsanthony** [comment]
@vania-pooh 

How much is the db growing? The compaction should free up pages in the db; it shouldn't keep growing indefinitely even if there's no defrag. Is there an upper bound to the number of keys the application will store to etcd? (judging by your description, yes, but just want to confirm)

Is the scheduled compaction happening? The compaction event won't mention snapshots.The etcd log should have an entry like:
```
2017-01-27 09:58:20.884759 I | mvcc: store.index: compact 4
2017-01-27 09:58:20.884949 I | mvcc: finished scheduled compaction at 4 (took 39.1µs)
```

**Comment by vania-pooh** [comment]
Yes, file size seems to be limited. My keys have uuid values and are using leases. Here's how I'm using etcd:
```
func (storage *EtcdStorage) AddSession(id string) {
	lease, err := storage.c.Grant(storage.ctx, int64(requestTimeout))
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	_, err = storage.c.Put(storage.ctx, id, string(lease.ID), client.WithLease(lease.ID))
	if err != nil {
		fmt.Println(err.Error())
		return
	}
}

func (storage *EtcdStorage) DeleteSession(id string) {
	resp, err := storage.c.Get(storage.ctx, id)
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	for _, 	ev := range resp.Kvs {
		leaseId, err := strconv.Atoi(string(ev.Value))
		if (err != nil) {
			storage.c.Delete(storage.ctx, id)
		} else {
			//Automatically deletes key
			storage.c.Revoke(storage.ctx, client.LeaseID(leaseId))
		}
	}
}
```
Here ```storage.c``` is etcd client v3. One instance of my application saves a key with uuid and lease ID (used to timeout the key) via AddSession method. Another instance deletes the key by getting lease ID and revoking it. Is it a correct approach?

**Comment by heyitsanthony** [comment]
> Yes, file size seems to be limited. 

So is the DB growing or not? If it is, by how much?

> [code]

That code does more than it has to do. The lease id will already be in `resp.Kvs[i].Lease`, so there's no need to store the lease id in the key's value; `storage.c.Revoke(storage.ctx, ev.Lease)` should always work.

Are you seeing the compaction messages in the log?

What's the TTL on the leases? It could be leaking leases if the TTL is very long (although it would take a lot of leases to significantly impact db size).

**Comment by vania-pooh** [comment]
1) Thank you for code review. I was sure there's better way to achieve my requirements.
2) Db file is about 250 megabytes. TTL is 20 minutes. I see compaction messages in log. So I think there's no issue. Let's close this and if I notice something strange, will reopen.
