### ISSUE TITLE
readiness API endpoint without auth

### ISSUE THREAD

**Issue by chulkilee** [coreos/etcd#7245]
When etcds authenticate clients using HTTPS client certificates, it is difficult to set up load balancer since not all load balancer supports it - especially Amazon ELB.

Although there are way to circumvent it (e.g. bind insecure http on private ip only reachable from load balancer), I think it would be nice to have *optional* readiness API endpoint which does not require any authentication.

For readiness (vs liveness) - see https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/ 

Edit: add "optional"

**Comment by heyitsanthony** [comment]
I think it's best to err on the side of caution with TLS, especially if there's already a workaround.

**Comment by xiang90** [comment]
@chulkilee TLS auth is designed for auth from the connection layer. The HTTP endpoint is at a layer above. If you want to have per resource (endpoint) auth, you probably should try the etcd-auth at application layer. The health endpoint can be accessed by all users.

Even with TLS auth, there exists workaround as you mentioned, so I do not feel this is something we want to solve, at least for short term.

**Comment by chulkilee** [comment]
All make sense - but where is documentation for v3 auth api? https://coreos.com/blog/etcd-3-1-announcement.html says "The etcd v3 authentication API, which was alpha in the 3.0 series, is now stable" but I could not find any doc for this, so I thought v3 only supports TLS client certs auth.

**Comment by xiang90** [comment]
@chulkilee 

https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#service-auth-etcdserveretcdserverpbrpcproto

https://github.com/coreos/etcd/blob/master/etcdctl/README.md#authentication-commands

@mitake We probably need a dedicate Auth doc for v3?

**Comment by mitake** [comment]
@chulkilee @xiang90 sure, I created an issue for the doc: https://github.com/coreos/etcd/issues/7251

**Comment by chulkilee** [comment]
Thanks for all the quick response. Closing this.
