### ISSUE TITLE
Add docs about v3 auth API and usage

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#7251]
- [x] Import a digested version of the design doc: https://goo.gl/fwBxz6
- [x] Release note and usage guide of CN based auth (after finishing the PR): https://github.com/coreos/etcd/pull/6881
- [x] Release note and description about token types (after finishing the PR of jwt token): https://github.com/coreos/etcd/pull/6082

**Comment by xiang90** [comment]
@mitake Thanks! We finish all of them. So closing.
