### ISSUE TITLE
etcdmain: invalid config errors don't respect --log-output flag value

### ISSUE THREAD

**Issue by ericchiang** [coreos/etcd#7252]
# Bug reporting

Noticed this when trying to use rkt to run etcd. Since rkt's default stage 1 sets up a systemd environment, etcd logs to journald. If I run it correctly using `--log-output` I get output, but if I provide invalid configuration, no output:

```
$ sudo rkt run coreos.com/etcd:v3.1.0 -- --listen-client-urls=http://0.0.0.0:2379 --log-output=stderr
stage1: warning: no volume specified for mount point "data-dir", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.
stage1: warning: no volume specified for mount point "data-dir", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.
$ echo $?
1
```

If I run this outside of rkt, I get this

```
$ etcd --listen-client-urls=http://0.0.0.0:2379 --log-output=stderr
2017-01-30 11:14:58.670515 E | etcdmain: error verifying flags, --advertise-client-urls is required when --listen-client-urls is set explicitly. See 'etcd --help'.
2017-01-30 11:14:58.670557 E | etcdmain: When listening on specific address(es), this etcd process must advertise accessible url(s) to each connected client.
```

It looks like etcd doesn't try to setup logging if a configuration is invalid[0]. On rkt this means invalid command line flags get sent to journald even though I specified "stderr".

cc @heyitsanthony 

[0] https://github.com/coreos/etcd/blob/v3.1.0/etcdmain/etcd.go#L66-L75

**Comment by xiang90** [comment]
@ericchiang I am not sure about this. I wont expect --log-output to be respected if a flag is invalid. If users pass in invalid args like `garbage garbage --log-output=stderr garbage`, we need special care about parsing --log-output. I do not think it worth the effort.

We can always log command line parsing error to stderr though, no matter what is specified in --log-output.

What do you think? @heyitsanthony

**Comment by heyitsanthony** [comment]
@xiang90 it's probably worth figuring out why rkt goes mute at some point; so long as the wrong arguments go in, it's silent

**Comment by gyuho** [comment]
@ericchiang What's your `rkt` version?

```
/rkt version
rkt Version: 1.23.0
appc Version: 0.8.9
Go Version: go1.7.3
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

For me, stderr outputs the expected errors?

```
sudo /rkt \
      run \
      --stage1-name coreos.com/rkt/stage1-fly:1.23.0 \
      --volume etcd-data-dir,kind=host,source=/var/lib/etcd \
      --mount volume=etcd-data-dir,target=/var/lib/etcd \
      quay.io/coreos/etcd:v3.1.0 -- \
      --listen-client-urls=http://0.0.0.0:2379 \
      --log-output=stderr
```

```
2017-01-31 19:20:32.053641 E | etcdmain: error verifying flags, --advertise-client-urls is required when --listen-client-urls is set explicitly. See 'etcd --help'.
2017-01-31 19:20:32.053673 E | etcdmain: When listening on specific address(es), this etcd process must advertise accessible url(s) to each connected client.
```

**Comment by ericchiang** [comment]
Old version. I guess rkt started defaulting to either disabling journald or printing the journald output?

```
$ rkt version
rkt Version: 1.19.0
appc Version: 0.8.8
Go Version: go1.7.3
Go OS/Arch: linux/amd64
Features: -TPM +SDJOURNAL
```

Closing since the rkt issue seems to have been fixed. However we still see a lot of funny-ness with etcd's journald integrations (e.g. https://github.com/coreos/bugs/issues/373). I know that's been discussed to death however, so I'll not rehash that issue here.
