### ISSUE TITLE
About Leader Change Signal/Hook

### ISSUE THREAD

**Issue by ghostplant** [coreos/etcd#7264]
When router is out of service, or part of etcd node is down, leader node often change among machines. `When leader machine is changed, is it possible to touch an event from new machine who just became leader?`

This notification signal is efficient and really needed in many backend system maintaining.

Currently, an alternative choice is to let every machine to run a check that looply posts a client query to check whether self-node is leader. The weakness of this approach is that it not only takes too much latency to catch leader change signal ( sleep 1s every time ??), but it also brings plenty of client query (checking leader) from every machines which is not good to reduce etcd working load.

**Comment by gyuho** [comment]
You can try watch API, to get notification whenever the data is ready, if I understand your use case correctly.

> touch an event from new machine

What do you mean by this?

**Comment by ghostplant** [comment]
Does `watch API` must use a another daemon as a client to request? I prefer the etcd daemon itself to notify a event when it is newly updated as a leader.

For example,

`node1(peer)  node2(peer)  node3(peer)`
`node1(peer)  node2(leader)  node3(peer)`  -> etcd daemon at node2 constructs an event to its host (e.g. "touch /tmp/leader-change-event", thus users can use 'inotifyd' to catch this signal efficiently and then special scripts can be executed: node2 call a DNS server to map a domain to node2 itself)
`node1(peer)  node2(crash)  node3(peer)`
`node1(peer)  node2(crash)  node3(leader)` -> ... node3 call a DNS server to map a domain to node3 itself)

An ugly implementation is to use another node as a client to looply request http://127.0.0.1:2379/v2/stats/leader and check whether the value is changed. If changed, this client node will call the DNS server to map a domain to the new leader).

**Comment by heyitsanthony** [comment]
@ghostplant the watch api is for monitoring updates to keys, not the status of the etcd cluster.

Maybe have whatever would listen for an inotify instead monitor the etcd server logs for cluster election messages? This DNS scheme (inotify or not) seems like it could race since there's no way to control for consistency, though. Consider:
1. node1 elected; begin updating DNS with node1
2. node1 is partitioned, connection to cluster lost
3. node2 elected; updates DNS with node2
4. node1 finishes updating DNS with node1, then crashes
5. dns has node1 as leader, but cluster has node2 as leader

**Comment by ghostplant** [comment]
@heyitsanthony 
Thanks. Maybe my previous example is not a good one.
We can consider letting the leader to listen on a constant IP (instead of requesting to update DNS):


1) node1 elected; -> node1 added a constant IP address
2) node1 is partitioned, connection to cluster lost -> node1 drop this constant IP address
3) node2 elected; -> node2 added a constant IP address
4) node1 finishes updating DNS with node1, then crashes -> (node1 should not be a leader again since step-3 is performed, but whatever, we assume node1 becames a leader, thus node2 must be not a leader, this result in: node1 added a constant IP address + node2 dropped this constant IP address)

This also need leader-changed notification.

**Comment by heyitsanthony** [comment]
OK, is there a reason why the daemon can't listen on the etcd server logs? It's unlikely etcd will support inotify signaling when the leader changes since the notification is already available in the logs...

**Comment by heyitsanthony** [comment]
@ghostplant ping?

**Comment by ghostplant** [comment]
Okay, maybe piping logs to an analyzer can solve it. I'll close this issue.
