### ISSUE TITLE
play.etcd.io: writes fail if node1 is down.

### ISSUE THREAD

**Issue by philips** [coreos/etcd#7271]
play.etcd.io writes file if node1 is down. If any other node is down the  writes succeed. cc @gyuho

**Comment by gyuho** [comment]
@philips 

![screenshot from 2017-02-03 13-22-56](https://cloud.githubusercontent.com/assets/6799218/22608956/e352b920-ea13-11e6-8a60-0e0a0c20ba8a.png)

Works for me? Do you have any error message from it?
You have to choose another endpoint other than node1, if the node1 was killed.

**Comment by philips** [comment]
ahhh, missed the endpoints thing, that is new?

**Comment by gyuho** [comment]
@philips I remember we used to requests to all nodes by default.
Now we send to the selected nodes only. :)
