### ISSUE TITLE
grpcproxy: TestWatchCancelOnServer: expected 0 watchers, got 1

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7272]
via https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/633/console
```
--- FAIL: TestWatchCancelOnServer (1.53s)
	watch_test.go:829: expected 0 watchers, got "1"
```

**Comment by fanminshi** [comment]
i noticed this when i am testing the lease proxy logic too. it is quite reproducible.

**Comment by xiang90** [comment]
@fanminshi can you try to fix this one?
