### ISSUE TITLE
raft: async apply ConfChange is not safe 

### ISSUE THREAD

**Issue by siddontang** [coreos/etcd#7280]
Consider nodes 1, 2, 3, 1 is leader, and 1 adds 4, 2 and 3 commit the log but don't apply it. If 3 begins to start an election, the quorum for 3 is 2, but now the cluster quorum is 3. 

This is caused by the async apply, now we don't wait the apply done before raft advance. I guess doing this is for improving performance, but it has a risk now.

**Comment by xiang90** [comment]
I can believe this is a bug. Previously, we only allow one pending apply, and wait for its finish before proceeding. This gave us some parallelism. Later on, we changed it to be fully async, but forgot about the fact that candidate has to wait for all pending configuration to be actually applied to send out votes to others.

**Comment by siddontang** [comment]
Hi @xiang90

Could you tell me how do you want to solve this problem? In TiKV, we split origin `Advance` to `AdvanceAppend` and `AdvanceApply` to handle appending and applying log separately.

**Comment by xiang90** [comment]
@siddontang I will get this fixed. But I do not have time to work on it for the next couple of weeks. I will ping you when it is fixed though.
