### ISSUE TITLE
MemberAdd api is not consistent with cluster creation

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#7289]
// MemberAdd adds a new member into the cluster.
	MemberAdd(ctx context.Context, peerAddrs []string) (*MemberAddResponse, error)

For members created initially, we have all the information like <name, peerURLs and clientURLs>. For members added subsequently through this API, only the peerURLs are present. While it doesn't affect functionality, the MemberList api shows inconsistent information between members.

**Comment by ravigadde** [comment]
I think it should be:

MemberAdd(ctx context.Context, member *Member) (*MemberAddResponse, error)

**Comment by xiang90** [comment]
name, clientURLs are actually self published by the member itself. So add member does not need these information.

**Comment by xiang90** [comment]
But yea, the API looks not ideal.

**Comment by ravigadde** [comment]
@xiangli Thanks, its only a temporary issue then. Feel free to close the issue.
