### ISSUE TITLE
Get historical version of a key

### ISSUE THREAD

**Issue by cw9** [coreos/etcd#7292]
Hi

What's the best way of getting the value of a key on a certain historical version, assuming the revision for that version is not compacted? 
From the v3 API, I can only find WithRev() option to get the value of a key on a certain store revision, rather than on a certain key version. 

Or is there any good way to get the value for the previous version rather than an arbitrary historical version?

Thanks

**Comment by xiang90** [comment]
@cw9 

Right now, you have to get the key with revision. Then get the previous version with the mod (revision - 1) till you reach a point where (mod revision == create revision).

We thought about adding an option to get the key with a specific version. But we do not have any strong use case for it yet.

**Comment by cw9** [comment]
Got it, I guess I'll just loop back from latest rev using the way you suggested then, thanks!

**Comment by xiang90** [comment]
@cw9 Can you explain your use case a little bit?

**Comment by cw9** [comment]
I mainly have 2 use cases for historical values:
1, config roll back, which is perfectly covered by the revision look back schema
2, to know the value of a key in a certain version range, which won't be called very often, so the the look back is probably also ok for me.

**Comment by xiang90** [comment]
> 1, config roll back, which is perfectly covered by the revision look back schema

If this is your most use case, I believe the current revision -1 approach should work well. This is what we designed this for mostly.

> to know the value of a key in a certain version range, which won't be called very often, so the the look back is probably also ok for me.

OK. Fair enough. If this becomes a common requirement, we might consider to add version fetch. But I guess not for now. This is not super important for you either.

Thanks for the info.

**Comment by adolphlwq** [comment]
Hi @xiang90, thanks for you suggesion. I have some questions.

## Problem of your advice
> Right now, you have to get the key with revision. Then get the previous version with the mod (revision - 1) till you reach a point where (mod revision == create revision).

**Can work well only when the mod rev of key increase one by one**. But mostly the mod rev increase random.

I write some go(go version go1.16.6 linux/amd64) code to demo the problem, I use Makefile and docker to run a etcd container.

Makefile:
```makefile
root_pass=pass

prod:
        docker run -d --name etcd --net host \
        -e ETCD_ROOT_PASSWORD=$(root_pass) bitnami/etcd:3
clean:
        docker stop etcd
        docker rm etcd
```

### go code
```go
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	clientv3 "go.etcd.io/etcd/client/v3"
)

func main() {
	endpoints := []string{"127.0.0.1:2379"}
	cli, err := clientv3.New(clientv3.Config{
		Endpoints: endpoints,
		Username:  "root",
		Password:  "pass",
	})
	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close()

	// put sample data random
        put(cli, "foo", "bar_init")
	put(cli, "name", "etcd_init")
	put(cli, "foo", "bar_1")
	put(cli, "name", "etcd_1")

	getRevisionRange(cli, "foo")
}

func put(cli *clientv3.Client, key, value string) {
	cli.Put(context.Background(), key, value)
	resp, err := cli.Get(context.Background(), key)
	if err != nil {
		log.Fatal(err)
	}

	if len(resp.Kvs) != 0 {
		fmt.Printf("-->put (%s:%s) head rev=%d, create rev=%d, mod rev=%d, version=%d\n",
			string(resp.Kvs[0].Key),
			string(resp.Kvs[0].Value),
			resp.Header.Revision,
			resp.Kvs[0].CreateRevision,
			resp.Kvs[0].ModRevision,
			resp.Kvs[0].Version)
	}
}

func getRevisionRange(cli *clientv3.Client, key string) {
	resp, err := cli.Get(context.TODO(), key)
	if err != nil {
		log.Fatal(err)
	}
	cnt := len(resp.Kvs)
	if cnt == 0 {
		fmt.Println("empty value")
		return
	}

	// version := resp.Kvs[0].Version
	modRev := resp.Kvs[0].ModRevision
	createRev := resp.Kvs[0].CreateRevision

	i := 0
	for rev := modRev; rev >= createRev; rev-- {
		fmt.Printf("%d: ", i)
		i++
		getRev(cli, key, rev)
	}
}

func getRev(cli *clientv3.Client, key string, rev int64) {
	resp, err := cli.Get(context.TODO(), key, clientv3.WithRev(rev))
	if err != nil {
		log.Fatal(err)
	}

	if len(resp.Kvs) != 0 {
		fmt.Printf("-->get (%s:%s), head rev=%d, create rev=%d, mod rev=%d, version=%d\n",
			string(resp.Kvs[0].Key),
			string(resp.Kvs[0].Value),
			resp.Header.Revision,
			resp.Kvs[0].CreateRevision,
			resp.Kvs[0].ModRevision,
			resp.Kvs[0].Version)
	}
}
```

### output
```shell
-->put (foo:bar_init) head rev=2, create rev=2, mod rev=2, version=1
-->put (name:etcd_init) head rev=3, create rev=3, mod rev=3, version=1
-->put (foo:bar_1) head rev=4, create rev=2, mod rev=4, version=2
-->put (name:etcd_1) head rev=5, create rev=3, mod rev=5, version=2

0: -->get (foo:bar_1), head rev=5, create rev=2, mod rev=4, version=2
1: -->get (foo:bar_init), head rev=5, create rev=2, mod rev=2, version=1
2: -->get (foo:bar_init), head rev=5, create rev=2, mod rev=2, version=1
```

The value of key `foo` only has two versions, but the mod rev is 4, create rev is 2, version is 2, we loop 3 times and get duplicated value.

## My use case
the same of @cw9, our team uses etcd as database of config system. We use etcd to store config content, **we will update config content, so we want get content history for review and rollback**

## My solutions
1. use cli.Watch to get all event of key and parse history values from event. This is not a good solution
```go
func watch(cli *clientv3.Client, key string) {
	ctx, cancel := context.WithTimeout(context.Background(), 15000*time.Millisecond)
	defer cancel()
	rch := cli.Watch(ctx, key, clientv3.WithRev(2))
	for wresp := range rch {
		for _, ev := range wresp.Events {
			fmt.Printf("%s %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
		}
	}
	return
}
```
2. use MySQL to store mod rev of key each time we put etcd. We pick this solution.

## Suggested API
**For reference only**
1. get value of key by specific version
```go
cli.Get(ctx, key, clientv3.WithVersion(version)
```
2. get values of key by version range
```go
cli.Get(ctx, key, clientv3.WithMinVersion(minVersion), clientv3.WithMaxVersion(maxVersion))
```
