### ISSUE TITLE
etcdv3 how to send an authdisable request through api

### ISSUE THREAD

**Issue by xjjy1083** [coreos/etcd#7293]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on
[reporting bugs][report_bugs] before you submit your bug report. 

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by xiang90** [comment]
I do not understand this question. Can you please be more specific?

**Comment by xjjy1083** [comment]
etcdv3: Can you please provide more details about how to pass token in header during an authdisable request?

**Comment by xiang90** [comment]
What header? Are you trying to use HTTP API instead of gRPC?

**Comment by xjjy1083** [comment]
Yes, HTTP API.Where should i place token?In header?

**Comment by xiang90** [comment]
@mitake I do not think HTTP gateway works well for v3 auth, right?

**Comment by heyitsanthony** [comment]
@xiang90 people have asked about it in the past, we should probably doc how to use auth with the grpc gateway since it's not obvious at all (fiddling with http headers to populate the metadata?)

**Comment by xiang90** [comment]
@heyitsanthony I am not sure if it can even work... I will give it a try over this week though.

**Comment by mitake** [comment]
@xiang90 @heyitsanthony @xjjy1083 currently proxies cannot work with auth, it is a swagger matter: https://github.com/coreos/etcd/issues/6643#issuecomment-255041315

It seems that some people need the feature. After finishing the jwt support, I would be able to allocate a time for it if no one works on it at the time. But if someone can find a way of configuring metadata in swagger, it will be very helpful.

**Comment by brkyn** [comment]
I just encounter the same problem. 
Is there a workaround? OR we must use gRPC currently?
Thx!

**Comment by mitake** [comment]
@brkyn Could you use `clientv3` package directly for now? It is an only way for using auth in v3 API.

**Comment by xiang90** [comment]
this is a dup with #6643 Let's track the issue there. Closing.
