### ISSUE TITLE
etcd2 (bug?): env variables are not loaded on reboot

### ISSUE THREAD

**Issue by Bekt** [coreos/etcd#7300]
I have etcd2 set up from cloud-config on AWS.

```
#cloud-config
coreos:
  update:
    reboot-strategy: off

  etcd2:
    name: master
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://0.0.0.0:2380
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    initial-cluster: master=http://$private_ipv4:2380
    initial-cluster-token: k8s_etcd
    initial-cluster-state: new
```

When the instance is rebooted, etcd2 does not respect any of the above values. Starts with `localhost:2379` instead of `0.0.0.0:2379` for example. This resulted in a k8s cluster outage for some time.

```
$ journalctl -u etcd2
```

```
-- Reboot --
Feb 09 21:09:30 ip-172-32-1-129.ec2.internal systemd[1]: Starting etcd2...
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: recognized and used environment variable ETCD_NAME=db57595c09c94a13a0bd15c7f0423837
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: etcd Version: 2.3.7
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: Git SHA: fd17c91
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: Go Version: go1.7.3
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: Go OS/Arch: linux/amd64
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: the server is already initialized as member before, starting as etcd member...
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: listening for peers on http://localhost:2380
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: listening for peers on http://localhost:7001
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: listening for client requests on http://localhost:2379
Feb 09 21:09:31 ip-172-32-1-129.ec2.internal etcd2[815]: listening for client requests on http://localhost:4001
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: recovered store from snapshot at index 2270227
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: name = db57595c09c94a13a0bd15c7f0423837
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: data dir = /var/lib/etcd2
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: member dir = /var/lib/etcd2/member
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: heartbeat = 100ms
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: election = 1000ms
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: snapshot count = 10000
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: advertise client URLs = http://localhost:2379,http://localhost:4001
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: restarting member a3c26d075afd717e in cluster a5ca89fce9cddded at commit index 2273197
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: a3c26d075afd717e became follower at term 2
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: newRaft a3c26d075afd717e [peers: [a3c26d075afd717e], term: 2, commit: 2273197, applied: 2270227, lastindex: 2273197, lastterm: 2]
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: added member a3c26d075afd717e [http://172.32.1.129:2380] to cluster a5ca89fce9cddded from store
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: set the cluster version to 2.3 from store
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: starting server... [version: 2.3.7, cluster version: 2.3]
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal systemd[1]: Started etcd2.
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: a3c26d075afd717e is starting a new election at term 2
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: a3c26d075afd717e became candidate at term 3
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: a3c26d075afd717e received vote from a3c26d075afd717e at term 3
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: a3c26d075afd717e became leader at term 3
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: raft.node: a3c26d075afd717e elected leader a3c26d075afd717e at term 3
Feb 09 21:09:32 ip-172-32-1-129.ec2.internal etcd2[815]: published {Name:db57595c09c94a13a0bd15c7f0423837 ClientURLs:[http://localhost:2379 http://localhost:4001]} to cluster a5ca89fce9cddded
```

However, if I simply `systemctl restart etcd2`, everything starts as expected.

```
$ journalctl -u etcd2
```

```
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal systemd[1]: Starting etcd2...
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://172.32.1.129:2379
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd2
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1200
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.32.1.129:2380
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_INITIAL_CLUSTER=master=http://172.32.1.129:2380
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=new
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recognized and used environment variable ETCD_NAME=master
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: etcd Version: 2.3.7
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: Git SHA: fd17c91
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: Go Version: go1.7.3
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: Go OS/Arch: linux/amd64
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: setting maximum number of CPUs to 1, total number of available CPUs is 1
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: the server is already initialized as member before, starting as etcd member...
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: listening for peers on http://0.0.0.0:2380
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: listening for client requests on http://0.0.0.0:2379
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: recovered store from snapshot at index 2320232
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: name = master
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: data dir = /var/lib/etcd2
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: member dir = /var/lib/etcd2/member
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: heartbeat = 100ms
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: election = 1200ms
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: snapshot count = 10000
Feb 10 00:26:10 ip-172-32-1-129.ec2.internal etcd2[2900]: advertise client URLs = http://172.32.1.129:2379
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: restarting member a3c26d075afd717e in cluster a5ca89fce9cddded at commit index 2321659
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: a3c26d075afd717e became follower at term 5
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: newRaft a3c26d075afd717e [peers: [a3c26d075afd717e], term: 5, commit: 2321659, applied: 2320232, lastindex: 2321659, lastterm: 5]
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: added member a3c26d075afd717e [http://172.32.1.129:2380] to cluster a5ca89fce9cddded from store
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: set the cluster version to 2.3 from store
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: starting server... [version: 2.3.7, cluster version: 2.3]
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal systemd[1]: Started etcd2.
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: a3c26d075afd717e is starting a new election at term 5
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: a3c26d075afd717e became candidate at term 6
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: a3c26d075afd717e received vote from a3c26d075afd717e at term 6
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: a3c26d075afd717e became leader at term 6
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: raft.node: a3c26d075afd717e elected leader a3c26d075afd717e at term 6
Feb 10 00:26:11 ip-172-32-1-129.ec2.internal etcd2[2900]: published {Name:master ClientURLs:[http://172.32.1.129:2379]} to cluster a5ca89fce9cddded
```

`$ sudo systemctl cat etcd2`: [Output](http://pastebin.com/raw/QqDMZA77)
`$ sudo systemctl show etcd2`: [Output](http://pastebin.com/raw/tbvmE8iy)

**Comment by Bekt** [comment]
Found similar issues in https://github.com/coreos/bugs/issues/396 and https://github.com/coreos/bugs/issues/947

But it's not solved or documented anywhere. I don't have any dependency on etcd2 in my systemd configs.

**Comment by heyitsanthony** [comment]
@Bekt It seems like whatever is booting etcd is losing the config before passing it as environment variables. Can you confirm that the etcd process is being given the right set of environment variables in the first place?
```sh
$ cat /proc/<ETCD-PID>/environ | tr '\000' '\n' | grep ETCD
```

**Comment by Bekt** [comment]
## On reboot (problematic case)

`$ systemctl status etcd2`: [output](http://pastebin.com/raw/jCUNNkBg)
`$ systemctl show etcd2`: [output](http://pastebin.com/raw/uUJEvm5M)
`$ systemctl cat etcd2`: [output](http://pastebin.com/raw/fitatSLe) (notice how env variables are present here)

```
core@ip-172-32-1-129 ~ $ sudo cat /proc/697/environ | tr '\000' '\n'
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NOTIFY_SOCKET=/run/systemd/notify
HOME=/dev/null
LOGNAME=etcd
USER=etcd
SHELL=/sbin/nologin
JOURNAL_STREAM=8:13694
ETCD_DATA_DIR=/var/lib/etcd2
ETCD_NAME=db57595c09c94a13a0bd15c7f0423837
```

## After `systemctl restart etcd2`

`$ systemctl status etcd2`: [Output](http://pastebin.com/raw/XUS7n76r)
`$ systemctl show etcd2`: [Output](http://pastebin.com/raw/A6zwbwNc)
`$ systemctl cat etcd2`: identical as the first case

```
core@ip-172-32-1-129 ~ $ sudo cat /proc/7008/environ | tr '\000' '\n'
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NOTIFY_SOCKET=/run/systemd/notify
HOME=/dev/null
LOGNAME=etcd
USER=etcd
SHELL=/sbin/nologin
JOURNAL_STREAM=8:113812
ETCD_DATA_DIR=/var/lib/etcd2
ETCD_NAME=master
ETCD_ELECTION_TIMEOUT=1200
ETCD_ADVERTISE_CLIENT_URLS=http://172.32.1.129:2379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.32.1.129:2380
ETCD_INITIAL_CLUSTER=master=http://172.32.1.129:2380
ETCD_INITIAL_CLUSTER_STATE=new
ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
```


I also have this unit in the cloud-config. From reading the two issues above, I still don't fully comprehend the relationship between coreos-cloudinit and systemd.

```
  units:
    - name: etcd2.service
      command: start
```

**Comment by heyitsanthony** [comment]
@bekt For the reboot case the process is not being given the right environment variables. What can etcd even do in that case? I don't think this is an etcd bug.

**Comment by Bekt** [comment]
Do you think it's a lower level CoreOS issue? Either way, it is an unexpected behavior that should be noted somewhere or provide a work-around since it is very common.

There's also a possibility that etcd2 COULD get the right values from `systemctl show etcd2` or `systemctl cat etcd2`. Imo it's a major etcd problem, whether root is from upstream or not.

**Comment by heyitsanthony** [comment]
> Do you think it's a lower level CoreOS issue?

Yes. Please follow the advice on the coreos issues. It is related to the init configuration, not etcd itself.

> There's also a possibility that etcd2 COULD get the right values from systemctl show etcd2 or systemctl cat etcd2. Imo it's a major etcd problem, whether root is from upstream or not.

Do any other daemons work like that?

**Comment by Bekt** [comment]
We can of course blame it on other components, but at the end of the day the issue is happening with etcd2, not other daemons.

The issue was first reported 1.5 years ago, and still hasn't been addressed on that side. I'm sure the adults will make the right decision here; just wanted to note that this has not been the most pleasant user experience.

**Comment by heyitsanthony** [comment]
> We can of course blame it on other components, but at the end of the day the issue is happening with etcd2, not other daemons.

Absolute nonsense. Any other daemon that relies on environment variables like etcd will be equally broken in this situation. Just because you've only observed it happening on etcd, that doesn't mean it's isolated to etcd or an etcd bug.

I'm feeling generous so I'll give you a free lesson on system design. etcd will do exactly what it is told. It will never second-guess the parameters provided by the init system. When system components try to make assumptions to work around misconfigurations, it becomes even more difficult to reason about the system because there is now an additional layer of "cleverness" papering over brokenness instead of being forthright with what it was given. By having etcd directly querying systemd to fetch environment variables, etcd would deftly violate in a single swoop both the principles of low coupling (it introduces a systemd assumption) and high cohesion (etcd isn't an init system).

There are deep usability issues. For example, suppose etcd boots direct from the command line or some shell script, but there is a unit file on the system. Should etcd pull the environment variables in that case? Or should it detect the direct execution case and not use the unit file? Suppose there are several unit files that may launch etcd, which should it choose? What is the idiomatic way to handle all of that? That's why I asked if other daemons work like that-- if it's a reasonable approach, it's likely other daemons have already done it.

Another way to do it: look at the initial boot variables, save them, then use those as the defaults. However, do other systems similar to etcd (key-value stores, databases, etc) work like that? I'm unaware of any that do. Even then, it seems like a lot of effort only to get around having a functioning init system in the first place.

> The issue was first reported 1.5 years ago, and still hasn't been addressed on that side. 

Solutions have already been offered for mitigating this problem; the system services are misconfigured and the upshot is etcd boots with the wrong arguments. Others have hit this problem and gladly fixed their broken configurations. The issue has been addressed at least twice. There could be more documentation around it (which seems to be in the works), but based on experience, I sense it will go unread.

The adult is closing this issue. Thanks for flying etcd.

**Comment by Bekt** [comment]
👍 

@heyitsanthony, I wasn't suggesting that was the correct approach or even remotely right.

The point was that these issues, specifically the relationship between cloudinit, coreos-cloudinit, and systemd, are not obvious and not [documented](https://coreos.com/os/docs/latest/cloud-config.html). My suggestion was to spark CoreOS company internal discussions since the Github issues are just being discarded as "not our bug." Somebody has to take the responsibility.
