### ISSUE TITLE
Async log compaction

### ISSUE THREAD

**Issue by bmizerany** [coreos/etcd#731]
etcd stops the writing-world while compacting its log. This was done on purpose to allow us to focus on harder problems. We plan to fix this problem in 0.5. See also: #732.

**Comment by xiang90** [comment]
this has been solved by https://github.com/coreos/etcd/commit/a4dab7ad7583c81300f5c75471e29321d2779858.

there are still some log compaction/snapshot related issue tracked by https://github.com/coreos/etcd/issues/2370
