### ISSUE TITLE
delayed heartbeat from etcd leader and caused leader election multiple times

### ISSUE THREAD

**Issue by nearbyfly** [coreos/etcd#7312]
Etcd v3 cluster started with 3 etcd nodes. Multiple etcd clients send frequent put requests ( one request per second per application). After run some time, the etcd leader log started to show following warnings. Then sometimes, multiple times leader election can be observed.

Configuration:
The heatbeat interval is 100ms, election time out is 1 sec.
Shared and slow disk.
Network RTT is good.

Preliminary check:
Captured tcpdump and found heartbeat were delayed indeed.
Multiple MsgProp received during heartbeat delay interval.

Question:
Looks like if WAL save is not finished, etcdserver (leader) can not process subsequent tick and send out heartbeat in-time. Is it correct understanding?

2017-02-10 08:02:47.025304 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 288.915798ms)
2017-02-10 08:02:47.025325 W | etcdserver: server is likely overloaded
2017-02-10 08:02:47.025332 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 288.968878ms)
2017-02-10 08:02:47.025335 W | etcdserver: server is likely overloaded
2017-02-10 08:03:06.263519 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 25.816201ms)
2017-02-10 08:03:06.263543 W | etcdserver: server is likely overloaded
2017-02-10 08:03:06.263549 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 25.863235ms)
2017-02-10 08:03:06.263552 W | etcdserver: server is likely overloaded
2017-02-10 08:03:17.036087 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 199.721076ms)
2017-02-10 08:03:17.036105 W | etcdserver: server is likely overloaded
2017-02-10 08:03:17.036111 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 199.757441ms)
2017-02-10 08:03:17.036115 W | etcdserver: server is likely overloaded
2017-02-10 08:03:47.224458 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 388.00984ms)
2017-02-10 08:03:47.224477 W | etcdserver: server is likely overloaded
2017-02-10 08:03:47.224482 W | etcdserver: failed to send out heartbeat on time (exceeded the 100ms timeout for 388.045106ms)
2017-02-10 08:03:47.224486 W | etcdserver: server is likely overloaded

**Comment by gyuho** [comment]
> Shared and slow disk.

Seems like this is the main cause?

See https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-failed-to-send-out-heartbeat-on-time-mean for more detail.

**Comment by nearbyfly** [comment]
Does it mean all  wal_fsync_duration_seconds must be less 10ms? 
The following metric from 3 etcd nodes shows 94.84%, 95.43%, 94.86% wal_fsync_duration_seconds were below 8ms. Is it not good enough?

#curl http://169.254.0.1:4001/metrics | grep wal
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 819
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 1.3400495e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 1.7852494e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 1.8745663e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 1.8788077e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 1.87975e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 1.8808099e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 1.8813756e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 1.8820377e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 1.8823831e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 1.8823904e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 1.882392e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 1.8823939e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 1.8823948e+07
etcd_disk_wal_fsync_duration_seconds_sum 85016.59519294072
etcd_disk_wal_fsync_duration_seconds_count 1.8823948e+07

#curl http://169.254.0.2:4001/metrics | grep wal
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 237
6556etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 1.3272061e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 1.7876306e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 1.8654978e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 1.869508e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 1.8709514e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 1.8715697e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 1.8722823e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 1.87293e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 1.8733e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 1.8733042e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 1.8733043e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 1.8733058e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 1.873307e+07
etcd_disk_wal_fsync_duration_seconds_sum 84714.40017204618
etcd_disk_wal_fsync_duration_seconds_count 1.873307e+07

#curl http://169.254.0.3:4001/metrics | grep wal
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 0
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 223
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 1.3217432e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 1.7705036e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 1.8578478e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 1.8624088e+07
100 29831  100 29831    0     0  4737k      0 --:--:-- --:--:-- --:--:-- 4855k
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 1.8639073e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 1.8644712e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 1.8653223e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 1.8659692e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 1.8663583e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 1.8663643e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 1.8663644e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 1.8663662e+07
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 1.8663665e+07
etcd_disk_wal_fsync_duration_seconds_sum 85299.01216744365
etcd_disk_wal_fsync_duration_seconds_count 1.8663665e+07

#curl http://169.254.0.1:4001/metrics | grep leader_changes_seen_total
etcd_server_leader_changes_seen_total 57

**Comment by xiang90** [comment]
> Does it mean all wal_fsync_duration_seconds must be less 10ms?

Yes.

> The following metric from 3 etcd nodes shows 94.84%, 95.43%, 94.86% wal_fsync_duration_seconds were below 8ms. Is it not good enough?

Usually you need 99% < 10ms, 99.9% < 100ms (99.999% < 1s).

From the metrics, there was serious IO contentions on your machine. Some fsyncs took more than 8 seconds, it is crazy. That will cause either leader election or a 8 seconds pausing. 

We might loose the heartbeat logic (keep sending, receiving heartbeats even if the machine is busy with IO) , however it wont help much. Leader can do nothing until it finishes fsyncing. Your cluster will be unresponsive for quite sometime.

You should fix the IO issue on your machine instead.

**Comment by nearbyfly** [comment]
Thanks a lot! I knew shared and slow disk can cause the issue, but didn't understand how fast disk we need.

Also from etcd code perspective, there is one go routine ((*raftNode)start in etcd/etcdserver/raft.go) to process tick and execute storage.Save, which triggers (*WAL).sync to do fsyncing. Before  (*WAL).sync finished, there is not possible to pick tick to trigger MsgHeartbeat to send out heartbeat from etcd leader. So more delay on fsyncing, more possibility of delayed heartbeat, and more frequent leader election.

I thought to process tick in another go routine can relieve the delayed heartbeat issue. But I agree with you that "leader can do nothing until it finishes fsyncing".  So resolve the IO issue is the 1st step.

**Comment by xiang90** [comment]
> I thought to process tick in another go routine can relieve the delayed heartbeat issue.

Then you will have a pausing leader and pausing cluster, which is possibly even worse than just giving up leadership to let other node to move forward the cluster :P

**Comment by xiang90** [comment]
I am closing this issue. Let us know if you have any further questions.
