### ISSUE TITLE
WithLimit(0) returns responses

### ISSUE THREAD

**Issue by necro351** [coreos/etcd#7316]
When running a query with WithLimit(0) on clientv3 I am retrieving at least one result. I expect to get an error or to retrieve zero results. This is the query:

```
   resp, err := kvc.Txn(ctx).                                                                         
      If(                                                                                             
         clientv3.Compare(clientv3.Version(root.cli.sharedLease(share)), ">", 0)).               
      Then(                                                                                           
         clientv3.OpGet(key,                                                                   
            clientv3.WithFromKey(),                                                                   
            clientv3.WithLimit(int64(len(ents))))).                                                
      Else().                                                                                         
      Commit()                                                                                        
   if err != nil {                                                                                    
      return 0, fmt.Errorf("cannot get share '%s': %v", share, err)                          
   } else if !resp.Succeeded {                                                                        
      return 0, fmt.Errorf("cannot perform ops on share '%s' unprotected!", share)               
   } 
```

This is how I iterate through the response, viewing one response in the for-loop, where I expect the for-loop to be skipped:
```
   resprange := resp.Responses[0].GetResponseRange()                                                  
   total := 0                                                                                         
   for i, kv := range resprange.Kvs {
      ...
```

Other values for WithLimit() work fine, like 1 or 2: in these cases I get a range response limited to 1 or 2 entries respectively. For now I work around by explicitly checking if the query will result in WithLimit(0) and return early, but this seems like a bug with clientv3?

I'm using 9b72c8ba1ba484802e155c9f6f0ddc21e9c256ce of clientv3, embed, etcdserver, and all the other dependencies of etcd. I'm vending and building etcd within my project.

Thoughts?

**Comment by heyitsanthony** [comment]
@necro351 this is a doc bug. A limit of 0 is treated as no limit since protobuf3 treats unset ints (e.g., no limit given) as 0. If you want a `Get` with no keys, try `WithCountOnly`.

**Comment by necro351** [comment]
Thanks for the explanation.
