### ISSUE TITLE
etcd v3 keepalive is frequent when lease ttl is small

### ISSUE THREAD

**Issue by nearbyfly** [coreos/etcd#7323]
I thought lease interval is 1/3*TTL(s) + 1s. But from etcd/clientv3/lease.go nextKeepAlive := time.Now().Add(1 + time.Duration(karesp.TTL/3)*time.Second). So it's 1/3*TTL(s) + 1us. 

So when lease interval is small, the keepalive is frequent than expectation. To me looks like plus 1us is too short. What's the guideline to set keepalive interval? Do we plan to at lease have two keepalive for given TTL?

**Comment by xiang90** [comment]
@nearbyfly I believe this a mistake. Can you help to fix it? it should bd 1 * time.Second.

**Comment by nearbyfly** [comment]
@xiang90 I tried to plus 1sec in private build. It worked well. There are some related company policies to be figured out firstly at my side.

**Comment by xiang90** [comment]
@nearbyfly I can fix this if you wish. I thought you already know the line to fix, so you might want to contribute. This is not something super urger either. We can wait. But, it is up to you. Just let us know.

**Comment by xiang90** [comment]
@nearbyfly I fixed it. Thanks for reporting!

**Comment by nearbyfly** [comment]
@xiang90 Sorry for the delay. I just got green lights.
