### ISSUE TITLE
high load and cpu usage on AWS

### ISSUE THREAD

**Issue by bambash** [coreos/etcd#7324]
Hi all,

I'm encountering an issue running etcd-3.0.17-1.fc25.x86_64 in a three node cluster (t2.medium) on  Fedora (fc25). I'm using etcd as a backend for flannel and kubernetes. I'm able to build and run everything. However, etcd is causing high load and the VIRT memory footprint is huge.

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                    
14163 etcd      20   0 10.427g 171040  12716 S  72.8  4.2 832:05.06 etcd      

load average: 3.66, 3.22, 3.35

The above metrics are after running etcd with no other processes accessing the cluster. Flannel and Kubernetes are both stopped. 

I can provide other details if needed. Thanks!

**Comment by xiang90** [comment]
> However, etcd is causing high load and the VIRT memory footprint is huge.

VIRT memory is per allocated. So it is expected to be as high as 10GB.

If you install a new etcd deployment, can you also observe the high CPU load? It is not obvious to me that even without k8s load on etcd, the CPU load is still high.

**Comment by xiang90** [comment]
Kindly ping.

**Comment by xiang90** [comment]
I am closing this due to lack of information. Reopen if you have the information we need.

**Comment by bambash** [comment]
My apologies - I was just able to get back to this today. I just provisioned 3 new instances and I'm seeing the same behavior.

load average: 2.45, 1.34, 0.58
12575 etcd      20   0 10.287g 152584  12884 S 188.7  3.8   7:13.72 etcd                       

the cluster is returning healthy:

    member 49575d8067ba3bec is healthy: got healthy result from https://<ip>:2379
    member 805eab3b6076c227 is healthy: got healthy result from https://<ip>:2379
    member 992257d14b6dbe79 is healthy: got healthy result from https://<ip>:2379
    cluster is healthy


here is my configuration:
# [member]
ETCD_NAME=etcd-01
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_HEARTBEAT_INTERVAL="300"
ETCD_ELECTION_TIMEOUT="15000"
ETCD_LISTEN_PEER_URLS="https://<ip>:2380"
ETCD_LISTEN_CLIENT_URLS="https://<ip>:2379,http://127.0.0.1:2379"
ETCD_ADVERTISE_CLIENT_URLS="https://<ip>:2379"
#[cluster]
ETCD_INITIAL_CLUSTER="etcd-01=https://<ip>:2380,etcd-02=https://<ip>:2380,etcd-03=https://<ip>:2380"
ETCD_INITIAL_CLUSTER_STATE="new"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-0"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://<ip addr>:2380"
#[security]
ETCD_CERT_FILE="/path/to/cert.pem"
ETCD_KEY_FILE="/path/to/key.pem"
ETCD_TRUSTED_CA_FILE="/path/to/ca.pem"
ETCD_PEER_CERT_FILE="/path/to/cert.pem"
ETCD_PEER_KEY_FILE="/path/to/key.pem"
ETCD_PEER_TRUSTED_CA_FILE="/path/to/ca.pem"

**Comment by xiang90** [comment]
@bambash How long have you been running this cluster? How did you setup the cluster? Can you give me the full top info?

**Comment by bambash** [comment]
The fresh cluster has been running for 30 minutes. I setup the cluster using the packages provided by the Fedora repository. 

etcd-3.0.17-1.fc25.x86_64

top output:

top - 20:21:28 up 40 min,  1 user,  load average: 2.60, 2.44, 1.72
Tasks:  86 total,   1 running,  85 sleeping,   0 stopped,   0 zombie
%Cpu(s): 93.4 us,  2.7 sy,  0.0 ni,  2.4 id,  0.0 wa,  0.7 hi,  0.8 si,  0.0 st
KiB Mem :  4045148 total,  2711720 free,   248004 used,  1085424 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3512952 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                    
12575 etcd      20   0 10.287g 153016  12884 S 190.0  3.8  32:17.65 etcd                       
  333 root      20   0  225720 108532 107996 S   1.3  2.7   0:26.42 systemd-journal            
    7 root      20   0       0      0      0 S   0.3  0.0   0:02.07 rcu_sched                  
    1 root      20   0  149100  10388   7652 S   0.0  0.3   0:01.17 systemd                    
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd                   
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/0                
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H               
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh                     
    9 root      20   0       0      0      0 S   0.0  0.0   0:02.09 rcuos/0                    
   10 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/0                    
   11 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/0                
   12 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 lru-add-drain              
   13 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 watchdog/0                 
   14 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/0                    
   15 root      20   0       0      0      0 S   0.0  0.0   0:00.00 cpuhp/1                    
   16 root      rt   0       0      0      0 S   0.0  0.0   0:00.00 watchdog/1                 
   17 root      rt   0       0      0      0 S   0.0  0.0   0:00.11 migration/1                
   18 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/1                
   20 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:0H               
   21 root      20   0       0      0      0 S   0.0  0.0   0:00.80 rcuos/1                    
   22 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcuob/1                    
   23 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kdevtmpfs                  
   24 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 netns                      
   25 root      20   0       0      0      0 S   0.0  0.0   0:00.00 xenwatch                   
   26 root      20   0       0      0      0 S   0.0  0.0   0:00.00 xenbus                     
   28 root      20   0       0      0      0 S   0.0  0.0   0:00.00 oom_reaper                 
   29 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 writeback                  
   30 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kcompactd0                 
   31 root      25   5       0      0      0 S   0.0  0.0   0:00.00 ksmd                       
   32 root      39  19       0      0      0 S   0.0  0.0   0:00.00 khugepaged                 
   33 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 crypto                     
   34 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kintegrityd                
   35 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 bioset                     
   36 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kblockd                    
   38 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 ata_sff                    
   39 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 md                         
   40 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 devfreq_wq                 
   41 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 watchdogd                  
   43 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kswapd0                    
   44 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 vmstat                     
   59 root      20   0       0      0      0 S   0.0  0.0   0:00.19 kworker/u30:1              
   90 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kthrotld

**Comment by xiang90** [comment]
We will try to reproduce this on a t2.m instances on aws.

**Comment by bambash** [comment]
@xiang90 I'm using the GP2 HVM AMI provided by Fedora:
https://alt.fedoraproject.org/cloud/

**Comment by fanminshi** [comment]
taking a look

**Comment by bambash** [comment]
I believe the increased cpu and load is due to the tls and security configurations. I provisioned a new cluster, the only difference being security. Here is the top output:

top - 21:00:01 up 6 min,  1 user,  load average: 0.10, 0.36, 0.21
Tasks:  91 total,   1 running,  90 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.2 hi,  0.0 si,  0.0 st
KiB Mem :  4045148 total,  2961292 free,   113836 used,   970020 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3651736 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                    
12368 etcd      20   0 10.163g  18392  12620 S   0.7  0.5   0:00.53 etcd                       
    1 root      20   0   67148  10316   7576 S   0.0  0.3   0:01.19 systemd                    
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd                   
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/0                
    4 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0                
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H               
    6 root      20   0       0      0      0 S   0.0  0.0   0:00.12 kworker/u30:0              
    7 root      20   0       0      0      0 S   0.0  0.0   0:00.13 rcu_sched

**Comment by xiang90** [comment]
> The fresh cluster has been running for 30 minutes.

There is no external load? And the cluster consumes 190% CPU constantly with TLS enabled?

**Comment by bambash** [comment]
Correct, no external load. After rebuilding the cluster without TLS, the load is minimal.

**Comment by xiang90** [comment]
@bambash Can you try with m4.m instead of t2? Probably t2 runs out of its CPU credit with TLS enabled.

**Comment by bambash** [comment]
I rebuilt the cluster using m3.medium and usage isn't quite as high...

top - 21:53:53 up 17 min,  1 user,  load average: 1.27, 0.71, 0.43
Tasks:  77 total,   2 running,  75 sleeping,   0 stopped,   0 zombie
%Cpu(s): 28.2 us,  1.6 sy,  0.0 ni,  0.0 id,  0.0 wa, 34.0 hi,  0.5 si, 35.7 st
KiB Mem :  3853116 total,  2657668 free,   202160 used,   993288 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3436436 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                     
12757 etcd      20   0 10.299g 122956  27580 S 49.0  3.2   1:02.52 etcd                        
  316 root      20   0   94484  21000  20468 S  1.7  0.5   0:02.39 systemd-journal             
    1 root      20   0   67140  10384   7660 S  0.0  0.3   0:01.23 systemd                     
    2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd                    
    3 root      20   0       0      0      0 S  0.0  0.0   0:00.00 ksoftirqd/0                 
    5 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H                
    7 root      20   0       0      0      0 R  0.0  0.0   0:00.25 rcu_sched                   
    8 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcu_bh                      
    9 root      20   0       0      0      0 S  0.0  0.0   0:00.21 rcuos/0                     
   10 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuob/0


I'm sure that rebuilding the cluster with m4.large would solve the load problem. I understand that TLS adds to the CPU workload during the encrypt/decrypt handshake process. Throwing more resources at the problem will work, but I feel like this is a little overkill.

**Comment by fanminshi** [comment]
My setup

```
etcd --name my-etcd-1 \
--data-dir /var/lib/etcd \
--listen-client-urls "https:PrivateIP:2379,http://127.0.0.1:2379" \
--advertise-client-urls https:PrivateIP:2379 \
--listen-peer-urls https:PrivateIP:2380 \
--initial-advertise-peer-urls https:PrivateIP:2380 \
--initial-cluster my-etcd-1=https:PrivateIP:2380,my-etcd-2=https:PrivateIP:2380,my-etcd-3=https:PrivateIP:2380 \
--initial-cluster-token "etcd-cluster-0" \
--initial-cluster-state new \
--trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--cert-file /etc/ssl/certs/my-etcd-1.pem \
--key-file /etc/ssl/certs/my-etcd-1-key.pem \
--peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--peer-cert-file /etc/ssl/certs/my-etcd-1.pem \
--peer-key-file /etc/ssl/certs/my-etcd-1-key.pem \
--auto-compaction-retention 1 \
--heartbeat-interval 300 \
--election-timeout 15000 

etcd --name my-etcd-2 \
--data-dir /var/lib/etcd \
--listen-client-urls "https:PrivateIP:2379,http://127.0.0.1:2379" \
--advertise-client-urls https:PrivateIP:2379 \
--listen-peer-urls https:PrivateIP:2380 \
--initial-advertise-peer-urls https:PrivateIP:2380 \
--initial-cluster my-etcd-1=https:PrivateIP:2380,my-etcd-2=https:PrivateIP:2380,my-etcd-3=https:PrivateIP:2380 \
--initial-cluster-token "etcd-cluster-0" \
--initial-cluster-state new \
--trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--cert-file /etc/ssl/certs/my-etcd-2.pem \
--key-file /etc/ssl/certs/my-etcd-2-key.pem \
--peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--peer-cert-file /etc/ssl/certs/my-etcd-2.pem \
--peer-key-file /etc/ssl/certs/my-etcd-2-key.pem \
--auto-compaction-retention 1
--heartbeat-interval 300 \
--election-timeout 15000 

etcd --name my-etcd-3 \
--data-dir /var/lib/etcd \
--listen-client-urls "https:PrivateIP:2379,http://127.0.0.1:2379" \
--advertise-client-urls https:PrivateIP:2379 \
--listen-peer-urls https:PrivateIP:2380 \
--initial-advertise-peer-urls https:PrivateIP:2380 \
--initial-cluster my-etcd-1=https:PrivateIP:2380,my-etcd-2=https:PrivateIP:2380,my-etcd-3=https:PrivateIP:2380 \
--initial-cluster-token "etcd-cluster-0"  \
--initial-cluster-state new \
--trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--cert-file /etc/ssl/certs/my-etcd-3.pem \
--key-file /etc/ssl/certs/my-etcd-3-key.pem \
--peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--peer-cert-file /etc/ssl/certs/my-etcd-3.pem \
--peer-key-file /etc/ssl/certs/my-etcd-3-key.pem \
--auto-compaction-retention 1
--heartbeat-interval 300 \
--election-timeout 15000 
```

```
$ top
top - 22:49:16 up  1:41,  2 users,  load average: 2.33, 1.97, 1.22
Tasks:  84 total,   2 running,  82 sleeping,   0 stopped,   0 zombie
%Cpu(s): 96.0 us,  1.3 sy,  0.0 ni,  1.3 id,  0.2 wa,  0.7 hi,  0.5 si,  0.0 st
KiB Mem :  4045148 total,  3499628 free,   170088 used,   375432 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3632252 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1479 fedora    20   0 10.197g 145272  29284 S 194.3  3.6  17:09.77 etcd
 1200 fedora    20   0  148820   4696   3416 S   0.7  0.1   0:02.17 sshd
    9 root      20   0       0      0      0 R   0.3  0.0   0:00.61 rcuos/0
    1 root      20   0  149108  10368   7636 S   0.0  0.3   0:00.84 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
    3 root      20   0       0      0      0 S   0.0  0.0   0:00.00 ksoftirqd/0
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:0H
```

```
etcdctl --endpoints=https://PrivateIP:2379 cluster-health
member 8c829c7acf94a3da is healthy: got healthy result from https://172.31.26.158:2379
member dae41bbf1553f847 is healthy: got healthy result from https://172.31.19.207:2379
member e4ab2dc3aa460726 is healthy: got healthy result from https://172.31.26.13:2379
cluster is healthy
```

However

I am observing a lot of transport errors on the console output.

```
...
2017-02-23 22:52:03.918512 I | v3rpc/grpc: transport: http2Client.notifyError got notified that the client transport was broken unexpected EOF.
...
```

@bambash did you see those errors too?

**Comment by bambash** [comment]
@fanminshi I'm also seeing those transport errors on every node. They're coming in every second.

Another interesting thing I'm seeing is that the CPU and load average on c4.large is about the same as t2.medium...

**Comment by fanminshi** [comment]
@bambash I think that the grpc is experiencing some kinda of error underneath and probably doing some looping on connection retry(that's my guess). The looping might be the reason why the cpu usage is high. I'll investigate it deeper.

**Comment by fanminshi** [comment]
@bambash I tried the setup with [etcd-3.1.2](https://github.com/coreos/etcd/releases/tag/v3.1.2). I do not see the high load issue anymore. Could you try 3.1.2 to see that fix high load issue on your side as well?

```
# Install etcd

ETCD_VER=v3.1.2

GOOGLE_URL=https://storage.googleapis.com/etcd
GITHUB_URL=https://github.com/coreos/etcd/releases/download

DOWNLOAD_URL=${GOOGLE_URL}

rm -f /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
rm -rf /tmp/test-etcd-${ETCD_VER} && mkdir -p /tmp/test-etcd-${ETCD_VER}

curl -L ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/test-etcd-${ETCD_VER} --strip-components=1

# sudo cp /tmp/test-etcd-${ETCD_VER}/etcd* /usr/local/bin
sudo cp /tmp/test-etcd-${ETCD_VER}/etcd* /

/etcd --version
/etcdctl --version
```

```
/etcd --name my-etcd-1 \
--data-dir /var/lib/etcd \
--listen-client-urls "https://172.31.18.6:2379,https://127.0.0.1:2379" \
--advertise-client-urls https://172.31.18.6:2379 \
--listen-peer-urls https://172.31.18.6:2380 \
--initial-advertise-peer-urls https://172.31.18.6:2380 \
--initial-cluster my-etcd-1=https://172.31.18.6:2380,my-etcd-2=https://172.31.22.92:2380,my-etcd-3=https://172.31.29.112:2380 \
--initial-cluster-token my-etcd-token \
--initial-cluster-state new \
--trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--cert-file /etc/ssl/certs/my-etcd-1.pem \
--key-file /etc/ssl/certs/my-etcd-1-key.pem \
--peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--peer-cert-file /etc/ssl/certs/my-etcd-1.pem \
--peer-key-file /etc/ssl/certs/my-etcd-1-key.pem \
--auto-compaction-retention 1 \
--heartbeat-interval 300 \
--election-timeout 15000 

/etcd --name my-etcd-2 \
--data-dir /var/lib/etcd \
--listen-client-urls "https://172.31.22.92:2379,https://127.0.0.1:2379" \
--advertise-client-urls https://172.31.22.92:2379 \
--listen-peer-urls https://172.31.22.92:2380 \
--initial-advertise-peer-urls https://172.31.22.92:2380 \
--initial-cluster my-etcd-1=https://172.31.18.6:2380,my-etcd-2=https://172.31.22.92:2380,my-etcd-3=https://172.31.29.112:2380 \
--initial-cluster-token my-etcd-token \
--initial-cluster-state new \
--trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--cert-file /etc/ssl/certs/my-etcd-2.pem \
--key-file /etc/ssl/certs/my-etcd-2-key.pem \
--peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--peer-cert-file /etc/ssl/certs/my-etcd-2.pem \
--peer-key-file /etc/ssl/certs/my-etcd-2-key.pem \
--auto-compaction-retention 1 \
--heartbeat-interval 300 \
--election-timeout 15000 

/etcd --name my-etcd-3 \
--data-dir /var/lib/etcd \
--listen-client-urls "https://172.31.29.112:2379,https://127.0.0.1:2379" \
--advertise-client-urls https://172.31.29.112:2379 \
--listen-peer-urls https://172.31.29.112:2380 \
--initial-advertise-peer-urls https://172.31.29.112:2380 \
--initial-cluster my-etcd-1=https://172.31.18.6:2380,my-etcd-2=https://172.31.22.92:2380,my-etcd-3=https://172.31.29.112:2380 \
--initial-cluster-token my-etcd-token \
--initial-cluster-state new \
--trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--cert-file /etc/ssl/certs/my-etcd-3.pem \
--key-file /etc/ssl/certs/my-etcd-3-key.pem \
--peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
--peer-cert-file /etc/ssl/certs/my-etcd-3.pem \
--peer-key-file /etc/ssl/certs/my-etcd-3-key.pem \
--auto-compaction-retention 1 \
--heartbeat-interval 300 \
--election-timeout 15000 
```

```
$ ETCDCTL_API=3 /etcdctl --endpoints 172.31.18.6:2379,172.31.22.92:2379,172.31.29.112:2379 --cacert /etc/ssl/certs/etcd-root-ca.pem --cert /etc/ssl/certs/my-etcd-1.pem --key /etc/ssl/certs/my-etcd-1-key.pem endpoint health
2017-02-24 19:16:55.202212 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-02-24 19:16:55.203406 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-02-24 19:16:55.204571 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
172.31.18.6:2379 is healthy: successfully committed proposal: took = 2.011749ms
172.31.22.92:2379 is healthy: successfully committed proposal: took = 1.248089ms
172.31.29.112:2379 is healthy: successfully committed proposal: took = 1.706253ms
```
```
]$ ETCDCTL_API=3 /etcdctl --endpoints 172.31.18.6:2379,172.31.22.92:2379,172.31.29.112:2379 --cacert /etc/ssl/certs/etcd-root-ca.pem --cert /etc/ssl/certs/my-etcd-1.pem --key /etc/ssl/certs/my-etcd-1-key.pem lease grant 100
2017-02-24 19:18:21.968221 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
lease 6ab65a717b1d0108 granted with TTL(100s)
```

```
top - 19:13:44 up 59 min,  2 users,  load average: 0.00, 0.00, 0.00
Tasks:  84 total,   2 running,  82 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
KiB Mem :  4045148 total,  3565700 free,    62976 used,   416472 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  3738380 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 1093 fedora    20   0 10.044g  38436  28532 S   0.3  1.0   0:04.46 etcd
 1103 fedora    20   0  148820   4632   3368 S   0.3  0.1   0:00.05 sshd
    1 root      20   0  148976  10156   7536 S   0.0  0.3   0:00.76 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.00 kthreadd
```

**Comment by bambash** [comment]
@fanminshi thanks for the help, i'm running on the latest release rather than 3.0.17. load is great now - 
top - 20:22:38 up  1:31,  1 user,  load average: 0.18, 0.55, 1.64

**Comment by fanminshi** [comment]
@bambash not a problem. Free free to reach out if you have any more questions.
