### ISSUE TITLE
Corrupted data after using rollback tool

### ISSUE THREAD

**Issue by fgrzadkowski** [coreos/etcd#7325]
I'm performing the following operations:

1. Start etcd (as storage for kubernetes) in version 3.0.14
2. Write data in v3 via kube apiserver
3. Kill etcd and rollback data to v2
4. Start etcd in version 2.3.7 and check that it works; kill etcd
5. Start etcd in version 3.0.14 with random port (to avoid any writes) with data in v2 and make sure it works and kill it (in this particular workflow this step is optional but it's needed in some other scenarios)
6. Migrate data to v3
7. start etcd 3.0.14, create a lease and attach all keys to it, kill etcd
7. Start etcd in version 3.0.14 and use v3 data

Unfortunately for some reasons sometimes steps 7&8 (and 6 IIRC) are failing with the following error:

```
2017-02-14 13:34:53.369897 C | etcdserver: read wal error (walpb: crc mismatch) and cannot be repaired
```

I'm attaching wal file that it keeps failing on.

[0000000000000000-0000000000000000.wal.gz](https://github.com/coreos/etcd/files/774594/0000000000000000-0000000000000000.wal.gz)

**Comment by fgrzadkowski** [comment]
@mml @wojtek-t

**Comment by mml** [comment]
@hongchaodeng @xiang90

**Comment by hongchaodeng** [comment]
> I'm attaching wal file that it keeps failing on.

On what step it's failing on?

Can you write down scripts to reproduce it?

**Comment by fgrzadkowski** [comment]
It failed after step 6 (migration) - either in step 7 (when attaching leases) or during step 8 (running regular step etcd).

I can try to write the script to reproduce it, but it will take some time. In the meantime - is there something obviously wrong with that wal file? Do you have some suggestions what have caused this kind of problem?

**Comment by fgrzadkowski** [comment]
I mean "either" as "sometimes" - sometimes it worked ok, sometimes it failed in step 7 and sometimes in step 8.

**Comment by heyitsanthony** [comment]
Here's a partial dump after disabling index/crc checking:
```
Term          Index     Type    Data
   1          7110      norm    method=SYNC time="2017-02-14 05:34:48.725155239 -0800 PST"
   1          7111      norm    method=SYNC time="2017-02-14 05:34:49.225151681 -0800 PST"
   1          7112      norm    method=SYNC time="2017-02-14 05:34:49.725104714 -0800 PST"
   1          7113      norm    method=SYNC time="2017-02-14 05:34:50.22513068 -0800 PST"
   1          7114      norm    method=SYNC time="2017-02-14 05:34:50.72546139 -0800 PST"
   2          7115      norm    
   2          7116      norm    method=PUT path="/0/members/2f7fbfd36802ff7a/attributes" val="{\"name\":\"etcd-kubernetes-master\",\"clientURLs\":[\"http://127.0.0.1:18629\"]}"
   2          7117      norm    method=PUT path="/0/version" val="3.0.0"
   2          7118      norm    method=SYNC time="2017-02-14 05:34:52.620871333 -0800 PST"
   2          7119      norm    method=SYNC time="2017-02-14 05:34:52.819713978 -0800 PST"
   2          7120      norm    method=PUT path="/1/etcd_version" val="3.0.14"
   1          7119      norm    method=SYNC time="2017-02-14 05:34:53.225088899 -0800 PST"
   1          7120      norm    method=SYNC time="2017-02-14 05:34:53.72511293 -0800 PST"
   1          7121      norm    method=SYNC time="2017-02-14 05:34:54.225131258 -0800 PST"
   1          7122      norm    method=SYNC time="2017-02-14 05:34:54.725123344 -0800 PST"
   1          7123      norm    method=SYNC time="2017-02-14 05:34:55.225121424 -0800 PST"
   1          7124      norm    method=SYNC time="2017-02-14 05:34:55.725109752 -0800 PST"
   1          7125      norm    method=SYNC time="2017-02-14 05:34:56.225128288 -0800 PST"
   1          7126      norm    method=SYNC time="2017-02-14 05:34:56.725120619 -0800 PST"
   1          7127      norm    method=SYNC time="2017-02-14 05:34:57.225111875 -0800 PST"
   1          7128      norm    method=SYNC time="2017-02-14 05:34:57.725122571 -0800 PST"
   1          7129      norm    method=SYNC time="2017-02-14 05:34:58.22512064 -0800 PST"
   1          7130      norm    method=SYNC time="2017-02-14 05:34:58.72512467 -0800 PST"
   1          7131      norm    method=SYNC time="2017-02-14 05:34:59.225118715 -0800 PST"
   1          7132      norm    method=SYNC time="2017-02-14 05:34:59.72513744 -0800 PST"
   1          7133      norm    method=SYNC time="2017-02-14 05:35:00.225103196 -0800 PST"
   1          7134      norm    method=SYNC time="2017-02-14 05:35:00.725113836 -0800 PST"
   1          7135      norm    method=SYNC time="2017-02-14 05:35:01.225111481 -0800 PST"
   1          7136      norm    method=SYNC time="2017-02-14 05:35:01.725074728 -0800 PST"
   1          7137      norm    method=SYNC time="2017-02-14 05:35:02.225132678 -0800 PST"
   1          7138      norm    method=SYNC time="2017-02-14 05:35:02.725107969 -0800 PST"
   1          7139      norm    method=SYNC time="2017-02-14 05:35:03.225123287 -0800 PST"
```

The CRC error happens at the 2->1 transition.

**Comment by wojtek-t** [comment]
@heyitsanthony - thanks a lot for looking into it!

Let me clarify one thing - what is this "Term"? Is it the generation of the master? So what is happening here is that:
- we have an elected master up to 7114 index
- the we elect a new master and we have it up to 7120 index
- and then again master changes, but because of some reason it has term one? [I guess this is what the rollback tool is messing with or sth like that]

Do I understand correctly?

**Comment by heyitsanthony** [comment]
@wojtek-t Term is from directly from raft. It represents an election.

Judging by the WAL data (the sizes aren't padded and the corrupt entry doesn't clobber anything, it's directly appended suggesting 2.3.x's O_APPEND), there's a 2.3.x process writing the new entries. Likewise, the file locking logic in 2.3.x is unconvincing to say the least. It's possible 2.3.7 is still running / relaunching using the same wal file during the migration.

**Comment by mml** [comment]
So a possible workaround would be to insert a `wait()` on the 2.3.7 process?  Unfortunately, we are already doing that.  https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/migrate-if-needed.sh#L148

**Comment by mml** [comment]
@heyitsanthony also, can you clarify bwhat you mean by "unconvincing"?  In particular, are the different versions of etcd using locking semantics or algorithms that are incompatible with each other?

**Comment by heyitsanthony** [comment]
@mml the file locking code wasn't very good. I had to tear it out for 3.0 so it's something sane. There's no incompatibility, it's just that 2.3 plays loose and fast with file locks in such a way that mutual exclusion among processes isn't necessarily guaranteed. In particular, https://github.com/coreos/etcd/blob/release-2.3/wal/wal.go#L200 assumes the lock on the read fd is enough for opening a writable file.

The 2.3.7 process either needs to be killed off or the wal data needs to be copied somewhere else so it won't get clobbered by the old process.

**Comment by mml** [comment]
Thanks.  I will try to read the locking code to understand clearly, but are the locks based on filehandles, filenames (path names), inode numbers, or something else?  That is, if I rename a "locked" file, does the lock follow the file or its name?

Is this shortcoming documented somewhere in the upgrade instructions for 3.0?

**Comment by heyitsanthony** [comment]
@mml 

> file locking semantics

2.3.x uses `flock`. 3.0 uses `F_OFD_SETLW` (this buys NFS locking and semantics that better match windows locking) but falls back to `flock` if unavailable. The `flock` and `fcntl` manpages provide a better explanation of the semantics than I could here.

> Is this shortcoming documented somewhere in the upgrade instructions for 3.0?

No. The file locking shouldn't play a part in the standard upgrade process for etcd; it doesn't make sense to give warnings for upgrade processes that go off the rails.

**Comment by fgrzadkowski** [comment]
I was running some more experiments and my current hypothesis is that it's due data we are storing in etcd3. In step 2) I wrote data in binary format (protocol buffers). As etcd2 does not support binary data I think something might have broken during rollbacks. When I changed data format to be regular strings I was not able to reproduce this bug.

Closing this issue. I'll re-open if I see it again.

@wojtek-t @mml

**Comment by heyitsanthony** [comment]
@fgrzadkowski the data clearly shows there's a stray 2.3 process still writing to the wal file. It is not related to binary data; etcd2 supports writing out binary values (but not keys):
```sh
$ etcdctl set /abc `echo -e -n '\x1\x2\x3'`
$ etcdctl get /abc | od -tx1
0000000    01  02  03  0a
```
