### ISSUE TITLE
Contradicting instructions in Runtime Configuration

### ISSUE THREAD

**Issue by zihaoyu** [coreos/etcd#7326]
In the [Runtime Configuration](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md) documentation, I find the instructions contradicting, especially around how to **replace a member**.

- Under [Replace a failed machine](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#replace-a-failed-machine) use case, it reads:
  > To replace the machine, follow the instructions for removing the member from the cluster, and then add a new member in its place. 

- Under [Cluster reconfiguration operations](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#cluster-reconfiguration-operations), it reads:
  > To replace a single member, make an add then a remove operation.

I'm confused. I'm in need of replacing a running member with better hardware. What is the correct procedure here?

**Comment by fanminshi** [comment]
@zihaoyu use the first instruction to replace a machine [Replace a failed machine](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#replace-a-failed-machine)

We are working on fixing the confusion in doc right now. Thank you for pointing it out for us.

**Comment by zihaoyu** [comment]
Thank you @fanminshi

**Comment by xiang90** [comment]
@zihaoyu Well... They are actually different. One is to replace a failed member, the other one is to replace a running member.

To replace a dead member, you should replace it first. To replace a running member, adding then replacing is somewhat safer.

**Comment by heyitsanthony** [comment]
OK, so this needs to be clarified with replace a /running/ member?

**Comment by xiang90** [comment]
@heyitsanthony Yes.
