### ISSUE TITLE
How to enable strict consistency for data GET?

### ISSUE THREAD

**Issue by ghostplant** [coreos/etcd#7333]
It seems that by etcd default, PUT(key,data) is strict consistent. But GET(key) is not, instead, it is eventually consistent. Two fact can prove it:

1) PUT a new key with large value to leader node, and quickly query this key from a follower. The follower don't get this key SYNCed so it returns empty, but it is expected to return the latest value;
2) When 5-node etcd cluster is divided into 2 parts: 2-node as the first part, and 3-node as the second part. It's obvious that 3-node part can still construct a health service while 2-node part can't. After the division, I query a 2-node part and they can still return the self-value, but it is expected to return SYNC-timeout because they don't know whether their self-owned value is the latest.

So how to enable strict consistency for GET data? I need 2 cases above to return result as expected as a strict consistency model.

**Comment by heyitsanthony** [comment]
Internal `SYNC` messages in etcd have very little to do with consistency; they're used for invalidating v2 TTLs. The `Sync()` client call is totally unrelated; it is used for updating membership so the client can find all the cluster endpoints in case of membership reconfiguration.

Try using a quorum get / linearized get. These must go through raft before they can be satisfied; the result will up-to-date at the time of the request. For v2 etcdctl, it's `etcdctl get -q key`. For ETCDCTL_API=3 etcdctl, it's enabled by default. For the v2 client, it's `GetOptions.Quorum = true`. For the v3 client, it's enabled by default.
