### ISSUE TITLE
Bad etcdctl v3 environment variables in README

### ISSUE THREAD

**Issue by harobed** [coreos/etcd#7334]
In README https://github.com/coreos/etcd/blob/master/etcdctl/README.md#etcdctl, I see:

```
ETCDCTL_CACERT=/tmp/ca.pem
ETCDCTL_CERT=/tmp/cert.pem
ETCDCTL_KEY=/tmp/key.pem
```

they are bad names, good names are:

```
ETCDCTL_CA_FILE=/tmp/ca.pem
ETCDCTL_CERT_FILE=/tmp/etcdctl.pem
ETCDCTL_KEY_FILE=/tmp/etcdctl-key.pem
```

my etcdctl version are:

```
./etcdctl --version
etcdctl version: 3.1.0
API version: 2
```

**Comment by heyitsanthony** [comment]
These are valid options for ETCDCTL_API=3 (i.e., note the `--dial-timeout` that's v3 only), but not the v2 etcdctl API. Unclear whether this is worth correcting if 3.2 is going to flip the switch to default v3.

**Comment by harobed** [comment]
Ok, I find this very confusing. Why change this variables between v2 and v3 ?

I see that when I set `ETCDCTL_API=3` then `etcdctl --help` is different!

I think warning about this subject need to be append in README.

**Comment by harobed** [comment]
Suggest: display a warning if user use v3 variables names when v2 api is enabled.

**Comment by heyitsanthony** [comment]
> I think warning about this subject need to be append in README.

This is literally in the first line after the title heading:
```
etcdctl is a command line client for etcd. Make sure to set environment variable ETCDCTL_API=3. For etcdctl v2, please check READMEv2.
```

**Comment by harobed** [comment]
Ok, it was not clear for me.

I think I can close the issue.
