### ISSUE TITLE
etcd v2 proxy compatibility

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7344]
We are running etcd v2.3.6 in prod for 2 years and are planning to upgrade to v2.3.7 and then to 3.0 and then 3.1 to use it with vault.

Scenario: 
5 machine cluster in qa and prod.
n machines with proxy - each app talks to proxy on localhost and proxy talks to etcd cluster.

Upgrade only etcd cluster to 2.3.7 without upgrading proxy.
Upgrade only etcd cluster to 3.0 without upgrading proxy.
Upgrade only etcd cluster to 3.1 without upgrading proxy.

Questions:
Can v2.3.6 proxy talk to 2.3.7, 3.0 and 3.1 etcd cluster? (Ofcourse the v2 data store not v3)

The reason is existing clients can continue talking to v2 store via v2 proxy on etcd_v3_cluster and clients requiring vault can talk to v3 via new means.

**Comment by heyitsanthony** [comment]
@raoofm yes, it should work. The only difference between that one and the current version of the proxy (proxy/httpproxy) is a few bugfixes-- nothing that would imply any kind of upgrade breakage. The unit tests only cover the current proxy with the current cluster, so I just tried the 2.3.6 proxy with 3.1 and it works OK.

**Comment by raoofm** [comment]
ok thanks thats gr8.

**Comment by xiang90** [comment]
Closing since the question is answered. Thanks @heyitsanthony!
