### ISSUE TITLE
I think etcd client driver should provide a way to set timeout!

### ISSUE THREAD

**Issue by 756445638** [coreos/etcd#7353]
Etcd client driver only provides set  timeout of dail to server!!
I think it is very import to provides timeout mechanism for get&put.

**Comment by gyuho** [comment]
@756445638 Are we talking about `clientv3`?
You can pass your own `context.Context` with timeout for get and puts.

Please see https://godoc.org/github.com/coreos/etcd/clientv3#KV.

**Comment by xiang90** [comment]
Closing this one. As @gyuho suggested, please use go standard way, context, to cancel/timeout the request
