### ISSUE TITLE
etcdserver: mvcc: database space exceeded on mirroring

### ISSUE THREAD

**Issue by AnjaniKr** [coreos/etcd#7356]
Feb 15 02:57:31  vm3 systemd[1]: Starting etcd - highly-available key value store...
Feb 15 02:57:33  vm3 etcd[1200]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd/default
Feb 15 02:57:33  vm3 etcd[1200]: recognized and used environment variable ETCD_NAME= vm3
Feb 15 02:57:33  vm3 etcd[1200]: etcd Version: 3.2.0+git
Feb 15 02:57:33  vm3 etcd[1200]: Git SHA: b9bbfda
Feb 15 02:57:33  vm3 etcd[1200]: Go Version: go1.6.2
Feb 15 02:57:33  vm3 etcd[1200]: Go OS/Arch: linux/amd64
Feb 15 02:57:33  vm3 etcd[1200]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Feb 15 02:57:33  vm3 etcd[1200]: the server is already initialized as member before, starting as etcd member...
Feb 15 02:57:33  vm3 etcd[1200]: advertising using detected default host "x.x.x.x"
Feb 15 02:57:33  vm3 etcd[1200]: listening for peers on http://localhost:2380
Feb 15 02:57:33  vm3 etcd[1200]: listening for client requests on localhost:2379
Feb 15 02:57:33  vm3 etcd[1200]: name =  vm3
Feb 15 02:57:33  vm3 etcd[1200]: data dir = /var/lib/etcd/default
Feb 15 02:57:33  vm3 etcd[1200]: member dir = /var/lib/etcd/default/member
Feb 15 02:57:33  vm3 etcd[1200]: heartbeat = 100ms
Feb 15 02:57:33  vm3 etcd[1200]: election = 1000ms
Feb 15 02:57:33  vm3 etcd[1200]: snapshot count = 100000
Feb 15 02:57:33  vm3 etcd[1200]: advertise client URLs = http://localhost:2379
Feb 15 02:57:34  vm3 etcd[1200]: restarting member eb1aa43632ee8c7e in cluster 30e15548eff6b6d7 at commit index 6
Feb 15 02:57:34  vm3 etcd[1200]: eb1aa43632ee8c7e became follower at term 3
Feb 15 02:57:34  vm3 etcd[1200]: newRaft eb1aa43632ee8c7e [peers: [], term: 3, commit: 6, applied: 0, lastindex: 6, lastterm: 3]
Feb 15 02:57:34  vm3 etcd[1200]: starting server... [version: 3.2.0+git, cluster version: to_be_decided]
Feb 15 02:57:34  vm3 etcd[1200]: added member eb1aa43632ee8c7e [http://x.x.x.x:2380] to cluster 30e15548eff6b6d7
Feb 15 02:57:34  vm3 etcd[1200]: set the initial cluster version to 3.2
Feb 15 02:57:34  vm3 etcd[1200]: enabled capabilities for version 3.2
Feb 15 02:57:34  vm3 etcd[1200]: eb1aa43632ee8c7e is starting a new election at term 3
Feb 15 02:57:34  vm3 etcd[1200]: eb1aa43632ee8c7e became candidate at term 4
Feb 15 02:57:34  vm3 etcd[1200]: eb1aa43632ee8c7e received MsgVoteResp from eb1aa43632ee8c7e at term 4
Feb 15 02:57:34  vm3 etcd[1200]: eb1aa43632ee8c7e became leader at term 4
Feb 15 02:57:34  vm3 etcd[1200]: raft.node: eb1aa43632ee8c7e elected leader eb1aa43632ee8c7e at term 4
Feb 15 02:57:34  vm3 etcd[1200]: published {Name: vm3 ClientURLs:[http://localhost:2379]} to cluster 30e15548eff6b6d7
Feb 15 02:57:34  vm3 etcd[1200]: ready to serve client requests
Feb 15 02:57:34  vm3 systemd[1]: Started etcd - highly-available key value store.
Feb 15 02:57:34  vm3 etcd[1200]: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
Feb 21 00:42:17  vm3 systemd[1]: Stopping etcd - highly-available key value store...
Feb 21 00:42:17  vm3 etcd[1200]: received terminated signal, shutting down...
Feb 21 00:42:18  vm3 etcd[1200]: skipped leadership transfer for single member cluster
Feb 21 00:42:18  vm3 systemd[1]: Stopped etcd - highly-available key value store.
Feb 21 00:50:08  vm3 systemd[1]: Starting etcd - highly-available key value store...
Feb 21 00:50:08  vm3 etcd[45612]: recognized and used environment variable ETCD_DATA_DIR=/var/lib/etcd/default
Feb 21 00:50:08  vm3 etcd[45612]: recognized and used environment variable ETCD_NAME= vm3
Feb 21 00:50:08  vm3 etcd[45612]: etcd Version: 2.2.5
Feb 21 00:50:08  vm3 etcd[45612]: Git SHA: Not provided (use ./build instead of go build)
Feb 21 00:50:08  vm3 etcd[45612]: Go Version: go1.6.2

Before mirroring there was no issue with space, once mirroring happened it took around ( 3.5 GB) only for around 10 keys.

**Comment by xiang90** [comment]
Can you please provide more details? A step by step reproduce would be good.

**Comment by heyitsanthony** [comment]
@AnjaniKr `mvcc: database space exceeded on mirroring` is from the store exceeding the space quota-- since etcd is MVCC it keeps a full key history; keys need to occasionally be compacted away or the database will grow indefinitely. Please see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#history-compaction and https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota

**Comment by AnjaniKr** [comment]
1 > installed etcd using apt-get
2 > second, upgrade to etcd 3.x from source
     # apt-get -y install git golang
3 > replaced binaries
4 > checked the version : 
       ETCDCTL_API=3 etcdctl version
      etcdctl version: 3.2.0+git 
      API version: 3.2
5 > Added around 10 keys without mirroring (space allocation 62M)
6 > started mirroring with same set of keys ( space rose to 3.5GB) 
7 > started giving error database space exceeded

**Comment by heyitsanthony** [comment]
@AnjaniKr how is `etcdctl make-mirror` being invoked? I tried:

```
bin/etcd --name infra1 --listen-client-urls http://127.0.0.1:2379 --advertise-client-urls http://127.0.0.1:2379 --listen-peer-urls http://127.0.0.1:12380 --initial-advertise-peer-urls http://127.0.0.1:12380 --initial-cluster-token etcd-cluster-1 --initial-cluster 'infra1=http://127.0.0.1:12380' --initial-cluster-state new &
bin/etcd --name infra2 --listen-client-urls http://127.0.0.1:22379 --advertise-client-urls http://127.0.0.1:22379 --listen-peer-urls http://127.0.0.1:22380 --initial-advertise-peer-urls http://127.0.0.1:22380 --initial-cluster-token etcd-cluster-2 --initial-cluster 'infra2=http://127.0.0.1:22380' --initial-cluster-state new &

for a in `seq 1 10`; do ETCDCTL_API=3 bin/etcdctl put $a $a; done

# mirror from infra1 to infra2
ETCDCTL_API=3 ./bin/etcdctl make-mirror --no-dest-prefix http://localhost:22379
```

This mirrors 10 keys, periodically printing `10` to indicate that it's only propagated 10 updates; I can't seem to reproduce the failure.

**Comment by AnjaniKr** [comment]
this is what we r doing for mirroring - $from=$HOST1  prefix=/realm/infra1 remote=$HOST2  &&  ssh root@$from "no_proxy=127.0.0.1,$from,$remote ETCDCTL_API=3 nohup etcdctl make-mirror --prefix $prefix --dest-prefix=$prefix $remote:2379 > /dev/null 2>&1 &"
Also we are doing bidirectional mirroring. Once mirroring starts it starts to print key from 0 , 10 ,...some big number(988674)

**Comment by heyitsanthony** [comment]
@AnjaniKr can you reproduce this with hardcoded values, without all the variable substitution?

I strongly suspect make-mirror is being configured to mirror a single cluster back to itself. If the source is the same as the destination then make-mirror will storing keys to the source which will generate new events from the source which will then write back to the source which will generate new events which will be written to the source and so on until storage is exhausted. This can happen if HOST2 is never set; $remote:2379 will substitute to :2379 which will be accepted by a listener on 127.0.0.1:2379.

**Comment by AnjaniKr** [comment]
@heyitsanthony please find detailed steps : 
I'm using two host for mirroring ( bidirectional mirroring)
on first host - etcdctl make-mirror --prefix /realm --dest-prefix=/realm 2nd hst:2379
on second host - etcdctl make-mirror --prefix /realm --dest-prefix=/realm 1st host ip:2379
these r the netstat -lntp status on each host : 
tcp        0      0 x.x.x.x:7001        0.0.0.0:*               LISTEN      26560/etcd
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      26560/etcd
tcp        0      0 x.x.x.x:4001        0.0.0.0:*               LISTEN      26560/etcd
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      26560/etcd
tcp        0      0 x.x.x.x:2379        0.0.0.0:*               LISTEN      26560/etcd
tcp        0      0 x.x.x.x:2380        0.0.0.0:*               LISTEN      26560/etcd

One one way mirroring keys remain constant but as we start bidirectional then it starts increasing (301974) but only 10 keys are there

**Comment by heyitsanthony** [comment]
```sh
etcdctl make-mirror --prefix /realm --dest-prefix=/realm 2nd hst:2379
etcdctl make-mirror --prefix /realm --dest-prefix=/realm 1st host ip:2379
```
This won't work. A write to /realm/X on host1 willl write to /realm/X on host2. If host2 mirrors all writes on /realm back to host1, then /realm/X will be written back to host1, which will then mirrored to host2 then mirrored to host1, etc. There is a cycle; the prefixes must be distinct.

**Comment by AnjaniKr** [comment]
sorry but both realm are different ie /realm and /realm2
etcdctl make-mirror --prefix /realm2 --dest-prefix=/realm2 host1:2379
etcdctl make-mirror --prefix /realm --dest-prefix=/realm host2:2379

**Comment by AnjaniKr** [comment]
@heyitsanthony  within 5 minutes of time mirror count was - 752150 & 789445

**Comment by AnjaniKr** [comment]
@heyitsanthony thanks its working :) 👍

**Comment by heyitsanthony** [comment]
@AnjaniKr `--prefix=/realm --dest-prefix=/realm` may cause problems for a bi-direction setup since /realm prefixes /realm2; you may want to try `/realm1` and `/realm2` or `/realm/` and `/realm2/`. If there's no traffic going into the cluster (aside from the mirroring) the count should be stable.

**Comment by AnjaniKr** [comment]
@heyitsanthony as per  ur comments if I need to set up bidirectional between host A and host B, this is how I need to do : 
frm host1 : 
etcdctl make-mirror --prefix /realm2 --dest-prefix=/realm2 host1:2379
(here prefix realm2 is the key that host1 is putting its data and --dest-prefix is what is being exposed to host2 to mirror right)
So, at host1 I can give both values to be same and at other host those will have different values (ex realm2)

**Comment by heyitsanthony** [comment]
@AnjaniKr 

Running on host1, this will mirror from host1 to host2:
```sh
etcdctl make-mirror --prefix /realm1 --dest-prefix=/realm1 host2:2379
```

Running on host2, this will mirror from host2 to host1:
```sh
etcdctl make-mirror --prefix /realm2 --dest-prefix=/realm2 host1:2379
```

The main thing to avoid is a cycle where `make-mirror` is writing to the same destination path and cluster that it's reading from.

**Comment by xiang90** [comment]
@AnjaniKr Can we close this issue now? I believe @heyitsanthony already helped with all your questions.

**Comment by AnjaniKr** [comment]
@xiang90 Yes thanks we can close the issue.
