### ISSUE TITLE
No working v3 docs?

### ISSUE THREAD

**Issue by shakefu** [coreos/etcd#7378]
I was looking to upgrade our environment to using the v3 API but it looks like the docs are all auto-generated or full of TODOs.

Where's the docs at guys?

**Comment by heyitsanthony** [comment]
There's a bunch of client examples in the [godocs](https://godoc.org/github.com/coreos/etcd/clientv3) and the [Documentation](https://github.com/coreos/etcd/tree/master/Documentation) directory is entirely about v3 (aside from the v2/ directory which is kept for posterity) and includes a simple guide for interacting with v3 [using etcdctl](https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/interacting_v3.md) in addition to the [full etcdctl documentation](https://github.com/coreos/etcd/blob/master/etcdctl/README.md). What sort of documentation are you looking for, exactly?

**Comment by heyitsanthony** [comment]
@shakefu ping?

**Comment by shakefu** [comment]
These docs, the ones that show up when googling "etcd v3 docs"? 

- https://coreos.com/etcd/docs/latest/
- https://coreos.com/etcd/docs/latest/learning/api.html - "NOTE: this doc is not finished!"
- https://coreos.com/etcd/docs/latest/dev-guide/api_reference_v3.html - "This is a generated documentation. Please read the proto files for more."

Maybe they could be updated to link to the repository docs if the repo docs aren't stable enough for publishing yet.

At any rate, it looks like there's zero support for the v3 API via the grpc proxy or direct in node or python, so we can't upgrade anyway.

**Comment by heyitsanthony** [comment]
@shakefu

> https://coreos.com/etcd/docs/latest/learning/api.html 

OK this one is garbage and should probably be nixed; it basically repeats the RPC documentation. The additional prose should just be merged into the protobuf defs. /cc @xiang90 

> https://coreos.com/etcd/docs/latest/dev-guide/api_reference_v3.html 

Are the RPC descriptions not clear enough? If it didn't say it was generated, would you have cared?

> there's zero support for the v3 API via the grpc proxy  or direct in node or python

Huh? The grpc proxy is v3 only. What do you mean there's no support? There's even [grpc proxy documentation](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/grpc_proxy.md). Likewise, there's also a [python library](https://github.com/kragniz/python-etcd3) which is listed in the [libraries and tools documentation](https://github.com/coreos/etcd/blob/master/Documentation/libraries-and-tools.md).

Again, what /sort/ of documentation do you want? Looking for constructive criticism, here. Thanks!

**Comment by shakefu** [comment]
Hey, apologies for missing this notification and not getting back sooner.

Really I think my biggest problem with the docs is the lack of "here's how to use the v3 API" kind of quickstart. Even if the rest of the v3 API docs were rough/generated, getting into a working configuration with etcd and a v3 API client would let me start to learn it through experimentation. 

Ideally this would include some basic examples in a couple main target languages. For me that would obviously be Node and Python, but I suspect for the etcd project Go would be the main target and maybe Java or Python seem to have working v3 clients.

Probably some very basic "why gRPC and what it is vs. HTTP API" would be helpful as well to those of us coming from a non-Go world, who are seeing the v3 API docs and going, "WTF is this shit?" I had to Google "gRPC" to figure out what it was.
