### ISSUE TITLE
Tips for investigating client timeouts after switching to etcd3

### ISSUE THREAD

**Issue by munkyshi** [coreos/etcd#7380]
We've recently switched one of our projects from using an etcd2 backend to an etcd3 backend, and are now hitting client timeouts.

I've been struggling to work on a repro that I can share (still trying!), but posting here to see if anyone has any ideas on how to pinpoint / any thoughts on what the trigger could be.

## Details:
We run multiple parallel processes on the same host as an etcd node, each of which:
- downloads a tarball from S3
- copies it to another location on the host
- untars
- reads a file
- uses that data to sets a couple of keys in etcd
- retars the file with a couple of extra files added

When backed by etcd2, we didn't observe any client timeouts, and usually ran with >4 of these processes in parallel. After switching to an etcd3 client/server, we occasionally see timeouts with 2 processes in parallel, and very frequently with 4.

I'm attaching logs from a timeframe where the client timed out on a single node etcd cluster, as well as system stats during that timeframe (via `sar`).
[logs.zip](https://github.com/coreos/etcd/files/802426/logs.zip)

## Additional observations:
- There seems to a strong correlation between the timeouts and the appearance of `wal sync duration` warnings in the log (we see the `apply entries took too long` outside of this, though perhaps less frequently).
- I initially thought this was related to CPU load generated by tarring/untarring, but artificially inflating CPU load does not seem to trigger the timeouts.
- My current hypothesis has been that there's some disk IOPS sensitivity caused by the S3 downloads and copying files around -- I can trigger the timeouts by saturating IOPS, but I'm also able to trigger the timeouts with etcd2 using the same method, so perhaps this is a red herring.

Please let me know if there's any other info I can give to help (and apologies if there's any obvious information I've missed)!

**Comment by xiang90** [comment]
> we occasionally see timeouts

Are these timeouted requests read or write?

> My current hypothesis has been that there's some disk IOPS sensitivity caused by the S3 downloads and copying files around

I can see very long fsync time in the log, probably you should separate s3 disk and etcd disk?

**Comment by munkyshi** [comment]
> Are these timeouted requests read or write?
These were for linearized gets.

> I can see very long fsync time in the log, probably you should separate s3 disk and etcd disk?
I think that would be reasonable, but difficult in the short term because of how we have the system designed (for more context, we have this sort of setup in many environments, a few of which we don't have the best control of the hardware setup for).

We've throttled the s3 downloads for now, to make things more manageable, so we aren't hurting for any changes -- the two things on my mind were the following:
- Is there any reason to expect etcd3 to be more sensitive to disk IO than etcd2?
- The logs are from a single node etcd, but this also happened on a 3-node test cluster -- is this an expected failover situation? It feels unfortunate that etcd would have been more responsive if we stopped the node instead of having it run while under disk contention.

**Comment by xiang90** [comment]
> These were for linearized gets.

I can guess what happened. By default, v2 Get is not linearized, thus no disk accesses are involved. v3 Get is linearized by default. It hits disk in etcd 3.0 release. We improved that in 3.1 to make it disk free. You might either use serialized get (as v2) or upgrade to etcd 3.1 to mitigate your issue.

**Comment by munkyshi** [comment]
Hmm, I think we were explicitly doing the v2 call with quorum, so I'm not sure if that makes a difference.

That's still great news about the disk free reads in 3.1 -- I will try that out and see how things look.

**Comment by xiang90** [comment]
> Hmm, I think we were explicitly doing the v2 call with quorum, so I'm not sure if that makes a difference.

Then there should not be a HUGE difference. But v3 does need more IOPS during normal operations due to incremental snapshot, but overall it usually results of a more reliable cluster and lower avg IOPS. Perviously, full snapshot will trigger IOPS spikes.

**Comment by munkyshi** [comment]
Wow, bumping my test stack to v3.1.2 does wonders -- this is great, thanks!

**Comment by xiang90** [comment]
@munkyshi Also you can use `ionice` to give etcd more priority on disk to reduce latency when under contention. I am closing this issue now. Thanks for reporting!
