### ISSUE TITLE
Does etcd support QoS

### ISSUE THREAD

**Issue by whustone** [coreos/etcd#7381]
Does etcd support multi-users to use one etcd cluster?
Some user has been  controlled by some hacker, Will it affect other users? Does etcd cluster support QoS?

**Comment by xiang90** [comment]
No. It does not. etcd is designed to be an internal service. Do not expose etcd cluster to public network.

We might add server side rate limiter in the future to support very limited multi-tenancy feature.

**Comment by tangcong** [comment]
#8483
