### ISSUE TITLE
Suggestion: document how to access v3 API in `etcdctl --help`

### ISSUE THREAD

**Issue by caesarxuchao** [coreos/etcd#7385]
It would help a new user if the output of `etcdctl --help` warns the user to specify `ETCDCTL_API=3` if he wants to access v3 API.

I'm use etcdctl in the context of kubernetes, where the etcd cluster is setup by kubernetes. Because kubernetes uses v3 API, at first I couldn't retrieve any keys via etcdctl, it took me a while to figure out that I need to set `ETCDCTL_API=3`.

cc @hongchaodeng

**Comment by hongchaodeng** [comment]
Probably add a line of suggestion when users type `etcdctl xxx` to indicate that v3api should be accessed by enabling `ETCDCTL_API=3` ?

cc @xiang90 @heyitsanthony

**Comment by heyitsanthony** [comment]
@hongchaodeng if there's a message it should probably be under `--help`. Having it for all commands no matter what will make v2 etcdctl's output really ugly. An alternative would be to detect that `ETCDCTL_API` is not set and give a warning.

**Comment by xiang90** [comment]
@heyitsanthony We are going to switch to v3 api by default, right? Seems like this will not be an issue anymore.

**Comment by heyitsanthony** [comment]
@xiang90 sure, but it might be useful to have a warning that ETCDCTL_API is not set so v2 users get some warning they need to update their scripts before everything breaks. I'm fine with leaving it as-is, though.
