### ISSUE TITLE
RFE: Support for encrypt at REST within the clients.

### ISSUE THREAD

**Issue by timothysc** [coreos/etcd#7388]
It's fairly typical for storage systems to provide an encrypt at REST to ensure both the key's data + channel are encrypted.  

I don't think you can store encoded keys.

**Comment by heyitsanthony** [comment]
Is this similar to #7250? The idea is to wrap the client KV and Txn implementations to encrypt data going into etcd and decrypt it coming out.

**Comment by timothysc** [comment]
yup.. I'll close this one in favor for that one.
