### ISSUE TITLE
Upgrade etcd v2 to v3

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7389]
Follow up to #7344 

Recently upgraded production cluster of 5 to 2.3.8. Want to upgrade to v3.1 to use as vault backend.

Is direct upgrade from 2.3.8 to 3.1.2 possible or should I first upgrade to 3.0.17 or just 3.0.0?

**Comment by heyitsanthony** [comment]
2.3.8 -> 3.0.17 -> 3.1.2 is the recommended upgrade path. Direct upgrade from 2.3 to 3.1 might work but it's untested.

**Comment by xiang90** [comment]
I am going to close this one. @heyitsanthony's suggestion is good.

**Comment by raoofm** [comment]
thanks guys
