### ISSUE TITLE
v3 API endpoint status different output formats return contradictory member ID

### ISSUE THREAD

**Issue by LLParse** [coreos/etcd#7391]
When I run `etcdctl endpoint status -w simple` I get this output:
```
127.0.0.1:2379, 2076fb2113bcf20, 3.1.0, 25 kB, false, 2, 276
```
When I run `etcdctl endpoint status -w json` I get this output:
```
[{"Endpoint":"127.0.0.1:2379","Status":{"header":{"cluster_id":983170781618320308,"member_id":146208323496824608,"revision":1,"raft_term":2},"version":"3.1.0","dbSize":24576,"leader":18091059109996920133,"raftIndex":294,"raftTerm":2}}]
```

The decimal member_id 146208323496824608, when converted to hexidecimal, is 2076FB2113BCF18, which is not the reported member ID 2076fb2113bcf20. Is this expected? How am I supposed to deduce the understood hex ID from this JSON output?

**Comment by heyitsanthony** [comment]
> 146208323496824608, when converted to hexidecimal, is 2076FB2113BCF18


```sh
printf "%x\n" 146208323496824608
2076fb2113bcf20
```
???

**Comment by xiang90** [comment]
I am closing this since etcd converts the number correctly.

**Comment by LLParse** [comment]
Sorry, I copied the corrected number by accident. This is what I observed:

```
/ # ./scale-down.sh 
+ ETCDCTL_API=3 etcdctl --endpoints 127.0.0.1:2379 endpoint status -w json
+ jq .[0]
+ ep_status={
  "Endpoint": "127.0.0.1:2379",
  "Status": {
    "header": {
      "cluster_id": 983170781618320300,
      "member_id": 146208323496824600,
      "revision": 1,
      "raft_term": 2
    },
    "version": "3.1.0",
    "dbSize": 24576,
    "leader": 18091059109996920000,
    "raftIndex": 34,
    "raftTerm": 2
  }
}
+ leader_id=18091059109996920000
+ echo obase=16; 146208323496824600
+ bc
+ member_id=2076FB2113BCF18
+ echo obase=16; 18091059109996920000
+ bc
+ leader_id=FB105A68F5F5FCC0
+ etcdctl member remove 2076FB2113BCF18
Couldn't find a member in the cluster with an ID of 2076FB2113BCF18.
```

After some time, I ran the command manually and the member_id had been corrected:
```
/ # etcdctl endpoint status 
127.0.0.1:2379, 2076fb2113bcf20, 3.1.0, 25 kB, false, 2, 130
/ # etcdctl endpoint status -w json
[{"Endpoint":"127.0.0.1:2379","Status":{"header":{"cluster_id":983170781618320308,"member_id":146208323496824608,"revision":1,"raft_term":2},"version":"3.1.0","dbSize":24576,"leader":18091059109996920133,"raftIndex":136,"raftTerm":2}}]
```

**Comment by LLParse** [comment]
I am now realizing the `jq` utility is not going to work for this - it must be mucking up the unsigned integer.

**Comment by vincent99** [comment]
`leader`/`member_id`/`cluster_id` should really be serialized as strings instead of numbers if they are going to be that large.  The JSON spec (intentionally & explicitly) specifies no particular definition of what constitutes a `number`... but JavaScript and many other implementations of JSON parsers unmarshal them into 64-bit float, which has fairly limited precision.

So your JSON response is essentially unusable in many clients & languages because there is not an exact representation for all integers > 2^51 and they will "become" a different number when unserialized.

**Comment by LLParse** [comment]
Conversation was concluded in https://github.com/coreos/etcd/issues/7396
