### ISSUE TITLE
migrate functionality

### ISSUE THREAD

**Issue by holser** [coreos/etcd#7406]
Hi,

Kubernetes is going to use etcdv3 API by default starting from 1.6. However, many projects share one etcd cluster between several resource. For instance, kargo uses etcd for kubernetes and calico.

```
ETCDCTL_API=2 etcdctl ls
/calico
/registry
```

If we decide to upgrade  to v3 data by

```
ETCDCTL_API=3 etcdctl migrate --data-dir="default.etcd" --wal-dir="default.etcd/member/wal"
```

it will upgrade all data. In this case calico will lose all data as it won't be able to read data. It should still support data till it's ready.

Is it possible to make functionality to migrate only '/registry' to v3 and leaving '/calico' in v2 format till it's ready? It would be nice to allow operators to decide what branches should be converted and what should be left untouched.

**Comment by xiang90** [comment]
>  In this case calico will lose all data as it won't be able to read data. It should still support data till it's ready.

Migration will not remove the old data. Have you gave it a try? If it loses data, please file a bug report with reproduce steps.

**Comment by mattymo** [comment]
@xiang90 Thanks! You seem to be right. Old data still persists as you said.
