### ISSUE TITLE
how to rotate logs

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7414]
I tried to look for any documentation or issues explaining this but didn't find. I would like to know what is the recommended approach to handle ever growing logs, which grows a lot if 1 node is down or even for some latencies. Though this can be handled with any custom script or cron but wanted to know if etcd itself provides anything to rotate log files (say daily) and  keep only n number of old copies.

The closest i got to is #5728

Also if there is a solution is it different for v2 and v3?

**Comment by gyuho** [comment]
Are we talking about etcd server logs?

I tried `logrotate` and works well?
http://www.linuxcommand.org/man_pages/logrotate8.html

Or if you deploy etcd with systemd, `journalctl` has some vacuum features with `journalctl --vacuum-*` 

We don't have any built-in support or documentation.

**Comment by raoofm** [comment]
> Are we talking about etcd server logs?
yes

**Comment by xiang90** [comment]
etcd itself does not rotate logs. So no magic will happen inside etcd. There are a lot of existing external tools to manage logs for you: journald, logrotate, fluentd etc..

**Comment by raoofm** [comment]
ok, just checking :smiley:
