### ISSUE TITLE
docs: Migrate example is missing migrate command

### ISSUE THREAD

**Issue by tmjd** [coreos/etcd#7418]
I believe the example of the migrate command in the docs
https://github.com/coreos/etcd/blob/master/etcdctl/README.md#example-14
is missing the actual migrate command.

**Comment by xiang90** [comment]
@tmjd Right. Can you help to fix it?

**Comment by tmjd** [comment]
Sure, I'll fix it, I just was not sure that I was correct.

**Comment by xiang90** [comment]
@tmjd Thanks for the quick fix!
