### ISSUE TITLE
docs: no references to 'etcd-member.service' for etcd3 on container linux

### ISSUE THREAD

**Issue by euank** [coreos/etcd#7436]
As best I can tell, the recommended way to run etcd3 on recent Container Linux (by CoreOS) versions is using the etcd-member service: https://github.com/coreos/coreos-overlay/blob/build-1325/app-admin/etcd-wrapper/files/etcd-member.service

I can't find any etcd documentation on doing that.

The documentation also doesn't point to config-transpiler's etcd sugar, but really it should mention both how to add the service on an existing node, and how to provision a new one with ct.
We can start with just the etcd-member docs.

cc @crawford

**Comment by euank** [comment]
The document https://coreos.com/etcd/docs/latest/op-guide/container.html does exist.

I don't believe there are any links to it though, so it's just something you have to either find on github or know exists somehow.

**Comment by gyuho** [comment]
Yeah the container doc only covers general usage. On Container Linux, you can do

```

# to update etcd-member service file
cat > /tmp/override-my-etcd-1.conf <<EOF
[Service]
Environment="ETCD_IMAGE_TAG=v3.1.0"
Environment="ETCD_DATA_DIR=/var/lib/etcd"
Environment="ETCD_SSL_DIR=/etc/ssl/certs"
Environment="ETCD_OPTS=--name my-etcd-1 \
    --listen-client-urls https://10.240.0.1:2379 \
    --advertise-client-urls https://10.240.0.1:2379 \
    --listen-peer-urls https://10.240.0.1:2380 \
    --initial-advertise-peer-urls https://10.240.0.1:2380 \
    --initial-cluster my-etcd-1=https://10.240.0.1:2380,my-etcd-2=https://10.240.0.2:2380,my-etcd-3=https://10.240.0.3:2380 \
    --initial-cluster-token my-etcd-token \
    --initial-cluster-state new \
    --client-cert-auth \
    --trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
    --cert-file /etc/ssl/certs/my-etcd-1.pem \
    --key-file /etc/ssl/certs/my-etcd-1-key.pem \
    --peer-client-cert-auth \
    --peer-trusted-ca-file /etc/ssl/certs/etcd-root-ca.pem \
    --peer-cert-file /etc/ssl/certs/my-etcd-1.pem \
    --peer-key-file /etc/ssl/certs/my-etcd-1-key.pem \
    --auto-compaction-retention 1"
EOF
sudo mkdir -p /etc/systemd/system/etcd-member.service.d
sudo mv /tmp/override-my-etcd-1.conf /etc/systemd/system/etcd-member.service.d/override.conf

# to check service-file-override status
sudo systemd-delta --type=extended

# to start service
sudo systemctl daemon-reload
sudo systemctl enable etcd-member.service
sudo systemctl start etcd-member.service
```

This works in alpha channel. But not sure about other channels.
@crawford should know better?

**Comment by crawford** [comment]
We should document this. Would you mind adding it to coreos/doc?

**Comment by xiang90** [comment]
I closed this since it is tracked here: https://github.com/coreos/docs/pull/1016
