### ISSUE TITLE
Missing info about flags in upgrade v3 doc

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7440]
Just wondering if there is a need to mention about any changes/new flags to consider while upgrading from v2 to v3.
Or for that matter if there is no change to the flags and no new flags were added then should we mention that all the configuration/flags should work as is.

Didn't find any mention about flags in 
https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md

**Comment by heyitsanthony** [comment]
It should work as-is so long as etcd wasn't configured with flags that were marked as deprecated in v2's command line options:
"ca-file"
"peer-ca-file"
"addr"
"bind-addr"
"peer-addr"
"peer-bind-addr"

**Comment by raoofm** [comment]
Thanks, this answers my query. Closing it.
