### ISSUE TITLE
Using etcd with tmpfs backing only?

### ISSUE THREAD

**Issue by wrouesnel** [coreos/etcd#7445]
Had anyone had any luck using etcd with an ephemeral or disabled local data directory?

Specifically is it possible to keep data in memory but cluster membership details on disk to avoid needing to script to cluster rejoining on an unexpected shutdown?

The use case is master nodes in a DC which hold easily recreatable state in the event of a total outage but for which I do not have dedicated fast storage for each local disk (but tons of RAM available).

**Comment by heyitsanthony** [comment]
If a member acknowledges data as persisted, it can't come back up without that data. The way to do tmpfs is to remove the lost member from the cluster and add a fresh one.

**Comment by xiang90** [comment]
@wrouesnel If you can make sure you NEVER restart a member whose data is lost. It is safe. Or you might end up inconsistent cluster state.

**Comment by xiang90** [comment]
I am closing this. I believe the question is answered.
