### ISSUE TITLE
etcd 2.3.6, cannot rebuild the cluster from the backup wal

### ISSUE THREAD

**Issue by wangyumi** [coreos/etcd#7447]
# Bug reporting

I am trying to rebuild a three nodes etcd cluster from the backup wal file.

# env
$ etcdctl -version
etcdctl version 2.3.6

$ uname -a
Linux SZX1000254594 3.13.0-107-generic #154-Ubuntu SMP Tue Dec 20 09:57:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# restore script
my rebuild screipt :
$ pwd
/var/lib/etcd
$cat rebuild.sh
service etcd stop
rm -rf backup && mv -f 10.21.91.148 backup &&  mkdir 10.21.91.148
etcdctl backup --data-dir backup --backup-dir 10.21.91.148
service etcd start

# step 1:  I change the etcd conf file:
$ cat /etc/default/etcd
ETCD_OPTS='-force-new-cluster -data-dir=/var/lib/etcd/10.21.91.148 -name=10.21.91.148 -listen-client-urls=http://0.0.0.0:2379 -listen-peer-urls=http://0.0.0.0:2380 -advertise-client-urls=http://10.21.91.148:2379 -initial-advertise-peer-urls=http://10.21.91.148:2380'

# step 2:
$sh rebuild.sh
etcd stop/waiting
etcd start/running, process 69724

# step3, check:
$ etcdctl cluster-health
member 5aab64a5fb01 is healthy: got healthy result from http://10.21.91.148:2379
cluster is healthy
$ etcdctl member list
5aab64a5fb01: name=10.21.91.148 peerURLs=http://localhost:7001,http://localhost:2380 clientURLs=http://10.21.91.148:2379 isLeader=true

# step4, try add a node to the cluster:
$etcdctl member add 10.21.74.106 http://10.21.74.106:2380
Added member named 10.21.74.106 with ID c7059fa5aa489ac9 to cluster

ETCD_NAME="10.21.74.106"
ETCD_INITIAL_CLUSTER="**10.21.91.148=http://localhost:7001,10.21.91.148=http://localhost:2380**,10.21.74.106=http://10.21.74.106:2380"
ETCD_INITIAL_CLUSTER_STATE="existing"

you can see the ETCD_INITIAL_CLUSTER is not correct , and if I start a new node on 10.21.74.106 withe the given parameters, it can not find th leader node.

Actually I find the result is random, sometime I can get the correct ETCD_INITIAL_CLUSTER env when a add new member.

Any ideas?

/Regards
Yu Wang

**Comment by heyitsanthony** [comment]
Restore will default the peer advertise address to localhost. The [restore guide](https://github.com/coreos/etcd/blob/master/Documentation/v2/admin_guide.md#restoring-the-cluster) notes that the peer advertise address should be [updated](https://github.com/coreos/etcd/blob/master/Documentation/v2/runtime-configuration.md#update-a-member) before adding new members.

**Comment by wangyumi** [comment]
@heyitsanthony  thank you for your quick response. I believe sometime I can get the expected result even if I do not use member update but I cannot reproduce it now.

Anyway, I write the script blow and make it work as expected:
```
leader_ip=10.21.91.148

service etcd stop
cd /var/lib/etcd
rm -rf backup && mv -f $leader_ip backup &&  mkdir $leader_ip
etcdctl backup --data-dir backup --backup-dir $leader_ip
service etcd start

sleep 5

leader=$(etcdctl member list|cut -f 1 -d ' '|cut -f 1 -d ':')

echo leader: $leader

etcdctl member update $leader http://$leader_ip:2380

echo cluster health
etcdctl cluster-health

echo member list
etcdctl member list
```

**Comment by heyitsanthony** [comment]
Closing since this appears resolved.
