### ISSUE TITLE
Are GPG signatures available for source tar.gz files?

### ISSUE THREAD

**Issue by tpot** [coreos/etcd#7449]
Hi there.  Is there is supposed to be a .asc file as a signature for the source releases?  I'm poking around at the v3.1.2 release and there are detached signatures for the binary releases but not for the source.  

Apologies if I've missed something obvious here.

**Comment by gyuho** [comment]
Currently we don't sign zipped source files.
Should we? /cc @xiang90 @heyitsanthony

**Comment by heyitsanthony** [comment]
Probably a good idea; some users prefer to build from source for auditing purposes.

**Comment by gyuho** [comment]
Ok I will start signing the zipped source files as well from the next release.

**Comment by tpot** [comment]
Fantastic - thanks very much!

**Comment by xiang90** [comment]
Fixed. Closing.

**Comment by tpot** [comment]
Just added tweaks to the Debian etcd package that successfully verifies the source signature when downloading. Thanks again!
