### ISSUE TITLE
ETCD MIRROR NOT HAPPENING ON TLS

### ISSUE THREAD

**Issue by AnjaniKr** [coreos/etcd#7451]
etcd.service - etcd - highly-available key value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-03-08 00:55:14 PST; 1h 56min ago
     Docs: https://github.com/coreos/etcd
           man:etcd
 Main PID: 11139 (etcd)
    Tasks: 9
   Memory: 22.5M
      CPU: 36.952s
   CGroup: /system.slice/etcd.service
           └─11139 /usr/bin/etcd

Mar 08 00:55:13vmetcd etcd[11139]: enabled capabilities for version 3.2
Mar 08 00:55:14 vmetcd etcd[11139]: ce2a822cea30bfca is starting a new election at term 3
Mar 08 00:55:14 vmetcd etcd[11139]: ce2a822cea30bfca became candidate at term 4
Mar 08 00:55:14 vmetcd etcd[11139]: ce2a822cea30bfca received MsgVoteResp from ce2a822cea30bfca at term 4
Mar 08 00:55:14 vmetcd etcd[11139]: ce2a822cea30bfca became leader at term 4
Mar 08 00:55:14 vmetcd etcd[11139]: raft.node: ce2a822cea30bfca elected leader ce2a822cea30bfca at term 4
Mar 08 00:55:14 vmetcd etcd[11139]: published {Name:infra1 ClientURLs:[https://localhost:2379]} to cluster 7e27652122e8b2ae
Mar 08 00:55:14 vmetcd systemd[1]: Started etcd - highly-available key value store.
Mar 08 00:55:14 vmetcd etcd[11139]: ready to serve client requests
Mar 08 00:55:14 vmetcd etcd[11139]: serving client requests on x.x.x.x:2379

etcdctl is running on tls using option --cert and --key options
I am making mirror using below command : 
HOST1=host1
HOST2=xhost2
from=$HOST1  prefix=/realm/abc remote=$HOST2  &&  ssh root@$from "no_proxy=127.0.0.1,$from,$remote ETCDCTL_API=3 nohup etcdctl make-mirror --prefix $prefix --dest-prefix=$prefix $remote:2379" &

If I put data under /realm/abc in host1 , same thing is not reflecting on host2

If I manually give --endpoints=host1 then it is able to fetch the details

**Comment by heyitsanthony** [comment]
What error is `make-mirror` returning? How is etcd being started?


```sh
from=$HOST1 prefix=/realm/abc remote=$HOST2 && ssh root@$from "no_proxy=127.0.0.1,$from,$remote ETCDCTL_API=3 nohup etcdctl make-mirror --prefix $prefix --dest-prefix=$prefix $remote:2379" &
```
There's no `--cert` or `--key` in that command?

> If I manually give --endpoints=host1 then it is able to fetch the details


make-mirror uses `--endpoints` for the data source. This defaults to `127.0.0.1:2379`. TLS expects the https scheme to be explicitly configured (e.g., , `--endpoint=https://host1:2379`).

**Comment by AnjaniKr** [comment]
@heyitsanthony  etcd is started as a system service - service etcd start
following is etcd conf : /etc/default/etcd
ETCD_PROXY=off
ETCD_NAME=infra1
ETCD_DISCOVERY=
ETCD_CERT_FILE=/opt/etcd_certs/server.crt
ETCD_KEY_FILE=/opt/etcd_certs/server.key
ETCD_LISTEN_CLIENT_URLS=https://x.x.x.x:2379
ETCD_ADVERTISE_CLIENT_URLS=https://x.x.x.x:2379  

this is how make mirror is invoked : 
etcdctl make-mirror --prefix /realm --dest-prefix=/realm x.x.x.x:2379

**Comment by heyitsanthony** [comment]
`etcdctl` needs `https://` for both the source endpoint in `--endpoints` and the destination endpoint, otherwise it won't know to use tls

**Comment by AnjaniKr** [comment]
so u mean cmd should be like : 
etcdctl make-mirror --endpoints https://x.x.x.x:2379 --prefix /realm --dest-prefix=/realm https://x.x.x.x:2379

**Comment by AnjaniKr** [comment]
also do we need to pass crt files in make mirror

**Comment by heyitsanthony** [comment]
@AnjaniKr yes it needs `https://` for the endpoints and if you want to authenticate the servers, it'll need `--cacert` if the cert is not already installed (otherwise use `--insecure-skip-tls-verify=true`).

**Comment by AnjaniKr** [comment]
@heyitsanthony getting Error:  grpc: timed out when dialing after using --cacert with endpoints.
Also remote is also running on https with its own certificates

**Comment by heyitsanthony** [comment]
@AnjaniKr you'll need to set `--dest-cacert` too. These options are in `etcdctl make-mirror --help`.

**Comment by AnjaniKr** [comment]
oh then I need to have both cacerts in one machine right. Let me try

**Comment by AnjaniKr** [comment]
@heyitsanthony thanks its working also have one query how can it listen to https://127.0.0.1:2379
I tried giving in configuration file but its not working

**Comment by heyitsanthony** [comment]
It probably needs 127.0.0.1 as an accepted host in server certificate.

**Comment by AnjaniKr** [comment]
thanks will do 👍

**Comment by AnjaniKr** [comment]
@heyitsanthony  thanks closing
