### ISSUE TITLE
v2 to v3 migrate command just hangs

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7460]
Just ran this command on 1 of the 3 machines and it just hangs here. It never comes back saying compelted. Am I doing something wrong here

$sudo ETCDCTL_API=3 ./etcdctl --endpoints=https://node01.example.com2379,https://node02.example.com:2379,https://node03.example.com:2379 --cacert=/var/home/rm/cfssl/ca.pem migrate --data-dir=/var/lib/etcd/cluster/datadir

using default transformer
2017-03-08 20:35:03.714521 I | api: enabled capabilities for version 3.0
2017-03-08 20:35:03.714597 I | membership: added member 684f2e4032b4dcc2 [https://node03.example.com:2380] to cluster 0 from store
2017-03-08 20:35:03.714609 I | membership: added member ac463f989b4b89ae [https://node02.example.com:2380] to cluster 0 from store
2017-03-08 20:35:03.714617 I | membership: added member c8d81b0c5a97ef5f [https://node01.example.com:2380] to cluster 0 from store
2017-03-08 20:35:03.714625 I | membership: set the cluster version to 3.0 from store

**Comment by raoofm** [comment]
Using etcd v 3.0.17

**Comment by heyitsanthony** [comment]
@raoofm I suspect it's trying to run on a wal directory that belongs to a running etcd process. It'll try to acquire a lock on the wal files but etcd already holds it. The way to mitigate is either make a copy of the member directory for migrate to process or shutdown the etcd server and then run; it's meant to be an offline tool.

There's a warning in 3.1 about this.

**Comment by raoofm** [comment]
Thanks, makes sense. Below link gave an impression that the load balancer can be set to read only and then migrate can be run on data-dir. I missed the part that says "copy the etcd data directories and begin the migration. After all etcd nodes are migrated, we start a new etcd3 cluster with the migrated data"

https://coreos.com/blog/migrating-applications-etcd-v3.html

Will it migrate just the data or the users and roles as well. I mean will the auth work on v3 with the same credentials and permissions as v2?

**Comment by heyitsanthony** [comment]
It only migrates keys into v3.

**Comment by raoofm** [comment]
Makes sense, thanks.

**Comment by gjw0317** [comment]
@raoofm I meet the same question. I have stopped all the kube services on k8s's master node, but it doesn't work. The migrate command just hangs, how do you solve this problem?

**Comment by heyitsanthony** [comment]
@gjw0317 it's hanging from using a member directory that's being used by an active etcd instance; either stop etcd first or run migrate on a copy of the directory.
