### ISSUE TITLE
allowing a one member cluster without wedging

### ISSUE THREAD

**Issue by glycerine** [coreos/etcd#7464]
https://github.com/coreos/etcd/blob/master/raft/README.md says

>To ensure there is no attempt to commit two membership changes at once by matching log positions (which would be unsafe since they should have different quorum requirements), any proposed membership change is simply disallowed while any uncommitted change appears in the leader's log.
>
>This approach introduces a problem when removing a member from a two-member cluster: If one of the members dies before the other one receives the commit of the confchange entry, then the member cannot be removed any more since the cluster cannot make progress. For this reason it is highly recommended to use three or more nodes in every cluster.

This means two servers are really just one server from a fault-tolerance point of view. You can't loose one of the two without going down. They are effectively just a less robust version of one server; a fault with either will take down the cluster.

Lets figure out how this can be fixed; how to support going from a configuration of two to a configuration of one without getting wedged.  This will mean tolerating split brain situations (perhaps with permission from a config setting), but that is okay/desired in many circumstances.

**Comment by heyitsanthony** [comment]
> This means two servers are really just one server from a fault-tolerance point of view.

No. They're effectively in a mirroring configuration. If one member is lost, you can rebuild the cluster through disaster recovery using the remaining member.

> This will mean tolerating split brain situations (perhaps with permission from a config setting), but that is okay/desired in many circumstances.

Features that can lead to split brain totally defeat the purpose of etcd. I don't think this will ever happen.

**Comment by glycerine** [comment]
> No. They're effectively in a mirroring configuration. If one member is lost, you can rebuild the cluster through disaster recovery using the remaining member.

I don't understand. You seem to be disputing the accuracy of the statements quoted from the README.  The README.md claims, and I experienced myself, that a two -> one member cluster may become irrepairably wedged:

> This approach introduces a problem when removing a member from a two-member cluster: If one of the members dies before the other one receives the commit of the confchange entry, then the member cannot be removed any more since the cluster cannot make progress. For this reason it is highly recommended to use three or more nodes in every cluster.

@heyitsanthony if you see a way out, please be specific. What is the recovery protocol in this situation?

**Comment by heyitsanthony** [comment]
The recovery guide is here: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md

Quorum for that cluster will become lost forever. However, since a commit on the cluster must persist to both nodes before acking, no data is lost. That data can be used to recover into a fresh cluster. This is handled mechanically with the etcd-operator and can also be done manually by following the recovery guide.

**Comment by heyitsanthony** [comment]
@glycerine ping? Does recovery resolve the issue?

**Comment by xiang90** [comment]
> but that is okay/desired in many circumstances.

You can work around this by forcing commit the apply entry. This is not really what we want to do in etcd though. But if you plan to use raft library directly, nothing will prevent you from doing so.

**Comment by glycerine** [comment]
Thanks for your helpful comments, guys. This has been educational. I don't think there's anything that etcd should or plans to change in response, so I'll mark this closed.
