### ISSUE TITLE
gateway: does not send sd_notify event

### ISSUE THREAD

**Issue by bdudelsack** [coreos/etcd#7465]
The default configuration for etcd-member.service (from CoreOS) with Type=notify does not work for the gateway mode.

**Comment by gyuho** [comment]
Try overwriting `etcd-member.service` in `override.conf` and run it again?

**Comment by heyitsanthony** [comment]
@gyuho it needs to explicitly send the message. The etcd server does it at https://github.com/coreos/etcd/blob/master/etcdmain/etcd.go#L172 but the gateway does nothing.

**Comment by heyitsanthony** [comment]
grpc proxy is missing this too
