### ISSUE TITLE
Cannot use etcd v3 (via gRPC) with PHP?

### ISSUE THREAD

**Issue by snarlysodboxer** [coreos/etcd#7490]
Is there a way to generate working PHP gRPC client stubs? Maybe I'm missing something?

According to the [Protobuf PHP runtime docs' Known Issues](https://github.com/google/protobuf/tree/master/php#known-issues), there is "Missing support for proto2." and [rpc.proto](https://github.com/coreos/etcd/blob/master/etcdserver/etcdserverpb/rpc.proto) imports at least three protobuf files that are proto2: `gogoproto/gogo.proto`, `google/protobuf/descriptor.proto`, and `google/protobuf/compiler/plugin.proto`.

I can seemingly successfully use protoc to generate the etcd php client stubs, but the mentioned dependancies are missing, so it fails at runtime.

I was following gRPC docs for PHP, [here](http://www.grpc.io/docs/quickstart/php.html) and [here](http://www.grpc.io/docs/tutorials/basic/php.html).

**Comment by xiang90** [comment]
No one in the etcd team are PHP experts. You probably should ask in gRPC community instead.
