### ISSUE TITLE
v3 https: config finished and auth failed

### ISSUE THREAD

**Issue by strugglingyouth** [coreos/etcd#7494]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

$ etcdctl version
etcdctl version: 3.0.14
API version: 3.0

as follow tutorial generate self-signed certificates:

https://coreos.com/os/docs/latest/generate-self-signed-certificates.html

use  follow config:

$ cat /etc/etcd/etcd.conf
ETCD_CERT_FILE="/etc/ssl/etcd/server.pem"
ETCD_KEY_FILE="/etc/ssl/etcd/server-key.pem"
ETCD_TRUSTED_CA_FILE="/etc/ssl/etcd/ca.pem"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_PEER_CERT_FILE="/etc/ssl/etcd/member1.pem"
ETCD_PEER_KEY_FILE="/etc/ssl/etcd/member1-key.pem"
ETCD_PEER_TRUSTED_CA_FILE="/etc/ssl/etcd/member1.pem"
ETCD_PEER_CLIENT_CERT_AUTH="true"

$ systemctl status -l etcd

Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:4001: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:4001: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:4001: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:2379: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:2379: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:2379: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:2379: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:2379: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:4001: connection error: desc = "transport: remote error: bad certificate"; please retry.
Mar 14 10:56:10 localhost.localdomain etcd[27810]: Failed to dial 0.0.0.0:4001: connection error: desc = "transport: remote error: bad certificate"; please retry.

**Comment by strugglingyouth** [comment]
Test whether the certificate is available:

$ etcdctl --endpoints=[xxxxx:2379] --cacert=/etc/ssl/etcd/ca.pem --cert=/etc/ssl/etcd/client.pem --key=/etc/ssl/etcd/client-key.pem member list
145b401ad8709f51, started, node1, http://xxxxx:2380, https://xxxx:2379


$ etcdctl --endpoints=[xxxx:2379] --cacert=/etc/ssl/etcd/ca.pem --cert=/etc/ssl/etcd/client.pem --key=/etc/ssl/etcd/client-key.pem put /foo/bar  "hello world"
OK

$ etcdctl --endpoints=[xxxx:2379] --cacert=/etc/ssl/etcd/ca.pem --cert=/etc/ssl/etcd/client.pem --key=/etc/ssl/etcd/client-key.pem get /foo/bar
/foo/bar
hello world

config kube-apiserver use https (k8s version is 1.6)

$ kubectl get cs
NAME                 STATUS      MESSAGE                                                                   ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-0               Unhealthy   Get https://xxxx:2379/health: remote error: tls: bad certificate


then  update etcd to 3.1.3, `systemctl status etcd `  result is ok,but `kubectl get cs `  is still the result above.

**Comment by gyuho** [comment]
> 145b401ad8709f51, started, node1, http://xxxxx:2380, https://xxxx:2379

The scheme for peer URL is `http`?

**Comment by strugglingyouth** [comment]
Yes,the output is really that.Forget to say, kubernetes is ok, it can be create deployment and pod....,`kubectl get node` also  is ok.

The following is my complete configuration:

$ cat /etc/etcd/etcd.conf

ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="https://xxxx:2380"
ETCD_LISTEN_CLIENT_URLS="https://xxxx:2379,https://xxxx:4001"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://xxxx:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://xxxx:2379"

ETCD_NAME="node1"
ETCD_INITIAL_CLUSTER="node1=https://xxxx:2380"
ETCD_INITIAL_CLUSTER_STATE="new"

#[security]
ETCD_CERT_FILE="/etc/ssl/etcd/server.pem"
ETCD_KEY_FILE="/etc/ssl/etcd/server-key.pem"
ETCD_TRUSTED_CA_FILE="/etc/ssl/etcd/ca.pem"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_PEER_CERT_FILE="/etc/ssl/etcd/member1.pem"
ETCD_PEER_KEY_FILE="/etc/ssl/etcd/member1-key.pem"
ETCD_PEER_TRUSTED_CA_FILE="/etc/ssl/etcd/member1.pem"
ETCD_PEER_CLIENT_CERT_AUTH="true"

**Comment by gyuho** [comment]
> ETCD_PEER_TRUSTED_CA_FILE="/etc/ssl/etcd/member1.pem"

Isn't this cert file? If you self-sign, you need to pass CA file to `ETCD_PEER_TRUSTED_CA_FILE`.
Can you double-check?

**Comment by strugglingyouth** [comment]
Thanks, It's really wrong.Now etcd is ok ,but `kubectl get cs`  have  problem seems to be kubernetes's bug.

**Comment by gyuho** [comment]
Ok then closing. Thanks.
