### ISSUE TITLE
how to deploy a etcd cluster in different IDC

### ISSUE THREAD

**Issue by huangsanye** [coreos/etcd#7506]
l want to understand  how to deploy a etcd cluster in different IDC
                                                                                         

                                                                                       thank you

**Comment by xiang90** [comment]
Can you please provide more information?

- What is your use case

- What do you want to achieve for multi DC deployment? (Simple master slave backup? Consistent replication? Eventual consistent replication?)

- Any other requirements?

**Comment by huangsanye** [comment]
@xiang90  our Micro service run in different idc，so l want to deploy a etcd cluster in different IDC，each Mirco service can connect one of member of the etcd cluster.

**Comment by xiang90** [comment]
@huangsanye You want the etcd member to accept writes in both DC?

**Comment by huangsanye** [comment]
@xiang90  yes  in different dc

**Comment by xiang90** [comment]
OK. Please read https://github.com/coreos/etcd/blob/master/Documentation/tuning.md#time-parameters. All you can do is to tune the timeout parameter. You have to accept the additional latency due to cross DC communication. Max throughput wont be affect a lot though.
