### ISSUE TITLE
clientV3: How to get all the keys?

### ISSUE THREAD

**Issue by sipt** [coreos/etcd#7510]
Get all the keys in EtcdV3.
My way:
```go
r, err := cli.Get(context.Background(), "!", clientv3.WithPrefix(), clientv3.WithRange("~"))
```
Feeling so coding is not elegant.Is there a better way?

**Comment by gyuho** [comment]
`cli.Get(context.Background(), "\x00", clientv3.WithFromKey())` returns the whole key.
