### ISSUE TITLE
Error: unknown flag: --enable-pprof

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#7514]
The latest master doesn't appear to recognize the --enable-pprof flag. 

![screenshot from 2017-03-15 14-23-13](https://cloud.githubusercontent.com/assets/423038/23966901/078f9a1a-098b-11e7-89ab-6bbb412c510c.png)

**Comment by heyitsanthony** [comment]
There's never been an --enable-pprof flag for grpc-proxy. It can be added, though.

**Comment by davissp14** [comment]
I am trying to troubleshoot an issue that appears similar to: https://github.com/coreos/etcd/pull/7492 on the proxy.  If it's an easy add, that would be amazing.

**Comment by xiang90** [comment]
@davissp14 If you can submit a patch, we will happily accept it.

**Comment by davissp14** [comment]
@xiang90 I'll see what I can do.
