### ISSUE TITLE
Quorum Get cause high disk utils

### ISSUE THREAD

**Issue by supermeng** [coreos/etcd#7519]
etcd Version: 2.3.7
Git SHA: fd17c91
Go Version: go1.6.3
Go OS/Arch: linux/amd64

Hello, In our produce etcd cluster, disk utils keeps on 30%-50% and sometimes 100%. So I have done some simple test to find the reason, finally I found  docker swarm do a lot of QGET(800qps) which result in written wal frequently.

I'm a little bit confused with Etcd's Qurorum Get, why should it need to store in wal, and may i patch etcd written wal ignore QGET？

**Comment by xiang90** [comment]
v2 API is not super efficient/smart about QGET. It does need a write. It is already improved in v3. It is unsafe to simply ignore that write inside WAL. The best way to handle this is to upgrade to etcd3 and start using v3 API.
