### ISSUE TITLE
Is there any metrics for data sync latency from leader to each member

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#7520]
We encountered one issue in one etcd cluster which has 5 members in kubernetes cluster. There're hundreds of nodes in the cluster, and there're a lot of operations on the k8s resources.
We got some business logic error when there's one switch on the service endpoint switch to kube-apiserver.

And after investigation for some time, we got the message that the data has latencies on different etcd members, and the business part get the old data from another different etcd member. 

And there're no such metrics to show the latencies between etcd leader and etcd members. 
Or I haven't found it yet.
Need your help.

**Comment by xiang90** [comment]
We do not have builtin function to calculate the latency. However, you can use endpoint status call to get the raft index of leader, followers in parallel. You can know the revision/index lags between leader and different followers. Then you can covert it to timing if you wish.
