### ISSUE TITLE
Update etcd 2.0.9 to etcd 3

### ISSUE THREAD

**Issue by drinktee** [coreos/etcd#7534]
# Update etcd 2.0.9 to etcd 3

I've read the doc about update.Now I wonder if I should update 2.0.9 to 2.1,2.2,2.3 and then 2.3=>3, or I can just update 2.0.9 to 2.3, and the 2.3 =>3 ?

**Comment by raoofm** [comment]
@drinktee  I have asked similar q?s earlier and the general idea is

2.0 -> 2.1 -> 2.2 -> 2.3 -> 3.0 -> 3.1

Above is the recommended way. 

For all other types of upgrades, it might work but it isn't tested extensively.

**Comment by xiang90** [comment]
@drinktee What @raoofm suggested is correct. We might test cross minor versions updates in the future, but we do not have the bandwidth to do it now.

I am closing this issue now.
