### ISSUE TITLE
Is it possible to add comments in raft/raftpb

### ISSUE THREAD

**Issue by ggaaooppeenngg** [coreos/etcd#7535]
The message are generated by gogoprotobuf and contains no comments (so no doc can be rendered), for example I can not tell the Message.Term == 0 means local Message, is it possible to add comments to Message, or an alternative way to make up the lost documents?

**Comment by gyuho** [comment]
We have un-complete docs in the file https://github.com/coreos/etcd/blob/master/raft/doc.go (I see some are even outdated...).

**Comment by ggaaooppeenngg** [comment]
As go-raft is not maintained, etcd/raft maybe the best choice for someone to implement a raft-based clusters. Really hope the document is consistent with the code, and I am willing to help complete it if I fully deep into the implementation.

**Comment by xiang90** [comment]
OK. There are quite a lot of users of etcd/raft. If you feel some parts of the doc needs improve, just send us PRs.
