### ISSUE TITLE
Support for other auth providers.

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7537]
Just wondering if this usecase is in plan. We have a usecase where we would like to have users authenticate to ldap or other oauth providers, rather than maintaining users in etcd with passwords of no rules.

**Comment by raoofm** [comment]
In this case, we will only need policies and can get rid of maintaining passwords/users

**Comment by xiang90** [comment]
We do not have any plan to integrate with other auth provider at the moment.

**Comment by srinathkotu** [comment]
+1

**Comment by mitake** [comment]
If someone can implement a prototype, probably I'll be able to review. But we need to care about that external components should be linearizable and highly available for keeping these properties of etcd.

**Comment by gyuho** [comment]
Closing in favour of https://github.com/coreos/etcd/issues/8217.
