### ISSUE TITLE
etcdtcl v3.1 unsupported output format proto for member list

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7538]
[root@node-01 etcd]$ ./etcdctl version
etcdctl version: 3.1.3
API version: 3.1

[root@node-01 etcd]$  ./etcdctl --endpoints=https://node-01.example.com:2379 --cert=/cfssl/member1.pem --key=/cfssl/member1-key.pem --cacert=/cfssl/ca.pem member list --write-out=proto
Error:  unsupported output format

**Comment by gyuho** [comment]
Right, it's not supported in master branch as well. Should we? /cc @heyitsanthony @xiang90

**Comment by heyitsanthony** [comment]
It's always been `protobuf`, not `proto`. The help string is wrong.
