### ISSUE TITLE
Feature: Encryption Wrapper 

### ISSUE THREAD

**Issue by lumjjb** [coreos/etcd#7542]
Our work on encryption wrappers
-------------------

Hi! We have been working on some encryption wrapping work on the `etcd/client`, in hopes of creating an easy way to enable encryption with minimal changes to an application. It serves as a simple wrapper without any key management mechanisms (as of now). 

We have worked on a simple wrapper for etcd `get/put` which seems similar to the wrapper idea mentioned in https://github.com/coreos/etcd/issues/7388. Our implementation doesn't require any changes to the etcd client, but could be made to be an option in etcd client. We would like to gather some feedback on whether what we've done would be helpful to the community and how we can approach putting it somewhere (i.e. whether it is something that should be added to the project or as a separate project). Details are as follows!

Our Implementation
-------------------
Our implementation is a simple client wrapper which takes in a `KeysAPI ` and outputs the same interface `KeysAPI`. And for v3, the `KV` corresponding interface. The keys/encryption routines are all on the client side (to ensure that compromise of the storage server will not result in data being decrypted).

As a result of this encryption model, the `Txn` feature doesn't work (since the server doesn't have the ability to decrypt secrets). Currently the implementation doesn't require any code changes to etcd. However, it could be added as an option. 

An example of the interface is the following (for etcdv2 client). We have created an interface `EncConfig` to detail the encryption/decryption process as specified by the user. 

```
type EncConfig interface {
    Encrypt([]byte) ([]byte, error)
    Decrypt([]byte) ([]byte, error)
}
```

The user can then make a secure `KeysAPI` by doing the following:

```
encConfig, err := encconfig.NewAESCBCEncConfig([]byte("this is the key!"))
if err != nil {
    log.Fatal(err)
}

kapi, err = skeysapi.NewSecureKeysAPI(kapi, encConfig)
if err != nil {
    log.Fatal(err)
}
```

All subsequent calls to use this `KeysAPI`will be encrypted before sending to the server/decrypted before consuming by the code.

The Interface
-------------------
More concretely, the interface currently looks like:

v2
```
func NewSecureKeysAPI(k etcd.KeysAPI, encConf encconfig.EncConfig) (etcd.KeysAPI, error)
```

v3 - additional interface for Op*s for Do method.
```
type SecureKV interface {
    etcd.KV
    OpGet(key string, opts ...etcd.OpOption) etcd.Op
    OpDelete(key string, opts ...etcd.OpOption) etcd.Op
    OpPut(key, val string, opts ...etcd.OpOption) (etcd.Op, error)
    OpValue(val string) (string, error)
}


type SecureKV
    func NewSecureKeysAPI(k etcd.KV, encConf encconfig.EncConfig) (SecureKV, error)
    func SecureClient(c *etcd.Client, encConf encconfig.EncConfig) (SecureKV, error)
```

Future extensions
-------------------
On top of the encryption, we could extend the wrapper to sign the values. Key encryption could also be done.

**Comment by heyitsanthony** [comment]
@lumjjb excellent stuff. 

> the Txn feature doesn't work (since the server doesn't have the ability to decrypt secrets).

Would this only need changes to the Compare interfaces to encrypt values? Or is there something else missing?

> how we can approach putting it somewhere (i.e. whether it is something that should be added to the project or as a separate project

If it's a separate project, a link can be added to Documentation/integrations.md immediately. Official support for an encryption layer in the etcd client would be more difficult (e.g., the v2 client isn't taking new features).

One comment on the interface:
```
    OpGet(key string, opts ...etcd.OpOption) etcd.Op
    OpDelete(key string, opts ...etcd.OpOption) etcd.Op
    OpPut(key, val string, opts ...etcd.OpOption) (etcd.Op, error)
```

`Op` is going to have functions to make them mutable / less opaque in general. The reasoning being that there may be transforms on the Ops that need to know the entire txn and therefore can only be done at Commit time. This is a good workaround until then, though.

**Comment by lumjjb** [comment]
Thanks @heyitsanthony for the awesome pointers and feedback! While we continue this conversation, let me work on getting this code public.

>`Op` is going to have functions to make them mutable / less opaque in general. The reasoning being that there may be transforms on the Ops that need to know the entire txn and therefore can only be done at Commit time. This is a good workaround until then, though.

This is great news :). I actually struggled with trying to make something clean with Ops, but with mutability, this may just clean itself up, and we can do the transformation once the entire transaction has been constructed.

>If it's a separate project, a link can be added to Documentation/integrations.md immediately. Official support for an encryption layer in the etcd client would be more difficult (e.g., the v2 client isn't taking new features).

It's not a public project right now, I would need to talk to my team first about releasing this publicly. Curious about the freeze on v2 features. Are all new features going forward going to be only implemented in the v3 client?

>Would this only need changes to the Compare interfaces to encrypt values? Or is there something else missing?

Unfortunately, I think it may be more to it - or I may be overthinking it. 

When I was making this I looked at it from the perspective of a particular encryption model - Where only the client holds the key and the Server processes the transaction without additional client intervention. Maybe there are other use-cases that I didn't consider, but my thoughts is that there is a crypto restriction that makes this difficult. I'm going to brain-dump my thoughts on this, and hope it is well articulated.

I convinced myself that with this model it was infeasible and was thinking that with an encryption layer, only simple get/put operations would be permitted (modulo simple transaction - where technically I could unroll the transaction and inspect if they would be do-able without this restriction).

Assumptions:
- Only the client has the encryption keys
- Transactions are carried out purely on server side without any communication to the client, but correct me if this is a bad assumption.

Given an operation: `Compare(LessThan, Get("foo"), GET("bar"))`

Values of foo and bar are encrypted and thus, the server is not able to make any comparison of the encrypted data. 

For the server to carry out comparisons on encrypted data, there are 2 options that I've evaluated:
1) Homomorphic Encryption, which is pretty impractical right now 
2) Allow equality comparators by ensuring the the same plain text will result in the same ciphertext always - this however, opens it up to "Chosen-Plaintext Attacks". 
I.e. In DES, encryption of plaintext would result in same ciphertext `encrypt(foo) = j8ie, encrypt(foo) = j8ie` 
whereas in AES, encryption of plaintext would result in different ciphertext  `encrypt(foo) = (iv1,i28e), encrypt(foo) = (iv2,ow92)` 

_Potential Alternative_ The alternative would have to be somehow making a transaction interactive between the server and client (where the server requests the client to evaluate an expression).

**Comment by xiang90** [comment]
> It's not a public project right now, I would need to talk to my team first about releasing this publicly. 

If you can talk about it publicly, do you mind adding it to https://github.com/coreos/etcd/blob/master/Documentation/production-users.md? Thanks!

**Comment by heyitsanthony** [comment]
@lumjjb OK, I see what you mean about the values. I was thinking (2) would be OK for equality tests, but as you point out, IV's/nonces wreck it (and are generally preferable).

The encryption client could just reject any txn's that have comparisons on values before even sending off to the server if it's nonced. Most txn code only cares about revisions / versions, so dropping value comparisons probably won't be too serious in terms of system usability.

**Comment by heyitsanthony** [comment]
Op wrapping support added in f9b6066dd6be7212c5857db8b582c00dad7e5c82 so custom encryption wrappers should be easier to write. Please submit a PR to update Documentation/integrations.md or Documentation/production-users.md if interested in officially documenting this in the etcd repo.

Closing since I don't think there's much more to do here, but feel free to reopen. Thanks!

**Comment by lumjjb** [comment]
@heyitsanthony I managed to get my code up! (hopefully it will be clearer what I'm trying to do) https://github.com/lumjjb/etcd/tree/enc_wrapper/clientwrap/encwrapper

Main modules are `skeysapi`/`skeysapiv3`/`encconfig`. 

As you will notice it doesn't actually touch any of the etcd code at all, so I'm not sure if this is valuable in terms of adding it to the code base, or as an independent project. Part of the project includes some crypto objects that user can choose from. 

I can also update my v3 wrapper code so that it uses the new `Op` wrapping that you added.

**Comment by heyitsanthony** [comment]
@lumjjb it would probably work better as an independent project for the time being since there's a maintenance burden to including it in the main repo...

Add a link to `Documentation/integrations.md` and submit a PR? Thanks!

**Comment by lumjjb** [comment]
Will do! Thanks @heyitsanthony !
