### ISSUE TITLE
Health Check Error Messages for Peers

### ISSUE THREAD

**Issue by spirrello** [coreos/etcd#7544]
Hi,

I'm seeing the following messages on my Etcd cluster (3 nodes) and can't seem to figure out the root cause.  Can someone please point me in the right direction?  I'm running Etcd on Centos 7.2. 

**Error messages:**

Mar 20 20:59:33 machine01 etcd[21601]: health check for peer 12963b0892211347 could not connect: x509: certificate is valid for machine02.mydomain.net, not machine02
Mar 20 20:59:33 machine01 etcd[21601]: health check for peer 54991278e8cab08f could not connect: x509: certificate is valid for machine03.mydomain.net, not machine03

**Etcd vesion:**
etcd Version: 3.1.0
Git SHA: 8ba2897
Go Version: go1.7.4
Go OS/Arch: linux/amd64

**Service config file:**
All other machines are running the exact corresponding configuration with their respective machine name.  For example, machine02.mydomain.net, machine03.mydomain.net.

[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
ExecStart=/usr/bin/etcd --name machine01.mydomain.net \
  --cert-file=/opt/my/certs/machine01.mydomain.net.pem \
  --key-file=/opt/my/certs/machine01.mydomain.net.key \
  --peer-cert-file=/opt/my/certs/machine01.mydomain.net.pem \
  --peer-key-file=/opt/my/certs/machine01.mydomain.net.key \
  --trusted-ca-file=/opt/my/certs/RootCA_2026.crt \
  --initial-advertise-peer-urls https://machine01.mydomain.net:2380 \
  --listen-peer-urls https://machine01.mydomain.net:2380 \
  --listen-client-urls https://machine01.mydomain.net:2379,http://127.0.0.1:2379 \
  --advertise-client-urls https://machine01.mydomain.net:2379 \
  --initial-cluster-token etcd-cluster-0 \
  --initial-cluster machine01.mydomain.net=https://machine01.mydomain.net:2380,machine2.mydomain.net=https://machine2.mydomain.net:2380,machine3.mydomain.net=https://machine3.mydomain.net:2380 \
  --initial-cluster-state new \
  --data-dir=/var/lib/etcd
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by gyuho** [comment]
Where's the error message?

**Comment by spirrello** [comment]
Error messages:

Mar 20 20:59:33 machine01 etcd[21601]: health check for peer 12963b0892211347 could not connect: x509: certificate is valid for machine02.mydomain.net, not machine02
Mar 20 20:59:33 machine01 etcd[21601]: health check for peer 54991278e8cab08f could not connect: x509: certificate is valid for machine03.mydomain.net, not machine03

**Comment by gyuho** [comment]
> x509: certificate is valid for machine02.mydomain.net, not machine02

Your cert configuration seems wrong? Did you set the correct host for your certs?

**Comment by spirrello** [comment]
When I generated the CSR for each certificate I used the corresponding host names for each machine.

machine01.mydomain.net
machine02.mydomain.net
machine03.mydomain.net

**Comment by gyuho** [comment]
How do you generate your certs? Did it work before?

Do something like

```
openssl x509 -in YOUR-CA.pem -text -noout
openssl x509 -in YOUR-PUB-KEY.pem -text -noout
```

?

**Comment by spirrello** [comment]
It's actually never worked.  I'm going to retry generating the certs and see what happens.  I'll post my results.

Thanks for the quick response.

**Comment by gyuho** [comment]
If you use `cfssl`, you might find this http://play.etcd.io/install helpful.

**Comment by spirrello** [comment]
Thanks!  I used that instead and it worked fine.  I do eventually need to circle back in using private certs and our internal CA.
