### ISSUE TITLE
data race at 27550b2.../clientv3/concurrency/election.go#L60

### ISSUE THREAD

**Issue by darasion** [coreos/etcd#7547]
data race at `https://github.com/coreos/etcd/blob/27550b229aaedf4b46431919c865918264bb50a3/clientv3/concurrency/election.go#L60`
`e.leaderKey, e.leaderRev, e.leaderSession = k, resp.Header.Revision, s`
if multiple goroutine elect.Campaign() call.

my test code is something like this:
```
elect := conc.NewElection(sess, "prefix")
go elect.Campaign(ctx, "foo")
go elect.Campaign(ctx, "foo")
```

with -race flag, it will panic:
```
==================
WARNING: DATA RACE
Write at 0x00c420130770 by goroutine 194:
  github.com/coreos/etcd/clientv3/concurrency.(*Election).Campaign()
      /.../src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:60 +0x828
...

Previous write at 0x00c420130770 by goroutine 193:
  github.com/coreos/etcd/clientv3/concurrency.(*Election).Campaign()
      /.../src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/concurrency/election.go:60 +0x828
...
```

**Comment by heyitsanthony** [comment]
It seems like it should race here since this kind of usage looks risky (broken ordering, unnecessary campaigning) so `-race` should complain about it. What's the intent/expected outcome from doing concurrent campaigns on the same election?

**Comment by darasion** [comment]
@heyitsanthony 
thanks for reply, i am just fix that by creating new election object for each goroutine, but i am still not sure about how to use the Election. is there any examples for demo?

**Comment by xiang90** [comment]
@darasion Use different session for different go routines/processes.
