### ISSUE TITLE
after  l migrating data, l must get key add a '/' 

### ISSUE THREAD

**Issue by huangsanye** [coreos/etcd#7548]
for example 
  v2 : get abc 
 v3: get /abc

**Comment by xiang90** [comment]
that is correct. even in v2, the key is `/abc`. v2 will auto fill in `/` for you. v3 will not.

**Comment by xiang90** [comment]
If you dislike this, you can write your own transformer func to do the migration.

**Comment by huangsanye** [comment]
yes  l have write a new migrate,thanks.
