### ISSUE TITLE
unavailable or misconfigured

### ISSUE THREAD

**Issue by jimmyliuacs** [coreos/etcd#7550]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by gyuho** [comment]
What's the issue? Please provide more details.

**Comment by xiang90** [comment]
I am closing this since it is not helpful without any detailed information. Please create a new one with necessary information mentioned in the issue guide.
