### ISSUE TITLE
"auto-compaction-retention" param from YAML config does not work?

### ISSUE THREAD

**Issue by mwf** [coreos/etcd#7555]
@xiang90 could you please also have a look at auto-compaction param from **YAML config**?

We set `auto-compaction-retention: 24`, but we don't observe compaction messages in logs.

I've tried auto-compaction in etcd docker image (the same 3.0.15 version), with command-line parameter - and it worked OK. There were messages:
```
2017-03-16 08:31:44.457840 N | etcdserver: Starting auto-compaction at revision 1689
2017-03-16 08:31:44.489054 I | mvcc: store.index: compact 1689
2017-03-16 08:31:44.490835 W | etcdserver: apply entries took too long [23.181202ms for 1 entries]
2017-03-16 08:31:44.490949 W | etcdserver: avoid queries with large range/delete range!
2017-03-16 08:31:44.492409 I | mvcc: finished scheduled compaction at 1689 (took 1.108457ms)
2017-03-16 08:31:44.492652 N | etcdserver: Finished auto-compaction at revision 1689
```
And no such messages at production server :(
Just in case when you're doing `compact` manually.

Have you ever faced it?

etcd server 3.0.15

**Comment by gyuho** [comment]
`auto-compaction-retention: 24` means it will run once a day. Did you search the full logs after 24-hour and still no `etcdserver: Starting auto-compaction at revision`?

**Comment by mwf** [comment]
@gyuho sure, I searched all the logs.

I've just started a second etcd daemon with yaml config and `auto-compaction-retention` of 1 hour. I'll ping you in an hour with the results :)

**Comment by mwf** [comment]
@gyuho I was on my way home )

Yeap, it seems etcd 3.0.15 does not read `auto-compaction-retention` from YAML.
No compaction appeared!

**Comment by gyuho** [comment]
That's strange. I just double-checked and `auto-compaction-retention` is being correctly parsed into etcd config, though.

Let me investigate more.

**Comment by mwf** [comment]
Maybe it's OK in 3.1+? I did not check it, just 3.0.15, as we have it installed.

**Comment by gyuho** [comment]
@mwf Oh yeah good catch. It's not JSON-tagged in 3.0 https://github.com/coreos/etcd/blob/release-3.0/etcdmain/config.go#L145.

It will work in 3.1+

**Comment by mwf** [comment]
Oh, OK then, thanks. I will push our Infra guys to update the server.
