### ISSUE TITLE
Invalid Authorization only though clientv3

### ISSUE THREAD

**Issue by tgrosinger** [coreos/etcd#7557]
# Versions

etcd Version: 3.1.3
etcd Version SHA: 21fdcc6

client Version SHA: 350d0cd211fd61f7fd0fce667e262aa0fe513441

# Repro Steps

## From etcd server

Create a new user and role, enable auth:

```sh
etcdctl user add "root:${rootpw}"
etcdctl user add "myuser:mysecret"
etcdctl role add myrole
etcdctl role grant myrole -path '/test-path/*' -readwrite
etcdctl user grant myuser -roles myrole
etcdctl auth enable
```

# From a client

Try making some curl requests:

```sh
$ curl -X GET -H "Authorization: Basic <omitted>" "http://etcd-server:2379/v2/keys/test-path/something"                                     
{"action":"get","node":{"key":"/test-path/something","value":"123","modifiedIndex":26,"createdIndex":26}}
```

Try making requests from Go clientv3:

```go
package main

import (
	"time"

	client "github.com/coreos/etcd/clientv3"
)

// Connect initiates a connection to the etcd server.
func Connect(hostports ...string) {
	return client.New(client.Config{
		Endpoints:   hostports,
		DialTimeout: 5 * time.Second,
		Username:    "myuser",
		Password:    "mysecret",
	})
}
```

Results in errors such as `etcdserver: authentication failed, invalid user ID or password` from the client and `etcdserver: invalid authentication request to user myuser was issued` from the server.

I just can't spot what I am doing wrong, and why it works in one place but not the other. Thank you.

**Comment by fanminshi** [comment]
Taking a look.

**Comment by tgrosinger** [comment]
> Taking a look.

Thank you, let me know if there is more information I can provide that would be useful.

**Comment by fanminshi** [comment]
@tgrosinger I encounter the same issue when creating role and user using etcdctl v2 api(not sure why still investigating). However, I don't encounter the issue when creating auth using etcdcetl v3 api.

```
# Use V3 api
ETCDCTL_API=3 bin/etcdctl user add root:123
ETCDCTL_API=3 bin/etcdctl user add myuser:123
ETCDCTL_API=3 bin/etcdctl role add myrole
ETCDCTL_API=3 bin/etcdctl role grant-permission myrole --prefix=true readwrite '/test-path/'
ETCDCTL_API=3 bin/etcdctl user grant myuser myrole
ETCDCTL_API=3 bin/etcdctl auth enable
```

```go
// Works
func TestAuthRole(t *testing.T) {
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"127.0.0.1:2379"},
		DialTimeout: 5 * time.Second,
		Username:    "myuser",
		Password:    "123",
	})
	if err != nil {
		t.Fatal(err)
	}
	resp, err := cli.Put(context.TODO(), "/test-path/stuff", "bar")
	if err != nil {
		t.Fatal(err)
	}
	fmt.Println(resp)
	rresp, rerr := cli.Get(context.TODO(), "/test-path/stuff")
	if err != nil {
		t.Fatal(rerr)
	}
	fmt.Println(rresp)
}
```
```
// Console Output

&{cluster_id:14841639068965178418 member_id:10276657743932975437 revision:4 raft_term:2 <nil>}
&{cluster_id:14841639068965178418 member_id:10276657743932975437 revision:4 raft_term:2  [key:"/test-path/stuff" create_revision:3 mod_revision:4 version:2 value:"bar" ] false 1}
```

Is there a reason not using etcdctl v3 api? By default if you don't set ETCDCTL_API env variable, the etcdctl uses v2 api, fyi.

**Comment by heyitsanthony** [comment]
v2 and v3 auth are independent like the v2 and v3 data stores. v2 auth only works for v2 api requests and v3 auth only works for v3 api requests.

**Comment by tgrosinger** [comment]
Oh wow, I had no idea that the auth was separate across versions. Maybe it's in the documentation and I just missed it, but it should probably be highlighted a little more.

Thank you very much @heyitsanthony and @fanminshi. I will give this a try tomorrow morning and close the issue if it solves the problem.
