### ISSUE TITLE
While binding socket to 'localhost' it's always resolved by DNS servers only

### ISSUE THREAD

**Issue by artem-panchenko** [coreos/etcd#7559]
By default etcd tries to use **localhost** address for different endpoints, for example:

https://github.com/coreos/etcd/blob/5015480e0c385e7fd9aa8825c26f18c6eba17395/embed/config.go#L44-L45

Before binding a socket it needs to be converted to an IP address, so resolving is always performed. And when official docker image **quay.io/coreos/etcd** is used, the resolving is made using **DNS queries** to name servers from resolv.conf **only**, while **entries from /etc/hosts file are completely ignored**. It happens because **alpine** base image is used and it **lacks of /etc/nsswitch.conf** file, so Golang resolving function (if I'm not mistaken) is not able to determine proper resolving order.

That means if your DNS server resolves 'localhost' to something different than '127.0.0.1', then etcd fails to start (at least with default settings):

> $ docker run -it --rm --dns 172.18.247.8 --dns 8.8.8.8 --dns-search maas --entrypoint etcd quay.io/coreos/etcd:latest
> 2017-03-21 15:47:03.006894 I | etcdmain: etcd Version: 3.1.3
> 2017-03-21 15:47:03.006947 I | etcdmain: Git SHA: 21fdcc6
> 2017-03-21 15:47:03.006951 I | etcdmain: Go Version: go1.7.5
> 2017-03-21 15:47:03.006955 I | etcdmain: Go OS/Arch: linux/amd64
> 2017-03-21 15:47:03.006960 I | etcdmain: setting maximum number of CPUs to 12, total number of available CPUs is 12
> 2017-03-21 15:47:03.006968 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
> 2017-03-21 15:47:03.211167 C | etcdmain: listen tcp 172.18.247.8:2380: bind: cannot assign requested address

In the example above DNS server 172.18.247.8 resolves localhost.maas to itself (172.18.247.8) and therefore socket binding fails.

**Comment by gyuho** [comment]
@artem-panchenko Could you help me verify this part? I tried your patch and confirm that it works well. I just want to confirm that it fixes the issue:

> 2017-03-21 15:47:03.211167 C | etcdmain: listen tcp 172.18.247.8:2380: bind: cannot assign requested address

`docker run --rm --dns 172.18.247.8 --dns 8.8.8.8 --dns-search mass quay.io/coreos/etcd:latest /usr/local/bin/etcd` runs fine without such error.

How's your DNS server set up to get this?

Thanks.

**Comment by artem-panchenko** [comment]
@gyuho Yes, I tested the patch and confirm that it fixes this issue.

> How's your DNS server set up to get this?

As far as I know it's set up by our MAAS instance automatically and it has localhost.maas zone:

`$ dig +short @172.18.247.8 localhost.maas`
`172.18.247.8`

**Comment by artem-panchenko** [comment]
@gyuho here is how you can reproduce the issue and verify the patch

> docker run -d --name myDNS andyshinn/dnsmasq -d --address='/localhost.maas/5.5.5.5'
> myDnsIP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' myDNS)
> dig +short @"${myDnsIP}" localhost.maas # check it returns 5.5.5.5
> docker run --rm --dns "${myDnsIP}" --dns 8.8.8.8 --dns-search maas --entrypoint etcd quay.io/coreos/etcd:latest
> docker rm -f myDNS
