### ISSUE TITLE
gRPC proxy doesn't support SRV discovery

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7562]
gRPC proxy doesn't support SRV discovery. This should be supported to be consistent with all other interface configs.

**Comment by raoofm** [comment]
@xiang90 ? Will this be supported?

**Comment by xiang90** [comment]
@raoofm I am fine with supporting SRV discovery. But we do not have the bandwidth to add this feature for the next couple of weeks (or month?!). If you can contribute, it would be great.

**Comment by raoofm** [comment]
@xiang90 I'm not into go. Can you give me direction to give it a try?

**Comment by raoofm** [comment]
@xiang90 @fanminshi thanks much
