### ISSUE TITLE
How to make one of the nodes try not to become leader

### ISSUE THREAD

**Issue by ckeyer** [coreos/etcd#7566]
I have a cluster in two locations，A(two nodes)+B(one node) 
How to make the leader as much as possible in ‘A’

**Comment by xiang90** [comment]
We do not support hard limit. But there is a hacky way to do it. You can set the election timeout for A to x seconds and the election timeout for B to be 2*x+1.

**Comment by ckeyer** [comment]
Thanks, @xiang90
