### ISSUE TITLE
Explicitely resolve IP addresses from DNS name in client library

### ISSUE THREAD

**Issue by wrouesnel** [coreos/etcd#7567]
The etcd client library for Go uses the built-in http client, which by default only tries the first address in the list of IPs that is returned to it.

As a result if an etcd cluster is presented under a common A record to the client, it is likely to only try the first, possibly broken etcd host and then return failure - and then because of a lack of hosts in the list, fail the entire request.

It would be better if each supplied hostname was resolved to it's explicit list of IPs, and each IP retried on failure first (or I suppose shunted to the end of the list to be tried as a last resort).

**Comment by heyitsanthony** [comment]
@wrouesnel is this for the v2 client or the v3 client?

**Comment by wrouesnel** [comment]
v2 client has the immediate problem, I should check if v3 resolves it or not.

**Comment by xiang90** [comment]
@wrouesnel 

here is the issue in go: https://go-review.googlesource.com/c/go/+/34914.

i do not think etcd/client want to be in the business of determining how to resolve DNS. If you do care about this, you should have something resolve the DNS to IP addresses first, and supply the resolved IP addresses into etcd/client. Then etcd can do what you want inside its client library.
