### ISSUE TITLE
TestNetworkPartition5MembersLeaderInMajority: unexpected leader change

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7587]
https://semaphoreci.com/coreos/etcd/branches/master/builds/1704

```
--- FAIL: TestNetworkPartition5MembersLeaderInMajority (15.71s)
network_partition_test.go:86: unexpected leader change from dd28efa683b366fa, got 8740e8022ce66ee0
```

**Comment by gyuho** [comment]
Think it's possible to have another leader election in majority group while waiting here https://github.com/coreos/etcd/blob/master/integration/network_partition_test.go#L85, given that it took over 10 seconds to get this failure

```go
	// leader must be hold in majority
	leadIndex2 := clus.waitLeader(t, majorityMembers)
	leadID, leadID2 := clus.Members[leadIndex].s.ID(), majorityMembers[leadIndex2].s.ID()
	if leadID != leadID2 {
		t.Fatalf("unexpected leader change from %s, got %s", leadID, leadID2)
	}
```

Should we just make sure that `leadID2` belong to majority?

**Comment by heyitsanthony** [comment]
I feel like that weakens the test. If I partition off a minority from the cluster and then have it join back, the leader shouldn't change so long as the majority can sustain its heartbeats.

It can ignore the check if the term is larger than expected, indicating additional elections, but it probably should t.Log that it did. My only concern with that approach is etcd may get a regression where it triggers elections when it partitions and CI will never flag it as an error.

The other option is to retry the test once or twice if there's an election in between, the idea being that if it's frequent enough to be noticeable, the test will still catch it.
