### ISSUE TITLE
raft memory leak

### ISSUE THREAD

**Issue by yanlinly** [coreos/etcd#7606]
we found etcd leader memory raise。 

(pprof) top 10
60.21GB of 64.27GB total (93.67%)
Dropped 928 nodes (cum <= 0.32GB)
Showing top 10 nodes out of 58 (cum >= 0.37GB)
      flat  flat%   sum%        cum   cum%
   47.87GB 74.47% 74.47%    48.09GB 74.82%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.stepLeader
    5.11GB  7.95% 82.42%     5.68GB  8.84%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft/raftpb.(*Message).Unmarshal
    2.61GB  4.07% 86.49%     2.61GB  4.07%  github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*node).ReadIndex

(pprof) disasm  stepLeader
         .    61.55MB     8effc5: CALL github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/raft.(*raft).bcastHeartbeatWithCtx(SB)	
         .          .     8effca: MOVQ 0x9d0(SP), BP	
         .          .     8effd2: ADDQ $0x9d8, SP	
         .          .     8effd9: RET	
         .          .     8effda: CALL runtime.panicindex(SB)	
         .          .     8effdf: UD2	
         .          .     8effe1: MOVQ 0x1d0(SP), AX	
         .          .     8effe9: MOVQ AX, 0x2d8(SP)	
         .          .     8efff1: MOVQ 0x160(SP), CX	
         .          .     8efff9: MOVQ CX, 0x2e0(SP)	
         .          .     8f0001: LEAQ 0x41c2b8(IP), DX	
         .          .     8f0008: MOVQ DX, 0(SP)	
         .          .     8f000c: MOVQ $0x0, 0x8(SP)	
         .          .     8f0015: MOVQ $0x0, 0x10(SP)	
         .          .     8f001e: MOVQ $0x0, 0x18(SP)	
    4.57GB     4.57GB     8f0027: CALL runtime.makemap(SB)	
         .          .     8f002c: MOVQ 0x20(SP), AX	
         .          .     8f0031: MOVQ AX, 0x218(SP)	
         .          .     8f0039: LEAQ 0x47fb60(IP), CX	
         .          .     8f0040: MOVQ CX, 0(SP)	
   30.98GB    30.98GB     8f0044: CALL runtime.newobject(SB)	

## so  we doubt this Message without gc。 only leader have this problem, when leader become slow, then leader change. the new leader have same problem.

// sendHeartbeat sends an empty MsgApp
func (r *raft) sendHeartbeat(to uint64, ctx []byte) {
	// Attach the commit as min(to.matched, r.committed).
	// When the leader sends out heartbeat message,
	// the receiver(follower) might not be matched with the leader
	// or it might not have all the committed entries.
	// The leader MUST NOT forward the follower's commit to
	// an unmatched index.
	commit := min(r.prs[to].Match, r.raftLog.committed)
	m := pb.Message{
		To:      to,
		Type:    pb.MsgHeartbeat,
		Commit:  commit,
		Context: ctx,
	}

	r.send(m)
}

**Comment by fanminshi** [comment]
The mem leak is fixed via #7574.

**Comment by yanlinly** [comment]
thx fanminshi . 
![image](https://cloud.githubusercontent.com/assets/17695352/24337052/0911db2a-12cb-11e7-8b2a-24e0b9931e44.png)

**Comment by fanminshi** [comment]
Np
