### ISSUE TITLE
Question: Best practices for automating compaction / defrag

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#7607]
Reading through: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md

Looking at compaction: 
> Since etcd keeps an exact history of its keyspace, this history should be periodically compacted to avoid performance degradation and eventual storage space exhaustion

What metrics should we be using to determine when compaction is necessary or at the very least a good idea?

> After compacting the keyspace, the backend database may exhibit internal fragmentation. Any internal fragmentation is space that is free to use by the backend but still consumes storage space. The process of defragmentation releases this storage space back to the file system. Defragmentation is issued on a per-member so that cluster-wide latency spikes may be avoided

What metrics should be used to monitor fragmentation?  Initially I assumed that monitoring HeapAlloc and HeapInuse would get me close, but seems I have mistaken.

Any thoughts or advise?

Thanks in advance
.

**Comment by xiang90** [comment]
> What metrics should we be using to determine when compaction is necessary or at the very least a good idea?

It depends on your application. If your application is OK with 1hr duration, do 1hr. The shorter duration the better. The limit factor is the total db size though, do not let it grow more than 2GB if you use a normal cloud machine.

> What metrics should be used to monitor fragmentation?

This is actually about disk fragmentation. But if you do not suddenly remove a lot of keys and want to reclaim the disk space immediately, you do not need to defrag.

**Comment by davissp14** [comment]
I went ahead and ran a few benchmarks to see if I could get a better understanding of what's going on.

After seeding some data, I went ahead and ran a compact / defrag.  I know you mentioned the defrag is a disk fragmentation thing, but it also seems to reclaim the cache along with it.
![screenshot from 2017-03-26 18-58-20](https://cloud.githubusercontent.com/assets/423038/24355376/4c131ab6-12bb-11e7-8520-403a3442bc34.png)

Normally I wouldn't really care about the cache as it should be freed upon memory pressure, however, in the benchmarks we are seeing quite a few failcnts starting at the time the cache fills up.
![screenshot from 2017-03-27 07-10-25](https://cloud.githubusercontent.com/assets/423038/24355726/9e35dd50-12bc-11e7-960d-914d1bc285ff.png)

Failcnts associated with the above benchmark.
![screenshot from 2017-03-27 07-10-53](https://cloud.githubusercontent.com/assets/423038/24355729/a1349190-12bc-11e7-99b5-5dd6283d95d1.png)

It appears we are seeing a negative performance impact due to the aggressive caching.  It also doesn't seem like constantly defragging is a great solution to this problem. 

Any thoughts?

**Comment by xiang90** [comment]
> It appears we are seeing a negative performance impact due to the aggressive caching. It also doesn't seem like constantly defragging is a great solution to this problem.

Can you share the benchmark result?

**Comment by davissp14** [comment]
![screenshot from 2017-03-27 10-43-38](https://cloud.githubusercontent.com/assets/423038/24365356/4a4322a6-12db-11e7-895c-6c68fd2cd561.png)

**Comment by xiang90** [comment]
How did you figure out the cache size has an impact over the benchmark result? I want to see a bench perf over cache size graph. Also note that the more keys you put into etcd the less throughput you might get if you run etcd on slow hdd. The level of btree grows so more io will be needed.

**Comment by davissp14** [comment]
I guess I should clear clarify.  I am less worried about the size of the cache and more worried about how the frequent cache evictions affect response times. The results below are from a cluster that's been allocated just enough memory to not have to force cache evictions.  I can work on creating a better comparison, but may take a bit due to other obligations.  
  
![screenshot from 2017-03-27 12-26-28](https://cloud.githubusercontent.com/assets/423038/24374517/c814f578-12fa-11e7-9e12-dcbd31f4fc72.png)

**Comment by xiang90** [comment]
@davissp14 

The avg latency is very high for 1.5k throughput. I am more interested in the comparison. I want to see the bad impact of cache. The evicted memory should on the old tree node. If you do seq write, the tree nodes should be all in memory (xMB should be far than enough), I am surprised it has an observable impact.

**Comment by gyuho** [comment]
We will document how to monitor this in https://github.com/coreos/etcd/issues/9438.

Let's move this discussion to https://github.com/coreos/etcd/issues/9438.

**Comment by regardfs** [comment]
> > What metrics should be used to monitor fragmentation?
> 
> This is actually about disk fragmentation. But if you do not suddenly remove a lot of keys and want to reclaim the disk space immediately, you do not need to defrag.
@xiang90 That just means no fragmentation will not influence the performance of etcd cluster but only no more disk space freed?

**Comment by regardfs** [comment]
@gyuho，hi，What will happen if no defrag proceed, Only no free for disk space? Does it influence the performance of  etcd cluster?
