### ISSUE TITLE
etcd v3  https add member failed, your document is wrong?

### ISSUE THREAD

**Issue by strugglingyouth** [coreos/etcd#7608]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

as follow doc:

https://coreos.com/etcd/docs/latest/v2/members_api.html

$ etcdctl version
etcdctl version: 3.1.3
API version: 3.1

I have used https and want add a member.

$ etcdctl member add node3  https://10.89.114.29:2380
Error:  member name not provided.

What is the reason?

In addition, I would like to make a proposal, whether the command line to support a parameter -vv=number, similar to kubectl, in order to facilitate our troubleshooting , Thanks.

**Comment by xiang90** [comment]
@strugglingyouth The doc you referred is HTTP API not etcdctl. Please check etcdctl doc: https://github.com/coreos/etcd/blob/master/etcdctl/README.md#member-add-membername-options
