### ISSUE TITLE
migrate from etcd2 to etcd3 on ContainerOS Alpha

### ISSUE THREAD

**Issue by kfirufk** [coreos/etcd#7616]
Hi :)

I have Container Linux by CoreOS 1353.1.0 installed on my cluster.
it has etcd2 installed.

I wanna play a bit with kubernetes 1.6, and I noticed that it's default storage backend is etcd3, yes I know I can change it to etcd2 but I don't wanna :)

first of all.. since etcd3 is already stable, why it's not supported in latest ContainerOS Alpha ?

what would be the recommended method to install etcd3 on my container os ?

should I use https://github.com/coreos/etcd-operator and install it directly on kubernetes? or any other way?

thank you!

**Comment by gyuho** [comment]
It's supported via `etcd-member.service`.

Please see https://coreos.com/etcd/docs/latest/getting-started-with-etcd.html.

I recommend running etcd with our official `etcd-member.service`.
