### ISSUE TITLE
could not connect: dial tcp and getsockopt: no route to host messages

### ISSUE THREAD

**Issue by spirrello** [coreos/etcd#7618]
Hi,

I'm seeing some odd messages in the logs of my leader node and members that see like there is a problem however I've added several key value pairs from the leader and from the other nodes without trouble.  Can you advise if this cosmetic or indicative of an underlying problem?

etcdctl --version
etcdctl version: 3.1.0
API version: 2

**Leader node is 10.172.9.135**

etcdctl \
  --ca-file=/opt/acme/certs/ca.pem \
  --cert-file=/opt/acme/certs/kubernetes.pem \
  --key-file=/opt/acme/certs/kubernetes-key.pem \
  cluster-health

member 5e76ef6b20c5170d is healthy: got healthy result from https://10.172.9.137:2379
member be698d5880ef1135 is healthy: got healthy result from https://10.172.9.136:2379
member c104354c8be8d1e3 is healthy: got healthy result from https://10.172.9.135:2379

Logs:

failed to dial 5e76ef6b20c5170d on stream MsgApp v2 (dial tcp 10.172.9.137:2380: getsockopt: connection refused)

**Other nodes**

etcdctl \
  --ca-file=/opt/acme/certs/ca.pem \
  --cert-file=/opt/acme/certs/kubernetes.pem \
  --key-file=/opt/acme/certs/kubernetes-key.pem \
  cluster-health

2017-03-28 12:43:53.224330 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
2017-03-28 12:43:53.227787 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
member 5e76ef6b20c5170d is healthy: got healthy result from https://10.172.9.137:2379
member be698d5880ef1135 is healthy: got healthy result from https://10.172.9.136:2379
failed to check the health of member c104354c8be8d1e3 on https://10.172.9.135:2379: Get https://10.172.9.135:2379/health: dial tcp 10.172.9.135:2379: getsockopt: no route to host
member c104354c8be8d1e3 is unreachable: [https://10.172.9.135:2379] are all unreachable

Logs

Mar 28 12:42:03 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:08 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:13 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:18 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:23 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:28 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:33 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:38 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:43 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: i/o timeout
Mar 28 12:42:48 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host
Mar 28 12:42:53 lvk8s02 etcd: health check for peer c104354c8be8d1e3 could not connect: dial tcp 10.172.9.135:2380: getsockopt: no route to host

If I try to open a connection on port 2379 from one of the nodes to the leader:

telnet 10.172.9.135:2379
telnet: 10.172.9.135:2379: Name or service not known
10.172.9.135:2379: Unknown host
[root@lvk8s02 ~]# telnet 10.172.9.135 2379
Trying 10.172.9.135...
telnet: connect to address 10.172.9.135: No route to host
[root@lvk8s02 ~]# ping 10.172.9.135
PING 10.172.9.135 (10.172.9.135) 56(84) bytes of data.
64 bytes from 10.172.9.135: icmp_seq=1 ttl=64 time=0.598 ms
64 bytes from 10.172.9.135: icmp_seq=2 ttl=64 time=0.850 ms
64 bytes from 10.172.9.135: icmp_seq=3 ttl=64 time=0.841 ms
64 bytes from 10.172.9.135: icmp_seq=4 ttl=64 time=0.786 ms
64 bytes from 10.172.9.135: icmp_seq=5 ttl=64 time=0.781 ms

**Systemd configuration**

[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
Type=notify
ExecStart=/usr/bin/etcd --name lvk8s01 \
  --cert-file=/opt/acme/certs/kubernetes.pem \
  --key-file=/opt/acme/certs/kubernetes-key.pem \
  --peer-cert-file=/opt/acme/certs/kubernetes.pem \
  --peer-key-file=/opt/acme/certs/kubernetes-key.pem \
  --trusted-ca-file=/opt/acme/certs/ca.pem \
  --peer-trusted-ca-file=/opt/acme/certs/ca.pem \
  --initial-advertise-peer-urls https://10.172.9.135:2380 \
  --listen-peer-urls https://10.172.9.135:2380 \
  --listen-client-urls https://10.172.9.135:2379,http://127.0.0.1:2379 \
  --advertise-client-urls https://10.172.9.135:2379 \
  --initial-cluster-token 8asdf!!dsfsdfII# \
  --initial-cluster lvk8s01=https://10.172.9.135:2380,lvk8s02=https://10.172.9.136:2380,lvk8s03=https://10.172.9.137:2380 \
  --initial-cluster-state new \
  --data-dir=/opt/etcd
NotifyAccess=all
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by xiang90** [comment]
Telnet does not even work, it cannot find host or route. This is not an etcd issue I am sure. You probably need to check the network configuration instead.

**Comment by heyitsanthony** [comment]
Looks like a network issue:
```
[root@lvk8s02 ~]# telnet 10.172.9.135 2379
Trying 10.172.9.135...
telnet: connect to address 10.172.9.135: No route to host
```

**Comment by spirrello** [comment]
You missed the part where I'm able to ping just fine.

[root@lvk8s02 ~]# ping 10.172.9.135
PING 10.172.9.135 (10.172.9.135) 56(84) bytes of data.
64 bytes from 10.172.9.135: icmp_seq=1 ttl=64 time=0.598 ms
64 bytes from 10.172.9.135: icmp_seq=2 ttl=64 time=0.850 ms
64 bytes from 10.172.9.135: icmp_seq=3 ttl=64 time=0.841 ms
64 bytes from 10.172.9.135: icmp_seq=4 ttl=64 time=0.786 ms
64 bytes from 10.172.9.135: icmp_seq=5 ttl=64 time=0.781 ms

**Comment by xiang90** [comment]
@spirrello Both ping and telnet should work. If telnet does not work, etcd wont work either. that is why i think this is a network issue.
