### ISSUE TITLE
clientv3: timeouts doesn't work with --user key

### ISSUE THREAD

**Issue by idonin** [coreos/etcd#7627]
etcdctl version: 3.1.2
API version: 3.1

Error:
When passing --user username:password on etcdctl command, timeount doesn't work at all

How to reproduce:
1. Stop etcd node
2. Run `ETCDCTL_API=3 etcdctl --user foo:bar get /`

What I see:
Hangs on. Permanent loop with this messages in strace
```
futex(0x1148ab0, FUTEX_WAIT, 0, NULL)   = 0
futex(0x1148ab0, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
epoll_wait(4, {}, 128, 0)               = 0` in strace
```

What expected:
Failing with `Error:  grpc: timed out when dialing` after timeout

Additional:
* With another clients like confd problem may exist, but not checked.
* Another commands like watch, put also affected

**Comment by heyitsanthony** [comment]
also broken on master
