### ISSUE TITLE
Suggestion: being more liberal on protobuf version allowed

### ISSUE THREAD

**Issue by akauppi** [coreos/etcd#7631]
I was trying to build `etcd` documentation, on macOS with HomeBrew.

```
$ brew install protobuf
$ protoc --version
libprotoc 3.2.0
```

Documents should be buildable with `scripts/genproto.sh -g`, but it demands protobuf 3.1.0:

```
# for now, be conservative about what version of protoc we expect
if ! [[ $(protoc --version) =~ "3.1.0" ]]; then
	echo "could not find protoc 3.1.0, is it installed + in PATH?"
	exit 255
fi
```

Would it be possible to also include 3.2.0 so that life would be easier for people who contribute on the repo, but don't want to go to special lengths in setting up their system. Homebrew does not seem to have 3.1.0 available.

```
$ brew switch protobuf 3.1.0
Error: protobuf does not have a version "3.1.0" in the Cellar.
Versions available: 3.2.0
```

**Comment by akauppi** [comment]
I changed the check in `scripts/genproto.sh` to allow 3.2.0, and things seem to build okay.

However, multiple generated files are different than their in-the-repo counterparts. This is probably the reason to keep to protobuf 3.1.0, in the first place?

- `Documentation/dev-guide/apispec/swagger/rpc.swagger.json`: white space changes, and added `format` fields.
- About 10 `*.pb.go` files changed slightly, like this

```
--- a/wal/walpb/record.pb.go
+++ b/wal/walpb/record.pb.go
@@ -506,7 +506,7 @@ func init() { proto.RegisterFile("record.proto", fileDescriptorRecord) }
 
 var fileDescriptorRecord = []byte{
        // 186 bytes of a gzipped FileDescriptorProto
-       0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x4d, 0xce,
+       0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4a, 0x4d, 0xce,
        0x2f, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4f, 0xcc, 0x29, 0x48, 0x92,
        0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x8b, 0xe8, 0x83, 0x58, 0x10, 0x49, 0x25, 0x3f, 0x2e, 0xb6,
        0x20, 0xb0, 0x62, 0x21, 0x09, 0x2e, 0x96, 0x92, 0xca, 0x82, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
```

**Comment by heyitsanthony** [comment]
@akauppi not surprised the output is different, but I doubt it would break anything. I don't think there's any reason avoid upgrading etcd to protoc 3.2.
