### ISSUE TITLE
etcd  cluster can not use  in docker 

### ISSUE THREAD

**Issue by luweijie007** [coreos/etcd#7635]
I run etcd cluster in docker. it just run etcd as  ./etcd in a docker container 
I use envrionment to config etcd. using docker inspect get env info as:
        "Env": [
            "SERVICE_ID=/root/store/etcd/dzh.etcd_3",
            "CM=tcp://10.15.208.147:10400",
            "ZK_LIST=10.15.107.245:2181,10.15.107.246:2181,10.15.107.71:2181",
            "INTERFACE=",
            "ETCD_ADVERTISE_CLIENT_URLS=http://10.15.208.147:2379",
            "ETCD_DEBUG=DEBUG",
            "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.15.208.147:2380",
            "ETCD_INITIAL_CLUSTER=codis-etcd1=http://10.15.144.29:2380,codis-etcd2=http://10.15.144.25:2380,codis-etcd3=http://10.15.208.147:2380",
            "ETCD_LISTEN_PEER_URLS=http://10.15.208.147:2380",
            "LOCALHOST=10.15.208.147",
            "POCCADDR=10.15.208.66:9900,10.15.209.181:9900,10.15.208.115:9900",
            "ETCD_INITIAL_CLUSTER_STATE=new",
            "ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-0",
            "ETCD_LISTEN_CLIENT_URLS=http://10.15.208.147:2379",
            "ETCD_NAME=codis-etcd3",
            "INSTALLTYPE=4",
            "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LD_LIBRARY_PATH=/usr/local/lib:",
            "imagename=etcd"
        ],
execute cmd:

ETCDCTL_API=3 /tmp/test-etcd/etcdctl --endpoints=10.15.208.147:2379 put a 1
Error:  context deadline exceeded

and use telnet can login to 10.15.208.147:2379

**Comment by heyitsanthony** [comment]
@luweijie007 Can the peers communicate with each other? What do the etcd server logs look like?

Does `curl -s http://10.15.208.147:2379/metrics` return a list of server metrics? Sometimes a `context deadline exceeded` error is caused by blackhole endpoints that accept connections but never send any responses.

**Comment by luweijie007** [comment]
I clear all data of etcd, and set config again ,and run cluster so working right.
I guess maybeen some configures has been seted wrong before
