### ISSUE TITLE
doc in pkg/idutil maybe ambiguous

### ISSUE THREAD

**Issue by ggaaooppeenngg** [coreos/etcd#7636]
In the doc it is said
// High order byte is memberID, next 5 bytes are from timestamp,
// and low order 2 bytes are 0s.

while I think in fact it is
// High order 2 bytes are from memberID, next 5 bytes are from timestamp,
// and low order one byte is a counter.

**Comment by heyitsanthony** [comment]
@ggaaooppeenngg  Yeah, the comments in the code are wrong.. Submit a PR if you'd like. If not, I can correct it. Thanks!
