### ISSUE TITLE
Number of total watches spike after split brain

### ISSUE THREAD

**Issue by cw9** [coreos/etcd#7638]
Hi guys,

I'm running an etcd cluster of 5 nodes on version 3.1.0, I've been running a daily "destroy" test case against the cluster which blocks inbound traffic on port 2379,2380 on all 5 nodes for 5 mins. 

The cluster would recover fine from the disaster, all watches will resume to get notifications, get/set will pass through(yay!), but sometimes the total number of watches spikes. 

For example:
Below is the metrics of etcd_debugging_mvcc_watcher_total from each nodes in the cluster, the graph is stacked, meaning the top line is actually the total value of 5 metrics and the gap between 2 lines are the real value for the metric.

![screenshot1](https://cloud.githubusercontent.com/assets/6710599/24569917/aa742fd6-1636-11e7-9122-3250619c5e9c.png)

Timeline:
14:00: "destroy" started, after 5 mins the cluster recovered but each node reported a way higher number of watchers than before.
15:25: I restarted etcd on etcd02, hoping to remove some obsolete watches that was created during/before the split brain, but the watches on it just got moved to other 4 nodes and there is no change in total number of watches, etcd02 also got 0 watches after its restart, no load balance happened during this process.
15:35: I restarted etcd on etcd04, again, no change in total watches, etcd04 got 0 watches after restart
15:40: I kicked off another "destroy" run, but this time the cluster recovered without seeing a spike on number of watches, it also did not rebalance the number of watches between nodes in the cluster.

I'm sorry I can't provide a graph with longer history because I only added metrics recently for the etcd clusters, but I'm running 2 etcd clusters, 1 with this daily test, 1 without, both running with similar amount of load but the cluster with daily test on definitely show a much higher number of watches than the other cluster.

Questions:
1, Is this spike expected?
2, How to clean up the extra watches in the cluster?
3, My test also shown that there is no rebalancing of watches when the capacity of the cluster changes(restarts on etcd02 and etcd04), if a cluster is running fine near the max capacity, what would happen when one node die and come back, would it push the cluster over the limit and has no way to rebalance itself?
4, Is there any manual way to balance the watches/load in the cluster?

**Comment by heyitsanthony** [comment]
> 1, Is this spike expected?

No. There should be little to no change in total watches on the cluster.

> 2, How to clean up the extra watches in the cluster?

The cluster doesn't have extra watches. The client may be opening more watches than it needs, but the server doesn't have enough information to distinguish between useful and useless watches.

Is the code using the client opening new watches if there's a network disruption? Can the spike be reproduced with a simple program connecting to the cluster?

> would [lack of rebalancing] push the cluster over the limit and has no way to rebalance itself?

Yes, there's no automatic rebalancing at the moment.

> Is there any manual way to balance the watches/load in the cluster?

Yes, fetch the metrics for each member and have the client connect to the member with the fewest watches with `SetEndpoints`.

**Comment by cw9** [comment]
> Is the code using the client opening new watches if there's a network disruption? Can the spike be reproduced with a simple program connecting to the cluster?

Yeah, I think during the network disruption, I tried several times to recreate watches and some of those were not cleaned up properly. I'll see if that fixes the issue.

> Yes, fetch the metrics for each member and have the client connect to the member with the fewest watches with SetEndpoints.

I'm more interested in a function or a command that can be applied on the etcd cluster side in a case like this, like the restart process would move all watches to be owned by the rest of the etcd cluster, I wonder if there could be a "balance" cmd that finds out the target load (number of watches) for each node and rebalance some of the over-loaded hosts.

**Comment by heyitsanthony** [comment]
> I wonder if there could be a "balance" cmd that finds out the target load (number of watches) for each node and rebalance some of the over-loaded hosts.

The etcd servers don't have much say over where/how clients connect. There's currently a too many requests error code that might be useful here-- the server would detect it's overloaded and error out the client. As it stands though the client will try to reconnect to the same endpoint if it gets that error.

Are there any existing systems that have a similar client balancing facility?

**Comment by cw9** [comment]
Yeah... I guess that balance has to be done by the clients choosing which etcd server to connect to, it just feels not so ideal to have the cluster running so unbalanced after 1 node restarts, maybe the function that "fetch the metrics for each member and have the client connect to the member with the fewest watches with SetEndpoints" could be build in the client?

**Comment by xiang90** [comment]
@cw9 maybe. can you create a new issue to track the rebalancing issue? as of the watcher spikes, have you got any more information? we would like to reproduce it and get if resolved if it is an etcd issue.

**Comment by cw9** [comment]
The watcher spike is confirmed to be caused by not cleaning up watchers properly on my side.

The Rebalancing is more interesting, the cluster itself recovers very slowly because it's totally up to the clients to decide which node to connect to, but luckily I have the "destroy" test case, so every time that test runs, the whole cluster has a chance to rebalance. 
Created: https://github.com/coreos/etcd/issues/7683
