### ISSUE TITLE
optimize quorum read

### ISSUE THREAD

**Issue by sandflee** [coreos/etcd#7645]
Now quorum read go through raft and will apply to every follower's store. 
1, every follower will apply a read and get the data from store, no need?
2, is it necessary to go though raft?  could the follower  get the newest commitIndex of leader, and wait util the log with the commitIndex applied to follower, then get the data from the store ?

**Comment by mitake** [comment]
After this PR, a follower skips log applying if the log doesn't have side effect (e.g. Range, read operations in Txn): https://github.com/coreos/etcd/pull/5689

Also, this PR implemented readIndex mechanism: https://github.com/coreos/etcd/pull/6212
With the change, a leader can execute read only requests without appending log entries.

**Comment by xiang90** [comment]
already implemented in 3.1. so closing.
