### ISSUE TITLE
Clarify TLS configuration

### ISSUE THREAD

**Issue by unixwitch** [coreos/etcd#7648]
Current documentation on TLS configuration is here: https://coreos.com/etcd/docs/latest/op-guide/security.html - but this doesn't really explain very much.

To use TLS, you need at least three keypairs:

1. Server keypair to accept client connections (`extendedKeyUsage = serverAuth`)
2. Server keypair to accept peer connections (`extendedKeyUsage = serverAuth`)
3. Client keypair to connect to peers (`extendedKeyUsage = clientAuth`)

But etcd only has two configuration options to set keypairs, `--peer-{cert,key}-file` and `--{cert,key}-file`.

1 and 2 could be the same keypair, but it's not clear from the help output or the documentation whether they are or not.

Does `--peer-{cert,key}-file` specify the cert to use to verify incoming peer connections, or the cert to use to authenticate an outgoing peer connection?

What does `--{cert,key}-file` specify - the cert to present to incoming clients, or the cert to present to incoming peers, or the cert to use for outgoing peer connections?

**Comment by xiang90** [comment]
@unixwitch 

> Does --peer-{cert,key}-file specify the cert to use to verify incoming peer connections, or the cert to use to authenticate an outgoing peer connection?

There are more flags in the same security doc:

```
--peer-client-cert-auth: When set, etcd will check all incoming peer requests 
from the cluster for valid client certificates signed by the supplied CA.

--peer-trusted-ca-file=<path>: Trusted certificate authority.
```

These options are what you looking for verifying incoming connections through TLS. 

Similar for client side.
