### ISSUE TITLE
Data version detection

### ISSUE THREAD

**Issue by ingvagabund** [coreos/etcd#7681]
Is there a way to detect version of data in the db? By running ``--version``, resp. ``version`` I can detect API version. However, that does not say anything about the keys inside the db. If there is no such command, is there any way do detect the data version by inspecting ``snap/db`` file or ``wal`` directory?

**Comment by heyitsanthony** [comment]
@ingvagabund What do you mean by version of data/keys? Would that be the version of the etcd cluster that wrote to the DB?

**Comment by ingvagabund** [comment]
The data stored in each etcd member are either v2 or v3 or both. I would like to know a way how to detect that version.

**Comment by ingvagabund** [comment]
If you are using v2 api, you write v2 data. If you are using v3 api, you write v3 data.

**Comment by heyitsanthony** [comment]
@ingvagabund those are stored separately. v2 data is in .snap files, v3 data is in snap/db. The wal file can hold both. What's your use case?

**Comment by ingvagabund** [comment]
Did not know that. Thanks for the info. My use case a migration of data from v2 to v3 in Kubernetes/OpenShift environment. Before I do the migration I would like to check if there are already some v3 data. In that case I will not migrate the v2 -> v3 as I could overwrite already existing v3 data.

**Comment by heyitsanthony** [comment]
@ingvagabund the safest way to do that at the moment is boot etcd on the target member directory with a client listen address that's not being used by any clients, and issue `curl http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "AA==", "range_end": "AA==", "count_only": true}'` to check that count == 0.

**Comment by ingvagabund** [comment]
Any idea what could cause the following error?
```
{"error":"connection error: desc = \"transport: remote error: tls: bad certificate\"","code":13}
```

Running:
```sh
curl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt -L https://172.16.186.45:2379/v3alpha/kv/range -X POST -d '{"key": "AA==", "range_end": "AA==", "count_only": true}'
```

Though, running the following works:
```sh
curl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt -X GET https://172.16.186.45:2379/v2/keys
{"action":"get","node":{"dir":true,"nodes":[{"key":"/ggg","dir":true,"modifiedIndex":24,"createdIndex":24}]}}
```

**Comment by ingvagabund** [comment]
Optionally, I could run:

```sh
export ETCDCTL_API=3
alias etcdtl='etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints "https://172.16.186.45:2379"' 
etcdctl get "" --from-key --keys-only -w json --limit 1
```

with the output:

```json
{
  "header":{
    "cluster_id":2878521931686889904,
    "member_id":6915328958812104709,
    "revision":10,
    "raft_term":10
  },
"kvs":
  [
    {
      "key":"L25lY28va2V5",
      "create_revision":9,
      "mod_revision":9,
      "version":1
    }
  ],
  "more":true,
  "count":2
}
```

And check if `output["count"]` > 0

**Comment by heyitsanthony** [comment]
@ingvagabund yeah that works

**Comment by ingvagabund** [comment]
Thanks. In that case this issue can be closed. @heyitsanthony do you think this is worth documenting?
