### ISSUE TITLE
How to backup and restore etcd cluster by docker container env?

### ISSUE THREAD

**Issue by regardfs** [coreos/etcd#7699]
Our env:
Three docker containers(on three hosts)for etcd and volume `mount /usr/local/etcd/data:/data` mount on each host.

node1: 172.17.9.101
node2: 172.17.9.102
node3: 172.17.9.103

Backup and Restore process:

When use v2 with cmd like `etcdctl backup --data-dir /data --backup-dir /data/data_bak`, 
and restore it firstly into a single member cluster by docker-compose.yml with command: `command: /usr/local/bin/etcd --data-dir /data/data_bak  --force-new-cluster`, then change the peerurl with cmd:   `etcdctl  member update 8e9e05c52164694d http://172.17.9.101:2380`
 info for this single member cluster:

> / # etcdctl  member update 8e9e05c52164694d http://172.17.9.101:2380
Updated member with ID 8e9e05c52164694d in cluster
/ # etcdctl member list
8e9e05c52164694d: name=default peerURLs=http://172.17.9.101:2380 clientURLs=http://localhost:2379 isLeader=true
/ # netstat -tnulp|grep 2380
tcp        0      0 127.0.0.1:2380          0.0.0.0:*               LISTEN      -

You know, when reload by docker restart, the port was still listening on 127.0.0.1, but not 172.17.9.101, thus i could not add the node2, node3 to this cluster. So how can i fulfill this backup/restore function in such env?Do your experts has any recommend method?

**Comment by heyitsanthony** [comment]
@regardfs is etcd restarted with `--listen-peer-urls` set? `etcdctl member update` will update the advertised peer url, but etcd still has to be called with `--listen-peer-urls` to bind to the right interface/address for listening.

**Comment by regardfs** [comment]
@heyitsanthony, When i start docker-compose with this command:
`    command: /usr/local/bin/etcd
      --data-dir /data/data_bak
      --listen-peer-urls http://0.0.0.0:2380`
There are mismatch errors in each node:
node1:

> etcd1          | 2017-04-11 02:32:21.959753 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.061261 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.063836 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.163369 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.166902 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.266822 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.268380 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.369789 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)
etcd1          | 2017-04-11 02:32:22.373123 E | rafthttp: request cluster ID mismatch (got b853b134c9640cad want cdf818194e3a8c32)

node2 and node3(**already delete all /data!!!**):

> etcd2          | 2017-04-11 02:32:14.531294 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[12558efa96ea1646]=cdf818194e3a8c32, local=b853b134c9640cad)
etcd2          | 2017-04-11 02:32:14.533902 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[12558efa96ea1646]=cdf818194e3a8c32, local=b853b134c9640cad)
etcd2          | 2017-04-11 02:32:14.635218 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[12558efa96ea1646]=cdf818194e3a8c32, local=b853b134c9640cad)
etcd2          | 2017-04-11 02:32:14.637433 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[12558efa96ea1646]=cdf818194e3a8c32, local=b853b134c9640cad)
etcd2          | 2017-04-11 02:32:14.736936 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[12558efa96ea1646]=cdf818194e3a8c32, local=b853b1

I have viewed some bugs and issues which quite like this scenario, such as `https://github.com/coreos/etcd/issues/3651`, but not work...

**Comment by regardfs** [comment]
@heyitsanthony , Hi , in docker compose env, all depend on docker-compose.yml, so finally, I change my docker-compose.yml command part to and etcd could start with listening on right ip and port, thanks a lot, i hope this experience could help those guys who do this process in docker env.

>   command: /usr/local/bin/etcd
      --data-dir /data/data_bak
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      --force-new-cluster
