### ISSUE TITLE
Question: Is there an equivalent to --debug option for V3 API

### ISSUE THREAD

**Issue by mcginne** [coreos/etcd#7720]
I find the --debug option useful when debugging to understand requests against etcd when using the V2 API, but I can't find an equivalent when using the V3 API.
Is there any way to log requests from V3 API?

**Comment by heyitsanthony** [comment]
@mcginne check master with `--debug`. There's a tracing endpoint `http://etcd:2379/debug/requests` that will list grpc requests as of c4f1e64de70232359e354ed599fa84ee52e08448.

**Comment by mcginne** [comment]
Awesome, will give it a try, thanks.

**Comment by mcginne** [comment]
That is exactly what I'm looking for, any idea when this will make it to a release?

**Comment by heyitsanthony** [comment]
It'll be in 3.2.

**Comment by xiang90** [comment]
closing this. answer is given.
