### ISSUE TITLE
etcdctl requires auth for endpoint status in 3.1.5

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7721]
This was not the case before. I'm sure until 3.1.3

[rm@dev-vm-01 etcd]$ sudo ETCDCTL_API=3 ./etcdctl --endpoints=https://dev-vm-01.example.com:2379,https://dev-vm-02.example.com:2379,https://dev-vm-03.example.com:2379 --cacert=/var/home/rm/cfssl/ca.pem -w table endpoint status
2017-04-12 16:21:24.474696 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Failed to get the status of endpoint https://dev-vm-01.example.com:2379 (rpc error: code = 2 desc = auth: user name is empty)
Failed to get the status of endpoint https://dev-vm-02.example.com:2379 (rpc error: code = 2 desc = auth: user name is empty)
Failed to get the status of endpoint https://dev-vm-03.example.com:2379 (rpc error: code = 2 desc = auth: user name is empty)
+----------+----+---------+---------+-----------+-----------+------------+
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------+----+---------+---------+-----------+-----------+------------+
+----------+----+---------+---------+-----------+-----------+------------+
[rm@dev-vm-01 etcd]$ sudo ETCDCTL_API=3 ./etcdctl --endpoints=https://dev-vm-01.example.com:2379 version
etcdctl version: 3.1.5
API version: 3.1

**Comment by heyitsanthony** [comment]
it's been there since 3.1.1: 98c60e8faabd31e358f04d4f97d8007d8e306344 

/cc @mitake

**Comment by raoofm** [comment]
my bad, i was running 3.1.0 b4
@heyitsanthony any reason this requires auth.

**Comment by heyitsanthony** [comment]
the auth requirement on `Status` can probably be relaxed

**Comment by mitake** [comment]
@raoofm @heyitsanthony I agree with relaxing the auth requirement of `Status()`. It doesn't need the protection unlike other maintenance RPCs.
