### ISSUE TITLE
Best way to dump v3 db to text?

### ISSUE THREAD

**Issue by pgburt** [coreos/etcd#7723]
[From Twitter](https://twitter.com/raesene/status/852209076985630721) What's the best way of dumping an etcdv3 database to text format?

I suggested tumbling through rows with [Clientv3](https://github.com/coreos/etcd/tree/master/clientv3) might be one option. But, that might be naive. Is there an easier way of dumping a v3 db to text output?

Thanks,

**Comment by gyuho** [comment]
One can try this https://github.com/coreos/etcd/tree/master/tools/etcd-dump-db?

**Comment by raesene** [comment]
Hi, so I'm the original twitterer :)  My use case was that I'm looking at Kubernetes security and one of things I was wondering about would be whether it'd be possible to dump information straight from the etcd database of a Kubernetes cluster to help with auditing/reviewing its configuration.  It occurred that this could be a good way of doing it as a lot/most of the cluster config is stored in the database.  

Through some searching I found https://github.com/br0xen/boltbrowser which kind of works, but gets a lot of non-printable chars in the output.  I'll have a look at the etcd-dump-db command as well.

thanks!

**Comment by xiang90** [comment]
>  Kubernetes security 

k8s use proto format by default in 1.6. so you cannot really dump human readable text from etcd anymore as json format before.

**Comment by raesene** [comment]
ahh, thanks for that, would explain the non-printable characters in straight dumps.  So to do this properly I'd need to deserialize the data...

**Comment by xiang90** [comment]
yes

**Comment by xiang90** [comment]
closing this. answers are provided.
