### ISSUE TITLE
if auth is disabled the etcdctl doesn't work with --user option

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7724]
etcdctl fails. It should still work. If this was done intentionally so that the user is aware that auth is disabled then a warning is sufficient. Else after disabling auth all the scripts needs a change too.

[rm@dev-vm-01 etcd]$ sudo ETCDCTL_API=3 ./etcdctl --endpoints=https://dev-vm-01.example.com:2379 version
etcdctl version: 3.1.5
API version: 3.1

[rm@dev-vm-01 etcd]$ sudo ETCDCTL_API=3 ./etcdctl --endpoints=https://dev-vm-01.example.com:2379,https://dev-vm-02.example.com:2379,https://dev-vm-03.example.com:2379 --cacert=/var/home/rm/cfssl/ca.pem --user=root:password endpoint status
2017-04-12 17:35:23.081712 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
Error:  etcdserver: authentication is not enabled

**Comment by mitake** [comment]
> after disabling auth all the scripts needs a change too

Thanks for your report and the above motivation seems to be reasonable. I'll solve this problem.
