### ISSUE TITLE
etcdctl should require root user authentication for enabling auth

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#7727]
[rm@dev-vm-01 etcd]$ sudo ETCDCTL_API=3 ./etcdctl --endpoints=https://dev-vm-01.example.com:2379 version
etcdctl version: 3.1.5
API version: 3.1

The workflow seems a little weird.

 - First we create a root user/password
 - Enable auth doesn't require auth
 - Disable auth requires auth
 - enable again doesn't require auth

I think everyone will agree that enable should also require auth, else if you have a root user created then anyone can enable auth even if you don't intend to.

**Comment by heyitsanthony** [comment]
I don't agree here. What is the threat model? If auth is disabled, then auth is disabled. A user could wipe the entire store in the meantime.

**Comment by raoofm** [comment]
@heyitsanthony yeaah pretty much :smile: or a better argument is a person enabling auth should at-least know the root password before locking the entire store.

Closing it.
