### ISSUE TITLE
Ruby: WatchResponse doesn't generate unique watch_id.

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#7738]
I am not sure if this is an issue in within the Etcd codebase or if it's a Grpc specific issue, but  `Etcdserverpb::WatchResponse` doesn't seem to be generating a unique `watch_id`.

Each WatchResponse returns `watch_id: 0`.
```
<Etcdserverpb::WatchResponse: header: <Etcdserverpb::ResponseHeader: cluster_id: 14841639068965178418, member_id: 10276657743932975437, revision: 44, raft_term: 5>, watch_id: 0, created: false, canceled: false, compact_revision: 0, events: [<Mvccpb::Event: type: :PUT, kv: <Mvccpb::KeyValue: key: "key", create_revision: 27, mod_revision: 44, version: 18, value: "naddmeasd", lease: 0>, prev_kv: nil>]>
```

The codebase I am using is here:  https://github.com/davissp14/etcdv3-ruby/tree/master/lib/etcdv3/etcdrpc

How to reproduce:

```
# Install Gem
gem install etcdv3

# Use the interactive ruby shell 'irb'
require 'etcdv3'

stub = Etcdserverpb::Watch::Stub.new('localhost:2379', :this_channel_is_insecure)
create_req = Etcdserverpb::WatchCreateRequest.new(key: 'key', progress_notify: true)
watch_req = Etcdserverpb::WatchRequest.new(create_request: create_req)

# Start watching on specified key
Thread.new { stub.watch([watch_req]).each{|i| puts i.inspect } }

# Execute a change on the given key
conn = Etcdv3.new(url: 'http://localhost:2379')
conn.put('key', 'testvalue')
```

Any thoughts?

**Comment by heyitsanthony** [comment]
Watch ID's aren't supposed to be unique across the system. They're only unique within the grpc stream where they're created.

**Comment by davissp14** [comment]
Interesting, are the ID's simply incremented from 0 then?

**Comment by heyitsanthony** [comment]
@davissp14 yes. The watch id is meant to identify which watch substream is associated with the watch response / events received on a watch stream.

**Comment by davissp14** [comment]
Great, I appreciate the quick response!  Closing this out!
