### ISSUE TITLE
etcd service collapsed

### ISSUE THREAD

**Issue by yangzwsir** [coreos/etcd#7741]
# Bug reporting
our network topology:
three etcd services on a machine make up a cluster.

etcd Version: 3.2.0+git
Git SHA: da6a035
Go Version: go1.8
Go OS/Arch: linux/amd64

we want to use the etcd to develop out configuration center.

And we do some test on the cluters, after the cluster run half a day, when wen test AuthDisable api; we use the api  to disable auth; then we found the etcd service which the client connect to was collapsed,the left two etcd service are ok. 
if we don`t use AuthDisable api, the cluster works ok.

restart all the etcd service, it works ok at the beginning, but this situation appeared some hours later(about one day).

we don`t know why.

the output of the collapsed etcd:

![_l nu8m1s u 1s zbr 93](https://cloud.githubusercontent.com/assets/17515389/25037666/fee920a2-212c-11e7-9b65-d6a0cb94e7c1.png)

this is my test code:
void test_auth()
{
    std::shared_ptr<grpc::Channel> mychannel(grpc::CreateChannel("localhost:11001", grpc::InsecureChannelCredentials()));
    std::unique_ptr<etcdserverpb::Auth::Stub> auth_stub(etcdserverpb::Auth::NewStub(mychannel));

    //使能认证。即打开认证功能。
    ::etcdserverpb::AuthEnableRequest aenrequest;
    ::etcdserverpb::AuthEnableResponse aenresponse;
    grpc::ClientContext context1;
    
    ::grpc::Status status = auth_stub->AuthEnable(&context1, aenrequest, &aenresponse);
    if (!status.ok())
    {
        printf("AuthEnable.fail:%d,%s!!\n", status.error_code(), status.error_message().c_str());
        return;
    }
    printf("AuthEnable_success:%s!!\n", status.error_message().c_str());

    //认证
    ::etcdserverpb::AuthenticateRequest authrequest;
    ::etcdserverpb::AuthenticateResponse authresponse;
    grpc::ClientContext context2;
    authrequest.set_name("root");
    authrequest.set_password("123");
    status = auth_stub->Authenticate(&context2, authrequest, &authresponse);

    if (!status.ok())
    {
        printf("Authenticate.fail:%s!!\n", status.error_message().c_str());
        return;
    }

    const ::std::string& mytoken = authresponse.token();
    printf("Authenticate_success.mytoken:%s!!\n", mytoken.c_str());

#if 1
    //this lead to the "localhost:11001" service crash.
    ::etcdserverpb::AuthDisableRequest adisrequest;
    ::etcdserverpb::AuthDisableResponse adisresponse;
    grpc::ClientContext context3;
    context3.AddMetadata("token", mytoken);
    status = auth_stub->AuthDisable(&context3, adisrequest, &adisresponse);

    if (!status.ok())
    {
        printf("AuthDisable.fail2:%d,%s!!\n", status.error_code(), status.error_message().c_str());
        return;
    }
    printf("AuthDisable_success2:%s!!\n", status.error_message().c_str());
#endif
}

**Comment by mitake** [comment]
Thanks for your report. Could you try the latest master branch? The problem would be fixed by https://github.com/coreos/etcd/pull/7729

**Comment by gyuho** [comment]
Please try https://github.com/coreos/etcd/releases/tag/v3.1.6 or master branch. Thanks.
