### ISSUE TITLE
raft: memory "leak" in unstable log

### ISSUE THREAD

**Issue by petermattis** [coreos/etcd#7746]
`unstable.stableTo` truncates a prefix of the unstable log after those entries have been written to stable storage:

```
func (u *unstable) stableTo(i, t uint64) {
	gt, ok := u.maybeTerm(i)
	if !ok {
		return
	}
	// if i < offset, term is matched with the snapshot
	// only update the unstable entries if term is matched with
	// an unstable entry.
	if gt == t && i >= u.offset {
		u.entries = u.entries[i+1-u.offset:]
		u.offset = i + 1
	}
}
```

The truncation is performed by the line: `u.entries = u.entries[i+1-u.offset:]`. But consider what happens to the truncated entries (i.e. `u.entries[:i+1-u.offset]`). They are left untouched and continue to reference `raftpb.Entry.Data` preventing GC from reclaiming that memory. 

On the surface it seems straightforward to clear those entries via something like:

```diff
diff --git a/raft/log_unstable.go b/raft/log_unstable.go
index 8ae301c..a64349c 100644
--- a/raft/log_unstable.go
+++ b/raft/log_unstable.go
@@ -83,7 +83,14 @@ func (u *unstable) stableTo(i, t uint64) {
        // only update the unstable entries if term is matched with
        // an unstable entry.
        if gt == t && i >= u.offset {
-               u.entries = u.entries[i+1-u.offset:]
+               // Clear the entries we are truncating so that the GC can reclaim any
+               // resources they were pointing to. This is important if one or more of the
+               // truncated entries is large.
+               n := i + 1 - u.offset
+               for j := uint64(0); j < n; j++ {
+                       u.entries[j] = pb.Entry{}
+               }
+               u.entries = u.entries[n:]
                u.offset = i + 1
        }
 }
```

Unfortunately, this causes `TestUnstableEnts` to fail as we're mutating the entries in `unstable` which is one of the guarantees that test is checking is not violated. I'm not clear on whether that is accidental or not.

**Comment by bdarnell** [comment]
I think the check in `TestUnstableEnts` was an accident, but it seems like a good property that old entries not be changed once they've been returned to the application. I think there is another solution here.

Once the `u.entries` slice gets reallocated, we no longer hold a reference to the former backing array. The problem here is that if the log has gotten too big, it may have preallocated enough space that it will be a while before the next reallocation. I think we could do something like `if cap(u.entries) > 2*len(u.entries) { /* copy u.entries into a new array */ }`

**Comment by petermattis** [comment]
> The problem here is that if the log has gotten too big, it may have preallocated enough space that it will be a while before the next reallocation.  I think we could do something like if cap(u.entries) > 2*len(u.entries) { /* copy u.entries into a new array */ }

I don't think that would help with the specific scenario we encountered this on. The range received a series of large requests and then was idle afterwards.

**Comment by a-robinson** [comment]
Why wouldn't something along the lines of Ben's `cap(u.entries) > 2*len(u.entries)` suggestion work if placed in `stableTo`? As the number of unstable entries drops down to zero as the range becomes idle, it'll decrease the capacity of `u.entries` down to a more reasonable size. And during the onslaught of large requests, it'd keep `u.entries` from growing to an unnecessarily large capacity.

**Comment by petermattis** [comment]
> Why wouldn't something along the lines of Ben's cap(u.entries) > 2*len(u.entries) suggestion work if placed in stableTo?

I suppose it would if we take that approach to the limit. The situation I saw had `len(u.entries) == 0` which would require setting `u.entries = nil` (or something similar).

**Comment by nvanbenschoten** [comment]
I'm confused about how the change in https://github.com/etcd-io/etcd/pull/7758 fixed this issue. `u.entries` is modified in two ways:
1. it is appended to: `u.entries = append(u.entries, ents...)`
2. it has the front of it cut off: `u.entries = u.entries[i+1-u.offset:]`

In either case, the `u.entries` slice we're left with should not have a capacity that is significantly different than its length. My reading of https://github.com/etcd-io/etcd/commit/45406d84867240ba09e9736b89dac8ccf5d7c2f2#diff-138992d006c7d129dd91591c44fb9d11R104 is that it is assuming `cap(u.entries)` will return the full size of the backing array, including the unreachable prefix. That [isn't the case](https://play.golang.org/p/DQv00B23beh). Am I missing something?

For context, I stumbled on to this without initially realizing that we were the ones who made the change when looking into whether we could turn `unstable.entries` into a ring buffer.

**Comment by bdarnell** [comment]
> it is assuming cap(u.entries) will return the full size of the backing array, including the unreachable prefix. That isn't the case. 

I think you're right (I was also under the impression that `cap(slice)` returned the size of the backing array until now). But #7758 is a partial solution even though this issue means it's not tracking the unused buffer precisely. Go slices often grow by doubling, so after `append()`, there will be some amount of unused space in the tail (less than half the cap()). As the head is cut off, the unused space will be a larger fraction of the whole, eventually triggering the shrinkEntriesArray logic to reset the buffer.
