### ISSUE TITLE
Cannot fetch all keys in a namespace

### ISSUE THREAD

**Issue by wttw** [coreos/etcd#7750]
If I create a (v3) client with a prefixed namespace and try and fetch all keys in that namespace with ...

    cli.KV = namespace.NewKV(cli.KV, "my-prefix/")
    resp, _ := cli.Get(ctx, "", clientv3.WithPrefix())

... the zero length key causes the namespace wrapper function for Get() to return ErrEmptyKey immediately, rather than passing the query to the underlying client as Get("my-prefix/").

The (hack?) that's used elsewhere of passing "\x00" as the key doesn't seem to work with namespaces, returning no results.

**Comment by heyitsanthony** [comment]
@wttw `cli.Get(ctx, "\x00", clientv3.WithFromKey())`

**Comment by wttw** [comment]
Perfect, if a little unintuitive. Thanks!
