### ISSUE TITLE
compile proto

### ISSUE THREAD

**Issue by yueyongyue** [coreos/etcd#7751]
etcdctl version: 3.1.5
API version: 2

I want use python client，but I can't compile /etcd-master/etcdserver/etcdserverpb/rpc.proto.
How do I generate .py file?

**Comment by fanminshi** [comment]
@yueyongyue which python client are you talking about?

**Comment by heyitsanthony** [comment]
This probably duplicates #5156

**Comment by yueyongyue** [comment]
I know , Thanks

**Comment by heyitsanthony** [comment]
Closing since duplicates #5156
