### ISSUE TITLE
Using etcd discovery with go-grpc

### ISSUE THREAD

**Issue by juaby** [coreos/etcd#7760]
go version go1.8.1 linux/amd64
   etcd 3.1.5
   os : centos 7
    go code :

    cli, cerr := clientv3.NewFromURL("http://localhost:2379")
    if cerr != nil {
        log.Fatalf("failed to init etcd3: %v", cerr)
    }
    r := &etcdnaming.GRPCResolver{Client: cli}
    md := metadata.Pairs("alias", "alias")
    
    cerr = r.Add("helloworld/", "127.0.0.1:50051" , md)
    if cerr != nil {
        log.Fatalf("failed to Add endpoint: %v", cerr)
    }
    cerr = r.Add("helloworld/", "127.0.0.2:50052" , md)
    if cerr != nil {
        log.Fatalf("failed to Add endpoint: %v", cerr)
    }

   etcd code :

    ETCDCTL_API=3 ./etcdctl --endpoints=localhost:2379 get /github.com/grpc/helloworld/

    why got result always added last one?

**Comment by heyitsanthony** [comment]
@juaby what is `Add`? It's not in the etcd codebase.

**Comment by juaby** [comment]
@heyitsanthony 

import (
    "log"
    "net"
    
    "golang.org/x/net/context"
    "google.golang.org/grpc"
    "google.golang.org/grpc/metadata"
    pb "google.golang.org/grpc/examples/helloworld/helloworld"
    
    "github.com/coreos/etcd/clientv3"
    etcdnaming "github.com/coreos/etcd/clientv3/naming"
)

**Comment by juaby** [comment]
https://coreos.com/etcd/docs/latest/dev-guide/grpc_naming.html

**Comment by heyitsanthony** [comment]
@juaby yeah, I wrote that doc. There's still no `Add` function:
```
./main.go:24: r.Add undefined (type *"github.com/coreos/etcd/clientv3/naming".GRPCResolver has no field or method Add)
./main.go:28: r.Add undefined (type *"github.com/coreos/etcd/clientv3/naming".GRPCResolver has no field or method Add)
```

**Comment by juaby** [comment]
package main

import (
    "log"
    "net"
    
    "golang.org/x/net/context"
    "google.golang.org/grpc"
    "google.golang.org/grpc/metadata"
    pb "google.golang.org/grpc/examples/helloworld/helloworld"
    
    "github.com/coreos/etcd/clientv3"
    etcdnaming "github.com/coreos/etcd/clientv3/naming"
)

const (
    port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct{}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
    return &pb.HelloReply{Message: "Hello1 " + in.Name}, nil
}

func main() {
    cli, cerr := clientv3.NewFromURL("http://localhost:2379")
    if cerr != nil {
        log.Fatalf("failed to init etcd3: %v", cerr)
    }
    r := &etcdnaming.GRPCResolver{Client: cli}
    md := metadata.Pairs("alias", "alias")
    
    cerr = r.Add("helloworld", "127.0.0.1" + port, md)
    cerr = r.Add("helloworld", "192.168.0.100" + port, md)
    if cerr != nil {
        log.Fatalf("failed to Add endpoint: %v", cerr)
    }
    
    lis, err := net.Listen("tcp", port)
    if err != nil {
        log.Fatalf("failed to listen: %v", err)
    }
    s := grpc.NewServer()
    pb.RegisterGreeterServer(s, &server{})
    s.Serve(lis)
}

**Comment by juaby** [comment]
go get github.com/coreos/etcd/clientv3

**Comment by heyitsanthony** [comment]
Again, there is no `Add` function in `naming.GRPCResolver` and if there were, it would have a ctx argument so it'd be cancelable-- how is that compiling on your side?

master branch gives:
```
./main.go:37: r.Add undefined (type *"github.com/coreos/etcd/clientv3/naming".GRPCResolver has no field or method Add)
./main.go:38: r.Add undefined (type *"github.com/coreos/etcd/clientv3/naming".GRPCResolver has no field or method Add)
```

Cf. https://godoc.org/github.com/coreos/etcd/clientv3/naming#GRPCResolver

**Comment by juaby** [comment]
![2017-04-19 09-41-07](https://cloud.githubusercontent.com/assets/4152978/25159793/b9f8c012-2477-11e7-81ea-dacd71d8e16f.png)

**Comment by juaby** [comment]
![2017-04-19 09-47-33](https://cloud.githubusercontent.com/assets/4152978/25159896/581f67b4-2478-11e7-8957-5347a0eb7ccd.png)

**Comment by heyitsanthony** [comment]
It's only listing one key because it's writing to the same key (`helloworld`). Use a different `target`.

**Comment by heyitsanthony** [comment]
@juaby that `Add` function has never been part of the clientv3 codebase. I don't know how it got there in your environment. Seriously: https://github.com/coreos/etcd/blob/master/clientv3/naming/grpc.go

**Comment by heyitsanthony** [comment]
OH, it was there but deleted in october. Never mind. Ugh

**Comment by heyitsanthony** [comment]
That old version never worked by the way and predates the documentation afaik. Update clientv3. Thanks!

**Comment by juaby** [comment]
[juaby@juaby coreos]$ rm -rf etcd
[juaby@juaby coreos]$ go get github.com/coreos/etcd/clientv3
# github.com/coreos/etcd/etcdserver/etcdserverpb
etcd/etcdserver/etcdserverpb/rpc.pb.go:2201: undefined: grpc.SupportPackageIsVersion4

**Comment by heyitsanthony** [comment]
@juaby the go-grpc package in your gopath is out of date. Please use vendoring (glide, dep, govendor, godep) instead of `go get` or things will break all the time.

**Comment by juaby** [comment]
@heyitsanthony ths very very very much! 谢谢

**Comment by heyitsanthony** [comment]
OK, closing. That grpc naming doc should hopefully make more sense now / be easier to follow. Reopen if you have any other problems. Thanks!

**Comment by juaby** [comment]
# github.com/coreos/etcd/etcdserver/etcdserverpb
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:614: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:616: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:621: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:625: not enough arguments in call to forward_KV_Range_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:642: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:644: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:649: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:653: not enough arguments in call to forward_KV_Put_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:670: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:672: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.gw.go:672: too many errors

**Comment by heyitsanthony** [comment]
@juaby use https://github.com/Masterminds/glide to vendor packages. It'll lock go packages to a specific revision. Otherwise you'll keep getting build conflicts since not every go package's master branch (the code that's fetched with `go get`) is synced / master branches are unstable.

For an example glide file for an etcd client see https://github.com/coreos/zetcd/blob/master/glide.yaml
