### ISSUE TITLE
delete all prev key

### ISSUE THREAD

**Issue by 735254599** [coreos/etcd#7762]
I tried del command with flag --prev-kv ,but it just delete the key  I set in the last time.how does it working,I want to delete all the prev key.

**Comment by fanminshi** [comment]
use `--prefix[=false]		delete keys with matching prefix` instead of `--prev-kv`

**Comment by heyitsanthony** [comment]
@735254599 can you give an example of what behavior you're expecting?

**Comment by xiang90** [comment]
--prev-kv simply return you the previous value of the key. please check the help string for its usage.

if you want to delete a range of keys, you can specify `\x0` as range start and your key as the end key. it will delete all the keys that are smaller than your key.
