### ISSUE TITLE
Current state of master breaks programs that link to the etcd3 client

### ISSUE THREAD

**Issue by aaronjwood** [coreos/etcd#7763]
We're seeing an issue when doing a `go get ./...` today:

```
# github.com/grpc-ecosystem/grpc-gateway/runtime
../github.com/grpc-ecosystem/grpc-gateway/runtime/context.go:99: undefined: metadata.NewOutgoingContext
```

When trying to build our project (just a plain `go build`) that uses etcdv3 we hit the same thing:
```
# github.com/grpc-ecosystem/grpc-gateway/runtime
../../../github.com/grpc-ecosystem/grpc-gateway/runtime/context.go:99: undefined: metadata.NewOutgoingContext
```

Please let me know if I should submit this issue upstream to `grpc-gateway` instead.

**Comment by heyitsanthony** [comment]
@aaronjwood don't build against master; it etcd master itself is unstable and tracking upstream means vendoring unstable / non-release revisions. Use vendoring if you don't want this kind of breakage. etcd binaries can be built with vendored libaries using `go get github.com/coreos/cmd/etcd`.

**Comment by aaronjwood** [comment]
So if we import `github.com/coreos/etcd/clientv3` and do a `go get ./...` based on that you're saying we should expect things to break every so often?

**Comment by heyitsanthony** [comment]
@aaronjwood Yes. There's no way to keep all dependencies perfectly in sync if everything is being fetched from master. Vendoring solves this issue. Use glide or godep or govendor to manage dependencies.

**Comment by aaronjwood** [comment]
I didn't realize that master was an unstable branch. We'll have to figure out some vendoring strategy internally I guess...

**Comment by tmc** [comment]
It appears that a current ```glide install; go build``` works on HEAD for this repository. The current vendored versions of grpc-gateway and grpc in etcd do not have metadata.NewOutgoingContext.

**Comment by heyitsanthony** [comment]
Vendoring is the workaround here. etcd will update grpc when there's a new release. Closing.
