### ISSUE TITLE
etcd 2.2.4 support the unsafe 3DES cipher

### ISSUE THREAD

**Issue by zllbeck** [coreos/etcd#7777]
Use etcd 2.2.4, this version use the unsafe 3DES cipher.
But there no way to config disable the unsafe 3DES cipher for security purpose.

**Comment by xiang90** [comment]
we do not maintain etcd 2.2 branch anymore. we only maintain the current master and a previous release 3.1.

**Comment by xiang90** [comment]
please stop filing bugs on ancient releases.
