### ISSUE TITLE
Ephemeral Docker Ports

### ISSUE THREAD

**Issue by enkoder** [coreos/etcd#7781]
What is the best way to accept client requests from a docker container when I am using random ephemeral port mappings? I am bringing up multiple etcd containers on a single host (CI integration tests) and cannot use the standard 2379 ports for `listen-peer-urls`. 

In an entrypoint.sh I could dynamically pass a portion of the port range (http://0.0.0.0:32768, http://0.0.0.0:32769, etc) to `listen-peer-urls`, but this is pretty hacky and fragile. 

Is there a way to just accept all clients requests? This would be very useful for automation and parallel testing.

**Comment by heyitsanthony** [comment]
`listen-peer-urls` is for etcd cluster peers and uses port 2380, `listen-client-urls` is for clients and uses port 2379...

I'm not sure I understand what behavior you're expecting with ephemeral ports. The container would `EXPOSE 2379` and docker will map the container port from 2379 to an ephemeral host port. The etcd process itself will think it's listening on 2379 and the host mapping / ephemeral port that's accessible outside the container would found via `docker port`.

**Comment by xiang90** [comment]
> Is there a way to just accept all clients requests? 

You can make etcd listen on 0.0.0.0:x to accept connections on all its interfaces on port x. How you configure docker is out of the scope of etcd project.

Let us know if you have any further etcd related questions. Thanks!

**Comment by enkoder** [comment]
Hey guys, apologies for dropping a poorly worded question and not responding promptly. Poor timing to file an issue then go on vacation :tropical_drink:. Please let me elaborate on my question. 

I am using docker to run etcd, specifically docker compose, to bring up all services linked in a network. When using a 1:1 mapping of host to container port mapping to the default 2379 port I can connect to etcd no problem from my host or from a linked container. 

I am having issues when using a random ephemeral port. To test you can run the following...

```
docker run --name etcd -p 4001 -p 2379 -p 2480 quay.io/coreos/etcd:v3.1.5 etcd \
       --name=etcd  \
       --initial-cluster-token=etcd-cluster \
       --initial-cluster=etcd=http://0.0.0.0:2380 \
       --initial-cluster-state=new \
       --initial-advertise-peer-urls=http://0.0.0.0:2380 \
       --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001,http://localhost:239 \
       --listen-peer-urls=http://0.0.0.0:2380 \
       --advertise-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001 \
       --data-dir=/etcd-data
```

Container should be running and named etcd. Now try to connect to the etcd container. 
```
etcdctl --endpoints http://$(docker port etcd 2379/tcp) ls
```

I am certain I am doing something wrong here but I am not sure exactly what is wrong. Thanks for you help fellas.

**Comment by heyitsanthony** [comment]
@enkoder have you tried using `docker port` to resolve the mapping?

**Comment by heyitsanthony** [comment]
@enkoder what is the docker port output? I get:

```sh
$ docker port etcd 2379/tcp
0.0.0.0:32770
```

`etcdctl` can't connect to `0.0.0.0`. Try:

```sh
etcdctl --endpoints http://$(docker port etcd 2379/tcp | sed 's/0.0.0.0/127.0.0.1/')
```

**Comment by enkoder** [comment]
@heyitsanthony I get the same output if I replace `0.0.0.0` with localhost ip. 

```
$ docker port etcd 2379/tcp                                              
0.0.0.0:33049
```

```
$ etcdctl --endpoints http://$(docker port etcd 2379/tcp | sed 's/0.0.0.0/127.0.0.1/') ls
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 0.0.0.0:4001: getsockopt: connection refused
; error #1: dial tcp 0.0.0.0:2379: getsockopt: connection refused

error #0: dial tcp 0.0.0.0:4001: getsockopt: connection refused
error #1: dial tcp 0.0.0.0:2379: getsockopt: connection refused
```

**Comment by heyitsanthony** [comment]
`etcdctl --no-sync`
