### ISSUE TITLE
ETCDCTL_API=3 etcdctl lease grant <TTL> -w json does not return json

### ISSUE THREAD

**Issue by ingvagabund** [coreos/etcd#7783]
When creating a lease with json as the output format, the output is not printed in json. Instead, it is printed as a simple format.

```sh
ETCDCTL_API=3 etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints https://172.16.186.106:2379 lease grant 10 -w json
2017-04-20 09:40:33.817507 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
lease 694d5b8b1830d1ae granted with TTL(10s)
```

Affected version: etcd-3.1.3

**Comment by ingvagabund** [comment]
Because https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/lease_command.go#L70

**Comment by ingvagabund** [comment]
@heyitsanthony @gyuho

**Comment by ingvagabund** [comment]
Maybe? Just shooting atm, did not try to compile it and run it.
```go
if _, ok := display.(*simplePrinter); ok {
	fmt.Printf("lease %016x granted with TTL(%ds)\n", resp.ID, resp.TTL)
} else {
	displaydisplay.Get(*resp)
}
```

**Comment by ingvagabund** [comment]
```
src/github.com/coreos/etcd/etcdctl/ctlv3/command/lease_command.go:73: cannot use *resp (type clientv3.LeaseGrantResponse) as type clientv3.GetResponse in argument to display.Get
```

Ok, the LeaseGrantResponse needs to implemented the interface.

**Comment by gyuho** [comment]
Yeah, @heyitsanthony do you remember why some lease RPCs are missing from `printer` interface?

**Comment by heyitsanthony** [comment]
@gyuho lease commands weren't picked up during the printerization of the commands. They should be displayable as json since they map to RPCs.

**Comment by ingvagabund** [comment]
Thanks guys
