### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [coreos/etcd#7791]
$ go get -u github.com/coreos/etcd
github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw
../../coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:147: not enough arguments in call to runtime.AnnotateContext

my environment:
go 1.8 or 1.7
centos 7.2 or 7.1
protoc 3.1.0 or 3.2.0

**Comment by heyitsanthony** [comment]
Use go vendoring if consuming the client. Build with vendoring (`go get github.com/coreos/etcd/cmd/etcd`) if building etcd from master.

Can't update grpc-gateway until go-grpc cuts a new release. Duplicates #7772. Closing.
