### ISSUE TITLE
TestNetworkPartition5MembersLeaderInMinority: context deadline exceeded

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#7802]
via https://semaphoreci.com/coreos/etcd/branches/master/builds/1843
```
--- FAIL: TestNetworkPartition5MembersLeaderInMinority (21.77s)
        cluster_test.go:521: #3: watch on unix://127.0.0.1:2274623440 error: context deadline exceeded
```

**Comment by gyuho** [comment]
FYI. Found the root cause yesterday. Same issue with https://github.com/coreos/etcd/issues/7739 and https://github.com/coreos/etcd/issues/7595. Will share logs next week.

**Comment by gyuho** [comment]
Fixed via https://github.com/coreos/etcd/pull/7810.
