### ISSUE TITLE
should I maintain a heartbeat in application layer?

### ISSUE THREAD

**Issue by hzxuzhonghu** [coreos/etcd#7838]
Firstly, client  connect to etcd cluster, and watch for something change
then,   if send a SIGSTOP signal to the etcd connected to by hand, client would not sense connection disconnect in both V2 and V3. And client still treate connection alive. beacuse  tcp heartbeat  still exist

Should I maitain a heartbeat every period time, and when heartbeat timeout then try another etcd endpoint?

**Comment by heyitsanthony** [comment]
With the client as it is now, yes, that check would need application-level heart beats. Related: #7321 #7247

**Comment by heyitsanthony** [comment]
Closing. Please reopen if you have any further questions. Thanks!
