### ISSUE TITLE
docs for standalone etcd in docker are failing with "oci runtime error..."

### ISSUE THREAD

**Issue by sdanieru** [coreos/etcd#7843]
I'm attempting to get a standalone etcd up and running on coreos so I can further eval kubernetes. I'm following the instructions found here:

https://coreos.com/etcd/docs/latest/v2/docker_guide.html

and pulling the latest coreos/etcd image (which is currently v3.1.5)

but the container fails to run with the following error:

`docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"-name\\\": executable file not found in $PATH\"\n".`

I did have success running an older version (v2.3.7) but this version is unsupported and I'd really rather be running the latest and greatest as it's likely to play better with Kubernetes.

Does anyone know how to resolve or work around this? I would assume that the doc just hasn't kept up with changes in the image and there's a parameter or something that needs to be updated, but I don't know where to start; any help appreciated!

I can also add that I initially asked this question on the coreos google group [here](https://groups.google.com/forum/#!searchin/coreos-user/daniel%7Csort:relevance/coreos-user/Hzhbcla7bRk/0iDedppgEQAJ) and the response from Rob was:

> It looks like your docker run command is detecting the etcd configuration flags (starting with -name) as the path to the binary within the container. I’d guess that the 2.x dockerfile specified this path, and the 3.x one doesn’t, _or_ your command has extra whitespace or some other malformed argument.

> The etcd docs are contained within the repo, so you can file bugs or even better, contribute back fixes: https://github.com/coreos/etcd/issues

**Comment by heyitsanthony** [comment]
@sdanieru The v2 documentation was written for etcd 2.x operation. Maybe the latest [docker guide](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker) would be useful?

**Comment by sdanieru** [comment]
hi @heyitsanthony, thanks for the response. Since the v2 documentation is pulling `quay.io/coreos/etcd`, it's going to pull the v3 image and break for anyone referencing the v2 doc; perhaps the v2 documentation should be changed to explicitly pull a v2 image?

I'm new to etcd; the v2 docs i came to were linked from [here](https://coreos.com/kubernetes/docs/latest/kubernetes-on-generic-platforms.html). How could I adapt the [docker guide](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker) for a standalone etcd installation?
