### ISSUE TITLE
Question: Why support v2 Storage and API in 3.2?

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#7847]
Given the v2 api is deprecated, what's the reasoning for continuing to support it in 3.2?

**Comment by heyitsanthony** [comment]
There's a period between deprecation and actually removing the feature. Not everyone has migrated to using the v3 API (and probably won't, for that matter)

**Comment by heyitsanthony** [comment]
@davissp14 if you just want to disable the v2 endpoint, it can be done by passing `--enable-v2=false` to the etcd server...

**Comment by davissp14** [comment]
@heyitsanthony Perfect, thank you!
