### ISSUE TITLE
discovery: able to specify and use tls client certificates

### ISSUE THREAD

**Issue by schofield** [coreos/etcd#785]
The discovery feature lacks the ability to use a client certificate to communicate with the discovery server. The client should be able to specify a CA file, client certificate, and client key.

**Comment by xiang90** [comment]
@kelseyhightower @philips @yichengq @jedsmith 

Would love to hear your opinion on this one. For our public service, we will not verify the client cert. For private service, user can somehow keep it secure without this feature. But, yea, it would be a hard thing to add. I have no objection to add it.

**Comment by yichengq** [comment]
I would like to know whether there will be users to use this feature, considering this issue has lasted for one year.

@schofield Are you hosting the local discovery service? Could you talk more about the use case?

**Comment by xiang90** [comment]
@yichengq As we still wait for the reply from @schofield, I move this to 2.2 release milestone. I do not think this is blocker for rc release next week.

**Comment by schofield** [comment]
Sorry for the delay in response, the project I was working on moved away from using coreos and etcd. At the time I was trying to run a private discovery service and wanted it to authenticate via client certificates as we already have other pieces of our infrastructure doing the same.
