### ISSUE TITLE
AsyncWatch collapsed

### ISSUE THREAD

**Issue by yangzwsir** [coreos/etcd#7850]
when i use async grpc api, use AsyncWatch get a handler,when call Write, the programe collapsed. how to use the AsyncWatch ???

i consulted this url:
https://github.com/nokia/etcd-cpp-apiv3/blob/master/v3/src/AsyncWatchAction.cpp, but there is no use.

the output like below:
I0502 20:48:09.361018216   92975 init.c:178]                 grpc_init(void)
I0502 20:48:09.361022825   92975 completion_queue.c:128]     grpc_completion_queue_create_internal(completion_type=1, polling_type=0)
I0502 20:48:09.361030996   92975 channel.c:353]              grpc_channel_create_registered_call(channel=0x28149a0, parent_call=(nil), propagation_mask=ffff, completion_queue=0x28078e0, registered_call_handle=0x2806e00, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=(nil))
I0502 20:48:09.361045344   92975 grpc_context.c:41]          grpc_census_call_set_context(call=0x28199e0, census_context=(nil))
I0502 20:48:09.361052039   92975 call.c:1787]                grpc_call_start_batch(call=0x28199e0, ops=0x7fff41dd3e10, nops=1, tag=0x28092e0, reserved=(nil))
I0502 20:48:09.361057118   92975 call.c:1430]                ops[0]: SEND_INITIAL_METADATA(nil)
run here:4.
I0502 20:48:09.361068973   92975 call.c:1787]                grpc_call_start_batch(call=0x28199e0, ops=0x7fff41dd3e70, nops=2, tag=0x28092e0, reserved=(nil))
I0502 20:48:09.361073671   92975 call.c:1430]                ops[0]: SEND_INITIAL_METADATA(nil)
I0502 20:48:09.361078222   92975 call.c:1430]                ops[1]: SEND_MESSAGE ptr=0x28076b0
E0502 20:48:09.361084537   92975 channel_cc.cc:136]          assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)

the code like below:
void test()
{
    ::etcdserverpb::WatchRequest request;
    ::etcdserverpb::WatchCreateRequest watch_req1;
    watch_req1.set_key(key);

    watch_req1.set_prev_kv(true);
    watch_req1.set_start_revision(0);
watch_req1.add_filters(::etcdserverpb::WatchCreateRequest_FilterType::WatchCreateRequest_FilterType_NODELETE); 
    watch_req1.set_prev_kv(true);
    request.mutable_create_request()->CopyFrom(watch_req1);
    
    ::grpc::ClientContext watch_context;
    ::grpc::CompletionQueue completion_cq;
    ::grpc::WriteOptions optionsxx;
    auto watch_handler = _watch_stub->AsyncWatch(&watch_context, &completion_cq, (void *)"watch");

    watch_handler->Write(request, optionsxx, (void*)"write");  //--collapsed at this point.
    .......
}
To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by yangzwsir** [comment]
i don`t use nokia/etcd-cpp-apiv3 api to realize AsyncWatch call, i use the source version of the etcd AsyncWatch  api. but when i call watch_handler->Write, the programe collapsed. then i consulted   nokia/etcd-cpp-apiv3, the  programe collapsed too.

 so i think that there is no direct relationship between collapsed and nokia/etcd-cpp-apiv3,api.

my question: how to use etcd AsyncWatch to avoid the program ??

**Comment by yangzwsir** [comment]
@heyitsanthony 

i don`t use nokia/etcd-cpp-apiv3 api to realize AsyncWatch call, i use the source version of the etcd AsyncWatch api. but when i call watch_handler->Write, the programe collapsed. then i consulted nokia/etcd-cpp-apiv3, the programe collapsed too.

so i think that there is no direct relationship between collapsed and nokia/etcd-cpp-apiv3,api.

my question: how to use etcd AsyncWatch to avoid the program ??

**Comment by heyitsanthony** [comment]
@yangzwsir where are you finding `AsyncWatch` in the etcd repo?

**Comment by heyitsanthony** [comment]
Oh, OK, I see it's generated as part of the C++ gRPC stubs. What version of protoc, C++ gRPC, and etcd are you using?

**Comment by yangzwsir** [comment]
@heyitsanthony 
protoc:
libprotoc 3.2.0

etcd:
etcd Version: 3.2.0+git
Git SHA: 7e3dd74
Go Version: go1.7.4
Go OS/Arch: linux/amd64

grpc:
core_version = "3.0.0-dev"

gcc:
gcc version 4.8.2 20140120

**Comment by zhangwuliang** [comment]
Hi，I have this problem, too. Have you sloved it? And how to slove? Thx!

**Comment by mauiarches** [comment]
Hello,
When we used grpc version 1.2.0, assert was gone.

**Comment by zhangwuliang** [comment]
@yangzwsir  Have you solved it? I'm still troubled by this problem， the watcher can not work

**Comment by xiang90** [comment]
gRPC c++ 1.2+ fixes this issue. not etcd specific, closing
