### ISSUE TITLE
Suggestions on V2 API missing events

### ISSUE THREAD

**Issue by reterVision** [coreos/etcd#7858]
Hi etcd maintainers,

We are using Etcd for service discovery internally, each service `set` a key in etcd when startup and `delete` the key when shutdown, each key has a TTL attached. The key structure looks like this

```
/serviceA
    /Host1
    /Host2
```

Client using V2 watcher API to watch for key changes under each service's directory and add/remove host when key changes.

However, we observed that clients could miss key deletion events and that leads to clients try connecting to bad hosts issue.

Is there a way to prevent V2 clients missing events? I know V3 has some improvements on this but upgrading to V3 will take sometime for us as it doesn't have directory structures as far as I know and that will be a major change in our client SDK.

Thanks in advance!

**Comment by heyitsanthony** [comment]
@reterVision as you noted, this was solved in v3; there's not much motivation to fix it in v2. Wouldn't the v3 client be able to do this with `cli.Watch(ctx, "/serviceA/", clientv3.WithPrefix())` even without directories? V3 can emulate directory listing too, but it's not clear whether that's necessary here.

**Comment by xiang90** [comment]
No. v2 api is not designed for it. It wont be fixed. Try v3 instead.
