### ISSUE TITLE
Is there any way use one set of certificates for several etcd cluster

### ISSUE THREAD

**Issue by workhardcc** [coreos/etcd#7883]
If I have several etcd cluster, simply I should create several certificates for each cluster.
However can I create only one set of certificates for those etcd cluster? Cause it's too complicated when I want scaling the cluster or some other scenarios( to tell the truth I want use only one set of certificates for etcd cluster and kubernetes cluster).
I try to generate server certificate like below, but dosen't work:
`cfssl print-defaults csr > server.json`
```
...
    "CN": "coreos1",
    "hosts": [
        ""
    ],
...
```
I follow the guide: https://coreos.com/os/docs/latest/generate-self-signed-certificates.html
Thanks!

**Comment by gyuho** [comment]
You can just configure more nodes in `hosts` field.

```json
  ...
  "hosts": [
    "127.0.0.1",
    "localhost",
    "10.240.0.1"
  ]
}
```

But we recommend unique certs for each node, because it provides better security (e.g. add,remove nodes).

**Comment by gyuho** [comment]
@workhardcc I am closing this. Please let me know if you have further questions on TLS set-up.
