### ISSUE TITLE
The endpoint is probably not valid etcd cluster endpoint.

### ISSUE THREAD

**Issue by shihuan830619** [coreos/etcd#7894]
[root@**k8s** etcd]# more etcdstart.sh
/usr/bin/etcd --name etcd1 \
--data-dir /var/lib/etcd/etcd1 \
--wal-dir /var/lib/etcd/wal1 \
--listen-peer-urls http://192.168.100.112:2380 \
--listen-client-urls http://192.168.100.112:2379,http://127.0.0.1:2379 \
--initial-advertise-peer-urls http://192.168.100.112:2380 \
--advertise-client-urls http://192.168.100.112:2379 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster etcd1=http://192.168.100.112:2380,etcd2=http://192.168.100.113:2380,etcd3=http://192.168.100.114:2380 \
--initial-cluster-state new >> /usr/local/etcd/etcd_log/etcd.log 2>&1 &

[root@**k8snode1** etcd]# more etcdstart.sh
/usr/bin/etcd --name etcd2 \
--data-dir /var/lib/etcd/etcd2 \
--wal-dir /var/lib/etcd/wal2 \
--listen-peer-urls http://192.168.100.113:2380 \
--listen-client-urls http://192.168.100.113:2379,http://127.0.0.1:2379 \
--initial-advertise-peer-urls http://192.168.100.113:2380 \
--advertise-client-urls http://192.168.100.113:2379 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster etcd1=http://192.168.100.112:2380,etcd2=http://192.168.100.113:2380,etcd3=http://192.168.100.114:2380 \
--initial-cluster-state new >> /usr/local/etcd/etcd_log/etcd.log 2>&1 &

[root@**k8snode2** etcd]# more etcdstart.sh
/usr/bin/etcd --name etcd3 \
--data-dir /var/lib/etcd/etcd3 \
--wal-dir /var/lib/etcd/wal3 \
--listen-peer-urls http://192.168.100.114:2380 \
--listen-client-urls http://192.168.100.114:2379,http://127.0.0.1:2379 \
--initial-advertise-peer-urls http://192.168.100.114:2380 \
--advertise-client-urls http://192.168.100.114:2379 \
--initial-cluster-token etcd-cluster-1 \
--initial-cluster etcd1=http://192.168.100.112:2380,etcd2=http://192.168.100.113:2380,etcd3=http://192.168.100.114:2380 \
--initial-cluster-state new >> /usr/local/etcd/etcd_log/etcd.log 2>&1 &

[root@**k8s** bin]# **_./etcdctl --debug --endpoints http://192.168.100.112:2379,http://192.168.100.112:2380 ls_**
start to sync cluster using endpoints(http://192.168.100.112:2379,http://192.168.100.112:2380)
cURL Command: curl -X GET http://192.168.100.112:2379/v2/members
cURL Command: curl -X GET http://192.168.100.112:2380/v2/members
got endpoints(http://192.168.100.112:2379,http://192.168.100.112:2380) after sync
Cluster-Endpoints: http://192.168.100.112:2379, http://192.168.100.112:2380
cURL Command: curl -X GET http://192.168.100.112:2380/v2/keys/?quorum=false&recursive=false&sorted=false
**_Error:  client: response is invalid json. The endpoint is probably not valid etcd cluster endpoint._**

Please advice!

**Comment by shihuan830619** [comment]
已经自行解决， 打扰大家了。

**Comment by kevinadmins** [comment]
> 已经自行解决， 打扰大家了。

请教一下，是怎么解决的，我也碰到这个问题了，在用V2写入网段和配置信息的时候

**Comment by menghao11** [comment]
> > 已经自行解决， 打扰大家了。
> 
> 请教一下，是怎么解决的，我也碰到这个问题了，在用V2写入网段和配置信息的时候

也许是etcd版本的原因，我使用的ectd2的client，但是server是etcd3，返回的也是这个错误，你要不检查一下你的client的版本
