### ISSUE TITLE
raft: behaviours for m.Term < r.Term mismatch in doc and code

### ISSUE THREAD

**Issue by mhowto** [coreos/etcd#7895]
[doc](https://github.com/coreos/etcd/blob/master/raft/raft.go#L719):
```
// If checkQuorum is false, this will be handled by incrementing term numbers
// in response to MsgVote with a higher term
```

[code](https://github.com/coreos/etcd/blob/master/raft/raft.go#L729):
just ignore
```
// ignore other cases

r.logger.Infof("%x [term: %d] ignored a %s message with lower term from %x [term: %d]",
r.id, r.Term, m.Type, m.From, m.Term)
```
Did I miss some details? Or it's just a mismatch.

**Comment by xiang90** [comment]
what is your question exactly? I do not quite follow it. Can you give me an example?

**Comment by gyuho** [comment]
@mhowto Did you mean this part `case  m.Term < r.Term:` and

> r.logger.Infof("%x [term: %d] ignored a %s message with lower term from %x [term: %d]", r.id, r.Term, m.Type, m.From, m.Term)

This log is correct, because `m` (Message) has the lower term.

**Comment by mhowto** [comment]
@xiang90  @gyuho 
In the comment, it says "If checkQuorum is false, this will be handled by incrementing term numbers in response to MsgVote with a higher term". My understanding about this comment is that "case m.Term < r.Term", the r will return a MsgVoteResp message with a higher term.

But in the code, "case m. Term < r.Term", it just log the MsgType message, and never return a MsgVoteResp messae.

So I think there is something wrong in the comment. It does not describe the behavior exactly.

**Comment by xiang90** [comment]
@mhowto in the response, we will attach the term, which is higher than the term of the request. so it will increase the term of the sender. the comment is correct. i am closing this.
