### ISSUE TITLE
Will APi grpc server close the idle connection in sometime later?

### ISSUE THREAD

**Issue by yueyongyue** [coreos/etcd#7905]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by heyitsanthony** [comment]
@yueyongyue how are you using etcd so that it needs to close idle connections?

Would closing idle grpc connections in the go client work or will the server have to do it?

**Comment by yueyongyue** [comment]
Too much TCP connection ，I want to close it， How to set up the idle time?

**Comment by heyitsanthony** [comment]
@yueyongyue there's no grpc idle timeout yet. Can you explain how you're using etcd and why it's using so many connections?

**Comment by yueyongyue** [comment]
I want to periodically check the etcd state of health

**Comment by heyitsanthony** [comment]
@yueyongyue how often is the checking performed? Why not do something like:
```go
func checkHealth(ctx context.Context, cfg clientv3.Config) {
   for ctx.Err() == nil {
       cli, err := clientv3.New(cfg)
       if err != nil {
           ...
       }
       doCheck(ctx, cli)
       cli.Close()
       select {
       case <-ctx.Done():
       case <-time.After(HealthCheckPeriod):
       }
   }
}
```

**Comment by heyitsanthony** [comment]
@yueyongyue ping?

**Comment by heyitsanthony** [comment]
Closing. Feel free to reopen the issue if closing the client does not fix the problem. Thanks!
