### ISSUE TITLE
3.2.0-rc0, Windows: 10GB db file in snap directory

### ISSUE THREAD

**Issue by danielfaust** [coreos/etcd#7910]
I'm new to etcd, and creating a cluster of 3 members. Two on Windows machines, one inside Docker on Ubuntu.

I'm wondering if it is normal for the `\etcd-v3.2.0-rc.0-windows-amd64\default.etcd\member\snap\db` file to be 10GB big. This is the case on both Windows machines. The wal directory contains two 62M wal files.

On Linux it's just 28K for the snap/db and also two 62M wal files.

I couln't find anything on the net related to this.

The following is the config file of one of the Windows machines, they are almost identical.

---
update: I just noticed that I'm running `quay.io/coreos/etcd` and not `quay.io/coreos/etcd:v3.2.0-rc.0` in the Docker container.

```
name: 'server-win'
data-dir: 'C:\App\etcd\etcd-v3.2.0-rc.0-windows-amd64\default.etcd'
wal-dir:
snapshot-count: 10000
heartbeat-interval: 100
election-timeout: 1000
quota-backend-bytes: 0

max-snapshots: 5
max-wals: 5
cors: 

initial-advertise-peer-urls: http://192.168.20.23:2380
listen-peer-urls: http://192.168.20.23:2380
listen-client-urls: http://192.168.20.23:2379,http://127.0.0.1:2379
advertise-client-urls: http://192.168.20.23:2379

discovery: 
discovery-fallback: 'proxy'
discovery-proxy: 
discovery-srv: 

initial-cluster-token: 'etcd-cluster'
initial-cluster: server-win=http://192.168.20.23:2380,xeon-win=http://192.168.20.26:2380,xeon-ubt=http://192.168.20.25:2380
initial-cluster-state: 'new'

strict-reconfig-check: false
enable-v2: true

proxy: 'off'
proxy-failure-wait: 5000
proxy-refresh-interval: 30000
proxy-dial-timeout: 1000
proxy-write-timeout: 5000
proxy-read-timeout: 0

client-transport-security: 
  cert-file: 
  key-file: 
  client-cert-auth: false
  trusted-ca-file: 
  auto-tls: false

peer-transport-security: 
  cert-file: 
  key-file: 
  client-cert-auth: false
  trusted-ca-file: 
  auto-tls: false

debug: false
log-package-levels: 
force-new-cluster: false
```

**Comment by heyitsanthony** [comment]
I think what's happening is boltdb is passed an initial mmap size of 10GB, which was linux-only before 5e4b0081065925ab9d04009cd4fb559c4cceb304, and windows will immediately set the db file to use the full 10GB.

**Comment by danielfaust** [comment]
How will this affect me when it gets fixed? I won't be able to reduce the size at a later point in time, right? 

So I'm better off not using etc 3.2.0r on windows until this is fixed?

**Comment by heyitsanthony** [comment]
@danielfaust running [`etcdctl defrag`](https://github.com/coreos/etcd/tree/master/etcdctl#defrag) on the member should reduce the db size once the initial mmap size bug is fixed. I'd advise against putting 3.2.0rc on windows until there's a fix since transferring 10GB snapshots will lead to poor MTRR.
