### ISSUE TITLE
tls: found a certificate rather than a key in the PEM for the private key

### ISSUE THREAD

**Issue by shamalco** [coreos/etcd#7911]
I installed new SSL certificates on a cluster and etcd2 is throwing up errors. When I check the log I get the following error

`tls: found a certificate rather than a key in the PEM for the private key`

I regenerated the certificates a couple of times, but I can't figure out what is the error or what I am doing to cause it when self-generating the certs.

**Comment by gyuho** [comment]
It literally means your private key path points to cert, so error is returned from Go. How did you configure?

**Comment by shamalco** [comment]
Followed the documentation [https://coreos.com/etcd/docs/latest/etcd-live-http-to-https-migration.html](url)

This what is currently configured on host. And certs are place in /etc/ssl/etcd/

cat /etc/systemd/system/etcd2.service.d/30-certs.conf 
`[Service]
Environment="ETCD_CERT_FILE=/etc/ssl/etcd/hivemind0.pem"
Environment="ETCD_KEY_FILE=/etc/ssl/etcd/hivemind0.pem"
Environment="ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/ca.pem"
Environment="ETCD_CLIENT_CERT_AUTH=true"
Environment="ETCD_PEER_CERT_FILE=/etc/ssl/etcd/hivemind0.pem"
Environment="ETCD_PEER_KEY_FILE=/etc/ssl/etcd/hivemind0-key.pem"
Environment="ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/ca.pem"
Environment="ETCD_PEER_CLIENT_CERT_AUTH=true"`

/etc/systemd/system/etcd2.service.d/40-tls.conf 
`[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=https://172.16.0.2:2379"
Environment="ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379"
Environment="ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380"`

/run/systemd/system/etcd2.service.d/20-cloudinit.conf 
`[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://172.16.0.2:2379"
Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://172.16.0.2:2380"
Environment="ETCD_INITIAL_CLUSTER=borg0=http://172.16.0.4:2380,borg1=http://172.16.0.5:2380,hivemind0=http://172.16.0.2:2380"
Environment="ETCD_INITIAL_CLUSTER_STATE=new"
Environment="ETCD_INITIAL_CLUSTER_TOKEN=collection"
Environment="ETCD_LISTEN_CLIENT_URLS=http://172.16.0.2:2379,http://127.0.0.1:2379"
Environment="ETCD_LISTEN_PEER_URLS=http://172.16.0.2:2380"
Environment="ETCD_NAME=hivemind0"`

**Comment by gyuho** [comment]
@shamalco `ETCD_KEY_FILE=/etc/ssl/etcd/hivemind0.pem" ` seems wrong? Try ETCD_KEY_FILE=/etc/ssl/etcd/hivemind0-key.pem" if `hivemind0-key.pem` is your key file.

**Comment by shamalco** [comment]
Wow how did I miss that *face-plant ... Thanks gyuho much appreciated
