### ISSUE TITLE
 x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by spirrello** [coreos/etcd#7912]
Hi,

I'm seeing the following messages when checking the cluster health.  All of my certs are legit using CFSSL - am I missing something in my service file?

**etcd version: 3.1.4
OS: Ubuntu 16.04 LTS**

failed to check the health of member 42845de23d1c2672 on https://10.155.9.171:2379: Get https://10.155.9.171:2379/health: x509: certificate signed by unknown authority
member 42845de23d1c2672 is unreachable: [https://10.155.9.171:2379] are all unreachable
failed to check the health of member 6c3494ef1883a6e1 on https://10.155.9.175:2379: Get https://10.155.9.175:2379/health: x509: certificate signed by unknown authority
member 6c3494ef1883a6e1 is unreachable: [https://10.155.9.175:2379] are all unreachable

**However, if I curl and reference the same information, I get a positive response.**
curl https://10.155.9.171:2379/health --cacert /opt/acme/certs/ca.pem
{"health": "true"}

**root@at4d-lvk8se01:~# cat /etc/systemd/system/etcd.service**
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
Type=notify
ExecStart=/usr/bin/etcd --name at4d-lvk8se01 \
  --cert-file=/opt/acme/certs/kubernetes.pem \
  --key-file=/opt/acme/certs/kubernetes-key.pem \
  --peer-cert-file=/opt/acme/certs/kubernetes.pem \
  --peer-key-file=/opt/acme/certs/kubernetes-key.pem \
  --peer-trusted-ca-file=/opt/acme/certs/ca.pem \
  --initial-advertise-peer-urls https://10.155.9.169:2380 \
  --listen-peer-urls https://10.155.9.169:2380 \
  --listen-client-urls https://10.155.9.169:2379,http://127.0.0.1:2379 \
  --advertise-client-urls https://10.155.9.169:2379 \
  --initial-cluster-token 8asdasdfasdf12!! \
  --initial-cluster at4d-lvk8se01=https://10.155.9.169:2380,at4d-lvk8se02=https://10.155.9.170:2380,at4d-lvk8se03=https://10.155.9.171:2380,at4d-lvk8se04=https://10.155.9.174:2380,at4d-lvk8se05=https://10.155.9.175:2380 \
  --initial-cluster-state new \
  --data-dir=/opt/etcd \
  --peer-client-cert-auth=true \
  --debug=true \
  --log-output=stdout \
  --metrics extensive
NotifyAccess=all
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**root@at4d-lvk8se01:~# openssl x509 -in /opt/acme/certs/kubernetes.pem -text -noout**
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            17:fb:06:44:ee:a6:ef:82:f2:35:b6:c4:93:88:da:8c:dd:9e:55:0a
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Georgia, L=Alpharetta, O=acme Technologies, OU=GA, CN=Kubernetes
        Validity
            Not Before: May 11 16:02:00 2017 GMT
            Not After : May  9 16:02:00 2027 GMT
        Subject: C=US, ST=Georgia, L=Alpharetta, O=acme Technologies, OU=at4d-dev3, CN=kubernetes
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier:
                98:C3:60:45:AA:B4:64:9A:FA:07:B4:6C:A3:9A:9B:B2:D0:2B:96:BE
            X509v3 Authority Key Identifier:
                keyid:A2:39:3D:CB:84:EE:60:62:6D:02:B0:66:2F:06:2E:F1:C5:C7:41:B9

            X509v3 Subject Alternative Name:
                DNS:*.acme, DNS:*.paas.acme, DNS:*.paas.acme.dev, DNS:*.acme.dev, DNS:acme.dev, IP Address:10.155.9.169, IP Address:10.155.9.170, IP Address:10.155.9.171, IP Address:10.155.9.174, IP Address:10.155.9.175, IP Address:10.155.9.166, IP Address:10.155.9.167, IP Address:10.155.9.168
    Signature Algorithm: sha256WithRSAEncryption

**Comment by spirrello** [comment]
This show's my certificate is validated.

openssl verify -verbose -CAfile ca.pem kubernetes.pem
kubernetes.pem: OK

**Comment by gyuho** [comment]
> failed to check the health of member 

What was the `etcdctl` command to get this error?

**Comment by spirrello** [comment]
I used etcdctl cluster-health. Thanks for responding so quickly.

**Comment by gyuho** [comment]
@spirrello I think it's missing the `--trusted-ca-file` flag if the client certs are self-signed as well.

**Comment by spirrello** [comment]
I'll try that now.

**Comment by spirrello** [comment]
Same results.

root@at4d-lvk8se01:~# cat /etc/systemd/system/etcd.service
[Unit]
Description=etcd
Documentation=https://github.com/coreos

[Service]
Type=notify
ExecStart=/usr/bin/etcd --name at4d-lvk8se01 \
  --trusted-ca-file=/opt/acme/certs/ca.pem \
  --cert-file=/opt/acme/certs/kubernetes.pem \
  --key-file=/opt/acme/certs/kubernetes-key.pem \
  --peer-cert-file=/opt/acme/certs/kubernetes.pem \
  --peer-key-file=/opt/acme/certs/kubernetes-key.pem \
  --peer-trusted-ca-file=/opt/acme/certs/ca.pem \
  --initial-advertise-peer-urls https://10.155.9.169:2380 \
  --listen-peer-urls https://10.155.9.169:2380 \
  --listen-client-urls https://10.155.9.169:2379,http://127.0.0.1:2379 \
  --advertise-client-urls https://10.155.9.169:2379 \
  --initial-cluster-token 8asdasdfasdf12!! \
  --initial-cluster at4d-lvk8se01=https://10.155.9.169:2380,at4d-lvk8se02=https://10.155.9.170:2380,at4d-lvk8se03=https://10.155.9.171:2380,at4d-lvk8se04=https://10.155.9.174:2380,at4d-lvk8se05=https://10.155.9.175:2380 \
  --initial-cluster-state new \
  --data-dir=/opt/etcd \
  --peer-client-cert-auth=true \
  --debug=true \
  --log-output=stdout \
  --metrics extensive
NotifyAccess=all
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target

**root@at4d-lvk8se01:~# etcdctl cluster-health**
failed to check the health of member 42845de23d1c2672 on https://10.155.9.171:2379: Get https://10.155.9.171:2379/health: x509: certificate signed by unknown authority
member 42845de23d1c2672 is unreachable: [https://10.155.9.171:2379] are all unreachable
failed to check the health of member 6c3494ef1883a6e1 on https://10.155.9.175:2379: Get https://10.155.9.175:2379/health: x509: certificate signed by unknown authority
member 6c3494ef1883a6e1 is unreachable: [https://10.155.9.175:2379] are all unreachable
failed to check the health of member 7cc476042dbc92b1 on https://10.155.9.170:2379: Get https://10.155.9.170:2379/health: x509: certificate signed by unknown authority
member 7cc476042dbc92b1 is unreachable: [https://10.155.9.170:2379] are all unreachable
failed to check the health of member 993c5eab2b144374 on https://10.155.9.169:2379: Get https://10.155.9.169:2379/health: x509: certificate signed by unknown authority
member 993c5eab2b144374 is unreachable: [https://10.155.9.169:2379] are all unreachable
failed to check the health of member bf981892445135ef on https://10.155.9.174:2379: Get https://10.155.9.174:2379/health: x509: certificate signed by unknown authority
member bf981892445135ef is unreachable: [https://10.155.9.174:2379] are all unreachable
cluster is unhealthy

**Comment by gyuho** [comment]
> etcdctl cluster-health

You need to specify your certs when running `cluster-health`

**Comment by spirrello** [comment]
That did it!  Thanks!!!!

**Comment by FurkanVural** [comment]
what did u add to the etcd.service file? I'm new to these issues and I can't understand.
