### ISSUE TITLE
Make maxRequestBytes configurable

### ISSUE THREAD

**Issue by xichen2020** [coreos/etcd#7923]
cc @xiang90 

We've been using etcd to maintain config data. On average the size of each value is a few hundred KB, but some large values can go up to a few MBs. Recently during our load testing we discovered that there is a [1.5 MB hard limit](https://github.com/coreos/etcd/blob/d3456b5ecdd58ea96edbf83e37e9bea6804e0020/etcdserver/v3_server.go#L38) on the maximize value size for a given key. Can we make this limit configurable so we can possibly provide a different limit (slightly larger than 1.5 MB) if needed?

Our write qps is relatively low and it's okay if the requests are blocked when large keys are persisted.

**Comment by xiang90** [comment]
@xichen2020 We will add the support for this in 3.3.0

**Comment by xichen2020** [comment]
@xiang90 Ah brilliant, do you know the rough ETA for the 3.2.0 and 3.3.0 release by any chance?
