### ISSUE TITLE
Auth function performs not as expected.

### ISSUE THREAD

**Issue by regardfs** [coreos/etcd#7929]
#### below is my step, you could reproduce by following this:
Already enable auth！！！
> #etcdctl --username root:rootps role add foos(Role foos created)
#etcdctl --username root:rootps role  list
foos
guest
root
#etcdctl --username root:rootps user add foos
#etcdctl --username root:rootps user grant --roles foos foos
#etcdctl --username root:rootps  role  revoke/grant --path /foos/* -read  foos
#curl -u foos:123  http://127.0.0.1:2379/v2/keys/foos/test
{"action":"get","node":{"key":"/foos/test","value":"test","modifiedIndex":50,"createdIndex":50}}
#curl -u foos:123 -XPUT http://127.0.0.1:2379/v2/keys/foos/test -d value="test"
{"errorCode":110,"message":"The request requires user authentication","cause":"Insufficient credentials","index":0}
#curl -XPUT http://127.0.0.1:2379/v2/keys/foos/test -d value="test"
{"action":"set","node":{"key":"/foos/test","value":"test","modifiedIndex":50,"createdIndex":50}}

look！！！ It is very funny，I want only permit given user to access my key dir， but none user provided could also access my key and set it，Is it a bug？@xiang90

**Comment by regardfs** [comment]
@heyitsanthony ，please CC

**Comment by heyitsanthony** [comment]
@regardfs it looks OK?

I started with a fresh etcd cluster and created `foos` with read access to `foos/*`
```sh
[anthony@etcd]$ ./bin/etcdctl user add root:root
User root created
[anthony@etcd]$ ./bin/etcdctl auth enable
Authentication Enabled
[anthony@etcd]$ ./bin/etcdctl --username root:root role add foos
Role foos created
[anthony@etcd]$ ./bin/etcdctl --username root:root user add foos:foos
User foos created
[anthony@etcd]$ ./bin/etcdctl --username root:root user grant --roles foos foos
User foos updated
[anthony@etcd]$ ./bin/etcdctl --username root:root role grant --path /foos/* -read foos
Role foos updated
```

fetching under foos/* works:
```
[anthony@etcd]$ curl -u foos:foos localhost:2379/v2/keys/foos/test
{"errorCode":100,"message":"Key not found","cause":"/foos","index":14}
```

fetching something outside of foos*/ fails:
```
[anthony@etcd]$ curl -u foos:foos localhost:2379/v2/keys/fo
{"errorCode":110,"message":"The request requires user authentication","cause":"Insufficient credentials","index":0}
```

writing under foos/* fails since the foos role only has read-only permissions:
```
[anthony@etcd]$ curl -XPUT -dvalue='abc' -u foos:foos localhost:2379/v2/keys/foos/test
{"errorCode":110,"message":"The request requires user authentication","cause":"Insufficient credentials","index":0}
[anthony@etcd]$
```

do you have more specific steps for reproducing the issue?

**Comment by regardfs** [comment]
@heyitsanthony , hi, yes all good with provided user, but if u do not provide user , just run:

> "curl -XPUT -dvalue='abc' localhost:2379/v2/keys/foos/test" 

it also run as success.
Does it make sense？with auth enable，I thought only provided user could do these tasks，if we do not provide any user，anything would be forbidden.

**Comment by heyitsanthony** [comment]
@regardfs try revoking the guest permissions:
`etcdctl --username root:root role revoke guest --readwrite --path=/*`

**Comment by regardfs** [comment]
@heyitsanthony thanks ! I will close this issue
