### ISSUE TITLE
How can i redirect etcd log to file?

### ISSUE THREAD

**Issue by dearboll** [coreos/etcd#7936]
Here is just 3 params about logging flag, --debug, --log-package-levels and --log-output. How can i redirect etcd log to file? Thank you for your attention.

**Comment by heyitsanthony** [comment]
@dearboll have you tried redirecting stderr to a file?
```sh
./bin/etcd 2>log.txt
```

**Comment by dearboll** [comment]
I use systemd to manage my etcd process, which params will help to do that ? @heyitsanthony

**Comment by gyuho** [comment]
If you run with systemd, all logs are handled via journald. You can do something like

```
journalctl -u YOUR_SERVICE.service -l --no-pager|less
```

**Comment by dearboll** [comment]
@gyuho  Thanks. 
I wanna specify the log file for etcd to do some log process, rather than all in syslog. So etcd cannot specify a log file ?

**Comment by gyuho** [comment]
@dearboll etcd has no option to specify a log file, because it can be done without it (unix pipes, journald). You can store `journald` logs on disk with

```
[Journal]
Storage=persistent
```

And do the log processing
