### ISSUE TITLE
how to put a key with ttl or expiration

### ISSUE THREAD

**Issue by 756445638** [coreos/etcd#7940]
I am using etcd for healthcheck and service discover.
I don`t know how create a key with ttl or expiration.

my code is blow..
func Reporter(status *healthcheck.NodeStatus) error {
	if cli == nil {
		err := InitEtcdClient()
		if err != nil {
			return err
		}
	}
	ctx, _ := context.WithTimeout(context.Background(), timeout)
	key := healthcheck.NODE_STATUS_PREFIX + status.NodeId.ID
	bs, _ := json.MarshalIndent(status, "", "\t")
	value := string(bs)
	//log.Tracef("put:key[%v] value[%v]\n", key, value)
	_, err := cli.Put(ctx, key, value)
	if err != nil {
		cli.Close()
		cli = nil
		return err
	}
	return nil
}

**Comment by gyuho** [comment]
You can try https://godoc.org/github.com/coreos/etcd/clientv3#example-Lease--Grant.

**Comment by 756445638** [comment]
thanks..

**Comment by novalagung** [comment]
FYI, since the mod name of ETCD source code is changed. here is the updated link https://pkg.go.dev/go.etcd.io/etcd/clientv3#example-Lease-Grant
