### ISSUE TITLE
etcdctl get error:  context deadline exceeded

### ISSUE THREAD

**Issue by garyyang85** [coreos/etcd#7950]
I am using kubernetes + etcd 3.0.17, now encountered such issue: 
when I run "kubectl get node" , it always returns error with about more than 50 percent:  "error from server: rpc error: code = 14 desc = etcdserver: request timed out"
when I run the etcd cmd "etcdctl get /registry/minions/xx", it always return with about more than 50 percent: "context deadline exceeded"
I looked into the etcd log, but seems not any clue, the etcd server logs are all bellow lines:
May 18 15:47:06 kvm-009660.novalocal docker[22970]: 2017-05-18 07:47:06.357980 W | etcdserver: avoid queries with large range/delete range!
May 18 15:47:07 kvm-009660.novalocal docker[22970]: 2017-05-18 07:47:07.863538 W | etcdserver: apply entries took too long [1.265482337s for 3 entries]

could you help me about this. I googled some issues like below with the same error output "context deadline exceeded", but now sure if it is the same issue. Thanks.
https://github.com/coreos/etcd/issues/7739

**Comment by gyuho** [comment]
> etcdserver: apply entries took too long

Is it running on slow disk?

Also see https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-apply-entries-took-too-long-mean.

**Comment by gyuho** [comment]
@garyyang85 Ping?

**Comment by garyyang85** [comment]
should be a slow storage issue...after change to a new disk, it works fine.
