### ISSUE TITLE
what is the disk requirements of etcd?

### ISSUE THREAD

**Issue by HardySimpson** [coreos/etcd#7960]
have seen the disk [requirements here](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/hardware.md#disks)

>etcd is very sensitive to disk write latency. Typically 50 sequential IOPS (e.g., a 7200 RPM disk) is required. For heavily loaded clusters, 500 sequential IOPS (e.g., a typical local SSD or a high performance virtualized block device) is recommended. Note that most cloud providers publish concurrent IOPS rather than sequential IOPS; the published concurrent IOPS can be 10x greater than the sequential IOPS. To measure actual sequential IOPS, we suggest using a disk benchmarking tool such as diskbench or fio.

so, when in the `Typically 50 sequential IOPS`, what is the input etcd API qps?

**Comment by heyitsanthony** [comment]
@HardySimpson QPS depends on the hardware and workload characteristics (e.g., concurrency, size of values, read/write ratio, size of txns). 

For example, on a 7200rpm drive here's a benchmark of QPS for a pure write workload as concurrency increases:
```
./tools/benchmark/benchmark --conns=$CONNS --clients=$CONNS --key-size=64 --val-size=64 --total=1000 put
```

Results:

CONNS | Average QPS
 --- | --- 
1 | 58
64 | 904
128 | 2453
256 |  4628


There's also a new `ETCDCTL_API=3 etcdctl check perf` command that can help confirm whether a cluster meets minimum performance for some simple performance models.

**Comment by xiang90** [comment]
> Typically 50 sequential IOPS

meaning ~50 writes if the number of concurrent client is 1. see @heyitsanthony's result for more details.

**Comment by HardySimpson** [comment]
Thanks, we will try to repeat the test on our VM

**Comment by xiang90** [comment]
closing.

**Comment by liurd** [comment]
In could environment, there is no local SSD. any way to improve ETCD performance, or not so disk sensitive? It's big suffering in cloud environment, always timeout.  Not every load have SSD.
