### ISSUE TITLE
Failed to build on Windows: fatal error: dlfcn.h: No such file or directory

### ISSUE THREAD

**Issue by hsluoyz** [coreos/etcd#7962]
Hi, I'm building etcd on Win10 x64. Go is latest 1.8.1. Dependencies are updated with glide. Then I got this ``dlfcn.h not found error``. How to solve it? Thanks!

```
"C:\Program Files (x86)\JetBrains\Gogland 171.3780.106\bin\runnerw.exe" C:/Go\bin\go.exe run C:/GoPath/src/github.com/coreos/etcd/main.go
# github.com/coreos/etcd/vendor/github.com/coreos/pkg/dlopen
vendor\github.com\coreos\pkg\dlopen\dlopen.go:21:20: fatal error: dlfcn.h: No such file or directory
 // #include <dlfcn.h>
                    ^
compilation terminated.

Process finished with exit code 2
```

```
C:\WINDOWS\system32>go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GoPath\
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\go-build429837135=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
```

**Comment by heyitsanthony** [comment]
@hsluoyz try building with `build.bat`?

**Comment by hsluoyz** [comment]
Hi @heyitsanthony ,

Building with ``build.bat`` seems to be OK. But I still want to build it in the Gogland IDE, so I can debug in the IDE too. I have seen ``build.bat``, and it calls ``build.ps1``. And this powershell script at last calls:

```powershell
go build -a -installsuffix cgo -ldflags $GO_LDFLAGS -v -o bin\etcd.exe "$REPO_PATH\cmd\etcd"
```

However, when I manually call this go build command, I still encounter the dlfcn.h compile error. Do you know why? How to proceed to make etcd build on Gogland IDE on Windows?

**Comment by heyitsanthony** [comment]
@hsluoyz it could be failing because `go env` is defaulting to CGO_ENABLED=1; the build script uses CGO_ENABLED=0

**Comment by hsluoyz** [comment]
Hi @heyitsanthony ,

Setting ``CGO_ENABLED=0`` in the IDE build configuration fixed the issue. Thanks!

I still have one small issue here, do you know how to set ``CGO_ENABLED``'s default value to 0 globally for my OS? In my environment vairables, I only see ``GOPATH`` and ``GOROOT ``, I don't know where default values for other variables of ``go env`` are defined? So I can change them?

**Comment by heyitsanthony** [comment]
etcd issue solved; not providing windows go support here. Thanks!
