### ISSUE TITLE
when etcd v3 compact, the client get error: context deadline exceeded

### ISSUE THREAD

**Issue by lijianweia** [coreos/etcd#7971]
I use  etcd 3.0.15, there is a long time running.
The clients put a key per second, and I set compact per hour.
I found the client always get error " context deadline exceded" ,and in the same time etcd is compacting.
I guess the performance cause the problem.
Is there any suggestion?

**Comment by xiang90** [comment]
Can you reproduce this with a simulated workload generator?

**Comment by lijianweia** [comment]
Yes, but maybe a long time. Do you need the log?

**Comment by xiang90** [comment]
Yes. We need the log and a simple way to reproduce it.

**Comment by xiang90** [comment]
@lijianweia kindly ping.

**Comment by xiang90** [comment]
I am going to close this due to low activity. reopen if you still feel this issue is useful.
