### ISSUE TITLE
No s390x binary available

### ISSUE THREAD

**Issue by scheuran** [coreos/etcd#7978]
Etcd Binaries for a couple of architectures are provided for download on this github site , e.g. [1].
I'm missing a binary for s390x. What would need to be done to have one available here? Is it that just somebody needs to compile & upload it? Or does it require more, like a CI environment?

[1] https://github.com/coreos/etcd/releases/tag/v3.2.0-rc.1

**Comment by dims** [comment]
@scheuran looks like someone has to do what was done for ppc64 - https://github.com/coreos/etcd/issues/6818

**Comment by scheuran** [comment]
Ok, I'll have a look!

**Comment by scheuran** [comment]
Thanks!

**Comment by gyuho** [comment]
> Or does it require more, like a CI environment?

We are missing a lot of testing work on s390x and arm64. Those builds won't be in the actual release until we have enough testing. Sorry!

**Comment by duanedsouza** [comment]
Hey. I guess you could look at the following to try and build etcd to generate the binaries on s390x: https://github.com/linux-on-ibm-z/docs/wiki/Building-etcd

**Comment by scheuran** [comment]
Thanks for your reply. I'm aware of this side - the question is more how to make the binary hosted here. And the answer is: Provide a testing infrastructure.

The problem I'm facing is, that devstack (the OpenStack developer setup) is downloading etcd from this location... In devstack the problem gets solved once the distros have support for etcd3. until then we need a workaround - I was thinking of adding code to devstack that compiles etcd3, as I'm not in the position to provide s390x test nodes at the moment.

**Comment by duanedsouza** [comment]
Hey scheuran. Yes a CI setup would be needed to get the binary hosted. Just thought of providing you the steps to build etcd.

**Comment by glevand** [comment]
The first thing is to add s390x to the [travis file](https://github.com/coreos/etcd/blob/master/.travis.yml), then fix any travis failures.  Next would be to add a `Dockerfile-release.s390x` file and get the [release script](https://github.com/coreos/etcd/blob/master/scripts/release.sh) working.

**Comment by Nayana-ibm** [comment]
Created a new issue to add support for s390x for Etcd #9409

**Comment by gyuho** [comment]
Closing. If anyone wants us to build official release binaries, please contribute.
