### ISSUE TITLE
Use Casbin as the authorization module for etcd

### ISSUE THREAD

**Issue by hsluoyz** [coreos/etcd#7979]
Hi, I'm the creator of [Casbin](https://github.com/casbin/casbin). It is a Go authorization library that supports access control models like ACL, RBAC, ABAC. See details here: https://github.com/casbin/casbin

I noticed the etcd uses a RBAC model to do the authorization. However, I don't think it's flexible or enough secure. In terms of flexibility and security, Casbin will bring several advantages:

1. the current permissions can only be granted to roles, cannot directly granted to users. Sometimes this is inconvenient. Casbin supports assigning permissions to both roles and users.
2. the current RBAC doesn't support cascaded roles (aka only RBAC0), while in Casbin, roles can be cascaded, aka roles can have roles (so RBAC1 is supported).
3. Casbin also supports resource roles (or groups), so we can group some keys and use groups instead of resource keys in permission granting. This is useful when we have some important built-in keys that want to protect (for example, the keys used by Kubernetes), so we can define these keys into a group like ``built_in_keys``.
4. Current etcd only has two permissions (or actions): ``read`` and ``write``, and they are hard-coded in the code. Casbin supports customized actions, for example, the HTTP methods or CRUD or whatever. 
5. Currently ``root`` user and ``root`` role are hard-coded in the etcd, I don't think it's flexible and secure, because this ``root`` can do anything. Maybe a etcd user (like Kubernetes) wants to split the power into several admin users, one for user management, one for permission management and one can read/write all keys to inspect some errors. With current implementation, the etcd user (k8s team) has to modify the source code.
6. Current etcd only supports ``Allow`` authorization. While, Casbin can support both ``Allow`` and ``Deny``. In fact, you can use logical or math operators to express your authorization objective.
7. The resource prefix matching only supports ``*``. Casbin supports the resource matching via **regex**, so the user can write very flexible matching rules if he knows regex. (Casbin also supports the tradtional * matching).
8. the permission granting in Casbin can be persisted in files or database, or not persisted at all (just kept in memory), just dynamically modified with Casbin API. Of course, persistence for etcd's permission granting is never a problem and can just store in etcd itself. But Casbin just provides another option for the user to store the policy elsewhere. For example, storing the granting into file in the test stage to test the authorization is more convenient than storing them into the datastore, because files can be easily modified by hand.
9. Casbin supports a model description language to describe the access control model. So when etcd wants to update its model anytime (e.g., remove the root role or add some ABAC, attribute-based access control support), it will be as easy as modifying the model file, no need to change the code. Because Casbin already supports RBAC and ABAC, and also supports their mix.

So please consider using Casbin. Let me know if there's any question:)

**Comment by mitake** [comment]
@hsluoyz thanks for your suggestion and sorry for my reply. I'll check Casbin but it would take a time for a while because it is interesting but also difficult. Please feel free to ping me if you feel waiting too long :)

**Comment by hsluoyz** [comment]
Hi @mitake ,

Thanks for your reply! The model language is a new conception and may be difficult at the first glance, but the core idea is to define the matching rules between the access request and the policy rule, which makes it flexible.

There are many examples [here](https://github.com/casbin/casbin#examples), which shows what this library can do. I will try to make an example specifically for etcd scenario these days.

**Comment by hsluoyz** [comment]
Hi @mitake ,

I have made a PR about the Casbin auth store here: https://github.com/coreos/etcd/pull/8154

Casbin auth store reuses many functions provided by the original authStore, like user add/delete, role add/delete, authentication related (like password management). Casbin implements the functions mainly for user-role mapping, permission management and permission checking.

The current auth store mixes authentication (AuthN) and authorization (AuthZ) together. AuthN is about who you are (aka log-in), it can use HTTP basic authentication, OAuth, LDAP, etc. AuthZ is about what resource a logged-in user can access. AuthZ can choose to use ACL, RBAC, ABAC, etc. Casbin is only an authorization library. So it can't handle the password checking, and it doesn't maintain the list of users (so no way to add or delete a user), because that part belongs to authentication. So besides integrating Casbin, I also suggest we separate AuthN and AuthZ, maybe an authnStore and an authzStore. So this will be clearer and more convenient to develop alternative modules for different purposes (authn or authz).

I also made some tests in this PR, including features like wildcard (*), RBAC with multi-level inheritance, root support, etc. Other features like regex, ABAC, custom functions are not demonstrated in my test.

I think this shows that Casbin is more flexible in auth policy enforcement. Most of the etcd users are not end-users and they may have need to customize the authorization policy for etcd API. So I think Casbin can satisfy their need.

This PR still doesn't enable Casbin auth store by default. And the policy storage is still using file. I think it should finally use etcd itself for policy storage. I'm still learning the default auth store about its storage part. And I want to hear your advice first. Thanks!

**Comment by mitake** [comment]
@hsluoyz thanks a lot for your PR, it is very interesting. Providing the flexible authorization policy based on Casbin seems to be very valuable because the default authorization mechanism of etcd v3 is very simple (it is intentional. Complex mechanisms would be able to result unintentional authorization that makes users surprise). I'll review your PR next week because I have some work to do today.

BTW, do you have any suggested docs or papers that is helpful for understanding the design of Casbin?

**Comment by hsluoyz** [comment]
Hi @mitake these docs may be a help: 

1. The docs for Casbin: https://github.com/casbin/casbin
2. Docs for Casbin model language: https://github.com/casbin/casbin/blob/master/Model.md
3. Examples for different models: https://github.com/casbin/casbin#examples

Another question is that my PR still doesn't store policy in etcd itself as what the default auth store does. I still need to learn how to do that. If you have any suggestion for the policy storage, please let me know:)

**Comment by mitake** [comment]
@hsluoyz thanks for the pointers, I'll visit them.

For storing the Casbin policies in etcd, I suggest following how other auth related RPCs work (e.g. `UserAdd()`: https://github.com/coreos/etcd/blob/master/etcdserver/v3_server.go#L407). The auth related metadata is stored in their own buckets of `backend` like this: https://github.com/coreos/etcd/blob/master/auth/store.go#L907

Creating a special bucket for Casbin and adding new RPCs for manipulating it would be a good idea. If you have questions, please let me know.

**Comment by hsluoyz** [comment]
Hi @mitake ,

I have updated the PR: https://github.com/coreos/etcd/pull/8154. It stores the policy into etcd backend.

> For storing the Casbin policies in etcd, I suggest following how other auth related RPCs work (e.g. UserAdd(): https://github.com/coreos/etcd/blob/master/etcdserver/v3_server.go#L407).

The current Casbin auth store uses the same perm management API with the default auth store. So it does not require to change the server API for now. But it may be changed in future.

Here's the roadmap I planed personally, please advise:

1. Create the Casbin auth store, which uses the same permission management API with the default auth store. Make sure Casbin can provide at least the same capability as the original auth store.

2. Separate the authentication (AuthN) and authorization (AuthZ) in the default auth store, maybe via two stores: an AuthN store and an AuthZ store. This will serve as a good basis to replace the AuthZ-specific part with other libs like Casbin. So we can still use the original AuthN store after replacing the AuthZ store. (I don't know if this is a good idea?)

3. Make Casbin the default AuthZ store. This may need more test, because all users will use it now. (if this is not acceptable, I'm also OK with the current optional way. So any user who wants to use it can enable it in code or via an etcd API).

4. Enhance the authorization and provide more features based on the new Casbin authZ store, including enhancing the permission management API at etcdserver. And etcdctl can support the new perm mgmt commands too.

Please advise:)

> The auth related metadata is stored in their own buckets of backend like this: https://github.com/coreos/etcd/blob/master/auth/store.go#L907

A backet named ``casbinAuth`` is created to store the auth policies. But the Casbin model is still in file, because I think it's static and won't change at run-time. Is this OK? If not, I can also change to initialize the Casbin model in Golang code.

**Comment by mitake** [comment]
@hsluoyz sorry for my late response, I'll reply this wednesday possibly (your idea and PR are interesting but heavy ;)

**Comment by hsluoyz** [comment]
@mitake , thanks, let me know for any questions:)

**Comment by xiang90** [comment]
this is not active. we do not have any plan to make etcd auth more complicated at the moment. so closing.
