### ISSUE TITLE
etcdserver: mvcc: database space exceeded. help!!!!!!!!!!

### ISSUE THREAD

**Issue by 756445638** [coreos/etcd#7986]
I use etcd for healthcheck,one of the client(etcd client) will report his status once a second,I have run the program for couple of days,and I encounter with this error "etcdserver: mvcc: database space exceeded".
when I go through document,there is a concept about revisions for key,I think it is the reason why the space exceeded(I have too many revisons for one key) ,but I don`t know how put a key with revsion,I don`t how to control amount of revsion..

**Comment by 756445638** [comment]
my code. 
package etcd

import (
	"encoding/json"
	log "github.com/cihub/seelog"
	"github.com/coreos/etcd/clientv3"
	"golang.org/x/net/context"
	"hmi-server/common/healthcheck"
	"time"
)

var cli *clientv3.Client
var lease *clientv3.LeaseGrantResponse

func initEtcdClient() error {
	var err error
	cli, err = clientv3.New(clientv3.Config{
		Endpoints:   []string{"http://127.0.0.1:2379"},
		DialTimeout: time.Second,
	})
	if err != nil {
		return err
	}
	lease, err = cli.Grant(context.TODO(), 60*60) //grand lease for an hour
	if err != nil {
		closeClient()
		return err
	}
	panic(lease.TTL)
	return err

}

func closeClient() {
	if cli != nil {
		cli.Close()
		cli = nil
	}
}

var (
	putcontext context.Context
	timeout    = time.Second
)

func Reporter(status *healthcheck.NodeStatus) error {
	if cli == nil {
		err := initEtcdClient()
		if err != nil {
			return err
		}
	}
	ctx, _ := context.WithTimeout(context.Background(), timeout)
	key := healthcheck.NODE_STATUS_PREFIX + status.NodeId.ID
	bs, _ := json.MarshalIndent(status, "", "\t")
	value := string(bs)
	log.Tracef("put:key[%v] value[%v]\n", key, value)
	_, err := cli.Put(ctx, key, value, clientv3.WithLease(lease.ID))
	if err != nil {
		closeClient()
		return err
	}
	return nil
}

**Comment by heyitsanthony** [comment]
@756445638 etcd needs to be periodically [compacted](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#history-compaction) to truncate its history. etcd will check if its db exceeds a space quota limit, in which case it'll throw this error. To recover from this error first compact etcd, then defragment, then finally disarm the quota alarm. The [space quota](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota) documentation has an example.

To avoid having to manually compact with etcdctl, etcd also accepts the flag `--auto-compaction` which will periodically compact the store.

**Comment by 756445638** [comment]
ok,thank you very much!!

**Comment by heyitsanthony** [comment]
OK, closing. Please reopen if this is still an issue.
