### ISSUE TITLE
Deprecated Keys

### ISSUE THREAD

**Issue by namsoila** [coreos/etcd#8001]
I am trying to use a cloud config file to start etcd using version 3.*. Most cloud config files  even in the example here (updated April 20):

https://github.com/coreos/docs/blob/master/etcd/etcd-live-cluster-reconfiguration.md

Have values such as:

`advertise_client_urls: http://<PEER_ADDRESS>:2379
  initial_advertise_peer_urls: http://<PEER_ADDRESS>:2380
  listen_client_urls: http://0.0.0.0:2379,http://0.0.0.0:4001
  listen_peer_urls: http://0.0.0.0:2380
`

But when I try use the coreos online validator:

https://coreos.com/validate/

I get errors:

deprecated key "initial_advertise_peer_urls" (etcd2 options no longer work for etcd)
deprecated key "listen_client_urls" (etcd2 options no longer work for etcd)
deprecated key "listen_peer_urls" (etcd2 options no longer work for etcd)
deprecated key "advertise_client_urls" (etcd2 options no longer work for etcd)

Am I just supposed to ignore the validation? Should I use etcd2 in the cloud config file so that they validate and then use export ETCDCTL_API=3?

**Comment by namsoila** [comment]
For example, here in when running the flannel backend on GCE, what would be the equivalent command for:

'etcd2 -advertise-client-urls http://$INTERNAL_IP:2379 -listen-client-urls http://0.0.0.0:2379'

**Comment by namsoila** [comment]
Solved by using etcd-member.service with the following drop in:

[Service]
Environment="ETCD_ADVERTISE_CLIENT_URLS=http://$INTERNAL_IP:2379"
Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"

Running that service to start etcd v3 cluster then:

ETCDCTL_API=3 etcdctl set /coreos.com/network/config '{"Network":"10.40.0.0/16", "Backend": {"Type": "gce"}}'

Acquires subnet least with latest version of flannel.

**Comment by krish512** [comment]
I tried to update the /usr/lib/systemd/system/etcd-member.service to add listen_client_urls and other variables but the file is readonly. Tried via root user as well. The file permission is 544, owner and group is root:root

Anyone facing similar issue?
