### ISSUE TITLE
running etcd under rkt exit with error code1 

### ISSUE THREAD

**Issue by zozo6015** [coreos/etcd#8014]
Trying to run etcd under rkt with discovery enabled running on debian jessie. The installed version of rkt is 1.26.0. I am starting the command using the following: 

```
sudo rkt run --net=host \
--dns=8.8.8.8 \
--hostname=$(hostname)
--set-env=ETCD_INITIAL_ADVERTISE_PEER_URLS=http://$IP:2380 \
--set-env=ETCD_DISCOVERY=https://discovery.etcd.io/288a4e442099920f5e99cbb7dde68d09 \
--set-env=ETCD_LISTEN_PEER_URLS=http://$IP:2380 \
--set-env=ETCD_LISTEN_CLIENT_URLS=http://$IP:2379,http://127.0.0.1:2379 \
--set-env=ETCD_ADVERTISE_CLIENT_URLS=http://$IP:2379 \
--set-env=ETCD_NAME=$(hostname)-etcd-cluster coreos.com/etcd:v3.1.8 \
--debug=true
```

The output can be found in the attached file: 
[etcd-output.txt](https://github.com/coreos/etcd/files/1043255/etcd-output.txt)

Anyone can help with these?

**Comment by xiang90** [comment]
i did not see any etcd related log. if this is a rkt issue, probably you should open an issue in rkt repo.

**Comment by zozo6015** [comment]
Unforunately rkt does not give any logs, But this is definatly an etcd issue since if I change the etcd version to 2.0.0 everything works. But my apps need me to run v3.x

**Comment by zozo6015** [comment]
I have started the rkt via systemd-run with the following command:

```
systemd-run \
--slice=machine \
--unit=etcd3 \
rkt run \
--net=host \
--dns=8.8.8.8 \
--hostname=$(hostname) \
--set-env=ETCD_INITIAL_ADVERTISE_PEER_URLS=http://$IP:2380 \
--set-env=ETCD_DISCOVERY=http://54.215.153.3/288a4e442099920f5e99cbb7dde68d09 \
--set-env=ETCD_LISTEN_PEER_URLS=http://$IP:2380 \
--set-env=ETCD_LISTEN_CLIENT_URLS=http://$IP:2379,http://127.0.0.1:2379 \
--set-env=ETCD_ADVERTISE_CLIENT_URLS=http://$IP:2379 \
--set-env=ETCD_NAME=$(hostname)-etcd-cluster \
--set-env=ETCD_DATA_DIR=$(hostname) coreos.com/etcd:v3.1.8 \
--debug=true -- --log-output=stderr
```

and I get the following output including the etcd logs attached in the file:

[etcd-output.txt](https://github.com/coreos/etcd/files/1044585/etcd-output.txt)

**Comment by zozo6015** [comment]
Nevermind, I have started all 3 nodes using the command above and they have started correctly.
