### ISSUE TITLE
Adding guidance of configuring compaction related parameters

### ISSUE THREAD

**Issue by mitake** [coreos/etcd#8018]
I did some performance evaluation and found that too short compaction is harmful for throughput but too long compaction also degrades throughput. The result can be found in page 49 to 51 of https://www.slideshare.net/mitakeh/understanding-performance-aspects-of-etcd-and-raft

Based on profiling with pprof, I found that some functions related to memory allocation and garbage collection (e.g. `runtime.mallocgc` and `runtime.scanobject`) are consuming much more cycles when the compaction interval becomes larger. It can be considered that the mark phase of GC becomes heavy because of the increased number of live objects (in this case, `raft.MemoryStorage.ents` would be a dominating object).

Although the difference is not so significant, adding guideline for performance tuning would be helpful because the long interval is not good for memory consumption and CPU cycles.

/cc @xiang90 @heyitsanthony this is what I talked today

**Comment by gyuho** [comment]
@mitake  Link is broken?

**Comment by mitake** [comment]
@gyuho really? I could see the link even without login to slideshare. Did you see 404?

**Comment by fanminshi** [comment]
@gyuho link works for me

**Comment by heyitsanthony** [comment]
Related: #7607

**Comment by mitake** [comment]
@fanminshi thanks for checking!
@gyuho if you still see the problem, please let me know.
