### ISSUE TITLE
No documentation on how to authenticate clients based on Common Name

### ISSUE THREAD

**Issue by jesseendahl** [coreos/etcd#8020]
It doesn't look like the documentation ever got completed for how to use the feature implemented in #6881 (authenticating clients based on the `CN` field within their TLS client certificate). I've checked all the related issues, such as #7251 and #3916 and couldn't find anything. I did find a comment from @mitake [here](https://github.com/coreos/etcd/pull/3916#issuecomment-283359359) where mentioned he was going to work on it soon, but that's where the trail seems to go cold.

**Comment by mitake** [comment]
@jesseendahl it is already documented here: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/authentication.md#using-tls-common-name
you can use the feature with `--client-cert-auth=true`.

**Comment by jesseendahl** [comment]
@mitake thank you! For what it's worth, in addition to checking those Github issues, I'd also checked this page https://coreos.com/etcd/docs/latest/op-guide/security.html and found no mention of the feature, even under the two examples involving client cert authentication:

[Example 2: Client-to-server authentication with HTTPS client certificates](https://coreos.com/etcd/docs/latest/op-guide/security.html#example-2-client-to-server-authentication-with-https-client-certificates)

[Example 3: Transport security & client certificates in a cluster](https://coreos.com/etcd/docs/latest/op-guide/security.html#example-3-transport-security--client-certificates-in-a-cluster)

Anyway thanks again!

**Comment by mitake** [comment]
@jesseendahl no problem. If you have suggestions about the docs, please pointing out or send PRs.

**Comment by jesseendahl** [comment]
@mitake I don't this any PR is needed, since your documentation looks good. But for some reason there is no "Authentication guide" page for v3 accessible from https://coreos.com/etcd/docs/latest/

Since the v2 page is accessible at https://coreos.com/etcd/docs/latest/v2/authentication.html

And since the security page is available at https://coreos.com/etcd/docs/latest/op-guide/security.html

I expected the v3 "Authentication guide" page to be available at https://coreos.com/etcd/docs/latest/op-guide/authentication.html

But there is nothing at that URL, and no link to it from the [main docs page](https://coreos.com/etcd/docs/latest/).

Here's a screenshot of the v2 section. You can see that there are links to 3 pages, one of which is the v2 Authentication Guide.

![image](https://cloud.githubusercontent.com/assets/251066/26720420/11bc4ac0-473d-11e7-841e-0763d2767678.png)

Now here's the section for v3:

![image](https://cloud.githubusercontent.com/assets/251066/26720445/2c9ae752-473d-11e7-83b7-caafa07d9914.png)

I'm happy to do whatever work is required to get this updated on the website, but even after extensive searching I couldn't find any information on how the docs website gets updated/built/released.

**Comment by heyitsanthony** [comment]
@jesseendahl etcd side is fixed up (which will eventually get pulled into security.html), so closing. Please file an issue on https://github.com/coreos/docs/issues for the website menu. Thanks!
