### ISSUE TITLE
Is there storage size limit in etcd V2?

### ISSUE THREAD

**Issue by dongxiaojiehit** [coreos/etcd#8021]
# Storage size limit in V2
Storage size limit supports up to 8GB in etcd V3(https://coreos.com/etcd/docs/latest/dev-guide/limit.html), Is there a limit in etcd v2?

**Comment by xiang90** [comment]
yes. no more than 200MB normally: https://github.com/coreos/etcd/blob/master/Documentation/v2/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md#data-size-threshold
