### ISSUE TITLE
api: grpc health checking service

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8022]
See: https://github.com/grpc/grpc/blob/master/doc/health-checking.md

There are cases where the client needs to know that the server is responding to requests. If the server is not responding (but possibly still accepting connections), the balancer should try another endpoint. For instance, a watch may be disconnected but the connection will stay open and hang instead of connecting to another member.

via https://groups.google.com/d/msg/etcd-dev/N6DLgT9rl-M/LTp6j2XNAAAJ
additional grpc context https://groups.google.com/forum/#!topic/grpc-io/69k_6HKVai0

**Comment by heyitsanthony** [comment]
Related: #7321

This heartbeat mechanism is somewhat weaker in that it doesn't need a leader, but there still needs to be some kind of polling to avoid waiting indefinitely on a disconnected socket. The client implementations for heartbeat/lost leader reconnect can both poll or lost leader can depend on heartbeat to cover the wait case.

**Comment by xiang90** [comment]
move this to 3.4

**Comment by gyuho** [comment]
Moving to https://github.com/coreos/etcd/issues/8673, since it also needs client-side work.
