### ISSUE TITLE
how to get lease id?

### ISSUE THREAD

**Issue by jeremywu0127** [coreos/etcd#8030]
when I execute `etcdctl lease timetolive`, it requires the id of lease , so how can I get the id of lease?

**Comment by xiang90** [comment]
how did you create the lease?

**Comment by jeremywu0127** [comment]
I didn't create it manually, it's created by `flannel` automatically.

**Comment by heyitsanthony** [comment]
@jeremywu0127 I don't think flannel uses v3 leases, so `etcdctl lease timetolive` won't get the ttl for that. Have you tried https://github.com/coreos/flannel/blob/master/Documentation/reservations.md?

**Comment by xiang90** [comment]
as @heyitsanthony mentioned, flannel does not use etcd3. so closing.

if you want to know the lease status, you have to know the lease id first. lease id is returned when you create it.
