### ISSUE TITLE
BoltDB - syscall.MAP_POPULATE

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#8032]
What are your thoughts on making this optional?  I don't think it always makes sense to do this.

https://github.com/coreos/etcd/blob/31e3899663522556e06933297e12fd030efae488/mvcc/backend/config_linux.go#L30

**Comment by xiang90** [comment]
when it is not good to do this?

**Comment by davissp14** [comment]
Anytime you may be running multiple Etcds on a single host.  

Correct me if I am wrong, but looking at the comments: 

> enable MAP_POPULATE for faster key-value store recovery in storage  package.

 This is trading additional upfront memory utilization for a faster recovery process?  If that's the case, wouldn't that be use-case driven?

**Comment by heyitsanthony** [comment]
If there's no significant performance gain it can be removed. It could possibly blow out the cache when a regular boltdb recovery wouldn't (will boltdb scan on boot?). I'd rather not have this as an option since it's relatively minor; either etcd should prepopulate or it shouldn't. Is this prepopulation causing a problem on your end @davissp14?

**Comment by xiang90** [comment]
> If there's no significant performance gain it can be removed. 

There is a HUGE performance gain for large backups. Like reducing reload from 5 minute to 30s if I remember correctly.

**Comment by davissp14** [comment]
I just stumbled across this today when trying to figure out why VmRSS was reporting higher than expected.  This pre-population was the cause.   The big concern outside of making our auto-scaling bits difficult :) was like you said, blowing out the cache in a resource constrained environment.

**Comment by xiang90** [comment]
@davissp14 

You should expect etcd to take 2x actual data as RSS. I do not feel we should optimize that. The primary goal of etcd is to be reliable and provide predictable latency. The way to get that is serving anything from memory directly and batch writes.

**Comment by davissp14** [comment]
https://github.com/boltdb/bolt/blob/e9cf4fae01b5a8ff89d0ec6b32f0d9c9f79aefdd/bolt_unix.go#L50

Given this is shared memory in the page cache it should be sent to LRU during memory contention right?  Just want to confirm my understanding of this.

**Comment by xiang90** [comment]
yes. if there is a contention

**Comment by davissp14** [comment]
Great, thanks guys.  Gonna close this out.
