### ISSUE TITLE
proper way to limit snapshot size

### ISSUE THREAD

**Issue by sergik** [coreos/etcd#8036]
I have an etcd cluster which creates ~50 revisions every 30 seconds. So if I create snapshot it growth in 20mb every hour. What is the proper way to compact revisions log? Especially I am interested in some automatic configuration option(not manually calling a etcdctl compact).

**Comment by heyitsanthony** [comment]
@sergik Have you tried `--auto-compaction-retention`? https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#history-compaction

**Comment by sergik** [comment]
yes, sure. Set it to 1 so according to docs it should start work after 1h. Waited for about 2h but snapshot size still grow liner.

**Comment by heyitsanthony** [comment]
@sergik compacting should reclaim the space. Could be a bug, I'll need more information:
* version of etcd?
* etcd server logs around the auto compaction?
* how much does the snapshot grow versus what is expected?
* does manually compacting stop the snapshot from growing?
* how much time does `ETCDCTL_API=3 etcdctl snapshot save` take to complete?
* what is the output for  `ETCDCTL_API=3 etcdctl -w table endpoint status`?

Thanks!

**Comment by sergik** [comment]
- Update version to 3.1.8
- Looks like autocompaction executed and snapshot stoped growth in time
- We store around 50kb of data snapshot growth per 20mb every hour
- Manual compaction helps
- Depends from current snapshot size

/ # ETCDCTL_API=3 etcdctl -w table endpoint status
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | a4620f0f74fe9708 | 3.1.8   | 21 MB   | false     |         8 |      46785 |
+----------------+------------------+---------+---------+-----------+-----------+------------+
 Is there way to perform auto defragmentation as well? To small down snapshot size after compaction?

**Comment by xiang90** [comment]
> Is there way to perform auto defragmentation as well? To small down snapshot size after compaction?

etcd db size should be stabilizing after 16MB. You should expect it take up to 2x space.

In your case, why do you care about if it takes 16MB or 500B? Is there a visible difference to you? The WAL file already can take up more than 300MB by default. And we do not have any plan to make it size down.

**Comment by heyitsanthony** [comment]
> Looks like autocompaction executed and snapshot stoped growth in time

So is auto-compaction working, then? Does that mean the snapshot size stabilizes?

I'm not sure if auto-defrag can solve much since if the db size periodically bloats up, it'll still bloat up after defrag to whatever the steady state happens to be. What's the advantage?

**Comment by xiang90** [comment]
Closing due to low activity. Reopen if this is still a problem.
