### ISSUE TITLE
panic when running benchmark tool for watch: 

### ISSUE THREAD

**Issue by SuhasAnand** [coreos/etcd#8056]
What:
panic: send on closed channel

Details:
goroutine 101452 [running]:
github.com/coreos/etcd/tools/benchmark/cmd.recvWatchChan(0xc435dad140, 0xc420733920)
	/Users/suhas/Workspace/go/src/github.com/coreos/etcd/tools/benchmark/cmd/watch.go:201 +0x1bc
created by github.com/coreos/etcd/tools/benchmark/cmd.doWatch
	/Users/suhas/Workspace/go/src/github.com/coreos/etcd/tools/benchmark/cmd/watch.go:189 +0x234

Why:

121	r := report.NewReportRate("%4.4f")
122	for i := range streams {
123		go doWatch(streams[i], requests, r.Results()) <- The Results sent here is also propagated to the goroutines in the doWatch function:

188 bar.Increment()
189	go recvWatchChan(wch, results) <- Notice the results chan being sent here. 

The channel is how ever closed when watchCompletedNotifier notifies, 
136	<-watchCompletedNotifier
137	bar.Finish()
138	close(r.Results())

The fix should involve two separate report instantiation.

**Comment by heyitsanthony** [comment]
fixed by #8069. closing
