### ISSUE TITLE
Expose /metrics an a separate port

### ISSUE THREAD

**Issue by fabxc** [coreos/etcd#8060]
In many scenarios etcd nodes run on designated nodes that are very restrictive for outside traffic.

If we want to monitor etcd, we don't need access to any critical APIs but just `/metrics`. It's not generally feasible to run Prometheus on the same nodes as etcd though. Having etcd expose `/metrics` on a designated port that can be exposed relatively safely would solve those scenarios.

It could be an optional flag,that exposes an additonal `/metrics` endpoint on another address if set.

@xiang90 @brancz

**Comment by heyitsanthony** [comment]
@fabxc would etcd get an allocation on https://github.com/prometheus/prometheus/wiki/Default-port-allocations or is that something different?

**Comment by brancz** [comment]
That would generally make sense @heyitsanthony. Next one up is usually marked. It is `9267` right now. This should of course be configurable if a user desires to bind it differently.

**Comment by fabxc** [comment]
TBH, I'm not too much of a fan of dedicated Prometheus ports beyond our
core components. It's just not practical to maintain those global
registries.
As an etcd user, I'd probably prefer the default metric port to be default
API port + 1 or similar, so it's easier to remember.

**Comment by brancz** [comment]
FWIW certainly not all exporters and applications oblige to it, so etcd being a relatively prominent application I think it's valid to choose whatever we like best. The wiki page is also open and I don't think anyone monitors the changes much, so the reliability is questionable either way (I've brought this up before but it was decided to keep as guidance for now).

**Comment by xiang90** [comment]
@heyitsanthony 

do you think this is a reasonable enhancement we could do in 3.3?

**Comment by gyuho** [comment]
@xiang90 @heyitsanthony Do we want to *move* `/metrics` endpoints to a separate port, or *duplicate* the handler in the separate port?

**Comment by heyitsanthony** [comment]
Duplicate the handler. There could be clients that have access to the internal port that expect /metrics to be available.

**Comment by brancz** [comment]
Awesome! Thanks for the collaboration everyone!

**Comment by seh** [comment]
Is it correct that even if one activates additional URLs with distinct ports for _etcd_ serving metrics (per #8242), the server still demands the same authentication credentials as the other _etcd_ ports (2379, 2380)? It is challenging to arrange for Prometheus to have the client key and certificate available to authenticate to _etcd_—as mentioned in kubernetes/kubernetes#53405.

Running a dedicated Prometheus server on each Kubernetes master machine would allow mounting the client key and certificate files from the host—permissions willing. An alternative is to place those files into a _Secret_ object, though creating such a _Secret_ poses challenges too.

**Comment by gyuho** [comment]
> server still demands the same authentication credentials as the other etcd ports

You can specify HTTP URL, bypassing TLS auth.

**Comment by seh** [comment]
Thank you, @gyuho. I see that accommodation [here in `transport.wrapTLS`](https://github.com/etcd-io/etcd/blob/c47d4450c7218a333e1c1545c10a27d0f32b73ef/pkg/transport/listener.go#L51:L56).
