### ISSUE TITLE
Docs probably use dev image not release image

### ISSUE THREAD

**Issue by erikbgithub** [coreos/etcd#8078]
For instance [this page](https://coreos.com/etcd/docs/latest/v2/docker_guide.html) doesn't contain the `etcd` binary in their code examples. But if you install the [release image](https://github.com/coreos/etcd/blob/master/Dockerfile-release#L17) instead of however you start the [devel image](https://github.com/coreos/etcd/blob/master/Dockerfile#L6) you won't have an ENTRYPOINT, so you need to explicitely state the binary you want to use.

**Comment by gyuho** [comment]
https://coreos.com/etcd/docs/latest/v2/docker_guide.html assumes that you are running v2.

Since v3, we use `CMD` https://github.com/coreos/etcd/blob/master/NEWS#L154

**Comment by erikbgithub** [comment]
I see, thanks for the explanation!
