### ISSUE TITLE
v3.2.0-arm64 release

### ISSUE THREAD

**Issue by glevand** [coreos/etcd#8085]
There doesn't seem to be any arm64 release of v3.2.0 in either [github](https://github.com/coreos/etcd/releases/tag/v3.2.0) or [quay.io](https://quay.io/repository/coreos/etcd?tab=tags).  PR https://github.com/coreos/etcd/pull/7714 (add multi-arch support in release binaries) should have made that possible.

rkt's TestFetchAny functional test uses etcd images, so to fix that for arm64 I need arm64 releases of etcd to at least the github downloads.  See https://github.com/rkt/rkt/blob/master/tests/rkt_fetch_test.go#L93.

**Comment by gyuho** [comment]
@glevand We will include those builds from 3.2.1+.
I should have communicated earlier.
Thanks!

**Comment by glevand** [comment]
@gyuho OK.    Just to mention it here, the [v3.2.0-rc.1](https://github.com/coreos/etcd/releases/tag/v3.2.0-rc.1) release was missing the pgp signature file for the arm64 aci image, so please include it in 3.2.1.  The rkt tests will fail without that.

Thanks.
