### ISSUE TITLE
Script to convert etcd storage data from api v2 to api v3

### ISSUE THREAD

**Issue by trunet** [coreos/etcd#8094]
I don't know how do you want to document this, but here's a quick and dirty script to convert the data from etcd api v2 to v3.

    #!/bin/bash
    PREFIX="/vault"
    for KEY in $(etcdctl ls ${PREFIX} -recursive -p)
    do
         if ! [[ "${KEY}" == */ ]]
         then
                 # key on etcd2 is base64 encoded and has a point on the "filename"
                 NEW_KEY=$(echo ${KEY} | sed 's/\/\./\//')
                 etcdctl get ${KEY} | base64 --decode | ETCDCTL_API=3 etcdctl put ${NEW_KEY}
         fi
    done

**Comment by heyitsanthony** [comment]
@trunet does this script have any advantage over `ETCDCTL_API=3 etcdctl migrate`? The online conversion here can lead to inconsistencies if other services are still talking to etcd while the script is running...

**Comment by trunet** [comment]
I posted this on the wrong github project, I'm so sorry... I was willing to post this on the vault project, as the keys and the encoding are different. closing.......

**Comment by trunet** [comment]
correct issue: https://github.com/hashicorp/vault/issues/2862

**Comment by heyitsanthony** [comment]
FWIW, the base64 decoding could be done with a custom migration transformer using the `--transform` flag, but that's admittedly more involved than a shell script.

**Comment by trunet** [comment]
good to know, thanks.
