### ISSUE TITLE
revision based auto-compaction-retention

### ISSUE THREAD

**Issue by clusc** [coreos/etcd#8098]
Hi,

Currently we are using the [`auto-compaction-retention`](https://coreos.com/etcd/docs/latest/op-guide/configuration.html#auto-compaction-retention) parameter to compact etcd data every 24h. But given our spiky usage pattern(we are using etcd as distributed lock), this time based compaction policy doesn't work too well for us. Is there a revision-based auto-compaction policy that we can configure? Also, is there a metric for # of revision that we can watch on(I didn't find in the current exposed metrics)?

Thanks

**Comment by xiang90** [comment]
It makes sense. We will probably add it.

**Comment by clusc** [comment]
Thanks. Is there a workaround that we can do now to alleviate us from manually compacting every now and then? We are using etcd-operator, is this something that operator can help?

**Comment by xiang90** [comment]
@clusc Not really. It is all manual at the moment.

**Comment by xiang90** [comment]
@clusc 

>  is there a metric for # of revision

revision is attached in every response header.

**Comment by clusc** [comment]
It doesn't for `/metrics` endpoint though right?

**Comment by xiang90** [comment]
@clusc No. You can add a debugging metrics for it if you wish. Open a pr, thanks.

**Comment by yudai** [comment]
I had the same idea and just crated a PR for it.
Still, compaction happens every 5 minutes, but I believe it should cover almost all environments.

**Comment by xiang90** [comment]
fixed by #8123
