### ISSUE TITLE
ClientV3 does not support nested keys

### ISSUE THREAD

**Issue by SonarBeserk** [coreos/etcd#8100]
# Fix
```sh
MSYS_NO_PATHCONV=1
```

# Version
Latest

# Steps to reproduce

1 Add key with cli
```sh
ETCDCTL_API=3 etcdctl put /test/nest 1
```
2 Try to get the nested key
``` go
	cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		panic(err)
	}
	defer cli.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	resp, err := cli.Get(ctx, "/test/nest")
	cancel()
	if err != nil {
		panic(err)
	}

	fmt.Println(resp.Count)

	for _, val := range resp.Kvs {
		fmt.Println(string(val.Value))
	}
```

# Expected:
Should print 1 and the string version of the value

# Result
resp.Count  == 1 and no other response

# Notes
No errors returned

**Comment by fanminshi** [comment]
Mine works fine.
```sh
$bin/etcd
main: etcd Version: 3.2.0-rc.1+git
2017-06-14 13:30:52.040993 I | etcdmain: Git SHA: 4dff7aa
2017-06-14 13:30:52.040996 I | etcdmain: Go Version: go1.8
...
```

```go
cli, err := clientv3.New(clientv3.Config{
		Endpoints:   []string{"localhost:2379"},
		DialTimeout: 5 * time.Second,
	})
	if err != nil {
		panic(err)
	}
	defer cli.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	resp, err := cli.Get(ctx, "/test/nest")
	cancel()
	if err != nil {
		panic(err)
	}

	fmt.Println(resp.Count)

	fmt.Printf("%+v \n", resp)
```
```sh
#output
1 # resp.Count
&{Header:cluster_id:14841639068965178418 member_id:10276657743932975437 revision:42 raft_term:6  Kvs:[key:"/test/nest" create_revision:42 mod_revision:42 version:1 value:"1" ] More:false Count:1} # resp
```

you can see that kv is successfully retrieved` Kvs:[key:"/test/nest" create_revision:42 mod_revision:42 version:1 value:"1" ] `

**Comment by fanminshi** [comment]
@SonarBeserk can you run my script to see if you get the same result. you script works on my machine as well.

**Comment by SonarBeserk** [comment]
@fanminshi When trying your script there is nothing returned still
```sh
0
&{Header:cluster_id:7288516548352293881 member_id:7537664514937571529 revision:11 raft_term:6  Kvs:[] More:false Count:0}
```
etcdctl version
```sh
etcdctl version: 3.2.0
API version: 3.2
```

**Comment by fanminshi** [comment]
@SonarBeserk if you run `ETCDCTL_API=3 etcdctl put /test/nest`, what's the response?

**Comment by SonarBeserk** [comment]
The command hangs any time I try that and seems to wait indenfinitely

**Comment by fanminshi** [comment]
that shouldn't happen. it should return a result immediately. 
can you run `ETCDCTL_API=3 etcdctl endpoint health`?

**Comment by heyitsanthony** [comment]
@fanminshi `put` will hang because it's expecting input from stdin, perhaps you meant `get`?

**Comment by fanminshi** [comment]
@heyitsanthony good catch. my mistake.

**Comment by SonarBeserk** [comment]
When running get the response is
``` sh
C:/Program Files/Git/test/nest
1
```
I am unsure of why it uses that folder

**Comment by fanminshi** [comment]
@SonarBeserk how come the key is `C:/Program Files/Git/test/nest` not `/test/nest`?

**Comment by SonarBeserk** [comment]
I am not sure, I am running etcd in a docker container. I am running the cli in the git bash terminal which is MINGW64 based.

**Comment by SonarBeserk** [comment]
@fanminshi There appears to be something wrong with how the cli interprets paths on windows as changing the key to ./test/nest returns 
``` sh
1
&{Header:cluster_id:7288516548352293881 member_id:7537664514937571529 revision:12 raft_term:6  Kvs:[key:"./test/nest" create_revision:12 mod_revision:12 versio
n:1 value:"1" ] More:false Count:1}
```

**Comment by heyitsanthony** [comment]
Try it with quotes `ETCDCTL_API=3 etcdctl put "/test/nest" 1`?

**Comment by SonarBeserk** [comment]
No dice with quotes, it has the same issue

**Comment by fanminshi** [comment]
@SonarBeserk how about single quote `ETCDCTL_API=3 etcdctl put '/test/nest' 1`

**Comment by heyitsanthony** [comment]
OK it's doing the mangling at a lower level than bash globbing. `MSYS_NO_PATHCONV=1 ETCDCTL_API=3 etcdctl put /test/nest 1` or `MSYS2_ARG_CONV_EXCL="*" ...` might work
