### ISSUE TITLE
endpoint health/status doesn't show all etcd members' values

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#8115]
In ETCD v2, the `cluster health` will show all the etcd members' health status. And in ETCD v3, the etcdctl can't show all the members' status.

After reading the source code of the endpoint command, it only connect to the endpoints configured in the command argument. It's very inconvenient to catch all members' status.

```go
func epStatusCommandFunc(cmd *cobra.Command, args []string) {
	c := mustClientFromCmd(cmd)

	statusList := []epStatus{}
	var err error
	for _, ep := range c.Endpoints() {
		ctx, cancel := commandCtx(cmd)
		resp, serr := c.Status(ctx, ep)
		cancel()
		if serr != nil {
			err = serr
			fmt.Fprintf(os.Stderr, "Failed to get the status of endpoint %s (%v)\n", ep, serr)
			continue
		}
		statusList = append(statusList, epStatus{Ep: ep, Resp: resp})
	}

	display.EndpointStatus(statusList)

	if err != nil {
		os.Exit(ExitError)
	}
}

```

**Comment by xiang90** [comment]
this is by design. it is under endpoint, not cluster anymore, which means it only cares about the endpoint you provide. 

a cluster level ping is usually broken by design for various reasons. we do not want to go that route again.

**Comment by armstrongli** [comment]
@xiang90 Here is what I do to make it:
https://github.com/armstrongli/etcd/commit/0c7034cd907169723ee7cb60833e5128cdcca9f3

**Comment by armstrongli** [comment]
If the endpoint which is being checked is not in the `soft balancer`, the ping will be failure. I haven't check the root cause.

**Comment by armstrongli** [comment]
I'll commit the PR first. 
https://github.com/coreos/etcd/pull/8116

If it's design level, I hope add one `cluster` sub-command to support that.

**Comment by xiang90** [comment]
Cluster level command is too easy to be confusing. please open issue for discussion before implement it.

**Comment by armstrongli** [comment]
@xiang90 I created one issue here: https://github.com/coreos/etcd/issues/8117
