### ISSUE TITLE
etcd clientv3 prevExist

### ISSUE THREAD

**Issue by arun0009** [coreos/etcd#8119]
How can I make sure am creating a k/v in etcd clientv3? In previous version we have prevExist option, is there a way to 'create' key/val and if one exists throw an exception instead of just doing a 'put'?

**Comment by heyitsanthony** [comment]
@arun0009 It can be done with transactions:
```go
opput := clientv3.OpPut(key, val)
resp, err := c.Txn(context.TODO()).
    If(clientv3.Compare(clientv3.Version(key), "=", 0)).
    Then(opput).
    Else(opput).Commit()
if err != nil { ... }
if resp.Succeeded {
    /* created new key */
} else {
   /* overwrote existing key */
}
```

**Comment by arun0009** [comment]
Thanks!
