### ISSUE TITLE
Do we have a plan to move etcd3 grpc-gateway out of alpha?

### ISSUE THREAD

**Issue by realityone** [coreos/etcd#8125]
Hi there,

We are using etcd and python to build our applications. In etcd2, everything works fine. But etcd3 using gRPC as the original way. Cause python2 `grpcio` is incompatible with `gevent`, so we plan to using the etcd3 grpc-gateway in our applications.

But I aware that the API is prefixed with `/v3alpha`. And I checked the roadmap, nothing about the grpc-gateway.

I'm curious do we have a plan to move etcd3 grpc-gateway out of alpha? Or this will always be an alpha feature?

Any help would be appreciated.

Reference:
- https://github.com/grpc/grpc/issues/4629
- https://github.com/gevent/gevent/issues/938
- https://github.com/gevent/gevent/issues/786
- https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3450

**Comment by zyf0330** [comment]
@realityone When you say *do we have a plan ...*, I guess you are Chinese like me.😂

**Comment by gyuho** [comment]
We will add `/v3alpha` routes with same handler for safe upgrades, in v3.3.

**Comment by raoofm** [comment]
@gyuho any timeline for /v3. I mean are there any tasks remaining to mark it as stable?

**Comment by xiang90** [comment]
@raoofm we just fixed the bi-streaming endpoint. need to do a new beta release to encourage people to try it out. if there is nothing comes out for the next release, we will bump it to stable.

**Comment by gyuho** [comment]
We've just changed `/v3alpha` to `/v3beta` in master branch, while keeping `/v3alpha` endpoints with HTTP redirects. Will be included in our upcoming 3.3 release.
