### ISSUE TITLE
k8s-master etcd[19597]: serving insecure client requests on [::]:2379, this is strongly discouraged!

### ISSUE THREAD

**Issue by liuyihe111** [coreos/etcd#8137]
I have deployed Kubernetes on two worker nodes. On the master node I installed etcd docker kube-apiserver kube-controller-manager and kube-scheduler. On the minion node I installed flanneld docker kube-proxy and kubelet. Then I configured Two-way TLS communication between two nodes.

But I have a question when I start etcd. As follows:
![image](https://user-images.githubusercontent.com/28377923/27332985-c4eb399a-55f6-11e7-9c51-3d1f63c48792.png)
I want to know how to solve this problem ? And could you please tell me how to achieve secure etcd communication ?

My version as follows:
CentOS 7
![image](https://user-images.githubusercontent.com/28377923/27333118-615c0566-55f7-11e7-938e-c047564e9c9e.png)

Thanks for every kind friend helping me .

**Comment by gyuho** [comment]
> Then I configured Two-way TLS communication between two nodes.

But you are configuring etcd with non-TLS URLs?

**Comment by xiang90** [comment]
you need to enable etcd TLS. it has nothing to do with k8s. check https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md

**Comment by liuyihe111** [comment]
@gyuho Yes. This is the etcd.conf file:
[root@k8s-master ~]# vim /etc/etcd/etcd.conf
#[member]
ETCD_NAME=default
ETCD_DATA_DIR=”/var/lib/etcd/default.etcd”
ETCD_LISTEN_CLIENT_URLS=”http://0.0.0.0:2379”(表示etcd在2379端口上监听所有网络接口)

#[cluster]
ETCD_ADVERTISE_CLIENT_URLS=”http://192.168.6.130:2379”

When I change the "http" to "https", the etcd can't be started. What should I do ??
Thanks for your attention.

**Comment by liuyihe111** [comment]
@xiang90 The k8s I have generated self-signed certificates for k8s, should I need to enable etcd TLS as follows:
https://github.com/coreos/docs/blob/master/os/generate-self-signed-certificates.md
