### ISSUE TITLE
Provide a php client for etcd v3

### ISSUE THREAD

**Issue by LinkedDestiny** [coreos/etcd#8139]
https://github.com/CatsSystem/swoole-etcd

**Comment by xiang90** [comment]
we do not maintain php client. and we have no plan for it.

**Comment by heyitsanthony** [comment]
@LinkedDestiny please open a PR adding the client to https://github.com/coreos/etcd/blob/master/Documentation/integrations.md under `PHP Libraries` if you'd like etcd to link to the project. Thanks!
