### ISSUE TITLE
vote endpoint returns 404 on new cluster

### ISSUE THREAD

**Issue by jefferai** [coreos/etcd#815]
I created a fresh cluster of three machines yesterday, using the 0.4.1 tag. I added one key to the cluster (/global/serfkey) and then left it alone overnight.

It's a very simple cluster:

```
etcdctl -debug -peers http://others:4001 ls --recursive /_etcd/machines
Cluster-Peers: http://10.8.8.108:4001 http://10.8.8.106:4001
Curl-Example: curl -X GET http://10.8.8.108:4001/v2/keys/_etcd/machines?consistent=true&recursive=true&sorted=false
/_etcd/machines/others
/_etcd/machines/hurley

etcdctl -debug -peers http://others:4001 ls --recursive /
Cluster-Peers: http://10.8.8.108:4001 http://10.8.8.106:4001
Curl-Example: curl -X GET http://10.8.8.108:4001/v2/keys/?consistent=true&recursive=true&sorted=false
/global
/global/serfkey
```

Then I tried to simply add a directory:
```
etcdctl -debug -peers http://others:4001 mkdir /roles/eventcenter
Cluster-Peers: http://10.8.8.108:4001 http://10.8.8.106:4001
Curl-Example: curl -X PUT http://10.8.8.108:4001/v2/keys/roles/eventcenter?dir=true&prevExist=false

Curl-Example: curl -X PUT http://10.8.8.108:4001/v2/keys/roles/eventcenter?dir=true&prevExist=false
Curl-Example: curl -X PUT http://10.8.8.108:4001/v2/keys/roles/eventcenter?dir=true&prevExist=false
Curl-Example: curl -X PUT http://10.8.8.108:4001/v2/keys/roles/eventcenter?dir=true&prevExist=false
Error: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
```

One of my three machines (hurley at 10.8.8.108) is now spitting out:
```
[etcd] May 30 14:17:51.322 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:51.579 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:51.579 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:51.900 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:51.900 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:52.197 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:52.197 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:52.537 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:52.537 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:52.882 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
[etcd] May 30 14:17:52.882 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
```

Restarting etcd doesn't help. The other two machines can't connect to it, fail to generate a quorum between them, and the whole cluster is unusable (and I'm hoping not doomed).

**Comment by rca** [comment]
I see the same errors as @coozy above:

```
Jan 05 03:27:57 ip-172-30-0-11.ec2.internal etcd[572]: [etcd] Jan  5 03:27:57.339 WARNING   | [vote] Error: nil response
```

```
Jan 05 03:28:32 ip-172-30-0-125.ec2.internal etcd[9798]: [etcd] Jan  5 03:28:32.262 INFO      | 55feb942c50942aebc9406fa236d62c6: state changed from 'candidate' to 'follower'.
Jan 05 03:28:32 ip-172-30-0-125.ec2.internal etcd[9798]: [etcd] Jan  5 03:28:32.262 INFO      | 55feb942c50942aebc9406fa236d62c6: term #2308 started.
Jan 05 03:28:33 ip-172-30-0-125.ec2.internal etcd[9798]: [etcd] Jan  5 03:28:33.965 INFO      | 55feb942c50942aebc9406fa236d62c6: state changed from 'follower' to 'candidate'.
Jan 05 03:28:33 ip-172-30-0-125.ec2.internal etcd[9798]: [etcd] Jan  5 03:28:33.967 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 05 03:28:35 ip-172-30-0-125.ec2.internal etcd[9798]: [etcd] Jan  5 03:28:35.380 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
```

**Comment by piaohai** [comment]
Jan 11 09:10:06 core-03 etcd[456]: [etcd] Jan 11 09:10:06.730 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 11 09:10:06 core-03 kubelet[950]: I0111 09:10:06.828030     950 logs.go:39] etcd DEBUG: get /registry/nodes/172.17.8.103/boundpods [http://127.0.0.1:4001]
Jan 11 09:10:06 core-03 kubelet[950]: I0111 09:10:06.828187     950 logs.go:39] etcd DEBUG: Connecting to etcd: attempt1forkeys/registry/nodes/172.17.8.103/boundpods?consistent=true&recursive=false&sorted=false
Jan 11 09:10:06 core-03 kubelet[950]: I0111 09:10:06.828213     950 logs.go:39] etcd DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/registry/nodes/172.17.8.103/boundpods?consistent=true&recursive=false&sorted=false | method GET
Jan 11 09:10:06 core-03 kubelet[950]: I0111 09:10:06.849250     950 logs.go:39] etcd DEBUG: network error:Get /v2/keys/registry/nodes/172.17.8.103/boundpods?consistent=true&recursive=false&sorted=false: stopped after 10 redirects
Jan 11 09:10:06 core-03 kubelet[950]: E0111 09:10:06.851528     950 etcd_tools_watch.go:171] watch was unable to retrieve the current index for the provided key ("/registry/nodes/172.17.8.103/boundpods"): 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]
Jan 11 09:10:06 core-03 kubelet[950]: I0111 09:10:06.851776     950 etcd.go:71] Watch closed (&api.Status{TypeMeta:api.TypeMeta{Kind:"", APIVersion:""}, ListMeta:api.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]", Reason:"", Details:(*api.StatusDetails)(nil), Code:0}). Reopening.
Jan 11 09:10:06 core-03 etcd[456]: [etcd] Jan 11 09:10:06.961 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 11 09:10:06 core-03 etcd[456]: [etcd] Jan 11 09:10:06.962 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 11 09:10:07 core-03 etcd[456]: [etcd] Jan 11 09:10:07.303 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 11 09:10:07 core-03 etcd[456]: [etcd] Jan 11 09:10:07.305 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 11 09:10:07 core-03 etcd[456]: [etcd] Jan 11 09:10:07.664 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field
Jan 11 09:10:07 core-03 etcd[456]: [etcd] Jan 11 09:10:07.668 WARNING   | transporter.vr.decoding.error:proto: field/encoding mismatch: wrong type for field

i have met same problem too atfer server crash,

**Comment by joshuarubin** [comment]
+1

**Comment by xiang90** [comment]
This is a go-raft problem. And go-raft is unmaintained now. We are using new raft now. So this problem should be solved in etcd 2.0. Thanks!

**Comment by david-gurley** [comment]
+!

When will etcd 2.0 get integrated in the alpha channel?

**Comment by jpmx** [comment]
+1 for etcd 2.0 on alpha

**Comment by yichengq** [comment]
@david-gurley It plans to happen in Feb.
@jpmx If you meet it in 2.0, please open a new issue with details about it.

**Comment by stianstr** [comment]
So it's a go-raft problem, what are the details of that problem? Does it shed any light on a possible workaround for us who want to use etcd, but do not want to run Alpha in production? Because I assume it will take some time before etcd 2.0 makes it way to Stable?

**Comment by jefferai** [comment]
@stianstr For now (and maybe permanently) we've moved to Consul. etcd has great features but it will be a while before I feel good about its raft implementation; not just because of go-raft but because of how new and untested its new implementation is.

**Comment by brandonkruse** [comment]
Consul is really fantastic, however, fleet is tied so closely with etcd that I'd like to stay with etcd. +1 for alpha coreos with etcd 2.x

**Comment by mosquitorat** [comment]
I got the same problem with etcd 0.4.6, but after remove all data in /var/lib/etcd/*, I cloud start the etcd cluster.

**Comment by wutil** [comment]
@mosquitorat 3Q

**Comment by wptad** [comment]
Works for me !! @mosquitorat 

Thanks a lot

**Comment by wangzi19870227** [comment]
Works for me too !! @mosquitorat

Thanks a lot

**Comment by jefferai** [comment]
@mosquitorat Which removes all of the cluster data, correct?
