### ISSUE TITLE
channel_cc.cc:121]          assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)

### ISSUE THREAD

**Issue by zhangwuliang** [coreos/etcd#8165]
Hi，when i use client  [ https://github.com/nokia/etcd-cpp-apiv3 ]  to watch etcd change, the client crash, and it report    "channel_cc.cc:121]          assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), cops, nops, ops, nullptr)", how to slove?

**Comment by xiang90** [comment]
can you create an issue in the nokia repo?

**Comment by zhangwuliang** [comment]
@xiang90 I created, but no nody reply. I am not sure whether it is the nokia problem or the etcd problem

**Comment by xiang90** [comment]
we are not going to look into every client problem. and it works ok on go client. so it is probably a c++client issue.

**Comment by zhangwuliang** [comment]
this isssue is the same as me,    https://github.com/nokia/etcd-cpp-apiv3/issues/7
