### ISSUE TITLE
Metrics in V3

### ISSUE THREAD

**Issue by davissp14** [coreos/etcd#8167]
I noticed that when we disable v2 by using --enable-v2=false, we lose access to the /metrics endpoint.  

Are there plans for exposing this to the v3 api?

**Comment by xiang90** [comment]
this is a bug. will be fixed.

**Comment by davissp14** [comment]
Also, it appears that specifying `--enable-v2 false` doesn't work while `--eanble-v2=false` does.

![screen shot 2017-06-23 at 1 01 25 pm](https://user-images.githubusercontent.com/423038/27494568-183a329e-5814-11e7-9072-9988d1af86a5.png)

**Comment by heyitsanthony** [comment]
All bool flags work like that-- the command line parser sees `--enable-v2`, parses it as `--enable-v2=true`, then expects another flag but sees `false` and bails.

**Comment by davissp14** [comment]
Interesting, thanks for the clarifying that!
