### ISSUE TITLE
Does the user need to eat all keep alive messages?

### ISSUE THREAD

**Issue by helinwang** [coreos/etcd#8168]
When user keep alive a lease, the function `KeepAlive` returns a channel of keep alive messages. From the code in [Session](https://github.com/coreos/etcd/blob/master/clientv3/concurrency/session.go#L63), it creates a net go-routine and eats all messages.
Is it necessary for the lease keep alive to work properly?

I am under impression that it does not have to 
 according to the code [here](https://github.com/coreos/etcd/blob/5fedaf2dd78aca3eeae723f4dfe9d37ea6edd2fa/clientv3/lease.go#L481), since the implementation just discard the message if the channel is full.

Just want to confirm if I need to add extra code to eat all the messages every time I create a lease and keep alive it.

**Comment by yudai** [comment]
AFIK, you virtually must drain messages from the channel returned by `KeepAlive` if the code has been not changed since #7446. Otherwise, keep alive messages are sent every 500ms to the server, as I reported in the issue.

**Comment by helinwang** [comment]
@yudai Thanks for the response! Your issue is very informative!

A side question, do your application actually care the result coming from the keep alive response channel? I am curious about the use case, maybe I could learn something to improve the program that I am currently working.

Thanks!
Helin

**Comment by yudai** [comment]
In my code, there some code like `for range keepAliveCh {}`.
I actually don't have any use case that requires to check the content of messages to this channel so far.

**Comment by xiang90** [comment]
i think the question is well answered. thanks @yudai. closing.
