### ISSUE TITLE
Etcd does not run on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by RobinGeuze** [coreos/etcd#8178]
When running etcd on Bash on Ubuntu on Windows in any form (I'm mainly trying to run the integration test, but the normal application doesn't start either), I get the following error:

```
etcdserver: create wal error: rename /tmp/etcd930045107/member/wal.tmp /tmp/etcd930045107/member/wal: permission denied
```

I did some digging and found the following comment in etcd/wal/wal_windows.go and I suspect the same thing is valid for the filesystem in Bash on Ubuntu on Windows:
```
// rename of directory with locked files doesn't work on
// windows; close the WAL to release the locks so the directory
// can be renamed
```

**Comment by philips** [comment]
This is a BashOnWindows issue: https://github.com/Microsoft/BashOnWindows/issues/2243

**Comment by philips** [comment]
@RobinGeuze in the meantime just use etcd.exe from the etcd windows releases as this is an issue with how BashOnWindows emulates POSIX filesystems, not an issue with etcd.

**Comment by RobinGeuze** [comment]
I actually managed to "fix" it by including the code from wal_windows.go in the wal_unix.go in case the rename fails (a retry if you will). However then I run into boltdb/bolt#702 so that joy was short lived :P

**Comment by heyitsanthony** [comment]
Partially duplicates #6984. The wal package / fileutil can dynamically check if the FS permits locked directory renames then act accordingly instead of tying it to the build target OS like how it is now.
