### ISSUE TITLE
export ETCDCTL_API=3 not working 

### ISSUE THREAD

**Issue by shamalco** [coreos/etcd#8180]
Hi,

I am sure I might be messing up some how, but I can't figure out what I am doing wrong. I want to use etcdctl with ver. 3 cluster. I followed the guide correctly [CoreOS interacting with v3](https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/interacting_v3.md)

After running:
`export ETCDCTL_API=3`

When trying to verify as documented:
```
etcdctl version
No help topic for 'version'
```

When I try etcdctl alone I see its still 2.3.7 for some reason. I suspect maybe there is an issue with the env not taking the export, but confirmed it is:
```
printenv 
...
ETCDCTL_API=3
...
```

I am not sure what I am doing wrong, seems simple enough (I am running CoreOS stable (1409.2.0))

**Comment by xiang90** [comment]
i do not think coreos ships etcdctl3. you probably should create an issue on coreos issues to track this.
