### ISSUE TITLE
What will happen if assign several leases with different TTL to one key ?

### ISSUE THREAD

**Issue by NetWilliam** [coreos/etcd#8185]
I am trying to use etcd as server health checking tool. 

I am expecting that one node will be considered as offline if it cannot write its corresponding key on time, so I create a new lease and bind it to a key every-time I rewrite the key.

I am sure that all nodes are perfectly online, however I still have some node key lost. I don't know if I've misunderstood the mechanism of lease TTL. Does that mean my key will get deleted whichever the bound lease is expired?

**Comment by gyuho** [comment]
If you overwrite a key with different lease, the key will be deleted when the latest lease expires.

**Comment by xiang90** [comment]
As @gyuho mentioned, each key is attached to one lease. 

I am not sure what happened to your program. If you think it is an etcd issue, feel free to create another issue with reproduce steps. thank you.
