### ISSUE TITLE
data  is sorted order by ascend when calling get method

### ISSUE THREAD

**Issue by wjliu** [coreos/etcd#8186]
When calling get method with NONE sort order option, but return data  is sorted order by ascend. 
Environment:

    ETCD server version : 3.1.7
    ETCD client :  jetcd
    API version : v3
    OS : Centos 7

Below is my test code:

    Client client = ClientBuilder.newBuilder().endpoints("http://127.0.0.1:2379").build();
    KV kvClient = client.getKVClient();

    ByteSequence key1 = ByteSequence.fromBytes("test_3".getBytes());
    ByteSequence key2 = ByteSequence.fromBytes("test_1".getBytes());
    ByteSequence key3 = ByteSequence.fromBytes("test_6".getBytes());
    ByteSequence key4 = ByteSequence.fromBytes("test_4".getBytes());

    ByteSequence prefix = ByteSequence.fromBytes("test".getBytes());
    CompletableFuture<RangeResponse> getFuture1 = kvClient.get(prefix, GetOption.newBuilder().withPrefix(prefix).withSortOrder(RangeRequest.SortOrder.NONE).build());
    RangeResponse response1 = getFuture1.get();
    response1.getKvsList().forEach(kv -> {
      System.out.println(kv.getKey().toStringUtf8());
      System.out.println(kv.getValue().toStringUtf8());
    });

Expected output is : 
test_3
test_3
test_1
test_1
test_6
test_6
test_4
test_4

But the actual output is : 
test_1
test_1
test_3
test_3
test_4
test_4
test_6
test_6
   
Is this a bug?

**Comment by wjliu** [comment]
I checked the source code and found the data is stored in a btree in memory, and the btree provide get method to return data is sorted order by ascend or descend.  So when I called get method with sort target is KEY and sort order is NONE, can only return data is sorted order by ascend. 

I think this can be resolved by adding below code in the etcdserver/apply.go (Range function) : 

    diff --git a/etcdserver/apply.go b/etcdserver/apply.go
    index e4bf35b..3ea8122 100644
    --- a/etcdserver/apply.go
    +++ b/etcdserver/apply.go
    @@ -305,6 +305,11 @@ func (a *applierV3backend) Range(txnID int64, r *pb.RangeRequest) (*pb.RangeResp
            }

            sortOrder := r.SortOrder
    +       if r.SortTarget == pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_NONE {
    +               r.SortTarget = pb.RangeRequest_CREATE
    +               sortOrder = pb.RangeRequest_ASCEND
    +       }
    +
            if r.SortTarget != pb.RangeRequest_KEY && sortOrder == pb.RangeRequest_NONE {
                    // Since current mvcc.Range implementation returns results
                    // sorted by keys in lexiographically ascending order,

**Comment by xiang90** [comment]
none only means there is no ordering guarantees. It may be sorted, or not.

**Comment by wjliu** [comment]
But in the Client API doc this option is described as no sorting, so I think the data should be returned in the order in which they were put.

**Comment by xiang90** [comment]
No. There is no such guarantee. You need to sort by modifying rev to get the put order.

**Comment by wjliu** [comment]
Ok， I see 
Thanks
