### ISSUE TITLE
Question: how to implement high availability of IP in nodes using etc?

### ISSUE THREAD

**Issue by selvakumarnms** [coreos/etcd#8192]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by selvakumarnms** [comment]
I wanted to know similar to keepalived how to achieve IP high availability using etcd

**Comment by xiang90** [comment]
Probably post this to our mailing list. github is for issue tracking, not general high level questions.
