### ISSUE TITLE
etcd public discovery problem

### ISSUE THREAD

**Issue by akd31** [coreos/etcd#8196]
Hi,
I am trying to use etcd public discovery service which is guided below.
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md#etcd-discovery

I have 3 docker containers run etcd and when I create all 3 of them they work perfectly.However, when I stop and try to restart them there is an error like 

2017-06-30 07:26:01.525466 I | etcdmain: etcd Version: 3.2.1
2017-06-30 07:26:01.525550 I | etcdmain: Git SHA: 61fc123
2017-06-30 07:26:01.525556 I | etcdmain: Go Version: go1.8.3
2017-06-30 07:26:01.525558 I | etcdmain: Go OS/Arch: linux/amd64
2017-06-30 07:26:01.525561 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2017-06-30 07:26:01.525666 I | embed: listening for peers on http://0.0.0.0:2380
2017-06-30 07:26:01.525704 I | embed: listening for client requests on 0.0.0.0:2379
2017-06-30 07:26:02.928722 E | etcdmain: member "etcd-node-0" has previously registered with discovery service token (http://discovery.etcd.io/c748ef8a0982bb0fc83da1ec29716f66).
2017-06-30 07:26:02.928738 E | etcdmain: But etcd could not find valid cluster configuration in the given data dir (/etcd-data).
2017-06-30 07:26:02.928741 I | etcdmain: Please check the given data dir path if the previous bootstrap succeeded
2017-06-30 07:26:02.928743 I | etcdmain: or use a new discovery token if the previous bootstrap failed.

My starting commands like below

ETCD_VERSION=latest
TOKEN=my-etcd-token
CLUSTER_STATE=new
NAME_1=etcd-node-0
NAME_2=etcd-node-1
NAME_3=etcd-node-2
HOST_1=0.0.0.0
HOST_2=0.0.0.0
HOST_3=0.0.0.0
CLUSTER=${NAME_1}=http://${HOST_1}:2380,${NAME_2}=http://${HOST_2}:12380,${NAME_3}=http://${HOST_3}:22380
DATA_DIR_1=/tmp/etcd-data-0
DATA_DIR_2=/tmp/etcd-data-1
DATA_DIR_3=/tmp/etcd-data-2

# For node 1
THIS_NAME=${NAME_1}
THIS_IP=${HOST_1}
docker run \
  -p 2379:2379 \
  -p 2380:2380 \
  --volume=${DATA_DIR_1}:/etcd-data \
  --name etcd-0 quay.io/coreos/etcd:${ETCD_VERSION} \
  /usr/local/bin/etcd \
  --data-dir=/etcd-data --name ${THIS_NAME} \
  --initial-advertise-peer-urls http://${THIS_IP}:2380 --listen-peer-urls http://${THIS_IP}:2380 \
  --advertise-client-urls http://${THIS_IP}:2379 --listen-client-urls http://${THIS_IP}:2379 \
  --discovery http://discovery.etcd.io/c748ef8a0982bb0fc83da1ec29716f66

# For node 2
THIS_NAME=${NAME_2}
THIS_IP=${HOST_2}
docker run \
  -p 12379:12379 \
  -p 12380:12380 \
  --volume=${DATA_DIR_2}:/etcd-data \
  --name etcd-1 quay.io/coreos/etcd:${ETCD_VERSION} \
  /usr/local/bin/etcd \
  --data-dir=/etcd-data --name ${THIS_NAME} \
  --initial-advertise-peer-urls http://${THIS_IP}:12380 --listen-peer-urls http://${THIS_IP}:12380 \
  --advertise-client-urls http://${THIS_IP}:12379 --listen-client-urls http://${THIS_IP}:12379 \
  --discovery http://discovery.etcd.io/c748ef8a0982bb0fc83da1ec29716f66

# For node 3
THIS_NAME=${NAME_3}
THIS_IP=${HOST_3}
docker run \
  -p 22379:22379 \
  -p 22380:22380 \
  --volume=${DATA_DIR_3}:/etcd-data \
  --name etcd-2 quay.io/coreos/etcd:${ETCD_VERSION} \
  /usr/local/bin/etcd \
  --data-dir=/etcd-data --name ${THIS_NAME} \
  --initial-advertise-peer-urls http://${THIS_IP}:22380 --listen-peer-urls http://${THIS_IP}:22380 \
  --advertise-client-urls http://${THIS_IP}:22379 --listen-client-urls http://${THIS_IP}:22379 \
  --discovery http://discovery.etcd.io/c748ef8a0982bb0fc83da1ec29716f66

I have another problem which is when I set discovery url with https containers couldn't connect.Therefore I used http but my main problem is what I told above for now. Can someone help me ?

**Comment by gyuho** [comment]
> etcdmain: member "etcd-node-0" has previously registered with discovery service token (http://discovery.etcd.io/c748ef8a0982bb0fc83da1ec29716f66).

Seems like you started the fresh cluster? If you want to use the discovery token, try mounting your data volume and restarting from that data directory.

**Comment by akd31** [comment]
No actually I didn't start fresh cluster I restart the cluster I have already . Here my commands : 

docker stop etcd-0

docker start etcd-0

**Comment by gyuho** [comment]
But when you restart cluster without data volume, it runs as a fresh cluster, because there's no data from previous run. Or did you configure data dir?

**Comment by akd31** [comment]
I think when I create a node I identify data dir and when restart node it know that isn't it ? if not How would I configure data dir ?

**Comment by gyuho** [comment]
`DATA_DIR_1=/tmp/etcd-data-0`? Did you reboot the machine? Then `/tmp` is gone?

**Comment by akd31** [comment]
Yeah you are right I didn't realize that . Thanks I'll try asap.

**Comment by gyuho** [comment]
@akd31 Please reopen if you still have issues.
