### ISSUE TITLE
Large range read blocks writes on 3.2.1?

### ISSUE THREAD

**Issue by smarterclayton** [coreos/etcd#8202]
I'm testing a very large 1.5 Kubernetes data set upgraded to 1.6 and etcd v3 mode (etcd 3.2.1).  Post v3 migration, I'm performing a kubernetes storage migration (GET -> PUT of all data) to force migration to protobuf.  However, as I was letting the migration run in the background (single threaded is taking about 30-40 minutes, since i'm migrating about ~500k kubernetes objects) I tried to do a range read of the `/kubernetes.io` keyspace to list all of the keys (`etcdctl get /kubernetes.io --keys-only`) and the migration halted until the range read completed or timed out.  I tried both serializable and linearizable, and both seemed to have the same behavior of "blocking" the migration process from continuing (specifically, the PUT of the object from Kubernetes to etcd timed out after 30s).

I didn't expect a range read to block writes, and have not noticed that behavior elsewhere.  It's somewhat reproducible on the data set I have, but was not sure where to start looking to debug.

**Comment by xiang90** [comment]
dup with https://github.com/coreos/etcd/issues/7719

also: https://github.com/coreos/etcd/issues/8114

@smarterclayton can you move the comment to #7719. if we decide to solve this, we will solve it there. thanks.
