### ISSUE TITLE
clientv3: Use KeepAlive for a key and watch it, del and put will be received

### ISSUE THREAD

**Issue by sparkthu** [coreos/etcd#8203]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

For example, when I put a key /abc with a lease A, and call keepalive will lease A. Then I use watch method for prefix /abc, I will receive del and put event for key /abc with interval TTL

**Comment by xiang90** [comment]
yes. that is the expected behavior. watch will return all events associated with the watched key. you can filter out some though. check v3 api for more details.

**Comment by sparkthu** [comment]
@xiang90  Sorry, I might not find the exact problem. Below is my code:


	ctx, _ := context.WithTimeout(context.Background(), 30 * time.Second)
	resp, err := r.cli.Grant(ctx, ttlSecond)
	if err != nil {
		return errors.New("Setup ttl failed:" + err.Error())
	} else {
		log.Println("LeaseID:", resp.ID)
	}
	ctx, _ = context.WithTimeout(context.Background(), 30 * time.Second)
	keepaliveChan, err := r.cli.KeepAlive(ctx, resp.ID)
	if err != nil {
		return errors.New("Setup keepalive failed:" + err.Error())
	}


In this case, the KeepAlive will stop working after 30 seconds(the context timeout), which I thought should not be the meaning of context.WithTimeout.
When I replace the second ctx with context.TODO(), it works.
