### ISSUE TITLE
There are a lot of raft proposals when there're only GET requests

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#8204]
Here is the grafana dashboard.
<img width="1420" alt="screen shot 2017-07-03 at 11 33 51 pm" src="https://user-images.githubusercontent.com/8025018/27799610-76084ac8-6048-11e7-9e25-2d0c3da37cb4.png">

**Comment by xiang90** [comment]
get goes through in 3.1, but not in 3.2.
