### ISSUE TITLE
etcd should report unhealthy status when in state: "mvcc: database space exceeded"

### ISSUE THREAD

**Issue by wojtek-t** [coreos/etcd#8207]
When etcd v3 enters the state of "mvcc: database space exceeded", it isn't fully functional. The user can only perform read operations, performing write operations returns in an error.

In such case, etcd shouldn't report it's state as healthy - it should be either unhealthy (or something in between).

@xiang90

**Comment by xiang90** [comment]
agreed.

**Comment by wojtek-t** [comment]
Reproduction steps:
$ etcd --quota-backend-bytes=1000000 &
$ for i in `seq 10000`; do ETCDCTL_API=3 etcdctl put $i$i$i$i$i$i $i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i$i; done

Then running the following command returns:
$ curl localhost:2379/health
{"health": "true"}

So even if we are in "database space exceeded" etcd returns "heatlh: true".
