### ISSUE TITLE
Strange code in kvstore rangeKeys function

### ISSUE THREAD

**Issue by armstrongli** [coreos/etcd#8208]
https://github.com/coreos/etcd/blob/master/mvcc/kvstore_txn.go#L134
https://github.com/coreos/etcd/blob/master/mvcc/kv.go#L24

There is `limit` parameters parsed to the range function. However, the range limit is always `0`. It will result in range all the keys from kv store.

```go
type RangeOptions struct {
	Limit int64
	Rev   int64
	Count bool
}
```

```go
func (tr *storeTxnRead) rangeKeys(key, end []byte, curRev int64, ro RangeOptions) (*RangeResult, error) {
...
	var kvs []mvccpb.KeyValue
	for _, revpair := range revpairs {
		start, end := revBytesRange(revpair)
		_, vs := tr.tx.UnsafeRange(keyBucketName, start, end, 0)
		if len(vs) != 1 {
			plog.Fatalf("range cannot find rev (%d,%d)", revpair.main, revpair.sub)
		}
...
```

**Comment by heyitsanthony** [comment]
@armstrongli it's fetching keys one-by-one since `end` bounds the range request to a single key; the unlimited fetch is in `tr.s.kvindex.Range(...)`, however. I think there's potential for getting rid of an allocation in this path, though-- the `end` doesn't look necessary.
