### ISSUE TITLE
discovery: register with v3 API

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8209]
Currently etcd writes/watches v2 data to discovery service servers https://github.com/coreos/etcd/blob/master/discovery/discovery.go, so even if discovery.etcd.io is having scaling issues with v2 API, it cannot migrate to v3 yet.

c.f. https://github.com/coreos/discovery.etcd.io/issues/52

**Comment by xiang90** [comment]
not sure if we are going to do this. maybe we should just deprecate discovery eventually.

**Comment by gyuho** [comment]
Closing in favor of https://github.com/coreos/etcd/issues/6925.
