### ISSUE TITLE
Why the wal file sync duration  can become as longer as 1m11.162122634s?

### ISSUE THREAD

**Issue by hejingxian123** [coreos/etcd#8216]
2017/06/20 12:53:52 server.go:636: Warning: avoid queries with large range/delete range!
2017/06/20 12:54:01 wal.go:403: Warning: sync duration of 8.001014846s, expected less than 1s
2017/06/20 12:55:12 wal.go:403: Warning: sync duration of 1m11.162122634s, expected less than 1s
2017/06/20 12:55:12 index.go:171: Info: store.index: compact 1747703

This is the log which occurred in our project. Why the sync duration  can become as longer as 1m11.162122634s? While the sync is running(which saves ents and state to the underlying stable storage), the client request will can not be processed.  I think that is terrible.

I have another question:
--
updateCommittedIndex(&ap, rh)
  |  
  | select {
  | case r.applyc <- ap:
  | case <-r.stopped:
  | return
  | }
  |  
  | // the leader can write to its disk in parallel with replicating to the followers and them
  | // writing to their disks.
  | // For more details, check raft thesis 10.2.1
  | if islead {
  | // gofail: var raftBeforeLeaderSend struct{}
  | r.transport.Send(r.processMessages(rd.Messages))
  | }
  |  
  | // gofail: var raftBeforeSave struct{}
  | if err := r.storage.Save(rd.HardState, rd.Entries); err != nil {
  | plog.Fatalf("raft save state and entries error: %v", err)
  | }

In the upper code, Why r.storage.Save must  be in the goroutine of applying enties. Can the storage saving operation move to another goroutine ?

Thanks very much!

**Comment by gyuho** [comment]
> Warning: avoid queries with large range/delete range!

what was your command to trigger this? And is it running on HDD?

**Comment by xiang90** [comment]
fsync time is directly measured from syscall time. there is probably some io contention going on in your environment (using vm? running io intensive workload?)
