### ISSUE TITLE
Can we read keys with prefix by HTTP API?

### ISSUE THREAD

**Issue by gunli** [coreos/etcd#8228]
Hi there,
    As we know, we can read all the values of keys with prefix by gRPC API like this:
    ./etcdctl get tglog --prefix
    
tglog
tglogvalue
tglog/qmfjdz
{["10.125.30.50:3600","10.125.30.51:3600"]}
tglog/wzry
{"port":3600,"heartbeatport":3601,"ips":["10.125.30.50","10.125.30.51"]}

    I wonder if we can do this by HTTP API? It seems we can read  just one value once according to the Docs, it is that right?

**Comment by gyuho** [comment]
We have grpc-gateway for HTTP + JSON endpoints.

https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md

**Comment by gunli** [comment]
Hi gyuho,
    Thank you for your replying. I'm afraid I didn't give my requirements clearly, My requirement is to read all the values of keys that with prefix "tglog" by one HTTP API call, the example in https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md read just ONE value, and my question is how can I put "--prefix" option to JSON as we do that in gRPC client.

    It seems I can add a field name range_end to the JSON according to https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md, then I try 
curl -L http://localhost:2379/v3alpha/kv/range -X POST -d '{"key": "dGdsb2c=", "range_end":"dGdsb2g="}'
where "dGdsb2g=" is the base64 encoded value of "tgloh"(tgloh==tglog+1), it works, so I think it is better to add an example of reading values of keys with prefix like my case to https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md, because when we use etcd to handle service discovery cases, we usually reading keys with prefix by one API call. I think it will be helpful for those people like me.
