### ISSUE TITLE
TestTLSReloadAtomicReplace: grpc: timed out when dialing

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8235]
via semaphore https://semaphoreci.com/coreos/etcd/branches/pull-request-8213/builds/2
```
--- FAIL: TestTLSReloadAtomicReplace (2.88s)
	v3_grpc_test.go:1790: expected no error, got grpc: timed out when dialing
```

**Comment by heyitsanthony** [comment]
TestTLSReloadCopy is hitting this too (https://semaphoreci.com/coreos/etcd/branches/master/builds/2143)

```
--- FAIL: TestTLSReloadCopy (3.29s)
	v3_grpc_test.go:1790: expected no error, got grpc: timed out when dialing
```

**Comment by gyuho** [comment]
Should we just bump up the dial timeout (current 1-second)? I have been running this test over a week with slow CPU machine, but still cannot reproduce.

**Comment by heyitsanthony** [comment]
@gyuho ok let's bump to 5s and reopen if it's still failing
