### ISSUE TITLE
Make major and minor version tags of docker images available

### ISSUE THREAD

**Issue by F21** [coreos/etcd#8239]
I am not sure if this is the best place to post this, however, it would be really convenient if you guys could publish major and minor tags for the docker images.

For example, the latest version as of writing is `v3.2.2`. Sometimes, we just want to pin our deployment to `v3.2` or even just `v3`. In this case it would be super useful to have a tag for `v3` and `v3.2`.

**Comment by gyuho** [comment]
Done. `v3.2` will be tagged for following minor releases (e.g. v3.2.2, v3.2.3, ...)
