### ISSUE TITLE
Transactional Compare for WithCountOnly()

### ISSUE THREAD

**Issue by tgraf** [coreos/etcd#8241]
While porting code to etcdv3 I noticed this gap in functionality which would render tremendously useful:

```
         cmp := client.Value(prefix).WithPrefix().WithCountOnly()
         txnresp, err := c.Txn(ctx.TODO()).
                 If(client.Compare(cmp, "=", 0)).
                 Then(client.OpDelete(key)).
                 Commit()
```

## Use Case

1. Insert master key plus first key in prefix only count on prefix is still 0
2. Delete master key after last key inside the prefix is gone

This allows maintaining a shared key with reference counting exclusively maintained by the presence of keys which share a common prefix.

**Comment by heyitsanthony** [comment]
@tgraf This can be done already (in master now, will be in 3.3) by comparing on the Version. See https://github.com/heyitsanthony/scraps/blob/master/delkeypfx/main.go for an example with delete.

**Comment by tgraf** [comment]
> @tgraf This can be done already (in master now, will be in 3.3) by comparing on the Version. See https://github.com/heyitsanthony/scraps/blob/master/delkeypfx/main.go for an example with delete.

Fantastic! I saw the `WithPrefix()` in master but wasn't sure how to use it for this use case. Thanks!
