### ISSUE TITLE
Understand why one node is down

### ISSUE THREAD

**Issue by zihaoyu** [coreos/etcd#8246]
I'm using Grafana to monitor my five-node cluster, v3.1.9. There is one graph which shows metrics from `sum(etcd_server_has_leader)`. I noticed there was a slight dip today.

<img width="357" alt="screen shot 2017-07-11 at 7 55 11 pm" src="https://user-images.githubusercontent.com/464299/28095875-eb791ea6-6672-11e7-9d68-a09c1de72cd5.png">

How can I investigate why there was a temporary unavailable node? When this happened, our `kubectl` operations failed quite a lot.

```
zihaoyu@partybox ~/src> kubectl delete deployment/comet-canary-pr-1220  
error: Scaling the resource failed with: etcdserver: request timed out; Current resource version 368582622
```

**Comment by xiang90** [comment]
network issues? node reboots? there are a lot of possibilities. you should look into your server log + etcd log first.
