### ISSUE TITLE
Etcd3 proxy can't get data from the same key twice.

### ISSUE THREAD

**Issue by zhuqunzhou** [coreos/etcd#8247]
etcd cluster: 192.168.10.4:2379,192.168.10.5:2379,192.168.10.6:2379
proxy:192.168.10.5:2389
etcd version:V3.2.0

Here is the code:

     cli, _ := clientv3.New(clientv3.Config{
		Endpoints: []string{"http://192.168.10.5:2389"},
		Username:"name",
		Password:"password",
	})

	for i:=0;i<10;i++ {
		resp,_ := cli.Get(context.TODO(),"/warden/test")

		fmt.Printf(string(resp.Kvs[0].Value) + "\n")

		time.Sleep(1 * time.Second)
	}

If i set the `endpoints` directly to the `etcd` cluster,the code works well,but if i set the `endpoints` to the proxy url,the code just can print one line data.

**Comment by gyuho** [comment]
Could you provide exact steps to reproduce this issue? How did you set up etcd and proxy?

**Comment by zhuqunzhou** [comment]
@gyuho 
Here is the  `etcd`  flags 
`  etcd --name infra0 --initial-advertise-peer-urls http://192.168.10.4:2380   --listen-peer-urls http://192.168.10.4:2380   --listen-client-urls http://192.168.10.4:2379,http://127.0.0.1:2379   --advertise-client-urls http://192.168.10.4:2379   --initial-cluster-token etcd-cluster-1   --initial-cluster infra0=http://192.168.10.4:2380,infra1=http://192.168.10.5:2380,infra2=http://192.168.10.6:2380   --initial-cluster-state new`

And here is the `proxy` flags
`etcd grpc-proxy start --endpoints=192.168.10.4:2379,192.168.10.5:2379,192.168.10.6:2379 --listen-addr=192.168.10.5:2389`

Thank you.

**Comment by gyuho** [comment]
What do you mean by

> code just can print one line data

Did you write the key `/warden/test`?

**Comment by heyitsanthony** [comment]
Looks like an auth bug in the proxy. I tried it and got `etcdserver: user name is empty`. /cc @mitake

**Comment by zhuqunzhou** [comment]
@gyuho ,i had write the key `/warden/test`,and the value is 'data'

The code want print the value of the key `/warden/test` 10 times,but in proxy mode,the code just print the value once.

**Comment by mitake** [comment]
@heyitsanthony I found that current grpc proxy isn't dealing with tokens at all. We need a wrapper that extracts the token of client's connection (like https://github.com/coreos/etcd/blob/master/auth/store.go#L1000) and attach it to proxy's connection (like https://github.com/coreos/etcd/blob/master/clientv3/client.go#L330). Possibly the change would conflict with your WIP: https://github.com/heyitsanthony/etcd/commit/00b397d8a318e477c5cdcffd00309f57ebb3259d should I wait or can I work on first?

@zhuqunzhou sorry for the inconveniecne!

**Comment by heyitsanthony** [comment]
@mitake I've been revamping e2e so this can be caught in CI at http://github.com/heyitsanthony/etcd/tree/test-e2e-grpcproxy. Not too worried about conflicts with 00b397d8a318e477c5cdcffd00309f57ebb3259d but I'd like some way to use the client's auth so vauth  can be dropped into the proxy by replacing client.Auth.

**Comment by mitake** [comment]
@heyitsanthony OK, I'll try it. Thanks for the test.
