### ISSUE TITLE
Token / Basic auth on the peer port

### ISSUE THREAD

**Issue by luxas** [coreos/etcd#8248]
It would be nice if etcd supported token or basic auth on the peer port as well, not just the client one.

The ese case is to cluster easily with TLS using `--peer-auto-tls` and a token that can be copied from master A to B.
In particular I'm thinking about implementing something like this for kubeadm cluster.

Something like:
kubeadm init
 - start etcd listening on client requests on `localhost` but peer requests on `0.0.0.0`
 - add a token / basic auth user that is able to join as a peer

kubeadm join --master --token <token> <master-ip>
 - start etcd listening on client requests on `localhost` but peer requests on `0.0.0.0`, joining etcd on `<master-ip>` using a token / basic auth as the auth mechanism

`--peer-auto-tls` is specified so the intra communication is secured with TLS anyway

Note that the kubeadm example here **is just for illustration purposes** in order to have an use-case
What I'm asking for is the general functionality of joining the cluster as a peer with some kind of auth mechanism other than TLS

cc @mitake we talked about this
cc @justinsb interested in an approach like this

**Comment by heyitsanthony** [comment]
Why can't the entity responsible for provisioning tokens just generate peer certs and use regular TLS instead of `--peer-auto-tls`?

**Comment by mitake** [comment]
@luxas I thought about this idea for a while but I'm still not sure I can provide what you want. This is because the inter peer communication between etcd is bidirectional (leader can cause fail over anytime) so generating a secure token (e.g. jwt) needs a key pair for signing and verifying in every node. For your use case, will it make the management simple?

Of course implementing the feature for easier management with other way will be valuable.

**Comment by luxas** [comment]
> so generating a secure token (e.g. jwt) needs a key pair for signing and verifying in every node

Gotcha. What about basic auth then?

**Comment by mitake** [comment]
@luxas simply adding the basic auth to `rafthttp` wouldn't be costly so I think the idea is feasible. How do you think about it? @xiang90 @heyitsanthony

**Comment by luxas** [comment]
> Why can't the entity responsible for provisioning tokens just generate peer certs and use regular TLS instead of --peer-auto-tls?

There is pretty much complexity with creating certs for everything, especially in a dynamic environment where you start the initial etcd node/master without knowing if other nodes are gonna join later or not.
When you then add a new node to the cluster you must somehow make sure the node is allowed to join the cluster and the communication must be secured as well. This would be one way to achieve that with etcd.

**Comment by heyitsanthony** [comment]
> There is pretty much complexity with creating certs for everything, especially in a dynamic environment where you start the initial etcd node/master without knowing if other nodes are gonna join later or not.

How would authorization be conducted in this case? Is there a single shared auth token for the entire cluster and spinning up a new member would reuse that?

> When you then add a new node to the cluster you must somehow make sure the node is allowed to join the cluster and the communication must be secured as well.

Why doesn't cert signing solve this?

**Comment by luxas** [comment]
> How would authorization be conducted in this case?

If you want, you could have some kind of "join" role for example. If the user has that role, the node can join.

> Is there a single shared auth token for the entire cluster and spinning up a new member would reuse that?

Doesn't have to be a single one necessarily, but possibly shared yes. Up to the implementor

> Why doesn't cert signing solve this?

It does, but is a lot more complex and requires the user to copy files around which is much harder than it could be.

**Comment by mitake** [comment]
> If you want, you could have some kind of "join" role for example. If the user has that role, the node can join.

A user needs to have a root role when the user changes membership e.g. `etcdctl member add <name> <peer URL>` if auth is enabled in the existing cluster. So you don't have to worry about the case of mistakenly or illegally added nodes.

I think that having different key pairs in each node wouldn't be so problematic because clients can be authorized with each node individually. How about generating the key pairs during initializing each etcd node?

**Comment by xiang90** [comment]
@luxas Is there any other (distributed) systems doing this? Personally, I would rather not add this when TLS auth already solves it just for the sake of "simplicity".

**Comment by luxas** [comment]
Sorry that I fell off the thread. This might be nice to have, but I don't have time to dig into the details of pros/cons with this proposal / feature request for now. I might want to revisit it in the future. If you think it's not the best idea; feel free to punt on this for now :)

**Comment by xiang90** [comment]
@luxas I am going to close this for now, since no one is going to work on it in short-mid term. Please reopen the issue when you have a better idea of why we should do this. Thank you!
