### ISSUE TITLE
Backport #8009 into 3.0?

### ISSUE THREAD

**Issue by lavalamp** [coreos/etcd#8253]
It would be super nice to have the fix for #8009 backported into 3.0.x.

@wojtek-t @mml @jpbetz

**Comment by heyitsanthony** [comment]
Unlikely to happen. Since the fix doesn't sync down the free list, booting into the patched etcd then booting into an older version of 3.0 will leak free pages at best / corrupt the db at worst.

**Comment by mml** [comment]
What does this imply for our ability to roll back from a fixed 3.1.x to a broken 3.0.x?

**Comment by heyitsanthony** [comment]
@mml 3.3.0 will have the patch and proper rollback support. Issuing a rollback would restore the backend to the slow mode with free lists before reverting the cluster version to 3.2.

**Comment by jpbetz** [comment]
@heyitsanthony If we only backported "Garbage collect pages allocated after minimum txid" (https://github.com/coreos/bbolt/pull/3) to etcd 3.0.x and 3.1.x. We might be able to resolve the most pressing issues with #8009.

We would either need to get https://github.com/boltdb/bolt/pull/694 merged or build a version of bbolt that contains https://github.com/coreos/bbolt/pull/3 but not https://github.com/coreos/bbolt/pull/1. After that, Etcd would just pick up the new versions for the minor release of 3.0.x and 3.1.x.

Does this sound reasonable? I'll be available to contribute.

**Comment by xiang90** [comment]
> We might be able to resolve the most pressing issues 

We tried it, and it will not solve what #8009 hit. A sudden free pages release due to compaction (and a previous spike on page usage) will still trigger the problem unless we stop syncing the free pages.

coreos/bbolt#3 helps more on reducing page usage on concurrent read/write txn case.

**Comment by jpbetz** [comment]
Thanks @xiang90 How did you try it? Do you have a way to replicate #8009?

**Comment by abel-von** [comment]
@xiang90 we are also considering to back port the PRs to 3.1.9 to fix the  "database space exceed" issue, Is there any way to do this ?

**Comment by xiang90** [comment]
The backport policy is documented here: https://github.com/coreos/etcd/blob/master/Documentation/branch_management.md

We could backport patches to more than one minor releases in theory, but given the people we have today, it is not feasible. I am closing this.
