### ISSUE TITLE
Can the get operation with no options set return more than one value?

### ISSUE THREAD

**Issue by rc979** [coreos/etcd#8254]
Looking at the example about the simplest get operation with no options set on GoDoc for V3 API (https://godoc.org/github.com/coreos/etcd/clientv3#ex-KV--Get) I see that for a given key ("foo") the code iterates over the response instead of assuming it's just one value. Can one safely assume that the response will only have one key/value pair for this particular case of no options set?

**Comment by gyuho** [comment]
> one safely assume that the response will only have one key/value pair for this particular case of no options set

`Get` response can also return 0 value when the key does not exist. If key exists and no option is specified (no range end, no prefix, no from-key, etc.), it should return only the latest key-value pari.
