### ISSUE TITLE
c++ how to request with token

### ISSUE THREAD

**Issue by lyhuzi** [coreos/etcd#8255]
1、git  token  by Authenticate with username and password.
2、how to build the new channel for request with token by grpc

**Comment by mitake** [comment]
Hi @lyhuzi , I hope the issue and its answers would be helpful for you: https://github.com/coreos/etcd/issues/7705

**Comment by lyhuzi** [comment]
the answer is helpful.
but i still have a question.
in grpc source， the first param must be  SecureChannelCredentials  in CompositeChannelCredentials.
if the first param is InsecureChannelCredentials， the function will return nullptr.
so i have to use SslCredentials for the channel.
but i don't hope  ssl.
do you have a solution.

**Comment by lyhuzi** [comment]
grpc::ClientContext context;
context.AddMetadata("token", response.token());
可用
