### ISSUE TITLE
etcd v3 auth enable lose efficacy

### ISSUE THREAD

**Issue by lyhuzi** [coreos/etcd#8256]
restart etcd， auth enable lose efficacy
1、start etcd
2、etcdctl set a 100
3、./etcdctl user add root
4、./etcdctl role add root
5、./etcdctl user grant-role root root
6、./etcdctl --user=root:root role grant-permission root readwrite a b
7、./etcdctl auth enable
8、./etcdctl  get a b                               #    Error:  etcdserver: permission denied
9、./etcdctl --user=root:root get a b    #    a 100
10、restart etcd
11、./etcdctl  get a b                             #  a 100

**Comment by mitake** [comment]
which version are you using? There was a problem like this in the previous version but the latest master and stable releases have a fix.

**Comment by lyhuzi** [comment]
@mitake 
etcd Version: 3.0.12
Git SHA: 2d1e2e8
Go Version: go1.6.3
Go OS/Arch: linux/amd64

**Comment by mitake** [comment]
Please try the latest master.

**Comment by xiang90** [comment]
closing since we believe it is fixed in master.
