### ISSUE TITLE
etcd mirroring going off after sometime ( 2-3 hr)

### ISSUE THREAD

**Issue by AnjaniKr** [coreos/etcd#8271]
Following is etcd service status on both machine : 
tcd.service - etcd - highly-available key value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-07-10 21:58:10 PDT; 6 days ago
     Docs: https://github.com/coreos/etcd
           man:etcd
 Main PID: 4673 (etcd)
    Tasks: 9
   Memory: 30.4M
      CPU: 38min 27.665s
   CGroup: /system.slice/etcd.service
           └─4673 /usr/bin/etcd

This is how I'm starting etcd mirroring : 
etcdctl --endpoints https://x.x.x.x:2379 --cacert host.pem make-mirror --prefix /realm/realm1 --dest-prefix=/realm/realm1 https://x.x.x.x:2379 --dest-cacert target.pem

**Comment by heyitsanthony** [comment]
what are the server logs from `journalctl --unit etcd.service ` around the time it stops? what version etcd server/client?

**Comment by AnjaniKr** [comment]
@heyitsanthony 

etcdctl -version
etcdctl version: 3.2.0+git
API version: 2
# ETCDCTL_API=3 etcdctl version
etcdctl version: 3.2.0+git
API version: 3.2

There r no  entries in journalctl

**Comment by gyuho** [comment]
What's the output of `systemctl cat etcd.service`? Please provide exact steps to reproduce.

**Comment by heyitsanthony** [comment]
`ETCDCTL_API=3 ./bin/etcdctl -w table endpoint status` and `ETCDCTL_API=3 ./bin/etcdctl -w json alarm list` may also be helpful here.

**Comment by AnjaniKr** [comment]
op - systemctl cat etcd.service
[Unit]
Description=etcd - highly-available key value store
Documentation=https://github.com/coreos/etcd
Documentation=man:etcd
After=network.target
Wants=network-online.target

[Service]
Environment=DAEMON_ARGS=
Environment=ETCD_NAME=%H
Environment=ETCD_DATA_DIR=/var/lib/etcd/default
EnvironmentFile=-/etc/default/%p
Type=notify
User=etcd
PermissionsStartOnly=true
#ExecStart=/bin/sh -c "GOMAXPROCS=$(nproc) /usr/bin/etcd $DAEMON_ARGS"
ExecStart=/usr/bin/etcd $DAEMON_ARGS
Restart=on-abnormal
#RestartSec=10s
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
Alias=etcd2.service

**Comment by AnjaniKr** [comment]
op - ETCDCTL_API=3 etcdctl --endpoints https://x.x.x.x:2379 --cacert server.pem -w table endpoint status

+-----------------------------+------------------+-----------+---------+-----------+-----------+------------+
|          ENDPOINT           |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+-----------------------------+------------------+-----------+---------+-----------+-----------+------------+
| https://x.x.x.x:2379 | ce2a822cea30bfca | 3.2.0+git | 19 MB   | true      |        10 |        719 |
+-----------------------------+------------------+-----------+---------+-----------+-----------+------------+

**Comment by AnjaniKr** [comment]
ETCDCTL_API=3 etcdctl --endpoints https://x.x.x.x:2379 --cacert server.pem -w json alarm list
{}

**Comment by AnjaniKr** [comment]
its writing only etcd service log but not mirror log, for mirroring I'm redirecting to file and only numbers are printed on this file

**Comment by gyuho** [comment]
> its writing only etcd service log but not mirror log

What's the etcd error message?

And what's the etcdctl error message?

Try to reproduce without systemd?

**Comment by AnjaniKr** [comment]
there is no etcd error since its running fine
etcdctl doesn't write any error logs so not able to reproduce what's exact cause.

**Comment by gyuho** [comment]
Ok, I will try to reproduce tomorrow. Thanks.

**Comment by gyuho** [comment]
> only numbers are printed on this file

This means mirroring runs fine.

How do you know `make-mirror` is off? Does the process just exit? If so, there should be an error. Did you also redirect stderr from `etcdctl` process?

I tried `make-mirror` with TLS and runs fine.

**Comment by AnjaniKr** [comment]
I ran ps -ef | grep mirror - there was no process running. There is no log written to the temp file where I'm redirecting the stdout & stderr. Only numbers are printed for the time it is running. Is there any specific flag I need to set for the same

**Comment by gyuho** [comment]
> Only numbers are printed for the time it is running

This is expected.

> I ran ps -ef | grep mirror - there was no process running

Did you run `make-mirror` with systemd? Then `journalctl` should have logs whether `make-mirror` exited or not (not an etcd issue).

Or just as a command? Then machine or VM reboot will just exit the process without any error logs?

**Comment by gyuho** [comment]
Please reopen when you have exact steps to reproduce.
