### ISSUE TITLE
Multikey operation in etcd

### ISSUE THREAD

**Issue by RadhikaBhat** [coreos/etcd#8276]
I'm using etcd tool to save key value pair data. I have a use-case where I need to perform batch get, bulk insertion on etcd through the Go API

Does etcd support multikey operations?

Thanks in advance!

**Comment by xiang90** [comment]
see txn here: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#service-kv-etcdserveretcdserverpbrpcproto

**Comment by RadhikaBhat** [comment]
@xiang90 Thank you for the response..does HTTP Go API support this ? or it's just gRPC ?

**Comment by daniel-kotler-exa** [comment]
> see txn here: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_reference_v3.md#service-kv-etcdserveretcdserverpbrpcproto

Does a txn "compare" can be true by default?
