### ISSUE TITLE
Auth Token expiration

### ISSUE THREAD

**Issue by vedant15** [coreos/etcd#8287]
Hello,

I am writing a Node.js client for etcd(v3) and I am in middle of implementing the authentication part.
My question is after the `authenticate` call when does the auth `token` expires ?

What is the criteria for expiration , is it based on duration of the token or how long the client remains idle ?

In case,  the expiration is based on the period for which client remains idle, should I send regular requests to keep the token alive ? Will the token still expire if I have a `watch` or a `lease` (since it's a streaming RPC) 

My apologies if my questions are dumb, I am new to world of etcd

**Comment by mitake** [comment]
> My question is after the authenticate call when does the auth token expires ?

In the case of simple token, the tokens will be expired after 5 min of token generation. In the case of jwt, currently token expire is not supported (yes, it must be supported in the future).

Issuing requests doesn't help to extend the token TTL. The expiration can be handled in a transparent manner in the client libraries (in the case of go clientv3: https://github.com/coreos/etcd/blob/master/clientv3/retry.go#L67)

In the case of watch, the token will be checked every watch iteration. In the case of lease, the token will be checked during `Grant()`.

**Comment by vedant15** [comment]
thanks @mitake for your response

So if I understand correctly, for `lease` and `watch` the token expiration has no effect unless I try to create a new lease or create a watch (or is it on each time etcd sends a watch event).

**Comment by mitake** [comment]
@vedant15 yes, the expiration doesn't affect in these cases. You can retry simply.

**Comment by vedant15** [comment]
thanks @mitake

**Comment by fanminshi** [comment]
@mitake  `Issuing requests doesn't help to extend the token TTL.`

I was looking into the code, it seems to me that Issuing `Get` with `AuthEnable` do extend the token TTL. Please correct me If I am wrong.

`kvServer.Range` -> `EtcdServer.Range` -> ... -> `EtcdServer.AuthInfoFromCtx` -> `authStore.AuthInfoFromCtx` -> `authStore.authInfoFromToken` -> `tokenSimple.info`

```go
func (t *tokenSimple) info(ctx context.Context, token string, revision uint64) (*AuthInfo, bool) {
	if !t.isValidSimpleToken(ctx, token) {
		return nil, false
	}
	t.simpleTokensMu.Lock()
	username, ok := t.simpleTokens[token]
	if ok && t.simpleTokenKeeper != nil {
		t.simpleTokenKeeper.resetSimpleToken(token) // renew token TTL if token is not expired. 
	}
	t.simpleTokensMu.Unlock()
	return &AuthInfo{Username: username, Revision: revision}, ok
}
```

https://github.com/coreos/etcd/blob/master/auth/simple_token.go#L174-L185

**Comment by mitake** [comment]
@fanminshi thanks for pointing, I forgot about the behaviour. As you say, simple token extends TTL in the way.

I'm also planning to add a new option for configuring TTL including the case of JWT. In the case of JWT, extending TTL is impossible. So I'm not sure that guaranteeing issuing nop RPCs extending TTL is a good idea. Actually clients can simply retrying auth for renewing their tokens.

**Comment by fanminshi** [comment]
@mitake thanks for your clarification.
