### ISSUE TITLE
functional-tester: txn stresser

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8293]
Bugs in the txn code can lead to inconsistencies among members distinct from bugs caused by only puts/gets, so it should be tested in the functional tester. Although the etcd-runner tests use txns in some places, the throughput/concurrency/txn complexity isn't enough.

Flat txns could be stressed via:
1. Have a set of keys K (e.g., "/k0", "/k1", ..., "/k9")
2. Choose random keys kA...kB from K
3. Submit a txn If(kA.Version > 0, ..., kB.Version > 0).Then(Delete kA...kB).Else(Put kA...kB). 

Nested txns stressing could assign a key per level:

```
If (kA.Version > 0) {
   Delete(kA)
   If (kB.Version > 0) {
      Delete(kB)
   } else {
      Put(kB)
   }
} else {
    Put(kA)
    If (kB.Version > 0) { ... }
}
```

Related: #8214

**Comment by xiang90** [comment]
1. All client write requests are executed in one single thread non-concurrently. 
2. The only thing might happen concurrently with client writes is compaction. 

We either violates 1, or there is a bug in 2.

Is there anything else missed?

**Comment by xiang90** [comment]
oh. or there is a bug in the recovery/restore logic.
