### ISSUE TITLE
etcdctl: Proper exit status of endpoint subcommand 

### ISSUE THREAD

**Issue by koorgoo** [coreos/etcd#8295]
etcdctl may be used for simple monitoring to check etcd cluster's health.
However, as of now `etcdctl endpoint health` returns 0 for a dead endpoint.

```
$ etcdctl endpoint health
127.0.0.1:2379 is unhealthy: failed to connect: dial tcp 127.0.0.1:2379: getsockopt: connection refused
$ echo $?
0
```

Expected exit statuses of `etcdctl endpoint health` command:
- for single endpoint:
  - `0` - endpoint is healthy
  - non-`0` - endpoint is unhealthy
- for multiple endpoints:
  - `0` - all endpoints are healthy
  - non-`0` - one or more endpoints are unhealthy

```
$ etcdctl version
etcdctl version: 3.2.4
API version: 3.2
```

**Comment by xiang90** [comment]
@koorgoo This is a bug. Would you like to help us fix it?

**Comment by koorgoo** [comment]
@xiang90 Yeah! With pleasure!
