### ISSUE TITLE
How to put multiple key-values by one API?

### ISSUE THREAD

**Issue by 201tank** [coreos/etcd#8303]
Is there is an API with which we can put multiple key-values into etcd together? I know that the Put operation can set key-value, but it can just put one everytime. Maybe, I can call the Put API for the multiple key-values one by one, maybe it's not good performance because there will be many API calls.

**Comment by heyitsanthony** [comment]
Use [transactions](https://godoc.org/github.com/coreos/etcd/clientv3#Txn).

Example:
```go
c, err := clientv3.New(...)
if err != nil { ... }
txnresp, err = c.Txn(context.TODO()).
    If(clientv3.Compare(clientv3.Version("key"), ">", 0)).
    Then(clientv3.OpPut("key", "key already exists"), clientv3.OpPut("key2", "other key")).
    Else(clientv3.OpPut("key", "key is new"),  clientv3.OpPut("key3", "other key")).
    Commit()
if err != nil { ... }
```

**Comment by 201tank** [comment]
Thanks!
