### ISSUE TITLE
etcd client keeps the connection with a node which can not connect to leader.

### ISSUE THREAD

**Issue by abel-von** [coreos/etcd#8308]
We are doing the HA test, and we found that when we cut the network connection between between an etcd instance and the leader, the etcd client do not close the connection with that instance. and all request will return a `grpc timeout` error.

I know that the etcd client will keep using a long live connection with one node of the cluster to send its request, until the connection is closed, by network partition or when the node stopped. but any etcd error will not make the client close the connection by its own.

I think maybe we can change the code to check the error, by some of the errors (like the grpc timeout error), we can close the connection and retry to request to other nodes.

**Comment by gyuho** [comment]
Related https://github.com/coreos/etcd/issues/8022.

**Comment by gyuho** [comment]
Superseded by https://github.com/coreos/etcd/issues/8660.
