### ISSUE TITLE
How to migrate Data from v2.3.7 to v3.2.4

### ISSUE THREAD

**Issue by penglongli** [coreos/etcd#8336]
## Description
First, i have a etcd-cluster with v2.3.7, `data-dir` is `/data/etcd`, run on `host-1/host-2/host-3`
Then,  i have a new etcd-cluster with 3.2.4, `data-dir` is `/data/etcd`, run on `host-4/host-5/host-6`

## What's i want
And i want to migrate the **Data** from the old-cluster(v2.3.7) to the new-cluster(v3.2.4).

I had saw some documents, but i didn't find what I wanted. If there has some documents can help me?

## End
If I don't have a clear description, please advise. Thank you for seeing this ISSUE.

**Comment by gyuho** [comment]
Have you checked https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrading-etcd.md?

**Comment by penglongli** [comment]
@gyuho Yeah, i checked it. 
According to this URL, it looks like i can only upgrade from v2.3 to v3.0, and then from v3.0 to v3.1, and from v3.1 to v3.2. I need step by step upgrade,  is that so?

**Comment by gyuho** [comment]
@penglongli Yes, right.
