### ISSUE TITLE
etcdv3.client.Watch is not thread safe

### ISSUE THREAD

**Issue by stefan-improbable** [coreos/etcd#8338]
clientv3.Client.Watch(ctx, ...) is not thread safe when ctx is CancellableContext.
https://github.com/coreos/etcd/blob/master/clientv3/watch.go#L216 can panic on "concurrent map iteration and map write". I think we should take address of that `inctx`.

**Comment by heyitsanthony** [comment]
@stefan-improbable the ctx's GoString method is not thread safe. See #8275 for a fix.

**Comment by devnev** [comment]
Why not just use the actual value of the context object without converting it to a string? From a quick check of the code that seems like it should work fine. Requiring a concurrency-safe String() is not supported by the base context libraries and will require every single context to be wrapped... this looks like a landmine for anyone using watchers.

**Comment by stefan-improbable** [comment]
Also, if you have:
```
func RPCMethod(ctx *context.Context, ...) {
    cctx, _ := context.WithCancel(ctx)
   ...
}
```
`ctx` and `cctx` will have different `fmt.Sprintf("%v", ...)` representations even though they are on the same connection.

**Comment by mwitkow** [comment]
@xiang90 has any other users of etcd3 watchers, including Kubernetes, hit something similar?
