### ISSUE TITLE
No option for running etcd in docker v.3 ?

### ISSUE THREAD

**Issue by bgrissin** [coreos/etcd#8340]
# Cant find a reference for v3 as easily as the v2 release defined a way to run etcd in docker container (or swarm cluster)

**Comment by heyitsanthony** [comment]
@bgrissin have you tried the [docker cointainer guide](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md#docker)?

**Comment by bgrissin** [comment]
the issue is getting into any of the containers and being able to run any commands such as etcdctl

**Comment by gyuho** [comment]
@bgrissin You can try the example usage here https://github.com/coreos/etcd/releases.

```
docker exec etcd-v3.2 /bin/sh -c "export ETCDCTL_API=3 && /usr/local/bin/etcd -version"
docker exec etcd-v3.2 /bin/sh -c "export ETCDCTL_API=3 && /usr/local/bin/etcdctl version"
docker exec etcd-v3.2 /bin/sh -c "export ETCDCTL_API=3 && /usr/local/bin/etcdctl endpoint health"

docker exec etcd-v3.2 /bin/sh -c "export ETCDCTL_API=3 && /usr/local/bin/etcdctl put foo bar"
docker exec etcd-v3.2 /bin/sh -c "export ETCDCTL_API=3 && /usr/local/bin/etcdctl get --consistency=s foo"
```

**Comment by bgrissin** [comment]
Unable to find image 'quay.io/coreos/etcd:v3.2' locally
v3.2: Pulling from coreos/etcd
88286f41530e: Pull complete 
45382447aa91: Pull complete 
0c499c291c78: Pull complete 
c9f676bdc3ac: Pull complete 
2de528bc9712: Pull complete 
8050aa75d456: Pull complete 
Digest: sha256:c5d7bc89aa6140db5645670cb9a1c47e9812f7fe7bb492442f8637abaaa3a3a4
Status: Downloaded newer image for quay.io/coreos/etcd:v3.2
93a5a3043a552d5dc3e83379d4ef3e3764eb692d224bc645df83f20eb680bf5e
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"-name\": executable file not found in $PATH".

Obviously still issues with using Docker APIs to gain access to the namespace!  why close this ?

**Comment by gyuho** [comment]
@bgrissin 

> docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: "-name": executable file not found in $PATH".

What command did you run to get this error?

**Comment by heyitsanthony** [comment]
I run it with `docker run  --rm --name etcd quay.io/coreos/etcd:latest /usr/local/bin/etcdctl -v`

**Comment by gyuho** [comment]
@bgrissin Ping? Did you figure out?

**Comment by pockywei** [comment]
`docker exec $CONTAINER_ID /bin/sh -c "export ETCDCTL_API=3 && /usr/local/bin/etcdctl --cert="/etc/kubernetes/pki/etcd/peer.crt" --key="/etc/kubernetes/pki/etcd/peer.key" --cacert="/etc/kubernetes/pki/etcd/ca.crt" --endpoints=[https://$endpoints:$port] endpoint status"`

This works for me. Thanks! @gyuho
