### ISSUE TITLE
Grant permission for a set of keys in etcd-v3 Go client

### ISSUE THREAD

**Issue by Abhijith1** [coreos/etcd#8343]
I'm using the Go client v3 to store keys in a hierarchical manner:
`one/one <val>` 
`one/two <val>`
`one/three/four`
and so on.
How do I grant permission to all the keys under "one" to a role.

RoleGrantPermission() doesn't solve my problem since the key hierarchy is not static and new keys maybe added anytime. So, giving a rangeEnd isn't possible when a role is created.

This can be achieved in etcdctl by specifying the prefix=true for the grant-permssion command like this:
`ETCDCTL_API=3 etcdctl --user="root:root" role grant-permission testRole --prefix=true readwrite one/`
What is the equivalent for this in the Go clientv3?

**Comment by gyuho** [comment]
Here's how we do it in etcdctl https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/role_command.go#L208.

```go
// returns range end
clientv3.GetPrefixRangeEnd(args[0])
```

**Comment by Abhijith1** [comment]
@gyuho Thank you! Solves my problem 👍
