### ISSUE TITLE
the problem of raftexample 

### ISSUE THREAD

**Issue by 42701618** [coreos/etcd#8345]
After using raftexample,I send data to the raftexample server.Every time I send 50000 reqeusts to the server,
After some hour, there are some error ;"out of memory........."

**Comment by gyuho** [comment]
Do you have reproducible code?

> out of memory

Or your machine is just out of memory...

**Comment by 42701618** [comment]
I can reproduce it.I try it in 16G or 48G machine

**Comment by gyuho** [comment]
@42701618 How do you send 50k requests to the raftexample server?
It's **example** to show how to use raft package... so do not expect it to perform like etcd.

**Comment by 42701618** [comment]
wait for moment，please.I am ready the code.

**Comment by 42701618** [comment]
main.go

package main

import (
  "net/http"
  _ "net/http/pprof"
  "*****/raft"
  "time"
  "fmt"
)

func main() {
  go func() {
    fmt.Printf(http.ListenAndServe("localhost:6060", nil))
  }()
  raftcluest  := cacheraftkv.NewRaftCluster()
  go raftcluest.StartClutster()
  fmt.Printf("Raft server is running")

  var key string = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa8.bbb.ccc.ddddddddddddddddddddddd.eeeeeeeeeed:ffffffffffffffffffffffffffffffffffffffff"
  var valueJson = "{\"gggggg\":{\"hhhhhhhhh\":\"iiiiiii\",\"jjjjjjjjjj\":[{\"jjjj\":\"ikkkkkkkkkk\",\"lllll\":\"mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm\"}],\"ooooooooooo\":\"ppppppppppppppppppppppp\"},\"qqq\":\"%d\",\"tttttttttttt\":\"%d\",\"ggggg\":\"%d\",\"unit\":\"B/s\"}"
  var val_fm string = "{\"Value\":" + valueJson + ",\"TTL\":%d}"


  for {
    go func() {
      for i := 0; i < 50000; i++ {
        raftcluest.KVS.Propose(key,val_fm)
      }
    }()
    time.Sleep(10 * time.Second)
  }

}

**Comment by 42701618** [comment]
raftcluster.go

package cacheraftkv

import (
  "github.com/coreos/etcd/raft/raftpb"

  "fmt"
  "flag"
  "strings"
)

type RaftCluster struct {
  id               int
  join             bool
  peers            []string
  proposeC         chan string
  confChangeC      chan raftpb.ConfChange
  KVS              *KvStore
}

func NewRaftCluster() *RaftCluster {
  cluster := flag.String("cluster", "http://127.0.0.1:9021", "comma separated cluster peers")
  peers := strings.Split(*cluster, ",")
  id := 1
  join := false
  kvs := &KvStore{}
  clus := &RaftCluster{
    id:id,
    join:join,
    peers:peers,
    KVS:kvs,
  }
  return clus
}
func (rc *RaftCluster) StartClutster() {
  rc.proposeC = make(chan string)
  defer close(rc.proposeC)
  rc.confChangeC = make(chan raftpb.ConfChange)
  defer close(rc.confChangeC)

  getSnapshot := func() ([]byte, error) {
    return rc.KVS.getSnapshot()
  }
  commitC, errorC, snapshotterReady := newRaftNode(rc.id, rc.peers, rc.join, getSnapshot, rc.proposeC, rc.confChangeC)
  rc.KVS = newKVStore(<-snapshotterReady, rc.proposeC, commitC, errorC)
  if err, ok := <-errorC; ok {
    fmt.Printf(err)
  }
  fmt.Printf("!!error:%v",errorC)

}

**Comment by 42701618** [comment]
other file depend on raft example

**Comment by gyuho** [comment]
@42701618 As I said, it's overloading the raftexample that is not built for such workloads. Your code is writing >10MB in the for-loop. So it's easy to reach the memory limit. Please use etcd or other database if you need that much throughput.

**Comment by 42701618** [comment]
the etcd do not use storage.go?

**Comment by gyuho** [comment]
@42701618 etcd is key-value store. https://godoc.org/github.com/coreos/etcd/clientv3
