### ISSUE TITLE
etcdctl: endpoint hash command

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8348]
Support hashing the KV store through etcdctl.

**Comment by heyitsanthony** [comment]
This should also include an update to op-guide/v2-migration.md with an example to check the hashes

**Comment by gyuho** [comment]
I am also interested, for play.etcd.io.

Should we also expose Hash API to clientv3 and go from there?
Then adding hash field to `StatusResponse`?
Or just separate wrapper in clientv3 for `HashResponse`.

**Comment by heyitsanthony** [comment]
@gyuho I'm hesitant to change `StatusResponse` to include data that's not returned by the status RPC. Just `HashKV(int64) (*HashKVResponse, error)` under the maintenance interface should be OK.
