### ISSUE TITLE
Database significantly larger than contents

### ISSUE THREAD

**Issue by immesys** [coreos/etcd#8352]
I have a cluster with about 20k keys in it, most of them fairly small (<100 bytes), but the size of the database is larger than I would expect. My intuition could be wrong, but I wanted to reach out and see if someone could help me work out what is going on.

There are no v2 keys

There are 22k v3 keys

The size of a snapshot and the size reported in endpoint status is 2.6GB after compaction and 1.6GB after defrag.

If I dump everything as protobuf/json with `ETCDCTL_API=3 etcdctl get "" --prefix -w protobuf > content.pb` then it is only 2.4MB (4.5MB for json)

The size has started to cause problems for me (like backups not working because the snapshot took too long). Why is the size on disk/snapshot 3 orders of magnitude bigger than the contents exported as protobuf/json? Is there some other kind of history that I can get rid of with something other than compaction/defrag?

BTW I get similar results on 3.2.4 and 3.1.8.

**Comment by gyuho** [comment]
> 20k keys in it

what's the size of value?

**Comment by immesys** [comment]
Most values are about 10-20bytes, but when you export as protobuf it incudes the values (+revisions+version etc), so the information in the keys+values together is less than 2.4MB

**Comment by immesys** [comment]
The biggest value is maybe 500 bytes

**Comment by xiang90** [comment]
@immesys 

have you ever compacted your kv space?

**Comment by xiang90** [comment]
and how did you run the compact/defrag command?

**Comment by immesys** [comment]
I have a production cluster of three machines running 3.1.8. To try and investigate this more, I took a snapshot from that and restored it on a single node 3.1.8 (and a 3.2.4 in case it was fixed). I did an etcdctl get on a key to get the global revision and did `ETCDCTL_API=3 etcdctl compaction <rev>`. This did not change the size (it stays at 2.6GB) but I suspect it was already compacted because of the snapshot (or because production compacts every hour). I then did `ETCDCTL_API=3 etcdctl defrag` with a long command timeout. It finishes after a few tens of seconds and the database size is then 1.6GB on 3.2.4 and 1.3GB on 3.1.8. If I do a snapshot after the defrag, the new snapshot is exactly the same size as the database directory.

I can give you the snapshot if you would like.

**Comment by xiang90** [comment]
@immesys 

can you try to pull out all the keys, recreate a fresh etcd cluster, and put the keys to the new cluster? then check the size of the new cluster?

you can email it to me at xiang.li@coreos.com. i can take a look later this week. i suspect there is a really simple cause somewhere.

**Comment by immesys** [comment]
I did actually just notice something. Look at this:

```
 ETCDCTL_API=3 ./etcdctl get "" --prefix --keys-only --hex=true | wc -l
44536
```
So ~45k keys by that method. But look at the snaphsot itself:

```
 ETCDCTL_API=3 ./etcdctl snapshot status ../foo.sn -w table
+----------+-----------+------------+------------+
|   HASH   | REVISION  | TOTAL KEYS | TOTAL SIZE |
+----------+-----------+------------+------------+
| 114f3112 | 167175255 |   11305527 |     2.7 GB |
+----------+-----------+------------+------------+
```

That says 11 million keys. Now it's not impossible that my software has a bug and has put 11 million keys in when I was not expecting it, but why do they not show up in `get "" --prefix` ?

Also, when I do this
```
ETCDCTL_API=3 ./etcdctl get "" --prefix -w json | jq . | tail -n 10
```
I get this field at the end, which is why I (perhaps erroneously) thought there were only 22k keys

```
  "count": 22268
}
```

**Comment by xiang90** [comment]
@immesys 

how did you do the compaction?

you need to something like `etcdctl compact 167175255`

**Comment by immesys** [comment]
Yeah, like that. This is what I get when I do it again:

```
$ export ETCDCTL_API=3
$ ./etcdctl endpoint status -w json | jq '.[0].Status.header.revision'
167175256
$ ./etcdctl compact 167175256
Error:  etcdserver: mvcc: required revision has been compacted
```

**Comment by xiang90** [comment]
@immesys have you created a lot of leases?

**Comment by immesys** [comment]
Possibly, but I doubt that many. It's a 5 second lease and we use client.KeepAlive(). We don't create more than 1 per execution and I doubt we have restarted more than a few thousand times.

**Comment by xiang90** [comment]
there should be lease list command. can you try that out?

**Comment by immesys** [comment]
I can't find the lease list command, only variants that take an id

**Comment by xiang90** [comment]
@immesys OK. too bad then. probably you have to send the snapshot to me... we will write some docs around debugging the snapshot file in the future.

**Comment by immesys** [comment]
Ok am uploading it somewhere, I'll email you a link. 

I actually can't find a way to list leases either with etcdctl or the go clientv3 bindings, is there a way?

**Comment by xiang90** [comment]
@immesys probably i remember it incorrectly :( at some point, we thought about adding it. probably we decided it is a bad idea if no one has ever asked for it.

**Comment by immesys** [comment]
@xiang90 any ideas? Did you get the snapshot I emailed?

**Comment by xiang90** [comment]
@immesys yes. i will take a look today.

**Comment by xiang90** [comment]
@immesys 

I took a look at the db file you sent me. There are tons of historical keys. Then I did a compaction at the most recent revision: 167117792. It took 1 minutes or so to finish the compaction since there are A LOT OF keys. Then I did a defrag. The db size went back to 77MB.

**Comment by immesys** [comment]
Ok, thank you, it turns out I was not waiting for the compaction to finish (I needed physical=true)

**Comment by xiang90** [comment]
@immesys Glad that you figured it out.
