### ISSUE TITLE
etcdv2 migration http -> https

### ISSUE THREAD

**Issue by gambol99** [coreos/etcd#8353]
Hiya

Version: v2.2.1 (I know!) found [here](https://github.com/kubernetes/kops/blob/master/protokube/pkg/protokube/etcd_manifest.go#L39-L40)
Image: gcr.io/google_containers/etcd

This is less of a bug and more reaching out for advice. I recently raised a PR on [kops](https://github.com/kubernetes/kops) to provide a long required feature of TLS on the etcd cluster [#PR3114](https://github.com/kubernetes/kops/pull/3114). While whipping up a new cluster isn't an issue I would need to provide a migration path of those already using http peers. I attempted to update a previous cluster and while the advertised client urls are updated to https, the peer url remain on http. I was able to migrate manually via doing a 'member update' and changing the peer url, but obviously I like this to be seamless. Any advice?

**Comment by gyuho** [comment]
We have https migration doc here https://coreos.com/etcd/docs/latest/etcd-live-http-to-https-migration.html.

But strongly recommend to upgrade to v3 first, since we have fixed a lot of TLS issues, and v2 TLS still has some edge cases we haven't figured out. v2 will be deprecated soon.
