### ISSUE TITLE
etcdctl: set ETCDCTL_API=3 by default

### ISSUE THREAD

**Issue by koorgoo** [coreos/etcd#8354]
As of version >= 3 (3.2.4 currently) should admins continue to `export ETCDCTL_API=3`?
Is there something critical what forbids to set api version to 3 by default?

**Comment by heyitsanthony** [comment]
@koorgoo Yes, the reason is that defaulting to api=3 will break any scripts that rely on etcdctl for v2 features. It'll be a default in the future, but v2 still isn't fully deprecated.

**Comment by koorgoo** [comment]
Good old legacy... Thank you for comment.
