### ISSUE TITLE
etcd2.3 upgrade to etcd3.2: remote version is too low

### ISSUE THREAD

**Issue by RayQiQi** [coreos/etcd#8362]
2.3 upgrade to 3.2 directly is not support?
If we'd like to do this upgrade, what step should we do?

Aug 03 08:32:26 node1 etcd[7846]: set the initial cluster version to 2.2
Aug 03 08:32:26 node1 etcd[7846]: enabled capabilities for version 2.2
Aug 03 08:32:26 node1 etcd[7846]: started streaming with peer c5c32c983df15f43 (stream MsgApp v2 reader)
Aug 03 08:32:26 node1 etcd[7846]: updated the cluster version from 2.2 to 2.3
Aug 03 08:32:26 node1 etcd[7846]: enabled capabilities for version 2.3
Aug 03 08:32:26 node1 etcd[7846]: request sent was ignored by peer 1c0237f83d17c6d1 (server version incompatible)
Aug 03 08:32:26 node1 etcd[7846]: request sent was ignored by peer 1c0237f83d17c6d1 (server version incompatible)
Aug 03 08:32:26 node1 etcd[7846]: request sent was ignored by peer c5c32c983df15f43 (server version incompatible)
Aug 03 08:32:26 node1 etcd[7846]: request sent was ignored by peer c5c32c983df15f43 (server version incompatible)
Aug 03 08:32:26 node1 etcd[7846]: request version incompatibility (remote version is too low: remote[c5c32c983df15f43]=2.3.7, local=3.2.1)
Aug 03 08:32:26 node1 etcd[7846]: request version incompatibility (remote version is too low: remote[1c0237f83d17c6d1]=2.3.7, local=3.2.1)
Aug 03 08:32:26 node1 etcd[7846]: request version incompatibility (remote version is too low: remote[c5c32c983df15f43]=2.3.7, local=3.2.1)
Aug 03 08:32:26 node1 etcd[7846]: request version incompatibility (remote version is too low: remote[c5c32c983df15f43]=2.3.7, local=3.2.1)
Aug 03 08:32:26 node1 etcd[7846]: request version incompatibility (remote version is too low: remote[c5c32c983df15f43]=2.3.7, local=3.2.1)
Aug 03 08:32:26 node1 etcd[7846]: request version incompatibility (remote version is too low: remote[1c0237f83d17c6d1]=2.3.7, local=3.2.1)

**Comment by gyuho** [comment]
Upgrade must be done sequentially.

2.3 -> 3.0, 3.0 -> 3.1, ...

We have more docs here:

1. https://github.com/coreos/etcd/blob/master/Documentation/op-guide/v2-migration.md
2. https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrading-etcd.md
