### ISSUE TITLE
separate insecure /health

### ISSUE THREAD

**Issue by Unb0rn** [coreos/etcd#8363]
Hello!
It's not a bug, but more like feature request/search for advice.
I'm trying to run a secure etcd cluster on container linux on top of GCE, but due to lack of some features in GCE itself, it seems to be impossible to use health checks on HTTPS (HTTPS health checks are incompatible with Network load balancer and I think it's impossible to use client certificates with HTTPS on other kinds of load balancers, where HTTPS itself is available)
So, are there any workarounds? Maybe there is a way to host /health on http(or it would be a great feature for such plantforms) Maybe there are some kind of proxies, which would use required certs and then return state via HTTP? Some best practices? Thanks!

**Comment by gyuho** [comment]
We've added `--metrics-addr` flag https://github.com/coreos/etcd/pull/8282. It will be included in our next major release.
