### ISSUE TITLE
etcdctl(V3)：reduce session timeout for lock command

### ISSUE THREAD

**Issue by jiaxuanzhou** [coreos/etcd#8365]
1,the default timeout of lock command is etcd\clientv3\concurrency\session.go: `defaultSessionTTL = 60`
in the production scenario, when there is an unexpected  server crash of the client side(container scenario: kill the docker), the client process can not capture the signal of the syscall, then the other clients must wait 60s to gain the lock, the timeout is too long in production environment, i suggest to reduce the timeout to less than 10s.

2, suggest add another mechanism to ensure the lock will be released immediately when the client process who holds the lock exited. 
Currently code just capture two kind of syscall signals to inform the process to close the communication link: `signal.Notify(sigc, syscall.SIGINT, syscall.SIGTERM)`

**Comment by heyitsanthony** [comment]
> i suggest to reduce the timeout to less than 10s.

How about a `--ttl` flag so it's configurable?

> add another mechanism to ensure the lock will be released immediately when the client process who holds the lock exited.
> Currently code just capture two kind of syscall signals to inform the process to close the communication link: signal.Notify(sigc, syscall.SIGINT, syscall.SIGTERM)

What other mechanism?

**Comment by jiaxuanzhou** [comment]
@heyitsanthony 
i agree with you if adding a flag to config the ttl, it can avoid the long waits when seesion expired and no other mechanism needed with a flag.

**Comment by xiang90** [comment]
@jiaxuanzhou do you want to work on this improvement?

**Comment by jiaxuanzhou** [comment]
@xiang90 i can work on it ,will submit a patch soon.

**Comment by xiang90** [comment]
@jiaxuanzhou thanks!

**Comment by jiaxuanzhou** [comment]
@xiang90 i found NewSession(client *v3.Client, opts ...SessionOption) is called by elect cmd two, need to add the flag as a gloabal role  or just as a sub-flag used by lock ?

**Comment by jiaxuanzhou** [comment]
@heyitsanthony 
related PR #8370 has been merged , the issue could be closed.

**Comment by heyitsanthony** [comment]
ok, thanks!
