### ISSUE TITLE
etcdv3 API can not support CompareAndSwip?

### ISSUE THREAD

**Issue by Steven086** [coreos/etcd#8376]
can  not  find how to call CAS from a v3 client as per api document

**Comment by yudai** [comment]
@Steven086 There is no CAS function in the v3 library, but [you can use `Tnx`(https://godoc.org/github.com/coreos/etcd/clientv3#Txn) instead]. It's more flexible than the simple CAS operation.

**Comment by gyuho** [comment]
@Steven086 Please try `Txn` as @yudai suggested.
