### ISSUE TITLE
health check for peer could not connect: dial tcp error

### ISSUE THREAD

**Issue by beyondli** [coreos/etcd#8377]
when I create 3 node cluster, and with static bootstrapping to start cluster. but I found each node are depend with others two. the error is :

since all three node will start and depend with others , configure likes for all nodes : 
--initial-cluster k8server=https://10.6.128.100:2380,k8node1=https://10.6.128.101:2380,k8node2=https://10.6.128.102:2380 \\
--initial-cluster-state new \\

I start any of them will error like below will occur.  so someone can help me ?? 
seems it is easy to start cluster with static  bootstrapping
--------------------------------
Aug 08 15:31:57 k8node2 etcd[15011]: publish error: etcdserver: request timed out
Aug 08 15:31:57 k8node2 etcd[15011]: health check for peer f54a37612c5cfa79 could not connect: dial tcp 10.6.128.100:2380: i/o timeout
Aug 08 15:31:57 k8node2 etcd[15011]: health check for peer ff1a39e8ec6861fc could not connect: dial tcp 10.6.128.101:2380: i/o timeout
Aug 08 15:31:59 k8node2 etcd[15011]: 7ae45426b59675d8 is starting a new election at term 2316
Aug 08 15:31:59 k8node2 etcd[15011]: 7ae45426b59675d8 became candidate at term 2317

**Comment by beyondli** [comment]
seems firewell is not closed!! more test!!

**Comment by gyuho** [comment]
> seems firewell is not closed!! more test!!

What do you mean? Do you set up firewall? Then it's not an etcd issue.

**Comment by beyondli** [comment]
yes, just because centos default firewell state is running which prohibit tcp connection among peers. when I close firewell. etcd run OK. right, not ETCD itself.

**Comment by 32328254** [comment]
systemctl stop firewalld.service & systemctl disable firewalld.service
try runing？
