### ISSUE TITLE
exit with error on shadowed environment variables

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8380]
Configure etcd to have both an environment variable and flag for some option:
```sh
$ export ETCD_WHATEVER=abc
$ etcd --whatever=def
```

etcd will warn that ETCD_WHATEVER is shadowed and use --whatever.  Given a lot of documentation out there suggests using environment variables in drop-ins, I suspect this permissiveness leads to some degree of breakage. Is this worth deprecating away?

**Comment by gyuho** [comment]
@heyitsanthony 

> I couldn't come up with any compelling reasons for why anyone would want shadowing besides backwards compat. Is 3.4 good for fatal or should it be deferred to later?

Let's fatal for 3.4? /cc @xiang90

**Comment by heyitsanthony** [comment]
Marking as 4.0.0 so this can eventually fatal

**Comment by sh8121att** [comment]
I'm seeing 'etcdctl move-leader <some_id>' fail with a shadow message even when now CLI arg is provided:

```
# etcdctl member list
57da4560b50c8f03, started, auxiliary-0, https://172.24.1.10:12380, https://172.24.1.10:12379, false
a6103004597d4f6b, started, auxiliary-1, https://172.24.1.10:22380, https://172.24.1.10:22379, false
b6503c2150dedc1a, started, n0, https://172.24.1.10:2380, https://172.24.1.10:2379, false
# etcdctl move-leader b6503c2150dedc1a
2019-09-06 21:08:16.323276 C | pkg/flags: conflicting environment variable "ETCDCTL_CACERT" is shadowed by corresponding command-line flag (either unset environment variable or disable flag)
# etcdctl version
etcdctl version: 3.4.0
API version: 3.4
```

**Comment by C-PET** [comment]
seeing same issue in etcdctl 3.4.3 when trying to get endpoint status for all members 
```
docker exec etcd etcdctl endpoint status --endpoints=$(docker exec etcd /bin/sh -c "etcdctl member list | cut -d, -f5 | sed -e 's/ //g' | paste -sd ','") --write-out table

 pkg/flags: conflicting environment variable "ETCDCTL_ENDPOINTS" is shadowed by corresponding command-line flag (either unset environment variable or disable flag)
```

the same above command worked in etcdctl 3.3.15

**Comment by mrnonz** [comment]
Anyone has interim solution for `etcdctl move-leader` without waiting upgrade version?

**Comment by mrnonz** [comment]
> Anyone has interim solution for `etcdctl move-leader` without waiting upgrade version?

I founded interim solution is unset all ENV variable first and run by hand
```bash
unset ETCDCTL_CACERT
unset ETCDCTL_CERT
unset ETCDCTL_ENDPOINTS
unset ETCDCTL_KEY

etcdctl --endpoints XXXX --cacert XXX --cert XXX --key XXX move-leader ${transferee_id}
```
