### ISSUE TITLE
Question: Is there a preferred mock library to test clientv3 code?

### ISSUE THREAD

**Issue by drewlandis** [coreos/etcd#8395]
# Question

I'm just barely starting with the etcd and am totally new to clientv3, so I apologize if this question has already been answered. Are there any existing/recommended libraries that I can use to mock clientv3 for testing? After lots of google'ing and searching through issues, goDocs, etc. I couldn't find anything.

If there is not a recommended library, could anyone give me a hint about how they personally test clientv3?

Thanks!

**Comment by gyuho** [comment]
You can check out our integration tests https://github.com/coreos/etcd/blob/master/clientv3/integration/kv_test.go#L35

**Comment by drewlandis** [comment]
Such a fast answer! Checking it now, thanks!

**Comment by drewlandis** [comment]
I actually had seen the `integration` directory prior to asking the question, but wasn't quite sure of how it worked. I should def be able to figure it by looking at the above example.

I might recommend adding a `README` to the integration directory and/or a note on the Go Doc. It was somewhat confusing looking in both those locations and just seeing them blank. Thanks again!
