### ISSUE TITLE
raft: constraint for proposing conf change

### ISSUE THREAD

**Issue by neverchanje** [coreos/etcd#8396]
Hi,

I'm porting etcd/raft to cpp11 and I noticed the following issue.

In https://github.com/coreos/etcd/blob/master/raft/raft.go#L844-L852.

I'm wondering why stepLeader and stepFollower does not just return an error or ignore the message, when MsgProp is carrying more than one entries. It makes the states more complicated.

Both of RawNode and Node propose exactly one entry for a time. I didn't find any place where multiple entries written in a single MsgProp.

**Comment by xiang90** [comment]
@neverchanje 

We can return an error. That is a super old TODO for us... But no one really cares about it on the other hand. etcd/cockroach both works fine without it. We simply handle retry at application side.

You can extend the interface to return error if you wish.

**Comment by neverchanje** [comment]
OK, I understand.
Thanks!
