### ISSUE TITLE
How to disable logging in embedded ETCD?

### ISSUE THREAD

**Issue by akupila** [coreos/etcd#8397]
I want to use the embedded ETCD for integration tests. The tests become quite noisy with the output and I'd like to disable this.

I noticed a `LogPkgLevels` key in `embed.Config` but I'm not sure what i need to enter here for it to have some effect. Looking through I see [capnslog] is used. My best guess so far looks something like this but has no effect ([source]):

```diff
package main

import (
	"log"
	"time"

	"github.com/coreos/etcd/embed"
)

func main() {
	cfg := embed.NewConfig()
	cfg.Dir = "default.etcd"
+	cfg.LogPkgLevels = "github.com/coreos/etcd/embed=E"
	e, err := embed.StartEtcd(cfg)
	if err != nil {
		log.Fatal(err)
	}
	defer e.Close()
	select {
	case <-e.Server.ReadyNotify():
		log.Printf("Server is ready!")
	case <-time.After(60 * time.Second):
		e.Server.Stop() // trigger a shutdown
		log.Printf("Server took too long to start!")
	}
	log.Fatal(<-e.Err())
}
```

Output:
```
$ go run main.go
2017-08-13 15:30:10.952639 I | embed: listening for peers on http://localhost:2380
2017-08-13 15:30:10.954746 I | embed: listening for client requests on localhost:2379
SET LOG LEVEL github.com/coreos/etcd/embed=E
must equal [http://localhost:2380] [http://localhost:2380]
-> default http://localhost:2380
2017-08-13 15:30:10.955688 I | etcdserver: name = default
2017-08-13 15:30:10.955696 I | etcdserver: data dir = default.etcd
2017-08-13 15:30:10.955699 I | etcdserver: member dir = default.etcd/member
2017-08-13 15:30:10.955702 I | etcdserver: heartbeat = 100ms
2017-08-13 15:30:10.955704 I | etcdserver: election = 1000ms
...
```

Expected:
Only show error output

[capnslog]: https://github.com/coreos/pkg/tree/master/capnslog
[source]: https://godoc.org/github.com/coreos/etcd/embed

**Comment by gyuho** [comment]
It will only set log level in `embed` package. Try specifying all the packages you need silence, or try `capnslog.SetGlobalLogLevel(capnslog.CRITICAL)`?

**Comment by akupila** [comment]
Ah, of course. I would need to set the level for each package for this to work.

However, `capnslog.SetGlobalLogLevel(capnslog.CRITICAL)` does exactly what i need and is even easier. Thanks!

**Comment by pecheriere** [comment]
I'll add that you can do 

`cfg.LogPkgLevels = "*=E"`
