### ISSUE TITLE
Watch api hangs sometimes.

### ISSUE THREAD

**Issue by zhuqunzhou** [coreos/etcd#8401]
Version:3.2.0

Sometimes,the `watch` api works well.Like
![normal](https://user-images.githubusercontent.com/10348876/29301063-33a94c1a-81ac-11e7-9f7b-07f961ad68fb.png)
But,After a period of time .The api will hangs up,and will not recovery.And there is no exception.
![exception](https://user-images.githubusercontent.com/10348876/29301088-66ec0a4a-81ac-11e7-8b0f-2c6c6f97bafd.png)

**Comment by hexfusion** [comment]
@zhuqunzhou I believe this this is related to https://github.com/coreos/etcd/issues/8237  and https://github.com/grpc-ecosystem/grpc-gateway/issues/435 . I hope to start work on this soon re: grpc-gateway but can't make any promises on where it will go.

**Comment by hexfusion** [comment]
@zhuqunzhou I am trying to reproduce this, can you please provide more details. How much time approximately does it take for the "hangup" to occur? Also curious what version of etcd are you using.

**Comment by zhuqunzhou** [comment]
@hexfusion ,I found the [issue](https://github.com/coreos/etcd/pull/8238),and update the version to `2.3.5`,The problem seems solved.

I have about 10000 clients need to watch.

**Comment by xiang90** [comment]
@zhuqunzhou Glad it works for you now. Closing the issue.
