### ISSUE TITLE
Consider merging 478ba2c (#8306) into release-3.2

### ISSUE THREAD

**Issue by zhaoyao** [coreos/etcd#8406]
Sometimes we got  etcd error: `rpc error: code = Unknown desc = auth: revision in header is old`

#8306  fixes this issue in master which does not appear in release-3.2.

**Comment by heyitsanthony** [comment]
@zhaoyao is there a simple way to reproduce this? That patch shouldn't have changed any error behavior.

**Comment by zhaoyao** [comment]
Yes, i can always reproduce in my env. Below is steps.

1. starting a etcd server in terminal 1:
`$ etcd`

2. add `root` user and enable auth in terminal 2:
```bash
$ export ETCDCTL_API=3
$ echo root | etcdctl user add root --interactive=false
$ etcdctl auth enable
```

3. run [gist](https://gist.github.com/zhaoyao/1563a218ea0df666786435a7e821e3f6) in terminal 3

here is my output:
```bash
panic: rpc error: code = Unknown desc = auth: revision in header is old

goroutine 39 [running]:
main.test(0xc420098f20, 0xc42019e180, 0x1)
       ***/main.go:46 +0x815
created by main.main
        ***/main.go:67 +0x213
panic: rpc error: code = Unknown desc = auth: revision in header is old

goroutine 45 [running]:
main.test(0xc420098f20, 0xc42019e180, 0x7)
        ***/main.go:46 +0x815
created by main.main
        ***/main.go:67 +0x213
exit status 2
```

I have tested in both master and release-3.2 branch

master works fine
```
etcd Version: 3.2.0+git
Git SHA: fa32a85e6
Go Version: go1.8.3
Go OS/Arch: darwin/amd64
```

but release-3.2 will panic
```
etcd Version: 3.2.5+git
Git SHA: fa0f27878
Go Version: go1.8.3
Go OS/Arch: darwin/amd64

**Comment by zhaoyao** [comment]
The reason why I think #8306 fixes this issue is that pr checks `internalRaftRequest` result.Err, while release-3.2 does not check this.

**Comment by heyitsanthony** [comment]
OK, this can be backported once there's a test case for CI
