### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by jkarneges** [coreos/etcd#8410]
Typo in `dl_build.md`:

> mapped from a file. than For running

**Comment by heyitsanthony** [comment]
@jkarneges open a PR?

**Comment by gyuho** [comment]
@jkarneges Which line are we talking about and what branch? Can't find `... a file. than For ...`.

**Comment by jkarneges** [comment]
https://github.com/coreos/etcd/blob/v3.2.5/Documentation/dl_build.md
Currently live here: https://coreos.com/etcd/docs/latest/dl_build.html

Looks like this was fixed in master. Sorry for the noise!

**Comment by gyuho** [comment]
Just fixed https://github.com/coreos/etcd/blob/release-3.2/Documentation/dl_build.md.

Thanks for point it out!
