### ISSUE TITLE
zero DialTimeout

### ISSUE THREAD

**Issue by stamm** [coreos/etcd#8413]
I have a question about behaviour of DialTimeout.
I don't have a running etcd on port 5000.

If I don't pass DialTimeout or pass zero to this option, it's don't try to connect to etcd. And error will be nil.
```
client, err := etcdClient.New(etcdClient.Config{
	Endpoints: []string{"http://localhost:5000"},
})
```

But if I setup DialTimeout, it will return an error
```
client, err := etcdClient.New(etcdClient.Config{
	Endpoints: []string{"http://localhost:5000"},
	DialTimeout: 1 * time.Second,
})
```

Is it documented behaviour or it may be changed in future?

**Comment by heyitsanthony** [comment]
@stamm this is unlikely to change in the future. A 0 timeout won't wait to establish a connection, which is similar to dialing an ordinary grpc connection.

**Comment by stamm** [comment]
Thanks for answer!
