### ISSUE TITLE
etcdctl v3 has no --discovery-srv flag

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8440]
Like title. So how to use this flag in etcdctl v3?

**Comment by heyitsanthony** [comment]
SRV resolution is not yet supported in etcdctl3.

**Comment by zyf0330** [comment]
Ok, I know.

**Comment by heyitsanthony** [comment]
Reopening to track this feature

**Comment by jiaxuanzhou** [comment]
@heyitsanthony 
i can work on it, i just add modified the support in our production environment

**Comment by heyitsanthony** [comment]
@jiaxuanzhou OK, thanks!
