### ISSUE TITLE
Revise 'Data model' doc

### ISSUE THREAD

**Issue by shenlanse** [coreos/etcd#8444]
[data mode](https://github.com/coreos/etcd/blob/master/Documentation/learning/data_model.md)

1.  " Each modification of a key creates a new generation of the key and increases its version."

It's not precise. Modify will not create a new generation, it only updates its version and appends new revision to current generation.

2.  " Each revision of the store’s state only contains the delta from its previous revision to be efficient"

I think each revision just stores the value we set for this key.
`	kv := mvccpb.KeyValue{
		Key:            key,
		Value:          value,
		CreateRevision: c,
		ModRevision:    rev,
		Version:        ver,
		Lease:          int64(leaseID),
	}`
There is no delta.

3. "The key of key-value pair is a 3-tuple (major, sub, type)."

Hard to understand for a fresh bird. 

Create and update operation for k-v, key will have 2-tuple(main revision, sub revision). All operations within one txn share same main revision but have different sub revision. 

Delete operation for k-v, key will have 3-tuple(main revision, sub revision, t), which  marks it a delete operation.

**Comment by shenlanse** [comment]
kind/documentation

**Comment by heyitsanthony** [comment]
> 1

OK

> 2

It's a delta with respect to the view from the revision. Given ("a", "123", rev=1), ("b", "456", rev=2), the key "a" is still visible from revision 2.

> 3

The key is always 3-tuple, otherwise there's no way to recover whether the operation was a put or a delete. The storage for the type byte can be elided if it's a put, but it's still a 3-tuple using the default type.

Please submit a PR with the changes you have in mind? Thanks!

**Comment by shenlanse** [comment]
@heyitsanthony Thanks.

3.  Do I miss something important? After review the mvcc source code, I still think key is not always 3-tuple, only when it is a delete operation.

PUT operation: key is 2-tuple
mainRevision_subRevision

DELETE operation : key is 3-tuple
mainRevision_subRevision**t**

**Comment by heyitsanthony** [comment]
@shenlanse it's still a 3-tuple; the last part of the tuple is the implicit/default type so it can be elided from storage. `(x,y,t)` is a 3-tuple and so is `(x,y,[])`
