### ISSUE TITLE
etcdctl --endpoints [https://url] fails

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8446]
I do these things from remote client.
Cmd `etcdctl --endpoints [https://url] get a` shows `Error:  grpc: the client connection is closing`
If I use http json api like `https://url:4758/v3alpha/kv/range` to show key `a`, it successes.
So? Thanks for answering.

**Comment by heyitsanthony** [comment]
@zyf0330  what is the etcdctl output with `--debug`? Does `--insecure-skip-tls-verify` fix it? How are the certificates configured? How is etcd configured?

**Comment by zyf0330** [comment]
By the way, I use v3 etcdctl.
With `--debug=true`, output is the same.
With `--insecure-skip-tls-verify=true`, cmd executes a little slower but output is the same.
Certificates is set  by nginx. Nginx does ssl termination, listens https://url:4758 and sends request to etcd .
Etcd listens 127.0.0.1:2379,

**Comment by heyitsanthony** [comment]
Are there any nginx error logs? Can nginx proxy grpc? It doesn't seem like it can yet judging by the nginx/grpc discussion at https://github.com/grpc/grpc.github.io/issues/230

**Comment by zyf0330** [comment]
After searching something, maybe like you said, it has not been supported till now.
Thanks.
