### ISSUE TITLE
Question: what's the meaning of ReadOnlyOptionLeaseWithoutCheckQuorum?

### ISSUE THREAD

**Issue by javaforfun** [coreos/etcd#8450]
raft ReadOnlyLeaseBased ensures linearizability of the read only request **by relying on the leader lease**.
and lease is relying on checkQuorum,  so if ReadOnlyLeaseBased is true,  checkQuorum must be true.

```go
type ReadOnlyOption int
const (
	// ReadOnlySafe guarantees the linearizability of the read only request by
	// communicating with the quorum. It is the default and suggested option.
	ReadOnlySafe ReadOnlyOption = iota
	// ReadOnlyLeaseBased ensures linearizability of the read only request by
	// relying on the leader lease. It can be affected by clock drift.
	// If the clock drift is unbounded, leader might keep the lease longer than it
	// should (clock can move backward/pause without any bound). ReadIndex is not safe
	// in that case.
	ReadOnlyLeaseBased
)
```

for [TestReadOnlyOptionLeaseWithoutCheckQuorum](https://github.com/coreos/etcd/blob/master/raft/raft_test.go#L1901), if network partition happen, and leader is in minority pratition,  
it can't ensures linearizability read.

```go
func TestReadOnlyOptionLeaseWithoutCheckQuorumHasNetworkPartition(t *testing.T) {
        a := newTestRaft(1, []uint64{1, 2, 3}, 10, 1, NewMemoryStorage())
        b := newTestRaft(2, []uint64{1, 2, 3}, 10, 1, NewMemoryStorage())
        c := newTestRaft(3, []uint64{1, 2, 3}, 10, 1, NewMemoryStorage())
        a.readOnly.option = ReadOnlyLeaseBased
        b.readOnly.option = ReadOnlyLeaseBased
        c.readOnly.option = ReadOnlyLeaseBased

        nt := newNetwork(a, b, c)
        nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgHup})

        if a.state != StateLeader {
                t.Fatalf("state = %s, want %s", a.state, StateLeader)
        }
        nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgProp, Entries: []pb.Entry{{}}})

        nt.isolate(1)
        for i := 0; i < a.electionTimeout; i++ {
		a.electionElapsed++ // TickQuiesced
                a.tick()
        }

        ctx := []byte("ctx1")
        nt.send(pb.Message{From: 1, To: 1, Type: pb.MsgReadIndex, Entries: []pb.Entry{{Data: ctx}}})

        if len(a.readStatesrs != 0) {
                t.Errorf("len(readStates) = %d, want 0", len(sm.readStates))
        }
}
```
will fail:  len(readStates) = 1, want 0

**Comment by irfansharif** [comment]
While I don't have the right area context at the moment to answer your original question looking at your original statement _"so if ReadOnlyLeaseBased is true, checkQuorum must be true"_ and then looking at your attached test, I observe that you set `a.readOnly.option = ReadOnlyLeaseBased` but don't explicitly set `a.checkQuorum = true` (the same is true for `{b,c}`). Naively. this may not be what you want and possibly causing the observed behavior.

**Comment by javaforfun** [comment]
@irfansharif  yes, if set `a.readOnly.option = ReadOnlyLeaseBased`, and `a.checkQuorum = true` (also `{b, c}`),  there will be no failure.  So I think `TestReadOnlyOptionLeaseWithoutCheckQuorum` has no meaning.

**Comment by xiang90** [comment]
If checkQ is not enabled, LeaseBasedRead should always return index 0 as readIndex. That is what the test is for (see https://github.com/coreos/etcd/blob/master/raft/raft.go#L873). It seems line 876 is wrong, it still uses the commit index.

@javaforfun can you help to fix it and add a test?
