### ISSUE TITLE
api2 and api3

### ISSUE THREAD

**Issue by xueyihan** [coreos/etcd#8456]
I used API=2 to set a key named qwe and it worked fine when i used API=2 to get the key
But I can't get the key by API=3

here is the command
etcdctl --endpoints=http://etcd:2379 set qwe 1
./etcdctl --endpoints=http://etcd:2379 get qwe
ETCDCTL_API=3 etcdctl --endpoints=http://etcd:2379 get qwe (can't find the key)
Why! Does it store data in seperated space?

**Comment by heyitsanthony** [comment]
v2 and v3 have different semantics; the different namespaces is by design. Use `ETCDCTL_API=3 etcdctl put` to set keys in v3.

**Comment by xueyihan** [comment]
so we can't both use api v2 and api v3? @heyitsanthony

**Comment by heyitsanthony** [comment]
@xueyihan for key-value operations, v2 and v3 are independent backends; they only share raft

**Comment by xueyihan** [comment]
Thanks! @heyitsanthony
