### ISSUE TITLE
Any filters or level control in v3 Get?

### ISSUE THREAD

**Issue by CMGS** [coreos/etcd#8467]
we are trying migrate data from v2 to v3. however we have to face a problem is in v2, we can list nodes in a directory without recursive but in v3 withPrefix will list all keys like force recursive in v2.
so is there any filters or level control in v3 get operation ?

for example, we have a data like this
```
/a/1/a
/a/1/b
/a/1/c
/a/2/a
/a/2/b
/a/3/c
/a/3/b
```
in v2, we can get "/a" then we know under directory a, there are 3 nodes (1,2,3). we will do something with those keys. if we get "/a" without prefix in v3, there is no response. but if we get with prefix all keys will return to client. we have to filter by ourselves.

**Comment by heyitsanthony** [comment]
@CMGS v3 uses a flat keyspace, it doesn't know about directories. The keys can be encoded with depth information to get efficient directory-level listing like:
```
000/a/
001/a/1/
001/a/2/
001/a/3/
002/a/1/a
002/a/1/b
...
```
the directories immediately under /a/ would be fetched with `Get(context.TODO(), "001/a/", WithPrefix())`

**Comment by CMGS** [comment]
@heyitsanthony I know v3 use a flat keyspace so there is no directory any more. but in this case, it will change much logical in real projects and migration process will not smoothly. I think it's a bit ridiculous.

in our real online cluster, we had many directories (100k+). and the business logical depend on those directories' name to do right things. according to official migration guide, offline will be better. thus encode directory's name with depth information will take a long time and make keys more than before. we have to spend more time on check it and modify our logical to fit it. I don't think it's a good idea. however, if there is any pattern methods or filters built in, things will be easy.

**Comment by heyitsanthony** [comment]
@CMGS ok, wait for the v2 emulation proxy; there are no plans to support directories natively in v3. Filtering and pattern matching would be too slow; processing `ls /` would have to churn through the entire data store.

**Comment by CMGS** [comment]
@heyitsanthony sounds great! any roadmap for v2 emulation proxy?

**Comment by heyitsanthony** [comment]
@CMGS experimental in 3.3, stable in 3.4

**Comment by CMGS** [comment]
got it thank you

**Comment by evildecay** [comment]
Can v3.3 be used? If there is an example?
