### ISSUE TITLE
The Watch request will not be closed and retry other etcd instances even if the connected instance is unhealthy.

### ISSUE THREAD

**Issue by abel-von** [coreos/etcd#8470]
Hi, One of our test case is to separate the network between one etcd instance and the leader. 

We have found that, Both in both etcd v2 and v3, the watch request will not receive the new events if the client is connecting to the unhealthy etcd instance (the client port is still listening and the network between the instance and client is ok, it's just the network between the instance and leader is broken). and the client can not close the connection and connect to a new instance because it can not determine is if the connecting instance is unhealthy or it is just there is no updating.

So we have made some change in the server side, anytime when the server new a watch stream, it will run a goroutine to watch the health condition of itself. if it is unhealthy, it will close the watch stream, to notify the client to change the connecting instance. we will check many times to ensure that the node is really unhealthy and do not recover in a long time,  before we close the stream.

@heyitsanthony @xiang90 @gyuho I will submit a PR if you guys think this is a correct way to handle the issue.

**Comment by heyitsanthony** [comment]
@abel-von this is already supported server-side using WithRequireLeader()

**Comment by abel-von** [comment]
OK, that a better and simpler way.

**Comment by abel-von** [comment]
@heyitsanthony please close this issue.
