### ISSUE TITLE
Why 250 thousand small records cost excessive memory

### ISSUE THREAD

**Issue by gwtony** [coreos/etcd#8482]
There are 250,000 records in my etcdv3, each key is 50Byte, value is 100Byte, 
but it cost 1.3GB memory
I got all key and value directly from db file with bolt lib, all data in bolt is only 50MB
What causes this situation, is this a bug ？

**Comment by heyitsanthony** [comment]
What version of etcd? I tried it on master and it's OK:

```
./bin/etcd &
./tools/benchmark/benchmark put --clients=100 --conns=100 --total=250000 --key-size=50 --val-size=100 --key-space-size=99999999999
# resident: 180776KB
killall etcd
./bin/etcd &
# resident 183736KB
$ ls -sh default.etcd/member/snap/db 
55M default.etcd/member/snap/db
```

What is the workload? I can force it to eat a lot of memory by requesting the entire key range:

```
./tools/benchmark/benchmark range --clients=100 --conns=100  `echo  -e -n '\x01'`   `echo -e -n '\xff'` 
```

**Comment by gwtony** [comment]
etcd Version: 3.2.0+git
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.8
Go OS/Arch: linux/amd64

Workload is very light, only 1% cpu
Some infomation in top:
VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
12.5g 1.3g 979m S  1.0  8.2  36:25.38 etcd

>ls -sh db
957M db

I open db file, print kv with this code

    db.View(func(tx *bolt.Tx) error {
        c := tx.Bucket([]byte("key")).Cursor()

        for k, v := c.First(); k != nil; k, v = c.Next() {
            fmt.Printf("%s, %s\n", string(k), string(v))
        }

        return nil
    })

and the output is:
50M kv

I used to delete more than 500 thousand records and enabled auto compcation, is there any relation to this situation

**Comment by heyitsanthony** [comment]
The db needs to be defragmented to reclaim file space. See https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#defragmentation

**Comment by gwtony** [comment]
Thanks, it worked, db size shrinked to 128MB after defrag
