### ISSUE TITLE
lease: monotonic time has been supportted in go1.9

### ISSUE THREAD

**Issue by lorneli** [coreos/etcd#8493]
Lease package needs monotonic time to measure whether a lease is expired. Previously, pkg/monotime implements monotonic time,  using `go:linkname` to touch golang's `runtime.nanotime`.

Monotonic clock has been supportted in go1.9 ([release note](https://golang.org/doc/go1.9#monotonic-time)). As described in [time package's doc](https://golang.org/pkg/time/#hdr-Monotonic_Clocks), monotonic clock is used for time-measuring operations.

Is there any plan to replace pkg/monotime with go1.9 time package? By the way, Removing pkg/monotime has obvious shortcoming, requiring go version >= 1.9 to support this feature.

**Comment by heyitsanthony** [comment]
duplicates #6174

**Comment by gyuho** [comment]
We still run CIs on 1.8.3. Once Semaphore supports Go 1.9, we will switch. Thanks.

**Comment by lorneli** [comment]
@gyuho My pleasure. Haven't seen your comment and created a pr #8507 few minutes ago.
