### ISSUE TITLE
etcdserver: use PreVote so majority partition's leader isn't forced to step down

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8499]
If a cluster is partitioned then connectivity is fixed, the minority partition can trigger a new election that will cause the majority partition's leader to step down and disrupt availability. The fix, as described in 9.6 of the raft disseration, is PreVote.

**Comment by shenlanse** [comment]
I have found the implementation in etcd. Do I miss important point?

**Comment by irfansharif** [comment]
@shenlanse: it isn't as stable/battle tested as yet, see https://github.com/coreos/etcd/issues/8501, https://github.com/coreos/etcd/issues/8498 and the issues linked therein. We (cockroachdb/cockroach) have run into issues enabling it as it stands today.

**Comment by shenlanse** [comment]
@irfansharif Ohh，thanks, I will see it

**Comment by gyuho** [comment]
Will be enabled by default in v3.5. Has been testing pre-vote in functional testing for several months, and seems stable.
