### ISSUE TITLE
e2e SRV record tests

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8502]
Not much testing around SRV records because DNS is difficult to run in ordinary tests. Would like to test/collect coverage for both TLS and non-TLS SRV discovery behavior using:

* etcdctl client
* etcdctl clientv3
* etcd gateway
* etcd peer bootstrapping

There's some dockerized DNS testing in e2e/docker, which is probably where to start for supporting this.

**Comment by gyuho** [comment]
All basic tests are done via https://github.com/coreos/etcd/pull/8954.

We can integrate them in CI once we cut CI time to 10-min (https://github.com/coreos/etcd/issues/8862).
