### ISSUE TITLE
support <1hr automatic compaction retention

### ISSUE THREAD

**Issue by heyitsanthony** [coreos/etcd#8503]
Systems (e.g., k8s) that expect a lot of writes must implement their own compaction logic to periodically compact etcd at a rate of less than an hour. That is, some agent outside of etcd must be granted ownership of compaction which complicates system design. Since the intent is only etcd should compact more frequently, it would be much simpler to support automatic retention with finer granularity.

Currently the flag for configuring the compaction interval is an integer:
```
         --auto-compaction-retention '0'
                auto compaction retention length. 0 means disable auto compaction.
```

It could instead be parsed from a string:
```
        --auto-compaction-mode 'periodic'
                'periodic' means hours if an integer or a duration string otherwise, 'revision' means revision numbers to retain by auto compaction
```

Then, etcd can get 5 minute retention via `time.ParseDuration`:

`--auto-compaction-retention 5m`

Related #8458

**Comment by fanminshi** [comment]
@heyitsanthony should we have a minimum `retention`?

**Comment by heyitsanthony** [comment]
@fanminshi no, if the user gives a very short retention time, that's on them

**Comment by fanminshi** [comment]
@heyitsanthony got it.
