### ISSUE TITLE
etcd should not produce grpc.ErrClientConnTimeout errors

### ISSUE THREAD

**Issue by dfawley** [coreos/etcd#8504]
https://github.com/grpc/grpc-go/blob/4bbe223b12805ab25acbb9d2cadfab2ec9d04bb6/clientconn.go#L46-L49

gRPC has not used this error in a year.  I would like to remove it, since it is dead within our project. 
 However, it seems etcd is generating and returning this error.  Please find a more appropriate error to return; we will be removing it soon.  (Note: the original PR that deprecated it said it would be removed in 2017Q1.)  Thanks!

**Comment by gyuho** [comment]
@dfawley Thanks for heads-up! We've just deprecated `grpc.ErrClientConnTimeout` in https://github.com/coreos/etcd/pull/8505.

**Comment by dfawley** [comment]
Thanks for the super quick turnaround!  :+1:
