### ISSUE TITLE
[rafthttp] In pipeline handler and snapshot handler, add remote when it doesn't exist

### ISSUE THREAD

**Issue by shenlanse** [coreos/etcd#8506]
# Bug reporting

In rafthttp package, pipeline handler and snapshot handler will add remote if transport doesn't have corresponding peer or remote. 

Corresponding PR: https://github.com/coreos/etcd/pull/4431

https://github.com/coreos/etcd/blob/master/rafthttp/http.go#L94    
https://github.com/coreos/etcd/blob/master/rafthttp/http.go#L179

```
func (h *pipelineHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		w.Header().Set("Allow", "POST")
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
		return
	}

	w.Header().Set("X-Etcd-Cluster-ID", h.cid.String())

	if err := checkClusterCompatibilityFromHeader(r.Header, h.cid); err != nil {
		http.Error(w, err.Error(), http.StatusPreconditionFailed)
		return
	}

	if from, err := types.IDFromString(r.Header.Get("X-Server-From")); err != nil {
		if urls := r.Header.Get("X-PeerURLs"); urls != "" {
			h.tr.AddRemote(from, strings.Split(urls, ","))
		}
	}
```

I wonder why the if conditon is err!=nil, instead of err==nil.

**Comment by shenlanse** [comment]
@heyitsanthony

**Comment by heyitsanthony** [comment]
@shenlanse it's fallback behavior; if there is no X-Server-From given, it will use X-PeerURLs

**Comment by heyitsanthony** [comment]
Closing. Feel free to reopen if there's some reproducible bug concerning this code, thanks!
