### ISSUE TITLE
etcd is failing build on ppc64le

### ISSUE THREAD

**Issue by mkumatag** [coreos/etcd#8524]
Build is failing consistently on ppc64le architecture and below is the error: 

```
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/client.go:327: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
	*authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
		have GetRequestMetadata("context".Context, ...string) (map[string]string, error)
		want GetRequestMetadata("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, ...string) (map[string]string, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/client.go:380: cannot use client.balancer (type *simpleBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
	*simpleBalancer does not implement grpc.Balancer (wrong type for Get method)
		have Get("context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
		want Get("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:92: cannot use *retryKVClient literal (type *retryKVClient) as type etcdserverpb.KVClient in return argument:
	*retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:93: cannot use retryBasic (type *retryKVClient) as type etcdserverpb.KVClient in field value:
	*retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:158: cannot use retry (type *retryLeaseClient) as type etcdserverpb.LeaseClient in field value:
	*retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:158: cannot use *retryLeaseClient literal (type *retryLeaseClient) as type etcdserverpb.LeaseClient in return argument:
	*retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:185: cannot use retryClusterClient literal (type *retryClusterClient) as type etcdserverpb.ClusterClient in return argument:
	*retryClusterClient does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)
		have MemberAdd("context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
		want MemberAdd("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:219: cannot use retryAuthClient literal (type *retryAuthClient) as type etcdserverpb.AuthClient in return argument:
	*retryAuthClient does not implement etcdserverpb.AuthClient (wrong type for AuthDisable method)
		have AuthDisable("context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
		want AuthDisable("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/leasepb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/leasehttp
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/auth_client_adapter.go:28: cannot use as2ac literal (type *as2ac) as type etcdserverpb.AuthClient in return argument:
	*as2ac does not implement etcdserverpb.AuthClient (wrong type for AuthDisable method)
		have AuthDisable("context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
		want AuthDisable("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/chan_stream.go:151: cannot use srv (type *chanStream) as type grpc.Stream in field value:
	*chanStream does not implement grpc.Stream (wrong type for Context method)
		have Context() "context".Context
		want Context() "github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/cluster_client_adapter.go:28: cannot use cls2clc literal (type *cls2clc) as type etcdserverpb.ClusterClient in return argument:
	*cls2clc does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)
		have MemberAdd("context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
		want MemberAdd("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/election_client_adapter.go:28: cannot use es2ec literal (type *es2ec) as type v3electionpb.ElectionClient in return argument:
	*es2ec does not implement v3electionpb.ElectionClient (wrong type for Campaign method)
		have Campaign("context".Context, *v3electionpb.CampaignRequest, ...grpc.CallOption) (*v3electionpb.CampaignResponse, error)
		want Campaign("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *v3electionpb.CampaignRequest, ...grpc.CallOption) (*v3electionpb.CampaignResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/election_client_adapter.go:51: cannot use es2ecClientStream literal (type *es2ecClientStream) as type v3electionpb.Election_ObserveClient in return argument:
	*es2ecClientStream does not implement v3electionpb.Election_ObserveClient (wrong type for Context method)
		have Context() "context".Context
		want Context() "github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/kv_client_adapter.go:28: cannot use kvs2kvc literal (type *kvs2kvc) as type etcdserverpb.KVClient in return argument:
	*kvs2kvc does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/lease_client_adapter.go:30: cannot use ls2lc literal (type *ls2lc) as type etcdserverpb.LeaseClient in return argument:
	*ls2lc does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/lease_client_adapter.go:45: cannot use ls2lcClientStream literal (type *ls2lcClientStream) as type etcdserverpb.Lease_LeaseKeepAliveClient in return argument:
	*ls2lcClientStream does not implement etcdserverpb.Lease_LeaseKeepAliveClient (wrong type for Context method)
		have Context() "context".Context
		want Context() "github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/lock_client_adapter.go:28: cannot use ls2lsc literal (type *ls2lsc) as type v3lockpb.LockClient in return argument:
	*ls2lsc does not implement v3lockpb.LockClient (wrong type for Lock method)
		have Lock("context".Context, *v3lockpb.LockRequest, ...grpc.CallOption) (*v3lockpb.LockResponse, error)
		want Lock("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *v3lockpb.LockRequest, ...grpc.CallOption) (*v3lockpb.LockResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/maintenance_client_adapter.go:28: cannot use mts2mtc literal (type *mts2mtc) as type etcdserverpb.MaintenanceClient in return argument:
	*mts2mtc does not implement etcdserverpb.MaintenanceClient (wrong type for Alarm method)
		have Alarm("context".Context, *etcdserverpb.AlarmRequest, ...grpc.CallOption) (*etcdserverpb.AlarmResponse, error)
		want Alarm("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.AlarmRequest, ...grpc.CallOption) (*etcdserverpb.AlarmResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/maintenance_client_adapter.go:28: too many errors
```

look @ https://jenkins-etcd-public.prod.coreos.systems/job/etcd-ci-ppc64/ for more information.

**Comment by gyuho** [comment]
We've migrated to Go 1.9.
Could you upgrade the Go version to 1.9?

**Comment by mkumatag** [comment]
okay, will migrate the go version

**Comment by mkumatag** [comment]
upgraded to go 1.9 in the ppc64le etcd slave, can someone please reinvoke the jenkins job to confirm things are okay!

**Comment by mkumatag** [comment]
Now `etcd-ci-ppc64` job is green, hence closing this issue. -Thanks

**Comment by numkem** [comment]
For people googling this issue, it's not only related to ppc64. I believe that if you aren't running 1.9 you won't be able to use the current master branch.

**Comment by sascha-andres** [comment]
My go version:
go version go1.9 linux/amd64
Same error

**Comment by mkumatag** [comment]
@sascha-andres make sure you clean old golang1.8 code completely. This happens sometime if you have both 1.9 and 1.8 in the path.

**Comment by sascha-andres** [comment]
Got it working a second ago. Just mad an go get -u clientv3. Though my previous get was just three days ago

**Comment by sascha-andres** [comment]
Thanks for the comment

**Comment by kunth** [comment]
I bumped into this problem in my Mac, and solved it by upgrading golang version from 1.8 to 1.10

**Comment by duchuanLX** [comment]
golang 1.8.7 on mips complie error:

docker run --interactive -v /root/go/src/Kubernetes/kubernetes-1.13.5/cluster/images/etcd/../../../:/go/src/k8s.io/kubernetes -v /tmp/tmp.NEN9gVrTeD:/build -e GOARCH=amd64 golang:1.8.7 \
	/bin/bash -c "CGO_ENABLED=0 go build -o /build/migrate k8s.io/kubernetes/cluster/images/etcd/migrate"
# k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3
src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/client.go:346: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
	*authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
		have GetRequestMetadata("context".Context, ...string) (map[string]string, error)
		want GetRequestMetadata("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, ...string) (map[string]string, error)
src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/client.go:421: cannot use client.balancer (type *healthBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
	*healthBalancer does not implement grpc.Balancer (wrong type for Get method)
		have Get("context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
		want Get("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/retry.go:145: cannot use retryKVClient literal (type *retryKVClient) as type etcdserverpb.KVClient in return argument:
	*retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/retry.go:198: cannot use retryLeaseClient literal (type *retryLeaseClient) as type etcdserverpb.LeaseClient in return argument:
	*retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/retry.go:252: cannot use retryClusterClient literal (type *retryClusterClient) as type etcdserverpb.ClusterClient in return argument:
	*retryClusterClient does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)

**Comment by mkumatag** [comment]
> golang 1.8.7 on mips complie error:
> 
> docker run --interactive -v /root/go/src/Kubernetes/kubernetes-1.13.5/cluster/images/etcd/../../../:/go/src/k8s.io/kubernetes -v /tmp/tmp.NEN9gVrTeD:/build -e GOARCH=amd64 golang:1.8.7
> /bin/bash -c "CGO_ENABLED=0 go build -o /build/migrate k8s.io/kubernetes/cluster/images/etcd/migrate"
> 
> # k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3
> src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/client.go:346: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
> *authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
> have GetRequestMetadata("context".Context, ...string) (map[string]string, error)
> want GetRequestMetadata("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, ...string) (map[string]string, error)
> src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/client.go:421: cannot use client.balancer (type *healthBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
> *healthBalancer does not implement grpc.Balancer (wrong type for Get method)
> have Get("context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
> want Get("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
> src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/retry.go:145: cannot use retryKVClient literal (type *retryKVClient) as type etcdserverpb.KVClient in return argument:
> *retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
> have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
> want Compact("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
> src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/retry.go:198: cannot use retryLeaseClient literal (type *retryLeaseClient) as type etcdserverpb.LeaseClient in return argument:
> *retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
> have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
> want LeaseGrant("k8s.io/kubernetes/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
> src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/retry.go:252: cannot use retryClusterClient literal (type *retryClusterClient) as type etcdserverpb.ClusterClient in return argument:
> *retryClusterClient does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)

I think you are also hitting the same problem what mentioned above, can you please clean up your golang installation and try with fresh golang installation.?
