### ISSUE TITLE
lease: question about optimizing finding expired leases with heap

### ISSUE THREAD

**Issue by lorneli** [coreos/etcd#8538]
Here is the comment about optimizing finding expired leases with heap.
https://github.com/coreos/etcd/blob/master/lease/lessor.go#L121-L126

> 	// TODO: probably this should be a heap with a secondary
	// id index.
	// Now it is O(N) to loop over the leases to find expired ones.
	// We want to make Grant, Revoke, and findExpiredLeases all O(logN) and
	// Renew O(1).
	// findExpiredLeases and Renew should be the most frequent operations.

After adding a heap, `findExpiredLeases` is to delete min element in heap, taking O(logN). But search a lease in heap takes O(N) time complexity, which means `Renew` is O(N) using heap.

In my view, making `Renew` O(1) is to use built-in type `map`, which implements a hash table. So there should be two structures holding the leases: hash table and heap.  I don't know if I'm thinking it the right way?

Thanks in advance.

**Comment by shenlanse** [comment]
> After adding a heap, findExpiredLeases is to delete min element in heap, taking O(logN). 

Delete min element from heap,taking O(logN). But we might need to delete X elements from heap.

> In my view, making Renew O(1) is to use built-in type map, which implements a hash table. So there should be two structures holding the leases: hash table and heap.

when renew from map, you need to adjust heap, which takes O(logN)

**Comment by heyitsanthony** [comment]
@lorneli it would use a map for fast renew and a min-heap for fast expiry scanning. Unless there are some performance measurements that would justify adding a heap, it's probably best to leave the code as-is instead of introducing unnecessary complexity.

**Comment by lorneli** [comment]
@shenlanse Thanks. `findExpiredLeases` takes O(NlogN). `Renew` needs to find lease first, see @heyitsanthony's comment.

**Comment by lorneli** [comment]
@heyitsanthony Thank you very much.
