### ISSUE TITLE
etcd v3.2.5: missing grpc_server_* metrics when scraping with Prometheus

### ISSUE THREAD

**Issue by dannyk81** [coreos/etcd#8541]
We are scraping etcd (v3.2.5) instances with Prometheus and not getting any of the `grpc_*` metrics, all other `etcd_*` are collected correctly.

Am I missing some configuration? my understanding is that these should be included by default and only the histogram metrics are optional (enabled with `–metrics extensive`)

Any suggestions? thoughts?

**Comment by gyuho** [comment]
`grpc_*` won't show up until initial requests come in, as far as I know. Can you try sending test requests to your cluster and try again?

**Comment by dannyk81** [comment]
This particular etcd cluster is part of K8s control plane, the clients in this case are ectd proxies deployed on the K8s worker nodes (these are actually running etcd v2).

I tried executing a bunch of etcdctl command (not sure if it's enough)

But not seeing any of the gprc metrics.

**Comment by gyuho** [comment]
> I tried executing a bunch of etcdctl command (not sure if it's enough)

What commands are you sending to etcd cluster? If v2, it won't send any gRPC requests.

**Comment by heyitsanthony** [comment]
Works fine:
```sh
$ bin/etcd &
$ curl localhost:2379/metrics 2>&1 | grep -v "#" | grep grpc 
etcd_grpc_proxy_cache_hits_total 0
etcd_grpc_proxy_cache_keys_total 0
etcd_grpc_proxy_cache_misses_total 0
etcd_grpc_proxy_events_coalescing_total 0
etcd_grpc_proxy_watchers_coalescing_total 0
etcd_network_client_grpc_received_bytes_total 0
etcd_network_client_grpc_sent_bytes_total 0
$ ETCDCTL_API=3 ./bin/etcdctl put abc def
OK
$ curl localhost:2379/metrics 2>&1 | grep -v "#" | grep grpc
etcd_grpc_proxy_cache_hits_total 0
etcd_grpc_proxy_cache_keys_total 0
etcd_grpc_proxy_cache_misses_total 0
etcd_grpc_proxy_events_coalescing_total 0
etcd_grpc_proxy_watchers_coalescing_total 0
etcd_network_client_grpc_received_bytes_total 10
etcd_network_client_grpc_sent_bytes_total 29
grpc_server_handled_total{grpc_code="OK",grpc_method="Put",grpc_service="etcdserverpb.KV",grpc_type="unary"} 1
grpc_server_msg_received_total{grpc_method="Put",grpc_service="etcdserverpb.KV",grpc_type="unary"} 1
grpc_server_msg_sent_total{grpc_method="Put",grpc_service="etcdserverpb.KV",grpc_type="unary"} 1
grpc_server_started_total{grpc_method="Put",grpc_service="etcdserverpb.KV",grpc_type="unary"} 1
```

**Comment by dannyk81** [comment]
Thank you both, indeed all clients (including etcdctl) that we have are v2 and as described these won't generate grpc requests.
