### ISSUE TITLE
exec ./build error

### ISSUE THREAD

**Issue by yinhongbo** [coreos/etcd#8551]
./build
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/netutil.go:45: undefined: net.DefaultResolver in net.DefaultResolver.LookupPort
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/netutil/netutil.go:55: undefined: net.DefaultResolver in net.DefaultResolver.LookupIPAddr
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener.go:182: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener.go:182: undefined: tls.CertificateRequestInfo
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/transport/listener_tls.go:233: undefined: net.DefaultResolver in net.DefaultResolver.LookupAddr
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/debugutil
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/debugutil/pprof.go:28: undefined: runtime.SetMutexProfileFraction
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/pkg/debugutil/pprof.go:30: undefined: runtime.SetMutexProfileFraction
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/client.go:328: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
	*authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
		have GetRequestMetadata("context".Context, ...string) (map[string]string, error)
		want GetRequestMetadata("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, ...string) (map[string]string, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/client.go:381: cannot use client.balancer (type *simpleBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
	*simpleBalancer does not implement grpc.Balancer (wrong type for Get method)
		have Get("context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
		want Get("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:98: cannot use retryBasic (type *retryKVClient) as type etcdserverpb.KVClient in field value:
	*retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:163: cannot use retry (type *retryLeaseClient) as type etcdserverpb.LeaseClient in field value:
	*retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:190: cannot use retryClusterClient literal (type *retryClusterClient) as type etcdserverpb.ClusterClient in return argument:
	*retryClusterClient does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)
		have MemberAdd("context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
		want MemberAdd("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/clientv3/retry.go:224: cannot use retryAuthClient literal (type *retryAuthClient) as type etcdserverpb.AuthClient in return argument:
	*retryAuthClient does not implement etcdserverpb.AuthClient (wrong type for AuthDisable method)
		have AuthDisable("context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
		want AuthDisable("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/lease/lessor.go:630: undefined: time.Until
# github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/auth_client_adapter.go:28: cannot use as2ac literal (type *as2ac) as type etcdserverpb.AuthClient in return argument:
	*as2ac does not implement etcdserverpb.AuthClient (wrong type for AuthDisable method)
		have AuthDisable("context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
		want AuthDisable("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/chan_stream.go:151: cannot use srv (type *chanStream) as type grpc.Stream in field value:
	*chanStream does not implement grpc.Stream (wrong type for Context method)
		have Context() "context".Context
		want Context() "github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/cluster_client_adapter.go:28: cannot use cls2clc literal (type *cls2clc) as type etcdserverpb.ClusterClient in return argument:
	*cls2clc does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)
		have MemberAdd("context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
		want MemberAdd("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/election_client_adapter.go:28: cannot use es2ec literal (type *es2ec) as type v3electionpb.ElectionClient in return argument:
	*es2ec does not implement v3electionpb.ElectionClient (wrong type for Campaign method)
		have Campaign("context".Context, *v3electionpb.CampaignRequest, ...grpc.CallOption) (*v3electionpb.CampaignResponse, error)
		want Campaign("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *v3electionpb.CampaignRequest, ...grpc.CallOption) (*v3electionpb.CampaignResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/election_client_adapter.go:51: cannot use es2ecClientStream literal (type *es2ecClientStream) as type v3electionpb.Election_ObserveClient in return argument:
	*es2ecClientStream does not implement v3electionpb.Election_ObserveClient (wrong type for Context method)
		have Context() "context".Context
		want Context() "github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/kv_client_adapter.go:28: cannot use kvs2kvc literal (type *kvs2kvc) as type etcdserverpb.KVClient in return argument:
	*kvs2kvc does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/lease_client_adapter.go:30: cannot use ls2lc literal (type *ls2lc) as type etcdserverpb.LeaseClient in return argument:
	*ls2lc does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/lease_client_adapter.go:45: cannot use ls2lcClientStream literal (type *ls2lcClientStream) as type etcdserverpb.Lease_LeaseKeepAliveClient in return argument:
	*ls2lcClientStream does not implement etcdserverpb.Lease_LeaseKeepAliveClient (wrong type for Context method)
		have Context() "context".Context
		want Context() "github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/lock_client_adapter.go:28: cannot use ls2lsc literal (type *ls2lsc) as type v3lockpb.LockClient in return argument:
	*ls2lsc does not implement v3lockpb.LockClient (wrong type for Lock method)
		have Lock("context".Context, *v3lockpb.LockRequest, ...grpc.CallOption) (*v3lockpb.LockResponse, error)
		want Lock("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *v3lockpb.LockRequest, ...grpc.CallOption) (*v3lockpb.LockResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/maintenance_client_adapter.go:28: cannot use mts2mtc literal (type *mts2mtc) as type etcdserverpb.MaintenanceClient in return argument:
	*mts2mtc does not implement etcdserverpb.MaintenanceClient (wrong type for Alarm method)
		have Alarm("context".Context, *etcdserverpb.AlarmRequest, ...grpc.CallOption) (*etcdserverpb.AlarmResponse, error)
		want Alarm("github.com/coreos/etcd/cmd/vendor/golang.org/x/net/context".Context, *etcdserverpb.AlarmRequest, ...grpc.CallOption) (*etcdserverpb.AlarmResponse, error)
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/proxy/grpcproxy/adapter/maintenance_client_adapter.go:28: too many errors

**Comment by heyitsanthony** [comment]
@yinhongbo what version of the go compiler? etcd 3.2.x needs go 1.8+ to build, master needs go 1.9+

**Comment by yinhongbo** [comment]
@heyitsanthony thanks , i am use 1.7.4 now. i try it use 1.9 later. thanks
