### ISSUE TITLE
etcdctl endpoints format error

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8557]
In newest commit, when I run `etcdctl endpoint health --endpoints=[http://a1.com,http://a2.com,http://a3.com]`, I got 
```
https://a2.com is healthy: successfully committed proposal: took = 122.394163ms
https://a3.com] is unhealthy: failed to connect: context deadline exceeded
[https://a1.com is unhealthy: failed to connect: context deadline exceeded
Error: unhealthy cluster
```
As you can see, it seems that `-endpoints` list doesn't be split properly. And if I change it into `http://a1.com,http://a2.com,http://a3.com` which remove `[ ]`, it works normally.

**Comment by heyitsanthony** [comment]
`--endpoints` has always been comma delimited. Square brackets are malformed input, so don't expect it to work. Closing.

**Comment by zyf0330** [comment]
It just works at least at version v3.2.7. Ok, it's all right.
