### ISSUE TITLE
suggest update version info of etcd from build

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8558]
When build etcd, its version info always is 
```
etcdctl version: 3.2.0+git
API version: 3.2
```
and from http path `/version` always get 
```
{"etcdserver":"3.2.0+git","etcdcluster":"3.2.0"}
```
Is this info is up to date with release version?

**Comment by heyitsanthony** [comment]
This is correct since that's master and not an official release. The current master is branched starting from the 3.2.0 release, making the version 3.2.0+git. Master builds are tracked by the SHA which is printed when starting etcd, the version strings are bumped only when cutting a release.

**Comment by zyf0330** [comment]
So etcds built from master and release version will work together?
