### ISSUE TITLE
etcdv3 client.go with multi endpoints stops working after first endpoint stop work

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8559]
## Background
I use confd and find a problem. It use etcdv3 client.go to watch changes and I give three endpoints to it.
## there problems
* After client.go starts running, if I stop one etcd related to **first** endpoint, client.go won't watch new change of key, even though that etcd restores.
* If I stop one etcd before client.go run, it works even though I start that stopped etcd and stop another etcd again.
* If I stop two etcd and restart them, client.go doesn't work too.

Confd use 2016-September commit of clientv3-client.go,so did these problems actually exist and be fixed?

**Comment by heyitsanthony** [comment]
Please try with a more recent client, there have been a lot of bug fixes over the past year.

**Comment by zyf0330** [comment]
Ok, thanks.
