### ISSUE TITLE
etcd Version: 3.1.9 get high disk io in the case of small client request.

### ISSUE THREAD

**Issue by xdk25d** [coreos/etcd#8565]
Description: In VM, my etcd(each of the etcd cluster) get high disk io about 2+MB/s when the flow from client is about 20 KB/s

Following is some system status:

1. iotop show the io disk info:

 PID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
 2612 be/3 root        0.00 B/s   11.05 K/s  0.00 % 38.91 % [jbd2/vdb2-8]
  691 be/3 root        0.00 B/s    7.37 K/s  0.00 %  4.31 % [jbd2/vdb1-8]
13265 be/4 paas        0.00 B/s    2.16 M/s  0.00 %  0.66 % etcd --name infra1 --initial-advertise-peer-urls http://192.168.0.6:15017 --listen-peer-urls http://192.168.0.6:15017 --listen-client-urls https://192.168.0.6:35013,https://127.0.0.1:15013 --advertise-client-urls https://192.168.0.6:15013 --initial-cluster-token etcd-cluster-1 --initial-cluster infra0=http://192.168.0.5:35017,infra1=http://192.168.0.6:15017,infra2=http://192.168.0.7:15017 --initial-cluster-state new --heartbeat-interval=500 --election-timeout=5000 --data-dir=/var/paas/etcd/data --ca-file /srv/kubernetes/ca.crt --cert-file /srv/kubernetes/tls.crt --key-file /srv/kubernetes/tls.key

2. iftop grep the flow from 15013,15017 which when etcd used:
cmd:iftop -Nn -B -i bond0 -f "port 15013 or port 15017"
TX:             cumm:   719KB   peak:   15.4KB               rates:   9.24KB  8.93KB  8.35KB
RX:                     984KB           17.6KB                        10.6KB  11.7KB  11.5KB
TOTAL:                 1.66MB           32.7KB                        19.8KB  20.6KB  19.8KB

3. os info:
CentOS 7, 3.10.0-327.36.58.4.x86_64
ftab:
/dev/vda1    /boot    ext4    defaults 1 2
sysfs                /sys                 sysfs      noauto                0 0
proc                 /proc                proc       defaults              0 0
usbfs                /proc/bus/usb        usbfs      noauto                0 0
devpts               /dev/pts             devpts     mode=0620,gid=5       0 0
/dev/vdb1       /var/lib/docker ext4    defaults 1 2

4.file which etcd write or read:
ll /proc/13265/fd|grep -v socket
lr-x------ 1 paas paas 64 Sep 11 16:04 0 -> /dev/null
l-wx------ 1 paas paas 64 Sep 11 16:04 1 -> /var/log/canal_etcd.log
lr-x------ 1 paas paas 64 Sep 11 16:04 10 -> /var/paas/etcd/data/member/wal
l-wx------ 1 paas paas 64 Sep 11 16:04 2 -> /var/log/canal_etcd.log
lr-x------ 1 paas paas 64 Sep 11 16:04 36 -> /dev/urandom
lrwx------ 1 paas paas 64 Sep 11 16:04 4 -> anon_inode:[eventpoll]
l-wx------ 1 paas paas 64 Sep 11 16:04 58 -> /var/paas/etcd/data/member/wal/000000000000002c-000000000037d402.wal
l-wx------ 1 paas paas 64 Sep 11 16:04 60 -> /var/paas/etcd/data/member/wal/0.tmp
lrwx------ 1 paas paas 64 Sep 11 16:04 7 -> /var/paas/etcd/data/member/snap/db

5.strace track has a huge write(about 1.2MB) in fd 7:
[000000000045ea23] futex(0x1338df0, FUTEX_WAIT, 0, NULL) = 0
[000000000045ea23] futex(0x1338df0, FUTEX_WAIT, 0, NULL) = 0
[000000000045ea23] futex(0x1338df0, FUTEX_WAIT, 0, NULL) = 0
[0000000000761a3a] pwrite(7, "\370\1\0\0\0\0\0\0\2\0\2\0\0\0\0\0\0\0\0\0 \0\0\0\21\0\0\0\314\5\0\0"..., 4096, 2064384) = 4096
[0000000000761a3a] pwrite(7, "\7\2\0\0\0\0\0\0\2\0\3\0\0\0\0\0\0\0\0\0000\0\0\0\21\0\0\0\265\0\0\0"..., 4096, 2125824) = 4096
[0000000000761a3a] pwrite(7, "\10\2\0\0\0\0\0\0\1\0N\0\0\0\0\0\340\4\0\0\21\0\0\0|\1\0\0\0\0\0\0"..., 4096, 2129920) = 4096
[0000000000761a3a] pwrite(7, "\n\2\0\0\0\0\0\0\1\0\6\0\0\0\0\0`\0\0\0\21\0\0\0\20\2\0\0\0\0\0\0"..., 4096, 2138112) = 4096
[0000000000761a3a] pwrite(7, "\30\2\0\0\0\0\0\0\2\0\n\0\0\0\0\0\1\0\0\0\240\0\0\0\5\0\0\0 \0\0\0"..., 4096, 2195456) = 4096
[0000000000761a3a] pwrite(7, "e\2\0\0\0\0\0\0\20\0\377\377%\1\0\0\261J\2\0\0\0\0\0\371\1\0\0\0\0\0\0"..., 1204224, 2510848) = 1204224
[00000000007619c4] fdatasync(7)         = 0
[000000000045ea23] futex(0x1338158, FUTEX_WAKE, 1) = 1
[000000000045ea23] futex(0x1338090, FUTEX_WAKE, 1) = 1
[0000000000761a3a] pwrite(7, "\1\0\0\0\0\0\0\0\4\0\0\0\0\0\0\0\355\332\f\355\2\0\0\0\0\20\0\0\0\0\0\0"..., 4096, 4096) = 4096
[00000000007619c4] fdatasync(7)         = 0
[000000000045ea23] futex(0x1338158, FUTEX_WAKE, 1) = 1
[000000000045ea23] futex(0xc420037910, FUTEX_WAKE, 1) = 1
[000000000045ea23] futex(0x1338df0, FUTEX_WAIT, 0, NULL) = 0

6.PS:
in my another test system, I put "helloXX"(XX is a random number) in key "/a/b/c" into etcd cluster from three node, etcd2 io performace better then etcd3
etcd2 is 2.1.3, etcd3 is 3.1.9.

**Comment by heyitsanthony** [comment]
@xdk25d this is possibly from a boltdb issue that will be fixed in 3.3. Defragmenting the members might help, see https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#defragmentation

**Comment by xiang90** [comment]
@xdk25d Please give master a try, and let us know if it helps.

**Comment by xdk25d** [comment]
@heyitsanthony @xiang90 After defragmenting the members, the disk io get much lower now.
Thanks .

**Comment by xiang90** [comment]
@xdk25d also give master a try if you are doing tests. master should not require a defrag. let us know if it works.

**Comment by xdk25d** [comment]
@xiang90 I give master of etcd a try,  the result as below:
https://192.168.0.5:15013, a9b9071a4f665c35, 3.1.9, 1.6 MB, true, 223, 4503827
https://192.168.0.6:15013, 634e3d48bd4a7f4b, 3.1.9, 656 MB, false, 223, 4503827
https://192.168.0.7:15013, da4358f49d5bd5f2, 3.1.9, 658 MB, false, 223, 4503827

**Comment by xiang90** [comment]
it is strange that a9b9071a4f665c35 has 1.6MB db size. did you do a defrag only on that node?

**Comment by xdk25d** [comment]
@xiang90  yes,  i only do it on that endpoint

**Comment by xiang90** [comment]
@xdk25d do you still see high i/o during the test on master as before? or it is getting better?

**Comment by xdk25d** [comment]
@xiang90  much better

**Comment by xiang90** [comment]
@xdk25d ok. thank you for the confirmation.
