### ISSUE TITLE
Failed to go get client

### ISSUE THREAD

**Issue by Gobonoid** [coreos/etcd#8573]
# Bug? - Failing to get client
`go get github.com/coreos/etcd/client`
On my computer and on CI. Go version 1.8.3. Are there any changes I should be aware of ?
```
go get -u github.com/coreos/etcd/client
# github.com/coreos/etcd/client
../../coreos/etcd/client/keys.generated.go:192: too many arguments in call to r.DecodeBytes
	have ([]byte, bool, bool)
	want ([]byte, bool)
../../coreos/etcd/client/keys.generated.go:604: too many arguments in call to r.DecodeBytes
	have ([]byte, bool, bool)
	want ([]byte, bool)
../../coreos/etcd/client/keys.generated.go:994: assignment count mismatch: 2 = 1
```
Kind regards,
M.

**Comment by Gobonoid** [comment]
Bah. 1.9+ required shown in documentation. Sorry to bother.

**Comment by Gobonoid** [comment]
```
go get -u github.com/coreos/etcd/client
# github.com/coreos/etcd/client
../../coreos/etcd/client/keys.generated.go:192: too many arguments in call to r.DecodeBytes
	have ([]byte, bool, bool)
	want ([]byte, bool)
../../coreos/etcd/client/keys.generated.go:604: too many arguments in call to r.DecodeBytes
	have ([]byte, bool, bool)
	want ([]byte, bool)
../../coreos/etcd/client/keys.generated.go:994: assignment count mismatch: 2 = 1
```

```
go version
go version go1.9 darwin/amd64
```

**Comment by abronan** [comment]
Experiencing the same thing here with `go 1.9`

**Comment by ggirtsou** [comment]
Could be related to changes in package https://github.com/ugorji/go/codec?

https://github.com/ugorji/go/commit/54210f4e076c57f351166f0ed60e67d3fca57a36

**Comment by lsytj0413** [comment]
same problem here

**Comment by Gobonoid** [comment]
Thank you.

**Comment by nulladmin** [comment]
I just got bitten by this too. Go 1.9 amd64

As a possibly interesting side note that ugorji/codec import adds 6.5M to the size of my binaries, basically doubling them in size. It's imported by both etcd and prometheus packages and is by far the largest sized import. If you're using only a limited functionallity from that package (I don't know if you are) then it may be worth reducing your dependency on pulling in the whole package.

This can tell you the binary size of each package in your build:

`
$: eval `go build -work -a 2>&1` && find $WORK -type f -name "*.a" | xargs -I{} du -hxs "{}" | sort -rh | sed -e s:${WORK}/::g
`

**Comment by gyuho** [comment]
@nulladmin What etcd packages are you vendoring? If you think it's unusual, please open a new issue. Thanks.
