### ISSUE TITLE
Question: Should I create a new client per request or reuse existing clients?

### ISSUE THREAD

**Issue by drewlandis** [coreos/etcd#8577]
# Question
Near the top of the clientv3 GoDoc it says:
`Make sure to close the client after using it. If the client is not closed, the connection will have leaky goroutines.`
Then just a few lines later it says:
`The Client has internal state (watchers and leases), so Clients should be reused instead of created as needed. Clients are safe for concurrent use by multiple goroutines.`

I have an app that infrequently makes get/put/delete requests to Etcd (<10 requests/min). I'm also about to start using watchers. I'm not so much worried about performance of the app as much as I just want to make sure that I'm using Etcd idiomatically (and making sure that it works correctly with watchers).

Should I create a new client per request or create one client at startup and then reuse that client throughout the rest of the app?

Thanks!

**Comment by xiang90** [comment]
> Make sure to close the client after using it.

A client means an application. When the life of your application ends, closes the etcd client it uses.

**Comment by ogunheper** [comment]
@xiang90 
How about the thread safety of the client? Is it legitimate to use the same client for different operations by different threads in parallel, or each of them should have their own?

Thanks and best regards,
