### ISSUE TITLE
Builds broken with latest go-codec change

### ISSUE THREAD

**Issue by purpleidea** [coreos/etcd#8579]
Recently ~23h ago:

https://github.com/ugorji/go/commit/54210f4e076c57f351166f0ed60e67d3fca57a36#diff-46a6c1a93a41b9397422576c715bf9f6L731

DecodeBytes changed from:
```
DecodeBytes(bs []byte, isstring, zerocopy bool) (bsOut []byte)
```
to:
```
DecodeStringAsBytes() (s []byte)
```

Etcd is using the old version here: https://github.com/coreos/etcd/blob/5bb9f9591f01d0a3c61d2eb3a3bb281726005b2b/client/keys.generated.go#L192 (current git master)

This broke all the builds using git master, and will be yet another thing to track down and fix if we ever want to increase the go-codec version. This is one of the reasons I argue *against* vendoring anything that doesn't *require* vendoring, because it makes it hard to move everything forward, instead of fixing one small thing at a time.

It was caught here: https://travis-ci.org/purpleidea/mgmt/jobs/277369429#L779 in our cron tests for https://github.com/purpleidea/mgmt/ since we use only the minimal subset of etcd that *requires* vendoring.

**Comment by gyuho** [comment]
Duplicate https://github.com/coreos/etcd/issues/8573?

**Comment by purpleidea** [comment]
@gyuho 

yeah I think so. I search issues, but didn't see it, sorry. I'd close that one as this one has more information, but it's up to you, and it's definitely a dupe :)

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/8574.

Thanks.

**Comment by purpleidea** [comment]
Thanks! (Could we use this opportunity to unvendor libs like this that don't need to be stuck at a specific version?)

**Comment by purpleidea** [comment]
LMK if you'd like a patch for that.

**Comment by gyuho** [comment]
@purpleidea `github.com/ugorji/go/codec` still needs to be vendored for `etcd/client` package. Even if it's only for generated code, seems like a good idea to have pinned version of it in glide.yaml.
