### ISSUE TITLE
etcd_wal_fsync_durations_seconds_bucket

### ISSUE THREAD

**Issue by igortin** [coreos/etcd#8586]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by gyuho** [comment]
Hi, what's your question?

**Comment by igortin** [comment]
Hi,

Could you help please to solve problem: etcd is overloaded.

DISK I/O:
curl -L http://localhost:2379/metrics | grep etcd_wal_fsync_durations_seconds_bucket
etcd_wal_fsync_durations_seconds_bucket{le="0.001"} 0
etcd_wal_fsync_durations_seconds_bucket{le="0.002"} 0
etcd_wal_fsync_durations_seconds_bucket{le="0.004"} 0
etcd_wal_fsync_durations_seconds_bucket{le="0.008"} 0
etcd_wal_fsync_durations_seconds_bucket{le="0.016"} 529
etcd_wal_fsync_durations_seconds_bucket{le="0.032"} 848052
etcd_wal_fsync_durations_seconds_bucket{le="0.064"} 2.7211701e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.128"} 3.3938307e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.256"} 3.541656e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.512"} 3.5706348e+07
etcd_wal_fsync_durations_seconds_bucket{le="1.024"} 3.5748624e+07
etcd_wal_fsync_durations_seconds_bucket{le="2.048"} 3.5752424e+07
etcd_wal_fsync_durations_seconds_bucket{le="4.096"} 3.5752512e+07
etcd_wal_fsync_durations_seconds_bucket{le="8.192"} 3.5752571e+07
etcd_wal_fsync_durations_seconds_bucket{le="+Inf"} 3.5752594e+07

Can anybody describe how to count a transactions per second? What is normal value?
For example p99 < 10ms, how to count that with our values?

**Comment by igortin** [comment]
What is mean etcd_wal_fsync_durations_seconds_bucket{le="0.064"} 2.7211701e+07 ????

**Comment by igortin** [comment]
thanks

**Comment by gyuho** [comment]
`etcd_wal_fsync_durations_seconds_bucket{le="0.064"}` counts wal fsync duration with `64ms` as upper bound of histogram bucket.

See https://github.com/coreos/etcd/blob/master/Documentation/faq.md#what-does-the-etcd-warning-failed-to-send-out-heartbeat-on-time-mean.

**Comment by igortin** [comment]
Thanks for help

**Comment by igortin** [comment]
Can you can tell how many transactions per1 ms according our statistics ?

**Comment by gyuho** [comment]
WAL has nothing to do with number of transactions. To query transactions, you would need something like

```
sum(rate(grpc_server_started_total{grpc_type=\"unary\"}[5m]))
sum(rate(grpc_server_handled_total{grpc_type=\"unary\",grpc_code!=\"OK\"}[5m]))

# or
sum(grpc_server_started_total{grpc_service=\"etcdserverpb.Txn\"})
```

ref. https://github.com/coreos/etcd/blob/master/Documentation/op-guide/monitoring.md#prometheus.

**Comment by igortin** [comment]
can you please suppose are values below:
etcd_wal_fsync_durations_seconds_bucket{le="0.064"} 2.7211701e+07
is disk io problem?

**Comment by gyuho** [comment]
Yes, `2.7211701e+07` fsyncs took +/-60ms. Slow disk will overload etcd.

**Comment by igortin** [comment]
thanks
