### ISSUE TITLE
DNS resolution from servers other than primary doesn't appear functional

### ISSUE THREAD

**Issue by naemono** [coreos/etcd#859]
etcd fails to start when using discovery when the primary dns server doesn't return a response, or is unreachable.  

etcd version 0.4.3
NAME=CoreOS
ID=coreos
VERSION=349.0.0
VERSION_ID=349.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 349.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"

logs from etcd are here:
https://gist.github.com/naemono/d7c3a974ad76e6ab34db

core@host-10-30-0-40 ~ $ cat /etc/resolv.conf
---cut---
nameserver 172.16.0.21
nameserver 8.8.8.8
domain openstack.local

In my case, when 172.16.0.21 was unreachable (system crashed), etcd never tried to resolve from 8.8.8.8, and simply died with the error referenced above.  

stack trace that pointed me to the issue:
https://gist.github.com/naemono/895b7aa8c252c065593d

Let me know if you need more information.

**Comment by f0** [comment]
i have the same error (useing etcd 0.4.6 on centos7) if the first nameserver in resolv.conf is not reacheble, etcdctl fails to sync woth the cluser (--no-sync also does not work), at the same time curl works.
I also tried to set resolv.conf options timeout:1 and attempts:1 this work for all expect etcdctl....

i think it is a BUG not an enhancement

**Comment by xiang90** [comment]
@f0 @naemono This sounds like a golang lib issue. Maybe you can try with today's etcd/etcdctl. Or you can file a issue for golang.
