### ISSUE TITLE
etcd-member.service starting issue v 3.1.0

### ISSUE THREAD

**Issue by dpoison** [coreos/etcd#8596]
# Bug reporting

Hello, 
I have tried to setup kubernetes with iPxe and matchbox.

every thing is going smooth. followed many diff docutments. but getting error while setting up controller. etcd-member is not starting. giving bellow error. 

systemctl status etcd-member
● ```
etcd-member.service - etcd (System Application Container)
   Loaded: loaded (/usr/lib/systemd/system/etcd-member.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/etcd-member.service.d
           └─40-etcd-cluster.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-09-22 14:00:40 UTC; 1s ago
     Docs: https://github.com/coreos/etcd
  Process: 1001 ExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS (code=exited, status=254)
  Process: 998 ExecStartPre=/usr/bin/rkt rm --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid (code=exited, status=254)
  Process: 995 ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos (code=exited, status=0/SUCCESS)
 Main PID: 1001 (code=exited, status=254)
      CPU: 614ms

Sep 22 14:00:40 node1.dynamic systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Sep 22 14:00:40 node1.dynamic systemd[1]: Failed to start etcd (System Application Container).
Sep 22 14:00:40 node1.dynamic systemd[1]: etcd-member.service: Unit entered failed state.
Sep 22 14:00:40 node1.dynamic systemd[1]: etcd-member.service: Failed with result 'exit-code'.

```
Have any one tried this and have any suggetions? 

The link i have followed is : https://github.com/coreos/matchbox/blob/master/Documentation/deployment.md

Other log error from journalctl -xe is as bellow. 

```
 Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616887 I | pkg/flags: recognized and used environment variable ETCD_TRUSTED_CA_FILE=/etc/ssl/certs/etcd/server-ca.crt
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616908 W | pkg/flags: unrecognized environment variable ETCD_SSL_DIR=/etc/ssl/etcd
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616918 W | pkg/flags: unrecognized environment variable ETCD_USER=etcd
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616926 W | pkg/flags: unrecognized environment variable ETCD_IMAGE_TAG=v3.2.0
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616957 I | etcdmain: etcd Version: 3.2.0
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616965 I | etcdmain: Git SHA: 66722b1
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616971 I | etcdmain: Go Version: go1.8.3
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616977 I | etcdmain: Go OS/Arch: linux/amd64
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.616984 I | etcdmain: setting maximum number of CPUs to 1, total number of available CPUs is 1
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.617057 I | embed: peerTLS: cert = /etc/ssl/certs/etcd/peer.crt, key = /etc/ssl/certs/etcd/peer.key, ca = , trusted-ca = /etc/ssl/certs/etcd/peer-ca.crt, client-cert-auth = true
Sep 22 13:09:15 node1.dynamic etcd-wrapper[3630]: 2017-09-22 13:09:15.622183 C | etcdmain: open /etc/ssl/certs/etcd/peer.crt: no such file or directory
Sep 22 13:09:15 node1.dynamic systemd[1]: etcd-member.service: Main process exited, code=exited, status=1/FAILURE
Sep 22 13:09:15 node1.dynamic systemd[1]: Failed to start etcd (System Application Container).
-- Subject: Unit etcd-member.service has failed
-- Defined-By: systemd
```

**Comment by gyuho** [comment]
> C | etcdmain: open /etc/ssl/certs/etcd/peer.crt: no such file or directory

Your cert path is wrong?

**Comment by dpoison** [comment]
Yes path is proper, as per the guideline. 
Now after running bootkube render again, getting new error. 

```

_Sep 23 09:55:14 node1.dynamic systemd[1]: Starting etcd (System Application Container)...
-- Subject: Unit etcd-member.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd-member.service has begun starting up.
Sep 23 09:55:14 node1.dynamic rkt[965]: rm: unable to resolve UUID from file: open /var/lib/coreos/etcd-member-wrapper.uuid: no such file or directory
Sep 23 09:55:14 node1.dynamic rkt[965]: rm: failed to remove one or more pods
Sep 23 09:55:14 node1.dynamic etcd-wrapper[968]: ++ id -u etcd
Sep 23 09:55:14 node1.dynamic etcd-wrapper[968]: + exec /usr/bin/rkt run --uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid --trust-keys-from-https --mount volume=coreos-systemd-dir,target=/run/systemd/system --volume coreos-systemd-dir,kind=host,source=/run/systemd/system,readOnly=true --mount volume=coreos-notify,target=/run/systemd/notify --volume coreos-notify,kind=host,source=/run/systemd/notify --set-env=NOTIFY_SOCKET=/run/systemd/notify --volume coreos-data-dir,kind=host,source=/var/lib/etcd,readOnly=false --volume coreos-etc-ssl-certs,kind=host,source=/etc/ssl/etcd,readOnly=true --volume coreos-usr-share-certs,kind=host,source=/usr/share/ca-certificates,readOnly=true --volume coreos-etc-hosts,kind=host,source=/etc/hosts,readOnly=true --volume coreos-etc-resolv,kind=host,source=/etc/resolv.conf,readOnly=true --mount volume=coreos-data-dir,target=/var/lib/etcd --mount volume=coreos-etc-ssl-certs,target=/etc/ssl/certs --mount volume=coreos-usr-share-certs,target=/usr/share/ca-certificates --mount volume=coreos-etc-hosts,target=/etc/hosts --mount volume=coreos-etc-resolv,target=/etc/resolv.conf --inherit-env --stage1-from-dir=stage1-fly.aci quay.io/coreos/etcd:v3.2.0 --user=232 --
Sep 23 09:55:42 node1.dynamic etcd-wrapper[968]: run: discovery failed
Sep 23 09:55:42 node1.dynamic systemd[1]: etcd-member.service: Main process exited, code=exited, status=254/n/a
Sep 23 09:55:42 node1.dynamic systemd[1]: Failed to start etcd (System Application Container).
-- Subject: Unit etcd-member.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd-member.service has failed.
--
-- The result is failed.
Sep 23 09:55:42 node1.dynamic systemd[1]: etcd-member.service: Unit entered failed state.
Sep 23 09:55:42 node1.dynamic systemd[1]: etcd-member.service: Failed with result 'exit-code'.
Sep 23 09:55:52 node1.dynamic systemd[1]: etcd-member.service: Service hold-off time over, scheduling restart.
Sep 23 09:55:52 node1.dynamic systemd[1]: Stopped etcd (System Application Container).
-- Subject: Unit etcd-member.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit etcd-member.service has finished shutting down._

```

**Comment by gyuho** [comment]
> path is proper, as per the guideline

Does path actual exist in your machine? Or correctly mounted?

**Comment by gyuho** [comment]
@dpoison Ping? Also this doesn't seem like an etcd issue.

**Comment by gyuho** [comment]
> etcdmain: open /etc/ssl/certs/etcd/peer.crt: no such file or directory

etcd error is clear. Seems like misconfiguration in certs directory mounting.
And regarding bootkube, please open an issue in bootkube or matchbox repo.

Please reopen if you still think this is an etcd issue.

**Comment by rushins** [comment]
i got the same error and its clear with ETCD issue not certs . what certs are you referring

**Comment by gyuho** [comment]
@rushins It depends how you configure certs directory. See https://github.com/coreos/etcd/blob/master/Documentation/platforms/container-linux-systemd.md#etcd-3x-service for example.

**Comment by rushins** [comment]
i am confused, i am using matchbox with tectonic installer and i expected that certs will be copied during the install. ? i didnt' configure any certs as ETCD is container in Master (controller) and its exiting at the first bootup and its "RKT" environment "rkt list "

**Comment by gyuho** [comment]
@rushins Please open an issue at https://github.com/coreos/tectonic-installer/issues. Thanks.

**Comment by rushins** [comment]
i just did etcd-member.service starting issue #2030

**Comment by gyuho** [comment]
If you think it's an etcd issue, please provide fully detailed steps to reproduce in a separate issue.
If you are using it with matchbox + tectonic installer, installer team should be able to help you better.

**Comment by eddieesquivel** [comment]
@gyuho just ran into this with a customer. If I find a solution I'll go ahead and document it here.

**Comment by eddieesquivel** [comment]
We had a mismatch between dnsmasq hostnames and the hostnames specificed in the terraform.tfvars controller_domains and worker_domains.

In order to debug we pre-pended TF_LOG=debug to the terraform apply step.

**Comment by dpoison** [comment]
We have successfully implemented bellow environment. 

Env Info:

> provisioner.example.com > 192.168.51.80 > my dhcp, tftp, xientd, dns, matchbox server
> node1.example.com > 192.168.51.208 > Controller node with Calico networking
> node2.example.com > 192.168.51.210 > Worker node with secure etcd (with ssl)
> node3.example.com > 192.168.51.211 > Worker node with secure etcd (with ssl)

Version Details

> CoreOS 1520.8.0
> Kubelet 1.8.2
> Calico 2.6.2
> Etcd 3.2.0

Files from **/var/lib/matchbox** are given here if anyone wants to test. (FYI: all the keys are wrong so please change for yourself)
[matchbox.zip](https://github.com/coreos/etcd/files/1453945/matchbox.zip)


**Here is the output of some kubectl commands for status.** 

```
[root@provisioner ~ ]$ kubectl get nodes
NAME                STATUS    ROLES     AGE       VERSION
node1.example.com   Ready     master    48m       v1.8.2+coreos.0
node2.example.com   Ready     node      48m       v1.8.2+coreos.0
node3.example.com   Ready     node      48m       v1.8.2+coreos.0
```

```
[root@provisioner ~ ]$ calicoctl get nodes
NAME
node1.example.com
node2.example.com
node3.example.com
```

```
[root@provisioner ~ ]$ calicoctl get ippool
CIDR
172.16.0.0/16
```

```
[root@provisioner ~ ]$ kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   calico-kube-controllers-f58c74bfd-vtpsv     1/1       Running   0          48m       192.168.51.211   node3.example.com
kube-system   calico-node-fx8q9                           2/2       Running   0          48m       192.168.51.210   node2.example.com
kube-system   calico-node-qqd4n                           2/2       Running   0          48m       192.168.51.208   node1.example.com
kube-system   calico-node-zgvdl                           2/2       Running   0          48m       192.168.51.211   node3.example.com
kube-system   calico-policy-controller-566dc8d645-7bhd9   1/1       Running   0          48m       192.168.51.211   node3.example.com
kube-system   kube-apiserver-nvfkp                        1/1       Running   0          48m       192.168.51.208   node1.example.com
kube-system   kube-controller-manager-645b5d5567-xsnr7    1/1       Running   0          48m       172.16.0.3       node1.example.com
kube-system   kube-dns-678d98c748-7sg5z                   3/3       Running   0          48m       172.16.0.2       node1.example.com
kube-system   kube-proxy-2wwkd                            1/1       Running   0          48m       192.168.51.208   node1.example.com
kube-system   kube-proxy-5f2kr                            1/1       Running   0          48m       192.168.51.210   node2.example.com
kube-system   kube-proxy-kfqs9                            1/1       Running   0          48m       192.168.51.211   node3.example.com
kube-system   kube-scheduler-8ddbc88b6-jvjth              1/1       Running   0          48m       172.16.0.4       node1.example.com
kube-system   pod-checkpointer-74jtn                      1/1       Running   0          48m       192.168.51.208   node1.example.com
kube-system   pod-checkpointer-74jtn-node1.example.com    1/1       Running   0          48m       192.168.51.208   node1.example.com
```
Thanks @gyuho @dghubble & @eddieesquivel for your suggestions. 

And special thanks to Mr. Amit Patel @amit2277

**Comment by dghubble** [comment]
Again, this isn't a design I recommend, workers shouldn't be etcd peers. But good luck.

**Comment by amit2277** [comment]
Thanks Dalton for valuable advice :) this is our test environment now we'll setup development environment where we should separate etcd cluster from workers , best would be i believe on controller or out of k8s cluster right? but we dont want to waste our physical hardware only fro etcd , what is your suggestion best fit?  
Thanks in Advance  :)

**Comment by dghubble** [comment]
The default matchbox examples run etcd across controller(s). That allows you to handle controllers with more care, while workers are fungible and can be killed or replaced at any time. That setup wouldn't increase your hardware footprint.

**Comment by amit2277** [comment]
Thanks Dalton , our next step will be High availability of controller I am not sure how to achieve this without load balancer , is there anything you have tested if you can share would be highly appreciable or we can start another thread with that topic.  PS : i have tried manually installation of k8s with two controller and load balancer (pfsense HAProxy) it was successfully failed :) .  so would be grateful to you and team who can guide us (this community) to achieve HA K8S with Matchbox  :)  Thanks and again appreciated

**Comment by dghubble** [comment]
Matchbox provides a multi-controller (and thus multi-etcd) [example](https://github.com/coreos/matchbox/tree/master/examples/terraform/bootkube-install#optional). You can also checkout https://github.com/coreos/matchbox#projects which are built around Matchbox.

If you have further questions, ping me on IRC or Kubernetes slack (dghubble), I don't want to hijack this issue.

**Comment by dpoison** [comment]
Thanks, @dghubble  for your support. We will be in touch with result or errors.
