### ISSUE TITLE
Question: starting up raft cluster with incomplete peers list

### ISSUE THREAD

**Issue by rsm10** [coreos/etcd#8598]
Scenario:

Have nodes A,B,C,D.

A starts, and is missing node C in its list of peers that it passed to raft.StartNode(). No other nodes have started yet.
B starts and has all 4 nodes in its peer list that it passes to StartNode().
C starts, and also has all 4 nodes in its peer list.
D starts and has all 4 nodes as well.

I would expect that even though A was missing C initially, when C starts it should send A and ConfChangeAddNode message and A should update its internal peers list with this new node; in the same way adding a new join would (if we expanded our cluster).

My question is if this is a correct assumption?

What I have seen does not seem to support my assumption:

Everything goes the same as what I expect, except that NodeA does not seem to register the ConfChangeAddNode from NodeC; and instead gets a second ConfChangeAddNode for itself (which I thought was impossible since it ignores duplicate addNode calls).

"Start with peers" is called just before "StartNode". And the "ApplyConfChange" message is in the main raft loop, in the "case raftpb.EntryConfChange:" branch.

NodeA == 11902872
NodeB == 11201715
NodeC == 11296742
NodeD == 11397556

NodeA:/home/admin # grep ApplyConf /tmp/rsm
Sep 21 18:34:11 INFO: Start with peers [{11397556 []} {11902872 []} {11201715 []}]
Sep 21 18:34:11 INFO: ApplyConfChange {0 ConfChangeAddNode 11397556 [] []} 98-245:
Sep 21 18:34:11 INFO: ApplyConfChange {0 ConfChangeAddNode 11902872 [] []}
Sep 21 18:34:11 INFO: ApplyConfChange {0 ConfChangeAddNode 11201715 [] []}  -99-158
Sep 21 18:34:55 INFO: ApplyConfChange {0 ConfChangeAddNode 11902872 [] []} 99-159

NodeB:/home/admin
Sep 21 18:34:44 INFO: Start with peers [{11296742 []} {11397556 []} {11902872 []} {11201715 []}]
Sep 21 18:34:44 INFO: ApplyConfChange {0 ConfChangeAddNode 11296742 [] []}
Sep 21 18:34:44 INFO: ApplyConfChange {0 ConfChangeAddNode 11397556 [] []}
Sep 21 18:34:44 INFO: ApplyConfChange {0 ConfChangeAddNode 11902872 [] []}
Sep 21 18:34:44 INFO: ApplyConfChange {0 ConfChangeAddNode 11201715 [] []}

NodeC:/home/admin # grep ApplyConf /tmp/rsm

Sep 21 18:34:48 INFO: Start with peers [{11201715 []} {11296742 []} {11397556 []} {11902872 []}]
Sep 21 18:34:48 INFO: ApplyConfChange {0 ConfChangeAddNode 11201715 [] []}
Sep 21 18:34:48 INFO: ApplyConfChange {0 ConfChangeAddNode 11296742 [] []} 99-157
Sep 21 18:34:48 INFO: ApplyConfChange {0 ConfChangeAddNode 11397556 [] []}
Sep 21 18:34:48 INFO: ApplyConfChange {0 ConfChangeAddNode 11902872 [] []}

NodeD:/home/admin
Sep 21 18:34:49 INFO: Start with peers [{11201715 []} {11296742 []} {11397556 []} {11902872 []}]
Sep 21 18:34:49 INFO: ApplyConfChange {0 ConfChangeAddNode 11201715 [] []}
Sep 21 18:34:49 INFO: ApplyConfChange {0 ConfChangeAddNode 11296742 [] []}
Sep 21 18:34:49 INFO: ApplyConfChange {0 ConfChangeAddNode 11397556 [] []}
Sep 21 18:34:49 INFO: ApplyConfChange {0 ConfChangeAddNode 11902872 [] []}

**Comment by xiang90** [comment]
Everyone needs know everyone for its their first starts.

**Comment by rsm10** [comment]
Can you elaborate on how this scenario is different than when you add a new node to the cluster?

Ie. You start A,B,C and they are all up and running fine. Then you add D, and it sends a ConfChangeAddNode to all of them (and since it is new none of A,B and C know about D yet)
