### ISSUE TITLE
Support setting multiple keys in one atomic commit

### ISSUE THREAD

**Issue by tristanz** [coreos/etcd#860]
Zookeeper supports updating multiple nodes in one atomic commit.  This can be very useful. 

http://zookeeper.apache.org/doc/r3.4.3/api/org/apache/zookeeper/ZooKeeper.html#multi(java.lang.Iterable)

**Comment by yichengq** [comment]
@bgrant0607 
The design of new kv api is in progress and we have draft thoughts and prototype around. We are actively working on it now, and plan to publish it about two weeks later.
Here are some rough ideas about new api and how it can solve k8s requirements(we get it from k8s issue):
- Support multiple versioned key. Each key maintains its local version, which increments by 1 whenever it changes. This helps to solve optimistic concurrency, and efficient reliable watch.
- Support client-driven compaction. History is kept in the cluster until it is compacted. It ensures that client can access to past versions of objects.
- Support multi-object streaming watch. After connecting to the server, client can watch on multiple objects, and will be notified about all changes of them until the connection is closed.
- Support transaction.
- Only keep hot keys in memory, and save others into disk. This largely increases the capacity of the store.
- Support more efficient TTL mechanism. It is supposed to hold million-level ttl keys for one cluster.

For acl, it will be added in the proxy. 
Can you please explain what is "Pagination support"? or point me to a reference?

**Comment by bgrant0607** [comment]
Great!

FYI, our high-level feature wishlist (which maybe you saw) is here:
https://github.com/GoogleCloudPlatform/kubernetes/issues/1957#issuecomment-69863343

"Pagination" is some way to break up large responses into multiple responses. Chunked HTTP would be a simple example, but typically multiple requests are necessary in REST APIs. For instance:
http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api#pagination
https://blog.apigee.com/detail/restful_api_design_can_your_api_give_developers_just_the_information
https://cloud.google.com/appengine/docs/python/datastore/queries#Python_Query_cursors

We use recursive GETs to retrieve lists of objects in a subtree. If there were, say, a hundred thousand objects in a subtree, that shouldn't be returned in one enormous request or list. Internally, we use streaming RPCs for such cases, but pagination is more common in REST APIs. Search for "rest api pagination" and you'll find loads of examples: github, twitter, newrelic, ...

/cc @lavalamp @smarterclayton

**Comment by xiang90** [comment]
@bgrant0607 Thanks!
Actually we have the plan to use the `range` header in http to achieve the goal. internally etcd keep all versions of keys, so it is simple to do.

**Comment by sckott** [comment]
+1

**Comment by xiang90** [comment]
See https://github.com/coreos/etcd/blob/master/Documentation/rfc/v3api.md

**Comment by hot13399** [comment]
Hi,

does etcd support range now? I want to do pagination through it.

Thanks,
Jerry

**Comment by tejinderss** [comment]
Hey how can i achieve this? Should i use transaction put multiple keys without using any precondition ? And does range provide setting the keys ? Also can I use range for fetching the multiple keys under same namespace. I have a use case where i need to store multiple keys under same name corresponding to micro service. How can i do that ?
