### ISSUE TITLE
Use of client's crt/key pair to launch a cluster memeber

### ISSUE THREAD

**Issue by ayashjorden** [coreos/etcd#8607]
Hello ETCd team,
I've got a security question for you.

Assuming that we have a TLS enabled cluster with N members.
Both `--peer-client-cert-auth` and `--client-cert-auth` are enabled as well.

Given that one gains access to a **client's** TLS crt/key pair, will he/she be able to launch a **cluster member** ETCd instance using the **client's TLS crt/key pair** and it will successfully join the cluster?

I've read through #8262, which is great, but currently I have to run two CAs, one will generate ETCd cluster peers' crt/key-s and the second will generate clients' crt/key-pairs (k8s, applications and such.)

The issue is not clear on the [TLS][TLS_link] page.

I will be able to test it in a couple of days, but until then, if anyone can comment or share experience, that would be great 👍 

Best,
Yarden

[TLS_link]: https://coreos.com/etcd/docs/latest/op-guide/security.html

**Comment by jpbetz** [comment]
@ayashjorden Are you asking if the cert/key pairs used for "client-to-server" communication can also be used for "server-to-server / cluster" communication? My reading of the [TLS](https://coreos.com/etcd/docs/latest/op-guide/security.html) page is that they are separate. What did you find unclear about the page?

**Comment by ayashjorden** [comment]
Hi @jpbetz,

My reading of the TLS page is that I can use two crt/key pairs in the cluster-member configuration. One for server-to-server and one for client-to-server. but it does not explain how cluster members are controlled.

Given that I have **one** CA that issues certificates for cluster-members and clients(with CN or SAN), What prevents me from using a _client-to-server_ crt/key pair for _server-to-server / cluster_ communication?

Is there some RBAC for cluster members?

**Comment by gyuho** [comment]
> will he/she be able to launch a cluster member ETCd instance using the client's TLS crt/key pair and it will successfully join the cluster?

Only if your server certs have matching hosts (either exact match or wildcard matching).
DNS SAN wildcard reverse lookup is only available from etcd v3.2.5.

**Comment by ayashjorden** [comment]
That would be a nice experiment

As @Ulexus mentioned in [this][coreos_user_thread] thread, the best practice for preventing interloop cluster members is multiple CAs. one for server-to-server and another for client-to-server.

Any comments/ideas?

[coreos_user_thread]: https://groups.google.com/forum/#!topic/coreos-user/gLQPxv_-Idg

**Comment by Ulexus** [comment]
Also note that the PKI for the members is _only_ used between members, so it's much easier (better?) to use a private, unaffiliated, unregistered, undistributed CA for the peering system.

I believe your basic assumption about the system, though, is correct.  The only present authorization available for members is the CA test, so if the client key is compromised and the clients and members share the same CA, cluster membership is at risk.

However, if your client keys are compromised, you're really at the mercy of any number of problems anyway.  A client could change any data in the database.  A client could change the membership such that quorum is lost.  A client could add members which bypass non-source-discriminatory firwalls.

Basically, then, if you can't trust your clients, you really need to use [role-based access control](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/authentication.md) on the client side.  No amount of PKI wrangling will protect your cluster if your clients are compromised.

**Comment by ayashjorden** [comment]
@Ulexus, to clarify, by 

> you really ned to use RBAC on the client side

you mean the ETCd RBAC system on the KeySpace?

**Comment by Ulexus** [comment]
The `root` roles provide access to the cluster membership controls, from what I understand, yes.  In etcdv2, the membership data was stored inside the key space like everything else.  I presume (but have not verified) that this is still true for etcdv3.

If the vulnerability you are trying to address is a compromised client keyset (and, one presumes, any authentication thereof), then keeping your operational clients constrained within restricted roles seems to be the surest answer.

**Comment by ayashjorden** [comment]
Thank you **all** for the valuable info and insights.

Is there any way I can help to get this information to the community in a more visible way than a Github issue?

**Comment by gyuho** [comment]
We have auth doc https://github.com/coreos/etcd/blob/master/Documentation/op-guide/authentication.md. And https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md. If you find anything missing, please let us know. Thanks!

**Comment by ayashjorden** [comment]
@gyuho,
The two links provided does not describe what what discussed in this ticket about best-practices for authorization of cluster-members vs. cluster-clients.
