### ISSUE TITLE
question: why url type is constrained in "host:port(no path)" format

### ISSUE THREAD

**Issue by lorneli** [coreos/etcd#8609]
Url used in etcd is constrained in "host:port(no path)" format. https://github.com/coreos/etcd/blob/master/pkg/types/urls.go#L28

    if _, _, err := net.SplitHostPort(u.Host); err != nil {
        return nil, fmt.Errorf(`URL address does not have the form "host:port": %s`, in)
    }
    if u.Path != "" {
        return nil, fmt.Errorf("URL must not contain a path: %s", in)
    }

Under this constraint, the path of unix socket file in integration pkg is `127.0.0.1:port+pid`, a related path. 
https://github.com/coreos/etcd/blob/master/integration/cluster.go#L460 . In my view, a more common unix socket file path may be `/absolute/path/xxx.sock`(url.host="", url.path="absolute path").

    func newLocalListener(t *testing.T) net.Listener {
        c := atomic.AddInt64(&localListenCount, 1)
        // Go 1.8+ allows only numbers in port
        addr := fmt.Sprintf("127.0.0.1:%05d%05d", c+basePort, os.Getpid())
        return NewListenerWithAddr(t, addr)
    }

So why url type is constrained in "host:port(no path)" format? Can't find the reason from this constraint's commit https://github.com/coreos/etcd/commit/83137f9eba183b454264b9902f00739b42ba49a8 .

Thanks in advance.

**Comment by gyuho** [comment]
> So why url type is constrained in "host:port(no path)" format?

It was added merely for testing, so it makes sense to enforce URL format.
For more general unix socket use case, we might remove such constraints in the future.
