### ISSUE TITLE
How to get versioning key history using curl/http:- etcd

### ISSUE THREAD

**Issue by bhaveshj21** [coreos/etcd#8610]
Hi,

I have an api which hit etcd using http, I need to get the key history like all the previous version

etcdctl get --prefix --rev=4 foo

my etcd configuration are 

**{"etcdserver":"3.2.7","etcdcluster":"3.2.0"}**

How can I do it through the http/curl ?

also only curl/http command works for me, If I try to run using etcdctl 
I get 
**-bash: etcdctl: command not found**

**Comment by gyuho** [comment]
Please see https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md.

**Comment by bhaveshj21** [comment]
Is it compulsory for key value to be base64, is there a way I can store normal string as I want to store some json values also.

**Comment by gyuho** [comment]
> Is it compulsory for key value to be base64

Yes, for etcd grpc-gateway.

You can get previous version of key-value pairs.

https://godoc.org/github.com/coreos/etcd/clientv3#WithPrevKV

**Comment by Rakoth** [comment]
WithPrevKV has no effect on get operation
