### ISSUE TITLE
LICENSE file missing some templating information

### ISSUE THREAD

**Issue by devoxel** [coreos/etcd#8613]
This is a trivial issue. Your license file is [missing some template info](https://github.com/coreos/etcd/blob/master/LICENSE#L190).

**Comment by gyuho** [comment]
We check other projects with same license and seems it's ok to keep as it is (e.g. https://github.com/kubernetes/kubernetes/blob/master/LICENSE#L190).

We add LICENSE header to every single source code file, which is good enough.

Thanks.
