### ISSUE TITLE
question about isBadOp func in clientv3/leasing

### ISSUE THREAD

**Issue by lorneli** [coreos/etcd#8617]
Sorry for the bother.

In clientv3/leasing/cache.go, function [evalOps](https://github.com/coreos/etcd/blob/master/clientv3/leasing/cache.go#L287) tries to use cache to response `get` ops. It calls `isBadOp` to check whether it can serve one `get` op.

    func (lc *leaseCache) evalOps(ops []v3.Op) ([]*v3pb.ResponseOp, bool) {
        resps := make([]*v3pb.ResponseOp, len(ops))
        for i, op := range ops {
            if !op.IsGet() || isBadOp(op) {
			return nil, false
		}
        // ....
    }

    func isBadOp(op v3.Op) bool { return op.Rev() > 0 || len(op.RangeBytes()) > 0 }

`isBadOp` function checks whether this op's revision > 0 or this op is a range query. Why leasing cache can't serve the op with revision >0? I find cache key itself has a revision, maybe key's revision could be used to match op's revision?

    type leaseKey struct {
        response *v3.GetResponse
        // rev is the leasing key revision.
        rev   int64
        waitc chan struct{}
    }

Thanks in advance.:smiley:

**Comment by gyuho** [comment]
What's your use case of specifying `rev` field?

**Comment by lorneli** [comment]
I haven't used clientv3/leasing in practice. 

I can understand why cache doesn't serve range query ( `len(op.RangeBytes()) > 0` ): it maybe doesn't have all qualified keys. But the former statement `op.Rev() > 0` confuses me. I can't figure out why leasing cache refuses to serve op with `rev` >0 here.

**Comment by gyuho** [comment]
If range request specifies old revision, cache might serve stale data?

**Comment by lorneli** [comment]
Cache key stores a revision itself. For a single query, maybe key's revision could be used to match op's revision to avoid getting stale data? Or they are not the same thing?

    type leaseKey struct {
        response *v3.GetResponse
        // rev is the leasing key revision.
        rev   int64
        waitc chan struct{}
    }

    func (lc *leaseCache) Add(key string, resp *v3.GetResponse, op v3.Op) *v3.GetResponse {
        lk := &leaseKey{resp, resp.Header.Revision, closedCh}
    // ...

**Comment by gyuho** [comment]
> maybe key's revision could be used to match op's revision to avoid getting stale data

There's no guarantee that your specified revision is the latest.
If revision==0, you get the latest.

**Comment by lorneli** [comment]
@gyuho  Thanks for your help.
