### ISSUE TITLE
etcdclient: leases keep alive halted: etcdserver: request timed out

### ISSUE THREAD

**Issue by zimulala** [coreos/etcd#8618]
I want to use the interface of `NewSession` in clientv3 to new a session. But I encountered a problem in the certain case.
The result of `NewSession` always failed and reported "etcdclient: leases keep alive halted: etcdserver: request timed out". 
I think it's because the etcd server occurs an ErrTimeout, the log content is "[warning] etcdserver: [timed out waiting for read index response]". Then it makes the client's channel of `donec` closed in recvKeepaliveLoop function. And makes the execution result fail.
I think it's unreasonable. In my opinion, handle it in one way that closes the client when the keepalive is halted, or another way that provides an interface which can restart the recvKeepaliveLoop.

**Comment by gyuho** [comment]
> etcd server occurs an ErrTimeout, the log content is "[warning] etcdserver: [timed out waiting for read index response]"

Means etcdserver is not responding?

And why not just retry in for-loop?

**Comment by zimulala** [comment]
No. I mean the etcdserver returns the `ErrTimeout` to the client, and I retry `NewSession`.
But I think the `recvKeepaliveLoop` is returned and `donec` is closed when the etcdserver returns `ErrTimeout` as a response. So it is useless to try `NewSession`  again.

**Comment by gyuho** [comment]
What is `recvKeepaliveLoop`? Please provide reproducible code snippet.

**Comment by zimulala** [comment]
It is fixed in the master branch.

**Comment by zimulala** [comment]
@gyuho Thanks！
RP #7890
