### ISSUE TITLE
go build many many error

### ISSUE THREAD

**Issue by yuchao86** [coreos/etcd#8623]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md
go build                                                                                                                                  [15:51:53]
# github.com/coreos/etcd/clientv3
../../go/src/github.com/coreos/etcd/clientv3/client.go:331: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
	*authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
		have GetRequestMetadata("context".Context, ...string) (map[string]string, error)
		want GetRequestMetadata("golang.org/x/net/context".Context, ...string) (map[string]string, error)
../../go/src/github.com/coreos/etcd/clientv3/client.go:383: cannot use sb (type *simpleBalancer) as type balancer in argument to newHealthBalancer:
	*simpleBalancer does not implement balancer (wrong type for Get method)
		have Get("context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
		want Get("golang.org/x/net/context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
../../go/src/github.com/coreos/etcd/clientv3/retry.go:112: cannot use *retryKVClient literal (type *retryKVClient) as type etcdserverpb.KVClient in return argument:
	*retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
../../go/src/github.com/coreos/etcd/clientv3/retry.go:113: cannot use retryBasic (type *retryKVClient) as type etcdserverpb.KVClient in field value:
	*retryKVClient does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
../../go/src/github.com/coreos/etcd/clientv3/retry.go:178: cannot use retry (type *retryLeaseClient) as type etcdserverpb.LeaseClient in field value:
	*retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
../../go/src/github.com/coreos/etcd/clientv3/retry.go:178: cannot use *retryLeaseClient literal (type *retryLeaseClient) as type etcdserverpb.LeaseClient in return argument:
	*retryLeaseClient does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
../../go/src/github.com/coreos/etcd/clientv3/retry.go:205: cannot use retryClusterClient literal (type *retryClusterClient) as type etcdserverpb.ClusterClient in return argument:
	*retryClusterClient does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)
		have MemberAdd("context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
		want MemberAdd("golang.org/x/net/context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
../../go/src/github.com/coreos/etcd/clientv3/retry.go:239: cannot use retryAuthClient literal (type *retryAuthClient) as type etcdserverpb.AuthClient in return argument:
	*retryAuthClient does not implement etcdserverpb.AuthClient (wrong type for AuthDisable method)
		have AuthDisable("context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
		want AuthDisable("golang.org/x/net/context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
# github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:147: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:149: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:154: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:158: not enough arguments in call to forward_Election_Campaign_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:175: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:177: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:182: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:186: not enough arguments in call to forward_Election_Proclaim_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:203: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:205: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go:205: too many errors
# github.com/coreos/etcd/proxy/grpcproxy/adapter
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/auth_client_adapter.go:28: cannot use as2ac literal (type *as2ac) as type etcdserverpb.AuthClient in return argument:
	*as2ac does not implement etcdserverpb.AuthClient (wrong type for AuthDisable method)
		have AuthDisable("context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
		want AuthDisable("golang.org/x/net/context".Context, *etcdserverpb.AuthDisableRequest, ...grpc.CallOption) (*etcdserverpb.AuthDisableResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/chan_stream.go:151: cannot use srv (type *chanStream) as type grpc.Stream in field value:
	*chanStream does not implement grpc.Stream (wrong type for Context method)
		have Context() "context".Context
		want Context() "golang.org/x/net/context".Context
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/cluster_client_adapter.go:28: cannot use cls2clc literal (type *cls2clc) as type etcdserverpb.ClusterClient in return argument:
	*cls2clc does not implement etcdserverpb.ClusterClient (wrong type for MemberAdd method)
		have MemberAdd("context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
		want MemberAdd("golang.org/x/net/context".Context, *etcdserverpb.MemberAddRequest, ...grpc.CallOption) (*etcdserverpb.MemberAddResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/election_client_adapter.go:28: cannot use es2ec literal (type *es2ec) as type v3electionpb.ElectionClient in return argument:
	*es2ec does not implement v3electionpb.ElectionClient (wrong type for Campaign method)
		have Campaign("context".Context, *v3electionpb.CampaignRequest, ...grpc.CallOption) (*v3electionpb.CampaignResponse, error)
		want Campaign("golang.org/x/net/context".Context, *v3electionpb.CampaignRequest, ...grpc.CallOption) (*v3electionpb.CampaignResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/election_client_adapter.go:51: cannot use es2ecClientStream literal (type *es2ecClientStream) as type v3electionpb.Election_ObserveClient in return argument:
	*es2ecClientStream does not implement v3electionpb.Election_ObserveClient (wrong type for Context method)
		have Context() "context".Context
		want Context() "golang.org/x/net/context".Context
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/kv_client_adapter.go:28: cannot use kvs2kvc literal (type *kvs2kvc) as type etcdserverpb.KVClient in return argument:
	*kvs2kvc does not implement etcdserverpb.KVClient (wrong type for Compact method)
		have Compact("context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
		want Compact("golang.org/x/net/context".Context, *etcdserverpb.CompactionRequest, ...grpc.CallOption) (*etcdserverpb.CompactionResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/lease_client_adapter.go:30: cannot use ls2lc literal (type *ls2lc) as type etcdserverpb.LeaseClient in return argument:
	*ls2lc does not implement etcdserverpb.LeaseClient (wrong type for LeaseGrant method)
		have LeaseGrant("context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
		want LeaseGrant("golang.org/x/net/context".Context, *etcdserverpb.LeaseGrantRequest, ...grpc.CallOption) (*etcdserverpb.LeaseGrantResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/lease_client_adapter.go:45: cannot use ls2lcClientStream literal (type *ls2lcClientStream) as type etcdserverpb.Lease_LeaseKeepAliveClient in return argument:
	*ls2lcClientStream does not implement etcdserverpb.Lease_LeaseKeepAliveClient (wrong type for Context method)
		have Context() "context".Context
		want Context() "golang.org/x/net/context".Context
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/lock_client_adapter.go:28: cannot use ls2lsc literal (type *ls2lsc) as type v3lockpb.LockClient in return argument:
	*ls2lsc does not implement v3lockpb.LockClient (wrong type for Lock method)
		have Lock("context".Context, *v3lockpb.LockRequest, ...grpc.CallOption) (*v3lockpb.LockResponse, error)
		want Lock("golang.org/x/net/context".Context, *v3lockpb.LockRequest, ...grpc.CallOption) (*v3lockpb.LockResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/maintenance_client_adapter.go:28: cannot use mts2mtc literal (type *mts2mtc) as type etcdserverpb.MaintenanceClient in return argument:
	*mts2mtc does not implement etcdserverpb.MaintenanceClient (wrong type for Alarm method)
		have Alarm("context".Context, *etcdserverpb.AlarmRequest, ...grpc.CallOption) (*etcdserverpb.AlarmResponse, error)
		want Alarm("golang.org/x/net/context".Context, *etcdserverpb.AlarmRequest, ...grpc.CallOption) (*etcdserverpb.AlarmResponse, error)
../../go/src/github.com/coreos/etcd/proxy/grpcproxy/adapter/maintenance_client_adapter.go:28: too many errors
# github.com/coreos/etcd/etcdserver/etcdserverpb/gw
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:654: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:656: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:661: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:665: not enough arguments in call to forward_KV_Range_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:682: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:684: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:689: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:693: not enough arguments in call to forward_KV_Put_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:710: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:712: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/etcdserverpb/gw/rpc.pb.gw.go:712: too many errors
# github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:100: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:102: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:107: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:111: not enough arguments in call to forward_Lock_Lock_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:128: not enough arguments in call to runtime.AnnotateContext
	have ("golang.org/x/net/context".Context, *http.Request)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, *http.Request)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:130: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:135: not enough arguments in call to runtime.HTTPError
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, error)
../../go/src/github.com/coreos/etcd/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go:139: not enough arguments in call to forward_Lock_Unlock_0
	have ("golang.org/x/net/context".Context, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, []func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error...)
	want ("golang.org/x/net/context".Context, *runtime.ServeMux, runtime.Marshaler, http.ResponseWriter, *http.Request, proto.Message, ...func("golang.org/x/net/context".Context, http.ResponseWriter, proto.Message) error)

**Comment by gyuho** [comment]
Try

```
go get -v -u -d golang.org/x/net/...
go get -v -u -d github.com/coreos/etcd/clientv3/...
```

With Go 1.9

**Comment by yuchao86** [comment]
thanks , I 'm upgrade my golang from 1.8 to 1.9, then build successful.
