### ISSUE TITLE
Best way to upgrade etcd

### ISSUE THREAD

**Issue by vbmade2000** [coreos/etcd#8633]
# Bug reporting

A good bug report has some very specific qualities, so please read over our short document on [reporting bugs][report_bugs] before submitting a bug report.

To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

What is the proper way to upgrade etcd2 to etcd3 in CoreOS ?
I know this may not be the right place to ask such question but I tried coreos irc and etcd kubernetes channel and didn't get any reply.

**Comment by xiang90** [comment]
this documentation might help: https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md

we do not have container linux specific documentation at the moment.

**Comment by vbmade2000** [comment]
@xiang90 Thanks but the documentation contained in url you mentioned doesn't provide adequate guidance. Is there any place I can get help from ?

**Comment by gyuho** [comment]
Also see https://github.com/coreos/etcd/blob/master/Documentation/platforms/container-linux-systemd.md for Container Linux specific docs.

**Comment by vbmade2000** [comment]
Thanks @gyuho. Links was useful.
