### ISSUE TITLE
etcd using docker compose

### ISSUE THREAD

**Issue by craigivy** [coreos/etcd#8646]
I was wonder if you can help me with the best deployment strategy using docker compose.  A couple of requirements we have is to not mount a  file system.  We have small amounts of data so I'm hoping the replication is not a big issue.  Also we want it automated as possible if an etcd node goes down we would like it to join the cluster without any manual steps.  

The issue I'm having right now is when a docker etcd service restarts its unable to join the cluster as it thinks its a new node but really its an existing node.  I'm seeing the error "2017-10-05 04:30:18.692907 C | etcdmain: member 67336ef57b58b19d has already been bootstrapped"  which I understand but am wonder how I can support a docker compose automated deployment that handles restarts of etcd services.  Here is my compose project file https://github.com/craigivy/etcd-compose.  

Any docker compose deployment samples or ideas appreciated.

**Comment by gyuho** [comment]
> 2017-10-05 04:30:18.692907 C | etcdmain: member 67336ef57b58b19d has already been bootstrapped

means cluster had booted before, and now trying to restart from old data directory on disk. Try cleaning up data directories, if you start fresh cluster.

And we do not run docker compose to set up etcd cluster.
There are many other ways: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md and http://play.etcd.io/install.
