### ISSUE TITLE
SSL Config - Docker

### ISSUE THREAD

**Issue by bhujangr** [coreos/etcd#8667]
To ask a question, go ahead and ignore this.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md
Hi, have been trying to setup SSL in a Docker container and etcdctl fails to connect to etcd as the connection is closed on the server side. The very same set of configs when run natively on a Mac, everything works perfectly fine, am sure am missing something w.r.t. Docker, any help would be great.

To test things out, am generating the certs, as detailed [here](https://coreos.com/os/docs/latest/generate-self-signed-certificates.html)

When run natively
``` 
etcd-v3.2.7-darwin-amd64/etcd --name infra0 --data-dir infra0 \
--cert-file=/etc/cfssl/server.pem \
--key-file=/etc/cfssl/server-key.pem \
--advertise-client-urls=https://127.0.0.1:2379 \
--listen-client-urls=https://127.0.0.1:2379 --debug
```

^^ works perfectly fine, when trying to connect to the instance via etcdctl
```
etcd-v3.2.7-darwin-amd64/etcdctl --endpoints=https://localhost:2379 --cacert=/etc/cfssl/ca.pem put test test
```

However if I try to the same within a docker container:
```
docker run --name etcd -p 2379:2379 \
-v /etc/cfssl/server.pem:/etc/ssl/server.pem \
-v /etc/cfssl/server-key.pem:/etc/ssl/server-key.pem \
quay.io/coreos/etcd:v3.2.7 \
/usr/local/bin/etcd \
--cert-file=/etc/ssl/server.pem \
--key-file=/etc/ssl/server-key.pem \
--advertise-client-urls=https://127.0.0.1:2379 \
--listen-client-urls=https://127.0.0.1:2379 \
--debug
```

Testing the above via etcdctl results in errors of the form
```
grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: EOF"; Reconnecting to {localhost:2379 <nil>}
grpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: EOF"; Reconnecting to {localhost:2379 <nil>}
grpc: Failed to dial localhost:2379: context canceled; please retry.
```

I can confirm that I am able to reach localhost:2379, however for some reason the connection is abruptly closed.

**Comment by gyuho** [comment]
Try using `0.0.0.0` for Docker container?

**Comment by bhujangr** [comment]
@gyuho Oh yeah, forgot about that, yes that helps. Will close this issue.
