### ISSUE TITLE
Unknown field `NoFreelistSync`

### ISSUE THREAD

**Issue by olivere** [coreos/etcd#8692]
We are using the current master branch of `etcd` vendored with dep and keep getting an error when running our test suite with Linux.

```
go test -v -tags integration $(go list ./... | grep -v 'vendor\|kubernetes')
# github.com/xxx/yyy/vendor/github.com/coreos/etcd/mvcc/backend
vendor/github.com/coreos/etcd/mvcc/backend/config_linux.go:31:16: unknown field 'NoFreelistSync' in struct literal of type bolt.Options
```

We tried to switch back to 3.2.9, but unfortunately that yields in a different error due to breaking changes in grpc-go 1.6.0:

```
# github.com/xxx/yyy/vendor/github.com/coreos/etcd/clientv3
vendor/github.com/coreos/etcd/clientv3/client.go:336:9: undefined: metadata.NewContext
vendor/github.com/coreos/etcd/clientv3/lease.go:326:14: undefined: metadata.FromContext
# github.com/xxx/yyy/vendor/github.com/coreos/etcd/auth
vendor/github.com/coreos/etcd/auth/store.go:995:12: undefined: metadata.FromContext
```

Now we're stuck and only have the chance to choose between the two errors :-)

We have tried to get dep vendor the correct version of `github.com/coreos/bbolt` (which has the `NoFreelistSync`), but we're unsuccessful yet.

Is there anything we can do here?

**Comment by gyuho** [comment]
> We are using the current master branch of etcd

Did you vendor exactly the way we do here https://github.com/coreos/etcd/blob/master/glide.yaml#L7?

I've also tried `dep` for etcd, but don't think it's production-ready yet.

**Comment by olivere** [comment]
Aha! I will try that. Thank you! Will re-open if that won't work.

Re `dep`: They state [here](https://github.com/golang/dep#current-status) that they're production ready, and we're using it for ~2 months and didn't see any real issues besides being a bit slow when updating dependencies. But that's a known issue being worked on.

**Comment by xiang90** [comment]
@olivere it would be great if you can explore if `dep` works for etcd, and maybe send a pr to demonstrate that. thank you.

**Comment by gyuho** [comment]
@olivere Ok that's great to know 👍  If you're interested, https://github.com/coreos/etcd/issues/7225.

**Comment by olivere** [comment]
Hmm... that didn't do the trick with `dep` at least. But TBH I'm not sure if that's a problem with `dep` as it's trying to get `github.com/boltdb/bolt` instead of your fork at `github.com/coreos/bbolot` when I initialize with `dep init`, which finds and uses your Glide configuration (see my comment on #7225).

**Comment by olivere** [comment]
Ah, I was wrong. I didn't update from upstream. Will update my findings in #7225.
