### ISSUE TITLE
Earlier revisions are replayed in watchers with start_revision

### ISSUE THREAD

**Issue by connor4312** [coreos/etcd#8699]
I noticed this happening _sometimes_ in my unit tests for the Node etcdv3 library.

I make a watch request like this:

```js
{
  "progress_notify": true,
  "key": "foo",
  "start_revision": "489"
}
```

Then, on the stream, I immediately get notified of a put with a previous revision:

```js
{
  "key": "foo",
  "create_revision": "488",
  "mod_revision": "488",
  "version": "1",
  "value": "bar",
  "lease": "0"
}
```

One example of this happening can be found in [this Travis build](https://travis-ci.org/mixer/etcd3/jobs/288401433). [This](https://github.com/mixer/etcd3/blob/bcf75e1a44eeeab89f1e0e9b10f9617d667c255d/test/watch.test.ts#L63-L83) is the code that causes it.

Is this by design, or is it a potential bug in etcd?

**Comment by xiang90** [comment]
seems like a bug. can you try etcdctl or clientv3 to reproduce this?

**Comment by xiang90** [comment]
@connor4312 kindly ping.

/cc @jpbetz can you help on this one?

**Comment by jpbetz** [comment]
Yeah, I can take this one.

**Comment by connor4312** [comment]
Yep, I'll try to get a standalone repro on the clientv3 this wekeend

**Comment by connor4312** [comment]
After further investigation, this look like it's a bug on my end. Sorry for the noise! 😄

**Comment by jpbetz** [comment]
Thanks for following up @connor4312
