### ISSUE TITLE
Problem Running etcd docker image  

### ISSUE THREAD

**Issue by bhaveshj21** [coreos/etcd#8700]
Hi, 
wrt [issue](https://github.com/coreos/etcd/issues/8647 ) I have pulled a released image from your repository, I have deployed it in our DC/OS cluster and trying to query it through http like 
var options = {
    host: etcd_host,
    port: etcd_port,
    path: encoded_url,
    method: 'GET'
  };
so While connecting I am getting this error connect ECONNREFUSED 11.189.99.233:2379
I talked the my support team so he told me that container is trying to connect to something which we don't expose and this IP is not in our cidrs, is it something to do with the image , how can make etcd to run on the DC/OS cluster.

**Comment by gyuho** [comment]
> I talked the my support team so he told me that container is trying to connect to something which we don't expose and this IP is not in our cidrs, is it something to do with the image , how can make etcd to run on the DC/OS cluster.

This has nothing to do with etcd. Docker community or DC/OS should have better answer?
