### ISSUE TITLE
invoke grpc naming by balance

### ISSUE THREAD

**Issue by koko990** [coreos/etcd#8701]
# Bug reporting
there is a error in invoke service by balance like grpc_naming.md: 
etcd/Documentation/dev-guide/grpc_naming.md:
```go
import (
	"github.com/coreos/etcd/clientv3"
	etcdnaming "github.com/coreos/etcd/clientv3/naming"

	"google.golang.org/grpc"
)

...

cli, cerr := clientv3.NewFromURL("http://localhost:2379")
r := &etcdnaming.GRPCResolver{Client: cli}
b := grpc.RoundRobin(r)
conn, gerr := grpc.Dial("my-service", grpc.WithBalancer(b))
```
sometimes occurrs error as 
```
rpc error: code = Unavailable desc = there is no address available
```
After the experiment, the call must add a block as below 
```
grpc.Dial("my-service", grpc.WithBalancer(b),grpc.WithBlock())
```
so it's better to fix the description file, grpc_naming.md

**Comment by gyuho** [comment]
You can just pass `DialTimeout > 0` in your client configuration, and that will block until first connection. Also if you can improve our docs, it would be great. Thanks!

**Comment by koko990** [comment]
ok, there is a pr #8703
