### ISSUE TITLE
v3 benchmark tool won't ask for password

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8706]
when use `--user` flag and only give a username, it won't ask for password. So I must write password into cmd, it is not safe. I think it is.

**Comment by gyuho** [comment]
Which command? `benchmark` or `check perf`?

**Comment by zyf0330** [comment]
oh, it is `benchmark` , build from `tools/benchmark/main.go`

**Comment by xiang90** [comment]
this tool is mainly designed for debugging and performance testing. 

supporting user/pw is a super low priority right now. if you are interested, you can contribute to this feature.

**Comment by zyf0330** [comment]
When I have enough ability, I will.😆

**Comment by xiang90** [comment]
fixed by #8712
