### ISSUE TITLE
etcd out of service

### ISSUE THREAD

**Issue by featheryus** [coreos/etcd#8707]
# Bug reporting

There is a process exit due to etcd out of service.
If it always failed when operate etcd, it will restart to recover.
But my question is that why etcd out of service.
around Oct 17 14:50:48, it seems that etcd go wrong.
For etcd log, please refer to the attachment.

Thanks.

```
14:50:21.072291 node-0 etcd[905]: the clock difference against peer 311797de1182985c is too high [1.015379231s > 1s]
14:50:48.972417 node-0 process_etcd_user[1703]: fceef700:_send_cluster_request__r:520: send db request failed msg=etcd_cluster_request: all cluster servers failed. last error: Timeout was reached,cause=v2/keys/etcd_user/supervision/mn-0/etcd?quorum=true.
```

[etcd.log](https://github.com/coreos/etcd/files/1393690/etcd.log)

**Comment by featheryus** [comment]
For this case, there is 3 instance node, they are  node-0, node-1, snode-2
In all the three node , process_etcd_user running and doing supervision for etcd every 15s.
If etcd out of service, it will report warning as below.

> 14:50:21.072291 node-0 etcd[905]: the clock difference against peer 311797de1182985c is too high [1.015379231s > 1s]
> Oct 17 14:50:36.222409 node-0 process_etcd_user[1703]: fceef700:etcd_supervision_thread__r:82: dhadb get etcd supervison key failed with 0xe108.
> Oct 17 14:50:49.347911 node-0 etcd[905]: apply entries took too long [305.876478ms for 1 entries]

In other 2 instance node, there is no such supervision failure from process_etcd_user.

Please help to check.
Thanks.
attach full log



[etcd_node_0.log](https://github.com/coreos/etcd/files/1400727/etcd_node_0.log)
[etcd_node_1.log](https://github.com/coreos/etcd/files/1400728/etcd_node_1.log)
[etcd_snode_2.log](https://github.com/coreos/etcd/files/1400729/etcd_snode_2.log)

**Comment by gyuho** [comment]
> apply entries took too long

Your cluster is either overloaded or just being slow from slow disks. So it can trigger leader elections.

**Comment by featheryus** [comment]
What's the meaning of "avoid queries with large range/delete range!"
Do you think it's similar with #8722
Thanks.

**Comment by gyuho** [comment]
It means request was taking long time to process, or cluster is overloaded. Please check your `/metrics`.

**Comment by gyuho** [comment]
@featheryus Ping?

**Comment by gyuho** [comment]
Please reopen if any more help is needed.
