### ISSUE TITLE
ask about dial-timeout and real took time

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8708]
In one of my client, I run `etcdctl endpoint  health` and get `took = 803.998451ms` just with flag `--dial-timeout 3s`. And if this flag is default `2s`, result is `is unhealthy: failed to connect: context deadline exceeded`.
So I want to ask what is the relation of this time from `took` and dial-timeout?

**Comment by gyuho** [comment]
We do not count the dial time for initial client connection. `took` means the time it takes to send `Range` RPC and receive response from the server.

https://github.com/coreos/etcd/blob/f83ac2541213021eb7848d188513461a162edd05/etcdctl/ctlv3/command/ep_command.go#L104-L117

**Comment by zyf0330** [comment]
I know.
So `*cfg` of `cli, err := v3.New(*cfg)` is related to `--dial-timeout`, and if it takes more time than it to connect to etcd, it gives `fail to connect` error info.
