### ISSUE TITLE
Renew lease

### ISSUE THREAD

**Issue by marcovc** [coreos/etcd#8719]
This is a question, not a bug.

I have the following workflow (in pseudo code):
    
    while true
        lease = etcdctl lease grant ttl
        if test
            etcdctl put --lease=lease key value
        else
            etcdctl del key
        endif
        sleep ttl/2

The idea is to have a key in the etcd2 meaning that a periodic test succeeds. The ttl exists to ensure that if the program is interrupted the key is cleared. 

My ttl is small (like 5 seconds),  meaning that I'm creating a new lease every 5 seconds. This seems to be hurting the etcd2 cluster performance, so I'm guessing this is not the intended use of leases.

What I would like to do is more like:

    lease = etcdctl lease grant ttl
    while true
        if test
            etcdctl put --lease=lease key value
        else
            etcdctl del key
        endif
        sleep ttl/2
        etcdctl renew lease <--- this would reset the lease ttl to the original value

But I can't find a command for renewing the lease. Also, I'm aware of the keepalive command, but I don't know how to use that with a test.

Can anyone point me in the right direction please?

Thanks!
Marco

**Comment by xiang90** [comment]
keepalive is a blocking call. probably you want something like `keepalive --once`, which only sends one renew call?

**Comment by marcovc** [comment]
Yes, that would work. It is not there yet, right?

**Comment by xiang90** [comment]
@marcovc no it is not. would like to help to add the feature?

**Comment by marcovc** [comment]
Sure, I'll do it. Thanks

**Comment by marcovc** [comment]
@xiang90, here is my attempt at this: 

https://github.com/coreos/etcd/pull/8775

Never wrote go code before, so please look at it twice.

Thanks

**Comment by xiang90** [comment]
@marcovc thanks for the contribution. and go is really easy to get started :P

**Comment by marcovc** [comment]
Thank you for all the work. This was a simple one 😊
