### ISSUE TITLE
etcd service failed due to sync duration?

### ISSUE THREAD

**Issue by featheryus** [coreos/etcd#8722]
Here is another case related etcd failed. From the log I'm not sure if it same with #8707. So I report a new issue and upload all related log to make them clear.
Maybe it's similar issue, but different scenario and new log may give you new view to trace the issue.
Thanks.

Also there are three instance node, node-0, node-1, snode-2
process_etcd_user running in all three instance node.
it is an user of etcd, it will supervise the etcd service. if it can't access etcd for a while. It will trigger node reboot to recover.

The problem is that , when restart the whole cluster ( node-1, node-1, snode-2), the etcd service work unstable.

> Oct 20 10:58:14 node-0 tipc_node_get_node[1162]: set value into etcd failed: 58632 (**etcd can't work**)
> Oct 20 10:58:15 node-0 tipc_node_get_node[1162]: Node id 1 successfully assigned to node-0(**etcd works**)
> Oct 20 10:58:29 node-0 etcd[911]: sync duration of 1.034111027s, expected less than 1s
> Oct 20 10:58:29 node-0 process_etcd_user[1976]: 52489700:_send_request__r:346: curl_easy_perform send request to etcd by url=http://127.0.0.1:2379/v2/keys/dha/supervision/node-0/etcd?quorum=true failed, curl ret=28 ( **etcd not works**)

attach all the log.
[etcd_node_0.log](https://github.com/coreos/etcd/files/1400987/etcd_node_0.log)
[etcd_node_1.log](https://github.com/coreos/etcd/files/1400988/etcd_node_1.log)
[etcd_snode_2.log](https://github.com/coreos/etcd/files/1400989/etcd_snode_2.log)

**Comment by gyuho** [comment]
```
sync duration of ...
```

Means fsyncs are taking longer than it should in your machine. This possibly leads to leader elections, making the cluster unavailable.

**Comment by featheryus** [comment]
Then, do you have any suggestion to avoid such problem.
Except the slow disk, is there any other possible reason to trigger such problem.
BTW, we use SSD in our system.
Thanks.

**Comment by gyuho** [comment]
etcd cluster could be overloaded. Do you have output of `/metrics`?

**Comment by gyuho** [comment]
Please inspect `/metrics` output with https://github.com/coreos/etcd/blob/master/Documentation/op-guide/monitoring.md.

And reopen if you still think it's an etcd issue.
