### ISSUE TITLE
Shouldn't save the snapshot index AFTER saving the sapshot?

### ISSUE THREAD

**Issue by libreoscar** [coreos/etcd#8730]
https://github.com/coreos/etcd/blob/ebc09b114970b5ab1faf1b3db9f146b25c95ab96/etcdserver/storage.go#L55
https://github.com/coreos/etcd/blob/ebc09b114970b5ab1faf1b3db9f146b25c95ab96/contrib/raftexample/raft.go#L109

Shouldn't save the snapshot index AFTER saving the snapshot? What if the process aborts between `WAL.SaveSnapshot()` and `Snapshotter.SaveSnap`?

**Comment by xiang90** [comment]
In the case you described, etcd will start with a previous snapshot, and continue to read though WAL.
