### ISSUE TITLE
 connection error: desc = "transport: tls: server selected unsupported protocol version 301"; please retry.

### ISSUE THREAD

**Issue by zzq392342084** [coreos/etcd#8733]
# Bug reporting

 ETCDCTL_API=3 etcdctl 
  --cacert=source/etcd/etc/etcd/ssl/ca.pem 
--cert=source/etcd/etc/etcd/ssl/etcd.pem 
--key=source/etcd/etc/etcd/ssl/etcd-key.pem  
--endpoints=https://192.168.89.210:2379 
--write-out=protobuf 
put /esn.com/network/config '{"Network":"172.30.0.0/16","SubnetLen":25,"Backend":{"Type":"vxlan"}}' 

the above output:
     Failed to dial 192.168.89.210:2379: connection error: desc = "transport: tls: server selected unsupported protocol version 301"; please retry

****when try " curl https://192.168.89.210:2379/v2/memebers ":****
 curl: (60) Peer's certificate issuer has been marked as not trusted by the user.
 More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

I need run "curl -k https://192.168.89.210:2379/v2/members"

I think etcdctl has something related to curl ,but I do not know what is wrong

**Comment by gyuho** [comment]
You have to pass certs flags to `curl` as well.

Something like `curl --cacert /path/to/ca.crt https://127.0.0.1:2379/v2/keys/foo -XPUT -d value=bar -v`

**Comment by xiang90** [comment]
closing this. this is not an etcd issue. you need to pass in cert as @gyuho said, or you need to ignore checking like what you does with `-k`.
