### ISSUE TITLE
How to minimize etcd ?

### ISSUE THREAD

**Issue by socketpair** [coreos/etcd#8744]
I need to use etcd in embedded environment. So I want to minimize it's binary. How does this can be achieved ?

For example, I do not need V2 API, and maybe some other features. Is there any configuration like `make menuconfig` ? maybe strip binary somehow and/or compile it with size minimisation like gcc's `-Os`.

Please give me advise how to do that.

**Comment by xiang90** [comment]
probably you need to search about about minimizing go binary by stripping symbol table etc.. but i am not sure how much you can achieve. 

for us, this is not going to be a priority anytime soon. if you wish to do it, you have to do your own research, and come up with a proposal to push it forward.

**Comment by socketpair** [comment]
@xiang90 You did not answer about ability to switch off some features during compilation. Is it possible ? What you recommend for that ?

**Comment by xiang90** [comment]
@socketpair it is possible by providing build tags to etcd/golang. but we do not provide that feature currently.
