### ISSUE TITLE
Is the order of replies to watch requests strict ?

### ISSUE THREAD

**Issue by socketpair** [coreos/etcd#8745]
i.e. if I pass multiple watch requests in same http/2 stream, is the order of replies guarantied ?

Answer to this question must be highlited in documentation. It is very important for getting right `watch_id` for each request if watches are created in parallel.

**Comment by xiang90** [comment]
i am not exactly sure what do you mean. can you clarify?

**Comment by socketpair** [comment]
Etcd watch API requires us to use stream-steram GRPC API. This mean that creation of two watchers will look like sending two requests of watcher creation in SINGLE http/2 stream. After that, two responses (about successful watcher creation) will be sent by etcd inside that HTTP/2 stream. I'm asking about order of these replies. I'm asking if order of replies strictly match order of requests. In other words, is it possible to have next situation:

```
-> create watch on key "xxx"
-> create watch on key "yyy"
<- watch on "yyy" created with watch_id=2
<- watch on "xxx" created with watch_id=1
```

or even worse (note different order of watch_id)

```
-> create watch on key "xxx"
-> create watch on key "yyy"
<- watch on "yyy" created with watch_id=1
<- watch on "xxx" created with watch_id=2
```

**Comment by xiang90** [comment]
the current implementation does guarantee about this ordering. however, it might change later on.

what we suggested is to create watch one by one none concurrently, or wait for https://github.com/coreos/etcd/pull/8662 to land.

**Comment by socketpair** [comment]
Please reopen issue. This fact must be specified in documentation.

**Comment by xiang90** [comment]
where in the doc says the ordering is guaranteed? 

https://github.com/coreos/etcd/pull/8662 is well covered the fact. if you think the doc needs to be improved, please open an issue/pr to fix it. thank you.

**Comment by socketpair** [comment]
docs does not say anything about order. Why not to fix docs (specify that order is strict) using this issue number ?

**Comment by xiang90** [comment]
the doc improvement is here: https://github.com/coreos/etcd/pull/8662/files#diff-c60cc9a0d9c8fe4cdedc8b5944475568R676

i am not sure what you want. i would suggest you to read through the issue i provided, and the pr to fix it. if you need anything more, make a pr.
