### ISSUE TITLE
clientv3: no way to control some of the outputted logs 

### ISSUE THREAD

**Issue by mthenw** [coreos/etcd#8778]
# Bug reporting

I'm using etcd (via [libkv](https://github.com/abronan/libkv)) in my service. The issue is that even though I set logging level to CRITICAL

```
etcdLogger, err := capnslog.GetRepoLogger("github.com/coreos/etcd")
...
etcdLogger.SetRepoLogLevel(capnslog.CRITICAL)
```

I still see following messages in the console when my service is not able to connect to etcd node

```
 I | etcdserver/api/v3rpc: grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:2379: getsockopt: connection refused"; Reconnecting to {127.0.0.1:2379 <nil>}
```

Is there a way to control/silence those messages? In general, is there a way to control log messages produced by etcd internally? If I use etcd client I think I should be able to control that and etcd client shouldn't log anything directly to stdout/stderr. 

etcd version: v3.2.9

**Comment by mthenw** [comment]
Looks like the culprit is https://github.com/grpc/grpc-go/issues/1044 so I guess the solution is to update the dependency(?)

**Comment by gyuho** [comment]
Can you try setting `grpclog.SetLoggerV2(grpclog.NewLoggerV2(ioutil.Discard, ioutil.Discard, ioutil.Discard))` to silent grpc logs?

**Comment by mthenw** [comment]
That works, thanks!
