### ISSUE TITLE
Member reported healthy even if it has wrong cluster id

### ISSUE THREAD

**Issue by cristifalcas** [coreos/etcd#8788]
Scenario:

* cluster created with 3 members (A, B, C). Get health for endpoint B from member A: 

    is healthy: successfully committed proposal: took = 2.800791ms

* removing the data-dir from from member B. Get health for endpoint B from member A: 

    Error from server: error dialing backend: dial tcp 172.19.40.136:10250: getsockopt: connection refused

* restart member B with the same etcd configuration as previous (this will recreate the data-dir for a new cluster). Get health for endpoint B from member A: 

    is healthy: successfully committed proposal: took = 525.325046ms

But, at this point, member B throws those errors (which are correct):

    2017-10-30 12:01:01.903417 E | rafthttp: request cluster ID mismatch (got 5a60902085be31f6 want cdf818194e3a8c32)

So why is the cluster reporting the member as healthy? Even if it's clearing not part of the cluster anymore?

Thank you

**Comment by gyuho** [comment]
> Get health for endpoint B from member A:

What was the etcdctl command to get this? Or did you just fetch `/health`?

**Comment by gyuho** [comment]
@cristifalcas Ping?

**Comment by cristifalcas** [comment]
The command is:

    SSL_OPTS="--cacert=/etc/kubernetes/pki/ca.crt --cert=/etc/kubernetes/pki/client.crt --key=/etc/kubernetes/pki/client-key.pem --endpoints=$(hostname):2379"
    ETCDCTL_API=3 etcdctl $SSL_OPTS endpoint health

**Comment by cristifalcas** [comment]
etcd is inside a kubernetes pod with hostnetwork

**Comment by xiang90** [comment]
endpoint healthy is to check the health of the endpoint, not the cluster. if you get health response from A, it means A is healthy not B.

**Comment by cristifalcas** [comment]
Do I have any possibility to check if a member is accepted in a cluster? Now I'm parsing the logs for errors.

For example if a new machine is added with the same hostname in an existing cluster.
