### ISSUE TITLE
network delay on leader, get from follower also delay

### ISSUE THREAD

**Issue by YuleiXiao** [coreos/etcd#8794]
Three etcd nodes ABC, A is leader with election-timeout=5s. 
Set the network delay 2s on the leader node. 
Get kv from B,C with ``` ---endpoints=B,C```. 
It was expected that there should be no delay, but delay still exist. 
The smallest timeout value is ```--command-timeout=5s``` and ```--dial-timeout=5s``` to get success.
Why get from follower also delay?

**Comment by xiang90** [comment]
by default, etcd3 read is linearizable. It depends on the leader. You can switch to a local read with an option.
