### ISSUE TITLE
Documentation: alert for grpc related methods is outdated

### ISSUE THREAD

**Issue by dqminh** [coreos/etcd#8802]
With commit https://github.com/coreos/etcd/commit/5e810e30ccb42a36b24e933c09177b575e6494e6, etcd defers to go-gprc-prometheus to set up prometheus metrics.

The new prometheus metrics are like:

```
grpc_server_handled_total{grpc_code="OK", grpc_type="unary"}
```

But alerts refenrence guide is still using old metrics:

```
IF sum by(grpc_method) (rate(etcd_grpc_requests_failed_total{job="etcd"}[5m]))
  / sum by(grpc_method) (rate(etcd_grpc_total{job="etcd"}[5m])) > 0.01

IF histogram_quantile(0.99, rate(etcd_grpc_unary_requests_duration_seconds_bucket[5m])) > 0.15
```

We should update the reference guide to use new prometheus metrics instead.

cc @gyuho @brancz

**Comment by gyuho** [comment]
Closing via https://github.com/coreos/etcd/pull/8879.
