### ISSUE TITLE
Support v2 exec-watch in v3 etcdctl

### ISSUE THREAD

**Issue by wwyiwzhang** [coreos/etcd#8814]
Hi there,
I cannot use `exec-watch` in etcdctl api v3. 
I wonder if it is going to be added as a feature soon or is there a command that can substitute it in v3?

Thanks!

**Comment by gyuho** [comment]
What's your use case? We don't have `exec-watch` command for v3, and no plan yet.

If you use v3 lock command, we have something similar

https://github.com/coreos/etcd/blob/b65435b86d80fd3e71c6411832e8cc7eb8fb8b44/etcdctl/ctlv3/command/lock_command.go#L34-L37

**Comment by wwyiwzhang** [comment]
In API *v2*, I can do something like,
`etcdctl  --no-sync --endpoints ${ENDPOINTS} exec-watch --recursive /${prefix} -- sh -c 'python <name of the script> -a "$ETCD_WATCH_ACTION" -ck "$ETCD_WATCH_KEY" -cv "$ETCD_WATCH_VALUE"`
How can I replicate in API *v3*?

**Comment by wwyiwzhang** [comment]
Based on the offline chat, I think `etcd watch` seems to be the only option. 
I am trying to replicate this, 
`etcdctl --no-sync --endpoints ${ENDPOINTS} exec-watch --recursive /${prefix} -- sh -c 'python <name of the script> -a "$ETCD_WATCH_ACTION" -ck "$ETCD_WATCH_KEY" -cv "$ETCD_WATCH_VALUE"` in API v2
using API v3.
We reply on `exec-watch` to trigger events for the downstream applications. Could you provide any workaround or ideas?

**Comment by pldmgg** [comment]
Any news on this? From @wwyiwzhang 's comment, it seems like we use v2's `exec-watch` similarly.

I'm not sure I quite follow the `lock` example either...

**Comment by gyuho** [comment]
@pldmgg Currently, we don't have bandwidth to add this feature. Contributions are welcome!

**Comment by jiaxuanzhou** [comment]
@xiang90 I will effort on it

**Comment by gyuho** [comment]
@jiaxuanzhou Can you try https://github.com/coreos/etcd/pull/8919? Thanks!
