### ISSUE TITLE
etcd client v3 golang - how to get endpoint when receiving new event from in watcher

### ISSUE THREAD

**Issue by namgivu** [coreos/etcd#8827]
When using  watcher of etcd client v3, how can we know from which endpoint the message/event is coming from?
I have [google search](https://www.google.com.vn/search?newwindow=1&ei=MWgBWqbNHaWUvQTy24PQBg&q=etcd+client+v3+golang+-+how+to+get+endpoint+when+receiving+new+event+from+in+watcher&oq=etcd+client+v3+golang+-+how+to+get+endpoint+when+receiving+new+event+from+in+watcher&gs_l=psy-ab.3...1352254.1352254.0.1352720.1.1.0.0.0.0.122.122.0j1.1.0....0...1.1.64.psy-ab..0.0.0....0.4yPfXLsrW-4) for this though found it little helpful.

**Comment by gyuho** [comment]
Watch event is PUT, DELETE, etc., which means the entry has already been persisted in majority of nodes. It doesn't matter which node has the data or not. If you're talking about which node the client is connected to(endpoint pin), you have to enable client debug logging (for our current clientv3 master branch)

> clientv3.SetLogger(grpclog.NewLoggerV2WithVerbosity(os.Stderr, os.Stderr, os.Stderr, 4))
