### ISSUE TITLE
Raft EventListener for state change?

### ISSUE THREAD

**Issue by zhenkai** [coreos/etcd#8836]
We would like to do some prep when a node becomes leader and clean up when it loses leader status. It seems it's not possible to listen for raft role change event (e.g. become leader) now. 

Looking at the code, it seems it won't require lots of change to add an EventListener. Is there any concern on adding this support? 

(EventListener callbacks would be invoked from the actual goroutine where the event occurs and should not run for an extended period of time before return).

**Comment by xiang90** [comment]
what is eventListener? probably you reported to wrong repo?

etcd/raft will return a ready state when anything is changed. so "listening" changes is supported.

**Comment by zhenkai** [comment]
@xiang90 

Sorry for the confusion. There is no event listener yet. I was asking if there is any concern in adding one.

Yes, reading from Ready() is one way, but there is a lag because the actual state change could happen while the user code is processing previous `Ready`. Unless the user code was polling `Status`, it has to wait until next `Ready` to find out the change.

In `raft.go` there is already some methods for state transition, e.g. `func (r *raft) becomeLeader()`, `func (r *raft) becomeFollower(term uint64, lead uint64)`, etc. I was thinking if it is ok for users to pass in callbacks to be invoked in these state transition methods. E.g. `OnBecomeLeader()` would be invoked in `func (r *raft) becomeLeader()`. This way, even if processing `Ready` took a long time in user code, the state transition would be notified immediately.

**Comment by xiang90** [comment]
we do not have any plan to add the callback you described. 

why do you want to have the push-style hook? what is your use case?

**Comment by zhenkai** [comment]
We have a use case where we want a node to stop processing requests if it steps down from leader.  Slight delay in the notification of `leader->follower` transition is ok, but our code can't handle the case where the delay is comparable to the election timeout (which may happen in pathological case where `Ready` processing takes very long due to, e.g., write stall in storage engine). Also we'd like to do some prep when a node becomes leader, and the code could be simplified if an immediate notification could be obtained.

I'd be happy to send a PR if you're ok with this push-style hook.

**Comment by xiang90** [comment]
I think you should fix your code by processing io in another routine. Or create another routine to pull status. I do not like the idea to introduce callback into raft. Pushing state change into a no blocking chan might be ok, but I am not a fan either.

**Comment by xiang90** [comment]
@zhenkai can you explain why this is closed? or this might confuse other people who watches this issue. does the suggestion we have work for you? or you figured out a better solution?

**Comment by zhenkai** [comment]
Yea, we can use the polling method as work around. Although it would be convenient for us to have callbacks, I don't have strong arguments to push for it given that you think this doesn't fit well with current raft design, and I'm not sure how general this use case is. 

Thanks for the quick response.

**Comment by zhenkai** [comment]
Yea, we can use the polling method as work around. Although it would be convenient for us to have callbacks, I don't have strong arguments to push for it given that you think this doesn't fit well with current raft design, and I'm not sure how general this use case is. 

Thanks for the quick response.

**Comment by xiang90** [comment]
@zhenkai OK. We can reevaluate this if polling does not work for you, or you have any concrete examples to show callback is a must. Thank you.
