### ISSUE TITLE
Upgrade grpc-gateway to 1.3

### ISSUE THREAD

**Issue by tamalsaha** [coreos/etcd#8838]
grpc-gateway just released v1.3 https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.3 . It brings some useful options around [passing headers via proxy.](https://github.com/grpc-ecosystem/grpc-gateway/issues/311) This work required changes in the generated *.gw.go code.

Some of use has a dependency on these *.gw.go files via Kubernetes. We would like to see the generator upgraded to v1.3 and hopefully also pushed to Kubernetes (v1.9?)

cc: @philips

**Comment by xiang90** [comment]
@tamalsaha would you like to send a PR?
