### ISSUE TITLE
Benchmark - Unable to compile package and dependencies

### ISSUE THREAD

**Issue by manishjindal** [coreos/etcd#8846]
I am trying to get benachmark using following command 

`go get github.com/coreos/etcd/tools/benchmark ` 

It's giving following error 

> # github.com/coreos/etcd/clientv3
/root/go/src/github.com/coreos/etcd/clientv3/client.go:331: cannot use c.tokenCred (type *authTokenCredential) as type credentials.PerRPCCredentials in argument to grpc.WithPerRPCCredentials:
        *authTokenCredential does not implement credentials.PerRPCCredentials (wrong type for GetRequestMetadata method)
                have GetRequestMetadata("context".Context, ...string) (map[string]string, error)
                want GetRequestMetadata("golang.org/x/net/context".Context, ...string) (map[string]string, error)
/root/go/src/github.com/coreos/etcd/clientv3/client.go:387: cannot use client.balancer (type *healthBalancer) as type grpc.Balancer in argument to grpc.WithBalancer:
        *healthBalancer does not implement grpc.Balancer (wrong type for Get method)
                have Get("context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)
                want Get("golang.org/x/net/context".Context, grpc.BalancerGetOptions) (grpc.Address, func(), error)

**Further i tried cloning the whole repo and build only benchmark, i am able to clone the full repo using "git clone" but again after cloning the repo if i try to build the benchmark i am getting the same error.**

**Comment by madhukarreddy2203** [comment]
Even i'm facing the same issue can you please fix it ASAP.

![image](https://user-images.githubusercontent.com/30296444/32627025-b7c3f1b0-c556-11e7-8614-fb29e86499d5.png)

**Comment by gyuho** [comment]
You need etcd's dependencies.
Have the same dependencies as etcd https://github.com/coreos/etcd/blob/master/glide.yaml in your GOPATH.

Or do

```bash
# in etcd repo root
go build -v ./cmd/tools/benchmark
```

**Comment by gyuho** [comment]
Or you can try `go get -u` to update dependencies.

**Comment by madhukarreddy2203** [comment]
Still not working .Tried  both options getting same error

**Comment by gyuho** [comment]
@madhukarreddy2203 What's the error message when you run `go build -v ./cmd/tools/benchmark`?

**Comment by madhukarreddy2203** [comment]
The same above screenshot which i posted

**Comment by gyuho** [comment]
@madhukarreddy2203 Please provide full reproducible step.

**Comment by madhukarreddy2203** [comment]
FROM golang:1.8
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN export PATH="/usr/local/go/bin:$PATH";\
go version

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH/src

# Installing bechmark tool
RUN go get github.com/coreos/etcd/tools/benchmark
WORKDIR $GOPATH/src/github.com/coreos/etcd/tools/benchmark
RUN  go build -o benchmark

#Checking if benchmark is installed
RUN benchmark  -h

# Installing hey tool
WORKDIR $GOPATH/src
RUN go get github.com/rakyll/hey
WORKDIR $GOPATH/src/github.com/rakyll/hey
RUN  go build -o hey

WORKDIR $GOPATH/src/github.com/coreos/etcd/hack/benchmark

**Comment by gyuho** [comment]
> RUN go build -o benchmark

You are not running `go build -v ./cmd/tools/benchmark` ...

**Comment by madhukarreddy2203** [comment]
@gyuho Can you fix the above dockerfile .

**Comment by gyuho** [comment]
@madhukarreddy2203 Just git clone etcd and `go build -v ./cmd/tools/benchmark` from etcd repo root.

**Comment by gyuho** [comment]
And use Go 1.9+

**Comment by madhukarreddy2203** [comment]
![image](https://user-images.githubusercontent.com/30296444/32628268-e1a5f57e-c55a-11e7-819b-e225efd76cb8.png)
 
Error for below dockerfile 
FROM golang:1.9
ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN export PATH="/usr/local/go/bin:$PATH";\
go version

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
WORKDIR $GOPATH/src

# Installing bechmark tool
RUN go get github.com/coreos/etcd

WORKDIR $GOPATH/src/github.com/coreos/etcd

RUN  go build -v ./cmd/tools/benchmark

#Checking if benchmark is installed
RUN benchmark  -h

**Comment by gyuho** [comment]
@madhukarreddy2203 Try `go install` then. `go build` just outputs binary to your working directory.

**Comment by madhukarreddy2203** [comment]
![image](https://user-images.githubusercontent.com/30296444/32632983-486a4944-c56b-11e7-85cf-ea38e6af609e.png)

**Comment by madhukarreddy2203** [comment]
@gyuho 
![image](https://user-images.githubusercontent.com/30296444/32632996-56d1377c-c56b-11e7-8b13-4d0e842725e8.png)

**Comment by gyuho** [comment]
@madhukarreddy2203 Did you try git clone and build from repo root?

**Comment by madhukarreddy2203** [comment]
FROM debian:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    curl \
    git

# Instaling golang
RUN curl -s https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz | tar -v -C /usr/local -xz

ENV GOPATH /go
ENV GOROOT /usr/local/go
ENV PATH /go/bin:/usr/local/go/bin:/usr/local/sbin/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN export PATH="/usr/local/go/bin:$PATH" \
    go version

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

WORKDIR $GOPATH/src

#Installing benchmark tool
RUN go get github.com/coreos/etcd

WORKDIR $GOPATH/src/github.com/coreos/etcd

RUN  go install -v ./cmd/tools/benchmark

RUN  go build -v ./cmd/tools/benchmark

RUN benchmark  -h
@gyuho

**Comment by madhukarreddy2203** [comment]
FROM debian:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --no-install-recommends -y \
    curl \
    git

# Instaling golang
RUN curl -s https://storage.googleapis.com/golang/go1.9.2.linux-amd64.tar.gz | tar -v -C /usr/local -xz

ENV GOPATH /go
ENV GOROOT /usr/local/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
RUN export PATH="/usr/local/go/bin:$PATH" \
    go version

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"

WORKDIR $GOPATH/src

#Installing benchmark tool
RUN go get github.com/coreos/etcd

WORKDIR $GOPATH/src/github.com/coreos/etcd

RUN  go install -v ./cmd/tools/benchmark

RUN  go build -v ./cmd/tools/benchmark

RUN benchmark  -h
@gyuho  yes i tried

**Comment by gyuho** [comment]
@madhukarreddy2203 

> RUN go get github.com/coreos/etcd

This is not git clone.
And that `gcc` error is not etcd issue.

**Comment by gyuho** [comment]
Also check https://github.com/coreos/etcd/blob/master/Dockerfile-test.
And try `make compile-with-docker-test -f ./hack/scripts-dev/Makefile` from repo root, if you need other references that work.

**Comment by madhukarreddy2203** [comment]
Finally built image..Is there any document some where to use benchmark tool. How it works.

**Comment by gyuho** [comment]
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/performance.md

**Comment by madhukarreddy2203** [comment]
Is there any other some other tool to perform some load testing on k8 etcd cluster?

**Comment by gyuho** [comment]
@madhukarreddy2203 See https://github.com/kubernetes/kubernetes/tree/master/cluster/kubemark.

**Comment by madhukarreddy2203** [comment]
I want some thing for coreos @gyuho

**Comment by madhukarreddy2203** [comment]
@gyuho And i didn't find any proper documentation how to use it.

**Comment by gyuho** [comment]
> I want some thing for coreos

I do not understand this.

And what are you trying to do with etcd, since now you are asking how to run kubernetes and kubemark, which is clearly outside of this project scope.

For kubernetes, please see https://kubernetes.io/community/.

**Comment by gyuho** [comment]
And I have some experience with running kubemark but do not want to discuss it here.

See https://github.com/kubernetes/kubernetes/tree/master/test/kubemark or ping me on kubermetes slack community.
