### ISSUE TITLE
etcdv3 client has no ErrClusterUnavailable

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#8860]
I see a problem in my product server.
When I use confd with etcdv2 go client, it often logs err info from `ErrClusterUnavailable` and **watch monitor** can resume. But when I use it with etcdv3 client, it nevers log error info, and **watch monitor** will feign death after a period of time.
Definitely there is network stability problem around server. I notice that keepalive is in master but not released, does this feature solve this problem?

**Comment by gyuho** [comment]
> etcd watch API is not meant for detecting connection issues.
You can use Session.
>
> Disconnect should be handled in client balancer layer.
We've added HTTP/2 keepalive and client balancer health checking.
Once stabilized, it will be released in v3.3.

https://github.com/coreos/etcd/issues/8615#issuecomment-332432044

**Comment by zyf0330** [comment]
I have found code about keepalive, it works indeed. Can you tell me where client balancer health checking is?

**Comment by gyuho** [comment]
https://godoc.org/github.com/coreos/etcd/clientv3#Config

Just configure `DialKeepAliveTime` and `DialKeepAliveTimeout` (available in v3.2.10)

**Comment by atinsood** [comment]
@gyuho do you mind elaborating more on `DialKeepAliveTime and DialKeepAliveTimeout` . I am still trying to understand if the client exceeds the above, then per documentation the connection will be closed, but the client never gets notified, so is the only way is to drop the old connection if still there and go from creating a new connection in retry
