### ISSUE TITLE
old K8s POD IP on peer check after etcd redeployment

### ISSUE THREAD

**Issue by juliole** [coreos/etcd#8870]
We have etcd 3.1.6 installed as k8s stateful set.
After we  uninstalled etcd,  deleted PVs and reinstalled, we got  the following error on the etcd PODs, and the error had the old POD IPs:
check for peer 110df71582ea3c23 could not connect: dial tcp 10.32.0.35:2380: getsockopt: connection refused

I had to delete the persistence folders and redeploy etcd to get it resolved. Is it the expected behavior? Does it make sense to persist K8s cluster IPs when it is not likely to be the same on redeployment?

**Comment by gyuho** [comment]
> I had to delete the persistence folders and redeploy etcd to get it resolved.

Your data is gone. If this node reboots and tries to rejoin the cluster, it should fail.
You need to manually reconfigure the cluster to add this node.

> Does it make sense to persist K8s cluster IPs when it is not likely to be the same on redeployment?

I do not understand this?

**Comment by juliole** [comment]
I had to delete the persisted data because it had information about previous POD IPs. See that the  log says "**10.32.0.35:2380: getsockopt: connection refused**", but it was not  the IP of any of the etcd pods. Why the list of pods did not get refreshed with redeployment?

Why etcd has the peer IPs and persists it when etcd is redeployed. I was expecting the list to get refreshed with the new pods or IPs get resolved  based on pod name, considering that it is a  k8s stateful set deployment and pod names are the same.

**Comment by gyuho** [comment]
> but it was not the IP of any of the etcd pods. Why the list of pods did not get refreshed with redeployment?

Are you running etcd on top of Kubernetes, as stateful sets? Still, if your pod and data are gone, you need to reconfigure the cluster to add a new pod. And this is what etcd operator does.

https://github.com/coreos/etcd-operator

**Comment by juliole** [comment]
I think the steps are not clear. Let me try to clarify:
- have a etcd stateful set controller with data on Persistent Volumes (PVs)
- uninstall the etcd stateful controller and PVs via kubectl delete
- install a new etcd stateful controller and PVs
- pods on the new controller will have "check for peer" errors because they will be checking old pods IPs that were already deleted
- My assumption is that the info (POD IPs) is saved on the PVs path and do not get refreshed when a new controller is installed. If I delete the path content before reinstalling the controller it works fine.

Is it the expected behavior?
