### ISSUE TITLE
etcdctl lock --ttl unknown flag

### ISSUE THREAD

**Issue by luomiao** [coreos/etcd#8875]
Hi,

I am trying out the ttl flag for etcdctl lock command. According to PR #8370, etcdctl should have a "--ttl" option to setup the timeout for session:
```
$ ETCDCTL_API=3 ./etcdctl lock --help
NAME:
lock - Acquires a named lock

USAGE:
etcdctl lock [exec-command arg1 arg2 ...]

OPTIONS:
--ttl=10 timeout for session
```

However after I downloaded v3.2.9 etcdctl, on either mac or linux I got the same complain of unknown flag:
```
ETCDCTL_API=3 etcdctl lock --ttl=10
Error: unknown flag: --ttl
NAME:
	lock - Acquires a named lock

USAGE:
	etcdctl lock <lockname> [exec-command arg1 arg2 ...]

GLOBAL OPTIONS:
...
```

Anyone has any idea why this flag is disappeared with v3.2.9?
I think this PR is merged into master branch in August, while 3.2.9 is released in October. Is it possible that it's not included into the latest release?

Thanks!

**Comment by gyuho** [comment]
It has not been released (ref https://github.com/coreos/etcd/pull/8370).
It will be shipped in 3.3 releases early next year.
