### ISSUE TITLE
Couldn't add new member to cluster

### ISSUE THREAD

**Issue by akd31** [coreos/etcd#8876]
etcd version 3.2.7

I have 3 node etcd cluster. One of my nodes is corrupted and I am trying to replace this. Since restart doesn't help (data is corrupted) I removed data folder then I removed the node from cluster.

I added new node to cluster via etcdctl. However, it remains unstarted on member list and when I start the node it  logs repeatedly 

E | rafthttp: failed to find member <node1Id> in cluster <clusterId>
E | rafthttp: failed to find member <node2Id> in cluster <clusterId>

How could I replace my corrupted node successfully ?

**Comment by gyuho** [comment]
How did you restart the node (the member that's being added)?

**Comment by akd31** [comment]
I cleared data folder and start with these env variables:
ETCD_NAME=etcd-2
ETCD_DATA_DIR=/var/lib/etcd-data
ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.0.0.91:32048
ETCD_ADVERTISE_CLIENT_URLS=http://10.0.0.91:31250
ETCD_INITIAL_CLUSTER=etcd-1=http://10.0.0.91:30301,etcd-2=http://10.0.0.91:32048,etcd-3=http://10.0.0.91:30575

**Comment by gyuho** [comment]
@akd31 The newly added member must be started with `--initial-cluster-state existing`

**Comment by akd31** [comment]
Thank you @gyuho It works.
