### ISSUE TITLE
The event in requested index is outdated and cleared

### ISSUE THREAD

**Issue by cumirror** [coreos/etcd#8877]
Hi,

I'm not sure this is a problem since there are some issues similarly such as:
https://github.com/coreos/etcd/pull/8240
https://github.com/coreos/etcd/issues/587

my etcd server version is 3.1.0, and Git SHA: 8ba2897, and etcd cluster has three nodes. 
 
I use etcd between several components for communication.
There are about 200~300 components which would send(use 'set' option) heartbeat to etcd cluster every two seconds, and there is a monitor who watches etcd cluster to get components' status. 

heartbeat key is like fllowing, and monitor watches '/xxx/status':
/xxx/status/componentA
/xxx/status/componentB
/xxx/status/componentC
/xxx/status/componentD
...

Then I found monitor always report an error like this:
client.Error 401: The event in requested index is outdated and cleared (the requested history has been cleared [690585115/690585114]) [690586114]
since my program will reset watcher when this occurred, but it appeared again every 20s.

my monitor startup like this: (nodeA、nodeB and nodeC belongs to the same cluster)
./monitor --etcd-servers=https://nodeA:2379,https://nodeB:2379,https://nodeC:2379

I also found when monitor only connected one node, the result was different when picked up different node.
when I connected nodeA, 401 error would appear every 20s, but when connected nodeC, error not easy to happen.
I started two monitors like this, and found different logs:
./monitor --etcd-servers=https://nodeA:2379
watch Node change:  {Key: /xxxx/status/abc, CreatedIndex: 691454528, ModifiedIndex: 691454528, TTL: 5} Index 691455527
client.Error 401: The event in requested index is outdated and cleared (the requested history has been cleared [691454530/691454529]) [691455529]

./monitor --etcd-servers=https://nodeC:2379
watch Node change:  {Key: /xxxx/status/abc, CreatedIndex: 691454528, ModifiedIndex: 691454528, TTL: 5} Index 691454615

Connected to different nodes in the same cluster, X-Etcd-Index is not the same, see  Index 691455527 and Index 691454615 (index is Response's Index filed).

why this happened, and how to fix it?

thanks

**Comment by gyuho** [comment]
We don't know what your `./monitor` script does.

Please provide full reproducible step (preferably with master branch).

**Comment by cumirror** [comment]
use watcher like this:
`
func NewClientEtcd(endpoints []string) (*ClientEtcd, error) {
	//client skip cert verify when etcd server enable https
	transport := &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, DisableKeepAlives: true}
	cfg := client.Config{
		Endpoints:               endpoints,
		Transport:               transport,
		HeaderTimeoutPerRequest: time.Second * 5,
	}
	etcdClient, err := client.New(cfg)
	if err != nil {
		return nil, err
	}
	api := client.NewKeysAPI(etcdClient)
	clientEtcd := &ClientEtcd{
		KeysAPI: api,
		Watcher: map[string]*WatchInfo{},
	}
	return clientEtcd, nil
}

func (c *ClientEtcd) AddWatch(key string, handle interface{}) {
	api := c.KeysAPI
	watcher := api.Watcher(key, &client.WatcherOptions{Recursive: true})
	ctx, cancel := context.WithCancel(context.Background())
	c.Watcher[key] = &WatchInfo{Watcher: watcher, Cancel: cancel}

	go func() {
		for {
			res, err := watcher.Next(ctx)
			if err != nil {
				glog.Errorln("Watch next failed:", reflect.TypeOf(err), err)
				switch err.(type) {
				case *client.ClusterError:
					// retry and wait for etcd cluster to recover!
					time.Sleep(time.Second * 5)
				case client.Error:
					if err.(client.Error).Code == client.ErrorCodeEventIndexCleared {
						watcher = api.Watcher(key, &client.WatcherOptions{Recursive: true})
						c.Watcher[key].Watcher = watcher
						glog.Errorln("Watch next failed: reset watcher")
					}
				default:
					// do nothing, just retry
				}
				continue
			}
			if res.Action == "set" || res.Action == "update" || res.Action == "compareAndSwap" ||
				res.Action == "delete" || res.Action == "create" || res.Action == "expire" {
				glog.V(4).Infoln("watch Node change: ", res.Node, res.Action)
				go func() {
					defer func() {
						if err := recover(); err != nil {
							glog.Errorln("handle failed: ", res.Node.Key, res.Node.Value, err)
						}
					}()
					handle.(func(key, val, action string, index uint64) error)(res.Node.Key, res.Node.Value, res.Action, res.Node.ModifiedIndex)
				}()
			} else {
				/* get/compareAndDelete */
			}
		}
	}()
}
`
endpoints is from --etcd-servers, and key is like '/xxx/status/', watch with Recursive options.
handle.(func(key, val, action string, index uint64) error)(res.Node.Key, res.Node.Value, res.Action, res.Node.ModifiedIndex)
handle do nothing, just print a log.

i have solved this promblem: classify components and put their hearbeat in different groups, then use multi-watcher each one only watch a group like group1/group2...:
'/xxx/status/group1/componentA'
'/xxx/status/group1/componentB'
'/xxx/status/group1/componentC'
'/xxx/status/group1/componentD'
'/xxx/status/group2/componentE'
'/xxx/status/group2/componentF'
'/xxx/status/group2/componentG'
'/xxx/status/group2/componentH'
...

By using multiple watchers, this problem no longer reappears. 

@gyuho i don't understand cluster's X-Etcd-Index and ModifiedIndex: what's the influencing factors of them and why the difference between them increased so quickly when watch /xxx/status/?

**Comment by gyuho** [comment]
`X-Etcd-Index` is the current index of **v2** store.

`ModifiedIndex` is the last modified index on the key update.
