### ISSUE TITLE
Cluster-health changes status every second

### ISSUE THREAD

**Issue by PleaseTakeItEasy** [coreos/etcd#8890]
We had a storage issue come up recently. It corrupted the .wal files on two hosts. This isn't product so it wasn't a big deal so I just shutdown the etcd on the one working node. On each node I deleted the directory in /var/lib/etcd called default and after the service started on all hosts. Now when I do etcd cluster-health one second it will give me an output like 
member b45eeda590aaa3de is healthy: got healthy result from http://192.168.200.106:2379
member c4fb4448dd62539f is unhealthy: got unhealthy result from http://192.168.200.105:2379
member fded82065929ad4b is healthy: got healthy result from http://192.168.200.107:2379

and the next second I could get
member b45eeda590aaa3de is healthy: got healthy result from http://192.168.200.106:2379
member c4fb4448dd62539f is healthy: got healthy result from http://192.168.200.105:2379
member fded82065929ad4b is healthy: got healthy result from http://192.168.200.107:2379

What would cause members to go from healthy to unhealthy in the matter of seconds? There are no networking issues as other services such as docker-swarm on these hosts are working as normal.

**Comment by gyuho** [comment]
Can you provide server logs?

> On each node I deleted the directory in /var/lib/etcd called default and after the service started on all hosts

How did you do this? Do you mean you stop etcd server, delete data, restart cluster?

**Comment by xiang90** [comment]
@PleaseTakeItEasy 

kindly ping.

**Comment by xiang90** [comment]
I am closing this due to low activity. What might happen is that the cluster was unstable, and the leader was flipping. Without logging, it is impossible to tell what exactly happened.
