### ISSUE TITLE
put failed with clientv3 after changed etcd serving port, error: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded

### ISSUE THREAD

**Issue by seven-eleven** [coreos/etcd#8892]
Hi, i have an etcd cluster with two node. When **i changed client port from 2379 to 4001, deleted all the files under wal directory, and reloaded the cluster**, I met the ploblem: **I cann't use clientv3 to put kye/value into etcd**!  

etcdctl input:(ETCDCTL_API=3)  
```etcdctl --endpoints=http://127.0.0.1:4001 put test3 yyyy  ```   

ectdctl output: (ETCDCTL_API=3)  
```Error:  context deadline exceeded```

journalctrl -f -u etcd:  
```etcd[8912]: grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"```  

etcd --version:  
```
etcd Version: 3.2.9
Git SHA: f1d7dd8
Go Version: go1.8.4
Go OS/Arch: linux/amd64
```  

Why it happened, and what can i do?

**Comment by seven-eleven** [comment]
Update etcd to 3.2.10, the error log is:  
```transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:4001->127.0.0.1:43715: read: connection reset by peer```

**Comment by xiang90** [comment]
> i changed client port from 2379 to 4001, deleted all the files under wal directory, and reloaded the cluster

why do you destroy the cluster? why do you expect etcd continue to work after you destroy it?

**Comment by seven-eleven** [comment]
THX @xiang90 
Clientv2 works. I can set & get key/value with v2 api in the situation.  

I just want to restart the etcd cluster. What can i do if i want to restart an etcd cluster properly?  And i will be very happy to know why this happened to v3 api.

**Comment by xiang90** [comment]
you should not remove the wal file or touch anything in the data dir.

v3 read and v2 read are different by default. v3 read will need the quorum to be available to succeed.

**Comment by Colstuwjx** [comment]
wal means write ahead log, I don't think it should maintain something about quorum or leader election etc, we can accept that 'removing wal means some data lost', but it's not reasonable that we faced broken cluster while removed the wal data.

As I known, consul has raft.json, which indicates the cluster peers, does etcd has such configuration file in wal or others?

**Comment by xiang90** [comment]
> wal means write ahead log, I don't think it should maintain something about quorum or leader election etc, we can accept that 'removing wal means some data lost', but it's not reasonable that we faced broken cluster while removed the wal data.

etcd does not allow a member to start if the wal is corrupted or a data lost is detected. That is a fundamental goal of etcd. Silent data loss is not acceptable in etcd. 

If you have different requirement, do not use etcd.
