### ISSUE TITLE
Crytical problem: type codec.encDriver has no fields or methods

### ISSUE THREAD

**Issue by NikSmith** [coreos/etcd#8903]
# Bug reporting

Hi, I'm using viper for my project, and it includes etcd.
After a recent update, it stopped working and gives an error related to etcd.

For more information:
![image](https://user-images.githubusercontent.com/6698935/33120566-82532bc2-cf83-11e7-98de-50261340c6ff.png)

**Comment by gyuho** [comment]
Please update your dependency to

https://github.com/coreos/etcd/blob/15bfc1b36162805e8a90ae747d955667870c2f95/glide.yaml#L83-L86
