### ISSUE TITLE
etcd 3.2.10 client Keepalive params

### ISSUE THREAD

**Issue by mwf** [coreos/etcd#8905]
Hi, guys :)

First of all, thanks for releasing 3.2.10! It's a huge step towards reliability and stability of etcd-based systems :) Waited so long and finally it happened!

I've made some tests of 3.2.10 release and I have several questions around it:

1. As I discovered, new 3.2.10 client with enabled DialKeepAlives works great with older servers versions - I've tested with 3.1.5. It was surprising for me, because I was sure it's gRPC stuff and the fix requires to have some minimal gRPC lib version both on client and server.
    So KeepAlive is more client-side issue and old grpc version of 3.1.5 server supports it well? Are there any known compatability issues with it? 

2. What about server configuration 
    ```
    DefaultGRPCKeepAliveMinTime  = 5 * time.Second
    ```
    It's said that if client pings server more often `too_many_pings` error is returned.
    I experimented and set `DialKeepAliveTime` to 1 sec on client, but almost nothing happened - client Watch operated well and smoothly transferred between nodes on node outage. 
    The only thing found - just 2 lines in log of 1 server for 15 minutes...
    ```
    2017-11-22 15:23:01.425657 I | etcdserver/api/v3rpc: transport: Got to too many pings from the client, closing the connection.
    2017-11-22 15:36:58.446237 I | etcdserver/api/v3rpc: transport: Got to too many pings from the client, closing the connection.
    ```

    Maybe it's painful for etcd Client to operate undercover? Just the error is not exposed anywhere?

3. What is the recommended configuration for client `DialKeepAliveTime` and `DialKeepAliveTimeout`? 
`DialKeepAliveTime = 5*time.Second` must be the minimal if talking about Server default set to 5?
    And having 5 `Time` and 5 `Timeout` will tell that totall maximum time is 10 seconds? Keepalive ping request every 5 second and 5 sec of waiting for response, and again new ping in 5 seconds? I mean is the send-wait-recieve cycle is sequential or parallel?

**Comment by gyuho** [comment]
Glad it worked :)

> So KeepAlive is more client-side issue and old grpc version of 3.1.5 server supports it well?

Keepalive ping from 3.2.10 client to 3.1.x server should work, since it's the client that keeps track of activity of streams. If it doesn't work, please let us know.

> It's said that if client pings server more often too_many_pings error is returned.

Yeah, gRPC's default limit is `keepalive.EnforcementPolicy` is 5-minute.
etcd's default 5-sec (if HTTP/2 ping is sent more than once within 5-sec, `too_many_pings`).
You can configure this with `--grpc-keepalive-min-time` flag to the v3.2.10 server.

> And having 5 Time and 5 Timeout will tell that totall maximum time is 10 seconds?

Correct, if server doesn't respond after 5-second, it will wait extra 5-second before closing the connection. If ping has arrived from server within that extra 5-second, it will proceed without closing.

**Comment by xiang90** [comment]
> Maybe it's painful for etcd Client to operate undercover?

Not sure what is the best way either. Can you raise this question in grpc-go repo? It is more a gRPC question.

**Comment by mwf** [comment]
Thanks guys!
Closing the issue then, will proceed in grpc-go.
