### ISSUE TITLE
etcd performance

### ISSUE THREAD

**Issue by yongqigood** [coreos/etcd#8906]
I created etcd cluster and a gateway which forward all request to backend etcd cluster.

My gateway is just forward request using http2 proxy.

I find that my gateway's cpu usage higher than etcd cluster's cpu usage.

I am using benchmark to test my gateway.

I think etcd should do more work(process request and do raft) than gateway.

What caused gateway's cpu usage higher than etcd's cpu usage?

**Comment by xiang90** [comment]
what is the gateway? something you build or etcd-gateway?

**Comment by yongqigood** [comment]
I build gateway, not etcd-gateway.

**Comment by xiang90** [comment]
so you need to figure it out why the software you built uses more CPU, not etcd community i guess.
