### ISSUE TITLE
etcd grpc-proxy performance

### ISSUE THREAD

**Issue by yongqigood** [coreos/etcd#8907]
I created etcd cluster and a etcd grpc gateway which forward all request to backend etcd cluster.

I find that etcd grpc gateway's cpu usage higher than etcd cluster's cpu usage.

I am using benchmark to test gateway.

I think etcd should do more work(process request and do raft) than etcd grpc gateway.

What caused gateway's cpu usage higher than etcd's cpu usage?

**Comment by gyuho** [comment]
@yongqigood Isn't this same issue as https://github.com/coreos/etcd/issues/8906?

**Comment by yongqigood** [comment]
Not same, I also tested etcd grpc gateway and same issue, gate cpu usage higher than etcd cpu usage.

**Comment by xiang90** [comment]
grpc proxy and gateway are two different thing. which one are you talking about?

**Comment by yongqigood** [comment]
I am using grpc proxy forward etcd request to bankend etcd cluster.

**Comment by xiang90** [comment]
@yongqigood 

grpc proxy is not a simple gateway. it interprets the request/response, and handles caching. I would expect it does more work than etcd server in terms of CPU currently. There are def places that can be optimized to reduce CPU load on the grpc proxy. Hope that answer you question.

**Comment by yongqigood** [comment]
Thanks for your reply and suggestions Xiang. We have do what you said and even don't decode, forward it directly(not decode request and forward to backend etcd, Also not decode respond and forward to user client), cup usage is same. Is there some suggestion?

**Comment by xiang90** [comment]
I really cannot say anything about the software you built since i have no insight into it.

**Comment by xiang90** [comment]
I am closing this now since the original question is answered.
