### ISSUE TITLE
nslookup fails in quay.io/coreos/etcd:v3.2

### ISSUE THREAD

**Issue by ayashjorden** [coreos/etcd#8913]
A question, 

I'm deployed a k8s cluster from scratch.
Also deployed kube-dns

When I deployed quay.io/coreos/etcd:v3.2 and tried to run `nslookup kubernetes.default`, I got:
```
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'kubernetes.default': Try again
```
The I followed up on [k8s DNS troubleshooting][dns_trouble] and when I ran `kubectl exec -ti busybox -- nslookup kubernetes.default` I got:
```
Server:    10.2.0.10
Address 1: 10.2.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.2.0.1 kubernetes.default.svc.cluster.local
```
Both Pods are running in the same Namespace.
Both containers have identical /etc/resolv.conf:
```
nameserver 10.2.0.10
search default.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```

Is this related to Alpine image? or something else?
Any ideas?

[dns_trouble]:https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#check-the-local-dns-configuration-first

**Comment by xiang90** [comment]
It does not seem like an etcd issue. You can ask this in Kubernetes community instead.
