### ISSUE TITLE
clientv3 can create directory

### ISSUE THREAD

**Issue by songlong** [coreos/etcd#8917]
ctx, cancel := context.WithTimeout(context.Background(), requestTimeout)
	pd, err := cli.Put(ctx, "/test/tt", "sssbar")
        
       but  curl http://127.0.0.1:2379/v2/keys    {"action":"get","node":{"dir":true}}
       It is obvious that clientv3 cant create directory?

**Comment by xiang90** [comment]
there is no directory concept in v3. "/" is a char as "a" or "b".
