### ISSUE TITLE
etcdctl cluster-health tries to connect to http in https-only cluster

### ISSUE THREAD

**Issue by discordianfish** [coreos/etcd#8929]
I've successfully enabled TLS for peer and client authentication but have trouble using etcdctl. When running with only --ca-file, --cert-file and --key-file flags I just get: `client: etcd cluster is unavailable or misconfigured`. Running with `--debug` print a bunch of curl(??) statements that are referring to http.
With `--no-sync` this is working fine though.

Now I need to use cluster-health to controll my rolling upgrades I can't get that to work at all. Even with --no-sync it fails:

```
etcdctl --endpoints https://localhost:2379   --ca-file=/etc/ssl/etcd/ca.crt   --cert-file=/etc/ssl/etcd/peer.crt   --key-file=/etc/ssl/etcd/peer.key   --no-sync --debug cluster-health                                   
Cluster-Endpoints: https://localhost:2379
cURL Command: curl -X GET https://localhost:2379/v2/members
failed to check the health of member 345f941c33059416 on http://172.20.96.91:2379: Get http://172.20.96.91:2379/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
member 345f941c33059416 is unreachable: [http://172.20.96.91:2379] are all unreachable
failed to check the health of member bbf6f3fff3b80e93 on http://172.20.40.240:2379: Get http://172.20.40.240:2379/health: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
member bbf6f3fff3b80e93 is unreachable: [http://172.20.40.240:2379] are all unreachable
cluster is unhealthy
```

Is `cluster-health` as well as --no-sync=false not support with TLS? What is my best option to check for cluster health?

**Comment by xiang90** [comment]
What are the flags that you used to start etcd? etcdctlv2 first syncs with etcd server to update its advertised URL. I think you probably provide incorrect URLs to etcdserver at the first place.

**Comment by discordianfish** [comment]
Ah damn, you're right.. While typing the response I realized I've still have http in the advertised client url. Never mind and sorry about the noise!
