### ISSUE TITLE
Get config setting from etcd

### ISSUE THREAD

**Issue by Stevenhuangqian** [coreos/etcd#8940]
i want to get the config settings from etcd using the http request in nginx with interval time . 
I think the request url should not be fixed in my lua script or any config file. Because when any nodes crash, the ip will be unusable, At that time i have to change the ip  on  each server. 
So i wonder whether etcd support this function:
       lua send UDP broadcast to the LAN .
       etcd nodes get my nginx callback address  from the udp pack
       nodes send the cluster infos using the callback address

**Comment by gyuho** [comment]
No, we don't support it.

Recommended way is remove the crashed node, and add a new member.
