### ISSUE TITLE
Set vs Put

### ISSUE THREAD

**Issue by philiprbrenan** [coreos/etcd#8942]
On page:

https://github.com/coreos/etcd

ETCDCTL_API=3 etcdctl **put** mykey "this is awesome"

but it should be **set**:

ETCDCTL_API=3 etcdctl **set** mykey "this is awesome"
this is awesome
ETCDCTL_API=3 etcdctl **get** mykey
this is awesome
ETCDCTL_API=3 etcdctl **put** mykey "this is awesome"
No help topic for 'put'

**Comment by gyuho** [comment]
Have you tried `ETCDCTL_API=3 etcdctl set mykey "this is awesome"`?

v3 has no command `set`.
`put` is correct.
