### ISSUE TITLE
High memory usage on 3.2.9

### ISSUE THREAD

**Issue by ahmadster** [coreos/etcd#8949]
I'm running etcd to save json documents with a plain UUID key. All of my data is about 2-4GB. When I store in etcd it eats up close to 27 GB of RAM and more. It crashes consistently.
What am I doing wrong.
![root_sjc04p1dkrap52__home_tesler_pulsar_prd_data_etcd](https://user-images.githubusercontent.com/24639101/33464239-2cf55b18-d5f6-11e7-8c0d-778b017998b4.jpg)

**Comment by fanminshi** [comment]
@ahmadster 
Is `--snapshot-count` and`--max-snapshots` the only configurable flags that you used?
Does this memory issue happen all the time? or only happen occasionally?
Do you ever update to `UUID key` with different json doc?

**Comment by ahmadster** [comment]
snapshot-count and max-snapshots are the only configurable flags
It happens all the time consistently. I wipe out my data, start a fresh etcd data dir, it takes ~5-6 hours and it fills up again, then crashes and keeps crashing until I wipe the data out.

No, UUID key is never updated. Just a one time write.

The keys are all in a directory. So I create a directory named `/json/` and when saving a new json I create a uuid and save it with key `/json/abc123...`.

Could it be that each key in `/json/` is considered an update and the whole directory is then snapshot on each write?

**Comment by ahmadster** [comment]
Here are my files since, I wiped about 4 hours ago.
```
[root@sjc04p1dkrap52 member]# ls -laRh
.:
total 16K
drwx------. 4 root root 4.0K Nov 30 19:34 .
drwx------. 3 root root 4.0K Nov 30 19:34 ..
drwx------. 2 root root 4.0K Dec  1 01:54 snap
drwx------. 2 root root 4.0K Dec  1 01:51 wal

./snap:
total 2.6G
drwx------. 2 root root 4.0K Dec  1 01:54 .
drwx------. 4 root root 4.0K Nov 30 19:34 ..
-rw-r--r--. 1 root root 1.3G Dec  1 01:52 0000000000000002-00000000000e1348.snap
-rw-r--r--. 1 root root 1.3G Dec  1 01:54 0000000000000002-00000000000e1733.snap
-rw-------. 1 root root  17M Dec  1 01:53 db

./wal:
total 367M
drwx------. 2 root root 4.0K Dec  1 01:51 .
drwx------. 4 root root 4.0K Nov 30 19:34 ..
-rw-------. 1 root root  62M Dec  1 00:51 000000000000000f-00000000000b0b03.wal
-rw-------. 1 root root  62M Dec  1 01:07 0000000000000010-00000000000bc43e.wal
-rw-------. 1 root root  62M Dec  1 01:30 0000000000000011-00000000000c7285.wal
-rw-------. 1 root root  62M Dec  1 01:51 0000000000000012-00000000000d4588.wal
-rw-------. 1 root root  62M Dec  1 01:54 0000000000000013-00000000000e0ffa.wal
-rw-------. 1 root root  62M Dec  1 01:51 1.tmp
```

**Comment by xiang90** [comment]
@ahmadster 

You are using the old v2 backend, which only support ~100MB total data size: see https://github.com/coreos/etcd/blob/master/Documentation/v2/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md#data-size-threshold.

etcd is not designed to hold a lot of data either. Even with v3, we limit the data size to a few GB.

**Comment by fanminshi** [comment]
@ahmadster you should use v3 api instead of v2 api to write your key to etcd. try that out to see if same issue still occur.
