### ISSUE TITLE
Extract etcd transaction logs for user

### ISSUE THREAD

**Issue by nizam037** [coreos/etcd#8950]
i have some commonn doubts in etcd DB. They are 
1.how i can tail the logs of etcd like how can i get entries in the etcd db or How can i get to see logs about etcd transactions?
2. Is there any method to see key-value data in normal human readable format?
3.And if the user wants to know what is happening during transaction how user can know ... Is there any methods to see transaction logs for the user??

For example : suppose i have one application with mysql as a DB. so whenever i save some info. in that application in the backgrounds it will perform some MySQL query like INSERT and save the info right.. i want that kind of information's.. this is just a example :)

Isit possible to extract similar kind of information from etcd...

**Comment by gyuho** [comment]
@nizam037 

1. etcd system log outputs to stderr by default. etcd Raft logs persists to WAL (on disk). And if you are talking about transaction events log (e.g. https://dev.mysql.com/doc/refman/5.7/en/binary-log.html), etcd doesn't have it. If you are talking about historical data before transaction, you can query by the revision.

2. See https://github.com/coreos/etcd/tree/master/tools/etcd-dump-db.

3. No.
