### ISSUE TITLE
Metric etcd_http_failed_total is more than etcd_http_received_total

### ISSUE THREAD

**Issue by EqbalS** [coreos/etcd#8965]
etcd version: v3.2.4
docker image: quay.io/coreos/etcd:v3.2.4
docker version: 17.05.0-ce

We are using a 3 member etcd cluster for the master nodes of a local kubernetes cluster:
```
+------------------+---------+-------+--------------------------+--------------------------+
|        ID        | STATUS  | NAME  |        PEER ADDRS        |       CLIENT ADDRS       |
+------------------+---------+-------+--------------------------+--------------------------+
| 77fdfbd3966d88d6 | started | etcd1 | https://172.19.2.31:2380 | https://172.19.2.31:2379 |
| 861df46a1b5a0416 | started | etcd3 | https://172.19.2.33:2380 | https://172.19.2.33:2379 |
| bb9301e4274969f0 | started | etcd2 | https://172.19.2.32:2380 | https://172.19.2.32:2379 |
+------------------+---------+-------+--------------------------+--------------------------+
```

In the prometheus data we have discovered this issue that in http metrics for GET method on the etcd2 instance we have more failed requests with error code 400 than the total received. this is the actual values for this metrics in a 5 minute window scraped every 30 seconds: 
```
etcd_http_received_total{endpoint="api",instance="172.19.2.32:2379",job="etcd",method="GET",namespace="kube-system",service="etcd-k8s"}
425995 @1512303407.387
426007 @1512303437.387
426018 @1512303467.387
426029 @1512303497.387
426040 @1512303527.387
426052 @1512303557.387
426064 @1512303587.387
426075 @1512303617.387
426087 @1512303647.387
426099 @1512303677.387

etcd_http_failed_total{code="400",endpoint="api",instance="172.19.2.32:2379",job="etcd",method="GET",namespace="kube-system",service="etcd-k8s"}
5122978 @1512303407.387
5123098 @1512303437.387
5123218 @1512303467.387
5123338 @1512303497.387
5123458 @1512303527.387
5123578 @1512303557.387
5123698 @1512303587.387
5123818 @1512303617.387
5123938 @1512303647.387
5124058 @1512303677.387
```

As you can see both rate and the total number of failed requests are more than total received. We are getting an alert by prometheus telling that there are high number on failed requests but these numbers don't make sense. the alert rule is the following: (copied from alerting rules from monitoring section of etcd documentation)
```
sum(rate(etcd_http_failed_total{job="etcd"}[5m])) BY (method) / sum(rate(etcd_http_received_total{job="etcd"}[5m])) BY (method) > 0.05
```

**Comment by xiang90** [comment]
can you reproduce it outside kubernetes? like with a simple script? thanks.

**Comment by EqbalS** [comment]
@xiang90 
I couldn't reproduce it outside kubernetes.
etcd seems to be ok and there is no problem with performance and there are no errors in the logs.
And the strange thing is that it is only happening in one of the nodes.
I think it's just a inconsistency in metrics that's causing a false alarm. I've just silenced the alert for now.

**Comment by xiang90** [comment]
/cc @hexfusion maybe you want to try to reproduce this one? you might need to know how Prometheus (https://prometheus.io/) is integrated into etcd (see https://github.com/coreos/etcd/blob/master/etcdserver/api/v2http/metrics.go#L30).

then we need to check if the accounting of the metrics is correct in a few code paths.

**Comment by hexfusion** [comment]
@xiang90 sounds interesting, thanks.

**Comment by hexfusion** [comment]
@xiang90, a quick update I setup a test ENV in compose. https://github.com/hexfusion/etcd-compose-examples/tree/master/etcd2-prometheus . Could use curl directly vs compose but I figured it was a decent example to document for others.

I will add a test script to generate a dataset that we can review metric accounting. I hope to have time this evening.

**Comment by hexfusion** [comment]
@xiang90 @EqbalS I can not recreate the issue.

```
$ git clone https://github.com/hexfusion/etcd-compose-examples.git
$ cd etcd2-prometheus
$ docker up -d
$ ./data.pop.sh
[..]
Complete!

View results here http://127.0.0.1:36012
```
![2017-12-18-22 15 01-screenshot](https://user-images.githubusercontent.com/1249749/34139225-8e48b69a-e441-11e7-8ab9-d46a54193f1f.png)

**Comment by hexfusion** [comment]
@xiang90 shall I try to replicate the issue within k8s?

**Comment by hexfusion** [comment]
@xiang90  perhaps this is just a misunderstanding? By received total, it seems the metric is collecting 200's or success. where the failure is collecting 400's. Is the assumption that received total is success plus failure? That appears to not be the case. So it is easy to have more failure then total as they are separate metrics.

**Comment by hexfusion** [comment]
Maybe we could include `etcd_http_total` or you could manually create it by adding them together.

**Comment by hexfusion** [comment]
@xiang90, @EqbalS are we on the same page with my assessment? ^^

**Comment by EqbalS** [comment]
@hexfusion 
If that's the case I think this should change:
https://github.com/coreos/etcd/blob/b01f16a4a4a3d71cd7d187dba89808edde0cbddc/Documentation/op-guide/etcd3_alert.rules.yml#L58-L77
This is the suggested alerting rules here in the monitoring documentation:
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/monitoring.md#alerting
and it obviously is dividing failed_total by received_total.

**Comment by hexfusion** [comment]
@EqbalS if the alert threshold is intended to be a percentage failure rate I would agree with you.

**Comment by hexfusion** [comment]
@EqbalS, would you be interested in helping to fix it?

**Comment by hexfusion** [comment]
@EqbalS just checking in, would you be interested in working with me to resolve this?

**Comment by EqbalS** [comment]
@hexfusion 
Sorry to keep you waiting,
Yes I'd be happy to help.

**Comment by hexfusion** [comment]
@EqbalS not a problem I just figured since you found the problem that you should get the credit for the resolution. :) I will swing back with some details I dug up shortly. Thanks!

**Comment by gyuho** [comment]
> etcd seems to be ok and there is no problem with performance and there are no errors in the logs.

Doesn't seem like an etcd issue. Please create a new one if you still need help.
