### ISSUE TITLE
compile error about etcdserver/etcdserverpb/rpc.pb.go

### ISSUE THREAD

**Issue by chacha923** [coreos/etcd#8967]
hello , i find sth while compiling etcd project on mac. 

this file github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go has reported some error
it look like a type convert error, 
maybe package google.golang.org/grpc is updated but you are not notified?? 
thanks !!!

---------------------
../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3391: cannot use _KV_Range_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3395: cannot use _KV_Put_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3399: cannot use _KV_DeleteRange_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3403: cannot use _KV_Txn_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3407: cannot use _KV_Compact_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3739: cannot use _Lease_LeaseGrant_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3743: cannot use _Lease_LeaseRevoke_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3747: cannot use _Lease_LeaseTimeToLive_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3751: cannot use _Lease_LeaseLeases_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3917: cannot use _Cluster_MemberAdd_Handler (type func(interface {}, "github.com/vendor/golang.org/x/net/context".Context, func(interface {}) error, grpc.UnaryServerInterceptor) (interface {}, error)) as type grpc.methodHandler in field value

../../../github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go:3917: too many errors

**Comment by chacha923** [comment]
my go env is go version go1.8 darwin/amd64

**Comment by chacha923** [comment]
oh, i change the import packge of "context" to "golang.org/x/net/context" in clientv3/client.go,  health_balancer.go, retry.go ,  it compile success, 

i see the dir of golang.org/x/net/context,  it only has go17.go and go19.go , 
you can see   https://github.com/golang/net/tree/master/context
i guess it just not support go 1.8 _(:з」∠)_

**Comment by gyuho** [comment]
You need Go 1.9+

https://github.com/coreos/etcd#getting-etcd

> For those wanting to try the very latest version, build the latest version of etcd from the master branch. This first needs Go installed (version 1.9+ is required). All development occurs on master, including new features and bug fixes. Bug fixes are first targeted at master and subsequently ported to release branches, as described in the branch management guide.
