### ISSUE TITLE
Misleading documentation on --listen-metrics-urls

### ISSUE THREAD

**Issue by andrestc** [coreos/etcd#8969]
The [monitoring etcd docs](https://coreos.com/etcd/docs/latest/op-guide/monitoring.html) for version 3.2.9 mention the `--listen-metrics-urls` flag. This flag is not mentioned in [Configuration flags docs](https://coreos.com/etcd/docs/latest/op-guide/configuration.html) and I can also confirm that trying to run etcd with this flag set results in an error:

```
flag provided but not defined: -listen-metrics-urls
```

I see that the flag is implemented in master but seems to be missing from the releases. Is this a doc error or the flag should've been included in past releases?

**Comment by gyuho** [comment]
It was a bad cherry-pick in our end. Fixed in the release branch.
Will be synced up in the next release.

Thanks for the report!

**Comment by andrestc** [comment]
Thanks, @gyuho.

**Comment by gyuho** [comment]
@zbwright @joshix Can we sync https://coreos.com/etcd/docs/latest/op-guide/monitoring.html with latest release https://github.com/coreos/etcd/releases/tag/v3.2.11?

**Comment by gyuho** [comment]
This is now fixed. Please visit https://coreos.com/etcd/docs/latest/op-guide/monitoring.html.

Thanks for report!
