### ISSUE TITLE
How to change a public discovery cluster to be static after it has launched?

### ISSUE THREAD

**Issue by pavlo** [coreos/etcd#8976]
Hey!

I have a cluster of 3 members bootstrapped using the public discovery thing. The cluster launched and operated just fine. Each machine has this in its cloud-config:

    etcd2:
      advertise-client-urls: http://$private_ipv4:2379
      discovery: https://discovery.etcd.io/<the ID here>
      initial-advertise-peer-urls: http://$private_ipv4:2380
      listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
      listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001

All worked fine - I bootstrapped it initially and was able to restart the nodes one by one to simulate temporary issues with a member while the other two keep maintaining the quorum.

Now, I want not just restart the member but rather remove it and start on an other box whose `$private_ipv4` would be different. In this case the use of the public discovery service is no longer helpful and the documentation says a cluster ought to be changed to static before `member remove` and `member add` commands could be used.

So, while I have the three member cluster still - how would I change it to be static, how to re-configure it? Should I fix their `cloud-config` now to not contain `discovery` but contain `initial-cluster` and `initial-cluster-state` and restart the member nodes one by one?

Also, what if I had a bunch of proxies in the cluster, should their cloud-config be modified and the nodes restarted?

Thank you!
Pavlo

**Comment by hexfusion** [comment]
@pavlo I hacked up an example using docker-compose, it uses TLS but you can remove that for your purpose. https://github.com/hexfusion/etcd-compose-examples/tree/master/discovery. See if you can update the cluster using etcdctl https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md. Hope that helps your experimentation.

**Comment by xiang90** [comment]
> So, while I have the three member cluster still - how would I change it to be static, how to re-configure it?

You do not need to do anything. There is no such concept like `dynamic cluster` in etcd. No matter what bootstrap mechanism you use, you will end up with the same `static cluster`, and you need to manage the cluster on your own after the bootstrap. For a cluster that is created by using discovery service, the discovery token will simply be ignored after the first bootstrap. The member will persist all membership information onto local disk, so discovery is no longer needed once the member is bootstrapped.

**Comment by pavlo** [comment]
@xiang90, thanks for clarifying this matter for me, you were right that I thought there's a dynamic cluster concept which led me to the whole lots of confusions.

I am getting into a trouble when trying to work my way further. Here's what I do:

a) Create three members (M1, M2, M3) and one proxy (P1) using the following in `user-data`

     etcd2:
         advertise-client-urls: http://$private_ipv4:2379
         discovery: https://discovery.etcd.io/<the ID here>
         initial-advertise-peer-urls: http://$private_ipv4:2380
         listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
         listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001

The cluster bootstrapps just fine. All is fine at this point

b) Terminate the M2 node physically. Check `cluster-health` from M1 and confirm that M2 is no longer reachable. All is fine here too.

c) Execute `member remove <M2 ID>` - all is fine, `cluster-health` now shows a healthy cluster of 2 members. Expected.

d) Boot up a new node, that would be a replacement for M2. **Note, it would have a different IP address...** Let's call it M4 here. I use the same user-data so it boots up into the cluster and becomes a proxy:

    etcd2:
         advertise-client-urls: http://$private_ipv4:2379
         discovery: https://discovery.etcd.io/<the ID here>
         initial-advertise-peer-urls: http://$private_ipv4:2380
         listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
         listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001

e) I stop etcd2 and remove its data dir on M4:
    
    sudo systemctl stop etcd2
    sudo rm -rf /var/lib/etcd2

f) Now, since the IP address of M4 is known, I go to M1 add the new member to the cluster:

    member add m4 http://<M4-IP>:2380

it gives this in the output:

    ETCD_NAME="m4"
    ETCD_INITIAL_CLUSTER="m4=http://172.XX.XX.XX:2380...long line goes here"
    ETCD_INITIAL_CLUSTER_STATE="existing"

g) I copy the three lines above and paste them in `/etc/environment` on M4.

h) Reboot M4 hoping it would become a member. 

Once it boots up it again is a proxy and from its logs I see that it uses the configuration from `user-data` rather. So, it clearly does not do what you said it would:

> The member will persist all membership information onto local disk, so discovery is no longer needed once the member is bootstrapped

I just want to understand how it is supposed to work. From one hand a CoreOS node is supposed to be restarted at any time because an automated update may come, but from other hand the `user-data` settings win which makes it impossible to get the new env. vars applied after restart. 

How do you guys use etcd in a heavy production? Is it about modifying `user-data` with the updated env. var values and restart the nodes with an updated user-data? Also, say I restart the proxy (P1) and it would hit the discovery URL and find an outdated cluster information there - should its `user-data` be changed as well? It's going to be an issue given one may have dozens of dozens proxies, right?

Hope I miss something really obvious!
Thank you very much for your help, appreciate the time you spend on this!

Pavlo
