### ISSUE TITLE
FAIL    github.com/coreos/etcd [build failed]

### ISSUE THREAD

**Issue by nicolasStevenin** [coreos/etcd#8981]
Hello !
When I try to test the project github.com/coreos/etcd/ in version 3.2.11 it fails with

github.com/grpc-ecosystem/grpc-gateway/runtime
/usr/share/gocode/src/github.com/grpc-ecosystem/grpc-gateway/runtime/context.go:84: undefined: metadata.NewContext
FAIL    github.com/coreos/etcd [build failed]

Thank you for your help.

**Comment by hexfusion** [comment]
@nicolasStevenin I can not replicate this issue. Can you please post the steps you are taking?

**Comment by gyuho** [comment]
@nicolasStevenin If you try building `v3.2.11`, make sure you have the matching grpc dependencies as etcd

https://github.com/coreos/etcd/blob/ed4d70888caef77a9b1d875be70e3e61d3374552/glide.yaml#L99-L100

`metadata.NewContext` is deprecated in the latest gRPC releases.
