### ISSUE TITLE
no buildable Go source files

### ISSUE THREAD

**Issue by nicolasStevenin** [coreos/etcd#8982]
Hello !
When I try to test etcdctl, etcdctl/ctlv2/command, etcdctl/ctlv2  in version 3.2.11 it fails with

ctlv3/command/check.go:32:2: no buildable Go source files in /usr/share/gocode/src/gopkg.in/cheggaaa/pb.v1

Thank you for your help

**Comment by hexfusion** [comment]
Hi @nicolasStevenin are you using release binaries i.e https://github.com/coreos/etcd/releases/download/v3.2.11/etcd-v3.2.11-linux-amd64.tar.gz or building from source? Please provide exact commands/process used to reproduce the issue.

**Comment by gyuho** [comment]
@nicolasStevenin Make sure you have the same `gopkg.in/cheggaaa/pb.v1` version as etcd in your GOPATH. See https://github.com/coreos/etcd/blob/release-3.2/glide.yaml.

**Comment by nicolasStevenin** [comment]
it's ok ! my bad. @gyuho in fact, i have a bad gopkg.in/cheggaaa/pb.v1
thanks
