### ISSUE TITLE
Documentation/op-guide: update container.md

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8984]
ACI is deprecated, so maybe drop `rkt coreos.com/etcd:v3.1.2` commands.
Clean up other commands as well.

https://github.com/coreos/etcd/blob/master/Documentation/op-guide/container.md

**Comment by spzala** [comment]
@xiang90 thanks much and yes absolutely, this will be good start :-). I will be working on it soon get back to home tomorrow.

**Comment by spzala** [comment]
Update on work - started digging into it. Thanks!
