### ISSUE TITLE
what are the flags for member remove in etcd 3?

### ISSUE THREAD

**Issue by eiselesr** [coreos/etcd#8990]
I was able to start a 2 node cluster and add a new node. I am trying to remove that node before starting it with `etcdctl member remove <memberID>` however  i get this error : 

`Error:  client: etcd cluster is unavailable or misconfigured;
 error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused; error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused error #0: dial tcp 127.0.0.1:4001: getsockopt: connection refused error #1: dial tcp 127.0.0.1:2379: getsockopt: connection refused`

My cluster is on 10.0.0.x:2379 so I'm not surprised it can't get a connection. How can I specify where my cluster is with member remove?

**Comment by hexfusion** [comment]
@eiselesr try passing the cluster endpoints.
`etcdctl --endpoints=http://10.0.0.1:2379,http://10.0.0.2:2379,[..] member remove <memberID>`

**Comment by eiselesr** [comment]
Ah yes, that works. Thanks.  My problem was I was putting the --endpoints flag after member remove.
