### ISSUE TITLE
clientv3: document context.Context parameter to streaming APIs

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#8993]
Related to https://github.com/coreos/etcd/issues/8980.

We haven't documented how our stream APIs work with client's contexts.

https://github.com/coreos/etcd/blob/e3da56a8dfb88c7ee8f6c282c986fb5154700910/clientv3/watch.go#L44-L53

https://github.com/coreos/etcd/blob/e3da56a8dfb88c7ee8f6c282c986fb5154700910/clientv3/lease.go#L116-L117

https://github.com/coreos/etcd/blob/e3da56a8dfb88c7ee8f6c282c986fb5154700910/clientv3/maintenance.go#L57-L58

Would cancelling the context close the watch stream? What if the context timeouts? If the stream is kept open, what is the retry policy? What happens to the underlying `io.ReadCloser` when the context gets cancelled?

Also

https://github.com/coreos/etcd/blob/b48cf77abb78755c8654eb8da61bc90a32802e7d/clientv3/concurrency/session.go#L132-L141

**Comment by gyuho** [comment]
`WithContext` is already documented well. Closing!

**Comment by xiang90** [comment]
@gyuho good job on this one!!
