### ISSUE TITLE
Cluster setup prevented by default setup

### ISSUE THREAD

**Issue by rboyc** [coreos/etcd#8997]
Hi

I am installing etcd package in order to setup a cluster

As soon as I have run

apt-get install etcd

I can check the member list

etcdctl member list

which displays  that I have an instance running:

ce2a822cea30bfca: name=ip-172-31-19-228 peerURLs=http://localhost:2380,http://localhost:7001 clientURLs=http://localhost:2379,http://localhost:4001

I try to start cluster with a discovery token:
etcd --name ip-172-31-23-121 \
  --initial-advertise-peer-urls http://172.31.23.121:2380 \
  --listen-peer-urls http://172.31.23.121:2380 \
  --listen-client-urls http://172.31.23.121:2379 \
  --advertise-client-urls http://172.31.23.121:2379 \
  --discovery https://discovery.etcd.io/2d08417d09f4de18f8104dab2a053489

I can set up all members on the cluster with this but when I 

etcdctl cluster-health 

or

etcdctl member list

It only displays the localhost instance with a different identifier from what the cluster set up displayed:

ce2a822cea30bfca: name=ip-172-31-19-228 peerURLs=http://localhost:2380,http://localhost:7001 clientURLs=http://localhost:2379,http://localhost:4001

Any idea how I get around this?

thanks very much

**Comment by hexfusion** [comment]
@rboyc 

> I try to start cluster with a discovery token:

Discovery token is for bootstrapping a cluster. As you already have a node running I don't believe discovery token is going to work.

> Any idea how I get around this?

I think what you want to do now is basically what the docs say regarding adding new member.
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member

```
etcdctl --endpoints=http://172.31.19.228:2379 member add ip-172-31-19-2xx --peer-urls=http://172.31.19.2xx:2380
```

which will give you something like
```
Member 837d486fbd22eb1d added to cluster 46d80cbf0df2d098
ETCD_NAME="ip-172-31-19-228"
ETCD_INITIAL_CLUSTER="ip-172-31-19-228=http://172.31.19.228:2380,ip-172-31-19-2xx=http://172.31.19.2xx:2380"
ETCD_INITIAL_CLUSTER_STATE=existing
```
Then follow the docs on setting ENV etc and starting new nodes using the output generated. This should add the new nodes to the existing running instance. I hope this helps.

**Comment by rboyc** [comment]
Thanks @hexfusion 

I guess my problem is how do install etcd without it initially bootstrapping, so that I can create it with my cluster config?

thanks

**Comment by hexfusion** [comment]
> I guess my problem is how do install etcd without it initially bootstrapping, so that I can create it with my cluster config?

@rboyc etcd is a binary please look at the [download and build guide](https://github.com/coreos/etcd/blob/master/Documentation/dl_build.md) to install only the binary.

Although the apt-get brings in the binary it also presumably installs a systemd unit file with possible dependencies on ENV variables to bootstrap a cluster correctly.  This is unclear to me and would require more review on your end if you wanted to use this method.

-HTH

**Comment by hexfusion** [comment]
@rboyc feel free to post the unit file content and maybe we can shed more light?

```
systemctl status etcd
Loaded: loaded (/my/path/to/etcd.service; static)
```

**Comment by rboyc** [comment]
Thanks, workking when i use binarys
