### ISSUE TITLE
All atomic Set should be one shot in go client

### ISSUE THREAD

**Issue by xiezhenye** [coreos/etcd#8998]
Currently, only PrevNoExist Set is one shot. PrevValue, PrevIndex Set should also be one shot. Otherwise, when client got an 101: Compare failed, There could be to situation:

1. The value is changed by other process.
2. Got a network/cluster error but the set operation is succeeded, and then a retry got a compare failed.

We are not able to make certain what has happened.

**Comment by gyuho** [comment]
> Currently, only PrevNoExist Set is one shot.

What do you mean?

**Comment by xiezhenye** [comment]
`Set` with option `PrevNoExist: true` ，is one shot, the operation won't be retried when failed.

**Comment by gyuho** [comment]
We won't support v2 client features anymore.
