### ISSUE TITLE
E1211 07:19:48.090611 00006 watch.go:43] Watch subnets: invalid character 'â' looking for beginning of value

### ISSUE THREAD

**Issue by garyyang85** [coreos/etcd#9001]
I am using etcd3.0.17 and flannel 0.6.2 in my kubernetes, there are a lot of network error log suddenly in my flannel log:
**E1211 07:19:40.077502 00006 watch.go:43] Watch subnets: invalid character 'â' looking for beginning of value**

Etcd status is healthy, some output for the etcdctl:
etcdctl --peers https://localhost:2379 ls /cluster.local/network/subnets
/cluster.local/network/subnets/10.254.21.0-24
/cluster.local/network/subnets/10.254.82.0-24
/cluster.local/network/subnets/10.254.98.0-24
/cluster.local/network/subnets/10.254.134.0-24

If I manually delete the subnets, it will generate a new one, then the error log gone.
I deleted two subnets, and a odd status here:
Pods on the new two subnets vm, can reach each other, but can not reach the other pods on the error logs vms. The pods on the error logs vm can reach each other but can not reach the pods on the two new subnets vm.

New subnet output like this:
{"PublicIP":"x.x.x.x","BackendType":"vxlan","BackendData":{"VtepMAC":"a2:81:90:6c:b0:ef"}}
Erros logs subnet output like this:
{"PublicIP":"x.x.x.x","BackendType":"vxlan","BackendData":{"VtepMAC":"66:1b:f8:95:7f:5c"}}

Looks the same.

I am wondering where to find the invalid character 'â' ? It is very hard to input character like this..

**Comment by hexfusion** [comment]
> I am wondering where to find the invalid character 'â' ? It is very hard to input character like this..

I think this is some kind of invalid data possibly encoding issue? I have seen this before copying and pasting into shell. This is not visible in the shell but you can see the odd hyphens before endpoints below. So I think the issue is not so much with the character itself. Doesn't answer the question of why but maybe it helps shed a little light.

```
Error: unknown shorthand flag: 'â' in -—endpoints=http://127.0.01:35262
```

**Comment by xiang90** [comment]
@garyyang85 

As @hexfusion mentioned, it is probably due to bad data or bad encoding rather than etcd itself. I would suggest you open an issue in flannel repo to get more help. Thanks!
