### ISSUE TITLE
Does etcd support watcher group feature?

### ISSUE THREAD

**Issue by gokepler** [coreos/etcd#9019]
something that is similar to kafka's consumer group, to etcd is that when several watchers belong to the same group and only one of them will be notified when a event fired.

**Comment by hexfusion** [comment]
> Does etcd support watcher group feature? something that is similar to kafka's consumer group.

Hi @gokepler could you provide a more detailed example of your use case and how etcd should respond? I am unfamiliar with `kafka's consumer group`. 

I have questions like what is the group of? watchers only, users? What is the logic for choosing which is notified when an event is triggered if multiple watchers exist? Txn seems to possibly provide the foundation for something like this but... we don't support watcher groups to my knowledge. Perhaps it could be useful for many? More info could help that question. Also, would you be interested in helping? Thanks!

**Comment by hexfusion** [comment]
ping @gokepler are you interested in helping with this?

**Comment by xiang90** [comment]
I also want to learn about your use case first @gokepler. What problem are you trying to solve with this feature specifically?

**Comment by hexfusion** [comment]
@gokepler I am going to close this if you have more details on your use case please reopen to discuss.

**Comment by sherry2014** [comment]
Multiple consumers consume one topic , each msg can be recived by only one consumer.
While multiple clients are watching one same key, each event can be recived by only one client.
So each event is just be handled only once.
