### ISSUE TITLE
transport: Error while dialing dial tcp [::]:6060

### ISSUE THREAD

**Issue by vyasprashant** [coreos/etcd#9027]
# Issue reporting

Am running clair on minikube and am getting the error in the logs

{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:88","Time":"2017-12-17 23:10:41.165052","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2017-12-17 23:10:41.165317","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2017-12-17 23:10:41.165986","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2017-12-17 23:10:41.166213","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2017-12-17 23:10:41.166555","package":"RHEL"}
2017/12/17 23:10:42 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:10:43 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:10:46 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:10:50 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:10:57 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"finished fetching","Level":"info","Location":"updater.go:290","Time":"2017-12-17 23:10:58.348510","updater name":"alpine"}
2017/12/17 23:11:07 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:11:24 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"finished fetching","Level":"info","Location":"updater.go:290","Time":"2017-12-17 23:11:36.645906","updater name":"debian"}
2017/12/17 23:11:53 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:12:36 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:13:38 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:15:25 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"could not get notification to send","Level":"warning","Location":"notifier.go:132","Time":"2017-12-17 23:15:41.159017","error":null}
2017/12/17 23:17:41 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:19:50 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"could not get notification to send","Level":"warning","Location":"notifier.go:132","Time":"2017-12-17 23:20:41.258043","error":null}
2017/12/17 23:22:11 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
2017/12/17 23:24:08 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}
{"Event":"could not get notification to send","Level":"warning","Location":"notifier.go:132","Time":"2017-12-17 23:25:41.381871","error":null}
2017/12/17 23:26:25 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::]:6060: connect: cannot assign requested address"; Reconnecting to {[::]:6060 <nil>}

Why am i getting this error what are the config files and if you can provide the samples

**Comment by hexfusion** [comment]
> Why am i getting this error what are the config files and if you can provide the samples

Hi @vyasprashant, looks like everything you need should be in the Clair repo.
https://github.com/coreos/clair/blob/master/Documentation/running-clair.md#deployment-strategies

> transport: Error while dialing dial tcp [::]:6060: connect

I am not sure but using ipv6 vs ipv4 could be the root of the issue. Is Clair listening on ipv6? `sudo netstat -ptln | grep 6060`

In general, this is a Clair config issue vs etcd issue it seems.

**Comment by xiang90** [comment]
I agree with @hexfusion that this is a clair rather than etcd issue. So closing here.
