### ISSUE TITLE
etcdctl/v3: improve "lease timetolive" output on expired leases

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#9028]
https://github.com/coreos/etcd/pull/9017/files#r157349677

Before

```
LEASE_ID TTL(0s), remaining(-1s)
```

Should be

```
LEASE_ID already expired
```

/cc @xiang90 @hexfusion

**Comment by hexfusion** [comment]
> LEASE_ID already expired

@gyuho, I agree, **LEASE_ID TTL(0s), remaining(-1s)** is neither helpful or clear.

+1

**Comment by hexfusion** [comment]
@gyuho think this can make 3.3?

**Comment by gyuho** [comment]
@hexfusion Yes, as long as we document clearly. Do you want to work on this?

**Comment by hexfusion** [comment]
@gyuho, sure
