### ISSUE TITLE
Authentication of multiple users

### ISSUE THREAD

**Issue by benmccann** [coreos/etcd#903]
etcd appears currently to allow only authentication using only a single certificate. When starting etcd you can specify -ca-file -cert-file -key-file. I see no mention in the documentation of being able to specify multiple values here, so I assume only one can be provided.

In order to support ACLs we probably need to have multiple users each with their own authentication key.

**Comment by xiang90** [comment]
@benmccann 

we have a rfc for security at https://github.com/coreos/etcd/blob/master/Documentation/rfc/api_security.md

the implementation progress will be tracking at https://github.com/coreos/etcd/issues/2384.
