### ISSUE TITLE
etcd discover 

### ISSUE THREAD

**Issue by WandyLau** [coreos/etcd#9030]
When I try to bring up a cluster with this discover tech, I got two question as follow:

1. The first step is to determine the cluster size with curl command: curl -X put .....
    It seems this command use the 80 port as default. But when I tried this with my localhost, which
    report with connection refused when a etcd server is actually running in my host.  Is there any 
    other config against this?

2.  And this command use http, what if I use a https scheme? Can this still comply with? 

Or Can I just ask for short, could this etcd discover service be used for https cluster?

**Comment by WandyLau** [comment]
As far as I can tell that the discovery mechanism requires a existing etcd cluster. The etc member will anticipate the cluster with curl from the port 80. As I found in the doc following lines.

**If http://example.com hosts an etcd cluster for discovery service, a full URL to discovery keyspace will be http://example.com/v2/keys/_etcd/registry.** 

But when I start a cluster in local, I cannot get access to port 80 with curl.

**Comment by WandyLau** [comment]
It seems the port should be assigned, 80 is the default one.

 **curl -X PUT http://example.com/v2/keys/_etcd/registry/${UUID}/${member_id}?prevExist=false -d value="${member_name}=${member_peer_url_1}&${member_name}=${member_peer_url_2}"**

what does this **member_id** means here?

**Comment by hexfusion** [comment]
>The first step is to determine the cluster size with curl command: curl -X put .....
It seems this command use the 80 port as default. But when I tried this with my localhost, which
report with connection refused when a etcd server is actually running in my host. Is there any
other config against this?

@WandyLau I think you are focusing on the port 80 example too much.

```
#!/bin/sh

UUID=$(uuidgen)
cluster_size=3

curl -X PUT http://127.0.0.1:2379/v2/keys/_etcd/registry/${UUID}/_config/size -d value=${cluster_size}
```
maybe this example will help you.

> And this command use http, what if I use a https scheme? Can this still comply with?

Sure as far as curl is concerned curl -X PUT **https**://127.0.0.1:2379/..... you may need additional flags to connect to the cluster depending on your setup. 

https://github.com/coreos/etcd/blob/master/Documentation/v2/security.md

**Comment by hexfusion** [comment]
Also why not use [public-discovery-service](https://github.com/coreos/etcd/blob/master/Documentation/v2/discovery_protocol.md#public-discovery-service)?

**Comment by WandyLau** [comment]
@hexfusion Thanks for your reply. We are trying to build up a production solution, so this public service may not be proper in security. We have to reduce the dependency on the third party.

**Comment by WandyLau** [comment]
yes, I can make it.  BTW, what does this v2 mean in the link? I thought it was the version of etcd. So 
I could not get the result with v3. 
   
    curl -X PUT http://127.0.0.1:2379/v2/keys/_etcd/registry/${UUID}/_config/size -d 
    value=${cluster_size}

And what does this member_id mean in below link? How can I get it?
    curl -X PUT http://example.com/v2/keys/_etcd/registry/${UUID}/${member_id}?prevExist=false -d 
    value="${member_name}=${member_peer_url_1}&${member_name}=${member_peer_url_2}"

**Comment by WandyLau** [comment]
When I try to register the first node, I got some confused

    curl -X PUT http://example.com/v2/keys/_etcd/registry/${UUID}/${member_id}?prevExist=false -d 
    value="${member_name}=${member_peer_url_1}&${member_name}=${member_peer_url_2}"

what does the member_id means?

**Comment by hexfusion** [comment]
>what does the member_id means? And after I register a etcd, how can I unregister it if I may find some mistake arguments that I set.

**member_id** is a unique identifier for each node. For example `etcdctl member list` would display the member_id of each node in the cluster.

@WandyLau I am not that familiar with manual node management of v2 cluster using REST API but assuming your using etcdctl.

[cluster-reconfiguration-operations](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#cluster-reconfiguration-operations)

> And after I register a etcd, how can I unregister it if I may find some mistake arguments that I set.

from the link above 

``` 
etcdctl member remove a8266ecf031671f3
Removed member a8266ecf031671f3 from cluster
```
You might need to review the `--endpoints` flag for etcdctl. 

I hope that helps.

**Comment by WandyLau** [comment]
@hexfusion yes, that's helpful. 

One more question on DNS discovery, how the DNS SRV records are created? They are created by the etcd automatically or manually? I found no explanation on this. Could you please help me with this?

**Comment by hexfusion** [comment]
>One more question on DNS discovery, how the DNS SRV records are created? They are created by the etcd automatically or manually?

@WandyLau you would need to add these records manually. This is a pretty good example of what is expected from the docs. [create-dns-srv-records](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md#create-dns-srv-records)

**Comment by WandyLau** [comment]
@hexfusion Ah, I got it. Thanks. I think I can close this.
