### ISSUE TITLE
Testing with v3 Client

### ISSUE THREAD

**Issue by frankgreco** [coreos/etcd#9035]
I am trying to test a function that calls `github.com/coreos/etcd/clientv3.New()`. I thought I'd just refactor my function that I could pass in the client. However, I am unable to find a mock/fake client provided by the package. Does one exist? Could you point me to the code where testing the client is done. Worst case scenario I could just create a test `Client` struct but that would be messy.

**Comment by hexfusion** [comment]
> Could you point me to the code where testing the client is done. 

@frankgreco are you looking for this?

https://github.com/coreos/etcd/blob/master/clientv3/client_test.go

**Comment by frankgreco** [comment]
@hexfusion not quite.

Suppose I want to unit test the following function:
```go
func Foo(cli *clientv3.Client) {
   cli.Put(...)
}
```

Because `clientv3.Client` is not an interface, I would have to wrap it with an interface, implement my own test client and pass that to my `Foo` function instead. Does this library have any helper packages that assist with this?

**Comment by hexfusion** [comment]
@frankgreco I see, perhaps you are looking for integration?

https://github.com/coreos/etcd/blob/9c326ab78cd43d6386e4d206ed440530d2db9db0/integration/cluster_proxy.go#L96-L102

**Comment by gyuho** [comment]
Currently there's no mock v3 client. All etcd clientv3 implementation require actual etcd servers (either executable binaries or embedded).

What is your use case for mock client?

**Comment by xiang90** [comment]
We make etcd server embeddable to make test easier, and avoid mocking when possible. I have never found a use case that i would have to mock etcd client. if you want to make setup easier, you can write a reusable func to setup initial key sets.

**Comment by echlebek** [comment]
This can be accomplished with the clientv3.KV interface. Write the function like this:

```
func DoAThing(kv clientv3.KV) error {
    kv.Put(...)
}
```

*clientv3.Client embeds clientv3.KV. You can also produce one with the NewKV func. It's unclear to me what the difference is.

Once you've written the function in terms of the KV interface, you can create a KV implementation that does whatever you like. (Using mocks or fakes for instance)

**Comment by jetndra** [comment]
Can anyone please suggest me some negative scenarios that we can test in  etcd cluster  ?
