### ISSUE TITLE
qps will decrease for many tests frequently?

### ISSUE THREAD

**Issue by nick-99999** [coreos/etcd#9049]
hi，all：
       I used one etcd node，everything is default.The qps will decrease when i create keys and delete 
 keys for many tests frequently.

version:
etcdctl version: 3.2.11
API version: 3.2

**Comment by hexfusion** [comment]
hi @nick-99999 can you provide the exact steps to reproduce this with a simple script?

**Comment by nick-99999** [comment]
OK！
1.sudo ectd
2.start server
3.begin to test with k6,every time about 3w keys
   keys format
  /test/1513736674430000000/uid1
  /test/1513736674367000000/uid2
  /test/1513736674368000000/ui3
  ......
4.server get keys with range,the number is 200 every time
5.server delete keys when got them
repeat step 3~5,after many times,the qps decrease frenquently.

But when i restart etcd, and then delete default.etcd folder,the qps will recover,but after many times will still decrease,so i don't think it has some relation when store many keys,then delete many keys?
