### ISSUE TITLE
docs: include mention of etcd configuration yaml in configuration.md

### ISSUE THREAD

**Issue by philips** [coreos/etcd#9063]
[Configuration.md](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/configuration.md) doesn't mention the [etcd.conf file](https://github.com/coreos/etcd/blob/master/etcd.conf.yml.sample) format or the order of precedent between flags, file, and environment variables.

**Comment by xiang90** [comment]
@spzala 

might want to pick it up?

**Comment by gyuho** [comment]
Currently, if etcd is configured with config file, environmental values are ignored

https://github.com/coreos/etcd/blob/2f57a84ee6294e2d1e3dcda6ef2388bc582a9844/etcdmain/config.go#L247-L255

**Comment by spzala** [comment]
@xiang90 sure, sounds good, I will be working on it. Thanks!

**Comment by spzala** [comment]
WIP. I also noticed that some flags are in the Configuration.md are not in the etcd.conf (e.g. metrics, listen-metrics-urls etc) and vice-versa (e.g. log-output is missed in the Configuration.md). I will add them as part of the fix unless there was a specific reason. Also, I wonder if it makes sense to have flags ordered alphabetically (per section)? Thanks!

**Comment by xiang90** [comment]
@spzala 

> Also, I wonder if it makes sense to have flags ordered alphabetically (per section)? 

Some of them might be grouped again within the section. For example, we put all network related flags together again. But it seems that it is `man`'s convention to sort them alphabetically. No strong opinion here.

**Comment by spzala** [comment]
@xiang90 thanks, makes sense, so let's not worry about that part under this issue. May be something we can talk about as part of future discussions.
