### ISSUE TITLE
Explain about disk metrics

### ISSUE THREAD

**Issue by zyf0330** [coreos/etcd#9068]
I want to know if I understand correctly.
About this line `etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 114`, 114 of total 226 commit spend time less than 0.001 second.
But I don't know what `etcd_disk_backend_commit_duration_seconds_sum 0.9805108359999999` means.
```
# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 114
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 147
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 167
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 189
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 208
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 224
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 226
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 226
etcd_disk_backend_commit_duration_seconds_sum 0.9805108359999999
etcd_disk_backend_commit_duration_seconds_count 226
```

**Comment by hexfusion** [comment]
Hi @zyf0330 great question! I dug around a bit and found that this output is exposed via go-grpc-prometheus via EnableHandlingTimeHistogram.

https://github.com/coreos/etcd/blob/24c718f7dea45a0f7e2f0688c938fc3a9a34560a/etcdmain/etcd.go#L181-L185

Promethius calls this output a [histogram](https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/master/README.md#histograms).

If you take the example they give in the readme little more details on the purpose of the sum is exposed. I bet if you dig into the package further it should become a bit more clear.

```
grpc_server_handling_seconds_sum - cumulative time of RPCs by status and method, useful for calculating average handling times
```

So I agree this is not immediately clear/obvious but hopefully, this gives you a bit of yarn to pull on and explore. If you get the math figured out it in your example it would make a great addition to our [metrics](https://github.com/coreos/etcd/blob/master/Documentation/metrics.md) documentation. Thanks!

**Comment by zyf0330** [comment]
Thanks, I understand.
