### ISSUE TITLE
Etcd attempts to listen on unavailable, non-loopback IP address by default

### ISSUE THREAD

**Issue by andremarianiello** [coreos/etcd#9070]
When running etcd in an environment where DNS host resolution is preferred over /etc/hosts, or when localhost is not defined in /etc/hosts, the default listen URLs defined in embed/config.go prevent etcd from starting correctly.

For example, this issue occurs with the official kubernetes etcd image and kubeadm:

```
# docker run -it --rm gcr.io/google_containers/etcd-amd64:3.1.11 etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://127.0.0.1:2379 --data-dir=/var/lib/etcd --debug=true
2017-12-28 16:41:51.630402 I | etcdmain: etcd Version: 3.1.11
2017-12-28 16:41:51.630451 I | etcdmain: Git SHA: 960f4604b
2017-12-28 16:41:51.630455 I | etcdmain: Go Version: go1.8.5
2017-12-28 16:41:51.630459 I | etcdmain: Go OS/Arch: linux/amd64
2017-12-28 16:41:51.630464 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
2017-12-28 16:41:51.631377 C | etcdmain: listen tcp 10.168.91.198:2380: bind: cannot assign requested address
```

10.168.91.198 is the IP address for localhost.\<search-path-domain\>. I am currently working around this by specifying --listen-peer-urls=http://127.0.0.1:2380 myself, but I would imagine that 127.0.0.1 is strictly better.

**Comment by hexfusion** [comment]
Hi @andremarianiello can you please explain what you are attempting to accomplish? I think that will help us help you.

**Comment by andremarianiello** [comment]
@hexfusion I am using kubeadm to create a kubernetes cluster. Kubernetes uses etcd to persist state, but etcd fails to start correctly because of the described issue, thus my cluster doesn't work without the workaround I mentioned.

**Comment by xiang90** [comment]
If you know exactly what interface/ip you want to listen on, why not
provide it explicitly? Also can you investigate where the ip comes from and
why etcd tries to bind on it

**Comment by andremarianiello** [comment]
@xiang90  As I mentioned in the issue, I am working around this problem by explicitly providing the IP.

The IP comes from my DNS server. There is a record that maps "localhost.\<search-path-domain\>" -> 10.168.91.198. etcd tries to bind to it because "localhost" is the default peer URL https://github.com/coreos/etcd/blob/master/embed/config.go#L55.

**Comment by xiang90** [comment]
what I am saying is that if you know the ip you should provide it
explicitly. Also you always want to do that for clustered etcd, which is
the most common use case. In terms of local host binding, I do not feel
strong feeling about it, defaulting it to 127.0.0.1 might be ok. But I
remembered there is something we ended up with using localhost. I do not
think we would spend the effort to check the feasibility to select which to
bind though.

**Comment by andremarianiello** [comment]
@xiang90 

> what I am saying is that if you know the ip you should provide it explicitly

I already stated that I'm doing that, so I guess I am misunderstanding what you are trying to say.

>  I do not feel strong feeling about it, defaulting it to 127.0.0.1 might be ok.

This is what I want.

> But I remembered there is something we ended up with using localhost.

If you remember the reasoning for that I would be interested in hearing it.

**Comment by hexfusion** [comment]
@andremarianiello thanks for your details.  It seems to me that `localhost` is a flexible default. Assuming IPv4 in my opinion is no saner and less flexible then the current `localhost`. As you have shown `localhost` can mean many things.

https://tools.ietf.org/html/rfc6761#section-6.3
``` 
Users may assume that IPv4 and IPv6 address queries for localhost
names will always resolve to the respective IP loopback address.
```
Changing that assumption would certainly cause backwards incompatability. In the case you outlined I think that overriding your ENV's localhost with 127.0.0.1 is a reasonable one.

Defer to @xiang90

**Comment by andremarianiello** [comment]
@hexfusion Thanks for looking at this. I will report this issue to the parties responsible for the docker image I am using instead.
