### ISSUE TITLE
unsupported architecture "arm64" since ETCD_UNSUPPORTED_ARCH is set

### ISSUE THREAD

**Issue by gititk** [coreos/etcd#9077]
Hi 
I'm trying to install devstack on arm64. while doing so I got:

etcdmain: running etcd on unsupported architecture "arm64" since ETCD_UNSUPPORTED_ARCH is set
2018-01-02 09:58:39.132476 W | pkg/flags: unrecognized environment variable ETCD_UNSUPPORTED_ARCH=arm64
2018-01-02 09:58:39.132516 I | etcdmain: etcd Version: 3.2.9
2018-01-02 09:58:39.132527 I | etcdmain: Git SHA: f1d7dd8
2018-01-02 09:58:39.132536 I | etcdmain: Go Version: go1.8.4
2018-01-02 09:58:39.132544 I | etcdmain: Go OS/Arch: linux/arm64

How can I solve it?
Thanks
Gitit

**Comment by hexfusion** [comment]
@gititk this is a known issue. Duplicates, https://github.com/coreos/etcd/issues/5054.

Not sure where this fork stands.  https://github.com/glevand/coreos--etcd

**Comment by hexfusion** [comment]
Hmm but we do provide arm64 release binaries. IE https://github.com/coreos/etcd/releases/tag/v3.2.12. That is confusing. I guess can you confirm that this is a 64bit arm system? I believe Raspberry Pi are still 32bit.

/cc @xiang90

**Comment by gititk** [comment]
Thanks. my server is 64bit arm. 
Ill try 3.2.12

**Comment by gyuho** [comment]
@gititk If you run with arm, this is an expected warning.

https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md#32-bit-and-other-unsupported-systems

> To avoid inadvertently running a possibly unstable etcd server, `etcd` on unstable or unsupported architectures will print a warning message and immediately exit if the environment variable `ETCD_UNSUPPORTED_ARCH` is not set to the target architecture.

**Comment by xiang90** [comment]
@gyuho 

> unrecognized environment variable ETCD_UNSUPPORTED_ARCH=arm64

why this line showed up?

**Comment by gyuho** [comment]
@xiang90 We only support `ETCD_UNSUPPORTED_ARCH` through environment variable (no such flag as `--unsupported-arch`), so it warns at `flags.SetFlagsFromEnv`.

**Comment by xiang90** [comment]
the logging is pretty confusing. we probably should get it fixed.

**Comment by gyuho** [comment]
yeah, how about just adding `--unsupported-arch` flag, or say the flag doesn't exist?

```
unrecognized environment variable ETCD_UNSUPPORTED_ARCH=arm64 (or no flag "unsupported-arch" found)
```

**Comment by hexfusion** [comment]
why do we ship unsupported binaries? that in itself is confusing.

**Comment by gititk** [comment]
Hi
I get this error with 3.2.12
tar xzvf /opt/stack/devstack/files/etcd-v3.2.12-linux-arm64.tar.gz -C /opt/stack/devstack/files
2018-01-03 12:40:59.693 | 
2018-01-03 12:40:59.693 | gzip: stdin: not in gzip format
2018-01-03 12:40:59.693 | tar: Child returned status 1
2018-01-03 12:40:59.694 | tar: Error is not recoverable: exiting now

**Comment by hexfusion** [comment]
Hi @gititk sounds like a bad download I can not reproduce. As @xiang90 noted the message you reported is expected so the version will not change that.

```
wget https://github.com/coreos/etcd/releases/download/v3.2.12/etcd-v3.2.12-linux-arm64.tar.gz
mkdir test
tar -xzvf etcd-v3.2.12-linux-arm64.tar.gz -C test/
[..]
etcd-v3.2.12-linux-arm64/etcd
```

**Comment by glevand** [comment]
@hexfusion arm64 etcd binaries are published to fulfill the user request for them, and also to allow the rkt test suite to complete without failure on arm64 machines.  See https://github.com/coreos/etcd/issues/8085 (v3.2.0-arm64 release).

**Comment by hexfusion** [comment]
@glevand, could rkt build the binaries during testing? Issue is when a binary is released and we get a request like the above it is confusing. Technically this is unsupported yet we offer it pre-built in the release.  Maybe if the name of the binary included unsupported or some other direct indication? How far off is arm64 from being supported?

**Comment by glevand** [comment]
@hexfusion See: https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md

**Comment by duchuanLX** [comment]
I export ETCD_UNSUPPORTED_ARCH=mips64le set. on/etc/profile
still running error:

2020-01-09 17:03:30.370991 E | etcdmain: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=mips64le set.

**Comment by Doorer** [comment]
> I export ETCD_UNSUPPORTED_ARCH=mips64le set. on/etc/profile
> still running error:
> 
> 2020-01-09 17:03:30.370991 E | etcdmain: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=mips64le set.
Check the os.LookupEnv("ETCD_UNSUPPORTED_ARCH") return  or run export |grep "ETCD_UNSUPPORTED_ARCH " in bash
It works  for me

**Comment by Doorer** [comment]
> I export ETCD_UNSUPPORTED_ARCH=mips64le set. on/etc/profile
> still running error:
> 
> 2020-01-09 17:03:30.370991 E | etcdmain: etcd on unsupported platform without ETCD_UNSUPPORTED_ARCH=mips64le set.

@duchuanLX 
Check the os.LookupEnv("ETCD_UNSUPPORTED_ARCH") return  or run export |grep "ETCD_UNSUPPORTED_ARCH " in bash
It works  for me

**Comment by sri-vathsa** [comment]
Hey! I am trying to start the etcd daemon using the command `sudo systemctl  start etcd.service` and then I ran the command `journalctl -xe`. It says I should set ETCD_UNSUPPORTED_ARCH to arm64. I set the environment variable as said and am still receiving the same error. Am I doing something wrong? Can someone help me out? Thanks :D

**Comment by leo-frank** [comment]
> Hey! I am trying to start the etcd daemon using the command `sudo systemctl start etcd.service` and then I ran the command `journalctl -xe`. It says I should set ETCD_UNSUPPORTED_ARCH to arm64. I set the environment variable as said and am still receiving the same error. Am I doing something wrong? Can someone help me out? Thanks :D

 You simply need to add one line to /etc/default/etcd: ETCD_UNSUPPORTED_ARCH=arm64 and then run sudo systemctl enable etcd && sudo systemctl restart etcd.

**Comment by Clivern** [comment]
you need to remove the check from the main https://github.com/Clivern/etcd/commit/16652241855fd7342da80458bf688bafa0be9b38

then

```zsh
$ go get ./...
$ GOOS=linux GOARM=7 GOARCH=arm ARCH=arm GO_BUILD_FLAGS='-v -mod=readonly' ./build.sh
```
binaries will work on raspberry pi
