### ISSUE TITLE
Question: clientv3 vs. client

### ISSUE THREAD

**Issue by radu-matei** [coreos/etcd#9078]
Hi, everyone!
I have a question regarding the approach to use `clientv3` vs. `client` - when is each of them suitable?

An approach I have in mind is to use `client`(which I assume is HTTP based?) for short-running operations and `clientv3` when streaming / watching is involved?

Are there any best practices / docs on this?

Thanks,
Radu M

**Comment by gyuho** [comment]
clientv3 uses gRPC with stream HTTP/2 multiplexing and many more benefits. There's no reason to use v2 client if you start a new project. Please see https://github.com/coreos/etcd/tree/master/clientv3.

**Comment by gyuho** [comment]
Also check out https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md if you can't use gRPC. It's HTTP based gRPC wrapper :)

**Comment by radu-matei** [comment]
Thanks a lot for the answer, and sorry for not replying sooner 😄 

Thanks!
