### ISSUE TITLE
stream warning logging in v3 rpc pkg

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#9085]
We probably should not log expected errors (for example if the watcher is closed by the client, we should not log a warning saying that the context is canceled.)

/cc @gyuho @jpbetz @hexfusion @spzala

**Comment by xiang90** [comment]
an example of bad logging

```
2017-12-28 04:54:32.106592 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
```

**Comment by gyuho** [comment]
Those are now debug level https://github.com/coreos/etcd/pull/9080 but we could make it warning after we filtering out those context errors.

**Comment by xiang90** [comment]
I think we should make non expected errors at warning level, and expected ones (like user cancellation at debug level.)

**Comment by gyuho** [comment]
@spzala Do you want to work on this? It will be pretty straightforward. Please refer to https://github.com/coreos/etcd/blob/c699470d3b27d2e968df313110255734105687fa/clientv3/client.go#L532-L554 on error parsing.

**Comment by spzala** [comment]
@gyuho sure, I was actually thinking on the same :-). Thanks much for the above info, that will help!
