### ISSUE TITLE
wrong comment

### ISSUE THREAD

**Issue by GhostComputing** [coreos/etcd#9097]
There is wrong comment(maybe typo) following:

 https://github.com/coreos/etcd/blob/master/raft/log_unstable.go#L150

it should be:

      // u.offset <= lo <= hi <= u.offset+len(u.entries)
      ...

**Comment by xiang90** [comment]
@GhostComputing can you send a pr to get this fixed?

**Comment by GhostComputing** [comment]
PR: #9102

**Comment by xiang90** [comment]
this is already fixed. thanks @GhostComputing .
