### ISSUE TITLE
how to create the DNS SRV recodes?

### ISSUE THREAD

**Issue by WandyLau** [coreos/etcd#9099]
As I read the DNS discovery service, I can not find how to create the DNS SRV records.
The document just gives an example of command of dig which shows the result of the DNS query.

So I just want to know how can I create the DNS SRV? I cannot find any document on this.

**Comment by gyuho** [comment]
Please see an example https://github.com/coreos/etcd/tree/master/hack/scripts-dev/docker-dns-srv.

**Comment by hexfusion** [comment]
@WandyLau the example @gyuho noted is a great example of BIND9 records. SVR records are very common in DNS please see your documentation for manually adding.

```
;SVR Record assuming hexfusion.local domain

_etcd-server-ssl._tcp.hexfusion.local. 300 IN  SRV  0 0 2380 node1.hexfusion.local.
_etcd-server-ssl._tcp.hexfusion.local. 300 IN  SRV  0 0 2380 node2.hexfusion.local.
_etcd-server-ssl._tcp.hexfusion.local. 300 IN  SRV  0 0 2380 node3.hexfusion.local.

_etcd-client-ssl._tcp.hexfusion.local. 300 IN  SRV  0 0 2379 node1.hexfusion.local.
_etcd-client-ssl._tcp.hexfusion.local. 300 IN  SRV  0 0 2379 node2.hexfusion.local.
_etcd-client-ssl._tcp.hexfusion.local. 300 IN  SRV  0 0 2379 node3.hexfusion.local.
```

**Comment by WandyLau** [comment]
@hexfusion thanks. I am not familiar with this. And I googled, I can not find it. So I just ask. I will read this.

**Comment by hexfusion** [comment]
https://en.wikipedia.org/wiki/SRV_record
