### ISSUE TITLE
documentation: close watcher to avoid etcd clientv3 memory leak problem

### ISSUE THREAD

**Issue by barnettZQG** [coreos/etcd#9103]
# Bug reporting
![image](https://user-images.githubusercontent.com/18493394/34603717-15ca8182-f240-11e7-99d0-594a242a3242.png)
This is one of our service memory based on etcd,The result is that the etcd client memory is not released.
In our use case, the "v3. Client" object is repeated for the Watch operation, should we close the Client at the end of the Watch?

**Comment by xiang90** [comment]
can you provide a simple script to reproduce this issue?

**Comment by gyuho** [comment]
Do you create clientv3 for every watch? How do you use watch in your code?

**Comment by adityadani** [comment]
@barnettZQG We had seen similar memory usage profile in etcd client code, but most probably the culprit would be the caller of Watch API.

In our case we were incorrectly closing the Watch causing the etcd client watch to still get all the updates even if there was no one processing them.

**Comment by barnettZQG** [comment]
@adityadani @gyuho 
```
//WaitPrefixEvents WaitPrefixEvents
func WaitPrefixEvents(c *clientv3.Client, prefix string, rev int64, evs []mvccpb.Event_EventType) (*clientv3.Event, error) {
	wc := c.Watch(context.Background(), prefix, clientv3.WithPrefix(), clientv3.WithRev(rev))
	if wc == nil {
		return nil, ErrNoWatcher
	}
	return waitEvents(wc, evs), nil
}

func waitEvents(wc clientv3.WatchChan, evs []mvccpb.Event_EventType) *clientv3.Event {
	i := 0
	for wresp := range wc {
		for _, ev := range wresp.Events {
			if ev.Type == evs[i] {
				i++
				if i == len(evs) {
					return ev
				}
			}
		}
	}
	return nil
}
```
I use this in my code，for each GRPC call, I will call the WaitPrefixEvents method using the same client. The client does not close until the process exits. I didn't find the watch's closing method

**Comment by gyuho** [comment]
What's your etcd server and client version? And workloads?

**Comment by barnettZQG** [comment]
Should the following changes be made:
```
//WaitPrefixEvents WaitPrefixEvents
func WaitPrefixEvents(c *clientv3.Client, prefix string, rev int64, evs []mvccpb.Event_EventType) (*clientv3.Event, error) {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	wc := c.Watch(ctx, prefix, clientv3.WithPrefix(), clientv3.WithRev(rev))
	if wc == nil {
		return nil, ErrNoWatcher
	}
	return waitEvents(wc, evs), nil
}
```

**Comment by gyuho** [comment]
If you cancel context, watcher will be closed. It's ok to have long running watch stream with context background.

**Comment by barnettZQG** [comment]
Because my external method is called every time, I create watch. If you don't close, you will cause the problem @adityadani  describe, causing a memory leak

**Comment by xiang90** [comment]
@gyuho @spzala 

we probably should document that watcher MUST be closed by cancelling the context after use, or memory leak will happen.

**Comment by gyuho** [comment]
Yeah maybe add a few more lines around https://github.com/coreos/etcd/blob/65464838ba7d2ddbc282f0330153e4fb999ac598/clientv3/watch.go#L51?

**Comment by xiang90** [comment]
@gyuho sure.
