### ISSUE TITLE
Documentation: write a debugging/bug filing doc

### ISSUE THREAD

**Issue by philips** [coreos/etcd#911]
We need to write a basic guide to point people to on how to debug etcd based on our time debugging stuff in #coreos and etcd-dev.

- Tell people to use kill -QUIT $PID when things are locked up
- Asking people for the log from the journal
- other ideas?

/cc @robszumski

**Comment by xiang90** [comment]
@kelseyhightower Can you try to work on this? 

things to be reported: 
reproduce the problem with simple setup (no other dependencies for the best)

etcd printed log

etcd data log/snapshot if possible

**Comment by brianredbeard** [comment]
@barakmich Can we get some traction on this?
