### ISSUE TITLE
print out the request detail when it takes too long to process

### ISSUE THREAD

**Issue by xiang90** [coreos/etcd#9111]
We print out a warning if some requests take more than 100ms to execute. However, we do not print out the details of these requests, which make it harder for users to locate the bad requests.

We can do a better job to print it out in etcdserver/apply.go, and also add metrics around apply duration.

**Comment by hexfusion** [comment]
@xiang90 this looks interesting, do you think it would make sense for me to take a look at this?

**Comment by xiang90** [comment]
@hexfusion 

sure. right now the printing is at here:https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L800-L804. it is too coarse grind. 

you can trigger this warning by range over 100k keys in one range request.
