### ISSUE TITLE
how about some etcd-proxy metrics 

### ISSUE THREAD

**Issue by WIZARD-CXY** [coreos/etcd#9126]
Now we have etcd server metrics https://coreos.com/etcd/docs/latest/metrics.html. I wonder how about some etcd-proxy metrics like recording the get_key latency,For example promethus-like metrics:
get_etcd_key_latency_ms{key="etcd/version"} 1

**Comment by hexfusion** [comment]
Hi @WIZARD-CXY, we do have Promethus metrics setup for various proxies. For example gRPC proxy https://github.com/coreos/etcd/blob/master/proxy/grpcproxy/metrics.go. But we could use some help with documenting them it seems :). Would you be interested in helping us out with that?

I think once we have these documented we could look at what is missing and have a conversation about what is lacking?

Possible Steps:

- Setup Prometheus for etcd.

- Run traffic through proxy and see if you can populate some of the grpc_proxy metrics. Watchers?

- Extend documentation with a PR.

- Review how we added new metrics in the past https://github.com/coreos/etcd/commit/0cb680800e10839dddfe7af5a4b98c806113c2fb

- Add a PR for missing metrics.

- Profit :)

Let us know if you have any troubles or questions.

**Comment by WIZARD-CXY** [comment]
@hexfusion thanks for your guidance. I need some api client related metrics, e.g. get_etcd_key_latency_ms{key="etcd/version","client_addr": "10.1.10.1:54905"} 1

**Comment by WIZARD-CXY** [comment]
yeah documenting the existing one is nice, I think maybe I can lend a hand.

**Comment by xiang90** [comment]
@WIZARD-CXY You shall enable the grpc client's metrics in the proxy. then you will get what you want. Example here: https://github.com/coreos/etcd/blob/master/clientv3/example_metrics_test.go#L33-L40

If you want to know the overall latency from client <-> proxy <-> etcd, enable the metrics at your application side too.

**Comment by xiang90** [comment]
@WIZARD-CXY Send a PR to add a flag to grpc proxy to enable the extensive client metrics please. Thank you.

**Comment by WIZARD-CXY** [comment]
@xiang90 thanks a lot

**Comment by WIZARD-CXY** [comment]
@xiang90 seems proxy already has some client metrics
![2018-01-15 10 51 01](https://user-images.githubusercontent.com/2142864/34925561-02b8d98e-f9e5-11e7-8a02-2d59358b7f51.png)

**Comment by WIZARD-CXY** [comment]
AFAIK, the grpc proxy metrics does not record the client address and key prefix that we request. That's what I need e.g. ```
get_etcd_key_latency_ms{key="etcd/version","client_addr": "10.1.10.1:54905"} 1
```

**Comment by xiang90** [comment]
@WIZARD-CXY if you want client_addr, ask here https://github.com/grpc-ecosystem/go-grpc-prometheus.

i feel it is not a good thing to add in general. it can explode metrics tagging since the number of different clients can be "unlimited".

if you want to track client side behavior, you should track it at your application side in general.

**Comment by WIZARD-CXY** [comment]
@xiang90 I agree with u.

**Comment by WIZARD-CXY** [comment]
@hexfusion If you need some help documenting the existing one, ping me. I close this issue because I and xiang90 agree this is not a good thing to do now

**Comment by hexfusion** [comment]
Understood, your help is always welcome. :)
