### ISSUE TITLE
v3.3.0-rc.0 --rev, return error

### ISSUE THREAD

**Issue by lyddragon** [coreos/etcd#9127]
# watch,  return all revision
$ ETCDCTL_API=3 /usr/local/etcd/etcdctl watch 'bar' --rev=8 -w json|jq
{
  "Header": {
    "cluster_id": 8850367152553793000,
    "member_id": 371247452853820740,
    "revision": 10010,
    "raft_term": 4
  },
  "Events": [
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10002,
        "version": 1,
        "value": "ZG9vdDE="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10003,
        "version": 2,
        "value": "ZG9vdDI="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10004,
        "version": 3,
        "value": "ZG9vdDM="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10005,
        "version": 4,
        "value": "ZG9vdDQ="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10006,
        "version": 5,
        "value": "ZG9vdDU="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10007,
        "version": 6,
        "value": "ZG9vdDY="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10008,
        "version": 7,
        "value": "ZG9vdDc="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10009,
        "version": 8,
        "value": "ZG9vdDg="
      }
    },
    {
      "kv": {
        "key": "YmFy",
        "create_revision": 10002,
        "mod_revision": 10010,
        "version": 9,
        "value": "ZG9vdDk="
      }
    }
  ],
  "CompactRevision": 0,
  "Canceled": false,
  "Created": false
}

# get, no data return
$ ETCDCTL_API=3 /usr/local/etcd/etcdctl get 'bar' --rev=8     # no data return 
$ ETCDCTL_API=3 /usr/local/etcd/etcdctl get 'bar' 
bar
doot9

**Comment by gyuho** [comment]
@lyddragon I think you are confused with key version and global create/modify revision.

Version is per key.
And the `---rev` is the revision to start watch from.

If the key was written after revision 8, `get` request on the key would return 0.

**Comment by lyddragon** [comment]
How to get old version value of key?

**Comment by lyddragon** [comment]
thx
