### ISSUE TITLE
etcd with discovery.io

### ISSUE THREAD

**Issue by WandyLau** [coreos/etcd#9131]
I tried the discovery.io service. And I found that I can not config a real https service, by which I mean that the https can only be used as a hostname, but not a cert configured real one ssl or tls.

So I wonder if it does not support ssl or tls? Or I missed some?

**Comment by hexfusion** [comment]
Hi, please post your config and logs we can’t help you unless we can see that information.

**Comment by WandyLau** [comment]
I use the discovery.etcd.io repo to start up a private discovery service. The cluster is bootstrapped with cert.And I start the discovery service as:

    #./discovery -e https://localhost:2379

The etcd booted as

    /usr/bin/etcd --name=default --client-cert-auth 
    --trusted-ca-file=/etc/kubernetes/ca.pem \
    --cert-file=/etc/kubernetes/etcd-client.pem \
    --key-file=/etc/kubernetes/etcd-client-key.pem \
    --peer-cert-file=/etc/kubernetes/etcd-server.pem \
    --peer-key-file=/etc/kubernetes/etcd-server-key.pem \
    --advertise-client-urls=https://127.0.0.1:2379 \
    --listen-client-urls=https://0.0.0.0:2379 \
    --data-dir=/var/lib/etcd/default.etcd

So I think this discovery service is OK, right?

when I try to get the toke with:

    curl -v -X PUT localhost:8087/new 
and 
    curl --cacert /path/to/cacert --cert /path/to/etcd-client.pem --key /path/to/etcd-client-key.pem
    -X PUT localhost:8087/new

Both command will not get the token link as the public discovery service.
So I think the second command is supposed to be right. but I got error like:

    `Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to localhost (127.0.0.1) port 8087 (#0)
    > PUT /new HTTP/1.1
    > Host: localhost:8087
    > User-Agent: curl/7.52.1
    > Accept: */*
    > 
    setupToken returned: Couldn't setup state <nil> client: endpoint https://localhost:2379 exceeded 
    header timeout
    127.0.0.1 - - [11/Jan/2018:02:08:51 +0000] "PUT /new HTTP/1.1" 400 25
    < HTTP/1.1 400 Bad Request
    < Content-Type: text/plain; charset=utf-8
    < X-Content-Type-Options: nosniff
    < Date: Thu, 11 Jan 2018 02:08:52 GMT
    < Content-Length: 25
    < 
    Unable to generate token
    * Curl_http_done: called premature == 0
    * Connection #0 to host localhost left intact`

I try to debug the code. But this seems a little difficult. So please give some clue on this error. Thanks.

**Comment by WandyLau** [comment]
@gyuho I saw there is a public discovery service, is it brought up by this repo? Try to change `--host` flag? I have tried that but the hostname can not be resolved. Should I use the host name in `/etc/hosts`?

**Comment by WandyLau** [comment]
@gyuho Hi, I wonder if no body ever maintains this repo, why the public discovery io service is still available. This service is from this repo, right?

BTW, are you going to abandon this project?

**Comment by gyuho** [comment]
I wouldn't say it's abandoned. We didn't have enough bandwidth and people to maintain it, at least for now.

**Comment by WandyLau** [comment]
OK, if possible. I will try to do it then.

**Comment by hexfusion** [comment]
How are you doing @WandyLau? I might be able to take a closer look if you are still stuck. First, can you explain your use case vs using the public service https://discovery.etcd.io https://coreos.com/os/docs/latest/cluster-discovery.html ?

**Comment by WandyLau** [comment]
@hexfusion Thanks for you reply. As I found this `https` is not real one, right? It is just a name, not with TLS implemented. And my problem above is not solved. I am occupied recently to investigate it.
If you can help, I will be very grateful.

**Comment by gyuho** [comment]
Closing.

Sorry, discovery.etcd.io is not maintained anymore.
