### ISSUE TITLE
Gopath resolve error when read the code in IDEA

### ISSUE THREAD

**Issue by GhostComputing** [coreos/etcd#9132]
## Problem

When I read the source code in IDEA (only use `GOPATH`={PWD}/gopath), the IDEA(maybe the Go plugin) will produce the error like: "has no buildable Go source files".

Seems the same problem [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000706284--golang-support-for-projects-where-GOPATH-contains-a-symbolic-link)

### IDEA

IntelliJ IDEA 2017.3.2 (Ultimate Edition)
Build #IU-173.4127.27, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

### Go Plugin

Go v173.4381.1

### Go Version

go 1.9.2

### GOPATH Setting

![image](https://user-images.githubusercontent.com/1625098/34808388-913c883c-f6c9-11e7-8942-998e0e5c015f.png)

### Error Screenshot

![image](https://user-images.githubusercontent.com/1625098/34808401-b1c9b822-f6c9-11e7-94a2-41f55178bccf.png)

## How to reproduce

- Clone the code

- Create the new project of Go ( already install Go plugin)

- Set the GOPATH ( don't use the system settings)

- After indexing, you will see the same problem

**Comment by xiang90** [comment]
i do not think this is an etcd issue. i do not use IDEA personally either. maybe someone uses that can help you future. but i am going to close this issue since it is not etcd related.
