### ISSUE TITLE
etcd/raft library  usage?

### ISSUE THREAD

**Issue by lihailei2016** [coreos/etcd#9134]
Why I refer to raft - example to implement a raft application, the result only when the application starts, commitC there is data channel, starts, to proposeC channel data, send the need for consensus in commitC has been no news, don't have anything to do and I am a single node test?

**Comment by GhostComputing** [comment]
Maybe you need to read `etcd/contrib/raftexample`, it's a very simple example to show you how to use `etcd/raft`.

**Comment by xiang90** [comment]
I am going to close this as @GhostComputing provided a good answer already.
