### ISSUE TITLE
The bool true returned by API /health does not work with Kubernetes v1.9.1

### ISSUE THREAD

**Issue by henrywang** [coreos/etcd#9141]
The etcd exposes health information via HTTP at /health in JSON format. If it returns {"health": "true"}, then the cluster is healthy.
There's a bool type value got returned since 3.3.0. But when it integrated with Kubernetes, the Kubernetes component status check will report an error.

```shell
$ etcdctl -v
etcdctl version: 3.3.0-rc.1
API version: 2

$ curl -L http://127.0.0.1:2379/health
{"health":true}
```

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl get componentstatuses
NAME                 STATUS      MESSAGE           ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-0               Unhealthy   {"health":true}   json: cannot unmarshal bool into Go struct field etcdHealth.health of type string
```

**Comment by henrywang** [comment]
I reported this issue on Kubernetes as well. https://github.com/kubernetes/kubernetes/issues/58240

**Comment by hexfusion** [comment]
Hi @henrywang I am going to close this as it is a documented change for etcd. Thank you for keeping the Kubernetes community up to date on the change.

**Comment by charles4cicy** [comment]
I met the same problem in Kubernetes v1.8.6.


[root@promote charles]# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:23:29Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

[root@promote charles]# kubectl get componentstatuses
NAME                 STATUS      MESSAGE           ERROR
controller-manager   Healthy     ok                
scheduler            Healthy     ok                
etcd-0               Unhealthy   {"health":true}   json: cannot unmarshal bool into Go struct field etcdHealth.health of type string

**Comment by hexfusion** [comment]
FWIW it seems that the supported version of etcd is 3.1.10. This issue reported will only happen with etcd 3.3+. This has been documented in the v3.3 [release notes](https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_3.md#change-in-health-endpoint-response-value). I am going to leave it at this as we have provided plenty of details for anyone who may stumble upon it..

https://github.com/kubernetes/kubernetes/blob/32dc50476e6750774da96fa54989098bd0169f03/cmd/kubeadm/app/constants/constants.go#L235-L241
