### ISSUE TITLE
Hidden nodes in etcd v3

### ISSUE THREAD

**Issue by NoxisStyle** [coreos/etcd#9146]
Hi,

Do hidden nodes (using the underscore prefix) still exist in etcd v3?
I saw in this [issue ](https://github.com/coreos/etcd/issues/898) that it would still be supported in v2 but would disappear in v3.

I am using etcd with SkyDNS 2 in order to store DNS SRV information which can contain underscores. 
e.g.
/skydns/local/cluster/myservice/_tcp/_http

In the meantime I need to monitor ('watch') etcd for changes, which seems impossible as some keys are considered as hidden.

Is there a way to handle this ?

regards,

**Comment by xiang90** [comment]
i do not quite follow your use case. can you provide more details? do you mean that you do not want to watch the hidden key changes but all other keys?

**Comment by NoxisStyle** [comment]
Not exactly, I'll clarify my need.

What I expect is, for instance, to make a recursive watch at **/skydns/local/cluster** and be notified when child nodes are added
e.g
/skydns/local/cluster/myservice1/_tcp/_http
/skydns/local/cluster/myservice2/_tcp/_http/myInstance

NB: The use of the underscore is only used in order to follow the form of DNS SRV records. Unfortunately, it is also considered by etcd as a hidden node, which in this case is not the intent.
As a result, changes are not notified in these cases.

Is there a way to achieve this ?

**Comment by gyuho** [comment]
> also considered by etcd as a hidden node

Can you clarify? There's no such thing as hidden node in v3.

**Comment by NoxisStyle** [comment]
I double-checked and discovered that I was not using the "--prefix" option of of etcdctl. Therefore watch was not returning anything. I falsly thought that it was because of the underscores.

As a matter of fact, it seems that undersocores are no longer considered as hidden nodes in etcd v3.

Thanks.
