### ISSUE TITLE
question about raft

### ISSUE THREAD

**Issue by jacky1193610322** [coreos/etcd#9148]
###recently, I'm learning the raft and view the etcd-raft to help me learn, 
but there are some questions.
1. what happened when the leader cannot replicate to the majority?
if the network is ok, but when the leader broadcast the propose, the majority of nodes fail maybe because of the full disk or full memory or something else, how should I do?
if I respond the client failure, if the leader down, and the follower maybe have the value which will commit later，and when the client read it, it has the  #value,
if the server doesn't response the client，the client will timeout,
it's ok because timeout means success or failure, but I think it's not good.

2. if the Follower's last log different with the leader's prevLogTerm and prevIndex, the follower will response false and the leader will decrease the nextIndex, but if the follower fails with other reason, for example, full disk, it will response false too, how can leader distinguish the situation. the raft doesn't describe.

**Comment by gyuho** [comment]
Can you separate questions or clarify a bit more on what you are asking?

For first question, if you are talking about raft in etcd server, the follower will overwrite its data with snapshot from leader. The follower only starts applying snapshot once the snapshot message has been committed, so leader would either been notified of its sending message failure or successfully send snapshot to follower, where follower fails to apply due to disk outage. It really depends on what kind of failure scenario you are thinking about.

If follower fails for whatever reason, the applied index won't be updated, thus it's safe against crash.

**Comment by jacky1193610322** [comment]
Thank you for your replying. I'm sorry.
1. what happened when the leader cannot replicate to the majority?
the raft says: the leader will commit when it receives success from the majority of nodes,
but if it doesn't exceed the quorum, for example, there are 5 nodes a,b,c,d,e.
a is the leader,  it receives the client's request, then broadcast the propose to the followers, if c,d,e fail with full disk or something but the network is ok, it will respond the failure to the leader or doesn't respond. in the end, the leader only receives a success from b, what should the leader respond the client?
 1) the leader respond the client failure, but the b success, the raft doesn't support delete operation to delete the value in the b, if the leader down, and the follower b maybe become the leader which will commit the value later，and when the client read it, it has the value, but we just respond the client failure.
 2) if the server doesn't response the client，the client will timeout,
     it's ok because timeout means success or failure, but I think it's not good.

2. the follower will respond the false or doesn't respond to the leader when the follower fails with full disk or others?

**Comment by gyuho** [comment]
> in the end, the leader only receives a success from b, what should the leader respond the client?

You lost 3 members out of 5, so there is no leader. Cluster halts and cannot serve any requests.

> the leader respond the client failure

What do you mean by respond to client failure?

> follower will respond the false or doesn't respond to the leader when the follower fails with full disk or others?

Follower is just another node in the cluster. If the disk is full, the follower process would just terminate.

Again, if the snapshot apply or send fails, the apply index won't be updated in follower, so the failure would be retried in the next reboot.

**Comment by jacky1193610322** [comment]
Thank you very much, I think I didn't describe clearly.

> 1. the follower will respond the false or doesn't respond to the leader when the follower fails with full disk or others?

I mean each system call maybe fail. for example malloc or write. if the error happens, will the follower respond the failure or doesn't respond when an error happens in the middle of handling the proposal? 
for example.
p_malloc = malloc(20);
if (p_malloc == NULL){
     return error_code;
}
handle(propose);

malloc is just an example, I just want to describe an error happen in the middle of handling the proposal, the proposal doesn't handle successfully,  Will the follower respond the false or doesn't respond to the leader?

**Comment by gyuho** [comment]
> will the follower respond the failure or doesn't respond when an error happens in the middle of handling the proposal?

Doesn't matter. If leader has not receive response from follower, it will retry. Leader keeps track of its replication progress for each peer.
