### ISSUE TITLE
api/maintenance: add alarm/health information in endpoint status

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#9163]
https://github.com/coreos/etcd/pull/9162 removes `"errors"` field from `/health` endpoint.

Better place to serve this information is `etcdserverpb.StatusResponse`. Probably, just add another `repeated` field of `errors`.

**Comment by gyuho** [comment]
@dvonthenen Do you want to work on this (very similar to https://github.com/coreos/etcd/pull/9176)?

**Comment by dvonthenen** [comment]
Sure thing! If you have any other ones, just let me know.

**Comment by dvonthenen** [comment]
@gyuho Do we want to also expose these errors on the etcdctl table output?

**Comment by gyuho** [comment]
@dvonthenen Yes. Thanks!

**Comment by dvonthenen** [comment]
No problem

**Comment by dvonthenen** [comment]
PR https://github.com/coreos/etcd/pull/9206 submitted

**Comment by dvonthenen** [comment]
I believe this issue can be closed since PR https://github.com/coreos/etcd/pull/9206 has been merged. Thanks!

**Comment by xiang90** [comment]
@dvonthenen thanks for the contribution.
