### ISSUE TITLE
etcdctl snapshot mixes stdout and stderr

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd#9179]
`etcdctl snapshot restore` command mixes stdout and stderr message into stderr. This is due to capnslog sets it by default:
https://github.com/coreos/etcd/blob/0f1ac0cef6834f0927dec74b0f0bf4d0dad9b763/cmd/vendor/github.com/coreos/pkg/capnslog/init.go#L36

It is better to only write error messages into stderr.

**Comment by hongchaodeng** [comment]
```
2018-01-19 23:42:54.398661 I | pkg/netutil: resolving test-etcd-backup-restore-0-0000.test-etcd-backup-restore-0.e2e-etcd-operator-flaketest-580.svc:2380 to 10.28.5.36:2380
2018-01-19 23:42:54.402454 I | pkg/netutil: resolving test-etcd-backup-restore-0-0000.test-etcd-backup-restore-0.e2e-etcd-operator-flaketest-580.svc:2380 to 10.28.4.183:2380
Error:  --initial-cluster must include test-etcd-backup-restore-0-0000=https://test-etcd-backup-restore-0-0000.test-etcd-backup-restore-0.e2e-etcd-operator-flaketest-580.svc:2380 given --initial-advertise-peer-urls=https://test-etcd-backup-restore-0-0000.test-etcd-backup-restore-0.e2e-etcd-operator-flaketest-580.svc:2380
```

From user's perspective, only the error message should go into stderr, i.e. last line with `Error`. The first two lines look like logging messages, and as a user I would expect them go into stdout.

**Comment by xiang90** [comment]
what messages you see went into stdout? 

it is wrong that only error should go to stderr. users should expect only result of the command goes (the matched text of grep command for example) into stdout, which is the common practice of unix program. All informational or diagnostic messages go to stderr.

**Comment by hongchaodeng** [comment]
I agree with that. But is the "resolving ..." messages considered "diagnostic message"? Because the last line should contain enough message to diagnose.

**Comment by xiang90** [comment]
> I agree with that. But is the "resolving ..." messages considered "diagnostic message"? Because the last line should contain enough message to diagnose.

yes. it is informational not the executing result of the command. it should go to stderr.

**Comment by xiang90** [comment]
closing this out since etcdctl does the right thing.
