### ISSUE TITLE
github.com/hashicorp/go-msgpack is a really old unmaintained fork

### ISSUE THREAD

**Issue by nim-nim** [coreos/etcd#9186]
Hi,

Now that https://github.com/ugorji/go/ made its first stable and supported release, maybe it's time to use it directly instead of vendoring github.com/hashicorp/go-msgpack which is an old unmaintained fork from 2015 which his lagging hundreds of commits behind?

**Comment by gyuho** [comment]
@nim-nim We do not use `github.com/hashicorp/go-msgpack`?

**Comment by hexfusion** [comment]
@nim-nim perhaps you should make issue here :)

https://github.com/hashicorp/consul/issues

**Comment by nim-nim** [comment]
Sorry for the confusion !

**Comment by nim-nim** [comment]
(I think it got pulled in my etcd builds through unit tests)

**Comment by hexfusion** [comment]
@nim-nim no worries Consul is using it so letting them know might not be soo bad either :+1:

**Comment by nim-nim** [comment]
Actually I was right etcd does use this old umaintained fork

It's real sneaky, it is used to generate files, but they are only regenerated if client/keys.generated.go is removed and github.com/hashicorp/go-msgpack is available

So you won't find it in import paths even though etcd needs it

**Comment by nim-nim** [comment]
(so this should probably be reopened)

**Comment by hexfusion** [comment]
@nim-nim 

It seems to me that etcd shares a common codec package that we **do** vendor. 

`github.com/ugorji/go/codec`

```bash
client/keys.generated.go:15:    codec1978 "github.com/ugorji/go/codec"
```

But I don't see anywhere how this brings in that package your talking about.

**Comment by nim-nim** [comment]
I *think* that once upon a time it was done through github.com/hashicorp/go-msgpack
 
If it's done directly nowadays, that's all for the best, just needs to make sure it uses the stable release of github.com/ugorji/go/codec

**Comment by hexfusion** [comment]
thanks for looking out @nim-nim !
