### ISSUE TITLE
etcd3 golang STM client does not Support Range fetch over keys?

### ISSUE THREAD

**Issue by amansardana** [coreos/etcd#9188]
I am trying to use STM client in my project for transaction purpose. I need to:

1.) Query keys between particular range 
2.) Query keys with specified prefix

in the transaction. But i wasn't able to find a function which provides this functionality in STM interface. There is Get(keys ...string) function but it does not have any OpOptions parameter.

Is there some particular reason that it has been left out and what is the best way to do this.

**Comment by hexfusion** [comment]
@amansardana  this is a duplicate issue. Please review https://github.com/coreos/etcd/issues/7383
