### ISSUE TITLE
Feature Request: Ability to pick source IP address

### ISSUE THREAD

**Issue by doekerqhtv** [coreos/etcd#9193]
I have a use case where I need to specify an outgoing IP address. Currently etcd does not support ability to pick outgoing IP address. 

On a system with multiple IP addresses, I would like to be able to specify the exact IP address for outgoing client connectivity.

**Comment by xiang90** [comment]
i do not quite understand this issue. can you be more specific, and provide us an example?

**Comment by doekerqhtv** [comment]
I have a system with multiple interfaces and IP addresses. The etcd, when communicating with peers, will pick an IP address based on the routing table. I would like to specify the outgoing IP address (bound to the system) for peer connectivity.

**Comment by xiang90** [comment]
> The etcd, when communicating with peers, will pick an IP address based on the routing table. 

How do you config etcd today? What are the listening and advertise urls of peers?

**Comment by doekerqhtv** [comment]
Basically, 
I need a new configuration flag added in etcd/etcdmain/config.go:
fs.StringVar(&cfg.ec.LocalAddr, "local-address", cfg.ec.LocalAddr, "LocalAddress bind for outgoing peer connections") 
and dialSetupOpts extended in clientv3/client.go via Net.Dial to specify source IP.

**Comment by xiang90** [comment]
@doekerqhtv 

oh. ok. i understand you now. so you want to choose the IP source address when etcd peer acts a client when connecting to the other etcd server.

**Comment by doekerqhtv** [comment]
Correct.

**Comment by xiang90** [comment]
would you like to help on this feature? do you know how other systems call this flag or configuration?

**Comment by doekerqhtv** [comment]
I believe net dial takes "LocalAddr" to make this happen.

**Comment by doekerqhtv** [comment]
Also, this should be optional setting. Not specifying it, should leave things as they are today.

**Comment by xiang90** [comment]
local/source seems OK to me. just want to make sure we are consistent with conventions. would you like to send a PR to add this feature?

**Comment by doekerqhtv** [comment]
Sure. I will try to make one.

**Comment by doekerqhtv** [comment]
I think I have the patch available.

**Comment by fanminshi** [comment]
@doekerqhtv could you submit an pr with test? that will help the maintainer to review the patch.

**Comment by doekerqhtv** [comment]
I think I messed up on the PR, if someone can delete it.

**Comment by fanminshi** [comment]
@doekerqhtv it is all good. i closed that pr.  

pr workflow.
1. fork etcd reop to your github account
2. download etcd repo from your account
3. create a feature branch
4. modify code in the feature branch.
5. commit and push.
6. go to etcd repo. you should see an banner mentioning about creating an pull request.
7. click the banner to create the pull request.

**Comment by doekerqhtv** [comment]
Sorry - first time doing this. 

$ git push --set-upstream origin local-address-bind
remote: Permission to coreos/etcd.git denied to doekerqhtv.

**Comment by fanminshi** [comment]
@doekerqhtv  you need to first fork etcd repo to you github account. I don't see any etcd repo under your name.

**Comment by fanminshi** [comment]
@doekerqhtv a good tutorial https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by gyuho** [comment]
I think this is out of etcd scope. Peer traffic can be controlled though through `host-whitelist` flag https://github.com/coreos/etcd/blob/master/CHANGELOG-3.4.md#security-authentication. You can still limit access with auth + TLS. And there are many other lower level linux tools to achieve outbound traffic. Please create a separate issue if you have other valid use cases. Thanks.
