### ISSUE TITLE
can *.wal format file be used to recover etcd data?

### ISSUE THREAD

**Issue by knightXun** [coreos/etcd#9214]
Yesterday, I found my stand-alone etcd crashed.I tried to recover etcd,but the db file is broken.All content of db is '^@'. Now only *.wal file has valid content. but i don't know how to use it.Does comunity provide related tools? Or my data totally broken and can't be taken back.

Etcd version is: v3.2.5

**Comment by gyuho** [comment]
> I tried to recover etcd,but the db file is broken

How? Did you manually overwrite db file?

WAL is only for raft entries, agnostic of key-value structure. And etcd periodically discard previous entries, so mostly likely your old data is already deleted.

**Comment by xiang90** [comment]
closing. @gyuho provides great answer already.
