### ISSUE TITLE
Distributed lock with lease

### ISSUE THREAD

**Issue by rselbach** [coreos/etcd#9218]
Hi, we're trying to use distributed locking in a project but we're having some trouble getting them to work. Maybe we don't get how they're supposed to work. We have a little test case here that should reproduce the problem:

```
package main

import (
	"context"
	"fmt"
	"log"

	"time"

	"github.com/coreos/etcd/clientv3"
	"github.com/coreos/etcd/clientv3/concurrency"
)

func main() {
	cli, err := clientv3.New(clientv3.Config{Endpoints: []string{"localhost:2379"}})
	if err != nil {
		log.Fatal(err)
	}
	defer cli.Close()

	// get a grant
	ctxc, cancelc := context.WithTimeout(context.Background(), 1*time.Second)
	lresp, err := cli.Grant(ctxc, 2)
	if err != nil {
		log.Fatal(err)
	}
	defer cancelc()
	fmt.Println("lease", lresp.ID)

	// create two separate sessions for lock competition
	s1, err := concurrency.NewSession(cli, concurrency.WithLease(lresp.ID))
	if err != nil {
		log.Fatal(err)
	}
	defer s1.Close()
	m1 := concurrency.NewMutex(s1, "/xxxsx/")

	s2, err := concurrency.NewSession(cli)
	if err != nil {
		log.Fatal(err)
	}
	defer s2.Close()
	m2 := concurrency.NewMutex(s2, "/xxxsx/")

	// acquire lock for s1
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	if err := m1.Lock(ctx); err != nil {
		log.Fatal("timeout", err)
	}
	defer cancel()
	fmt.Println("acquired lock for s1")

	m2Locked := make(chan struct{})
	go func() {
		defer close(m2Locked)
		// wait until s1 is unlocked /xxxsx/
		if err := m2.Lock(context.TODO()); err != nil {
			log.Fatal(err)
		}
	}()

	<-m2Locked
	fmt.Println("acquired lock for s2")
}
```

As you can see, we get a grant with a TTL of 2 seconds : 

`lresp, err := cli.Grant(ctxc, 2)`

And this lease is used when we create the section:

`s1, err := concurrency.NewSession(cli, concurrency.WithLease(lresp.ID))`

We manage to acquire the lock correctly the first time, but the second `Lock` (from a goroutine) never returns.

Shouldn't the lock be unlocked when the lease expires?

**Comment by rselbach** [comment]
I think I [have my answer.](https://github.com/mixer/etcd3/issues/56#issuecomment-360200875). Thanks @connor4312.

However, that means that if I have a process that is in some sort of deadlock and never ends its session, the lock will never be unlocked and no other process will be able to acquire it. Is this so by design?

**Comment by xiang90** [comment]
@rselbach 

you need to either close the session (https://godoc.org/github.com/coreos/etcd/clientv3/concurrency#Session.Close) or disconnect the client from etcd. i do not think this is a deadlock. this is the intended behavior, and the right way to do locking.

**Comment by rselbach** [comment]
Thanks @xiang90, we'll work around it here. Just to be clear, I never said this was a deadlock. Cheers :)
