### ISSUE TITLE
all: reorganize "internal" Go packages

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#9220]
Packages like "alarm" and "compactor" are not expected to be used outside of etcd project.

Move all internal packages under `/internal/*`.

**Comment by xiang90** [comment]
lease, mvcc, store should be moved too.

**Comment by gyuho** [comment]
@mitake Could you double-check if it's safe for us to move `auth` package to `internal/auth`? `"github.com/coreos/etcd/auth"` is not meant to be used directly by clients. And also all errors are converted to `rpctypes`, so moving to `internal` won't break anything (e.g. clients will still receives error typed `rpctypes.ErrRoleAlreadyExist`, not `auth.ErrRoleAlreadyExist`).

**Comment by mitake** [comment]
@gyuho ok, I'll look at it

**Comment by mitake** [comment]
Moving the package to internal won't cause problems, I think. Should I create a PR for this? @gyuho

**Comment by gyuho** [comment]
@mitake Sure! Thanks!
