### ISSUE TITLE
Launch / debug etcd from intellij idea x64 (for learning)?

### ISSUE THREAD

**Issue by acxlam** [coreos/etcd#9235]
I am trying to launch the latest ETCD on windows from within Intellij Idea with MinGW installed, but with errors below. Any parameters would help? <br/>

~~~~
GOROOT=F:/portable/GO
GOPATH=F:/GOPATH
F:/portable/GO\bin\go.exe build -i -o D:\Users\ace.lam\AppData\Local\Temp\___main_go.exe F:/GOPATH/src/github.com/coreos/etcd/main.go
# command-line-arguments
F:\portable\GO\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
F:/MinGW/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status
~~~~

**Comment by hexfusion** [comment]
Hi @acxlam this is a Windows ENV issue, not etcd. Searching `ld.exe: cannot find -ldl` in google seems to shed some light. Please try to resolve these path/ENV issues and let us know if you have any issues related to etcd itself.

**Comment by hexfusion** [comment]
I am going to close this but feel free to reply here with additional comments/questions, thanks.
