### ISSUE TITLE
Handling election storms

### ISSUE THREAD

**Issue by anshulpundir** [coreos/etcd#9241]
This is more of a questions for the etcd/raft impl.

If there is a flaky raft member, it may drop in and out causing constant elections. 

This is because a flaky member can get partitioned from the rest of the raft peers and end up at a higher term. When this member rejoins, the current leader sees a message from this flake member at a higher term and this causes a new election. 

The question is if and how you this is handled in etcd. Thanks in advance for looking into it!

**Comment by xiang90** [comment]
The pre-vote feature is to solve this problem. It is not super stable right now. But we are working on stabilizing it.

**Comment by anshulpundir** [comment]
Can we prevent the leader from stepping down when it sees a message with higher term from the partitioned node unless the log term (or index, not sure of the correct terminology) for the partitioned node is greater than the log term for the current leader ? @xiang90

**Comment by xiang90** [comment]
@anshulpundir check out pre-vote as i just mentioned. the raft paper or the code explains much better than what i can do here on github.

**Comment by anshulpundir** [comment]
I don't see the term prevote in the raft paper https://raft.github.io/raft.pdf 
Is this specific to etcd/raft ?

@xiang90

**Comment by xiang90** [comment]
search here: https://ramcloud.stanford.edu/~ongaro/thesis.pdf

> Is this specific to etcd/raft ?

not sure if other raft impl has implemented this. but our raft does.

**Comment by xiang90** [comment]
I am going to close this out as the feature to avoid the issue exists already.
