### ISSUE TITLE
snapshot/restore --data-dir with existing directory

### ISSUE THREAD

**Issue by ry4nz** [coreos/etcd#9248]
I am trying to understand the reason why return error when the `--data-dir` specified exists. https://github.com/coreos/etcd/blob/902bdb474eb9086c3ebbac05e08ed373d2b103ec/snapshot/v3_snapshot.go#L217

An option to force restore that overwrites the existing `--data-dir` would be nice.

**Comment by gyuho** [comment]
This is to prevent overwriting existing WAL files, which is unsafe for most operations.
The overwriting logic can easily be implemented in your application layer?
