### ISSUE TITLE
error in the manual "guide to generating self-signed key pairs"

### ISSUE THREAD

**Issue by beatlejuse** [coreos/etcd#9253]
# Bug reporting

https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md
on this page of the documentation you describe "Transport security & client certificates" and use "ca.crt" and "member1.crt".
in the beginning you link to "guide to generating self-signed key pairs":
https://github.com/coreos/docs/blob/master/os/generate-self-signed-certificates.md
But this "guide to generating self-signed key pairs" guide describes the generation of "ca.pem", "server-key.pem", "server.pem" and other ".pem".
I think this guide is incomplete (or inaccurate), since the generation of demand ".crt" has not been reviewed.

[report_bugs]: https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md

**Comment by hexfusion** [comment]
HI @beatlejuse, thank you for the report.  Perhaps this code snippet might shed light on the .pem vs .crt.

https://github.com/coreos/etcd/blob/0b9dc9ccd355a9978a9ec1f91f64928da75de4b3/hack/scripts-dev/docker-dns/certs-common-name-multi/gencerts.sh#L13-L15

**Comment by hexfusion** [comment]
I think the documentation could use some work though. @beatlejuse would you like to create a PR with updates and we can talk about it?

**Comment by hexfusion** [comment]
Going to close this feel free to extend the documentation with a PR or continue the conversation here if you have more questions.

**Comment by beatlejuse** [comment]
@hexfusion  i'm testing it today.
if i use real ".crt" and ".key" file? i get error "tls: failed to find any PEM data in certificate input".
most likely expected certificates in pem format.
in that way, "Generate self-signed certificates" manual is right.
I think you need to correct the user manual "Transport security model".
and i don't like to create PR ))

**Comment by beatlejuse** [comment]
and yes, if i use certificates in PEM format - it's works!

**Comment by hexfusion** [comment]
Hi @beatlejuse the actual format of the files does **not** change if the file extension does right?

### please review

https://crypto.stackexchange.com/questions/43697/what-is-the-difference-between-pem-csr-key-and-crt

> if i use real ".crt" and ".key" file, i get error "tls: failed to find any PEM data in certificate input".

What do you mean by real .crt and .key? These are only file extensions. The documentation only shows how to generate PEM format certificates. It is common practice to append certificate file with .crt extension ie `mv ca.pem ca.crt`.

>and yes, if i use certificates in PEM format - it's works!

As I stated above changing the file extension does not change format.

**Comment by beatlejuse** [comment]
by real .crt and .key i mean  convertation PEM file to key and crt:
openssl x509 -outform der -in your-cert.pem -out your-cert.crt
openssl rsa -outform der -in private.pem -out private.key
if i convert it (not only rename) - i get error "tls: failed to find any PEM data in certificate input".
this means that expected files exactly in PEM format
and yes, changing the file extension does not change format, right!
instructions for generating certificates is correct.
all you need to fix - is the file extension in https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md
same as "--client-cert-auth --trusted-ca-file=/path/to/ca.crt --cert-file=/path/to/server.crt" to "--client-cert-auth --trusted-ca-file=/path/to/ca.pem --cert-file=/path/to/server.pem".

**Comment by hexfusion** [comment]
1.) does the docs say to convert PEM to DER format?

2.) did you review the link I sent regarding file extensions?

I can see the confusion I guess you are assuming that a file with extension .crt or .key should or must be in DER format. But that is simply not the case.

**Comment by beatlejuse** [comment]
1. explicitly it is not specified, but the specified file extensions hint at it
2. yes
3. I also see the confusion. I think to avoid confusion, it is necessary just to fix the documentation. at generation we get .pem files. and nowhere expressly stated that they simply rename. by the way, the second option is to explicitly specify the renamed files.

**Comment by hexfusion** [comment]
I agree the documentation should explicitly state that etcd expects pem format. Once we define that, the rest I think can stay the same. Can you give it a shot?

I think this is nice documentation on the process. 
https://gist.github.com/Chaser324/ce0505fbed06b947d962

I am eager to see what other areas of documentation you can help improve:) let me know if you need help and thanks for contributing!
