### ISSUE TITLE
Is there any configuration flag like sync_binlog to put off data saving?

### ISSUE THREAD

**Issue by alpha-li** [coreos/etcd#9261]
Given the poor performance of hard disk，leader election failure occured frequently? So I wonder if there is any conf flag like sync_binlog which exists in mysql to decrease the overhead of io request。

**Comment by hexfusion** [comment]
@alpha-li great question but I believe the answer is no. The tradeoff for using `sync_binlog` is safety and although it does improve performance it can in the case of failure cause data loss. For this reason in MySQL 5.7.7+ sync_binlog is true by default as a safety precaution. https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#sysvar_sync_binlog. The issue of data safety is even greater with a distributed database.

**Comment by xiang90** [comment]
@alpha-li As @hexfusion mentioned, the answer is no. etcd has to sync down everything to its WAL file before responding to any messages either from clients or from its peer in the cluster. Without syncing, it breaks the consistency/safety guarantees.

**Comment by xiang90** [comment]
@alpha-li if you want to learn more about the why part, you can read https://raft.github.io/raft.pdf
