### ISSUE TITLE
etcdv2 subsequent backup size increase issue/misunderstanding

### ISSUE THREAD

**Issue by nickkeyzer** [coreos/etcd#9264]
### Setup
Kubernetes v1.8.2 cluster deployed with Kubespray (test cluster will little activity)
Etcd version 3.2.4
CentOS 7.3.1611

### Issue
I'm trying to understand a phenomenon where my etcdv2 backups appear to be growing in size after each subsequent backup. My etcd DB is only 6.9MB (as reported by etcdv3 api) however my backups are much larger and keep growing which each new backup. I understand that backups will increase as more data is added to the store. However the size of the backup between my first and second backup doubled in size (62M to 123M) in backups taken just 3 minutes apart. 

Kubernetes 1.8.x uses etcdv3 however I'm running Flannel which relies on etcdv2. My understanding is that etcdv3 "snapshots" will not contain etcdv2 data. However, etcdv2 "backups" will contain both v2 and v3 mixed data.

Hopefully this is just a misunderstanding of how etcd is intended to function.

Here's my simple backup function in my script:
```bash
    export ETCDCTL_API=2
    /usr/local/bin/etcdctl backup \
        --data-dir $ETCD_DATA_DIR \
        --backup-dir $ETCD_BACKUP_DIRECTORY
```

Here's size of the backup directories (the first backup doubled in size 3 minutes later, note the timestamps):
```
# du -h -d 1
62M	./etcd-2018-01-31_14:07:59
123M	./etcd-2018-01-31_14:10:54
129M	./etcd-2018-01-31_14:23:08
152M	./etcd-2018-01-31_15:17:03
233M	./etcd-2018-02-01_10:36:50
```

And here's the output of `ETCDCTL_API=3 /usr/local/bin/etcdctl --endpoints https://10.12.26.75:2379,https://10.12.26.76:2379,https://10.12.26.77:2379 endpoint status -w table`:
```
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
|         ENDPOINT         |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
| https://10.12.26.75:2379 | c877ff6709942c1e |   3.2.4 |  6.9 MB |     false |        16 |    2853930 |
| https://10.12.26.76:2379 | c9d009145f7269c1 |   3.2.4 |  6.8 MB |     false |        16 |    2853930 |
| https://10.12.26.77:2379 | 923b66f7759cef1e |   3.2.4 |  6.8 MB |      true |        16 |    2853930 |
+--------------------------+------------------+---------+---------+-----------+-----------+------------+
```

I'm somewhat stumped here and I'd be happy to provide more information as needed.

Thanks

**Comment by xiang90** [comment]
db size only reflects the data in v3 database backend, not v2.

**Comment by xiang90** [comment]
there is no plan to make v3 api to understand any v2 data related stuff.

**Comment by nickkeyzer** [comment]
@xiang90 I understand that there is a difference between the v2 and v3 database backend. It doesn't seem that you read through my question entirely.

I wanted to know why the v2 backup command would consistently create backups that are considerably larger than the previous one. Why would the resulting backup file double in size from one that was take only 3 minutes prior? This cluster barely has any activity and we're not adding data to the store.

I'm trying to understand how this backup function is intended to work. I've already read the documentation for it but I still have questions based on my test.

Thanks
