### ISSUE TITLE
Certs for TLS auth question

### ISSUE THREAD

**Issue by eroji** [coreos/etcd#9270]
This is really a question as I am confused on what certs I need to generate to enable TLS auth for etcd in a kubernetes cluster. Following the guide: https://coreos.com/os/docs/latest/generate-self-signed-certificates.html, there are 3 category of certs. Server, client and peer. I am unsure which cert goes to which server type. What cert do I need to etcd nodes, which cert for kube master nodes? Also, I assume the kube worker nodes don't need any cert since it talks only to the masters?

**Comment by hexfusion** [comment]
@eroji does this document help? https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md

**Comment by eroji** [comment]
Immensely. Thank you!
