### ISSUE TITLE
Peer certificate with wildcard hostname not working

### ISSUE THREAD

**Issue by eroji** [coreos/etcd#9276]
Running 3 CentOS 7.4 nodes with etcd 3.2.11-1.el7. I am able to generate the CA, server, client and peer certs per https://coreos.com/os/docs/latest/generate-self-signed-certificates.html. I can confirm the server and client certs are definitely working. However, my nodes are unable to form successful peer connections with each others on startup.

I generated the peer cert with these param:
```
export ADDRESS="*.mydomain.com"
export NAME=peer
echo '{"CN":"'$NAME'","hosts":[""],"key":{"algo":"rsa","size":2048}}' \
     | cfssl gencert -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem -hostname="$ADDRESS" - \
     | cfssljson -bare $NAME
```

Peer settings in etcd.conf:
```
ETCD_PEER_CERT_FILE="/etc/etcd/tls/peer.pem"
ETCD_PEER_KEY_FILE="/etc/etcd/tls/peer-key.pem"
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
ETCD_PEER_AUTO_TLS="false"
```

When I start the nodes, I see these errors being logged:
```
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: b7e8b1c8346e3d56 [logterm: 1, index: 3] sent MsgVote request to 78886c6b59167b9 at term 130
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: b7e8b1c8346e3d56 [logterm: 1, index: 3] sent MsgVote request to a421b19894562278 at term 130
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: rejected connection from "10.1.130.156:54950" (error "remote error: tls: bad certificate", ServerName "")
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: rejected connection from "10.1.130.156:54956" (error "remote error: tls: bad certificate", ServerName "")
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: rejected connection from "10.1.130.156:54958" (error "remote error: tls: bad certificate", ServerName "")
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: rejected connection from "10.1.130.156:54964" (error "remote error: tls: bad certificate", ServerName "")
```

**Comment by hexfusion** [comment]
Hi @eroji please show us the full etcd.conf please.

**Comment by eroji** [comment]
Here you go. I removed the stuff that are commented out to be more concise.

```
ETCD_DATA_DIR="/var/lib/etcd/kube-etcd-01.etcd"
ETCD_LISTEN_PEER_URLS="https://10.1.130.155:2380"
ETCD_LISTEN_CLIENT_URLS="https://10.1.130.155:2379,https://127.0.0.1:2379"
ETCD_NAME="kube-etcd-01.mydomain.com"
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://10.1.130.155:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://10.1.130.155:2379"
ETCD_INITIAL_CLUSTER="kube-etcd-01=https://10.1.130.155:2380,kube-etcd-02=https://10.1.130.156:2380,kube-etcd-03=https://10.1.130.157:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"

ETCD_CERT_FILE="/etc/etcd/tls/kube-etcd-01.pem"
ETCD_KEY_FILE="/etc/etcd/tls/kube-etcd-01-key.pem"
ETCD_CLIENT_CERT_AUTH="true"
ETCD_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
ETCD_AUTO_TLS="false"
ETCD_PEER_CERT_FILE="/etc/etcd/tls/kube-etcd-01-peer.pem"
ETCD_PEER_KEY_FILE="/etc/etcd/tls/kube-etcd-01-peer-key.pem"
ETCD_PEER_CLIENT_CERT_AUTH="true"
ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
ETCD_PEER_AUTO_TLS="false"
```

**Comment by hexfusion** [comment]
@eroji `nslookup 10.1.130.156` ?

**Comment by eroji** [comment]
Works fine. Gets kube-etcd-02.mydomain.com.

**Comment by hexfusion** [comment]
Shouldn't the peer cert have its own CA?

```
ETCD_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
ETCD_PEER_TRUSTED_CA_FILE="/etc/etcd/tls/ca.pem"
```

**Comment by eroji** [comment]
BTW I generated the peer certs for each node using the same CA, without using wildcard hostname and that worked. The problem seems to be using the wildcard but documentation says it's supported since 3.2.5.

**Comment by hexfusion** [comment]
@eroji if your going to use FQDN as name

`ETCD_NAME="kube-etcd-01.mydomain.com"`

try this 

`ETCD_INITIAL_CLUSTER: kube-etcd-01.example.com=https://kube-etcd-01.example.com:2380,kube-etcd-02.example.com=https://kube-etcd-02.example.com:2380,kube-etcd-03.example.com=https://kube-etcd-03.example.com:2380`

**Comment by hexfusion** [comment]
I think it works but my reverse DNS isn't resolving correctly so I am getting error like below which is expected.

`error "tls: \"10.1.130.155\" does not match any of DNSNames [\"*.example.com\"]", ServerName "kube-etcd-01.example.com"`

**Comment by eroji** [comment]
Thank you. I'll give it a try when I'm back in the office.

**Comment by eroji** [comment]
Service won't start with that configuration it seems.
`Feb 05 10:38:25 kube-etcd-01.mydomain.com etcd[16626]: couldn't find local name "kube-etcd-01.mydomain.com" in the initial cluster configuration`

**Comment by eroji** [comment]
Looks like that worked. Thank you!

**Comment by hexfusion** [comment]
@eroji, sure I am going to carve this out into the docs a bit better.

**Comment by hexfusion** [comment]
@gyuho is this a bug? For wildcard SAN to work cluster members must be defined by domain vs IP. I was going to update docs but why can't etcd perform a lookup on IP and then match against SAN as well? just not sure this is expected.

**Comment by hexfusion** [comment]
We for sure need better coverage in this area.

**Comment by gyuho** [comment]
>  is this a bug? For wildcard SAN to work cluster members must be defined by domain vs IP. I was going to update docs but why can't etcd perform a lookup on IP and then match against SAN as well?

If there's any IP in your SAN field, peer must have matching IP. If there's any domain in SAN field, we do additional checking but depends on the etcd version. Detailed auth logic can be found here https://github.com/coreos/etcd/blob/master/Documentation/op-guide/security.md#notes-for-tls-authentication.

@hexfusion Do we miss anything in that doc?

**Comment by hexfusion** [comment]
> @hexfusion Do we miss anything in that doc?

well what I find is that if you have cert SAN "*.example.local" and you define 

`ETCD_INITIAL_CLUSTER="kube-etcd-01=https://10.1.130.155:2380,kube-etcd-02=https://10.1.130.156:2380,kube-etcd-03=https://10.1.130.157:2380"`

even if nslookup 10.1.130.155 = 'kube-etcd-01.mydomain.com' which should be ok for SAN etcd gives error.

```
Feb 02 16:41:48 kube-etcd-01.mydomain.com etcd[12322]: rejected connection from "10.1.130.155:54964" (error "remote error: tls: bad certificate", ServerName "")
```

But if instead we use domains

`ETCD_INITIAL_CLUSTER="kube-etcd-01=https://kube-etcd-01.mydomain.com:2380,kube-etcd-02=https://kube-etcd-02.mydomain.com:2380,kube-etcd-03=https://kube-etcd-03.mydomain.com:2380"`
`
we seem to check the address of the peer member domain then reverse-lookup address to validate against SAN. So why not reverse lookup of IP in the first example? Maybe I am just confused but it seems wrong. The docs outline domain/IP in SAN but I see the difference between IP and domain when for example using the initial-cluster flag. This I feel is not documented or a possible bug?

**Comment by gyuho** [comment]
> reverse-lookup address to validate against SAN. So why not reverse lookup of IP in the first example?

I do not understand. If you need authenticate by IP, you just add IPs to your SAN field.

> rejected connection from "10.1.130.155:54964" (error "remote error: tls: bad certificate", ServerName "")

You probably get this because your SAN field only has IPs?

Initial cluster flag doesn't seem related here, if we are talking about authenticating remote cert with remote IPs.

**Comment by hexfusion** [comment]
Going to review the code on this and will reopen another issue with reproducible details if necessary, thanks.

**Comment by hexfusion** [comment]
I understand now, reverse DNS is really a security issue as validation assumes secure DNS. Maybe it should not be done at all.

**Comment by petersutty** [comment]
would you be able to provide working cluster config for certificate with SAN=*.example.com ?
I tried several config combinations, but always getting:
rejected connection from "10.99.4.2:36668" (error "remote error: tls: bad certificate", ServerName "")
Jan 02 14:29:54 spvault01 etcd[31837]: failed to dial c2ef3ff524aff825 on stream MsgApp v2 (x509: cannot validate certificate for 10.99.4.2 because it doesn't contain any IP SANs)
etcd Version: 3.3.10
Git SHA: 27fc7e2
Go Version: go1.10.4
Go OS/Arch: linux/amd64

**Comment by sangeethdba** [comment]
same issue .any update please

**Comment by sangeethdba** [comment]
> BTW I generated the peer certs for each node using the same CA, without using wildcard hostname and that worked. The problem seems to be using the wildcard but documentation says it's supported since 3.2.5

I did created certificate for each host,but still no luck.

**Comment by YanzhaoLi** [comment]
To use domain in SANs, is there any requirement for my dns server? 


`dig -x 10.0.8.4. ` can return what I want: two domains.
```
;; ANSWER SECTION:
6.8.0.10.in-addr.arpa.  0       IN      PTR     8d71b446-4102-446a-a479-dec89412ec07.master.scratch-gorilla-services-subnet.service-instance-941a792e-f7cc-423a-9171-d63c792f5e8d.bosh.
6.8.0.10.in-addr.arpa.  0       IN      PTR     master-2.etcd.cfcr.internal.
```

Using etcd's  golang code of checkSANs fails for returning only one domain
```
lnames, lerr := net.DefaultResolver.LookupAddr(ctx, host)
fmt.Println("INFO: reverse-dns Result of " + host + " :", lnames)

INFO: reverse-dns Result of 10.0.8.4 : [c8f968eb-4f5c-4c64-9e19-3661c53d2103.master.scratch-gorilla-services-subnet.service-instance-941a792e-f7cc-423a-9171-d63c792f5e8d.bosh.]
```
