### ISSUE TITLE
Curl not working with my etcd cluster ? (despite having a healthy state)

### ISSUE THREAD

**Issue by yaumeg** [coreos/etcd#9277]
Hi,

I have one etcd node (version 2.3.8) on an on-premise Kubernetes (version is 1.8.7), deployed with the "Kubernetes core" juju charm (https://jujucharms.com/kubernetes-core/). The etcd node runs on my master, and my k8s cluster runs fine.

The command `etcdctl cluster-health` executed on my master return a healthy state :

```
member 5eea96fe49f3c82d is healthy: got healthy result from https://master-ip:2379
cluster is healthy
```
But when I do a `curl http://127.0.0.1:2379/version`, I have no error but no answer either.

Why curl not working with my etcd node ?

**Comment by hexfusion** [comment]
@yaumeg, etcd is using TLS, but then you are telling curl to get via http.

**Comment by hexfusion** [comment]
Going to close this as it is not an etcd issue. Feel free to continue conversation here with additional questions.
