### ISSUE TITLE
watch prefix change with depth control or regex in jetcd 0.0.1 

### ISSUE THREAD

**Issue by zonghaishang** [coreos/etcd#9284]
I'm using jetcd (version 0.0.1), How to use api:
`client.Watch("\x02/servers/", clientv3.WithPrefix()) ; `
`client.Watch("\x03/servers/server-a/", clientv3.WithPrefix()) ?`
@heyitsanthony @xiang90 @yy2008

refer: https://github.com/coreos/etcd/issues/5402

**Comment by gyuho** [comment]
Duplicate with https://github.com/coreos/jetcd/issues/280.
