### ISSUE TITLE
Code using `mvccpb.KeyValue` fail to compile 

### ISSUE THREAD

**Issue by kaoet** [coreos/etcd#9293]
After https://github.com/coreos/etcd/commit/80d15948bcfc93aabd2c5245d7993c8a9e76bf8f, code using `mvccpb.KeyValue` explicitly fail to compile since it is moved into `internal` directory.

`mvccpb.KeyValue` is export as field type of `github.com/coreos/etcd/etcdserver/etcdserverpb.RangeResponse.Kvs`. Since `RangeResponse` is a public API. `mvccpb.KeyValue` should be public, too.

**Comment by gyuho** [comment]
Plan was revert that change https://github.com/coreos/etcd/pull/9274, until we find better way to handle internal packages. /cc @xiang90

**Comment by gyuho** [comment]
@kaoet Sorry for late response. We've reverted the changes for now. Please try the master branch.
