### ISSUE TITLE
When I import "github.com/coreos/etcd/internal/mvcc/mvccpb"   , prompting not to use how to solve？

### ISSUE THREAD

**Issue by tx991020** [coreos/etcd#9310]
import "github.com/coreos/etcd/internal/mvcc/mvccpb"
Use of internal package is not allowed less... (⌘F1) 
Reports invalid imports.

**Comment by hexfusion** [comment]
Hi @tx991020 this is a duplicate of https://github.com/coreos/etcd/issues/9293, please follow here.
