### ISSUE TITLE
re: clientv3

### ISSUE THREAD

**Issue by YeruchamB** [coreos/etcd#9316]
I generated a self-signed key pair and was able to run etcdctl succesfully. I tried writing a simple go binary that runs on the same instance as the cluster agent and would just connect and watch on "foo" and im having connection errors...

Cluster configuration:
```bash
#!/usr/bin/env bash

THIS_IP="$1"
THIS_NAME=infra-${THIS_IP}

TOKEN=token-02
CLUSTER_STATE=new
etcd --data-dir=data.etcd --name ${THIS_NAME}
--auto-tls --peer-auto-tls
--initial-advertise-peer-urls https://${THIS_IP}:2380 --listen-peer-urls https://${THIS_IP}:2380
--advertise-client-urls https://${THIS_IP}:2379 --listen-client-urls https://${THIS_IP}:2379
--discovery https://discovery.etcd.io/48f750c4f2254d71e7726b45abef4379
--initial-cluster-state ${CLUSTER_STATE} --initial-cluster-token ${TOKEN}
```
go code:

```go
package main

import (
"time"
"crypto/tls"
"flag"
"fmt"
"github.com/coreos/etcd/clientv3"
"io/ioutil"
"context"
"log"
)

func main() {
certPath := flag.String("cert", "", "path to certificate")
keyPath := flag.String("key", "", "path to key")
flag.Parse()

cert, err := ioutil.ReadFile(*certPath)
if err != nil {
	log.Fatal(err)
}

key, err := ioutil.ReadFile(*keyPath)
if err != nil {
	log.Fatal(err)
}

certificate, err := tls.X509KeyPair(cert, key)
if err != nil {
	log.Fatal(err)
}

cfg := clientv3.Config{
	TLS: &tls.Config{ InsecureSkipVerify: true, Certificates: []tls.Certificate{certificate} },
	Endpoints:   []string{"127.0.0.1:2379"},
	DialTimeout: 30 * time.Second}
client, err := clientv3.New(cfg)
if err != nil {
	log.Fatal(err)
}
rch := client.Watch(context.Background(), "foo")
for wresp := range rch {
	for _, ev := range wresp.Events {
		fmt.Printf("%s %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
	}
}
}
```
Error:
./simple-etcd-client --cert cert.pem --key key2.pem
2018-02-12 16:33:58.210907 I | dial tcp 127.0.0.1:2379: getsockopt: connection refused

Can you tell me what i'm doing wrong?

**Comment by hexfusion** [comment]
@YeruchamB it seems like your etcd is not listening on 127.0.0.1:2379?  ` ss -tan | grep 2379`  re: `--listen-client-urls https://${THIS_IP}:2379` while you are explicitly telling clientv3 to hit it? `Endpoints:   []string{"127.0.0.1:2379"},`

**Comment by gyuho** [comment]
@YeruchamB Just use https://godoc.org/github.com/coreos/etcd/clientv3#Config.

We have an example of constructing TLS config with `transport.TLSInfo`.

And make sure you use the auto-generated client certs from server.

**Comment by YeruchamB** [comment]
Thanks!
