### ISSUE TITLE
Mechanism to identify data directory corruption.

### ISSUE THREAD

**Issue by georgekuruvillak** [coreos/etcd#9318]
Is there a good way to validate the data directory for corruption before etcd is started?

I could find from  the source that sanity checks are made on the snap files(`snapshotter.Read(snapname string)`) and the wal files(`wal.ReadAll()`). I could not however find a mechanism in the source for validation of the db file in snap directory. Is there a way to validate whether the db file in the snap directory is corrupt or not?

**Comment by gyuho** [comment]
WAL has built-in CRC checks.

For backend db, you can try `--experimental-corrupt-check-time` and `--experimental-initial-corrupt-check`.

Please try out and let us know!

**Comment by georgekuruvillak** [comment]
@gyuho, Thank you for the information. I went through the `--experimental-corrupt-check-time` and `--experimental-initial-corrupt-check`. I run a single instance etcd server.

I enabled the flag and tried corrupting the db file by changing some keys and values in the db file. etcd failed to detect the error and listed out the changed values.

**Comment by gyuho** [comment]
@georgekuruvillak Currently, there's no way to detect single-node data corruption. The corrupt check compares digests of database with other nodes. If you have use case of single-node data corruption check, please open a new issue?
