### ISSUE TITLE
Index issues with ordered directories

### ISSUE THREAD

**Issue by shannonmpoole** [coreos/etcd#932]
I am having a very strange issue that I don't know how to debug. I have a basic build queue setup. I add a single value to /build/queue via post and I can see that an item is created at /build/queue/439653. My build process is watching this directory and then I process the value and delete the key. Then the strangeness happens. I list the directory via etcdctl and I get
```
etcdctl ls /build/queue --recursive
/build/queue/440098
```

I noticed that the index is off so I go to see whats there.
```
etcdctl get /build/queue/440098
Error:  100: Key not found (/build/queue/440098) [443883]
```

That's strange enough so I check via curl
```
curl localhost:4001/v2/keys/build/queue -L
{"action":"get","node":{"key":"/build/queue","dir":true,"nodes":[{"key":"/build/queue/434799","value":"REDACTED","modifiedIndex":434799,"createdIndex":434799}],"modifiedIndex":33473,"createdIndex":33473}}
```
Then I notice that index and the key are completely different again. The directory that should be empty is not and I have no idea where this new key came from or what really just happened.

This is part of a 7 machine CoreOS cluster. I am interacting with etcd via node-etcd but these commands were entered manually as part of my debugging because my build process was finding records that should have already been processed. I already check to see if something was still moving things around but all three commands return the exact same results every time.

**Comment by yichengq** [comment]
@shannonmpoole During development so far, We find that it could be related to an inconsistent index bug in store, and it has been fixed in latest etcd2. Sorry for bringing troubles to you.

Welcome to give etcd 2.1 a try. It is much more stable than 0.4, and I believe it could run well in your environment now.
