### ISSUE TITLE
Identify data directory corruption for single instance etcd.

### ISSUE THREAD

**Issue by georgekuruvillak** [coreos/etcd#9325]
Is there a good way to validate the data directory for corruption before single node etcd is started?

I could find from the source that sanity checks are made on the snap files(`snapshotter.Read(snapname string)`) and the wal files(`wal.ReadAll()`). I could not however find a mechanism in the source for validation of the db file in snap directory. Is there a way to validate whether the db file in the snap directory is corrupt or not?

I went through the `--experimental-corrupt-check-time` and `--experimental-initial-corrupt-check`. The corruption check mandates multi-instance etcd cluster. 

I enabled the flag and tried corrupting the db file by changing some keys and values in the db file. etcd failed to detect the error and listed out the changed values.

Related issue: [#9318](https://github.com/coreos/etcd/issues/9318)

**Comment by gyuho** [comment]
Currently corrupt check only happens between cluster members. And no way to verify single instance.
Other storage layer WAL keeps rolling CRC for corrupt check, but WAL logs are divided by 64 MiB chunks and append-only. The Bolt DB file is a single file, and keys are often deleted (deletion, compaction), so more expensive to maintain/persist rolling CRC or other digests. Bolt DB has internal page-level checksums, but won't protect against manipulated keys. If you have strong use case, I would fetch hash values manually (Hash API) for now.

Maybe add Bolt DB checksums to header? /cc @xiang90

**Comment by georgekuruvillak** [comment]
@gyuho, I cannot be sure if the data is corrupt by fetching the hash value. It would be the hash of a corrupt db file, right? I wanted to create a command-line tool to check the data directory for corruption before starting etcd. It is to run as an init-container for the etcd Pod.  If the directory is corrupt, I would do a restore from the snapshot and bring up etcd.

**Comment by gyuho** [comment]
@georgekuruvillak We are aware of it. We do have embedded SHA digest in snapshot file, but not in the db file. Adding SHA to db file is simple, but we need to evaluate the overhead of maintaining SHA or any digests, for every write and delete.

**Comment by gyuho** [comment]
Maintaining hashes for every single mutable operation would be too costly. I don't think it's necessary now. If users have real use case, please let us know.
