### ISSUE TITLE
embed: value of AutoCompactionRetention and embed.CompactorModeRevision are incompatible

### ISSUE THREAD

**Issue by grepory** [coreos/etcd#9337]
Specifying [embed.CompactorModeRevision](https://github.com/coreos/etcd/blob/master/embed/config.go#L100) for the configuration's [AutoCompactionMode](https://github.com/coreos/etcd/blob/master/embed/config.go#L120) parameter will result in an unintentional value for the revision compactor's [retention](https://github.com/coreos/etcd/blob/11214aa33bf5a47d3d9d8dafe0f6b97237dfe921/internal/compactor/compactor.go#L64) parameter.

Because of the treatment of retention as a time.Duration and its conversion [here](https://github.com/coreos/etcd/blob/6f76e46c0cdbc1d9721dcbc290ce2e41e3577586/embed/etcd.go#L147) -- we end up passing a 1 hour time.Duration and converting it to an int64 via `int64(retention)`, which tells the revision compactor to only compact after revision 3600000000000.

To get around this, we're specifying the retention value for CompactorModeRevision in nanoseconds which parses as a "1ns" -> 1, for example.

**Comment by grepory** [comment]
Also, I'd assume this isn't just affecting embedded etcd, but have not loooked into how the command line does it for etcd.

**Comment by gyuho** [comment]
@grepory How do you configure `embed.Config`?

We define `AutoCompactionRetention` as `time.Duration` in order to support both compact modes (revision-based, interval-based).

> Because of the treatment of retention as a time.Duration

If you need periodic compaction, you can:

```go
// auto-compaction every hour
cfg.AutoCompactionMode = embed.CompactorModePeriodic
cfg.AutoCompactionRetention = "1h"
```

If you need revision-based compaction, you can:

```go
// auto-compaction every 5000 rev
cfg.AutoCompactionMode = embed.CompactorModeRevision
cfg.AutoCompactionRetention = "5000"
```

I don't think you need to convert `time.Hour`? Just passing `"1h"` should work?

**Comment by grepory** [comment]
AutoCompactionRetention gets cased to a time.Duration no matter what mode you specify.

At some point, that value gets multiplied by time.Hour -- at which point 5000 becomes 5000 hours which gets converted to an int64 -- which is much more than revision 5000. Right now, we're doing this:

```golang
	// Every 5 minutes, we will prune all values in etcd to only their latest
	// revision.
	cfg.AutoCompactionMode = embed.CompactorModeRevision
	// This has to stay in ns until https://github.com/coreos/etcd/issues/9337
	// is resolved.
	cfg.AutoCompactionRetention = "1ns"
```

Specifying only "1" in AutoCompactionRetention ended up specifying a revision number of 3600000000000. Again, where this happens is here:

https://github.com/coreos/etcd/blob/6f76e46c0cdbc1d9721dcbc290ce2e41e3577586/embed/etcd.go#L147

1 hour does not translate to 1 revision.

**Comment by gyuho** [comment]
> Specifying only "1" in AutoCompactionRetention ended up specifying a revision count of 3600000000000. 

Oh now I see the issue.

`time.Duration(int64(h)) * time.Hour` was there only for backward compatibility, but we did it wrong.

Thanks for report.

We will fix this soon!

/cc @fanminshi

**Comment by grepory** [comment]
No problem! Thanks for looking into it. :) <3

**Comment by gyuho** [comment]
@grepory Should be fixed by https://github.com/coreos/etcd/pull/9339. Will backport to 3.3 as well. Thanks.
