### ISSUE TITLE
how to  go install this  project in  linux os

### ISSUE THREAD

**Issue by 727023460** [coreos/etcd#9346]
sorry，I am a newcomer to golang,
when I git clone it in linux os 
many not find errors
I need move many folder when I command
` go install etcd` and
` go install etcdctl`

**Comment by MoSunDay** [comment]
just download it `https://github.com/coreos/etcd/releases`

**Comment by 727023460** [comment]
fatal: repository 'https://github.com/coreos/etcd/releases/' not found

**Comment by MoSunDay** [comment]
Select the compression package that corresponds to your platform, because this is a Go - compiled binary file, so unraveling it can be used.

or build source code to get binary file.

**Comment by 727023460** [comment]
thanks , I want see source code ,compiled binary file is not needed for me

**Comment by MoSunDay** [comment]
You can run `go get github.com/coreos/etcd` to get source code.
or just git clone source code, and move to the project directory( not recommend ).

**Comment by hexfusion** [comment]
Hi @727023460, please see https://github.com/coreos/etcd/blob/master/Documentation/dl_build.md. Closing but feel free to continue the conversation here.
