### ISSUE TITLE
Handling panic calls in goroutines created.

### ISSUE THREAD

**Issue by georgekuruvillak** [coreos/etcd#9373]
I am starting an etcd server by calling [embed.StartEtcd()](https://github.com/coreos/etcd/blob/master/embed/etcd.go#L92). This eventually does try to create a backend at [here](https://github.com/coreos/etcd/blob/master/etcdserver/backend.go#L55) in a different goroutine. Internally, it results in a panic in case of an error. The panic call is in a different goroutine than the one starting etcd. This makes error handling not possible. Deferred handling of panics using recover() can be trickled up only till the top-level function executing in the goroutine. 

It would be better if the code that creates goroutines handles the panic instances and return err.

**Comment by georgekuruvillak** [comment]
The panic occurs [here](https://github.com/coreos/etcd/blob/master/mvcc/backend/backend.go#L138). It would be nice to return an error in that case at embed.StartEtcd(). I believe that would make it robust to use.

**Comment by gyuho** [comment]
Seems too low-level of an error to expose to users. Also breaks current interface, although mvcc is assumed to be internal. Do you have specific use case that needed that `bolt.Open` error exposed?

**Comment by georgekuruvillak** [comment]
I would like to start etcd from within my application and not via cmd line. The panic will result in an app crash as I would not be able to handle the panic which occurs at a goroutine over which I don't have control to handle the panic.

**Comment by heyitsanthony** [comment]
@georgekuruvillak it may be simpler to do `cmd.Run()` on etcd from the application if it can't tolerate panics; there are a lot of panics in the core server

what's causing the db to fail to open?

**Comment by georgekuruvillak** [comment]
Thanks @heyitsanthony, @gyuho 

> what's causing the db to fail to open?

@heyitsanthony one reason can be a corrupt db file.

`cmd.Run()` works well with me. However, it does run etcd as a seperate command. It would have been perfect if I could have used `embed.StartEtcd()` but this solves my issue. 😉

**Comment by xiang90** [comment]
@georgekuruvillak 

Even if embed.StartEtcd() wont panic during initialization, etcd might panic in other places when it hits a unrecoverable error internally during its runtime.
