### ISSUE TITLE
limitation of key/value length

### ISSUE THREAD

**Issue by featheryus** [coreos/etcd#9392]
I have question about the key/value length.
Does the etcd has a explicit limitation for length of key/value

Thanks.

**Comment by swathins079** [comment]
@featheryus what's the max key length?

Regards,
Swathin

**Comment by hexfusion** [comment]
@featheryus keys are measured in bytes on the server this is configurable via `---max-request-bytes`[1] the default is 1572864 or about 1.5 MiB

[1] [Documentation/op-guide/configuration.md#--max-request-bytes]( https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--max-request-bytes)

**Comment by swathins079** [comment]
Thanks @hexfusion 
But I am more interested in the key length rather than the length of the data or value.

For example:
/something/somekey <== what's max length of this?
{"id": 100, "Name": "Rob", ....}

Regards,
Swathin
