### ISSUE TITLE
metrics: what does this data mean? 

### ISSUE THREAD

**Issue by RayQiQi** [coreos/etcd#9407]
Hi,

What does this data mean? what do le and the number "5.6053369e+07" mean? 
Is there a document to interpreted this?

# HELP etcd_wal_fsync_durations_seconds The latency distributions of fsync called by wal.
# TYPE etcd_wal_fsync_durations_seconds histogram
etcd_wal_fsync_durations_seconds_bucket{le="0.001"} 0
etcd_wal_fsync_durations_seconds_bucket{le="0.002"} 0
etcd_wal_fsync_durations_seconds_bucket{le="0.004"} 2.2724968e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.008"} 5.4649043e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.016"} 5.5625811e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.032"} 5.5703951e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.064"} 5.5732661e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.128"} 5.5746725e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.256"} 5.6021752e+07
etcd_wal_fsync_durations_seconds_bucket{le="0.512"} 5.6038783e+07
etcd_wal_fsync_durations_seconds_bucket{le="1.024"} 5.6053369e+07
etcd_wal_fsync_durations_seconds_bucket{le="2.048"} 5.6055184e+07
etcd_wal_fsync_durations_seconds_bucket{le="4.096"} 5.6055516e+07
etcd_wal_fsync_durations_seconds_bucket{le="8.192"} 5.6055588e+07
etcd_wal_fsync_durations_seconds_bucket{le="+Inf"} 5.6055631e+07
etcd_wal_fsync_durations_seconds_sum 329832.62183343136

**Comment by yudai** [comment]
`NeM` is the scientific format or e-notation: https://en.wikipedia.org/wiki/Scientific_notation#E-notation. `5.6053369e+07` is `56053369`.

These lines display the (cumulative) histogram of the latency of wal fsync. It's a Prometheus format. https://prometheus.io/docs/practices/histograms/ (http://linuxczar.net/blog/2017/06/15/prometheus-histogram-2/)

**Comment by gyuho** [comment]
As @yudai answered, please refer to Prometheus documentation.
