### ISSUE TITLE
Release planning for March

### ISSUE THREAD

**Issue by gyuho** [coreos/etcd#9411]
Most of items are already addressed. Just to not forget.

- v3.1.12
  - [X] Communicate through https://github.com/kubernetes/kubernetes/issues/60589
  - [X] Run tests + functional tests (I enabled functional tests for 3.1 branch).
  - [X] Update https://github.com/coreos/etcd/blob/master/CHANGELOG-3.1.md
  - [X] Make sure to compile/test with Go 1.8.7
  - [X] Release/publish
- v3.2.17
  - [X] Backport TTL value validation https://github.com/coreos/etcd/pull/9399
  - [X] Run tests + functional tests
  - [X] Update https://github.com/coreos/etcd/blob/master/CHANGELOG-3.2.md
  - [X] Make sure to compile/test with Go 1.8.7
  - [X] Release/publish
- v3.3.2
  - [X] Backport TTL value validation https://github.com/coreos/etcd/pull/9399
  - [X] Run tests + functional tests
  - [X] Update https://github.com/coreos/etcd/blob/master/CHANGELOG-3.3.md
  - [X] Make sure to compile/test with Go 1.9.4
  - [X] Release/publish

<br>

- v3.1.13
  - [X] Update https://github.com/coreos/etcd/blob/master/CHANGELOG-3.1.md
  - [X] Backport "adjusted election ticks for higher availability" ~~https://github.com/coreos/etcd/pull/9364~~ https://github.com/coreos/etcd/pull/9415
  - [X] Backport "fix missing `peer_sent_failures_total` metrics" https://github.com/coreos/etcd/pull/9437
- v3.2.18
  - [X] Update https://github.com/coreos/etcd/blob/master/CHANGELOG-3.2.md
  - [X] Backport "adjusted election ticks for higher availability" ~~https://github.com/coreos/etcd/pull/9364~~ https://github.com/coreos/etcd/pull/9415
  - [X] Backport "fix missing `peer_sent_failures_total` metrics" https://github.com/coreos/etcd/pull/9437
- v3.3.3
  - [X] Update https://github.com/coreos/etcd/blob/master/CHANGELOG-3.3.md
  - [X] Backport "adjusted election ticks for higher availability" ~~https://github.com/coreos/etcd/pull/9364~~ https://github.com/coreos/etcd/pull/9415
  - [X] Backport "fix missing `peer_sent_failures_total` metrics" https://github.com/coreos/etcd/pull/9437
  - [X] Backport "compactor fix" https://github.com/coreos/etcd/pull/9485

<br>

/cc @jpbetz

**Comment by jpbetz** [comment]
I'm in favor of getting #9364 in, ideally all the way back to v3.1.12 (since we're releasing it).  But I haven't been involved closely enough to make a careful assessment of the risk. @wojtek-t, @mborsz what do you think?

**Comment by jpbetz** [comment]
I'm available this afternoon (1pm-) to do the 3.1 and 3.2 releases. I'll submit the remaining backport requests shortly.

**Comment by gyuho** [comment]
> But I haven't been involved closely enough to make a careful assessment of the risk

Yeah, it would be great if someone else can cross-check https://github.com/coreos/etcd/pull/9364.

Also to clarify, ideally we get all fixes in and publish releases, by today. But if it takes longer, I am also available next week as well. I just cannot sign the binaries, but can still push official release images.

**Comment by wojtek-t** [comment]
+1 for waiting for #9364 if that's possible.

**Comment by jpbetz** [comment]
Current thinking is that we'll release v3.1.12, v3.2.17, v3.3.2 today without #9364 and then aim for an additional set of releases next week for #9364 once we've validated the latest changes against GKE and any other use cases we can find.

**Comment by gyuho** [comment]
I'm working on simpler solution for https://github.com/coreos/etcd/issues/9333. Once we test it, we can backport to release branches.

**Comment by wojtek-t** [comment]
> Current thinking is that we'll release v3.1.12, v3.2.17, v3.3.2 today without #9364 and then aim for an additional set of releases next week for #9364 once we've validated the latest changes against GKE and any other use cases we can find.

SGTM

**Comment by jpbetz** [comment]
Backports for 3.1.13:
- https://github.com/coreos/etcd/pull/9500 (cherrypick of #9415)
- https://github.com/coreos/etcd/pull/9501 (cherrypick of #9437)

and for 3.2.18:
- https://github.com/coreos/etcd/pull/9502 (cherrypick of #9415)
- https://github.com/coreos/etcd/pull/9503 (cherrypick of #9437)

**Comment by jpbetz** [comment]
3.1.13 and 3.2.18 backports are merged.

**Comment by gyuho** [comment]
@jpbetz Thanks!

I manually ran test suites (including functional tests) for 3.1 and 3.2, locally; all passed.
And 3.3 CI https://semaphoreci.com/coreos/etcd/branches/release-3-3/builds/65 passed.

We will publish releases tomorrow.

**Comment by gyuho** [comment]
We've just published:
- https://github.com/coreos/etcd/releases/tag/v3.1.13
- https://github.com/coreos/etcd/releases/tag/v3.2.18
- https://github.com/coreos/etcd/releases/tag/v3.3.3

Please check the CHANGELOGs for all details.
