### ISSUE TITLE
Query: whether can reduce the size for the wal files.

### ISSUE THREAD

**Issue by nenzhang** [coreos/etcd#9422]
I only configured below to have only  1 file for wal and snap. however, it has one temp file as below indicates and totally have 128M.  How can I reduce this size space ? is exist any configuration to define the size? thank you.

ETCD_MAX_SNAPSHOTS="1"
ETCD_MAX_WALS="1"

total 125008
drwx------ 2 root root     4096 Mar 12 09:51 .
drwx------ 4 root root     4096 Mar 12 09:51 ..
-rw------- 1 root root 64000000 Mar 12 10:37 0000000000000000-0000000000000000.wal
-rw------- 1 root root 64000000 Mar 12 09:51 0.tmp

The used version:

etcdctl --version
etcdctl version: 3.1.4
API version: 2

**Comment by nenzhang** [comment]
Can somebody help me clarify this ?

**Comment by gyuho** [comment]
This is intentional. We preallocate WAL stores to eliminate latencies for metadata updates or block allocations.

**Comment by nenzhang** [comment]
Thanks, @gyuho ,  is it possible to configure to be smaller size value if we only support very small cluster and not so frequently DB operations?

**Comment by nenzhang** [comment]
Hi
@Gyuho
I change to the definition from 64M to 16M and do compile, looks not have much impact, also I change the snapshot_count to 1000 during testing for one etcd instance.
Could you help confirm any impact will be? thanks.

**Comment by gyuho** [comment]
@nenzhang We won't support configurable preallocation.
