### ISSUE TITLE
Error:  etcdserver: mvcc: required revision is a future revision

### ISSUE THREAD

**Issue by shsjshentao** [coreos/etcd#9423]
Is it a bug? 
I start etcd use this command.
"./etcd --quota-backend-bytes=56777216 --auto-compaction-retention=1"
And I cannot understand the effect of "--auto-compaction-retention" clearly.
Does it compact old key revisions then release space to use if i do not exec defrag?
In my testing, configured it also will cause "mvcc: database space exceeded" without defrag.
So for a production environment, how to use it correctly? Configure "--auto-compaction-retention" then run a crontab to defrag?

[root@SGDLITVM0931 tmp]# ./etcdctl -w table endpoint status
+----------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | 8e9e05c52164694d |  3.2.14 |  2.1 MB |      true |         3 |        307 |
+----------------+------------------+---------+---------+-----------+-----------+------------+
[root@SGDLITVM0931 tmp]# ./etcdctl compact 307
Error:  etcdserver: mvcc: required revision is a future revision

**Comment by yudai** [comment]
I think the information you need is described in https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md

The auto compaction remove old revisions, but doesn't run defrag or release free disk space. Therefore, if you keep putting more data to your etcd faster than it removes old revisions, you eventually get a `database space exceeded` error.
For production environments, compaction strategy depends on each use case. If you have enough (fast) disk space and assign a larger quota size, just using a longer retention time would work. If you cannot assign a large quota, then you need to set a shorter retention time.
If your writing speed is enough lower than the compaction speed, ideally there is no need to run defrag, as long as you have large enough quota. Free space created by compactions will be automatically reused internally.

`RAFT INDEX` is not the revision number you need to run compaction. You can find the revision using `-w json`, e.g.

```
etcdctl endpoint -w json status
[{"Endpoint":"127.0.0.1:2379","Status":{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":2225,"raft_term":5},"version":"3.3.0+git","dbSize":155648,"leader":10276657743932975437,"raftIndex":2234,"raftTerm":5,"raftAppliedIndex":2234,"dbSizeInUse":147456}}]
```

**Comment by gyuho** [comment]
@yudai's response explains well. Closing.
