### ISSUE TITLE
why the 'key' and 'key_end' param in AuthRoleRevokePermissionRequest are string rather than bytes

### ISSUE THREAD

**Issue by Revolution1** [coreos/etcd#9424]
https://github.com/coreos/etcd/blob/4408ecede8903225128acee649f5e4e5ae6ed87a/etcdserver/etcdserverpb/rpc.proto#L988-L992

I noticed this abnormal type definition while im writing the etcd3-py client

In every other message 'key' and 'range_end' are bytes, except this one

I'm very curious about that

does that mean the functions of key-range (like prefix, all_keys) are limited here?

**Comment by mitake** [comment]
@Revolution1 thanks for your report. The string type wouldn't have a rationale reason, I'll fix it soon.
