### ISSUE TITLE
server is likely overloaded

### ISSUE THREAD

**Issue by itnikita** [coreos/etcd#9427]
3 nodes etcd and k8s 

192.168.2.186 hostname:docker-master  etcd1 k8s master
192.168.2.187 hostname:docker-node1  etcd2 k8s node1
192.168.2.188 hostname:docker-node2  etcd3 k8s node2

Not use TLS

OS:centos 7.2 64bit
uname -an
Linux docker-master 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

etcd -version
etcd Version: 3.1.9
Git SHA: 0f4a535
Go Version: go1.7.4
Go OS/Arch: linux/amd64

kubectl --version
Kubernetes v1.5.2

kubectl get cs   
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   
scheduler            Healthy   ok                   
etcd-0               Healthy   {"health": "true"}   

api-server config shown as follows
cat /etc/kubernetes/apiserver 
###
# kubernetes system config
#
# The following values are used to configure the kube-apiserver
#

# The address on the local server to listen to.
#KUBE_API_ADDRESS="--insecure-bind-address=127.0.0.1"
KUBE_API_ADDRESS="--insecure-bind-address=0.0.0.0"

# The port on the local server to listen on.
KUBE_API_PORT="--port=8080"

# Port minions listen on
KUBELET_PORT="--kubelet-port=10250"

# Comma separated list of nodes in the etcd cluster
KUBE_ETCD_SERVERS="--etcd-servers=http://192.168.2.186:2379"

# Address range to use for services
KUBE_SERVICE_ADDRESSES="--service-cluster-ip-range=10.254.0.0/16"

# default admission control policies
KUBE_ADMISSION_CONTROL="--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"

# Add your own!
KUBE_API_ARGS=""

End here for file /etc/kubernetes/apiserver 

The problem is etcd,please find out the logs of etcd1
journalctl -u etcd -xe -f
Mar 13 07:26:17 docker-master etcd[26377]: failed to send out heartbeat on time (exceeded the 100ms timeout for 53.377974ms)
Mar 13 07:26:17 docker-master etcd[26377]: server is likely overloaded
Mar 13 07:26:17 docker-master etcd[26377]: failed to send out heartbeat on time (exceeded the 100ms timeout for 54.720625ms)
Mar 13 07:26:17 docker-master etcd[26377]: server is likely overloaded
Mar 13 07:35:25 docker-master etcd[26377]: start to snapshot (applied: 5640569, lastsnap: 5630568)
Mar 13 07:35:25 docker-master etcd[26377]: saved snapshot at index 5640569
Mar 13 07:35:25 docker-master etcd[26377]: compacted raft log at 5635569
Mar 13 07:35:30 docker-master etcd[26377]: purged file /var/lib/etcd/default.etcd/member/snap/0000000000030fe9-0000000000554e24.snap successfully
Mar 13 07:56:45 docker-master etcd[26377]: failed to send out heartbeat on time (exceeded the 100ms timeout for 82.859487ms)
Mar 13 07:56:45 docker-master etcd[26377]: server is likely overloaded
Mar 13 07:56:45 docker-master etcd[26377]: failed to send out heartbeat on time (exceeded the 100ms timeout for 91.79113ms)
Mar 13 07:56:45 docker-master etcd[26377]: server is likely overloaded
Mar 13 08:16:20 docker-master etcd[26377]: start to snapshot (applied: 5650570, lastsnap: 5640569)
Mar 13 08:16:20 docker-master etcd[26377]: saved snapshot at index 5650570
Mar 13 08:16:20 docker-master etcd[26377]: compacted raft log at 5645570
Mar 13 08:16:30 docker-master etcd[26377]: purged file /var/lib/etcd/default.etcd/member/snap/0000000000030fe9-0000000000557535.snap successfully

I doubt an IO issues? but I can't confirm it.any ideas?
7200RPM disk no raid and 7200RPM disk RAID10 have the same issues

What can I do to test and find out whether it is an IO problem or any other problem?

**Comment by itnikita** [comment]
iostat -x -k -d 1 
Linux 3.10.0-327.el7.x86_64 (docker-master)     03/13/2018      _x86_64_        (1 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.13    0.01    2.27     0.40     8.90     8.15     0.01    3.18    5.68    3.17   3.13   0.71
dm-0              0.00     0.00    0.01    2.40     0.39     8.90     7.71     0.01    3.17    6.30    3.16   2.97   0.71
dm-1              0.00     0.00    0.00    0.00     0.00     0.00    10.17     0.00    3.18    5.04    1.31   1.58   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00    21.14     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    1.03     0.00     4.12     8.00     0.00    1.00    0.00    1.00   1.00   0.10
dm-0              0.00     0.00    0.00    1.03     0.00     4.12     8.00     0.00    1.00    0.00    1.00   1.00   0.10
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    1.02     0.00     4.08     8.00     0.00    1.00    0.00    1.00   1.00   0.10
dm-0              0.00     0.00    0.00    1.02     0.00     4.08     8.00     0.00    1.00    0.00    1.00   1.00   0.10
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-2              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

**Comment by itnikita** [comment]
here is another cluter with 3 nodes etcd and 3 of k8s master 

etcdctl member list
2bc25bbe31f9fca3, started, etcd1, https://192.168.9.181:2380, https://192.168.9.181:2379
4e1794faf2c704bf, started, etcd3, https://192.168.9.183:2380, https://192.168.9.183:2379
5e5566ced69cc2fe, started, etcd2, https://192.168.9.182:2380, https://192.168.9.182:2379

kubectl get cs
2018-03-13 10:56:17.305439 I | proto: duplicate proto type registered: google.protobuf.Any
2018-03-13 10:56:17.305523 I | proto: duplicate proto type registered: google.protobuf.Duration
2018-03-13 10:56:17.305557 I | proto: duplicate proto type registered: google.protobuf.Timestamp
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   
controller-manager   Healthy   ok                   
etcd-1               Healthy   {"health": "true"}   
etcd-0               Healthy   {"health": "true"}   
etcd-2               Healthy   {"health": "true"}   

I think 3 of k8s masters have the same problem with TLS.
etcd v3.2.1  k8s v1.7.2

Please find out the log of etcd
Mar 12 15:04:00 etcd-host1 etcd[14092]: start to snapshot (applied: 420042, lastsnap: 410041)
Mar 12 15:04:00 etcd-host1 etcd[14092]: saved snapshot at index 420042
Mar 12 15:04:00 etcd-host1 etcd[14092]: compacted raft log at 415042
Mar 12 15:04:08 etcd-host1 etcd[14092]: purged file /var/lib/etcd/etcd1.etcd/member/snap/000000000000000c-000000000005a575.snap successfully
Mar 12 15:04:50 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
Mar 12 15:04:50 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
Mar 12 15:05:37 etcd-host1 etcd[14092]: apply entries took too long [449.080815ms for 1 entries]
Mar 12 15:05:37 etcd-host1 etcd[14092]: avoid queries with large range/delete range!
Mar 12 15:06:28 etcd-host1 etcd[14092]: apply entries took too long [233.89929ms for 1 entries]
Mar 12 15:06:28 etcd-host1 etcd[14092]: avoid queries with large range/delete range!
Mar 12 15:06:42 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
Mar 12 15:06:42 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 90441
Mar 12 15:08:21 etcd-host1 etcd[14092]: store.index: compact 415716
Mar 12 15:08:21 etcd-host1 etcd[14092]: finished scheduled compaction at 415716 (took 829.566µs)
Mar 12 15:09:34 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 90359
Mar 12 15:09:34 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 90481
Mar 12 15:13:21 etcd-host1 etcd[14092]: store.index: compact 416009
Mar 12 15:13:21 etcd-host1 etcd[14092]: finished scheduled compaction at 416009 (took 659.086µs)
Mar 12 15:14:26 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 90445
Mar 12 15:14:26 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
Mar 12 15:14:33 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
Mar 12 15:14:33 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 85149
Mar 12 15:18:13 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 90485
Mar 12 15:18:21 etcd-host1 etcd[14092]: store.index: compact 416302
Mar 12 15:18:21 etcd-host1 etcd[14092]: finished scheduled compaction at 416302 (took 1.010224ms)
Mar 12 15:20:21 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 90549
Mar 12 15:21:24 etcd-host1 etcd[14092]: failed to receive watch request from gRPC stream ("rpc error: code = Unavailable desc = stream error: stream ID 85153
Mar 12 15:22:13 etcd-host1 etcd[14092]: apply entries took too long [198.453351ms for 1 entries]
Mar 12 15:22:13 etcd-host1 etcd[14092]: avoid queries with large range/delete range!
Mar 12 15:23:21 etcd-host1 etcd[14092]: store.index: compact 416594
Mar 12 15:23:21 etcd-host1 etcd[14092]: finished scheduled compaction at 416594 (took 604.001µs)
 

iostat -x -k -d 1
Linux 3.10.0-327.el7.x86_64 (etcd-host1) 	03/13/2018 	_x86_64_	(8 CPU)

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.64    0.00    7.76     0.10    28.02     7.24     0.07    8.60    1.14    8.60   7.71   5.98
dm-0              0.00     0.00    0.00    8.14     0.10    28.02     6.90     0.07    8.24    1.41    8.24   7.35   5.99
dm-1              0.00     0.00    0.00    0.00     0.00     0.00    15.10     0.00    1.47    1.47    0.00   1.36   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    2.00     0.00     4.00     4.00     0.03   17.00    0.00   17.00  17.00   3.40
dm-0              0.00     0.00    0.00    2.00     0.00     4.00     4.00     0.03   17.00    0.00   17.00  17.00   3.40
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00   13.00     0.00    52.00     8.00     0.10    7.69    0.00    7.69   7.69  10.00
dm-0              0.00     0.00    0.00   13.00     0.00    52.00     8.00     0.10    7.69    0.00    7.69   7.69  10.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     3.00    0.00    3.00     0.00    20.00    13.33     0.26   86.00    0.00   86.00  86.00  25.80
dm-0              0.00     0.00    0.00    5.00     0.00    20.00     8.00     0.26   51.60    0.00   51.60  51.60  25.80
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.00    0.00   20.00     0.00    88.00     8.80     0.22   11.10    0.00   11.10  10.95  21.90
dm-0              0.00     0.00    0.00   21.00     0.00    88.00     8.38     0.22   10.57    0.00   10.57  10.43  21.90
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00   15.00     0.00    60.00     8.00     0.27   17.67    0.00   17.67  17.33  26.00
dm-0              0.00     0.00    0.00   15.00     0.00    60.00     8.00     0.27   17.67    0.00   17.67  17.33  26.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00   14.00     0.00    56.00     8.00     0.18   12.93    0.00   12.93  10.71  15.00
dm-0              0.00     0.00    0.00   14.00     0.00    56.00     8.00     0.18   12.93    0.00   12.93  10.71  15.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     3.00    0.00    5.00     0.00    88.00    35.20     0.05    9.80    0.00    9.80   9.80   4.90
dm-0              0.00     0.00    0.00    7.00     0.00    88.00    25.14     0.05    7.00    0.00    7.00   7.00   4.90
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     5.00    0.00   11.00     0.00    64.00    11.64     0.09    8.36    0.00    8.36   8.36   9.20
dm-0              0.00     0.00    0.00   15.00     0.00    64.00     8.53     0.09    6.13    0.00    6.13   6.13   9.20
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    9.00     0.00    36.00     8.00     0.02    2.56    0.00    2.56   2.56   2.30
dm-0              0.00     0.00    0.00    9.00     0.00    36.00     8.00     0.02    2.56    0.00    2.56   2.56   2.30
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-0              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00   13.00     0.00    56.00     8.62     0.10    7.38    0.00    7.38   7.31   9.50
dm-0              0.00     0.00    0.00   13.00     0.00    56.00     8.62     0.10    7.38    0.00    7.38   7.31   9.50
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     3.00    0.00    3.00     0.00    20.00    13.33     0.02    6.00    0.00    6.00   6.00   1.80
dm-0              0.00     0.00    0.00    5.00     0.00    20.00     8.00     0.02    4.20    0.00    4.20   3.60   1.80
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.00    0.00   15.00     0.00    76.00    10.13     0.17   11.20    0.00   11.20  11.07  16.60
dm-0              0.00     0.00    0.00   16.00     0.00    76.00     9.50     0.17   10.50    0.00   10.50  10.38  16.60
dm-1              0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00

**Comment by hexfusion** [comment]
@itnikita please review [etcd metric docs](https://github.com/coreos/etcd/blob/677606da7ddcf030fe48acc64db0c84231e52d7e/Documentation/metrics.md#metrics.) If you can post the output of the /metrics endpoint we can get a better picture of what is going on with your nodes, specifically we are looking at fsync for I/O.

> 7200RPM disk 

In general SSD is strongly recommended vs HDD

**Comment by itnikita** [comment]
first one is the 1 of the k8s master and 2 of k8s node ,etcd metrics without TLS  etcd version 3.1.9
2nd is 3 of k8s master  with TLS ,etcd version 3.3.1
all of the 2 clusters have 3 etcd node

output is from the first node of every cluster:

I read the docs but don't know how to get the output of the metrics exactly.
I just guess to use the curl command.

curl 127.0.0.1:2379/metrics | grep etcd_disk_                                  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 7
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 7
etcd_disk_backend_commit_duration_seconds_sum 0.007136362000000001
etcd_disk_backend_commit_duration_seconds_count 7
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 6820
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 16800
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 19552
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 19966
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 20224
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 22147
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 23586
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 23640
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 23644
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 23644
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 23644
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 23644
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 23644
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 23644
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 23644
etcd_disk_wal_fsync_duration_seconds_sum 145.95571872700026
etcd_disk_wal_fsync_duration_seconds_count 23644
100 28220  100 28220    0     0  2061k      0 --:--:-- --:--:-- --:--:-- 2296k


 curl 127.0.0.1:2379/metrics | grep etcd_disk_ 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30590  100 30590    0     0  63# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
4# TYPE etcd_disk_backend_commit_duration_seconds histogram
9etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 0
ketcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 4
 etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 47045
 etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 144055
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 208055
 etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 321910
 etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 402947
 etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 418574
 etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 463924
0 -etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 465949
-etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 465979
:--:--etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 465984
 etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 465985
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 465985
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 465985
etcd_disk_backend_commit_duration_seconds_sum 18092.21131934407
--etcd_disk_backend_commit_duration_seconds_count 465985
:# HELP etcd_disk_backend_snapshot_duration_seconds The latency distribution of backend snapshots.
-# TYPE etcd_disk_backend_snapshot_duration_seconds histogram
-etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.01"} 0
:etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.02"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.04"} 0
-etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.08"} 0
-etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.16"} 0
 etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.32"} 0
-etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.64"} 0
-etcd_disk_backend_snapshot_duration_seconds_bucket{le="1.28"} 0
:etcd_disk_backend_snapshot_duration_seconds_bucket{le="2.56"} 0
--:-- 7468ketcd_disk_backend_snapshot_duration_seconds_bucket{le="5.12"} 0

etcd_disk_backend_snapshot_duration_seconds_bucket{le="10.24"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="20.48"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="40.96"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="81.92"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="163.84"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="327.68"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="655.36"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_snapshot_duration_seconds_sum 0
etcd_disk_backend_snapshot_duration_seconds_count 0
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 59
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 129182
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 196667
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 233333
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 308097
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 407019
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 460028
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 472178
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 497767
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 499339
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 499355
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 499360
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 499362
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 499362
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 499362
etcd_disk_wal_fsync_duration_seconds_sum 12653.050055996642
etcd_disk_wal_fsync_duration_seconds_count 499362

**Comment by hexfusion** [comment]
These fsync numbers look very bad as noted above your issue appears to be IO. etcd relies on fast disk I/O and can be a major bottleneck. 

>To rule out a slow disk from causing this warning, monitor wal_fsync_duration_seconds (p99 duration should be less than 10ms) to confirm the disk is reasonably fast. 

You have many fsyncs way in excess of this, please move to SSD drives per FAQ.

**Comment by hexfusion** [comment]
Feel free to ask any additional questions, closing as the source of the issue points to I/O.
