### ISSUE TITLE
etcd release-3.3 branch build failed, undefined: CompactorModeRevision

### ISSUE THREAD

**Issue by lsytj0413** [coreos/etcd#9429]
# Description

checkout release-3.3 branch and run ./build failed.

# Reproduction guide

- clone etcd repo
- git checkout release-3.3
- ./build

# Observed behaviour:

build failed, the error report is:

```
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/config.go:461:7: undefined: CompactorModeRevision
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/config.go:461:30: undefined: CompactorModePeriodic
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:561:8: undefined: CompactorModeRevision
gopath/src/github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/embed/etcd.go:563:8: undefined: CompactorModePeriodic
```

# Expected behaviour:

build with no error.

# System Info

- WSL on win10
- Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014
- go version go1.9.2 linux/amd64

on the other hand, the branch release-3.2 is build success on my enviroment. is there any wrong with my steps or enviroment?

**Comment by gyuho** [comment]
Try the latest release-3.3 branch? Should be fixed.

**Comment by lsytj0413** [comment]
@gyuho 3ks
