### ISSUE TITLE
go-etcd: Watch channel closed

### ISSUE THREAD

**Issue by yangzh** [coreos/etcd#943]
Sorry if I put this bug into the wrong place, but I can not find any more proper place at github.com/coreos/go-etcd/

This bug is about the Go client library for etcd (github.com/coreos/go-etcd/etcd), I'm using this function:

func (c *Client) Watch(prefix string, waitIndex uint64, recursive bool,
    receiver chan *Response, stop chan bool) (*Response, error)

in the following gist: https://gist.github.com/yangzh/eb1e4e5809c5fa13ad3d
The channel (that watches etcd update) gets closed by the client library in an unpredictable way, making my server unable to communicate with etcd service. This normally happens after about 5min after the server starts, I have no clue how it was caused.

I'm happy to provide more details if needed.

**Comment by yichengq** [comment]
etcd doesn't have 5min watch timeout now, and go-etcd has been improved to handle the watch better.
