### ISSUE TITLE
Incorrect URIs for some lease related functions in JSON API

### ISSUE THREAD

**Issue by akashbaid** [coreos/etcd#9430]
Some Lease related URIs for the HTTP/JSON API appear to be incorrect in the generated Swagger API definitions at: https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/apispec/swagger/rpc.swagger.json

**Correct URIs:** 

- "/v3/lease/grant"
- "/v3/lease/keepalive"

**Possibly incorrect URIs:** 

- "/v3/kv/lease/leases"
- "/v3/kv/lease/revoke"
- "/v3/kv/lease/timetolive"

As per the API guide, I think these should not be under the "kv" service. Not sure if the problem is just with the Swagger JSON but also in the code.

**Comment by hexfusion** [comment]
I will do a bit of testing with this soon, if it works would you like to take it on @akashbaid ?

**Comment by hexfusion** [comment]
@akashbaid Well this is not going to be as easy as that. Leases are showing expired with timetolive, will try to dig in when I get some time but feel free to test and explore on your own.

```
diff --git a/etcdserver/etcdserverpb/rpc.proto b/etcdserver/etcdserverpb/rpc.proto
index 0cfad92ab..826dff5fb 100644
--- a/etcdserver/etcdserverpb/rpc.proto
+++ b/etcdserver/etcdserverpb/rpc.proto
@@ -90,8 +90,12 @@ service Lease {
   // LeaseRevoke revokes a lease. All keys attached to the lease will expire and be deleted.
   rpc LeaseRevoke(LeaseRevokeRequest) returns (LeaseRevokeResponse) {
       option (google.api.http) = {
-        post: "/v3/kv/lease/revoke"
+        post: "/v3/lease/revoke"
         body: "*"
+
+        additional_bindings {
+            post: "/v3/kv/lease/revoke"
+        }
     };
   }

@@ -107,16 +111,24 @@ service Lease {
   // LeaseTimeToLive retrieves lease information.
   rpc LeaseTimeToLive(LeaseTimeToLiveRequest) returns (LeaseTimeToLiveResponse) {
       option (google.api.http) = {
-        post: "/v3/kv/lease/timetolive"
+        post: "/v3/lease/timetolive"
         body: "*"
+
+        additional_bindings {
+            post: "/v3/kv/lease/timetolive"
+        }
     };
   }

   // LeaseLeases lists all existing leases.
   rpc LeaseLeases(LeaseLeasesRequest) returns (LeaseLeasesResponse) {
       option (google.api.http) = {
-        post: "/v3/kv/lease/leases"
+        post: "/v3/lease/leases"
         body: "*"
+
+        additional_bindings {
+            post: "/v3/kv/lease/leases"
+        }
     };
   }
 }
```

**Comment by gyuho** [comment]
Let's define `additional_bindings` for 3.4, and deprecate them all in 3.5.

**Comment by hexfusion** [comment]
> Let's define additional_bindings for 3.4, and deprecate them all in 3.5.

@gyuho sounds good I got this to work the newline seemed to cause the issue between body and the binding. Will issue PR.

**Comment by gyuho** [comment]
@hexfusion I got it to work, by adding comma after body line?
