### ISSUE TITLE
gh: new tracking labels

### ISSUE THREAD

**Issue by hexfusion** [coreos/etcd#9431]
I would like to add a GitHub labels `gRPC-gateway` and  `Metrics` or `Prometheus` for issue tracking. Any input here? @gyuho

**Comment by gyuho** [comment]
Oh that's what you meant by grouping. Yes, you can add here https://github.com/coreos/etcd/labels.

Please let me know if you don't have "edit" access to "labels".

**Comment by hexfusion** [comment]
complete
