### ISSUE TITLE
clientv3: how to call public methods of healthBalancer?

### ISSUE THREAD

**Issue by jefurry** [coreos/etcd#9434]
i read source codes of clientv3. healthBalancer has some public methods, such as Start, UP, Notify, ConnectNotify, Close etc. but it uses only in Client struct and healthBalancer is private in Client struct, how to call public methods of healthBalancer?

**Comment by gyuho** [comment]
Those public methods were to implement gRPC Balancer interface, so not meant be consumed by etcd client users.

**Comment by jefurry** [comment]
thanks.
