### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by wjx0912** [coreos/etcd#9435]
hi, i find same issues https://github.com/coreos/etcd/issues/9235
not resolved but closed.

`C:\Users\clock>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\clock\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\goproject\common;D:\goproject\prj1;D:\goproject\prj2;D:\goproject\prj3;D:\goproject\prj4;D:\goproject\prj5;D:\goproject\prj6;D:\goproject\test;D:\goproject\wblog;
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2 -static
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\clock\AppData\Local\Temp\go-build726914806=/tmp/go-build -gno-record-gcc-switches

C:\Users\clock>
C:\Users\clock>
C:\Users\clock>
C:\Users\clock>go get -u -v github.com/coreos/etcd
github.com/coreos/etcd (download)
# github.com/coreos/etcd
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
c:/mingw-nuwen/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -ldl
collect2.exe: error: ld returned 1 exit status
`

i test several mingw64 variate toolchain, but all failed.

**Comment by gyuho** [comment]
Can you help us fix this?

**Comment by hexfusion** [comment]
I don't have windows but google search brings up this. https://groups.google.com/forum/#!topic/spatialite-users/vWDE2fTWy6o perhaps this can be useful to debug.

**Comment by wjx0912** [comment]
hi,
i think it's mingw64 problem, 
the mingw64 doesn't have dlfcn.h and libdl.a, but coreos use the functions.

please close this issue, thanks.

**Comment by hexfusion** [comment]
> if you carefully check the how-to guide about MinGW-64
you'll discover that the expected argument is
"--target=mingw32", even when using the 64 bit compiler;
this will effectively trigger the Windows native API
support, and will discard any reference to -ldl
"--target=mingw64" simply is an unrecognized option,
and will have absolutely no action. 

From the link I think this kind of sums it up.
