### ISSUE TITLE
Not need to use gateway or grpc-proxy of etcd?

### ISSUE THREAD

**Issue by jefurry** [coreos/etcd#9440]
clientv3 includes some features with cluster, health balancer etc. and clientv3 will be auto sync member list, so we are not need to use gateway or grpc-proxy of etcd?

**Comment by gyuho** [comment]
gateway is just tcp packet router, grpc-gateway is for HTTP endpoints.
So, if you use clientv3, you don't need grpc-gateway.

**Comment by jefurry** [comment]
i see. i am said not use gateway and grpc-proxy? my application direct connect to endpoints? because clientv3 includes features of all.

**Comment by gyuho** [comment]
Yeah, just use clientv3 by specifying your endpoints. grpc-proxy is for scale out the number of watchers.

**Comment by jefurry** [comment]
ok, thanks! 
https://coreos.com/etcd/docs/latest/op-guide/grpc_proxy.html
