### ISSUE TITLE
why change the code for dealing with ‘/health’ interface in v3 version?

### ISSUE THREAD

**Issue by taohuadaozhu9** [coreos/etcd#9448]
i meet a problem that the 'health' interface return 503 with a little percent. just like this below 3 issues:
https://github.com/coreos/etcd/issues/9113
https://github.com/coreos/etcd/issues/6756
https://github.com/coreos/etcd/pull/4968
but it seems they didn't slove it.

my version is 2.2.4 (okey, it is so old :) 
I am sure it is not because of netwok problem or leader reelection or hardware performance. we meet it in many commercial env and our lab. we checked logs but did not find any problem.

then i checked the code for '/health' interface in 3.2.0 version and found the code is changed as below:
```
func healthHandler(server *etcdserver.EtcdServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !allowMethod(w, r.Method, "GET") {
			return
		}
		if uint64(server.Leader()) == raft.None {
			http.Error(w, `{"health": "false"}`, http.StatusServiceUnavailable)
			return
		}
		ctx, cancel := context.WithTimeout(context.Background(), time.Second)
		defer cancel()
		if _, err := server.Do(ctx, etcdserverpb.Request{Method: "QGET"}); err != nil {
			http.Error(w, `{"health": "false"}`, http.StatusServiceUnavailable)
			return
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"health": "true"}`))
	}
}
```

but in 2.2.4 version, the code is this:
```
func healthHandler(server *etcdserver.EtcdServer) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !allowMethod(w, r.Method, "GET") {
			return
		}

		if uint64(server.Leader()) == raft.None {
			http.Error(w, `{"health": "false"}`, http.StatusServiceUnavailable)
			return
		}

		// wait for raft's progress
		index := server.Index()
		for i := 0; i < 3; i++ {
			**time.Sleep(250 * time.Millisecond)**
			if server.Index() > index {
				w.WriteHeader(http.StatusOK)
				w.Write([]byte(`{"health": "true"}`))
				return
			}
		}

		http.Error(w, `{"health": "false"}`, http.StatusServiceUnavailable)
		return
	}
}
```

my question is:

1. why do you change the code? is there any prolem found before?  or the method to check health in 2.2.4 version is not reliable?
2. why do you set the timeout to '250 * time.Millisecond'  for 3 loop times in 2.2.4 version?
3. why do you set the timeout to 1 second  in 3.2.0 version?

thanks a lot!

**Comment by taohuadaozhu9** [comment]
@gyuho  do you know why?

**Comment by hexfusion** [comment]
> why do you set the timeout to '250 * time.Millisecond' for 3 loop times in 2.2.4 version?

@taohuadaozhu9 For why it changed please review. https://github.com/coreos/etcd/pull/7068

**Comment by hexfusion** [comment]
The information to answer your questions seem to be found in the linked issues. Feel free to continue conversation here if you have more related questions.
