### ISSUE TITLE
How work by php v3 client?

### ISSUE THREAD

**Issue by jefurry** [coreos/etcd#9455]
How work by php v3 client? which one is the best php v3 client?

**Comment by hexfusion** [comment]
@jefurry quick review of https://github.com/coreos/etcd/blob/master/Documentation/integrations.md shows 2 PHP clients both are for v2 I am afraid.

**Comment by hexfusion** [comment]
https://github.com/ouqiang/etcd-php
But this looks promising if you want to check it out maybe reach out to author about adding to integrations list if it works out?
