### ISSUE TITLE
When the network isolated node in etcd recovers，what is the status of etcd?

### ISSUE THREAD

**Issue by chunqiulfq** [coreos/etcd#9459]
When the network isolated node in etcd recovers，what is the status of etcd?
I want to know when the etcd isolated node resumes communication with the cluster network, but the data hasn't been synchronized yet, what happens when a request is received？

**Comment by gyuho** [comment]
As long as quorum is up, cluster continues to serve client requests.

And the client balancer would switch over to non-partitioned node, on request failure.

**Comment by zyf0330** [comment]
I think he wants to ask that, when a query request arrives at isolated nodes, who will handle it?
For example, there are 7 nodes cluster, and three nodes are isolated and then resume communication with other 4 nodes, they need to sychonize newest data before providing service, at this time which will handle the query request to these three nodes?

**Comment by chunqiulfq** [comment]
@gyuho 
As @zyf0330 said, when the isolated node resumes communicating with the leader, it needs to synchronize the data. When this node is quarantined, the request will fail. So how does this node receive the request **during this node's recovery from the leader communication to the data synchronization**? Is the request failed?

**Comment by gyuho** [comment]
> I think he wants to ask that, when a query request arrives at isolated nodes, who will handle it?

If the request were serializable read, it can be still served locally by partitioned node. If the isolated node belongs to minority partition and the request were linearizable read, the request will fail because there's no active leader in the minority partition.

**Comment by zyf0330** [comment]
Thanks for your reply.
