### ISSUE TITLE
v3 api 404 error

### ISSUE THREAD

**Issue by peng0208** [coreos/etcd#9472]
Version: v3.3.2
api: v3
problem: **404 error page is shown.**
![image](https://user-images.githubusercontent.com/21224670/37699766-d6257cfc-2d23-11e8-97fc-86be387f5e3f.png)
Why ?
But *http://127.0.0.1:23790/v3beta/kv/range* is accessable.

**Comment by hexfusion** [comment]
Hi @peng0208 /v3 will be available in 3.4+ or is now available now in master.
https://github.com/coreos/etcd/blob/master/CHANGELOG-3.3.md#added-grpc-gateway

ref: https://github.com/coreos/etcd/issues/9189
