### ISSUE TITLE
Watch through etcdv2 HTTP API, any way to get all continuous modifications with one request?

### ISSUE THREAD

**Issue by 2225377fjs** [coreos/etcd#9477]
As title, for example:
Watch at index 100,  at etcd server  modifications at index 110 and 120 are related,  so this time http response is info about index 110.
Is there any way to get all infos of index 110 and 120 with only one http watch request?

**Comment by gyuho** [comment]
v2 store does not support historical data.
So if you watch on a key, for every write, previous value will be overwritten.
You have to track those manually.

I would try v3 API.

**Comment by 2225377fjs** [comment]
@gyuho  thanks
https://coreos.com/etcd/docs/latest/v2/api.html

It mentioned "etcd only keeps the responses of the most recent 1000 events across all etcd keys"

If all related modifications are all in recent 1000 event, I think there is some way to get them through one HTTP request.

**Comment by gyuho** [comment]
@2225377fjs Try `client.WatcherOptions{AfterIndex: x}`?
