### ISSUE TITLE
High etcd 2.2.5 IO writes and CPU IOwait on really small Kubernetes cluster (3 nodes)

### ISSUE THREAD

**Issue by zwindler** [coreos/etcd#9478]
Hello,

This is not a really a bug report, maybe between the bug report and the question.

We have a few really small Kubernetes clusters hosted on azure virtual machines (IaaS). These clusters are composed of 3 masters which are also running etcd 2.2.5 directly on the host (not in a pod), and a few workers (3 on average).

To provide better performance, the etcd working directory is separated from the OS disk, and is SSD storage providing 500 IOPS and a throughput limit of 100 MB/sec which seemed to be more than enough for this really small cluster.

On all clusters, we are recording a really high amount of CPU IOwait on all master nodes (~40%) and a constant 300 IOPS (100% writes) and 1MB/s writen. All of this comes from the etcd process and is located on etcd own disk.

As far as we can tell, the azure SSD disk hosting etcd working directory is not up to its limit (we made some tests and got to the advertised 500 with both big and small writes). The performance throughput doesn't seem to be the issue also as we are very far from the 100 MB/s limit.

I'm really skeptical about this intensive write use of the SSD provided to etcd and I feel that this is not a normal behaviour, especially for such a small cluster (3 workers only !).

Can you provide me with some input regarding whether or not this is a normal behaviour ?

Some additionnal informations 
```
d.germain@k8s-master0:~$ etcd --version
etcd Version: 2.2.5
Git SHA: Not provided (use ./build instead of go build)
Go Version: go1.6.2
Go OS/Arch: linux/amd64

d.germain@k8s-master0:~$ sudo systemctl cat etcd2
# /lib/systemd/system/etcd.service
[Unit]
Description=etcd - highly-available key value store
Documentation=https://github.com/coreos/etcd
Documentation=man:etcd
After=network.target
Wants=network-online.target

[Service]
Environment=DAEMON_ARGS=
Environment=ETCD_NAME=%H
Environment=ETCD_DATA_DIR=/var/lib/etcd/default
EnvironmentFile=-/etc/default/%p
Type=notify
User=etcd
PermissionsStartOnly=true
#ExecStart=/bin/sh -c "GOMAXPROCS=$(nproc) /usr/bin/etcd $DAEMON_ARGS"
ExecStart=/usr/bin/etcd $DAEMON_ARGS
Restart=on-failure
#RestartSec=10s
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
Alias=etcd2.service

d.germain@k8s-master0:~$ sudo journalctl -u etcd2
-- No entries --
```

**Comment by gyuho** [comment]
etcd is write-intensive for consistent distributed log replication. So high IOPS is expected.
I would try to upgrade to latest etcd first. One huge benefit would be quorum read with no I/O (from v3.1).

**Comment by xiang90** [comment]
etcd 2.x is not maintained anymore. Please move to 3.x.

**Comment by zwindler** [comment]
Hi,

Thanks @gyuho for your valuable input
