### ISSUE TITLE
optimize NewClient in client V3

### ISSUE THREAD

**Issue by jiaxuanzhou** [coreos/etcd#9488]
https://github.com/coreos/etcd/blob/a994fdedb36ed911bc775e53005340ca3771b5dd/clientv3/client.go#L93
suggest `func NewFromURL(url []string) (*Client, error) `  to new a v3 client?

**Comment by gyuho** [comment]
@jiaxuanzhou Do you want to contribute to adding that function?

**Comment by jiaxuanzhou** [comment]
@gyuho will submit one pr soon
