### ISSUE TITLE
why there is always a dummy entry when init?

### ISSUE THREAD

**Issue by lichuang** [coreos/etcd#9489]
MemoryStorage init with a dummy entry as the first entry in entry vector,as well as a node become leader,the leader will always append a dummy entry,can any one explain the reason?

**Comment by gyuho** [comment]
Raft guarantees leader has all committed entries for a given term. But, if leader is at the start of its current term, it may not know which those entries are. That's why leader commits a blank no-op entry at the beginning of a term.

You can read more about this in Raft paper.
