### ISSUE TITLE
raft: tests in rafftest fail because of improper field casing

### ISSUE THREAD

**Issue by kchristidis** [coreos/etcd#9504]
Head: `053bab06d`

```bash
~/Go/src/github.com/coreos/etcd/raft/rafttest (master) $ go test
# github.com/coreos/etcd/raft/rafttest
./node_bench_test.go:26:26: unknown field 'Id' in struct literal of type raft.Peer (but does have ID)
./node_test.go:26:26: unknown field 'Id' in struct literal of type raft.Peer (but does have ID)
./node_test.go:52:26: unknown field 'Id' in struct literal of type raft.Peer (but does have ID)
./node_test.go:92:26: unknown field 'Id' in struct literal of type raft.Peer (but does have ID)
FAIL    github.com/coreos/etcd/raft/rafttest [build failed]
```

Unless I'm missing something and this is somehow the desired behavior, these tests are broken and the fix is simple (change all the `Id` field references to `ID`).

Submitting a PR on this now.

**Comment by kchristidis** [comment]
Correct, I believe this is the changeset that introduced the issue.

Any idea why this isn't covered in CI?

**Comment by hexfusion** [comment]
> Any idea why this isn't covered in CI?

That is a good question @gyuho, what are your thoughts here?

**Comment by gyuho** [comment]
@hexfusion It's skipping `rafttest` to bypass `unused` linters https://github.com/coreos/etcd/blob/release-3.0/test#L16-L23.
