### ISSUE TITLE
how to add  member in etcd v3.1.11 which not on Container Linux

### ISSUE THREAD

**Issue by yingyan003** [coreos/etcd#9516]
I have found the document in https://coreos.com/etcd/docs/latest/tls-etcd-clients.html,but my etcd is v3.1.11,the method you show seems on Container Linux,but I didn't use it.So I seems not suit to me. I 
 use etcd banary file to set up etcd. Here My configurantion:
![image](https://user-images.githubusercontent.com/30212457/38189353-5d2e9bc6-3692-11e8-8f34-6975c0e70cf7.png)
Can you help me how I can add one Member to existing cluster?Thanks.

**Comment by hexfusion** [comment]
Hi @yingyan003, please review [etcd add new member](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#add-a-new-member) and let us know if you have any questions.

**Comment by gyuho** [comment]
@yingyan003 Please try `member add` command

```bash
# member add
ETCDCTL_API=3 /tmp/test-etcd/etcdctl \
  --endpoints localhost:2379,localhost:22379 \
  --cacert ${HOME}/certs/etcd-root-ca.pem \
  --cert ${HOME}/certs/s1.pem \
  --key ${HOME}/certs/s1-key.pem \
  member add s3 --peer-urls=https://localhost:32380
```

And restart the new member with `--initial-cluster-state existing` flag.

And let us know if it still doesn't work.
