### ISSUE TITLE
etcdctl/ctlv3: Error: table not supported as output format

### ISSUE THREAD

**Issue by ncsibra** [coreos/etcd#9522]
Hi,

The etcdctl tool mention that the "table" output format is supported, but I got back an error.

```bash
➜  ~ etcdctl version                                                                                                                                                                  
etcdctl version: 3.3.2
API version: 3.3
➜  ~ etcdctl --help                                                                                                                                                                   
...
  -w, --write-out="simple"			set the output format (fields, json, protobuf, simple, table)
...
➜  ~ etcdctl -w table get a                                                                                                                                                           
Error: table not supported as output format

```
The other options work fine.

**Comment by gyuho** [comment]
This was never supported (e.g. too large value to fit in table).

**Comment by ncsibra** [comment]
Then maybe just the flag description is incorrect.

**Comment by xiang90** [comment]
@ncsibra how do you suggest to improve the flag description?

**Comment by ncsibra** [comment]
Maybe just remove the table option if it not supported? :)
But I think it would be useful for smaller values, they would fit in the table easily. The other formats are not always helpful, because simple does not return the revisions/version, fields does not separate the values, e.g. when we're using `--prefix` and the command returns more than one kv and json does not decode the base64 key/values so really hard to figure out what are they. The last one maybe a bug, I don't know, but strangely that's the only one which not doing the decoding for us.

**Comment by gyuho** [comment]
@ncsibra Please send a PR to improve if you have time. Thanks!
