### ISSUE TITLE
Call etcd3 without version api store key-value, etcd will automatically clear the history keyvalue?

### ISSUE THREAD

**Issue by zonghaishang** [coreos/etcd#9553]
@xiang90

1. Call etcd3 without version api store key-value ( eg: jetcd `com.coreos.jetcd.KV#put(com.coreos.jetcd.data.ByteSequence, com.coreos.jetcd.data.ByteSequence)`), etcd will automatically clear the history keyvalue?

2. Or the client user must manually call the clean history keyvalue method ？

**Comment by gyuho** [comment]
@zonghaishang The overwritten data will be preserved unless it's compacted with higher revision. So, either server auto-compacts it or client calls compact request to discard historical data. Otherwise, the old data will be kept, and can be queried by specific revisions.

**Comment by gyuho** [comment]
@zonghaishang Ping? Did I understand your question correctly?

**Comment by zonghaishang** [comment]
@gyuho 
Thanks for your replay, My understanding is that：
1. server side, I'm should do nothing, server will auto-compacts it
2. client side, I should call the compact method then release the historical version data.

**Comment by gyuho** [comment]
> server side, I'm should do nothing, server will auto-compacts

You can still configure `--auto-compaction-retention`.

> client side, I should call the compact method then release the historical version data.

Yes.
