### ISSUE TITLE
ETCD with authentication: Granting permission to create Snapshot?

### ISSUE THREAD

**Issue by ChrisCavegn** [coreos/etcd#9554]
In my setup, etcd runs with enabled authentication and I need to automatically create snapshots.

Is it required that my backup-user has to be member of the root-group?
Or is it possible to grant snapshot-rights to a specific user?

**Comment by mitake** [comment]
@ChrisCavegn yes, your user for backup purpose needs to have root role.

**Comment by ChrisCavegn** [comment]
@mitake Thank you for your clarification
