### ISSUE TITLE
Interpret Etcd Metrics

### ISSUE THREAD

**Issue by spirrello** [coreos/etcd#9561]
Hi,

I'm troubleshooting a problem that is likely due to disk latency but need to understand these metrics before presenting them to my infrastructure team.

**If I look at this line --> etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 126016**

**Is this saying that fsync took over 8 seconds 126016 times?**

**Also what do the following two lines indicate?**

etcd_disk_wal_fsync_duration_seconds_sum 2897.086810966015
etcd_disk_wal_fsync_duration_seconds_count 126025

Gather the metrics above from the following curl.
curl http://127.0.0.1:2379/metrics | grep fsync

etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 100675
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 113120
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 116734
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 118832
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 120003
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 121029
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 122230
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 123199
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 123909
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 124594
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 125215
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 125711
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 125967
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 126016
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 126025
etcd_disk_wal_fsync_duration_seconds_sum 2897.086810966015
etcd_disk_wal_fsync_duration_seconds_count 126025

**Comment by gyuho** [comment]
It means `less or equal` https://github.com/prometheus/client_golang/blob/e11c6ff8170beca9d5fd8b938e71165eeec53ac6/prometheus/histogram.go#L50-L52. And this metrics is histogram https://prometheus.io/docs/concepts/metric_types/#histogram.

**Comment by gyuho** [comment]
We will improve https://github.com/coreos/etcd/blob/master/Documentation/op-guide/monitoring.md on how to intepret some important metrics.

**Comment by hexfusion** [comment]
@gyuho I would be glad to extend this doc if you have not started.
