### ISSUE TITLE
etcd:etcdserverpb.Watch  Unavailable

### ISSUE THREAD

**Issue by AnberLu** [coreos/etcd#9576]
i start my etcd , i find some msg from metric:
```
grpc_server_handled_total{grpc_code="Unavailable",grpc_method="Watch",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream"} 2
```
but,when i restart etcd , this msg never show again.

**Comment by gyuho** [comment]
> but,when i restart etcd 

You should set up a separate Prometheus node_exporter if you want to persist previous metrics data. Metrics served via etcd does not get stored on disk. So on reboot, etcd starts over collecting metrics.
