### ISSUE TITLE
System-wide etcdctl.conf

### ISSUE THREAD

**Issue by mrueg** [coreos/etcd#9581]
It would be nice, if etcdctl would look up configuration settings from a system-wide configuration file, e.g. /etc/etcdctl/etctcdl.conf. 
This would allow to define apiversion and various other settings in addition to environment variables and shorten down etcdctl calls without the need for a wrapper-script around etcdctl.
Environment variables should still be able to shadow settings from etcdctl.conf

**Comment by hexfusion** [comment]
Hi @mrueg! Would ENV variables alone suffice for you as we support them already? If not could you outline your use case where a config works better for you?  I think a config file for the client binary might be more complicated then it needs to be but let's see how others feel.

https://github.com/coreos/etcd/tree/master/etcdctl#etcdctl

**Comment by mrueg** [comment]
Thanks for your fast reply @hexfusion 
My use case here is to pin the connected etcd servers, api version and used cert/key paths. This is possible via environment variables, but sometimes those are not available and I'd like to use my custom "sane defaults" as a fallback. Otherwise this would require me to attach them to any etcdctl call or write a wrapper around etcdctl (that does the former).

**Comment by fanminshi** [comment]
Maybe viper https://github.com/spf13/viper can help.

**Comment by gyuho** [comment]
> This would allow to define apiversion and various other settings in addition to environment variables and shorten down etcdctl calls without the need for a wrapper-script around etcdctl.

> use my custom "sane defaults" as a fallback

Do you have example settings in your etcdctl wrapper script?

**Comment by gyuho** [comment]
@mrueg Those client-specific configurations could be supported via YAML file, as is supported for `etcd`. Then we would have 3 kinds of configuration format; flag, YAML, environment variable. Keep them in sync is a lot of work. We'd rather keep it simple for now.

**Comment by gyuho** [comment]
Let me close this. Will revisit once etcdctl flags are stabilized and we find an easy way to automate YAML configuration support.
