### ISSUE TITLE
Does clientv3 support 32-bit system?

### ISSUE THREAD

**Issue by Pc6** [coreos/etcd#9585]
According to the [op-guide](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/supported-platform.md) on supported systems, etcd server has known issues on 32-bit systems due to a bug in the Go runtime. 
The issues are mainly caused by the usage of package `sync/atomics`. And the clientv3 package doesn't import the `sync/atomics`, does it mean that clientv3 can be used stably in 32-bit system?

**Comment by hexfusion** [comment]
> does it mean that clientv3 can be used stably in 32-bit system?

Hi @Pc6 on the client level this should be OK as your calls to the server are presumably over TCP thus archtecture agnostic . So as long as the binary compiles I believe this should be stable. Think of a 32bit browser connecting to a 64bit web server.

Would you mind testing and reporting back your results? If all is well maybe you could append the docs? Thanks!

**Comment by Pc6** [comment]
Sure, I'm glad to : )

**Comment by Pc6** [comment]
@hexfusion as for the test result, I have been tested the clientv3 in 32-bit system with the test cases presented in the package. The client performs well. My testing platform is **Ubuntu Server 16.04.1 LTS 32-bit**, and go version is **go1.10.1 linux/386**. Should I offer more test cases so that I can append the docs?

**Comment by gyuho** [comment]
@Pc6 If you use 64-bit for server, 32-bit client should just work. But make sure to test it. We don't say it's stable in the doc, because we don't run all integration tests for 32-bit. You might try run

> GOARCH=386 CPU=4 PASSES='integration' ./test

And report to us if you find any bugs.
