### ISSUE TITLE
add X-Etcd-Index for /v2/members handlers

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#959]
So people could figure out the logical time.

**Comment by xiang90** [comment]
@yichengq Can I know why you would like to have this feature? Do you have a use case in mind?

**Comment by yichengq** [comment]
The original usage is to compare the results from different /v2/members. If it has an index, it helps:

1. know which cluster info is the latest
2. help to debug and explain to end user

using /health endpoint could be an good alternative for this today. We could revisit this when there is other use cases.

**Comment by xiang90** [comment]
@yichengq I am closing this since we do not have a clear use case. If we do have one in the future, I would prefer to have a separate index starting from 1. Say cluster-version 1, 2, 3 ...
