### ISSUE TITLE
 etcd metric moved to SSD

### ISSUE THREAD

**Issue by itnikita** [coreos/etcd#9593]
@hexfusion
Issue#9427
As your saying,SSD is strongly recommended vs HDD.
Now etcd cluster was moved to SSD.
Please check the metric. Is that OK?

Now the error logs never appear after moved to SSD.

 curl 127.0.0.1:2379/metrics | grep etcd_disk_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 0
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 6
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 6
etcd_disk_backend_commit_duration_seconds_sum 0.008433969999999999
etcd_disk_backend_commit_duration_seconds_count 6
# HELP etcd_disk_backend_snapshot_duration_seconds The latency distribution of backend snapshots.
# TYPE etcd_disk_backend_snapshot_duration_seconds histogram
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.01"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.02"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.04"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.08"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.16"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.32"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.64"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="1.28"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="2.56"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="5.12"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="10.24"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="20.48"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="40.96"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="81.92"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="163.84"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="327.68"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="655.36"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_snapshot_duration_seconds_sum 0
etcd_disk_backend_snapshot_duration_seconds_count 0
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 1
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 2
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 3
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 3
etcd_disk_wal_fsync_duration_seconds_sum 0.0048297340000000005
etcd_disk_wal_fsync_duration_seconds_count 3
100  123k  100  123k    0     0  12.4M      0 --:--:-- --:--:-- --:--:-- 13.3M

**Comment by hexfusion** [comment]
Yes I only see 3 records but they are less than or equal 4ms. I would say that is very fast! :)

**Comment by itnikita** [comment]
here is the logs from the node etcd1 in the etcd cluster,when I start k8s master kube-apiserver in every 3 node.
when I restart the k8s kube-apiserver the logs about rejected connection shows up 
k8s version is 1.7.2
 
Apr 26 16:32:31 etcd1 etcd[14054]: lost the TCP streaming connection with peer 7196e1d26380cfc5 (stream Message reader)
Apr 26 16:32:31 etcd1 etcd[14054]: failed to dial 7196e1d26380cfc5 on stream MsgApp v2 (EOF)
Apr 26 16:32:31 etcd1 etcd[14054]: peer 7196e1d26380cfc5 became inactive
Apr 26 16:32:32 etcd1 etcd[14054]: lost the TCP streaming connection with peer 7196e1d26380cfc5 (stream Message writer)
Apr 26 16:32:33 etcd1 etcd[14054]: peer 7196e1d26380cfc5 became active
Apr 26 16:32:33 etcd1 etcd[14054]: established a TCP streaming connection with peer 7196e1d26380cfc5 (stream Message reader)
Apr 26 16:32:33 etcd1 etcd[14054]: established a TCP streaming connection with peer 7196e1d26380cfc5 (stream Message writer)
Apr 26 16:32:33 etcd1 etcd[14054]: closed an existing TCP streaming connection with peer 7196e1d26380cfc5 (stream MsgApp v2 writer)
Apr 26 16:32:33 etcd1 etcd[14054]: established a TCP streaming connection with peer 7196e1d26380cfc5 (stream MsgApp v2 writer)
Apr 26 16:32:33 etcd1 etcd[14054]: established a TCP streaming connection with peer 7196e1d26380cfc5 (stream MsgApp v2 reader)
Apr 26 16:34:02 etcd1 etcd[14054]: rejected connection from "192.168.9.151:25516" (error "EOF", ServerName "")
Apr 26 16:34:57 etcd1 etcd[14054]: store.index: compact 153
Apr 26 16:34:57 etcd1 etcd[14054]: finished scheduled compaction at 153 (took 72.182µs)

**what it happend when it shows that**
rejected connection from "192.168.9.151:25516" (error "EOF", ServerName "")

etcd1 192.168.9.151
etcd2 192.168.9.152
etcd3 192.168.9.153

I find out that the etcd1 is the leader of the cluster.

**Comment by itnikita** [comment]
after I restat the kube-apiserver.I have to restart etcd1 ,better to restart all the etcd cluster to fix the error.

when I restart the kube-apiserver, the etcd logs shows at the beginning  
rejected connection from "192.168.9.151:25516" (error "EOF", ServerName "")
but later much of logs as follows came up

Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21184" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21186" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21188" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21190" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21192" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21194" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21196" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21202" (error "tls: first record does not look like a TLS handshake", ServerName "")
Apr 26 16:49:32 etcd1 etcd[14054]: rejected connection from "192.168.9.151:21206" (error "tls: first record does not look like a TLS handshake", ServerName

**Comment by itnikita** [comment]
here is the metric of the 3 nodes
curl 127.0.0.1:2379/metrics | grep etcd_disk_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 1
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 4
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 9
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 9
etcd_disk_backend_commit_duration_seconds_sum 0.017873569
etcd_disk_backend_commit_duration_seconds_count 9
# HELP etcd_disk_backend_snapshot_duration_seconds The latency distribution of backend snapshots.
# TYPE etcd_disk_backend_snapshot_duration_seconds histogram
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.01"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.02"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.04"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.08"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.16"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.32"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.64"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="1.28"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="2.56"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="5.12"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="10.24"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="20.48"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="40.96"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="81.92"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="163.84"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="327.68"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="655.36"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_snapshot_duration_seconds_sum 0
etcd_disk_backend_snapshot_duration_seconds_count 0
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 6
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 12
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 13
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 13
etcd_disk_wal_fsync_duration_seconds_sum 0.016109090000000003
etcd_disk_wal_fsync_duration_seconds_count 13
100  123k  100  123k    0     0  12.8M      0 --:--:-- --:--:-- --:--:-- 13.3M

**Comment by itnikita** [comment]
etcd3 node metric 
curl 127.0.0.1:2379/metrics | grep etcd_disk_
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP etcd_disk_backend_commit_duration_seconds The latency distributions of commit called by backend.
# TYPE etcd_disk_backend_commit_duration_seconds histogram
etcd_disk_backend_commit_duration_seconds_bucket{le="0.001"} 1
etcd_disk_backend_commit_duration_seconds_bucket{le="0.002"} 11
etcd_disk_backend_commit_duration_seconds_bucket{le="0.004"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.008"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.016"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.032"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.064"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.128"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.256"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="0.512"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="1.024"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="2.048"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="4.096"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="8.192"} 29
etcd_disk_backend_commit_duration_seconds_bucket{le="+Inf"} 29
etcd_disk_backend_commit_duration_seconds_sum 0.059180726
etcd_disk_backend_commit_duration_seconds_count 29
# HELP etcd_disk_backend_snapshot_duration_seconds The latency distribution of backend snapshots.
# TYPE etcd_disk_backend_snapshot_duration_seconds histogram
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.01"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.02"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.04"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.08"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.16"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.32"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="0.64"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="1.28"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="2.56"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="5.12"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="10.24"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="20.48"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="40.96"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="81.92"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="163.84"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="327.68"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="655.36"} 0
etcd_disk_backend_snapshot_duration_seconds_bucket{le="+Inf"} 0
etcd_disk_backend_snapshot_duration_seconds_sum 0
etcd_disk_backend_snapshot_duration_seconds_count 0
# HELP etcd_disk_wal_fsync_duration_seconds The latency distributions of fsync called by wal.
# TYPE etcd_disk_wal_fsync_duration_seconds histogram
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001"} 27
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002"} 49
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192"} 55
etcd_disk_wal_fsync_duration_seconds_bucket{le="+Inf"} 55
etcd_disk_wal_fsync_duration_seconds_sum 0.06612963499999999
etcd_disk_wal_fsync_duration_seconds_count 55
100  123k  100  123k    0     0  12.6M      0 --:--:-- --:--:-- --:--:-- 13.3M

**Comment by itnikita** [comment]
I still do not know how to run benchmark .
all the files ends with go.
I donot know how to compile it 
or is there a binary files, so I can run it

**Comment by hexfusion** [comment]
@itnikita it sounds like your problem is solved by moving to SSD. Please open a new issue if you run into any other errors! Thanks!
