### ISSUE TITLE
Specifying transport timeout

### ISSUE THREAD

**Issue by CMajeri** [coreos/etcd#9594]
Hi guys,

So I've had a few issues with my etcd installation ever since I switched to TLS (and, by extension, hostnames instead of IPs in URLs).
I have two resolvers on my host, one for a kubernetes DNS, which comes first. and another with my regular DNS. The kubernetes DNS can't work as long as etcd is off, so resolutions tend to take some time. This caused etcd to fail with `i/o timeout` errors when trying to reach peers.

A quick look in the code showed this :

```
t, err := NewTransport(tlsInfo, 5*time.Second)
...
conn, cerr := t.Dial("tcp", ep[len("https://"):])
if cerr != nil {
    errs = append(errs, fmt.Sprintf("%q failed to dial (%v)", ep, cerr))
    continue
}
```

So the timeout used for dialing is set to 5s flat??
Would it be possible to have the possibility to specify this as a parameter??

Thanks.

(edited because I was completely wrong the first time around and thought it had something to do with ReqTimeout when really someone just removed the DNS from resolv.conf...)

**Comment by CMajeri** [comment]
Just to try things out, I recompiled with a timeout set to 50s and it works as I expect...

Would you guys agree with adding that flag? I propose a `--dial-timeout` flag in millisecond that gets used there. I think it would have an added value since my setup can't be that exotic.

**Comment by hexfusion** [comment]
> So the timeout used for dialing is set to 5s flat??

@CMajeri could you please post your startup flags and logs of these timeouts so that we can have a better view of what is going on for reference? Are you using SRV discovery?

**Comment by hexfusion** [comment]
@CMajeri the reason I asked about SRV is the snippet you referenced which shows a hardcoded `t, err := NewTransport(tlsInfo, 5*time.Second)` is part of the ValidateSecureEndpoints function which is only used by discoverEndpoints from what I can tell.

> Just to try things out, I recompiled with a timeout set to 50s and it works as I expect...

Please confirm your code change, I will dig into this a bit more tonight.

**Comment by hexfusion** [comment]
It seems that the 5 second interval is defined by the prober here which basically does a health check against the peer during `AddPeer` at the error interval during bootstrap.

https://github.com/coreos/etcd/blob/913a98567eac90397018ebd38f1ccbd39bf9b668/rafthttp/probing_status.go#L28

> This caused etcd to fail with i/o timeout errors when trying to reach peers.

Can you clarify what you mean here, it seems etcd is only printing logging in which case this is expected. If you see more fatal error please include it in full logs for review.

**Comment by CMajeri** [comment]
Wow it looks like you're right, those ARE just log messages.
Increasing the timeout there just makes the logs much nicer :

```
May 03 08:15:45 host-3.test.com etcd.new[1847]: peer 822183d8a194b77d became active
May 03 08:15:45 host-3.test.com etcd.new[1847]: established a TCP streaming connection with peer 822183d8a194b77d (stream MsgApp v2 reader)
May 03 08:15:45 host-3.test.com etcd.new[1847]: established a TCP streaming connection with peer 822183d8a194b77d (stream Message reader)
May 03 08:15:45 host-3.test.com etcd.new[1847]: peer 3c274ab33c00915c became active
May 03 08:15:45 host-3.test.com etcd.new[1847]: established a TCP streaming connection with peer 3c274ab33c00915c (stream MsgApp v2 reader)
May 03 08:15:45 host-3.test.com etcd.new[1847]: established a TCP streaming connection with peer 3c274ab33c00915c (stream Message reader)
```

But there seems to be no correlation with the fact that it started working...
I'm very confused and will keep looking. But it seems to be my fault rather than etcd!

Thanks for looking into it, I'm sorry, it seems I dreamed a problem and it just happened to get fixed when I tried changing that timeout value...

**Comment by hexfusion** [comment]
@CMajeri no worries I think your approach was logical but since the messages are expected and the result is non-fatal I think we can leave things as is. Thanks for creating the issue please don't hesitate to create a new one if you have more questions!
