### ISSUE TITLE
[kubernetes-deploy]  etcd pod restartPolicy

### ISSUE THREAD

**Issue by shenlanse** [coreos/etcd#9603]
https://github.com/coreos/etcd/blob/master/hack/kubernetes-deploy/etcd.yml

I have a question, why  set pod.Spec.RestartPolicy=Never instead of Always. If we set Always restartPolicy, is there any potential data broken risk?

**Comment by shenlanse** [comment]
@hexfusion @gyuho

**Comment by shenlanse** [comment]
In our production environment, we deploy etcd cluster with kubelet and static pod. So when static pod exits  exceptionally， kubelet will start it automatically.

**Comment by gyuho** [comment]
> I have a question, why set pod.Spec.RestartPolicy=Never instead of Always. If we set Always restartPolicy, is there any potential data broken risk?

There shouldn't be an issue as long as the data have been persisted somewhere and get reloaded on restart. Where do you persist your etcd data?

**Comment by shenlanse** [comment]
@gyuho Thanks for your reply. We store data in local disk. If automatic restart not result in unexpected risk, then our deploy will works fine and set pod.spec.restartpolicy=always is better.

**Comment by gyuho** [comment]
@shenlanse Yeah, as long as the mounted volume or disk is still there, always restart should be correct. 

Actually, could you update that example with your Kubernetes deploy? Ours is outdated.

Thanks!
