### ISSUE TITLE
When rejoin cluster, the instance used the old ID

### ISSUE THREAD

**Issue by wenxuwan** [coreos/etcd#9613]
Hi

Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo df /mnt/rcpha/etcd/ | grep /mnt/rcpha/etcd, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mkdir -p /mnt/rcpha/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chmod 750 /mnt/rcpha/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chown _nokrcpsysha:_nokrcpsysha /mnt/rcpha/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mkdir -p /mnt/rcpha/image/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mount -t tmpfs -o size=294M tmpfs /mnt/rcpha/image/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [145B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Creating filesystem with 301056 1k blocks and 75480 inodes
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Filesystem UUID: 2d2c6010-057b-4458-8aa7-887abe2d82b9
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Superblock backups stored on blocks:
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]:         8193, 24577, 40961, 57345, 73729, 204801, 221185
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [49B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [46B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Creating journal (8192 blocks): done
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [83B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: , stderr is mke2fs 1.44.0 (7-Mar-2018)
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mkdir -p /mnt/rcpha/etcd/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mount -o loop /mnt/rcpha/image/etcd_image /mnt/rcpha/etcd/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo rm /mnt/rcpha/etcd/dummy, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chmod -R 600 /mnt/rcpha/image/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chmod -R 600 /mnt/rcpha/etcd/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The cluster is healthy
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Inquire mn-1 node in cluster from mn-0 node
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: the member have existed in cluster
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The memer in cluster, we need remove it and join again
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The member have in cluster, we will remove it first
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The remove operation result is: Removed member 7262c06152767c6a from cluster
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: **Remove member 7262c06152767c6a**
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]:  success!!
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Remove the old memer success, we will add it now!!
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The add method result is:
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: **Added member named mn-1 with ID 61981f90db63f090 to cluster**
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: ETCD_NAME="mn-1"
Apr 23 03:18:36.040857 mn-1 systemd[1]: Got disconnect on private connection.
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: ETCD_INITIAL_CLUSTER="sn-2=http://sn-2.local:2380,mn-1=http://mn-1.local:2380,mn-0=http://mn-0.local:2380"
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: ETCD_INITIAL_CLUSTER_STATE="existing"
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: add success
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: sn-2=http://sn-2.local:2380,mn-1=http://mn-1.local:2380,mn-0=http://mn-0.local:2380
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: Add the memeber success
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: The etcd configure fished with ETCD_INITIAL_CLUSTER_STATE existing

Apr 23 03:18:36.366625 mn-1 etcd[1753]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.1.8:2379
Apr 23 03:18:36.366672 mn-1 etcd[1753]: recognized and used environment variable ETCD_DATA_DIR=/mnt/rcpha/etcd/rcp20.etcd
Apr 23 03:18:36.366692 mn-1 etcd[1753]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1500
Apr 23 03:18:36.366704 mn-1 etcd[1753]: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=300
Apr 23 03:18:36.366717 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.1.8:2380
Apr 23 03:18:36.366731 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_CLUSTER=mn-0=http://mn-0.local:2380,mn-1=http://mn-1.local:2380,sn-2=http://sn-2.local:2380
Apr 23 03:18:36.366741 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
Apr 23 03:18:36.366750 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=rcp20
Apr 23 03:18:36.366775 mn-1 etcd[1753]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://192.168.1.8:2379,http://127.0.0.1:2379
Apr 23 03:18:36.366786 mn-1 etcd[1753]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.1.8:2380
Apr 23 03:18:36.366800 mn-1 etcd[1753]: recognized and used environment variable ETCD_MAX_SNAPSHOTS=1
Apr 23 03:18:36.366809 mn-1 etcd[1753]: recognized and used environment variable ETCD_MAX_WALS=1
Apr 23 03:18:36.366829 mn-1 etcd[1753]: recognized and used environment variable ETCD_NAME=mn-1
Apr 23 03:18:36.366900 mn-1 etcd[1753]: etcd Version: 3.1.4
Apr 23 03:18:36.366912 mn-1 etcd[1753]: Git SHA: 4e1824f
Apr 23 03:18:36.366919 mn-1 etcd[1753]: Go Version: go1.9.2
Apr 23 03:18:36.366926 mn-1 etcd[1753]: Go OS/Arch: linux/amd64
Apr 23 03:18:36.366935 mn-1 etcd[1753]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Apr 23 03:18:36.366999 mn-1 etcd[1753]: listening for peers on http://192.168.1.8:2380
Apr 23 03:18:36.367037 mn-1 etcd[1753]: listening for client requests on 127.0.0.1:2379
Apr 23 03:18:36.367068 mn-1 etcd[1753]: listening for client requests on 192.168.1.8:2379
Apr 23 03:18:36.392577 mn-1 etcd[1753]: resolving mn-0.local:2380 to 192.168.1.3:2380
Apr 23 03:18:36.392779 mn-1 etcd[1753]: resolving mn-0.local:2380 to 192.168.1.3:2380
Apr 23 03:18:36.392991 mn-1 etcd[1753]: resolving mn-1.local:2380 to 192.168.1.8:2380
Apr 23 03:18:36.393169 mn-1 etcd[1753]: resolving mn-1.local:2380 to 192.168.1.8:2380
Apr 23 03:18:36.494576 mn-1 etcd[1753]: resolving sn-2.local:2380 to 192.168.1.4:2380
Apr 23 03:18:36.494829 mn-1 etcd[1753]: resolving sn-2.local:2380 to 192.168.1.4:2380
Apr 23 03:18:36.496059 mn-1 etcd[1753]: name = mn-1
Apr 23 03:18:36.496076 mn-1 etcd[1753]: data dir = /mnt/rcpha/etcd/rcp20.etcd
Apr 23 03:18:36.496093 mn-1 etcd[1753]: member dir = /mnt/rcpha/etcd/rcp20.etcd/member
Apr 23 03:18:36.496102 mn-1 etcd[1753]: heartbeat = 300ms
Apr 23 03:18:36.496110 mn-1 etcd[1753]: election = 1500ms
Apr 23 03:18:36.496118 mn-1 etcd[1753]: snapshot count = 10000
Apr 23 03:18:36.496134 mn-1 etcd[1753]: advertise client URLs = http://192.168.1.8:2379
Apr 23 03:18:36.503429 mn-1 etcd[1753]: **starting member 7262c06152767c6a in cluster 62f1ea8a6f48c9f2**
Apr 23 03:18:36.504404 mn-1 etcd[1753]: 7262c06152767c6a became follower at term 0
Apr 23 03:18:36.504426 mn-1 etcd[1753]: newRaft 7262c06152767c6a [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Apr 23 03:18:36.504433 mn-1 etcd[1753]: 7262c06152767c6a became follower at term 1
Apr 23 03:18:36.511014 mn-1 etcd[1753]: started HTTP pipelining with peer 706869770ca14e9
Apr 23 03:18:36.511049 mn-1 etcd[1753]: started HTTP pipelining with peer 97ce3ec97538cc91
Apr 23 03:18:36.511072 mn-1 etcd[1753]: starting peer 706869770ca14e9...
Apr 23 03:18:36.511093 mn-1 etcd[1753]: started HTTP pipelining with peer 706869770ca14e9
Apr 23 03:18:36.512682 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (writer)
Apr 23 03:18:36.512809 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (writer)
Apr 23 03:18:36.514814 mn-1 etcd[1753]: started peer 706869770ca14e9
Apr 23 03:18:36.514876 mn-1 etcd[1753]: added peer 706869770ca14e9
Apr 23 03:18:36.514912 mn-1 etcd[1753]: starting peer 97ce3ec97538cc91...

As the log show, i remove the instance(remove the data dir too), and add it again, but the instance startup with old instance ID.

The problem is occasional， and the etcd version is:3.1.4

**Comment by gyuho** [comment]
> As the log show, i remove the instance(remove the data dir too), and add it again, but the instance startup with old instance ID.

Can you clarify with exact log?

**Comment by wenxuwan** [comment]
What's the meaning of exact log?  I have attached the log.


Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo df /mnt/rcpha/etcd/ | grep /mnt/rcpha/etcd, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mkdir -p /mnt/rcpha/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chmod 750 /mnt/rcpha/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chown _nokrcpsysha:_nokrcpsysha /mnt/rcpha/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mkdir -p /mnt/rcpha/image/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mount -t tmpfs -o size=294M tmpfs /mnt/rcpha/image/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [145B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Creating filesystem with 301056 1k blocks and 75480 inodes
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Filesystem UUID: 2d2c6010-057b-4458-8aa7-887abe2d82b9
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Superblock backups stored on blocks:
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: 8193, 24577, 40961, 57345, 73729, 204801, 221185
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [49B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [46B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Creating journal (8192 blocks): done
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: [83B blob data]
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: , stderr is mke2fs 1.44.0 (7-Mar-2018)
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mkdir -p /mnt/rcpha/etcd/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo mount -o loop /mnt/rcpha/image/etcd_image /mnt/rcpha/etcd/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo rm /mnt/rcpha/etcd/dummy, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chmod -R 600 /mnt/rcpha/image/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: exec cmd sudo chmod -R 600 /mnt/rcpha/etcd/, stdout is , stderr is
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The cluster is healthy
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Inquire mn-1 node in cluster from mn-0 node
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: the member have existed in cluster
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The memer in cluster, we need remove it and join again
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The member have in cluster, we will remove it first
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The remove operation result is: Removed member 7262c06152767c6a from cluster
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: **Remove member 7262c06152767c6a**
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: success!!
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: Remove the old memer success, we will add it now!!
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: The add method result is:
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: **Added member named mn-1 with ID 61981f90db63f090 to cluster**
Apr 23 03:18:36.040923 mn-1 create-etcd-conf[810]: ETCD_NAME="mn-1"
Apr 23 03:18:36.040857 mn-1 systemd[1]: Got disconnect on private connection.
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: ETCD_INITIAL_CLUSTER="sn-2=http://sn-2.local:2380,mn-1=http://mn-1.local:2380,mn-0=http://mn-0.local:2380"
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: ETCD_INITIAL_CLUSTER_STATE="existing"
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: add success
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: sn-2=http://sn-2.local:2380,mn-1=http://mn-1.local:2380,mn-0=http://mn-0.local:2380
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: Add the memeber success
Apr 23 03:18:36.042043 mn-1 create-etcd-conf[810]: The etcd configure fished with ETCD_INITIAL_CLUSTER_STATE existing

Apr 23 03:18:36.366625 mn-1 etcd[1753]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=http://192.168.1.8:2379
Apr 23 03:18:36.366672 mn-1 etcd[1753]: recognized and used environment variable ETCD_DATA_DIR=/mnt/rcpha/etcd/rcp20.etcd
Apr 23 03:18:36.366692 mn-1 etcd[1753]: recognized and used environment variable ETCD_ELECTION_TIMEOUT=1500
Apr 23 03:18:36.366704 mn-1 etcd[1753]: recognized and used environment variable ETCD_HEARTBEAT_INTERVAL=300
Apr 23 03:18:36.366717 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_ADVERTISE_PEER_URLS=http://192.168.1.8:2380
Apr 23 03:18:36.366731 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_CLUSTER=mn-0=http://mn-0.local:2380,mn-1=http://mn-1.local:2380,sn-2=http://sn-2.local:2380
Apr 23 03:18:36.366741 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_CLUSTER_STATE=existing
Apr 23 03:18:36.366750 mn-1 etcd[1753]: recognized and used environment variable ETCD_INITIAL_CLUSTER_TOKEN=rcp20
Apr 23 03:18:36.366775 mn-1 etcd[1753]: recognized and used environment variable ETCD_LISTEN_CLIENT_URLS=http://192.168.1.8:2379,http://127.0.0.1:2379
Apr 23 03:18:36.366786 mn-1 etcd[1753]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://192.168.1.8:2380
Apr 23 03:18:36.366800 mn-1 etcd[1753]: recognized and used environment variable ETCD_MAX_SNAPSHOTS=1
Apr 23 03:18:36.366809 mn-1 etcd[1753]: recognized and used environment variable ETCD_MAX_WALS=1
Apr 23 03:18:36.366829 mn-1 etcd[1753]: recognized and used environment variable ETCD_NAME=mn-1
Apr 23 03:18:36.366900 mn-1 etcd[1753]: etcd Version: 3.1.4
Apr 23 03:18:36.366912 mn-1 etcd[1753]: Git SHA: 4e1824f
Apr 23 03:18:36.366919 mn-1 etcd[1753]: Go Version: go1.9.2
Apr 23 03:18:36.366926 mn-1 etcd[1753]: Go OS/Arch: linux/amd64
Apr 23 03:18:36.366935 mn-1 etcd[1753]: setting maximum number of CPUs to 4, total number of available CPUs is 4
Apr 23 03:18:36.366999 mn-1 etcd[1753]: listening for peers on http://192.168.1.8:2380
Apr 23 03:18:36.367037 mn-1 etcd[1753]: listening for client requests on 127.0.0.1:2379
Apr 23 03:18:36.367068 mn-1 etcd[1753]: listening for client requests on 192.168.1.8:2379
Apr 23 03:18:36.392577 mn-1 etcd[1753]: resolving mn-0.local:2380 to 192.168.1.3:2380
Apr 23 03:18:36.392779 mn-1 etcd[1753]: resolving mn-0.local:2380 to 192.168.1.3:2380
Apr 23 03:18:36.392991 mn-1 etcd[1753]: resolving mn-1.local:2380 to 192.168.1.8:2380
Apr 23 03:18:36.393169 mn-1 etcd[1753]: resolving mn-1.local:2380 to 192.168.1.8:2380
Apr 23 03:18:36.494576 mn-1 etcd[1753]: resolving sn-2.local:2380 to 192.168.1.4:2380
Apr 23 03:18:36.494829 mn-1 etcd[1753]: resolving sn-2.local:2380 to 192.168.1.4:2380
Apr 23 03:18:36.496059 mn-1 etcd[1753]: name = mn-1
Apr 23 03:18:36.496076 mn-1 etcd[1753]: data dir = /mnt/rcpha/etcd/rcp20.etcd
Apr 23 03:18:36.496093 mn-1 etcd[1753]: member dir = /mnt/rcpha/etcd/rcp20.etcd/member
Apr 23 03:18:36.496102 mn-1 etcd[1753]: heartbeat = 300ms
Apr 23 03:18:36.496110 mn-1 etcd[1753]: election = 1500ms
Apr 23 03:18:36.496118 mn-1 etcd[1753]: snapshot count = 10000
Apr 23 03:18:36.496134 mn-1 etcd[1753]: advertise client URLs = http://192.168.1.8:2379
Apr 23 03:18:36.503429 mn-1 etcd[1753**]: starting member 7262c06152767c6a in cluster 62f1ea8a6f48c9f2**
Apr 23 03:18:36.504404 mn-1 etcd[1753]: 7262c06152767c6a became follower at term 0
Apr 23 03:18:36.504426 mn-1 etcd[1753]: newRaft 7262c06152767c6a [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Apr 23 03:18:36.504433 mn-1 etcd[1753]: 7262c06152767c6a became follower at term 1
Apr 23 03:18:36.511014 mn-1 etcd[1753]: started HTTP pipelining with peer 706869770ca14e9
Apr 23 03:18:36.511049 mn-1 etcd[1753]: started HTTP pipelining with peer 97ce3ec97538cc91
Apr 23 03:18:36.511072 mn-1 etcd[1753]: starting peer 706869770ca14e9...
Apr 23 03:18:36.511093 mn-1 etcd[1753]: started HTTP pipelining with peer 706869770ca14e9
Apr 23 03:18:36.512682 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (writer)
Apr 23 03:18:36.512809 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (writer)
Apr 23 03:18:36.514814 mn-1 etcd[1753]: started peer 706869770ca14e9
Apr 23 03:18:36.514876 mn-1 etcd[1753]: added peer 706869770ca14e9
Apr 23 03:18:36.514912 mn-1 etcd[1753]: starting peer 97ce3ec97538cc91...
Apr 23 03:18:36.511093 mn-1 etcd[1753]: started HTTP pipelining with peer 706869770ca14e9
Apr 23 03:18:36.512682 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (writer)
Apr 23 03:18:36.512809 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (writer)
Apr 23 03:18:36.514814 mn-1 etcd[1753]: started peer 706869770ca14e9
Apr 23 03:18:36.514876 mn-1 etcd[1753]: added peer 706869770ca14e9
Apr 23 03:18:36.514912 mn-1 etcd[1753]: starting peer 97ce3ec97538cc91...
Apr 23 03:18:36.514952 mn-1 etcd[1753]: started HTTP pipelining with peer 97ce3ec97538cc91
Apr 23 03:18:36.515756 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (stream MsgApp v2 reader)
Apr 23 03:18:36.517477 mn-1 etcd[1753]: started streaming with peer 706869770ca14e9 (stream Message reader)
Apr 23 03:18:36.519274 mn-1 etcd[1753]: started streaming with peer 97ce3ec97538cc91 (writer)
Apr 23 03:18:36.520223 mn-1 etcd[1753]: started streaming with peer 97ce3ec97538cc91 (writer)
Apr 23 03:18:36.520818 mn-1 etcd[1753]: started peer 97ce3ec97538cc91
Apr 23 03:18:36.520855 mn-1 etcd[1753]: added peer 97ce3ec97538cc91
Apr 23 03:18:36.520896 mn-1 etcd[1753]: starting server... [version: 3.1.4, cluster version: to_be_decided]
Apr 23 03:18:36.520995 mn-1 etcd[1753]: started streaming with peer 97ce3ec97538cc91 (stream MsgApp v2 reader)
Apr 23 03:18:36.521739 mn-1 etcd[1753]: started streaming with peer 97ce3ec97538cc91 (stream Message reader)
Apr 23 03:18:36.522337 mn-1 etcd[1753]: the member has been permanently removed from the cluster
Apr 23 03:18:36.522389 mn-1 etcd[1753]: the data-dir used by this member must be removed.
Apr 23 03:18:36.528286 mn-1 etcd[1753]: streaming request ignored (ID mismatch got 61981f90db63f090 want 7262c06152767c6a)
Apr 23 03:18:36.528316 mn-1 etcd[1753]: streaming request ignored (ID mismatch got 61981f90db63f090 want 7262c06152767c6a)
Apr 23 03:18:36.528436 mn-1 etcd[1753]: streaming request ignored (ID mismatch got 61981f90db63f090 want 7262c06152767c6a)
Apr 23 03:18:36.528556 mn-1 etcd[1753]: peer 97ce3ec97538cc91 became active
Apr 23 03:18:36.528604 mn-1 etcd[1753]: established a TCP streaming connection with peer 97ce3ec97538cc91 (stream Message writer)
Apr 23 03:18:36.528630 mn-1 etcd[1753]: streaming request ignored (ID mismatch got 61981f90db63f090 want 7262c06152767c6a)
Apr 23 03:18:36.528975 mn-1 etcd[1753]: established a TCP streaming connection with peer 97ce3ec97538cc91 (stream MsgApp v2 writer)
Apr 23 03:18:36.623135 mn-1 etcd[1753]: failed to dial 97ce3ec97538cc91 on stream MsgApp v2 (the member has been permanently removed from the cluster)
Apr 23 03:18:36.623161 mn-1 etcd[1753]: peer 97ce3ec97538cc91 became inactive

**Comment by gyuho** [comment]
> I just check the etcd code , the local instance will read from remote client, and will compare with local client, if same,

I don't understand this? What do you mean by same local clients?

As you said, the newly joined member will need fetch cluster ID from its remote peers.

**Comment by wenxuwan** [comment]
I just mean ValidateClusterAndAssignIDs(local *RaftCluster, existing *RaftCluster) function will compare the local cluster and existing cluster.

And from the log, you can find 

1.Remove member 7262c06152767c6a
2.Added member named mn-1 with ID 61981f90db63f090 to cluster
3.starting member 7262c06152767c6a in cluster 62f1ea8a6f48c9f2
4. streaming request ignored (ID mismatch got 61981f90db63f090 want 7262c06152767c6a)
The instance still use the old ID.

**Comment by gyuho** [comment]
> 1.Remove member 7262c06152767c6a

Did you remove the data directory as well?

Also, please provide reproducible steps.

**Comment by wenxuwan** [comment]
Did you remove the data directory as well?
yes, i remove folder directly
Also, please provide reproducible steps.
the problem can't be reproduced now.

**Comment by gyuho** [comment]
> The instance still use the old ID.

Please make sure to delete the data directory, and start fresh. If you still have issues, or can reproduce, open a new issue.
