### ISSUE TITLE
etcd v3.3 data migration

### ISSUE THREAD

**Issue by yyyyyyyyyg** [coreos/etcd#9637]
We have a requirement to migrate an existing etcd data to a new etcd cluster, both the two etcd cluster are v3.3 version.
Just have a search, there are some guides which indicates how to migrate from v2 to v3, but not my case. Is there any guide here for my case? 
I just tried save a snapshot, start a new cluster and then import snapshot to the etcd data dir, but seems snapshot is not for this usage, it reports an error about the etcd data dir already exists.

Thanks very much for your help!!

**Comment by raoofm** [comment]
@yyyyyyyyyg It should be straight forward.

This is what you need
https://github.com/coreos/etcd/blob/master/Documentation/op-guide/recovery.md

**Comment by gyuho** [comment]
Also check out https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_0.md and https://github.com/coreos/etcd/tree/master/etcdctl#migrate-options.

**Comment by yyyyyyyyyg** [comment]
Thanks for your kindly help. Will have a try!
