### ISSUE TITLE
support Multiple datacenter/region

### ISSUE THREAD

**Issue by yichengq** [coreos/etcd#964]
Current workaround is 
1. measure the longest RTT
2. turn up heartbeat interval and election timeout

Discussion is needed to an elegant way.

**Comment by yichengq** [comment]
I am starting to tackle this. The problem is what is the best way to run etcd cluster in multiple data center or region, so it could provide fault tolerance across multiple data centers and low read latency.

The proposed solution is as this:
1. run a world-wide etcd cluster across multiple data centers. It still consists of 3-9 members, but each member is located at different data center. Even if one data center is down, the etcd cluster could still make progress.
2. mirroring data from world-wide etcd cluster to the cluster in data center. If both cluster are healthy and can talk to each other, the local cluster will see all data eventually.

The solution is missing two parts today:
1. etcd should support global deployment with higher -heartbeat-interval and -election-timeout, and it should tolerate more latency in network communication
2. a mirroring tool that mirrors kv from one cluster to another. (https://github.com/coreos/etcd/issues/1749)

**Comment by xiang90** [comment]
@yichengq Basically, we should suggest 2. But now you can do 1. And we need to explicitly tell the story around failure domain. Why do you want to deploy your etcd across data center? 

For 1 (etcd in multiple dc)
For low latency write? No. It would only increase the write latency in any case.
For low latency read? Maybe. Client does not guarantee to read from local node.
For higher potential availability? Yes. You get another failure domain. 

For 2.
Simply for low latency read and data backup.

And I would say we suggest 2 for most cases. Now etcd does not support it though... It is WIP.

**Comment by yichengq** [comment]
For global deployment as method 1, it includes some changes:
- [ ] adjust proposal timeout at server side
- [ ] adjust transport connection at rafthttp pkg

**Comment by yichengq** [comment]
The mirroring tool is tracked at #1749. And we need to doc the best practices to deploy etcd across data center after the tool is done.

Moving this issue to 3.0-alpha to wait for mirror tool to finish.

**Comment by xiang90** [comment]
@yichengq I think we should close this one. The mirror tool has its own issue. If you have other concern, you can open another one to track. This one is too noisy.

**Comment by yichengq** [comment]
Close this one because the left part is covered by other issues.
