### ISSUE TITLE
[Feature Request]Enable unencrypted access to /health endpoint when client TLS is enabled

### ISSUE THREAD

**Issue by crielly** [coreos/etcd#9653]
It would be useful if, while client TLS is enabled, `/health` could still be accessed via http. It is not always possible to provide a certificate bundle to things like Load Balancers. For example, when you enable client TLS, you make it impossible for an AWS ALB to get a healthy result from `/health`:

```
Apr 27 19:01:29 ip-172-16-6-245.us-east-2.compute.internal etcd[13984]: rejected connection from "172.16.0.164:41145" (error "tls: client didn't provide a certificate", ServerName "")
Apr 27 19:01:29 ip-172-16-6-245.us-east-2.compute.internal etcd[13984]: rejected connection from "172.16.4.201:6126" (error "tls: client didn't provide a certificate", ServerName "")
Apr 27 19:01:30 ip-172-16-6-245.us-east-2.compute.internal etcd[13984]: rejected connection from "172.16.2.135:2789" (error "tls: client didn't provide a certificate", ServerName "")
Apr 27 19:01:31 ip-172-16-6-245.us-east-2.compute.internal etcd[13984]: rejected connection from "172.16.2.229:7075" (error "tls: client didn't provide a certificate", ServerName "")
Apr 27 19:01:31 ip-172-16-6-245.us-east-2.compute.internal etcd[13984]: rejected connection from "172.16.0.247:25430" (error "tls: client didn't provide a certificate", ServerName "")
Apr 27 19:01:31 ip-172-16-6-245.us-east-2.compute.internal etcd[13984]: rejected connection from "172.16.4.47:28475" (error "tls: client didn't provide a certificate", ServerName "")
```

That's an internal and external ALB hitting `/health`.

Two possible implementations:
- `/health` simply is not encrypted
- an option is provided to specify whether or not `/health` is served over https

**Comment by joelegasse** [comment]
@gyuho It looks like `--listen-metrics-urls` already handles the `/health` endpoint in addition to `/metrics`.

@crielly Can you try setting a separate endpoint via `--listen-metrics-urls` and point the load balancer health check there?

**Comment by crielly** [comment]
Excellent, thank you! Covers my use case.
