### ISSUE TITLE
Can watch revision that is larger then the latest revison now

### ISSUE THREAD

**Issue by cloudzhou** [coreos/etcd#9656]
say the etcd latest revision is 12345,
can i watch from the revision 12350 ?

I had try in my local testing and it will get notify after 5 writes, it looks good.

but does etcd guarantee that we can watch revision larger then the latest revision ?

https://coreos.com/etcd/docs/latest/learning/api.html do not mention about this

**Comment by gyuho** [comment]
Yes, you can specify future revisions.
