### ISSUE TITLE
C/C++ client

### ISSUE THREAD

**Issue by topilski** [coreos/etcd#9659]
Hi, do you have C/C++ client for etcd?

**Comment by hexfusion** [comment]
Hi @topilski please review the integrations list we currently have a v2,v3 client in C++.

https://github.com/coreos/etcd/blob/master/Documentation/integrations.md

**Comment by topilski** [comment]
Hi @hexfusion , thank you for reply i'am looking for offical api, i thinking about integration etcd into FastoNoSQL.
