### ISSUE TITLE
raft: Any issues with persisting snapshots first?

### ISSUE THREAD

**Issue by kchristidis** [coreos/etcd#9673]
The [README](https://github.com/coreos/etcd/blob/master/raft/README.md) for etcd/raft states:

> Write Entries, HardState and Snapshot to persistent storage in order, i.e. Entries first, then HardState and Snapshot if they are not empty.

What would happen if someone were to persist the Snapshot first, and then the Entries and HardState?

My guess is that if the node were to crash right after persisting the snapshot, it would reboot into an inconsistent state. Is that correct?

**Comment by xiang90** [comment]
> My guess is that if the node were to crash right after persisting the snapshot, it would reboot into an inconsistent state. Is that correct?

It depends on how do you recover. If you can check the hardstate first, then make sure the snapshot matches the hardstate, you will be fine. It is just easier to follow the ordering we suggest.
