### ISSUE TITLE
Inconsistent release binary file permissions

### ISSUE THREAD

**Issue by yudai** [coreos/etcd#9701]
I realized that the etcd binary of the v3.2.19 release doesn't have read or execute permission for others, while that of v3.2.18 has (our pipeline failed due to a `permission denied` error).

v3.3.4 also has `rx` for others, and binaries built with the `build` script also has it. I therefore assume that v3.2.19 lost those permissions accidentally for some reason. v3.1.14 also lacks `rx` for others as well.

```
yudai@yudai01% ls -al etcd*/etcd
-rwxr-x--- 1 yudai yudai 16356384 Apr 24 13:35 etcd-v3.1.14-linux-amd64/etcd
-rwxr-xr-x 1 yudai yudai 17837888 Mar 29 10:49 etcd-v3.2.18-linux-amd64/etcd
-rwxr-x--- 1 yudai yudai 17850176 Apr 24 14:18 etcd-v3.2.19-linux-amd64/etcd
-rwxr-x--- 1 yudai yudai 16558624 Apr 24 14:19 etcd-v3.2.19-linux-arm64/etcd
-rwxr-xr-x 1 yudai yudai 19262720 Apr 24 13:31 etcd-v3.3.4-linux-amd64/etcd
```

I think it's better to recover those `rx` if there is no particular reason to remove them.

**Comment by gyuho** [comment]
/cc @jpbetz 

@yudai Thanks for report. Another release is planned for next week. We will double-check on this.

**Comment by jpbetz** [comment]
Having a look now.

**Comment by jpbetz** [comment]
@yudai Was this the `etcd-v3.2.19-linux-amd64.tar.gz` release binary from https://github.com/coreos/etcd/releases/tag/v3.2.19?

**Comment by yudai** [comment]
@jpbetz yes. The one at https://github.com/coreos/etcd/releases/download/v3.2.19/etcd-v3.2.19-linux-amd64.tar.gz

**Comment by jpbetz** [comment]
@yudai Okay, I suspect my default umask of `022` is at fault. I'll fix.

**Comment by jpbetz** [comment]
Confirmed that umask was the problem. I've fixed our release script to always set the correct umask. This will be correct in all future releases.
