### ISSUE TITLE
How many copies of peer info should we maintain?

### ISSUE THREAD

**Issue by FlyingOnion** [coreos/etcd#9722]
In etcd, when we want to add a peer, at least 3 functions are called.
`raft.Node.ApplyConfChange`, `rafthttp.Transport.AddPeer`, `membership.RaftCluster.AddMember`
That means we have to maintain at least 3 copies of peer information? How could these information got sync?

**Comment by xiang90** [comment]
These copies are maintained by a top-down call in sequence. When the call returns, everything is in sync.
