### ISSUE TITLE
json watch function not work

### ISSUE THREAD

**Issue by lunakaer** [coreos/etcd#9723]
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.
json watch not work for v3 api , when put value cant receive response
 as the example:
curl -L http://localhost:2379/v3alpha/kv/put \
  -X POST -d '{"key": "Zm9v", "value": "YmFy"}'

**Comment by gyuho** [comment]
Please try

```bash
ETCDCTL_API=3 ./bin/etcdctl put foo bar

curl -L http://localhost:2379/v3/watch  \
  -X POST -d '{"create_request": {"key":"Zm9v"} }'

curl -L http://localhost:2379/v3/lease/leases  \
  -X POST -d '{}'
```

**Comment by lunakaer** [comment]
I am sorry, i have tried but it still not work, the etcd version I used is the latest v3.3.5,  I export ETCDCTL_API=3 in my system environment.

first i watch the key foo with curl:
```
curl -L http://localhost:2379/v3beta/watch  \
  -X POST -d '{"create_request": {"key":"Zm9v"} }'
```
then i put the value with etcdctl:
```
etcdctl put foo bar
```
but the curl watch cant receive any message.

and then i try watch with ectdctl 
```
etcdctl watch foo
```
this can receve the change of the key foo.
so is there something wrong with the useage or is there a bug with the json watch api ?
