### ISSUE TITLE
systemd service 

### ISSUE THREAD

**Issue by sevillalarry** [coreos/etcd#9747]
(I'm not sure if this is the right forum.  If not pls point me to the correct site.)

I'm trying to setup OpenStack environment with AntiX as host.

I tried to install with the guide from “https://docs.openstack.org/install-guide/”
I used the ubuntu portion since both ubuntu and antiX are derived from debian.

But stopped at “https://docs.openstack.org/install-guide/environment-etcd-ubuntu.html”
at #3 “Create and edit the /lib/systemd/system/etcd.service file:”
(I'm using v3.3.5)

Sorry I’m not familiar with services, is there an equivalent for non-systemd?

**Comment by gyuho** [comment]
You can check out http://play.etcd.io/install.
