### ISSUE TITLE
ETCD not showing metric & version

### ISSUE THREAD

**Issue by prasenforu** [coreos/etcd#9750]
I am using  Openshift Origin (3.9) CentOS7 with following infrastructure.
OS : CentOS Linux release 7.5.1804 (Core)

1 MASTER (10.09.1.205)
3 ETCD (10.90.1.205,10.90.1.206,10.90.1.207)
2 Infra
3 Nodes

Installation done using ansible.

Openshift & ETCD Cluster running fine

![image](https://user-images.githubusercontent.com/19322497/40338351-3d1fc6a8-5d92-11e8-9d4b-e1343ecd2fbe.png)

Want to get Prometheus metric of ETCD nodes.

When trying to fetch metric from curl command its coming blank even version also not visible.

![image](https://user-images.githubusercontent.com/19322497/40337671-85c13da0-5d8e-11e8-95c7-0de158c38099.png)

but if I try to fetch command line its showing version
![image](https://user-images.githubusercontent.com/19322497/40337517-b123a308-5d8d-11e8-8f61-ef25751b0e0b.png)

Its happens all three nodes.

![image](https://user-images.githubusercontent.com/19322497/40337879-b2ff13ae-5d8f-11e8-8819-e774d0af4566.png)

**Comment by gyuho** [comment]
How is your etcd configured? Default configuration `/metrics` endpoint works for me.

**Comment by prasenforu** [comment]
As I told initially it's through sensible which comes with installation of open shift.

**Comment by gyuho** [comment]
Still not related to etcd. It cannot even get version information.
How do you write to etcd? How is API server configured?

**Comment by prasenforu** [comment]
Insallation done by Anisible playbook, I have not done any special configuration.

ETCD Cluster also showing healthy from Master server.

![image](https://user-images.githubusercontent.com/19322497/40408413-101e2142-5e85-11e8-9034-35a8532dc93b.png)

**Comment by gyuho** [comment]
Try metrics on https://ose-etcd1.tcs-ally.tk:2379 with TLS certs?

**Comment by prasenforu** [comment]
can u please provide example, I have very less experience in certificate.

**Comment by prasenforu** [comment]
Fixed. Thank you.
