### ISSUE TITLE
gRPC gateway to 1.4

### ISSUE THREAD

**Issue by hexfusion** [coreos/etcd#9753]
gRPC gateway team released 1.4.0 a few days ago. I would like to start testing and maybe get this into 3.4 if practical. The [Bazel support](https://github.com/grpc-ecosystem/grpc-gateway/commit/289beb39aef12492572e3bd569fcbf3ad2e28f54) seems interesting.

https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.4.0

ref: https://github.com/coreos/etcd/issues/9189

**Comment by gyuho** [comment]
Can you upgrade our gRPC gateway dependency and bump up genproto script with latest gRPC gateway? Similar to https://github.com/coreos/etcd/pull/9754.
