### ISSUE TITLE
Release including fix to passwords in logs

### ISSUE THREAD

**Issue by YeruchamB** [coreos/etcd#9758]
Hey, when can I expect a release that includes this fix?
https://github.com/coreos/etcd/pull/9636

**Comment by hexfusion** [comment]
Hi @YeruchamB this was cherry-picked into #9661 although I do not see it specifically in 3.4 yet I imagine 3.4 release. Perhaps because of its secure nature, this might get backported as well but I am not sure.

/cc @gyuho @mitake

**Comment by gyuho** [comment]
It was never released. Will be in 3.4.
