### ISSUE TITLE
Confused about network tuning section

### ISSUE THREAD

**Issue by tangle329** [coreos/etcd#9770]
In Documentation/tuning.md, it saied peer traffic can be prioritized by using the traffic control mechanism: 

```
tc qdisc add dev eth0 root handle 1: prio bands 3
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip sport 2380 0xffff flowid 1:1
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dport 2380 0xffff flowid 1:1
tc filter add dev eth0 parent 1: protocol ip prio 2 u32 match ip sport 2379 0xffff flowid 1:1
tc filter add dev eth0 parent 1: protocol ip prio 2 u32 match ip dport 2379 0xffff flowid 1:1
```

But for me it should be:
```
tc qdisc add dev eth0 root handle 1: prio bands 3
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip sport 2380 0xffff flowid 1:1
tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dport 2380 0xffff flowid 1:1
tc filter add dev eth0 parent 1: protocol ip prio 2 u32 match ip sport 2379 0xffff flowid 1:2
tc filter add dev eth0 parent 1: protocol ip prio 2 u32 match ip dport 2379 0xffff flowid 1:2
```

The change is: For 2379 port we should put the flow to 1:2 not 1:1 class. Am i right?

**Comment by hexfusion** [comment]
> The change is: For 2379 port we should put the flow to 1:2 not 1:1 class. Am i right?

Hi @tangle329 in the example we are showing the root handle 1: then we prioritize 2 ports on the root class, 1:1. The resource allocation for the root class should be the sum of its children so assigning these rules to the root would be just an example. But in this example, I think it makes sense to use root 1:1 and then prioritize based on port. Thus both ports have full access to the root class's resources with peer traffic taking priority.

tc and HTB are very configurable and it's full usage is of course out of the scope of this document. I could see a use case as you have shown where you wanted to throttle total bandwidth available to the client. So, for example, you provide peer traffic root class 1:1 then add your client to leaf class 1:2 class with a limited total bandwidth.

Just my 2 cents but I think the example is OK :)

**Comment by tangle329** [comment]
@hexfusion  Thanks
