### ISSUE TITLE
Raft question: Snapshotting and Compaction on disk based storage

### ISSUE THREAD

**Issue by sithembiso** [coreos/etcd#9800]
I'm trying to implement a disk-based storage driver for Raft using SQLite as a datastore and I want to confirm my understanding of these two concepts. Before I continue, I must state that the reason for my use of SQLite is to have a datastore that is easy to query without duplicating data. But also, I would love to have an option to never discard any data (unless there are perfomance related issues). With that said:

### Compaction
The raft paper paper defines compaction (roughly) as a way of discarding data we no longer need to recreate the current state machine. 
- Is this left to the application to decide which data is no longer of use? 
- And also, if I have a log with 10 entries, and I truncate from 0 - 5: Is the rest of the cluster happy knowing that 0 - 5 no longer exists? Does it not always try to retaining the chaining ability where Index5 is preceded by Index4 and so on...?
- If I say stored log entries as rows in my SQLite database, would I need compaction for reasons other than saving disc space? Are there any perfomance related pernalties?

### Snapshotting
From what I understand from reading the `MemoryStorage` source code, a snapshot allows you to create an object representing the current state of the log. This includes the `Term`, `Index`, `ConfState` as well as the `Data` at the time the snapshot was created. This snapshot can then be used to update new nodes or slow followers in the cluster, meaning it is sent to other nodes? If so then:

- What's in the `Data` field of the snapshot? Is it all the entries in the log? And if so, what happens if you have 10GB worth of data in there. Does Raft handle the chunking of the snapshot?
- Once the snapshot has served it's purpose, do we then discard it leaving the original copy of the log? Or is it then used as the current state of the log going forward?

Please let me know if you need clarity on any of the subjects. I'm very new to raft. Also, I'd love to know if anyone has ever created a production ready database (*SIMPLE TO UNDERSTAND*) storage for raft.

PS: Happy new overlords day 😆! (*as Microsoft acquires Github*)

**Comment by sithembiso** [comment]
### Re: What's in the `Data` field of the snapshot? Is it all the entries in the log?
After further reading, I think I'm misunderstanding the point of the log. 

**Initially** 
I thought the point of log replication is to end up with an identical log in all the nodes, which made me believe that it's about keeping every entry that ever existed so that new nodes end up with an identical log.

**Now**
I think log entries are just means to an end (the desired state). And that the snapshot should have the desired state in the `Data` field, instead of log entries. Which means that compaction is used to get rid of entries that have already been applied to the state machine.

**Comment by manishrjain** [comment]
@sithembiso : We built this and using it in Dgraph. Uses Badger.

https://github.com/dgraph-io/dgraph/tree/master/raftwal

Etcd team, if you think this DiskStorage solution could be useful in general, maybe you could mention it in the README.

**Comment by sithembiso** [comment]
@manishrjain Thank you so much. I've gained much better understanding of Raft since, but I'll either try using yours or use as a reference.
Thanks again 😃
