### ISSUE TITLE
etcd 3.1.12 auth with certificates doesn't work

### ISSUE THREAD

**Issue by cristifalcas** [coreos/etcd#9816]
In a standard kubernetes installation with kubeadm version 1.10.3, the default etcd installed is version 3.1.12.

If I'm trying to enable authentication with certificates, it complains that it can't find the user:
```
# DIR=/etc/kubernetes/pki/
# openssl x509 -noout -text -in ${DIR}/apiserver-etcd-client.crt | grep "Subject:"
        Subject: O=system:masters, CN=kube-apiserver-etcd-client

# SSL_OPTS="--cacert=${DIR}/etcd/ca.crt --cert=${DIR}/apiserver-etcd-client.crt --key=${DIR}/apiserver-etcd-client.key --endpoints=localhost:2379"
# alias etcds="ETCDCTL_API=3 etcdctl $SSL_OPTS"

# etcds user add root:secretpass
# etcds user add kube-apiserver-etcd-client:$(head -c 32 /dev/urandom | base64)
# etcds user add kube-etcd-healthcheck-client:$(head -c 32 /dev/urandom | base64)
# etcds user grant-role kube-apiserver-etcd-client root
# etcds user grant-role kube-etcd-healthcheck-client root

# etcds auth enable
# etcds get / --keys-only=true --prefix
Error:  etcdserver: user name is empty
# etcds auth disable
Error:  etcdserver: user name not found
# etcds auth disable --user root
Password: 
Authentication Disabled
```

If I upgrade the etcd server to version 3.2.18, it works correctly.

**Comment by cristifalcas** [comment]
Before using "etcds get / --keys-only=true --prefix", I defined an alias:
```
alias etcds="ETCDCTL_API=3 etcdctl $SSL_OPTS"
```
Antyway, it doeasn't work even if I use the entire command:
```
ETCDCTL_API=3 etcdctl --cacert=${DIR}/etcd/ca.crt --cert=${DIR}/apiserver-etcd-client.crt --key=${DIR}/apiserver-etcd-client.key --endpoints=localhost:2379 get / --keys-only=true --prefix
```

**Comment by hexfusion** [comment]
> Before using "etcds get / --keys-only=true --prefix", I defined an alias

@cristifalcas I saw that but it's not passing auth unless I am missing something.

> Antyway, it doeasn't work even if I use the entire command:
ETCDCTL_API=3 etcdctl --cacert=${DIR}/etcd/ca.crt --cert=${DIR}/apiserver-etcd-client.crt --key=${DIR}/apiserver-etcd-client.key --endpoints=localhost:2379 get / --keys-only=true --prefix

My example passes auth `--user=root:secretpass`

**Comment by cristifalcas** [comment]
Sorry, i didn't catch that. My issue is that it's not using the CN from the certificate as the user

**Comment by hexfusion** [comment]
@cristifalcas I see then I was confused :), the good news is it is easily explained as CN client auth was added in 3.2.

https://github.com/coreos/etcd/commit/0191509637546621d6f2e18e074e955ab8ef374d
