### ISSUE TITLE
field.go:33: syntax error: unexpected = in type declaration

### ISSUE THREAD

**Issue by 2008820** [coreos/etcd#9824]
when  go get github.com/coreos/etcd/clientv3, occur error：

> ../../../../coreos/etcd/vendor/go.uber.org/zap/field.go:33: syntax error: unexpected = in type declaration

my go version 1.80
plz, how to resultion!!

**Comment by hexfusion** [comment]
```
$ go get github.com/coreos/etcd/clientv3
$ go version
go version go1.10.2 linux/amd64
```
@2008820 to build latest etcd requires 1.10.1

>../../../../coreos/etcd/vendor/go.uber.org/zap/field.go:33: syntax error: unexpected = in type declaration

from https://github.com/uber-go/zap#installation

"Note that zap only supports the two most recent minor versions of Go."
