### ISSUE TITLE
Configure local discovery url

### ISSUE THREAD

**Issue by Sideris35** [coreos/etcd#9836]
HI all,

I install magnum in Openstack infrastructure, magnum use ETCD when he create a cluster.
When i create a cluster I have this error: Failed to get discovery url from 'https://discovery.etcd.io/new?size=1'

It's normal, in my infra i don't have internet.
My question is, how can i build a discovery URL ? for exemple i want to etcd get discovery from http://localhost/new?size=1.

This is the configuration of etcd:
`name: imgesx07`
`data-dir: /var/lib/etcd`
`initial-cluster-state: 'new'`
`initial-cluster-token: 'etcd-cluster-01'`
`initial-cluster: imgesx07=http://192.168.10.20:2380`
`initial-advertise-peer-urls: http://192.168.10.20:2380`
`advertise-client-urls: http://192.169.10.20:2379`
`listen-peer-urls: http://0.0.0.0:2380`
`listen-client-urls: http://192.168.10.20:2379`

Thanks, 
Best regards!

**Comment by gyuho** [comment]
Try https://github.com/coreos/discovery.etcd.io#docker-container? Also, `discovery.etcd.io` is not maintained. I would not use it in production.
