### ISSUE TITLE
How to limit number of keys with same prefix?

### ISSUE THREAD

**Issue by ravigadde** [coreos/etcd#9852]
Is there a recommended way to limit number of keys with the same prefix? I am thinking if new key creation can be combined with this check in an atomic manner. Current comparators work on value, would it be possible to include count in the comparator?

**Comment by ravigadde** [comment]
@gyuho The intent is to limit creation of keys in a prefix to a certain number. The use case is tracking resource allocation of a constrained resource. Each key corresponds to a single unit of the resource.  Want to cap maximum number of keys to the total number of resources. If the resource allocation can be done using a primitive, it makes the failure handling a lot easier.

**Comment by gyuho** [comment]
@ravigadde 

> limit creation of keys in a prefix to a certain number

Currently, there is no way to limit the number of key writes per namespace.

I would try pre/suffix-ing your own key with index, to keep track of how many resources have been created.
