### ISSUE TITLE
why make-mirror documentation shows read only

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd#9867]
I was trying to use make-mirror for [replicating vault data across region](https://github.com/coreos/vault-operator/issues/330).

[Documentation](https://github.com/coreos/etcd/blob/master/etcdctl/doc/mirror_maker.md) on this mentions 

> Data under the destination cluster’s mirroring prefix should be treated as read only.

I think this is not true. We can as well write to the mirrored etcd cluster and infact in the same prefix.

This needs some clarification. I can correct it with a PR but needed someone to ack it before I proceed.

So suppose cluster-1 has secrets and mirroring tool copies the secrets to cluster-2 but this doesn't stop cluster-2 clients to write to the prefix. If they did write, I don't think it would affect the mirroring process or corrupt the data. 
Ofcourse the new data added to the same prefix is not synced back to cluster-1.

**Comment by gyuho** [comment]
@raoofm Yeah, it would still accept writes, technically. So, we need clarification on docs. Could you help improve? Thanks!

**Comment by xiang90** [comment]
probably mention that the copy is uni-directional. changing the value on the mirrored cluster wont reflect the value back to the origin cluster.
