### ISSUE TITLE
How to show v3 debug-level logging

### ISSUE THREAD

**Issue by alpha-li** [coreos/etcd#9874]
When --debug flaog is set, only v2 related debug-level logging is printed. So how can I show the debug-level logging for v3 API?

**Comment by gyuho** [comment]
@alpha-li `--debug` flag should enable v3 debug logs. Please let us know if you don't see expected debugging logs.

**Comment by alpha-li** [comment]
If --debug flag is set, when I access etcd through the v2 API, the "[GET] or [PUT]" loging is shown, but there is no similar logging for the v3 API.
