### ISSUE TITLE
Question: watching, or fetching with a wildcard 

### ISSUE THREAD

**Issue by EwanValentine** [coreos/etcd#9875]
Hi folks,

Apologies if this is the wrong place for a question. I'm using the Golang client (v3). I'm attempting to Watch, and Get with a wildcard, it doesn't seem to be possible, but I thought I'd check if there was a way of doing it. Currently I'm attempting: 

```
$ docker exec etcd-gcr-v3.3.8 /bin/sh -c "ETCDCTL_API=3 /usr/local/bin/etcdctl set /modules/item {"id":"","host":"localhost","image_id":"28bdc8399c8f","endpoint":"/test-module","status":false}"

$ docker exec etcd-gcr-v3.3.8 /bin/sh -c "ETCDCTL_API=3 /usr/local/bin/etcdctl get /modules/item"
; {"id":"","host":"localhost","image_id":"28bdc8399c8f","endpoint":"/test-module","status":false}

$ docker exec etcd-gcr-v3.3.8 /bin/sh -c "ETCDCTL_API=3 /usr/local/bin/etcdctl get /modules/*"
; nil
```

Codewise, I'm doing: 

```golang
etcd.watcher.Watch(context.Background(), "/modules/*")
``` 

```golang
resp, err := etcd.api.Get(context.Background(), "/modules/*")
```

This doesn't seem possible, but I wondered if there was some other way to achieve this?

Thanks in advance!

**Comment by gyuho** [comment]
You can watch by prefix https://godoc.org/github.com/coreos/etcd/clientv3#WithPrefix:

```go
cli.Watch(ctx, "foo", clientv3.WithPrefix())
```

**Comment by EwanValentine** [comment]
@gyuho - I saw that used in the following format in the examples, `foo1, foo2` etc, can that be anything, for example, `foo-bar`?

**Comment by EwanValentine** [comment]
yo @gyuho ?

**Comment by gyuho** [comment]
@EwanValentine No, it will only match foo1 and foo2. We don't support wildcard.

**Comment by gyuho** [comment]
@EwanValentine You can instead try range end. Something like `Put(ctx, "foo", "fzz", 0)` (ref https://godoc.org/github.com/coreos/etcd/clientv3#GetPrefixRangeEnd).

**Comment by EwanValentine** [comment]
@gyuho awesome, that's perfect, thank you!
