### ISSUE TITLE
Etcd Cluster setup with ansible

### ISSUE THREAD

**Issue by phemmmie** [coreos/etcd#9878]
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

Hello 
I desperately need your help in Deploying an etcd cluster with the specification below. 

Provision an etcd cluster to serve as a service registry using ansible. Create a simple  service that will register itself on etcd so that it's discoverable by other services.  

*   Automate the creation of the etcd cluster using ansible;

*  The etcd cluster should contain at least 2 nodes;

**Comment by hexfusion** [comment]
Hi @phemmmie we don't support ansible but here is a few reference docs to get you started. Please let us know if you have etcd specific questions once you get the ansible bits going.

* https://github.com/coreos/etcd/blob/master/Documentation/op-guide/clustering.md
* https://github.com/kubernetes/contrib/tree/master/ansible/roles/etcd

**Comment by phemmmie** [comment]
Thanks so much but how can I provision an etcd cluster.to do service
discovery and registration.

Thanks so much in anticipation

**Comment by hexfusion** [comment]
If you would like to run etcd as a service please review the systemd examples. You can also look for examples of systemd that use rkt to deploy etcd. This is pretty common with container linux.

* https://github.com/coreos/etcd/tree/master/contrib/systemd/etcd3-multinode.

* https://coreos.com/etcd/docs/latest/platforms/container-linux-systemd.html#etcd-3x-service

**Comment by hexfusion** [comment]
I misread your question, still early here. But please spend some time in the docs and feel free to come back with specific questions.

https://github.com/coreos/etcd/blob/master/Documentation/dev-internal/discovery_protocol.md

**Comment by phemmmie** [comment]
Thanks so much.

but here is the exact specification sir

Provision an etcd cluster to serve as a service registry using ansible.
Create a simple  service that will register itself on etcd so that it's
discoverable by other services.

*   Automate the creation of the etcd cluster using ansible;

*  The etcd cluster should contain at least 2 nodes;

* etcd should automatically start on after the VM boots up;

*  etcd should try to automatically restart if it's stopped due to an error

*   e.g. it should recover from a temporary networking problem that caused
a panic in  the code to stop the etcd service.


Service Discovery

* Create a "ping" service that will register itself in etcd so that other
services can  discover it:

* Create a simple HTTP server that will reply to GET /ping requests. The
response  should be in JSON with a field called message and the content
should be "pong  from (IP/hostname) in (time it took)"

*  Use etcd to register the "ping" service once it's started so that it can
be discovered  by others.

* Create a script that will query etcd to list all servers that are
announcing the "ping"  service.

Thanks

**Comment by hexfusion** [comment]
> but here is the exact specification sir

:) I think this is for your devops team not etcd support. The reference docs I provided should be enough to get going on this list.

**Comment by nvtkaszpir** [comment]
@phemmmie search over ansible-galaxy https://galaxy.ansible.com/list#/roles?page=1&page_size=10&autocomplete=etcd
