### ISSUE TITLE
Raft library does not retry unsent messages

### ISSUE THREAD

**Issue by manishrjain** [coreos/etcd#9884]
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

Raft (Etcd) version tested with: v3.3.8

We found a bug in Dgraph code, based on a wrong assumption about the workings of Raft library. The issue was that certain proposals, which were accepted by Raft (by calling raft.Propose(..)), were not being processed by a healthy 3-node Dgraph cluster. This was despite a solid communication link, and no leader changes.

Turns out the issue was that when batching up messages to send in a Go channel, we were dropping them if the channel was full.

https://github.com/dgraph-io/dgraph/blob/009b18f2266efc8d0045b1776a7c15c633c14ecb/conn/node.go#L170-L175

This was based on the understanding that Raft would automatically retry the messages which failed to be sent. However, this assumption turned out to be false. Those messages got "lost", and never made it through to the followers (or perhaps the leader, if the proposal was made by the follower).

Switching this select case, by a blocking push to `n.messages` channel fixed the message drop issue.

Can you confirm this behavior? What happens if a network link to a follower is disrupted? In what conditions would the library retry sending the messages?

**Comment by gyuho** [comment]
> This was based on the understanding that Raft would automatically retry the messages which failed to be sent. However, this assumption turned out to be false. Those messages got "lost", and never made it through to the followers

Correct. Regarding how etcd handles this, server transport layer drops internal messages with warnings such as `... sending buffer is full (overloaded network)`, to indicate that message have been dropped.

> Based on a separate thread, the understanding is that MsgProp messages won't be retried, but the rest (MsgApp) would be. This helps a lot, in understanding the behavior.

Yes, Raft keeps track of each follower's progress. The dropped proposals will be retried in next Ready struct.

> Can you confirm this behavior? What happens if a network link to a follower is disrupted? In what conditions would the library retry sending the messages?

I think it depends on your application how to limit retries? etcd transport layer limits the buffer to 4,096.

ref. https://github.com/coreos/etcd/blob/master/raft/design.md#flow-control

**Comment by gyuho** [comment]
@manishrjain Could you help improve our docs? This was confusing to me as well.

**Comment by manishrjain** [comment]
I'll send a doc PR next week. Closing this issue.
