### ISSUE TITLE
ReadIndex doesn't provide ReadStates

### ISSUE THREAD

**Issue by manishrjain** [coreos/etcd#9893]
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

Version: 3.3.8

I'm seeing this issue where if you ask for ReadIndex, but no proposals are going through the system, ReadStates are not populated. I tested it with a 5-node cluster. If I propose anything after, only then do I see populated ReadStates.

```
		ch := make(chan uint64, 1)
		ri := n.setRead(ch) // Store ch so we can get a callback.
		var b [8]byte
		binary.BigEndian.PutUint64(b[:], ri)
		// Store the uint64 as data.
		if err := n.Raft().ReadIndex(cctx, b[:]); err != nil {
			return err
		}
		x.Printf("[%d] Waiting for READ with ri=%d\n", n.Id, ri)
                // MUST do the following to get the read index in Ready().
		if err := n.Raft().Propose(cctx, nil); err != nil {
			x.Errorf("Couldn't propose empty. Error: %v\n", err)
		}
```

**Comment by gyuho** [comment]
Do you know why dgraph has these two calls in sequence? etcd has a separate goroutine sending message read index. And another goroutine to call Propose.

**Comment by manishrjain** [comment]
We don't. I added that Propose because otherwise the `ReadIndex` wasn't causing `ReadStates` to be populated. I pasted that code to show that one MUST call Propose to get ReadIndex to do its thing. The original code is without the Propose.

From the above code:
```
                // MUST do the following to get the read index in Ready().
```

**Comment by manishrjain** [comment]
What's strange is that `Ready()` being called regularly, no communication issues, and proposals going through fine. And yet, the `ReadIndex` isn't being serviced. I also tried on v3.2.23.

**Comment by manishrjain** [comment]
Hey @gyuho , @xiang90 ,

Any ideas what could be happening here? I had to turn off linearized reads for the moment in Dgraph.

**Comment by gyuho** [comment]
@manishrjain 

> raft.Ready() is being called regularly,

Is `Ready.ReadStates` field populated?

**Comment by manishrjain** [comment]
Nope. ReadStates isn't populated.

> the ReadIndex wasn't causing ReadStates to be populated.

**Comment by gyuho** [comment]
I would debug if `MsgReadIndex` was ever transported to followers.

**Comment by manishrjain** [comment]
So, it *seems* like MsgReadIndex is sent by the leader, but then never received:

```
bank-dg0.1 | Got MsgReadIndex at StepLeader: {Type:MsgReadIndex To:0 From:0 Term:0 LogTerm:0 Index:0 Entries:[{Term:0 Index:0 Type:EntryNormal Data:[82 82 45 48 48 48 48 49] XXX_unrecognized:[]}] Commit:0 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 Context:[] XXX_unrecognized:[]}. Context: 52522D3030303031
bank-dg0.1 | Broadcasting heartbeat with context: RR-00001
bank-dg0.1 | raft.send Got context: RR-00001. Message: {Type:MsgHeartbeat To:3 From:0 Term:0 LogTerm:0 Index:0 Entries:[] Commit:4 Snapshot:{Data:[] Metadata:{ConfState:{Nodes:[] XXX_unrecognized:[]} Index:0 Term:0 XXX_unrecognized:[]} XXX_unrecognized:[]} Reject:false RejectHint:0 Context:[82 82 45 48 48 48 48 49] XXX_unrecognized:[]}
```

raft/raft.go
```
			case ReadOnlySafe:
				fmt.Printf("Broadcasting heartbeat with context: %X\n", m.Entries[0].Data)
				r.readOnly.addRequest(r.raftLog.committed, m)
				r.bcastHeartbeatWithCtx(m.Entries[0].Data)

...

// send persists state to stable storage and then sends to its mailbox.
func (r *raft) send(m pb.Message) {
	if bytes.HasPrefix(m.Context, []byte("RR-")) {
		fmt.Printf("raft.send Got context: %s. Message: %+v\n", m.Context, m)
	}
	m.From = r.id
```

So, it looks like it's sent, but then never received. I can confirm that other messages are in fact being received, communication between leaders and followers is going on alright. So, this message gets dropped somehow between `raft.send` and actual sending.

**Comment by manishrjain** [comment]
Actually, even one step earlier, I can see that the message isn't being sent over the wire.

From Dgraph codebase:

```
func (n *Node) Send(m raftpb.Message) {
	x.AssertTruef(n.Id != m.To, "Sending message to itself")
	data, err := m.Marshal()
	x.Check(err)
	if bytes.HasPrefix(m.Context, []byte("RR-")) {
		fmt.Printf("Sending %s over network: %+v\n", m.Context, m)
	}
```

This `fmt.Printf` never gets called.

**Comment by gyuho** [comment]
> MsgReadIndex is sent by the leader, but then never received

> Actually, even one step earlier, I can see that the message isn't being sent over the wire.

Is this from local leader node? `MsgReadIndex` should be forwarded "to" leader, to trigger heartbeat broadcast. Ideally,  `MsgReadIndex` should be coming both from local leader node and remote follower nodes.

**Comment by manishrjain** [comment]
Actually, looks like this is an error at our end. We were overwriting `msg.Context` to store some connection information just before sending messages -- we thought `Context` field was for us to pass some context around. But, I realize it's being used by raft library internally. So, we were accidentally replacing those contexts.

I'll fix up our code, and see if I run into more problems. If not, I'll close this issue. Sorry for the false alarm.

**Comment by manishrjain** [comment]
It works. Thanks for pointing me in the right direction to look, @gyuho .

**Comment by gyuho** [comment]
@manishrjain No problem! For etcd, we pass request ID, in order for follower to block until the follower becomes in-sync with leader to the requested request ID.
