### ISSUE TITLE
Tag a release with "dep" vendoring?

### ISSUE THREAD

**Issue by jsha** [coreos/etcd#9898]
I would love to be able to import a tagged release that incorporates https://github.com/coreos/etcd/pull/9155, moving coreos to `dep` vendoring.

I'm [working on `dep` vendoring for Trillian](https://github.com/google/trillian/pull/1220) and running into the problem described at https://github.com/coreos/etcd/issues/8692. I believe upgrading to a version of etcd that uses `dep` for vendoring would solve the problem, but as far as I can tell, no such version is tagged yet.

Thanks,
Jacob

**Comment by gyuho** [comment]
Yeah, released branches are still using glide (to support symlinks). 3.4 will be released with `dep` in a few months.
