### ISSUE TITLE
"broken pipe" error when write to client after network recovery from physical interrupt

### ISSUE THREAD

**Issue by zhousoft** [coreos/etcd#9900]
etcd version:
```
etcd Version: 3.2.4
Git SHA: c31bec0
Go Version: go1.8.3
Go OS/Arch: linux/amd64
```
background:
I use etcd cluster as config server and use confd to watch keys in etcd for update local config files, thereare hundreds of confd in diffrent client nodes,Everthing worked fine at first.
One day the network between confd nodes and etcd cluster was shut down for several hours(physical cause).After network recovery,there are a lot error message like below when change key's value:

````
2018-07-03 14:54:45.629702 E | etcdserver/api/v2http: error writing event (write tcp 10.10.9.192:2379->10.10.81.71:25606: write: broken pipe)
````
I know "broken pipe" means client has close the connection. What confuse me is that even I restart the client confd and restart etcd, the error message still appears in log file.
After restart confd and etcd:
on 10.10.9.192：
```
# netstat -napt | grep etcd |grep 10.10.81.71
tcp        0      0 10.10.9.192:2379            10.10.81.71:58299            ESTABLISHED 17292/etcd  
```
on 10.10.81.71:
```
# netstat -napt | grep 2379
tcp        0      0 10.10.81.71:58299            10.10.9.192:2379            ESTABLISHED 29562/confd 
```
The confd and etcd has made a new connection with new port,why the etcd still try to write information to the old connection after get "broken pipe" error, even though I restart both side?

**Comment by gyuho** [comment]
Can you try latest etcd v3.2 with v3 client?

**Comment by zhousoft** [comment]
@gyuho  It is a liite difficult to try latest etcd V3.2 for the error occurred on production enviroment.But I had a try on my develop enviroment,The phenomenon cannot be reproduced.
Besdies,I check the log file on production enviroment, the errror message seems to have disappeared. I reload the etcd cluster at July 3rd, the last error message appeard atJuly 3rd, it seems that etcd stop write to the error connnection after a period of time after reload, I will keep watching and reopen this when  something new comes up.
