### ISSUE TITLE
About   *zap.log  of  etcd.wal

### ISSUE THREAD

**Issue by CrocdileChan** [coreos/etcd#9904]
the raft and wal  packages of  etcd  is very  powerful and high-performance.    Recently I  write a distributed KV  database,  I  want  to use  the raft and  wal  package of etcd.

BUT,  there is a little  trouble about it . some of instances of it are as follows：
`func Create(lg *zap.Logger, dirpath string, metadata []byte)`
`func New(lg *zap.Logger, dir string) *Snapshotter`

these code are about  create a wal  and  a  snapshotter. Now  I  want  call  these  functions  but the parameter  lg (*zap.Logger) is   in  vendor package, it doesn't allow us to call.  And these functions only   accpet  *zap.Logger  of vendor  as parameter.

I think  that  you can make this parameter (lg  *zap.Logger)  to **be an interface**. Then  we will be able to use the wal and raft package  outside in other project.

Thanks!

**Comment by gyuho** [comment]
@CrocdileChan Sorry, I don't see any easy way to define an interface for https://godoc.org/go.uber.org/zap#Logger. It's structured logging, so even if we define interface, you would still need to pass `zap.Int`, `zap.String`, etc..

Have you tried vendoring `zap` in your project?

**Comment by gyuho** [comment]
Please reopen if you still have issues.
