### ISSUE TITLE
etcd/integration - consider allowing the configuring Unix Socket location or TCP

### ISSUE THREAD

**Issue by MichaelMitchellM** [coreos/etcd#9907]
I write code on a Windows machine that has my workspace symlinked into a Linux VM.
Since etcd/integration/cluster.go:519 has a colon in the name, it cannot create the socket file inside my directory which originates in Windows.
If possible I would like the option to say where the Unix Socket is created. This way I could tell it to be created somewhere like /tmp.
Allowing TCP may also fix this.

**Comment by gyuho** [comment]
For now, all unix sockets are created in the same directory as `integration`. And we do not plan to run integration tests with TCP sockets, due to port conflicts between multiple tests.
