### ISSUE TITLE
etcd value size limit in 1M

### ISSUE THREAD

**Issue by gyliu513** [coreos/etcd#9925]
Please read https://github.com/coreos/etcd/blob/master/Documentation/reporting_bugs.md.

From the discussion here https://github.com/kubernetes/kubernetes/issues/19781#issuecomment-172553264 , seems etcd has a limitation that the value can be at most be 1M, does this value can be configured?

**Comment by gyuho** [comment]
It's 1.5 MB by default.

Have you tried `--max-request-bytes` flag?

**Comment by gyliu513** [comment]
Thanks @gyuho , it works and I got more detailed info from https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/limit.md#request-size-limit
