### ISSUE TITLE
[Question] get value from slave at once after put operation

### ISSUE THREAD

**Issue by shenlanse** [coreos/etcd#9930]
**Version**

```
etcdctl version
etcdctl version: 3.3.0+git
API version: 3.3

```

**Environment**

I have deployed 5 node etcd cluster. 

```
etcdctl endpoint status --cluster -w=table
+--------------------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+
|         ENDPOINT         |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+
| http://10.173.32.14:2379 | 395461d1ca981d2c | 3.3.0+git |   51 MB |     false |         2 |     445093 |             445087 |        |
| http://10.173.32.14:4379 | 642c3bb595d924a0 | 3.3.0+git |   51 MB |     false |         2 |     445094 |             445094 |        |
| http://10.173.32.14:3379 | 6dd46d7ef38ffbf0 | 3.3.0+git |   51 MB |     false |         2 |     445093 |             445093 |        |
| http://10.173.32.10:2379 | 765e840503358ad8 | 3.3.0+git |   51 MB |     false |         2 |     445094 |             445094 |        |
| http://10.173.32.14:5379 | d45d824eedd2a9ef | 3.3.0+git |   51 MB |      true |         2 |     445094 |             445094 |        |
+--------------------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+

```

**What happened**:

All my operation is to slave node, for example `http://10.173.32.14:2379`.

I get value **at once after I put**. I want to know if there is any possiblity that i can't get expected value.

That is to say, client access slave member. Firstly, client `put key value`. When the slave member send reponse to client, Does the correponding PUT  message has already been applied to this slave member?

test script:
```
#!/bin/bash
for i in {100000..999999}
do
    _=`etcdctl --endpoints=http://10.173.32.14:2379 put "$i" "$i"`
    real=`etcdctl --endpoints=http://10.173.32.14:2379 get "$i" --consistency="s" --print-value-only`
    expect=`echo "$i"`
    if [ "$real" != "$expect" ]
    then
        echo "wrong"
    fi
done
```

I run this script many times, "wrong" result never happen.

**Comment by shenlanse** [comment]
@gyuho

**Comment by gyuho** [comment]
> Does the correponding PUT message has already been applied to this slave member?

Put succeeds whenever the quorum of cluster commits and applies that entry, so if there is one partitioned follower, it may not have the latest data.

**Comment by shenlanse** [comment]
Seems that you don't get my point. Suppose the cluster is healthy, all members work fine. I put key value to **one slave**, when command return, I get it from **this same slave** at once. I want to know if there is any possiblity that i can't get expected value.

**Comment by gyuho** [comment]
> I put key value to one slave

You can't. When put returns, it's already replicated in majority nodes.

> any possiblity that i can't get expected value

The follower returning OK on put command means it's already applied. So, no.

**Comment by shenlanse** [comment]
@gyuho  Thanks a lot.

**Comment by shenlanse** [comment]
@gyuho  Sorry to bother you again.

> I put key value to one slave

when put return, I know this request has already been applied to majority members. I want to make sure again this request has already been applied to **this slave** also. 

> any possiblity that i can't get expected value

Serializable read, Not Linearizable read.

**Comment by gyuho** [comment]
> Serializable read

Then there's no guarantee. The follower may return old data, since all writes are forwarded to leader.

**Comment by shenlanse** [comment]
```
+--------------------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+
|         ENDPOINT         |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+
| http://10.173.32.14:2379 | 395461d1ca981d2c | 3.3.0+git |  741 MB |     false |         2 |    6405894 |            6405894 |        |
| http://10.173.32.14:4379 | 642c3bb595d924a0 | 3.3.0+git |  741 MB |     false |         2 |    6405894 |            6405894 |        |
| http://10.173.32.14:3379 | 6dd46d7ef38ffbf0 | 3.3.0+git |  741 MB |     false |         2 |    6405894 |            6405894 |        |
| http://10.173.32.10:2379 | 765e840503358ad8 | 3.3.0+git |  741 MB |     false |         2 |    6405894 |            6405894 |        |
| http://10.173.32.14:5379 | d45d824eedd2a9ef | 3.3.0+git |  741 MB |      true |         2 |    6405894 |            6405894 |        |
+--------------------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+
```

my test script:    
write to one follower and get from this same follwer at once.
```
#!/bin/bash
for i in {100000..999999}
do
    _=`etcdctl --endpoints=http://10.173.32.14:2379 put "$i" "$i"`
    real=`etcdctl --endpoints=http://10.173.32.14:2379 get "$i" --consistency="s" --print-value-only`
    expect=`echo "$i"`
    if [ "$real" != "$expect" ]
    then
        echo "wrong"
    fi
done
```

I run this script to different followers concurrently(key and value are also different from other followers, avoid influence each other). Also put chaos when test, for example unrelated concurrent operation, large data.

Unexpectedly, I always get new value, `wrong` output never happens.

**Comment by shenlanse** [comment]
When I put value to one follower but then get it **from another follower** at once, `wrong` output happened many times:

```
#!/bin/bash
for i in {100000..999999}
do
    _=`etcdctl --endpoints=http://10.173.32.10:2379 put c"$i"b c"$i"b`
    real=`etcdctl --endpoints=http://10.173.32.14:2379 get c"$i"b --consistency="s" --print-value-only`
    expect=`echo c"$i"b`
    if [ "$real" != "$expect" ]
    then
        echo "wrong"
    fi
done

```

**Comment by shenlanse** [comment]
@gyuho
