### ISSUE TITLE
etcdctl put command issue

### ISSUE THREAD

**Issue by FatMole** [coreos/etcd#9932]
Hi,

When using etcd 3.3.8, and run below command:
[postgres@rh2 ~]$ ETCDCTL_API=3 etcdctl put test1 "Hello World!"
bash report error:
-bash: !": event not found

Question: Why we do not support ! in the value?

Thanks!

**Comment by gyuho** [comment]
Try `./bin/etcdctl put foo "a b\!"`?

**Comment by FatMole** [comment]
yes, after add \, it can be added, but the result also has \ like:
[postgres@rh1 ~]$ ETCDCTL_API=3 etcdctl get test1
test1
Hello World\!

It meas if I use my own program I'll get a string include \ , 
It is ok to add special handling code with this \ , but do we have a way to put string without \ ? 
I mean get "Hello World!" from etcd.

Thanks.

**Comment by gyuho** [comment]
@FatMole 

> It meas if I use my own program I'll get a string include \ ,

Did you mean the new line character?

> do we have a way to put string without \ ?

I would take a look into Go clientv3 library, and do not worry about handling corner cases around delimiter.

**Comment by FatMole** [comment]
yes, I mean I will get Hello World\!, with slash.
And I wonder if there's a way I can get the reture string without slash.

Thanks.
