### ISSUE TITLE
etcd cluster vote constantly!

### ISSUE THREAD

**Issue by NaNi-Z** [coreos/etcd#9933]
etcd version 2.3.7
It is a three nodes cluster. Because of power cut, one of the etcd is down which snopshot file is broken. The rest two etcd are running well but vote constantly.
The network and disk are well, I checked the metrics. I tried to restart, but it doesn't work.
At the beginning of vote, both of the etcd start votes constantly, and did not reponse the other. After a while, one becomes a follower, but the other still starts votes constantly.
And there are also some "publish error: etcdserver: request timed out" errors.
Sorry I can't offer logs or something detail, becacuse it is a internal environment. I meet this situation at least twice. 
Is this a problem? Please give me some idea, thanks.

**Comment by gyuho** [comment]
What's the server error message? And metrics output?

**Comment by NaNi-Z** [comment]
@gyuho 
The error is just "publish error: etcdserver: request timed out" and can not connect to the failed one. The vote has no error.
The log is like(sorry I can't copy)
xxx is start vote   term 22323
xxx is set to candidate
sent vote message to yyy
sent vote message to zzz
xxx is start vote   term 22324
xxx is set to candidate
sent vote message to yyy
sent vote message to zzz
...(repeat)

Metrics I checked  fsync and raft_failed. fsync are all less 0.001s, the raft_failed is all send to the failed etcd.

**Comment by xiang90** [comment]
We are not actively maintaining etcd v2 any more. Please try etcd 3.x releases.

**Comment by NaNi-Z** [comment]
(ó﹏ò｡)
