### ISSUE TITLE
etcd doesn't bind --listen-peer-urls for outbound peer traffic

### ISSUE THREAD

**Issue by chaosaffe** [coreos/etcd#9953]
Similar to a previous issue ([Feature Request: Ability to pick source IP address](https://github.com/coreos/etcd/issues/9193)), we would like the ability to specify the source address of the peer traffic.
In our environment each node has multiple IP addresses, including a specific IP for etcd. While inbound traffic is handled correctly by etcd, outbound peer traffic is handled by binding any available address, resulting in identity issues, i.e. with client certificates.
While this could be handled by using other tools to NAT the outbound traffic of etcd, we consider this to be unexpected behaviour. Additionally, as the outbound ports are dynamic, NATing this traffic is very difficult to do at a granular level to ensure that _only_ etcd traffic can use it's assigned IP.

**etcd Version:** 
3.3.2

**Expected:**
When `--listen-peer-urls` is set, etcd will bind the given IP address for outbound traffic to peers. 

**Actual:**
etcd binds any available address for outbound traffic to peers.

**Steps to reproduce:**
1. Configure etcd with `--listen-peer-urls` set on a node that has multiple outbound IP addresses.
2. Join the etcd instance to a cluster.
3. Observe source address (i.e. via tcpdump)
 
**Proposed solutions:**
1. Attempt to bind the address from `listen-peer-urls`, fall back to any available address if bindable
2. Add a configuration flag for the outbound address to bind

**Comment by chaosaffe** [comment]
Just as a note, we are happy to invest effort into adding this if it will be upstreamed

**Comment by jpbetz** [comment]
@chaosaffe I'm not sure I follow what you believe is wrong with selecting source ports from the ephemeral port range and what problems this has caused with client certificates. Could you explain the motivation in more detail?

**Comment by chaosaffe** [comment]
@jpbetz the issue isn't the source _port range_, rather the source _IP_. 

We have multiple IP's assigned per node, and while an etcd instance will only listen on the `listen-peer-urls` IP, the etcd instance will connect to peers using _any_ IP available on the node.

As the source IP is not deterministic, we must add any potential node IP to the peer certificate SAN as we cannot deterministically assign _which_ IP an etcd instance will use to contact it's peers.

__Example:__
__Node Addresses:__
- `10.0.0.1`
- `10.0.1.1`
- `10.255.0.1`
etcd-1 started with `--listen-peer-urls="https://10.255.0.1:2380"`

__Current Result:__
peer -> etcd-1 will use a destination IP of `10.255.0.1`
etcd-1 -> peer will use a source IP of `10.0.0.1`, `10.0.1.1` _or_ `10.255.0.1`, non-deterministically 

__Expected Result:__
peer -> etcd-1 will use a destination IP of `10.255.0.1`
etcd-1 -> peer will use a source IP of `10.255.0.1`

**Comment by joelegasse** [comment]
@chaosaffe What do your network segments look like, and what are the subnet masks for each of those addresses? As I understand it, you're trying to ensure that etcd will use the `listen-peer-url` address as the source for the peer connections? That should happen automatically assuming that the `10.255.0.0` is on a smaller subnet (`/24` for example) than `10.0.0.1`, and that all peers are on the same `10.255.0.0` subnet and network segment.

If instead all of the addresses you listed have a `/8` subnet mask (`255.0.0.0`), then yes, any of those addresses will be equally likely to be chosen as a source address.

**Comment by chaosaffe** [comment]
@joelegasse our subnets are the following:

|interface| etcd-1 Node | etcd-2 Node | etcd-3 Node |
|--- | --- | --- | --- |
|`lo`| `10.6.255.1/32` | `10.6.255.2/32` | `10.6.255.3/32` |
|`eth0`|`10.6.0.10/30` | `10.6.0.6/30` | `10.6.0.2/30`|
|`eth1`|`10.6.1.10/30` | `10.6.1.6/30` | `10.6.1.2/30`|

Peers do not share a subnet. We have a 3 layer CLOS topology. Peers do not share a network segment, they are on separate ToR's.

**Comment by chaosaffe** [comment]
Putting all etcd instances into the same subnet (`10.6.255.0/28`) resolved the issue, but I can't find any documentation on this. Can we hold the issue open until we can make a docs PR please?

**Comment by joelegasse** [comment]
@chaosaffe Another option would be to adjust the routing table on each of the nodes to select the desired source IP at the OS/kernel level.

I don't really consider this to be an etcd issue. You would see this same behavior out of a lot of systems, since most don't specify a source IP as the OS generally handles the network configuration of a host. I don't think the etcd documentation is the correct place to include instructions about source address selection.

**Comment by chaosaffe** [comment]
Fair enough. Thank you for your help!
