### ISSUE TITLE
etcdctl set remote cluster url

### ISSUE THREAD

**Issue by vankofalcon** [coreos/etcd#9972]
Hi guys,
I need to connect to remote etcd cluster and I want to use the etcdctl util as a client, but I can't find how to set the remote host name on the etcdctl. Can you please help me with that?

**Comment by hexfusion** [comment]
Hi @vankofalcon are you looking for the --endpoints flag?

ETCDCTL_API=3 etcdctl --endpoints http://hostname:port put foo bar

**Comment by vankofalcon** [comment]
:+1:

**Comment by bhagatdharmendra** [comment]
Hi @vankofalcon You need to start the ETCD listen on server IP not localhost 
Etcd server side:- etcd --listen-peer-urls http://172.16.11.111:2380  #keys & Certificate 
client side:- etcdctl --endpoints http://172.16.11.111:2380 put foo "bar" #keys & Certificate
