### ISSUE TITLE
Q: Why not use systemd watchdog for health check?

### ISSUE THREAD

**Issue by Nefelim4ag** [coreos/etcd#9981]
Subj,
You have a health http endpoint for check etcd, that allow to make some external checks for node status.

But as you in any way running etcd under coreos and systemd, why not use systemd watchdog?
Even you import sd_notify for use Type=notify in service.

Thanks!

**Comment by hexfusion** [comment]
@Nefelim4ag, in general, we don't want to have a systemd dependency.  Although many distros used systemd some don't, the largest whole with that would probably be Windows.

**Comment by hexfusion** [comment]
ref: http://without-systemd.org/wiki/index.php/Linux_distributions_without_systemd

**Comment by Nefelim4ag** [comment]
Sorry,
but i don't have a list of distros without etcd to compare.
But thanks anyway!
